### ISSUE TITLE
ordenes sin creador

### ISSUE THREAD

**Issue by rihanuch** [IIC2233/Syllabus#59]
me di cuenta que hay ocasiones (varias) en las que hay ordenes sin creadores, por ejemplo me paso que la orden 12 no tiene creador (como no se puede adjuntar voy a pegar los archivos)(también me pasa con las ordenes 13,14,15,17,21,28,29,34,41,48,49,6_y_algo,68,74,78,83,92)

ORDERS.CSV

ticker: string;order_id: int;date_match: string;type: string;date_created: string;price: float;amount: float
WUBBAN;27;2017-04-09;bid;1999-04-15;297.8;163.6
RUPRIN;63;2016-07-03;bid;2007-10-23;233.7;237.8
RINBAN;95;2015-12-07;ask;1999-01-07;76.7;39.6
RINNEC;33;2017-08-12;ask;2017-02-11;92.0;34.5
NECRUP;56;2014-03-09;bid;2009-02-03;235.3;280.7
SIMNEC;25;;bid;2010-07-24;38.4;194.4
RINKAM;99;;bid;2007-10-16;289.5;105.9
NECBAN;5;2006-10-27;bid;2003-08-10;289.2;184.5
KAMWUB;4;2016-01-01;ask;2011-05-23;243.3;179.3
SIMKAM;11;2014-10-04;bid;1998-10-02;127.1;230.6
BANSIM;17;;bid;2007-03-11;285.7;244.6
RUPRIN;18;;bid;2008-08-26;26.2;244.4
WUBBAN;45;2012-05-14;bid;2007-02-20;277.1;92.0
SIMKAM;12;2014-10-04;ask;2012-11-17;127.1;230.6
WUBRUP;60;2015-10-29;bid;2009-07-16;3.1;57.4
RINSIM;50;;bid;2015-04-29;293.3;226.5
SIMKAM;39;;bid;1997-02-10;188.1;12.1
RUPWUB;77;2004-01-16;bid;2003-07-03;164.4;214.1
SIMRIN;15;2016-12-22;ask;2005-10-03;119.6;238.3
RUPKAM;97;;bid;1997-06-05;182.3;169.3
NECWUB;75;2017-07-24;ask;2016-07-03;229.3;168.0
RINBAN;96;2015-12-07;bid;2008-09-27;76.7;39.6
WUBNEC;74;2014-06-01;bid;2008-03-19;298.3;121.9
NECKAM;54;2007-06-14;bid;2004-02-08;292.3;131.2
RUPSIM;23;;ask;1999-12-13;86.4;11.0
WUBSIM;30;;ask;1999-01-26;137.9;4.4
NECWUB;14;;ask;2016-01-17;43.9;2.1
RUPWUB;80;;ask;2006-11-22;100.8;38.1
RUPNEC;72;;ask;2000-07-05;236.7;56.8
SIMWUB;69;2006-04-03;ask;2001-04-26;60.5;254.2
WUBNEC;42;;bid;2009-06-23;134.7;75.6
NECSIM;49;;bid;2015-07-31;110.7;28.7
WUBNEC;89;2013-01-08;ask;1997-03-30;45.5;214.3
WUBRIN;82;2013-08-09;ask;2010-01-13;80.8;122.9
BANKAM;1;2017-06-19;bid;2012-11-02;73.0;63.6
BANRIN;40;;ask;2014-10-07;171.4;12.5
NECSIM;10;2005-09-23;ask;2002-07-14;286.7;174.6
WUBNEC;88;2013-01-08;bid;2008-09-16;45.5;214.3
BANSIM;43;;bid;2006-07-15;140.1;155.8
NECWUB;76;2017-07-24;bid;2017-02-18;229.3;168.0
RUPRIN;62;2016-07-03;ask;2016-03-04;233.7;237.8
SIMRIN;16;2016-12-22;bid;1997-10-17;119.6;238.3
NECRUP;57;2014-03-09;ask;2005-04-15;235.3;280.7
WUBSIM;70;2010-05-20;bid;2004-07-10;51.3;232.2
BANKAM;2;2017-06-19;ask;2002-07-18;73.0;63.6
WUBNEC;73;2014-06-01;ask;1997-05-13;298.3;121.9
KAMWUB;3;2016-01-01;bid;1999-10-12;243.3;179.3
RUPWUB;78;2004-01-16;ask;1999-09-19;164.4;214.1
RINNEC;32;2017-08-12;bid;2013-02-13;92.0;34.5
RUPRIN;7;;ask;2011-05-12;39.8;291.9
KAMRIN;52;2006-05-20;bid;2005-04-26;123.8;142.9
WUBRIN;24;;bid;1997-11-18;264.7;129.3
RINBAN;31;;ask;1997-07-20;270.5;128.7
SIMNEC;38;2013-11-09;ask;2010-06-26;51.5;253.8
KAMRIN;51;2006-05-20;ask;1997-12-07;123.8;142.9
BANNEC;98;;ask;2012-02-27;252.6;129.1
KAMRUP;35;2007-10-19;bid;2006-10-06;53.7;130.2
SIMRUP;22;2017-06-24;bid;2016-07-14;209.7;123.1
NECKAM;53;2007-06-14;ask;1998-04-19;292.3;131.2
SIMWUB;68;2006-04-03;bid;1998-03-15;60.5;254.2
NECKAM;67;;bid;2015-03-23;172.2;41.3
WUBBAN;44;2012-05-14;ask;2010-12-16;277.1;92.0
RUPNEC;34;;ask;2008-10-03;189.2;232.3
NECWUB;87;2009-07-02;ask;2003-06-21;146.3;299.4
NECBAN;6;2006-10-27;ask;2003-04-30;289.2;184.5
WUBRUP;61;2015-10-29;ask;2010-10-23;3.1;57.4
RINBAN;20;2015-04-03;ask;2009-08-09;6.2;145.1
WUBRIN;83;2013-08-09;bid;2009-07-14;80.8;122.9
NECSIM;29;2011-05-03;bid;2005-01-10;78.8;59.3
WUBRUP;92;2002-03-19;ask;2001-05-25;7.1;295.3
KAMRUP;36;2007-10-19;ask;2004-03-07;53.7;130.2
RUPWUB;79;;ask;2006-04-19;178.9;169.6
WUBRIN;46;;ask;2002-01-12;3.8;41.9
BANWUB;59;;bid;2009-12-06;295.7;190.3
RINKAM;48;2012-07-09;bid;2009-08-22;211.3;234.9
BANKAM;65;;bid;2000-12-22;60.1;112.9
NECSIM;28;2011-05-03;ask;2001-06-14;78.8;59.3
RUPBAN;13;;bid;2016-03-02;252.1;177.6
RINBAN;19;2015-04-03;bid;1997-12-15;6.2;145.1
BANWUB;8;;ask;2012-06-01;67.6;68.8
WUBRUP;93;2002-03-19;bid;1997-02-23;7.1;295.3
BANRUP;58;;bid;1997-01-03;82.4;10.1
SIMRUP;21;2017-06-24;ask;2017-03-25;209.7;123.1
NECWUB;86;2009-07-02;bid;2006-06-04;146.3;299.4
NECSIM;9;2005-09-23;bid;2000-09-11;286.7;174.6
BANRIN;55;;bid;2012-04-16;49.6;189.1
WUBRUP;84;2016-04-29;bid;1997-03-27;73.0;106.9
NECRUP;91;;bid;2011-08-03;243.1;18.5
WUBSIM;71;2010-05-20;ask;1998-11-17;51.3;232.2
RINKAM;47;2012-07-09;ask;2004-07-17;211.3;234.9
SIMNEC;37;2013-11-09;bid;2000-07-17;51.5;253.8
RINKAM;66;;bid;2004-08-06;69.9;206.1
RUPWUB;64;;bid;2007-11-14;205.0;223.2
BANSIM;81;;bid;2014-02-13;55.6;41.3
WUBRUP;85;2016-04-29;ask;2015-10-03;73.0;106.9
BANWUB;41;;ask;2000-09-05;89.9;130.6
NECBAN;94;;ask;1997-05-11;47.9;202.2
RINNEC;0;;ask;2003-01-15;142.5;133.6
WUBKAM;90;;bid;2010-08-31;166.6;44.1
WUBBAN;26;2017-04-09;ask;2013-10-09;297.8;163.6

USERS.CSV

lastname: string;orders: list;name: string;birthday: string;username: string
Guerra;65:63:39;Sebastián;1995-02-08;sguerra2
Garrido;;Tanya;1991-03-26;tcgarrido
Balbontín;57:55:44:0;Nicolás;1991-08-15;nfbalbontin
Acevedo;69:43:86:26:2;Ignacio;1991-06-08;Iqacevedo
Hormazabal;27:95:4:52:23;Jessica;1995-07-09;Arcoirisky
Torres;70:35:47:99;Santiago;1996-04-20;chapito96
Tagle;;Joaquín;1995-12-28;jtagle2
Fernández;96;Andrés;1994-11-01;andresfdezc
Carrera;;Isaac;1994-06-11;ifcarrera
Álvarez;;Raúl;1993-11-19;KnowYourselves
Cruz;72:3:53:7:89;Sebastián;1993-07-23;sebacruzd
Barrios;67:42:50:61;Florencia;1997-05-23;flobarrios
Chau;91:30:73:51:62;Stephanie;1994-03-25;stephichau
Romero;36:87;Erick;1996-07-20;egromero
Juárez;56:88:32;Vicente;1995-05-25;vijuarez
Salvadores;90:80;Tomas;1991-12-08;TomasSalvadores
Tamburini;54;Enzo;1990-12-20;entamburini
López;94:66:22:98;Camilo;1993-03-02;cilopez
Larraín;;Jose Manuel;1990-02-22;jnlarrain
Cárcamo;77:8:5:20;Benjamín;1995-02-09;fringlesinthestreet
Pieressa;1:10:33:11:79;Fernando;1990-06-29;FernandoPieressa
Quinteros;46;Felipe;1992-05-31;fnquinteros
Prudencio;84:82:24:60:58;Gustavo;1991-08-09;GustavPrudencio
Dominguez;59:9:76:71:25;Felipe;1997-07-03;fdominguezclaro
Kaminetzky;38:64;Alejandro;1994-11-18;akaminetzkyp
Riesco;81:85:93;Jorge;1995-04-12;jorgeriesco
Valdivieso;16:19:18:75;Hernán;1992-10-09;hernan4444
Navarrete;;Hugo;1997-09-24;hanavarrete
Vera;;Octavio;1995-06-06;ofvera
Salvo;31:40:37:45:97;Paula;1996-08-19;pcsalvo

perdón por el texto largo, pero no hay otra forma, GitHub no me dejo adjuntar los archivos 😢 
gracias! 😄

**Comment by nmaturana97** [comment]
emm creo q ya lo respondieron hanuch

**Comment by ifcarrera** [comment]
#55
