### ISSUE TITLE
SublimeLinter-pycodestyle : sublime 3

### ISSUE THREAD

**Issue by Jeanjncls** [IIC2233/syllabus#59]
Hola:
Al poner  SublimeLinter-pycodestyle, no me aparece  nada y menos al colocar Auto PEP8. 

![Anotación 2020-08-19 181135](https://user-images.githubusercontent.com/69616060/90695068-b8d8e900-e247-11ea-8f1b-376e043292c0.jpg)

**Comment by lily416** [comment]
Hola @Jeanjncls,

¿Pusiste `Package Control: Install Package` antes de poner `SublimeLinter-pycodestyle`?
Si no haces eso, no podrás acceder al listado de paquetes disponibles para instalar.

Cuéntame cómo te va 🤓📦

**Comment by Jeanjncls** [comment]
si si, si lo puse

**Comment by lily416** [comment]
¿Te fijaste en si usaste `Ctrl + Shift + P` en vez de `Ctrl + P` para abrir la paleta de comandos?
Aunque los comandos son parecidos, cada uno hace algo distinto:

* `Ctrl + P` permite moverte entre los archivos que tienes abierto: ![image](https://user-images.githubusercontent.com/26393515/90706057-53debc80-e262-11ea-8413-e39e87e5e900.png)

* Mientras que `Ctrl + Shift + P` abre la paleta de comandos: ![image](https://user-images.githubusercontent.com/26393515/90706112-6fe25e00-e262-11ea-94c6-b9a9aa186b4a.png)

Además, cada vez que abras la paleta de comandos debes volver a poner `Package Control: Install Package` y después `SublimeLinter-pycodestyle`.

**Comment by Jeanjncls** [comment]
puse, control+ shift + p, pero nada,  yo creo que usare visual studio si, ya lo tengo instalado y configurado.

**Comment by lily416** [comment]
Ya, ojala que VSC no tengas problemas 🙏. 

Si en algún minuto vuelves a intentar configurar Sublime y logras solucionar el problema, coméntalo aquí.
Así puede que ayudes a alguien con el mismo problema 😉.
