### ISSUE TITLE
Aumentar la tasa de minerales/deuterio?

### ISSUE THREAD

**Issue by naquiroz** [IIC2233/Syllabus#59]
En la sección 6.2 dice que se le debe permitir al usuario:
> Aumentar la tasa de minerales por segundo de los planetas no conquistados.
> Aumentar la tasa de deuterio por segundo de los planetas no conquistados.

Con lo anterior se refiere a permitirle cambiar directamente los valores de las tasas? O se refiere a permitirle subir de nivel la el nivel de economía?

Saludos.

**Comment by IchottMano** [comment]
Hola!
Esa parte se refiere a cambiar directamente los valores de las tasas de los planetas no conquistados.
Saludos!

**Comment by jminostroza** [comment]
Entonces en los planetas que no han sido conquistados, NO se puede aumentar el nivel de economía?, sólo aumentar las tasas de minerales y deuterio por segundo directamente??

**Comment by IchottMano** [comment]
Hola!
@jminostroza Efectivamente es como tu lo dices.
@mramirez7 Como lo tomes queda a tu criterio, pero recomiendo que no compliques el problema mas de lo necesario.
Saludos!

**Comment by dedarritchon** [comment]
En la definicion de tasa de minerales dice que es un numero aleatorio entre 1 y 10. Al aumentarla directamente no puede pasar de 10? gracias

**Comment by IchottMano** [comment]
@dedarritchon Efectivamente.
Saludos!

**Comment by mplazadelosreyes** [comment]
Por lo que entiendo entonces el aumento es "arbitrario" porque queda bajo el criterio del usuario, siempre y cuando se respeten los valores máximos de los minerales o deuterio establecidos.
Mi pregunta es si hacer estos aumentos tiene algún costo para el usuario? para los recursos de la galaxia? o el aumento es "gratis"?

**Comment by IchottMano** [comment]
@mplazadelosreyes Hola!
Efectivamente es gratis.
Saludos!
