### ISSUE TITLE
Duda sobre el archivo mensajes.csv

### ISSUE THREAD

**Issue by andrescf** [IIC2233/syllabus#59]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]
Hola! Quería saber si se puede asumir que en el archivo de mensajes.csv los mensajes estarán ordenados por fecha y hora de emisión o si debemos ordenarlos.
[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by pabloist** [comment]
Hola! :)

Debido a que dicho archivo .csv corresponde a un documento que tu código debe poblar, no puedes asumir que se encontrará de forma automáticamente ordenado, aún cuando si **debiera** encontrarse ordenado, pero todo dependerá de como realices la modificación de dicho archivo.

Saludos!

**Comment by andrescf** [comment]
Entiendo! Muchas gracias.

**Comment by pabloist** [comment]
No hay problema ;)
