### ISSUE TITLE
Promedio de llamados totales

### ISSUE THREAD

**Issue by AlexanderBarrera** [IIC2233/Syllabus#590]
Hola, 
En el  punto 6.12 de la tarea, se nombra a promedios de llamadas totales por limpiadores(o tecnicos), ¿este promedio corresponde al promedio de llamadas por dia, o corresponde a los promedios entre los totales de llamadas por simulacion?  
Muchas gracias ^.^

**Comment by Hernan4444** [comment]
@AlexanderBarrera por día.

Saludos ✌️
