### ISSUE TITLE
Codificacion de mensajes

### ISSUE THREAD

**Issue by fplois** [IIC2233/syllabus#590]
Una consulta, es que como me piden que todos los mensajes que sean enviados entre el servidor y el cliente deben ser codificados con lo que se pide en la seccion 3.1.3 , ¿Que pasa en el caso que quiera enviar un diccionario?, ya que este no se puede codificar con utf-8.
¿Puedo pasar el diccionario a str con json y luego codificar ese string con lo pedido?
Gracias

**Comment by jeschuwirth** [comment]
Hola @fplois,

No hay problema con que utilices json para pasar el diccionario a string.
