### ISSUE TITLE
importar funciones entre modulos

### ISSUE THREAD

**Issue by BValdes16** [IIC2233/syllabus#590]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, quería saber si es considerado bajo acoplamiento el importar un par de funciones y ciertas clases que me ayudan en el funcionamiento del backend (por ejemplo la clase personaje la tengo en otro módulo que la clase juego, y la importo). si no lo hago así me queda bastante sucio, ya que tendría que poner muchísimas señales y hasta me pasaría de las 500 líneas. 

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by mmunoz12** [comment]
Holaa @BValdes16! El uso de señales se debe realizar entre el frontend y el backend a modo de que el código sea de bajo acoplamiento, es decir, se deben implementar las funciones con una clara separación entre entidades dedicadas a lo visual (front-end) y las que están dedicadas a la lógica del programa (back-end). Por lo tanto, puedes importar funciones que se encuentren en archivos propios del backend, sin embargo no es posible hacerlo con funciones del frontend (ya que es aquí donde se utilizan las señales). Además debes tener en cuenta que tu backend se debe encontrar correctamente modularizado en archivos y funciones a modo de continuar respetando el bajo acoplamiento de este. Quedo atenta si te quedan dudas!
