### ISSUE TITLE
Calidad promedio de productos por escenario

### ISSUE THREAD

**Issue by Polea012** [IIC2233/Syllabus#590]
¿Esta medida de desempeño no hay que mostrarla en la consola (teniendo en cuenta que es por escenario)
o mostramos la calidad promedio de la simulación?
¿Ademas, queda a criterio nuestro la medición de la calidad promedio si consideramos que depende del tiempo, (por ejemplo, registrar la calidad cuando una persona compra el producto)?
Gracias de antemano!

**Comment by iqacevedo** [comment]
Hola,

Cuando estás simulando normal si debes mostrarla, es la de la simulación misma como dices.
Si en otras issues se indicó que queda a su criterio en que momento considerarla (tenía que ser lógico cuando tomarlo). Debes escribir en tu README el criterio.

Saludos !

**Comment by Polea012** [comment]
Muchas Gracias !
