### ISSUE TITLE
Dudas Diagrama de Clase

### ISSUE THREAD

**Issue by valerianazal** [IIC2233/syllabus#590]
Hola! 
Tengo algunas dudas sobre la estructura del diagrama:
1. ¿Tengo que poner los parámetros que reciben los métodos? Y si es así, ¿Qué puedo hacer para abreviarlos si son muchos?
2. Si un método retorna objetos de distintas clases al mismo tiempo, ¿Cómo lo especificamos?
3. Si un método retorna objetos de distintas clases dependiendo de las condiciones que se cumplen o no, ¿Cómo lo especificamos?
4. Si un atributo de una clase C es una instancia de una clase A que hereda de otra clase B, ¿Pongo en el diagrama el nombre de la instancia como ClaseA o ClaseB?

Muchas gracias :)

**Comment by retamalcito** [comment]
¡Hola @valerianazal!

A continuación respondo tus preguntas:

1. Debes especificar el **tipo** de los parámetros que reciben tus métodos, por ejemplo: `comer(str, bool): None`
2. Es muy raro que un método retorne objetos de distintas clases, a menos que ambas hereden de una misma clase madre. Por ejemplo, digamos que tienes una `ClaseA` que es madre de `ClaseB` y `ClaseC`. Si tienes un método que retorna o `ClaseB` o `ClaseC`, entonces debes colocar que retorna un objeto de clase `ClaseA`, ya que tanto `ClaseB` como `ClaseC` son, a su vez, `ClaseA` (esto se explica también en la issue #349). Sin embargo, si las dos clases que puede retornar no tienen relación entre ellas, probablemente tengas un problema de modelación :thinking:, pero a estas alturas del plazo, como sería difícil cambiarlo, podrías simplemente indicarlo con un "o" (por ejemplo: `comer(): str o int`).
3. **No** es necesario indicar las condiciones que se deben cumplir para que un método retorne una cosa u otra.
4. Siempre debes intentar ser lo más específique posible, por lo que, según tu ejemplo, deberías poner que el atributo es de `ClaseA`. :smile:

Espero haber aclarado tus dudas, ¡éxito! 🏅

**Comment by valerianazal** [comment]
Gracias!! 
Y sobre la pregunta 3 a lo que me refería es como hay dos retornos posibles escribimos: `metodo(): int o str`? (por ejemplo)

**Comment by valerianazal** [comment]
Gracias !!
Y es mala práctica que un método retorne objetos de distintas clases en una tupla? Por ejemplo `método(): Deportista, Delegacion`
