### ISSUE TITLE
Problema código Ayudantia Networking

### ISSUE THREAD

**Issue by Arcoirisky** [IIC2233/Syllabus#590]
Hola, una pregunta ¿Debería cambiar algo del código si quiero correr la actividad en mi computador? Servidor y Cliente no quieren conectar, pensando que no he tocado en nada el código :C

**Comment by malopez16** [comment]
A mi me corre bien con el código tal cual, no habría que hacerle cambios.
No creo que puedan ayudarte si no escribes el error que te tira (?)

**Comment by Arcoirisky** [comment]
Esa es la cosa, sólo no conecta :c Corre el programa y dice "No fue posible realizar la conexión"

PD: Tarde se me ocurrió sacarle el try, dice esto:

"""
Traceback (most recent call last):
  File "C:/Users/Jeka/Desktop/Avanzada/Arcoirisky-iic2233-2017-1/Actividades/AC14/Client.py", line 54, in <module>
    client = Cliente(nombre)
  File "C:/Users/Jeka/Desktop/Avanzada/Arcoirisky-iic2233-2017-1/Actividades/AC14/Client.py", line 19, in __init__
    self.s_cliente.connect((self.host, self.port))  # El cliente
TimeoutError: [WinError 10060] Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder
"""

**Comment by sebacruzd** [comment]
Hola,

Estás haciendo un servidor antes de iniciar un cliente? Debería ser en ese orden para que se pueda conectar.

**Comment by Arcoirisky** [comment]
Sip, eso estoy haciendo. El servidor funciona pero el cliente aún así no desea conectarse

**Comment by Arcoirisky** [comment]
El programa llega hasta:
self.s_cliente.connect((self.host, self.port))
Ni siquiera logra completarlo

**Comment by ranieto** [comment]
Me pasó lo mismo, pero se arregló cambiando el valor de PORT.

**Comment by Arcoirisky** [comment]
No me funciona :( 
Así ni se puede :'(

**Comment by akaminetzkyp** [comment]
Debería ser prácticamente lo mismo, pero quizás pase algo si cambias el `host` del servidor a un string vacío y el del cliente a `localhost`.

**Comment by stephichau** [comment]
@Arcoirisky si no te funciona lo que dijo @akaminetzkyp , cambia ambos ```host``` por strings vacíos :)

**Comment by Arcoirisky** [comment]
Sólo me tira para fuera más rápido. Ya lo intentamos con localhost, con socket.gethostbyname(socket.gethostname()) 
Todos los Port que se nos ocurrieron (incluso el 80)

:(

**Comment by Arcoirisky** [comment]
También desconectamos el firewall de windows

**Comment by Arcoirisky** [comment]
Gracias por la ayuda o: 
Al final era elun antivirus. 
Dato para otro con el mismo problema
