### ISSUE TITLE
importar un magizoologo

### ISSUE THREAD

**Issue by trinidadgatica** [IIC2233/syllabus#590]
Al intentar importar del archivo donde creo las clases, me lanza este error:
module 'entidades' has no attribute 'Magizoologo_docencio'
siendo que si poseo la clase magizoologo_docencio, sin embargo, cuando intento iniciarlizarlo no me deja por el error anterior.

**Comment by jeschuwirth** [comment]
Hola @trinidadgatica,

Para evitar estos mismos errores se pide CamelCase y snake_case en pep8, según el error que escribiste tienes 'Magizoologo_docencio' con la M inicial en mayúscula y magizoologo_docencio sin la m mayúscula.

Te recuerdo que las clases deberían estar escritas en CamelCase, por lo que debería ser MagizoologoDocencio.

Si esa no era la solución escribe un comentario para seguir ayudándote :)

**Comment by trinidadgatica** [comment]
hola, me sigue dando el problema despues de arreglar lo de las mayusculas y escribirlas en camel

**Comment by jeschuwirth** [comment]
pushea tu tarea y avísame por esta issue para revisar el código
