### ISSUE TITLE
Prohibición eval/exec

### ISSUE THREAD

**Issue by CataSudo** [IIC2233/syllabus#591]
Porque usar la función eval da un 1 automaticamente?

**Comment by CataSudo** [comment]
Tambien, si hago bool("False"), esto siempre da True, porque es un booleano. Como hago que sea False sin uso de bool?

**Comment by moquezada** [comment]
Hola @CataSudo,

> Porque usar la función eval da un 1 automaticamente?

¿Podrías dar un ejemplo sobre lo que te refieres? No entiendo en qué contexto te daría siempre 1 😮 


> Tambien, si hago bool("False"), esto siempre da True, porque es un booleano. Como hago que sea False sin uso de eval?


Eso se debe a que `bool()` retorna `True` para strings no vacíos y `False` para strings vacíos.

Saludos!

**Comment by CataSudo** [comment]
Ah, esta bajo Built-ins Prohibidos. Me entro la duda de porque no se puede usar.

**Comment by lily416** [comment]
Hola @CataSudo 

Los _built-ins_ `eval` y `exec` se encuentran prohibidos, ya que permiten la **inyección de código malicioso** en su computadora si es que sin que se den cuenta (como puede ser, apagando sus computadores o borrando archivos sensibles de este).

Un ejemplo más inocente sería:
```python
text_input = input("Ingrese True o False: ")
print(f'Valor variable: {text_input}, tipo: {type(text_input)}')

boolean_input = eval(text_input)
print(f'Valor variable: {boolean_input}, tipo: {type(boolean_input)}')
```
Lo esperado es que el usuario siga las instrucciones y ponga `True` o `False`:
```
Ingrese True o False: True
Valor variable: True, tipo: <class 'str'>
Valor variable: True, tipo: <class 'bool'>
```
Pero puede que el usuario no las siga e ingresar `exit()`, lo que haría que el programa se cierre al momento de ejecutar `eval()`:
```
Ingrese True o False: exit()
Valor variable: exit(), tipo: <class 'str'>
```

Por eso no pueden usar estos comandos en sus actividades y tareas, salvo cuando tengan que utilizar la librería `pickle`, pero aún falta mucho para ese momento del curso.

Más adelante, en otros cursos como Bases de Datos y Tecnologías y Aplicaciones Web, les enseñaran sobre la inyección de código y cómo evitarla.


Saludos y éxito en la tarea 👋🧙

**Comment by igbasly** [comment]
Hola @ignacioarteaga99 :v:

Debes preguntar eso en la issue correspondiente a las [librerías permitidas de la T00](https://github.com/IIC2233/syllabus/issues/87) en el syllabus del 2020-2.
