### ISSUE TITLE
Duda reproducción canción en sala vacía T06

### ISSUE THREAD

**Issue by malopez16** [IIC2233/Syllabus#591]
En el enunciado se indica:

> Siempre que haya jugadores en la sala, se debe estar tocando una canción.

Pero puedo interpretar ésto de dos formas:
1) La reproducción de las canciones se pausa cuando no hay nadie en la sala.
2) Siempre se reproduce una canción en la sala, haya gente o no.

Debido a que no está explícito en el enunciado, es correcto hacer cualquiera de las dos?

**Comment by rmsolari** [comment]
Hola, queda a tu criterio ya que no está especificado en enunciado

**Comment by malopez16** [comment]
Gracias!
