### ISSUE TITLE
¿Cómo saber cuando se cierra una ventana?

### ISSUE THREAD

**Issue by midiaz8** [IIC2233/syllabus#591]
Hola.
Quisiera saber si existe alguna forma de comprobar cuando una ventana creada con PyQt5 es cerrada con la X que está en la parte superior derecha.

**Comment by jaromero6** [comment]
Hola
El evento de presionar la X en una ventana se captura de la misma forma que se captura un KeyPressEvent por ejemplo. En particular, lo que quieres hacer podría estar relacionado con el evento closeEvent.
Espero te sirva

**Comment by midiaz8** [comment]
Muchas gracias. Era lo que necesitaba
