### ISSUE TITLE
Que hacer y que no hacer en parametros.py

### ISSUE THREAD

**Issue by BValdes16** [IIC2233/syllabus#591]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola quería saber que puedo hacer y que no puedo hacer en parametros.py. En particular quiero saber si puedo importar os para poder poner las rutas como parámetros y que funcione tanto para windows como para mac. En segundo lugar quiero saber si puedo poner algo de este estilo:
VEL_H = 5
VEL_L = 10
VEL_K = 4
VEL_M = 9
VELOCIDADES = {"Homero" : VEL_H, "Lisa" : VEL_L, 
    "Krusty" : VEL_K, "Moe" : VEL_M}

En vez de hacer eso, podría hacer el diccionario en el mismo módulo en que lo necesito, pero esto creo que es considerado uso de variables globales... Además, no hacer el diccionario implicaría trabajar con muchos if's sin sentido.

Yo supongo que se puede, pero el enunciado dice "cada linea debe almacenar una constante con su valor, por lo que me entra la duda. Muchas gracias

**Comment by mmunoz12** [comment]
Hola @BValdes16! En parámetros.py debiesen ir todos los valores que permanecerán constantes y que se utilizarán en tu programa, por lo que se deben poner los paths a utilizar. Como dices, para evitar hacer paths absolutos es posible usar `os.path.join()` en tus path, por lo tanto no hay problema con importar `os` en este archivo para dejarlos como paths relativos.

Para tu segunda pregunta, te recomiendo dejar los nombres de los parámetros en el mismo nombre con el que fueron entregados en el enunciado, a modo de que estos sean lo más descriptivos posible y sean fáciles de reconocer. Además, como dice el enunciado, en este archivo puedes agregar valores constantes que vayas a utilizar en tu código, por lo que crear un diccionario que también se mantiene constante estaría bien. Igualmente, debes asegurarte de, por ejemplo, no implementar **funciones** que creen nuevos parámetros dentro del archivo `parametros.py`, y así respetar lo que dice el enunciado sobre  "cada linea debe almacenar una constante con su valor". Espero que se haya entendido! avísame si te quedan dudas :)

**Comment by BValdes16** [comment]
Perfecto, muchas gracias
