### ISSUE TITLE
Cuando competir T01

### ISSUE THREAD

**Issue by aayale** [IIC2233/syllabus#591]
Hola, tengo el problema de que no sé en que momento se empieza a competir realmente en la tarea 1. En el menú principal solo se encuentra la opción simular competencias ¿con esta opción se empieza la competencia?

**Comment by retamalcito** [comment]
¡Hola @aayale!

La opción **Simular competencias** del menú principal corresponde al "cambio de día", ya que, como dice el enunciado, al seleccionarla se deben elegir a los deportistas que participarán en las competencias, y luego deben realizarse las competencias mismas.

![image](https://user-images.githubusercontent.com/62028973/93323903-92c54b00-f7eb-11ea-9802-18507c1e1383.png)

Por lo tanto, esta opción corresponde al comienzo del día de competencias.

¡Éxito en lo que queda! 🏅
