### ISSUE TITLE
comparacion entre escenarios

### ISSUE THREAD

**Issue by Jamidd** [IIC2233/Syllabus#591]
como se obtiene la métrica a utilizar cuando comparo dos escenarios diferentes?

**Comment by iqacevedo** [comment]
Hola,

La métrica a comparar debe ser ingresada por el usuario, como opciones debe poder escoger una entre las estadísticas (se usará una estadística como medida de desempeño). 

Saludos !

**Comment by Bneya** [comment]
Si selecciono como métrica el parámetro 2 por ejemplo **Ctadad max, min y prom de productos vendidos**, ¿cués escenario es mejor? el que tiene más de todo en sumatoria?

>Escenario1: max = 10, min = 0, prom = 7   ---> suma = 17
Escenario2: max = 7, min = 2, prom = 9        ---> suma = 18

¿El mejor escenario sería el 2?

**Comment by iqacevedo** [comment]
@Bneya se respondió en #562 
Saludos !
