### ISSUE TITLE
He estado trabajando en el codigo y no entiendo por que al entrar a una sala de chat me da error

### ISSUE THREAD

**Issue by sofiuni** [IIC2233/syllabus#591]
Lo que esta en el titulo, el codigo esta en mi repo y no entiendo por que no funcona :/

**Comment by sofiuni** [comment]
He actualizado el codigo y me da un error distinto

**Comment by lily416** [comment]
Hola, 

Tu error se debe a que cuando en la clase `SalaDeChat` haces `json.load(self.userliststr)`, la variable `self.userliststr` es una _string_. 

La librería `json` tiene dos funciones que son muy parecidas: `load` y `loads`.
- `load` recibe como input un archivo,
- mientras que `loads` recibe como input una string

Entonces, el error se produce al hacer `load` de una variable que es una _string_, que en este caso sería `self.userliststr`.

Prueba leyendo correctamente el archivo `.json` y cuéntame cómo te fue.

Saludos y éxito con la tarea. 👋🐧

**Comment by sofiuni** [comment]
Antes tenia eso, ahora que lo reverti me da


Traceback (most recent call last):
  File "client/main.py", line 76, in lanzar_sala1
    self.sala = SalaDeChat(self.salas[1], self.nombre_usuario)
  File "client/main.py", line 35, in __init__
    print(json.loads(self.userliststr))
  File "/home/usuario/miniconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/usuario/miniconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/usuario/miniconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Aborted (core dumped)

**Comment by lily416** [comment]
Fijate que `self.userliststr` contiene una _string_ que representa el _path_ de un archivo, por lo que cuando haces `json.loads` estás traduciendo el _path_ y no el contenido de este archivo.

Abre el archivo y después utiliza `json` para procesar el contenido.

Si tienes más dudas sobre esto te recomiendo revisar el [material sobre `json`](https://github.com/IIC2233/contenidos/blob/master/semana-11/2-serialización.ipynb).

**Comment by lily416** [comment]
Además ten cuidado con usar `..` para acceder a los archivos. Como se dice en la _issue_ #544:
> no puedes usar _paths_ para compartir recursos entre el cliente y el servidor

**Comment by sofiuni** [comment]
Ahora (subi el codigo) me da un error distinto, el archivo si existe (se esta corriendo client/main.py)

Traceback (most recent call last):
  File "client/main.py", line 78, in lanzar_sala1
    self.sala = SalaDeChat(self.salas[1], self.nombre_usuario)
  File "client/main.py", line 35, in __init__
    f= open(self.userliststr,"r")
FileNotFoundError: [Errno 2] No such file or directory: '../usuarios.json'
Aborted (core dumped)

**Comment by lily416** [comment]
Ese error se debe a que desde la ubicación donde estas corriendo el programa no se puede acceder al archivo.

Basándonos en este diagrama:
![image](https://user-images.githubusercontent.com/26393515/70098751-b1b37180-160b-11ea-82bd-37a642cdcabe.png)

La forma en la que se accede a `un_archivo_que_no_es_del_cliente_ni_el_servidor.algo` depende del directorio desde el que se ejecuta tu código:
- Si corres el archivo `main.py` del cliente desde dentro del directorio `cliente/`, para poder acceder al archivo debes hacer `../un_archivo_que_no_es_del_cliente_ni_el_servidor.algo`, ya que debes retroceder una carpeta para acceder al archivo.
- Mientras que si corres `cliente/main.py` desde el directorio `T03/`, para acceder al archivo solo debes hacer `un_archivo_que_no_es_del_cliente_ni_el_servidor.algo` o `./un_archivo_que_no_es_del_cliente_ni_el_servidor.algo`, ya que te encuentras en la carpeta el que se ubica el archivo.

Esto es equivalente para acceder a los otro archivos. Recuerda que para esta tarea **no puedes usar _paths_ para compartir recursos entre el cliente y el servidor** y que **los archivos `usuarios.json` y `amigos.json` debe estar guardados dentro del directorio del servidor**, ya que este es el que controla dicha información.

---

Para ejecutar tu archivo `main.py` desde dentro del directorio `cliente/` debes:
1. Abrir la consola y utilizar el comando `cmd` para moverte hasta dicha carpeta. 
1. Después ejecutar el archivo usando el comando `python main.py` o `python3 main.py` (esto depende de como hayas instalado python en tu computador).
1. Y listo. Debería funcionar normalmente.
