### ISSUE TITLE
Multa por salud baja de criatura

### ISSUE THREAD

**Issue by franciscaaguilera** [IIC2233/syllabus#592]
Hola! tengo una pequeña duda, al momento de cobrar la multa por salud baja (cuando llega al mínimo de salud), se cobra solo por las criaturas que alcanzaron su mínima salud ese día? o por todas las criaturas que estén actualmente con mínima salud... No me queda demasiado claro con el enunciado :(

**Comment by aljara97** [comment]
Hola @franciscaaguilera! Esta duda ya fue respondida en la issue #369, te recomiendo revisarla y en caso que te queden dudas puedes comentar ahí mismo.

Suerte en lo que queda de la tarea 🧙‍♂️
