### ISSUE TITLE
Reemplazar min

### ISSUE THREAD

**Issue by jgespinosa10** [IIC2233/Syllabus#592]
Estoy ocupando la función min para sacar el tiempo de la siguiente acción. Mi problema es que funciona super lento por ese min. ¿Habrá alguna forma de hacer más eficiente esa función? (Miré cuanto gastaba con cProfile y es lo único que detiene a mi programa).

**Comment by jgespinosa10** [comment]
Vi que fmin de la librería scipy funciona. Se puede ocupar esa librería?

**Comment by vijuarez** [comment]
Cualquier duda de usar librerías va en #468, para mantener el foro ordenado.

Saludos!

**Comment by jgespinosa10** [comment]
Hola, mi pregunta era si me podrían recomendar alguna forma de optimizar un min

**Comment by vijuarez** [comment]
Hola!

Como no sabemos más detalles de que estas usando con min (saber más estaría bordando en que nos muestres código, cosa que no se puede hacer) no podemos saber que te hace "bottleneck", así que lo mejor que te podíamos ofrecer era dar opciones hará que una funcionara. Tu encontraste tu mismo una solución, así que ahora es tema de preguntar por la librería. 

(Ya queda muy poco, así que no te molestes en preguntar en la general. Si, si puedes usar scipy 🎉🎉 )

Saludos y suerte!!
