### ISSUE TITLE
Colacion de operadores

### ISSUE THREAD

**Issue by raespinoza4** [IIC2233/Syllabus#592]
Hola, cuando un operador de una atracción se va a colación esta deja de funcionar por el tiempo que no esté su operador designado ? De lo anterior, si no está funcionando, los clientes no deberían poder elegirla hasta que esté abierta y los que estén en la fila deben esperar ? (Considerando su paciencia)

**Comment by IchottMano** [comment]
@raespinoza4 Hola!

Efectivamente, la atracción deja de funcionar si no está el operador.
Además, los clientes en fila deberán esperar. Sin embargo, queda a tu criterio si la gente puede elegir la atracción o no.

Saludos!

**Comment by Pipelao** [comment]
Hola, 
Tengo una pregunta con los horarios de lo porteros, ¿en qué momento debo entregarles su horario de colación? porque yo lo hago al instanciar un objeto Portero, y podría ser que los horarios se topen entre uno y otro, ¿tendría que desplazar el horario de uno hasta que termine el otro para que vaya a almorzar?  ¿o hago que los horarios de los tres operadores nunca sean iguales?
De ante mano, gracias.
