### ISSUE TITLE
Escribir mas parametros de los pedidos en parametros.py

### ISSUE THREAD

**Issue by stephenwpugh** [IIC2233/syllabus#592]
Hola! Para ordenar todas las variables que instancio, las escribo todas en parametros.py y lo importo en los modulos donde se necesitan, además de escribir ahí todas las que piden en el enunciado. Está bien o sería una mala práctica? Gracias desde ya!

**Comment by hsazos** [comment]
¡Hola @stephenwpugh !

No hay problema con que hagas eso. Trata de mencionarlo en el readme para que sea mas fácil entender tu programa cuando sea corregido.

¡Animo con la tarea!🦕

**Comment by stephenwpugh** [comment]
Muchas gracias! 😃
