### ISSUE TITLE
Sobre ubicación de variables

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#592]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Puedo hacer que ciertas variables solo vivan en el backend? Por ejemplo, al principio pensé añadir vida como atributo de clase a cada personaje en base al enunciado
![image](https://user-images.githubusercontent.com/66154723/120583356-0ea80780-c3fc-11eb-81b4-a3239c5a63ee.png)

**Comment by Juampisaez** [comment]
Hola @fernandosmither 
Yo creo que independiente que sea la misma para todos los personajes, puedes instanciarla como atributo de clase, de esta manera puedes llamarlo en cualquier parte de la misma clase. Te digo esto porque como lo estas pensando puede llegar a ser una variable global (puede que no). De igual manera, si quieres implementarlo como dices, hazlo, pero ten en cuenta lo de las variables globales y cumplir con la distribucion de puntaje (si se da puntaje por modelacion, puede ser mejor modelarlo como un atributo de clase).

Espero te sirva :)

**Comment by fernandosmither** [comment]
> Hola @fernandosmither
> Yo creo que independiente que sea la misma para todos los personajes, puedes instanciarla como atributo de clase, de esta manera puedes llamarlo en cualquier parte de la misma clase. Te digo esto porque como lo estas pensando puede llegar a ser una variable global (puede que no). De igual manera, si quieres implementarlo como dices, hazlo, pero ten en cuenta lo de las variables globales y cumplir con la distribucion de puntaje (si se da puntaje por modelacion, puede ser mejor modelarlo como un atributo de clase).
> 
> Espero te sirva :)

Y en ese sentido, cuál sería la distinción entre global y no global?, entonces, es mejor que todas las variables anteriormente mencionadas las deje como atributo de clase y ya está?

**Comment by Juampisaez** [comment]
@fernandosmither 
La distincion de global y no global, es principalmente que la global puede ser llamada en todo el programa en la practica. Por ejemplo, podria ser intanciar un valor al principio del codigo y llamarlo en funciones o clases, si te fijas no hay restriccion para poder editar o usar este valor. En cambio, en las clases, solamente se podran acceder a lo valores si esta lo permite (hay atributos que solo se pueden llamar dentro de la clase).

Nose si se entiende mejor, en esta [issue ](https://github.com/IIC2233/syllabus/issues/561)comente algo parecido.

**Comment by fernandosmither** [comment]
> @fernandosmither
> La distincion de global y no global, es principalmente que la global puede ser llamada en todo el programa en la practica. Por ejemplo, podria ser intanciar un valor al principio del codigo y llamarlo en funciones o clases, si te fijas no hay restriccion para poder editar o usar este valor. En cambio, en las clases, solamente se podran acceder a lo valores si esta lo permite (hay atributos que solo se pueden llamar dentro de la clase).
> 
> Nose si se entiende mejor, en esta [issue ](https://github.com/IIC2233/syllabus/issues/561)comente algo parecido.

Pero si por ejemplo, defino una variable global solamente en un módulo de backend, en teoría directamente solo este podría acceder a ella directamente, no? o de todas maneras la recomendación está en darle hogar a estas variables en la clase de personaje?

**Comment by Juampisaez** [comment]
@fernandosmither 
Pero si la llamas de varias funciones distintas, no hay manera de controlar su valor, a eso va la definición de variable global y por lo cual no es buena practica. Si me preguntas a mi, te recomiendo como un atributo, tiene mas sentido la verdad.

**Comment by fernandosmither** [comment]
> @fernandosmither
> Pero si la llamas de varias funciones distintas, no hay manera de controlar su valor, a eso va la definición de variable global y por lo cual no es buena practica. Si me preguntas a mi, te recomiendo como un atributo, tiene mas sentido la verdad.

Vale. Gracias!
