### ISSUE TITLE
Salas Tarea 6

### ISSUE THREAD

**Issue by pcsalvo** [IIC2233/Syllabus#592]
Hola!! Estuve leyendo la tarea y no entendí bien cuántas salas serán, estas las definimos nosotros así como las canciones que tendrá? O son específicamente las del ejemplo mostrado en el punto 4.3? Es decir, nosotros debemos descargar esas canciones y crearle preguntas específicamente para esas canciones o son de libre elección o las subirán más adelante para saber con cuáles practicar?

**Comment by arturodelreal** [comment]
Hola, tienes que hacer un código para una cantidad arbitraria de salas, que vienen determinadas por las carpetas que hay dentro de la carpeta songs (Punto 4.3 del enunciado). Las canciones las subimos como ejemplo, tu puedes agregar más salas y canciones si quieres para practicar, pero la corrección se hará con otras canciones y otras salas.
Saludos.

**Comment by pcsalvo** [comment]
Ya, entonces las preguntas siempre serán o el nombre del artista o el nombre de la canción??

**Comment by flobarrios** [comment]
@pcsalvo si!!

**Comment by pcsalvo** [comment]
Yaa Gracias!!

**Comment by tcgarrido** [comment]
Hola! me quedó una duda con esto, se supone que tengo que hacer mi código con X salas y canciones, pero uds corregirán con otras, entonces mi duda es como adaptar el código a eso. La idea es que el programa setee las salas y sus canciones usando os? o nos pasaran un json con las salas y sus canciones? No se si se entiende :3 es más que nada para saber como adaptar el código
