### ISSUE TITLE
Random vs numpy

### ISSUE THREAD

**Issue by behrmann97** [IIC2233/Syllabus#593]
Para las distribuciones normales, uniformes y triangular ¿se utilizan las funciones de numpy.random o las de random? Pregunto porque dan resultados distintos

**Comment by Arcoirisky** [comment]
Hola! 
Te sugiero usar las de la librería Random con mucha más preferencia que las de numpy.random 😅 pero, sí ha lo hiciste con la segunda explicalo en el Readme :D
