### ISSUE TITLE
Tamaño canciones Tarea 06

### ISSUE THREAD

**Issue by ignacioaraya1995** [IIC2233/Syllabus#593]
¿Porque las canciones del enunciado pesan tanto?

![captura de pantalla 2017-06-07 a la s 20 32 01](https://user-images.githubusercontent.com/21697653/26907263-6542fe1e-4bc0-11e7-9b1d-0d2d62335589.png)

**Comment by hanavarrete** [comment]
En general pesan todas eso.  Puedes encontrar más información en google. Saludos
https://www.google.cl/search?q=%60tama%C3%B1o+canciones+wav&oq=%60tama%C3%B1o+canciones+wav&aqs=chrome..69i57j0.3277j0j7&sourceid=chrome&ie=UTF-8#q=why+wav+files+are+so+big
