### ISSUE TITLE
Diagrama de clases, metodo que retorna mas de una cosa

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2233/syllabus#593]
cual es la notacion cuando un metodo retorna mas de una cosa? Una palabra y un booleano por ejemplo.
funcion(): str, int ?

**Comment by dsepulveda3** [comment]
Tengo otra pregunta mas relacionado a esto. Tengo una funcion "comienzo_de_dia()" que retorna "menu_de_acciones". Cuando printeo el type a menu de acciones no me retorna nada, por lo tanto, no se que poner despues de comienzo_de_dia: type

**Comment by dsepulveda3** [comment]
Me surge otra duda. Cuando se dice que una clase depende de otra (composición), esto cuenta solo para los atributos o los metodos tambien? 
Mi pregunta es, si mi clase Magizoologos llama a mi clase DCCriaturas a traves de sus metodos, habría composicion por parte de Magizoologos??
Por otro lado, si ocupo atributos de la clase Magizoologo en los metodos de DCCriaturas tambien tendria composicion para el otro lado? 
Puedo tener composicion ya agregacion para los dos lados??

**Comment by lily416** [comment]
Sí, la notación es:
> funcion(): str, int

En el caso de la función `comienzo_de_dia()`, puedes ponerle que retorna `function`. No estoy segura si sea lo más correcto, pero el ayudante que vea tu diagrama entenderá que retorna una función.

Tanto como la composición y la agregación permite acceder a los métodos y atributos de la clase. 
Puedes tener una relación doble entre clases (para un lado y para el otro), pero esto se llama "Dependencia circular", lo cual se considera una mala práctica. Actualmente no se considerará en la T01, pero en la T02 si se evaluará que esto no suceda. 


Saludos y éxito en la tarea
PS: Cuando tengas varias dudas distintas (sin relación entre ellas) trata de hacerlas en _issues_ distintas.

**Comment by dsepulveda3** [comment]
Oka. Tener en mi clase DCCritaturas, un metodo que reciba la responsabilidad del Magizoologo (o sea el metodo es llamado desde la clase Magizoolo); por ejemplo (function(self, resp_magizoologo)), que seria? Ahí habría dependencia circular? 
Estoy supero confundido.

**Comment by lily416** [comment]
¿Tu Magizoólogo llama un método de la DCCriatura y le pasa como _input_ uno de sus atributos? 
Si es así, no es dependencia circular. 

No te preocupes por esto en esta tarea, más adelante aprenderán sobre ella y cómo evitarla.

**Comment by dsepulveda3** [comment]
Si, eso mismo. Dale, gracias
