### ISSUE TITLE
largo, ancho en 4 bytes? [funcion filtro] [serializacion]

### ISSUE THREAD

**Issue by JupaOlivares** [IIC2233/syllabus#593]
si tengo que expresar por ejemplo el largo "4" en 4 bytes y con 1 byte puedo hacerlo con que relleno los otros bytes

**Comment by jeschuwirth** [comment]
Hola JP!

Al codificar la imagen se ocupa el formato big-endian, por lo que si codificas un número que necesita menos de 4 bytes, entonces rellenas con bytes \x00, lo que en binario es: 00000000.

Un ejemplo:
Al codificar 200 en 4 bytes queda b'\x00\x00\x00\xc8', lo que en binario es:
00000000|00000000|00000000|11001000, (las líneas son para diferenciar los bytes no están normalmente en el número).

Suerte en la tarea!

**Comment by JupaOlivares** [comment]
Gracias Juan! esa era mi duda
