### ISSUE TITLE
Duda "Tiempo máximo entre clientes"

### ISSUE THREAD

**Issue by llloyola** [IIC2233/Syllabus#593]
Hola! Una consulta... Si ya pasó el __tiempo máximo entre clientes__ de una atracción, pero ésta se encuentra vacía, debe comenzar a funcionar de todas formas? Me surgió la duda en base a los siguientes dos casos:

- Si son las 10:00, la atracción está obligada a partir a las 10:00 + __tiempo máximo entre clientes__? O el tiempo empieza a correr desde la llega del primer grupo de clientes?

- Si una atracción acaba de terminar su recorrido/función/juego/paseo/loquesea y no hay grupos en su fila, el conteo para esperar el __tiempo máximo entre clientes__ y funcionar nuevamente parte desde ese momento o desde la llegada del siguiente grupo de clientes?

**Comment by Hernan4444** [comment]
@llloyola esos son casos que tu tienes que decidir.

Saludos ✌️
