### ISSUE TITLE
Como borrar elementos específicos del repositorio

### ISSUE THREAD

**Issue by sebamoralesm147** [IIC2233/syllabus#593]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Duda

Hola tengo una duda con como borrar elementos desde el repositorio, que durante la tarea creé varios que en su momento pensé que serian útiles, y los subí como actualización de mi trabajo, pero que después vi que no eran necesarios o los hice de otra forma, y que ahora creo pueden llegar a confundir un poco a la hora de la revisión, por lo que quería saber si es que se pueden borrar o si simplemente especifico en el readme que esos archivos no sean considerados.
De antemano muchas gracias

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by aaossa** [comment]
Hola @sebamoralesm147 , dado que usaste Git para subir los archivos, puedes usar Git para eliminarlos. Lo que tines que hacer es eliminar los archivos de tu repositorio local (en verdad basta con sacarlos de la carpeta en tu PC) y luego agregar los cambios en un nuevo *commit* (en `git status` apareceran como "`deleted`"). Cuando subas esos *commits* a tu repositorio personal en GitHub, estos ya quedarían fuera de tu entrega 👌 Inténtalo (te recomiendo probar con un archivo primero para que veas que todo funciona bien) y cuéntame cómo te va 🙌 ¡Éxito con tu tarea ✨!

**Comment by sebamoralesm147** [comment]
Hola!! si con eso me funciono perfecto muchas gracias
