### ISSUE TITLE
archivo corrompido en vsc

### ISSUE THREAD

**Issue by alvaritions** [IIC2233/syllabus#594]
'H�gado de Drag�n' es un ejemplo de cuando escribo algo en el archivo. Estoy haciendo todo en VSC

**Comment by matiasmasjuan** [comment]
Hola @alvaritions !

Este **error** se debe a la **codificación** en la que **lees** y **escribes** sobre los archivos (específicamente en el uso de tíldes o caracteres que no se reconocen). Recuerda que lo mas recomendado es trabajar **siempre** mediante la misma ***codificación***, de tal forma que no se produzcan este tipo de **errores**. Por lo mismo, intenta incluir un ```(encoding="utf-8")``` al momento de trabajar con los archivos.

En caso de que hayas quedado con alguna duda, se respondió a una pregunta muy similar en la ***Issue*** #478 .

Saludos y mucho éxito con la tarea! 😄
