### ISSUE TITLE
Registro de eventos

### ISSUE THREAD

**Issue by Cschavez** [IIC2233/Syllabus#594]
Hola! Para el registro de eventos, cuando ingresa un adulto al parque también hay que registrar por separado (en otra línea) los niños que entran con él? o da igual?
Muchas gracias !

**Comment by Hernan4444** [comment]
@Cschavez idealmente ingresan todos en el mismo evento, por lo tanto debería ser solo 1 línea donde se diga que llegaron y quienes llegaron con el adulto.
