### ISSUE TITLE
Lesión durante la competencia

### ISSUE THREAD

**Issue by Sofia-Arratia** [IIC2233/syllabus#594]
Hola!

Traté de buscar un issue para esta pregunta, pero no lo encontré. Cuando un deportista se lesiona compitiendo en algún deporte, ¿Pierde automáticamente en ese deporte? Entiendo que si está lesionado desde antes, pierde automáticamente, y se aplica a cuando compite en múltiples deportes, pero no se si se aplica en el mismo deporte en el que se lesionó.

Desde ya muchas gracias y buen dia!

**Comment by YehudaGurovich** [comment]
Del enunciado 4.2: *Lesionarse:* Cada vez que un jugador compite en un deporte, existe una probabilidad de lesionarse.
Esta probabilidad depende únicamente del valor de riesgo del deporte. Si un jugador se lesiona
durante una competencia, la pierde automáticamente.

**Comment by Sofia-Arratia** [comment]
Perfecto, muchas gracias a ambxs!
