### ISSUE TITLE
Pequeño cambio en el uso de vida

### ISSUE THREAD

**Issue by Raibruh** [IIC2233/syllabus#594]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

¡Hola! Quería saber si es posible tratar a la vida del personaje como una cantidad definida de corazones, solo por motivos estéticos, en decir, en vez de utilizar la vida como un porcentaje entre 1 y 0, utilizarla como una cantidad de corazones entre 1 y 3 por ejemplo. Claro que respetando esto a la hora de las aplicaciones de los objetos que influyen en la vida del personaje (veneno quita una cantidad de corazones, etc). Quedando algo así: 
![Captura de pantalla 2021-06-03 014049](https://user-images.githubusercontent.com/80918062/120593351-57b48780-c40d-11eb-81ca-14f75d6f35a8.png)
y cuando se pierde una vida:
![cora](https://user-images.githubusercontent.com/80918062/120593433-816dae80-c40d-11eb-9e80-7149f29c1673.png)

**Comment by valerianazal** [comment]
Hola @Raibruh ! Lamentablemente no puedes tratar la vida de esa forma, ya que la idea es que manejes de manera correcta la **barra de progreso** (donde los valores para la vida deben ser entre 0 y 1) y que se vea reflejado a medida que avanza el juego.
Mucho éxito en la tarea! ✨
