### ISSUE TITLE
Error al pasar de ventana de inicio a ventana principal

### ISSUE THREAD

**Issue by JosefaPaz** [IIC2233/syllabus#594]
Hola!

Quería consultarles (ya que no encontré mucha información en internet) porqué se produce este error al querer cambiar de ventana, específicamente al acceder con un usuario válido en la ventana de inicio hacia la ventana principal.

El error es " QBasicTimer::start: QBasicTimer can only be used with threads started with QThread " pero no tengo ningún QBasicTimer o QThread ejecutado en el código frontend.

Gracias!

**Comment by gatochico** [comment]
Hola! Bajé la ultima actualización de tu repo y no pude replicar el error :( ¿Lo solucionaste? Si no es así, podrías indicar los pasos específicos para replicarlo?

**Comment by JosefaPaz** [comment]
Hola!
Primero en un cmd corro el servidor, y desde otro corro el cliente. Inicio sesión con 'gatochico' y ahí es cuando la pantalla cambia a ventana principal congelandose y mostrando ese error en el cmd de  cliente.

Gracias por la ayuda!

**Comment by gatochico** [comment]
Todavía no hemos logrado replicar el mensaje de error que te aparece :crying_cat_face: . Algunas dudas con respecto a variables externas a tu programa: 

- ¿Qué sistema operativo usas? 
- ¿Con qué cmd corres el programa/cómo corres el programa? 
- ¿Podrías subir pantallazos de tu ejecución del server, la del cliente, la interfaz cuando se queda pegada, y el mensaje de error que sale? (Para mantener la privacidad de tu tarea, haz una issue en tu repo privado y súbelas ahí :eyes:)

Por mientras que revisamos lo que ocurre, podrías tratar de encapsular la sección que lanza código en un try/except genérico, para que puedas avanzar en el resto de tu tarea. 

Quedamos atentos!

**Comment by JosefaPaz** [comment]
Hola Fran! ya hice la issue en mi repositorio con todos los datos :)

**Comment by gatochico** [comment]
Hola Josefa! Aunque no pudimos hacer aparecer el error en específico de QBasicTimer, efectivamente en windows tu interfaz se quedaba "pegada" donde dices (en ubuntu no, curiosamente :o ).

Lo que solucionó el problema, por lo menos en nuestro caso, fue separar de forma completa el frontend y el backend (siendo el cliente que maneja los mensajes recibidos del server parte del backend) mediante señales, ya que el frontend se bloqueaba esperando que el backend reciba contantemente mensajes del servidor. Por ejemplo, en algunas partes de tu cliente usas cosas como `self.frontend.actualizar_estado()` o `self.frontend.ingresar()`, lo que debería ser manejado con señales y no un llamado directo a la interfaz. La idea sería evitar llamados directos entre front/backend :scream: 

Trata de solucionar eso, y cuentanos como te va! :cat:

**Comment by JosefaPaz** [comment]
voy a probarlo, gracias!!! <3
