### ISSUE TITLE
Bonus contraseña - Invalid Salt

### ISSUE THREAD

**Issue by videvidts** [IIC2233/syllabus#594]
Porfa ayuda esto me ha fallado facil 890 veces. Me tira Invalid Salt, busqué la solución a eso y dice que use str.encode('utf-8'), ahí me dice: TypeError: Unicode-objects must be encoded before checking.
Tanto clave usuario como clave archivo son strings.
Mi función es la siguiente:
            if usuario in self.usuarios.keys():
                if bcrypt.checkpw(clave_usuario.encode('utf-8'),
                                  clave_archivo):
                      bla bla

**Comment by lily416** [comment]
Hola 😃 

Fijate que cuando guardas la información en el archivo `usuarios.txt` las claves quedan en formato:
```
b$2b$12$<algo que está hasehado>
b$2b$12$pVAOKhH8FHQXqZAQTgZ5N.Mi7siaAfAIuga21awXcj8NkgXsujKoe
```
y después cuando lees el archivo lees la clave encriptada como una string, por lo que mantiene el `b` que indica que lo que viene a continuación es un conjunto de bytes. Lo correcto sería que  cuando guardes las claves lo hagas en formato de string, para así evitar este problema.

Con respecto a los errores que te salen:
- `TypeError: Unicode-objects must be encoded before checking`: se debe a que la función `bcrypt.checkpw` espera recibir los dos argumentos en formato byte, así que tanto `clave_usuario` como `clave_archivo` deben estar encodeados.
- `ValueError: Invalid salt`: por lo que leí se levanta cuando se produce algún error en la ejecución del la libreria `bcrypt`. Probablemente se deba al problema que mencione antes: que se mante la `b` cuando se guarda la clave.

Para arreglarlo, intente quitar la `b` antes de comparar las claves: 
```python
clave_archivo = bytes(clave_archivo[1:], encoding='utf-8')
```
y dejó de producirse el error, eso si sale que la "clave es incorrecta" pese a que es la misma, pero te corresponde a ti ver como resolver eso. 😉 
Como _hint_ te puedo decir que cuando hasheas varias veces la misma clave **no** da el mismo resultado. 🙊 


Ánimo y éxito con la tarea 💪 👋

**Comment by lily416** [comment]
PD: Sería bueno que agregues un botón para volver a la ventana de inicio desde la ventana de registro o de inicio de sesión 😉

**Comment by videvidts** [comment]
Muchas gracias! Es verdad, me dice que la clave es incorrecta, pero con uno de mis usuarios no, no entiendo por que... tendré que ver.
