### ISSUE TITLE
Dudas con los Chunks

### ISSUE THREAD

**Issue by Arcoirisky** [IIC2233/Syllabus#594]
Pregunta, estoy revisando los audios .WAV y me surgieron varias dudas (Si, no logré entender bien esta materia __Ni siquiera me resultó la actividad del Gif y el .WAV de la actividad 12 </3__ )

1) Se supone que un Chunk esta compuesto de 4Bits, Entonces, si quiero trabajar con un Chunk en particular, por ejemplo el SampleRate que debemos multiplicar por un float, ¿debo multiplicar cada byte por separado o sumarlo y luego multiplicarlo?

2) ¿En el data, todos los Chunks son de a 4 bytes?

3) ¿Existe algún número mágico que me diga que estoy haciendo algo mal? En plan, mayor a 255 está malo 

4) Si llego a trabajar con los Chunk uniendo (o sumando) sus bits ¿cómo los separo después?

5) Si el BlockAling es el numero de bytes para cada sample de cada canal ¿No debería poder dividir la parte de data en ese número y darme un entero? Ej: Si mi BlockAling es 4, el len(Data) -Número de Bytes que contiene Data- dividido en 4 ¿debería darme un entero? Porque, si necesitan chuncks de 4 bytes debería poder dividir el Data en esa cantidad ¿no? (Pregunto eso porque me da un float)

6) ¿Pueden explicarme a lo que se refieren con little endian y Big endian? Porque, de primera supongo que debo guardar los bits en orden descendente cuando los guardo pero, al ver el Chunk "Format" se ve que no es tan así, ya que sigue la secuencia "87, 65, 86, 69".

Creo que eso por ahora, intento entender lo mejor que puedo esto de la Serialización y, por primera vez, google no me está ayudando :C

**Comment by Arcoirisky** [comment]
Por ejemplo, tengo un .wav que me dice (al sumar los bits correspondientes):
BitsPerSample = 16 (que serían 16 bits por sample, lo cual corresponden a 2 Bytes (considerando lo de 8 bits es un Byte) pero el BlockAlign -número de bytes por sample- dice 4)

Revisando lo que debería decir ChunkID y Format, pude dividir el HEAD del data (considerando SubChunk2Size para atrás parte del HEAD) Entonces, cuando veo la parte de Subchunk2Size, me dice 381 pero, data tiene un largo de 44399 (44443 - 44 byets) y al dividirlo no queda parejo para ambos lados. 

Estoy muy confundida :'S

**Comment by stephichau** [comment]
revisa [esta issue](https://github.com/IIC2233/Syllabus/issues/595) !
