### ISSUE TITLE
Editar archivo arrivals

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#595]
Hola, 
¿Puedo editar el archivo arrivals.txt antes de iniciar el parque?
(Es porque en mi modelo me sale mucho más fácil que el archivo indique los minutos hasta el próximo cliente y no su hora de llegada)

**Comment by raespinoza4** [comment]
Aprovecho la issue para preguntar si se le puede sacar el acento a "sábado" dentro del mismo archivo ya que me genera errores

**Comment by Hernan4444** [comment]
Hola, no pueden editar a priori el archivo. Lo que si pueden hacer es que su programa tome el _arrivals.txt_ y genere un nuevo archivo con lo que ustedes quieran, pero **si o si** debe ser capaz de correr con nuestros archivos al inicio.

Saludos ✌️
