### ISSUE TITLE
TypeError: can't pickle module objects.

### ISSUE THREAD

**Issue by matiasmasjuan** [IIC2233/syllabus#595]
Hola!
Al mandar la información desde el servidor al cliente,  (un diccionario donde uno de los "values" es una instancia de una clase), lo serializé usando pickle. Yo tengo entendido que pickle puede mandar instancias de clases siempre y cuando ambas clases estén definidas tanto en el cliente como en el servidor. Sin embargo, al realizar pickle.dumps(mensaje), me arroja el siguiente error:
TypeError: can´t pickle module objects.
Intenté buscar en internet pero no logré entender qué se puede hacer en esos casos.

**Comment by gatochico** [comment]
Hola! ¿Lograste solucionar el problema? Corriendo tu código, asumo que este es la instancia que quieres enviar:
![image](https://user-images.githubusercontent.com/37161120/70142634-7602c100-1678-11ea-884e-36027d0593ca.png)
Por otro lado, buscando sobre tu problema, aparentemente este ocurre no cuando estás haciendo pickle a una instancia de una clase, sino **a un módulo completo** (el equivalente sería hacer pickle.dumps(pickle) o algo así :scream: ), lo que podría darte una pista para encontrar el problema. 

Si todavía tienes el error, ¿Podrías mandar un pantallazo del mensaje de error para saber en específico qué parte la causa? Ya que corriendo tu código, no logré hacerlo aparecer.

Quedamos atentos!

**Comment by matiasmasjuan** [comment]
Hola! Finalmente si pude solucionar el problema. El tema era, como tu decías, que estaba mandando desde el servidor al cliente una instancia creada en otro módulo, por lo que el cliente debía tener ese mismo módulo para poder hacer loads a esa instancia. Además, otro posible error fue que uno de los atributos de la instancia que quería mandar era un self.socket = socket (objeto socket) por lo que en realidad estaba mandando una instancia dentro de otra instancia (siendo que no tenía ninguna utilidad para mi código realizar esto)
¡Muchas gracias!
