### ISSUE TITLE
Almuerzo o Snack?

### ISSUE THREAD

**Issue by valeria-adasme** [IIC2233/Syllabus#595]
Tengo el caso en que un alumno llega a la universidad, decide comprar un snack, y mientras está en la fila decide comprar almuerzo (esta decisión incluía el tiempo de traslado). ¿Cuál tiene preferencia? ¿Hago uno y después el otro? ¿O mejor cancelo el Snack y lo mando a buscar dónde comprar almuerzo?

**Comment by cilopez** [comment]
Revisa #543 !
