### ISSUE TITLE
Ejemplo WAV

### ISSUE THREAD

**Issue by hanavarrete** [IIC2233/Syllabus#595]
Hola! en vista de algunas preguntas que nos han hecho, queremos agregar otra imagen explicativa, que tal vez, en junto con la ya existente, ayude a entender más como se ordenan los wav. Saludos y mucho éxito en la tarea!
![1](https://user-images.githubusercontent.com/20782545/26942117-e516e824-4c4e-11e7-9dc4-346ebbbe83d5.png)

**Comment by nivek0o0** [comment]
Hola, se entiende absolutamente nada entre lo explicado ahora, lo del enunciado y lo que resulta de leer un archivo wav. Llevo toda la semana intentando hacer el ecualizador y el reproductor tira error.

El enunciado dice que BlockAlign es el número de bytes que tiene un sample **para cada canal**, mientras que en esta imagen se multiplica por el número de canales. Lo mismo ocurre para el SampleRate.

El enunciado dice que trabajaremos con samples de 4 bytes y el header entrega un BitsPerSample de 16, lo que no tiene ningún sentido si sabemos que 8 bits = 1 byte.

**Comment by benjamimo1** [comment]
Existe la posibilidad de un codigo base similar al de la tarea GUI donde teniamos la bola verde Mavrakis?

**Comment by DiegoAndai** [comment]
Hola! perdón por la tardanza.

Efectivamente en el enunciado hay un error, cada sample (chunk) tiene efectivamente 2 bytes, por eso son 16 BitsPerSample. Sobre el BlockAlign, el enunciado dice:

<img width="622" alt="captura de pantalla 2017-06-11 a la s 00 15 28" src="https://user-images.githubusercontent.com/16889233/27008247-e83d8650-4e3a-11e7-8218-ebee3457f6ec.png">

Entonces, para representar un sample de cada canal necesitamos 4 bytes, (2 bytes cada uno) que es lo mismo que hacer:

(Número de bits por muestra * Número de canales) / 8 = (16 * 2) / 8 = 4

La duda del SampleRate es lo mismo. Sobre el Subchunk2Size, con qué canción estás probando? Efectivamente no debería decir 26. Resumiendo entonces: Un sample corresponde a 2 bytes, y se ordenan [..., sample_izquierdo, sample_derecho, sample_izquierdo, ...] intercalados (en el enunciado también se refiere a estos como chunks).

Sobre tu pregunta final sobre si hay que convertir los bytes a int, parte del desafío del bonus es que descubran como se codifica cada sample y así saber como transformarlos a números y poder operar con ellos, para esto es importante el endianness, que se explica en el enunciado. También deben descubrir las distintas formas de representar números decimales en binario, [aquí](https://www.swarthmore.edu/NatSci/echeeve1/Ref/BinaryMath/NumSys.html) hay una buena guía para aprender sobre este tema.

Saludos y cualquier duda que tengan no duden en preguntar por aquí.

**Comment by jorgeriesco** [comment]
Quiero decir que a mi el BitsPerSample me da 8 de la cancion de bruno mars :(

**Comment by DiegoAndai** [comment]
Efectivamente, el primero es 16 y el segundo 0, por lo tanto:

byte 1 = 00010000
byte 2 = 00000000

y por estar en little endian el byte 1 es el menos significativo:

valor = 0000000000010000 = 16

creo que te comiste un cero jajjaja suele pasar.

Saludos

**Comment by jorgeriesco** [comment]
@DiegoAndai Gracias, pero para dejar algo claro.

Yo concatené y luego di vuelta todo, tal como sale en el ejemplo del enunciado. Lo que tu hiciste es poner en orden los bytes de acuerdo a little endian, como sale en el enunciado antes del ejemplo, osea, que el ejemplo está malo y confunde.

Lo dejo claro para otros que lean esto.

**Comment by DiegoAndai** [comment]
El ejemplo efectivamente está errado... vamos a arreglarlo, disculpa por eso. Lo que pasa es que en el ejemplo del enunciado, se consideran palabras de 1 byte, por lo tanto 0b10100100 son dos palabras:

palabra 1 = 1010
palabra 2 = 0100

por lo tanto en little quedaría 01001010 = 74 y no 37 como aparece ahí. 

De todas formas el BitsPerSample podría ser 8. Tienen que entender los samples como "muestras" de frecuencia que se codifican en un número. Para este número se pueden ocupar 1, 2 o incluso más bytes. En las canciones que les pasamos debiesen ser todos de 16, pero esto solo cambia la codificación del número de la muestra y no la lógica de la estructura en absoluto. Quizás les quede más claro con esta pregunta de so:

https://stackoverflow.com/questions/13039846/what-do-the-bytes-in-a-wav-file-represent

**Comment by acrojas2** [comment]
@DiegoAndai 
Hola!
No entendí mucho tu explicación del sample, BlockAlign, etc. Al final que es cada cosa? 
Yo lo entiendo así y por favor corregir si estoy equivocada:

- supongamos tengo una lista con bytes : [byte1, byte2, byte3, byte4, byte5, byte6, byte7, ...,byte-n]

- si BlockAlign es 4: entonces el sample 1 del canal1 sería byte1, byte2  mientras que el sample 1 del canal2 sería byte3, byte4 y así sucesivamente ?


Espero puedas resolver mi duda. Saludos.

**Comment by acrojas2** [comment]
Hola!: 
Otra duda con los bytes:
cuando los transformo de int a byte me pasa lo siguiente:
numero -> 1
numero en bytes  -> b'\x01\x00'
numero ->87
numero en bytes  -> b'W\x00
¿está bien que me aparezca la W en lugar del byte? 
Me pasa con varios números, por eso pregunto. es como si un byte lo pasara a string.
Saludos!

**Comment by Hernan4444** [comment]
@acrojas, esa W es solo una forma de visualizar nomás el bytes, está bien eso. Si haces `int.from_bytes(b'W\x00', byteorder='little') `, eso dará 87 que es el mismo numero que tienes. No hay nada de que preocuparse :+1: 

Saludos!

**Comment by acrojas2** [comment]
Hola! 
Estaba ocupando int.from_bytes(...) e int.to_bytes(...) se puede?
Duda 2, cundo se hace la operación para obtener el chunk nuevo, eventualmente podría darnos un numero decimal (float) o también cuando se multiplica el SampleRate por f pasaría lo mismo, en este caso hay que considerar el int del resultado de la operación y eso pasarlo a bytes ? 
Duda 3, cuando hago append a un bytearray de un int.to_bytes(...) me tira el siguiente error: TypeError: an integer is required porqué pasa esto si se supone que le estoy agregando bytes al bytearray??
Saludos!

**Comment by Arcoirisky** [comment]
¿Qué diferencia en el archivo se produce en el caso de que el marcador de inicio del data sea "LIST" o "data"?
El filtro me funciona bien con los que tienen esa parte del head con "data" pero no se reproduce con el otro :C

**Comment by Arcoirisky** [comment]
¿Qué diferencia hace que la cabecera del data diga __b'data'__ en vez de __b'LIST'__? 
Lo que sucede es que archivos con el primer encabezado funciona bien en el filtro mientras el otro no. (También cambia el len del data. El primero tiene 47033856 y el otro 26)

a parte de eso y los fs, todo es igual :C

**Comment by DiegoAndai** [comment]
@acrojas2 Hola! 
- Duda1: Sí se puede
- Duda2: El chunk nuevo (sample nuevo para ser consistente con el enunciado actualizado) pasalo por el constructor de int (o sea has `int(sample_nueva)`) para obtener un entero. Haz lo mismo con el SampleRate y avísa por aquí si funciona o no.
- Duda 3: El bytearray se define como una "lista de enteros" en su [documentación](https://docs.python.org/3/library/stdtypes.html#bytearray), cada uno de estos enteros es un byte, pero para porder agregarlos tienes que hacerlo byte por byte, que Python como dice en #620 trata como ints. [Esto](https://docs.python.org/3/library/functions.html#func-bytearray) puede resultarte útil también.

@Arcoirisky Hola! ¿en que archivo exactamente pasa eso? para revisarlo. Te recomiendo ver [esta](https://stackoverflow.com/a/16242614) pregunta de StackOverflow, si eso no soluciona tu problema pregunta de nuevo por aquí.

**Comment by Arcoirisky** [comment]
Sucede en los .WAV que he descargado yo
Al parecer son LIST-INFO Chunk. Ese es el nombre inicial del data. Voy a intentar con StackOverflow pero, me gustaría saber qué son.

**Comment by DiegoAndai** [comment]
@Arcoirisky lo que pasa es que el header de los WAV puede ser de largo 44 y tener la información que aparece en el enunciado, pero hay algunos que agregan más cosas en el header, dependiendo del uso que se le quiera dar al archivo. Nosotros les pasamos WAV de header 44 para simplificar la comprensión y porque es el formato original de archivos WAV, pero pueden existir programas o sitios web que trabajen con más datos en el header. A pesar de esto, el trato de los bytes de la sección data debiese ser el mismo.

Saludos.
