### ISSUE TITLE
Crear personajes con señales?

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#595]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Cuando en este item de seleccionar el personaje en la ventana de preparación con uso de señales, se considera como señal el propio connect de un botón?
![image](https://user-images.githubusercontent.com/66154723/120681632-92e4a400-c469-11eb-8be3-b9f0073d0f41.png)
### Otra duda, está bien si al cambiar de personaje lo único que haga con una pyqtsignal como tal es enviar los datos de la partida (vida, pje, etc) al backend y nada más, pero el frontend como tal se encargue de todo respecto a verificar colisiones, spawnear los personajes, etc?

**Comment by tqmbanados** [comment]
Hola! Voy por partes.
1.- claro que si! Recuerda eso sí que la señal la deberás conectar en el main :)
2.- aquí creo que te perdiste un poco! La vida y el puntaje deben ser guardados y cargados en el backend, y este envia la info al frontend para ser mostrado. Las colisiones y sus consecuencias también son trabajo del backend. La aparicion del personaje es un area gris, pues no creo que haya logica de por medio. Sin embargo, su movimiento es trabajo del backend!

Espero haberte ayudado :) cuentame si te queda alguna duda.

**Comment by fernandosmither** [comment]
> Hola! Voy por partes.
> 1.- claro que si! Recuerda eso sí que la señal la deberás conectar en el main :)
> 2.- aquí creo que te perdiste un poco! La vida y el puntaje deben ser guardados y cargados en el backend, y este envia la info al frontend para ser mostrado. Las colisiones y sus consecuencias también son trabajo del backend. La aparicion del personaje es un area gris, pues no creo que haya logica de por medio. Sin embargo, su movimiento es trabajo del backend!
> 
> Espero haberte ayudado :) cuentame si te queda alguna duda.

perfect!
