### ISSUE TITLE
Connection Reset Error

### ISSUE THREAD

**Issue by videvidts** [IIC2233/syllabus#595]
Al intentar usar el chat desde varios clientes me tira Connection Reset Error y no me deja hacer nada más (ni salir de la sala, cerrar sesion, etc). ¿Alguna idea de como solucionarlo o por qué pasa?

**Comment by lily416** [comment]
Hola 😄 

Estuve probando el último código que subiste a tu repositorio y nunca me salio tu error 😕 
¿En qué situaciones te aparece? Lo estuve probando con hasta 8 personas en una misma sala y no tuve ningún problema: 

![image](https://user-images.githubusercontent.com/26393515/59925861-015c0300-9407-11e9-9f23-754496b67a49.png)

**Comment by videvidts** [comment]
Que raro, quizas la ultima versipon fue sin alfunos cambios que hice, podrías intentarlo ahora?

**Comment by lily416** [comment]
Volví a clonar tu repo y a probarlo con 8 clientes en una misma sala y no tuve problemas 😕 

![image](https://user-images.githubusercontent.com/26393515/59958586-0789c800-9477-11e9-8119-a281f715616b.png)

No sé si se puede deber a tu computador o si es la forma en la que estoy haciendo las cosas:
 1. Generar los clientes de a uno en uno
 1. Crear una sala y agregarlos a esta
 1. Probar si hay problemas con los mensajes del chat  

Dime los pasos que sigues para que se genere el error, para así tratar de replicarlo en mi computador.

Saludos 👋 💪
