### ISSUE TITLE
problemas con .gitignore

### ISSUE THREAD

**Issue by MariaJoseCovarrubias** [IIC2233/syllabus#595]
Hola!! No me hace ningún efecto el .gitignore sobre los datos que pongo dentro de el. No sé cuál es el problema porque al parecer lo estoy haciendo bien. Adjunto pantallazo!

![Captura de pantalla 2020-04-20 a la(s) 15 23 53](https://user-images.githubusercontent.com/54035477/79791482-63cdaa80-831b-11ea-9c4f-8663d65728de.png)

**Comment by Dnpoblete** [comment]
Hola @MariaJoseCovarrubias, de casualidad estas tratando de eliminar elementos que ya subiste previamente al repositorio? si es así podrías revisar la issue #588 en donde se habla del tema.

Avísame si es eso y si no es para ver como ayudarte! 😄
