### ISSUE TITLE
Duda bonus servidor y cliente robusto

### ISSUE THREAD

**Issue by JuaniAndres** [IIC2233/syllabus#596]
Hola tengo varias dudas respecto a este bonus
El enunciado dice esto:
![image](https://user-images.githubusercontent.com/48482216/70071653-6df14580-15d4-11ea-9898-ce65b08e804f.png)
![image](https://user-images.githubusercontent.com/48482216/70071680-76e21700-15d4-11ea-8ec4-1ac0eb2e9254.png)

Mis dudas:
1: Cuando el cliente pierde la conexión al servidor muestro el mensaje pero como seria la opción de cerrar el programa?
2: A  que se refieren con manejar todos los casos con una sola linea de flujo no me quedo muy claro en ese ejemplo
3: A que se refieren con seguir su curso natural y no hacerlo de manera forzada por ejemplo es valido que para terminar con el cliente llamar al exit del QApplication para cerrar todas las ventanas y terminar de correr el programa por el sys.exit(app.exec_())
4: Como seria un timer daemon?

Muchas gracias de antemano

**Comment by lily416** [comment]
En respuesta a tus dudas:
> 1: Cuando el cliente pierde la conexión al servidor muestro el mensaje pero cómo sería la opción de cerrar el programa?

En caso de que el servidor se cierre abruptamente, se le debe informar al usuario por medio de la interfaz gráfica (i.e. un _pop up_ o una nueva ventana) y en caso de que el usuario cierre el aviso o haga _click_ en un botón específico, se procede a cerrar el programa.

---

> 2: A que se refieren con manejar todos los casos con una sola línea de flujo no me quedó muy claro en ese ejemplo

Se refiere a que el proceso de salida debe ser más que atrapar la excepción y hacer `exit()` del programa.

Por ejemplo, en el caso del servidor hacer:
```python
try:
    ...
except ConnectionError:
    print('Se cayó el servidor')
    exit()
```
estaría malo, ya que no se procesa la desconexión del servidor (que sería lo de la pregunta anterior), sino que solo se hace un `print`.

En el caso del cliente, se espera que el proceso del `except` incluya lo que se dijo anteriormente, además de cerrar los archivos utilizados por el cliente y cerrar correctamente las ventanas de la interfaz, etc.

---

> 3: A que se refieren con seguir su curso natural y no hacerlo de manera forzada por ejemplo es válido que para terminar con el cliente llamar al exit del QApplication para cerrar todas las ventanas y terminar de correr el programa por el sys.exit(app.exec_())

Se refiere a que si el servidor pierde la conexión de un usuario, se proceda a desconectarlo: sacarlo de las salas de chat en las que se encuentra conectado, sacarlo de la lista de usuarios conectados, cerrar los archivos relacionados al usuario (si es que hay), etc. A fin de cuentas que se realice un proceso de desconexión similar a la desconexión de un usuario normal.

En el caso de que el cliente pierda la conexión del servidor, la idea se centra en lo que expliqué anteriormente.

---

>  4: Cómo sería un timer daemon?

Sobre esto te recomiendo revisar [el material sobre threads](https://github.com/IIC2233/contenidos/blob/master/semana-05/1-threading.ipynb).


Saludos y éxito con la tarea 👋🐧

**Comment by JuaniAndres** [comment]
Muchas gracias me quedo más claro
