### ISSUE TITLE
Duda con .gitignore

### ISSUE THREAD

**Issue by lewebe** [IIC2233/syllabus#596]
Hola, para hacer el .gitignore, tengo que añadirle esas dos carpetas iniciales? (.vscode y pycache)
![image](https://user-images.githubusercontent.com/62037289/79796282-469cda00-8323-11ea-9d8b-85b3ffa7c319.png)

**Comment by JosefaPaz** [comment]
¡Hola @lewebe !

Dado que estas carpetas son "caché" de las aplicaciones VSCode y Python, y no las queremos arriba en el repositorio, sí, también hay que añadirlas al .gitignore.

Éxito!
