### ISSUE TITLE
Problema con intersecciones

### ISSUE THREAD

**Issue by elpelaoloco** [IIC2233/syllabus#596]
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola , estoy intentando hacer que cuando los objetos se generen no lo hagan en la misma posicion que otros, para estoy ocupando intersects, el problema es que ahora corro mi codigo y se me queda pegado durante la ejecucion. sin embargo el codigo que estoy ocupando no es nada del otro mundo.  nose como hacerlo si no es de esa forma. el codigo esta subido en mi repo, esto ocurre en planta_nuclear.py, linea 119 en adelante. ojala me puedan ayudar plz

**Comment by catalina-arcila** [comment]
Hola @elpelaoloco (gran nombre jaja), el problema de tu código es que si bien haces las restricciones para que no haya ningún objeto solapado, no haces nada al respecto (132 al 137). Entonces genera como un bug infinito. Lo que debes es hacer es ir iterando hasta encontrar un posición que no tenga intersecciones con  objetos y/o obstáculos.
Pd: Recuerda detener los Qtimer al terminar de usarlos
Espero haberte ayudado! 🙌

**Comment by elpelaoloco** [comment]
pero con el randint deberia estar iterando siempre o no??

**Comment by catalina-arcila** [comment]
Yo diría que si, pero depende totalmente de tu modelación 👀

**Comment by elpelaoloco** [comment]
ya. muchas gracias, lo revisare
