### ISSUE TITLE
Duda emojis

### ISSUE THREAD

**Issue by Okhan97** [IIC2233/Syllabus#596]
Hola ! 

En la tarea se menciona que el chat reconoce automaticamente los comandos de los emojis y los cambia altiro, mi pregunta es: ¿ Si el mensaje es "hola:)" ( sin espacio entre el "hola" y el ":)" ) tambien se desplegará  el emoji ?

**Comment by DiegoAndai** [comment]
Si, debería desplegarse :)

**Comment by vaguila95** [comment]
respecto a las imágenes de los emojis ¿dónde las almacenamos?

**Comment by hanavarrete** [comment]
eso queda a tu criterio, como en la t05, en alguna subcarpeta llamada emojis, etc. Saludos!

**Comment by ignacioaraya1995** [comment]
Hay alguna pagina web para bajarse los emojis?

**Comment by iqacevedo** [comment]
Lo mejor es buscarlo por Google, basta con que sean imágenes.
