### ISSUE TITLE
Importar archivo .json

### ISSUE THREAD

**Issue by josejimenezp** [IIC2233/syllabus#596]
Hola, tengo un problema cuando intento exportar el archivo parametros.json de la carpeta 'client' en el archivo del front_end que está en el mismo path que la carpeta 'client'. Este es el código que pongo y el error que me arroja.
![Captura de pantalla 2019-06-20 a las 21 37 29](https://user-images.githubusercontent.com/48298035/59891858-d640c780-93a4-11e9-8b0a-4968d7884e13.png)
![Captura de pantalla 2019-06-20 a las 21 39 39](https://user-images.githubusercontent.com/48298035/59891859-d6d95e00-93a4-11e9-8286-16ea8f2d5a7d.png)

**Comment by jeschuwirth** [comment]
Hola,

Si el archivo .py que estas usando esta en la misma carpeta que parametros.json no tienes que poner client/parametros.json, sino que basta con parametros.json.

Si ese no es el problema puede que sea que en la foto de arriba tienes with open("client/**parmtros**.josn) en vez de parametros

Avisa si alguna de estas soluciones te sirve para seguir buscando si no!

**Comment by josejimenezp** [comment]
Hola otra vez jajaja las fotos que mandé están mal :P el archivo no está en la misma carpeta, pero la carpeta 'client' está en la misma carpeta que el archivo del front_end. Y el problema no es que esté mal escrito :'(

**Comment by jeschuwirth** [comment]
Sube lo que tienes a tu repo, ahí lo puedo ver más fácil

**Comment by josejimenezp** [comment]
Listoo!! Graciasss

pd: vas a tener que copiar (no mover) el archivo de parametros.py que está en client fuera de la carpeta para que funcione todo

**Comment by jeschuwirth** [comment]
![image](https://user-images.githubusercontent.com/37160256/59893894-8d8d0c80-93ac-11e9-99cc-d190eb85d56e.png)
<3

Poner lo siguiente en las líneas 9 y 10 me funcionó 😅 

![image](https://user-images.githubusercontent.com/37160256/59893921-ab5a7180-93ac-11e9-9f63-151849486458.png)

**Comment by josejimenezp** [comment]
Es lo mismo que intenté y a mí no me funciona :c lo corriste directamente desde el archivo front_end.py o ejecutando el main.py del cliente? Lo dejo así no más si no aunque a mí no me funcione? jajaja

**Comment by jeschuwirth** [comment]
No deberías tener ningún archivo fuera de client o server, así que realmente no es un problema, si te falla colocar "/" vas a tener que importar la librería os y trabajar con ella 

Suerte en la tarea :D
