### ISSUE TITLE
Nauseas

### ISSUE THREAD

**Issue by nicoparraguez** [IIC2233/Syllabus#597]
Hola , quería preguntar si el valor inicial de las nauseas esta bien y en caso que este bien , si el valor 90 de tope para que la persona tenga probabilidad de vomitar, ya que con los valores dichos en el enunciado nunca alguien vomita ya que son valores definidos muy elevados y por lo tanto nunca pasa :(

de antemano,muchas gracias.

**Comment by Hernan4444** [comment]
@nicoparraguez por cosas como estas, es que tenemos el parameters.py y puedes cambiar el 90 por otro valor mas chico, aumentar la cantidad de nausias que sube con cada atracción o el valor inicial. Es probable que nunca alguien vomite porque los datos que les dimos solo funcionan cuando se suban a demasiadas atracciones, pero los adultos no cuentan con tanto dinero para financiar tantas atracciones.
