### ISSUE TITLE
Convertir gran numero int a 4 bytes 

### ISSUE THREAD

**Issue by JupaOlivares** [IIC2233/syllabus#597]
hola!
no encuentro la forma de dejar expresado un numero grande ej: 1300 en 4 bytes en un bytearray como que bytearray no me acepta numeros grandes o me los corta

**Comment by jeschuwirth** [comment]
Hola!

Creo que estas teniendo problemas para pasar de int a byte, recuerda que un byte no es más que 8 bits, o 8 valores 0 o 1. 
00000000 = 0
11111111 = 255
Por lo tanto el mayor valor que puedes guardar en un byte es 255, por esta razón el **largo** se guarda en 4 bytes en vez de 1, de ese modo el mayor valor que puedes tomar es:

11111111111111111111111111111111 = 4.294.967.295 

En tu caso si quieres guardar el 1300, primero debes pasarlo a binario:
10100010100

luego rellenarlo con ceros hasta los 32 dígitos
00000000000000000000010100010100

y divirlo en grupos de 8
00000000|00000000|00000101|00010100

Y ahí tienes tus 4 bytes que respresentan el 1300 sin problemas

Te recomiendo revisar el documentación de int.to_bytes() que te puede ayudar bastante.

Exito!
