### ISSUE TITLE
Imprimir resultados.txt

### ISSUE THREAD

**Issue by fedezang** [IIC2233/syllabus#597]
Hola, tenía la duda de si en la tarea se debe imprimir en consola los resultados de la competencia que se realizó además de escribirlos en ```resultados.txt```. Ya que el enunciado no menciona que se deban imprimir.

**Comment by vicentevegaulloa** [comment]
Hola @fedezang !

El archivo resultados.txt es un registro de los ganadores por día en cada competencia, que debe escribirse en un archivo txt pero **no** es necesario mostrarlo.
