### ISSUE TITLE
Largo de Lineas 

### ISSUE THREAD

**Issue by martin-quevedo** [IIC2233/syllabus#597]
Como hago para no pasarme de los 100 caracteres por linea, cada vez que corto lo que estoy escribiendo y sigo en la linea de abajo, no me funciona

**Comment by moquezada** [comment]
Hola @martin-quevedo,

En los contenidos de la semana 00 se dan opciones sobre como hacer line breaks. Específicamente te pueden ser de utilidad las secciones de **1-guía-de-estilo** y **4-strings**. Además, te dejo un [link](https://stackoverflow.com/questions/53162/how-can-i-do-a-line-break-line-continuation-in-python) donde también se explica este tipo de formato.

Saludos.
