### ISSUE TITLE
QObject::killTimer: Timers cannot be stopped from another thread

### ISSUE THREAD

**Issue by Baelfire18** [IIC2233/syllabus#597]
Hola estoy en la T3 y no me deja abrir la ventana principal.
 Tengo que si se acepta el nombre del usuario en el servidor, este llega al cliente el cual hara hide en la ventan de inicio y abrirá la ventana principal. Más no me deja hacerlo porque me tira el siguiente error:
QObject::killTimer: Timers cannot be stopped from another thread

Que puede ser?

**Comment by tomasgv** [comment]
Hola!

Ese error se debe a que estás deteniendo un *Timer* desde un *thread* que no es el principal de éste.  La causa más probable es que estés usando los métodos ```hide``` y ```show``` de las ventanas dentro del *thread* que usa el cliente para escuchar al servidor. ¡Recuerda usar señales! De este modo los métodos anteriores serán realizados dentro de sus respectivos *threads* (de las ventanas) y lograrás una mejor separación *frontend/backend* :tada:.

Espero haberte ayudado! 🐧

**Comment by Baelfire18** [comment]
Gracias!!
