### ISSUE TITLE
Interfaz - Puntaje y tabla de puntajes T06

### ISSUE THREAD

**Issue by malopez16** [IIC2233/Syllabus#597]
En cuanto al punto 3.4 del enunciado (Puntaje),

Se indica información acerca de lo que debe mostrar la sección puntajes en la pantalla inicial, pero la redacción genera ambiguedades. En el punto 2 y 3:

> 2. La sala en la que **han** contestado correctamente a más canciones

> 3. La sala en la que **no han** contestado incorrectamente más canciones

**han** -> Siendo ellos cada cliente local o todos los usuarios?

Para explicarlo mejor, la redacción da 3 posibilidades. Puede que:

- El usuario local pueda ver en qué sala él mismo ha contestado correctamente / incorrectamente a más canciones.

- En la tabla de ranking deba aparecer una sola vez dos salas: En la que más usuarios en total han contestado correctamente y en la que más usuarios han contestado incorrectamente (como para ver que sala hasta ahora es la más fácil o más difícil).

- Las estadísticas acerca de la sala en la que ha contestado más/menos canciones para cada usuario incluyendo el local, implicando que se muestra un par de salas para cada usuario.

¿Cuál tenemos que hacer?

Muchas gracias :)

**Comment by hanavarrete** [comment]
la tercera posibilidad, mostrar un par de salas para cada usuario. Saludos!!

**Comment by malopez16** [comment]
Gracias!
