### ISSUE TITLE
Logs servidor

### ISSUE THREAD

**Issue by mpbascunan** [IIC2233/syllabus#598]
En el enunciado dice que se debe imprimir un log cada vez que el servidor le envíe un mensaje a un cliente (entre otras acciones), pero ¿esto significa que sólo se deben imprimir de este tipo de logs cuando el servidor responde una consulta?, o ¿también cuando envía mensajes de otro tipo?, como cuando se actualiza la cantidad de personas en una sala o cosas así.

**Comment by gatochico** [comment]
Hola! 

En el enunciado se muestran algunos que **no** consultas directas donde se deben imprimir _logs_  (por ejemplo, el entrar o salir de una sala):
![image](https://user-images.githubusercontent.com/37161120/70100836-d9a5d380-1611-11ea-8d29-38efc62d7548.png)

Por otro lado, aunque los casos enumerados arriba son lo **mínimo** que deberían tener los logs, el añadir casos adicionales te beneficiaría tanto a tí (para poder ir debuggeando tu código a medida que haces tu tarea) como para el ayudante corrector (a quien le servirá de ayuda para ver de forma más clara el funcionamiento interno de tu tarea)!

Cualquier duda nos avisas y éxito! :nerd_face:

**Comment by mpbascunan** [comment]
Muchas gracias!

**Comment by sebacarrasco** [comment]
Hola, cuando uno hace el log de que un cliente recibe un paquete de información de algún cliente al indicar el tamaño del mensaje se refiere a mostrar el tamaño del mensaje que escribió el cliente que lo mandó? O si yo estoy enviando un diccionario en el que uno de los valores es el mensaje debería mostrar el tamaño del diccionario?
