### ISSUE TITLE
Botón Pausa

### ISSUE THREAD

**Issue by mjsifri** [IIC2233/syllabus#598]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, quería saber si se pueden implementar dos botones, uno de pausa y otro para reanudar el juego, o hay que hacerlo solamente con el botón de pausa, es decir, volver a presionarlo para que se reanude el juego?
Saludos

**Comment by mmunoz12** [comment]
Hola @mjsifri! Como dice el enunciado, como mínimo debe haber un botón de pausa, pero si deseas implementar otro botón más que permita reanudar la ronda, no hay problema. Suerte en tu tarea!
