### ISSUE TITLE
An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by rfenzo** [IIC2233/Syllabus#598]
Hola, estoy tratando de correr un codigo que se encuentra en le contenido del curso, el "Ejemplo Práctico: Servidor con manejo de múltiples clientes en forma concurrente", lo único que cambié fue el puerto y la ip. Sin embargo, al ejecutarlo, me entrerga todo esto en consola:

```
Inicializando cliente...
Cliente conectado exitosamente al servidor...
------ Consola ------
 Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python35\lib\threading.py", line 923, in _bootstrap_inner
    self.run()
  File "C:\Python35\lib\threading.py", line 871, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Romano\Desktop\clientest.py", line 56, in listen_thread
    response_bytes_length = self.socket_cliente.recv(4)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
```

Estoy haciendo algo mal?

**Comment by hanavarrete** [comment]
Hola! Estás corriendo el código tal cual como está? A mi no me hizo problema ☹️

**Comment by Hernan4444** [comment]
@rfenzo por otro lado, intenta por si acaso desactivar antivius y firewall, a veces esos 2 procesos detectan la conexión de Python como una posible amenaza y detienen al servidor. Podrías intentar eso para poder delimitar el posible problema que tienes?

Saludos

**Comment by rfenzo** [comment]
Haber, es que tengo varios problemas en realidad:

1-. Si ocupo un puerto X y ejecuto el servidor, y luego trato de ejecutarlo de nuevo, me dice que el puerto está siendo ocupado (`OSError: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted`), por lo que estoy ocupando el siguiente metodo antes de hacer bind:` self.socket_servidor.setsockopt(socket.SOL_SOCKET,socket.SO_REUSEADDR, 1) `que al parecer reduce a cero el delay para utilizar los puertos.

2-. Volví a copiar el codigo de el contenido del curso, y tan solo le agregé lo que expliqué en el punto anterior, además de cambiar el puerto porque me dice que no tengo permiso para usarlo:
`OSError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions`. Una vez cambiado el puerto, corro servidor sin problemas, pero al ejecutar cliente me arroja esto:
`OSError: [WinError 10049] The requested address is not valid in its context`. Y la verdad ya no sé de a donde salía me error anterior.

@Hernan4444 Desactivando firewall y el antivirus stock de windows (Windows defender security system) el problema persiste.

**Comment by rfenzo** [comment]
haré un push a mi repositorio en la carpeta T06 con los archivos que estoy tratando correr

**Comment by Hernan4444** [comment]
@rfenzo te sugiero que lo hagas tal como está en la ayudantía, si te dice que el puerto está ocupado cambiaré solo el numero del puerto pero puede ser que `self.socket_servidor.setsockopt(socket.SOL_SOCKET,socket.SO_REUSEADDR, 1)` está causando error.

Saludos!!
