### ISSUE TITLE
Consulta datos que deben ir parameters.py 

### ISSUE THREAD

**Issue by mblejeune** [IIC2233/Syllabus#598]
Hola! segun entiendo de enunciado todos aquellos parametros que sean parte de mi clase simulacion deben ir en parametros, por tanto, si yo tengo otro modulo donde defino las clases Cliente, Empleado, etc, este archivo.py con las clases de las entidades también debe cumplir que no contenga números como tal ( 0, 1, etc ), es decir, para los casos donde defino algun numero random no puedo usar random(1, 17) sino que debo usar random(one, seventeen) y estos numeros definirlos en parameters.py también? o solo aplica para parametros en la simulación como clase simulación ( ese archivo.py)

**Comment by Hernan4444** [comment]
Hola, **todo parametro** del enunciado debe ir en el archivo que les pedimos, aunque esos parámetros estén en distintos módulos, eso fue modulación tuya. Tanto los Clientes, como Empleados, atracciones, etc cuentan con parámetros que también queremos editar. Los únicos datos numéricos que pueden permanecer en tu código son los implementados por ti para hacer un calculo adicional (como 1 y 17 que dijiste), pero si un número se menciona en el enunciado, entonces va en parameter.py

**Comment by mblejeune** [comment]
Buenisima! en ese caso contadores que use también puedo usar numérico según entendi ! muchas muchas gracias!!!
