### ISSUE TITLE
libpng error: [22]IHD: invalid chunk type

### ISSUE THREAD

**Issue by matumartinez** [IIC2233/syllabus#598]
Hola,

Me ocurre el error "libpng error: [22]IHD: invalid chunk type" después de aplicar el filtro dibujo. Puedo guardar la imagen como png, pero está corrupta y no se puede leer. Necesito ayuda para encontrar que error tuve.

Saludos y gracias de antemano

**Comment by jeschuwirth** [comment]
Hola,

Voy a revisar el código que acabas de subir a github, te aviso cualquier cosa.

**Comment by matumartinez** [comment]
Hola,

Acabo de arreglar el error, pero ahora me aparece este: libpng error: bad adaptive filter value.

**Comment by jeschuwirth** [comment]
Tengo un par de cosas que te van a ayudar.

Primero que nada guardas la foto filtrada como filtro en vez de filtro.png, es importante el .png para que tu computador sepa interpretar los bytes.

Para la foto de Squirtle1.png en la issue #592 , todo tu header + el chunk_IHDR debería quedar así:
b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x02\xa7\x00\x00\x01\xb6\x08\x02\x00\x00\x00\xcd\xe5\xb8\xf0'

Por alguna razón el ancho y alto de tu foto (los que ocupas en for numero in bytes_4:) me dan 2 y 302690 respectivamente, quizas por ahí encuentres un error.

En la noche te puedo seguir ayudando, pero por ahora espero que esto te sirva.
