### ISSUE TITLE
.gitignore desde mac

### ISSUE THREAD

**Issue by maggiemunoz** [IIC2233/syllabus#598]
hola no logro hacer el git ignore ya que esta como archivo oculto y no se que hacer :(

**Comment by JosefaPaz** [comment]
Hola @maggiemunoz !

Para ver los archivos ocultos en un mac debes usar los comandos `cmd + shift + .` Ahí deberías poder visualizarlo y editarlo con un editor de texto.

Éxito!

**Comment by maggiemunoz** [comment]
hola! no se que hago mal pero no pasa nada cuando hago eso :(

**Comment by JosefaPaz** [comment]
@maggiemunoz  me faltó mencionar que debes apretar este comando en la carpeta donde se supone está el .gitignore oculto 😅 .

Avisame si ahí funciona!

**Comment by maggiemunoz** [comment]
aun asi no me sirve :((

**Comment by JosefaPaz** [comment]
@maggiemunoz , intenta desde la consola, estando en la carpeta escribir `open .gitignore`, y ahí debería abrirse el archivo. Si esto no pasa, intenta abrirlo desde el editor de código, ya que ahí debería aparecerte. Si nada de esto funciona, es porque el archivo no existe en tu carpeta y lo más recomendable es que lo crees nuevamente 😄

**Comment by maggiemunoz** [comment]
sii con open me funciona, el tema es que lo tengo en el syllabus y no en mi repositorio, y no se como moverlo si no lo veo jajajaj

**Comment by JosefaPaz** [comment]
@maggiemunoz lo más fácil es que crees el archivo en tu carpeta de la T01, añadas todo lo que debería contener el .gitignore, y guardes el archivo como ".gitignore". Creo que esto se facilitaría más que copiarlo desde el syllabus

**Comment by maggiemunoz** [comment]
ahi encontre la forma de ponerlo en la carpeta, esperemos que funcione jajaj gracias! (con escribir *.csv y *.pdf al final del archivo deberia funcionar verdad?)

**Comment by JosefaPaz** [comment]
@maggiemunoz  sí :) y si te llega a dar error esto, escribe manualmente cada archivo que deseas ignorar.

Éxito 😸

**Comment by maggiemunoz** [comment]
hola!! una ultima pregunta, como hago para que se use el git ignore al momento de pushear? porque si le hago git add a cada archivo individualmente ahi no lo estoy usando verdad?

**Comment by JosefaPaz** [comment]
@maggiemunoz si estás subiendo los archivos y además tienes subido o estás subiendo el .gitignore a la carpeta, sí estaría usándolo, ya que el archivo de .gitignore le indicaría a la consola que no se deben subir los archivos que este indica

**Comment by maggiemunoz** [comment]
pero hago un git add general? onda esta mal subir archivo por archivo?

**Comment by JosefaPaz** [comment]
@maggiemunoz no está mal! puedes hacerlo como más te acomode, subirlo archivo por archivo o hacer el git add general, pero primero sube el .gitignore para que se ignoren los archivos que se muestran en él. (enunciado, csv, etcétera)
