### ISSUE TITLE
Errores en PyQt5

### ISSUE THREAD

**Issue by Hernan4444** [IIC2233/Syllabus#598]
¿Cansado de caídas de PyQt5 sin saber el error? Evita utilizar mucho de try/except o de print para saber tu error con el siguiente código:

```
if __name__ == '__main__':
    def hook(type, value, traceback):
        print(type)
        print(traceback)
    sys.__excepthook__ = hook

    app = QtWidgets.QApplication([])
    mi_juego = MiJuego(*args)
    mi_juego.show()
    app.exec()
```
Implementa el siguiente código en tu main antes de instanciar tu backend o frontend y ya no se caerá tu programa.

Código de cortesía de @MainScientist

**Comment by IchottMano** [comment]
@Hernan4444 a pesar de que tengo eso puesto (y sirve en muchas ocasiones), me encuentro con que mi programa se cae y el único mensaje que aparece es:
Process finished with exit code -1073741819 (0xC0000005)
Lo cual sucede cuando muere un enemigo, busqué en internet un buen rato y no logré encontrar una solución ni una causa concreta a este problema, ni tampoco el que no aparezca la causa.

**Comment by Hernan4444** [comment]
@IchottMano en ese caso, si tienes pycharm (no sé si otros editores tienen), puedes utilizar el modo `debug` para analizar que pasa en la interfaz y ahí podría salir más detalle del error.

**Comment by IchottMano** [comment]
@Hernan4444 no me funciono mucho hacer eso... Sin embargo modifique algunas (muchas) funciones y el programa ya no se cae.
Muchas gracias de todos modos!
