### ISSUE TITLE
gitignore desde un subdirectorio

### ISSUE THREAD

**Issue by furzuadr** [IIC2233/syllabus#599]
Hola! estaba tratando de usar mi .gitignore para ignorar archivos dentro de un subdirectorio, pero no he podido. Cómo se hace?
Por ejemplo, tengo un archivo archivo.png dentro de client, cómo hago para no subir sólo ese archivo? No funciona poner client/archivo.png

Gracias!

**Comment by jeschuwirth** [comment]
Hola,

Utilizar client/archivo.png debería funcionar, si tienes problemas intenta mover el archivo.png a tu escritorio, hacer un "git rm client/archivo.png" hacer commit y pushear, duespués puede colocar el archivo de vuelta en la carpeta client. 

De ese modo vas a quitar el archivo de tu repositorio y no se debería subir de nuevo debido al .gitignore

Avisa si no funciona para encontrar el problema 😄 , exito en la tarea!
