### ISSUE TITLE
Salas

### ISSUE THREAD

**Issue by tcgarrido** [IIC2233/Syllabus#599]
Hola! se supone que tengo que hacer mi código con X salas y canciones, pero uds corregirán con otras, entonces mi duda es como adaptar el código a eso. La idea es que el programa setee las salas y sus canciones usando os? o nos pasaran un json con las salas y sus canciones? No se si se entiende :3

**Comment by hanavarrete** [comment]
![captura](https://user-images.githubusercontent.com/20782545/27005391-bd85e348-4deb-11e7-995d-b6fd1246cde1.PNG)
Hola! en el enunciado dice como.  Se entregarán carpetas con el nombre de las salas y sus respectivas canciones, por lo que podrían haber N salas. Tu tienes que ver como manejar esta información para crear la cantidad correspondiente. Saludos!

**Comment by tcgarrido** [comment]
Graciasss!

**Comment by malopez16** [comment]
Estimados, después de leer el enunciado muchas veces y de mandar algunas issues para confirmar que lo estaba entendiendo bien y no se produjeran ambiguedades (#591, #597) nunca me percaté de que se planteaba que la interfaz debía ser dinámica c/r a el numero de carpetas en el directorio de géneros sería variable.
En todo momento he estado escribiendo el código suponiendo que la cantidad de géneros no variaría (aunque la cantidad de canciones en cada género sí podría variar, agregándolas a cada carpeta). Probáblemente otros también asumen esto. 
  Debo entonces cambiar todo de manera que la interfaz sea dinámica? En tal caso considero que sería pertinente hacer un anuncio formal o una edición al enunciado para que quede claro.

**Comment by rpalmaotero** [comment]
@malopez16 el enunciado es claro al respecto. De todas maneras se va a agregar el label Importante para que no quede duda alguna. Debes considerar que el número de salas es dinámico.

**Comment by malopez16** [comment]
Gracias. Lo corregiré entonces :)
