### ISSUE TITLE
estadísticas Limpiadores y Técnicos

### ISSUE THREAD

**Issue by santilaguna** [IIC2233/Syllabus#599]
Hola!
En el enunciado se pide que en las estadísticas se muestre lo siguiente:
 el promedio de llamados totales a hacer aseo y reparación por Limpiador y Técnico respectivamente.
 Con lo anterior, no me queda claro si cada técnico y cada limpiador debe entregar su promedio de reparaciones totales o si se deben entregar dos promedios de llamados, uno para limpiadores y otro para técnicos.
Saludos!

**Comment by Hernan4444** [comment]
@santilaguna queda a tu criterio, puedes entregar los 2 valores en 1 línea como: "Limpiador X y Tecnico Y" o como el total: "Limpiador y tecnico: Z" donde X, Y, y Z son los resultados.

**Comment by sjkinast** [comment]
El promedio es el numero de llamados por día ?

**Comment by Hernan4444** [comment]
@sjkinast si.
Saludos ✌️
