### ISSUE TITLE
Problema con actualización de QProgressBar

### ISSUE THREAD

**Issue by raibd** [IIC2233/syllabus#599]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, por alguna razon aunque fijé el limite del ProgressBar con _QProgressBar.setMaximum(max)_ y después cambie el valor con  _QProgressBar.setValue()_, esta siempre empieza de 100. Además, cuando imprimo el valor con _QProgressBar.value()_ a medida que pasa el tiempo, este respeta el maximo que fije anteriormente e imprime el tiempo correcto, sin embargo, el "display" no. Por qué puede estar ocurriendo esto?

Gracias de antemano

**Comment by JadrinaDA** [comment]
Hola! La barra está empezando en 100 porque el valor es leído en porcentaje, y 60 es 100% de 60. Si modificas el máximo valor a 100 veras que ahí se mostraran los valores correctos. Podrías hacer un progress bar y un label separado para tener el valor del tiempo correcto y que la progress bar parte de estar llena. Avísame si tienes más dudas, éxito!
