### ISSUE TITLE
error gitpush 

### ISSUE THREAD

**Issue by Pedrowach** [IIC2233/syllabus#599]
![image](https://user-images.githubusercontent.com/61996021/79798981-c4fb7b00-8327-11ea-9f85-4d2e2b6bd840.png)
ayuda al hacer git push me sale eso y no me sube nada al repositorio!!!!

**Comment by JosefaPaz** [comment]
@Pedrowach ,

Este error se debe a que tu repositorio en git tiene cambios / es diferente al repositorio local de tu computador. Intenta hacer git status para ver qué te recomienda hacer, haz git pull para bajar a tu pc los archivos que cambiaste  y después deberías poder subir todo.

Quedo atenta!

**Comment by Pedrowach** [comment]
perfecto , gracias!, ya no me sale el error ,pero ahora tengo subidos los archivos ya que el gitignote no me funciono, como elimino esos archivos del repositorio? y como utilizar bien el gitignore ( solo me ignoro el __pycache__). Adjunto pantallaso con lo que tengo dentro del gitignore 
![image](https://user-images.githubusercontent.com/61996021/79800510-5835b000-832a-11ea-806b-4a95596a48e5.png)

**Comment by JosefaPaz** [comment]
@Pedrowach , Tendrías que eliminarlos desde el repositorio de github, y luego intentar subirlos nuevamente con el .gitignore (quizá no te funcionó ya que debe estar escrito como ".gitignore" y no "*.gitignore" -sin el asterisco) 👀

**Comment by Pedrowach** [comment]
No me funciona  el gitignore (sin asterisco), nose que más hacer :(

**Comment by JosefaPaz** [comment]
@Pedrowach y si escribes cada archivo .csv, sin agregarlos todos con el *.csv, te los ignora? 👀

**Comment by Pedrowach** [comment]
ahi me funciono!! alfin :) , gracias!
