### ISSUE TITLE
Bonus Foto de perfil

### ISSUE THREAD

**Issue by bahidalgo** [IIC2233/syllabus#599]
Hola!

Mi ventana principal posee:
**1)** nombre de usuario
**2)** cantidad de amigos del usuario
**3)** Un cuadro con la imagen de su personaje

Según entiendo, al implementar el bonus _foto de perfil_, se debe agregar un cuadro extra **sin** reemplazar la imagen que posee el cuadro del personaje, ¿Estoy en lo correcto? O, por el contrario, la imagen del personaje es considerada una foto de perfil, por ende, al subir otra, esta se reemplaza.

Gracias!

**Comment by bahidalgo** [comment]
Sobre esto mismo, ¿puedo modificar el archivo usuarios.json para agregar una nueva llave al usuario correspondiente con la nueva ruta de su foto de perfil? ¿O es preferible crear otro archivo.json?

**Comment by lily416** [comment]
Como dices, en caso de implementar el bonus de Foto de perfil la ventana debe contener las siguientes cosas:
1. Nombre de usuario
1. Cantidad de amigos del usuario
1. Imagen del personaje del usuario
1. Foto de perfil del usuario

Los 4 elementos deben verse correctamente, sin sobreponer alguno de los otros.

---

Con respecto a cómo guardar la información tienes dos opciones:
1. Guardar en un nuevo archivo (i.e. `foto_perfil_usuario.json`), o
1. Guardar en el mismo archivo `usuarios.json`.

En caso de que lo hagas de la primera forma, deberás indicar en tu readme que se debe crear el archivo o tu programa deberá manejar el caso de que este no exista.

En caso de que modifiques el archivo `usuarios.json`, tu programa deberá funcionar correctamente con el archivo original que les pasamos, es decir, con usuarios que no contengan una variable que indique su foto de perfil.


Saludos y éxito en la tarea 👋🐧
