### ISSUE TITLE
IMPORTANTE: QTimers / QThreads

### ISSUE THREAD

**Issue by hanavarrete** [IIC2233/Syllabus#599]
Hola! Para guiarlos un poco en el manejo de distintos eventos de manera asíncrona les dejo esta issue creada hace unos semestres que aclara el uso y diferencias de los QThreads y QTimers (cortesía de @fgvenegas)

### QThreads:
Los Qthreads siguen el mismo comportamiento que los Threads que fueron enseñados en el ramo, por lo que no debería presentarles mayor complicación aplicarlos en su tarea. Pero qué pasa si queremos utilizarlos para una acción que sabemos que se va a repetir constantemente ? Podríamos implementar algo así en el Qthread
```python
def run(self):
    while True:
        # Lo que quiero que el QThread haga en cada iteración
        time.sleep(0.1) # Muy importante para que su interfaz no se quede pegada, el valor es ajustable
```
* ¿Con esto que tenemos ?: Un QThread que repite una acción una y otra vez.
* ¿Problemas?: Si.
* ¿Cuáles? ¿Cómo detenemos este Qthread?
En general detener (matar) un thread es una [mala practica](https://stackoverflow.com/questions/323972/is-there-any-way-to-kill-a-thread-in-python), la idea es que un Thread se inicie, cumpla su objetivo y muera al terminarlo, no que lo tengamos que detener por nuestra cuenta (mas detalles en el link, es interesante y útil)
Entonces siguiendo esta misma lógica estamos abusando del run del Qthread con un vacío legal.
* ¿Puedo detenerlo con break ? Si, hay casos donde alumnos usan Qthreads en toda su tarea y no tienen problemas, como experiencia propia, empezar a matar Qthreads a diestra y siniestra con este método no escalo bien.

### Qtimers
Otra forma de realizar lo que hacíamos con Qthreads es con Qtimers.
* ¿Cuál es la ventaja que tienen estos sobre Qthreads?:
Qtimers está pensado para que se repita una y otra vez lo que contiene su run sin necesidad de utilizar un while, recibe como parámetro al inicializarlo el tiempo cada cuanto se debe ejecutar y además posee un método stop para poder detenerlo "legalmente". Si, se ve más limpio en general que usar Qthreads, pero no asegura que su programa vaya a ser perfecto ni vaya a sufrir problemas de lag o caídas de interfaz, eso ya va en la programación de cada uno.

## Recomendación final
Son libres de usar ambos en sus tareas, los 2 son útiles y pueden tener una tarea 100% funcional ya sea con uno, el otro o ambos. Por ejemplo para objetos que existan en muchas cantidades y sea difícil controlar cuando interrumpirlos puede ser más útil utilizar un Qtimer con ellos, pero para objetos que permanecen constantes en el escenario o que son más fáciles de controlar un Qthread es una buena opción.
Experimenten ! Vean con cual les anda mejor, con cual es mas eficiente su tarea y averigüen mas por su cuenta, siempre es útil leer un poco antes de lanzarse a usarlo algo, y no olviden siempre comentar en el README este tipo de decisiones y porque escogieron lo que escogieron.

**Comment by jvlara** [comment]
Hola, tengo una duda sobre los Qthreads, ¿Cual es la mejor de manera de pausarlos por un tiempo indefinido? debido a que buscando en google y en la documentacion no logre encontrar algo que me sirviera :c.

**Comment by fringlesinthestreet** [comment]
@jvlara Hola :)

A mí (cuando lo di) me sirvió este [link](https://stackoverflow.com/questions/33640283/python-thread-that-i-can-pause-and-resume)
