### ISSUE TITLE
Salir del programa

### ISSUE THREAD

**Issue by diego-ayala-2000** [IIC2233/syllabus#599]
Al momento que el jugador seleccione salir del programa se debe hacer algo especial, o simplemente que no se sigan ejecutando lineas de codigo?

**Comment by retamalcito** [comment]
¡Hola @diego-ayala-2000!

Si el enunciado no especifica nada, la opción **Salir del programa** debe simplemente detener la ejecución de este, sin hacer nada adicional.

¡Saludos! 👋

**Comment by diego-ayala-2000** [comment]
Gracias por la ayuda, me podrías especificar un poco más a que se refiere detener la ejecución y como se puede hacer?

**Comment by retamalcito** [comment]
¡Hola de nuevo!

Detener la ejecución de un programa es justamente eso, forzar al programa a detenerse. Es lo que ocurre, por ejemplo, cuando se levanta una excepción y no es atrapada; el programa deja de funcionar y detiene toda rutina que haya estado realizando.
En cuanto a tu segunda pregunta, la mejor forma de detener la ejecución de un programa (y la más simple) es utilizando el método `exit()` de la librería `sys`. Te invito a investigar por tu cuenta como funciona (para decirte más de lo que ya te dije :eyes:), pero no te preocupes, es sumamente simple. :smile:

¡Éxito! :sparkles:

**Comment by diego-ayala-2000** [comment]
Bacan, muchas gracias por la ayuda
