### ISSUE TITLE
En la base de usuarios hay un user que no es alfanumérico

### ISSUE THREAD

**Issue by Jairuru** [IIC2233/syllabus#6]
Solo aviso uwu

Saludos :)

**Comment by bimartinez** [comment]
@Jairuru gracias por avisarnos!

El detalle está corregido, por favor hagan *pull* del *Syllabus* nuevamente.

Saludos!

**Comment by Jairuru** [comment]
Falta cambiar los otros archivos, que quedaron con el nombre con guión.

Saludos n.n

**Comment by lily416** [comment]
@Jairuru se acaban de actualizar los archivos, si encuentras algún otro error (esperemos que ya no queden 😭) por favor avísanos. 😉 

Saludos y éxito en la tarea 👋🐦
