### ISSUE TITLE
Descarga de Python 3.6

### ISSUE THREAD

**Issue by mnzegpi** [IIC2233/Syllabus#6]
Hola, tengo un netbook con sistema operativo windows 7. Descargué Python 3.6.2 pero cada vez que intento abrir el IDLE aparece un mensaje de error que dice:

"Error del sistema: El programa no puede iniciarse porque falta api-ms-win-crt-runtime-l1-1-0.dll en el equipo. Intente reinstalar el programa para corregir este problema."

Reinstalé el programa pero apareció el mismo mensaje otra vez. Descargué otras versiones de Python 3.6 pero sigue pasando ¿qué hago?

**Comment by jnlarrain** [comment]
@mnzegpi tuve el mismo problema y desintale el programa y todas sus versiones que tenia en el computador, luego baje de nuevo el archivo de instalacion y me funciono.

**Comment by mnzegpi** [comment]
Hola, no, no funciona nada de eso. Busqué qué significa api-ms-win-crt-runtime-l1-1-0.dll en google y dice que hay que actualizar una cosa o algo así, no tengo idea, ya no sé qué hacer. Gracias de todas formas

**Comment by jnlarrain** [comment]
@mnzegpi probaste tambien con reinstalando o actualizando Microsoft Visual C++??
mira esto https://github.com/winpython/winpython/issues/245
igual aqui esta el link de descarga directa, dime que hiciste para buscar otra solucion osino

**Comment by mnzegpi** [comment]
ya, estoy intentando instalar Microsoft Visual C++, pero después de ejecutarlo cuando la barra de descarga llega al final aparece un mensaje que dice que la instalación no se pudo completar porque existe otra actualización en curso y tengo que solucionarlo para poder continuar; o sino se queda pegado y no aparece ningún mensaje. Pero parece que no tengo ninguna actualización en curso, no estoy intentando instalar ninguna otra cosa

**Comment by ifcarrera** [comment]
Hola, pero puedes correr un archivo .py desde la terminal o ni siquiera eso te deja hacer?
Saludos

**Comment by mnzegpi** [comment]
Hola, no me deja hacer eso, no puedo abrir nada relacionado con python, en todos los casos aparece ese mensaje sobre api-ms-win-crt-runtime-l1-1-0.dll

**Comment by jtagle2** [comment]
@mnzegpi, te funcionó?
Si aún no lo logras (lo que te dijo @jnlarrain no te funcionó), puedes hacerlo a la "mala" (Algunos recomiendan no hacerlo así, porque puede ser que el problema venga de algo más general en la instalación de frameworks de windows).


Ver el problema
---
Primero, para asegurarme que el problema es lo que creo. Anda a la carpeta C:\Windows\System32, y revisa si el archivo que te pide efectivamente no está ahí.
Luego en inicio, busca el mismo archivo, y asegúrate que no está. Si al buscarlo lo encuentras (cosa que dudo), guárdalo en la carpeta antes mencionada.

Posibles Soluciones
---

*1.- Hacerlo "a la mala"*
Descargar el archivo que te falta, ponerlo en C:\Windows\System32 y ver si funciona. Algunos no recomiendan hacer esto, porque los dll incluyen funcionalidades que utilizarán muchas aplicaciones, por lo que podría ser inseguro. Yo una vez instalé un archivo .dll de esta forma hace 1 año, y no me ha pasado nada grave. (mis cuentas bancarias siguen igual, y nadie se ha metido a mi mail). 

*2.- Hacerlo "a la buena" (?)*
Hay softwares que puedes descargar, que te revisa el estado de tu computador, y entre sus funcionalidades está ver el estado de los archivos .dll. La segunda opción es que te descargues uno de estos, lo compres, y luego le pidas al programa que te instale el archivo. De esto no te podría ayudar mucho, porque nunca he usado uno.

Saludos! 

PD: Si esto aún no te funciona, podemos verlo después de la ayudantía de la sala B18, para ver si encontramos el problema.
