### ISSUE TITLE
Privacidad de los repositorios

### ISSUE THREAD

**Issue by pggodoy** [IIC2233/Syllabus#6]
Hola!
En la pagina del Syllabus al apretar IIC2233 aparecen mi repo con el tag "Private", el Syllabus,  contenidos y los repos de flobarrios y fvr. No creo que esto sea normal.

**Comment by bamavrakis** [comment]
Ups, esos eran repos de prueba (estabamos probando el registro :P). Ahora no deberías poder verlos!
Saludos :D
