### ISSUE TITLE
Consulta Actividad Sumativa

### ISSUE THREAD

**Issue by etoteiza** [IIC2233/syllabus#6]
Hola!
Se puede usar el material durante una actividad sumativa, por ejemplo, para ver los métodos que puedan tener una clase?.
Gracias!

**Comment by Arcoirisky** [comment]
Hola!

No se prohíbe ver el material durante el desarrollo de las actividades :D La idea es que lo estudien antes para que puedan aprovechar todo el tiempo en hacer la actividad más que en entender lo que se está pidiendo :D
