### ISSUE TITLE
Uso de Anaconda

### ISSUE THREAD

**Issue by totoiii** [IIC2233/syllabus#6]
![WhatsApp Image 2020-08-13 at 10 16 21 AM](https://user-images.githubusercontent.com/69605379/90145603-1784fb00-dd4e-11ea-86c7-5d2c8ca74f02.jpeg)

Hola! Vi en las instrucciones que recomendaban no instalar anaconda para este curso, pero yo ya lo tengo instalado por razones personales y ya me acostumbré a este formato, me gustaría saber por qué recomiendan con tanta vehemencia el que no lo instalemos o que lo desinstalemos, ya que veo y anaconda ya viene por ejemplo con jupyter y con vs code preinstalados.  Se me hizo mucho mas facil la instalacion de los programas y no le veo falla alguna, no he tenido problemas a la hora de estudiar la materia.

**Comment by igbasly** [comment]
Hola @totoiii :v:

En general no recomendamos anaconda por las implicancias que esto trae, no es que sea algo malo, pero puede generar problemas en el futuro, sobre todo si continuas en el área de la computación.
Me explico, anaconda genera su propio ambiente para instalar los software y paquetes asociados, usualmente cuando los instalas directamente quedan en el directorio general de tu computador y son fácilmente reconocibles y accesibles por otros programas, lo que con anaconda puede llegar a complicarse.

El ejemplo más común sería, no sé como tienes instalado Python, pero si lo tuvieras instalado por anaconda y al mismo tiempo directamente en el computador, al utilizar `pip install alguna_libreria` sin saber cómo está configurado tu PATH de python es posible que se instale en la versión de anaconda en vez de la versión del sistema que utilizas, lo que se vería reflejado como que no se ha instalado.

Te digo esto, ya que la experiencia nos ha mostrado que anaconda suele producir errores tarde o temprano principalmente con las versiones de Python. Por lo mismo, como equipo docente no te podemos prohibir usarlo, pero tampoco te podemos asegurar que si un problema así surge, lo podamos resolver a tiempo para alguna entrega.

No dudes en preguntarnos cualquier duda o problema que surja, saludos 😄.
