### ISSUE TITLE
Problemas con "brew install git" 

### ISSUE THREAD

**Issue by luzmagurzua** [IIC2233/syllabus#6]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

Hola, me sale esto cuando trato de ejecutar
![Captura de Pantalla 2021-03-17 a la(s) 21 14 47](https://user-images.githubusercontent.com/80796978/111554817-d3375e80-8765-11eb-98ba-64f8069740e2.png)
 "brew install git" 
a qué se deberá? 

Gracias desde ya.

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by igbasly** [comment]
Hola Luz! :v:

Ok, viendo el error que aparece, podría pensar que aparentemente no está instalado `brew` en tu computador. Pero también puede ocurrir que el PATH de la terminal bash no este correctamente configurado, por lo cual no reconoce el comando pese a estar instalado 😅.

Para poder descartar esta última opción y no instalar cosas demás, te voy a pedir que intentes ejecutar un comando y me comentes de vuelta lo que te indica el sistema. :ok_hand:

Por favor ejecuta el comando:
`echo $PATH`

Quedo atento a tu respuesta :smile:

**Comment by luzmagurzua** [comment]
Hola, gracias por tu respuesta. Me apareció lo siguiente: 
![Captura de Pantalla 2021-03-18 a la(s) 11 07 08](https://user-images.githubusercontent.com/80796978/111639562-1fbc8180-87da-11eb-92a2-29c539dd7495.png)

**Comment by igbasly** [comment]
Gracias @luzmagurzua :smile:

Por lo visto, el PATH está bien configurado, por lo tanto, lo más probable es que no tengas brea instalado. Dicho eso, como estas intentando utilizarlo para instalar git, podríamos verificar si git ya está instalado primero. Eso porque MacOS trae git por defecto.

Compruébalo ejecutando el comando `git --version`. Si no ocurre un error como el anterior `command not found` y aparece una versión de git, entonces todo bien :+1: y pueden continuar tranquila con el curso, ya tienes git.

Si no, entonces puedes instalar brew con las instrucciones indicadas en el [sitio oficial](https://brew.sh).

Quedo atento a cualquier comentario 🙌 .

**Comment by luzmagurzua** [comment]
No me salió ningún error. Muchas gracias por tu ayuda, te pasaste !
