### ISSUE TITLE
Problema de configuración de Git

### ISSUE THREAD

**Issue by vale1206** [IIC2233/Syllabus#6]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.

### Problema

En la configuration de git entre por error mas de un comando user.name y se me guardaron mas variables en eso y necesito ayuda para mantenerla en 1. Me sale que el problema es warning: user.name has multiple values. Mi equipo es un mac. 
 Ahi va la imagen de como se ve (https://user-images.githubusercontent.com/127348279/224191843-39da3fcf-5a9c-4e26-9863-cec6d7b0ebe8.png).

(RESUELTO)

**Comment by Hernan4444** [comment]
Hola @vale1206,

Busqué cómo eliminar variables de `git config` y encontré [estos pasos](https://stackoverflow.com/a/50202011). Con esto deberías poder eliminar las variables e ingresar la que corresponde 😄. 

Cuentanos cómo te va con esa opción en relación a esa respuesta (o si te sirvió otra de ese post en stackoverflow).
Saludos c:

**Comment by vale1206** [comment]
Gracias! ahi logré configurarlo bien.
