### ISSUE TITLE
Problema del archivo parametros.py con mi interpretador

### ISSUE THREAD

**Issue by Alonsinho1** [IIC2233/syllabus#6]
Hola tengo un problema en como funciona el archivo parametros.py con mi interpretador

Estoy usando el siguiente codigo

<img width="272" alt="Captura de pantalla 2019-08-10 a la(s) 20 25 44" src="https://user-images.githubusercontent.com/53799932/62828149-18200a00-bbad-11e9-8af9-fe87095cf674.png">
<img width="166" alt="Captura de pantalla 2019-08-10 a la(s) 20 25 50" src="https://user-images.githubusercontent.com/53799932/62828150-1a826400-bbad-11e9-9ab4-d4999e9ecff5.png">

Esto se debe a que en el archivo original se define PROB_LEGO como 10/64 y no como 10.0/64.0. Entonces la division da un resultado en su forma entera. Existe una forma de arreglar ese problema sin tener que cambiar la definicion de parametros a 10.0/64.0. Estoy usando sublime text 3 con los siguientes packages
<img width="200" alt="Captura de pantalla 2019-08-10 a la(s) 20 25 19" src="https://user-images.githubusercontent.com/53799932/62828141-ff175900-bbac-11e9-945e-95c4a281dfe2.png">

Otra consulta se centra en que si debemos instalar los modulos a PYTHONPATH o simplemente los podemos colocar en la mismo ubicación que el archivo donde estamos realizando la tarea

Muchisimas gracias

**Comment by Arcoirisky** [comment]
Hola~ ¿Que sucede si imprimes float(parametros.PROB_LEGO)? Se me ocurre que podría ser configuración aunque nunca he usado sublime, solo Pycharm o VSCode

**Comment by Alonsinho1** [comment]
sigue tirando 0 ya que se define que 10/64 es 0. Osea al poner float estoy basicamente haciendo
float(0).

Tuve problemas para lograr funcionar vs code correctamente en mi computador y pycharm me recomendaron no utilizarlo :c

**Comment by jmwielandt** [comment]
Hola!

Ese problema es bastante extraño 👀. ¿Puedes hacer las siguientes cosas y decirnos qué pasa, como para acotar un poco el problema? Y por saber, ¿qué sistema operativo estás usando?

0. ¿Qué versión de python estás ejecutando? Quzás estás con python 2.7 en lugar de 3.7.
1. Pon un print en parametros.py de PROB_LEGO, luego de definirlo. Esto nos puede dar una pista de si el problema está al importar el módulo o al declarar la variable. Y ejecútalo como normalmente lo harías.
2. Ejecuta esto ahora desde la línea de comandos, para saber si tiene que ver con sublime al intentar correr el archivo o si tiene que ver con la versión de python instalada.
3. Desinstala anaconda, desinstala python, borra todos los archivos de la instalación de python de tu computador, todos los archivos de la instalación de anaconda, reinstala python **sin anaconda** y haz todo de nuevo. El uso de anaconda para el curso, al igual que el de pycharm, está completamente desaconsejado para este curso debido a múltiples problemas que han causado a lo largo de muchos semestres.

Cuéntanos cualquier cosa,
Saludos! 😄

**Comment by JuaniAndres** [comment]
> Hola!
> 
> Ese problema es bastante extraño 👀. ¿Puedes hacer las siguientes cosas y decirnos qué pasa, como para acotar un poco el problema? Y por saber, ¿qué sistema operativo estás usando?
> 
> 1. ¿Qué versión de python estás ejecutando? Quzás estás con python 2.7 en lugar de 3.7.
> 2. Pon un print en parametros.py de PROB_LEGO, luego de definirlo. Esto nos puede dar una pista de si el problema está al importar el módulo o al declarar la variable. Y ejecútalo como normalmente lo harías.
> 3. Ejecuta esto ahora desde la línea de comandos, para saber si tiene que ver con sublime al intentar correr el archivo o si tiene que ver con la versión de python instalada.
> 4. Desinstala anaconda, desinstala python, borra todos los archivos de la instalación de python de tu computador, todos los archivos de la instalación de anaconda, reinstala python **sin anaconda** y haz todo de nuevo. El uso de anaconda para el curso, al igual que el de pycharm, está completamente desaconsejado para este curso debido a múltiples problemas que han causado a lo largo de muchos semestres.
> 
> Cuéntanos cualquier cosa,
> Saludos! 😄

Hola con respecto a pycharm que problemas han tenido en otros semestres?
Es porque estoy un poco acostumbrado a ocuparlo y es para tener cuidado de no cometerlos
gracias de antemano

**Comment by Alonsinho1** [comment]
hice las recomendaciones y el problema aprece en sublime. sin embargo no puedo configurar bien vs studio en mi computador hay algun tutorial? ( los que he encontrado duran 1 hora o simplemente no me sirven)

No tengo anacconda instalada el que aparece en el menu de sublime es otro por lo que tengo etendido

**Comment by Arcoirisky** [comment]
@JuaniAndres yo ocupo Pycharm desde tiempos inmemorables y nunca me ha dado problemas, solo que a veces la gente se confunde e instala las librerías desde la consola de Pycharm causándoles problemas de configuración. Pero si no haces eso, funciona súper bien, sobretodo con Python (que básicamente es para lo que fue creado)

**Comment by JuaniAndres** [comment]
> @JuaniAndres yo ocupo Pycharm desde tiempos inmemorables y nunca me ha dado problemas, solo que a veces la gente se confunde e instala las librerías desde la consola de Pycharm causándoles problemas de configuración. Pero si no haces eso, funciona súper bien, sobretodo con Python (que básicamente es para lo que fue creado)

ya muchas gracias y si es genial Pycharm por eso seria una pena tener que cambiarme

**Comment by lily416** [comment]
@Alonsinho1, ¿probaste con el tutorial de instalación que sale en la [wiki del curso](https://iic2233.github.io/wiki/interface)?

**Comment by lisraelrat1** [comment]
Hola! me pasa el mismo problema con sublime, ya seguí los pasos indicados arriba pero al no tener anaconda  y haber descargado python versión 3.7, no sé que más puedo hacer para arreglarlo.

**Comment by aamartinez3** [comment]
Mismo problema acá
