### ISSUE TITLE
Sobre el readme.md

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#60]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

**Comment by Juampisaez** [comment]
Hola @fernandosmither 
- En principio solo deberían ser para las tareas, se entregan dos o tres dias despues de la entrega de la tarea (aparece en los enunciados). 
- En el caso de las actividades, por lo que tengo entendido no. Sin embargo, te aconcejo revisar los enunciados de las actividades por si te piden hacer un readme. De igual manera, los ayudantes siempre agradecemos un readme que describa tu trabajo.

Quedo atento si tienes dudas :)
