### ISSUE TITLE
Ejercicio 2.1 revolver cartas

### ISSUE THREAD

**Issue by kalarconvl** [IIC2233/syllabus#60]
Hola! En el ejercicio propuesto en la función repartir cartas sale que hay que barajar las cartas, para esto recomiendan usar alguna función importando random o las cambiamos de lugar con un sort? Y son solo 2 jugadores no? Entonces de las 100 cartas solo hay que repartir 10 (5 c/u)?

**Comment by igbasly** [comment]
Hola @kalarconvl :v:

Para barajar las cartas puedes usar el método que estimes conveniente, la librería `random` posee algunos métodos para iterables (listas) que te pueden ser útil. OJO 👀 que `sort` ordena de forma ascendente las listas y acá se busca desordenarlas.

Quedo atento a cualquier duda :smile:.

**Comment by kalarconvl** [comment]
@igbasly ahí encontré una función de random para desordenar los elementos de una lista, gracias!

**Comment by sreitze** [comment]
Hola!, respecto a este tema, quería saber si las cartas se deben repartir a ambos jugadores dentro de la misma función, o si se usa la función como instancia aparte para cada jugador. Gracias

**Comment by igbasly** [comment]
Hola @sreitze :smile:

Considerando que todo sucede dentro de la clase `Juego` y que el método `repartir_cartas` no recibe argumentos para diferenciar el jugador, se puede asumir que la repartición ocurre para ambos jugadores dentro de dicho método. De todas formas, recuerda considerar que se deben repartir las cartas **una a la vez** y no las 5 seguidas para cada jugador.

Saludos y éxito 🙌
