### ISSUE TITLE
Duda bonus Regla 5 y accion revisar solucion

### ISSUE THREAD

**Issue by SantiagoDLCB** [IIC2233/Syllabus#60]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/21)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/20)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

El bonus Regla 5 dice que un tablero solucion es valido si es que no hay celdas vacias desconectas o islas. Se te pide considerar eso para la accion 'Validar Tablero' y  'Solucionar Tablero' pero nada con respecto a 'Revisar Solución'. 

**¿Se debe incluir la regla 5 para la accion 'Revisar Solucion'?**. Y en caso de incluirse **¿Deberiamos considerar el 3x3_sol.txt como malo o no?**
Esto ultimo lo pregunto porque se nos entrega como ejemplo correcto pero contiene una isla en su solución y no existe solucion posible sin islas,por lo que si postulo al bonus y hay que considerar la regla 5 en esta accion , entonces estaria mala la solucion entregada de ejemplo. Por otra parte si no cuenta, estaria buena la solucion de tablero entregada, pero esa accion no cumpliria con la Regla 5

Actualmente yo tengo mi codigo considerando que la regla 5 no cuenta para esta acción.

**Comment by SALBUTAMOL12** [comment]
Hola @SantiagoDLCB
Con respecto a tu primera pregunta, 'Revisar Solucion' debería incluir la regla 5 para que la validación de tu solución sea completa en términos de todas las reglas, pero como requisito obligatorio para optar al bonus no va a ser exigido.

Y con respecto a la segunda pregunta 3x3_sol.txt si cumpliría la regla 5 ya que todas las celdas con bomba y vacías están conectadas de forma vertical y horizontalmente, por lo que solo debes considerar a las tortugas para la isla.
