### ISSUE TITLE
En caso de perder, ¿La partida guardada actúa como checkpoint?

### ISSUE THREAD

**Issue by ojedarcelo** [IIC2233/Syllabus#60]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola, tengo una duda con respecto a guardar y cargar partidas. Si abro una partida guardada y la pierdo, ¿La partida guardada se elimina? ¿O puedo volver a jugar desde el punto en que la guardé (como un checkpoint)?

**Comment by Emiliax16** [comment]
Hola! Dado que no se especifica en el enunciado, queda a tu elección como implementarlo, puedes eliminar la partida cargada del archivo una vez esté finalizada (perdida o ganada) o puedes dejarla y que funcione como un checkpoint. Recuerda __incluir esta implementación en tu readme__ . Saludos!
