### ISSUE TITLE
Properties en Diagrama de Clases

### ISSUE THREAD

**Issue by dmelberg** [IIC2233/syllabus#60]
Si una clase tiene una `Property`, en el diagrama de clases se pone como atributo, metodo, no se pone o ninguna de las anteriores?

**Comment by gatochico** [comment]
Hola! 

Generalmente las _properties_ se colocan en la parte de atributos. Luego, para diferenciarlas del resto de los atributos de tu clase, se les antepone un _<set/get/del>_ según cuales posea (Ej: <get/set> nombre_property).

Saludos! :cat:
