### ISSUE TITLE
Bucle con while se congela

### ISSUE THREAD

**Issue by KrishnaChaparro** [IIC2233/Syllabus#60]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Al realizar mi código aplique 3 while con condiciones boleanas (ej: a=True, while  a==True)  uno dentro del otro, al ejecutarlo, se queda congelada la consola y no se que hacer para solucionarlo, pues no se me ocurre otra manera de realizar esta parte del programa.*¿Por qué ocurre esto?*

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by admiranda** [comment]
Sin ver el código, si se queda pegada la consola debe ser que está en un loop infinito. Probaste printear algo dentro del loop y  así comprobar eso?

**Comment by Emiliax16** [comment]
Hola @KrishnaChaparro . Precisamente como dice @admiranda , si se te congela el programa es porque hay un loop que nunca termina, podría ser que nunca estableciste que `a` fuera `false` dentro del `while`, o que nunca utilizaste `break` . Ambas opciones terminarían con el loop. Si efectivamente implementaste estas opciones pero (como sería lo más lógico) dentro de condicionales (`if, elif, else`) revisa bien porqué tu programa no está entrando a la condición de término del loop, ahí debe estar el error. Saludos y suerte con el final de la tarea 😄
