### ISSUE TITLE
Duda sobre Variables Globales

### ISSUE THREAD

**Issue by gitlobo** [IIC2233/Syllabus#60]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

[Hola! Tengo una duda respecto a las variables globales, las googlié y sigo sin tener 100% de certeza a que se refieren, me podrían ayudar e indicar cuales pueden ser consideradas como tales? Muchas gracias]

**Comment by gitlobo** [comment]
Me quedó mucho más claro! Gracias!
Otra duda respecto a lo mismo... es que esas variables globales no las puedo usar en ningun modulo que yo cree? o solo aplica su *baneo* para mi archivo principal?

**Comment by Juampisaez** [comment]
Si entiendo bien, el unico lugar donde podrías usarlas como "variables globales" es el archivo parametros.py (no serian consideradas variables globales ya que deberías importar el archivo en los otros que existieran en tu programa). El concepto de variable global aplicaria a todo tu programa (sin contar el archivo que ya mencione).

**Comment by gitlobo** [comment]
Perfecto! muchas gracias :)
