### ISSUE TITLE
Error al ejecutar "python3 main.py" en la terminal

### ISSUE THREAD

**Issue by gaspar-mr05** [IIC2233/Syllabus#60]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.

Duda
Hola, primero que nada soy de windows, no de linux ni mac os. 
Tengo un problema a la hora de ejecutar archivos main.py en la cmd, tengo entendido que hay que dirigirse al directorio donde está este archivo, pero a mi me pasa que el comando "python3 main.py" me arroja un error, sin embargo con el comando "python main.py" me funciona correctamente y se ejecuta el código. El error que me aparece es el siguiente "No se encontr¾ Python; ejecuta sin argumentos para instalar desde Microsoft Store o deshabilita este acceso directo en Configuraci¾n > Administrar alias de ejecuci¾n de la aplicaci¾n.". 

Esto es extraño teniendo en cuenta que el python que ocupo es el 3.10.9 y lo instalé directamente desde la página de python, pero mas raro es que me funciona perfectamente cuando ejecuto "python main.py". Debo solucionar este error? o basta que corra con "python main.py"?

**Comment by mskdancers** [comment]
Hola! En efecto, los comandos python y python3 son básicamente equivalentes para lo que haremos en el curso, pero recuerda que si eres usuario de Windows debes tener instalado WSL y allí manejar todos tus archivos usando esta terminal, no la de Windows. Avísanos como te va con eso!
