### ISSUE TITLE
Funcionalidad 'Banco'

### ISSUE THREAD

**Issue by rakarachon** [IIC2233/Syllabus#60]
"Banco: En esta opción, el usuario puede enviar dinero desde un usuario a otro usuario. Al elegir esta
última opción, DCCapital Exchange obtiene el 5% del monto a cambiar en forma de comisión.
Esta comisión es guardada dentro del mercado respectivo."

No estoy segura de entender bien esta parte, ¿significa que además de las orders se pueden hacer algo así como transferencias bancarias? o sea, que un usuario puede enviarle dinero a otro sin recibir nada a cambio? Y tampoco me queda claro que DCCapital Exchange obtenga una comisión del 5%, no entiendo como es "guardada dentro del mercado respectivo".

Gracias de antemano!

**Comment by Bneya** [comment]
Tengo la misma duda, ¿en qué mercado quedan guardadas las comisiones por estas transferencias?, si transfiero dinero sin pasar por un cambio de divisa.

**Comment by Jiparavich** [comment]
x3

**Comment by stephichau** [comment]
Revisen la issue #54 !

**Comment by lootarola** [comment]
x4

**Comment by Jiparavich** [comment]
Ah claro! en el punto 4, se aclara. 
Muchas gracias!

**Comment by rakarachon** [comment]
Gracias!!
