### ISSUE TITLE
Crear Usuario (y recurso?)

### ISSUE THREAD

**Issue by gbordoni** [IIC2233/Syllabus#60]
Buena cabros tengo una duda. Cuando un usuario de la anaf quiere crear un nuevo usuario en el sistema, es necesario que en ese instante tambien cree un nuevo recurso (para asignarselo al nuevo usuario)? O se le puede asignar un id de un recurso ya existente?

Saludos

**Comment by iqacevedo** [comment]
Hola! 
Esto está respondido en #49, lo importante es que el usuario solo tenga asignado un recurso (el recurso puede estar asignado a más de un usuario).

Saludos!
