### ISSUE TITLE
"Idioma" del código

### ISSUE THREAD

**Issue by Alonsortega** [IIC2233/syllabus#60]
Una consulta, estoy acostumbrado a nombrar variables en inglés para que calce con el "idioma" del código, de igual manera con los comentarios. Es necesario que las variables estén en "español"? Y es posible dejar los comentarios en inglés?

**Comment by jmwielandt** [comment]
Hola!

Lo hablamos un poco entre los ayudantes y,
- Los nombres de las variables pueden estar en inglés, siempre y cuando continúen siendo nombres descriptivos.
- Los comentarios deberán estar en español, lo siento :(

Saludos!

**Comment by lily416** [comment]
Para complementar un poco la respuesta:

En general no es una mala práctica escribir código en inglés (mejor dicho muchos lo consideran una buena práctica), pero debido a que inglés no es un requisito del curso (tanto para los alumnos como para los ayudantes) no se puede asumir que todos tendrán un buen dominio del inglés. 😞 

Por esto mismo:
- Las variables pueden estar en inglés, ya que son conceptos más simples y concretos.
- Pero los comentarios deben estar en español, ya que al ser frases más complejas pueden conllevar errores (por parte del lector) y la principal función de los comentarios es que sean un aporte al momento de entender tu código (ya sea por ti o por terceros).

Espero entiendas 🙇‍♀ 
Saludos y éxito con tu tarea 👋😄

**Comment by Alonsortega** [comment]
Muchas Gracias!
