### ISSUE TITLE
Duda sobre redaccion enunciado sobre Menu

### ISSUE THREAD

**Issue by ManuelKastE** [IIC2233/Syllabus#60]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Holaa, estaba leyendo el enunciado y me di cuenta de que en la seccion 3.2.2 del Menu de acciones en la parte 2 de plantar dice que asumamos que el usuario nos entregara "correctamente los datos, es decir, entregará un str para el parámetro de codigo_cultivo y dos números enteros positivos para los parámetros de alto y ancho" pero tengo entendido que el codigo de cultivo es tambien un int, ya que en ambos metodos buscar_y_plantar() y plantar() el codigo_cultivo es recibido como un int, disculpa si se me esta pasando algo pero llevo como media hora leyendolo y todavia no pillo que se me pueda estar pasando jajajaja y gracias de antemano

**Comment by ignacio-sp** [comment]
Hola @ManuelKastE, interpreta que lo que se recibirá mediante el input seguirá siendo el número para el código del cultivo, el input que se recibirá mediante consola será de tipo "str" (el cual corresponde a un número) por lo que es necesario que manejes esa variable adecuadamente para que sea compatible con la función

Espero haber resuelto tu duda!
