### ISSUE TITLE
Grito = Mensaje Personalizado?

### ISSUE THREAD

**Issue by naquiroz** [IIC2233/Syllabus#60]
En la seccion 5.3 (Razas) dicen que cuando una raza logra conquistar un planeta, tiene un mensaje personalizado. Luego en cada raza especifican un _"Grito de guerra cuando invaden un planeta"_. Este grito es el mensaje personalizado? O el mensaje es otro?

**Comment by leolivares** [comment]
Hola!
Si, el mensaje personalizado se refiere al grito de guerra especificado en cada una de las razas.
Saludos.

**Comment by jmwielandt** [comment]
El archivo grita algo?

**Comment by jmwielandt** [comment]
*archimago 
Perdón, fue el autocorrector

**Comment by IchottMano** [comment]
@jmwielandt Dado que el archimago no conquista el planeta, sólo lo deja no conquistado, no tiene grito de guerra.
Saludos!
