### ISSUE TITLE
Envío de información servidor-cliente

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2233/Syllabus#600]
Si pretendo enviar una clase u objeto desde el servidor al cliente, ¿Es posible hacer eso solo codificando a la clase u objeto? ¿O debo usar pickle o json para serializarlo y luego enviarlo? Si ocupo pickle o json, ¿Es necesario que que codifique lo que estoy serializando? ¿Es necesario que decodifique lo que estoy deserializando?

**Comment by Hernan4444** [comment]
@jorgeriesco serializar es la acciones de transformar un objeto en una **secuencia de bytes** y codificar (`encode`) es el método para transformar un string en una **secuencia de bytes**. Ambos son dos formas distintas de llevar a bytes un objeto y por lo tanto no puedes mezclar ambas cosas. Recordar que json convierte un objeto tipo diccionario a un string y por ello es necesario después codificar para transformarlo en una secuencia de bytes. Pero en el caso de pickle, este hace todo de una.

Espero haber resuelto tu duda.
Saludos!

**Comment by jorgeriesco** [comment]
sipi, gracias

**Comment by josemlira** [comment]
@Hernan4444 quizás entendí mal pero, no podemos usar en la tarea pickle y json (los dos), para codificar en distintos casos?

**Comment by Hernan4444** [comment]
@josemlira si pueden usar ambos pero no mezclarlos. Si serializas algo con pickle no lo intentes codificar con encode o deserializar con json. Si los usan para diferentes casos no hay problema :+1: 

Saludos!

**Comment by acrojas2** [comment]
@Hernan4444 
Tengo una gran duda acerca de esto.  En el envío de mensajes entre el servidor y el cliente, solo debemos escoger una forma de serialización (pickle o json + encode y decode) ? o es posible mezclar todo? Con lo de mezclar todo me refiero a mandar algunos mensajes a través de dumps y loads de pickle y otros solo codificando y decodificando con "utf-8" o el lenguaje que queramos. Cual sería la buena práctica ?
Saludos!

**Comment by Hernan4444** [comment]
@acrojas2 puedes mezclar dependiendo del caso, lo que no puedes hacer  por ejemplo (porque python tira error) es mezclar piclkle con json para un mismo archivo enviado. Si serializas con pickle ese objeto, deserializa con pickle y no intentes con otra forma. La idea es que al enviar un archivo o comando sean consecuentes con el protocolo que tomen. ¿Cual es una buena practica? No te podría decir, depende de lo que quieras mandar.

Saludos!

**Comment by rrhurtado** [comment]
Hola! 

Bajo la premisa de que el objetivo de la tarea siempre es aprender, eres libre de usar ambas (siempre que sean consecuentes con el protocolo para un mismo archivo)
