### ISSUE TITLE
Biblioteca math ausente, numpy y random no tienen exp

### ISSUE THREAD

**Issue by jadiaz6** [IIC2233/Syllabus#600]
Hola, por alguna razón mi Python no tiene la librería math, numpy (que tengo instalado) y random están pero no tienen el método exp.

Intenté instalar math y no pude, me tira errores. Y busyqe sobre la función exp, pero en internet sale solo como usarla.

Cómo hago para obtenerla?

**Comment by andresfdezc** [comment]
Por favor revisa que no tengas ningún archivo llamado `math.py` en la carpeta en donde estés intentando importar esa librería.

**Comment by jadiaz6** [comment]
No tengo ninguno, se que math viene con python, eso es lo raro.

**Comment by iqacevedo** [comment]
Respecto a que no te aparece exp en random, será que quieres usar expovariate?

**Comment by nmaturana97** [comment]
como alternativa podriai usar el valor aproximado del numero euler(?)

**Comment by rihanuch** [comment]
Numpy si tiene exp

**Comment by jadiaz6** [comment]
Si se! Pero no me aparece. Escribo numpy.exp y no sirve, también probé con numpy.random.exp.

Voy a usar un euler escrito a mano, lo específico en el readme.

Gracias por la idea.

**Comment by nmaturana97** [comment]
de nada, jajajaja

**Comment by andresfdezc** [comment]
@jadiaz6 Si quieres, te puedo ayudar a buscar el problema hoy después de la ayudantía.

**Comment by jadiaz6** [comment]
Voy a preguntar en la ayudantía extra de mañana, gracias.
