### ISSUE TITLE
Diagrama de Clases hecho "a mano"

### ISSUE THREAD

**Issue by luisignaciosc** [IIC2233/syllabus#600]
No sé si sea muy tonta la pregunta, pero ¿puedo dibujar el diagrama de clases y subirlo en el formato pedido?, pregunto porque tenía uno escrito y quería saber si lo podía aprovechar para la entrega.

Respecto a las preguntas tontas les comparto un proverbio chino bastante interesante jajaj: "Aquel que pregunta es un tonto por cinco minutos, pero el que no pregunta permanece tonto por siempre"

Saludos

**Comment by lily416** [comment]
Se pueden subir diagramas hechos a mano, pero la imagen que subas debe verse claramente toda la información del diagrama. 

Es recomendable:
* Usar lápiz pasta o plumones, por sobre lápiz mina.
* Escanear la imagen, por sobre sacarle una foto con el celular.

Si tienes el tiempo, te recomiendo hacerlo con alguno de los programas recomendados en el enunciado, porque el resultado tiene una mejor calidad y le permiten al ayudante verlo más claramente.

Saludos y éxito con la tarea 👋🦄
