### ISSUE TITLE
Duda locks distribución de puntaje de la tarea

### ISSUE THREAD

**Issue by JuaniAndres** [IIC2233/syllabus#600]
Hola a que se refiere esta parte de consistencia

> Se utilizan locks cuando es necesario.

Se refiere a locks de threads? 
En ese caso estamos obligados a ocuparlos porque yo no ocupe ninguno y hasta el momento esta funcionando sin problemas mi programa

**Comment by fdoflorenzano** [comment]
Hola @JuaniAndres,

Sí, se refiere a *locks* de *threading*. 

Debido a la naturaleza del problema que se presentó en la tarea, es normal utilizar *threading* para manejar ciertos aspectos que posiblemente son concurrentes en la ejecución de los programas. Específicamente, en el servidor. Luego, como hay múltiples *threads* en ejecución dentro del contexto de un programa, estos probablemente comparten recursos en su ejecución, y posiblemente los utilicen casi al mismo tiempo. Si recuerdas bien, esto puede traer a posibles errores de sincronización cuando instrucciones de un hilo no se ejecutan completamente y luego inician las instrucciones de otro hilo en el mismo contexto.

Si tu programa usa *threads*, te recomiendo te cuestiones cuales son los recursos compartidos a los que tienen acceso, y si un problema de sincronización podría aparecer. A modo de ejemplo, te dejo las siguientes preguntas:

- ¿Los *threads* tienen acceso a lectura/escritura de los mismos archivos de forma concurrente?

- ¿Qué ocurre si dos *threads* intentan enviar información a través del mismo *socket* al mismo tiempo? ¿Podría llegar a pasar en tu programa?

Ahora bien, todo lo anterior supone el uso de *threads* en tu programa, y cierto uso de ellos específico. Eventualmente podría haber un programa modelado de tal manera que se asegure que las **secciones críticas** queden a cargo de un *thread* a la vez. Esto último sería equivalente a asegurar el espacio de secciones críticas como *locks* lo hubiera hecho, así que se evaluaría correctamente.

Espero se entienda, cualquier otra duda nos avisas.
Saludos.

**Comment by JuaniAndres** [comment]
Muchas gracias profe
Si suponía que tenia que ver con lo segundo que menciono pero pensándolo bien supongo que no me a fallado por la velocidad en que se corre el código que me gana en tratar de colapsarlo al testearlo en teoría si debería fallar cuando varios usuarios en distintos computadores se comunican así que tendré que ponerle locks para asegurarme
