### ISSUE TITLE
estadísticas dinero perdido en entradas

### ISSUE THREAD

**Issue by santilaguna** [IIC2233/Syllabus#600]
Hola!
tengo una duda, puesto que el costo de la entrada es cero, podemos simplemente mostrar el total de personas que no entraron al parque por eventos externos o sumar los presupuestos que tenían para gastar?

**Comment by Hernan4444** [comment]
@santilaguna basta con indicar cuantas personas no entraron debido al evento externo.

**Comment by santilaguna** [comment]
gracias!
