### ISSUE TITLE
Hardcodeos con designer

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#600]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

**Comment by fernandosmither** [comment]
a propósito, detalles como que un brazo se pueda salir del fondo del mapa, serán considerados?
![image](https://user-images.githubusercontent.com/66154723/120743565-4465f280-c4c7-11eb-92bb-df89bcb999f4.png)

**Comment by Juampisaez** [comment]
Hola @fernandosmither 
Es posible que si seteas los limites de tu mapa como un parametro, sea considerado hardcoding. En este caso te recomendaria tomar la geometria de tu mapa (label tal vez) para setear los limites.
Por ejemplo:
``
self.x = 150
``
No es lo mismo que decir
``
self.x = self.mapa.geometry().x()
``
A pesar de que sean los mismos valores.

Respecto a tu segunda pregunta, la idea es que el personaje con salga del mapa, te puede descontar puntaje la situacion de la foto.

Espero quede mas claro, quedo atento igual :)

**Comment by fernandosmither** [comment]
> Hola @fernandosmither
> Es posible que si seteas los limites de tu mapa como un parametro, sea considerado hardcoding. En este caso te recomendaria tomar la geometria de tu mapa (label tal vez) para setear los limites.
> Por ejemplo:
> `self.x = 150`
> No es lo mismo que decir
> `self.x = self.mapa.geometry().x()`
> A pesar de que sean los mismos valores.
> 
> Respecto a tu segunda pregunta, la idea es que el personaje con salga del mapa, te puede descontar puntaje la situacion de la foto.
> 
> Espero quede mas claro, quedo atento igual :)

Esque es algo distinto mi situación, en vez de setear límites numéricos del mapa, junto con crear la label del mapa en Designer, creé 4 labels invisibles en los bordes con las cuales chequeo las colisiones y me sirven para limitar el mapa justamente.

Esto estaría bien?, a mí me hace sentido porque como se vio en la issue #556, el tamaño de la ventana lo fijamos nosotros, y como siempre será el mismo tamaño de ventana, las labels límites que rodean al mapa siempre estarán en el mismo lugar.

**Comment by Juampisaez** [comment]
Aaaah, entiendo. Entonces lo que estarias haciendo no esta nada mal, de hecho no se consideraria hardcodeo. (una solucion muy creativa jajajjaja).
No te preocupes, no te consideraremos que es hardcodeo :). De igual manera puedes comentar esta issue en tu readme, para que tu ayudante sepa que te basaste aqui.
Lo otro, fijate en la situacion de la foto que mandaste, no esta bien que el personaje salga del mapa.

Espero quede todo mas claro :)

**Comment by fernandosmither** [comment]
> Aaaah, entiendo. Entonces lo que estarias haciendo no esta nada mal, de hecho no se consideraria hardcodeo. (una solucion muy creativa jajajjaja).
> No te preocupes, no te consideraremos que es hardcodeo :). De igual manera puedes comentar esta issue en tu readme, para que tu ayudante sepa que te basaste aqui.
> Lo otro, fijate en la situacion de la foto que mandaste, no esta bien que el personaje salga del mapa.
> 
> Espero quede todo mas claro :)

Perfecto! Lo he arreglado. Muchísimas gracias
