### ISSUE TITLE
Duda enunciado:

### ISSUE THREAD

**Issue by enriquemolinare** [IIC2233/syllabus#600]
Hola, en el inicio del enunciado dice 'Luego de que se acabe el último día de competencia, la DCCumbre Olímpica se da por finalizada y se deberán guardar los ganadores, medallas y resultados'. En donde se deben guardar los resultados?

**Comment by retamalcito** [comment]
¡Hola @enriquemolinare!

Cómo dice el enunciado, los resultados del campeonato deben guardarse en el archivo `resultados.txt`, según el formato especificado en la sección del mismo nombre.

¡Éxito! 🏅
