### ISSUE TITLE
Usuario abandona sala

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2233/syllabus#600]
Hola, es valido que un usuario solo puede abandonar la sala solo clickeando la cruz, y se cerraria su juego completo? O es necesario implementar un boton que me devuelva a la seleccion de salas? Saludos

**Comment by jeschuwirth** [comment]
Hola!

Creo que el enunciado no especifica, por lo que quedaría a tu criterio, **pero** debido a que no es tan complejo volver a la sala principal y apretar la cruz cierra todo el programa, si debe haber un botón que te devuelva a la selección de salas, si no lo implementas puede aplicarse un descuento a criterio de ayudante por incomodidad al corregir la tarea.

Suerte!

**Comment by mjespinoza** [comment]
Holaa, tengo una duda con respecto a esto mismo, un usuario puede salirse en la mitad de una ronda?

**Comment by jeschuwirth** [comment]
@mjespinoza te diría la misma respuesta que puse anteriormente, ya que si no colocas un botón para volver el ayudante va a tener que jugar el juego por completo o cerrar el programa. Por lo que podría llegar a aplicarse como descuento de ayudante.

Por otro lado, como dentro de la partida está el comando \chao ya deberías tener un programa más o menos hecho que te regrese al menú anterior y basta con conectar todo con un botón.

Suerte!
