### ISSUE TITLE
Properties en el diagrama de clases 

### ISSUE THREAD

**Issue by mpmunoz13** [IIC2233/syllabus#601]
Hola! Como hay que poner los properties en el diagrama? Vi la issue #581 pero no me queda claro.

**Comment by mpmunoz13** [comment]
Donde hay que poner <get/set>, tengo que definir los métodos?

**Comment by moquezada** [comment]
Hola @mpmunoz13,

Acabo de responder tu duda en la issue #581. Cualquier otra pregunta puedes escribirla ahí.

Saludos!
