### ISSUE TITLE
Envío de instancias

### ISSUE THREAD

**Issue by josemlira** [IIC2233/Syllabus#601]
Hola! por los sockets es posible envíar instancias de clases (codificadas con pickle)? Lo intenté y me arroja Import Error

**Comment by iqacevedo** [comment]
Hola !
Deberías poder, puedes especificarnos más del error que te sale ?

Saludos !

**Comment by josemlira** [comment]
Tengo la clase que deseo enviar en el modulo x, luego al hacer send con el socket lo codifico con pickle.dumps y cuando en el servidor quiero hacer loads, me arroja ImportError: No module named 'x'

**Comment by stephichau** [comment]
@josemlira importa el modulo x en el codigo del servidor :)

**Comment by josemlira** [comment]
Ahí me funcionó! Gracias!
