### ISSUE TITLE
nombres deportistas y heredar property

### ISSUE THREAD

**Issue by feliperojas123** [IIC2233/syllabus#601]
hola buenas queria saber si los nombres de los deportistas pueden haber dos iguales pero con diferentes atributus y que no se como heredar las funciones property... en este caso tengo una clase madre la cual quiero usar property para un atributo... luego mi clase que hereda de esta como engo que instanciar esa funcion para poder ver y modificar el atributo usado como property...

**Comment by jitorcas** [comment]
Hola! @feliperojas123 

Los nombres de los deportistas no se repetirán, dado que es la única manera que los puedes identificar desde `delegaciones.csv`. 

Con respecto a tu segunda pregunta, puedes verificar las issues #483 y #466 que explican muy bien cómo es el uso de _properties_ con herencia, puedes volver a preguntar si quedas con dudas. 

Éxito en la tarea! 🏃🏻🏋️‍♀️

**Comment by feliperojas123** [comment]
graciaaaaaas te pasaste!!!!
