### ISSUE TITLE
Direccion de movimiento de los personajes

### ISSUE THREAD

**Issue by rihanuch** [IIC2233/Syllabus#601]
Hola! Queria saber que restricciones tienen los pesonajes para moverse. Con esto me refiero a que se enuncia que un enemigo escoge una direccion con una p=0,25 , por lo que asumo que solo se puede mover en los los angulos 0,90,180,270? O se puede mover en una direccion arbitraria no perpendicular ni paralela a los ejes?

**Comment by Arcoirisky** [comment]
Hola!
Puede moverse en cualquier dirección.
Saludos~ :D

**Comment by rihanuch** [comment]
Gracias!
Entonces tengo varias dudas
1) como se decide en que direccion mover
2) como se haria con las imagenes? Se tendria que tener un modelo pseudo 3d para asi poder hacer una rotacion continua?

**Comment by tomasrivera** [comment]
Hola, con cualquier dirección entiendo que es cualquier ángulo (más de 4).
¿Cómo es esto posible?, ¿se puede explicar mejor?

**Comment by hanavarrete** [comment]
@rihanuch  Se elige cualquier dirección al azar, pero solo pueden moverse en una cruz, no cualquier ángulo. Para que quede más claro, solo se puede mover paralela/perpendicularmente a los ejes como mencionaste antes.

**Comment by hanavarrete** [comment]
@rihanuch Y para las imagenes solo debes tener una de topview, con eso debiese bastar (spoiler alert).

**Comment by hanavarrete** [comment]
@tomasrivera  Espero las respuestas anteriores hayan respondido tu duda 😁

**Comment by hanavarrete** [comment]
@rihanuch , @tomasrivera Wait, error mío, no tomen válido lo de antes. La explicación oficial es la que viene ahora:

**Comment by Arcoirisky** [comment]
Digamos que inicalmente avanza hacia arriba, cada segundo que pase hay un 25% de probabilidad que cambie de dirección donde esta caminando, con un 75% que siga avanzando en la dirección actual. El movimiento queda a criterio de ustedes, siempre y cuando se muevan en todas las direcciones.

@rihanuch 
1. Queda a tu criterio
2. Eso debes de averiguarlo por tu cuenta :D Pero te digo que si se puede con todo lo que les hemos dado :)
3. Y~ Nop. No es 0 :D Revisa un poco más tu lógica pero no puedo darte la respuesta directa a eso.

**Comment by Arcoirisky** [comment]
¿Se entiende mejor? O:

**Comment by rihanuch** [comment]
1. Ok!
2. También ok jajaja, 
3. La forma de rotacion es **ESTRICTAMENTE** continua o discreta?

**Comment by Arcoirisky** [comment]
Queda a tu criterio. Es irrelevante si usas la forma continúa o discreta :)

**Comment by valeria-adasme** [comment]
Hola :o yo había entendido que 0.25 era la probabilidad de moverse en cada dirección, considerando solamente 4 direcciones (1/4 de probabilidad cada uno). Varios conocidos le entendieron así también...
¿Van a cambiar el enunciado o se puede dejar a la interpretación?

**Comment by FernandoPieressa** [comment]
@valeria-adasme No se deja a la interpretación.  Es como explico @Arcoirisky el funcionamiento del movimiento.

**Comment by inmadariaga** [comment]
@FernandoPieressa respecto a la rotación del personaje principal (al apretar a o d ) el angulo en el que rota queda a criterio nuestro?, por ejemplo: que cada giro se torne en 45 grados? o tiene que el personaje poder avanzar en cualquiera de los 360 grados?

**Comment by Arcoirisky** [comment]
@inmadariaga O: Ese caso queda a vuestro criterio :D 
Ánimo y suerte con la Tarea! :DD

**Comment by caespinoza5** [comment]
Aun no me queda totalmente claro el movimiento de los enemigos. Si un enemigo se mueve en 4 direcciones (arriba, abajo, derecha, izquierda), y cumple con que cada un segundo, eliga con probabilidad de 3/4 de seguir o 1/4 de cambiar de dirección, se cumple lo del enunciado? Ya que está moviéndose en todas las direcciones.

Mi pregunta va orientada a si estamos haciendo un juego con movimiento tipo agario  o tipo bomberman, o una mezcla extraña donde los enemigos se mueven como agario y el personaje como bomberman (por la respuesta anterior).

**Comment by Arcoirisky** [comment]
@caespinoza5, cómo se dice más arriba. El personaje debe poder moverse en todas direcciones, no en cruceta como e. Bomberman. Podría decirse que es cómo agario O:!
