### ISSUE TITLE
Duda bonus mensaje con foto 

### ISSUE THREAD

**Issue by JuaniAndres** [IIC2233/syllabus#601]
Hola la foto del mensaje tiene que ser scrolleable en casos de ser muy grande o bastaria con que la escale al tamaño del globo manteniendo el aspecto
Gracias de antemano

**Comment by gatochico** [comment]
Hola! En el enunciado se menciona que si la imagen sobrepasa el tamaño máximo permitido, esta debe ser **reescalada** acordemente:
![image](https://user-images.githubusercontent.com/37161120/70175952-64d8a500-16b6-11ea-9a2e-ec3dc49c1072.png)
Así que tu segundo caso sería el pedido.

Éxito ! :penguin:

**Comment by JuaniAndres** [comment]
yap muchas gracias eso me quita problemas

**Comment by itplanella** [comment]
Hola! Existe alguna forma de crear el globo utilizando pyqt? ya que este no esta en los sprites

**Comment by gatochico** [comment]
@itplanella Algunas ideas serían utilizar `QPainter`, y buscar en línea sobre esta clase y algunos ejemplos similares a lo que quieres. Sin embargo, dependiendo de tu avance en la tarea y/o tiempo disponible, quizá te convenga usar sprites propios (Recuerda que puedes agregar todos los sprites extras que quieras, mientras estén en una carpeta diferente a  `sprites` y la subas junto a tu tarea final).
