### ISSUE TITLE
JSONDecodeError cuando un cliente se cierre su ventana

### ISSUE THREAD

**Issue by cambrinKD** [IIC2233/syllabus#601]
El error entero es "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)". 

Se pasa cuando un cliente se cierre su ventana de juego/conexión. 

Seguro que puedo cachar el error pero no estoy seguro donde.

**Comment by jeschuwirth** [comment]
Hola,
¿Podrías subir el código a tu repositorio? 
ahí lo puedo mirar y ayudarte más fácilmente.

**Comment by cambrinKD** [comment]
Ahora si

**Comment by cambrinKD** [comment]
Es raro porque ahora, a veces funciona y a veces se produce un error
