### ISSUE TITLE
Problemas para que aparezca la ventana de juego de Lisa

### ISSUE THREAD

**Issue by luzmagurzua** [IIC2233/syllabus#601]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola! Tengo un problema para hacer aparecer la ventana de juego de Lisa (para Homero me funciona bien, e implementé lo mismo para lisa, sin embargo no resulta) para esto defini una funcion que entrega la ubicación del personaje (general) como atributo y en base a eso y los pixeles de mapa calculo si el personaje está en su lugar de "entrada" al juego o no. Entonces Quería saber que puede estar  pasando? Hice un push a mi repo recién. 
De antemano gracias

**Comment by valerianazal** [comment]
Hola @luzmagurzua ! Revisé tu repo y el problema es que al revisar `self.posicion_y` lo tenías de la siguiente manera:
`(self.posicion_y >= 566 and self.posicion_y <= 355)`
Si te fijas estás pidiendo que la posición en el _eje y_ sea **mayor a 566 y menor a 355**, solo debes cambiar el sentido de las desigualdades y tu problema se resolverá 😁 
Aprovecho de comentarte que seguramente al poner las fotos en las ventanas, pusiste _Choose resource_ en vez de _Choose file_,  por lo que cuando corrí el programa no seapreciaban las fotos correspondientes, para que lo revisas!!
Si tienes alguna otra duda comenta esta misma issue! Mucho éxito ✨

**Comment by luzmagurzua** [comment]
Hola, muchas gracias por tu respuesta. Pucha había tenido ese problema de las fotos antes (las tenia con ressource, hice una issue y me enseñaron a hacerlo con choose fila) , lo tengo todo así y en mi computador me salen bien, que podrá estar pasando? :(

**Comment by valerianazal** [comment]
Puede ser que las ventanas que están subidas al repo no estén actualizadas con esos cambios. Revísalo, haz un nuevo push y avísame para verlo.

**Comment by luzmagurzua** [comment]
Si, o sea el último push lo hice ayer con las ventanas todas con choose file, hoy no he avanzado aún, ahora no estoy en mi casa (vacuna) pero cuando llegue lo hago denuevo por si acaso, y lo comento acá, gracias de antemano

**Comment by luzmagurzua** [comment]
Acabo de hacer push!
