### ISSUE TITLE
Consulta RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by mblejeune** [IIC2233/Syllabus#601]
Hola! en mi código al intentar cambiar (aumentar o disminuir) algun atributo de mis clases usando properties me sale este error:

RecursionError: maximum recursion depth exceeded while calling a Python object

hay alguna forma de solucionarlo ? he buscado por todas partes y nada me funciona :(

**Comment by Hernan4444** [comment]
@mblejeune es probable que el `setter` de tu propertie está seteando la misma propertie y por lo tanto estás llamando nuevamente al `setter`de tu propertie, así se genera una recursión que nunca acaba hasta que Python no soporta más. Verifica que el `setter`de tu propertie edita el mismo atributo que retornaría el `getter`.

**Comment by mblejeune** [comment]
me funciono!! además tenía definido igual nombre para atributo y nombre de las properties y le agregué un _ al atributo y funciona perfect:) Muchas gracias!!!!
