### ISSUE TITLE
duda envío de mensaje

### ISSUE THREAD

**Issue by Rafoxxa** [IIC2233/syllabus#602]
cuando se envían los mensajes, los 4 bytes que indican el número del chunk de 124 bytes que se envía, ¿estos se envían juntos? es decir en un envío de 128 bytes o se envían los 4 y luego los 124.

**Comment by lily416** [comment]
Sí, los 4 _bytes_ que indican el orden de los _chuncks_ se envían junto a los 124 _bytes_ que representan el contenido del mensaje, es decir, por cada _chuck_ se envían 128 _bytes_.

Saludos y éxito con la tarea 👋🐧
