### ISSUE TITLE
Subir un archivo nuevamente

### ISSUE THREAD

**Issue by 18638333** [IIC2233/syllabus#602]
Subí mal mi diagrama de clases, lo borré, y ahora no me deja subir el archivo correctamente, por que puede ser?

**Comment by jeschuwirth** [comment]
Hola @18638333!

tienes que hacer git rm <nombre archivo diagrama> del mismo modo que haces git add <nombre archivo diagrama> al eliminar un archivo para que este se elimine correctamente en tu repositorio.

Luego del rm tienes que hacer commit y push.

Si lo anterior no funciona intenta con el siguiente paso a paso:

1. mover archivo a otra carpeta
2. git rm <nombre_archivo>
3. git commit -m""
3. git push
3. mover archivo al repositorio
2. git add <nombre_archivo>
3. git commit -m""
3. git push

**Comment by 18638333** [comment]
![Captura de pantalla (7)](https://user-images.githubusercontent.com/62103274/79807981-73102080-833a-11ea-92bc-7a5cb656262f.png)
Me sale eso, y no me deja nisiquiera subir otro archivo

**Comment by jeschuwirth** [comment]
El problema que tiene que es el archivo esta en tu repo de github pero no en tu pc
y github está confundido con eso, la mejor solución que te puedo dar es partir de 0 nomas:

1. mover todos tus archivos a otra carpeta para respaldar
2. borrar el repositorio
3. clonar nuevamente tu repositorio
4. 
5. borrar tu archivo con el diagrama
6. mover todos tus archivos en el respaldo a tu nuevo repo
7. 
8. git add de todos los archivos
9. git rm del archivo que borraste
10. git commit -m""
11. git push

Si no te sirve avisa!
