### ISSUE TITLE
Ausencia Actividad motivo intercambio

### ISSUE THREAD

**Issue by fjaraneda** [IIC2233/Syllabus#602]
Holaa, no sabia de que otra forma comunicarme, pero lo que pasa es que todo el jueves debo estar haciendo pruebas para intercambio por la universidad, existe alguna forma de recuperar la actividad o la doy por perdida??

**Comment by fringlesinthestreet** [comment]
@fjaraneda Hola :)

Si es solo por este jueves vas a tener que botarlo nomás. Recuerda que tienen actividades que se borran por lo mismo.

Si es un problema para el resto de las actividades, entonces envía un mail a ayudantesiic2233@gmail.com. Ese es el medio para hablar estos temas!
