### ISSUE TITLE
Pantalla inicio

### ISSUE THREAD

**Issue by josemlira** [IIC2233/Syllabus#602]
Hola!, cuando se ingresa al programa, se debe mostrar una pantalla de inicio, en donde aparecen las salas de juego con cierta información para cada una, como la cantidad de usuarios en ella y el tiempo restante de la canción que se está reproduciendo, esta información se debe mostrar en tiempo real? por ejemplo si entra un usuario mientras nosotros estamos en la pantalla de inicio, debería cambiar el número de usuarios en la sala? o solo basta con mostrar la cantidad que había cuando entramos al programa?

**Comment by hanavarrete** [comment]
Hola! la idea es que sea en tiempo real. Puedes manejar esto con un botón que actualice o como quieras, pero que al menos pueda estar actualizado. Saludos!

**Comment by josemlira** [comment]
Muchas gracias!!!
