### ISSUE TITLE
Problema con guardar en self.equipo los jugadores como clases

### ISSUE THREAD

**Issue by Natydlb** [IIC2233/syllabus#602]
tengo un problema con guardar los jugadores en self.equipo como clases ya que lo hago en una función de la clase delegación "DCCroton" , pero al momento de fichar deportista al terminar de ficharlos, quiero que me imprima deportistas.nombre y me sale 'str' object has no attribute 'nombre', pero nose porque queda como str y no como una clase, actualice mi repo, lo de imprimir esta en la linea 479 y la función que guarda los deportistas como clases en el equipo es la 460

**Comment by mmunozmendez** [comment]
Hola, revisa.ndo superficialmente, veo que en la líneas 461 usaste una función que retorna un diccionario, no instancias de clases. Recuerda que la extensión máxima es de 400 líneas por archivo. 
Éxito 🦝

**Comment by Natydlb** [comment]
pero esa función comparar_deportistas retorna una instancia de clase :(

**Comment by mmunozmendez** [comment]
Hola
Línea 77, estás retornando datos, que es un diccionario

**Comment by Natydlb** [comment]
hola, lo siento, no lo había subido actualizado, ahi retorno una instancia y sigue sin funcionar

**Comment by mmunozmendez** [comment]
Hola,
ahí si jaja
Tengo la impresión de que la línea 458 hace algo extraño, te recomiendo ir poniendo prints en los pasos de lo que intentas hacer, para que veas que paso a paso va funcionando y vas obteniendo lo que realmente necesitas. 
Cuéntame como te va

**Comment by Natydlb** [comment]
hola!, lo intente ayer y hoy día y no me funciono :(
