### ISSUE TITLE
Duda distribución de puntajes (Ventana de Chat)

### ISSUE THREAD

**Issue by matiasmasjuan** [IIC2233/syllabus#603]
Hola! Tengo una duda. En el excel de distribución de puntajes, en la sección de Interfaz (Ventana de Chat) dice: "Se visualizan correctamente todos los avatares de usuarios, junto al último mensaje que enviaron."
¿Qué quiere decir esto? Que si alguien nuevo entra a la sala, se le debe cargar en su interfaz inmediatamente el último mensaje que fue enviado? Hago la pregunta porque el enunciado no dice acerca de eso. Además, si alguien entra a una sala, no creo que él/ella debería saber los mensajes enviados con anterioridad

**Comment by lily416** [comment]
La oración del enunciado hace referencia a que se debe mostrar el último mensaje de cada usuario desde que este entró a la sala de chat.

Es decir, si una nueva persona ingresa a la sala de chat, es esperable que no tenga un mensaje que mostrar, pero sí debería ser capaz de ver el último mensaje de los otros usuarios.

Lo siento por la confusión 🙇‍♀ 
Saludos y éxito en la tarea 👋🐧 

<details>
<summary>PD</summary>
Existen varios tipos de chat donde se pueden ver los mensajes que se enviaron antes de que el usuario ingresara al chat. 🙊 
</details>

**Comment by matiasmasjuan** [comment]
Ok! Me quedó mucho más claro. Gracias!
