### ISSUE TITLE
Duda simulacion (no encontre la respuesta en otras issues)

### ISSUE THREAD

**Issue by Clemente24** [IIC2233/Syllabus#603]
Hola! Quería preguntar si puedo simular de esta manera:

```python
class Simulacion:

    def __init__(self):
        self.motor = MotorSimulacion()
        self.estadisticas()

    def estadisticas(self):
        for day in ['Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sabado', 'Domingo']:
            self.parque = Nebiland(self.motor, day)
            self.simular()

    def simular(self):
            self.motor.run()
            self.parque.imprimir_estadisticas()

simulacion = Simulacion()
```

considerando que mi método run() cumple con el formato de:
```python
eventos = cola_de_eventos
while len(eventos):
    evento_actual = eventos.pop()
    # Procesar evento_actual
```

**Comment by Hernan4444** [comment]
@Clemente24 **no puedes**, eso es hacer una simulación por día y nosotros estamos solicitando una simulación de la semana. Aunque tu `run()` cumple lo solicitado, tu simular no, puesto que es llamado de forma sincrona.

Saludos ✌️

**Comment by jmwielandt** [comment]
@Hernan4444 
ups... yo tengo una constante en parametros.py que indica el número de semanas a simular y lo hace todo de corrido. Está mal?

**Comment by Hernan4444** [comment]
@jmwielandt si cada simulación es independiente entre si. No está mal

**Comment by jmwielandt** [comment]
@Hernan4444 a qué te refieres con que sea independiente?
Mi simulación sigue sumando los minutos desde el domingo hacia el lunes.
Lo hice así por ruziland, como está lo de que no puede atacar dos sábados seguidos era lo más fácil para cumplir con la restricción.

**Comment by Hernan4444** [comment]
@jmwielandt que nosotros simulamos una semana, se acaba la simulación y empieza otra la cual no sabe que antes hubo una simulación de una semana. 

Lo que hiciste por el tema de ruziland se debía abordar desde otro ámbito. En otra issue se hablo sobre eso en relación al evento Día colegio, ahí te podrías apoyar en lo que me refiero con abordar ruziland desde otro ámbito.

**Comment by jmwielandt** [comment]
😢 gracias
