### ISSUE TITLE
No me deja hacer push

### ISSUE THREAD

**Issue by emiliochandia** [IIC2233/syllabus#603]
![commit](https://user-images.githubusercontent.com/48336456/79809888-a73a1000-833f-11ea-836c-3471faf4a4d3.png)
 Me tira ese error al tratar de hacer push, ayuda :(

**Comment by emiliochandia** [comment]
Edit: No hay problema con que lo haga manual desde la página?

**Comment by Dnpoblete** [comment]
Hola @emiliochandia haz git pull antes de push!

**Comment by emiliochandia** [comment]
Gracias!!
