### ISSUE TITLE
Error al ejecutar Juego malloc: Double free of object 0x7f8b8fdf2ea0

### ISSUE THREAD

**Issue by piacabrera** [IIC2233/syllabus#603]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda con error extraño

Al jugar el juego, aveces me aparece este error. Es de la nada, y solo algunas veces. No logrado saber a que se debe. Ocurre en mi ventana de juego, mientras agarro objetos . Dice Python(68344,0x70000d573000) malloc: Double free of object 0x7f8b8fdf2ea0
Python(68344,0x70000d573000) malloc: *** set a breakpoint in malloc_error_break to debug

**Comment by tqmbanados** [comment]
Hola! Nunca había visto este error D: busqué y es algo más común en lenguajes como C y C++, por lo que debe ser algo de Qt inesperado. Pasa por que tu programa esta llamando a que se libere un espacio de memoria dos veces, lo que genera un error y puede causar pérdida de memoria (*malloc* es memory allocation). Es como si tratáramos de vaciar una caja que ya está vacía! La verdad es que lo más que puedo ayudarte es con la explicación del error, pero preguntaré por ahí para saber si alguien sabe más. Aunque quizás la explicación te de una idea de qué es lo que hace tu programa que podría generar este error!

**Comment by piacabrera** [comment]
Yaaaa gracias, igual mi código esta subido, por si lo tienen que ver para ver como se levanta el error,  podría ser por eliminar un thread dos veces? o Algo como borrar un elemento de una lista que ya borre? o eso tendría un error mas normal?

**Comment by tqmbanados** [comment]
si es un QThread es posible que sí! lo de la lista no creo, al menos que estes eliminando el elemento de la lista de una forma **muy** rebuzcada jajaj, sino sólo te tiraría un `IndexError` o algo así.

**Comment by tqmbanados** [comment]
Lo que puede ser es algo con dos threads trabajando sobre un mismo objeto al mismo tiempo, eso podría generar errores de memoria. Revisa si tienes algo así!

**Comment by piacabrera** [comment]
También me pasa que después de cierto tiempo jugando, desde la 3era ronda, o solo si dejo una ventana corriendo harto rato (como hasta después de que se termine la música), mi juego se pega al entrar a la ventana de juego, pero sin ningún error. Tampoco se a que se debe :(

**Comment by tqmbanados** [comment]
Revisando tu código, encontré que usas tanto `QThread` como `threading`. Es muy probable que esto genere errores, si bien quizás no sea el origen del malloc error. Trata de cambiar el `threading` por `QThread`, que es mucho más seguro al usar PyQt5. 

Tu otro error podría ser por algo de memoria también 😥Te recomiendo enfocarte primero en resolver lo del malloc que parece más serio, y luego trabajar en el otro error (quizás con otra issue). Igual, si identificaste que se te pega luego que termine la música, quizás tiene algo que ver con eso, así que revisa bien ahí si hay algo que genera un ciclo infinito, o un proceso que consuma mucha memoria.

**Comment by tqmbanados** [comment]
Hola! [Aquí](https://github.com/IIC2233-2016-1/syllabus/issues/527) hay una issue antigua con un error igual al tuyo. Podrías probar lo que proponían ahí :)
De todas maneras, cambia tus threads por QTimers o QThreads, nada bueno puede salir de combinarlas u.u

Finalmente, corrí tu programa varias veces, pero no me salió tu error. Tienes varios errores de index o de sacar elementos de listas vacías, y uno ocurre dentro de un `thread`! (el del jefe Gorgory). Además, no puedo avanzar de la primera ronda, por lo que no puedo verificar bien tu otro problema.

**Comment by piacabrera** [comment]
Creo que con la otra issue entendí que pasaba, otra duda, en donde te aparecen los errores de índex??? ya que lo he corrido varias veces, pero en mi computador no me tira ningún error :(

**Comment by tqmbanados** [comment]
En al pasar a la ventana de juego, y cuando trata de instanciarse el Jefe Gorgory!

Me alegro que te haya servido la otra issue :)
