### ISSUE TITLE
Recorrecion actividad 

### ISSUE THREAD

**Issue by ajahr95** [IIC2233/Syllabus#603]
Hace 2 meses atras mande a recorregir mi AC03, luego me comentaron en la issue la "solicitud de recorrección" pero nunca la han recorregido, es decir, sigue todo igual como desde la primera correcion.

**Comment by fringlesinthestreet** [comment]
@ajahr95 Hola :)

Este no es el medio para realizar esto. Cualquier cosa envía un mail a ayudantesiic2233@gmail.com.

(Igual vamos a revisar qué pasó)
