### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by stephichau** [IIC2233/Syllabus#603]
Estimad@s,
Para esta tarea, **deben** agregar en su repositorio un  archivo llamado [**.gitignore**](https://help.github.com/articles/ignoring-files/) que pueden crear [acá](https://www.gitignore.io/) para que no suban los archivos **.wav** y no saturar sus repositorios.

Saludos !

[Edit]: Acá hay otro ejemplo: [link](https://gist.github.com/octocat/9257657)

**Comment by FarDust** [comment]
Si no entienden como se usa: -> busquen Audio y le dan a crear.
Si estan en Windows no les va a dejar crear directamente el archivo .gitignore así que pueden crear un archivo "*.txt" luego abrir el cmd y usar el comando "ren archivo.txt .gitignore".

**Comment by yoavnavon** [comment]
El .gitignore se pone en el directorio principal, o basta que lo ponga en el de la tarea?

**Comment by stephichau** [comment]
@yoavnavon lo puedes poner en el directorio de la tarea :)

**Comment by Arcoirisky** [comment]
Si ya subimos una vez la tarea (antes de ver que existiera este post) con los .wav No pasa nada si los borro a mano ¿cierto?

**Comment by Hernan4444** [comment]
@Arcoirisky si, lo puedes eliminar a mano pero luego debes trabajarlos con el .gitignore :+1: 
Saludos!!

**Comment by rrhurtado** [comment]
Hola, al hacer push de los cambios a tu repositorio puedes comprobar en línea si es que efectivamente fueron borrados los archivos .wav

En particular, al momento de recolectar la tarea se espera que no exista ningún archivo de formato .wav en sus repositorios.

Saludos !

**Comment by fdominguezclaro** [comment]
Podrían explicar como crearlo? Que aprieto crear pero sólo se abre una ventana con texto.

**Comment by Arcoirisky** [comment]
Guarda eso como un archivo .txt y lo guardas en dónde va tu tarea. Luego, abres el git bash en esa carpeta y pones  "ren archivo.txt .gitignore". Y eso

**Comment by fdominguezclaro** [comment]
Se me olvidó poner que uso MacOS jaja

**Comment by Arcoirisky** [comment]
Haz muerto para mi </3

**Comment by FarDust** [comment]
[bash] (opcion 1)
(paso 1) MacOs + Linux: "touch .gitignore" -> crea el archivo
(paso 2) MacOs + Linux : "ls -a" -> muestra los archivos incluidos los ocultos (-a)[comprobar la existencia]
(paso 3) MacOs:  "pico .gitignore" -> editor de texto
(paso 3) Linux: "nano .gitignore" -> editor de texto
Nota: el caracter "^" suele referirse a las teclas "ctrl" o tal vez "cmd"
[editor favorito + bash](opcion 2)
(paso 1) Editor: crear el archivo con cualquier nombre
(paso 2) Terminal [(bash) LInux + MacOs + Windows Ubuntu]: "mv archivo.txt .gitignore" -> "renombramos"
(paso 3) Terminal [(bash) LInux + MacOs + Windows Ubuntu]: "ls -a" ->comprobar existencia

**Comment by nfbalbontin** [comment]
¿ No se puede simplemente eliminar la carpeta Songs y ustedes la agregan?

**Comment by stephichau** [comment]
@nfbalbontin la idea del .gitignore es que puedan trabajar libremente en la misma carpeta de la tarea sin que saturen su repositorio
