### ISSUE TITLE
Delegación no cumple requisitos para competir

### ISSUE THREAD

**Issue by Gustav2000** [IIC2233/syllabus#603]
Hola, en la página 9 del enunciado dice que en caso de que ninguna Delegación cumpla los requisitos necesarios, la competencia se declara como un empate. Para esto basta que un requisito ya no se cumpla o es necesario que no se cumplan los 2?

Y segunda pregunta, en caso de que una no cumpla con los requisitos (perdiendo de esta forma), la otra gana medalla?

**Comment by vicentevegaulloa** [comment]
Hola @Gustav2000 !

Sería lo segundo, si ambas delegaciones no cumplen con al menos un requisito se declara empate. En otras palabras, si a la dos delegaciones les falta uno o más requisitos se declara empate. Espero haberte ayudado 😄

**Comment by Gustav2000** [comment]
Muchas gracias!!!!

**Comment by vicentevegaulloa** [comment]
De nada!
