### ISSUE TITLE
Servidor

### ISSUE THREAD

**Issue by Dunkan1** [IIC2233/Syllabus#604]
queria preguntar si nuestro servidor se supone que esta siempre siendo ejecutado o no,
(me refiero a que no se desconecta nunca)?

ya que si no esta siempre siendo ejecutado entonces, debemos crear un archivo donde guardemos los datos de los usuarios para cuando volvamos a ejecutar el servidor.

si siempre se esta ejecutando, lo anterior no seria necesario ya que no habria necesidad de volver a cargar los datos. 😄

**Comment by Hernan4444** [comment]
@Dunkan1 el servidor se puede desconectar  y volver a conectar en un futuro cercado y por lo tanto debes crear un sistema que permita almacenar toda la información de una sesión y otra.

Saludos!

**Comment by Dunkan1** [comment]
ok
