### ISSUE TITLE
No entendí como usar el gitignore :(

### ISSUE THREAD

**Issue by Mario-uc** [IIC2233/syllabus#604]
No entendí como se hace el gitignore, intenté viendo como lo hacian en otras issues pero no me salió

**Comment by Dnpoblete** [comment]
Hola @Mario-uc, tienes el archivo creado? Trataste haciendo los pasos de las otras issues? Que no te funciona?

**Comment by Mario-uc** [comment]
Es decir cree un archivo .txt llamado .gitignore, que contiene todo lo que tiene que ignorar, pero de ahí intenté subir ese archivo pensando que se hacía así pero no :(

**Comment by Dnpoblete** [comment]
No es con extensión .txt!

**Comment by Mario-uc** [comment]
que extensión es?

**Comment by Dnpoblete** [comment]
.gitgnore

**Comment by Dnpoblete** [comment]
Issue #583

**Comment by Dnpoblete** [comment]
Para la próxima trata de ver estas cosas con mas anticipación 😔

**Comment by Mario-uc** [comment]
Y si ya se subieron los archivos .csv, como los puedo quitar para hacer el gitignore correctamente?

**Comment by Dnpoblete** [comment]
issue #588
