### ISSUE TITLE
Ayuda Crash

### ISSUE THREAD

**Issue by mnbenimeli** [IIC2233/syllabus#604]
Hola, estoy teniendo problemas al ejecutar mi cliente pues la ventana se me crashea. No me manda error ni nada.
Mi idea es crear un QThread como backend del cliente para que esté atento a recibir las instrucciones del servidor y mande los input del frontend; pero se crashea al hacer la conexión inicial. He estado un buen rato y no cacho cuál es el problema.

**Comment by jeschuwirth** [comment]
Hola,

Sube tu código a tu repositorio para poder ayudarte

**Comment by mnbenimeli** [comment]
Ya~~

**Comment by jeschuwirth** [comment]
Encontré el problema, era bien pequeño y costó bastante encontrarlo:

En el main de cliente, en e método ingresar_datos de VentanaInicial tienes a línea 
self.conexion.run()

Esto hace que corra el código de conexión en el thread principal y por esa razón se te queda pegado el programa, lo que necesitas es:
self.conexion.start()

Eso va a iniciar el mismo método en un nuevo thread que es lo que querias.

Exito con el resto de la tarea 😄
