### ISSUE TITLE
Dimensiones de los labels en parametros

### ISSUE THREAD

**Issue by CGR0** [IIC2233/syllabus#605]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola me preguntaba que tipo de labels hay que guardar sus dimensiones en el archivo de parametros.py. Hay que guardar las dimensiones de absolutamente todo? solo las dimensiones de los personajes? de los mapas?
Además me preguntaba si era necesario guardar estas dimensiones si es que se establecen en el designer como dimensiones fijas.
Muchisimas gracias de antemano

**Comment by valerianazal** [comment]
Hola @CGR0 ! La idea es que el archivo `parametros.py` se guarde todo lo que va a permanecer **constante** en el programa, así que deberías guardar todas las dimensiones. Sin embargo, no es necesario que las dimensiones establecidas en QtDesigner estén también en `parametros.py`, pues ya estarán determinadas en el archivo `.ui`.
Quedo atenta a cualquier duda ⭐

**Comment by CGR0** [comment]
Ya me quedo claro! Muchas gracias
