### ISSUE TITLE
Dilema TCP/UDP

### ISSUE THREAD

**Issue by RickyUC** [IIC2233/Syllabus#605]
Hola, por lo que sale en el material del curso pareciera adecuado usar TCP para el chat y UDP para la reproducción de la música.

¿Se pueden usar ambos protocolos en un servidor o dos servidores para el programa de la tarea? ¿O debemos optar por sacrificar la velocidad de la reproducción de los audios o la fiabilidad de que lleguen los mensajes del chat?

**Comment by arturodelreal** [comment]
Hola, no es necesario usar UDP para enviar la música ya que con QSound los audios se reproducen mediante la lectura de archivos .wav, que deben ser enviados a los clientes mediante el protocolo TCP.
Saludos

**Comment by RickyUC** [comment]
Gracias!
