### ISSUE TITLE
Error "Using variable 'print' before assignment"  

### ISSUE THREAD

**Issue by carolina-laferte** [IIC2233/syllabus#605]
Hola! Estaba tratando de imprimir una frase y de la nada me salio ese error en el codigo :c intente reescribirlo pero nada y si borro ese print me pasa con los que siguen :c no se que puede ser 😢 aiuda ya me desespere jajaj [](url)
![Error](https://user-images.githubusercontent.com/69823920/93382974-5587aa00-f839-11ea-9bf8-2caa26442056.png)

**Comment by aaossa** [comment]
Hola @carolina-laferte , por alguna razón piensa que `print` es una variable en lugar del *built-in*. ¿Estás utilizando Python 3? Otra opción es que quizás tienes en alguna parte una variable `print`, por lo que tu *linter* trata ese nombre como tal 🤔

**Comment by carolina-laferte** [comment]
Si, estoy usando python 3.7.8. Tambien pense lo mismo, aunque no la habia definido antes y cambie a otro file, donde me asegure que esa fuera la primera vez que escribia print y nada :c sigue el mismo error

**Comment by aaossa** [comment]
Por cierto, es un error realmente o es una advertencia? Dado que es algo que viene de `pylint` supongo que es una advertencia (o sea, que tu código se puede ejecutar sin problemas), ¿podrías confirmar si es as´?

**Comment by carolina-laferte** [comment]
Es un error realmente, no me deja correrlo y tampoco puedo importar la clase en el codigo principal

**Comment by aaossa** [comment]
Mmm bueno, eso es raro. Revisaste el *output* del código? Si haces un nuevo archivo solo con `print("algo")` te funciona?

**Comment by carolina-laferte** [comment]
si, fuera de ese archivo me funciona el print

**Comment by aaossa** [comment]
Puedes subir tu código a tu repositorio para darle una mirada? Además, podrías probar qué pasa si corres tu tarea desde fuera del editor (por consola)? Gracias 🙌

**Comment by carolina-laferte** [comment]
Tampoco me resulta 😢 ya lo subi

**Comment by aaossa** [comment]
@carolina-laferte asumo que dices que no te funciona porque hay un `ImportError`. Al parecer, esto ocurre porque hay una referencia circular en tus importaciones: `clases_delegaciones.py` tiene la línea `from menus import extrar_datos_deportista`, mientras que `menus.py` tiene la línea: `from clases_delegaciones import IEEEsparta`. Asumo que ese es el problema porque al comentar la importación de `menus.py` el código se ejecuta normalmente 🤔 Quizás esta importación circular es la que confunde a tu *linter*

**Comment by carolina-laferte** [comment]
Pense que podría ser eso pero ahora que lo hice en el flujo del main.py no me deja nisiquiera importar por el error del print, por lo que no me funciona nada 😢  actualice el archivo en mi repo pero asi se ve el error
![Erro2](https://user-images.githubusercontent.com/69823920/93402864-46662380-f85c-11ea-878b-fe8b7182fcce.png)

**Comment by aaossa** [comment]
@carolina-laferte pero cuál es el error que te aparece al ejecutarlo desde consola? Acabo de probar lo que está en tu repositorio y me corre todo bien al ejecutar `main.py`

**Comment by carolina-laferte** [comment]
Cuando intentaba realizar ese metodo me tiraba error por el tema que tomaba print como variable. Finalmente borre todo el codigo ( osea, esa parte jaajaj) y se arreglo solo. Gracias igual!!!
