### ISSUE TITLE
Tarea 4 documentacion

### ISSUE THREAD

**Issue by ChayoPerez** [IIC2233/Syllabus#605]
Hola! Se me olvidó documentar mi tarea. Valdría si la documento ahora? Ya sea para la nota y para que la corrección sea más fácil? Puedo hacerlo en una copia de la tarea para no editar la original

Gracias

**Comment by fgbruna** [comment]
Puedes documentarla hasta hoy a las 13:59 según esta [issue](https://github.com/IIC2233/Syllabus/issues/589

**Comment by Hernan4444** [comment]
@ChayoPerez @fgbruna En esa issue se dice que tienen hasta hoy a las 13:59 para el **Readme**. Pero la documentación que se solicitó en la tarea es parte de la tarea, es decir, que era hasta ayer a las 13:59. Puedes hacerlo si crees que eso ayudará a la corrección, pero no contará en la nota.

Saludos ✌️
