### ISSUE TITLE
Ayuda poner foto con filtro dibujo en label

### ISSUE THREAD

**Issue by elisafdz** [IIC2233/syllabus#605]
Hola!
Hice la función de filtro dibujo y funciona bien. La función retorna el path donde se guardo la foto con el filtro pero cuando en el frontend trato de poner esa foto abriendo el path que retorno la función (el mismo donde se guardo la foto) aparece null pixmap. Al revisar la foto con el filtro si esta guardada en el path. Puede ser que haya algún problema con el paso de RGBA a png que permite que la imagen  con el filtro se vea correctamente pero que al tratar de ponerla en una label diga nula pixmap? No se si se entiende pero muchas gracias!

**Comment by jeschuwirth** [comment]
Saludos,
Si entendí correctamente su issue el problema es que la imagen se crea correctamente y puedes abrir imagenes correctamente en tu código, pero cuando intentas leer el png creado por el filtro te retorna un null pixmap.

Es un error muy curioso, intenta lo que dice en el siguiente [link](https://stackoverflow.com/questions/16990914/python-pyqt-qpixmap-returns-null-for-a-valid-image), si eso no funciona sube tu código a tu repositorio e intentaré ayudarte, pero encuentro muy curioso el error.

**Comment by elisafdz** [comment]
Graciass, use lo que salía en el link y ya no aparece null pixmap, sin embargo, sigue sin mostrarse la imagen en la interfaz

**Comment by elisafdz** [comment]
<img width="214" alt="Screen Shot 2019-06-21 at 10 57 46 PM" src="https://user-images.githubusercontent.com/48265957/59958648-0efda100-9478-11e9-9aa7-8c2a86b2c45b.png">
<img width="399" alt="Screen Shot 2019-06-21 at 10 57 29 PM" src="https://user-images.githubusercontent.com/48265957/59958650-145aeb80-9478-11e9-97f8-37c882ed1e0c.png">
<img width="144" alt="Screen Shot 2019-06-21 at 10 57 38 PM" src="https://user-images.githubusercontent.com/48265957/59958654-19b83600-9478-11e9-93b4-9ef6681160b1.png">
Esta es la función en la que busco mostrar la imagen con el filtro en el label_foto_perfil a partir del path que retorna la función filtro dibujo.

**Comment by jeschuwirth** [comment]
No entendí si sigues teniendo un problea o si lo solucionaste 😅 , pero si lo sigues teniendo recuerda que el formato de la imagen luego de aplicado el filtro es PNG, por lo que el path final debe ser imagen_filtrada.png en vez de jpg

**Comment by elisafdz** [comment]
Sigo teniendo el problema! cambie el formato a png pero sigue sin aparecer
la imagen en la interfaz. Probe el método isNull que retorna True si el
QPixmap indicado es nulo y cuando escribo el código como en el link que me
mandaste isNull retorna False pero aun así no se muestra la imagen.

**Comment by jeschuwirth** [comment]
Sube tu código a tu repositorio y lo reviso :octocat:

**Comment by elisafdz** [comment]
Gracias, ya lo arregle! había un error en la transformación de rgb a png
que permitía ver la imagen con el filtro pero no mostrarla en un QLabel

**Comment by tomascortes** [comment]
Hola @elisafdz me dirías cual fue tu error?? que me pasa exactamente lo mismo 😅

**Comment by elisafdz** [comment]
Hola! Yo tenia un problema en el IEND!! Pero también lo que te puede estar pasando es que en mac tienes que hacer click afuera de la ventana para que se actualice la foto!
