### ISSUE TITLE
Re-subir Tarea

### ISSUE THREAD

**Issue by rifibla** [IIC2233/syllabus#605]
si subo de nuevo mi tarea, esta cuanta como atrasada?

**Comment by Dnpoblete** [comment]
Hola @rifibla, la tareas fueron recolectadas a las 20:00, por lo que si modificas tu tarea ahora y no quieres que sean considerados los cambios, se tomará en consideración el último commit antes del plazo de entrega. En el caso contrario, en que si quieras que se consideren los cambios esto se considerará como entrega atrasada y tendrás que seguir los pasos que explico Enzo en el último anuncio a través de canvas:

![image](https://user-images.githubusercontent.com/42362982/79818639-4964f280-8356-11ea-98bc-40bdf21862d7.png)

**Comment by rifibla** [comment]
muchas gracias!

**Comment by Dnpoblete** [comment]
Hola @sbcorrea, en el caso que mencionas hay varias opciones posibles, en primer lugar, si lo mencionaste en el ReadMe en el plazo de entrega del ReadMe (que esta vez fue en conjunto con la entrega de la tarea ayer a las 20:00), el ayudante que revise tu tarea cambiará los caracteres que mencionas y probablemente a lo más te descuente 1 pto en descuento de ayudante por eso. En el segundo caso, en donde no entregaste el ReadMe en conjunto con la tarea, el ayudante no sabrá lo que mencionas, por lo que se abren dos posibilidades, la primera, es que rellenes el formulario de atraso y la segunda es que después de que se revise la tarea mandes a recorregir y se descuente por hacer cambio de líneas.
A fin de cuentas siempre habrá un pequeño descuento por cambiar líneas o considerar otro push, por lo que queda a tu criterio la opción que te guste más.

Espero haber respondido tu duda y quería saber si entregaste el ReadMe ayer a las 20:00, por que no me quedo muy claro eso.

Quedo atenta a tus comentarios! :smile:

**Comment by Dnpoblete** [comment]
De nada ☺️, si sirven para estos casos en particular, pero para que tengas ojo la idea no es hacerlo un hábito, ya que es más trabajo para los ayudantes y también tiene un descuento asociado!

**Comment by sbcorrea** [comment]
Nunca más 🙅 generalmente le habría hecho esto en los 2 días de ReadMe, pero hoy estaba optimizando mi código para reutilizar a futuro y le encontré este error de puro viciosa 😅
