### ISSUE TITLE
Log tamaño del mensaje

### ISSUE THREAD

**Issue by sebacarrasco** [IIC2233/syllabus#605]
Hola, cuando uno hace el log de que un cliente recibe un paquete de información de algún cliente al indicar el tamaño del mensaje se refiere a mostrar el tamaño del mensaje que escribió el cliente que lo mandó? O si yo estoy enviando un diccionario en el que uno de los valores es el mensaje debería mostrar el tamaño del diccionario?
La misma pregunta para el detalle del contenido del mensaje en el log.

**Comment by gatochico** [comment]
Hola! 

Primero y solo como un recordatorio, el caso que estás dando se dividiría en 2: El primer evento sería el cliente enviando un mensaje al servidor, y el segundo el servidor distribuyendo el mensaje a el/los clientes apropiados. 

Ahora, con respecto a tus dudas: 

El tamaño del mensaje equivaldría al tamaño de **todo lo que quieres mandar previo a la codificación** (incluyendo el diccionario). Por ejemplo, digamos que tu diccionario completo sin hacer la codificación pesa 500 bytes, y luego de la codificación pesa 644 bytes, el log debería mostrar los 500 bytes.

El contenido del mensaje, eso si, debería ser el **mensaje concreto enviado y no el diccionario completo**. Como en el ejemplo del enunciado:
![image](https://user-images.githubusercontent.com/37161120/70237252-89c82900-1745-11ea-80f6-f7f550e37f3a.png)

En cualquier caso, puedes añadir este supuesto a tu README y citar esta issue para evitar problemas :see_no_evil: .

Éxito en tu tarea!
