### ISSUE TITLE
Plazo entrega README

### ISSUE THREAD

**Issue by RenatoVWS** [IIC2233/syllabus#606]
Hola, quería preguntar sobre cuál es el plazo de entrega del README, porque en el mail sobre la extensión de plazo salía que se debía entregar junto con el código, pero cuando avisaron que se cerró el plazo de entrega, solo mencionaban que era para entrega de código y de diagrama.
Saludos!

**Comment by entamburini** [comment]
Hola @RenatoVWS, 

Se subía con el resto del código, como fue avisado cuando se dio la extensión del plazo.

Saludos! :v:
