### ISSUE TITLE
Consulta sobre .gitginore

### ISSUE THREAD

**Issue by alvarocisternas** [IIC2233/syllabus#606]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ]x Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola!
Tengo una duda con respecto a como hacer el gitginore cuando quiero omitir una carpeta que está dentro de otra carpeta.

En mi caso tengo dos carpetas: 
1) frontend
2) backend
Cada una de ellas tiene dentro una carpeta __pycache__ .

Está correcta esta escritura para el .gitginore? :
frontend/__pycache__/

Quedo atento,

Saludos.

**Comment by alvarocisternas** [comment]
el pycache lleva guiones

**Comment by JadrinaDA** [comment]
Sí eso está bien, con los guiones sería frontend/_pycache_. Avísame si tienes más dudas, saludos!

**Comment by alvarocisternas** [comment]
@JadrinaDA el pycache al ser una carpeta no llevaría un slash  " / " al final?

**Comment by JadrinaDA** [comment]
No es necesario pero también funciona con el slash al final.

**Comment by alvarocisternas** [comment]
muchas gracias !!
