### ISSUE TITLE
Setear Posicion (x,y) de QLabel en Qwidget

### ISSUE THREAD

**Issue by andreslyon** [IIC2233/Syllabus#606]
Hola, para la tarea me gustaria poder setear la posicion (x,y) de un qlabel relativa al Qwidget en que está en el centro de la imagen que posee.
Pongo una imagen para explicar:
![issue](https://user-images.githubusercontent.com/26236216/32013796-87db5fe4-b992-11e7-9fdd-96f3ba2f7449.png)
He buscado harto por internet y no he podido encontrar cómo se hace, Existe algún método para hacerlo?
Muchas gracias

**Comment by hanavarrete** [comment]
Hola! Para que quieres hacer eso? Porque si solo deseas obtener el centro es cosa de sumar los lados/2 a cada eje, pero dudo que eso sea el objetivo. Tal vez te podamos ayudar más con eso.

**Comment by hanavarrete** [comment]
Si deseas rotar, esto puede ayudarte (ojo que es pyqt4): https://stackoverflow.com/questions/31892557/rotating-a-pixmap-in-pyqt4-gives-undesired-translation

**Comment by andreslyon** [comment]
Quiero hacerlo, porque el centro de la imagen me parece una posición más lógica para generar los rangos de visión, chequeo de colisiones, etc. Si esque no se puede hacer esto, claro que está la opcion de sumar lado/2 a cada eje. pero si existe una manera mas limpia de hacerlo sería bacan.
Gracias por el Link de todos modos ;)
