### ISSUE TITLE
Termino dias competencias

### ISSUE THREAD

**Issue by caroizquierdo** [IIC2233/syllabus#606]
Cuando se terminan los dias de competencias se tiene que terminar el programa o puede hacer otra DCCumbre?
Si es que se puede hacer otra DCCumbre esta parte todo desde el menu de inicio y se parte otra partida o sigo con la misma a delegacion y se vuelve al menu principal no mas?

**Comment by hsazos** [comment]
¡Hola @caroizquierdo !

Según enunciado, el usuario debería tener la elección de salir o hacer una nueva simulación al terminar la simulación actual. Esta debería incluir una nueva elección de delegación y nombre de usuario, por lo que parte desde el menú de inicio.

¡Animo con la tarea!🦕

**Comment by amahns1** [comment]
Hola!

¿Debemos resetear todos los valores que cambiaron durante las simulaciones anteriores? Si es el caso, ¿de qué manera es aconsejable resetear todos los atributos que cambiaron?

Muchas gracias!!

**Comment by hsazos** [comment]
¡Hola @amahns1 !

Para resetear tus atributos hay varias posibilidades, es algo bastante flexible. Un manera es un método encargado de resetearte todo o puedes guardar los stats iniciales en un .txt  y recuperarlos de ahí. Es decisión tuya como hacerlo y como te resulte mas fácil programarlo.

¡Animo con la tarea! 🦕

**Comment by caroizquierdo** [comment]
hola algo que no me quedo claro es que si se vuelve a iniciar la partida el dia actual vuelve a 0? seria el unico parametro que se conserva

**Comment by hsazos** [comment]
@caroizquierdo Si, tu día actual vuelve a 0.
