### ISSUE TITLE
Duda amigos, actualización amigos.json

### ISSUE THREAD

**Issue by itplanella** [IIC2233/syllabus#606]
Hola! al hacer un amigo se debe actualizar también el archivo amigos.json?
gracias de antemano.

**Comment by SamWeinstein** [comment]
Hola! De la mano de esta pregunta quería aprovechar de hacer otra pregunta muy cercana. De ser como lo dice @itplanella, es decir, al amistar a dos usuarios se debe actualizar el archivo amigos.json, (que es donde esta almacenado el grafo), cuando guardo la información con json en el archivo amigos.json, todo se guarda bien pero cambia un poco el formato, el diccionario entero queda en una linea en lugar de ser vertical como viene originalmente el archivo, esto tiene relevancia alguna? o se puede guardar la información así sin problemas para la corrección? De estar mal esta forma, como puedo hacer que se guarde el diccionario de manera vertical y no en una sola linea? Gracias.

**Comment by SamWeinstein** [comment]
Creo que me apresuré en hacer mi consulta pues ya descubrí la forma de mantener el formato con sort_keys= y indent=, por ende solo queda la consulta original de @itplanella, perdón por el spam :)

**Comment by Dnpoblete** [comment]
Hola @itplanella, la respuesta es sí, ya que en el enunciado dice que"Debes actualizar el archivo que almacena el grafo en ese momento", lo que se refiere a que cada vez que se realicen cambios al grafo se debe actualizar en ese momento el archivo amigos.json.

Éxito con la tarea! :smile:

**Comment by JuanDlugo** [comment]
Entonces podemos entregar un archivo amigos.json, distinto al inicial?

**Comment by lily416** [comment]
@JuanDlugo no es necesario que sigan el formato en que les entregamos el json (con saltos de líneas e indentación) ya que es para facilitar la lectura del archivo (como humano), pero como dice @SamWeinstein usando `sort_keys` e `indent` pueden lograr algo similar al formato que les entregamos.

Saludos y éxito en la tarea 👋🐧
