### ISSUE TITLE
Duda enunciado

### ISSUE THREAD

**Issue by monicabelen** [IIC2233/Syllabus#606]
En el enunciado dice "No se debe permitir ingresar a usuarios con el mismo nombre. El sistema debe cargar su puntaje actual en la interfaz. Si ingresa por primera vez, su puntaje es cero". 

Esto quiere decir que:

1. Los puntajes se van guardando en función de las veces que abro mi "cuenta de juego"??? (que no tiene contraseña así que cualquiera puede entrar al juego de alguien si se sabe el username).
2. Cuando dice que no se permite ingresar usuarios con el mismo nombre significa "usuarios con el mismo nombre en ese momento" o "usuarios usados anteriormente que tengan el mismo nombre que quiero ocupar ahora". En el último caso, lo que dije en el punto 1 no se podría hacer, es decir, los puntos no los podría guardar cada que quiero usar el mismo username. 

Gracias!

**Comment by arturodelreal** [comment]
Hola, es lo del punto 1 (no se permite usuarios con el mismo nombre en un momento, pero si se puede acceder con un usuario creado en el pasado)
Saludos

**Comment by monicabelen** [comment]
Gracias! Otra pregunta, cuál de las dos es buena práctica:

1. Que el frontend tenga un atributo cliente
2. Que el cliente tenga un atributo frontend
3. Da lo mismo?

**Comment by rpalmaotero** [comment]
@monicabelen en general, la buena práctica y regla de oro es que exista una separación de responsabilidades (https://en.wikipedia.org/wiki/Separation_of_concerns) entre los módulos de tu aplicación. Para mi tiene más sentido la opción 1) pero es una preferencia totalmente personal. Si para ti tiene más sentido diseñar la arquitectura de otra forma, respetando la separación de responsabilidades, no hay problema.
