### ISSUE TITLE
Llantos diarios

### ISSUE THREAD

**Issue by nicoparraguez** [IIC2233/Syllabus#606]
En el enunciado dice Promedio llantos diarios por atracción , lo que se quiere es mostrar por cada atracción su promedio de llantos o el promedio general de todas las personas que lloran en la simulación debido a las atracciones

de antemano, muchas gracias

**Comment by monicabelen** [comment]
Hola, lo que se pide es que por **cada** atracción calcules el promedio de llantos.

**Comment by sjkinast** [comment]
Hola no estoy entendiendo bien a que se refiere esa respuesta pero el promedio de llanto diarios por atracción se puede interpretar como numero de llantos en una simulacion divido por los dias y por el numero de atracciones , ahi tambien se obtiene el numero de esperado de llantos por cada atraccion en cada dia
