### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by fuentes145** [IIC2233/syllabus#607]
cuando  el servidor va a mandar información con socket.sendall(data) aveces me tira este error BrokenPipeError: [Errno 32] Broken pipe. es muy raro porque a veces haciendo la misma acción este aparece y otras veces no.

**Comment by jmwielandt** [comment]
Hola,

¿Está tu código en tu repo?

**Comment by fuentes145** [comment]
si ya lo subi

**Comment by jmwielandt** [comment]
Hola, he estado un rato probando tu código y no me sale ese error.

¿En qué sistema operativo está? ¿En qué situación aparece?

**Comment by fuentes145** [comment]
estoy con mac y el error aparece con socket.sendall(data) y en cualquier momento indiferentemente de la data que este mandando

**Comment by jmwielandt** [comment]
Estamos averiguando qué puede estar pasando, si cambias el sendall por un send, sigue pasando?
