### ISSUE TITLE
Convolution Matrix

### ISSUE THREAD

**Issue by csantiagopaz** [IIC2233/syllabus#607]
Hola, tengo una duda a respecto a la convolución, estaba con el mismo error de una issue( dimensión =! ) Fue al link que el ayudante dejo y intenté hacer la covolucion , al pasar la matriz a 1D numpy.convolute me retorna una matriz más grande que la del ejemplo de la png ( O = I * K)
Intenté ocupar mode="full","same","‘valid’" ,pero todos me tiran una matriz más grande
Quería saber cómo debo ocupar el convolute(que modo ocupar(full,same o valid) y como arma la matriz para ocupar en los parametros, (cómo la armo?[ [fila],[fila]...[fila]]?? O [[colina,...[coluna]]? [fila,fila,fila], [coluna,coluna,coluna ), ocupo numpy.ravel() directamente en la matriz o ocupo un numpy.array y en el array ocupo ravel?
gracias adelantado, :3 
Estoy atento a la issue, necesito desa información para continuar

**Comment by jeschuwirth** [comment]
Saludos,

Te recomiendo mirar el siguinte [link ](https://stackoverflow.com/questions/48097941/strided-convolution-of-2d-in-numpy), en el cual el usuario implementa un método que hace convolución en una matriz, para esta tarea necesitas que el argumeta stride(s) = 1 y el argumento padding(p)=0.

Entiendo que no es exactamente lo que buscabas que ya no ocupa numpy.convolute, pero busqué en google un rato y no recomendaban ese método, ya que convolute estaba hecho para 1D arrays y hay formas mejores y más sencillas de hacerlo, de todos modos si lo quieres ocupar el modo correcto es "valid"). 

Para armar la matriz te recomiendo ocupar el modo: 
```
[fila1[columna1,columna2],
 fila2[columna1,2columna2],
 fila3[columna1,2columna2]],
 fila4[columna1,2columna2]]
```

Entiendo que no es la respuesta que esperabas pero no conozco lo suficiente numpy como para darte solución más cercana a lo que buscabas.

Suerte en la tarea!

**Comment by csantiagopaz** [comment]
Muchas gracias <3

**Comment by csantiagopaz** [comment]
Hola Jeschuwirth, aún no me funciona, intente hacer con: 

```
def stride_conv(arr1, arr2, s, p): 
     beg = 0 
     end = arr2.shape[0] 
     final = [] 
     for i in range(0, arr1.shape[0] - 1, s): 
         k = [] 
         for j in range(0, arr1.shape[0] - 1, s): 
             k.append(np.sum(arr1[beg + i: end + i, beg + j:end + j] * (arr2))) 
         final.append(k) 

     return np.array(final) 
```
que es el único que ocupa los 2 parámetros que tu menciono, al intenta pasar cualquier matriz + las 2 matrizes 
```
M1 = np.array([[1, 0],
               [0, -1]])
M2 = np.array([[0, 1],
               [-1, 0]])
def matriz_gradiente(m1, m2, matriz):
    c1 = stride_conv(matriz, m1, 1, 0)
    c2 = stride_conv(matriz, m2, 1, 0)
```
    # resto del codigo de la matriz_gradiente...

```
if __name__ == "__main__":
    imagen = gp("teste.png")  # get_pixels
    matriz_gris = (to_gris(imagen))
    matriz_gradiente(M1, M2, np.array(matriz_gris))
```

y por ultimo esta el error que me genera:
![image](https://user-images.githubusercontent.com/42182095/59969116-66514f00-9514-11e9-9472-60507ace3fa2.png)

**Comment by jeschuwirth** [comment]
@csantiagopaz, la verdad no había ni probado la función, pero parecía funcionar 😅 

![image](https://user-images.githubusercontent.com/37160256/59969636-635c5b80-9520-11e9-84f1-31b6fdb23561.png)

Los siguientes cambios la arreglan, recuerda que si la ocupas tienes que citar el stackoverflow.

Suerte!

**Comment by csantiagopaz** [comment]
Ahora me funciono, de verdad Muchas Gracias ;3 <3

**Comment by isihirmas** [comment]
Hola! Pero entonces ninguno de los mode sirve para numpy.convolute ? (osea no me sirve para el filtro?)
