### ISSUE TITLE
Problema con QSound

### ISSUE THREAD

**Issue by sebamoreno2811** [IIC2233/syllabus#607]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Estoy intentando usar el QSound pero me sale un error al importarlo, lo estoy importando asi:
from PyQt5.QtMultimedia import QSound
se tiene que hacer de otra forma?. 

El error que me sale es: 
ImportError: dlopen(....) Symbol not found: _SSLCopyALPNProtocols

**Comment by Juampisaez** [comment]
Hola @sebamoreno2811 
Y si importas lo siguiente, pasa lo mismo?
`from PyQt5.QtMultimedia import QMediaPlayer`

**Comment by sebamoreno2811** [comment]
@Juampisaez si, me aparece el mismo error, estoy intentando hacer igual que en la AS2 pero me sigue tirando el mismo error, gracias por responder!

**Comment by Juampisaez** [comment]
Y te funciona PyQt5?
Lo encuetro raro, estos errores suceden cuando la libreria no se ha instalado

**Comment by sebamoreno2811** [comment]
osea todo lo demas me funciona perfecto, por eso tambien estoy perdido, de hecho la as2 me funcionab la musica y ahor ya no

**Comment by Juampisaez** [comment]
@sebamoreno2811 y si pruebas con desinstalar e instalar nuevamente pyqt5?

**Comment by sebamoreno2811** [comment]
@Juampisaez tambien lo hice y sigue dando el mismo error :/

**Comment by Juampisaez** [comment]
Ya mira, hace unos dias consteste un problema parecido, me percate que tienes mac jeje. Te recomiendo desinstalar la version de pyqt que tienes he instalar la versión 5.15.4 de pyqt.

Avisame si te funciona!

**Comment by sebamoreno2811** [comment]
como hago para instalar esa version en especifico? se puede desde el termina o tiene que ser desde alguna pagina? ( y si tengo mac jajaja)

**Comment by sebamoreno2811** [comment]
@Juampisaez tampoco me funciono :( lo descargue asi:
pip3 install PyQt5==5.15.4

**Comment by Juampisaez** [comment]
Lo comente con los ayudantes y la posible solucion que surge es que desinstales completamente pyqt5, verifiques que ya no esta instalado, e instalar la version que ya te comenté. Si eso no resulta tendria que preguntar nuevamente.
