### ISSUE TITLE
socket.error: [Errno 48] Address already in use

### ISSUE THREAD

**Issue by benjamimo1** [IIC2233/Syllabus#607]
Como evitar este error? Es resultado de que el OS no termina con el proceso del server pese a cerrar la terminal.

**Comment by akaminetzkyp** [comment]
Cambiar el puerto soluciona esto. Saludos!

**Comment by benjamimo1** [comment]
Pero no puedo estar cambiando el puerto todo el rato D:

**Comment by akaminetzkyp** [comment]
No estoy 100% seguro, pero creo que cerrando el socket con `close()` no deberían haber problemas.

**Comment by fdominguezclaro** [comment]
Cierra primero el cliente y luego el server, así me funcionaba en la actividad por lo menos.

**Comment by iqacevedo** [comment]
@benjamimo1, ¿pudiste solucionar tu problema con lo que te dijeron tus compañeros ?

Saludos !

**Comment by benjamimo1** [comment]
@iqacevedo Me parece que con cerrar los clientes primero se soluciona. Gracias por el seguimiento!

**Comment by jgramsch** [comment]
me pasaba a cada rato, despues encontré un comando para poder matar procesos en los puertos, en debian (y los linux basados en este ) se puede usar :
fuser -k 'puerto'/tcp
a lo mejor para mac o windows haya algo parecido

Saludos!
