### ISSUE TITLE
limite de paciencia

### ISSUE THREAD

**Issue by mblejeune** [IIC2233/Syllabus#607]
Hola! cuando se especifica el atributo paciencia dice que no se supera su límite de paciencia, entonces cuando aumento o disminuye su paciencia no puede superar este limite, pero no logro encontrar el limite en ninguna parte :(

**Comment by IchottMano** [comment]
@mblejeune Hola!

El límite de paciencia es una variable que debes calcular como una variable aleatoria que distribuye normalmente, como dice el enunciado.

Saludos!

**Comment by mblejeune** [comment]
aaaah me confundi yo entonces! pense que era como elegir un maximo entre la paciencia actual mas algo que se suma, y el limite jaja, gracias!!! :)
