### ISSUE TITLE
QSound

### ISSUE THREAD

**Issue by monicabelen** [IIC2233/Syllabus#608]
Es suficiente con poner lo siguiente para que se reproduzca el sonido? No me funciona con solo eso..

self.sound = QSound("path", self)
self.sound.play()

**Comment by mbfuster** [comment]
#no soy ayudante 
Yo use ese código pero dentro de un objeto qmainwindow (creo que tb serviría un qobject) y me resultó :D

**Comment by hanavarrete** [comment]
lo que dice @mbfuster  es correcto. Saludos!

**Comment by monicabelen** [comment]
Funcionó! Gracias!

**Comment by chapito96** [comment]
Hola, intento hacer lo que señalan para la reproducción pero no lo logro hacer funcionar.
Además googlee sobre Qsound y habian más formas de hacerlo pero ninguna me ha funcionado
