### ISSUE TITLE
maximo personas en fila atraccion

### ISSUE THREAD

**Issue by mblejeune** [IIC2233/Syllabus#608]
Hola! Puedo asumir un valor maximo de personas que pueden esperar en una fila de atraccion ? para así poder ver cuanto tiempo le queda por subirse al juego y cuanto esperara antes de abandonar la fila

**Comment by Arcoirisky** [comment]
Hola! No puedes asumir eso O: La espera en una fila es determinada por la paciencia. Pueden haber un millón de personas en la fila pero, si la última tiene una paciencia nivel dios, puede esperar tranquilo aunque los que estén entre él y la atracción se vayan yendo de a poco :D
