### ISSUE TITLE
Diagrama de Clases

### ISSUE THREAD

**Issue by domja** [IIC2233/syllabus#608]
Hola! queria saber si es posible entregar el diagrama de clases atrasado si el resto de la tarea ya lo entregue dentro del plazo, osea que me descuenten en el diagrama pero no en el resto de la tarea. Se puede?
Graciass

**Comment by entamburini** [comment]
Hola @domja!,

De poder subir se puede :o. Pero no lo recomiendo, puesto que igual se considera como entrega atrasada de la tarea y por ende tendrías al menos 5 décimas de descuento (aumentando cada momento que pasa). 

Saludos! :v:
