### ISSUE TITLE
qt Designer

### ISSUE THREAD

**Issue by SarahEverke** [IIC2233/Syllabus#608]
Hola

descargué qt de https://www1.qt.io/download-open-source/?hsCtaTracking=f977210e-de67-475f-a32b-65cec207fd03%7Cd62710cd-e1db-46aa-8d4d-2f1c1ffdacea , pero solo se descarga qt creator y no qt designer
¿Qué puedo hacer?

**Comment by hanavarrete** [comment]
Hola! en esta issue hay varios problemas con sus respectivas respuestas de instalación de designer. Revisa si hiciste alguno de esos casos. Si después de eso aún no tienes solución, comenta acá para que te podamos ayudar 😀

**Comment by iqacevedo** [comment]
Hola!

Intenta con escribir en consola:
`pip 3 install PyQt5-tools` o bien `pip install PyQt5-tools`.

Si estás en windows debería aparecer en una ruta similar a : 
C:\Users[Acá va su nombre de usuario del Pc]\AppData\Local\Programs\Python\Python36\Lib\site-packages\pyqt5-tools\designer

**Comment by SarahEverke** [comment]
Cuando uso pip3 me sale lo siguiente:
![captura de pantalla 2017-10-25 a la s 18 46 48](https://user-images.githubusercontent.com/30681133/32024438-ee674910-b9b2-11e7-863f-c13f4b62fdcc.png)

Cuando uso pip:
![captura de pantalla 2017-10-25 a la s 18 47 20](https://user-images.githubusercontent.com/30681133/32024442-f139783e-b9b2-11e7-9819-53cc59d4636f.png)

Y usé el link mencionado en la issue, pero solo me descargo qt creator :(

**Comment by iqacevedo** [comment]
@SarahEverke puedes probar cambiando PyQt5-tools por pyqt5-tools?

**Comment by SarahEverke** [comment]
Me sucedió lo mismo :(

**Comment by tcgarrido** [comment]
Intenta con cmd + barra de espacio, luego escribes designer. Debería aparecerte :c

**Comment by jtagle2** [comment]
Solucionado durante la sala de ayuda
