### ISSUE TITLE
Contenidos AS3

### ISSUE THREAD

**Issue by alvarocisternas** [IIC2233/syllabus#608]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola!

Para la AS3 del 10/06 entran los contenidos de la semana 11 y semana 12? o solo los de la semana 11?

Quedo atento,

Saludos :)

**Comment by aaossa** [comment]
Hola @alvarocisternas, para la actividad sumativa de esta semana (AS3), se evaluarán los contenidos de ambas semanas. Los contenidos de la semana 11 ("Estructuras nodales I") y de la semana 12 ("Estructuras nodales II") están muy relacionados, de hecho los de la primera son la base de los de la segunda :ok_hand: Si tienes alguna pregunta adicional de esto, avisa por acá mismo 🙌
