### ISSUE TITLE
archivos.csv

### ISSUE THREAD

**Issue by mleon17** [IIC2233/syllabus#608]
Los archivos csv pueden venir tanto las filas como columnas en diferente orden? O solamente las columnas? Gracias

**Comment by baosse** [comment]
Holaa @mleon17 !
El contenido de los archivos puede estar en cualquier orden (tanto filas como columnas). Sin embargo, la primera fila de estos será siempre el header, que te indicará  el orden de los datos de las delegaciones (las columnas).
Espero que esto te sirva! Mucho éxito :blue_heart:
