### ISSUE TITLE
ejecutar archivos.py, archivo ejecutado no existe

### ISSUE THREAD

**Issue by F-arellano** [IIC2233/syllabus#609]
cuando ejecuto directamente el archivo py del server o del client me arroja error porque supuestamente no existen los archivos que llamo en el modulo (los cuales si estan, y son abiertos correctamente cuando corro el archivo en el editor). A veces me pasaba que el directorio en el cual estaba ejecutando el modulo mi editor no correspondia al del archivo y me pasaba lo mismo, ¿sera ese el problema? y de ser asi, ¿como lo soluciono?

**Comment by DCCollao** [comment]
Hola! 
¿A qué te refieres con ejecutar directamente?
¿Qué editor usas, y cómo ejecutas el código en él?
