### ISSUE TITLE
Archivos enviados servidor - cliente

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2233/Syllabus#609]
Hay algo que si bien podría probar, quiero preguntarlo para estar seguro, pero por ahí igual lo voy a probar.

Yo se que puedo serializar clases, objetos, funciones y estructuras clásicas con pickle, pero igual me caben dudas en algunos casos, por ejemplo:

¿Que pasa si tengo un objeto que tiene un atributo que es otro objeto? Los dos de clases creadas por mi.
Al deserializar (después de una serializacion, obvio) dicho objeto, ¿Voy a tenerlo tal cual era antes de serializarlo? ¿Se va a mantener intacto el atributo que es un objeto de otra clase creada por mi?

Probé algunas cosas al respecto y me pasó lo siguiente:

Al enviar un objeto serializado, luego de deserializarlo el programa me tiró error diciendo esto:
`Can't get attribute 'NombreClase' on <module '__main__' from 'C:/Users/jorge riesco/Desktop/Repositorio/jorgeriesco-iic2233-2017-1/Tareas/T06/server/server.py'>`

Lo que entiendo como que no reconoce a la clase de este tipo en el modulo en el que estoy. Se me ocurre solucionar esto importando la clase, pero me pasa que es un poco complicado, ya que estoy en una carpeta distinta. Puedo obviamente averiguar como hacerlo, se que no debe ser difícil, pero aun así me gustaría saber una forma más simple de hacer lo que quiero hacer, si alguien me la dice, porfa.

**Comment by DiegoAndai** [comment]
Hola!, como dices tu problema es altamente googleable:

https://stackoverflow.com/questions/27732354/unable-to-load-files-using-pickle-and-multipile-modules/27733727#27733727

Ese es el primer link que aparece al buscar tu error y ahí mismo aparecen dos soluciones. Porfavor trata de no preguntar cosas que se pueden encontrar fácilmente en internet.

Saludos.
