### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by mblejeune** [IIC2233/Syllabus#609]
hola! termine mi tarea, pero al llamar a un key de un diccionario que cree que le doy un atributo de una clase que tiene si o si ya que es un atributo que saca de un csv, a veces tira este error:

TypeError: 'NoneType' object is not subscriptable

Y obvio cuando lo tira, no imprime las estadisticas :(
y solo pasa a veces :( y intenté buscar y me sale que es porque puede que sea None, pero es imposible ya que ese atributo se lee y guarda bien en el objeto

**Comment by jfbahamondes** [comment]
Yo creo que el problema está en el objeto. Ese error se tira cuando realizas, por ejemplo:

`a = None`
`print(a[1])`

Entonces en alguna parte estás haciendo que, si ocurre tal cosa, tu variable es tal objeto, pero si no ocurre, tu variable se está guardando como un None.
