### ISSUE TITLE
error en filtro 

### ISSUE THREAD

**Issue by JupaOlivares** [IIC2233/syllabus#609]
Hola! segui los pasos de la funcion para pasar la imagen a png pero no me funciona (el archivo PNG generado no se ve) hay alguna forma de saber que puede ser lo que tengo malo porque python no me genera errores.

**Comment by jeschuwirth** [comment]
En la siguiente línea
![image](https://user-images.githubusercontent.com/37160256/59959573-758abb00-9488-11e9-9abf-cfe43b7b3ebc.png)

Supongo que codificas el número 13 porque en el enunciado dice:
![image](https://user-images.githubusercontent.com/37160256/59959581-96531080-9488-11e9-8d1e-78f0997f69a4.png)

Pero recuerda que ese 13 depende del largo y ancho de la imagen, por lo tanto no es una constante.

En resumen debes cambiar el 13 por el valor que te entrega
![image](https://user-images.githubusercontent.com/37160256/59959591-b551a280-9488-11e9-81b3-4274c1c49533.png)

en tu imagen.

Suerte en la tarea!

**Comment by jeschuwirth** [comment]
Hola!

Cuando creas el IDAT pareces tener un par de errores, primero que nada te recomiendo utilizar lo que te recomiendo el enunciado:

![image](https://user-images.githubusercontent.com/37160256/59959848-dddb9b80-948c-11e9-9fc7-9013495699a6.png)

Segundo, el largo que guardas en esta parte no es el mismo largo anterior, sino el largo de toda la información que guardas en este paso (el largo de lo que comprimes con compress). 

También tienes que recordar agregar los 0 al inicio de cada fila en este mismo paso, 
![image](https://user-images.githubusercontent.com/37160256/59959864-1d09ec80-948d-11e9-8a08-ae338b575165.png)

No probé e código hasta que funcionara, pero creo que con eso te debería ayudar bastante, si te quedan muchas dudas o crees que lo tienes pero falla un poquito recuerda que puedes descargar la imagen filtrada de la issue #592 y ver como son sus bytes para compararlos con los que tienes, de seguro ahí encuentras algún patrón.

Suerte con la tarea!

**Comment by fbpesenti** [comment]
Tuve un problema similar y encontré esta pagina http://www.libpng.org/pub/png/apps/pngcheck.html
descarga el archivo para tu sistema operativo (expórtalo) y usa el comando en consola
**pngcheck -vt tu_imagen.png**
 lo que hace es leer tu imagen y te dice en que parte de tus bytes esta tu error 
Ojala te sirva!

**Comment by JupaOlivares** [comment]
> Hola!
> 
> Cuando creas el IDAT pareces tener un par de errores, primero que nada te recomiendo utilizar lo que te recomiendo el enunciado:
> 
> ![image](https://user-images.githubusercontent.com/37160256/59959848-dddb9b80-948c-11e9-9fc7-9013495699a6.png)
> 
> Segundo, el largo que guardas en esta parte no es el mismo largo anterior, sino el largo de toda la información que guardas en este paso (el largo de lo que comprimes con compress).
> 
> También tienes que recordar agregar los 0 al inicio de cada fila en este mismo paso,
> ![image](https://user-images.githubusercontent.com/37160256/59959864-1d09ec80-948d-11e9-8a08-ae338b575165.png)
> 
> No probé e código hasta que funcionara, pero creo que con eso te debería ayudar bastante, si te quedan muchas dudas o crees que lo tienes pero falla un poquito recuerda que puedes descargar la imagen filtrada de la issue #592 y ver como son sus bytes para compararlos con los que tienes, de seguro ahí encuentras algún patrón.
> 
> Suerte con la tarea!

Estoy haciendo lo del metodo compress pero me tira error en el formato que le estoy ingresando, mis bytes son de la forma [[(0,x,x,x),(0,x,x,x)],[(0,x,x,x),(0,x,x,x)]]
