### ISSUE TITLE
Abrir más de una ventana 

### ISSUE THREAD

**Issue by llloyola** [IIC2233/Syllabus#609]
A la hora de desplegar los puntajes más altos, tiene que ser necesariamente actualizando la misma ventana o puedo abrir otra con dichos puntajes (teniendo abierta la ventana del menú principal + la de los puntajes históricos)? Es necesario que TODO ocurra en una misma ventana?

**Comment by vijuarez** [comment]
Hola!

No esta especificado, por lo que queda a criterio tuyo.

Saludos!

**Comment by llloyola** [comment]
Bkn! Muchas gracias :)
