### ISSUE TITLE
Cambio de líneas

### ISSUE THREAD

**Issue by NikiHV** [IIC2233/syllabus#609]
Hola!
¿Habrá alguna instancia para solicitar cambios de línea previo a la recorreción? 
En un caso regular se especificaría en el README, pues este se podía entregar hasta dos días posterior a la entrega de la tarea. Pero esta vez el cierre del plazo de la tarea fue simultánea al README.

**Comment by entamburini** [comment]
Hola @NikiHV,

En términos cortos, no, no habrá una instancia adicional :disappointed: . Es verdad que en el caso regular tendrías más tiempo para especificar en el README, pero este era un caso excepcional y por eso no pensamos en otra instancia :o 

Saludos! :v:

**Comment by NikiHV** [comment]
Ok! Gracias!
