### ISSUE TITLE
Error test de crear plano

### ISSUE THREAD

**Issue by jtvvtj** [IIC2233/Syllabus#61]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Sucede que en el terminal al probar el test 0, el de crear planos, me aparece el siguiente error: 
AssertionError: Lists differ: [] != [['X', 'X', 'X'], ['X', 'X', 'X'], ['X', 'X', 'X']]

Sin embargo, al probar aquello, en realidad si genero la lista   [['X', 'X', 'X'], ['X', 'X', 'X'], ['X', 'X', 'X']].

Y me tira error con cada plano, y cada uno lo probe y los ejecuta como debería en VSCODE.

**Comment by jtvvtj** [comment]
Me pasa lo mismo con todos los test de la clase Predio, me los tira mal. Pero probando con el codigo de cada test, en VSCODE, me lo tira bueno.

**Comment by dvillas28** [comment]
Cuando estas en la terminal, en que ruta estas ejecutando los tests?

**Comment by jtvvtj** [comment]
Tareas/T1/ en esta ruta

**Comment by jtvvtj** [comment]
ya resolvi mi problema

**Comment by cristobalramos21** [comment]
@jtvvtj disculpa, estaba revisando los test cases nuevamente antes de entregar la tarea y me está arrojando el mismo error que a ti, y antes me tiraba buenos los test cases, como lo arreglaste?
