### ISSUE TITLE
Duda respecto al formato de entrega

### ISSUE THREAD

**Issue by jpperez5** [IIC2233/syllabus#61]
¿Existe alguna formalidad con respecto al nombre del archivo que los ayudantes van a correr, o basta con que sea un nombre simple como "tarea 00.py"?

**Comment by jmwielandt** [comment]
Hola!

En principio para esta entrega no importa el nombre, pero sí debe cumplir con las restricciones de _Formato de entrega_ y ser un nombre descriptivo. Por lo general, `main.py` basta. También `lego_sweeper.py` puede ser un nombre interesante.

Saludos!
