### ISSUE TITLE
Sobre el material

### ISSUE THREAD

**Issue by cronda1** [IIC2233/syllabus#61]
Hola 😃 , quería saber si para las actividades se puede usar o no el material del curso yy también si los ejercicios propuestos están enfocados para preparar las actividades o dar un poco de práctica para las tareas (o ambas). Gracias!

**Comment by knight-who-say-ni** [comment]
Hola!!
No hay problema con que tengas abiertos los contenidos durante las actividades, ya sean formativas o sumativas 😃.
En cuanto a lo segundo, la idea de los ejercicios propuestos es que practiques lo aprendido en los contenidos,  no estan relacionadas con las actividades y tareas (pero al hacerlas es más probable que te manejes con los contenidos, por lo que podrás hacer mejores actividades y tareas).

Saludos!!
