### ISSUE TITLE
Modificación tasa de minerales/deuterio y cantidad de soldados/magos

### ISSUE THREAD

**Issue by llloyola** [IIC2233/Syllabus#61]
En un planeta de no conquistado, sólo se pueden aumentar dichas cantidades o también la modificación permite disminuirlas?

**Comment by IchottMano** [comment]
Hola!
Tal y como dice el enunciado, sólo se pueden aumentar estas cantidades, no disminuirlas.
Saludos!

**Comment by Cschavez** [comment]
hola! y las cantidades de los soldados se aumentan según criterio propio?

**Comment by IchottMano** [comment]
@Cschavez Efectivamente! Sin embargo recuerda que no se puede pasar del tope establecido.
Saludos!
