### ISSUE TITLE
DUDA CÓDIGO: al cambiar una variable también se actualiza otra.

### ISSUE THREAD

**Issue by isajofre** [IIC2233/Syllabus#61]
* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Tengo una duda sobre el funcionamiento de código. Para contextualizar diré que tengo dos listas lista1 y lista2
En algún momento escribí
lista1 = lista2
sin embargo luego lo cambié por 
lista1 = lista2.copy()
y aún así cada vez que actualizo lista1 cambia también lista2, he intentado distintas cosas, incluso cambiar toda la lógica de mi código y los nombres de las variables pero me sigue pasando lo mismo. Quizás quedó guardado en alguna especie de memoria o algo así. No sé si me podrían ayudar, muchas gracias!

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by vicentethomas** [comment]
Hola! El problema es que cuando haces `lista1 = lista2` no estás haciendo una copia de la lista, si no referenciando la misma lista que ya existe con otro nombre. Ahora, cuando tu haces lista1 = lista2.copy(), sí se crea una copia de la lista que se separa de la original. El problema es que este tipo de copia se llama "shallow copy" y se refiere a que lo que hay dentro de la lista son solo **referencias** a otros objetos. Por lo tanto, si tenemos una lista dentro de nuestra lista copiada, en realidad lo que tenemos es una referencia a la misma lista en la copia y en la original. Entonces, si en la lista dentro de la lista copiada hacemos un cambio, este cambio también va a estar en la lista original. (Es un poco enredado de explicar, [acá](https://stackoverflow.com/questions/184710/what-is-the-difference-between-a-deep-copy-and-a-shallow-copy#:~:text=What%20is%20Shallow%20Copy%3F,the%20memory%20address%20is%20copied.) hay más info.)

Ahora para resolver este problema, en general lo que se hace es una deepcopy que te permite hacer también una copia de los elementos dentro de la lista y no solo una referencia. Para usarlo debes importar la librería `copy`, y hacer
```
lista 1 = copy.deepcopy(lista2)
```
Espero te sirva, saludos!

**Comment by isajofre** [comment]
Sii! ahí se solucionó, gracias!!
