### ISSUE TITLE
Duda con archivos de tableros solucionados

### ISSUE THREAD

**Issue by masoto22** [IIC2233/Syllabus#61]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/21)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/20)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, tengo una duda con los tableros en la carpeta Archivos. Leí en otra issue que luego para probar funcionalidades pueden utilizarse otros tableros, además de los de esa carpeta (al corregir). Mi duda es, los archivos de tableros solucionados son para algo más que verificar las funcionalidades? Ya que si no, no entiendo si luego se deben compararlas soluciones que se hagan en el programa a esos archivos? Entiendo o supongo que son solo de ejemplo y por ej para la funcion verificar_solución, pero prefiero asegurarme 😄 Gracias

**Comment by terelopezc** [comment]
Hola @masoto22! Tal como dices los ejemplos de tablero que se les entregan son para poder ir probando las diferentes funcionalidades que se piden y ver si las funciones realizan la acción correcta para un tablero por solucionar vs uno ya solucionado. Los archivos subidos como solución son **solo un** ejemplo de cómo se puede solucionar un tablero, pero este puede tener múltiples soluciones, así que no hay que comparar nada ya que puede haber más de una opción correcta.
