### ISSUE TITLE
SyntaxError Visual Studio Code

### ISSUE THREAD

**Issue by fcbahamondes** [IIC2233/syllabus#61]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola, cuando uso visual studio code me aparece un error de un archivo llamado builtins.pyi. Es un archivo externo el cual no he abierto. Eso si no me dificulta al hacer correr mi codigo en otra pestaña, solo que me aparece en la parte de los problemas. 

Adjunto imagen 
<img width="1141" alt="Captura de pantalla 2021-03-26 a las 17 50 43" src="https://user-images.githubusercontent.com/80771151/112691345-ecbe6180-8e5b-11eb-9025-c36070848229.png">

Al hacer click en el error me abre esta ventana 
<img width="1141" alt="Captura de pantalla 2021-03-26 a las 17 51 03" src="https://user-images.githubusercontent.com/80771151/112691387-fd6ed780-8e5b-11eb-92fa-868259bbedef.png">

Mi duda es que no se a que se debe eso, pensaria que mi codigo esta mal pero no me arroja error en el.

**Comment by pabloist** [comment]
Hola!

El error que te aparece en consola hace referencia a la forma en la que se definen las funciones, en las cuales un valor por default, como se explicará a continuación, no puede anteponer a una variables no default.

**ESTO ES INCORRECTO**

def funcion(hola = "soy", una = "funcion", x, y):
   print("ERROR")

**ESTO ES CORRECTO**"

def funcion(x, y, hola = "soy", una = "funcion"):
   print("SUPEER :)")

La explicación de por qué uno es considerado correcto y el otro no, es un poco larga, así que por el momento ten cuidado al definir tus funciones(La razón de que el error aparecía en otra parte corresponde a que el error se genera en un built-in interno de python).

**Comment by aaossa** [comment]
Solo paso para agregar que eso se explica en los contenidos de la [semana 1 "args y kwargs"](https://github.com/IIC2233/contenidos/blob/main/semana-01/7-args-kwargs.ipynb), por si quieres repasar y entender más sobre esto 👌
