### ISSUE TITLE
Problema con Git Push

### ISSUE THREAD

**Issue by fabiolagaruti** [IIC2233/Syllabus#61]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

Estaba super bien pasando mi tarea al repositorio personal con git push. 
Pero después empecé a editar el README.md de mi tarea desde GitHub porque me gustaba que se pudiera visualizar gráficamente los cambios hechos, sin embargo, esto hizo que ya no funcionara el git push. Me salieron los siguientes errores:

![image](https://user-images.githubusercontent.com/101306933/160050996-baff7360-3984-41b1-8769-1719e316cd78.png)
![image](https://user-images.githubusercontent.com/101306933/160051048-92bbb1aa-ce37-444c-a2b0-44fa3b61ade5.png)

**AYUDAA** como lo arreglo??

**Comment by Emiliax16** [comment]
Hola @fabiolagaruti . Estás haciendo commits verdad? recuerda que primero es:
`git add archivo`
`git commit -m "mensaje"`
`git push`

Si esto no funciona, puede que te sirva la información de esta página:
https://stackoverflow.com/questions/24114676/git-error-failed-to-push-some-refs-to-remote

Avísame si se solucionó el problema. Saludos!
