### ISSUE TITLE
Error seguidores.csv

### ISSUE THREAD

**Issue by bpardobravo** [IIC2233/syllabus#61]
Hola, me parece que hay errores en el archivo de seguidores. En C8 vemos que j1torcas sigue a m4narea, pero m4narea no existe (cambió a m4nareauwu en A27 después de arreglar los usuarios con menos de 8 caracteres).
No sé si habrás más errores de este tipo
Salu2

**Comment by DCCollao** [comment]
Gracias por avisar! Ya está actualizado el archivo.
