### ISSUE TITLE
A que menu ir al salir del menu publicaciones realizadas

### ISSUE THREAD

**Issue by bicos12** [IIC2233/Syllabus#61]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ]X Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ ]X Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

**Comment by Emiliax16** [comment]
Hola @bicos12 ! dado que el enunciado y la distribución indican cosas distintas en esa parte del menú, se considerará bueno de ambas maneras, volver al menú principal o al menú publicaciones desde publicaciones realizadas. Lo mejor es seguir el enunciado tal cual lo hiciste, pero si cualquier estudiante ya realizó el código según la distribución de puntajes, no habrá problema! gracias por mencionarlo. Saludos 💟
