### ISSUE TITLE
Duda sobre la estructura del repositorio privado, en particular, de la sección Tareas

### ISSUE THREAD

**Issue by ceojedab** [IIC2233/Syllabus#61]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.

### Contenido

Buenas. Mi duda es la siguiente : **¿Importa para la corrección de la tarea si creo una carpeta T1 dentro de la carpeta T1 del repositorio privado?**
Esto lo hice no a propósito, sino que al utilizar el comando" cp -r "en Ubuntu (estoy trabajando con Ubuntu desde Windows) se crea automáticamente otra carpeta T1 dentro de T1. 
Por otro lado, si esta modificación estructural llegara  afectar la corrección, no tengo problema en eliminar dicha carpeta y copiarla de nuevo, lo que sucede es que no sé cómo hacer eso sin sobreescribir la carpeta T1 del repositorio privado, con el comando cp. 

Muchas gracias.

**Comment by roahoki** [comment]
Hola Carlos, te recomiendo fuertemente que evites tener una carpeta T1 dentro de otra que se llame T1. Es decir, acostumbrate a tener 

T1
 - main.py
 - otros_archivos

y evita

T1
 - T1
   - main.py
   - otros_archivos

Para este caso, no es necesario que ocupes el comando cp. De todas maneras, puedes hacerlo como se te haga más cómodo siempre y cuando cumplas con tener una carpeta T1 en tu repositorio de la forma que te comento :)
