### ISSUE TITLE
importar modulo constantes

### ISSUE THREAD

**Issue by jfpena1** [IIC2233/syllabus#61]
Es posible copiar el archivo constantes.py hacia afuera de la carpeta data(pero aun adentro de la carpeta de la tarea) para asi poder importarla de manera facil en el archivo de las clases?

O hay que hacer algo especial que no involucre hacer una copia de constantes.py para poder imoortar ese modulo posteriormente?
muchas gracias

**Comment by hbkim94** [comment]
Hola!

El archivo `constantes.py` no debe moverse, pero te aseguro que es muy simple importar archivos/módulos desde una carpeta en Python, y que hay diversas formas de hacerlo (_hint: google es tu mejor amigo_).

Saludos!

**Comment by jitorcas** [comment]
Hola! en base a eso, donde debo guardar la partida actual? en Data?
