### ISSUE TITLE
Ordenes previas

### ISSUE THREAD

**Issue by IchottMano** [IIC2233/Syllabus#61]
En la tarea, si ingreso como un usuario que este previamente en users.csv, ¿debo darle los DCC por regisrarse? además muchos tienen ya órdenes previas por lo que ¿deben estar registrados en los mercados correspondientes? de ser asi, ¿obtienen el bono de 50000 monedas?
Lo siento si son muchas preguntas,
Muchas gracias

**Comment by ifcarrera** [comment]
Hola, 

los usuarios que están en users.csv ya fueron registrados anteriormente. Por lo tanto, tal como indicas, no reciben los 100.000 DCC ni los 50.000 de las divisas correspondientes. 

Saludos

**Comment by IchottMano** [comment]
Y el dinero que se ganó o se perdió en las ordenes anteriores? o podemos asumir que todos empiezan con 0 de cada currency

**Comment by rihanuch** [comment]
pero como lo hacen para negociar entre ellos? porque si no se pierde nada al hacer el intercambio, entonces seria super extraño ya que ambos estarían creando bienes de la nada, ya que no se puede entrar en balance negativo 💰

**Comment by IchottMano** [comment]
Además, debido a que las ordenes anteriores con creadas al azar, existen usuarios previos que deberían tener saldos negativos en ciertas divisas, lo cual no es posible

**Comment by sebacruzd** [comment]
Si se intenta hacer una _order_ que llegaría a dejar al usuario con saldos negativos, no se debería ejecutar dicha _order_. Saludos!

**Comment by movaldivia** [comment]
No me quedó claro con cuanto currencie comienzan los usuarios ya registrados

**Comment by Jiparavich** [comment]
x 2

**Comment by dmolina2** [comment]
@ifcarrera No me queda claro con lo que dices que los usuario previamente registrados no reciben ni los 100.000 DCC y tampoco los 50.000 de las divisas. Si es así, no podrían realizar ninguna de las orders que estan registradas en los archivos csv...

Por favor si es posible aclarar este tema .

Saludos!

**Comment by Arcoirisky** [comment]
Es que, los usuarios ya registrados en cierto mercado ya recibieron el bonus del mercado nuevo. Por eso no deben recibirlo O:! Es como si esas cuentas ya hubieran recibido ese regalo antes de que tu las tomaras en cuenta, por lo que al entrar nuevamente en el mercado X (al cuál ya estaban ingresados) no se les da nada y siguen como si no pasara nada. ¿Se entiende?

**Comment by rihanuch** [comment]
@Arcoirisky pero que pasas si estoy registrado (vengo de la base de datos entregada) y no he emitido ninguna orden? Para efectos prácticos aun no me registro en ningún mercado! 😿

**Comment by dmolina2** [comment]
@Arcoirisky Lo que sucedería entonces sería que todos partirían con 0 en todas sus monedas?
 No me calza porque así si ejecutamos todas las orders que vienen por la base de datos, quedarían algunos usuarios con saldos negativos en algunas monedas, lo que por enunciado no es posible...

Saludos!

**Comment by iqacevedo** [comment]
Hola a todos

@rihanuch efectivamente no estarías registrado en ningún mercado, pero si te registras en alguno recibirias los 50.000 de ese mercado (con lo que podrias comenzar).

@dmolina2, no partirían necesariamente en 0, ya que si tienen orders activas pueden estar intentando vender monedas (mientras no las vendan, aun las tienen en su poder y su saldo no es 0 por ello). Respecto a lo de los saldos negativos, tal como dice @sebacruzd más arriba si alguna order dejaria al usuario con saldo negativo no se debería ejecutar (ustedes deben controlar de que eso no ocurra).

Saludos !
