### ISSUE TITLE
Expansión del radio de Incendios

### ISSUE THREAD

**Issue by KnowYourselves** [IIC2233/Syllabus#61]
Hasta lo que tengo entendido, cuando uno ingresa al programa e ingresa una fecha es como una simulacion, osea que dada la fecha indicada tenemos que calcular la expansión del radio de los incendios, pero este calculo tiene que ser discreto?

Osea si ponemos una fecha por ejemplo, del año 2020, tenemos que considerar todos los pronosticos y el efecto que tuvieron en cada incendio, por cuanto tiempo y considerar eso en los cálculos? O asumimos que ninguno de los pronosticos aplica por la fecha y calculamos directamente como el valor base de 500?

**Comment by egbusch** [comment]
Hola 
Tambien tengo una duda sobre el radio del incendio. En la formula puntos poder = superficie afectada * potencia , el la superficie esta en km**2 o en m**2 ??

**Comment by rpalmaotero** [comment]
@KnowYourselves aunque un pronóstico haya terminado igual puede afectar significativamente un incendio. Imagina un incendio que se apaga debido a un temporal de lluvia. Debe ser considerado por el programa.

@egbusch el radio se trabaja en metros, por lo que son metros cuadrados.
