### ISSUE TITLE
Uso de exec() en QmessageBox

### ISSUE THREAD

**Issue by rfigueroa314** [IIC2233/syllabus#610]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

No estoy seguro de que el exec que ocupo en mi codigo para el QmessageBox esta prohibido o no. Por favor si pueden ver mi codigo y confirmarme, ocupo uno en la linea 309 del archivo logica de movimiento del backend.

Quedo atento a la respuesta, muchas gracias.

**Comment by tqmbanados** [comment]
Hola! La prohibición a `exec` es únicamente a la librería de python. En tu caso, estas utilizando un método propio del QMessageBox, necesario para mostrarlo correctamente! Así que ningún problema :)
Espero haberte sido de ayuda!

**Comment by rfigueroa314** [comment]
perfecto, gracias!
