### ISSUE TITLE
Filtros - 2xCancion

### ISSUE THREAD

**Issue by asdegoyeneche** [IIC2233/Syllabus#610]
Hola! 

Podemos asumir que las canciones son del largo necesario para poder hacer el filtro x2 (i.e almenos tengan 40 segundos para así la duración en el juego sean los 20 segundos pedidos). Caso contrario, las eliminamos de las posibles canciones de la sala?, se repite n veces hasta completar el tiempo?, etc?. La duda me salió por la canción de Queen que está recortada y dura solo 23 segs :c

Gracias!

**Comment by hanavarrete** [comment]
Si!. Saludos!

**Comment by frvalenzuela** [comment]
Respecto a la misma sección del filtro; "se forma un arreglo en que cada elemento de ´este son secciones del ´area data, donde el tama˜no de cada secci´on viene dado por el n´umero de bytes por muestra (N). El
arreglo resultante ser´a del tipo [Data(desde 0 a N bytes), Data(desde N a N+1 bytes, .., ..]" 

Lo anterior no afectaría a los samples de cada canal, solo separaría los chunks de los canales, no debería aplicarse alguna modificación a los chunks? Porque hasta el momento no veo la diferencia con solo duplicar la frecuencia, pues si los chunks no sufren una transformación estos no deberían separarse necesariamente.

**Comment by rfenzo** [comment]
Tengo la misma duda que @frvalenzuela , no entiendo nada de la canción x2, segun entiendo del enunciado, no hace nada diferente al equalizador (la parte de la frecuencia).

**Comment by acrojas2** [comment]
Hola! 
No entiendo bien la siguente instrucción para hacer este filtro, podrían darme un ejemplo más ilustrativo del arreglo resultante?
<img width="703" alt="captura de pantalla 2017-06-16 a las 12 07 31 a m" src="https://user-images.githubusercontent.com/26121354/27211526-dddc7cc0-5227-11e7-96ae-7b5b0d7b5155.png">
Saludos!

**Comment by FernandoPieressa** [comment]
Hola!
Lo explicare con strings para ver si es mas fácil entender y como los bytes se manejan de forma similar

Digamos tienes

holacomoestas

Ahora SI separas en muestra N=3 entonces queda el arreglo resultante quedaría como

[hol,aco,moe,sta,s]

Saludos!

**Comment by fcgfaura** [comment]
Con lo que dices el arreglo resultante sería entonces `[Data(0,N), Data(N, 2N), Data(2N, 3N), ...]`

**Comment by Veenty** [comment]
Si entiendo bien en terminos de algoritmo, esto seria algo como lo siguiente?

Supongamos que la cosas son imagenes. Sample rate = 1 segundo, lo grabado es:

[A,A,B,B,C,C] 

Con esto veriamos que los primeros 2 segundos se ve una A, luego una B y luego una C

Ahora quitamos todas las pares.

[A, B, C]

ahora veriamos cada letra por 1 segundo.

Esto es lo que esperan que hagamos?

**Comment by pizquierdo2** [comment]
@veenty Pero eso, al igual que con el ecualizador, haría que se escuche el doble de agudo.. Y supongo que no es lo que se espera que pase.
