### ISSUE TITLE
Duda administrativa controles

### ISSUE THREAD

**Issue by rihanuch** [IIC2233/Syllabus#610]
Hola! Queria saber como podia obtener mis controles (los ya corregidos)(independiente de si ya paso el plazo de recorreccion) para tener un registro de ellos y comparar con lo que sale en el google Spreadsheets! Gracias!😁😄

**Comment by fringlesinthestreet** [comment]
Hola están en el DCC (cuarto piso edificio San Agustín). Ahí hay una casilla con los controles :).

Cualquier cosa pregúntale a Yessenia (la secretaria).
