### ISSUE TITLE
Duda Interfaz T03

### ISSUE THREAD

**Issue by mariajesusbraun** [IIC2233/syllabus#610]
Hola! No se por qué al ejecutar el programa no se abre la interfaz. En el "dock" del computador se muestra una ventana nueva en blanco, pero no se abre, a pesar de apretarla.

**Comment by DCCollao** [comment]
Hola!
Probablemente esa ventana esté [crasheando](https://es.wikipedia.org/wiki/Crash_(inform%C3%A1tica)), y debería imprimirte un error en consola al hacerlo. 
Si no te imprime ningún error, probablemente no estés usando el [hook](https://github.com/IIC2233/contenidos/blob/master/semana-06-07/1-interfaces-gr%C3%A1ficas.ipynb) de errores que recomendamos para PyQt5. Utilizar el hook hace mucho más fácil el debuggeo de tu aplicación, pues te dice dónde buscar el error!

Avísame cómo te va😁

**Comment by mariajesusbraun** [comment]
Implementé el hook de errores y sigue sin imprimirme ningún error :(

**Comment by DCCollao** [comment]
Revisé el código que tenías en tu repositorio (actualizado hace 4 horas) y encontré que tienes un llamado a `self.recibir_msj_servidor()` en el  `main.py` correspondiente a tu cliente, dentro del `__init__` de la clase Cliente. Ese método es el que le pasas al Thread para escuchar al servidor, y borrando su llamado en el ``__init__``puedo abrir correctamente la ventana e ingresarle un input (esto para asegurarme de que no ha dejado de funcionar)
![image](https://user-images.githubusercontent.com/37167447/70284651-7b105f00-17a3-11ea-8cbe-215a62cc061a.png)

Quedo atento!

**Comment by mariajesusbraun** [comment]
Gracias!!

Tengo otra duda.. en el servidor, al codificar un mensaje (diccionario) para ser enviado, se codifica el mensaje, y además un mensaje None. He buscado harto por qué pasa, pero no he encontrado respuesta.

**Comment by DCCollao** [comment]
Hice `print(type(msj))` en la línea 51 de tu main.py de servidor, y eso es un NoneType que después envías en la línea 52, probablemente esa sea la causa del None que te aparece recibido después en cliente.

**Comment by mariajesusbraun** [comment]
Ahí cache por qué, gracias!!

**Comment by mariajesusbraun** [comment]
Tengo una otra duda!! Al haberse verificado el usuario, creo una instancia de VentanaPrincipal y le hago hide() a VentanaInicio y show() a VentanaPrincipal, pero no pasa ninguna de las dos cosas: la ventana inicio sigue mostrandose, y no se muestra la ventana principal :(
