### ISSUE TITLE
Ej. Propuesto semana 6 - 2.1

### ISSUE THREAD

**Issue by CristobalUrzua** [IIC2233/syllabus#610]
Hola, no entiendo muy bien que es lo que significa la instrucción que se da:
La métrica para medir que tanto se parecen dos textos es en cuantos índices los textos tienen exactamente el mismo carácter
Pero, ¿esto es por palabra?, es decir, la primera con la primera del segundo texto? 

Gracias de antemano

**Comment by KnowYourselves** [comment]
Hola @CristobalUrzua!

Esto es pcaracter por caracter. Por ejemplo:

```python3
"Hola!, ¿Como estas?"
"No lo se Tu sabras?"
```

Si vamos índice por índice, tiene la primera `o` y los tres últimos caracteres, `as?`, por lo cual la métrica entre estos dos textos es 4.

Espero haberte ayudado!
