### ISSUE TITLE
Duda sobre dónde guardar archivos entregados

### ISSUE THREAD

**Issue by mgbriones** [IIC2233/syllabus#611]
los archivo como sprites o amigos.json, donde hay que tenerlos guardados? somo libres de elegir si queremos tenerlo  guardado tanto en la carpeta de cliente como servidor??
Me gustaría guardar la carpeta sprites en la carpeta client, es posible?

**Comment by DCCollao** [comment]
Hola! Esta pregunta ya fue respondida en #582 y #544. Si aún así te quedan dudas, hazmelo saber.

Éxito!
