### ISSUE TITLE
Tiempo filtrado canciones

### ISSUE THREAD

**Issue by akaminetzkyp** [IIC2233/Syllabus#611]
Hola!

He estado trabajando harto en el filtro que promedia los chunks de la canción. Creo que funciona correctamente, creando una canción con ruido.

Sin embargo, tengo una duda con respecto al tiempo de creación de estas canciones. Mi programa se demora 20 segundos en filtrar una vez una canción. No parece tanto tiempo, pero si multiplicamos esto por las 18 canciones que están en la carpeta entregada obtenemos que el programa se demoraría 6 minutos en filtrar cada canción una vez. Ahora, debemos tomar en cuenta que el orden del filtro puede estar entre 1 y 10, por lo que ahí nuestro tiempo de creación podría aumentar hasta a una hora. Una hora cada vez que se enciende el servidor (ya que el orden del filtro es aleatorio).

He creado varios métodos para filtrar las canciones, pero todos se demoran ese tiempo o más. El que estoy usando actualmente lee y escribe los bytes directamente, por lo que creo que es eficiente.

¿Es este el tiempo que demora la acción usualmente? Si no lo es, ¿de qué manera se podría agilizar el proceso?

Saludos!

**Comment by nivek0o0** [comment]
No sería más rápido aplicar el filtro sólo sobre los 20 segundos de bytes que vas a reproducir en vez de aplicarlo sobre los 50 megabytes?

**Comment by akaminetzkyp** [comment]
Buena idea. La consideraré. Gracias!
