### ISSUE TITLE
Pausa de música

### ISSUE THREAD

**Issue by minsoos** [IIC2233/syllabus#611]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola, tengo la duda de si es posible para la música para que siga reproduciéndose desde donde se paró, busqué, pero no encontré nada. De esta forma, hay algún problema con que cuando pause el juego la música empiece de 0 cuando se reanude?
Gracias

**Comment by tomasrosenberg** [comment]
Hola @minsoos!

No hay problema si al reanudar la canción después de pausar, esta vuelva a comenzar desde 0.

Éxito programando!

**Comment by minsoos** [comment]
Gracias!
