### ISSUE TITLE
Bonus - Fullscreen / Pantalla Completa

### ISSUE THREAD

**Issue by B-Dominguez** [IIC2233/Syllabus#611]
Holaa,
1.- Pantalla completa se refiere a ventana maximizada? o realmente _fullscreen_ como por ej con los videos de Youtube?

2.- Para el bonus _Fullscreen_ dice _implica reescalar todos los elementos_. Esto se refiere a aspectos de la interfaz como posición y proporción de botones, mensajes, etc,; o a las células y movimientos etc también?

En otras palabras, debemos escalar también el tamaño de células y sus movimientos? Como si el mapa siguiera teniendo las mismas dimensiones? (por ej si antes medía 50x50 pixeles y se movía a 25 pixeles/ seg, que ahora mida 70x70 pix y se mueva 35 pix/seg por la proporción de la ventana)

**Comment by TomasSalvadores** [comment]
Buenas!
1.- Es solo escalar el tamaño de la ventana al tamaño de la pantalla de tu computador de modo que _abarque_ toda la pantalla. No es entrar en modo fullscreen.
2.- **Es reescalar todo**, tamaño de células, movimiento, botones, etc. Agrandar todo el juego.

Suertee

**Comment by B-Dominguez** [comment]
Ok graciaaas! Solo quiero aclarar, es necesario que la velocidad también sea proporcional?
