### ISSUE TITLE
Class FIFinderSyncExtensionHost is implemented in both

### ISSUE THREAD

**Issue by Juaco97** [IIC2233/syllabus#611]
Hola! Cuando hago correr el programa y trato de cambiar la foto de perfil por alguna que escoja el cliente, me arroja el error: 

> Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff897273c8) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x10eb35f50). One of the two will be used. Which one is undefined.

Busqué en internet y al parecer sería error de Mac, pero no entiendo bien cómo solucionarlo o de qué otra forma reemplazar lo que estoy haciendo (tengo actualizado el código en mi repo y el error sería en la linea 87 del archivo Front_VentanasSalas) por si a alguien le ocurrió lo mismo y me pueda ayudar 😢 😭

**Comment by Juaco97** [comment]
Logré hacer que cambie la foto en la interfaz, a pesar de que me arroje el error. ¿Hay algún problema en la corrección con eso? (el servidor y el cliente funcionan normal igual, solo que en la consola del cliente aparece el error)

**Comment by gatochico** [comment]
Hola! Uso windows y corrí tu tarea y nunca me apareció el error anterior, así que no debería haber problema siempre y cuando, como dices, el programa siga corriendo. Si quieres ser más precavido aún, puedes poner en tu README un aviso con lo que acabas de mencionar y así intentaremos que un ayudante que no use MacOS revise tu tarea 👍 

PD: La foto de perfil no se mantiene puesta si cierro sesión y entro con las mismas credenciales :0 , ya que en ningún momento se envía al server para almacenar. Un recordatorio para que lo implementes antes de la entrega!

**Comment by Juaco97** [comment]
> Hola! Uso windows y corrí tu tarea y nunca me apareció el error anterior, así que no debería haber problema siempre y cuando, como dices, el programa siga corriendo. Si quieres ser más precavido aún, puedes poner en tu README un aviso con lo que acabas de mencionar y así intentaremos que un ayudante que no use MacOS revise tu tarea 👍
> 
> PD: La foto de perfil no se mantiene puesta si cierro sesión y entro con las mismas credenciales :0 , ya que en ningún momento se envía al server para almacenar. Un recordatorio para que lo implementes antes de la entrega!

Hola @gatochico 
¿Es obligación que mantenga la foto de perfil si vuelve a abrir el programa? Como no lo vi en el enunciado no lo había agregado :s

**Comment by lily416** [comment]
@Juaco97 En el enunciado sale:
![image](https://user-images.githubusercontent.com/26393515/59970045-f26e7100-952a-11e9-83b1-6c11708517bf.png)

La foto de perfil se considera parte de la información del usuario, por lo que se debe poder acceder a ella aunque se cierre la sesión y se vuela a acceder a ella.

Saludos y éxito con la tarea 👋 💪
