### ISSUE TITLE
Desarrollo ayudantía 5

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#611]
Hola!
No encontré la solución de la ayudantía 6 en syllabus. Podrían subirla por favor?
Gracias :smile:

**Comment by Camila-sty** [comment]
en syllabus*

**Comment by Drpinto1** [comment]
¡Hola! 

Ya está disponible la solución en Syllabus y durante el día publicaremos el video en Canvas.

¡Saludos!
