### ISSUE TITLE
Parametros

### ISSUE THREAD

**Issue by mleon17** [IIC2233/syllabus#611]
Hola, debo parametrizar los números decimales de las formulas para calcular los puntajes de cada competencia también???? y como puedo importar todo los parámetros a mi archivo principal?? gracias

**Comment by jitorcas** [comment]
Hola! @mleon17 

Con respecto a tu primera pregunta, la issue #534 la responde!

En cuanto a la manera de importar, lo puedes hacer de la forma que te comode más. Para evitar importar uno a uno cada parámetro, podrías hacer lo siguiente:

```python
import parametros as p 

p.PARAMETRO
```

Mucho éxito en la tarea! 🥇
