### ISSUE TITLE
Duda Cliente + Interfaz

### ISSUE THREAD

**Issue by dfvasquez** [IIC2233/Syllabus#612]
Hola! 😄 

Estaba revisando una ayudantía de Networking 2016-1 para conectar bien el Cliente con la Interfaz y me surgió una duda:

La clase ClientWindow tiene como atributo al Cliente y la clase Cliente tiene como atributo ClientWindow...
¿esto no es referencia circular? 

Me surgió la duda de si es correcto hacerlo de esa forma o no y si no es correcto, ¿cómo se haría? :c

Adjunto link ayudantía: https://github.com/IIC2233-2016-1/syllabus/blob/master/Ayudantias/AY14%20-%20Networking/chat%20varios%20clientes%20con%20desconexion%20e%20interfaz/client_interfaz.py

Gracias 😃

**Comment by hanavarrete** [comment]
Hola! Si, esto es referencia circular, tu deberías manejarlo con señales. (ups) Saludos!

**Comment by acrojas2** [comment]
@hanavarrete
Hola!
Tenía exactamente la misma duda que @dfvasquez, pero no me queda claro quién se debería tener a quién si el cliente(socket) al juego(interfaz) o el juego al cliente, he buscado en los semestres pasados y en google y no he encontrado una respuesta concluyente.
Saludos!

**Comment by hanavarrete** [comment]
Esa pregunta ya sería soplarte la modelación. Aún quedan muchos días como para darles hints🙄

**Comment by iqacevedo** [comment]
@acrojas2 lo que si puedes considerar es que el cliente(socket) va a estar enviándole información a la interfaz continuamente (para que esta se actualice), mientras que la interfaz le enviará información al socket para que este la envié al servidor. Piensa en la T05, en como los Threads se comunicaban con la interfaz, y las cosas que hacia tu interfaz cuando tu interactuabas con ella. Como dice @hanavarrete deben ocupar señales para que se de esa comunicación correctamente.

Saludos !

**Comment by fcgfaura** [comment]
No se usa de todas formas referencia circular con señales?, porque si A contiene a B, A llamaría a los métodos de B directamente (bien), entonces B mandaría señales, pero para eso, B tiene que tener a A, para crear una señal con algún método de A, o no?

**Comment by Hernan4444** [comment]
@fcgfaura no necesariamente, si A contiene a B, A puede conectar algunas señales de B con sus propios métodos y por lo tanto B nunca tendrá a A. Si revisas la issue #571 hay un ejemplo "backend instancia objetos del frontend" donde Backend contiene a Frontend y se conectaron señales del frontend al backend sin necesidad de que el frontend tuviera al backend como atributo.

Saludos!

**Comment by fcgfaura** [comment]
Entiendo, ahora, en ese ejemplo solo el frontend le envía ordenes a Tower y Nexus, si tower le quisiera mandar alguna orden al Frontend lo podría contener sin ser referencia circular cierto?, y además ¿sería igualmente válido que en Tower, que tiene al Frontend,  hiciera los trigger.connect() del Frontend, para así no tener la clase Backend?

**Comment by Hernan4444** [comment]
tal como dices, en el segundo ejemplo. Tower podría contener al Frontend pero no es una buena practica porque estás haciendo que un sub-objeto del backend contenga al frontend mientras que lo ideal sería que solo el backend contuviera al frontend. Si deseas que la Tower ejecute algo del frontend, tendrías que agregarle un trigger a la Tower y desde el backend hacer algo del estilo:
```
self.tower.trigger.connect(self.frontend.algun_metodo)
```

Y así la tower cuando haga `self.trigger.emit(*args)` se ejecutará un metodo del frontend y en ningún momento Tower tuvo acceso al objeto frontend o viceversa.
