### ISSUE TITLE
Fecha Entregable

### ISSUE THREAD

**Issue by Drpinto1** [IIC2233/Syllabus#612]
Saludos, al inicio del enunciado dice que el entregable se debe subir a un cuestionario del Siding antes del domingo 3 de junio del 2018, 23:59 horas, pero en la sección 5 del enunciado (Entregable), dice que se debe entregar junto con el código en nuestros repositorios, cuál es la correcta?
De ser la primera, ese diagrama de clases podría diferir con el diagrama correspondiente al programa final, de ser la segunda, el plazo seguiría siendo el mismo que para la primera?, esto tiene el mismo problema de posibles diferencias; lo anterior tendría descuento?
Gracias de antemano por su respuesta :smile:

**Comment by FernandoPieressa** [comment]
Hola! Tienes razón, van a tener plazo hasta el domingo 3 de junio. Vamos a cambiar el modo de entrega a que sea por Siding en un cuestionario como las otras entregas. Esto lo anunciaré pronto.

Saludos!

**Comment by naquiroz** [comment]
@FernandoPieressa ya se hizo el anuncio? Que no he recibido nada.

**Comment by FernandoPieressa** [comment]
Si! Al final fue un Google form actualizado en el enunciado
