### ISSUE TITLE
Cambios notas T03

### ISSUE THREAD

**Issue by llloyola** [IIC2233/Syllabus#612]
Acabo de notar un cambio en las notas de la tarea 3. ¿Las están reajustando? ¿Se puede saber a qué se debe el cambio? Me bajó la nota :pensive:

**Comment by nmaturana97** [comment]
a mi igual :(

**Comment by felipecr00** [comment]
Podrian cargar los feedbacks??

**Comment by FernandoPieressa** [comment]
Hola! Los feedbacks serán entregados lo antes posible, el problema fue la formula utilizada para calcular la nota, las que están ahora son las correctas.

Saludos!
