### ISSUE TITLE
Duda sobre movimiento

### ISSUE THREAD

**Issue by rfigueroa314** [IIC2233/syllabus#612]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, en el enunciado solo sale que el movimiento tiene que ser con determinadas teclas. Pero no detallan como funciona mas específicamente. Por lo tanto yo puedo suponer que no se mantendrá apretada una tecla?. Es decir, que si se quiere mover distancias mas largas, se aprete hartas veces la tecla, pero no dejarla mantenida.

**Comment by catalina-arcila** [comment]
Hola @rfigueroa314 , creo que tu duda puede ser resuelta con los comentarios de la *issue* #560 😄
Avísame si sigues con dudas!

**Comment by rfigueroa314** [comment]
La verdad no me quedó claro, mi pregunta es si puedo poner como supuesto en el readme que para mover el personaje no se pueda dejar mantenida una tecla, sino que si se quiere mover una distancia más larga, aprete más veces la tecla (pero sin dejarla mantenida). Lo considero un supuesto valido, ya que en el enunciado no sale nada de eso y tampoco pasa a llevar algo mencionado en el enunciado.

**Comment by catalina-arcila** [comment]
Es un supuesto válido, solo recuerda colocarlo en tu README

**Comment by rfigueroa314** [comment]
perfecto, gracias!
