### ISSUE TITLE
Listas por compresión

### ISSUE THREAD

**Issue by drosselot** [IIC2233/syllabus#612]
Hola, no se si estoy con mala memoria o algo, pero no me acuerdo de haber visto listas por compresión. En el ejercicio 2.2 de la semana 06 te piden usarlas y no se a que se refieren. Si es que ya las pasamos, donde las puedo ver?

**Comment by igbasly** [comment]
Hola @drosselot 
Las listas por comprensión fueron parte del contenido de la semana 1, específicamente del [cuaderno introducción](https://github.com/IIC2233/contenidos/blob/master/semana-01/1-introducción.ipynb) bajo el título de *Listas por comprensión*.
Esto es solo una forma de implementación de listas, por lo que no creo que te tome gran tiempo en entender, además que muchas veces puede ser una herramienta bastante útil.

Quedo atento a cualquier duda, saludos ✌️ .
