### ISSUE TITLE
filtro dibujo problema color

### ISSUE THREAD

**Issue by mpsubiabre** [IIC2233/syllabus#612]
Hola! 
termine el filtro de dibujo, pero me sale con un color gris en el fondo. Esta bien o existira algun problema en el codigo?
gracias
![imagen5](https://user-images.githubusercontent.com/42593773/59960959-7b8b9680-949e-11e9-8648-30c3df654748.png)

**Comment by ariel-m-s** [comment]
¡Hola, @mpsubiabre!

Debido a cómo binarizas la imágen, esta debiese contener únicamente **blanco** (0) y **negro** (255). Intenta corregirlo.

Saludos,
Ariel

**Comment by mpsubiabre** [comment]
He revisado muchas veces y no puedo encontrar el error, en que parte podria estar? si al ver la matriz de inversion tengo efectivamente solo 0 y 255

**Comment by ariel-m-s** [comment]
@mpsubiabre, la imagen que subiste tiene fondo [R: 225, G: 225, B: 225]. Asegúrate de que pusiste 255 y no 225.

Saludos y éxito.

**Comment by mpsubiabre** [comment]
ESO ERA! muchas gracias!!!! no puedo creer que no lo note
