### ISSUE TITLE
json.loads

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2233/syllabus#613]
Hola, en la issue [#532](https://github.com/IIC2233/syllabus/issues/532) dijeron que era recomendable hacer sleep para solucionar ese problema, ya que en mi caso con 0.001 no me funcionó y con 1 segundo si. Además no se si para el ayudante corrector le funcione con el mismo valor, es recomendable indicar en el readme que juegue con este parametro? Saludos

**Comment by nhorellana** [comment]
Hola! En que parte pusiste el sleep? Estoy intentando y no me funciona con 1s

**Comment by VicenteMerino** [comment]
> Hola! En que parte pusiste el sleep? Estoy intentando y no me funciona con 1s

En mi caso la señal al servidor lo hago con una señal `servidor_signal` desde el frontend al server, por lo tanto cada vez que mando un mensaje al servidor, pongo un `sleep` antes del emit de la señal.

**Comment by jeschuwirth** [comment]
@VicenteMerino, 1 segundo yo diría que es el límite de cuanto se tarda, si es más que eso el ayudante puede tener problemas en la corrección, lo que te recomiendo es partir con 0,2 y si no sirve probar con 0,4, luego 0,6 y así hasta llegar a 1, para quedar con el menor valor posible.

Dentro de todo 1 segundo no es malo pero tampoco ideal, por lo que intentaría bajarlo.

Suerte!
