### ISSUE TITLE
sanar jugadores

### ISSUE THREAD

**Issue by feliperojas123** [IIC2233/syllabus#613]
tengo la duda si es que no se sana se descuenta el dinero igual???

**Comment by jitorcas** [comment]
Hola! @feliperojas123 

Para poder **acceder** a sanar un deportista la delegación debe pagar, y luego se calcula la probabilidad. 

Respondiendo a tu pregunta, debería descontarle igual el dinero. 

Mucho éxito! 🏋️‍♀️🏃🏻
