### ISSUE TITLE
Path desde el cual edito codigo

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2233/Syllabus#613]
Me pasa que es diferente abrir dos python, uno desde la carpeta client y el otro desde la carpeta server, que abrir solo uno desde la carpeta T06 que incluye a las carpetas anteriores, ya que la importación se comporta distinto. Asumo que se entiende esto, por eso no doy mas detalles.

Dado eso, ¿Cual es la forma correcta de abordar la tarea? Si no hay una más correcta que la otra ¿Hay una recomendable por sobre la otra?

**Comment by DiegoAndai** [comment]
La verdad depende del orden que quieras darle a tu tarea, que archivos tengas que importar, como los vayas a manejar, hay muchas variables y opciones y por eso no creo que podamos darte una respuesta específica pero siempre es bueno mantener una jerarquía en los archivos del juego, y probablemente sí tienes muchos archivos tenerlos todos en una sola carpeta sea muy desordenado y te produzca problemas a ti. Sin poder darte una respuesta muy clara te recomiendo mantener lo más ordenado posible, pero que siempre este orden sea un aporte en función de tu tarea (para el mejor  y más claro funcionamiento de esta) y no que la tarea se adapte al orden.

Saludos.

**Comment by rrhurtado** [comment]
Hola !

Como no hay una forma absolutamente más correcta que otra, queda a libre criterio cual encuentras va más acorde a tu modelación. Por lo mismo, sería bueno si explicaras en el README (con una línea basta) la razón de que escogieras una por sobre otra.

Saludos
