### ISSUE TITLE
Error en iterador con recursion.

### ISSUE THREAD

**Issue by sofiuni** [IIC2233/syllabus#613]
Tengo un iterador el cual funciona bien pero las veces en las que se tiene que saltar retorna e imprime none por lo que intente usar recursion pero me da puros none excepto por uno. Esto es del primer ejercicio propuesto.

**Comment by fdoflorenzano** [comment]
Hola @sofiuni,

¿Podrías compartir tu código, o una versión simplificada, para entender lo que sucede? Sin eso no tenemos mucha información para entender el error.

Saludos.

**Comment by sofiuni** [comment]
class IterablePrimos:
    
    def __init__(self, inicio, fin):
        self.inicio = inicio
        self.fin = fin
        self.n = inicio
    
    def __iter__(self):
        self.n = self.inicio
        return self
    
    def __next__(self):
        result = self.n
        self.n += 1
        if result <= self.fin and es_primo(result):    
            return result
        elif result > self.fin:
            raise StopIteration
        else:
            self.__next__()

**Comment by fdoflorenzano** [comment]
Hola @sofiun, gracias.

El problema es de recursión. Cuando haces la llamada recursiva (en el `else`), no retornas el valor que te da esa llamada. Entonces si bien llamas nuevamente al método `__next__` y este puede que retorne algo, la llamada original no está retornando ese valor, y se queda con `None` por predeterminado.

Espero se entienda, saludos.

**Comment by sofiuni** [comment]
me da 

1
3
4
6
8
12
14
18
20

:thinking:

**Comment by fdoflorenzano** [comment]
Hola @sofiuni ,
¿Qué código te genera eso? Nuevamente, necesitamos contexto. 
Saludos.

**Comment by sofiuni** [comment]
class IterablePrimos:
    
    def __init__(self, inicio, fin):
        self.inicio = inicio
        self.fin = fin
        self.n = inicio
    
    def __iter__(self):
        self.n = self.inicio
        return self
    
    def __next__(self):
        result = self.n
        self.n += 1
        if result <= self.fin and es_primo(result):    
            return result
        elif result > self.fin:
            raise StopIteration
        else:
            self.__next__()
            return result

**Comment by fdoflorenzano** [comment]
Te resulta en lo que comentaste porque tu método retorna `result` en el último caso, que es una variable local y mantiene el valor de la primera llamada. Si la primera llamada comienza con `1` en `self.n`, y luego hace llamadas recursivas en la penúltima línea, cuando termine de hacer las llamadas y vuelva al contexto inicial, `result` sigue siendo `1`, no el resultado de las llamadas recursivas. Por eso no vez el `2`, por ejemplo.

Saludos.

**Comment by sofiuni** [comment]
No entiendo, entonces donde modifico el valor para que funcione correctamente?

**Comment by fdoflorenzano** [comment]
Cuando haces las llamadas recursivas (mediante `self.__next__()`), el resultado de esa llamada no se guarda en ningún lado, y por eso no alcanzas a recibirlo para luego retornarlo. Si cambias la línea a: `valor_obtenido = self.__next__()`, en `valor_obtenido` queda almacenado el valor que retorna la llamada recursiva.

**Comment by sbcorrea** [comment]
Hola, también tengo un error de recursión que no entiendo... esto
```

class IterablePrimos:
    def __init__(self, inicio, fin):
        self.inicio = inicio
        self.fin = fin

    def __iter__(self):
        return IteradorPrimos(self)

class IteradorPrimos:
    def __init__(self, iterable):
        self.iterable = iterable
    
    def __iter__(self): 
        return self
    
    def __next__(self):
        if self.iterable.inicio == self.iterable.fin:
            raise StopIteration
        elif es_primo(self.iterable.inicio):    
            return self.iterable.inicio
        else:
            return self.__next__()

```
Me genera este error:

```RecursionError: maximum recursion depth exceeded in comparison```

¿Qué pasa? ☹️

**Comment by fdoflorenzano** [comment]
Hola @sbcorrea.

Tu código se queda pegado en llamadas recursivas porque siempre `__next__` se va por el último caso y vuelve a llamar a `__next__`. Python detecta que se llamó tantas veces, que probablemente no termine y debe detener el programa.

Si te fijas, no hay cambios en cada llamada como para que tu iterador se de cuenta cuando llegue al final o al siguiente elemento.

Espero se entienda.
