### ISSUE TITLE
múltiples key press

### ISSUE THREAD

**Issue by pascal1003** [IIC2233/syllabus#613]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola, me preguntaba si existe un comando especifico para capturar múltiples key press con un solo evento?

**Comment by clementevalladares** [comment]
Hola @pascal1003, no existe un método específico que te permita hacer esto. Cada vez que presiones una tecla se ejecutará el método `keyPressEvent`. Por ejemplo, si presionas la secuencia "A", "B", "C" (aunque lo hayas  hecho  prácticamente al mismo tiempo) el método se ejecutará 3 veces, la primera vez para la tecla "A", luego para la "B", y finalmente la "C".
Si lo que quieres es verificar qué teclas están siendo presionadas, puedes utilizar el método `keyReleaseEvent` en conjunto a `keyPressEvent`, registrando como presionadas (en alguna variable) todas las teclas que hayan activado `keyPressEvent` pero que  no hayan activado el método `keyReleaseEvent`. 
De esta manera, y siguiendo con el ejemplo, cuando se active el tercer evento (la tecla "C"), y mientras no hayas dejado de apretar ninguna tecla, tendrás registrado que las tres teclas están presionadas.
Espero te haya sido de ayuda.

Agrego a esta respuesta que es posible que te encuentres con la existencia de la clase QKeySequence, sin embargo esta se utiliza para shortcuts de teclado predefinidos, como "Ctrl + C", "Ctrl + O", "Shift + F3", etc... Por lo que en el contexto de esta tarea probablemente no te sea de utilidad.
