### ISSUE TITLE
ventana chat

### ISSUE THREAD

**Issue by mgbriones** [IIC2233/syllabus#613]
los mensajes se envían desde los globos de texto ?? Puedo enviarlos desde una barra de texto distinta tipo facebook??

**Comment by gatochico** [comment]
Hola! Los mensajes se deben **mostrar en los globos de texto sobre el personaje** una vez enviados, pero si puedes tener una barra distinta para escribir+enviar el mensaje (: 

Espero haber respondido tu duda!

**Comment by mgbriones** [comment]
gracias!
