### ISSUE TITLE
Puntaje enemigo

### ISSUE THREAD

**Issue by PIPEAPABLAZA** [IIC2233/Syllabus#613]
En la sección 4.6 de puntajes se menciona que el puntaje obtenido al derrotar el enemigo es:
1000 + PUNTAJE_ENEMIGO * (nivel_enemigo - nivel_jugador)
sin embargo los enemigos no tienen nivel solo tamaño ... debería ser tamaño_enemigo.

**Comment by hanavarrete** [comment]
Si, hay un pequeño error y debería ser tamaño de enemigo. Gracias por avisarnos! Saludos

**Comment by nlvargas** [comment]
¿Ambos son tamaño entonces? ¿O es (tamaño_enemigo - nivel_jugador)?

**Comment by mjgutierrez1** [comment]
@hanavarrete También ocurre que en la parte de la inteligencia de los enemigos (4.3.4.) se define el movimiento de los enemigos según la relación entre el nivel del personaje principal y el nivel de los enemigos. Si los enemigos no tienen nivel, ¿entonces cómo se harían estas comparaciones?

**Comment by iqacevedo** [comment]
En general estas formulas se refieren a tamaño, puesto que los enemigos no tienen nivel. La idea de la comparación es que sea del mismo orden, por lo que también seria tamaño para el personaje principal en estas comparaciones. Lamentamos el cambio de palabras, consideren que es tamaño en esos casos.

Saludos !

**Comment by mjgutierrez1** [comment]
Ok gracias!

**Comment by inmadariaga** [comment]
@iqacevedo entonces quedaria la formula asi:  1000 + PUNTAJE ENEMIGO * max(tamaño enemigo - tamaño jugador,1) , como cuando se calcula la adiccion de experiencia, o no tiene un minimo de 1 la adicion de puntaje (es por el caso si teniendo tamaño 3 mato a uno de tamaño 1, sin el max seria: 1000 + PUNTAJE ENEMIGO*(-1) ?

**Comment by iqacevedo** [comment]
@inmadariaga no es necesario, puesto que en ese caso solo ganaría algo menos que 1000 puntos,  lo que puedes hacer si te hace sentido es agregar un `max(puntaje, 1)` a toda la formula, para que siempre obtenga un puntaje positivo (pero no es necesario porque no aparecía la formula así).

Saludos !
