### ISSUE TITLE
Asignación de puntajes T05

### ISSUE THREAD

**Issue by Drpinto1** [IIC2233/Syllabus#613]
Saludos, el enunciado de esta tarea, a diferencia de los de las tareas anteriores, no tiene la ponderación de cada sección de esta, ni siquiera para el entregable :thinking:  (exceptuando el bonus).
Entiendo que esta tarea es distinta a las anteriores, pues el juego debe funcionar más como un todo que sección a sección, sin embargo pienso que no conocer estas ponderaciones reduce las nuestras opciones la momento de priorizar ciertas partes de la tarea en caso de tener la certeza de que no la podremos completar en un 100% (por le motivo que sea).
También creo que puede no ser posible hacer la repartición clara de los puntajes como para las demás tareas por lo que mi pregunta es, es el no tener la asignación de puntajes algo hecho a propósito o un error al momento de redactar el enunciado?
Gracias de antemano por su respuesta :smile:

**Comment by pcseisdedos** [comment]
Supongo que puede ser por la misma razón que en la tarea 3 (aún no determinan los puntajes y publicarán nuevamente el enunciado con los puntajes actualizados el martes luego de la reunión entre profesores)

**Comment by llloyola** [comment]
Si no han decidido bien todavía la distribución de los puntajes 💯, podríamos pedir que añadan un _Bonus_ 🎊  relacionado con que el juego tenga música 🎶  o sonidos 🔊 para distintos eventos (click de botones ⏯ ⏺, explosión de bombas 💣💥, activar _power-ups_ 🏃🛡❤️, etc) 👀:eyes::eyes:. Digo, suena divertido... jajja

**Comment by FernandoPieressa** [comment]
Hola! Exactamente al igual que en la tarea 3, no se determinan aun y se publicara cuando estén actualizados.

@llloyola Lamentablemente, no añadiremos mas contenido dentro del enunciado

**Comment by llloyola** [comment]
Okay :(
:cries_in_chilean:
