### ISSUE TITLE
Terminal Visual Studio Code

### ISSUE THREAD

**Issue by danvillablanca** [IIC2233/syllabus#614]
Hola!

Me gustaría saber cómo puedo abrir el terminal del VSC en una nueva ventana, como si quisiera jugar al juego y no ver el código.

Que tengan buen día y felices fiestas patrias!!

**Comment by amparostevens** [comment]
Hola! 
Lo más fácil es abrir directamente una terminal desde la carpeta de tu tarea. Si estás en Windows escribes cmd en la barra superior (o también puedes ocupar PowerShell), en Mac botón derecho y click en abrir terminal. Luego simplemente escribes el nombre del archivo que quieres ejecutar, como `main.py` y enter.

**Comment by danvillablanca** [comment]
> Hola!
> Lo más fácil es abrir directamente una terminal desde la carpeta de tu tarea. Si estás en Windows escribes cmd en la barra superior (o también puedes ocupar PowerShell), en Mac botón derecho y click en abrir terminal. Luego simplemente escribes el nombre del archivo que quieres ejecutar, como `main.py` y enter.

Gracias!!!
