### ISSUE TITLE
Enemigos.moverse()

### ISSUE THREAD

**Issue by Kitaps** [IIC2233/Syllabus#614]
Hola, 

tengo una duda respecto al movimiento de los enemigos cuando están en idle. 

En el enunciado dice que tienen una dirección aleatoria con 0.25 de probabilidad en cada dirección / segundo.

Entonces esto significa que los enemigos cuando estan en idle solo se mueven  en linea recta para arriba/abajo/derecha/izuiqerda?

gracias

**Comment by iqacevedo** [comment]
Hola !

Se habló en #601. Avísame si lo que se habla ahí no responde tu duda.

Saludos !

**Comment by Kitaps** [comment]
Oh vale no la había encontrado 
gracias
