### ISSUE TITLE
duda bonus DCCMascota

### ISSUE THREAD

**Issue by JuaniAndres** [IIC2233/syllabus#614]
Hola es necesario que la mascota tenga un globo o basta con que haga lo del sonido?
Gracias de antemano

**Comment by Dnpoblete** [comment]
Hola @JuaniAndres, si la idea es que tenga un globo al igual que su dueño, como se muestra en la imagen. Adicionalmente, si lo deseas puedes escribir algo cuando la mascota haga el sonido.

Éxito con la tarea! 😄

**Comment by JuaniAndres** [comment]
yap @Dnpoblete  entonces tengo que ponerle globo pero es opcional si muestra un mensaje cuando suena el animal?

**Comment by Dnpoblete** [comment]
Exacto!

**Comment by JuaniAndres** [comment]
ya muchas gracias
