### ISSUE TITLE
Git pull de contenidos: ¿borra mis ejercicios en jupyter?

### ISSUE THREAD

**Issue by sbcorrea** [IIC2233/syllabus#614]
¡Hola! Me entró la duda de cómo funciona git pull con los archivos `.ipynb`, porque en clase pregunté si se guardaban los cambios que yo haga en las celdas, y el profe me respondió que se guardaban solo localmente. Por lo tanto, asumo que al hacer `git pull` se sobreescribirían mis apuntes con la versión vacía que se sube a `contenidos` como plantilla. __¿Los `.ipynb` ignoran cambios locales, o tengo que guardar una copia de los archivos editados en otro directorio local para conservarlos?__
¡Gracias! ❤️ 

--------------------------------------------------------------------------------------------------------
PD: hay 2 cosas que me sacan de quicio de usar Jupyter Notebook, pero realmente no importan, así que no da para hacer una issue por separado... ¿las puedo preguntar acá mismo? 🙈 
1. ¿Cuál es el comando de git bash para cerrar Jupyter? Durante todo el tiempo que estoy usando Jupyter, el bash me obliga a mantener abierta una ventana inutilizable—pero bueno, si eso es inherente a Jupyter, lo puedo soportar. Lo que odio es que aún después de cerrar Jupyter, cuando voy a cerrar el bash me sale un pop-up de que hay programas corriendo y forzar el cierre podría causar error. Traté tecla escape, `exit`, `close`, `exit jupyter notebook`, `close jupyter notebook`, y nada funciona. De nuevo, no importa, pero me desespera 😅 
2. Cuando sin querer cliqueo demasiadas veces sobre el texto (no las celdas de código, sino las celdas de markdown) de un `.ipynb`, me muestra la celda en plain text con todos los caracteres especiales de markdown. Lo que me complica de eso es que hace que una celda con los contenidos redactados se vea igual que las celdas con código, y me pierdo 😢 ¿Cómo se devuelve a como se veía antes?

**Comment by igbasly** [comment]
Hola @sbcorrea :smile:
Respondiendo a tus consultas, primero comentar que `git pull` actualiza tu repositorio local con los cambios que hayan en el repositorio remoto (internet), por lo tanto, al ejecutar `git pull` lo que se hace es agregar cualquier archivo que se haya subido luego de tu última actualización y modificar **solo aquellos** archivos que se hayan cambiado y subido posterior a tu última actualización (Ej: arreglar un enunciado o archivo de datos).
Con esto último, lo de actualizar archivos ya descargados, hay que tener gran consideración, ya que si tu has modificado un archivo que luego se actualizó en el syllabus, al hacer `git pull` aparecerá un error de conflicto debido a que el archivo que modificaste no se encontraba como git tenía previsto que debía estar. Es por esto que siempre recomendamos que los cuadernos de jupyter los trasladen a otra carpeta antes de modificarlos o comenzar a trabajar en ellos.

Respecto a las otras preguntas correspondientes al uso de jupyter notebook:
1. Al iniciar `jupyter notebook`, en la ventana de inicio encontrarás un botón en la parte superior derecha que dice `Quit`, el cual termina la ejecución del servidor de jupyter. Además siempre cuentas con la opción de terminar los programas por consola mediante el comando `ctrl + c` (válido para Windows y macOS), que en jupyter además te pedirá una confirmación `y/n` para terminar con la ejecución del servidor.
2. Lo que sucede en esos casos, tal como mencionas al igual que con las celdas de código, es que entras al modo edición, por lo tanto, nuevamente al igual que con las celdas de código debes ejecutarlas con el comando `shift + enter` y estas se mostrarán con el markdown renderizado.

Espero haber aclarado todas tus preguntas y no dudes en comentar si algo no quedó claro.
Saludos :v:.

**Comment by sbcorrea** [comment]
¡Me quedó súper claro! Muchísimas gracias, te pasaste.
