### ISSUE TITLE
Duda bytes sample

### ISSUE THREAD

**Issue by anguiloff** [IIC2233/Syllabus#614]
Hola!
Tengo una duda con los archivos wav. En el enunciado dice:
"Para esta tarea se considerarán solo archivos WAV con sonido Stereo, por lo que trabajarán con una
estructura de 2 canales, con cada sample de 4 bytes."
Sin embargo, en el header se encuentra la sección Bits per Sample la que me dice que para el caso de la canción "Alan Parsons Project - Eye In the Sky.wav" esta tiene 16 bits, es decir, solo 2 bytes por sample.
La pregunta es si consideramos que esta canción dada es un ejemplo incorrecto a los que ustedes utilizarán para revisar la tarea o debemos aplicar el filtro considerando bits variables.

Saludos

**Comment by iqacevedo** [comment]
Hola,

Efectivamente el enunciado tenía un error, en #595 se comenta la corrección de este.

Saludos !
