### ISSUE TITLE
Dudas envío de audios

### ISSUE THREAD

**Issue by rfenzo** [IIC2233/Syllabus#615]
Hola, la verdad es que estoy bastante perdido con el tema de las canciones, aún no me queda claro si es que el cliente, en otro computador, deberá descargar en su computador la cancion que se está reproduciendo en la sala del servidor. Si es así, se demoraría demaciado en recibir la cancion completa por el tamaño de las canciones. Me imagino que la idea es que se vaya reproduciendo la canción mientras se va enviando?.

O simplemente debo reproducir la cancion en el computador del servidor?

Gracias

**Comment by aeperalta** [comment]
Lo que a mí se me había ocurrido es revisar si el cliente tiene las canciones cuando se logea. En caso de que no las tenga, el servidor se las envía. Creo que también hay que revisar si tiene cada una de las canciones por si, una vez que descargó las canciones, al servidor se le ocurre agregar más canciones en otra conexión. Luego que el cliente tiene las canciones, el servidor envía la señal cuando se reproducen (todavía no lo implemento del todo, pero así lo estoy haciendo)

**Comment by iqacevedo** [comment]
Hola

Justamente la idea es que las canciones las tenga el servidor y este las envié a los clientes para que las puedan ocupar. Lo importante de esto último es que originalmente el cliente no tenga las canciones y que en algún momento sea el servidor quien les envié las canciones. Como en el enunciado no se especifica en que momento debe enviarse puede ser cada vez que se necesite y después borrarlas, puede ser como dice @aeperalta que el servidor envié canciones al cliente y este las guarde o como prefieras hacerlo, **lo importante es que el servidor las envié y que originalmente el cliente no tenga las canciones**.

Saludos !

**Comment by monicabelen** [comment]
Es posible enviar las canciones usando pickle de una sola vez? o se debe enviar por partes? Se supone que pickle solamente hará loads si el archivo esta completo. Lo pregunto porque traté de hacerlo así y me lanza varios errores..

**Comment by arturodelreal** [comment]
Hola, los archivos son muy pesados para que puedan ser recibidos de una sola vez, debes primero recibir por partes todo lo que fue mandado, concatenar las partes, y posteriormente hacer load del resultado de la concatenación(que vendría siendo el archivo completo).
Saludos!
