### ISSUE TITLE
Descuento excelencia y respeto

### ISSUE THREAD

**Issue by Gustav2000** [IIC2233/syllabus#615]
Hola, en la parte de premiar deportistas dice: "...mientras que el deportista que no resulte ganador experimentará una baja de 10 en su moral y **0.02 de excelencia y respeto**". Esta excelencia y respeto corresponde a la de la delegación cierto? porque me generó confusión por como estaba planteado en el enunciado.

**Comment by jitorcas** [comment]
Hola! @Gustav2000 

Así es! El descuento se le hace a la delegación, ya que es quien posee el atributo excelencia y respeto. 

Mucho éxito! 🏃🏻🏋️‍♀️

**Comment by Gustav2000** [comment]
Yaya gracias!!!
