### ISSUE TITLE
Problema con JSON al enviar mensajes largos

### ISSUE THREAD

**Issue by FelipeA7** [IIC2233/syllabus#615]
Hola,
Al enviar mensajes en el chat, estoy haciendo que el cliente siempre los lea con JSON (pues son enviados con esto). El problema que estoy teniendo es que al enviar más de x carácteres me sale un error (creo que a los 124 carácteres). Al enviar mensajes cortos no tengo ningún problema.
El error que me sale es este:
![image](https://user-images.githubusercontent.com/48482398/70282743-8b254000-179d-11ea-9c8b-0b5428020006.png)

Como pueden ver, primero envío 2 mensajes "cortos" (los estaba printeando) y el 3er mensaje que ya es bien largo me tira el error que digo.
Traté de buscar en stackoverflow pero las soluciones de ahí no me sirvieron :(

**Comment by StroveLight** [comment]
Hola! podrías subir los cambios a tu repositorio para que pueda ver a mas detalle el programa?

**Comment by FelipeA7** [comment]
@StroveLight Acabo de subirlo

**Comment by StroveLight** [comment]
Saludos,
Tu servidor está recibiendo mal la informacion del cliente. La funcion recibir_informacion está recibiendo mal la data

![image](https://user-images.githubusercontent.com/48263952/70286743-21ac2e00-17ab-11ea-93fd-41165326799e.png)

en bytes:
![image](https://user-images.githubusercontent.com/48263952/70287896-54f0bc00-17af-11ea-98ed-927445a45d64.png)

ves esos espacios y el cuadrado despues del \\u? Probablemente sean caracteres corruptos. Ese caracter se encarga de que se lea mal el string
![image](https://user-images.githubusercontent.com/48263952/70287936-75207b00-17af-11ea-91eb-f1d367b94813.png)

----------------------

Ahora vamos de la funcion recibir_informacion:
creo que la culpa es de:
![image](https://user-images.githubusercontent.com/48263952/70287700-aa789900-17ae-11ea-8075-e06f4aff2bc7.png)
...ya que estás comparando todo un bytearray con  un byte, por lo que es una rareza entrar a ese while

Hay otros errores, como que estás recibiendo todo el mensaje en vez de hacerlo por partes (lo que hace que cuando hayan \\x00 adentro, json sufra mas), y un caso borde en el que la division entera no tiene resto cuando calculas el ```recibir = ```

Espero que esto te ayude!

**Comment by FelipeA7** [comment]
La verdad no entiendo muy bien cuál es el problema de la función. Llevo ya varias horas revisándola, y puedo ver que al recibir información esta llega corrupta como tú dijiste, pero no entiendo por qué.
Lo del while data[-1:] == b'\x00': lo uso para eliminar los bytes 0 que pongo al final de los mensajes que no alcanzan los bytes que dice el enunciado.

Además, no entiendo eso que dijiste de que no estoy recibiendo el mensaje por partes, pues en la función recibir_informacion tengo la línea data = client_socket.recv(tamano_mensaje) dentro de un while que va recibiendo la información en pedazos

**Comment by StroveLight** [comment]
@FelipeA7 Ah si, confundí la variable (Disculpa, que yo uso siempre ese nombre para el largo del mensaje), Saludos

Por cierto, procura fijarte en lo que pasa con la variable 'largo' cuando recibes una cantidad de bytes equivalente a 'largo_mensaje'
