### ISSUE TITLE
Duda Bonus T05

### ISSUE THREAD

**Issue by llloyola** [IIC2233/Syllabus#615]
Hola! Una duda... Si hacemos los _Bonus_, nuestro juego debe soportar que el usuario decida no jugar con los _Bonus_ implementados? O simplemente dejamos que el juego corra con esos _Bonus_ sin que exista la opción de desactivarlos/activarlos?

**Comment by Arcoirisky** [comment]
El bonus da la opción de:

> implementar bombas móviles, **en lugar** de las bombas por defecto.

Puedes activarlos o desactivarlos si quieres, queda a tu criterio, ya que no pasa por sobre lo otro :D

**Comment by llloyola** [comment]
O sea que sería perfectamente válido dejar que siempre esté implementado _Kick the bomb_ y que el _Multijugador_ pueda activarse y desactivarse? 

Thaaaanks de antemano 🥑 ❤️

**Comment by nachocontreras** [comment]
Exacto!
