### ISSUE TITLE
Funcionamiento correcto en otro computador

### ISSUE THREAD

**Issue by franciscareti** [IIC2233/syllabus#615]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola! Cuando entregué el avance de la tarea, el ayudante me puso que no había nada que corregir porque no había movimiento ni colisiones, y que solo se mostraban las ventanas, cuando en mi computador sí se movía el personaje y había implementado parte de las colisiones. Esto me preocupa por si mañana, al subir la tarea, pasa lo mismo y funciona bien en mi computador pero no en otro. A mi repositorio no he modificado el avance que subí en esa ocasión... no sé si me pueden ayudar a verificar si le ocurrió solo al ayudante corrector o le pasaría a todos, para ver qué puedo hacer para mi entrega. Muchísimas gracias de antemano!

**Comment by tomasrosenberg** [comment]
Hola @franciscareti!

Acabo de probar tu avance desde tu repositorio y me corre bien. No sé qué habrá sucedido y por qué no le aparecieron los objetos a la persona que te corrigió, pero para tu tranquilidad sí noté el movimiento y colisiones. Además, si alguna persona tiene problemas en correr un código o qué se muestre mal alguna ventana, se pide ayuda y lo puede ver con otro ayudante. Asi que si pruebas tu código a través de la terminal (CMD), no deberías preocuparte si no funciona en otro computador.

Estaré atento a cualquier otra duda. Éxito programando!
