### ISSUE TITLE
Colisiones múltiples

### ISSUE THREAD

**Issue by diegoheg** [IIC2233/Syllabus#615]
¿Debemos asumir que al colisionar con más de un enemigo a la vez, las bajas de vida y los ataques solo ocurrirán entre el primer enemigo con el cual se colisionó y el jugador?¿O, digamos, el jugador perderá vida y atacará a todos los que estén colisionando con él?

**Comment by Arcoirisky** [comment]
Tu segunda opción :D Si chocas con uno y luego otro te da, tu recibes dos de daño. Y si ambos te atacan, sería -2 de una.
