### ISSUE TITLE
importar pixel_collector

### ISSUE THREAD

**Issue by jfpena1** [IIC2233/syllabus#616]
Hola tengo una duda quizas muy basica pero no he podido solucionarlo con google. No logro poder importar pixel_collector en un archivo dentro de la carpeta cliente. 

En particular me sale el error
ValueError: attempted relative import beyond top-level package

Como debo hacerlo? muchas gracias

**Comment by ariel-m-s** [comment]
¡Hola @jfpena1!

Dos preguntas:

1. ¿Cuál es el _path_ de ```pixel_collector.py``` relativo al directorio ```T03```?

2. ¿Cómo estás importando ```pixel_collector.py```? Me refiero a la línea de código.

Quedo atento,

Ariel

**Comment by jfpena1** [comment]
1. pixel_collector.py esta en la carpeta T03, es decir su path estando en la carpeta T03 seria simplemente pixel_collector.py.  L estructura de la carpeta es :
T03/
   pixel_collecto.py
   otros
   client/
        _main.py
        manejar_imagenes.py
        otros
    server/
        main.py
        otros
        
2. La verdad no se bien como hacerlo. Hasta ahora tengo puesto from ..pixel_collector import get_pixels
y con eso es lo que tira el error. Gracias Ariel, Julio.

**Comment by ariel-m-s** [comment]
Dale. Lo que pasa es por alguna razón que desconozco, _Python_ te está prohibiendo importar cosas desde ese directorio.

Te recomiendo mover ```pixel_collector.py``` al directorio ```T03/server```. De esta manera podrás importarlo usando la sentencia

```python 
from pixel_collector import get_pixels
```

Esto debería funcionar. Recuerda, además, que este es módulo es usado sólo por el servidor, por lo que hace sentido que se encuentre en su mismo directorio.

Ariel

**Comment by jfpena1** [comment]
Gracias!!
