### ISSUE TITLE
Formato del juego - duda

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2233/Syllabus#616]
¿Se supone que tengo que poner una cierta cantidad de opciones para que el jugador elija la canción correcta?

**Comment by DiegoAndai** [comment]
Si! Eso está en el enunciado sección salas.

**Comment by djcontador** [comment]
Hola! 
1) La pregunta aleatoria de adivinar si es artista o nombre de la canción, debe ser indicada en la interfaz? por ejemplo: ¿Cuál es el artista? y luego se despliegan las 4 opciones, o simplemente se muestran las opciones sin dar un hint de cual es la pregunta? (el usuario debe de deducirla a partir de las opciones de respuestas posibles)

2) Las opciones de respuestas posibles (por ejemplo los distractores a la pregunta correcta) deben corresponder al mismo estilo musical? Por ejemplo: si está sonando la canción "Titerito" de Farruko, y la pregunta es "cual es el artista?" el resto de las opciones/distractores tienen que ser artistas del mismo estilo musical? o tiene que ser una muestra random de los artistas de todas las canciones disponibles en el servidor? De no ser así, en el caso de la sala Reggeaton solo hay 3 artistas disponibles (Farruko se repite 2 veces), podemos asumir que en una carpeta correspondiente a una sala de juegos siempre tendrá como mínimo 4 canciones de 4 artistas diferentes?  

Gracias de antemano! Saludos!

**Comment by arturodelreal** [comment]
Hola, deberías especificar la pregunta, ya que así evitarías confusiones. 
Respecto a lo segundo, lo más lógico sería que se muestren los interpretes de la misma sala, pero como no está especificado en el enunciado queda a tu criterio. De todos modos puedes asumir que habrá al menos 4 interpretes distintos por sala, por mientras puedes ponerle Farruko1 y Farruko2 para probar tu tarea.
Saludos

**Comment by djcontador** [comment]
perfecto! gracias!!

**Comment by jorgeriesco** [comment]
Hola, 

Todo lo que tenga que ver con el formato del juego queda a nuestro criterio? Ya que si bien sale que el jugador tiene que elegir artista o canción, no se dice si tengo que poner opciones de artistas en un momento, de canciones en otro, una mezcla o ambos (por ejemplo dar cuatro opciones de artista y cuatro de canción y habrían dos correctas). Tampoco se dice la cantidad de opciones que puedo dar. 

Me da la sensación de que queda a mi criterio (siempre y cuando sea coherente y entendible), pero para estar seguro.

Gracias.

**Comment by Hernan4444** [comment]
@jorgeriesco Exactamente, en el enunciado restringimos algunos detalles del juego pero la lógica general queda a tu criterio. Recuerda que te puedes basar en el famoso juego SongPop si es que no quieres implementar una nueva lógica.

Saludos

**Comment by fcgfaura** [comment]
Hola!. Dentro de una sala se deben reproducir las canciones disponibles de esa sala solo una vez?, o infinitamente??
