### ISSUE TITLE
Duda con Qt design

### ISSUE THREAD

**Issue by macagamerre** [IIC2233/syllabus#616]
Hola!!
Para la sala de chat puse una de las imágenes de fondo. Cuando pongo sobre ella un QTextEdit o un Qlabel (para las burbujas de texto) esta nueva sección tiene el mismo fondo de la sala (y no quiero que sea así).
Intenté solucionarlo con un png con fondo gris de base para la burbuja de texto y  poner sobre ese el QTextEdit pero no hay caso. Cuando abro el stylesheet  del QTextEdit no aparece nada "editable" tampoco. 
Intenté poner fondo al QTextEdit desde stylesheet y tampoco funciona, sigue referenciando la imagen del bosque.

¿Cómo puedo solucionarlo?

![InkedCaptura_LI](https://user-images.githubusercontent.com/12416081/70298589-e9b7e180-17d0-11ea-8f88-d6cd9cbb5e79.jpg)

**Comment by lily416** [comment]
Hola c:

¿Puedes subir tu código a tu repositorio de github?

**Comment by macagamerre** [comment]
Hola, lo hice de nuevo y  me funcionó jaja gracias igual!!
