### ISSUE TITLE
Properties vs Atributos

### ISSUE THREAD

**Issue by Kitaps** [IIC2233/Syllabus#616]
Hola, 

en la Tarea anterior me surgió la duda de cuando conviene más usar atributos y editar los atributos y cuando usar properties.

Según lo que tengo entendido, los porperties conviene más usarlos cuando dependen de otros atributos que cambian muy frecuentemente. 

Pero mi duda es: Al ser los properties funciones, que tan ineficiente es dejar algo como por ejemplo la vida maxima como property (ya que igual no cambia tanto (una vez por etapa o cuando compras items) versus usar la vida maxima como varaible y ir modificandola respectivamente cuando corresponda. 

gracais

**Comment by Hernan4444** [comment]
@Kitaps es cierto que las properties convienen más cuando dependen de otro atributo que cambia con frecuencia, pero también sirven para otorgar seguridad a los atributos. Generalmente estos son privados y la única forma de acceder a ellos, editarlos o eliminarlos es mediante properties. De este modo puede asegurarse que el atributo sea seteado con los valores correspondiente. (agregando condiciones en el `setter`).

Y sobre tu duda, recuerda que la vida máxima está en función del tamaño, por lo tanto no es mala idea usarla como property. La diferencia entre el atributo y llamar a esta property es mínima y por lo tanto no se apreciará una diferencia si usas cualquier de las dos.

En lo personal, las properties también aseguran tener un código más limpio, puesto que tienes que editar tantos atributos cada vez que otro cambie, sino que se hace automático, así que yo recomendaría su primera opción 😄 

Saludos ✌️
