### ISSUE TITLE
Duda bonus musica

### ISSUE THREAD

**Issue by mjadresic** [IIC2233/syllabus#616]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola, para poder pausar la musica en la ventana juego se me ocurrio utilizar Qsound (misma clase que ocupan en la AS2), sin embargo, este objeto no tiene el metodo pause() solo start() y stop() que lo hacen comenzar desde el principio. Mi duda es si es posible hacer la pausa con Qsound o si es mas conveniente utilizar otra clase de Qt, y si es asi, cual esta permitida o cual recomiendan? (si es que pueden decir)

**Comment by tomasrosenberg** [comment]
Hola @mjadresic!

Si puedes utilizar QSound y no es necesario que la canción se reanude desde donde se pauso. Esta puede volver a comenzar desde 0. Igual te recomiendo seguir buscando en la documentación de Qt si es que lo encuentras pertinente para tener un mejor programa.

Estaré atento a cualquier otra duda :D
