### ISSUE TITLE
Semana de Pausa de Ing

### ISSUE THREAD

**Issue by CataSudo** [IIC2233/syllabus#616]
Hola, me entro la duda si en este curso se va a hacer la semana de pausa la proxima semana? 
Gracias!

**Comment by fdoflorenzano** [comment]
Hola @CataSudo,

Sí, respetaremos la semana de pausa la próxima semana. Como implicancia directa, es que la actividad sumativa 3, agendada para la próxima semana, se pospone, y cambios se realizarán sobre el calendario del curso.

Los detalles de estos se los comunicaremos el viernes, ya que estamos en proceso de definir estos cambios. 

Saludos.
