### ISSUE TITLE
Error cuando selecciono una imagen de perfil en los archivos de la computadora

### ISSUE THREAD

**Issue by gustavobarrezueta** [IIC2233/syllabus#617]
Hola!, tengo una duda acerca de un mensaje que me aparece en la consola cuando el cliente selecciona una imagen desde sus archivos. El mensaje no detiene la ejecución y pareciera ser "inofensivo" pero me gustaría saber por que se produce o cómo puedo eliminarlo. He buscado e internet sobre el error pero no he podido resolverlo. El mensaje es: 
"objc[23000]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fffa2abac90) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x116634cd8). One of the two will be used. Which one is undefined."
Muchas Gracias desde ya.

**Comment by ariel-m-s** [comment]
Este tema ya está siendo tratado en la _issue_ #611.

**Comment by gustavobarrezueta** [comment]
oh Sorry... son muchas issues jajaj. Gracias :).
