### ISSUE TITLE
dudas diagrama

### ISSUE THREAD

**Issue by eliasbruchfeld** [IIC2233/syllabus#617]
Hola! tengo un par de preguntas respecto a que poner en el diagrama. 

Tengo una clase Deportista que recibe una lista con todos los atributos del deportista, y despues defino los otros atributos en base a la lista. ejemplo self.nombre = lista[0] etc etc etc. En el diagrama solo pongo que la clase recibe una lista? o tengo que poner todos los otros atributos creados a partir de la lista. 

Segundo: tengo atributos que al principio defino como None y despues de algun metodo pasan a ser un str o un int. En el diagrama como los pongo.

Tercero: me complique un poco haciendo el diagrama en el computador porque son muchas ramas. puedo hacerlo a mano y lo escaneo?

**Comment by furcelay** [comment]
Hola @eliasbruchfeld !
Respondiendo tus dudas:
1.  La clase en el diagrama debe tener todos los atributos y métodos correspondientes a la clase, independiente de cual es el input del `__init__` de ésta. 
2.  El tipo de atributo es el que va a tomar en el momento que le das un valor distinto de `None` (*int*, *str*, etc.)
3.  Idealmente debes hacerlo en computador, en general los programas para construir diagramas permiten hacer zoom in/out y no tienen límites de espacio para hecer diagramas grandes. Haciendolo a mano puedes tener problemas de espacio y es difícil actualizarlo con los cambios en tu código. De todos modos puedes hacerlo a mano, pero debe ser muuuy ordenado.

Saludos! 😄
