### ISSUE TITLE
codificación bytes

### ISSUE THREAD

**Issue by JuanDlugo** [IIC2233/syllabus#617]
Hola! Tengo la duda si todo tipo de comunicación entre servidor y cliente deben estar codificados con el formato pedido de Little y Big Endian. Me surge la duda porque realizo muchas otras consultas al servidor que no van destinadas precisamente a mensajes del chat. Entonces lo que hice fue mediante un header(codificado simplemente con utf-8) lograr diferenciar las respuestas del servidor. Por ende varias de mis consultas no están codificadas bajo el formato Endian, pero sí las que son mensajes de texto de los usuarios.

**Comment by DCCollao** [comment]
Hola!

![image](https://user-images.githubusercontent.com/37167447/70306924-ce57d100-17e6-11ea-8d9c-e7a1e8207420.png)
En esta sección "envío de mensajes" se refiere a cualquier comunicación entre cliente y servidor; y **no solamente** los mensajes de chat entre usuarios.
