### ISSUE TITLE
Duda reduce calcular_precio() - AS02

### ISSUE THREAD

**Issue by Christian-Klempau** [IIC2233/syllabus#617]
En la función calcular_precio(productos), al parecer se podía realizar lo pedido **sólo** con un `reduce`. Yo lo hice aplicando `map`, para obtener los ints, luego `reduce` sobre eso para sumar el total:
```python
precios = map(lambda x: x.precio, productos)
lista_precios = list(precios)
total = reduce(lambda x, y: x + y, lista_precios)
return total
```
Cuál era la implementación ideal sin map y sólo con reduce?

**Comment by aaossa** [comment]
Hola @Christian-Klempau ! Buena pregunta 👌 Primero que todo, en el enunciado se pedía que utilizaran `reduce` pero no "única y exclusivamente" `reduce`, por lo que adicionalmente podían ocupar `map`, `filter` o cualquier otra función, excepto `sum`. Con esto, la solución que planteas también es una solución válida y que podría recibir todo el puntaje en esa sección, ya que ocupas `reduce`. Ahora a la pregunta en sí:

Seguramente al intentar hacer esta sección directamente con `reduce` les apareció `TypeError`, así que veamos por qué pasa. Para explicarlo, reduje el problema: en lugar de utilizar instancias de una clase vamos a usar *strings* y en lugar de pedir un atributo de la clase utilizaremos su largo. Entonces, dada una lista de *strings*, se pide la suma de sus largos:
```python
usuarios = [
    "Christian-Klempau",
    "aaossa",
    "otro",
]
```
Primera idea: "Ah, tengo que acumular los largos de los usuarios, entonces démosle con `reduce`" (asumiendo las mismas restricciones que en la AS2).
```python
from functools import reduce

largo_total = reduce(lambda a, e: a + len(e), usuarios)
# Ocupé "lambda a, e" para indicar "acumulador" y "elemento"
```
:expressionless: Me da esto:
```python
Traceback (most recent call last):
  File "*\ewe.py", line 9, in <module>
    largo_usuarios = reduce(lambda a, e: a + len(e), usuarios)
  File "*\ewe.py", line 9, in <lambda>
    largo_usuarios = reduce(lambda a, e: a + len(e), usuarios)
TypeError: can only concatenate str (not "int") to str
```
Esto ocurre porque `reduce` toma los dos primeros elementos del iterable `usuarios` e intenta aplicar la función. Como `a` es `"Christian-Klempau"` y `e` es `"aaossa"`, empieza intentando hacer la suma `"Christian-Klempau" + len("aaossa")`, que provoca el `TypeError`. Es por esto, que necesitamos corregir el primer valor para `a`, el valor acumulado inicial. Una forma de evitar este error podría ser apoyarse en el tercer argumento de `reduce`, que es un "inicializador". 

```python
largo_usuarios = reduce(lambda a, e: a + len(e), usuarios, 0)
# Notar el 0 como tercer argumento
```
De esta manera, las sumas que se realizan serán:

- `0 + len("Christian-Klempau")`
- `17 + len("aaossa")`
- `23 + len("otro")`
- Resultado: `27`

Tal vez otra manera sería hacer una función (no anónima) que verificara el tipo de cada valor entregado (algo del tipo `type(a)` y `type(e)`, para decidir si usar `len` o no). Nuevamente, es posible que haya otras formas de resolver esto, pero esta es una forma de hacerlo utilizando solo `reduce`.

**Comment by Christian-Klempau** [comment]
Genial! Muchas gracias profesor, buena idea implementarlo con un valor inicial, eso soluciona los TypeError.
