### ISSUE TITLE
No me aparecen los objetos en el mapa

### ISSUE THREAD

**Issue by imuoz** [IIC2233/syllabus#617]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Estoy enviando una lista con los objetos que deberían aparecer hacia la ventana del juego, pero estos no se muestran en la pantalla. Tengo lo mismo para los obstáculos y si funciona, no entiendo qué puede estar pasando.

Probé usando raise_(), comprobé que se crearan con el path correspondiente y si se crean

**Comment by valerianazal** [comment]
Hola @imuoz !! Tu problema se puede resolver agregando `setVisible(True)` a los labels que creas para los objetos.
Quedo atenta ☺️

**Comment by imuoz** [comment]
No me funcionó uwu

**Comment by imuoz** [comment]
retiro lo dicho jajaja, era que habia borrado el raise_, gracias!!

**Comment by valerianazal** [comment]
Que bueno!! Mucho éxito ✨
