### ISSUE TITLE
Samples

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2233/Syllabus#617]
¿Que significa esto?

>  Cada uno de ellos (samples) contiene chunks correspondientes a la cantidad de canales de audio del archivo. 

Osea que si hay 2 canales, los chunks "corresponden" al numero 2, lo que no entiendo. Ademas cada sample tiene más de un chunk, pero tiene 4 bytes, tampoco entiendo eso, ¿Cuantos bytes tiene un chunk?

Los chunks se ordenan de manera intercalada siendo los pares para un canal y los impares para el otro. ¿Donde quedaron los samples o que son en esta estructura?

Un dibujo creo que sería muy explicativo, pero uno de data.

Aparte tampoco se lo que es un canal, lo que investigaré ahora, pero si alguien lo explica rápida y simplemente creo que me bastará.

**Comment by indonoso** [comment]
La issue #595 no resuelve tu duda?

**Comment by jorgeriesco** [comment]
@indonoso Sii! :) Gracias.
