### ISSUE TITLE
Material Salas Ayuda Tarea 5

### ISSUE THREAD

**Issue by pdesolminihac** [IIC2233/Syllabus#617]
Si es que para estas salas de ayuda utilizaron algun material ¿podrían subirlo? 
Para las personas que no pudieron ir a ninguna debido a sus otros ramos

**Comment by FernandoPieressa** [comment]
Hola!

El único material usado fue el ejemplo que se subió en la carpeta de la tarea 5 sobre señales.

Saludos!

**Comment by hanavarrete** [comment]
Se subió un material más detallado a la parte de contenidos en Pyqt.
