### ISSUE TITLE
Imagen de Homero se mueve, pero se queda pegada en ventana de juego

### ISSUE THREAD

**Issue by luzmagurzua** [IIC2233/syllabus#618]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola ! En mi ventana de juego Homero se mueve pero deja "rastros" de la imagen en la pantalla, es decir, se va modificando el fondo de la ventana a medida que se apretan las teclas. A que se puede deber? (acabo de hacer push porsia) 
Gracias de antemano.[
![Captura de Pantalla 2021-06-04 a la(s) 22 01 58](https://user-images.githubusercontent.com/80796978/120876809-f57c9380-c580-11eb-84e8-e3c5d37155f0.png)
](url)

**Comment by MatiasDuhalde** [comment]
Hola @luzmagurzua !

Revisé tu código, y pude replicar el problema! El problema a grandes rasgos está causado porque ocupas el mismo método de movimiento para la ventana de preparación y la ventana de juego (la planta nuclear en este caso). Si te fijas, la imagen solo se queda pegada en una zona específica, que correspondería a la zona de colisión en la ventana de preparación que activaría la ventana de juego. En la ventana de juego, cuando homero está sobre esta zona, se vuelve a llamar al método que inicializa la ventana de la planta nuclear cada vez que se mueve, por lo que se crea un label nuevo en esa posición, que es lo que ves en el fondo. El stack trace sería `mover_label -> abrir_ventana_juego -> senal_abrir_ventana_planta.emit -> abrir_ventana_planta`.

Para arreglar esto, lo más lógico sería usar un backend distinto para ámbas ventanas, de manera que no se revise la colisión correspondiente a la ventana de preparación en la ventana de la planta nuclear. Otra solución más corta pero que podría generar un código desordenado a futuro puede ser colocar una condición que dependa de la ventana, para que impida que se vuelva a inicial la ventana de juego una cuando esta ya esté abierta.

Como nota aparte, revisa bien las rutas de las imágenes que tienes en tus archivos `.ui`. Si bien son relativas, tienen carpetas que son específicas de tu computador, por lo que no funcionarían en los nuestros.

Ojalá esto te dé una idea de como solucionar el error, y si no se entendió la explicación o sigues con problemas, comenta en esta issue! :sparkles:

**Comment by luzmagurzua** [comment]
Muchas gracias por tu respuesta, ahora creé un backend para ventana nuclear y ya no se me pega!!! :) Con respecto a los paths de las imágenes, aún no me queda muy claro que es lo que tengo que hacer. Hice un pequeño arreglo en la carpeta que guarda esos fondos (que también pensé que se agregaba a mi código general) la puse a la misma altura que está assets. Funcionará ahora? 
![Captura de Pantalla 2021-06-05 a la(s) 07 18 59](https://user-images.githubusercontent.com/80796978/120890037-567e8880-c5ce-11eb-98af-e3e493001ce6.png)

**Comment by MatiasDuhalde** [comment]
Hola de nuevo @luzmagurzua !

Perdón si fui poco claro en eso punto, volví a revisar tu repositorio, y me refería específicamente a esto:

![image](https://user-images.githubusercontent.com/46191755/120901494-4afc8300-c609-11eb-85b4-d09b268d1e94.png)

Ese es tu archivo `ventanainicio.ui`, aunque el problema también se encuentra en el resto de tus archivos `ui`. Tu path contempla carpetas más allá de lo requerido para este programa, lo cual sólo funcionaría en tu estructura específica de archivos. La idea es que los paths dentro de la tarea no se salgan del directorio `T2/`.

Si quieres probar si los paths funcionarían en cualquier otro lugar, te recomiendo copiar la carpeta T2 a otro lado de tu computador, como el escritorio, probar el programa desde ahí, y comprobar que carguen las imágenes.

**Comment by luzmagurzua** [comment]
Ya! Muchas gracias, ahora lo arreglé. Ojala si se vea jajaja
