### ISSUE TITLE
Qt Designer

### ISSUE THREAD

**Issue by cfernandez9** [IIC2233/Syllabus#618]
Hola, he buscado en mil partes pero no logro descargar ni encontrar Qt Designer en mi computador. ¿Alguien sabe cómo hacerlo? Tengo un mac OS X Yosemite 10.10.5, uso pycharm y tengo instalado PyQt5, nosé que otra información pueda ser de utilidad...Muchas gracias!!!

**Comment by hanavarrete** [comment]
Hola, intenta hacer las soluciones propuestas en [esta](https://github.com/IIC2233/Syllabus-2017-1/issues/516) issue. Avisame como te va. Saludos!

**Comment by andresfdezc** [comment]
A mí me resultó instalando Qt desde [este link](https://www1.qt.io/download-open-source/?hsCtaTracking=f977210e-de67-475f-a32b-65cec207fd03%7Cd62710cd-e1db-46aa-8d4d-2f1c1ffdacea) y seleccionando todo en la parte de Tools como sale aquí:
![screen shot 2017-10-27 at 10 18 52 pm](https://user-images.githubusercontent.com/11430184/32129946-f61b90a4-bb64-11e7-839b-259346e9f5af.png)

Luego, para abrir designer lo busqué en Spotlight como Designer.
![screen shot 2017-10-27 at 10 20 27 pm](https://user-images.githubusercontent.com/11430184/32129952-10ce3640-bb65-11e7-93dc-2336ce52eac2.png)

**Comment by cfernandez9** [comment]
@hanavarrete @andresfdezc muchas gracias a los dos!!! Estoy siguiendo esos pasos, cualquier cosa volveré a preguntar :)

**Comment by bedefrunner** [comment]
@hanavarrete @andresfdezc hola! Seguí los pasos que dijo Andrés, pero se me instaló Qt Creator...también sirve?

**Comment by andresfdezc** [comment]
@bedefrunner Si se instaló bien, Qt Designer se puede usar desde Qt Creator. Por favor revisa #628 .
