### ISSUE TITLE
Enunciado - puntajes tarea

### ISSUE THREAD

**Issue by AmbrosioV** [IIC2233/Syllabus#618]
Holi! Podrían por favor subir los porcentajes/puntajes de cada parte de la tarea, para enfocarnos en lo que realmente vale y así rendir mejor. En las tareas pasadas estaban así que no veo por qué esta no los tiene.
Eso saludos ✌️

**Comment by rrhurtado** [comment]
Hola, ya fueron actualizados los puntajes de cada ítem en el enunciado.

Saludos !
