### ISSUE TITLE
Nombres sin distinción entre mayúsculas y minúsculas

### ISSUE THREAD

**Issue by camilapavesi** [IIC2233/syllabus#618]
Hola! 
Disculpa si ya hicieron esta pregunta, me leí todas las issues y no la encontré.
El enunciado pide que los nombres del jugador y rival no tengan distinción entre mayúsculas y minúsculas. ¿Qué significa esto en la práctica? ¿Tengo que chequear algo con respecto a esto?
Gracias! :)

**Comment by vsantelicest** [comment]
Hola **@camilapavesi**!
La no distinción de minúscula y mayúscula se refiere a que el programa debería tomar los nombre "CAMILA" y "camila" como iguales, sin embargo, esto no tiene ninguna incidencia en la escritura del programa porque en ningún minuto se define que este nombre debe ser diferente al de alguna otra persona.
Suerte!! 🏋️

**Comment by camilapavesi** [comment]
Muchas gracias!! :)
