### ISSUE TITLE
Clase Iterable, Iterador Ofertones AS02

### ISSUE THREAD

**Issue by macavarelau** [IIC2233/syllabus#618]
Me gustaría saber cómo se hacía esta parte. Hice algo, pero me tira errores que no entiendo, como el siguiente:
RecursionError: maximum recursion depth exceeded while calling a Python object
Si es posible, me gustaría saber alguna solución de cómo resolver esa parte de la actividad, no me gusta quedarme con la duda :( gracias!!!

**Comment by Juampisaez** [comment]
me sumo a la duda

**Comment by dlmed** [comment]
Yo al menos hice esto:

``` python
class IteradorOfertones:
    def __init__(self, iterable):
        self.iterable = copy(iterable)

    def __iter__(self):
        return self

    def __next__(self):
        if not self.iterable.productos:
            raise StopIteration()
        maximo = max(self.iterable.productos, key=lambda x: x.descuento_oferta)
        self.iterable.productos.remove(maximo)
        maximo.precio = maximo.precio * (1 - maximo.descuento_oferta / 100)
        return maximo
```

**Comment by igbasly** [comment]
Hola!

**Comment by igbasly** [comment]
**Hola a todos! 😄**

Primero @macavarelau, tu error se produce por un exceso de recursiones detectado por python. Esto se puede deber a que tu recursión no considera un caso de detención o no se están haciendo cambios para que se llegue a ese caso. De todas formas, puede ver la issues #613 de un tema similar.

---
Respecto a cómo se resolvía esta sección de la actividad, lo que plantea su compañero @dlmed es una solución válida para el iterador, pero como siempre les decimos, no es la única.

### Repaso y contexto :books::
Para entender cómo funciona esto, primero aclaremos que son los iterables e iteradores. 
* Los **iterables** son aquellos objetos sobre los cuales se puede iterar, es decir, recorrer su elementos de a uno. En términos de código en Python, son aquellos objetos que implementen el método `__iter__`, el cual siempre retorna un iterador.
* Los **iteradores** por otro lado, son aquellos objetos que recorren otro objeto (iterable) y nos entregan sus elementos de a uno. Lo que en Python se traduce como la implementación del método `__next__` que va entregando un elemento en su llamada.
En este caso por temas de la actividad, el iterador e iterable se hicieron como clases distintas, pero no necesariamente tiene que ser así.

Como el iterable, en este caso `IterableOfertones`, ya venía implementado solo quedaba completar `IteradorOfertones` que recibía una instancia del iterable y la guardaba en el atributo `iterable`. Pueden notar que recibía una instancia **en el método `__iter__` del iterable** donde se instancia el iterador como `IteradorOfertones(self)`y el argumento es la misma instancia del iterable, no la lista de productos.

### Concepto de solución 🗒️ :

Ahora, en el iterador se debe completar `__iter__` y  `__next__`, donde `__iter__` debe retornar una instancia del iterador para **el iterable en el mismo estado en que se encuentre**, es decir, aquí debe haber una persistencia de los datos del iterable. Una solución para esto es `return self` como lo hizo su compañero, ya que es un iterador (es el mismo) y mantiene los datos del iterable iguales (nuevamente porque es el mismo). **(1)**

Para `__next__` hay que considerar dos cosas:
1. Detener el retorno de datos cuando el iterable "se haya acabado" (lo hayamos recorrido completamente) mediante `raise StopIteration()`.
2. Devolver de a uno los datos que el iterador contenga.

Como ya daban hecho `self.iterable = copy(iterable)`, o sea, una copia del iterable, se podía trabajar directamente removiendo objetos de `self.iterable` ya que no se alteraría el iterabale original.
Como ya mencionamos, `self.iterable` del iterador es una instancia de la clase `IterableOfertones` por lo tanto, los datos con los que se necesita trabajar están en `self.iterable.productos` que es una lista con instancias de `Producto`.
 
Además nos piden que se itere ordenadamente de mayor a menor en base al descuento que tenga el producto, entonces para poder recorrer todos los productos una única vez básicamente se tiene dos opciones:
1. Quitarlo de la lista.
2. Llevar una cuenta de qué productos se han entregados sin quitarlos. Esto puede ser con una lista auxiliar, indices, guardando el último entregado, etc.

Para ambos casos, se tiene la opción de ordenar o no la lista de elementos, considerando la dificultad que pueda traer en cada caso.

Su compañero utilizó la opción 1 sin ordenar la lista, donde eligió que producto entregar mediante la función `max` junto a un criterio con una función `lambda`, lo cual además era un *hint* en el enunciado.
Como se van a quitar elemento de la lista, si intentasen hacer `max` de una lista vacía obtendrían un error. Por lo tanto, **es muy importante** en este caso verificar que hayan o no elementos en la lista (traducido a saber si se recorrido el iterable) antes de elegir un producto y avisar que se terminó la iteración. Lo cual hace mediante un `if`.

Para la actividad, además se les solicitó manipular el objeto `Producto` y actualizar su precio en base al descuento antes de entregarlo, entonces, una vez elegido el producto bastaba actualizar su precio con el porcentaje correspondiente y ya se podía retornar.

---

Eso fue un resumen de como se podía resolver esta sección de la actividad, pero no piensen que solo hay una forma, intenté dejar lo más abierta la respuesta. Les recomiendo además ver el [cierre de la AS](https://cursos.canvas.uc.cl/courses/7943/pages/cierre-actividad-sumativa-2), ya que ahí se explican estos y más conceptos. 
Espero haber aclarados sus dudas al respecto, escríbannos en cualquier otro caso :+1:

----
(1) Pueden revisar más acerca de la importancia de este elemento en el [contenido de la semana](https://github.com/IIC2233/contenidos/blob/master/semana-06/1-iterables-generadores.ipynb).

**Comment by igbasly** [comment]
**Como recomendación para *issues* futuras, cuando quieran compartir su forma de hacer una actividad, háganlo a nivel de concepto e idea más allá de publicar su código explícito. ❤️ **

**Comment by dlmed** [comment]
Lo siento! pensé que como ya había terminado la AS no había problema.

**Comment by igbasly** [comment]
@dlmed no te preocupes 😅 , no es porque haya algún problema, pero no queremos que se establezca algún tipo de **"es la solución"**, sino más bien un **"es una forma"**. Además les sirve para practicar como explicar el código, lo que en el fondo es un algoritmo y es la base de la computación :raised_hands:.
