### ISSUE TITLE
Duda módulos T05

### ISSUE THREAD

**Issue by llloyola** [IIC2233/Syllabus#618]
Al momento de subir nuestra tarea, debemos tener un sólo ```backend.py``` o podemos dividir nuestro _backend_ en varios módulos? Me explico... Por un tema de comodidad y orden, yo podría tener los módulos ```backend_personajes.py```, ```backend_casillas.py```, ```backend_powerups.py``` e importar todo eso a ```frontend.py``` o debe haber un sólo módulo relacionado a todo lo que es el _backend_?

**Comment by santilaguna** [comment]
@mfanselmo1  Hola! 
sumándome a esta pregunta, aplica también para frontend no?

**Comment by hanavarrete** [comment]
@santilaguna  Si, aplica. Saludos
