### ISSUE TITLE
os.add_dll_directory(dll_path) en Python 3.7.4

### ISSUE THREAD

**Issue by dlmed** [IIC2233/syllabus#619]
Hola, estoy ocupando un programa de simulación que usa python como un *remote API* y resulta que para poder tener la conexión lista entre el programa y mi código, tengo que usar un módulo que al parecer importa unos `.dll`, pero no entiendo del todo el código:

```python
import platform
import struct
import sys
import os
import ctypes as ct

libb0 = None
prefix, suffix = 'lib', '.so'
if platform.system() in ('cli', 'Windows'):
    prefix, suffix = '', '.dll'
if platform.system() in ('Darwin', ):
    suffix = '.dylib'
for path in ('.', 'build', '../../build'):
    fullpath = os.path.join(os.path.dirname(__file__), path)
    if not os.path.isdir(fullpath): continue
    libb0_fullpath = os.path.join(fullpath, '%sb0%s' % (prefix, suffix))
    if os.path.exists(libb0_fullpath):
        libb0 = ct.CDLL(libb0_fullpath)
        break
if libb0 is None:
    raise RuntimeError('%sb0%s not found' % (prefix, suffix))
```
De lo que entendí del código es que busca `b0.dll` en mi directorio de trabajo, pero este se encuentra en la carpeta del programa, por lo que buscando en internet encontré que una posible solución era hacer `os.add_dll_directory(dll_base_path)` (donde `dll_base_path = 'C:\Program Files\Programa'`), pero cuando ejecuto el código me sale un AttributeError, diciendo que `os` no tiene el atributo `add_dll_directory`, entonces en python3.7.4 no existe esta funcionalidad? cómo tendría que hacerlo para lograr lo que quiero?

**Comment by aaossa** [comment]
Hola @dlmed , no estoy familiarizado con el código que compartes, pero mirando [la documentación de Python 3.7](https://docs.python.org/3.7/library/os.html), al parecer `add_dll_directory` no está implementado. Sin embargo, sí está presente en [la documentación de Python 3.8](https://docs.python.org/3/library/os.html#os.add_dll_directory) (ojo que la función solo está disponible para Windows). Puedes cambiar entre versiones en la documentación con el *dropdown* que está en la parte superior de la página.

Si quieres utilizar esa función sí o sí, supongo que una opción es utilizar Python 3.8 (que tendrías que instalar y tener cuidado de usar 3.7 para cosas relacionadas con este curso) o intentar implementar la función por tu cuenta, lo que no es trivial. En este caso te recomendaría probar con Python 3.8, ya que al parecer la función `add_dll_directory` va de la mano con [temas de seguridad](https://docs.python.org/3.8/whatsnew/3.8.html#bpo-36085-whatsnew) asociados a la importanción de los archivos *.dll. 

PS: Si te interesa, aquí está [la *issue*](https://bugs.python.org/issue36085), en el *bug tracker* de Python, que motivó la adición de dicha función en Python 3.8.

**Comment by dlmed** [comment]
Gracias! creo que optaré por copiar todos los dll a mi directorio de trabajo jejeje
