### ISSUE TITLE
Clase objeto no me funciona correctamente

### ISSUE THREAD

**Issue by a-ck** [IIC2233/syllabus#619]
* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Hice una clase "Objeto" en el backend pero cuando intento instanciarla en el frontend no me aparece como me gustaría (como un label dentro de la ventana), si no que me aparece como una ventana diferente... no sé si me explico, desde ya gracias!

**Comment by clementevalladares** [comment]
Hola @a-ck, es posible que a tu QLabel no le estés pasando a la ventana como su parent. Recuerda que al crear un este tipo de objetos debes pasarle el widget al que pertenecen.
`self.label = QLabel(parent)`
En caso de no hacerlo, este objeto aparecerá como una ventana independiente.
Si no se trata de esto puedes subir tu código a tu repositorio para ver cual puede ser el problema.

**Comment by a-ck** [comment]
Ahí subí mi código pq creo que no es eso :( Lo que te digo está en ventana_juego línea 150 en adelante y la definición de la clase está en logica_juego :)

**Comment by clementevalladares** [comment]
@a-ck Logré solucionar el problema usando la solución que te di. Probablemente no se entendió como aplicarla en el contexto de tu programa.
En este caso, tu clase Objeto hereda de QLabel. Para que un QLabel se muestre como un objeto al interior de una ventana, y no como una ventana en si misma, debes entregarle como argumento parent la ventana en específico.
Por ejemplo, si tienes un QWidget llamado ventana, y quieres crear un nuevo QLabel dentro de ella, lo debes hacer de la siguiente manera:
```
class Ventana(QWidget):
    def __init__(self):
        super().__init__()
        self.label = QLabel(self)
```
Como puedes ver, al QLabel se le está entregando a la ventana como parent a través de `self`.
En el caso de tu programa en específico, esta definición tiene un paso adicional, debido a que creaste una clase que hereda de QLabel (Objeto), por lo tanto, si quieres entregar el parent como argumento, debes asegurarte de hacerlo a través del `super().__init()`.
Siguiendo estos pasos, la implementación dentro de tu programa es la siguiente:
En primer lugar, podemos identificar que de la manera en que se instancia tu clase Objeto actualmente, no hay ninguna referencia al parent, por lo que lo agregamos como nuevo argumento y se lo entregamos al `super().__init__()`
![image](https://user-images.githubusercontent.com/69611854/120878851-164ae600-c58d-11eb-9401-5dd604376ba7.png)
![image](https://user-images.githubusercontent.com/69611854/120878857-2662c580-c58d-11eb-89e2-26dc1039b831.png)
Posterior a esto, hay que asegurarse que cada vez que se esté creando un objeto de clase Objeto, le estemos pasando al parent como argumento final.
![image](https://user-images.githubusercontent.com/69611854/120878890-79d51380-c58d-11eb-9cbb-dfe0162fac38.png)
![image](https://user-images.githubusercontent.com/69611854/120878899-88bbc600-c58d-11eb-98a5-0d44b7fac4e6.png)
(línea 150 en ventana_juego.py)
Utilizamos `self` para entregar como parent debido a que esta clase se está creando dentro del QWidget que almacenará a tu QLabel, por lo que `self` hace referencia a sí misma.
Haciendo esto ya deberían aparecer los objetos dentro de tu ventana.
![image](https://user-images.githubusercontent.com/69611854/120878969-f7008880-c58d-11eb-87b7-d73c303d4607.png)
Espero haya quedado claro c:

**Comment by a-ck** [comment]
Ahora entendí disculpa!!!!!!! Muchísimas gracias en serio, lo implementaré :D
