### ISSUE TITLE
T01 Duda herencia

### ISSUE THREAD

**Issue by daniela-carreno** [IIC2233/syllabus#619]
Hola! En herencia es super útil tener métodos en la clase padre para no repetirlos en cada clase hija si se comportan igual, en ese sentido los "hijos" conocen los métodos de los "padres".  Mi duda es, una clase padre reconoce que tiene hijos?

Mi pregunta surge de que la clase DCCrotona debe pagar el doble de dinero para intentar sanar una lesión. Entonces empecé haciendo un método sanar en la clase padre y no se me ocurre como mandarlo a un método de la clase hija que le aplique el cobro extra o que reconozca el nombre de la clase hija a la que pertenece para hacer este cobro. Se entiende? 

Gracias!

**Comment by baosse** [comment]
Holaa Dani!
Cuando ocupas herencia la clase hija siempre sabe lo que hacen los métodos de la clase padre. Por lo tanto la mejor manera de que la padre reconozca la de la hija es cuando haces súper y le mandas los atributos correspondientes. Igual puedes hacer una función en la hija sin necesariamente llamar al método  de la padre.
Espero te haya quedado más claro 💙

**Comment by daniela-carreno** [comment]
En ese caso el método del padre debe ser abstracto o no necesariamente ? En el caso de mi situación voy en esto:

`class Delegacion(ABC):`
`    @abstractmethod`
`    def sanar_deportista(self):`
`          blablabla `

`class DCCrotona(Delegacion):`
`    def sanar(self):`
`          super().sanar_deportista()`          

pero ahora tengo el siguiente error "TypeError: Can't instantiate abstract class DCCrotona with abstract methods sanar_deportista".  Estaba pensando quitar el decorador del método abstracto y agregarle inputs, pero no se si el método padre puede pedir inputs y el hijo no. Quedaría algo asi a lo que me refiero:


`class Delegacion(ABC):`
`    def sanar_deportista(self, ponderador):`
`          blablabla * ponderador`

`class DCCrotona(Delegacion):`
`    def sanar(self):`
`          super().sanar_deportista(ponderador)`     

muchas gracias por tu respuesta! :)

**Comment by daniela-carreno** [comment]
@baosse  lo solucione y funciona!! 😄  
Saqué el decorador y no tuve problema para que el padre pidiera un input y el hijo no.

Pero me surgió otra duda, cuando se ocupa un método abstracto ? pensé que era para situaciones como en la que estaba hace un ratito

**Comment by baosse** [comment]
Que buena! Me alegro de que te haya funcionado! 💙 
Un método abstracto se utiliza cuando tienes una acción común en tus clases hijas pero que cada hija se desarrolla de manera distinta. Por ejemplo:

class Padre(ABC):
@abstractmethod
def acción(self, parametro):
if parametro > 5:
return True
else:
return False

class Hija_1(Padre):
def acción(self):
if super().acción(parmetro) is True:
blablabla

class Hija_2(Padre):
def acción(self):
if super().acción(parmetro) is True:
blablabla

Aquí las dos clases hijas ocupan a la padre para tener una confirmación para realizar una acción, pero cada acción a desarrollar en estas puede ser distinta. De igual forma, en la clase padre podría retornar algo distinto (número, lista, diccionario, etc) que se use de manera distinta en cada hija.
Espero que te haya quedado más claro y que te ayude con tu tarea (ya que lo debes ocupar 👀 )!
Mucho éxito con tu tareaa!✨

**Comment by daniela-carreno** [comment]
Bacaaaan! Muchas gracias. Sin saberlo lo estaba usando, le agregaré el decorador para que quede bien implementado.
