### ISSUE TITLE
Cómo mandar información con un QPushButton

### ISSUE THREAD

**Issue by mnbenimeli** [IIC2233/syllabus#619]
Hola, quería saber si es que hay manera de mandar más información con un botón, aparte de que este fue apretado o no.
Como en la tarea para la ventana de salas de crea una cantidad arbitraria de salas, tengo una cantidad arbitraria de botones "unir", por lo que quiero usar una misma funcion unirse_a_sala(self, valor) donde valor dependa de qué butón en mi Qgridlayout haya sido apretado.

Muchas Gracias!

**Comment by ariel-m-s** [comment]
¡Hola, @mnbenimeli!

Sí, se puede. Yo conozco dos maneras. La primera es a través de ```partial``` de la librería ```functools```. Esta herramienta sí se puede usar, tal como se mencionó en la _issue_ de librerías (#460). También lo puedes hacer a través de funciones anónimas (con la _keyword_ ```lambda```).

Te dejo [este link de StackOverflow](https://stackoverflow.com/questions/18925241/send-additional-variable-during-pyqt-pushbutton-click) y [este link del _blog_ de alguien](https://eli.thegreenplace.net/2011/04/25/passing-extra-arguments-to-pyqt-slot/) para que los leas y entiendas cómo funciona 😎.

Cualquier duda coméntala por acá mismo,

Ariel
