### ISSUE TITLE
ImportError: dlopen

### ISSUE THREAD

**Issue by Sweinzierl28** [IIC2233/syllabus#619]
Al intentar correr mi programa desde la terminar me aparece este error al intentar importar la libreria PyQt5. Esto me pasa solo desde la terminar porque desde el editor me abre bien.

![Captura de pantalla 2019-12-06 a las 16 19 09](https://user-images.githubusercontent.com/53844747/70350978-a8621900-1846-11ea-8aef-254537adb291.png)

**Comment by DCCollao** [comment]
Hola!

Buscando un poco encontré [esto](https://stackoverflow.com/questions/35989572/importerror-dlopen-symbol-not-found-pycodecinfo-getincrementaldecoder), que en resumen dice que desinstales la librería en conflicto tanto de pip como de brew, y luego instales con brew. 

[Acá](https://stackoverflow.com/questions/43531245/pyqt5-not-working-on-macos-sierra) hay otra persona que solucionó ese error específicamente con PyQt5

Avísame si te sirve alguno de esos métodos!

**Comment by Sweinzierl28** [comment]
Al final me di cuenta que el terminal estaba funcionando con el python3.6 y el editor con el 3.7, asi ahora me funciona si llamo al archivo directamente con 'python3.7 main.py',
Gracias
