### ISSUE TITLE
Máximo tamaño personaje

### ISSUE THREAD

**Issue by JPSF** [IIC2233/Syllabus#619]
Hola me surgió la duda de cuanto sería el máximo tamaño que se puede alcanzar, ya que en el enunciado dice que existen 10 tamaños diferentes, pero el personaje empieza con tamaño 2 en la etapa1(nivel1 del personaje). Como el personaje sube dos unidades de tamaño por cada etapa completada, entonces al empezar la etapa 5 el personaje tendrá tamaño 10, y luego al completar los 500 puntos de experiencia en esa etapa tendría que volver a aumentar una vez más de tamaño antes de que el juego termine
¿Asumimos que el personaje no volverá a aumentar de tamaño en la quinta etapa, o agregamos un tamaño extra?

**Comment by vijuarez** [comment]
Hola!

Una vez alcanzado el tamaño 10, el jugador ya no puede crecer más. Por lo tanto, el tamaño máximo es 10.

Saludos!
