### ISSUE TITLE
assets/nukeman.png

### ISSUE THREAD

**Issue by llloyola** [IIC2233/Syllabus#619]
Hola! Leí el enunciado, pero no me quedó claro para qué se usaría la imagen ```nukeman.png``` que está entre los assets de la tarea. Gracias de antemano :)

**Comment by hanavarrete** [comment]
Esa imagen era para un poder que no alcanzó a llegar a la versión final. Lo vamos a sacar, así que solo ignóralo por el momento. Saludos!
