### ISSUE TITLE
Filtro Equalizador

### ISSUE THREAD

**Issue by jgramsch** [IIC2233/Syllabus#619]
Hola! 
Una pregunta, para aplicar el ecualizador hay que solo hacer lo siguiente?
- multiplicar el samplerate por f
- separar los canales de la cancion (4 para el canal 1 y 4 para el canal 2, intercalados)
- tomar cada canal y aplicar la formula para cada chunk (4 bytes) 

eso?
donde se usa el n que aparece en el enunciado?
Gracias!

**Comment by DiegoAndai** [comment]
Hola! en el enunciado hay un par de errores, asi que para hacer el ecualizador ten en cuenta lo siguiente:
- separar canales: en data, los canales van intercalados: [sample_ch1, sample_ch2, ...] entonces tienes que separar por samples. El tamaño de estas está dado por el header (BitsPerSample) y en general van a ser 16 bits por lo tanto 2 bytes para canal 1 luego 2 para el 2 etc...
- luego tomo la secuencia de samples de cada canal y aplico la formula a cada sample (si el BitsPerSample es 16, entoces de 2 bytes cada uno).
- El n es la cantidad de veces que se realiza la filtración, si n es mayor a 1, se hace de nuevo el proceso partiendo ahora desde los datos procesados.

**Comment by jgramsch** [comment]
Buena Gracias ! me quedó claro

**Comment by vaguila95** [comment]
Hola! 
Me surgió una duda respecto este filtro: en el enunciado dice que lo único que debemos hacer en el header es multiplicar la sección de SampleRate por f, pero luego  debemos aplicar n veces el filtro a la data. ¿Esta situación no genera incongruencias?

**Comment by DiegoAndai** [comment]
@vaguila95 Perdón, no había visto tu comentario. Creo que #641 y #639 deberían responder tu duda.
