### ISSUE TITLE
Programación genérica

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#62]
Hola, el diagrama de clases con clases específicas para cada cosa me está quedando demasiado grande y básicamente no me cabe en R². ¿Puedo usar programación genérica sin que consideren que está "mal modelado"?

**Comment by jmwielandt** [comment]
Aclaración: digo programación genérica pero solo me refiero a hacer clases más "generales" en cuanto a que tengan todos los métodos y atributos de varias instancias diferentes y no usen todo.
Nada relacionado con "globals()"

**Comment by Arcoirisky** [comment]
Yo le daría una vuelta más a tu diagrama y así analizar qué cosas realmente deben ser una clase y cuáles no. Pero, no puedes hacerlo más genérico porque no estaríamos corrigiendo el diagrama que realmente habías creado, sino otro :/

**Comment by ciquezada** [comment]
Hola, 
Yo también tengo algunas dudas sobre herencia en esta parte y no entendí bien la respuesta.
En mi caso también tengo el dilema si escribir las tres clases de raza por separado (donde tendrían los mismo atributos con distinto valor por lo que me parece raro escribir tantas veces lo mismo) o crear una clase general con esos atributos y un montón de properties que hagan depender sus valores según la raza del heredero,
¿Qué es mas correcto?

**Comment by Hernan4444** [comment]
@ciquezada, en tu caso lo correcto es hacer el diagrama con la 3 clases que mencionas porque eso es lo que realmente modelaste. Si haces una clase general, los ayudantes no sabremos que hiciste 3 clases,  sino pensaremos que solo hiciste 1. 

**Ojo**, en el diagrama no se pone los valores de los atributos, solo los atributos/método/properties que tiene y si es que estás heredando, los atributos solo deberían estar escrito en la clase padre así que no lo estarías escribiendo tanta veces.  Si es que estás heredando y cada clase crea los mismos atributos en su `__init__`, lo cual te obliga a escribir cada atributo en las clases para el diagrama, entonces debe haber un mal concepto de la herencia.

Saludos!
