### ISSUE TITLE
Confusión simulando los sucesos

### ISSUE THREAD

**Issue by glbello** [IIC2233/Syllabus#62]
Estoy confundido respecto a la situación de los incendio y las movilizaciones de los recursos, si usuario no ha elegido ninguna estrategia de extinción y solo se ha dedicado a ver la base de datos (situación de todo), ¿el sistema debe automaticamente haber movilizado los recursos acorde fueron apareciendo los incendios en el tiempo?, de ser así, ¿debe escoger alguna estrategía de las mencionada en el enunciado (de forma aleatoria) o aplicar cualquier criterio que estime? Osea pensaba que si me meto a la fecha muy lejana, y no se estableció ninguna estrategia de extinción, los incendios del pasado debieron (por la expansión a través del tiempo) haber incendiado ya practicamente al mundo entero (porque los recursos no se les movilizó nunca)... no se... estoy algo bloqueado con eso (vi issue anteriores pero no vi que me aclara la idea).

**Comment by rpalmaotero** [comment]
El sistema sólo calcula estrategias si el usuario lo pide. Los recursos sólo se movilizan si así lo determina una estrategia. Por lo que no es necesario que el sistema movilice recursos automáticamente. Puedes asumir que los usuarios serán razonables en sus acciones (no quieren ver al mundo arder).

![43755c762c0e437638f96eaa6750e008](https://cloud.githubusercontent.com/assets/6728087/23980116/8c77f5fa-09dc-11e7-9150-87dd3299647e.jpg)

**Comment by glbello** [comment]
Genial ahora si puedo seguir avanzando con confianza, muchas gracias 😺
