### ISSUE TITLE
Complejidad temporal del código

### ISSUE THREAD

**Issue by gsinay** [IIC2233/Syllabus#62]
### Prerrequisitos

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/21)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/20)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Quiero saber si hay alguna restricción en cuanto a la complejidad temporal de nuestro código para solucionar tableros. Me preocupa especialmente para tableros más grandes, donde hay muuuuchas combinaciones de tableros validos posibles. Si hay una restricción, ¿cuál es el tamaño máximo del tablero que nos pedirán solucionar y cuál es el tiempo máximo permitido para la solución? Gracias!

**Comment by cegalleta** [comment]
Hola!!

No debería haber problemas con el tiempo de ejecución, si bien entiendo que el tamaño del tablero aumenta la complejidad con el orden  n^2 y que eso puede ser inconveniente, no usaremos tableros que generen inconvenientes al momento de ejecutar las tareas.

En caso de que quieras calcular combinaciones o permutaciones de forma eficiente, te recomiendo aplicar lo aprendido sobre estructuras de datos para evitar anidar iteraciones sobre las listas.
