### ISSUE TITLE
T0 - guardado de puntaje y usuario malévolo

### ISSUE THREAD

**Issue by 3rdPix** [IIC2233/Syllabus#62]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Es necesario lidiar con la malintención de un usuario malévolo? En concreto, cuando el jugador elige un nombre: tal nombre deberá ser guardado posteriormente si él mismo decide guardar una partida en progreso. Se nos indica que en tal caso el archivo debe **tener el nombre del usuario**.  En este contexto, pueden surgir problemas si el usuario decide experimentar con nombres que *rompen* el funcionamiento del sistema operativo, al ingresar caracteres inválidos tales como ":&¬|" o incluir en su nombre ".txt" o ".csv", etc.
Por ejemplo, un usuario puede querer llamarse
- El rompe novias.csv
- nomegustaprogramar¬|||
- ♪pepito>☻
Cómo debo lidiar con esto? simplemente se debe restringir la posibilidad de nombres extraños en el código, agregando así una funcionalidad más que debemos programar? O es correcto asumir que no hay usuarios malévolos que intentarán romper el funcionamiento con ese tipo de nombres?

**Comment by vicentethomas** [comment]
Hola! Para que no pase lo que comentas, podrías verificar con un `if` si el nombre ingresado está compuesto solo de caracteres alfanuméricos (puedes usar `nombre.isalnum()` que te entrega False si tiene algún carácter que no sea alfanumérico). Si haces esto, también debes especificar en el readme que el nombre de usuario solo admite ese tipo de caracteres para que no haya problemas. Con eso te aseguras que ningún usuario pueda poner algo que llegue a generar error.
