### ISSUE TITLE
archivo acciones.csv , desorden? 

### ISSUE THREAD

**Issue by jfpena1** [IIC2233/syllabus#62]
Hola, queria saber si es posible que la primera fila del archivo acciones.csv venga, al igual que civilizaciones.csv, en posible desorden respecto a lo mostrado en el enunciado.

Muchas gracias

**Comment by DCCollao** [comment]
Hola! 

Los archivos .csv que les entregamos vienen ordenados con headers (en el caso de civilizaciones.csv: turno, id_civilizacion, tipo_accion).  El orden de estos headers podría cambiar, y por esto es necesario que te guíes por ellos en tu lectura de archivos.

Saludos

**Comment by quememo** [comment]
### Las filas del archivo acciones.csv podrían venir desordenadas?
**Ejemplo:**

_turno,id_civilizacion,tipo_accion,input
7,0,Recolectar recurso,piedra;1
1,0,Recolectar recurso,oro;2
4,0,Recolectar recurso,oro;1
1,2,Recolectar recurso,madera;2
2,0,Recolectar recurso,oro;1
1,1,Recolectar recurso,oro;2_

O se asume que las filas irán en orden según el header **turnos**? (Tal como viene en el archivo original contenido dentro de la carpeta "_data_")

**Comment by lily416** [comment]
@quememo  Hola :)

__No__ puedes asumir que el archivo vendrá ordenado por filas. 
Para saber el orden de las acciones es que se les entrega el _header_ `turnos`.

Saludos y éxito con la tarea :wave: 🏰

**Comment by quememo** [comment]
@lily416 En tal caso bajo que criterio se decide cual CPU juega primero? En el archivo ambas indican que realizan acciones en cada turno y el id de cada una no determina su orden, sería correcto que yo determinara arbitrariamente cual CPU juega primero?

**Comment by quememo** [comment]
El header turnos solo me indicaría que acciones realiza cada CPU en determinado turno, pero dentro de ese turno no me indica cual realiza su acción antes que la otra

**Comment by lily416** [comment]
@quememo 

Queda a tu criterio cuál CPU juega primero, recuerda indicar en tu `readme.md` la decisión que tomes.

:wave: :desktop_computer:
