### ISSUE TITLE
NameError: name 'utf8' is not defined

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2233/syllabus#62]
Tengo un problema al abrir el archivo post.csv en modo de escritura ya que cuando hago eso me arroja el siguiente error
* Traceback (most recent call last):
  File "CORRECODIGO.py", line 18, in <module>
    for cada_post in leer_posts:
  File "C:\Users\ripley\AppData\Local\Programs\Python\Python37\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 1251: invalid start byte
Para probar mi código copie los archivos a otra carpeta, una vez que me aparece este error mi código termina pero al intentar correrlo nuevamente solo me arroja este error y para que vuelva a funcionar tengo que "resetear" mi archivo a esto me refiero a reemplazarlo por el que se subio originalmente.Intente usar el enconding=utf8 para solucionar esto pero al hacerlo me arroja este error
*Traceback (most recent call last):
  File "CORRECODIGO.py", line 76, in <module>
    edit=open("./posts.csv","w",encoding=utf8)
NameError: name 'utf8' is not defined

**Comment by matiasmasjuan** [comment]
Hola @RonaldoSosa!

Recuerda que al utilizar el código:

```open('archivo.ext', 'w', encoding='utf-8')```

El comando ```'w'``` borra todo el contenido si es que no escribes nada sobre el archivo, lo que podría estar ocasionando el primer error.

Con respecto al segundo error, recuerda que en el ```encoding='utf-8'```, debe estar escrito con comillas y con un guión ```-``` entre el ```utf```y el ```8```.

Espero haber entendido el error y sino, no dudes en escribir nuevamente!

**Comment by benjavicente** [comment]
@matiasmasjuan `utf8`, `u8`, `utf` y `utf-8` [parece que son lo mismo](https://docs.python.org/2/library/codecs.html#standard-encodings).

> UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 1251: invalid start byte

Eso puede ocurrir cuando se guarda el archivo con una codificación distinta a la usada cuando se lee, entonces en la segunda lectura del archivo no se puede decodificar el archivo.
El parámetro `encoding="utf-8"` debe estar tanto en la lectura como escritura.

> edit=open("./posts.csv","w",encoding=utf8)
NameError: name 'utf8' is not defined

Eso es porque `utf8` es una variable no definida y no un string. Debería ser `"utf-8"`.

**Comment by RonaldoSosa** [comment]
El problema se arreglo!Muchas gracias
