### ISSUE TITLE
Duda con eliminar una publicación

### ISSUE THREAD

**Issue by conicorreag** [IIC2233/Syllabus#62]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Cuando se elimina una publicación, ¿se mantienen los id de las otras, o las que estaban por debajo de la que se eliminó suben uno?

**Comment by catalina-arcila** [comment]
Hola @conicorreag, no está especificado en el enunciado por lo que puedes hacerlo como te parezca conveniente. Recuerda explicar tus supuestos en tu _README_!
