### ISSUE TITLE
Se me borraron los datos del archivo "usuarios.csv"

### ISSUE THREAD

**Issue by luzmagurzua** [IIC2233/syllabus#62]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola! Por accidente quería probar algo y escribí f = open("usuarios.csv","w") y se me borró toda la información (después recordé que con "w" se emepzaba un archivo desde 0) y ahora no funciona nada de mi código porque se actualizó el archivo a uno en blanco :(. ¿Cómo lo puedo recuperar?

**Comment by Tsbalart** [comment]
Hola @luzmagurzua! El archivo original debiese estar en tu copia del syllabus, puedes acceder a ella manualmente y volver a copiar el archivo "usuarios.csv" a tu carpeta personal. Cuentame si no te funciona :)

**Comment by luzmagurzua** [comment]
Tienes razón jajajaja. Ya lo copié denuevo, muchas gracias
