### ISSUE TITLE
Duda al actualizar encomiendas

### ISSUE THREAD

**Issue by SrGuspin** [IIC2233/Syllabus#62]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola!
Como las encomiendas tienen el atributo fecha, que posee el momento en el cual fue creada, **¿Ésta debe de ser actualizada cuando se actualiza su respectivo estado como administrador?** Es decir, si la fecha de cuando la encomienda fue creada es "24/03/2022 10:10:10", y está con el estado de "Emitida". Cuando se pasa su estado de "Emitida" a "Revisada por agencia" **¿ésta fecha deberia de ser actualizada a la fecha del momento de modificación?**

Muchas gracias de antemano! :D

**Comment by Emiliax16** [comment]
Hola! no se debe modificar la fecha, ya que esta es la fecha de creación de la encomienda, no de cuando se actualiza. Saludos.
