### ISSUE TITLE
Ejercicio 6.1: Set números aleatorios

### ISSUE THREAD

**Issue by margavicunas** [IIC2233/syllabus#62]
Hola!
La primera parte del ejercicio la hice sin problemas con un while pero me surgio la duda sobre cómo hacer lo mismo usando una estructura por comprensión. Hice un poquito de trampa y simplemente tomé el set que ya había creado antes para poder iterar sobre él y así replicar el resultado usando lo pedido (muy tramposa, lo sé). ¿Podrían darme una pista sobre cómo esperan que lo resolvamos?

De antemano gracias :)

**Comment by tocococa** [comment]
Hola @margavicunas ! 
Por lo que dices me imagino que ya sabes como obtener un número aleatorio usando `randint(a, b)` y también para que sirve la función `range(c, d)`. Si revisas atentamente la materia de sets te vas a dar cuenta de cómo incluir ambas funciones en la definición de un set por comprensión.

>! a = {x for foo in bar}

Si aún así te quedan dudas por favor responde este mismo mensaje.

**Comment by margavicunas** [comment]
Hola!
No si eso lo entiendo :) Pero no se me ocurre cómo podría hacer para seguir agregando números random al set hasta tener los 100. Imagino que iterar sobre range(100) (tipo a = { randint(0,100) for i in range(100)} ) no serviría porque podrían salir algunos números repetidos que no se van a agregar al set, ¿se entiende? igual puedo intentar explicarme de nuevo jeje.

Gracias!

**Comment by tocococa** [comment]
> iterar sobre range(100) (tipo a = { randint(0,100) for i in range(100)} ) no serviría porque podrían salir algunos números repetidos que no se van a agregar al set

Esa es justamente la idea detrás del ejercicio, que te puedas dar cuenta que a un set no se agregan elementos repetidos. En el enunciado nunca te dicen cuántos elementos tiene que tener el set resultante 🙀. Además, un set con todos los números del 0 al 100 tendría 101 elementos (0 y los otros 100 números) y no sería práctico poblarlo con enteros aleatorios entre 0 y 100 si esperamos que el resultado sean todos los números del 0 al 100.

**Comment by margavicunas** [comment]
Ahhh lol ajaja súper. ¡Muchas gracias por la aclaración! :)
