### ISSUE TITLE
Duda sobre test_02_tapar_tunel

### ISSUE THREAD

**Issue by sofiiit** [IIC2233/Syllabus#62]
Tengo un error en este test_2 el cual verifica que se tape un túnel diagonal donde existe uno, pasa que en el resultado esperado sale que debería ser 3, y mi función retorna un 1, ya que según el enunciado si se borra una conexión este debe retornar 1 y no contar las conexiones. Será un error del test o cuándo debo contar las conexiones?

**Comment by jprabyb** [comment]
Hola, el test está bueno.En el enunciado se menciona claramente que si se tapa un túnel se debe retornar la cantidad de túneles que va desde la estación de inicio.En ningún momento se menciona que si se borra una conexión se debe retornar 1
![image0 (4)](https://github.com/IIC2233/Syllabus/assets/141678962/ed069671-0e0e-4207-9e8e-f8a6bbf78346)

**Comment by sofiiit** [comment]
Graciass, sii había leído mal, jeje;(
