### ISSUE TITLE
Puedo importar la funcion `imprimir_tablero` en otro archivo que no sea main.py?

### ISSUE THREAD

**Issue by dvillas28** [IIC2233/Syllabus#62]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](https://github.com/IIC2233/Syllabus/issues/56)).
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](https://github.com/IIC2233/Syllabus/issues/55)).
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Para usar esa funcion en otro archivo que se encargue del menu del programa
Saludos!

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by Hernan4444** [comment]
Hola @dvillas28 

Si puedes 👍. La idea es que los ayudantes ejecuten tu `main.py`, pero si ese `main.py` llama a otro archivo y ese archivo usa `imprimir_tablero.py`, es una opción totalmente válida 😄 

Saludos y mucho éxito con tu tarea,
