### ISSUE TITLE
Hacerse premium, pasar a ser investor

### ISSUE THREAD

**Issue by Bneya** [IIC2233/Syllabus#62]
En el enunciado aparece en una parte que  _un trader puede cambiar a investor pagando una cuota única de 300.000 DCC_. Esta opción tiene que aparecer en el menú principal del trader o en qué lugar tiene que aparecer?

**Comment by hanavarrete** [comment]
Como no está especificado queda a tu criterio. Lo mejor es que sea un lugar simple, el menú es buena opción. Saludos!
