### ISSUE TITLE
Guardar

### ISSUE THREAD

**Issue by mvaldes12** [IIC2233/syllabus#62]
Cuando se elije guardar, se debe volver al menú de inicio o al menú de juego?

**Comment by KnowYourselves** [comment]
Hola @mvaldes12!

Esta la opción de **guardar sin salir** por lo cual se deberia seguir en el menú de juego. En el caso de **guardar con salir** queda a tu criterio si para el programa o si se vuelve al menu de inicio.

Espero haberte ayudado!

**Comment by lisraelrat1** [comment]
Hola! En el enunciado dice que las opciones del menú de juego son: "Dentro de las acciones, se debe ofrecer como mínimo las opciones de: descubrir una baldosa, guardar la partida, y **salir de la partida, con o sin guardar**". Pero en la respuesta de este issue dice la opción de **guardar con o sin salir**. Cuál es la correcta? O son ambas

**Comment by jeschuwirth** [comment]
Hola!

Ambas están correctas, la idea es que seas capaz de guardar la partida sin salir del juego **(guardar la partida)**, salir del juego guardando (**salir de la partida con guardar**) y salir del juego no guardando (**salir de la partida sin guardar**). La opción de guardar con salir es la misma a salir guardando y la de guardar sin salir es la misma a guardar la partida.

Espero a que haya quedado claro 😄
