### ISSUE TITLE
Serialización wavs

### ISSUE THREAD

**Issue by Kitaps** [IIC2233/Syllabus#620]
Hola, 

lo que yo quiero hacer es escribir el archivo de a poco, para poder editarlo mientras que se escribe y así poder hacer el x2 como tambien el mandarlo por partes. 
Leer el archivo wav con "rb" y luego con read() no es problema, ya que lo paso a un bytearray. 
Tambien, si lo escribo no hay problema (es decir "wb" y luego hago .write(elarray)).

Pero si itero sobre el bitearray, y hago un write de cada byte me dice que no se puede porque lo pasa a int parece. Si hago bytes(bite) o un append a un nuevo bytearray tampoco funciona, ya que me escribe la cancion, pero la deja pesando como 700mb, siendo que la original pesa 6mb. 

Talvez lo que esté haciendo de por si no sea la manera correcta de enfrentar el problema.

**Comment by DiegoAndai** [comment]
Si trabajas con un único byte python lo trata como int, es verdad, pero no entiendo muy bien cual es tu pregunta. Por lo que entiendo, quieres trabajar byte a byte, ¿para que quieres hacer esto?

Te recomiendo leer [la documentación](https://docs.python.org/3/library/stdtypes.html#bytes) de la clase bytes para entender mejor como se manejan estos. Lo que me imagino puede estar pasando, esque al hacer bytes(byte) lo transforma a una representación más grande que un sólo byte, quizás la función que buscas es [int.to_bytes](https://docs.python.org/3/library/stdtypes.html#int.to_bytes), con la cual puedes especificar el largo de la representación resultante.

**Comment by benjamimo1** [comment]
Como mantengo el status de byte y no de int cuando trabajo con uno solo?
