### ISSUE TITLE
Sala chat volver al menú

### ISSUE THREAD

**Issue by allullk** [IIC2233/syllabus#620]
¿Debe de existir la forma de volver al menú de personaje una vez que una ya se está en una sala de chat?
De ser así, ¿Esta forma de volver debe de ser a través de un botón o un comando del estilo "/salir"?
Muchas gracias de antemano.

**Comment by DCCollao** [comment]
Hola!

Inicialmente la idea era pedirles dicho botón en la sala de chat, pero se nos fue ponerlo en el enunciado 😥 así que no será evaluado. 

Aún así, esa funcionalidad ayudaría mucho a la navegación en tu tarea, y si decides hacerla, un botón es más que suficiente!

**Comment by allullk** [comment]
Muchas gracias @DCCollao :smile:
