### ISSUE TITLE
Pregunta sobre versión de python

### ISSUE THREAD

**Issue by jirarrazaval** [IIC2233/syllabus#620]
Hola! En optimización tenemos que instalar Gurobi, y dice que para eso hay que instalar Python 3.8. Pero para programación avanzada descargué la versión 3.7. Da lo mismo si me la descargo o afecta en algo? Osino saben si gurobi funcionaría bien con la versión que ya tengo, 3.7, envez de la 3.8?
Sé que suena un poco tonta mi pregunta pero sería muy bueno saber la respuesta!

**Comment by entamburini** [comment]
Hola @jirarrazabal! 

Gurobi te recomienda siempre la última versión de python para trabajar, pero en lo personal no he tenido problemas trabajando en versiones anteriores :).

Acerca de instalar otra versión de python, no te lo recomiendo porque después tienes que estar cambiando de versión (hay librerías para eso y si lo quieres hacer, es completamente factible :wink:). 

Trataría primero instalando gurobi y viendo si funciona en python 3.7, que es la versión que ya tienes instalada, en caso de que funcione, éxito :tada:!, en caso de que no funcione, tendrías que trabajar con múltiples versiones de python, [acá te dejo un tutorial](https://realpython.com/intro-to-pyenv/). 

La última opción es simplemente actualizar la versión de python a la más actual (3.8), no puedo recomendarte esto porque sería poco consecuente con el curso :roll_eyes:, pero también la dejo como opción.

Saludos y suerte con gurobi! :raised_hands:
