### ISSUE TITLE
error de QThread: (Destroyed while thread is still running)

### ISSUE THREAD

**Issue by APeraltaS16** [IIC2233/syllabus#620]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

al crear un thread para el jefe gorgory que imita el movimiento del personaje, de manera aleatoria despues de un rato me lanza este error "QThread: Destroyed while thread is still running" y no se como arreglarlo. este error hace crashear el juego por lo que no puede seguir a siguientes rondas.

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by JadrinaDA** [comment]
Hola! Esto significa que la thread esta siendo destruida antes de que termine. Piensa en donde estas creando la QThread, es posible que el objeto que la almacene este siendo eliminado antes de que termine de correr? Si necesitas que esto pases podrías hacer que  la QThread sea un daemon para que así no se tuviera que esperar hasta que esta termine. Avísame si te sirvió. Saludos!

**Comment by APeraltaS16** [comment]
Hola! estuve intentando con daemon, le agrege daemon a todos los threads por si el error era porque habian muchos al mismo tiempo, y me sigue tirando el error de manera aleatoria, a veces dura 100 segundos, a veces 5.

**Comment by JadrinaDA** [comment]
Creo que el problema es que siempre estas creando una nueva thread entonces estas reemplazando la pasada y algunas veces el thread no ha terminado. Tal vez podrías tener un booleano que al terminar la ronda cambie para que la thread termine de inmediato. Así te aseguras que al reemplazarla esta ya va a ver terminado.

**Comment by APeraltaS16** [comment]
Voy a tratar con eso a ver si se arregla!! Gracias

**Comment by APeraltaS16** [comment]
Lo intente pero con esto hace que el jefe vaya como a saltos de posicion, entonces no se si es mejor que vaya a saltos o que pueda crashear el juego? ¿Que me recomiendas?

**Comment by JadrinaDA** [comment]
Hay harto puntaje por fluidez de movimiento y no tanto por seguir las otras rondas. Por lo tanto te recomiendo que reviertas a lo que tenías antes. Buena suerte!

**Comment by APeraltaS16** [comment]
OK, Muchas Gracias!!
