### ISSUE TITLE
Cambiar nombre a parameters.py

### ISSUE THREAD

**Issue by pahaeussler** [IIC2233/Syllabus#620]
Hola, No es muy relevante la pregunta, pero me gustaría tener consistencia con el idioma de mi código.
Me gustaría saber si puedo cambiarle el nombre a los parámetros que nos entregaron, ejemplo TIEMPO ->TIME.
Gracias.

**Comment by hanavarrete** [comment]
Si, no hay problema. De todos modos indícalo en el readme. Saludos

**Comment by pahaeussler** [comment]
gracias :)

**Comment by jmwielandt** [comment]
Me sumo preguntando si puedo cambiar "parameters.py" por "constantes.py" para mayor comodidad

**Comment by hanavarrete** [comment]
Si, no hay problema mientras también lo indiques en tu readme 😁
