### ISSUE TITLE
como eliminar cosas de mi repo en github

### ISSUE THREAD

**Issue by snarriagada** [IIC2233/syllabus#620]
hola, tengo subido en mi repositorio algunos archivos .py  sueltos. Antes de haber formado las carpetas pedidas. Como se eliminan archivos subidos al github?

**Comment by Arcoirisky** [comment]
Debes de eliminarlo de tu repositorio local y al hacer add, agregarlos para que se ejecuten tus cambios en tu repositorio O:

Si están en una carpeta, es más fácil agregar la carpeta entera al add :0 

Asegúrate de hacer pull antes de intentar algún cambio :D

**Comment by ariel-m-s** [comment]
También puedes usar el comando ```git rm``` (_remove_). Funciona igual que un ```git add```, pero en vez de agregar archivos los elimina.

Salu14783
