### ISSUE TITLE
Importar archivos que tienen codependencia 

### ISSUE THREAD

**Issue by Natydlb** [IIC2233/syllabus#620]
hola! al intentar importar las clases y funciones de los demás archivos me sale este mensaje "cannot import name 'Deportista' from 'Tarea1' , entiendo que es porque por ejemplo la función menu_principal que esta en un archivo x llama a la clase DCCroton, y esta en alguna de sus métodos también lo hace, pero no sabría como arreglar este error de importación sin tener que cambiar mi código a la totalidad

**Comment by ignacio-urrutia** [comment]
Hola @Natydlb lo que entiendo que te sucede es que intentas importar elementos de un archivo B a un archivo A y al mismo tiempo otros elementos de un archivo A a un archivo B. Esto no se puede hacer debido a que se crea, tal como lo dices, una codependencia entre los archivos. Mi sugerencia es ingresar como parámetros de un lado a otro la información que quieres importar. Por ejemplo, si del menu principal, llamas a DCCroton para instanciarla, en lugar de llamar lo que sea que necesites del menú principal llamando a esta función, traspasa los datos como parámetros de DCCroton. Sino, otra opción que se me ocurre es crear un tercer archivo con algunos datos que no necesariamente tengas que tener en uno de los dos y así terminar con la dependencia circular. 

Espero haberte ayudado y mucho éxito con tu tarea! :D

**Comment by Natydlb** [comment]
hola! no entendi la primera parte:( casi todas las clases están conectadas
