### ISSUE TITLE
Pregunta tonta - Archivo constantes.py

### ISSUE THREAD

**Issue by HenryBlairG** [IIC2233/Syllabus#620]
Se pueden agregar constantes a este archivo(constantes.py), cierto? Me surgió la duda por tecnicismo, no de rebuscado 😆 
Desde ya gracias 😄

**Comment by Hernan4444** [comment]
@HenryBlairG si se pueden 👍  ideal si toda constante que usen esté en el archivo constante.py 

Saludos ✌️

**Comment by HenryBlairG** [comment]
Muchisimas gracias! 😃

**Comment by inmadariaga** [comment]
Otra pregunta "tonta" tengo que leer las constantes de algun lado? o las puedo "chantar" en donde las necesite al momento de crear el juego?

**Comment by Hernan4444** [comment]
@inmadariaga tienes que **importar** las constantes desde tu juego de tal modo que si el ayudante edita algo de `constantes.py`, tu juego se vea afectado. Si "chantar" permite hacer lo anterior,entonces puedes hacerlo.

Saludos ✌️
