### ISSUE TITLE
Archivos corrección tarea 3

### ISSUE THREAD

**Issue by tomasrivera** [IIC2233/Syllabus#621]
Hola, pueden subir los archivos que usaron para corregir la tarea?

**Comment by Hernan4444** [comment]
@tomasrivera se acaban de subir en la carpeta de T03/TEST
Cabe destacar que esos test no evaluan el 100% de la tarea, cada ayudante tuvo que agregar algunos a su criterio para evaluar lo que faltaba como el Genoma Error. Tambien, se aceptó un margen de error en los decimales.

Saludos ✌️
