### ISSUE TITLE
Método __str__ en Diagrama de Clases

### ISSUE THREAD

**Issue by camilapavesi** [IIC2233/syllabus#621]
Hola! :)
En varias de mis clases implementé el método ```__str__```, debo incluirlo en mi diagrama de clases?
Gracias!

**Comment by ignacio-urrutia** [comment]
Hola @camilapavesi como hiciste override de un método si debes implementarlo, nunca está de sobra ser un poco más específico en estos casos. 
Mucho éxito y que disfrutes la semana que viene! :D

**Comment by barbarafcp** [comment]
hola! y lo debo escribir la función tal cual en el diagrama? onda:
__str__(): str?

**Comment by ignacio-urrutia** [comment]
@barbarafcp sip, exactamente así ;)
