### ISSUE TITLE
Aclaración logs del servidor

### ISSUE THREAD

**Issue by FelipeA7** [IIC2233/syllabus#621]
Enunciado: "El servidor reciba un paquete de información de algún cliente. Se debe indicar que cliente envió el paquete, el tamaño del mensaje y su contenido decodificado."

Esto significa que en los logs se deben imprimir TODOS los paquetes que se envían desde un cliente, o solo aquellos que corresponden a un mensaje escrito en el chat? Porque en mi caso por lo menos yo envío varios mensajes del cliente al servidor que sirven para indicar algo que está pasando (por ejemplo cuando alguien sale del chat envío el texto "out" por el socket) y que no tendría mucho sentido mostrar esos mensajes.

Para el caso de envío de mensajes a los clientes, supongo que los logs deben funcionar igual que para recibir?

**Comment by DCCollao** [comment]
Hola!

- Con paquetes de información nos referimos a mensajes que envíe por chat, o a comandos de consulta que ingrese en el chat.
- De todas formas, cuando alguien sale del chat debería mostrarse,  como se menciona en el segundo caso de la sección 3.1.5
- Los logs de envío de mensaje a clientes efectivamente funcionan igual que para recibir, pues se debe indicar a qué cliente se le envió el mensaje, el tamaño del mensaje y además su contenido decodificado.

Hazme saber si te queda alguna duda!

**Comment by bahidalgo** [comment]
Me sumo a esta consulta. En caso de que el envío del mensaje sea una imagen ¿ Cómo puedo mostrar el contenido decodificado? Mi servidor envía imágenes al cliente y viceversa. No entiendo cómo mostrar el envío de este "paquete de información" por logs.

**Comment by JuaniAndres** [comment]
Me colo a la consulta
No me quedo claro los paquetes que no son del chat o de comandos no se muestran en el log?
Si yo cuando el cliente envía mensajes en el chat no solo mando el string también mando más información todo en un dict el contenido decodificado seria el diccionario y no solo el string?

**Comment by DCCollao** [comment]
@bahidalgo En el caso de imágenes, podrías mostrar la cantidad total de los bytes enviados y una cantidad fija de esos bytes; o también podrías simplemente indicar que el paquete de datos recibido corresponde a una imagen y su respectivo tamaño en bytes.

@JuaniAndres Los paquetes que no son del chat sí se muestran en el log. La gracia del log es que se muestre todo lo que los clientes le van mandando la servidor, de una forma ordenada. Esto los ayuda a ustedes a debuggear, y a nosotros a corregir 💃 . Si mandas información en un diccionario, debes imprimir el diccionario completo decodificado, pues el diccionario en sí corresponde al paquete de datos enviado.
