### ISSUE TITLE
Problema con QScrollArea/QLayout (pyqt/designer)

### ISSUE THREAD

**Issue by KnowYourselves** [IIC2233/Syllabus#621]
Mi problema es el siguiente, Quiero definir un QScrollArea con un QLayout como su widget y dentro de este layout agregar una cantidad arbritaria de botones. My problema es que no he podido hacerlo de ninguna forma o manera, Intente definiendo el scroll area y el layout desde designer para despues definir los botones con código pero nada parece funcionar. De antemano, Gracias!

**Comment by KnowYourselves** [comment]
Gracias por la respuesta!, mi problema es que ya intente esa solución y no sirvió.

Defino el ScrollArea desde designer, luego dentro del programa creo un QVBoxLayout y le agrego los botones dado una lista de strings, y aún asi no aparece nada.

**Comment by dfvasquez** [comment]
@KnowYourselves lo arreglaste? me pasaba lo mismo. Le puse un tamaño mínimo y se arregló! :)
