### ISSUE TITLE
sprites

### ISSUE THREAD

**Issue by clementeross** [IIC2233/Syllabus#621]
Hola,
El enunciado dice:
"Junto al enunciado se les entregara un conjunto básico de "sprites" para el entorno de su interfaz"
La cosa es que no encuentro ese conjunto de sprites. ¿Dónde está?

De antemano muchas gracias!

**Comment by hanavarrete** [comment]
@clementeross Hola, acabamos de subir el sprite de bomberman. Gracias por notarlo! 😃

**Comment by clementeross** [comment]
Tengo otra duda con la imagen de "bomberman" que nos pasaron:
1. ¿Nosotros debemos cortar esa imagen y generar imágenes más chicas, y guardarlas en una carpeta de sprites tal como la Ayudantía N°10?
2. ¿Qué pasa con las imágenes del movimiento hacia la izquierda del jugador?

**Comment by hanavarrete** [comment]
1: Si, debes cortar lo que necesites.
2: Puedes voltear la imagen del personaje para que vaya hacia el otro lado y guardar esa copia.

**Comment by clementeross** [comment]
@hanavarrete y cómo puedo invertir esa imagen?, porque al final es reflejarla como si fuese un espejo

**Comment by hanavarrete** [comment]
Googleando encontré [esto](https://www169.lunapic.com/editor/?action=mirror). Saludos 😄

**Comment by clementeross** [comment]
Gracias!

**Comment by FJavierOss** [comment]
Para cortar las imagenes de sprite hay aplicaciones que lo hacen, busquen en google algo como sprite sheet unpacker, les va a ahorrar tiempo para estar más tiempo programando que peleando con las sprites.
PD: No soy ayudante
