### ISSUE TITLE
Duda sobre Qlabel

### ISSUE THREAD

**Issue by Jesusdelgad** [IIC2233/syllabus#621]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
 Estoy en el menu de juego y no se como lograr que los personajes "se coma" el objeto que tiene en el mapa, lo que hice fue obtener la posicion del objeto y del personaje , y dentro de la funcion que hace la animacion que desaparece el objeto al comerlo, puse un if donde si se igualan las posiciones, desaparece el objeto pero no pasa nada porque mi personaje avanza a 15 pixele,s entonces nunca coincide con la poscion del objeto (eso creo yo que ocurre), existe una manera para saber si un qlabel esta encima de otro? o algo que me indique si un qlabel toca otro? , muchas gracias de antemano.

**Comment by mmunoz12** [comment]
Hola @Jesusdelgad! Una forma rápida para verificar intersecciones entre labels es utilizando la clase `QRect` de `QtCore`. El uso de esta clase se encuentra bien detallado en la issue #506 , por lo que podrías echarle un vistazo si es que no la habías visto todavía. La forma que mencionas yo creo que pasaba eso mismo, que es muy poco probable que las posiciones de ambos elementos (personaje y objeto) coincidan y lo que finalmente se busca es que apenas el personaje toque el label del objeto (con excepción de los obstáculos que se quedan fijos), este debe desaparecer. Por ello, se deben tomar en cuenta no sólo la posición de los labels, sino que también las dimensiones de cada uno, y es posible tomar en cuenta esto gracias a `QRect` y sus métodos. Espero que la issue te sea de ayuda!

Avísame si te quedan dudas! quedo atenta :)

**Comment by Jesusdelgad** [comment]
Oh te pasaste habia visto esa issues pero al princio de la tarea y despues se me olvido, muchas gracias! me salvaste

**Comment by Jesusdelgad** [comment]
Disculpa que te moleste de nuevo , Tengo otra consulta con los Qlabel , en la tarea no se indica cuantas cantidades de objetos deben aparecer en el mapa ,(ejemplo 3 rosquillas) es un n indefinido, y por lo que entiendo no es que haya que crear 3 qlabel de rosquilla , si no a través de 1 lograr que este se "copie" a diferentes posiciones , existe algo así , un metodo donde uno pueda copiar un qlabel?

**Comment by mmunoz12** [comment]
Como en el enunciado no se especifica cómo debes realizar la manipulación de los labels, este queda a tu criterio, siempre y cuando se respete lo pedido en el enunciado y en la pauta. Me parece que no existe (o al menos no encontré) un método que copie exactamente un label (con todos sus atributos como pixmap y dimensiones). Simplemente lo que se puede hacer es crear un nuevo label y darle los mismos atributos que el anterior.

Por lo tanto, sí lo prefieres, puedes crear 3 Qlabel de rosquillas, o el número indefinido de estas según corresponda con la aparición de objetos y su probabilidad. Además si lo ves desde el lado que dices, si buscas lograr que a través de un Qlabel este se copie en diferentes posiciones, puede volverse un poco complicado ya que cada uno tendrá atributos diferentes y tiempos diferentes de aparición y desaparición, por lo que en realidad no son exactamente una copia del otro.

Espero que esto te haya dado una idea más clara, si quedas con dudas pregunta nomás! ☺️☺️
