### ISSUE TITLE
Archivos .ui

### ISSUE THREAD

**Issue by bvallejo1** [IIC2233/syllabus#621]
Hola, para algunas de las interfaces de esta tarea utilicé QtDesigner, mi duda es si debo subir os archivos .ui generados a mi repositorio o en el .gitignore?

**Comment by gatochico** [comment]
Hola! Si, debes subir los archivos .ui a tu repo junto con tu tarea, ya que son **claves** para la visualización de tu interfaz. De otra forma, tu tarea no correrá 😟 .
