### ISSUE TITLE
Máximo de objetos en pantalla

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#622]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Tengo un problema, es que cierta ventana de juego no acepta más de 19 objetos a la vez, aunque este valor también depende de la suerte de spawneo. Bajo los parámetros que establecí esto no debería suceder, pero supongo que si cambian los parámetros al corregir la tarea, podría suceder que el programa se caiga al estar infinitamente intentando combinaciones aleatoreas que no colisionen. ¿Esto conlleva descuento? ¿Hay un mínimo/máximo esperable?

**Comment by JadrinaDA** [comment]
Hola! No hay un máximo de objetos, tu ventana debería poder aceptar mucho más que 19. Tal vez podrías cambiar la forma en que se generan para que acepte más objetos. O verificar que las threads están siendo eliminadas cuando los objetos desaparecen. Si no logras arreglarlo está bien pero creo que ese número es muy bajo para que sea una limitación real.

**Comment by fernandosmither** [comment]
> Hola! No hay un máximo de objetos, tu ventana debería poder aceptar mucho más que 19. Tal vez podrías cambiar la forma en que se generan para que acepte más objetos. O verificar que las threads están siendo eliminadas cuando los objetos desaparecen. Si no logras arreglarlo te recomiendo que avances con el resto no mas pero creo que ese número es muy bajo para que sea una limitación real.

Pero cómo puedo lograr esto sin cambiar el tamaño de la ventana misma o de los objetos? porque geométricamente estaba revisando y en mi caso, el tamaño de mi tablero de juego es de 760x240, entonces tomando como ejemplo el item del veneno que le puse un ponderador de tamaño de 0,3, queda de 99x87. Por estas medidas creo que físicamente solo puedo tener en el mejor de los casos 14 de estos venenos sin que se choquen. (en el caso de las donas es mucho más, pero este es solo el peor de los casos)

Lo que sí hice fue configurar mis parámetros de tal manera que el juego nunca se pueda quedar sin espacio en cualquier momento determinado, pero si estos parámetros se cambiasen, ya no funcionaría, por eso mi duda era más sobre si se evaluará el tablero con esos parámetros de spawneo cambiados.

**Comment by JadrinaDA** [comment]
Ahhh, no vamos a cambiar ningún parámetro que afecte la visualización. Así que ese ponderador de tamaño no se va a cambiar. Por lo tanto debería estar bien.

**Comment by fernandosmither** [comment]
> Ahhh, no vamos a cambiar ningún parámetro que afecte la visualización. Así que ese ponderador de tamaño no se va a cambiar. Por lo tanto debería estar bien.

Buena!! me tenía preocupado. Hay algún parámetro que sí se vaya a cambiar?
saludos

**Comment by JadrinaDA** [comment]
Los que aparecen azul en el enunciado podrían ser modificados, velocidades, tiempos, ese tipo de cosas.

**Comment by fernandosmither** [comment]
Ok! gracias 😄
