### ISSUE TITLE
problema de indentacion

### ISSUE THREAD

**Issue by javiermingo** [IIC2233/syllabus#622]
hola! tengo un problema con la indentacion de mi código en general. Trabajo en sublime text y ahí me aparecen indentaciones de 4 espacios en todas partes pero al visualizar mis archivos en mi repo de GitHub me aparecen mezcladas indentaciones de 4 espacios con de 8. Que debo hacer? es necesario arreglar esto?

**Comment by ignacio-urrutia** [comment]
Hola @javiermingo, lo más probable es que sea un problema con el visualizador de git. Revisé tu repo a la rápida y la mayoría está con los 4 espacios, sin embargo algunos saltos están con tabulación, cuidado con eso porque te puede descontar por el pep-8. Sin embargo, guíate por lo que ves en tu editor.

Saludos y mucho éxito con la tarea :D

**Comment by javiermingo** [comment]
perfecto! gracias. Y puedo hacer algo para arreglarlo de forma rápida?
