### ISSUE TITLE
problema os.path.join

### ISSUE THREAD

**Issue by niguzman** [IIC2233/syllabus#622]
Hola,
se supone que si uno usa os.path.join para los paths, estos servirán para cualquier computador, pero en mi caso no me reconoce los archivos, ya que me arroja la ruta con \ y mi computador (o el programa en verdad) sólo me reconoce los paths con /

Que puedo hacer?

**Comment by niguzman** [comment]
Creo que es eso, ya que en mi server en la parte de codificar_foto, cuando trato de leer en bytes la foto me da solamente b''

**Comment by niguzman** [comment]
y lo raro es que no me la carga y me da error, pero si ese mismo usuario trata de entrar de nuevo, ahí si aparece la foto :C

**Comment by lily416** [comment]
Hola 😄 

Te recomiendo que mires la issue #561, ya que se habla del mismo error que te sucede y de paso utilizan la misma foto de flaticon 👀 🌴

Ánimo y éxito con la tarea 👋 💪

**Comment by lily416** [comment]
Con respecto a los de `os.path.join` me llama la atención que ese sea el problema, ya que por lo que dices en tu segundo comentario si te deja acceder a la información del archivo 🤔 
Si el problema persiste ingresa los _paths_ de forma manual e indica que tuviste dicho problema o antes de entregar, vuelve a _paths_ por `os.path.join`.

Con respecto al segundo comentario, más que ser un problema de `os.path.join` parece ser que está leyendo un archivo vacío. Fijate en que cuando leas el archivo tenga la información que le corresponde (prueba abriendolo en modo `r` e imprimir su contenido).

**Comment by niguzman** [comment]
Hola,
si había visto esa issue (y ahí probé con esa foto) pero no mi mismo problema
Con respecto a si tengo un archivo vacío, si tengo la foto que estoy tratando de leer en bytes en esa ubicación por lo que realmente no entiendo de donde viene el error
