### ISSUE TITLE
setCentralWidget del MainWindow

### ISSUE THREAD

**Issue by josemlira** [IIC2233/Syllabus#622]
Hola! tengo un MainWindow en el cual voy controlando los widgets que se van mostrando. Cuando guardo en el init del MainWindow algún Widget y le hago self.setCentralWidget, cuando después quiero volver a poner el mismo widget guardado con el mismo comando (setCentralWidget) me dice que el atributo ha sido eliminado, en el programa nunca lo borro. Mi pregunta es si cuando en el MainWindow dejamos de mostrar un widget (usando el comando setCentralWidget) este se elimina automáticamente??

**Comment by DiegoAndai** [comment]
Hola!, ¿tienes guardado el widget como atributo de la clase MainWindow?¿Has probado creando un widget diferente cada vez, o es necesario para tu programa que el widget sea el mismo? Otra solución puede ser [esta](https://stackoverflow.com/a/13551018).

Saludos.

**Comment by josemlira** [comment]
Sí, tengo guardado el widget como atributo, podría crear el widget nuevamente cada vez, pero encuentro que no es lo óptimo. Voy a probar con el StackedWidget, muchas gracias!!!
