### ISSUE TITLE
Cálculo de afinidad

### ISSUE THREAD

**Issue by FelipeA7** [IIC2233/syllabus#622]
Tengo una duda con el cálculo de la afinidad, el total de amigos de A o B hay que consdiderar a la otra persona si es que son amigos?
Para verlo de manera más fácil, en el grafo del enunciado, cuanto es la afinidad entre C y E? 1/2 o 1/4?
![image](https://user-images.githubusercontent.com/48482398/70367871-3c51d600-1883-11ea-93c2-90896d13767c.png)

**Comment by DCCollao** [comment]
1.Entre C y E tienen solamente un amigo en común: F Entre C y E tienen solamente un amigo en común: F

2.El total de amigos de C o E sería {B, F, E} unión {D, F, C} = {B, F, E, D, C}

3.Entonces en común es 1(F) y el total de C o E son 5{B, F, E, D, C}; por lo que la afinidad sería 1/5.

**Comment by FelipeA7** [comment]
Ahh ok no me había quedado claro lo del punto 2, gracias!
