### ISSUE TITLE
Sprites

### ISSUE THREAD

**Issue by MariaJosefinaAlliende** [IIC2233/Syllabus#622]
En el item 4.9 de Representación gráfica sale que debemos tener al menos 3 estados de movimientos para cada acción y dirección ( pero en los sprites que nos dieron no hay para la acción de ataque). Estoy buscando sprites en internet pero todavía no encuentro ninguno gratuito que tenga acciones de ataque... ¿Puedo ocupar un sprite que me sirva para distintas direcciones pero que no tenga el ataque en sus dibujos? ¿Cuenta para el bonus de estiloso?

**Comment by rgevert** [comment]
Hola, encontré esta pagina, ve si te sirve.

[https://www.spriters-resource.com/](url)

**Comment by MariaJosefinaAlliende** [comment]
Muchas gracias @rgevert !!

**Comment by mundurragac** [comment]
tienen el contenido en alguna otra parte? que me tira a error cuando intento ingresar a la pagina

**Comment by mjgutierrez1** [comment]
@rgevert Cómo entraste a la página? a mi también me sale Page not gound.
