### ISSUE TITLE
Como puedo ignorar solo un archivo en vez de un tipo de archivos

### ISSUE THREAD

**Issue by MGilB** [IIC2233/syllabus#623]
Hola, no he podido encontrar el como escribir el gitignore para que ignore solo el pixel_collector.py y no todos los archivos .py.

**Comment by StroveLight** [comment]
relacionado a la pregunta, ¿como borro el pixel collector si ya lo envié?

**Comment by jeschuwirth** [comment]
@MGilB Basta con colocar `pixel_collector.py` en una línea dentro del gitignore, ten en cuenta que si ya subiste el archivo **creo** que .gitignore no los ignora, por lo que debes sacarlo del repositorio.

@StroveLight, hace poco preguntaron en la issue #620 eso mismo :)

Exito a ambos!
