### ISSUE TITLE
Puntajes grafos pauta

### ISSUE THREAD

**Issue by FelipeA7** [IIC2233/syllabus#623]
Hola,
Si es que realizo funciones que cumplan lo que se pide con respecto a los grafos (alcance de amistad, recomendaciones, afinidad, etc.) pero no logro implementarlo en el programa del servidor, solo se me descuentan los 4 puntos de la pauta que corresponden a "integración"? O habría un descuento adicional en esto por no tener todas las funcionalidades?

**Comment by DCCollao** [comment]
![image](https://user-images.githubusercontent.com/37167447/70374022-279a3000-18cd-11ea-8098-87878430c25b.png)
Si haces todo lo relacionado al grafo excepto integrarlo a tu programa, podríamos evaluar todos sus ítems excepto el de integración, así que perderías ese puntaje. El resto de ítems se evalúa normalmente
