### ISSUE TITLE
Aparicion objetos superponiendo Jugador

### ISSUE THREAD

**Issue by Ignacioislae** [IIC2233/syllabus#623]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

**Comment by mmunoz12** [comment]
Hola @Ignacioislae! Según pauta se pide que los elementos en la ventana de juego no se superpongan entre sí, por lo que si al iniciar el juego algún objeto aparece sobre el personaje, no se tendría el puntaje total en esta parte. Ahora, si tu pregunta se refiere en cualquier momento de la partida, que un objeto aparezca aleatoriamente justo donde tu personaje o el jefe Gorgory está caminando (lo cual me parece poco probable pero podría pasar), estaría bien tomar esto como una colisión inmediata. Saludos!
