### ISSUE TITLE
funciones de PyQt5

### ISSUE THREAD

**Issue by clementeross** [IIC2233/Syllabus#623]
Hola,
Alguna página web que recomienden para encontrar información acerca de las funciones que se pueden implementar con PyQt5? 

Gracias!

**Comment by MrEarle** [comment]
Hola!
Yo, en general, me baso en esta página:
[PyQt4 Documentation](http://pyqt.sourceforge.net/Docs/PyQt4/classes.html)

Si bien es la página de PyQt4 en vez de PyQt5, muchas cosas se parecen.

También está está documentación para PyQt5:
[PyQt5 Documentation](http://pyqt.sourceforge.net/Docs/PyQt5/)

También existe una de Qt en general, pero está en otro lenguaje de programación. Es muy completa, y sirve como referencia:
[Qt Documentation](http://doc.qt.io)

Espero que esto te ayude!

**Comment by hanavarrete** [comment]
Además te recomiendo ver el material extra del contenido. Este fue hecho por tus ayudantes ~~favoritos @iqacevedo  y @hanavarrete~~ con ejemplos sumamente enfocados a la tarea y cosas que suelen ser problematicas en los semestres pasados.

**Comment by Arcoirisky** [comment]
Si nada de lo anterior funciona o te basta, apaña poner Pqty5 class reference python en Google y te aparecen muuuchas referencias y funciones con sus descripciones uwu (estaban en inglés pero era muy básico :D)
