### ISSUE TITLE
error al ejecutar código de thread

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#623]
Hola, quise ir probando el código de la materia threading me sale un error que no sé por qué pasa si se supone que a ustedes les funciona.
Cómo puedo solucionarlo¿?
![threading](https://user-images.githubusercontent.com/59337116/80894171-cd986d80-8ca6-11ea-9558-f70ed657e7f6.PNG)

**Comment by aaossa** [comment]
Hola @Camila-sty , para utilizar la clase `Thread` deberías utilizar el módulo `threading`, que es justo lo que estás haciendo. Se me ocurre que el error puede ser que el archivo que estás ejecutando tiene por nombre `threading.py`, por lo que choca con el módulo de Python, o tal vez tengas un `threading.py` en esa misma carpeta. Si es así, modifica el nombre para que no coincida con el de alguna librería de Python, ¿será eso?

**Comment by Camila-sty** [comment]
sí, eso es, gracias!
