### ISSUE TITLE
Puntaje diagrama

### ISSUE THREAD

**Issue by lorenzosilva** [IIC2233/syllabus#623]
Buenas!
Quería saber si  es que tengo las clases modeladas pero mi código nunca las llama ¿tendré los puntos del diagrama?

**Comment by ignacio-urrutia** [comment]
Hola @lorenzosilva si hablas del diagrama del avance, los puntos son independientes de la entrega de la tarea, la idea era que tuvieras un feedback de como querías implementarlo pero puedes hacer cambios después sin ningún problema, si tienes los puntos en el avance, los tendrás independiente de tu entrega. 
Espero haberte ayudado y mucho éxito con la tarea! :D

**Comment by ignacio-urrutia** [comment]
Hola @lorenzosilv, si el diagrama está bien hecho, tiene sentido y tiene sentido con como modelaste el programa, tendrás los puntos. Sin embargo, también se evalúan las relaciones entre clases en el diagrama, por lo tanto tambén es importante este punto para obtener la totalidad del puntaje.

Espero haberte ayudado y felices fiestas! :D
