### ISSUE TITLE
Servidor ve las jugadas válidas

### ISSUE THREAD

**Issue by StroveLight** [IIC2233/syllabus#624]
Con respecto a que vea que las jugadas sean válidas, ¿No puedo usar el frontend para ver si la jugada se hace correctamente, mientras que el backend asigna la jugada a quien debería ser? de esa forma me ahorro mucho envío de datos entre ambos lugares. Esto lo digo ya que para ver si la jugada es válida sólo tengo que ver donde pulsó el botón en el frontend. Además que el mapa todos los jugadores lo deberían tener actualizado.

![image](https://user-images.githubusercontent.com/48263952/59969575-82f28480-951e-11e9-9d4a-2595e5f7fb68.png)

**Comment by jeschuwirth** [comment]
Hola,

En esta tarea se evalúa que tengas un cliente "dummy", esto significa que todos los archivos en el lado del cliente son sólo para mostrarle cosas al usuario (front-end) o enviar y recibir información básica al servidor (back-end), toda la lógica del juego debe estar en la carpeta servidor.

Entiendo que es más complicado pero es como funciona generalmente y es evaluado para esta tarea.

![image](https://user-images.githubusercontent.com/37160256/59969754-2fcf0080-9523-11e9-939c-94807068a79a.png)

Exito!

**Comment by StroveLight** [comment]
ok..., gracias
