### ISSUE TITLE
Objetos no aparecen en el frontend 

### ISSUE THREAD

**Issue by ftgodoy** [IIC2233/syllabus#624]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Problema con ver objetos en frontend

[Hola, estoy teniendo un problema para que aparezcan los objetos al frontend de la ventana de juego, manejo todo bien en el backend pero no logro que aparezcan luego en el frontend :( hice los import correspondientes y nada :(]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by ftgodoy** [comment]
Los obstaculos y el homero aparecen sin problemas, es cuando hago el timer para los objetos que no me los muestra en frontend, llevo días pegado con esto D:

**Comment by ftgodoy** [comment]
Subi mi codigo por si alguien me puede ayudar :(

**Comment by Tsbalart** [comment]
Hola @ftgodoy, probaste haciendo self.update en la ventana luego de enviar las señales?
