### ISSUE TITLE
Palabras bobba

### ISSUE THREAD

**Issue by mpbascunan** [IIC2233/syllabus#624]
Para este bonus ¿la palabra censurada también debe aparecer en la ventana del cliente que la escribió?, es decir, ¿la palabra debe estar censurada en el globo del cliente en su propia ventana de chat?

**Comment by Dnpoblete** [comment]
Hola @mpbascunan, la respuesta es si, ya que la idea es que nadie vea la palabras prohibidas! :see_no_evil:

Éxito con la tarea 😄
