### ISSUE TITLE
EOFError: Ran out of input

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2233/Syllabus#624]
Hola, investigué este error, por ejemplo aqui https://stackoverflow.com/questions/24726495/pickle-eoferror-ran-out-of-input-when-recv-from-a-socket sale mas o menos el mismo problema que tengo yo, porque uso piclke.loads y no pickle.load como sale en las otras paginas, pero sigo sin entender bien como arreglar esto o cual es el problema realmente.

Este error me pasa cuando el servidor le manda algo al cliente (una lista con cosas) y al hacer pickle.loads se cae.

**Comment by jorgeriesco** [comment]
Ya lo solucione. La verdad lo solucioné por algo muy especifico de mi programa y no puedo dar una explicación técnica de cual fue el problema porque la verdad no lo se muy bien. 

Lo único que puedo aportar es que si se manda algo vació aparece ese error, así que preocuparse de eso si aparece el error.

**Comment by rrhurtado** [comment]
Hola, dejaremos la issue abierta para que en caso de que a alguien más le ocurra tu error pueda encontrar la solución de manera fácil.

Saludos !

**Comment by jgramsch** [comment]
Hola ! 
a mi me pasó varias veces y al final caché que de alguna manera cuando compilaba el pickle (osea pickle.loads) no lo hacía aún con todos los datos. en mi caso en específico no todos habían llegado aún

Suerte!
