### ISSUE TITLE
Calcular nivel moral delegaciones

### ISSUE THREAD

**Issue by Gustav2000** [IIC2233/syllabus#624]
Hola, en el enunciado sección **4.4. Campeonato** dice que tengo que implementar el método *calcular el nivel de moral de las delegaciones*, mi pregunta es si ésta función se puede trabajar en otra parte del código? Ya que se me hace más fácil trabajarla en la clase Delegaciones.

**Comment by ignacio-urrutia** [comment]
Hola @Gustav2000 la tarea está pensada para que implementes esa clase ahí, lo que puedes hacer, es quizá implementar un método en la clase Delegaciones, que sea _calcular_moral_ y en Campeonato llamas a ese método para ambas delegaciones, pero debe estar el método que se pide en la clase que especifica el enunciado. 
Mucho éxito con la tarea y felices fiestas! :D

**Comment by Gustav2000** [comment]
Oka, gracias
