### ISSUE TITLE
Error JSON e Imágenes repetidas en otros labels

### ISSUE THREAD

**Issue by mariajesusbraun** [IIC2233/syllabus#625]
Hola! Tengo este error con JSON en el servidor y no he podido encontrar a qué se debe:

` raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by Dnpoblete** [comment]
Hola @mariajesusbraun, tienes tu código en el repositorio para poder revisarlo y ayudarte?

**Comment by mariajesusbraun** [comment]
Hola! pude solucionarlo, pero lo que me pasa ahora es que en la interfaz de la sala, en lugar de ponerse de fondo la imagen de la sala, se pone esa imagen en cada label creada.

Ya esta el código en mi repositorio!

**Comment by Dnpoblete** [comment]
Hola, al descargar tu tarea y tratar de ingresar el usuario, me sale el error que comentaste, puedes subir el código actualizado? por favor

**Comment by mariajesusbraun** [comment]
Ahí lo actualicé de nuevo!

**Comment by lily416** [comment]
Hola c:

Tu error se debe a que al hacer `self.setStyleSheet()` se ese mismo _style sheet_ a todos los widgets que contiene la ventana, por lo que afecta cada label de la ventana.
Te recomiendo utilizar `QImage` para cargar la imagen y después ponerla como fondo de la ventana.

Saludos y éxito en la tarea :wave::penguin:

PD: Ojo, que cuando pones la imagen del servidor, también afecta los otros labels y widget porque falta un `server` entre el `self` y el `setStyleSheet()`.

**Comment by mariajesusbraun** [comment]
Gracias!
