### ISSUE TITLE
Ruido blanco al aplicar filtro x2

### ISSUE THREAD

**Issue by frvalenzuela** [IIC2233/Syllabus#625]
Una vez aplicado que al arreglo de cada canal se reducice tomando un byte de cada dos, y volver a juntar los canales el resultado es un "estatica" o ruido blanco.

Estoy practicamente seguro de haber aplicado todas las instrucciones del enunciado, revisando todos los bytes del nuevo archivo, y viendo que cumple con las condiciones aplicadas a la data.

¿No bastaría solamente duplicar el samplerate?, pues al modificar la data como menciona el enunciado actualizado el archivo queda de forma inesperada, y además la cantidad de segundos se ve reducida a un cuarto (pues la data se ve reducida a la mitad y la frecuecia es duplicada).

**Comment by frvalenzuela** [comment]
Sumado a lo anterior, no deberia cambiarse el subchunk2size y el chunksize? Como la data es reducida a la mitad esos headers deberían también cambiarse, sin embargo el enunciado estipula que los headers se mantienen iguales.

**Comment by DiegoAndai** [comment]
Hola! perdón por la demora. ¿#629 y #610 aun no resuelven tu duda? Si, tienes que cambiar subchunk2size y el chunksize.

Saludos.

**Comment by frvalenzuela** [comment]
Si, gracias !
