### ISSUE TITLE
Duda Mostrar jugadores dentro de la sala

### ISSUE THREAD

**Issue by tomascortes** [IIC2233/syllabus#625]
Hola!
En el enunciado dice : 
"Al unirse a una sala, se deberá mostrar un chat con los participantes de esa sala", no entiendo si esto significa que debe haber una lista que diga cuales son los usuarios que están en la sala o solo se refiere a que en el chat participan los que están dentro de la sala

Gracias

**Comment by jeschuwirth** [comment]
Hola!

Cuando ingresas a una sala te debe mostrar todos los demás jugadores, eso es para que nosotros como ayudantes podamos saber que tu programa recibió a todos los clientes, también es importante porque es ahí donde muestras los puntajes de cada usuario, por ejemplo:

```
jeschuwirth: 10
tomascortes: 15
JupaOlivares: 2
Hernan4444: 99
```

Y así podemos checkear que actualizas correctamente ese puntaje para todos los usuarios
Suerte!

**Comment by tomascortes** [comment]
gracias!
