### ISSUE TITLE
Uso de Qt Designer

### ISSUE THREAD

**Issue by mjgutierrez1** [IIC2233/Syllabus#625]
¿Se recomienda usar QtDesigner en la tarea, o la idea es que seamos nosotros los que escribamos todo el código?

**Comment by hanavarrete** [comment]
No hay requisitos al respecto, usa lo que te simplifique más el trabajo. Como recomendación, hay veces que es más rápido hacer el código y otras usar qtdesigner, en mis tareas algunas veces usé ambas. Saludos!
