### ISSUE TITLE
duda recorrección t00

### ISSUE THREAD

**Issue by Mendez69** [IIC2233/syllabus#625]
Holaa, quería saber si ya subieron las recorrecciones de la t00.
También aprovecho de preguntar si los des-descuentos aplican al cambio de lineas.
Gracias!

**Comment by lily416** [comment]
Las recorrecciones están planeadas para publicarse mañana, ya que se cumple una semana desde el cierre del _form_ de recorrección (sin considerar la semana de ajuste).

Los des-descuentos sí se aplican sobre el cambio de líneas. 🙌🎉


Saludos y que tengas una buena semana. 😁
