### ISSUE TITLE
Citar a  AS2

### ISSUE THREAD

**Issue by Pakarati** [IIC2233/syllabus#625]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Quería saber si puedo sacar una línea de código y citar a la AS2, ya que estuve buscando mucho rato como obtener todos los labels que hay en una ventana y no encontraba nada. El único método que encontré fue en la AS2 (cuando se obtienen los labels de la grilla, necesito hacer algo similar). Si hay otro método me gustaría saberlo de todas maneras porfis :)

**Comment by tqmbanados** [comment]
Hola! Puedes citar tareas y actividades pasadas sin problema :) de hecho, es recomendable que miren los códigos dados de las actividades por que se puede aprender mucho de ahí. No te olvides de agregarlo a tu readme como corresponde 😸
