### ISSUE TITLE
Objetos solo desaparecen si es el último en aparecer

### ISSUE THREAD

**Issue by imuoz** [IIC2233/syllabus#626]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

estoy probando hide() y setVisible(False) para esconder un label , pero solo funciona para el último objeto que se genera y no entiendo bien por qué. Subí mi avance, el problema ocurre en ventana_juego lineas 107 a 118

**Comment by MatiasDuhalde** [comment]
Hola @imuoz !

Revisé tu código, y el problema no está exactamente en el uso de setVisible o hide, sino que es está en cómo manejas las listas de objetos dentro de tu programa.

En tu función `crear_objetos` de `logica_objetos`, cuando creas un objeto nuevo, le mandas al frontend cada vez la lista entera de objetos (los que existían de antes + los nuevos). Entonces, cuando el frontend recibe la lista en `crear_objetos`, vuelve a crear todas las instancias de objetos (duplicándolas cada vez). Además, dado que reinicias la lista en ese mismo paso (`self.objetos = []`), pierdes la referencia a las instancias anteriores pero siguen existiendo. Es por esto solo funciona cuando intentas eliminar el último objeto, debido a que es el único que aún no tiene ningún duplicado, y aún tienes la referencia original al label en tu lista `self.objetos`.

Para arreglar tu error, vas a tener que cambiar la lógica de como manejas estas listas, los pasos que te recomiendo tener en cuenta son:
- Pasar desde el backend al frontend sólo los objetos nuevos que se crearon, no la lista entera de objetos, que es como lo haces ahora
- No reiniciar la lista en el método `crear_objetos` de la ventana de juego, si no definirla inicialmente en el init (o el método que uses cuando se abre la ventana en cada ronda).

También, noté que tienes una implementación similar entre los obstáculos y los objetos, por lo que te recomiendo arreglar el manejo de ambas listas, para no tener problemas cuando implementes múltiples rondas.

Éxito! :sparkles:
