### ISSUE TITLE
Error Threading/Consistencia Servidor

### ISSUE THREAD

**Issue by nvenegasu** [IIC2233/syllabus#626]
Hola, mi programa corre sin problemas cuando lo usan hasta 2 usuarios, pero al momento de entrar un tercer cliente se genera un problema en la threads de los clientes que escuchan al servidor. 
Revise el servidor y los clientes se conectan correctamente. No sé si es un problema de thread locks o algo asi.
El código está subido a mi repositorio.
Muchas gracias.

**Comment by fdoflorenzano** [comment]
Hola @nvenegasu,

Ejecuté tu código desde mi computador y como dices funciona bien por lo que alcancé a ver, pero al conectar un tercer cliente en una sala se caían los programas por *loading* de JSON. Al agregar un `print` de lo que recibía, noté que llegaban cosas del estilo:

`{"tipo": "usuarios sala", "usuarios": [{"nombre": "fdoflorenzano", "personaje": "Robot"}, {"nombre": "bimartinez", "personaj`
`{"tipo": "usuarios sala", "usuarios": [{"nombre": "fdoflorenzano", "personaje": "Robot"}, {"nombre": "Nhorellana", "personaj`
`{"tipo": "usuarios sala", "usuarios": [{"nombre": "fdoflorenzano", "personaje": "Robot"}, {"nombre": "bimartinez", "personaj`

Si te fijas, pareciera que están cortados los JSON recibidos por parte de los clientes. Y se caen porque intentan interpretar un *string* inválido. Sospecho es más bien un problema de recepción o emisión de datos a partir del protocolo de mensajes.

Saludos.

**Comment by nvenegasu** [comment]
Gracias por la respuesta profe, justo era eso y logre solucionarlo.
Saludos.
