### ISSUE TITLE
Diagrama de clases: Función que retorna instancia de otra clase

### ISSUE THREAD

**Issue by isidorabecker** [IIC2233/syllabus#626]
Hola, como escribo en el diagrama si un método retorna una instancia de otra clase, y lo otro como debo escribir una clase abstracta para que se diferencie de las otras.
Gracias !!

**Comment by retamalcito** [comment]
¡Hola @isidorabecker!

1. Si por ejemplo tienes un método `elegir` que recibe un `int` y retorna un objeto de la clase `DCCriatura`, debe estar escrito como: `elegir(int): DCCriatura[]`.
2. No es necesario diferenciar clases abstractas de no-abstractas. :smile:

¡Éxito con lo que queda! ✨

**Comment by isidorabecker** [comment]
Muchas gracias !!!
