### ISSUE TITLE
IMPORTANTE: QTimers / QThreads

### ISSUE THREAD

**Issue by Hernan4444** [IIC2233/Syllabus#626]
Hola! Para guiarlos un poco en el manejo de distintos eventos de manera asíncrona les dejo esta issue creada hace unos semestres que aclara el uso y diferencias de los QThreads y QTimers (cortesía de @fgvenegas)

### QThreads:
Los Qthreads siguen el mismo comportamiento que los Threads que fueron enseñados en el ramo, por lo que no debería presentarles mayor complicación aplicarlos en su tarea. Pero qué pasa si queremos utilizarlos para una acción que sabemos que se va a repetir constantemente ? Podríamos implementar algo así en el Qthread
```python
def run(self):
    while True:
        # Lo que quiero que el QThread haga en cada iteración
        time.sleep(0.1) # Muy importante para que su interfaz no se quede pegada, el valor es ajustable
```
* ¿Con esto que tenemos ?: Un QThread que repite una acción una y otra vez.
* ¿Problemas?: Si.
* ¿Cuáles? ¿Cómo detenemos este Qthread?
En general detener (matar) un thread es una [mala practica](https://stackoverflow.com/questions/323972/is-there-any-way-to-kill-a-thread-in-python), la idea es que un Thread se inicie, cumpla su objetivo y muera al terminarlo, no que lo tengamos que detener por nuestra cuenta (mas detalles en el link, es interesante y útil)
Entonces siguiendo esta misma lógica estamos abusando del run del Qthread con un vacío legal.
* ¿Puedo detenerlo con break ? Si, hay casos donde alumnos usan Qthreads en toda su tarea y no tienen problemas, como experiencia propia, empezar a matar Qthreads a diestra y siniestra con este método no escalo bien.

### Qtimers
Otra forma de realizar lo que hacíamos con Qthreads es con Qtimers.
* ¿Cuál es la ventaja que tienen estos sobre Qthreads?:
Qtimers está pensado para que se repita una y otra vez lo que contiene su run sin necesidad de utilizar un while, recibe como parámetro al inicializarlo el tiempo cada cuanto se debe ejecutar y además posee un método stop para poder detenerlo "legalmente". Si, se ve más limpio en general que usar Qthreads, pero no asegura que su programa vaya a ser perfecto ni vaya a sufrir problemas de lag o caídas de interfaz, eso ya va en la programación de cada uno.

## Recomendación final
Son libres de usar ambos en sus tareas, los 2 son útiles y pueden tener una tarea 100% funcional ya sea con uno, el otro o ambos. Por ejemplo para objetos que existan en muchas cantidades y sea difícil controlar cuando interrumpirlos puede ser más útil utilizar un Qtimer con ellos, pero para objetos que permanecen constantes en el escenario o que son más fáciles de controlar un Qthread es una buena opción.
Experimenten ! Vean con cual les anda mejor, con cual es mas eficiente su tarea y averigüen mas por su cuenta, siempre es útil leer un poco antes de lanzarse a usarlo algo, y no olviden siempre comentar en el README este tipo de decisiones y porque escogieron lo que escogieron.

**Comment by sjkinast** [comment]
Qtimers y Qthreads tienen  las mismas diferencias que  thread y timers en el material?

**Comment by Hernan4444** [comment]
@sjkinast se te cae sin indicar ningún error? ¿Probaste con el código de #625 para habilitar que se vean los errores?

**Comment by sjkinast** [comment]
Si tengo puesto ese código y me reconoce los errores en general , en este caso no me tira niun error solo se cierra el programa.
@Hernan4444  podrías hacer un ejemplo básico de una clase de qtimer que estuve investigando y aun no me queda claró como implementarlo.

**Comment by ljrodriguez1** [comment]
A mi también se me cae al hacer start() y no se porque, no me lanza ningún error solo esto:
Process finished with exit code -1073740791 (0xC0000409)

**Comment by ljrodriguez1** [comment]
De hecho mi objeto que heredaba de la clase QThreads lo cambie para que herede de Threads y ahora funciona, no entiendo cual es la diferencia entre estos y si puedo ocupar Threads en vez se QThreads

**Comment by ljrodriguez1** [comment]
@Hernan4444 Podrias ayudarme a crear correctamente un QThread, lo quiero utilizar para crear las bombas, pero incluso el QThread mas sencillo causa que se caiga mi interfaz.
@sjkinast Lograste solucionar el problema de los Threads?
me encuentro atascado con esto y cree otra issue donde a un compañero le ocurre lo mismo. cualquier ayuda es bien recibida

**Comment by fpattillo** [comment]
Hola!! Estoy teniendo el mismo problema, alguien llegó a una solución??? Los qthreads hacen que el programa se caiga con el mismo error de @ljrodriguez1 y los qtimers simplemente ignoran el run().

**Comment by ljrodriguez1** [comment]
lo que debes hacer es guardar una instancia en la clase padre de tu QThread, con self.nombre = TuQThread
 ya que phyton mata al QThread al ver que no esta guardado en ningun lugar
