### ISSUE TITLE
Agregar Botones a un QScrollArea

### ISSUE THREAD

**Issue by FaZorrilla** [IIC2233/syllabus#626]
Hola,

Para la sala de espera, tengo un QScrollArea, donde, la idea, es que cuando se quiere crear una sala, se agregue un boton para entrar a la sala.
Para eso, me guié por esta página: https://stackoverflow.com/questions/22255994/pyqt-adding-widgets-to-scrollarea-during-the-runtime#
Pero sigue sin funcionar. No aparecen nunca botones en mi ScrollArea.
De la misma manera, busque como hacerlo de otra forma con QButtonGroup, pero sigue sin funcionar.
Obtuve esa informacion de esta pagina: https://impatientprogrammer.net/2018/09/14/pyside-pyqt-qbuttongroup-in-3-minutes/

Hay algo que pueda hacer para que me aparezcan los botones en el ScrollArea? Llevo 2 horas en solo esto, porque no puedo avanzar en otras cosas que me faltan por no poder crear las salas destinadas.

Por último, aunque el boton no sirva, quiero por lo menos que aparezca, no he podido agregar botones al ScrollArea desde el principio.

Saludos.

**Comment by lily416** [comment]
Hola 😄 

Te recomiendo ver la respuesta de **eyllanesc** en el siguiente [link](https://stackoverflow.com/questions/50914252/pyqt5-qscrollarea-widget-with-dynamically-created-groupboxes), solo que en vez de usar un `for` en el `__init__` de la venta haz que sea una función que reciba una lista con los nombre de las salas.

Ojala te sea de ayuda.
Ánimo y éxito con la tarea 👋 💪

**Comment by FaZorrilla** [comment]
GRACIASSS!!!
Al fin me funcionó!!!
