### ISSUE TITLE
Dimensiones de los widgets cuando se usa QHBoxLayout() y QVBoxLayout()

### ISSUE THREAD

**Issue by mjgutierrez1** [IIC2233/Syllabus#626]
Releyendo el material de PyQt me di cuenta de que si en el init de una ventana pongo 
```python
        self.edit1 = QLineEdit('', self)
        self.edit1.setGeometry(45, 15, 100, 20)
```
y luego uso `QHBoxLayout()` y `QVBoxLayout()`, al cambiar los argumentos de `self.edit1.setGeometry()` no pasa nada, mientras que si no uso `QHBoxLayout()` y `QVBoxLayout()` sí ocurren cambios.

Entiendo que respecto a los argumentos 45 y 15 que indican posición no debería pasar nada cuando uso `QHBoxLayout()` y `QVBoxLayout()`, ya que son estos últimos los que determinan la posición de `self.edit1`, pero respecto a los argumentos 100 y 20 que están indicando las dimensiones de `self.edit` no entiendo por qué no ocurren cambios.

**Comment by Hernan4444** [comment]
@mjgutierrez1 lo que pasa es que los `Layout` intentan mantener un equilibro de tamaño entre todos los elementos que contienen, es por ello que los últimos 2 argumentos son ignorados en el caso del QLineEdit, puesto que están  desestabilizando el equilibrio. En general el ` QLineEdit` se irá agrandando a medida que el Layout se agrande (como en la interfaz de la T03). 

SI quieres hacer que el tamaño se modifique, tendrías que editar los atributos de los elementos contenidos en el Layout para no aceptar que se reescalen por culpa del Layout.

Pero hay otros elementos como los QPixmap que si son capaces de desestabilizar este equilibrio puesto que dentro poseen una imagen la cual si puede ser reescalada y el Layout no tiene tantos privilegios como para reducir el tamaño de la imagen.

Si quieres saber un poco más, te recomiendo ver este [link](https://stackoverflow.com/questions/10758267/how-to-force-layout-update-resize-when-child-it-manages-resizes)

Saludos ✌️
