### ISSUE TITLE
error desconocido

### ISSUE THREAD

**Issue by aayale** [IIC2233/syllabus#627]
Hola, estoy haciendo la tarea y cuando la corro me sale el siguiente error 
![erro](https://user-images.githubusercontent.com/69651451/93489176-92a57800-f8dd-11ea-941b-14f1314d9052.PNG)

No se como arreglar esto ya que según yo, no hay un error ahí

**Comment by Juampisaez** [comment]
Hola @aayale 
Tengo una duda, el archivo que aparece alli es deportes.py?. De ser así, se esta formando un loop, ya que en Entidades importas deportistas, y luego en deportistas estas importando Entidades. Al importar recorres ese archivo, por esa razon se forma el loop.

Avisame si ese es el error, cualquier cosa quedo atento.
