### ISSUE TITLE
Modelación Circular Personaje-Ventana

### ISSUE THREAD

**Issue by Drpinto1** [IIC2233/Syllabus#627]
Saludos, he visto ejemplos de interfaces gráficas en que, por ejemplo, a un personaje que aparece dentro una ventana se le da el atributo "parent" que es dicha venta; además la ventana tiene su lista de personajes, donde está dicho personaje. Es claro que esto corresponde a modelación circular, pero al tratarse de una interfaz gráfica, no sé si es "incorrecto" que el personaje pueda acceder a la ventana o si tiene tan poco sentido como en otros casos.

En conclusión. es incorrecto modelar de la manera anterior?
Gracias de antemano :smiley:

**Comment by Sforrego** [comment]
Es correcto modelar de esa manera!
Pero asegurate de que el hijo no modifique al padre directamente, sino que por medio de señales.
