### ISSUE TITLE
argumentos de QApplication

### ISSUE THREAD

**Issue by mjgutierrez1** [IIC2233/Syllabus#627]
Respecto a los argumentos que le entregamos a QApplication, en el material sólo se muestra un comentario en uno de los códigos de ejemplo que dice "Si la aplicacion no recibe parámetros desde la line de comandos, QApplication recibe una lista vacía como `QApplication([])`." ¿En qué caso deberíamos darle parámetros a nuestra aplicación?¿por qué en el material a veces se le da el parámetro sys.argv? (probé algunos códigos usando `QApplication([])` y `QApplication(sys.argv)` y no note diferencias en la ejecución del programa)

**Comment by vijuarez** [comment]
Hola!

Primero que todo, hay que entender qué hace `sys.argv`. Esta variable contiene los argumentos que le llegan a Python cuando llamas tu programa desde la línea de comandos/terminal. Por ejemplo, digamos que tenemos un archivo llamado `ejemplo.py` que tiene el siguiente código:
```python
import sys

print(sys.argv)
```
Si yo lo llamo con el comando `python ejemplo.py` desde la línea de comandos el programa solo imprimirá `['ejemplo.py']`, y si añado más argumentos llamandolo con `python ejemplo.py un_argumento 23 22` nos devolverá una ordenada lista con todos los argumentos `['ejemplo.py', 'un_argumento', 23, 22]`.

Esto es bastante útil si quieres hacer tus propias utilidades más adelante! Pero ahora sabes lo que estás pasando a `QApplication`, una lista con los argumentos usados para llamar al programa. `QApplication` recepciona varios de esos argumentos para definir cosas de como correrá el programa, normalmente por motivos de debugeo. [Aquí hay una lista con los argumentos válidos](http://doc.qt.io/qt-5/qapplication.html#QApplication), además de que podrías crear tus propias opciones personalizadas (revisando `sys.argv` antes de pasarle a `QApplication`). Aún cuando tú no vayas a usar ninguna de estas opciones, es buena práctica pasarselos al programa de todas formas (nunca sabes quien usará tu programa en el futuro!).

Ojalá te haya servido, saludos!

**Comment by mjgutierrez1** [comment]
Perfecto, ¡muchas gracias!
