### ISSUE TITLE
Foto de perfil

### ISSUE THREAD

**Issue by BelenMadariaga** [IIC2233/syllabus#627]
Hola!

Ojalá no sea muy tarde, pero tengo una complicación con el bonus. Lo estoy haciendo de manera que al clickear un botón aparezca otra ventana 'preguntando' el nombre de la imagen (+formato) que se quiere colocar. El problema es que no sé de qué manera verificar que efectivamente existe esa foto (servidor), teniendo en cuenta que todas las imágenes y sprites están en la carpeta cliente y no debe haber 'recursos' compartidos entre ellos. Hay otra manera de hacer este bonus?

**Comment by DCCollao** [comment]
Hola!

Revisar que exista (o no) un archivo a subir es tarea del cliente, no del servidor. El servidor solamente debe recibir la foto que el cliente decida enviar, una vez verificada su existencia.

En #567 hay información más detallada de los roles del servidor y cliente. En este caso, la búsqueda de una imagen en los archivos corresponde a la lógica del programa (backend).
