### ISSUE TITLE
Linea roja y azul en foto post filtro

### ISSUE THREAD

**Issue by Tomasalvarez15** [IIC2233/syllabus#627]
Al hacer el filtro se me corrió un pixel por cada linea. Es decir la linea 1 no estaba corrida, la 2 en un pixel, la 3 en dos pixeles etc..
Por lo tanto procedí a corregir este error moviendo cada item de cada lista a la derecha la cantidad de veces de su linea.
El tema es que quedo bien la foto pero me aparecieron dos lineas una rojo y otra azul. ¿Se considera esto como un error en la aplicación del filtro?
Y si es así, algún tip de porque estaría ocurriendo me ayudaría mucho.
![listo](https://user-images.githubusercontent.com/42297751/59969821-60179e80-9525-11e9-90a2-751b6f112a45.png)
![listo2](https://user-images.githubusercontent.com/42297751/59969822-63ab2580-9525-11e9-8ecc-dd77401e6025.png)

**Comment by Tomasalvarez15** [comment]
Confundi el ancho con el alto. Está arreglado

**Comment by ariel-m-s** [comment]
Abriré la _issue_ por si alguien más tiene el mismo problema. Quizá tuvo el mismo error también.
