### ISSUE TITLE
Agregar cosas en el frontend a parte de las hechas en Qt designer

### ISSUE THREAD

**Issue by sjkinast** [IIC2233/Syllabus#628]
Hola si realizé algunas cosas de la clase en Qt designer pero hay otras que no se como hacerlas ahí, existe alguna forma para seguir agregando cosas de diseño en la misma clase ?

**Comment by Sforrego** [comment]
Si!
Puedes importar tu qtdesigner y seguir trabajando con eso. Compileui sirve para compilar el codigo .ui a python.
