### ISSUE TITLE
Ayuda github 

### ISSUE THREAD

**Issue by Jesusdelgad** [IIC2233/syllabus#628]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, tengo un problema subi un avance casi final , creando el git.ignore, pero en el avanze de la esta Tarea no alcance a crear el git ignore es por ende que tengo en mi repositorio los archivos pasados subidos (carpeta sprite y canciones) como las elimino?

**Comment by aaossa** [comment]
Hola @Jesusdelgad , para bajar archivos que quieres ignorar te recomiendo seguir 3 pasos:

1. Saca los archivos que quieres ignorar de tu repositorio (recomiendo moverlos fuera de la carpeta de tu repositorio personal)
2. Actualiza el .gitgnore dejándolo SIN las rutas que quieres ignorar (por ejemplo, borra la línea `assets/`).
3. Verifica con `git status` que se registrara el cambio (el .gitignore editado y los archivos eliminados). Crea un *commit* con todo lo anterior, luego `git push` y verifica que esté todo bien en GitHub.
4. Luego, actualiza de nuevo el .gitignore, agregando las líneas que quitaste en el paso 2 (si quieres ignorar `assets/`, agrega esa línea).
5. De nuevo el paso 3. Usa `git status` para ver si el .gitignore fue editado, crea un *commit* con todo lo anterior, luego `git push` y verifica que esté todo bien en GitHub.
6. Puedes mover de nuevo los archivos que sacaste en el Paso 1, y si usas `git status`, estos no deberían verse (usa `git status` para confirmar que todo funciona).

¡Avísame si te funciona 🙌 !

**Comment by Jesusdelgad** [comment]
Ahi sii ! Muchas graciass
