### ISSUE TITLE
Moral Delegaciones

### ISSUE THREAD

**Issue by osonodml** [IIC2233/syllabus#628]
En el enunciado se estipula que la moral de una delegación es igual al promedio de las morales de los deportistas que componen su equipo, sin embargo, al mismo tiempo se nos puede "entregar" una moral para la delegación.
Esto puede generar una discrepancia entre la moral entregada y el promedio, ¿Con cual debería quedarme?

**Comment by jitorcas** [comment]
Hola @osonodml 

La issue #375 responde a tu pregunta.

Éxito 🏃🏻🏋️‍♀️
