### ISSUE TITLE
ruido en ecualizador

### ISSUE THREAD

**Issue by acrojas2** [IIC2233/Syllabus#628]
Hola! 
He estado harto rato pegada con esto, mi ecualizador funciona en el sentido que toca mas rápido o lento. El problema es que de fondo suena como cuando la antena de un televisor se echa a perder o pierde la señal, no se si se entiende. Mi pregunta es si esto es normal o debo arreglarlo?
 Lo que está editado del header es SampleRate, ByteRate(como cambia la _fr_, según la imagen que subieron en la issue #595 este valor cambia a _((fr * bits_per_sample * 2) / 8)_ ), SunChunk2Size. Mientras que en el data, se aplicaron las operaciones según el enunciado al segmento de data necesario (segmento de secuencia de bytes) para tocar 20 segundos (cantidad de bytes: ByteRate * 20).
P.D:  El sonido de fondo del que hablo es como este: https://www.youtube.com/watch?v=P3EgPi-PDyc
Espero puedan ayudarme! Todo se agradece!
Saludos!

**Comment by akaminetzkyp** [comment]
Mi ecualizador hace lo mismo! Creo que es lo que debería pasar. Saludos!

**Comment by DiegoAndai** [comment]
Hola! Con que canción les pasa esto? con todas las que subimos o solo algunas? que tan grave es la distorsión? que f y n ocuparon? Si el ruido es menor no debería haber problema, puede pasar que al manipular los bytes se agregue ruido pero este no debería ser demasiado, o sea no debería afectar al reconocimiento de la canción.

Saludos.

**Comment by rrhurtado** [comment]
Hola, por lo que explicas existe una distorsión, que es esperable en cierto grado al aplicar algún filtro. Tal como dice Diego, podrías ir variando los parámetros de `f` y `n` de manera que el ruido de fondo sea lo menos notorio posible.

Saludos !

**Comment by acrojas2** [comment]
@DiegoAndai En mi caso se reconoce la canción clarito, pero igual considero que es como molesto. Es como si estuvieras viendo tele con ese ruido. No se si viste el video que puse, va como de fondo pero intenso, como el f y n son aleatorios y no se como arreglar el problema, ya que a menor n, menor es ese ruido. Podría ser que el aleatorio sea entre un rango menor? 
Saludos!

**Comment by acrojas2** [comment]
@rrhurtado hasta qué grado es esperable?
saludos!

**Comment by rrhurtado** [comment]
Abstrayéndonos de la tarea, el grado de distorsión que añade un filtro cualquiera depende de cuanto cambie éste el archivo original.

Puedes consultar más al respecto en el siguiente link
http://www.supremepiano.com/learn/eq2.html

Saludos

**Comment by akaminetzkyp** [comment]
Yo pensaba que el propósito de el filtro dado era hacer que la canción sea más difícil de reconocer. Aparte de la "estática" no escucho ninguna modificación a la canción.

Creo que el resultado que estamos obteniendo es el que se espera para la mezcla de bytes que estamos haciendo.

**Comment by acrojas2** [comment]
una pregunta, mi ecualizador ademas de cambiar la frecuencia cambia la velocidad de la canción, esto está bien ? Como mencioné anteriormente, del header edité el SampleRate, ByteRate y SunChunk2Size. Esto es correcto? o hay alguna de esas que no debo modificar? @DiegoAndai @rrhurtado 
Saludos!

**Comment by yoavnavon** [comment]
Hola, me pasa lo mismo de tener mucho ruido en ecualizador. De hecho, no se cual es la función del "filtro", ya que si solo cambio el SampleRate, ya ocurre el efecto esperado, y el ruido solo surge con el supuesto filtrado. Saludos!

**Comment by DiegoAndai** [comment]
Hola! Si bien puede generarse ruido, esto no debería pasar en gran cantidad ni ser demasiado notorio. El filtro no consiste en ese ruido, sino en efectos que se dan por el cambio de frecuencia y la fórmula que tienen que aplicar. La fórmula tiene efecto aparte del cambio del SampleRate, quizás a bajos n sea imperceptible. Si siguen los pasos del enunciado al pie de la letra debiese funcionar bien, recuerden que tienen que poner mucho ojo en el endianness y la representación de bytes que se ocupa, pues esonquizas les está causando problemas. Acuérdense de revisar la última versión del enunciado.

**Comment by Veenty** [comment]
@acrojas2 te fijaste que en wav signed = True?

**Comment by jorgeriesco** [comment]
Hola, a mi me pasaba lo mismo del ruido, pero con n = 1 y cualquier frecuencia el ruido no se nota. Ahora bien se me acelera la canción, lo que no se si está bien-

**Comment by acrojas2** [comment]
@Veenty No, de que me sirve eso?

**Comment by acrojas2** [comment]
hola! 
@DiegoAndai  puedes decir si lo que le pasa a @jorgeriesco está bien? a mi me pasa lo mismo y ya he intentado hacer lo siguiente: solo modificar el sample rate del header  y aplicar el tratamiento en el tal como dice el enunciado  y hacer lo lógico según la tabla que pusieron en la issue #595 que sería editar el sample rate, byte rate y subchunk2size del header y aplicar el filtrado respectivo al data. Saludos!

**Comment by DiegoAndai** [comment]
@acrojas2 Hola!, si, acelera la canción. Lo del ruido me parece curioso, porque no les debería pasar, averigua lo del comentario de @Veenty que es muy importante, eso tienen que tenerlo en cuenta y puede que incluso sea eso lo que les causa el ruido. 

Del header no cambies nada más que el sample rate, tal como dice el enunciado.

Saludos.
