### ISSUE TITLE
no puedo iniciar qt designer

### ISSUE THREAD

**Issue by bedefrunner** [IIC2233/Syllabus#628]
Hola! Seguí los pasos que dijeron en #618, me descargué Qt desde la página que dicen en esa issue (soy mac) y se me descargó Qt Creator, pero no Qt Designer. Si busco "designer" en spotlight no me aparece nada. Pero según he visto en internet, Qt Creator como que "incluye" a Qt Designer. De todas formas, al tratar de crear un Nuevo proyecto en Qt Creator, tengo un problema en el paso Kit Selection. Adjunto pantallazos paso por paso hasta llegar al problema.

1. Abro Qt Creator y selecciono "New Project"
![new project](https://user-images.githubusercontent.com/20782509/32138413-b93ed1a6-bc08-11e7-9801-245ed2e77cad.png)

2. Selecciono Applications -> Qt Widget Applications y apreto "Choose..."
![qwidgets application](https://user-images.githubusercontent.com/20782509/32138418-c8348e8a-bc08-11e7-95f5-4e7ea0f2d08f.png)

3. Pongo de nombre "helloWorld" y apreto "Continue"
![introduction and project location](https://user-images.githubusercontent.com/20782509/32138435-03926114-bc09-11e7-8258-e1c48413011d.png)

4. Y aquí está el problema, no sé que hacer. No me deja continuar.
![problema kit selection](https://user-images.githubusercontent.com/20782509/32138442-29387250-bc09-11e7-842b-ce061d8dfa3e.png)

**Comment by vijuarez** [comment]
Hola!

QtCreator es un poco mañoso con esas cosas, ya que además de QtDesigner (que es la parte que nos interesa) contiene todo lo necesario para crear y compilar aplicaciones en Qt. Si no tienes un kit de compilado, no te dejará crear un proyecto.

Lo que sí puedes hacer (y que yo hice durante el curso) es lo siguiente:
(notese que hice esto en Windows, pero a ti te debería funcionar igual)

1.  Primero que todo, abrimos QtCreator:
![image](https://user-images.githubusercontent.com/24497477/32138755-19541532-bc0f-11e7-9627-83cb32f53fe9.png)
2.  Abrimos `File` y seleccionamos `New File or Project...` (aquí también sirve `Ctrl + N`, me imagino que será el mismo comando en Mac con la tecla de comandos)
![image](https://user-images.githubusercontent.com/24497477/32138767-55eedab8-bc0f-11e7-8955-acdb96948620.png)
3.  Dentro del dialogo elegimos la categoría de `Qt` y luego la template de `Qt Design Form`. Continuamos con `Choose...`.
![image](https://user-images.githubusercontent.com/24497477/32138779-7ef0f7ca-bc0f-11e7-8f94-dab8c905bce2.png)
4.  Eliges la template que más te guste. (`Main Window` debería estar bien) y le das a `Next`.
![image](https://user-images.githubusercontent.com/24497477/32138792-b91f1e54-bc0f-11e7-999c-a8655fdbcf61.png)
5. Dale `Next` y `Finish` a los nuevos dialogos (ahí puedes ver donde guardar el archivo y si quieres meterlo de inmediato en tu VCS (como github)).
6. Y ya está, llegaste a QtDesigner!
![image](https://user-images.githubusercontent.com/24497477/32138803-ebc4f2f2-bc0f-11e7-8778-cade22699539.png)

Ojalá los pasos te sirvan. Nos cuentas, saludos!

**Comment by bedefrunner** [comment]
Funcionó! Muchas gracias
