### ISSUE TITLE
Forma mas simple de aplicar el 2x en las canciones

### ISSUE THREAD

**Issue by Jaluco** [IIC2233/Syllabus#629]
Si encuentro otra manera de acelerar el audio a 2x distinta a la puesta en el enunciado, puedo usar esa?
(Sin librerias de ningun tipo)

**Comment by hanavarrete** [comment]
Siempre y cuando sea con manejo de bytes, y no métodos mágicos si 😄

**Comment by Jaluco** [comment]
Fantástico
