### ISSUE TITLE
Velocidad de Movimiento

### ISSUE THREAD

**Issue by NoemiCC** [IIC2233/Syllabus#629]
En el enunciado de la tarea 5, en la parte de tamaño, dice que el tamaño afecta a la velocidad de movimiento pero luego no se especifica en ninguna parte como se calcula la velocidad ni como la afecta el tamaño. Queda a mi criterio o hay algún algoritmo?

**Comment by hanavarrete** [comment]
El movimiento queda a criterio de ustedes, depende de ustedes como quieren manejar el movimiento (tal vez en pixeles u otra cosa que les facilite el trabajo). Se esperaría que los enemigos de distintos tamaños se muevan más rápido o lento, pero como no está en el enunciado esto lo deciden ustedes 😄 . Saludos!

**Comment by valeria-adasme** [comment]
Además en la tienda hay items para aumentar la velocidad de movimiento del personaje principal, eso significa que es obligación crear esta velocidad o no?

**Comment by iqacevedo** [comment]
sipi :)
