### ISSUE TITLE
Filtro daltonismo

### ISSUE THREAD

**Issue by Ed0ss** [IIC2233/syllabus#629]
Hola, en el enunciado aparece que para el bonus de daltonismo se debe modificar la imagen para que una persona con deuteranopia pueda visualizarla correctamente, pero el problema es que he buscado bastante acerca de cómo hacer esto y no he encontrado nada, pero sí he encontrado formas para poder simular el cómo una persona con daltonismo ve las imágenes. Así mi duda es si es que es esto lo que están pidiendo (modificar la imagen para simular lo que ve una persona con deuteranopia), o lo que dice el enunciado, con lo que quizas debiera investigar un poco más.

Saludos!

**Comment by KnowYourselves** [comment]
Hola @Ed0ss!

Es lo primero que dices. Si pasas la imagen por un filtro de deuteranopia, debe verse igual a si lo pasas por tu filtro.

Éxito!
