### ISSUE TITLE
variable global parametros

### ISSUE THREAD

**Issue by BelenMadariaga** [IIC2233/syllabus#629]
hola, super rápido, para cambiarlo si está mal

por facilidad abri el archivo parámetros de cliente y servidor una vez en cada .py en lo que lo necesitaba, antes de todas las clases, contaría como variable global?

**Comment by lily416** [comment]
Esta bien mientras no modifiques el contenido de dichas variables, es decir, el valor se mantiene constante.

Saludos 👋
