### ISSUE TITLE
Métodos abstractos: Diagrama de clases

### ISSUE THREAD

**Issue by barbarafcp** [IIC2233/syllabus#629]
Hola! En una clase abstracta, algunos métodos tienen un pass, porque se definen en las clases hijas, le pongo que retorna None en el diagrama, y en las clases hijas poner lo que esta retorne? 
En caso de que se definan en la clase madre lo que retornan las funciones, igual las funciones las debo volver a escribir en la clase hija?, bajo esta misma linea, debo poner repetir todos los atributos que la clase hija hereda de la madre?
Y una duda aparte que tenia era que si un método recibe algo de la clase delegaciones y un string por ejemplo tengo que poner (Delegaciones[], str)?

**Comment by ignacio-urrutia** [comment]
Hola @barbarafcp con respecto a la primera pregunta, para las clases abstractas debes incluir todos los métodos que definas, incluyendo los que tengan un pass ( tal como dices, escribes que retorna None). Después, si haces override en una clase hija, también debes incluirla en el diagrama y especificar que va a retornar el método sobreescrito.
Con respecto a la segunda pregunta, debes poner el tipo de elementos que son los parámetros que entran al método, por ejemplo si es un bool de la clase delegaciones y un string, pones _(bool, str)_.
Espero haberte ayudado y mucho éxito :D
