### ISSUE TITLE
Duda sobre formato de crear publicaciones

### ISSUE THREAD

**Issue by Ikilly0** [IIC2233/Syllabus#63]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Muy breve, en el enunciado:
![image](https://user-images.githubusercontent.com/69522095/131723401-8fbea5ef-fc2f-46ed-84b5-9f41fdd413f1.png)
No dice nada sobre cual es el formato permitido/entrante de las publicaciones, por ejemplo: El nombre puede ser un espacio solamente? que deberia responder la consola si se ingresan letras y no numeros en el precio? Si la descripcion es un string vacio que sucede? de manera alternativa, a que deberiamos prepararnos en estos inputs del usuario? Muchas gracias.

**Comment by nanglada** [comment]
Hola Ikilly0! 
Lo que preguntas no está especificado en el enunciado, por lo que puedes asumir lo que te parezca conveniente. Alfinal lo que más importa es que las publicaciones se puedan crear correctamente y que tu programa no se caiga con estos casos borde. Más allá de eso, tu eliges según lo que te haga más sentido.
Recuerda mencionar explícitamente los supuestos en tu README!
Suerte con tu tarea ⭐

**Comment by Ikilly0** [comment]
Al final me di la lata de crear loops muy insistentes para que quede bonito

**Comment by nanglada** [comment]
Perfecto! Acuerdate de especificar tus supuestos en el README.
