### ISSUE TITLE
problema con archivos en cambiar_planos

### ISSUE THREAD

**Issue by Martinluco** [IIC2233/Syllabus#63]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/20)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/19)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Al probar los tests para el método cambiar_planos me sale este error: Traceback (most recent call last):

  File "/Users/martin/Desktop/Avanzada/Martinluco-iic2233-2024-1/Tareas/T1/tests_publicos/test_09_cambiar_planos.py", line 69, in test_2
    self.assertEqual(red.cambiar_planos("test_2.txt"), True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martin/Desktop/Avanzada/Martinluco-iic2233-2024-1/Tareas/T1/red.py", line 207, in cambiar_planos
    with open(nombre_archivo) as archivo:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'test_2.txt'

Asumo que no reconoce que se abre el archivo, y si es así, no se como hacerlo.
Gracias :)

**Comment by agustinvaldesz** [comment]
Me sale el mismo error. Es algo de los archivos o un error de código?

**Comment by IanZmen** [comment]
Hola!! creo que la respuesta a su pregunta la pueden encontrar en la issue #24 ... si eso no responde a su pregunta avísenme

**Comment by agustinvaldesz** [comment]
> Hola!! creo que la respuesta a su pregunta la pueden encontrar en la issue #24 ... si eso no responde a su pregunta avísenme

Hola! Me pasa que si se como probar los tests, pero para el caso de la funcion cambiar_planos, me tira un error del tipo
FileNotFoundError: [Errno 2] No such file or directory: 'data\\ciudad_T.dcc'
No se si es un error de codigo mío, o algo con los tests cases

**Comment by IanZmen** [comment]
@agustinvaldesz entiendo, que tal con la issue #42 creo que esta sí solucionará el problema, de no ser así vuelve a responderme y vemos más a fondo el problema

**Comment by Martinluco** [comment]
Ya lo resolví! muchas gracias

**Comment by agustinvaldesz** [comment]
> @agustinvaldesz entiendo, que tal con la issue #42 creo que esta sí solucionará el problema, de no ser así vuelve a responderme y vemos más a fondo el problema

Mmm, me sigue diciendo lo siguiente cuando corro los tests (lo estoy probando con todos_tests y comentando los que no me interesan)
FileNotFoundError: [Errno 2] No such file or directory: 'data\\ciudad_T.dcc' 
No se si quizas le estoy dando mal la ruta nomás.

**Comment by agustinvaldesz** [comment]
yaa voy, el comando que ejecuto en la terminal del computador es: 
C:\Users\Agustín Valdés Z\OneDrive - uc.cl\Escritorio\Practica\agustinvaldesz-iic2233-2024-1\Tareas\T1>python todos_tests.py

**Comment by agustinvaldesz** [comment]
ahí hice el git push

**Comment by IanZmen** [comment]
Hola Agustin, el error  FileNotFoundError: [Errno 2] No such file or directory: 'data\ciudad_T.dcc' es exactamente lo que prueba uno de los test, por lo que tu debes encontrar la formula de evitarlo. Como consejo te recomiendo que veas en que linea de tu archivo red.py salta tu código de error, pregúntate porque esta mal y piensa en como lo puedes corregir. Tristemente no estoy seguro si te puedo ayudar más porque la idea es que lo resuelvas tu. Mucho éxito!!!!!!!

**Comment by agustinvaldesz** [comment]
> Hola Agustin, el error FileNotFoundError: [Errno 2] No such file or directory: 'data\ciudad_T.dcc' es exactamente lo que prueba uno de los test, por lo que tu debes encontrar la formula de evitarlo. Como consejo te recomiendo que veas en que linea de tu archivo red.py salta tu código de error, pregúntate porque esta mal y piensa en como lo puedes corregir. Tristemente no estoy seguro si te puedo ayudar más porque la idea es que lo resuelvas tu. Mucho éxito!!!!!!!

Gracias! Ahí lo solucione
