### ISSUE TITLE
exec

### ISSUE THREAD

**Issue by F-arellano** [IIC2233/syllabus#63]
solia usar el comando exec para transformar una "lista" guardada como string a una lista de verdad, ya que solo requeria una linea de código. Averiguando sobre exec lei que podria traer varios problemas al usarlo, asi que solo abri el issue para saber un poco mas sobre por que no lo podemos utilizar.

**Comment by KnowYourselves** [comment]
Hola @F-arellano!

Hay una gran y larga lista de razones por las cuales no se debería utilizar `exec` y `eval`, algunas más complejas que otras, pero trataré de explicarte las que estimo que son más importantes:

1. Si estás haciendo algo con `exec`/`eval` **probablemente hay una mejor forma de hacerlo**, por ejemplo, en el caso que propones existen las funciones `join` y `split` que te podrían ayudar.
2. **Estas funciones hacen que tu código sea menos legible**, volviendo al ejemplo, si ocupas `exec` para transformar un string a una lista no hay una forma simple de saber que estás haciendo solo por inspección de tu código. 
3. Siguiendo la linea del punto 2. `exec` hace que **herramientas tengan dificultad para analizar tu código**, por ejemplo, el intérprete no podría decirte exactamente donde hay un error, tu IDE no podría encontrar definiciones ni funciones definidas dentro de un `exec`, etc.
4. Finalmente, funciones como `exec` y `eval` a la larga hacen que se te haga **muy dificil leer tu propio código**. En usos pequeños como el que mencionas no dan mayor problema, pero en programas más extensos y complejos (como las próximas tareas del curso) se podría volver un problema y traerte más dolor de cabeza que soluciones.

En resumen, les prohibimos el uso de estas funciones porque para gente que esta aprendiendo a programar puede parecer una alternativa muy tentadora, pero que a la larga trae más cosas malas que buenas. 

Espero haberte ayudado!

**Comment by KnowYourselves** [comment]
@F-arellano recuerda no cerrar las issues para que tu pregunta les sirva a otros!
