### ISSUE TITLE
Cuestionario SIDING para diagrama de clases

### ISSUE THREAD

**Issue by benjastraub** [IIC2233/Syllabus#63]
¿Cuándo estará disponible el cuestionario para subir el diagrama de clases?

**Comment by FernandoPieressa** [comment]
Hola!

Ya están disponible los cuestionarios para el diagrama de clases.

Saludos!

**Comment by rakarachon** [comment]
El diagrama se puede subir una única vez al cuestionario o puede ser más de una vez antes del plazo límite?

**Comment by stephichau** [comment]
@rakarachon puedes subirlo infinitas veces mientras esté vigente :)

**Comment by rakarachon** [comment]
@stephichau bacan, gracias!!
