### ISSUE TITLE
Uso de la función datetime

### ISSUE THREAD

**Issue by minsoos** [IIC2233/syllabus#63]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola, puedo usar el módulo datetime para agregarle la fecha y hora a los mensajes agregados?
[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by Tsbalart** [comment]
Hola @minsoos! Si puedes! De hecho, se recomienda. Éxito con la tarea!

**Comment by gatochico** [comment]
Complementando lo que indica @Tsbalart , recuerda que toda duda acerca de librerías/módulos a usar se debe hacer en la Issue respectiva ( #44)  y no en una issue aparte (es más, si lees el listado de librerías permitidas de esa issue verás que ya estaba `datetime` 👀 )
