### ISSUE TITLE
Distribución de puntaje: Formato Fecha

### ISSUE THREAD

**Issue by furcelay** [IIC2233/syllabus#63]
En la tabla de distribución de puntajes de Canvas se indica en **amarillo** el ítem 
_"La fecha del prograpost se encuentra en el formato pedido"_, 

¿Esto quiere decir que **necesariamente** debo almacenarlo en este formato en mi código? 

¿No puedo guardarlo como un objeto `datetime` y solo ajustarlo al formato pedido cuando se requiera? :slightly_frowning_face:

**Comment by Tito0906** [comment]
holaa @furcelay , lo que busca ese ítem de la pauta es que la fecha se muestre y se almacene a lo largo de tu programa en el formato YY/MM/DD. La manera en que tu manejes la fecha queda a tu disposición mientras sea con librerias y elementos permitidos.
