### ISSUE TITLE
verifica_ alcance_bomba()

### ISSUE THREAD

**Issue by vicenterodas** [IIC2233/Syllabus#63]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/21)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/20)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola, mi duda es la siguiente.
Puedo hacer que esta función retorne True o False (en caso de que su alcance sea correcto o incorrecto) en vez de retornar el alcance en si mismo. Esto porque me facilitaría su uso al momento de solucionar el tablero. Gracias

**Comment by joaquindm02** [comment]
Hola @vicenterodas, las funciones que debes completar no se les pueden modificar ni los parámetros que recibe, ni los que retorna, pero lo que puedes hacer en esta situación es hacer que una nueva función, que puede ser idéntica a la otra, pero que te retorne lo que tu quieras. Puede ser un poco tedioso, pero funciona.
