### ISSUE TITLE
Duda acerca del tablero y error de codigo

### ISSUE THREAD

**Issue by MaximilianWilke** [IIC2233/Syllabus#63]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

1.- No entendí si al crear la partida, al momento de ubicar cada bestia en el tablero solamente hay que generar unas 'coordenadas' para cada bestia, o tambien hay que crear la lista de listas con un 'N' en cada coordenada.

2.- Si la respuesta a lo anterior es sí, entonces estoy teniendo un problema para posicionar las bestias, ya que en lugar de que cada bestia se posicione en su coordenada respectiva, estas respetan la coordenada para la columna pero no la de la fila ya que estos se posicionan en cada sub-lista.

**Comment by Emiliax16** [comment]
Hola @MaximilianWilke . Al crear el tablero, debes primeramente calcular cuántas bestias existirán en total. Esto se hace con la fórmula en la sección 5.1 del enunciado. Por lo tanto tendremos. N = total de bestias en el tablero. Luego, debemos ubicar estas bestias al azar en el tablero. Si quieres crear una lista de listas para guardar las coordenadas de cada bestias, puedes hacerlo, aunque debe estar en el tablero. Entonces, si tu tablero es una listas de listas, ahí agregas estas coordenadas aleatorias para las N-bestias. La implementación del tablero debe ser de este modo para poder usar el archivo `tablero.py`.

Respecto a tu segunda pregunta, tienes que revisar cómo estas intentando agregar un caracter a una posición x de tu matriz del tablero. Recuerda que para acceder a una posición del tablero sería:
`tablero[fila][columna]`
Con esto, puedes simplemente asignarle un valor a esta posición. Quedo atenta a cualquier duda. Saludos!

**Comment by MaximilianWilke** [comment]
Es que hago literlamente tablero[fila][columna] para conseguir el objetivo, sin embargo como mencioné, la N no se añade sólo en esa coordenada, sino en todas las otras filas en la misma columna, intente hacerlo de nuevo y sigo obteniendo el mismo resultado

**Comment by Emiliax16** [comment]
@MaximilianWilke Miré tu código (el último commit que subiste) y el error está en como estás creando tu tablero. Efectivamente creas una matriz, pero estás utilizando listas previamente creadas para construirlas. Te dejo un link útil para aprender como manejar y construir matrices, de esta manera puedes seguir sin problema. Recuerda citar en tu readme cualquier código externo que utilices. Espero te sirva.
[http://www.cristalab.com/tutoriales/crear-matrices-en-python-utilizando-listas-c103122l/](url)
