### ISSUE TITLE
¿Hay que copiar la carpeta T1 de Syllabus?

### ISSUE THREAD

**Issue by martina-abello** [IIC2233/Syllabus#63]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](https://github.com/IIC2233/Syllabus/issues/56)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](https://github.com/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

En mi repositorio hubo desde el principio una carpeta para las tareas, y cada subcarpeta TX ya tenía una plantilla para el README.md, por lo que asumí que tendría que crear desde cero cada archivo necesario.
Sin embargo, estuve revisando la carpeta T1 del Syllabus, y veo que hay varias carpetas y archivos ya hechos? Los tests en particular. Además, la plantilla del README.md es distinta. Por eso quiero saber si en realidad se supone que copie a mi repositorio la carpeta desde Syllabus, y no mantenga la otra.

**Comment by roahoki** [comment]
Efectivamente, los archivos de la tarea 1 presentes en el Syllabus los puedes copiar a tu carpeta T1 en tu repositorio personal. El README que les dejamos en la carpeta T1 del Syllabus es un template que ustedes deben rellenar a medida que vayan avanzando en su trabajo , recuerda que un buen README es una excelente práctica que demuestra que sabes lo que hace tu programa 🐈‍⬛

**Comment by martina-abello** [comment]
Mhm, pasa que ya había un template de README en el repositorio personal, y era distinto pero no _tan_ distinto, y me confundió. Entonces, ¿se copian _todos_ los archivos que ya hay en la carpeta en Syllabus? ¿Las subcarpetas apoyo_adicional y tests, el enunciado, tableros.txt, el README y todos los .py? ¿O solo algunos?

**Comment by roahoki** [comment]
Como dices, sacas _todos_ los archivos que ya hay en la carpeta T1 del Syllabus, lo cual incluye las carpetas, .txt, el README y todos los .py. Una vez que tengas todos los archivos en tu repositorio personal, ya estarás lista para poder empezar la tarea como tal

**Comment by martina-abello** [comment]
Muchas gracias ^-^

**Comment by Hernan4444** [comment]
Hola @martina-abello 

Para complementar todo esto, si bien es correcto que copies los archivos a tu repo privado para trabajar. Antes de hacer push, recuerda que hay ciertos archivos a ignorar. Con ignorar nos referimos a que debes crear un archivo `.gitignore` que haga que git no pesque ciertos archivos al momento de ahcer `git add` o `git status`. Para que tengas cuidado de no subir los archivos a tu repositorio si es que el enunciado pide que los ignores.


Saludos y mucho éxito en tu tarea!

**Comment by roahoki** [comment]
Muy importante lo del `.gitignore`!!, mucho éxito en la tarea y cualquier otra duda, siempre estarán las _issues_

**Comment by JavierMoralesD** [comment]
Hola. Una última pregunta, acerca de la subcarpeta `apoyo_adicional`. Esta debería estar en la carpeta `T1`, o es únicamente para uso personal? Me surge esta pregunta porque no está especificada dentro de las instrucciones del `.gitignore`, tanto en las específicas del Enunciado, ni en Bases Generales, pero su nombre sugiere que no es parte de la entrega.
