### ISSUE TITLE
Diagrama de clases

### ISSUE THREAD

**Issue by santilaguna** [IIC2233/Syllabus#63]
Si tengo varios módulos y sólo uno de éstos tiene clases, ¿debo representar de alguna manera a los otros módulos, o no es necesario? Si es el primer caso, ¿Se realiza un diagrama aparte con las funciones que no son atributos, métodos, ni properties de ninguna clase ? o si deben ser referenciadas en un sólo diagrama de clases ¿de qué forma se debe hacer?

**Comment by IchottMano** [comment]
@santilaguna Hola!
Efectivamente no es necesario que representes a los otros módulos.
Para las funciones que no existan dentro de una clase en tu código, no es necesario que aparezcan en tu diagrama.
Saludos!

**Comment by santilaguna** [comment]
Gracias!

**Comment by joaquineichholz** [comment]
Hola, tengo un par de dudas sobre el diagrama que no aparecen en la materia.

1.- ¿Cómo pongo las properties en él? Hay alguna manera estándar o puedo poner una (P) al lado de donde puse el atributo y listo 

2.- ¿Es necesario poner si el atributo es privado (self.__atributo) o no? de ser así, ¿Cómo se pone?

**Comment by IchottMano** [comment]
@joaquineichholz Hola!
Tu primera pregunta ya fue respondida en la issue #30 con mas detalle, asi que te recomiendo que la leas.👍 👍 
En segundo lugar, si decides hacer un atriputo privado (self.__atributo) tienes que poner ese mismo nombre en tu diagrama, es decir escribirlo con los underscores ("_") correspondientes.
Espero te haya ayudado.
Saludos y mucha suerte con tu tarea! 👋👋

**Comment by bmorrisc** [comment]
Hola! Una duda relacionada al mismo tema... me gustaría saber si hay una forma para representar las clases abstractas con sus métodos y atributos en el diagrama, o solo se representa con herencia?

**Comment by IchottMano** [comment]
@bmorrisc Hola!
Tal y como dices se representa con herencia.
Saludos!
