### ISSUE TITLE
Error para encontrar archivos csv

### ISSUE THREAD

**Issue by Lexiesm** [IIC2233/Syllabus#63]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Holaa buenas! tengo una duda de un error que no se de donde salió. Hace unos días estaba haciendo el código de la tarea en vs code y me funcionaba super, me encontraba los archivos csv cuando los abría y todo. Pero un día volver a abrir el vs code para seguir y al correrlo ahora no encontraba los archivos csv, Me sale el siguiente error:
FileNotFoundError: [Errno 2] No such file or directory: 'reclamos.csv'

se que no lo encuentra pero es raro porque los archivos si están dentro de mi carpeta T0 :(

**Comment by catalina-arcila** [comment]
Hola @Lexiesm, revisa en que parte estás corriendo el programa, probablemente no lo estás corriendo en la carpeta de la tarea
