### ISSUE TITLE
Soldados en ataque y defensa.

### ISSUE THREAD

**Issue by aescobar4** [IIC2233/syllabus#63]
En el punto 4.1, sale que si una civilización ataca a otra, pierde a sus soldados para defender hasta el siguiente turno. Es decir, si DCC ataca y luego La Comarca lo ataca en el mismo turno, DCC no tendrá sus soldados para defenderse. Sin embargo, los turnos están dados por una forma [A,B,C], donde juega primero el jugador A, después el B y por último el C y después empieza un turno nuevo. Esto quiere decir que si la civilización C ataca a cualquiera en el turno 1 y después en el turno 2 es atacada, los soldados forman parte de la defensa o no? Técnicamente pasó el turno, pero la civilización C no ha pasado una "ronda" completa sin tener a los soldados sin defender. Que se hace en ese caso?

**Comment by SergioMoralesBasualto** [comment]
Si no me equivoco, es hasta el siguiente turno tuyo. Por ende, estarían ocupados si te atacan. Espero no estar mal

**Comment by gatochico** [comment]
Hola!

Se considera que los soldados están atacando en el mismo turno que se define que atacan a otra civilización. Si en un turno una civilización decide no atacar a nadie, esta se defenderá de cualquier potencial ataque con TODOS sus soldados, haya atacado a alguien en el turno anterior o no, ya que se considera que los soldados ya terminaron su ataque en el turno anterior.

Espero haberlos ayudado, saludos.

**Comment by JJJGGGG** [comment]
Creo que eso no responde la pregunta (tal vez me equivoco). Como dijo aescobar, si una civilizacion es la ultima en atacar en un turno, entonces al comienzo del proximo turno (porque ahi es el turno del jugador), recibe todos sus soldados de vuelta, por lo tanto nunca no puede defender.
Es esto cierto?

**Comment by gatochico** [comment]
Ya entendí tu duda. Si se manda a atacar en un turno, es ese mismo turno el que tiene el déficit de los soldados en defensa. Por ejemplo:

Turno 1: Orden de civilizaciones [A,B,C]
```
Acciones tomadas:
A decide atacar a C.
B no hace nada.
C decide atacar a B. 

Ejecución de acciones:
Como A decidió atacar a C, su defensa actual no incluye a sus soldados hasta que se acabe el turno.
B recibe daño, pero defiende con todos sus soldados.
C había decidido atacar a B, por lo que sus soldados no están disponibles para recibir el ataque de A. Su defensa no incluye a los soldados al momento del ataque de A.
```

Turno 2: Orden de civilizaciones [A,B,C]
``` 
Como este es un turno nuevo, tanto los soldados de A y C ya volvieron. Por ende, ambos tienen su defensa completa de nuevo (A menos que decidan atacar de nuevo, que se reflejaría en la parte de Acciones tomadas). 

Acciones tomadas:
.... 

Ejecución de acciones:
....

```

Saludos!

**Comment by aescobar4** [comment]
Perfecto, esa era la duda, gracias!
