### ISSUE TITLE
Duda Ejecución por terminal main.py

### ISSUE THREAD

**Issue by Amath3o** [IIC2233/Syllabus#63]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola! tengo una duda sobre como va a ser la ejecución del  archivo main.py y es si va a ser por la terminal de VScode  o por la de git, ya que en el caso de git al llegar a un input el código se queda estancado recibiendo respuestas y no estoy seguro de si este bien

![image](https://github.com/user-attachments/assets/929f2e18-6f6d-4b72-a8ba-4a36c2ab70d7)

**Comment by ignacio-sp** [comment]
Hola @Amath3o! como se indica en el enunciado, la tarea se ejecuta únicamente desde la terminal del computador, que normalmente depende del sistema operativo de cada ayudante (y no debería afectar a la ejecución de la tarea). La terminal de git no es utilizada para la revisión
