### ISSUE TITLE
Ejercicio 6.2, problema con módulo time

### ISSUE THREAD

**Issue by ngsuarez** [IIC2233/syllabus#63]
Cuando tengo que calcular la división `lista_promedio/ set_promedio:.2f` me arroja un error de _ZeroDivisionError_. Esto ocurre porque, la función `pertenencia_cronometrada` tarda 0.000000 segundos en encontrar el elemento en un set. Aún sabiendo esto, no se me ocurre como arreglarlo (el PC será muy rápido?)

**Comment by igbasly** [comment]
Hola @ngsuarez :v:

En el ejercicio propuesto se te pide calcular el tiempo promedio que se tarda en encontrar los elementos, por lo tanto, al ser un promedio no deberías tener que dividir por 0* (ni por el tiempo :wink:).*

Quedo atento por cualquier cosa :smile:.

**Comment by ngsuarez** [comment]
Si pero el problema es que la búsqueda promedio también me queda en 0 segundos. En consola obtengo (por ejemplo):
set  -- La búsqueda de 9047457 demoró... 0.000000 segundos.
list -- La búsqueda de 9047457 demoró... 0.113963 segundos.
set  -- La búsqueda de 7289703 demoró... 0.000000 segundos.
list -- La búsqueda de 7289703 demoró... 0.094970 segundos.
set  -- La búsqueda en promedio demoró... 0.000000 segundos.
list -- La búsqueda en promedio demoró... 0.064239 segundos.

Y todas las búsquedas con set me quedan en 0.000000, es bien extraño.

**Comment by igbasly** [comment]
Entiendo, en ese caso si ya verificaste que está implementado de forma correcta y que el valor obtenido es debido a la velocidad de procesamiento de tu computador, entonces se puede decir que está correcto y simplemente es demasiado rápido.
Como el ejercicio no se hizo pensando que esto llegase a pasar y que el primer dígito significativo no alcanza a ser reconocido por el programa, la división por 0 es solo un error colateral. Puedes asumir que una aproximación sería que las `listas` demoran un número muy grande de veces más que los `sets` en encontrar los datos.

De todas formas, te pido que revises tu implementación solo para agotar las opciones, pero a mi parecer no debería haber problemas. Quedo atento a cualquier comentario 😅.

**Comment by ngsuarez** [comment]
Probé cambiando la línea `from time import time` a `import timeit`. Y cambié la línea `time.time()` por `timeit.default_timer()` y funcionó 😁.

**Comment by igbasly** [comment]
Genial!😃 Más tarde intentaré averiguar por qué jajaja
Éxito 🙌
