### ISSUE TITLE
vel_movimiento vs. n_pixeles del mapa

### ISSUE THREAD

**Issue by clementeross** [IIC2233/Syllabus#630]
Hola,
Me gustaría si por favor revisaran una relación que existe entre la velocidad del bomberman y la cantidad de pixeles en el mapa de juego, en el sentido de que, si la cantidad de pixeles no es un múltiplo de la velocidad, todo tiende a descuadrarse y a bloquear movimientos permitidos en primera instancia.

En ese sentido, el parámetro vel_movimiento dependería de n_pixeles así como también los poderes de velocidad y más velocidad.

De antemano gracias!

**Comment by jmwielandt** [comment]
Según yo el parámetro vel_movimiento y n_pixeles son el mismo (VEL_MOVIMIENTO)
:/

**Comment by clementeross** [comment]
Un ejemplo para que se entienda mejor:
n_pixeles = 150 -> posición de la esquina superior izquierda = (0 , 0), posición de la esquina inferior derecha = (150 , 150).
Así, el largo y el ancho de las paredes es 10.
Si vel_movimiento = 9 (del cual 150 NO es un múltiplo), la posición de las paredes no permitiría al bomberman pasar entre medio de ellas, ya que, con esa velocidad no podría alcanzar la posición necesaria para avanzar por el espacio entre las paredes. En cambio, si vel_movimiento = 10, sí podría alcanzar la posición para moverse de buena forma.

**Comment by ptflores1** [comment]
Hola !
@clementeross debes ser capaz de manejar esos casos "especiales" de manera que no se bloqueen movimientos permitidos como tu lo dices.
@jmwielandt no son lo mismo, `VEL_MOVIMIENTO` hace referencia a cuantos pixeles se mueve el personaje y `N`es el tamaño de la grilla (cuadro, matriz) donde se movera el personaje
Saludos!

**Comment by jmwielandt** [comment]
@ptflores1 puedo setear ```N``` como el lado de un tile del mapa? El tamaño de la grilla completa no me sirve de nada (literal), pero el tamaño del tile sí :/

**Comment by ptflores1** [comment]
@jmwielandt `N`debe ser lo que se pide en el enunciado, te recomiendo calcular el tamaño de un tile (que lo entiendo como un cuadradito del mapa) en funcion de `N`
