### ISSUE TITLE
Retornar otro método: Diagrama de clases

### ISSUE THREAD

**Issue by barbarafcp** [IIC2233/syllabus#630]
Holiii, si dentro de una función retorno dos métodos distintos o salgo del programa dependiendo de la condición que se cumpla, como represento eso en el diagrama?

**Comment by barbarafcp** [comment]
Ah y otra duda jajajja
si yo llamo a una función en el __init__
por ejemplo
def __init__(self):
      self.comenzar_partida()
esa función le debo poner en el diagrama? y si es asi, como?

**Comment by ignacio-urrutia** [comment]
Hola @barbarafcp, con respecto a la primera pregunta, la idea es que siempre retornes el mismo tipo de elementos de un método, sugiero que arregles el código para que sea de esa manera. Con respecto a la segunda pregunta, en el diagrama debes incluir a todos los métodos de la clase, por lo tanto si debes incluir el método de comenzar partida.

Espero haberte ayudado y mucho éxito con la tarea :D
