### ISSUE TITLE
Duda enunciado: Ecualizar

### ISSUE THREAD

**Issue by Jaluco** [IIC2233/Syllabus#630]
Cuando dicen que el ultimo paso se repite n veces se refieren a que hay que aplicar la formula a todos los samples de data n veces? Quiero decir, que termino de pasar por todos los samples, y tengo que volver a empezar hasta lograr n veces?

**Comment by Jaluco** [comment]
Y tambien de lo mismo, como es eso de dividir los samples por 2? hay que pasarlos a numero primero?

**Comment by acrojas2** [comment]
Lo que yo hice fue aplicar la formula directo en los canales ya separados. Creo que no tiene sentido volver a separarlos por samples porque te quedarías con el mismo arregle de bytes en el sentido de que siempre el byte1 y el byte2 serán siempre el primer sample del canal1 y el byte3 y byte4 siempre serán el primer sample del canal2 y así sucesivamente... 
Saludos!

**Comment by Jaluco** [comment]
@acrojas2  y como aplicas la formula tu? yo paso todo a ints para poder dividir, no se me ocurre como mas lo podria hacer

**Comment by DiegoAndai** [comment]
Hola! #619 no resuelve tu duda? (Punto 3)

**Comment by Jaluco** [comment]
@DiegoAndai En parte, aun no entiendo como aplicar la formula, lo intente con transformar los samples a int y sumarlos y dividir por dos, pero el archivo resultante no suena nada. Es asi como se tiene que aplicar?

**Comment by DiegoAndai** [comment]
@Jaluco como transformaste cada sample a int? Tomaste en cuenta el endianness y la forma de representación utilizada en WAV? Tienes que tomar en cuenta que no todas las representaciones binarias significan lo mismo, [esta guía](http://soundfile.sapp.org/doc/WaveFormat/) te puede ser útil, para averiguar cómo se codifican, recuerda que los simples son de 16 bits.
