### ISSUE TITLE
FileNotFoundError con archivo de la ayudantía

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#630]
Hola, al completar la actividad de la ayudantía 8 me sale un error. Me sale que el archivo que se intenta leer no existe, pero debería existir ya que mi el código está en la misma carpeta donde se encuentran estos archivos.
Cómo puedo solucionarlo¿?
![error ayu8](https://user-images.githubusercontent.com/59337116/81208015-78a57180-8f9c-11ea-901c-b15e5ad71cd4.PNG)

**Comment by igbasly** [comment]
Hola @Camila-sty 
Por lo que alcanzó a ver estás usando VSCode para ejecutar tu actividad, tu error se puede deber a que en el editor abriste una carpeta superior a la carpeta de la actividad. 
Ej: Abriste la carpeta `Ayudantías` que a su vez contiene a `AY06`.
Como el editor abrió y tiene por raíz `Ayudantías`, al ejecutar un archivo, lo hará con el directorio en esa carpeta y todo será en relación a esta, por lo tanto, al ocupar un path relativo como `/archivo.ext` el editor asumirá que se refieren a `Ayudantías/archivo.ext` ya que esa era su referencia.
Para solucionarlo puedes abrir directamente la carpeta en el editor y luego ejecutar tu programa, siguiendo en la barra superior del editor:
`Archvios` -> `Abrir...` -> Seleccionas la carpeta `AY06`

O en la consola donde te apareció en el error puedes ocupar el comando `cd` *(change directory)* para cambiarte de directorio hasta la carpeta:
`cd ruta_hasta_AY06`
Y luego ejecutar tu programa. Con el ejemplo que llevaba, si tenías abierta la carpeta `Ayudantías`, entonces solo se necesitaba `cd AY06`.

Con cualquiera de esos métodos deberías poder ejecutar bien tu archivo. 
Por favor coméntanos cualquier problema que surja. Saludos ✌️
