### ISSUE TITLE
tamaño enemigos

### ISSUE THREAD

**Issue by cfernandez9** [IIC2233/Syllabus#630]
¡Hola! dependiendo de la etapa del juego los enemigos aparecen de determinado tamaño, pero luego estos crecen o se mantienen del mismo tamaño todo el juego?

**Comment by sebacruzd** [comment]
Los que ya aparecieron no deben cambiar de tamaño, ya que no comen.

Saludos!

**Comment by cfernandez9** [comment]
gracias!!!
