### ISSUE TITLE
Fallo filtro dibujo/Uso de pngcheck

### ISSUE THREAD

**Issue by felipecs13** [IIC2233/syllabus#630]
Hola, hice un archivo filtro_dibujo.py con la funcion con todos los pasos correspondientes para realizar el filtro dibujo pero no se logra visualizar la imagen, en una issue anterior alguien recomendó usar pngcheck (http://www.libpng.org/pub/png/apps/pngcheck.html) para revisar el png, pero no entiendo como utilizarlo. ¿Alguna idea de como se instala o de que puede estar pasando a mi codigo?

**Comment by csantiagopaz** [comment]
Tengo la misma duda, subi mi código al repositorio, si algun ayudante puede ver lo que esta malo porfa
