### ISSUE TITLE
Duda sobre parámetros

### ISSUE THREAD

**Issue by Raibruh** [IIC2233/syllabus#630]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
¡Hola! ¿Puedo separar los parámetros en dos archivos, uno para los parámetros que tengan que ver con el funcionamiento del juego y otro para los que tengan que ver con la interfaz? Esto para tener la tarea más ordenada. ¿O simplemente dejo todos en un solo parametros.py a pesar de la cantidad de líneas?

**Comment by JadrinaDA** [comment]
Hola! Te recomiendo no separar los archivos en vez uedes definir varios parámetros en una línea para acortar el que ya tienes (Ej PARAMETRO1, PARAMETRO2 = 10, 20). Buena suerte!
