### ISSUE TITLE
commit a revisar

### ISSUE THREAD

**Issue by BelenMadariaga** [IIC2233/syllabus#630]
Hola! 
sé que en domingo no se contestan dudas, pero me preocupa un poco que aun no me han abierto la issue con el commit a revisar y quiero ver si es el correcto y todo, para asegurarme

**Comment by entamburini** [comment]
Hola Belén,

Sufrí un imprevisto, por eso no había podido recolectar los commits. Dentro de los próximos minutos debería aparecerte pronto (en cosa de minutos desde que estoy comentándote esta issue) 

Perdón por la demora :c
