### ISSUE TITLE
WinError10061

### ISSUE THREAD

**Issue by JoseHerreros** [IIC2233/Syllabus#631]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/Syllabus/issues/421).
* [ ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/420)).
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

Este error no me esta dejando avanzar con mi tarea he probado con el ejemplo que usaron en la ayudantía 8 de resumen_servidor y resumen_cliente, lo que ocurre es que primero corro servidor y después en otra terminal corro cliente y me sale este error.

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by IsidoraGuinez** [comment]
Hola , este error puede ser porque tu servidor no esta inicializado correctamente o la configuración de puerto o IP están mal configuradas.
Te recomiendo agregar prints como "Servidor escuchando" y cosas así para identificar en que parte del programa esta el error

**Comment by JoseHerreros** [comment]
> Hola , este error puede ser porque tu servidor no esta inicializado correctamente o la configuración de puerto o IP están mal configuradas. Te recomiendo agregar prints como "Servidor escuchando" y cosas así para identificar en que parte del programa esta el error

Muchas gracias por la respuesta, pero el error era porque cerraba la terminal del servidor y al hacer eso el puerto dejaba de escucharse.

**Comment by IsidoraGuinez** [comment]
Buenisima , recuerda que el servidor siempre debe estar escuchando :)
