### ISSUE TITLE
Problema QSound con wav filtrada

### ISSUE THREAD

**Issue by josemlira** [IIC2233/Syllabus#631]
Hola! al momento de querer reproducir una canción con el filtro aplicado, QSound no me la reproduce. El archivo no está corrupto y el reproductor de mi computador sí me lo reproduce.

**Comment by arturodelreal** [comment]
Hola, debes tener un error en el header de tu archivo, para que QSound lo reproduzca el archivo no debe tener ningún tipo de error, en cambio el reproductor de tu computador es un poco más inteligente y puede arreglar errores pequeños del header, te recomiendo revisar cada parámetro del header y ver que todo coincida con lo que debiese ser.
Saludos!

**Comment by josemlira** [comment]
Sí, era eso jaja. Muchas Gracias!!
