### ISSUE TITLE
Diccionario bonus emojis

### ISSUE THREAD

**Issue by nbnavarro** [IIC2233/syllabus#631]
Hola,

El diccionario de emojis debe ser de la forma `diccionario = {":eyes:": "U+1F440"}` ?
o podría ser de la forma `diccionario = {":eyes:": "\U0001F440"}`?

Muchas gracias de antemano

**Comment by gatochico** [comment]
Hola! Queda a tu criterio como sea el formato a añadir un emoji al diccionario, siempre y cuando menciones en tu README como agregar emojis (cual de las formas de arriba usaste) y funcione, por supuesto. Saludos!

**Comment by jotanavarrete** [comment]
¡Hola!
Por lo que he buscado, el emoji en sí mismo, por ejemplo 👀, ya viene en formato unicode. ¿En ese caso el diccionario podría quedar de la forma `diccionario = {"eyes": "`:eyes:`"}` y al leer el diccionario con la llave `"eyes"` entregue el *string* ":eyes:" que será desplegado en el chat?

**Comment by gatochico** [comment]
Sip! :tada:
