### ISSUE TITLE
Actividad Propuesta

### ISSUE THREAD

**Issue by margavicunas** [IIC2233/syllabus#631]
Holaa, una pregunta muy chiquitita. La actividad propuesta la guardamos en la carpeta AP00 de nuestro repositorio o creamos la carpeta AP01? :eyes:

**Comment by Drpinto1** [comment]
¡Hola @margavicunas!

La idea es que creen la carpeta AP01, pero como esta actividad no tiene nota ni puntaje de formativa, no hay problema si no subes la solución o si la subes en otra carpeta (mientras no sea la carpeta de otra evaluación)

¡Saludos!
