### ISSUE TITLE
 Issue de dudas AC11: Recuperativa

### ISSUE THREAD

**Issue by fdoflorenzano** [IIC2233/syllabus#631]
Esta *issue* irá acumulando las dudas junto con sus respuestas correspondientes que vayan surgiendo durante la elaboración de la AC11. De tener una duda, debes comentarla en esta *issue* y una vez respondida se actualizará este contenido.

**RECUERDEN: Intenten ser descriptivos y específicos con sus dudas y errores, así se podrá atender más fácilmente la duda. Si les lanza un error inesperado, indiquen cual error. Si algo nos les funciona, expliquen el porque se siente así.**

**Sean cuidadosos y no compartan código por este medio, ya que podrían llevar a plagio en su evaluación. Ante la duda, suban su código a su repositorio para que el equipo docente tenga la opción de revisarlo remotamente.**

## Dudas generales:

- > ¿Cuántas partes debo entregar?

A lo más tres partes distintas de la AC. Como cada una vale dos puntos, menos de eso considerará nota máxima menor a 7. Si se entrega más de eso, se elegirán aleatoriamente cuales a considerarán para tu nota.

- > ¿Cómo entrego lo que hice en mi repositorio?

Las instrucciones de esto se detallan en el enunciado.

- > ¿Qué se entrega en el *commit* con mi progreso? ¿Todo?

No, solo es necesario entregar los archivos de extensión `.py` que se pide modificar.

- > ¿Se puede reutilizar el código encontrado en los ejemplos del material? 

Sí, se puede. Siempre tienen ese código de referencia para su uso durante las AC y Tareas.

- > Me equivoqué y subí todas las carpetas a mi repositorio. ¿Cómo elimino las que no deseo entregar?

Eliminando las carpetas y subiendo ese cambio utilizando Git. Cuando hacemos la secuencia `git add`, `git commit` y `git push`, lo que hacemos es registrar y subir **cambios** realizados en tu repositorio. De esa forma, **eliminar** archivos también es un cambio que se puede actualizar mediante Git. Puedes eliminar manualmente las carpetas, y luego agregar esos cambios con Git para sincronizarlo con GitHub. Si ejecutas `git status` después de eliminar las carpetas, verás un registro de esos cambios, similar a cuando agregar un archivo o lo modificas.

## Parte 1: Iterables:

- > Las líneas traen un caracter de salto de línea`'\n'`, ¿deberían aparecer y deben manejarse?

Sí, deben aparecer y deben manejarse para extraer los datos. Aparecen debido a que son el resultado de leer directamente el contenido del archivo como líneas.

- > ¿Se puede hacer esta parte solo utilizando estructuras por comprensión? ¿Sin usar necesariamente `map`, `filter` y `reduce`?

Sí, es valido. Definir las funciones usando estructuras por comprensión o mediante `map`, `filter` y `reduce` son formas válidas de realizarlo.

## Parte 3: Excepciones:

- > ¿Se puede modificar el método `__init__` de la clase `Bugterpie`? ¿Debe recibir algo?

Sí, se puede modificar el método. El enunciado especifica qué recibe y debe hacer.

- > ¿Es necesario usar `@static_method` para resolverla? ¿Cómo uso atributos de instancia y de clase en ese contexto?

Se entrega con `@static_method` porque en este contexto es suficiente. Este decorado delimita métodos dentro de una clase que no son necesariamente particulares a una instancia, por lo que el argumento `self` no es necesario. Lo pueden llamar instancias de la clase (`self.metodo()`), o incluso se puede llamar como una función que está dentro de la clase `Clase.metodo()`. Los atributos de instancia y de clase se comportan similar. Instancias pueden acceder a atributos de instancia y de clase mediante el `self`, pero los atributos de clase también pueden accederse mediante el nombre de la clase: `Clase.atributo_de_clase`.

- > Me lanza un error UnicodeEncodeError al intentar imprimir el nombre de un PROGRÁMON. ¿Qué puedo hacer?

Puede ser complicado arreglar eso ya que no necesariamente es un error de tu código, si no que del ambiente donde se ejecuta tu código. Para hacerlo simple, pueden eliminar de los archivos los caracteres especiales que producen el error para seguir avanzando, no es tan relevante para esa parte de la AC.

## Parte 4: Estructuras nodales I:

- > ¿Puedo asumir que se usan siempre los mismos PROGRÁMON del ejemplo para la construcción del árbol?

No, la solución debe ser general y no ajustarse ni a los datos específicos de ejemplo ni a la cantidad de ellos. Solo se puede esperar que se carguen datos de la misma forma de JSON, pero podrían generarse árboles más grandes o más chicos, dependiendo de los datos.

- > ¿Se pueden agregar métodos recursivos para resolver partes de lo pedido?

Sí, pueden agregar método auxiliares recursivos si les es más fácil. No es la única forma de hacerlo, se puede solucionar iterativamente, pero es válido.

- > ¿La ruta que retorna `ruta_programon` debe incluir el número del nodo que se busca?

Sí, se incluye.

-> ¿La ruta pedida puede incluir nodos que recorrí en otros caminos o solo debe incluir la ruta más corta?

La intención era que retornara la ruta más corta desde la raíz. Lamentablemente, queda medio ambiguo en la descripción de la función, por lo que se acepta también retorna la lista de nodos visitados.

## Parte 6: I/O, serialización y RegEx:

- Hubo un error de enunciado por un percance, pero ya se actualizó este en `syllabus`. Son tres las funciones a realizar, no dos.

- > Al pasar a binario me retorna siempre `'0b'` al comienzo. ¿No deberían ser solo unos y ceros?

Es normal, la [documentación](https://docs.python.org/3/library/functions.html#bin) de la función dice que le agrega ese prefijo. Simplemente se puede eliminar para obtener el *string* del binario buscado.

- > No hay un archivo `robados.poken`, pero si un `stolen.poken`. ¿Se refiere a ese el enunciado?

Sí, hubo un error de consistencia de nombres. Ese es el archivo al que se refiere el enunciado.

- > ¿Cómo cargo los datos serializados de la segunda parte?

Como se explica, ambas funciones desean extraer una lista de instancias de `Programon` al programa. La primera fue serializada con `json`, y otra con `pickle`. En los contenidos del curso se explica como se puede personalizar el cargado de estos dos métodos. Uno es específico para `json`, y otro específico para `pickle`.

**Comment by catalina-ramirez** [comment]
No hay errores en el archivo magnezone.pkmn de la parte 6?  Trato de leerlo, pero hay algunas partes que no me resulta leerlo.

**Comment by fdoflorenzano** [comment]
Hola @catalina-ramirez, ¿podrías ser más específica con que no te resulta leerlo? Recuerda que se debe leer como *bytes* y manejar como *bytes*, por lo que no veo porque no serías capaz de abrirlo y leerlo en tu programa.

**Comment by catalina-ramirez** [comment]
Hola! @fdoflorenzano lo leo como bytes y entre medio me salen signos de interrogación que no funciona decodificar.

**Comment by fdoflorenzano** [comment]
@catalina-ramirez Es difícil entender sin más detalles. Depende de como estés decodificando, y los valores que estés encontrando. Si sigues el algoritmo indicado, no deberían haber problemas. Si subes tu código a tu repositorio se puede revisar que ocurre.

**Comment by FelipeA7** [comment]
> Hola! @fdoflorenzano lo leo como bytes y entre medio me salen signos de interrogación que no funciona decodificar.

Tengo la misma duda, al leer las líneas del archivo me sale lo siguiente (estos son los primeros carácteres):  b'00330?303\x0c0\xc30\xff\x0c\x00?3?' 
No entiendo bien que significan los "?"

**Comment by catalina-ramirez** [comment]
@fdoflorenzano  la acabo de subir al repositorio!

**Comment by Juan379** [comment]
Hola! Creo que hay un problema en la parte 6 del enunciado. En la primera sección de esta parte no hay problema (la de los números binarios), sin embargo, en la segunda sección de serialización el enunciado creo que no incluye especificaciones para todas las funciones que hay que rellenar y hay un pequeño error en la parte de "Requerimientos" donde se repite dos veces la misma función.

**Comment by fdoflorenzano** [comment]
@Juan379 Toda la razón, hubo un problema con una sección comentada en esa parte. Faltó la especificación de una función que estaba en los archivos. Se acaba de subir una actualización del enunciado. Perdonen la molestia que pudo significar esto.

**Comment by fdoflorenzano** [comment]
@catalina-ramirez @FelipeA7 
Estimados, recuerden que al tratar con *bytes*, esos son objetos que pueden tomar 256 valores distintos. Cuando hacen `print` de ellos o lo intentan abrir con su editor de texto, muchas veces verán caracteres normales, otros raros y tal vez signos de interrogación. Esos que ven no son los valores de los *bytes*, son interpretaciones en *string* que `print` o el editor de texto genera para leerlos mejor. Para hacer esa interpretación, generalmente se usa ASCII para interpretarlos, pero este no tiene suficientes casos para cubrir los 256 valores, por lo que puede poner un signo de interrogación para la vista de usuario. Similarmente, al usar `decode` directamente en algo así, si el *byte* no tiene correspondencia con el *encoding* predeterminado (ASCII probablemente), lanzará un error. Esto siempre ha sido así manejando *bytes*.

Ahora, ojo que en el enunciado nunca se pide (en `Binaria.py`) decodificar directamente desde *bytes* a *string*. Se pide pasar a binario por el valor numérico, luego trabajar eso y luego volver a valor numérico para encontrar un *string*.

**Comment by mgbriones** [comment]
Hola tengo un problema parecido en la parte 6, al pasar los bites leidos a binario aparecen unas b´s:
0b110000 y 0b110011 por ejemplo, estos no deberían ser solo unos y ceros??

**Comment by fdoflorenzano** [comment]
@mgbriones el `0b` siempre se retorna al comienzo como resultado de esa función para clarificar que es un número binario. Solo debes eliminar esa parte y el resto del *string* es lo que necesitas.

**Comment by mgbriones** [comment]
toda la razón, gracias!

**Comment by catalina-ramirez** [comment]
Una pregunta de la parte 3, necesariamente la función "imprimir_bugterpies_atrapados" de la clase Bugterpie debe ser staticmethod???

**Comment by Juan379** [comment]
Hola! No entiendo bien el proceso que hay que hacer en la parte de deserializar de json en la parte 6. Cuando hago pickle.load(archivo) que es lo que obtengo? Una lista la cual puedo imprimir y revisar para ver que tiene adentro? Cuando quiero imprimirla no me deja.

**Comment by fdoflorenzano** [comment]
@catalina-ramirez 
Supongo no es completamente necesario, pero tiene la gracia que se puede llamar sin tener que instanciar una excepción. Fíjate que en `main.py` ya se llama a ese método al final, para que imprima el total de *bugterpies* encontrados.

**Comment by fdoflorenzano** [comment]
@Juan379 
¿JSON o `pickle`? Ojo que mezclaste ambos en tu pregunta. De todas formas, ambos casos se deserializa una lista de `Programon`, solo que cambia la forma. Uno mediante JSON y otro mediante `pickle`. Cada uno tiene una forma específica para personalizar el cargado que puedes encontrar en los contenidos.

**Comment by Juan379** [comment]
Hola si! Mi pregunta va a que para poder hacer la parte de JSON no necesité en ningún momento utilizar la funcion hook para pesonalizar el cargado. Sin embargo, supongo que para poder deserializar la lista que me entrega el archivo de Pickle si es necesario personalizar el cargado.

**Comment by fdoflorenzano** [comment]
@Juan379 
Como dije, cada método tiene su forma de personalizar el cargado. Siempre hemos utilizado la misma y está en los contenidos.

**Comment by Baelfire18** [comment]
En la 3, la de excpeciones como es que se llega al atributo que cuenta los bugertipes si es un staticmethot? Eso anula el self

**Comment by fdoflorenzano** [comment]
@Baelfire18 Si es un atributo de instancia, solo se puede llegar mediante el `self`. Pero como el contador debiera dar el conteo general de apariciones, sería raro que fuera un atributo de instancia el que lo maneje.

**Comment by Baelfire18** [comment]
Profesor, como se accede a un atributo de clase desde un staticmethot?

**Comment by fdoflorenzano** [comment]
@Baelfire18 Con el nombre de la clase. `Clase.atributo_de_clase`

**Comment by Juan379** [comment]
Hola profe nuevamente. Es necesario en la parte 6 utilizar personalizaciones en la serializacion? Lo pregunto ya que ya termine todo y realize la parte de JSON sin utilizar el hook, simplemente lo hice dentro de la misma funcion obtener_programons_json todo el desarollo necesario. (en la parte de pickle si use personalizacion son setstate). Me bajaran nota por no hacerlo si aun asi cumple con toda la funcionalidad?

**Comment by JosefaPaz** [comment]
Hola! En la parte 3, al leer el nombre del prográmon 29 no lo lee ya que tiene un carácter especial, qué se puede hacer? 

Me sale el siguiente error:

UnicodeEncodeError: 'charmap' codec can't encode character '\u2642' in position 38: character maps to <undefined>

**Comment by mmrodriguez5** [comment]
-- DUDA PARTE 5 --
No entiendo que es lo que tiene que hacer movimiento_posible(), si me pueden explicar mejor lo que debe hacer esta función se los agradecería mucho. 
Saludos

**Comment by fdoflorenzano** [comment]
@Juan379 No se especifica en enunciado que es necesario usar *hook*, es solo una forma de hacerlo, así que no habría descuento. De todas formas, lo que hiciste para procesar la información en `obtener_programons_json` hubiera sido equivalente a lo que se esperaría realizaras en el *hook*. Hubiera quedado más ordenado y legible solamente usando el *hook* 😉.

**Comment by fdoflorenzano** [comment]
> Hola! En la parte 3, al leer el nombre del prográmon 29 no lo lee ya que tiene un carácter especial, qué se puede hacer?
> 
> Me sale el siguiente error:
> 
> UnicodeEncodeError: 'charmap' codec can't encode character '\u2642' in position 38: character maps to

@JosefaPaz si es un error por imprimir un caracter especial, no te preocupes. Puedes eliminar del archivo momentáneamente el caracter para que puedas imprimir sin problemas. El problema de fondo puede que sea el ambiente donde lo ejecutas, y que no puede mostrar ese caracter, e intentar solucionarlo puede ser algo engorroso para efectos de la actividad :)

**Comment by fdoflorenzano** [comment]
> -- DUDA PARTE 5 --
> No entiendo que es lo que tiene que hacer movimiento_posible(), si me pueden explicar mejor lo que debe hacer esta función se los agradecería mucho.
> Saludos

@mmrodriguez5 La idea es que la función declare si es posible enseñarle a cierto PROGRÁMON cierto movimiento bajo las reglas que se explican antes. Es decir, ver si es posible encontrar una cadena de conexiones entre PROGRÁMON que pueden aprender el movimiento y que además pueden cruzarse tal que logre llegar al PROGRÁMON indicado.

**Comment by ceosorio** [comment]
- Parte 1-
En la primera función, las lineas que me entregan terminan en '\n'.
'499,Pignite,Fuego,Lucha,90,93,55,70,55,55\n'

Debo manejar esto o no se supone que debiese salir?

**Comment by fdoflorenzano** [comment]
>     * Parte 1-
>       En la primera función, las lineas que me entregan terminan en '\n'.
>       '499,Pignite,Fuego,Lucha,90,93,55,70,55,55\n'
> 
> 
> Debo manejar esto o no se supone que debiese salir?

@ceosorio Sí se debe manejar. Como son directamente el resultado de leer las líneas del archivo, traen el salto de línea.

**Comment by ignacio-urrutia** [comment]
Hola, en la parte 4, se puede crear una función para utilizar recursividad en la búsqueda por los nodos?

**Comment by fdoflorenzano** [comment]
> Hola, en la parte 4, se puede crear una función para utilizar recursividad en la búsqueda por los nodos?

@ignacio-urrutia Sí, puedes crear una función auxiliar recursiva para resolver la búsqueda si te es más fácil. No es la única forma, pero puedes.

**Comment by javier-ICO** [comment]
¿Se puede agregar un atributo al main.py de la actividad 3?, en su defecto ¿Se puede hacer que el método "remolinombre" no sea estático?
PD. Si leí lo que está más arriba pero no se donde "guardar" el numero de Bugterpies encontrados.

**Comment by fdoflorenzano** [comment]
> ¿Se puede agregar un atributo al main.py de la actividad 3?, en su defecto ¿Se puede hacer que el método "remolinombre" no sea estático?
> PD. Si leí lo que está más arriba pero no se donde "guardar" el numero de Bugterpies encontrados.

No hay clases en `main.py`, ¿dónde agregarías un atributo?
No debería ser necesario que el método `remolinombre` no sea estático.

PD: Si te referías a `bugterpie.py`, sí se pueden agregar atributos. Se dejó un comentario en un lugar muy particular por la misma razón.

**Comment by sebacarrasco** [comment]
Hola, en la parte 4 en la función encontrar_ruta se debe agregar a la ruta el número del mismo nodo que estamos buscando? O es hasta antes de ese nodo?

**Comment by fdoflorenzano** [comment]
> Hola, en la parte 4 en la función encontrar_ruta se debe agregar a la ruta el número del mismo nodo que estamos buscando? O es hasta antes de ese nodo?

Sí, la ruta incluye el nodo que se busca.

**Comment by sebacarrasco** [comment]
Hola de nuevo, no me di cuenta que subí las 6 carpetas en vez de solo tres y tengo entendido que si las borro normalmente no se borrarán de mi repositorio, ¿Cómo lo arreglo?

**Comment by DiegoPibe** [comment]
holaa, en la Parte 1 de Iterables, la ultima función "repr_lista(lista)" no entiendo que debo hacer, en el ejemplo del enunciado lo hacen con una lista de strings, pero en los prints del archivo que debemos desarrollar lo hacen con una lista de tuplas. No entiendo :(.

De antemano, agradezco una pista.

**Comment by fdoflorenzano** [comment]
> Hola de nuevo, no me di cuenta que subí las 6 carpetas en vez de solo tres y tengo entendido que si las borro normalmente no se borrarán de mi repositorio, ¿Cómo lo arreglo?

Subiendo ese cambio utilizando Git. Cuando hacemos la secuencia `git add`, `git commit` y `git push`, lo que hacemos es registrar y subir **cambios** realizados en tu repositorio.

De esa forma, **eliminar** archivos también es un cambio que se puede actualizar mediante Git. Elimina manualmente las carpetas, y luego agrega esos cambios con Git para sincronizarlo con GitHub. Si ejecutas `git status` después de eliminar las carpetas, verás un registro de esos cambios, similar a cuando agregar un archivo o lo modificas.

**Comment by fdoflorenzano** [comment]
> holaa, en la Parte 1 de Iterables, la ultima función "repr_lista(lista)" no entiendo que debo hacer, en el ejemplo del enunciado lo hacen con una lista de strings, pero en los prints del archivo que debemos desarrollar lo hacen con una lista de tuplas. No entiendo :(.
> 
> De antemano, agradezco una pista.

La idea es que retorne un *string* con saltos de línea que enumere el contenido de la lista que se le entregue usando índices desde el 1. Si tienes una lista de tuplas entonces, debería esperarse algo como:

```python
repr_lista([(1, 2), (2, 3), (4, "hola")])
```
Retorna:
```python
'''
1. (1, 2)\n
2. (2, 3)\n
3. (4, "hola")
'''
```
Ojo que el `"\n"` es solo para efectos de que el *string* debe contener un salto de línea, cuando se imprime el resultado, ese caracter no aparece así (ya que es un salto de línea). El enunciado indica que es para una lista genérica, así que basta con convertir los elementos de la lista con `str`, o un método equivalente. No debes preocuparte de que al ser tuplas se vea "más bonito".

**Comment by gvcespedes** [comment]
Hola! en la parte 4 puedo asumir que solo se usarán los programones que aparecen en json o tengo que hacerlo para una lista infinita de programones?

**Comment by fdoflorenzano** [comment]
> Hola! en la parte 4 puedo asumir que solo se usarán los programones que aparecen en json o tengo que hacerlo para una lista infinita de programones?

No entiendo bien a qué te refieres. No se probará una lista infinita, ya que no hay tantos PROGRÁMON, pero tampoco puedes ajustar tu solución solo para esos datos específicos. Por ejemplo, podrían cargarse en un orden distinto, o agregarse nuevos programon con nuevos datos. Debes implementar una solución general, debe servir con cualquier archivo JSON con la forma que se específica.

**Comment by mariajesusbraun** [comment]
Parte 1
Hola! No se por qué, all tratar de leer el archivo `programon.txt`, me sale el siguiente error:

`    with open(ruta, 'rt', encoding='utf-8') as archivo:
FileNotFoundError: [Errno 2] No such file or directory: 'programon.txt'`

Pero claramente el archivo sí existe.

**Comment by fdoflorenzano** [comment]
> Parte 1
> Hola! No se por qué, al tratar de leer el archivo `programon.txt`, me sale el siguiente error:
> 
> ` with open(ruta, 'rt', encoding='utf-8') as archivo: FileNotFoundError: [Errno 2] No such file or directory: 'programon.txt'`
> 
> Pero claramente el archivo sí existe.

Hola @mariajesusbraun, era algo tarde para responder. ¿Pudiste solucionarlo?
Si no, se me ocurren dos posibles razones: 
1. el archivo no está en la misma carpeta donde está el programa en ejecución.
2. la ejecución del programa no está en la carpeta donde está el archivo.

**Comment by DiegoPibe** [comment]
- - - PARTE 6 - - -

deberiamos tener un archivo que se llame robados.pkmn pero tenemos uno que se llama stolen.pkmn o al menos yo, lo abro asi nomas ? como stolen.pkmn?.

de antemano muchas gracias.

**Comment by fdoflorenzano** [comment]
>     * * * PARTE 6 - - -
> 
> 
> deberiamos tener un archivo que se llame robados.pkmn pero tenemos uno que se llama stolen.pkmn o al menos yo, lo abro asi nomas ? como stolen.pkmn?.
> 
> de antemano muchas gracias.

Toda la razón, fue un erro de consistencia en el enunciado. Sí, ese es el archivo al que se refiere.

**Comment by MartinAracena** [comment]
Hola, queria saber si en la 1 uso solamente estructuras por comprension(ya que me gusta mucho usarlas) entonces obtendria de todas formas todo el puntaje? Ya que al final filter, reduce y map todas se puede hacer con estructuras por compresion si no me equivoco.

**Comment by fdoflorenzano** [comment]
> Hola, queria saber si en la 1 uso solamente estructuras por comprension(ya que me gusta mucho usarlas) entonces obtendria de todas formas todo el puntaje? Ya que al final filter, reduce y map todas se pueden hacer con estructuras por compresion si no me equivoco, al menos si con map y filter.

Sí, es válido hacerlo solo con estructuras por compre**n**sión. Como dices, probablemente se pueden encontrar equivalencias usando ambas formas para cualquier expresión.

**Comment by camaruri** [comment]
***Parte 4***
Hola en la parte 4 en la parte de busqueda de ruta, en el enunciado sale:
''lista en donde aparezcan los nu ́meros de los PROGRa ́MON por los cuales pasaste.''
Si en mi algoritmo de busqueda se visitan otros nodos que van por otro camino antes de llegar al nodo buscado, esta bien que sean parte de mi ruta??
Por ejemplo si estoy buscando el nodo 7 pero mi algoritmo primero va a al 23 luego al 4 luego los hijos del 23 y finalmente a los hijos del 4 donde encuentra el 7. 
En ese caso mi lista seria: [12, 4, 23, 18, 25, 1, 7]
gracias

**Comment by itplanella** [comment]
*** Parte 1 ***
Hola! en la parte 1, en la funcion obtener_caracteristica_promediose entregan los nombres de los programones y no las namedtuple, por lo que se complica bastante el obtener estos valores. 
Mi duda va enfocada a como se podria hacer ya que no estamos ingresando de ninguna forma a la funcion estos namedtuple.

**Comment by fdoflorenzano** [comment]
> ```
>  ***Parte 4***
> ```
> 
> Hola en la parte 4 en la parte de busqueda de ruta, en el enunciado sale:
> ''lista en donde aparezcan los nu ́meros de los PROGRa ́MON por los cuales pasaste.''
> Si en mi algoritmo de busqueda se visitan otros nodos que van por otro camino antes de llegar al nodo buscado, esta bien que sean parte de mi ruta??
> Por ejemplo si estoy buscando el nodo 7 pero mi algoritmo primero va a al 23 luego al 4 luego los hijos del 23 y finalmente a los hijos del 4 donde encuentra el 7.
> En ese caso mi lista seria: [12, 4, 23, 18, 25, 1, 7]
> gracias

@camaruri La verdad es que la intención de esa función era que devolviera la ruta más corta desde la raíz, no los nodos recorridos hasta encontrarle. Pero, ya que no fuimos específicos y queda medio ambiguo, también se acepta lo que indicas.

**Comment by fdoflorenzano** [comment]
> *** Parte 1 ***
> Hola! en la parte 1, en la funcion obtener_caracteristica_promediose entregan los nombres de los programones y no las namedtuple, por lo que se complica bastante el obtener estos valores.
> Mi duda va enfocada a como se podria hacer ya que no estamos ingresando de ninguna forma a la funcion estos namedtuple.

@itplanella Lo que se entrega en la función es lo que retorna tu implementación de las otras funciones, las cuales específican que se retornen PROGRÁMON, no nombres de PROGRÁMON.

**Comment by itplanella** [comment]
@fdoflorenzano oka! muchas gracias

**Comment by rgmorales1** [comment]
Parte 2:
¡Holaa!, en la parte 2 no puedo entender como el atributo de instancia 'ganador' lo puedo obtener en otra instancia de la misma clase, ¿no puedo cambiarlo por un atributo de clase?

**Comment by fdoflorenzano** [comment]
> Parte 2:
> ¡Holaa!, en la parte 2 no puedo entender como el atributo de instancia 'ganador' lo puedo obtener en otra instancia de la misma clase, ¿no puedo cambiarlo por un atributo de clase?

@rgmorales1
Hola, lo que sugieres supone un ganador general, pero cada batalla tiene un ganador que puede ser distinto, solo al final hay solo un ganador. Para acceder a un atributo de una instancia podría ser: `instancia.ganador`.

**Comment by Juan379** [comment]
En la parte 1 puedo usar algún comando de namedTuples, diccionarios, sets, etc para tratar alguna lista? Necesito remover algo de una lista y se podría hacer con reduce, sin embargo con set es mucho mas facil y eficiente.

**Comment by fdoflorenzano** [comment]
> En la parte 1 puedo usar algún comando de namedTuples, diccionarios, sets, etc para tratar alguna lista? Necesito remover algo de una lista y se podría hacer con reduce, sin embargo con set es mucho mas facil y eficiente.

@Juan379 Sí, claro. Mientras no uses `for` para iterar, todo bien.

**Comment by emilianomm** [comment]
DUDA PARTE 5
Hola, me queda una duda con _movimiento_posible()_, ¿ De donde se supone que saco las lista de crianza para verificar si son validas?

**Comment by fdoflorenzano** [comment]
> DUDA PARTE 5
> Hola, me queda una duda con _movimiento_posible()_, ¿ De donde se supone que saco las lista de crianza para verificar si son validas?

@emilianomm Los Grupos Huevo de cada PROGRÁMON indican con quienes pueden cruzar. La idea es que en el cargado realices las referencias entre PROGRÁMON y Grupos Huevo para poder ser accedidas. Si no te basta para lo que necesitas, puedes agregar un argumento para tener el diccionario con todos los Grupos Huevo.

**Comment by Juan379** [comment]
Es necesario que el decimal entregado en la funcion del promedio del atributo sea truncada al primer decimal?

**Comment by fdoflorenzano** [comment]
> Es necesario que el decimal entregado en la funcion del promedio del atributo sea truncada al primer decimal?

@Juan379 No, no es necesario. ¡*PUSH*!
