### ISSUE TITLE
Acciones con CTRL+S y CTRL+T en mac

### ISSUE THREAD

**Issue by cristobalilabaca** [IIC2233/Syllabus#631]
Las acciones que deben ocurrir al presionar `CTRL+S` y `CTRL+T` deben ser con `ctrl` también en mac o pueden ser con la tecla `cmd`?

**Comment by sebacruzd** [comment]
Hola,

Como prefieras, pero especifícalo en tu readme.

Saludos!

**Comment by sebacruzd** [comment]
@cristobalilabaca hubo un error con la respuesta anterior. Debe ser con la tecla control.

Saludos!

**Comment by rihanuch** [comment]
@sebacruzd cuando uno presiona cmd en mac, pyqt lo interpreta como ctrl

**Comment by sebacruzd** [comment]
@rihanuch gracias por la información!

Que sea entonces con lo que PyQt5 reconozca como ctrl, para evitar problemas de corrección con los ayudantes que no tenemos Mac.

Saludos!
