### ISSUE TITLE
Duda ejemplo simulaciones 

### ISSUE THREAD

**Issue by amparostevens** [IIC2233/syllabus#631]
Hola! No entiendo muy bien el ejemplo de simulación en el cuaderno 3 de la semana 8. 
Mi duda está relacionada con los `Event`, los cuales se van modificando cuando dentro de cada clase se modifica el atributo `self.nombre_senal` a través de `set()`, pero cómo es que se altera el atributo de la otra clase siendo que en ningún momento se le llama? (es decir, no hay un llamado por ejemplo de `estudiante.nombre_senal.set()`), o eso se produce porque los atributos son un `Event` ya definido?

**Comment by fdoflorenzano** [comment]
Hola @amparostevens,

Creo entender tu pregunta, y creo que es buena. Los efectos se transmiten entre las instancias `Estudiante` y `Profe` porque si te fijas en el código de abajo, ambos reciben referencias a **las mismas instancias de eventos**. De alguna forma, ambos *threads* miran a los mismos dos objetos de eventos. Uno a veces espera que este se accione por el otro *thread*, y viceversa. 

Es más, funciona ya que están mirando a las mismas instancias. Si por ejemplo cada *thread* instancia por separado las señales que usan, no se coordinarían porque miran a objetos diferentes. Lo mismo ocurre con *locks*, se requiere que todos aquellos que se desean sincronizar utilicen la misma instancia de *lock*, no distintas. Tanto eventos como *locks* son mecanismos de sincronización de **compartir recursos**, ya que usan un recurso, u objeto, para sincronizarse.

Espero se entienda, y responda la pregunta. Cualquier cosa me dices.

Saludos.
