### ISSUE TITLE
perguntaaa

### ISSUE THREAD

**Issue by betolguin** [IIC2233/syllabus#632]
hola! me surgio una duda de ultimo minuto, para la competencia los dias 0 y 1 deben ser si o si de entrenamiento verdad??
y lo otro para el diagrama de clases se debe realizado si o si desde una paguina web o puedo hacerlo "a mano" y que quede bonito y subirlo asi??
gracias de antemanoooo!
felices fiestas :)

**Comment by amparostevens** [comment]
Hola! 
La issue #584 te puede servir. Y si, mientras esté ordenado no hay problema 😉
