### ISSUE TITLE
Duda con respecto a la Progress Bar.

### ISSUE THREAD

**Issue by rsommer1** [IIC2233/Syllabus#632]
Esta debe ser una barra que crece y luego se reinicia al llegar a la meta o puede ser un numero que se va actualizando al ser alcanzado??

**Comment by Arcoirisky** [comment]
Se pide que sea como una barra que crece y se reinicia o: (Esa es como la definición de Progress Bar c: )

**Comment by Pipelao** [comment]
En QtDesigner hay un objeto que es progress bar.
Saludos
