### ISSUE TITLE
ProgressBar para la vida actual

### ISSUE THREAD

**Issue by mjgutierrez1** [IIC2233/Syllabus#632]
Tanto el jugador principal como los enemigos deben tener una ProgressBar que indique la proporción de la vida actual respecto de la vida máxima. En el enunciado no se indica dónde se deben ubicar estas barras. ¿Cada instancia de una entidad debe tener al lado a su barra, y si la instancia se mueve su barra también se mueve junto con ella?

**Comment by tcgarrido** [comment]
Hola! Queda a tu criterio como muestras la proporción entre la vida restante y la máxima. El único requerimiento es que se entienda a qué entidad corresponde cada conjunto de datos.
