### ISSUE TITLE
Entrega atrasada Readme T03

### ISSUE THREAD

**Issue by SamWeinstein** [IIC2233/syllabus#632]
Hola, subí el readme de la T03 a mi repositorio 20 minutos tarde, debo rellenar algún formulario o algo? Pues el formulario de entrega atrasada se cerro un día antes del limite de tiempo para enviar el Readme. Gracias!

**Comment by entamburini** [comment]
Hola @SamWeinstein,

Desgraciadamente no hay posibilidad de entrega atrasada del readme. Lo que puedes hacer es subir el readme para que el ayudante tenga la guía de tu readme. Pero desgraciadamente tendrás el descuento por no entregar a tiempo el mismo :c
