### ISSUE TITLE
Problema al enviar canción: SOS

### ISSUE THREAD

**Issue by egbusch** [IIC2233/Syllabus#632]
Se que voy un poco tarde.... pero simplemente no he podido solucionar el envío de una canción desde el server al cliente. Cuando se la envío, parte rápido (como creo que debería ser) y se queda pegado sin ninguna razón. Después retoma de a pedazos muy lento y finalmente me aburro de esperar porque no puede ser que una canción se demore taaanto en enviarse.

Alguna idea de porque pasa esto ? Solo lee el archivo desde la carpeta desde el lado del servidor de a 2048 bytes y los va enviando.... el problema es que no acaba. Desde el lado del cliente va tomando esos pedazos y los va escribiendo en un archivo.

Saludos

**Comment by rrhurtado** [comment]
Hola, es difícil saber a ciencia cierta por qué ocurre el error. Puedes probar con un archivo de poco tamaño y ver que tal resulta el envío.

Además, verifica que en el lado del cliente el archivo se esté escribiendo (que el tamaño del archivo vaya subiendo), puede ser que ya haya terminado de transferirse (cuando el tamaño del archivo es igual que el original) pero el loop de trasnferencia no es cerrado correctamente y por eso queda ahí sin acabar.

**Comment by rfenzo** [comment]
No se si  se relaciona con lo que me pasó a mi, pero perdía datos por el hecho de enviarlos muy rapido desde el servidor, le puse un time.sleep(0.001) dentro del for que envía los paquetes y todo se solucionó (varios dias perdidos por eso), y al hacer esto, la transferencia se hizo muy lenta, pero lo sulucione aumentando el tamaño de los paquetes a 65kb.

**Comment by iqacevedo** [comment]
@egbusch como dice @rrhurtado intenta revisar bien que efectivamente el cliente termine el loop de transferencia una vez que se mando todo el archivo, para esto puedes probar enviar otro tipo de cosas como una lista o strings y cerciorarte de estar terminando bien ese loop. También revisa que efectivamente el servidor termine de enviar el archivo (intenta pararte en el momento justo después en que debería enviarlo, si nunca llegas probablemente tienes un loop infinito por ahí).

Cuéntanos como te va, también te puede servir la solución de @rfenzo.

Saludos !

**Comment by egbusch** [comment]
Implemente las soluciones que mencionaron y me fue bien, puedo enviar archivos sin problema (aumente los paquetes que enviaba). Sin embargo, me di cuenta de que el real problema es que mi servidor dura 34 segundos (siempre los mismo) corriendo como debería ser, pero luego se queda pegado y cada varios segundos (varia entre 5 a 30) responde y se vuelve a pegar.... hasta el infinito. Alguna razón por la que podría arrancar bien y luego pegarse ?? la carga debería ser la misma, desde el inicio se corren todos los salones en paralelo y justo ene se segundo se pega el servidor. Alguna ayuda para saber por donde empezar a buscar?

**Comment by arturodelreal** [comment]
@egbusch usas threads para enviar y recibir la información?

**Comment by egbusch** [comment]
mmm el servidor en si es un thread y cada vez que conecta un usuario los pasa a un thread que se dedica a escuchar sus mensajes. Los salones también son threads y  también reciben mensajes con un thread por cliente. Lo extraño es que aunque no conecte ningún cliente al servidor, este se queda pegado después de 30 segundos a 1 minutos. Incluso deje que lo único que hiciera el programa fuera correr el thread del servidor (sin salones) y que no escuchara a nadie... solo en un loop y se queda pegado igual. Aún lo logro encontrar la falla. 
* Los mensajes del servidor también se envían por threads.
Cualquier ayuda es bienvenida !

**Comment by arturodelreal** [comment]
En alguna parte haces envío de información a través del server?

**Comment by egbusch** [comment]
Sí, los clientes los manejo en un thread (server) que tiene un thread para escuchar a cada cliente. Cuando los clientes pasan a un salón, el server le pasa el cliente al salón (otro thread) que también genera un thread para escuchar a ese cliente. 
Lo raro es que aunque no envíe ni reciba nada del server (solo dejo corriendo el server) igual se queda pegado. De echo, aunque comente la linea para aceptar clientes y el código del server lo único que hace es quedarse pegado en un loop sin hacer nada, después de un minutos igual se pega..... :(
