### ISSUE TITLE
Readme Tarea: que hago si me falto agregar algo?

### ISSUE THREAD

**Issue by Ignacioislae** [IIC2233/syllabus#632]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

###  ¿Que hago si se me olvido poner algo en el Readme.md?

Se me olvido poner una de las librerias que importe. (from abc import ABC, abstractmethod)

¿Puedo avisarle al ayudante o algo similar?

Ignacio Isla

**Comment by Juampisaez** [comment]
Hola @Ignacioislae 
Puedes subir de igual manera tu readme a tu repositorio. Sin embargo, no te preocupes mucho, no es algo a lo que se le aplique un descuento directo.

Espero te sea de ayuda :)
