### ISSUE TITLE
Examen Hora

### ISSUE THREAD

**Issue by Arcoirisky** [IIC2233/Syllabus#633]
Si el examen es el 30 ¿A qué hora sería? Es que tengo otro el mismo día D: en el 5to y 6to módulo

**Comment by frvalenzuela** [comment]
La ayudantía para el examen será el 30 de Junio. 
El examen esta fijado para el día 4 de Julio de 08:30 a 11:30 según aparece en el calendario := https://iic2233.github.io/calendario/

**Comment by Arcoirisky** [comment]
Oooh, entre el pánico entendí nada.
Gracias <3
Pd: ¿Aún no se te corta la luz? Yo sigo sin ver nah
