### ISSUE TITLE
Video Ayudantía 06 - Threading

### ISSUE THREAD

**Issue by vobrador** [IIC2233/syllabus#633]
Holaa :) quería pedir si podrían subir el video de la ayudantía de ayer, tuve una prueba asique no pude asistir y la quería revisar para estudiar para la actividad de mañana

**Comment by entamburini** [comment]
Hola @vobrador!,

Vi que me mandaste un mail con esta misma pregunta jajaja, el vídeo se está subiendo :) pronto tendremos noticias :tada: 

Saludos! :v:

**Comment by Drpinto1** [comment]
¡Hola!

Lo primero, gracias por tu interés en las ayudantías del curso :D
Lo segundo, complementando un poco lo que dice Enzo, el video estará disponible pronto, pero el enunciado y solución ya están subidos a Syllabus, así que puedes revisar estos archivos por mientras (si es que quieres comenzar el estudio antes de que esté publicado el video)

¡Saludos!

**Comment by vobrador** [comment]
Gracias a ambos!! Sii, eso estaba haciendo :) esperaré entoncess
