### ISSUE TITLE
Herencia QObject? Es cierto?

### ISSUE THREAD

**Issue by naquiroz** [IIC2233/Syllabus#633]
Recuerdo que en la ayudantía de Interfaces Gráficas, uno de los ayudantes mencionó que es súper importante que las clases del _backend_ **deben** heredar de `QObject` para que su funcionamiento sea apropiado, pero estuve leyendo, y una de las cosas que encontré  es que las instancias de `QObject` son _thread-safe_ porque **solo pueden estar en una _thread_ a la vez** (entiendo que el concepto de _thread-safe_ no es ese, pero al poder estar en una sola thread, es implicito que es _thread-safe_) . Entonces, mi pregunta es, es necesario que hereden `QObject` realmente? Pregunto porque, que pasa si quiero hacer una clase que agrega y compone otras clases que están en otras _threads_, no me quedaría la escoba?

Eso, espero que se entienda mi pregunta.

**Comment by tomasrivera** [comment]
Creo que yo dije eso, tal como dices no es necesario que hereden de `QObject`
