### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by bvallejo1** [IIC2233/syllabus#633]
Hola, estaba creando el archivo .gitignore y me surgió la duda de que hacer con una carpeta llamada server/fotos/ en la cual se encuentran las fotos (.png) de los usuarios registrados en mi juego, esta debe ser ignorada? Además tengo un  archivo llamado server/data.json donde registro a cada uno de los jugadores, también tengo dudas sobre que hacer con el.

**Comment by KnowYourselves** [comment]
Hola  @bvallejo1!

En cuanto a lo primero, si es que esa carpeta es necesaria para el funcionamiento de tu programa, puedes subirla, pero sin ninguna foto. (Puedes ignorar todos los png dentro de ella). Otra opción es ignorarla y hacer que tu programa la cree en caso de que esta no exista.

En cuanto a lo segundo, aplica lo mismo. Si tu programa necesita que exista ese json inicialmente vacío puedes no ignorarlo. Otra opción es hacer que tu programa lo cree en caso de que no exista.

Éxito!
