### ISSUE TITLE
defaultdict(list)

### ISSUE THREAD

**Issue by conikuschel** [IIC2233/syllabus#634]
Hola! no se porque al agregar valores a un defaultdict(list) me arroja el siguiente error:
AttributeError: 'str' object has no attribute 'append'
Lo he probado fuera del programa y funciona bien, pero cuando lo pruebo se cae, subí el código a mi repo por cualquier cosa :(

**Comment by lily416** [comment]
Hola 😃 

Fijate que cuando haces:
```python
self.salas[recibido[1]] = self.sockets[client_socket]
```
estás cambiando el la lista del `defaultdict` por el valor que tienes guardan en `self.sockets[client_socket]` (asumo que es la string con el nombre de usuario o algo parecido).

Ánimo y éxito con la tarea 👋 💪

**Comment by conikuschel** [comment]
Si, si te entiendo, pero el error sale en la función unirse_sala del server, cuando conecto al segundo cliente que va a la misma sala que el primero que conecte, la que pusiste debería entrar solo cuando no existe la sala a la que entra :(

**Comment by lily416** [comment]
Fijate que el `self.salas[recibido[1]] = self.sockets[client_socket]` lo llamas en la función `manejar_comando` antes de que llames la función `crear_sala` y en dicha función **sólo** se agrega el cliente a la sala si esta no existe, pero como la creas antes de llamar la función se salta ese `if` y no se levanta el error, entonces cuando un segundo cliente intenta ingresar a la sala hace `append` a una string y se levanta el error.

Ojalá quede claro, saludos.

**Comment by conikuschel** [comment]
Sii, muchas gracias!!
