### ISSUE TITLE
Problema Qsound

### ISSUE THREAD

**Issue by chapito96** [IIC2233/Syllabus#634]
Hola, intento hacer lo que señalan  en la issue #608 para la reproducción pero no lo logro hacer funcionar.
Además googlee sobre Qsound y habian más formas de hacerlo pero ninguna me ha funcionado.

**Comment by arturodelreal** [comment]
Hola, en que clase estas intentando instanciar el objeto QSound?

**Comment by rrhurtado** [comment]
Hola, puede ser por el tema de desde donde ejecutas el código. Intenta ir paso por paso partiendo de lo más simple: desde un objeto QtMainWindow agrega un objeto Qsound con un path y luego llama a su método play().

**Comment by chapito96** [comment]
Estoy instanciando el objeto QSound como atributo de una clase QtMainWindow.
Primero hago self.sound = QSound("path",self)
Luego llamo a self.sound.play()

**Comment by maxjosecr** [comment]
Hola tengo el mismo problema, tengo una funcion para reproducir que la llamo mediante un thread y no se reproduce la cancion. Pero si la llamo desde el init si se reproduce, que puedo hacer?

**Comment by arturodelreal** [comment]
@maxjosecr tienes que enviar hacer la ejecución de la función que reproduce la canción mediante señales.
@chapito96 En que parte llamas a la función que ejecuta lo que pusiste?
Saludos

**Comment by chapito96** [comment]
@arturodelreal el cliente en su creación tiene una mainwindow en sus atributos. Luego de que el servidor le indique al cliente por una señal que reproduzca una canción, hace algo como self.mainwindow.reproducir("path").
En esa metodo de la clase mainwindow hago lo que indiqué antes.
Intenté crear el Qsound y ejecutar el play() en el __init__ de la mainwindow y funcionó sin poblemas.
Saludos

**Comment by chapito96** [comment]
Algo que intenté recién es crear la Qsound en el init y ejecutar el play() en el metodo.
Funcionó, pero de esa forma solo puedo escuchar la canción creada en el init. No entiendo por qué al intentar crear el Qsound fuera del init se generan problemas

**Comment by arturodelreal** [comment]
Tu problema es que haces self.mainwindow.reproducir('path'). Lo que deberías hacer es tener una señal que este conectada con la función reproducir de tu mainwindow, y en vez de llamar a self.mainwindow.reproducir('path') haces señal.emit(), esto debería solucionar tu problema.
Saludos

**Comment by chapito96** [comment]
Gracias @arturodelreal! 
Solucionado. Además las señales solucionaron varios problemas más!
