### ISSUE TITLE
Que es lo mas correcto con las colisiones?

### ISSUE THREAD

**Issue by naquiroz** [IIC2233/Syllabus#634]
Estoy un poco acomplejado con el tema de las colisiones, dado que nose cuando verificarlas. Entonces, mi pregunta es, que es mas correcto (o mas bien, como se hacen en general)?

1. Se verifican antes del movimiento, o despues del movimiento?
2. Interactuan con el mapa a traves de señales o composición pasando funciones (para evitar implementaciones circulares)?

**Comment by Sforrego** [comment]
1. Queda al criterio de cada uno.
2. Lo ideal es interactuar a través de señales.

**Comment by mfanselmo1** [comment]
Hola! Estuve investigando un poco mas de tu pregunta 1, y no encontré que hiciera mucha diferencia. En general va a ser mejor lo que se acomode a tu forma de programar el problema. 
https://stackoverflow.com/questions/27662374/must-collisions-be-detected-before-or-after-moving-the-object

**Comment by ljrodriguez1** [comment]
Profundizando sobre este tema, no entiendo a qué se refiere con que las colisiones interactúen sobre el mapa usando señales. A modo de ejemplo si yo quiero modelar un personaje y que este colisiones con un objeto para mí los más simple sería:
1- Qué el personaje conozca la posición del objeto y que no se le este permitido estar en esa posición. Pero aquí no ocupo señales.
2- que el bloque sea un thread Al cual se le envié una señal si se mueve el personaje y revise que este no se mueva a su posición. Estaría ocupando señales, pero al haber muchos bloques le enviaría una señal a cada bloque y sería poco eficiente (se me ocurren formas de solucionarlo pero quizás sería compartir mucha información) 
Mi duda es está bien pensar los bloques como threads? En especial los que se pueden romper. Y si es que la manera 1 de detectar colisiones está mal al no ocupar señales y por ende no separar al jugador de los bloques

**Comment by mfanselmo1** [comment]
Hola!
Primero, las señales en general son para darle mas estabilidad a tu programa, si ves en el material, se explica que el uso de señales y matar threads que ya no existen es lo mejor.
Ahora es tu tarea ver si funciona de la manera en que lo estas haciendo, ve si estas matando a tu computador al hacerlo o no. 
En general, lo más correcto o mejor va ser usar señales si necesitas ver interacciones o mandar información, pero podría funcionar sin estas.
Suerte!
