### ISSUE TITLE
Utilidad del atributo de cola

### ISSUE THREAD

**Issue by CarlosValleA** [IIC2233/syllabus#634]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola ! Estoy tratando de hacer el ejercicio propuesto 1.2 de lista ligada de la semana 11, pero no me queda claro para que sirve tener cola como atributo. Estoy viendo ejemplos de como remover un elemento y la mayoria no agrega la cola, no me queda claro cual es su utilidad.

Gracias!

**Comment by Juampisaez** [comment]
Hola @CarlosValleA 
En el caso que tu mencionas, puede darse el caso de que estes removiendo justo el elemento que este al final de la lista de ligada, si esto llega a ocurrir, la cola de la lista ligada cambiara al penultimo elemento de lista.
Tienes razon de igual manera que para remover puede que no afecte mucho, pero si luego quieres agregar un elemento nuevo, es mas facil agregarlo de inmediato al final de lista, en vez de recorrer toda la lista para encontrar el ultimo elemento.

No se si me explique bien, me avisas de igual forma :)

**Comment by CarlosValleA** [comment]
Hola @Juampisaez  ! gracias por la respuesta, pero aun tengo un par de dudas. En el siguiente codigo, no entiendo como self.cola se relaciona con self.cabeza. Al agregar un valor solo se accede a self.cabeza en la primera ejecución, y todas las demas pasan al `else`, pero cuando se hace el print self.cabeza si contiene toda la información. No logro comprender como self.cabeza accede a self.cola 

```python
class Lista:
    
    def __init__(self):
        self.cabeza = None
        self.cola = None
    
    def agregar(self, valor):
        nuevo = Nodo(valor)
        if self.cabeza is None:
            self.cabeza = nuevo
            self.cola = self.cabeza
        else:
            self.cola.siguiente = nuevo
            self.cola = self.cola.siguiente
            
    
    def __repr__(self):
        """Forma una representación de la lista"""
        string = ""
        nodo_actual = self.cabeza
        while nodo_actual is not None:
            string = f"{string}{nodo_actual.valor} → "
            nodo_actual = nodo_actual.siguiente
        return string
    
    
l = Lista()
l.agregar(1)
print(l)
l.agregar(2)
print(l)
l.agregar(3)
print(l)
```

**Comment by Juampisaez** [comment]
@CarlosValleA 
Ya mira, una lista ligada como un tren, en donde los elementos de la lista ligada son los carros. El tren tendra un primer vagon, un segundo y asi hasta el ultimo vagon. Cada vagon puede tener un vagon antecesor y otro sucesor (uno solo o ambos a la vez). Ahora bien, si el tren tiene tres vagones, el primer vagon se relacionara con el tercero (ultimo) por medio del segundo vagon.
En la lista ligada pasa lo mismo, la cabeza de esta, está conectada con la cola por medio de algun otro elemento (si la lista tiene dos elementos, la cabeza y la cola estan ligadas directamente).
Al agregar un elemento a la lista, tal como tu dices, solo nos importa el segundo caso si la lista ya tiene un elemento, por eso se agregan al final de la lista (cola).
Por ultimo, fijate que en el print al entrar en while esta iterando, `nodo_actual = nodo_actual.siguiente`, esta linea es la que permite pasar al siguiente elemento de la lista ligada hasta llegar al final (se deja de cumplir la condicion del while).

Espero quede mas claro, si no me dices :)

**Comment by CarlosValleA** [comment]
@Juampisaez la connexion entre self.cabeza y self.cola no la entiendo. En ninguna parte se define el atributo siguiente para self.cabeza, pero en el print si puedo acceder a el. Al agregar elementos solo se define self.cola.siguiente, lo que me da a entender que los elementos se agregan por medio de self.cola y no interactuan con self.cabeza. Nose si se entiende la pregunta

**Comment by Juampisaez** [comment]
Fijate que eso que mencionas si se hace, cuando agrego un primer elemento, entra al primer if, donde el elemento agregado seria la cabeza y la cola al mismo tiempo de la lista ligada. Luego, si agrego otro elemento, este se agregaria en el else a la cola de la lista ligada la que coincidira con la cabeza también (la cola y la cabeza son iguales en la primera agregacion), en es momento se le asigna el siguiente valor a la cabeza.
Por ultimo, tal como dices, los elementos se agregan siempre a la cola a excepción de cuando la lista esta inicialmente vacía.

Avísame si se entiende ahora.

**Comment by CarlosValleA** [comment]
Hola @Juampisaez ! creo que ahora entiendo lo que no entiendo jaja. Mas que no entender listas ligadas tengo dudas con el funcionamiento de python. Mi duda es como se llama esto o porque esto funciona:

```python
class Perro:
    def __init__(self):
        self.valor = None

a = Perro()
b = a
b.valor = 1
print(a.valor) # entrega 1
```
El valor se define en `b`, pero a igual puede acceder a el en `a`, ahi hay una referencia (?). Sorry si es algo muy basico, con que me digas como se llama esta propiedad lo puedo buscar por mi cuenta, hice intro a la progra hace como 6 años y nose si es algo que se ve en el curso o no.

**Comment by Juampisaez** [comment]
@CarlosValleA 
En el caso que comentas, cuando haces `a = Perro()` estas instanciado un objeto de la clase Perro, basicamente es una instancia. Ahora bien, es claro que `b` tambien lo sera puesto que igualas esa variable al mismo valor de `a`. De esta forma ambas variables corresponderan a la misma instancia de la clase Perro. Puedes pensarlo como tu dices, una referencia a una misma instancia.

En avanzada no recuerdo haber visto ningun ejemplo como el que menciones, es mas probable encontrarlo en contenidos de intro. Pero con explicacion anterior deberia responder a tu pregunta.

Espero quede mas claro, perdon lo tarde :)

**Comment by CarlosValleA** [comment]
Gracias @Juampisaez ! me quedo super claro !
