### ISSUE TITLE
Aparición enemigos

### ISSUE THREAD

**Issue by jgespinosa10** [IIC2233/Syllabus#634]
En el enunciado explican que el tamaño con que aparecen los enemigos depende de la formula [triangular(a, b, c)] ^3. Se refieren y a la función numpy.random.triangular? Y si es así, ocurre que los valores a, b y c no calzan para esa función, ya que c es menor a b. Tengo esta duda sobre el tamaño de los enemigos al aparecer

**Comment by nebil** [comment]
Ese <sup>3</sup> del enunciado no quiere decir que debes elevar al cubo, sino que es una referencia a un _footnote_ —nota al pie que, por las curiosidades que tiene la vida, debería responder a tu duda original. :smile:

Dicho en emoji, con [:game_die: **.** :small_red_triangle:](https://docs.python.org/3/library/random.html#random.triangular) sí debería calzar.
