### ISSUE TITLE
Tiempo ejecucion Ecualizador

### ISSUE THREAD

**Issue by pizquierdo2** [IIC2233/Syllabus#635]
Mi filtro ecualizador está demorándose más de lo que esperaba en terminar de operar.
¿Qué rango de tiempo es aceptable para el tiempo de ejecución del ecualizador?

**Comment by rrhurtado** [comment]
Hola,

No tenemos definido un rango de tiempo aceptable, pero generalmente coincide con el sentido común. Quizás sería buena idea intentar disminuir ese tiempo si encuentras que perjudica mucho la fluidez del juego.

Saludos!

**Comment by DiegoAndai** [comment]
Aún así, no se preocupen si se demora en terminar uno o dos minutos, sobre todo con un n alto. Hay que iterar todos los bytes y eso puede demorar dependiendo de la implementación. Sin embargo no les bajará la nota mientras se mantengan dentro de ese rango.

**Comment by jnhasard** [comment]
Hola, si la canción se esta por tan solo 20 segundos en reproducción y este proceso demora minutos me será imposible implementarlo en mi tarea...
