### ISSUE TITLE
Ejercicio 3.3 Semana 12: Problemas para llevar la cuenta de distancia

### ISSUE THREAD

**Issue by Pabloski100** [IIC2233/syllabus#635]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Tengo problemas para llevar la cuenta de la distancia

Si entendí bien, el recorrido que conviene modificar es BFS, sin embargo, tengo problemas para llevar la cuenta de la distancia. De alguna manera hay que implementar un contador que registra cada vez que el BFS avanza en el "nivel de búsqueda", sin embargo, he estado mucho tiempo pensando como detectar ese cambio de nivel sin éxito.

Hasta ahora pienso en que debo revisar que estén los vecinos del inicio, luego los vecinos de los vecinos del inicio, y así sucesivamente, pero por el momento no logro imaginar un método general para implementar esto.

¿Voy por buen camino o estoy complicando demasiado la implementación del contador?

**Comment by aaossa** [comment]
Hola @Pablok98 , sospecho que tienes una buena idea de cómo abordar el ejercicio, pero veamos el problema que mencionas. En una iteración cualquiera, efectivamente es difícil saber a qué distancia estás actualmente. Pero hazte esta pregunta: ¿qué pasaría si supieras la distancia **d** hasta el paso anterior? Con esto me refiero a la distancia desde la que llegaste al nodo que estás procesando ahora. Si tuvieras este dato, sabes que los siguientes datos estarían a una distancia **d + 1**. Esto no lo he implementado pero sospecho que el truco para resolver el problema está en la cola de procesamiento que ocupas 👀. Avísame si se entiende la idea y te funciona implementarla 🙌

**Comment by Pabloski100** [comment]
No se si la entendí la idea, pero le daré unas vueltas, gracias!
