### ISSUE TITLE
Pequeño error arruinó mi tarea, habrán cambios de lineas?

### ISSUE THREAD

**Issue by Sofia-Arratia** [IIC2233/syllabus#635]
Hola!

En la velocidad de arreglar las ultimas cosas de la tarea, importé mal un parámetro, el cual en vez de estar como p.PARAMETRO quedó como P.PARAMETRO, lanzando un error casi al principio de mi código. ¿Habrán cambios de líneas para corregir eso?, y si no es así, ¿Pueden corregirme alguna versión anterior? El código funcionaba perfecto antes de eso :c

Desde ya muchas gracias.

**Comment by lily416** [comment]
Hola @Sofia-Arratia 

Hemos habilitado el siguiente [formulario](https://forms.gle/mZxbFXznMT69hCw89), ahí puedes indicar un _commit_ anterior para la corrección de tu tarea 😄.  

Saludos y feliz fiestas 👋💃

**Comment by Sofia-Arratia** [comment]
Muchas gracias!

Tengo una duda por si me puedes ayudar dandome tu opinión, resulta que el último push de código sin este error que hice fue antes de subir el README, es decir, el error surgió con mi primer push de README. ¿Que me conviene mas? ¿Evaluar mi push funcional sin mucha explicación para quien tenga que corregirlo, arriesgandome a que no sepa como correr el programa? ¿O dejo lo que está, que es un código que se cae en el segundo menú, pero tiene las explicaciónes?

No se bien que debería hacer, ya que sin el README tampoco funcionaría el código, dado que usé una librería que se instala (beautifultable), y quien corrige no sabrá que la necesita. 

Muchas gracias 😭

**Comment by lily416** [comment]
No te puedo ayudar con respecto a esto, debido a que es una decisión que debes tomar tu fijándote en la [pauta de la tarea](https://docs.google.com/spreadsheets/d/14YkdSyV4yCSA15LsCc29xmS9LKlXFYZ7-kFv_F6g_e4/edit?usp=sharing) y en [la guía de descuentos](https://github.com/IIC2233/syllabus/blob/master/Tareas/Descuentos.md), pero lo que sí puedo hacer es comentarte un poco cada opción:
 
1. Si decides quedarte con **el _commit_ que no tiene el error**: Tendrás 1 décima de descuento debido a que no subiste el README y al momento de correr tu código aparecerá un mensaje como el siguiente:
   ```python
   Traceback (most recent call last):
     File "a.py", line 1, in <module>
       import beautifultable
   ModuleNotFoundError: No module named ‘beautifultable'
   ```
 
    Esto le permitirá a tu corrector saber que necesita instalar la librería `beautifultable`.
 
1. Si decides quedarte con **el _commit_ que tiene el error**: En vez de la décima de descuento, te descontarán por los cambios de líneas que sean necesarios para correr tu tarea o no te darán puntaje en los ítems relacionados con el error. 
 
 
Espero que esto te ayude a tomar la decisión.
Saludos 👋🥟

**Comment by Sofia-Arratia** [comment]
Muchisimas gracias!

Pensé que, ya que no corre el código, todo el puntaje de lo que se muestra en consola sería 0. Perdóname por molestarte de nuevo en tus días libres, pero es solo para confirmar si entendí bien. Si me quedo con mi commit actual, el error se mostrará al igual que se mostraría por la librería, y así podrán cambiar la línea incluso si no está especificado el error en el README? No pasará que se asignen los puntajes de acuerdo a que el código no corre? Y si necesito especificarle a mi ayudante el carácter que cambiar, cómo me pongo en contacto con el/ella?

Muchísimas gracias, perdón nuevamente, y que pases unas muy felices fiestas ☺️

**Comment by lily416** [comment]
Hola @Sofia-Arratia, 
 
Primero que todo, lo siento por la demora en responder 🙇 
 
Tal como dices, cuando el ayudante corrector trate de correr tu tarea le saldrá un error, aunque no será el mismo que con la librería `beautifultable`:
```python
Traceback (most recent call last):
  File "a.py", line 1, in <module>
NameError: name 'P' is not defined
```
Lo más probable es que al momento de corregir el ayudante se de cuenta del error y lo corrija, pero aún así le haré llegar el comentario, para que haga los cambios y aplique el descuento correspondiente. 
 
Recuerda que si en algún momento tienes algún problema con la corrección, en la recorrección puedes hacer llegar tus comentarios a tu ayudante corrector.
 
 
Saludos y que tenga una buena semana 👋🍬

**Comment by Sofia-Arratia** [comment]
Perfecto! Muchisimas gracias, me ayudaste bastante y quedo muy tranquila con lo que pueda pasar con mi tarea. Que estés muy bien! ☺️
