### ISSUE TITLE
¿Duda sobre nuestro criterio?

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#635]
Hola, 
Entiendo bien lo de que si algo no está especificado, queda a nuestro criterio, por qué se hace y esas cosas, pero, ¿hay límites para qué tan amplio/permisivo puede ser nuestro criterio? ¿Hay descuentos en caso de que sea demasiado amplio?

Pregunto porque por ejemplo, con la tarea anterior, mi criterio podría haber definido que cuando los operarios de atracciones se van a almorzar ponen a un espantapájaros en su puesto que cobra la entrada pero no verifica las fallas, entonces si la atracción falla se limita a indicar el número de bajas y cerrar la atracción hasta que llegue el operario. O que cuando el parque cierra, un dragón mata a todos los clientes que estaban en él y les roba el dinero que les quedaba (el que pasa a manos del parque).

Pongo estos ejemplos hipotéticos y para nada representativos de la realidad a modo de ejemplo también para preguntar ¿qué pasa cuando nuestro criterio simplifica demasiado las cosas? (Por ejemplo, que los operarios nunca hacen nada, las atracciones tienen cabina de pago automático y los operarios solo resuelven crucigramas (en el imaginario colectivo, ni siquiera implementado)).

**Comment by Arcoirisky** [comment]
1) Adoro tus criterios nada representativos a la realidad.
2) La idea y la condición que aparece en el enunciado es que nada **naaada** 😱 de lo que queda a tu criterio puede pasar sobre algo que diga el enunciado. Si el enunciado dice que los operarios tienen el trabajo de hacer X cosas, deben hacerlo en el sentido de que deben poseer un método que represente esa acción X. 

Si simplificado tanto la tarea como para que pase por sobre estas cosas, estarás perdiendo puntaje de modelación u en otros ítems dónde se pida que ese operario haga su trabajo. 

En cambio, si ves que no hay nada escrito ni parecido ante algún caso Y puedes asumir lo que desees y escribirlo en el Readme. Pero si sientes que puede pasar a llevar a algo del enunciado, entonces es mejor preguntar por aquí. 

Igual debes tener ojo, porque si asumes algo y sucede que alguien pregunta en las issues lo mismo o parecido, obteniendo como respuesta un "No puedes asumir aquello" GG. Tienes que cambiarlo porque este es el medio de comunicación oficial y todos están sujetos a lo que suceda aquí uou

Espero te aclare un poco xD
