### ISSUE TITLE
nuevo nivel

### ISSUE THREAD

**Issue by rihanuch** [IIC2233/Syllabus#635]
En el enunciado se dice 

> Al comenzar el juego empiezas en nivel 1 y tamaño 2, con 0% de progreso de nivel. Cada nivel nuevo comienza con 0 puntos de experiencia.

 El empezar con 0% implica que si se come a un enemigo y los xp points exceden lo necesario para avanzar de nivel este excedente se pierde? 🤔

**Comment by tcgarrido** [comment]
Hola! 

Exacto. Si los puntos exceden el necesario para avanzar de nivel, el excedente se pierde y comienzas el nivel siguiente con 0 puntos.

**Comment by rihanuch** [comment]
pobre jugador 😢 , pero ok! gracias!
