### ISSUE TITLE
Error al enviar múltiples mensajes

### ISSUE THREAD

**Issue by aljara97** [IIC2233/syllabus#635]
Hola, al enviar dos mensajes seguidos desde el servidor al cliente, el cliente arroja el siguiente error
json.decoder.JSONDecodeError: Extra data: line 1 column 35 (char 34)
Eso se debe a que está escuchando los dos mensajes a la vez? Implementé el método escuchar de manera similar al que estaba en el ejemplo de chat y el de la última actividad. Hay alguna forma de corregir este error?

**Comment by gatochico** [comment]
Hola! Tu problema ya ha sido tratado en múltiples issues. Comienza por revisar la #532 y la #613 
Esto ocurre porque el cliente no ha terminado de procesar un mensaje antes de que le llegue el otro.
