### ISSUE TITLE
dimensiones en setGeometry

### ISSUE THREAD

**Issue by mjgutierrez1** [IIC2233/Syllabus#636]
Hice una ventana básica en que definí su medidas con self.setGeometry(500, 250, 300, 300) y le agregué una barra self.bar_nivel = QProgressBar(self) con medidas self.bar_nivel.setGeometry(0,0,300,20).

Lo que no entiendo, es por qué el ancho de la ventana me queda más grande que el ancho de la barra, siendo que a ambas les puse un ancho de 300.

**Comment by hanavarrete** [comment]
Que tan grande es la diferencia de ancho? Creo que en algunos sistemas operativos (al menos en mac) la ventana principal tiene una pequeña diferencia de ancho con algunos objetos. Si revisas el material extra y cambias el ancho del botón por el mismo de la ventana podrás ver un pequeño margen correspondiente a esta última.
A priori no se donde te podrías haber equivocado dado que en lo que escribiste ambos tienen 300 de ancho. Igual podrías probar haciendo self.setMaximumWidth(300) como medida parche, pero revisa bien si en algún lado no cambiaste la geometría.
