### ISSUE TITLE
Pequeño error, commit 5 minutos tarde

### ISSUE THREAD

**Issue by Niko12121** [IIC2233/syllabus#636]
Holaaa
El codigo que asignaron a revisar tiene un error al principio del código, que no deja correrlo; este error lo corregí pero subí este commit corregido 5 minutos tarde. ¿Qué debo hacer para que me corrijan este último commit (obviamente con el descuento por atraso correspondiente)?

**Comment by lily416** [comment]
Hola @Niko12121,

Acabo de responder el correo que mandaste al mail oficial del curso, ahí te respondo lo mismo que indicas en la issue.

Saludos 👋
