### ISSUE TITLE
Problemas con .setText()

### ISSUE THREAD

**Issue by mpsubiabre** [IIC2233/syllabus#636]
Hola, estoy haciendo una cuenta regresiva que se muestre en la ventana. La estoy haciendo con  un qlabel el cual se actualiza con setText(f"texto {variabel a actualizar} "). Esta variable se va actualizando en intervalos mediante el metodo sleep().
Lo que me pasa es que en la ventana, solo aparece la ultima actualizacion, no las que tengo entremedio. 
Que podria estar fallando? mediante print compuebo que las variables cambian pero no entiendo por que no se muestra.
Muchas gracias,

**Comment by nbnavarro** [comment]
Hola, me pasaba lo mismo y cambié los `sleep()` por `QTest.qWait()`, con la diferencia que el último trabaja en ms y no en s por si acaso. 
(hay que hacer `from PyQt5.Qt import QTest)`
