### ISSUE TITLE
Ayudantía Threading

### ISSUE THREAD

**Issue by tolavarria** [IIC2233/syllabus#636]
Hola! Creo que aún no se desbloquea la ayudantía de threading (no la puedo ver). Pueden revisar porfavor?
saludos

**Comment by Drpinto1** [comment]
¡Hola!

Canvas me jugó una mala pasada en 2 de las secciones del curso, pero ahora debería estar visible el video para todos :D
Gracias por avisar que había un error :new_moon_with_face: 

¡Saludos!

**Comment by tolavarria** [comment]
Ahí lo puedo ver. Muchas gracias! 😄
