### ISSUE TITLE
Problema Interfaz y Cliente

### ISSUE THREAD

**Issue by fcgfaura** [IIC2233/Syllabus#636]
Hola!, a alguien le pasó que cuando el cliente recibe un mensaje del servidor y llaman a un método del mismo cliente, en ese método si llaman a la interfaz les tira el siguiente error: 
`QObject::setParent: Cannot set parent, new parent is in a different thread
 QBasicTimer::start: QBasicTimer can only be used with threads started with QThread`
Si alguien sabe como solucionarlo, porfa ayudaaa!!!

**Comment by iqacevedo** [comment]
Hola

Eso ocurre por no usar bien el manejo de señales, comunicando mediante señales las instrucciones a la interfaz debería solucionar tu problema. 
Si tu problema no se soluciona, especificanos si el cliente esta escuchando en un Thread aparte lo que envia el servidor.

Saludos!

**Comment by fcgfaura** [comment]
Pero desde el cliente no puedo generar señales porque no es un objeto de interfaz >.< . Y sobre el Thread, no entendí bien tu pregunta, pero mi cliente tiene un único thread y es el que escucha al servidor.

**Comment by iqacevedo** [comment]
Justamente esa era mi pregunta, lo que sucede es que la interfaz gráfica esta en un Thread y tu le estas pidiendo hacer algo directamente desde otro Thread (el que escucha el servidor), debes encontrar la forma de comunicarte con la interfaz mediante una señal.
Auto-Hint: Como lo mencionas necesitas un QObject que envié la señal a la interfaz (tu decides como lo modelas).

Espero puedas lograrlo :)
Saludos !

**Comment by fcgfaura** [comment]
@iqacevedo Lo logré !!!!!!, tu auto-hint me arregló la vida!!!!. Solo quería que lo supieras :)
