### ISSUE TITLE
Assets T05

### ISSUE THREAD

**Issue by Bipavez** [IIC2233/Syllabus#636]
Hola! 
Pregunta, ¿Cuanta restricción hay sobre los assets?
* ¿Puedo en vez de ocupar un background ocupar tiles de camino libre?
* ¿Puedo ordenar el directorio de assets como yo quiera?

**_Obviamente especificándolo en el README_**

**Comment by ptflores1** [comment]
Hola !
Las únicas restricciones sobre como manejas los assets son que:

- No interfiera con las funcionalidades del programa

- No contradiga nada del enunciado

- No dificulte la corrección

Saludos !

**Comment by Bipavez** [comment]
Muchísimas gracias!
