### ISSUE TITLE
Instanciar objetos en front end

### ISSUE THREAD

**Issue by JPSF** [IIC2233/Syllabus#637]
Hola, estaba viendo el material de interfaces gráficas y en un ejemplo de parte de "generar señales personalizadas" se instancian threats en el front end para recibir señales de ellos ¿Es esto una buena práctica(aplicable a la tarea)? Mi duda surge porque por lo que hemos visto en clases siempre nos han recalcado que se debe separar front end de back end, y me parece que sería más apropiado crear las instancias en el back end

**Comment by hanavarrete** [comment]
El ejemplo que está subido solo apunta a mostrar como funcionan las señales, además, el funcionamiento de este es tan mínimo que no existe un backend. Tal vez en estricto rigor debiese haber un backend en el ejemplo, pero sería solo para eso. De todos modos como tu dices (y te han dicho en clases) lo correcto sería separarlo siempre. Vere si existe la posibilidad de que hagamos un mini backend para que a todos los quede más claro. Muchas gracias por avisarnos! 😄

**Comment by JPSF** [comment]
Gracias @hanavarrete 
Me surgió una nueva duda ¿Sería correcto instanciar el back end(como un objeto) en el front end para recibir señales de él y que cualquier cambio interno en el programa sea enviado al front end como una señal?

**Comment by hanavarrete** [comment]
En general he visto tareas de las dos formas, algunas en las que el backend contiene al frontend y al revés. Creo que ambas formas son igual de correctas mientras exista consistencia y coherencia a lo largo de tu código en el manejo de señales y otros cambios externos/internos.

**Comment by JPSF** [comment]
Perfecto! gracias
