### ISSUE TITLE
Formulario T1

### ISSUE THREAD

**Issue by YehudaGurovich** [IIC2233/syllabus#637]
No se me abre el formulario para pedir corrección de un commit anterior. Justo antes de entregar cambié un IEEsparta por IEEEsparta y me produjo que se me caiga otro lado del codigo sin darme cuenta :s

**Comment by lily416** [comment]
Hola @YehudaGurovich,
 
¿Qué te aparece cuando tratas de entrar al formulario? 
Para poder acceder al formulario debes usar tu mail uc, ¿te fijaste en si tienes tu sesión abierta?
 
Quedo atenta a tus comentarios 👋

**Comment by YehudaGurovich** [comment]
Respecto a eso preferiria el cambio de lineas (que son como 5 o 6 con ese error) existe esa posibilidad?
