### ISSUE TITLE
Bonificación de Chat

### ISSUE THREAD

**Issue by KnowYourselves** [IIC2233/Syllabus#637]
He estado trabajando en el chat y tengo la siguiente pregunta, es válido separar los emojis por linea?

Es decir que cada vez que se use un emoji pasar a la siguiente linea del chat?

Ej: "Hola :) como estas?" devolvería:

"Hola
😄 como estas?"

de antemano, gracias!

**Comment by rrhurtado** [comment]
Hola

Al pasar a la siguiente línea del chat la concatenación de emojis perdería sentido (por ejemplo, 😄😄😄 quedaría en tres líneas distintas) por lo que no es válido separar los emojis por línea.

Saludos

**Comment by monicabelen** [comment]
Se puede usar la librería emoji?

**Comment by hanavarrete** [comment]
No se puede! la idea es que detectes donde esta el emoji e insertes una imagen tu misma. Saludos!
