### ISSUE TITLE
Bytearray append vs extend

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#637]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Por qué no puedo utilizar b"STRING" para el método .append de un bytearray, pero sí en el extend?
```python
mi_barray = bytearray(b"HOLA")
print(mi_barray)
mi_barray.extend(b"MUN")
print(mi_barray)
mi_barray.append(0x01)
print(mi_barray)
mi_barray.append(42)
print(mi_barray)
mi_barray.append(b"D")
print(mi_barray)

```
<details>
  <summary>Output:</summary>

```python
bytearray(b'HOLA')
bytearray(b'HOLAMUN')
bytearray(b'HOLAMUN\x01')
bytearray(b'HOLAMUN\x01*')
Traceback (most recent call last):
  File "prueba.py", line 9, in <module>
    mi_barray.append(b"D")
TypeError: 'bytes' object cannot be interpreted as an integer
```

</details>

**Comment by StroveLight** [comment]
Hola!
Esto tiene que ver con el ".append()" y el ".extend()", si te acuerdas un poco de las ```list```, probablemente recuerdes que el append agrega un elemento al final y el extend agrega los elementos de otra lista (o iterable) al final de la primera lista. 

Lo similar ocurre con los bytearray, b"SRING" es un arreglo de bytes, por lo que permite el extend, pero no se puede usar el append, porque solo se pueden guardar un byte por cada casilla del bytearray (y no varios bytes).

**Comment by fernandosmither** [comment]
> Hola!
> Esto tiene que ver con el ".append()" y el ".extend()", si te acuerdas un poco de las `list`, probablemente recuerdes que el append agrega un elemento al final y el extend agrega los elementos de otra lista (o iterable) al final de la primera lista.
> 
> Lo similar ocurre con los bytearray, b"SRING" es un arreglo de bytes, por lo que permite el usarlo para el extend de un bytearray, pero no se puede usar el append, porque solo se pueden guardar un byte por cada casilla del bytearray (y no varios bytes).

Y cómo podría crear un byte string único, y no un arreglo, para poder meterlo usando append?, o por la naturaleza de los byte strings no se puede?

**Comment by StroveLight** [comment]
No se puede, es como decir que sea un string ```my_string```, quieres que una casilla del string contenga una palabra (como por ejemplo, "HOLA"), tal que se almacene "HOLA" en ```my_string[1]```. Cada parte del string guarda un solo carácter por definición, algo similar ocurre con el bytearray, que contiene un solo byte en cada casilla por definición.

**Comment by fernandosmither** [comment]
> No se puede, es como decir que sea un string `my_string`, quieres que una casilla del string contenga una palabra (como por ejemplo, "HOLA"), tal que se almacene "HOLA" en `my_string[1]`. Cada parte del string guarda un solo carácter por definición, algo similar ocurre con el bytearray, que contiene un solo byte en cada casilla por definición.

Pero si el b-string es de solo 1 caracter? tipo b"h", por qué no podría appendearlo en ese caso, si ocuparía solo una casilla?

**Comment by StroveLight** [comment]
Porque es un arreglo de bytes, pero de largo uno, quecontiene un byte. Por lo tanto no puedes usar append con eso (ya que agregarías el arreglo de los bytes en vez de solo uno), sino extend.

**Comment by fernandosmither** [comment]
> Porque es un arreglo de bytes, pero de largo uno, quecontiene un byte. Por lo tanto no puedes usar append con eso (ya que agregarías el arreglo de los bytes en vez de solo uno), sino extend.

Perfecto! Muchas gracias
