### ISSUE TITLE
Formulario de recorreccion

### ISSUE THREAD

**Issue by jpmoraga1** [IIC2233/Syllabus#638]
Tengo una duda para mandar la recorrección, en el formulario piden el usuario de Git pero tuve la brillante idea de cambiar el nombre de usuario después de empezar el curso, por lo que mi nombre de usuario y el de mi repositorio son distintos. ¿Qué nombre coloco en el formulario, el del repositorio o el de usuario?

**Comment by andresfdezc** [comment]
En el caso de las actividades, nos sirve más que escribas tu usuario de github inicial (el que está en el nombre de tu repositorio). No estoy seguro sobre cuál le sirve a los ayudantes de tareas.

**Comment by jpmoraga1** [comment]
Es para recorregir tarea, probaré igual con mi usuario antiguo

**Comment by FernandoPieressa** [comment]
Hola! 

Al igual que en las actividades, en el caso de las tareas nos sirve más tu usuario antiguo.

Saludos!
