### ISSUE TITLE
Se puede asumir mapa 9x9?

### ISSUE THREAD

**Issue by naquiroz** [IIC2233/Syllabus#638]
Podemos asumir que en el archivo `mapa.txt`nunca se van a tener mapas mas grandes que 9x9?

**Comment by rihanuch** [comment]
Hola,

Los mapas son 15x15

Saludos!

**Comment by naquiroz** [comment]
@rihanuch pero puedo asumir entonces que siempre van a ser de 15?

**Comment by ptflores1** [comment]
#622
