### ISSUE TITLE
Enemigos

### ISSUE THREAD

**Issue by NicolasCourt** [IIC2233/Syllabus#639]
Para el movimiento de los enemigos, este tiene que ser con sprite sheets o puede ser una simple imagen que se mueva? (sin animacion)

**Comment by jfbahamondes** [comment]
Puede ser sin animación, saludos!

**Comment by NicolasCourt** [comment]
Oki doki Gracias!

**Comment by sjkinast** [comment]
Si no me equivoco en la ayudantía de la Tarea se dijó que el movimiento de los enemigos no era necesario que fuera continuo, esto significa que puedría asumir que el movimiento del enemigo es de un cuadrante a otro cuadrante y no entre dos ? o solo aplica para el tema de los sprites.
