### ISSUE TITLE
Problema filtro dibujo cuando se manda a servidor

### ISSUE THREAD

**Issue by totichi** [IIC2233/syllabus#639]
Hola! Tenia un problema con el filtro de dibujo: funciona perfecto si lo realiza el cliente mismo, pero si lo realiza el servidor aparece un error del tipo `libpng error: IEND: CRC error` .No obstante, cuando abro el archivo que fue creado por el frontend via codigo creado por el servidor (bites) funciona perfectamente.
Alguna idea de lo que puede ser?

**Comment by iqacevedo** [comment]
Hola, 

Tu error indica que el chunk IEND tiene un error, revisa que estas agregando todo bien, en especial que agregaste un crc al final de este chunk.

Saludos !
