### ISSUE TITLE
ecualizador

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2233/Syllabus#639]
Para aclarar esto, que si bien se habla en varias issues no me termina de dejar claro.
1) Si tengo que el bits per sample es 16, ¿Significa que es 1 byte por canal intercalado o son 2 bytes por canal intercalados?
Yo tenía entendido que era 1, pero ya no se.

Sumado a esa pregunta, tengo otra duda, que creo que no e trata en otra issue:

2) No entiendo como se relaciona el f con el n en los parámetros del ecualizador, porque los dos cambian cosas distintas, y si entiendo bien, el único que sirve en la practica es el n, porque cambiar el header no sirve para nada en cuanto a la reproducción de la canción, aunque si entiendo la importancia de tener un header adecuado que no "mienta".

3) Además es raro que el f sea un decimal, porque al multiplicarlo por el sample rate qurda un decimal y eso no se puede convertir a bytes. Al menos me tira error porque es un float.

**Comment by jorgeriesco** [comment]
1) Viendo ahora el enunciado nuevo, sale claro que si el bits per sample es 16, entonces son dos bytes por sample de cada canal, osea estan interclados de a dos bytes.

**Comment by DiegoAndai** [comment]
Como dices, 1. aparece en el enunciado.

2. El f y el n no tienen relación directa, ambos tienen efectos distintos que juntos conforman el filtro pedido. Cambiar el header si sirve, por ejemplo si se cambia el SampleRate se cambia el numero de samples reproducidos por segundo, que claramente tendrá un efecto en la canción.

3. En #595 preguntan lo mismo (no en la pregunta principal pero lo respondí en el comentario 14)
