### ISSUE TITLE
semana-8: Ejercicio 2.4 Duda Timer y Event

### ISSUE THREAD

**Issue by CatalinaGoldsack** [IIC2233/syllabus#639]
Hola! En el ejercicio 2.4 propuesto donde hay que utilizar timer no logro hacer que mi alarma.set() de manera que entre en
```python
    for i in range(15):
        if alarma.is_set():
            print("¡Gracias despertador, desperté a la hora!")
            return
```
He estado definiendo mi thread Timer como: `thread_timer = threading.Timer(tiempo_a_esperar, funcion, (arg_1, arg_2)))`, donde en `arg_2` e intentado utilizar el `alarma.set()`, pero no funciona :(

**Comment by fdoflorenzano** [comment]
Hola @CatalinaGoldsack,

¿Qué estás entregándole como función al `Timer`? Recuerda que eso es lo que se ejecuta después de esperar `tiempo_a_esperar` luego de hacer `start` a la instancia de `Timer`. 

Estoy atento,
Saludos.

PD: Edité tu pregunta para dejarla con formato de código :).
