### ISSUE TITLE
Serialización personalizada JSON

### ISSUE THREAD

**Issue by alvarocisternas** [IIC2233/syllabus#639]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ]x Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda
 Hola!
Estaba probando  en un documento .py el ejemplo de personalizar Serialización con JSON que aparece en los contenidos y cuando lo corro en mi consola me aparece que tiene errores: (aquí va el código)
```python
from datetime import datetime
import json


class PersonaEncoder(json.JSONEncoder):

    def default(self, obj):
        """Serializa en forma personalizada el objeto de tipo Persona"""
        if isinstance(obj, Persona):
            return {
                "Persona_id": obj.id_,
                "nombre": obj.nombre,
                "edad": obj.edad,
                "estado_civil": obj.estado_civil,
                "ano_nacimiento": datetime.now().year - obj.edad,
            }
        # Mantenemos la serialización por defecto para otros tipos
        return super().default(obj)


# Creamos tres instancias
p1 = Persona("Juanita", 37, "Soltera")
p2 = Persona("Jorge", 33, "Casado")
p3 = Persona("Mariela", 24, "Soltera")


# Probamos la serialización usando el método por defecto:
json_string = json.dumps(p1.__dict__)

print(json_string)

# Ahora, comparemos el resultado al serializar usando nuestro método personalizado:
json_string = json.dumps(p1, cls=PersonaEncoder)
print(json_string)

json_string = json.dumps(p2, cls=PersonaEncoder)
print(json_string)

json_string = json.dumps(p3, cls=PersonaEncoder)
print(json_string)
```
Los errores que me aparecen son:
1. NameError: name 'Persona' is not defined. Eso es cuando se crean las tres instancias.
2. Si modifico 'Persona' por 'PersonaEncoder' al crear las tres instancias me aparece el error: TypeError: __init__() takes 1 positional argument but 4 were given

Necesito algún tipo de orientación para resolver este inconveniente.

De antemano muchas gracias!

**Comment by aaossa** [comment]
Hola @alvarocisternas , lo que te faltó fue agregar en tu archivo *.py la clase `Persona`. La clase está definida en el mismo Jupyter, así que basta con que la copies. ¡Éxito con tu estudio 🙌!

**Comment by alvarocisternas** [comment]
Sí, ahí funcionó!
Muchas gracias profe @aaossa  

Saludos!
