### ISSUE TITLE
Github

### ISSUE THREAD

**Issue by blancaortuzarm** [IIC2233/Syllabus#64]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

Hola! envíe el formulario de github y aún no me agregan. Por si podrían revisarlo por favor

**Comment by gatochico** [comment]
Hola @blancaortuzarm ! Revisé y todavía no se te ha agregado ya que llenaste de forma incorrecta la sección que pide tu usuario de Github. Puedes editar tu respuesta para poner tu usuario correcto y se te debería crear tu repositorio 🤓

Saludos y quedo atenta!

**Comment by blancaortuzarm** [comment]
Ya lo cambié! Perdón por la confusión

**Comment by raymean11906** [comment]
CHristmas X live

**Comment by fernandosmither** [comment]
> CHristmas X live

Merry Xmas! (my profile pic)
