### ISSUE TITLE
Problema con paths

### ISSUE THREAD

**Issue by ElTurkos** [IIC2233/syllabus#64]
Hola, en Visual Studio no logro hacer que reconozca el path, siendo que creo esta bien escrito, adjunto recorte

**Comment by ElTurkos** [comment]
¿
![error](https://user-images.githubusercontent.com/62064830/76974072-81b88180-690f-11ea-94a9-132d13d485bc.PNG)

**Comment by aljara97** [comment]
Hola @ElTurkos, probablemente tu problema es que estás manejando un path absoluto y no un path relativo. La diferencia principal es que el path absoluto parte desde la raíz de tu computador, en este caso la carpeta "Users", mientras que un path relativo parte de la dirección relativa en que estás trabajando, la cual probablemente es la carpeta T00 de tu repositorio. Un ejemplo de path absoluto sería simplemente "usuarios.csv", puedes encontrar más detalle de esto en los contenidos del curso. Intenta probar actualizando el path y cuéntame cómo te va.

Éxito con tu tarea

**Comment by ElTurkos** [comment]
Me da el mismo error

**Comment by aljara97** [comment]
Probablemente es porque estás tratando de abrir un archivo ubicado en una carpeta distinta a la que se encuentra tu programa, como te puedes fijar ```usuarios.csv``` se encuentra en la carpeta del syllabus del curso y no se encuentra relacionado a una ruta en específico. Como te puedes fijar en la issue #8 se menciona que los ayudantes probaremos tu programa en la misma carpeta que los archivos csv. Recuerda usar un path relativo y archivos csv en el mismo directorio

**Comment by ElTurkos** [comment]
Lo acabo de hacer y sigo teniendo el mismo error

**Comment by aljara97** [comment]
Tu path tiene escrito usuarios.cvs en vez de usuarios.csv, disculpa por notar recién ese error

**Comment by ElTurkos** [comment]
Lo cambie, sigue dando error
![error2](https://user-images.githubusercontent.com/62064830/76994341-fe0d8d80-692c-11ea-976a-0af95b2611c5.PNG)

**Comment by aljara97** [comment]
Otro problema puede ser la forma en que haces correr tu programa en la terminal de tu computador o la generada por tu editor de texto, ya que si no estás situado en la carpeta T00 desde esta, tu programa se correrá desde la ubicación de python y eso evitará que los paths que utilizas funcionen de manera adecuada. Si pudieras especificar la carpeta en la que corres tu programa y desde cuál terminal, me serviría para aclararte tu duda

**Comment by ElTurkos** [comment]
![error3](https://user-images.githubusercontent.com/62064830/77002085-b5a89c80-6939-11ea-866a-e7304c68cc26.PNG)

**Comment by ElTurkos** [comment]
Tenias razon, eso era. Saludos

**Comment by aljara97** [comment]
Buenaa, por favor no cierres esta issue, podría ser de utilidad para otro de tus compañeros, nosotros lo haremos cuando sea necesario.

Mucho éxito con lo que queda de tarea :nerd_face:
