### ISSUE TITLE
espacios vs tab

### ISSUE THREAD

**Issue by F-arellano** [IIC2233/syllabus#64]
al utilizar mi editor automaticamente me generaba las tabulaciones, y si bien me permite situar el cursor en cualquier caracter (como si fueran 4 espacios) al borrarlos los trata como si fuera un tab, asi que no se si esta bien o no. ¿como puedo saber que efectivamente el archivo esta bien espaciado?

**Comment by KnowYourselves** [comment]
Hola @F-arellano!

Casi todas las IDE soportan indentar automaticamente cuando apretas `enter`. Usualmente esta indentación es hecha con espacios y si tu IDE te permite situar el cursos en cualquier carácter es casi certero que sean espacios. Si no estás seguro puedes ver la configuración de tu IDE para ver si efectivamente lo está haciendo. 

Quedo atento!

**Comment by benjastraub** [comment]
@F-arellano puedes configurar tu editor para que te muestre los espacios y tabs. Así verás ```·``` o ```->``` y sabrás qué es.
