### ISSUE TITLE
Suposición 

### ISSUE THREAD

**Issue by dgonzalezg** [IIC2233/Syllabus#64]
#¿Se puede asumir que el radio inicial de todos los incendios es de 500m? 
No logro identificar en que parte del enunciado sale cual es el radio inicial de un incendio y se necesita esto para calcular la superficie y a su vez los puntos de poder.

Saludos.

**Comment by FernandoPieressa** [comment]
Puedes asumir el radio inicial, tanto 500m como 0m, lo importante es aplicar los cálculos necesarios para saber el radio actual del incendio dado el tiempo de conexión.
Si asumes algún valor escribelo en el README.

Saludos!
