### ISSUE TITLE
acción conquistar planeta en galaxia

### ISSUE THREAD

**Issue by santilaguna** [IIC2233/Syllabus#64]
En la parte 5.1 del enunciado, se señalan acciones que se deben poder realizar en la galaxia durante su  modificación. Sin embargo, en la sección 6.2 la única de éstas que no se detalla, es la conquista del planeta (en el índice tampoco se menciona). 
Mi duda es: ¿Se debe implementar esta acción dentro de modificar galaxia? en cuyo caso esta modificación edita directamente los archivos, o bien ¿se debe limitar esta acción a jugar en galaxia y no guardar directamente este cambio?

**Comment by IchottMano** [comment]
@santilaguna Hola!
Ya que no sale en el enunciado, no debes implementarla.
Saludos!

**Comment by Pipelao** [comment]
Hola
Lo que había entendido del enunciado es que si el invasor (usuario) gana la batalla este conquista el nuevo planeta, ¿no es así?
Saludos

**Comment by IchottMano** [comment]
@Pipelao Hola!
Efectivamente es como tu lo dices.
Saludos!

**Comment by santilaguna** [comment]
Oka gracias!
