### ISSUE TITLE
Uso de funciones de DCCiudad dentro de otras funciones

### ISSUE THREAD

**Issue by josevalenzuelam** [IIC2233/Syllabus#64]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/20)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/19)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Quería saber si se pueden utilizar las funciones de dcciudad en la definición de las funciones en donde no se especifica que se deben utilizar o solo se pueden usar en aquellas que se especifican en el enunciado.

**Comment by MaxAl100** [comment]
Hola! Como regla general, puedes usar todas las funciones, crear más y llamarlas entre sí siempre y cuando ya sea que en el enunciado o en el github se mencione explícitamente que no se puede hacer.

**Comment by josevalenzuelam** [comment]
Perfecto gracias!
