### ISSUE TITLE
Encontrar ejercicios propuestos

### ISSUE THREAD

**Issue by diego-ayala-2000** [IIC2233/syllabus#64]
Hola, en que parte puedo encontrar los ejercicios propuestos?
Gracias

**Comment by lily416** [comment]
Hola @diego-ayala-2000,

Puedes encontrar los ejercicios propuestos dentro del [repositorio de contenidos](https://github.com/IIC2233/contenidos).
Cada semana de contenidos tiene su propia carpeta y dentro de ella podrás encontrar una carpeta llamada `ejercicios_propuestos`. 
Algunas semanas, como la semana 0, no tendrán estos ejercicios, pero la gran mayoría (por no decir casi todas) si tendrán.


Saludos 👋🏋️

**Comment by diego-ayala-2000** [comment]
Muchas gracias
