### ISSUE TITLE
Visualizar predio menu

### ISSUE THREAD

**Issue by cucho2** [IIC2233/Syllabus#64]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, en el enunciado dice que en [1] visualizar predio, en caso de ingresar código no existente se debe notificar por el terminal. En este caso, ¿se tiene que dar la opción de seguir ingresando códigos de predio hasta que se ingrese un código existente, o cuando se ingresa un código no existente se vuelve directamente al menú de acciones?

**Comment by ignacio-sp** [comment]
Hola @cucho2! Puedes seguir la misma lógica que con el resto de opciones del menú y volver al menú de acciones luego de la notificación, pero como no está especificado en el enunciado puedes realizar un supuesto siempre que lo indiques mediante el README
