### ISSUE TITLE
error de ciclo de import

### ISSUE THREAD

**Issue by Ilancf** [IIC2233/Syllabus#64]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Mi codigo funciona bien, pero tenia mas de 400 lineas, entonces lo separe en 3 codigos; el primero es el main que tiene la función de menu de inicio y un print que hace que se vea esta, el segundo tiene todas las funciones de administrador y el tercero tiene todas las funciones de usuarios. 
Al separarlo en estos 3 codigos, necesito que el main importe algunas funciones de usuario y de administrador, y que por el otro lado el de usuarios importe al main, y que el de administrador tambien importe al main, entonces se me hace un ciclo de import y no corre el programa, saliendo el siguiente error:

"Traceback (most recent call last):
  File "/Users/ilancf/Downloads/progra_avanzada/Ilancf-iic2233-2022-1/Tareas/T0/main.py", line 1, in <module>
    from funciones_usuario import ingresar_usuario, registrar_usuario
  File "/Users/ilancf/Downloads/progra_avanzada/Ilancf-iic2233-2022-1/Tareas/T0/funciones_usuario.py", line 2, in <module>
    from main import menu_de_inicio
  File "/Users/ilancf/Downloads/progra_avanzada/Ilancf-iic2233-2022-1/Tareas/T0/main.py", line 1, in <module>
    from funciones_usuario import ingresar_usuario, registrar_usuario
ImportError: cannot import name 'ingresar_usuario' from partially initialized module 'funciones_usuario' (most likely due to a circular import) (/Users/ilancf/Downloads/progra_avanzada/Ilancf-iic2233-2022-1/Tareas/T0/funciones_usuario.py)"

No se como importar correctamente para que no me genere este ciclo sin fin de import y a la vez al inicio de cada codigo importe los demas.

**Comment by Emiliax16** [comment]
Hola! el error es precisamente porque python no permite que dos módulos se importen entre sí, ya que se entra en un loop infinito. Lamentablemente la única manera de evitar esto es modificar tu código para que `main.py` contenga todo el flujo del programa y los módulos las funciones, de tal manera que la dependencia no sea mutua. Mucha suerte!
