### ISSUE TITLE
Que hacer con las tortugas inservibles.

### ISSUE THREAD

**Issue by Cristian1754** [IIC2233/Syllabus#64]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/21)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/20)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

DUDA

Al ejecutar un algoritmo similar al explicado hoy en clases, en algunas de mis soluciones hay tortugas que son validas pero que no detienen ninguna explosion. Ejemplo:
[  -  3  -  ]
[  -  T  2  ]
[  T  -  T  ]

La tortuga de la esquina inferior izquierda no esta haciendo nada util. No es complicado modificar el codigo para elminar esas tortugas, sin embargo, en el caso de que el tablero original venga ya con una de estas tortugas que no hacen nada tambien la terminaria eliminando, lo cual va en contra de el proposito de la funcion el cual es solo "Completar" el tablero dado y no eliminarle nada. Asi que no se que hacer en estos casos :c

**Comment by joaquindm02** [comment]
Hola @Cristian1754 !

No se puede modificar el tablero original en ese tipo de casos, pero no hay nada de malo con que existan tortugas inútiles. Puedes, en este tipo de situaciones, o buscar una solución nueva que no modifique la tortuga, o que las deje nomas. Lo importante es solo agregar tortugas y no modificar el tablero original.
Saludos
