### ISSUE TITLE
Uso de referencia.

### ISSUE THREAD

**Issue by Mardones567** [IIC2233/Syllabus#64]
Hola, se puede usar https://gist.github.com/JIGutierrez/77864621a0c674f02c55b869429fc8a9 como referencia o es copia?

**Comment by Juampisaez** [comment]
Holaa 👋 @Mardones567 
**Si, será considerado copia**. 
Inspirarse totalmente de ese código sería copia, puesto que la evaluación busca medir el rendimiento del alumno y no la busqueda de código. Si bien aceptamos que utilicen fragmentos de códigos (o funciones específicas) de internet siempre citando de donde salió, copiar un código con dicho nivel de avance tergiversa el propósito de la evaluación.

Por último, te recomiendo aprovechar esta tarea para poner en práctica la habilidad de programar la tarea con las herramientas aprendidas en intro y este curso, las tareas cada vez serán más creativas. En otro caso, aparte de que detectemos copia, solo te estarías perjudicando a ti en las siguientes evaluaciones.

Por favor no te arriegues a caer en plagio, la situación se tornaría más compleja y se alejaría de nuestro poder 🙏.

Quedo atento a cualquier otra duda 👀

**Comment by Mardones567** [comment]
Entiendo, entonces es mejor no usar referencias , ¿eso dices?

**Comment by Juampisaez** [comment]
Asi es, en el caso que propones junto al link, es muy parecido a lo que tienen que programar (lo esencial del programa), por lo que si llegas a utilizar un código así junto a su referencia, podrías caer en caso de copia.
Ahora bien, si es para el uso de una función (pequeña) para realizar una acción, mientras este referenciada esta todo bien. Pero como te digo, el uso de la referencia de arriba sería sospechosa.

Quedo atento si te quedan mas dudas 👀
