### ISSUE TITLE
duda mercados DCC

### ISSUE THREAD

**Issue by nmaturana97** [IIC2233/Syllabus#64]
ademas de los n mercado automaticamente creados teniendo en cuenta las currencies en el archivo currencies hay que crear los mercados DCC? ejemplo: si en el archivo currencies tngo AAA y BBB, debo crear: AAABBB, BBBAAA, DCCAAA, AAADCC, DCCBBB y BBBDCC?

**Comment by hanavarrete** [comment]
Si,  debes crearlos. Saludos!

**Comment by nmaturana97** [comment]
gracias!

**Comment by movaldivia** [comment]
@hanavarrete No entiendo por qué el AAABBB tendría que ser diferente a BBBAAA ya que si bien el usuario lo podría estar "viendo" desde una perspectiva diferente dentro del sistema se podría hacer que sean el mismo. En el caso de que hubiese que hacer los dos no se perdería eficiencia?

**Comment by hanavarrete** [comment]
Es por una tema de funcionalidad, no de eficiencia. Si revisas la issue #54 se habla sobre esta misma duda. Si no está claro ahí escríbeme por acá denuevo. Saludos!
