### ISSUE TITLE
¿Aclaración sobre cómo rellenar la plantilla del README.md?

### ISSUE THREAD

**Issue by martina-abello** [IIC2233/Syllabus#64]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](https://github.com/IIC2233/Syllabus/issues/56)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](https://github.com/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Busco aclaración en varios puntos, la verdad.

1. En la parte del "Menú", ¿hay que borrar los emojis que no correspondan y dejar solo el que sí? ¿Y a qué se refieren con agregarlos a los títulos?
2. En la parte de ejecución, tengo que poner en la lista todos los archivos de la carpeta? ¿Incluyendo subcarpetas y/o archivos en subcarpetas? ¿Qué se supone que coloque en "ubicación"?
3. En la parte de librerías, no entiendo el formato "librería_1: función() / módulo". Tampoco el "(debe instalarse)". ¿Eso no aplica para todas las librerías? Tienen que importarse, ¿no? Luego en las librerías propias, ¿eso no es lo mismo que los módulos que uno crea?
Muchas gracias de antemano.

**Comment by Benjeeeh** [comment]
Hola!
1.- Si, debes dejar solo el emoji de acuerdo al grado de cumplimiento de lo que se pide. Con "Agregarlos al título" se refiere a agregarle uno de los 3 emojis a la sección correspondiente, por ejemplo, en este caso está la sección de Menú, por lo que podrías agregarle un emoji al lado de acuerdo al cumplimiento de esa sección y que tenga coherencia con lo de cada ítem (Si están todos los ítems completados, entonces puedes poner el check verde a Menú, y así).
2.- No es necesario poner todos los archivos de la carpeta, eso es solo en caso de que tengamos que crear un archivo o carpeta adicional para que funcione tu programa. En este caso no se debería agregar nada. Lo que si es importante en esta sección es que **escribas el nombre de tu archivo principal**, es decir, el que debemos ejecutar (usualmente main.py) para así correr tu programa.
3.- Te explico el formato de las librerías con un ejemplo: Si ocupas random, tienes que especificar que funciones de random utilizaste. Siguiendo el formato, quedaría como: random: randint()... etc. Lo de instalar las funciones es para casos especiales, es por si ocupas una librería que se deba instalar. Esto es para que la persona que te corrija esté al tanto de esto, ya que debe instalar esta librería (que tu la tengas no significa que la otra persona la tenga). Ten cuidado si, [siempre consulta en la lista de librerías prohibidas](https://github.com/IIC2233/Syllabus/issues/55) en caso de utilizar una que no esté descrita ahí, sobre todo si tiene que instalarse.

Saludos y espero que te haya quedado claro!

**Comment by martina-abello** [comment]
Muchas gracias!
¿Y la parte de módulo del formato? ¿Qué va ahí?

**Comment by Benjeeeh** [comment]
Tienes que agregar en que archivo se encuentra implementada esta función. Si random está en "juego.py", agregas eso.
