### ISSUE TITLE
PyQt5

### ISSUE THREAD

**Issue by B-Dominguez** [IIC2233/Syllabus#640]
Hola, antes estaba trabajando en otro computador y ahora que estoy en el mío, tengo ciertos problemas. QSound.Play() no hace nada, por lo que quise intentar probarlo dentro de un QMainWindow o un QObject como se sugería en otra issue, pero mi PyQt5.QtGui no tiene QMainWindow ni QObject, no sé por qué. Traté desinstalarlo e instalarlo denuevo, usar pip, y ejecutar el configure.py, pero no hay caso. Hay alguna guía de como hacer esto correctamente desde cero? o algún problema que pueda no estar viendo?

Gracias, estoy un poco desesperado porque no puedo probar nada

**Comment by iqacevedo** [comment]
Hola
Has leído los problemas y soluciones que han surgido este semestre en otras Issues respecto a PyQt5?
Están [aca](https://github.com/IIC2233/Syllabus/issues?q=label%3ASetup+is%3Aclosed)

Saludos!

**Comment by Hernan4444** [comment]
@B-Dominguez QMainWindow no está en PyQt5.QtGui sino en PyQt5.widget. Si no es ese el error, recomiendo leer las otras issues y si no está la solución avisanos.

Saludos

**Comment by B-Dominguez** [comment]
@Hernan4444  no no era eso jajaj había probado con QtWidgets
@iqacevedo había leído casi todas
Peeero entre esas issues y mucho google descubrí que tenía hartos problemas, principalmente con los paths de instalación, y ya logré hacerlo funcionar! Gracias a ambos :)
Lo único eso sí, pycharm como que no me reconoce los módulos (me aparece como Unresolved Reference al importarlo y no me muestra las opciones de autocompletar los métodos), pero al correr el script si funcionan. Alguna razón por la que pueda ocurrir esto?

**Comment by MainScientist** [comment]
@B-Dominguez La razon por la cual pasa eso es porque pycharm referencia el auto completado desde la raiz de tu proyecto, es decir si tienes un modulo en `/Tareas/T07/modulo.py`  pycharm entendera que el import es `Tareas.T07.modulo`. Esto se puede arreglar marcando tu carpeta `T07` como source root. Para eso puedes hacerle click derecho,  apretar `Mark Directory As` en el menu y luego `Sources root`.
