### ISSUE TITLE
Colisión bordes del mapa

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#640]
Hola, 
Para las colisiones con el borde del mapa podemos usar simplemente propertys o necesariamente debe haber una señal que indique que hubo una colisión y a partir de ahí evitar que siga avanzando?

**Comment by ptflores1** [comment]
Hola !
Puedes usar properties o señales, es decision tuya pero lo recomendado es usar señales, el programa va a funcionar mucho mejor con las señales porque los objetos funcionan independientemente.
Saludos !
