### ISSUE TITLE
Ayudante disponible?

### ISSUE THREAD

**Issue by ptflores1** [IIC2233/Syllabus#640]
Hola ! Algún ayudante que me pueda dar una manito con la materia de la tarea mañana en la mañana  o en la tarde despues de las 5:00 ? Gracias !

**Comment by FernandoPieressa** [comment]
Hola! Recuerda usar el mail de contacto ayudantesiic2233@gmail.com para casos personales.

Saludos!

**Comment by ptflores1** [comment]
Perdon !
