### ISSUE TITLE
Duda con ejercicio 5 contenidos

### ISSUE THREAD

**Issue by chubretovic** [IIC2233/syllabus#640]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola, tengo una duda con el ejercicio 5. Al usar la celda para corroborar el código, me arroja puros diccionarios vacíos. La cosa es que al editar la ultima línea de esa celda, en vez de impimir p.\__dict__, imprimo solo p, me aparecen objetos de la clase Película (<__main__.Pelicula object at 0x0000016FD6815688>), pero lo extraño es que si imprimo p.title, me arroja el error __'Pelicula' object has no attribute 'title'__. 
No se en que estoy fallando.

**Comment by aaossa** [comment]
Hola @chubretovic , ¿cuáles *keys* te aparecen en `p.__dict__`? Recuerda además que debes agregar reemplazar el diccionario de cada instancia dentro de `__setstate__`: `self.__dict__ = state`. Ojalá te sirva esta última recomendación, pero sino cuéntame qué te aparece dentro de `p.__dict__`. Que te vaya bien con tu estudio ✨

**Comment by chubretovic** [comment]
Hola profesor, me sirvió la última recomendación.
Muchas gracias.
