### ISSUE TITLE
AP01 Falta de implementación en identidad DCComida

### ISSUE THREAD

**Issue by jarvasquez** [IIC2233/syllabus#640]
Según parece la función clientes_dieciocheros implementa un sorted que va comparando instancias de la clase DCComida. El problema es que esta clase no es capaz según mi parecer de comparar dos instancias de la clase. A menos que se implemente el constructor `__lt__` ('_less than_´). ¿Es cierto esto?

Muchas gracias por su tiempo y disposición, quedo atento!

Saludos y feliz 18!!

**Comment by jarvasquez** [comment]
Encontré otro problemita.

En el archivo calcular_datos.py creo que existe un error en una línea. En una de las líneas después del __name__ dice:
`costo_envio = calcular_costo_envio(clientes.comidas, costo_base)`

Cuando la clase DCCliente no tiene atribuido ese atributo. Creo que para poder arreglarlo hay que usar la función comidas_dieciocheras_por_cliente(cliente, dccomidas), bueno y también se tendrían que cargar los datos de las comidas desde el archivo csv.

Es correcto?

Muchas gracias!

**Comment by IgnacioPorte** [comment]
Holaa jarvasquez !!
Disculpa por la demora, respecto a tu primera pregunta es cierto lo que dices, pero también puedes borrarle la key al sorted para que te ordene correctamente las llaves del diccionario que corresponden a los nombres de los clientes y respondiendo a tu segunda duda lo que dices es correcto, pero es más simple cambiar el cliente.comidas por cliente.ids_comida
