### ISSUE TITLE
TXX: cuales y como en archivos a subir

### ISSUE THREAD

**Issue by StroveLight** [IIC2233/syllabus#640]
¿Cuales son archivos y las ubicaciones que se deben subir para la tarea XX?

**Comment by Hernan4444** [comment]
Hola,

Ambas respuesta están en el enunciado. (Primeras líneas de la primera hoja y sección de metodología de corrección)

Saludos ✌️

**Comment by bjruano** [comment]
Entiendo que no hay que subir, pero los archivos test.py y exceptions.py deben ser subidos? Pues esos no debemos editarlos pero no dice que no hay que subirlos.

Gracias 😄

**Comment by Hernan4444** [comment]
No hay necesidad, si quieres subirlo para tenerlos en tu repositorio, adelante c:

Saludos ✌️
