### ISSUE TITLE
Primer Sample Formula Ecualizador

### ISSUE THREAD

**Issue by RickyUC** [IIC2233/Syllabus#641]
Hola,
no logro entender como se debe aplicar la formula al primer sample del canal, es decir cuando `i=0`.
En el pie de pagina sale que debemos tomar  `i - 1 = 0`, por lo que en vez de `sample_nuevo-1` quedaría `sample_nuevo0`, pero ese es justamente el primer sample que se quiere calcular.

Creo que la inquetud de la ultima pregunta de #619 es la misma, pero aún no tiene respuesta y la issue se encuentra cerrada.

Agradecería me pudieran aclarar como ocupar esta fórmula.
Saludos.

**Comment by arturodelreal** [comment]
Hola, considera que `sample_nuevo0` =  `(sample_antiguo0 +  sample_antiguo0)/2`
Saludos

**Comment by RickyUC** [comment]
Gracias!
