### ISSUE TITLE
Cambios de linea

### ISSUE THREAD

**Issue by sofiaolmedos** [IIC2233/syllabus#641]
Hola! Me acabo de dar cuenta que una linea de mi código tiene un error. ¿Cómo lo puedo hacer para el cambio de línea? El formulario que subieron es solo para commit anteriores.

**Comment by jarvasquez** [comment]
Al parecer no se puede, según el anuncio que pusieron en canvas no existirá formulario para entregas atrasadas

![image](https://user-images.githubusercontent.com/68974390/93649657-dafa8e00-f9e2-11ea-8626-862dc3f79e76.png)

Este es el link del [anuncio](https://cursos.canvas.uc.cl/courses/18383/discussion_topics/161337)

**Comment by sofiaolmedos** [comment]
@jarvasquez pero igual no entiendo. Porque en la pauta está el descuento por cambio de lineas (hasta 5 líneas) pero no se como hacerlo.
Gracias igual

**Comment by jarvasquez** [comment]
Tal vez mandar mail sirva por lo menos para declarar que lo hiciste hace rato el cambio y el commit

![image](https://user-images.githubusercontent.com/68974390/93651240-2f077180-f9e7-11ea-99ee-9b985d1b9748.png)

Y agregar el commit que hiciste el cambio.

**Comment by sofiaolmedos** [comment]
@jarvasquez voy a hacer eso, gracias!!
