### ISSUE TITLE
Duda con la lectura por chunks: no cargar todos los bytes para leer

### ISSUE THREAD

**Issue by Pabloski100** [IIC2233/syllabus#641]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Como podría leer un archivo por chunks sin leer todo el archivo primero

Hola, haciendo ejercicios me surgió una duda sobre este tema, se supone que el fin de leer un archivo en chunks es
evitar leer todo el archivo de una vez, sin embargo, hasta ahora siempre he estado haciendo algo como lo siguiente:

```
bytes_archivo = archivo.read()

for i in range(0, len(bytes_archivo), tamaño_chunk):
    chunk = bytearray(bytes_archivo[i:i+tamaño_chunk])
```

No estoy seguro, pero me da la impresión de que esto no es lo ideal, ya que antes de leer por chunks cargo todo el archivo, ¿Existe una manera de ir leyendo por chunks iterativamente sin cargar todo el archivo antes? (Imagino que se puede usar `chunk = bytes_archivo.read(tamaño_chunk)` pero ahí no se me ocurre como hacer una iteración que se detenga cuando sea necesario)

**Comment by StroveLight** [comment]
Hola! La idea del chunk es la correcta. Asumiendo que abriste el archivo en modo de leer bytes, y sea ```acrhivo``` el file abierto, puedes hacer ```archivo.read(n)``` para leer ```n``` bytes. Y cuando el ```read(n)``` te retorne un bytearray vacío es porque ya leiste todo el archivo.
