### ISSUE TITLE
TXX:  tipo de árbol

### ISSUE THREAD

**Issue by isihirmas** [IIC2233/syllabus#641]
Hola! Cuál es la diferencia entre un heap binario y el árbol que nos están pidiendo? O son lo mismo?

Gracias!

**Comment by Hernan4444** [comment]
Hola, su diferencia está en el nombre y que estamos condicionando la forma de implementar este árbol y que el Heap posee más funcionalidades que las pedidas en esta tarea. 

Saludo :v:

**Comment by isihirmas** [comment]
Pero condicionando en qué sentido? Porque un heap sort también va a hacer swapping y va a dejar el mínimo valor en la raíz. Lo que no estoy segura es si el heap posee la característica de completar primero un nivel y después siempre llenar primero a la izquierda .

**Comment by Hernan4444** [comment]
Hola

Está condicionado porque pedimos que lo implementes como árbol con nodos hechos con objeto, pero esto se podría implementar, por ejemplo, con matriz de adyacencia, pero eso no estamos permitiendo.

 Y para esta tarea no es relevante cómo funciona un heap porque nosotros te explicamos cómo funciona nuestro AlgarroboTree y eso es lo que pedimos implementar. Recomiendo no darse vuelta con otro estructura de dato que nunca se han mencionado.

Saludos :V:

**Comment by isihirmas** [comment]
Es que estoy confundida con la modelación del reordenamiento, acabo de hacer un commit lo podrías revisar? Solo para saber que voy bien encaminada con el árbol.

Gracias!
