### ISSUE TITLE
Para que mi PC sobreviva IIC2233

### ISSUE THREAD

**Issue by sbcorrea** [IIC2233/syllabus#641]
¡Hola! Vengo a preguntar algo técnico sobre la interaccion OS-IDE para cuidar mi compu en cuarentena :sweat_smile:

**IDE: VSCode**
**OS: Windows 10**
**Procesador: i3 dual core 2.1GHz**
**RAM: 4G**
**Disco duro: SSD 128G**
Edad: 1 año 2 meses, pero está como tuna :crown: 

He tenido algunos problemas con mi computador en los últimos contenidos, y de hecho los tuve durante la AS03. En el proceso de resolver los ejercicios y las actividades muchas veces el desafío es definir bien cuándo salir de un loop, y otras uno se mete en un loop sin querer y sin darse cuenta. Como es muy complicado tratar de resolver todo antes de correr por primera vez, tengo que muchas veces meterme a correr algo que sé que es probable que termine en un loop infinito. Cuando solo tenía loops simples esto nunca fue un problema; hacía kill terminal y seguía editando. Sin embargo, a medida que se van complejizando, y sobre todo ahora con threads simultáneos, mi computador se marea.

Ahora, sé que con los stats pareciera que mi compu ta chikito y no puele, pero juro que la SSD lo deja realmente muy potente. Le doy un uso bastante intensivo, y aún así anda igual de rápido que el día que lo compré y no ha fallado más de 5 veces en ese año y tanto. Obvio que la cuarentena tiene un nivel de exigencia terrible para la pobrecita (sí, femenino, se llama Azucena), pero no se ha derechamente pegado en nada excepto VSCode durante runs, y con threading me pasó muy seguido.

--------------------------------------
Por lo tanto, quería preguntar si puedo hacer algo para preparar a mi computador cuando sé que es probable que el siguiente run sea complejo.
--------------------------------------

:rainbow: :rainbow: :rainbow: **Por ejemplo, no sé si haya una extensión de VSCode que pause todos los otros procesos de mi computador cuando hago run,** :rainbow: :rainbow: :rainbow: porque generalmente cuando programo tengo abierto en otros escritorios virtuales:
* Enunciados y demases
* uno o varios jupyter notebook para saber qué hacer, con su(s) bash respectivo(s)
* Alguno que otro stackoverflow y/o discord y/o issues
* el bash para ADD-COMMIT-PUSH
* Mi repo en github para revisar el push
* 2 youtube al mismo tiempo (musica + ruido de lluvia, lo recomiendo)
* permanentemente 2 filtros de color para que no muera mi vista
* a veces, una segunda pantalla conectada por HDMI

así que, ¿quizás dejarle SOLO el run sea suficiente?  :rainbow: :rainbow: :rainbow: **También he notado que el run and debug tira pinta, pero no sé cómo usarlo ni si tiene algo integrado para este tipo de problemas.** :rainbow: :rainbow: :rainbow: En Intro vivía a base del debugger de PyCharm, así que traté de aprenderme el de VSCode a principio de semestre, pero no funcionaban tan parecido y no encontré un tutorial amigable. :rainbow: :rainbow: :rainbow: **Sé que podría yo misma anticiparme a los errores levantando excepciones,** :rainbow: :rainbow: :rainbow: pero suena como demasiado código que escribir solo para irlo borrando y rehaciendo en cada paso--la falla de mi computador me quitaría menos tiempo.

Si a mí me pasa esto con un computador que no falla para nada más y teniendo solo un ramo del DCC, me imagino que otra gente debe tener este problema mucho peor. :pray: :question: **Si fuéramos vari@s quienes tenemos este problema, me gustaría proponer algún tipo de ayudantía o videocápsula** :pray: :question: al respecto. A mí solo me quita tiempo, pero para alguien que estuviera usando un computador más viejo, lento o lleno, podría llegar a perjudicar el medio que necesita para todos los ramos :sweat::sweat: **A mí incluso me encantaría preguntar dónde encontrar recursos para optimizar PCs en general, para ayudar a mis amig@s que no saben de computación y se ven perjudicad@s en sus ramos porque su PC no puede con el teletrabajo** :cry:

Muchísimas gracias de antemano, porque ya leer esta issue era bien largo y sé que responderla es mucha pega. Un abrazo con distanciamiento social :hugs:

**Comment by entamburini** [comment]
Hola! buen uso de emojis :raised_hands: jejeje

La verdad es que _Azucena_ puede aguantar bien lo que son las exigencias del curso, te creo que se te haya quedado pegado porque tiene poca ram y le exiges bastante teniendo en cuenta todo lo que tienes abierto. 

En general la primera recomendación que te puedo hacer es dejar de utilizar VS code y empezar a utilizar Sublime Text (editor) + la consola (para correr tu código). Ahora que se viene la parte de interfaces gráficas, que en combinación con los threads puede que te lleve a uno que otro dolor de cabeza si tienes tantas cosas abiertas :disappointed:. También como recomendación general utilizar la consola para correr código de threads y de pyqt, es más confiable :wink: 

Para programar uno en general no necesita tantos recursos, pero si estás limitada, tienes que aprender a explotar de la mejor manera tu pc. Cuando di el ramo solucioné varios de mis problemas cambiando el sistema operativo, pero no es algo que todos estén dispuestos a hacer y es algo que es completamente ajeno a lo que el curso apunta, por eso nos limitamos a sólo enseñar el cómo instalar los editores de texto :sweat_smile:.

## Optimizadores

Quiero recordarte que cada computador es un mundo a parte, por lo que recomedarte "optimizadores" puede ser contraproducente. En específico, no hay un plugin que pause o mate procesos al momento de correr tu código, pero acá van algunos tips que funcionan en tu SO:

- Usa un editor ligero como sublime text y corre el código desde la terminal
- Revisa qué servicios se corren al inicio y averigua cuáles son útiles y cuáles inutiles, te ahorrarás harta RAM con eso :D.
- Si el computador se está quedando muy pegado o es muy antiguo, desactiva las animaciones de windows y algunos estilos visuales de windows que no son necesarios. Esto es drástico y puede hacer más "fea" la visual de tu computador, peeero aumenta bastante el rendimiento. 
- Como siempre, ten un número máximo de pestañas en chrome o el navegador que utilices, también hay extensiones que "matan" el proceso de pestañas que están abiertas durante mucho tiempo. 

Siempre puedes cambiar tu SO, pero esa es lección para otro día :wink: 

Saludos! :raised_hands:

**Comment by sbcorrea** [comment]
Buenisimoooo te pasaste! :star_struck: sobre tus recomendaciones, te podria hacer unas preguntas?
1. El solo hecho de editar en sublime ya aumenta el rendimiento, o la gracia de pasarme a sublime sería desinstalar VSCode para liberar ese espacio en disco duro?
2. No creo que llegue al punto de cambiar el SO, pero si algún día lo hiciera... Linux?

**Comment by sbcorrea** [comment]
PD: eliminé todas las animaciones innecesarias y no encuentro que quede feooo de hecho me gustó mucho más así jajaja

**Comment by entamburini** [comment]
Perdón la demora, es una semana complicada :sweat_smile: 

Sobre tus preguntas:
1. Dado que tienes poco espacio en tu disco duro, quizás sea buena idea pegarle una "limpieza" en cuanto a aplicaciones que tienes en tu computador. Pero el rendimiento lo verás al correr sublime (y ver lo nada que se demora en partir).
2. Linux es un sistema operativo de código abierto. Para computadores existen varias distros (algo así como variantes) disponibles y que puedes probar, entre las mejores para partir está Ubuntu y Manjaro. En general son sistemas operativos mucho más ligeros que windows, pero tienen una curva de aprendizaje que tienes que estar dispuesta a asumir :o. En lo personal, siempre que puedo utilizo linux, en mi trabajo y para cosas de la u que no requieran de MS Office (como excel principalmente) o de algún programa que no se encuentra disponible en windows.

No estoy seguro de si tu segunda pregunta era sobre qué era Linux o si quieres que nombre alguna distro en particular ajjaja, por eso traté de abarcar un poco de ambas :) 

Saludos! :v:

**Comment by fddelabarra** [comment]
Hola, queria decir que a mi me paso algo parecido en la AS03, pero yo tenia abierto el discord, el material con jupyter notebook y sublime text 3, que es lo que uso, pero aun asi no me cargaba una vez corria el codigo (lo corro en la consola git bash), bueno el domsday_clock si me corrio (aunque tardo como 2 o 3 min en que aparecieran los resultados impresos, me hizo pensar que no funcionaba por la tardanza), pero el de los lideres no corrio nunca, se mantenia como con una linea " | " como de que estaba cargando, espere mucho y nunca aparecio nada (ni errores ni resultados, solo seguia con esa "linea de texto"), al final tuve que recurrir a un ayudante que corrio el codigo por mi enviando el error que le daba (perdi mucho tiempo a causa de eso :c),
En resumen no se que tendria que hacer para que no me ocurra todo eso :c

**Comment by sbcorrea** [comment]
> Perdón la demora, es una semana complicada 😅
tranquiii, muchas gracias!
> No estoy seguro de si tu segunda pregunta era sobre qué era Linux o si quieres que nombre alguna distro en particular ajjaja, por eso traté de abarcar un poco de ambas :)
ups, perdon, jeje. Mi pregunta era si, en caso de cambiar el sistema operativo, la recomendación general era ubuntu (no sabía que habían otras variantes de linux)

**Comment by entamburini** [comment]
@fddelabarra, necesito más información de tu pc para discernir si es algo de tu computador, de tu código (dudo si le corrió al ayudante), o algo más. De todas partes 

@sbcorrea, la verdad es que linux lo puedes considerar como una "base" y las distros ocupan esa base, como por ejemplo Ubuntu. Peero también hay otras que también son user-friendly como lo son linux mint, manjaro, deepin, elemetary OS... son muchas! jajaja. Puedes averiguar un poco en google buscando "user-friendly linux distros". 

Que estén bien! :raised_hands:

**Comment by fddelabarra** [comment]
> @fddelabarra, necesito más información de tu pc para discernir si es algo de tu computador, de tu código (dudo si le corrió al ayudante), o algo más. De todas partes
>
Bueno, es Windows 10
El procesador es Intel(R) Core(TM) i5-6200U 
La Ram es de 4 GB
El tipo de sistema es de 64bits

Y efectivamente, al ayudante le corría y le marcaba el error, en cambio yo dejé que corriera como por 10 minutos sin mostrar ningún resultado ni error.

No sé si se necesita algo más, si es así, me avisas, gracias!

**Comment by entamburini** [comment]
@fddelabarra, 

Veo que son computadores similares 🤭. No sé por qué se puede deber, corres muchas menos cosas que tu compañera. Como dije cada computador es un mundo, por lo que sólo te puedo dar consejos generales (desgraciadamente no tengo tanto tiempo como podrás adivinar en la tardanza y horas en que respondo :sweat_smile:). 

Trata de correr tu código en el terminal de windows (cmd o powershell) y no git bash y dime cómo te va :thinking:. En cuanto a otros motivos, he visto que algunos computadores presentan discordancias por cómo windows maneja los threads, se soluciona actualizando drivers de la placa madre... Si no es ninguna de las dos opciones, no podría ayudarte más sin ver tu pc :c 

Espero que alguna de las cosas que te dije si ayude :)

**Comment by fddelabarra** [comment]
> @fddelabarra,
> 
> Trata de correr tu código en el terminal de windows (cmd o powershell) y no git bash y dime cómo te va . En cuanto a otros motivos, he visto que algunos computadores presentan discordancias por cómo windows maneja los threads, se soluciona actualizando drivers de la placa madre... Si no es ninguna de las dos opciones, no podría ayudarte más sin ver tu pc :c
> 
> Espero que alguna de las cosas que te dije si ayude :)


Acabo de probar correr el archivo con powershell y funcionó sin problemas!! Muchas gracias.
Solo me preguntó ahora por qué no corre en la terminar de git 🤔 
GRACIAS! 🥰

**Comment by entamburini** [comment]
Buenaaa @fddelabarra :raised_hands: 

En términos sencillos, git bash en windows es un terminal emulado -> simula las llamadas que normalmente se hacen en linux y las convierte en algo que windows entiende. Sin saber mucho el cómo está implementado, seguramente en la emulación tiene ciertas limitaciones con el acceso a los threads de windows. 

En el curso de Sistemas Operativos (si es que lo tomas) verás un poco más del por qué puede suceder.. y lo dicta uno de nuestros profesores! :D
