### ISSUE TITLE
Ayuda teclas :(

### ISSUE THREAD

**Issue by frduran** [IIC2233/Syllabus#642]
Por algún motivo al hacer el keyPressEvent y ReleaseEvent, si lo hago con las teclas de flechas no logro hacer que mi bomber se mueva pero si las cambio a otras teclas (ej asdw) si lo hace. Que podría estar pasando? Ayuda :(

**Comment by Sforrego** [comment]
Hola!

Prueba imprimiendo el event.key() para ver que pasa.

**Comment by nachocontreras** [comment]
Hola!

Probablemente no estás llamando bien a la flecha. Prueba imprimir event.key() dentro de la función keyPressEvent para saber a cual estás llamando.

**Comment by frduran** [comment]
Me imprime como el código de las teclas al apretarlas... de TODAS las teclas menos las flechas :(

**Comment by Sforrego** [comment]
Estas usando Qt.Key_Up?
🤔🤔

**Comment by frduran** [comment]
Si, con Down, Right y Left cuando corresponde.
(antes de eso tengo el print (dentro de la función keyPressEvent) y me capta todas las teclas menos las flechas)
Estaba leyendo en foros que necesito tener instalado pygame para que python reconozca las flechas así que probaré con eso...

**Comment by Sforrego** [comment]
Creo que ese error se puede solucionar seteando el focus. 

class FormWidget(QWidget):
    def __init__(self, parent):
        ... 
        self.setFocusPolicy(Qt.StrongFocus)

No es necesario tener instalado pygame.

**Comment by frduran** [comment]
Con eso se solucionó! Muchas gracias :)

**Comment by ValentinaAlvarezG** [comment]
Hola! creo que me pasa lo mismo con esas teclas pero no entiendo como solucionarlo. Donde creo esa clase FormWidget? y como la uso? :c
