### ISSUE TITLE
Problema Qsound

### ISSUE THREAD

**Issue by Dunkan1** [IIC2233/Syllabus#642]
cuando hago

self.sound = QSound("path", self)
self.sound.play()

reproduce una cancion sin "problemas"
lo malo es que no reproduce la cancion que le indico en el path
es como si tocara solo la musica que le gusta 😄

**Comment by arturodelreal** [comment]
Hola, elige canciones al azar, o es siempre la misma?

**Comment by Dunkan1** [comment]
siempre es la misma

**Comment by Dunkan1** [comment]
cuando se lo doy asi:
        self.sound = QSound(bla\\bohemian rhapsody, self)
        self.sound.play()
toca a cualquier otro de otra carpeta :(

**Comment by rrhurtado** [comment]
Hola!

Podrías verificar que haya un correcto uso de señales, quizás por ahí vaya el problema. Dejo la siguiente issue con un problema parecido, ojalá sirva #634

Saludos

**Comment by Dunkan1** [comment]
ya solucione el problema.
lo que ocurria es que al enviar las canciones se mezclaban los nombres
por eso reproducia el path correcto solo que la cancion incorrecta
