### ISSUE TITLE
Problema para reconocer paths en Visual Studio Code

### ISSUE THREAD

**Issue by benjaguiloff** [IIC2233/syllabus#642]
Hola! Perdón de antemano por escribir un domingo, pero tengo un problema desde la actividad del jueves que no he podido solucionar :cold_sweat:

Al intentar ejecutar el archivo `main.py` desde la terminal de VS Code, me mustra el siguiente error:

![Captura de pantalla (36)](https://user-images.githubusercontent.com/48481681/81513285-59d51100-92f5-11ea-858c-42e121eb1177.png)

He intentado un par de cosas pero no logro entender de donde viene el problema. Haciendo prints, me dí cuenta de que el path se imprime bien (es decir, se imprime como `datos\pin_tweets.csv`) hasta antes de llegar a la linea `with open(path, 'r', encoding='utf-8') as archivo:` del archivo `cargar_tweets.py`, que es donde se produce el error.
Cuando hago correr el archivo en el IDLE de python no ocurre este problema, por lo que supongo que debe ser un problema de configuración de vscode, pero no he encontrado una solución en internet.

**Comment by KnowYourselves** [comment]
Hola @benjaguiloff!

Por lo que veo estas corriendo tu programa desde la UI de vscode. El problema con esto es que te ejecuta el programa haciendo uso de paths absolutos, esto quiere decir que todos los path relativos dentro de tu programa serán leídos desde el inicio del disco C.

Puedes modificar este comportamiento instalando extensiones de VSCode y modificando algunas configuraciones, pero para efectos de este curso te recomiendo abrir una terminal dentro de vscode y correr tus programas haciendo uso de `python3 <nombre>.py` siendo `<nombre>` el script que quieres ejecutar.

Si no sabes como abrir una terminal dentro de VSCode dime y te explico!

Espero haberte ayudado.

**Comment by benjaguiloff** [comment]
Buenísimo, ahí me funciono! Gracias!

Estoy abriendo la terminal con Ctrl + ñ y luego moviéndome hasta llegar al directorio donde está el archivo que quier ejecutar. No hay alguna forma de abrirlo directamente en el directorio del archivo?

**Comment by KnowYourselves** [comment]
Si tienes abierto vscode en la carpeta donde estas trabajando te debiésen salir los archivos al costado izquierdo de la UI. Si haces click izquierdo en algun arhivo/carpeta te saldrá la opción de abrir una terminal ahí.

Cuéntame que tal!
