### ISSUE TITLE
Pyuic

### ISSUE THREAD

**Issue by valeria-adasme** [IIC2233/Syllabus#642]
Hola, no entiendo cómo leer el archivo .ui que entrega QT designer desde Python, y leí en internet que se puede hacer con esa herramienta (librería? ni idea) del título, que convierte los archivos a .py 
¿Podrían explicarme cómo se usa? Encontré su ubicación pero no logro ejecutarla correctamente, no sé si el archivo ui debe estar en la misma carpeta o qué

**Comment by naazocar** [comment]
A mi me funciona con la terminal (dentro de la carpeta donde está el .ui) hacer, por ejemplo: pyuic5 juego.ui -> juego.py , no sé si en todos los casos sea igual, pero ve si te funciona

**Comment by felipecr00** [comment]
lo que yo hago al menos es en el modulo donde quieres usar tu interfaz
```
from PyQt5 import uic
ui = uic.loadUiType("como_le_pones_a_la_interfaz.ui") #podria ser una ruta tmbn
```
despues en la clase donde vas a usarla paso los argumentos asi (por que se entregan dos argumentos al usar esa funcion).
```
class MiClase(ui[0],ui[1]):
    def __init__(self):
        super().__init__()
```

**Comment by fdominguezclaro** [comment]
Hola! 

Para usar una interfaz creada con designer:

```
from PyQt5 import uic

miui = uic.loadUiType(“path”).

class MainWindow(miui[0], miui[1])
   pass

```

Saludos!!

**Comment by valeria-adasme** [comment]
Escribí esto, pero no logro abrir la ventana:
from PyQt5 import uic

miui = uic.loadUiType("prueba.ui")

class MainWindow(miui[0], miui[1]):
    
    def __init__(self):
        super().__init__()

intenté con show y con run x-x no entiendo bien cómo funciona la clase anterior antes definida

**Comment by naazocar** [comment]
Pusiste el self.setupUi(self) ? Despues de eso faltaría el .show() luego de instanciar la clase
