### ISSUE TITLE
Posible error archivo solution_tree_2

### ISSUE THREAD

**Issue by aacifuentesb** [IIC2233/syllabus#642]
Hola! Me parece que hay un error en el archivo solution_tree_2.json  

Ese arbol debiese generarse con la segunda lista del archivo trees_build_and_save.json, donde hay un 229 en vez del 299 que aparece en solution_tree_2.json  .

Gracias!

**Comment by Hernan4444** [comment]
Hola
Efectivamente se nos pasó ese número, era 229. Se acaba de actualizar el archivo

Saludos ✌️
