### ISSUE TITLE
Actividad AP01 / Comidas Dieciocheras

### ISSUE THREAD

**Issue by pedroriosg** [IIC2233/syllabus#642]
Hola! Creo que hay un error al momento de definir la clase `class DCComida` al momento de definir el atributo `dieciochera.` Por algún motivo, al ejecutar el código me aparecen que todas las comidas son dieciocheras (True).
Ojalá que me puedan ayudar con esto.

Gracias!!

**Comment by francisca0308** [comment]
Hola!
Efectivamente hay un problema en el código. Que al definir el ```self.dieciochera```, se usa ```bool(dieciochera)``` que toma como True cualquiera de los dos casos. Esto se puede arreglar creando una función de este estilo:
```    
    def ver_dieciochera(self, dieciochera):
        if dieciochera=='True':
            return True
        return False
```
y llamado a esta al momento de definir el atributo:
```
    def __init__(self, id, nombre, precio, dieciochera):
        self.id = int(id)
        self.nombre = nombre
        self.precio = int(precio)
        self.dieciochera = self.ver_dieciochera(dieciochera)
```
o de cualquier otra forma que se te ocurra. Perdón por el error y no dudes en escribir más _issues_ si te surgen más dudas en el camino.
