### ISSUE TITLE
Indexar en bytearrays

### ISSUE THREAD

**Issue by Piolawa** [IIC2233/syllabus#642]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda
Hola, no entiendo bien por qué al indexar en un valor entrega valores en hexadecimal, pero al indexar en un conjunto de valores, entrega el bytearray normal.
Como ejemplo, el ejercicio 1 de esta semana que estoy resolviendo:

``` python
for i in range(0, len(lectura), TAMANO_CHUNK):
    print(bytearray(lectura[i]))  #solo deberia retornar el valor en i
    print(bytearray(lectura[i:i+TAMANO_CHUNK])) #retorna el valor que está desde i hasta i + TAMANO_CHUNK

```
Output:
Primer print:
``` python
bytearray(b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
```
Segundo print:
``` python
bytearray(b'BM\xba\xfb\xdd\xfb\x01\x00')
```
Esperaba que el primer print entregara: ```bytearray(b'BM)```

**Comment by StroveLight** [comment]
Hola! Esto ocurre porque a bytearray le estás pasando un ```int``` como argumento. Y lo anterior ocurre porque ```lectura[i]``` es un ```int```. 

Cuando se le pasa un int ```n``` a un bytearray como un argumento, el bytearray queda con tamaño ```n```, y con todos sus bytes con valor 0. [(ver documentacion)](https://docs.python.org/3/library/stdtypes.html#bytearray)

Si deseas que se printee un solo byte en vez del int, puedes usar ```lectura[i:i+1]```, que te da un arreglo de bytes que contiene solo la casilla deseada

**Comment by Piolawa** [comment]
@StroveLight resultó lo que queria, y entendí lo que dijiste, gracias!
Pero me surge una duda media tonta, es que no entiendo en verdad que piden en este ejercicio propuesto, que debería obtener.
Tienes algún archivo de como debería quedarme el simpatico.bmp? unu

**Comment by StroveLight** [comment]
Lo siento, no veo los ejercicios propuestos, por lo que desconozco el resultado. Sin embargo, al ser el archivo resultando uno con extensión ```.bmp```, probablemente sea una imágen que puedas abrir y ver. Como se pide encriptar y desencriptar la imágen, probablemente comparando la inicial y la desencriptada puedas ver si estás haciendo las cosas bien

**Comment by Piolawa** [comment]
ahi caché, si resultó, graciaaas! uwu
