### ISSUE TITLE
Elementos Gráficos Básicos: Imagen no se muestra en PyQt, error no aparece.

### ISSUE THREAD

**Issue by Daniel-SebastianGaete** [IIC2233/syllabus#643]
Hola. Estaba revisando el contenido de la semana y al probar el código de la se sección Imágenes de Elementos Gráficos Básicos en Visual Studio Code el código corre pero la imagen no aparece. El código está copiado y pegado sin ninguna modificación. ¿Algún consejo para encontrar el error?

**Comment by fdoflorenzano** [comment]
Hola @Daniel-SebastianGaete,
Que bueno que preguntaste, ya que esto puede que le ocurra a más de una persona si no tiene cuidado. Es un error *"silencioso"* de PyQt, ya que no levanta una excepción.

Usualmente este error es debido al acceso de la imagen, específicamente al lugar donde ejecutas el código y la ruta relativa a la imagen que intentas cargar. Mencionas que copiaste y pegaste el código, pero ¿dónde se encuentra el archivo que estás ejecutando? ¿ese archivo tiene acceso mediante la misma ruta del ejemplo a la imagen? ¿desde dónde se ejecuta el código que estás probado?

Para asegurar que tiene acceso tu programa a la imagen, puedes agregar el siguiente código que utiliza el método `exists`. Este revisa la existencia de un archivo o directorio según una ruta:
```python
import os

print(os.path.exists(ruta_a_imagen))
```

Si imprime `True`, es porque tiene acceso, si imprime `False`, no tiene acceso y algo debes arreglar.
Si imprime `True` y aún así no aparece, entonces debe ser otro el problema.

Quedamos atentos.
Saludos.

**Comment by Daniel-SebastianGaete** [comment]
Efectivamente el problema era con respecto al lugar del archivo. Quedó corregido. Muchas gracias.

**Comment by fdoflorenzano** [comment]
Súper @Daniel-SebastianGaete.

No cierres la *issue*, este puede que le sirva a más de una persona. Luego de un tiempo la cerraremos nosotres. :)

**Comment by jtmeyer98** [comment]
Hola, estoy frente al mismo problema pero no puedo solucionarlo.
Tengo la imagen en la misma carpeta que el archivo de python.
La imagen se llama python.jpg.
Estoy con VS Code.

el codigo: 

ruta_imagen = os.path.join('python.jpg')
print(os.path.exists(ruta_imagen))  

me imprime False. 

¿Que puedo hacer?

**Comment by fdoflorenzano** [comment]
Hola @jtmeyer98,

Si imprime `False` pero el archivo está bien ubicado, quiere decir que el directorio de ejecución no corresponde a lo que esperas. Recuerda que siempre que se ejecuta un programa, este lo hace desde algún directorio del computador, que no necesariamente corresponde al directorio donde está el archivo que deseas ejecutar. Luego, puedes ejecutar un programa de otro directorio, y cualquier tipo de ruta relativa (como la de la imagen) lo será al directorio de ejecución. 

Si usas VS Code y ejecutas tu código desde ahí, revisa que estés navegando **desde** el directorio del archivo que deseas ejecutar. Ya que por defecto VS Code define su directorio de ejecución el que tiene abierto para navegar.

Por ejemplo, en la siguiente imagen, veo una porción de VS Code, donde navega desde el directorio `ejemplo` y el editor muestra `main2.py`, que está dentro de una carpeta `dudas_1`, dentro de `ejemplo`. Si intento ejecutar `main2.py`, VS Code ejecuta el código desde `ejemplo`, no `dudas_1`, y la ruta `'python.jpg'` pierde sentido desde ahí.

<img width="642" alt="image" src="https://user-images.githubusercontent.com/13511560/82491429-a1f0f200-9ab2-11ea-9022-9ef969359977.png">

Pero si cambias el directorio raiz de navegación (mediante una opción *Open* o *Abrir* en el menú), puedo cambiar el directorio `dudas_1` directamente y donde al intentar ejecutar si funciona:

<img width="620" alt="image" src="https://user-images.githubusercontent.com/13511560/82491659-f005f580-9ab2-11ea-8e03-50c9985fc8f5.png">

Espero esto arregle tu problema, nos avisas que tal. 
Saludos.

**Comment by jtmeyer98** [comment]
Perfecto, ahora entiendo como funcionan los directorios!

Muchas Gracias!
