### ISSUE TITLE
Semana 05 - lamba

### ISSUE THREAD

**Issue by enriquemolinare** [IIC2233/syllabus#643]
hola no me queda claro cual  sería el X y el Y en esta función cuando se itera sobre conjuntos

conjuntos = [{3, 5, 1}, {4, 3, 1}, {1, 2, 5}, {9, 5, 4, 1}]

unión = reduce(lambda x, y: x | y, conjuntos)
intersección = reduce(lambda x, y: x & y, conjuntos)

print("Unión:", unión)
print("Intersección:", intersección)

**Comment by MatiasDuhalde** [comment]
Hola @enriquemolinare !

En general, lo que hace `reduce` es ir tomando los elementos del iterable, pasarlos por la función, tomar el resultado, y volver pasar el resultado junto con el valor siguiente del iterable por la función. Esto se repite hasta agotar todos los elementos del iterable, y retorna el resultado final.

Para este ejemplo específico, se tiene una lista que contiene 4 sets/conjuntos. Al pasar esta lista por reduce con la función `lambda x, y: x | y`, `x` e `y` tomarían los siguientes valores:
```python
# primer ciclo:
x = {3, 5, 1}
y = {4, 3, 1}
# segundo ciclo
x = {1, 3, 4, 5} # resultado de x | y
y = {1, 2, 5} # siguiente valor en la lista
# tercer ciclo
x = {1, 2, 3, 4, 5} # resultado de x | y
y = {9, 5, 4, 1} # siguiente valor en la lista

resultado_final = {1, 2, 3, 4, 5, 9} # resultado de x | y
```

Ahora, con la función `lambda x, y: x & y`, `x` e `y` tomarían los siguientes valores:
```python
# primer ciclo:
x = {3, 5, 1}
y = {4, 3, 1}
# segundo ciclo
x = {1, 3} # resultado de x & y
y = {1, 2, 5} # siguiente valor en la lista
# tercer ciclo
x = {1} # resultado de x & y
y = {9, 5, 4, 1} # siguiente valor en la lista

resultado_final = {1} # resultado de x & y
```

Como nota aparte, recuerda que los argumentos que recibe reduce son una función (que puede ser una "función normal" o una función lambda), y un iterable. En general es común usar funciones lambda debido a que son más fáciles de definir. Si lo haces con "funciones normales", puedes colocar prints para visualizar mejor como cambian `x` e `y` en cada ciclo, como en el siguiente ejemplo:
```python
from functools import reduce

def f_interseccion(x, y):
    print(f"X: {x}")
    print(f"Y: {y}")
    result = x & y
    print(f"result: {result}")
    return result

def f_union(x, y):
    print(f"X: {x}")
    print(f"Y: {y}")
    result = x | y
    print(f"result: {result}")
    return result


conjuntos = [{3, 5, 1}, {4, 3, 1}, {1, 2, 5}, {9, 5, 4, 1}]

unión = reduce(f_union, conjuntos)
print("Unión:", unión)

intersección = reduce(f_interseccion, conjuntos)
print("Intersección:", intersección)
```

Output:
```
X: {1, 3, 5}
Y: {1, 3, 4}
result: {1, 3, 4, 5}
X: {1, 3, 4, 5}
Y: {1, 2, 5}
result: {1, 2, 3, 4, 5}
X: {1, 2, 3, 4, 5}
Y: {9, 4, 5, 1}
result: {1, 2, 3, 4, 5, 9}
Unión: {1, 2, 3, 4, 5, 9}

X: {1, 3, 5}
Y: {1, 3, 4}
result: {1, 3}
X: {1, 3}
Y: {1, 2, 5}
result: {1}
X: {1}
Y: {9, 4, 5, 1}
result: {1}
Intersección: {1}
```

**Comment by enriquemolinare** [comment]
muchas gracias, me quedó súper claro
