### ISSUE TITLE
Giro imagenes

### ISSUE THREAD

**Issue by felipecr00** [IIC2233/Syllabus#643]
Puedo usar un sprite que represente el giro de mi personaje? (para no tener que girar el pixmap)

**Comment by tcgarrido** [comment]
Hola!

La idea es que manejes el giro de tu personaje rotando la imagen. Esto quiere decir que no deberías usar un sprite que represente cada ángulo de giro.

**Comment by PIPEAPABLAZA** [comment]
@tcgarrido eso quiere decir que se requiere únicamente de sprites del tipo "top view"? 
 Pregunto para asegurarme 😸

**Comment by tcgarrido** [comment]
Hola! 

Exactamente. Te recomendamos usar sprites de “top view”.

**Comment by ifcarrera** [comment]
Hola! Puedes usar las imágenes que estimes conveniente, pero se evaluará que puedas manejar la rotación de imágenes en PyQt; como dices, debes rotar el pixmap.
Saludos

**Comment by Javierdr** [comment]
@tcgarrido si ya lo hice con esprites para cada angulo puedo dejarlo asi ?

**Comment by tcgarrido** [comment]
Hola!

En esta tarea evaluaremos el correcto uso de interfaz para manejar el cambio de ángulo. Por lo tanto, si lo dejas así no tendrás el puntaje correspondiente.

**Comment by mesantamaria** [comment]
@tcgarrido Hola, hay algún descuento si los sprites no son top view?
Creo que igual se entiende si es que son mirando "de lado" y pueden girar (para llegar a todas las direcciones).

**Comment by tcgarrido** [comment]
Hola!

No habrá descuento si usan sprites que no son “top view”.
