### ISSUE TITLE
Interaccion QListWidget con QTextEdit

### ISSUE THREAD

**Issue by KnowYourselves** [IIC2233/Syllabus#643]
En mi interfaz de sala tengo varias QListWidget y un QTextEdit, mi problema es que cada vez que ocupo el comando `QListWidget.clear()` de alguna de las listas esto tambien elimina el contenido del objeto QTextEdit, hay alguna forma de evitar que pase esto? o debería simplemente evitar usar clear?

**Comment by rrhurtado** [comment]
Hola!

Siendo un QListWidget independiente de otro QTextEdit, al usar `QListWidget.clear()` no debería ocurrir ese problema. Puede ser que haya alguna dependencia entre ambos objetos.

Prueba usando `QListWidget.takeItem (self, int row)` haber si el problema continúa.

Saludos

**Comment by KnowYourselves** [comment]
Con ese comando me sirvió perfect!, lo que si no entiendo por qué habría una dependencia, cree los objetos list y el objeto textedit desde designer, pero bueno, usando takeitem el textedit no se ve afectado. Gracias!
