### ISSUE TITLE
Duda pickle ayudantia 

### ISSUE THREAD

**Issue by Nicolemarin** [IIC2233/syllabus#643]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola! Tengo una duda de la ayudantia. En el ultimo ejercicio, la parte de pickle. guando usamos la funcion guardar instancia, queremos guardar una intancia de EquipoDocencia, en un archivo vacio. Pero al hacer pickle.dump, se supone que deberia entrar a un _ getstate _,. pero segun lo que tengo entendendido deberia entrar a un getstate DE la clase Equipodocencia, pero el unico que getstate que creamos fue en la clase AyudanteJefe.
no entiendo bien.. por que el getstate no está dentro del EquipoDocencia

o quizas se equivocaron y deberiamos guardar_instancia de AyudanteJefe?

**Comment by Julius9** [comment]
Hola Nicole, estas un poco confundida. Cuando se hace pickle.dump se entra al metodo ```__setstate__``` para setear el estado del objeto y serializarlo. Al principio de la parte pickle nosotros definimos el ```__setstate__``` del EquipoDocencia el cual es el objeto que necesitamos serializar.

Cuando se hace pickle.load se entra al metodo ```__getstate__``` para "tomar" el estado serializado del objeto y poder hacer una deserialización personalizada.
