### ISSUE TITLE
Recortar asset

### ISSUE THREAD

**Issue by ljrodriguez1** [IIC2233/Syllabus#643]
Mi duda es la siguiente, dado que los asset de bomberman vienen todos juntos en una imagen nosotros debemos cortarlos. quisiera saber si existe alguna manera de utilizar la imagen completa sin tener que cortarla. con alguna función de python que me permita elegir solo algunos pixeles de la imagen?. o si realmente lo mas conveniente seria cortarla.

**Comment by yoavnavon** [comment]
Hola! Hay varias manera de resolver tu problema. Una puede ser cargar la imagen completa en un pixmap. Despues, con la funcion copy de pixmap puedes generar una copia  de algun cuadrado de la imagen no necesariamente completa. Por ultimo, esta copia tendrias que pasarsela a la funcion setPixmap del label.

**Comment by Sforrego** [comment]
También puedes usar shoebox render para que corte tu imagen y te devuelva los sprites separados.
