### ISSUE TITLE
Problemas con instalación PyQt5

### ISSUE THREAD

**Issue by mariaignaciag** [IIC2233/syllabus#644]
Hola! he tenido un par de problemas al instalar la librería nueva, a lo que terminé desinstalando todo lo que tenía instalado para empezar de nuevo 😢 literal hasta Python, con tal que instale de nuevo Python 3.7.7 pero al ejecutar en terminal Python -V me sale la versión 2 (adjuntaré el archivo), sin embargo si coloco python3 -V me sale el 3.7.7 🙃,  asi que al instalar PyQt5 me tira error en la parte de withpython3, agradecería mucho su ayuda, porque llevo mucho tiempo tratando de arreglarlo y creo que la he embarrado más, y lo otro me gustaría saber que interfaz de desarrollo funciona mejor, porque la que tenía se me caía con el nuevo contenido, y por eso empezó todo esto.
![Captura de Pantalla 2020-05-11 a la(s) 17 25 02](https://user-images.githubusercontent.com/62075301/81613385-64061680-93ac-11ea-86f7-0734aba060c4.png)

**Comment by KnowYourselves** [comment]
Hola @mariaignaciag!
 
En primer lugar en cuanto a la diferencia entre escribir `python` y `python3`, sucede que todos los Mac vienen con `python2.7` instalado y asociado al comando `python`, por lo cual cuando instalas la versión 3.7, reconoce que el comando `python` ya esta ocupado y queda asociado a `python3`. Es por esto, que para efecto del curso siempre que ejecutes código debe ser con `python3`.

En cuanto acomo instalar `PyQt5` prueba con el siguiente comando:

```bash
pip3 install PyQt5
```
En caso de que no funcione, prueba con el siguiente comando: 

```bash
python3 -m pip install PyQt5
```
Espero que te funcione!

**Comment by mariaignaciag** [comment]
muchísimas gracias!, ahí me funcionó todo :simple

**Comment by mariaignaciag** [comment]
muchísimas gracias!, ahí me funcionó 😄

**Comment by KnowYourselves** [comment]
Que bien!!

PD: Recuerda no cerrar las issues inmediatamente 👀
