### ISSUE TITLE
Método Iter: Ejercicio propuesto 1.1

### ISSUE THREAD

**Issue by enriquemolinare** [IIC2233/syllabus#644]
Hola hay algo que no me queda muy claro con respecto al método iter. 
 Cuando en el metodo iter  retorno una lista me envia un error de TypeError: iter() returned non-iterator of type 'list' .  Sin embargo cuando retorno iter(lista) resulta todo ok. Mi duda es, si la lista ya es un objeto iterable, porque es necesario convertirlo en un iterador.
Además cuando se recorre una lista con un for no es necesario agregar un iter(lista), solo se debe poner la lista. Por ejemplo, se escribe "for elem in lista"  y no "for elem in iter(lista)".  Por lo tanto, porque envia TypeError cuando retorno una lista  cuando en realidad for si puede recorrer los elementos de una lista
```python
#TypeError
    def __iter__(self):
        lista_primos = []
        contador = self.inicio
        while contador <= self.fin:
            if es_primo(contador):
                lista_primos.append(contador)
            contador += 1  
        return (lista_primos)
    
#Correcto

    def __iter__(self):
        lista_primos = []
        contador = self.inicio
        while contador <= self.fin:
            if es_primo(contador):
                lista_primos.append(contador)
            contador += 1  
        #return iter(lista_primos)
        return iter(lista_primos)
```

**Comment by aaossa** [comment]
Hola @enriquemolinare , creo que tenías un poco enredado los conceptos al momento de hacer la pregunta. Perdón por responder tan tarde, pero espero que te sea útil de todas maneras 🙌 

Tal como dice la excepción que mencionas: `TypeError: iter() returned non-iterator of type 'list'`, una lista **no es un iterador**. Pero sí sabemos que **es un iterable**. ¿Qué implica que una lista sea iterable? Si una lista es iterable, entonces tiene implementado el método `__iter__`, y este método retorna un iterador. ¿Qué necesitaría una lista para ser un iterador? Si una lista fuera un iterador, entonces tendría implementado el método `__next__`. Sin embargo este no es el caso:

```python
# Una lista simple
a = [1, 2, 3]
# Tratemos de utilizar next()
next(a)
TypeError: 'list' object is not an iterador
# RIP 💀 
```

Ahora, volviendo a tu pregunta. En el método `__iter__` NO puedes retornar una lista, porque no es un iterable. Un iterable lo que hace es ir dándote uno a uno los elementos del iterador, pero la lista no puede hacer eso ya que no tiene implementado el método `__next__`. Que un objeto sea iterable no implica que sea iterador ❗.

Por otra parte, en un `for` no es necesario utilizar `iter(lista)` porque esos *loops* se aplican sobre iterables (de nuevo, una lista sí es un iterable, pero no un iterador) y le piden al objeto un iterable para recorrerlos (así es, llaman a su método `__iter__` 👀).

**PS:** Ojo con este comportamiento interesante, ¿puede un objeto ser iterable e iterador a la vez? *Spoiler*: sipis 😱
