### ISSUE TITLE
Modelación backend y frontend

### ISSUE THREAD

**Issue by sjkinast** [IIC2233/Syllabus#644]
Hola! estoy un poco confundido con respecto a que si el frontend solo se encarga exclusivamente de mostrar las imagenes o tambien es el encargado de como instanciar las clases y de hacer algunas funcionalidades. Entiendo que la idea es que hay que tratar de hacer todas la funciones en el backend pero no estaría mal que algunas cosas sean reguladas en el frontend o si ?, o si tengo que hacer cosas en el front end es porque estoy modelando mal?
Por ejemplo seria erroneo que el parent tuviese al mapa como un atributo?

**Comment by ptflores1** [comment]
Hola !
La idea como bien dices es que las funcionalidades de tu programa vayan en el Back End y todo lo relacionado con lo que se ve y se interactua en el Front. Muchas veces se pueden implementar las funcionalidades dentro del Front pero esta no es la manera correcta de crear la aplicación por varias razones 

- Habria baja cohesion porque el Front estaria haciendo trabajo del Back
- El programa es mas propenso a ser no modular porque van a estar compartiendo responsabilidades
- Si eventualmente quisieras cambiar el Front o el Back, lo mas probable es que tengas que cambiar ambos ya que serian dependientes

Todo esto esta mejor explicado en el [material](https://github.com/IIC2233/contenidos/blob/master/semana-10/5-Dise%C3%B1o-Front-Back.ipynb)

Una buena limitante de que puede hacer el Front y que no es pensar en si lo que esta haciendo realmente solo afecta a la interfaz, es decir si se quitase el codigo del Front, la aplicación puede seguir funcionando, obviamente no va a ser nada facil interactuar con ella ya que no tendremos la GUI, si no se esta cumpliendo esto es porque probablemente lo estas modelando con una mala separacion. En lo personal yo hacia una clase `BackEnd`que era instanciada dentro del Front y el Front solo contenia la logica necesaria para mostrar la interfaz basandose en el estado del Back. Espero hayas entendido.
Saludos !

**Comment by sjkinast** [comment]
En el caso de usar una clase que maneja todo el backend esta debiese heredar de Qobject?

**Comment by ptflores1** [comment]
Si accedes a las coordenadas solo para leer estaria bien porque tu Front esta cambiando en funcion del estado del Back, pero si el Front mismo hace los cambios en las coordenadas estaria mal, si quitaras el codigo del Front entonces ya no habria manera de que los personajes se movieran en el Back, con respecto a las señales lo que dije aqui #640 tambien aplica para lo que preguntas. En lo personal me gusta mas la ultima manera que dijiste para hacerlo, señal de ida y señal de vuelta
