### ISSUE TITLE
TXX: librería para __repr___

### ISSUE THREAD

**Issue by bjruano** [IIC2233/syllabus#644]
Hola! Quería saber si podría usar indent de la librería textwrap únicamente para simplificar la parte del __repr__ pues para saber lo que estoy haciendo, la estoy usando.

Gracias 😄

**Comment by Hernan4444** [comment]
Hola
En el enunciado, sección Restricciones y Alcance se especifica sobre el uso de librerías. Como consejo, si igual quieres usarla, adelante pero al momento de entregar recuerda eliminarla o no tendrás décimas por no respetar las Restricciones 

Saludos ✌️
