### ISSUE TITLE
Sample Rate / Ecualizador

### ISSUE THREAD

**Issue by RickyUC** [IIC2233/Syllabus#644]
Hola,
al multiplicar el sample rate  por el numero entre 0.5 y 3 el resultado es un float, por lo tanto lo paso a bytes como float. Pero mi consulta es, ¿tengo que asumir siempre que el valor que tiene el archivo es un `int`al momento de pasarlo a numero?
En ese caso, ¿Si los archivos de audio tienen siempre un int en esa sección, y  los programas de audio decodifican un ` int` de esos bytes, no se generan problemas de reproducción al entregar bytes que representan `float` en esa sección?

**Comment by DiegoAndai** [comment]
#595 (comentario 14) y #639
