### ISSUE TITLE
TXX: Funciones extra

### ISSUE THREAD

**Issue by ByronHidalgo1** [IIC2233/syllabus#645]
Hola,
En el módulo main.py, ¿puedo crear funciones extras que sean llamadas por las funciones que piden completar?
Ejemplo:

def search(tree_path, value):
    blabla
    be_path(tree_path)
    blabla

def be_path(tree_path):
    blabla

¿Puedo usar la librería pathlib? Esto debido a que no sé si los paths siempre estarán en la carpeta test.

**Comment by Hernan4444** [comment]
Hola
Si puedes crear funciones extras y no puedes usar librerías adiciónales. Este último punto se especifica en la sección Restricciones y Alcance del enunciado.

Saludos ✌️

**Comment by ByronHidalgo1** [comment]
En ese caso, ¿puedo suponer que los árboles de prueba estarán siempre dentro de la carpeta test?
Muchas gracias!

**Comment by Hernan4444** [comment]
No, no puedes asumir eso. En el enunciado incluso se indica que no puede asumir que las carpetas test y student_solution puedan estar. 

Solo puedes asumir que te entregaremos un path válido en la función 2 y 3, en la 1 puede ser inválido, pero con los contenidos del curso podrán solucionar ese problema.

Saludos ✌️
