### ISSUE TITLE
Error al ejecutar servidor.py 

### ISSUE THREAD

**Issue by barbaracalderonr** [IIC2233/syllabus#645]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Holaa, estaba revisando los contenidos de esta semana, y en la parte 2, de networking con python, en la parte donde servidor TCP, piden crear dos nuevos archivos para correr los códigos que aparecen, uno llamado servidor.py y el otro llamado cliente.py, pero cuando los corro me sale este error en servidor.py

OSError: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted

No sé si estoy haciendo algo mal, (no debería por que solo copié y pegué el codigo), o que pasa con esto, si pudieran guiarme en porque sale este error sería bacaan

**update: no había cachado que venían en otras carpetas, y al correr esos si m e funcionó, pero solo una vez, si los pongo a correr de nuevo me sale el mismo error:(
gracias!

**Comment by Julius9** [comment]
Hola Barbara :smile: cuando uno trabaja con sockets suelen aparecer con frecuencia estos errores extraños. Esto sucede muchas veces debido a que cuando se inicia un socket servidor y luego este se cierra (cerrando la consola por ejemplo) el puerto con el que estaba trabajando el socket se bloquea durante un periodo de tiempo y al intentar iniciar un nuevo socket servidor con este mismo puerto te aparecerán errores tipo como el que mandaste. Esto se puede solucionar simplemente cambiando el puerto del nuevo socket que utilizaras

**Comment by fernandosmither** [comment]
> ### Prerrequisitos
> (Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")
> 
> * [x]  Leí las reglas del foro (#1)
> * [x]  Busqué en las _issues_ si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
> * [x]  Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
> * [x]  Utilizaré un título descriptivo y llenaré correctamente esta plantilla
> * [x]  De ser necesario, colocaré código simple que permita explicar mi problema o duda
> 
> ### Duda
> Holaa, estaba revisando los contenidos de esta semana, y en la parte 2, de networking con python, en la parte donde servidor TCP, piden crear dos nuevos archivos para correr los códigos que aparecen, uno llamado servidor.py y el otro llamado cliente.py, pero cuando los corro me sale este error en servidor.py
> 
> OSError: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted
> 
> No sé si estoy haciendo algo mal, (no debería por que solo copié y pegué el codigo), o que pasa con esto, si pudieran guiarme en porque sale este error sería bacaan
> 
> **update: no había cachado que venían en otras carpetas, y al correr esos si m e funcionó, pero solo una vez, si los pongo a correr de nuevo me sale el mismo error:(
> gracias!

Tuve tu mismo problema (no soy ayudante) :( Pero a mi me funcionó printear en la consola el `socket.gethostname()`, y ponerlo manualmente como str en server_host de cliente.py.

También me di cuenta que dejar '' en el cliente a mi no me funcionaba, pero sí funciona si pongo '' en el servidor.py. ¿Pasará lo mismo en tu caso?

**Comment by juan-palma-1** [comment]
Hola me gustaría abrir nuevamente la pregunta pero con una variación, en mi caso se genera el siguiente error:

sock.bind((host, port))
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

busque en internet pero no pude encontrar solución al problema, estoy corriendo ambos archivos en dos terminales de OS y también lo intenté desde 2 ventanas de VsCode pero se genera el mismo error.

**Comment by fernandosmither** [comment]
> Hola me gustaría abrir nuevamente la pregunta pero con una variación, en mi caso se genera el siguiente error:
> 
> sock.bind((host, port))
> socket.gaierror: [Errno 8] nodename nor servname provided, or not known
> 
> busque en internet pero no pude encontrar solución al problema, estoy corriendo ambos archivos en dos terminales de OS y también lo intenté desde 2 ventanas de VsCode pero se genera el mismo error.

cómo definiste las variables host y port?

**Comment by juan-palma-1** [comment]
En cliente_tcp.py:
host = socket.gethostname()
port = 9000

En servidor_tcp.py:
host = socket.gethostname()
# print(host)
port = 9000

si printeo host en ambos archivos me arroja el mismo resultado:
nombre_de_mi_pc.local
