### ISSUE TITLE
Plazo entrega T06

### ISSUE THREAD

**Issue by asdegoyeneche** [IIC2233/Syllabus#645]
Hola! 

Se podría dar 1+ día(s)/horas más de plazo para la tarea?

Muchas gracias!

**Comment by iqacevedo** [comment]
Hola

Estamos evaluándolo. ¿Por qué crees que se necesita más tiempo para esta tarea?

Saludos !

**Comment by cilopez** [comment]
¿Quizás  hubo gente que tuvo problemas con el corte de luz o no ?

**Comment by frvalenzuela** [comment]
Yo estuve toda la tarde-noche del viernes sin luz ):

**Comment by anavarro01** [comment]
Hola. Yo tuve problemas con los cortes de luz. No pude hacer nada la tarde-noche del viernes ni casi todo el fin de semana porque no podía cargar mi notebook. Hablando con compañeros, hay varios que están en la misma situación.

**Comment by ignacioaraya1995** [comment]
Yo igual tuve problemas el viernes y todo el sábado.

**Comment by benjamimo1** [comment]
Yo tuve problemas de forma intermitente en mi edificio :(

**Comment by Arcoirisky** [comment]
Yo tuve como tres horas de luz el viernes y de ahí las luces iban y venían :( más iban que venían ;-;

**Comment by asdegoyeneche** [comment]
Sumándome a los demás, se podrían agregar las dificultades/confusiones que surgieron con el manejo de los bytes en los filtros y arrelgos de enunciado, lo cual significó tiempo y avance de la tarea

**Comment by flobarrios** [comment]
Estimados,

Tienen hasta el martes a las 23:59 para entregar la T06. Sin embargo, las fechas de la T07 se mantendrán y el enunciado se subirá hoy.

Saludos y mucho éxito programando!!
