### ISSUE TITLE
Cambiar nombres en parameters.py?

### ISSUE THREAD

**Issue by naquiroz** [IIC2233/Syllabus#645]
Quería saber si puedo ponerle otros nombres a las constantes que se piden tener en parameters.py? Particularmente quiero ponerle los nombres en ingles, por una cosa de comodidad nada mas.

**Comment by IchottMano** [comment]
@naquiroz Hola!

No hay problema con que cambies los nombres en el archivo. **Sin embargo**, debes especificar estos cambios en tu README, es decir explicitar que significan tus variables con los nombres cambiados, a modo de poder corregir.

Saludos!
