### ISSUE TITLE
Almacenar objeto de PyQt como atributo o como variable local

### ISSUE THREAD

**Issue by benjavicente** [IIC2233/syllabus#645]
No me quedó muy claro cuando se debe utilizar atributos en vez de variables locales para almacenar objetos de PyQt 🤔 .
```python
class MiVentana(QWidget):
    ...
    def init_gui(self):
        # como variable local
        obj = QObject()
        # como atributo
        self.obj = QObject()
```
Por lo que he leído, se debe usar un objeto como atributo porque:
- este **no será eliminado** por el _recolector de basura_ (si no es guardado en otro atributo tanto directamente como indirectamente por un método u otro objeto)
- permite el **uso externo** (como en los eventos y las señales)

**¿Existe otro caso en el que es necesario o "buena practica" utilizar atributos en vez de variables locales (y viceversa)?**

---

Por ejemplo, encontré que el código de _2-pyqt-main-window.ipynb_ de la semana 11:
```python
...
class MiVentana(QWidget):
    ...
    def init_GUI(self):
        self.label1 = QLabel('Texto', self)
        ...
        hbox.addWidget(self.label1)
        ...
```
entrega los mismos resultados que:
```python
...
class MiVentana(QWidget):
    ...
    def init_GUI(self):
        label1 = QLabel('Texto', self)
        ...
        hbox.addWidget(label1)
        ...
```
ya que `label1` es estático y es almacenado en `hbox`.

**Comment by KnowYourselves** [comment]
Hola @benjavicente!

Excelente pregunta! :tada:

Respondiendola directamentre, **en PyQt5 todo componente visual debiése ser un atributo**. Las razones son dos:

#### 1. Modelación Correcta ✔️ 

Viendolo desde una perspectiva OOP, los componentes visuales estan cercanamente relacionados a la instancia de la ventana, por lo cual tiene sentido desde ese punto de vista que estos sean atributos. Más aún, en caso de que no lo fueran no tendrías forma posible de modificarlos. 

En el ejemplo especifico que propones, si bien `label1` es almacenado en `hbox` sería complicado modificarla a travez de ese `hbox`, por lo cual si en un futuro quisieses modificar este label tendrías que devolverte y volvero atributo, por lo cual nos conviene que sea un atributo desde el inicio.

#### 2. Funcionamiento de PyQt5 👀 

Lamentablemente PyQt5 no es la librería mejor diseñada para interfaces gráficas, por lo cual tiene algunos errores extraños y hasta incluso diría que _esotéricos_, por como interactua con el _garbague collector_ de Python.

En ese sentido, hacer que algunos elementos gráficos sean atributos y otros no puede desembocar en errores en tu programa **extremadamente complicados de identificar**. En algunas tareas ha llegado a pasar que PyQt5 de lleno se queda pegado y _crashea_ solo por no haber puesto un elemento en especifico como atributo. En ese sentido, nos conviene que todos los elementos gráficos sean atributos.

Espero que esta justificación te parezca suficiente!

**Comment by benjavicente** [comment]
Gracias!
> **en PyQt5 todo componente _visual_ debiése ser un atributo**

Añadiendo un poco más a la respuesta: ¿esto no incluye elementos del _layout_ como `QBoxLayout`?

**Comment by KnowYourselves** [comment]
El caso de los layout es especial.

En primer lugar uno no los modifica, la idea es que sea permanente, ya que define la estructura general de tu ventana.

En segundo caso PyQt5 asocia por detrás los layout a la ventana haciendo uso de `setLayout` por lo cual el objeto `QBoxLayout` en si para PyQt5 no significa ni implica nada a menos que sea usado en `setLayout`.

En tal caso, como no tiene efecto en la ventana directamente y tampoco es algo que quisieses modificar, no se guarda como atributo.
