### ISSUE TITLE
Nodo Sprite

### ISSUE THREAD

**Issue by ifieldhouse** [IIC2233/Syllabus#645]
Quisiera tener dos clases: Entidad y Sprite, de manera que una composición de estos (y otros) genere mi personaje. ¿Cómo logro eso? ¿Qué clase debiese heredar Sprite y Entidad para que funcionen correctamente en conjunto?

**Comment by hanavarrete** [comment]
No entiendo porqué quieres hacer una clase Sprite. Tal vez te refieres a los pixmap por defecto de PyQt (los cuales traen ya varios métodos). Podrías ver bien tu modelamiento en base a eso, ya que tu entidad podría tener un pixmap fácilmente (sin la necesidad de que tengas que crear tu propia clase). Tal vez te entendí mal. Avísame si aclaré tu duda. Saludos!
