### ISSUE TITLE
Run en visual Studio Code

### ISSUE THREAD

**Issue by nicolaszanni** [IIC2233/syllabus#645]
Hola, quisiera saber si hay un shortcut key para hacer un run en visual studio code. Busqué en internet pero no encontré respuestas muy precisas. 
Se agradecería si saben cual es o cómo se agrega uno.
Gracias

**Comment by gatochico** [comment]
¡Hola @nicolaszanni ! (Disculpa la demora, ojalá todavía te sea útil y sino, le sirva a alguien más que lea esta issue)

El shortcut que buscas es probablemente `Ctrl+F5`, que corre automaticamente el archivo que tengas abierto en vscode. Si no resulta, puedes revisar en vscode en `Run > Run without debugging`. Sin embargo, déjame recomendarte una opción alternativa al Run de vscode... 

_**Utilizar la terminal**_ 🎉

A pesar de que correr código automáticamente con un botón suene tentador, puede ocurrir que esto te traiga problemas con _paths_ absolutos/relativos al ejecutar archivos, o en particular para esta segunda parte del curso, al tratar de correr el mismo archivo dos veces al mismo tiempo. Además, si decides tomar otros ramos donde se programe, probablemente tengas que usarla de todas formas 🙈 .

Para correr tus tareas o actividades mediante la terminal, debes:
- Abrir tu terminal en la carpeta donde se ubica el archivo, o moverte hacia esta mediante `cd`
- Escribir el comando `python nombre_archivo.py` (si usas windows) o `python3 nombre_archivo.py` (si usas mac o linux).
- Tu programa debería ejecutarse en la terminal. 

Pro-tips:
- Si mientras ejecutas el programa quieres cerrarlo puedes hacerlo con `Ctrl-C` para detener la ejecución y poder usar tu terminal de nuevo.
- Si mientras ejecutas el programa quieres ejecutar otra instancia de este (2 corriendo al mismo tiempo), debes simplemente abrir otra terminal y repetir los pasos de arriba.
- Estando en tu terminal, si presionas la tecla de arriba de tu pc, te empezará a mostrar el historial de comandos ingresados. Entonces escribes el código para ejecutar tu programa una sola vez y luego solo vas presionando arriba y enter para no escribirlo de nuevo.

Correr los archivos de esta forma te va a evitar varios dolores de cabeza a futuro ~~y se ve más hacker~~.

Incluso, si usas vscode, puedes abrir una terminal dentro de la ventana del programa, para que tengas todo en un mismo lugar y sea más cómodo trabajar. Esto se hace mediante el shortcut `ctrl-shift-ñ` y te abrirá algo así:
![image](https://user-images.githubusercontent.com/37161120/94748000-a2e63a00-0356-11eb-976f-f598e863601c.png)

Entonces puedes programar arriba y abajo tienes la terminal de tu pc en una misma ventana para ir corriendo tu programa. Si repites el shortcut puedes abrir múltiples terminales dentro de vscode 🌟  

Creo que me explayé un poco 😅, pero en verdad creo que es mucho más comodo trabajar así. 
Saludos!
