### ISSUE TITLE
Atributos de clases relacionadas 

### ISSUE THREAD

**Issue by ifieldhouse** [IIC2233/Syllabus#646]
Quisiera tener una clase que sea compuesta de distintas clases (ej. Enemigo, compuesta junto a Sprite y Hitbox), todas con muchos atributos en común (ej. posición). ¿Cómo logro que atributos de las clases relacionadas cambien cuando cambia la principal? ¿Debo hacerlo a través de setters? ¿O hay alguna manera de hacer que todos tengan un atributo compartido?

**Comment by tcgarrido** [comment]
Hola!

Como te respondieron en la issue #644 , no podemos indicarte cómo hacer las cosas, pues hay muchas formas de lograrlo. Sin embargo, puedes guiarte viendo el material y actividades o tareas pasadas.

_Hint:_ T04 2016-2. **Warning:** PyQt4
