### ISSUE TITLE
Error muy oscuro con pyqt :  "Cannot set parent, new parent is in a different thread"

### ISSUE THREAD

**Issue by jgramsch** [IIC2233/Syllabus#646]
Hola! 
tengo un problemilla,
Tengo mi clase GameRoom y al instanciarla desde mi clase main window me arroja el sgte. error :

'QObject::setParent: Cannot set parent, new parent is in a different thread'
aparte de esto casi siempre me manda este error
'QBasicTimer::start: QBasicTimer can only be used with threads started with QThread'
pero este error no afecta al funcionamiento, la cosa es q no uso q timers ni q threads y los únicos threads que uso son en el cliente y en el servidor

Creo que  es mi último error grave,

Saludos!

**Comment by fcgfaura** [comment]
#636 También me pasó

**Comment by hanavarrete** [comment]
hola! como dice @fcgfaura ya se comentó una posible solución en la issue #636 . Intenta con eso y dinos si te resultó el hint. Saludos!
