### ISSUE TITLE
Cierre Actividad Propuesta y video Ayudantía 5

### ISSUE THREAD

**Issue by margavicunas** [IIC2233/syllabus#646]
Hola!
¿Hay una posibilidad de que suban algún video de cierre para la actividad propuesta? Me surgieron varias dudas de enunciado y me gustaría ver más o menos qué se esperaba de cada item. 

También, ¿hay algún otro link de ayudantía 5? El video que subieron para mi sección (1) no está completo u-u

Muchas gracias de antemano 🌻

**Comment by lily416** [comment]
Hola @margavicunas 
 
Primero que todo lamento la demora en responder 🙇.
 
Ya se encuentra subido el cierre de la Actividad Propuesta 🎉, como los cierres anteriores se encuentra junto a los módulos de esa semana.
 
En cuanto al video de la ayudantía 5, lamentablemente ese día todas las secciones presentaron algún tipo de problema mientras se grababa la ayudantía, por lo que el único video disponible es el que les pasamos 😢. 
 
Lo siento por los inconvenientes. 
Saludos y éxito en la semana 👋📚

**Comment by margavicunas** [comment]
No te preocupes, muchísimas gracias por responder! lo bueno siempre llega tarde :heart:
