### ISSUE TITLE
Duda parámetro sock.listen()

### ISSUE THREAD

**Issue by franciscareti** [IIC2233/syllabus#646]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola! Estaba leyendo los contenidos de la semana y me surgió una duda ejecutando los códigos de la carpeta codigo_base. Cuando intento correr el archivo servidor_tcp.py me aparece el error de la imagen adjunta. 
Si a sock.listen() le pongo un int cualquiera como sock.listen(100000) me funciona, pero no entiendo bien qué significa el valor del parámetro que va ahí ni cómo determinarlo de manera correcta. Además, no me queda claro por qué me lo pide si en los contenidos aparece sin nada y debiera funcionar así. Muchas gracias de antemano!!

<img width="1440" alt="Captura de Pantalla 2021-06-21 a la(s) 16 11 13" src="https://user-images.githubusercontent.com/80775999/122822923-b94d7080-d2ac-11eb-971e-52ec1acc92d5.png">

**Comment by aaossa** [comment]
Hola @franciscareti , el problema es que en la consola estás ejecutando tu código con Python 2 (se ve en el *traceback*, `.../Version/2.7/...`). Intenta utilizando el comando `python3` en lugar de `python`: `python3 codigo.py` 🙌 En cuanto a qué significa el argumento recibido por [`socket.listen`](https://docs.python.org/3.7/library/socket.html#socket.socket.listen), es la cantidad de conexiones pendientes de aceptar, es decir, cuántos *sockets* clientes que aún no han sido recibidos con `socket.accept` puedes tener esperando. Según la documentación oficial, si no le entregas un número, se elige un valor "razonable". ¡Éxito con tu estudio 💪 !

**Comment by franciscareti** [comment]
Perfecto, ahí me funcionó bien!! Muchas gracias!!
