### ISSUE TITLE
Error con primer codigo del cuaderno

### ISSUE THREAD

**Issue by Juampisaez** [IIC2233/syllabus#646]
Hola, trate de implementar el primer codigo en un archivo python y me tiro el siguiente error:

![image](https://user-images.githubusercontent.com/48323752/81632669-dd1b6300-93d8-11ea-87cc-9d9f32724f46.png)

No entiendo bien porque aparece esto, instale pqty5 de la forma en que aparece en la seccion de software obligatorio (tengo windows).

**Comment by Juampisaez** [comment]
Al instalar pqty5 y qtdesigner me sale esto 
![image](https://user-images.githubusercontent.com/48323752/81634726-83696780-93dd-11ea-86e8-fcf0723402e7.png)

**Comment by fdoflorenzano** [comment]
Hola @Juampisaez,

El problema no parece ser del cuaderno específicamente, pero más un problema de instalación/importación. Busqué un poco en Google, y parece ser un problema recurrente en Windows, con distintos tipos de soluciones que a veces funcionan en ciertos casos.

Encontré algunas alternativas que parecen funcionar en algunos casos. 

1. En terminal, navega a la carpeta de instalación de Python en tu máquina, y ejecuta un comando de actualización. Por tu foto, intuyo tal carpeta es `c:\users\dell\appdata\local\programs\python\python37-32`, así que puedes llegar ejecutando los comandos:
```
cd\
cd c:\users\dell\appdata\local\programs\python\python37-32
```
Una vez en la carpeta, intenta con el comando:
```
python -m pip install --upgrade pyqt5
```
Luego vuelve a intentar con tu código.

2. Si lo anterior falla, intenta re-instalando Python completamente. Suena excesivo, pero puede que sea una alternativa más simple que meterse a buscar en carpetas de instalación.

¡Avisa como te va con las alternativas! Quedamos atentos/as.

Saludos

**Comment by Juampisaez** [comment]
No se que habra pasado la verdad. Pero hoy lo ejecute directamente desde la consola y funciono bien, me mostro "mi ventana". Luego lo ejecute desde VSC y ahora funciona. No se que habra sido, porque no hice el "python -m pip install --upgrade pyqt5".

Mi pregunta ahora es si es necesario hacer el "python -m pip install --upgrade pyqt5". Por lo que entiendo de eso, es una actualizacion?

**Comment by fdoflorenzano** [comment]
Hola @Juampisaez,

Los arreglos por arte de magia son los mejores. 

No te preocupes con ejecutarlo, solo si vuelve a aparecer el problema puedes intentarlo. Como indicas, la idea del comando era re-instalar en la última versión del paquete, solo en caso de que algo haya pasado en esa instalación. Es similar al caso de re-instalar Python completo, pero esa alternativa parece a muchas personas les funcionó.

Saludos.

**Comment by Juampisaez** [comment]
Jajajjajajaja entiendo. Gracias Profe!

**Comment by camolina2** [comment]
Hola, no puedo implementar el codigo de mi primera ventana :( me sale este error

![Captura de Pantalla 2020-05-14 a la(s) 12 41 36](https://user-images.githubusercontent.com/54114370/81961575-8da78380-95e0-11ea-92cc-a927a2669e4d.png)

**Comment by aaossa** [comment]
Hola @camolina2 , ¿podrá ser que estás utilizando Python 2 para correr el archivo? ¿Has utilizado el comando `python archivo.py` otras veces o normalmente usas `python3 archivo.py`?

**Comment by camolina2** [comment]
> Hola @camolina2 , ¿podrá ser que estás utilizando Python 2 para correr el archivo? ¿Has utilizado el comando `python archivo.py` otras veces o normalmente usas `python3 archivo.py`?

muchas gracias. Sii, no me había dado cuenta que se me estaba corriendo con eso! :D
