### ISSUE TITLE
TXX: Se pueden tener dos nodos con el mismo value

### ISSUE THREAD

**Issue by FaZorrilla** [IIC2233/syllabus#646]
Hola,

Me entró la duda si se puede tener 2 nodos con el mismo valor. Esto se debe a que no se menciona en el enunciado de ninguna manera. En este caso, un swap no haría nada.

Saludos!

**Comment by gatochico** [comment]
Hola! 

![image](https://user-images.githubusercontent.com/37161120/60122164-a1d95c80-9752-11e9-80e3-87f7b2943063.png)

Así que no te preocupes. Saludos!

**Comment by FaZorrilla** [comment]
Gracias!!
Pase de largo esa explicación parece xD
