### ISSUE TITLE
Vidas iniciales infinitas

### ISSUE THREAD

**Issue by santilaguna** [IIC2233/Syllabus#646]
Hola!
Al final,  ¿podemos asumir un límite de cantidad de vidas iniciales (en caso de que cambien el valor en parameters.py)? sino,  ¿podemos utilizar un número al lado del símbolo de vidas para representar cuántas vidas le quedan al jugador?
Saludos!

**Comment by joaquineichholz** [comment]
+= 1

**Comment by ptflores1** [comment]
Hola !
No pueden asumir un limite pero queda a su criterio como representan las vidas cuando la cantidad de vidas es mayor a 3, recuerden que debe ser claro cuantas vidas quedan
Saludos!
