### ISSUE TITLE
progress_bar y puntajes multijugador

### ISSUE THREAD

**Issue by santilaguna** [IIC2233/Syllabus#647]
Hola!
Me preguntaba si debíamos realizar una progress_bar y puntajes para cada jugador o si hay una para cada uno. La pregunta es más que nada por el aumento de dificultad cada ciertos puntos, en caso de ser la segundo opción, simplemente la dificultad de multijugador será mayor (se aumenta la dificultad cada vez que algún jugador alcanza una cantidad de puntos)?

**Comment by IchottMano** [comment]
@santilaguna Hola!

Efectivamente, cuando estés jugando el modo multijugador, tendrás una barra de puntajes para cada uno de los jugadores (como lo dice el enunciado).
Ahora, como no se explicita el enunciado cómo afecta esto a la aparición y dificultad de los enemigos, esto queda **a tu criterio**.

Saludos!

**Comment by santilaguna** [comment]
Gracias!
