### ISSUE TITLE
Duda con servidor.py en ejercicio de materia

### ISSUE THREAD

**Issue by ctoro05** [IIC2233/syllabus#647]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola! Ejecutando los ejemplos de Servidor TCP me encuentro con el siguiente error: "[WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión". Tengo entendido que el firewall bloquéo la acción que ejecuto. Cómo puedo solucionarlo? Muchas gracias

**Comment by pabloist** [comment]
Hola buenas,

En general dicha excepción se presenta cuando se trata de levantar una conexión, pero no hay "nadie" escuchando, es decir, cuando no se ha realizado el procedimiento de forma correcta. Te recomiendo revisar los ejercicios propuestos (los puertos, etc), en caso de que se siga presentando el problema, podrías subir tu repositorio para que lo revisemos 👌 y si todo lo anterior no funciona, revisaremos una solución en conjunto ante el problema del firewall (en caso de que sea el problema).

Saludos!

**Comment by ctoro05** [comment]
Ojalá que sea solo eso :) Muchas gracias, volveré a comentarlo en caso de ser necesario.
