### ISSUE TITLE
Error al instalar PyQt5 en mac

### ISSUE THREAD

**Issue by TeresitaS** [IIC2233/syllabus#647]
Hola, traté de instalar el programa desde el terminal con lo que dijeron (pip3 install pyqt5) y me tira un error.
<img width="568" alt="Captura de pantalla 2020-05-11 a la(s) 23 53 29" src="https://user-images.githubusercontent.com/62114500/81636953-1fe23880-93e3-11ea-849c-5e1c7a922ea3.png">

**Comment by fdoflorenzano** [comment]
Hola @TeresitaS,

Parece ser un rollo de permisos. Si te fijas el mismo mensaje te sugiere que agregues una opción al comando. Específicamente, te sugiere que ejecutes el comando:
```
pip3 install --user pyqt5
```

Intenta con eso y nos avisas.

Saludos.

**Comment by TeresitaS** [comment]
Ahi si me funciona! Muchas gracias!
