### ISSUE TITLE
Clase a heredar para clase Enemigo

### ISSUE THREAD

**Issue by ifieldhouse** [IIC2233/Syllabus#647]
¿Cuál es la mejor manera de hacer una clase Enemigo, y las clases a heredar? He visto que existe QWidget, QThread, QObject, etc. Quisiera crear una clase Enemigo que contenga muchas clases de manera que en conjunto determinen como se comporta (ej. una clase Sprite determina cómo se ve, una clase Hitbox no termina cómo colisiona). ¿Qué clases debo implementar/heredar para conseguir este comportamiento y todas actúen en conjunto?

**Comment by hanavarrete** [comment]
Depende que quieras que haga. Tal vez los ejemplos extras del material de pyqt puedan darte una intuición de que clase debiese ser algo que necesita mover. Saludos
