### ISSUE TITLE
drive con las grabaciones de todas las ayudantias 

### ISSUE THREAD

**Issue by betolguin** [IIC2233/syllabus#647]
hola! queria saber si existe algun drive que contenga las grabaciones con todos los ayudantes y no solo las que suben a canvas, de ser así agradecería me pudieran compartir el link.
Gracias de antemano!

**Comment by lily416** [comment]
Hola @betolguin, 
 
Primero que todo, muchas gracias por tu acotación. Actualmente todas las ayudantías se encuentran en el canal de YouTube del curso, pero se encuentran ocultas. Mañana cuando se suban los videos de la ayudantía de hoy, les haremos llegar una lista de reproducción con todas las ayudantías de este semestre 😄. 
 
Saludos y que tengas buena semana 👋🍬
