### ISSUE TITLE
TXX: swap

### ISSUE THREAD

**Issue by isihirmas** [IIC2233/syllabus#647]
Hola! es obligatorio programar el swap? O basta con que el árbol final quede reordenado con los valores correctos?
Saludos!

**Comment by gatochico** [comment]
Hola! No es necesario que implementes el swap de forma explícita con el método balance dado, pero se recomienda fuertemente hacerlo ya que las alternativas podrían mucho más dificiles de implementar. Con tal que el árbol quede ordenado de forma correcta al final, está todo bien.
Éxito!

**Comment by isihirmas** [comment]
Ya es que por ejemplo yo balanceo y al hacerlo asigno los hijos, pero luego en la siguiente iteración no se relaciona que ese nodo es "hijo" de alguien, está bien esa relación? Pregunto por lo que vi en los json de la carpeta test, que según yo por como armé mi árbol no podría hacer ese seguimiento.
Osea, cada nodo tiene bien asignados a su hijo izquierdo o derecho, pero en ninguna parte relaciono que ese hijo izquierdo es el padre de otro nodo, se entiende?

**Comment by gatochico** [comment]
Lo que podrías hacer es agregar un atributo dentro de cada nodo que almacene a su padre para no perder esta referencia y hacer más fácil la implementación de tu arbol. Recuerda que puedes agregar todos los atributos y métodos que quieras, con tal que uses los mínimos pedidos (:

**Comment by tnmarin** [comment]
sobre el metodo balace......se puede agregarle parametros a la funcion?
balance(nodo), asi la funcion sabe del nodo que parte haciendo swap(si es necesario)

**Comment by Hernan4444** [comment]
Hola,

No se puede. Pero puedes agregar más atributos a la clase para resolver ese problema.

Saludos ✌️
