### ISSUE TITLE
Duda Ayudantía

### ISSUE THREAD

**Issue by camirojasguajardo** [IIC2233/syllabus#648]
Hola! tengo una duda con respecto a la siguiente clase modelada en la ayudantía:
```python
class DCClass:
    def __init__(self):
        self.__lista = []
    
    @property
    def IICLista(self):
        return [x[0] for x in sorted(self.__lista, key=lambda e: e[1])]
```
Mi consulta es ¿cuál es la función de 'key=lambda' y 'e: e[1]' ? 
Saludos!

**Comment by aaossa** [comment]
Hola @camirojasguajardo , perdón la tardanza en la respuesta 😅 Lo que hace `key` en `sorted` es indicarle a Python cuál es el criterio según el que debe ordenar el iterable que le entregas. Por ejemplo, imagina que tenemos la siguiente línea de código:

```python
lista_ordenada = sorted(iterable, key=criterio)
```

Lo que estamos diciendo aquí es: "OK Python 🐍, ordena los elementos de `iterable` según `criterio` y entregame la lista ordenada en la variable `lista_ordenada`". Python va a tomar cada elemento de `iterable`, aplicarle la función `criterio` y comparar los valores retornados por dicha función para ordenar. De esta manera, lo que hace la línea del ejercicio es: toma cada elemento de `self.__lista`, toma el segundo elemento de cada uno (por eso el `e[1]`) y ordena los elementos según el valor obtenido. Ojalá haya quedado claro y si no es así pregunta acá mismo no más 👌
