### ISSUE TITLE
Librerías permitidas/prohibidas T07

### ISSUE THREAD

**Issue by hanavarrete** [IIC2233/Syllabus#648]
Para consultar sobre una librería deben responder esta issue con una pregunta de la siguiente forma:

> Puedo usar la librería nombre_libreria para hacer explicacion_de_lo_que_quiero_hacer

Recuerden especificar en su README qué librerías utilizan!

—-
## **Librerías Permitidas**
- requests
- PyQt
- QtDesigner
- zlib: compress, decompress, crc32
- collections: counter, deque, orderedDict, named tuples
- itertools
- operator
- os
- random
- re
- sys.exit
- time
- csv
- numpy
- pandas
- math
- scipy
- sympy
- struct
- hmac
- base64
- httplib2
- apiclient
- oauth2client
- urllib
- argparse
- functools
- webbrowser

## **Librerías Prohibidas**
(En general, cualquier wrapper de la api de telegram. La idea es solo usar flask y request.)
- bs4
- python-telegram-bot
- Telepot
- twx.botapi

## **Built-ins prohibidos**
- eval (:skull:)
- exec (:skull:)

**Comment by rjdelrio** [comment]
podemos usar pygithub para manipular las api de github?

**Comment by hanavarrete** [comment]
@rjdelrio No, la idea es que no usen ningún wrapper. Saludos!

**Comment by consuvalencia** [comment]
podemos usar flask verdad?

**Comment by akaminetzkyp** [comment]
Sip. El enunciado dice que lo usemos. :)

**Comment by benjamimo1** [comment]
Se puede usar la api de telegram "pura"? 
Import telegram

**Comment by rpalmaotero** [comment]
@consuvalencia sí, se puede usar `flask`.
@benjamimo1 no, no se puede usar ningún wrapper/framework de la API.

**Comment by consuvalencia** [comment]
Gracias!!
Y json?

**Comment by iqacevedo** [comment]
@consuvalencia si pueden usar la librería json.

Saludos !
