### ISSUE TITLE
Error al abrir jupyter

### ISSUE THREAD

**Issue by EmeraldMP** [IIC2233/syllabus#648]
Hola, no se por qué ahora no puedo abrir jupyter desde el cmd como jupyert notebook, intenté desinstalarlo e instalarlo de nuevo y me aparece esto 

"jupyter" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

![image](https://user-images.githubusercontent.com/62030696/81706284-ee4a8b00-943d-11ea-8652-f7e89025287f.png)

(no se si se puede ver la imagen)

**Comment by Drpinto1** [comment]
¡Hola!

Probablemente el problema sea porque te falta un guión, intenta usar `jupyter-notebook` y cuéntame si te funciona :D

**Comment by EmeraldMP** [comment]
intente con jupyter-notebook y me sale el mismo mensaje :(
![image](https://user-images.githubusercontent.com/62030696/81717721-e6441880-9448-11ea-80e7-039a60d18bd3.png)

**Comment by aaossa** [comment]
@EmeraldMP dijiste que lo desinstalaste e instalaste de nuevo, ¿realmente pudiste instalarlo? Por lo que se ve en tu primera captura, no pudo instalar algunas cosas. ¿Cuál es el *output* de `pip3 install jupyter`?

**Comment by EmeraldMP** [comment]
Creo que no se pudo instalar bien ya que después de cierta linea mes sale ese mensaje
![image](https://user-images.githubusercontent.com/62030696/81720202-150fbe00-944c-11ea-99cf-bd659051f25b.png)

**Comment by aaossa** [comment]
¿Puedes probar con `pip3 install --upgrade jupyter`? (Agregué `--upgrade`)

**Comment by EmeraldMP** [comment]
también, después de ciertos mensajes me sale lo mismo 
![image](https://user-images.githubusercontent.com/62030696/81729760-8191b980-945a-11ea-8644-f35fef061c78.png)

**Comment by aaossa** [comment]
Bueno, probemos instalando "wheel" entonces: `pip3 install wheel` y luego intenta instalar "jupyter"

**Comment by EmeraldMP** [comment]
Ahora no me tira "Could not build wheels" pero no me deja abrirlo al ejecutar  jupyter-notebook
![image](https://user-images.githubusercontent.com/62030696/81735437-0c76b200-9463-11ea-9686-016a0ffedde3.png)

**Comment by aaossa** [comment]
Prueba instalando "jupyter" y luego usando el comando `jupyter notebook`, no `jupyter-notebook`

**Comment by EmeraldMP** [comment]
Lo instale con el comando python -m pip install jupyter  y me sigue dando el mismo mensaje que es "jupyter" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

**Comment by jaimecoloma** [comment]
Hola! a mi me pasó lo mismo! He usado jupyter todo el semestre y ahora cuando intente abrir el cuaderno de esta semana me lanzo que no encuentra el comando jupyter, probe haciendo las mismas cosas y todavia no se ha solucionado :(

**Comment by EmeraldMP** [comment]
Intente ocupando en cmd python - m notebook y me funcionó, prueba con eso
