### ISSUE TITLE
cmd vs control KeyPressEvent

### ISSUE THREAD

**Issue by santilaguna** [IIC2233/Syllabus#648]
Hola!
Quería preguntar si es obligatorio que la letra que estemos usando sea ctrl, pues en mac cuando se usa Qt.Key_Control lee por defecto el cmd, de lo contrario cómo lo podría solucionar?

**Comment by Sforrego** [comment]
Si es obligatorio! Lo ideal es que este tipo de cosas sea generico.

**Comment by santilaguna** [comment]
@Sforrego existe otra forma de que me lea ctrl entonces o tengo que hacerlo poniendo el número de tecla manualmente ?

**Comment by Sforrego** [comment]
Perdon si no fui claro, tienes que usar qt. Key_control!

**Comment by Pipelao** [comment]
Hola :)
No soy ayudante, pero en QtDesigner en las configuraciones del botón puedes elegir shortcut que te permite seleccionar las teclas que quieras usar para que realice la misma función que si es clickeado, en este caso ctrl.
Saludos.

**Comment by santilaguna** [comment]
@Pipelao gracias igual pero ya lo hice todo sin qtdesigner! 
Pensé que estaba mal que me leyera el cmd en vez de ctrl, pero al parecer esa era la idea  =D
