### ISSUE TITLE
Protocolo TCP y ejemplo de apuntes

### ISSUE THREAD

**Issue by FVivess** [IIC2233/syllabus#648]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola, tengo una duda con lo que se indica en los ejemplos de networking. 
En el segundo ejemplo se muestra que se envían bytes y se guardan en un archivo, pero que el tamaño de este (4KB) es mucho menor que el tamaño de lo enviado (102KB).
La solución que se plantea es tener un protocolo para recibir la información, que consiste en enviar y recibir el largo de bytes en los primeros 4 bytes. Sin embargo, ya se está utilizando el protocolo TCP, que sirve para "enviar y recibir un stream de bytes serializados en forma confiable a un destinatario".
**¿Por qué es necesario implementar un protocolo adicional por sobre el protocolo TCP para que la información llegue de forma completa?**

**Comment by pabloist** [comment]
Hola buenas!

Respondiendo a tu pregunta, sucede que el protocolo TCP es un protocolo de comunicación que nos asegura la integridad de los "paquetes" que sean enviados, pero no nos dice nada de "cómo" viene el paquete, por lo que tenemos problemas al momento de escribir el código puesto que no sabemos de forma certera "hasta cuándo" recibir la data (el protocolo TCP solo nos asegura su integridad).

**Y para que quede más claro un ejemplo!**

Digamos que tienes que salir urgente de tu casa, pero dado que estás esperando 3 paquetes le avisas a tu abuela para que los reciba. Después de unas horas llegan los paquetes a través de la compañía IIC2233xpress, pero hay un problema; según la información de la compañía deben entregar 10 paquetes a tu dirección, pero como las abuelas son cuadradas y desconfiadas, tu abuela solo recibe los 3 que le indicaste.

En el ejemplo anterior la compañía IIC2233xpress representa el protocolo TCP (mediante GPS y fotos se aseguran que lleguen los paquetes), pero como sólo le indicamos a la abuela, que representa nuestro código y protocolo propio, que recibiera 3 de esos paquetes, el resto se pierde porque no hay quien los reciba y los procese.

Finalmente con el protocolo que diseñamos nos aseguramos de recibir todos los paquetes que nos envíen de forma segura y eficiente. 

Espero que haya quedado claro. :)

Saludos!

**Comment by FVivess** [comment]
Quedó claro. Muchas gracias!
