### ISSUE TITLE
Autoevaluación de Repaso

### ISSUE THREAD

**Issue by jarvasquez** [IIC2233/syllabus#649]
Hola!!

Realicé la autoevaluación de repaso y me quedó una duda. En la pregunta 9, CANVAS dice que la respuesta correcta es `La clase cuadrado está modificando directamente a un objeto de la clase contenedor`. Pero en el enunciado no se especifica ninguna clase Cuadrado. 

Si asumimos que la clase Cuadrado hace referencia a la clase Rectangulo, ¿por qué la respuesta `La clase contenedor está modificando directamente al objeto almacenado` no es correcta?

Muchas gracias!

**Comment by cruz** [comment]
Hola @jarvasquez ,

Lamento la demora en responder. En primer lugar, había un error en la descripción de la alternativa (que justamente era la correcta). Debería decir: `La clase Rectángulo está modificando directamente a un objeto de la clase Contenedor`

Si bien ya pasó el periodo de control, es igualmente valioso entregar una explicación porque es importante hacer un buen modelamiento, sobre todo en las tareas siguientes. Voy a copiar el código acá:

```
class Rectangulo:
    def __init__(self, x, y):
        self.x = x
        self.y = y

    def area(self):
        return self.x * self.y

    def guardar_en_contenedor(self, contenedor):
        contenedor.figura = self


class Contenedor:
    def __init__(self, figura=None):
        self.figura = figura

    def modificar_tamanho_figura(x, y):
        self.figura.x = x
        self.figura.y = y
```

La clase `Contenedor`recibe y almacena otro objeto (relación de agregación). El principio de encapsulamiento dice que el estado de un objeto debería ser modificable únicamente a través de sus interfaces, y es parte del "contrato" que se hace entre las clases `Rectangulo` y `Contenedor`. Cuando el `Rectangulo` ejecuta `guardar_en_contenedor(self, contenedor)` está modificando un atributo de `Contenedor` de manera externa a esa clase, y eso viola el principio de encapsulamiento, pues un objeto `Contenedor` ya no puede controlar sus atributos. Un mejor modelamiento sería definir en `Contenedor`:

```
class Contenedor:
    ...
    def actualizar_figura(figura):
        self.figura = f
    ...
```
y si `Rectangulo` quiere agregarse dentro de `Contenedor`, podría hacer:
```
class Rectangulo:
    ...
    def guardar_en_contenedor(self, contenedor):
        contenedor.actualizar_figura(self)
    ...
```
Si bien el efecto práctico es el mismo, de esta manera el objeto `Contenedor` puede utilizar su método `actualizar_figura(figura)` para implementar alguna decisión si quiere actualizar su atributo `figura` y/o controlar algún efecto lateral, como incrementar un contador de figuras, o modificar su estado.

Espero que esto haya ayudado.
