### ISSUE TITLE
TXX: Librerías

### ISSUE THREAD

**Issue by javieraochoa** [IIC2233/syllabus#649]
Hola!

Sé que en el enunciado de la tarea dice que sólo se puede usar json, pero eso significa que no puedo usar deque de collections?

gracias c:

**Comment by Hernan4444** [comment]
Hola, 

Así es, no pueden utilizar ninguna librería aparte de json. Con lo que viene de python sin librerías deben ser capaces de resolver esta tarea.

Saludos :v:

**Comment by YoGandalf** [comment]
Y se puede ocupar dumps?
Porque en el main esta solo loads por default

**Comment by Hernan4444** [comment]
Hola,

Si se puede porque tambien es parte de json.

Saludos ✌️

**Comment by nacholar** [comment]
Hola, se puede usar el módulo os?

**Comment by Hernan4444** [comment]
Hola, 
No, no es necesario usar `os`, se puede resolver con otras herramientas de python que no involucren librerías.

Saludos ✌️

**Comment by gustavobarrezueta** [comment]
Hola, 
Para estar completamente seguro, ¿es posible usar collections para importar un deque?
Gracias,

**Comment by gustavobarrezueta** [comment]
Esta respondido más arriba. Disculpas.
Saludos,

**Comment by Hernan4444** [comment]
Hola, no se puede
