### ISSUE TITLE
problemas con el key Espacio

### ISSUE THREAD

**Issue by joaquineichholz** [IIC2233/Syllabus#649]
Hola, al apretar la tecla "espacio" en mi programa pueden pasar 2 cosas totalmente random, una opción es que mande una señal al método keyPressEvent diciendo que fue apretada y funcione bien y la otra es que no se mande una señal al método keyPressEvent y la ventana del juego se cierre, lo segundo me pasa alrededor de un 80% de las veces :( y no se como solucionarlo, ¿alguien tiene alguna idea de que puede estar pasando?

gracias!

**Comment by aecanales** [comment]
Hola!

¿No será que el juego se esta cayendo por un error? ¿Con que exit code se cierra el juego?

**Comment by joaquineichholz** [comment]
No se imprime ningún error... es muy raro y pasa solo algunas veces, ahora me esta pasando menos eso si 👍

**Comment by mfanselmo1** [comment]
Respondi en [661](https://github.com/IIC2233/Syllabus/issues/661)
