### ISSUE TITLE
AF7: Duda sobre envió de mensajes en escuchar_cliente

### ISSUE THREAD

**Issue by Pabloski100** [IIC2233/syllabus#649]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Duda sobre el envió a varios destinatarios

Hola, estoy 99% seguro de que es así, pero por si acaso pregunto, en la función esuchar_cliente, cuando se tiene que mandar un mensaje, se hace de tal manera que todas las id de la lista dada por manejar_mensaje se ocupan para identificar a todos los destinatarios, cierto?

**Comment by MatiasDuhalde** [comment]
Hola @Pabloski100 !

No estoy seguro si entendí al 100% la duda, pero el método `manejar_mensaje` retorna una lista de "destinatarios" en caso de que el mensaje deba enviarse a más de un socket. Todas las ids de la lista retornada corresponden a un socket que puedes obtener en el diccionario `clientes_conectados`.
