### ISSUE TITLE
Error import QApplication AY07

### ISSUE THREAD

**Issue by jamigone** [IIC2233/syllabus#649]
Hola! Tengo instalado el PyQt5, pero no me reconoce la línea 2 del main.py de la ayudantía 07, cuando se importa QApplication desde PyQt5.QtWidgets. Adjunto imágenes:

Verifico instalación PyQt5:
![imagen](https://user-images.githubusercontent.com/50121013/81738350-94f75180-9467-11ea-893d-191f6a325966.png)

Error:
![imagen](https://user-images.githubusercontent.com/50121013/81738916-7e9dc580-9468-11ea-9574-44d1c72a2764.png)

Ayuda plis :')

**Comment by fdoflorenzano** [comment]
Hola @jamigone,

Por la imagen parece ser un warning de VSCode. Si intentas ejecutar el código, ¿lanza un error? ¿lanza ese error?

Estamos atentos.
Saludos.

**Comment by amparostevens** [comment]
Hola! A mi me pasa lo mismo pero el programa corre bien de todas formas y no lanza error.

**Comment by jamigone** [comment]
Se me olvidó completamente responder, perdón @fdoflorenzano. No lanza ningún error, efectivamente era solo el warning de VSCode :).
Por curiosidad, ¿qué se supone que me está advirtiendo el editor?

**Comment by fdoflorenzano** [comment]
Hola @jamigone,

Desde entonces otras issues sobre el tema han aparecido que puedes revisar: #668 #674.

Saludos.
