### ISSUE TITLE
QSound problema

### ISSUE THREAD

**Issue by nachojarasaez** [IIC2233/Syllabus#649]
Hola me pasa que al modificar la canción no la puedo reproducir con Qsound, pero si voy donde esta la canción y la reproduzco por fuera funciona perfectamente la canción. No se como solucionarlo.
Pd: el Sound me funciona con la canción original.

**Comment by josemlira** [comment]
Hola! A mi me pasaba algo similar, si al momento de modificar la canción la acortaste, lo que hice para arreglarlo fue modificar el subchunksize

**Comment by rrhurtado** [comment]
Hola,

Lo más probable es que la implementación de Qsound esté correcta, pero que al modificar la canción algún paso esté haciendo que no se pueda reproducir. Puedes probar con el consejo de josemlira.

Saludos
