### ISSUE TITLE
Centro urbano

### ISSUE THREAD

**Issue by jerrymendoza** [IIC2233/syllabus#65]
Se deben poder construir centros urbanos ?
En el apartado 3.3 mencionan que solo debe existir un centro urbano, sin embargo en el archivo de edificios... están los recursos mínimos para poder construir uno, al mismo tiempo, debemos iniciar con uno. 
Si solo debe existir uno, para que ocuparía esos datos?

Gracias.

**Comment by lily416** [comment]
Hola 😄 

Al igual que los valores `c_trabajadores`, `c_oro`, `c_madera` y `c_piedra` son para darle consistencia al archivo, así que al igual que los costos de producción de las murallas esos valores son despreciables.

Saludos y éxito con la tarea 👋 🏰

**Comment by jerrymendoza** [comment]
Gracias!
