### ISSUE TITLE
Tuplas y listas

### ISSUE THREAD

**Issue by sofiaolmedos** [IIC2233/syllabus#65]
Hola! No entiendo bien la diferencias en el uso de tuplas y listas, siento que todo lo que puedo hacer con tuplas lo pudo hacer también con listas.

**Comment by josefinareyes** [comment]
Hola! En general las tuplas se usan para agrupar valores que deben ir 'naturalmente' juntos (un ejemplo podría ser una tupla de coordenadas cartesianas```(x, y)```), y como además son inmutables permiten fijar dichos valores para usarlos como uno solo. Las puedes usar también para retornar dos o más valores en forma de una sola tupla dentro de una función.

Las listas permiten agrupar datos en general, de forma ordenada y mutable. Te recomiendo investigar sobre más usos de tuplas versus listas para entender mejor en qué casos son útiles, y tener claros los métodos asociados a cada tipo!
