### ISSUE TITLE
Duda documentos a entregar en la T0

### ISSUE THREAD

**Issue by FranciscoPinto1138** [IIC2233/Syllabus#65]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Holaa, tengo una duda sobre qué es lo que se tiene que subir al repositorio. Sé que hay que entregar los archivos .py que nosotros hayamos creado, pero ¿también se entrega parametros.py, usuarios.csv, encomiendas.csv y reclamos.csv? Pregunto porque sin estos archivos el código de la tarea no tiene mucho sentido, ya que estaría llamando archivos inexistentes en el repositorio. Gracias.

**Comment by Emiliax16** [comment]
Hola @FranciscoPinto1138 ! no se deben entregar los archivos csv. El archivo `parametros.py` se entrega sólo en caso de que lo hayas modificado (agregado algún parámetro extra). De hecho se podría practicar el uso de gitignore en esta entrega, de tal manera que metas ahí todos los archivos que no deben subirse en tu repositorio (csv, pdf, etc). Saludos!
