### ISSUE TITLE
Duda sobre modularizacion y maximo de lineas

### ISSUE THREAD

**Issue by franco-anfossi** [IIC2233/Syllabus#65]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola, tengo la duda de si hay un limite de líneas en un mismo archivo .py en el curso o en el archivo que se debe subir para la Tarea 0. De ser así tengo claro que deberíamos modularizar si es que lo necesitamos, estos archivos modularizados también se tienen que subir o se agregan al .gitignore y que solo se visualice el archivo .py que ejecuta la Tarea.

**Comment by Juampisaez** [comment]
Holaa 👋 @franco-anfossi 
Así es, aparece en la [guia de descuentos](https://github.com/IIC2233/Syllabus/blob/master/Tareas/Descuentos.md), te recomiendo revisarla. Por otro lado, debes subir con git, todos los archivos que compongan tu programa (los archivos que les entregamos junto al enunciado no es necesario que los subas).

Quedo atento si quedan mas dudas :)

**Comment by franco-anfossi** [comment]
Muchas gracias! :)
