### ISSUE TITLE
Duda enunciado, consultas básicas

### ISSUE THREAD

**Issue by fdominguezclaro** [IIC2233/Syllabus#65]
Al final del issue #44 preguntaron esto mismo pero no tiene la respuesta, y no encontré ningún issue con respecto a esto. 

1.  el enunciado, sección 4.2.3, dice que un usuario ANAF puede leer filas de las distintas base de datos (incendios, recursos y usuarios). Mi pregunta es que si un usuario ANAF pide leer filas de por ejemplo, los incendios, tenemos que devolverle toda la base de datos de los incendios? O alguna línea en específico?

2. Al preguntar por un incendio, hay que ingresar el id del incendio, la posición o lo que nosotros estimemos conveniente?

**Comment by FernandoPieressa** [comment]
1) La ANAF tiene acceso a todo, por lo tanto puede todo de la base de datos junto con la informacion extra pedida en el enunciado. Queda a tu criterio si pones que consulte por uno en particular o todo de una, pero que sea ordenado y entendible

2) Queda a tu criterio, eso si pon en el readme la decisión tomada

Saludos!
