### ISSUE TITLE
Donde guardar archivo solucionado y agregar variables a funciones de functions.py

### ISSUE THREAD

**Issue by vmunozgarachena** [IIC2233/Syllabus#65]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/21)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/20)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
 
Hola tengo 2 preguntas:
1.  Los archivos que hay que solucionar están en la carpeta Archivos, eso signfica que el archivo que se cree como solución luego de resolver el tablero también tiene que guardarse en la carpeta Archivos o puede guardarse simplemente en T0?
2.  A la función solucionar_tablero quería agregarle una variable que me ayudara a hacerlo, sin cambiar las cosas que ya recibía o entregaba, hay algún problema con eso?

Gracias

**Comment by joaquindm02** [comment]
Hola @vmunozgarachena !

Respondiendo a la pregunta 1, el archivo que se cree como solución debe quedar guardarlo en la carpeta archivos.

Respondiendo a la pregunta 2, no se pueden modificar, ni los parámetros que reciben, ni lo que retornan las funciones que se deben rellenar. Si es que quieres cambiar algunas de estas cosas, lo que podrías hacer es crear otra función a la que le puedas entregar mas parámetros, dejando la original sin modificar.
Saludos
