### ISSUE TITLE
Properties creadas en T1

### ISSUE THREAD

**Issue by vichoassadi** [IIC2233/Syllabus#65]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola,
Del enunciado de la T1 se entiende que no se pueden crear argumentos para las clases, pero, **¿se pueden crear properties?**
Gracias

**Comment by Benjeeeh** [comment]
Hola!
Si, de hecho está recomendado usar properties, como se dice en los objetivos en la portada del enunciado :)
Aparte, si bien no se pueden crear argumentos, si se pueden crear nuevos métodos, aparte de que algunos de los métodos establecidos **deben** ser properties.
![image](https://github.com/IIC2233/Syllabus/assets/78326186/2fcb39a5-7f3f-47f5-969f-daa19ac8fa14)
![image](https://github.com/IIC2233/Syllabus/assets/78326186/f0a039e4-ce19-43b0-829a-0cec1b90aa43)
Saludos y éxito con la tarea.

**Comment by vichoassadi** [comment]
Muchas gracias! Saludos
