### ISSUE TITLE
Entregar .ipynb en vez de .py

### ISSUE THREAD

**Issue by JuanDlugo** [IIC2233/syllabus#65]
¡Hola!
Consulta, si realicé la tarea con Jupyter Notebook, ¿Puedo subirla con la extension de este ".ipynb"?
O estrictamente debo subirla con extensión .py?

**Comment by lily416** [comment]
Hola 😊

Debes subir tu tarea como uno o más archivos con extensión `.py`, 😔
ya que en el curso esperamos que aprendan a escribir, modularizar, seguir guías de estilo, utilizar git y muchas cosas más y ~~por desgracia~~ los _jupyter notebooks_ no son una buena herramienta para lograr eso en su totalidad.

Los _jupyter notebooks_, son muy buenos para correr código corto o probar librerías, lo cual lo hace una excelente herramienta para aprender a programar, 😄
pero al momento de escribir programas más extensos y complejos puede presentar problemas, ya que:
- Dificulta la modularización del programa,
- Se pueden sobreescribir variables, 
- Es difícil de ejecutar, ya que las celdas no siguen un orden de ejecución
- y muchas más cosas. 😰


Espero que entiendas y que para las próximas tareas escribas tu código directamente en un archivo `.py`, así evitas tener que pasarlo desde el _jupyter notebook_ y hay menos probabilidades de que surja un error al traspasarlo.

Saludos y éxito con la tarea. 👋🍀

**Comment by JuanDlugo** [comment]
Otra consulta, traspase todo mi código (el que funcionaba perfecto en Jupyter) a Visual Studio Code. La cosa es que ahora el apretar "Run File in Terminal", me aparecen varios errores del terminal a la hora de leer símbolos como "!" o inclusive algunos de los que estan en tablero.py.
Errores como este : "'ascii' codec can't encode character '\xa1' in position 1"
No sé si estaré haciendo algo mal a la hora de correr el programa, ni como arreglarlo. 
Muchas Gracias de antemano :)

**Comment by nabenitez** [comment]
Hola @JuanDlugo! 

Primero, prueba lo que te comentaron en la issue #36. Puede ser que tu editor no pueda imprimir los caracteres especiales.

Si después de lo anterior tu error persiste entonces prueba ejecutando el código en consola, tal como se describe en #36, de la forma ```python3 nombre_archivo.py```. Si esto funciona es posible que VSCode tenga algún problema de configuración con el **encoding**, en ese caso te recomiendo revisar la configuración del editor, utilizando el siguiente  [link](https://stackoverflow.com/questions/30082741/change-the-encoding-of-a-file-in-visual-studio-code).

Comenta acá mismo si pudiste resolverlo con alguna de las dos formas o si el error continúa!!

**Comment by JuanDlugo** [comment]
Hola, comente en la otra Issue como lo resolví! 
Pero muchas gracias igual! Era eso, tenia que especificar que quería ejecutarlo con Python3.7 y funciona perfecto (:
