### ISSUE TITLE
Caracteres permitidos para nombres de usuarios a registrar

### ISSUE THREAD

**Issue by juan-palma-1** [IIC2233/syllabus#65]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Estimados:
Me surge la duda respecto a los caracteres permitidos "dentro" de el nombre del usuario al momento de registrarlo, en el pdf se menciona que no se permiten las ``comas "," `` pero ¿Se pueden ingresar caracteres como signos de interrogación, espacios ` `exclamación `!`, underscore`_`, hypen `-` , `"·%$/().:;`, etc; o deben ser solo caracteres alfanumericos?

**Comment by Juampisaez** [comment]
Hola @juan-palma-1 
Tal como dices, solo debes preocuparte de los requisitos puestos en el enunciado, esto quiere decir que se debe verificar que el "nombre del usuario no esté actualmente siendo utilizado por otro usuario, que tenga un largo entre 3 y 15 caracteres (ambos
extremos incluidos y no incluya comas (",")" (lo mismo que aparece en el enunciado). Entonces, respondiendo a tu pregunta, si se pueden ocupar esos caracteres que nombras (solo fijate que respeten las condiciones ya mencionadas).

Espero haya quedado mas claro, quedo atento :)

**Comment by Pakarati** [comment]
Hola! siguiendo con el tema, puedo añadir una restricción en el readme para el registro usuarios que sea que no pueden contener caracteres especiales como tildes y ñ? Es que al registrar un usuario con caracteres especiales y entablar un conversación, después de cerrar el chat no puedo volver a abrir el archivo mensajes.csv :(

**Comment by Juampisaez** [comment]
Hola @Pakarati 
Para ese caso particular, no puedes hacer eso ya que en el enunciado dice las restricciones que deben tener los usuarios al momento de registrar (si no lo dijera, quedaria a tu criterio, pero no es el caso).
Ahora, no se cual es error que te retorna al no poder abrir tu archivo mensajes.csv (deduzco que son cosas aparte).

Quedo atento :)

**Comment by Pakarati** [comment]
Ya, hice un ejemplo:
Cree un usuario con caracteres especiales, luego agrego un contacto y abro el chat con el nuevo contacto (sin mensajes). Al enviar un mensaje me da un error al tratar de imprimir el nuevo historial de mensajes. Lo mismo pasa si el mensaje contiene caracteres especiales :(
Revisé el archivo mensajes.csv y me aparece el mensaje registrado, pero con los caracteres especiales
![Error](https://user-images.githubusercontent.com/80866575/113197165-53fc5d00-9232-11eb-9c0c-0e48a7e035f7.png)
![Mensaje en archivo](https://user-images.githubusercontent.com/80866575/113199210-db4ad000-9234-11eb-94ee-2e2c3b6bf68b.png)

**Comment by Juampisaez** [comment]
El problema puede estar en como estas abriendo los archivos, probablemente no estas abriendo el archivo con `encoding="utf-8"`.
Puede ser ese el problema, te recomiendo ocupar los archivos de la repo del curso para ocupar nuevamente esos archivos.

**Comment by Pakarati** [comment]
Si agregué `encoding="utf-8"` al open de `mensajes.csv`. El archivo se abre bien normalmente, pero cuando se guarda una línea de un mensaje con un carácter especial o usuario con carácter especial en el archivo, deja de abrirse:( 
Busqué en internet y no entendí mucho la verdad, ¿se supone que las tildes y ñ ya están en utf-8? porque de ser así ¿por qué no me deja abrirlo luego de guardarlos?

**Comment by Pakarati** [comment]
No funcionaba, así que dejé el `encoding=utf-8` solo al escribir en el archivo, pero se cambiaron todos los caracteres especiales a `utf-8`, eso no se puede?
Ej: 

> QuÃ© tal? Me gustÃ³ el hotel que reservÃ©

 ahora está en el archivo como:

> Qué tal? Me gustó el hotel que reservé

**Comment by Juampisaez** [comment]
Mm, acabo de ver que estas haciendo un readlines, la forma que te recomendaria hacerla es abrir el archivo. Luego iterar sobre ese archivo linea por linea, y ver como se esta abriendo y guardando. Pruebalo tanto haciendo el encoding con utf-8, como sin hacerlo.
Si eso no funciona, no se me ocurre como podria ayudarte a no ser que me digas el nombre del archivo, las lineas donde tienes el error, y asi podria meterme a tu repo y ver el problema.
Quedo atento :)

**Comment by Pakarati** [comment]
Ya me funcionó! Creo que el problema era el encoding al escribir el archivo :) Muchas gracias!
