### ISSUE TITLE
Actualización Tests asegurar_ruta

### ISSUE THREAD

**Issue by Hernan4444** [IIC2233/Syllabus#65]
Hola, esperando que estén bien, hemos actualizado el archivo `test_10_asegurar_ruta.py` para ser consistente con el enunciado. En particular, en la explicación de `asegurar_ruta`, el enunciado dice:

> Este método se debe encargar de **copiar la red de metro**

Pero los _tests_ no estaban validando esta afirmación. Así que se actualizaron para ayudarlos a reconocer si es que no están haciendo la copia que corresponde.

## Importante

Tambien queremos reforzar que el enunciado explicita lo siguiente:

![image](https://github.com/IIC2233/Syllabus/assets/15641721/451b8751-1abe-4657-8724-68aee4d5b86a)

Es decir, los tests públicos son un apoyo en el desarrollo de la tarea, pero los test públicos no necesariamente evalúan todo lo que dice el enunciado, para que tengas precaución en esta y las siguientes tareas en siempre desarrollar una solución que respete el enunciado. 

Dicho lo anterior, los tests privados podrán evaluar situaciones que los tests públicos no incluían, siempre y cuando dicha situación haya estado definida como requisito en el enunciado.

Saludosヾ(＾-＾)ノ

**Comment by elneitans** [comment]
Una pregunta profesor, ¿el archivo todos_tests.py fue modificado?

**Comment by Hernan4444** [comment]
Hola @elneitans 

No, ese archivo no ha sido editado desde que se publicó el código.

El [Readme de la T1](https://github.com/IIC2233/Syllabus/tree/main/Tareas/T1) incluye un registro de los cambios realizados (y referenciando la issue que corresponda a ese cambio).

Saludosヾ(＾-＾)ノ

**Comment by SebastianArroyoSanchez** [comment]
Profesor, antes los test me corrían perfecto, pero ahora (al hacer e cambio) tengo el mensaje de que modifiqué la red original, cuando no lo he hecho en ningún momento dentro de la función. Usé red_2 = self.red para copiarla al comienzo y luego nunca más la toco ni la menciono, pero aún así me da ese error. 

Entonces, llegué a dos posibles conclusiones; 1) Tengo algún error en el código. 2) Que no estoy entendiendo bien a qué se refieren con copiar la red de metro.

Muchas gracias profesor

**Comment by KaopyHK** [comment]
Buenas, profesor, le hago una consulta: En el enunciado de la f asegurar_ruta indica que _"En caso de no
existir una solución que permita que la ruta más corta desde la estación inicio hasta la estación
destino contenga la cantidad de estaciones indicadas por p_intermedias, se debe retornar una
lista vacía"_ pero al revisar los test_cases públicos de esa función, los resultados esperados son [[]], es decir, lista de listas, cuál sería la relevante para los test privados?
