### ISSUE TITLE
duda currencies

### ISSUE THREAD

**Issue by nmaturana97** [IIC2233/Syllabus#65]
al momento de guardar todos los datos debo guardar las currencies de cada usuario. podria añadir columnas al archivo users, que contengan la cantidad de cada currencie? o bien crear otro archivo que contenga esa informacion?

**Comment by hanavarrete** [comment]
#41 en esa issue se responde tu duda de crear otro archivo, el tema de como manejar lo que necesites es parte de tu forma de modelar el problema. Saludos!
