### ISSUE TITLE
Duda naturalidad de los predios

### ISSUE THREAD

**Issue by AlvaroToledoMartinez** [IIC2233/Syllabus#65]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Sobre los predios creados, ¿se puede asumir que estos serán creados con al menos una unidad de alto y ancho? Es decir, el caso borde `predio_prueba = Predio(P1, alto=0, ancho=0)`, ¿se debe considerar?

**Comment by vgalfaro** [comment]
Hola! los predios son de 1x1 mínimo, saludos!
