### ISSUE TITLE
Duda sobre herencia de clases

### ISSUE THREAD

**Issue by simonmb12** [IIC2233/Syllabus#65]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola, tengo una duda con respecto a herencia de clases. Con respecto a uno de los ejemplos (Clase Auto y FurgonEscolar), me entró la duda de cómo utilizar un atributo "privado" de la superclase en mi subclase. En la parte de sobreescritura de métodos, traté de invocar al atributo __kilometraje (de la clase Auto), pero me tira error. 
Estoy tratando de llamarlo con "super().__kilometraje"
Cuando llamo a un método hago "super().método(argumentos)" y me funciona perfecto. Supongo que el problema es por la característica de "privado" del atributo.

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by tqmbanados** [comment]
Hola! Efectivamente, tiene que ver con el hecho que `__kilometraje` es un atributo privado "a la python". El *name mangling*, (es decir, comenzar un atributo con `__`) no sólo aplica al definir un atributo, sino que cada vez que llamamos un atributo desde dentro de un método. Aquí un ejemplo:
```python
class Test:
    def __init__(self):
        self.__atributo = 0   # Aquí, python crea un atributo de nombre "_Test__atributo"

    def prueba(self):
        print(self.__atributo)  # Aquí, python lee "print(self._Test__atributo)", y lo imprime.
        print(self._Test_atributo)  # Esta línea es idéntica a la de arriba!

# Ahora veamos que pasa con la herencia
class SubClase(Test):
    def __init__(self):
        super().__init__()  # Aquí se inicializa la super clase, incluyendo el atributo "_Test__atributo".

    def prueba_0(self):
        print(self.__atributo)  # Aquí, python lee "self._SubClase__atributo". Este atributo no existe! 

    def prueba_1(self):
        print(super().__atributo)  # Al igual que en "prueba_0", python lee "self._SubClase__atributo". 
   
    def prueba_2(self):
        print(self._Test__atributo)  # En este caso no hay error, pues ese atributo si fue definido en el __init__.
```

Trata de copiar el código de arriba y hacer algunas pruebas! Ahí se aclarará todo un poco más. 
Quizás queda aún la pregunta: **¿Por qué al llamar `super():__atributo` aun usamos la conversión de nombres de la clase `SubClase`? Esto es por que lo que importa al hacer *name mangling* no la clase cuyo atributo estamos invocando, sino **la clase desde la cual invocamos el atributo**. Esto se hace así, pues sino el *name mangling* no tendría sentido, ya que al invocar cualquier atributo privado, python automáticamente haría la conversión del nombre. 
Esto significa que al importar clases de módulos externos por ejemplo, no puedes utilizar atributos privados de esas clases simplemente usando herencia. Claro está, siempre puedes agregar manualmente el *name mangling*, pero esto es mala práctica, y sólo funcionaría en lenguajes como python. 

Espero haber resuelto tu duda!

**Comment by tqmbanados** [comment]
Emm, no se si entiendo del todo tu duda, pero creo que va por aquí la respuesta:

Al trabajar con herencia, lo único que tiene que hacer la subclase para implementar **todos** los métodos y atributos de la *super-clase* es agregar la línea ```super().__init__()``` dentro de su propio `__init__()`.
Es decir:

```python
class SubClass(dict):
    def __init__():
        # Aca todavía no inicializamos la super clase, por lo que no podemos trabajar con SubClass como si fuera un dict
          
         super().__init__()   # Luego de esta línea, la clase "SubClass" posee todos los métodos y atributos de la clase "dict".
 
        # El código aquí puede trabajar con self como si tratara de un dict
```

No es necesario definir los atributos y métodos por separado. La excepción en el caso de los métodos es cuando usamos *clases abstractas*, donde **forzamos a que las sub-clases definan ciertos métodos**.
Si es común que asignemos valores nuevos a los valores de la super_clase, en ese caso puede parecer que los estamos definiendo en el `__init__`, pero en verdad sólo estamos cambiando su valor!
