### ISSUE TITLE
Función "Volver atrás"

### ISSUE THREAD

**Issue by llloyola** [IIC2233/Syllabus#65]
La función "Volver atrás" debe estar implementada sólo para cuando se juega en una galaxia? O debe estar implementada para cada menú dentro del juego? De no ser así, el programa se acabaría al momento de hacer una consulta, modificación o creación de una galaxia, no?

**Comment by IchottMano** [comment]
@llloyola Hola!👋
La idea es que se puedan hacer varias consultas, modificaciones o creaciones de galaxias sin tener que reiniciar el código cada vez 😵😵(para hacerle mas fácil la vida a la persona que corrija tu tarea 😄), por lo que es recomendable que esa función exista 👍 👍 .
Sin embargo, queda a tu criterio implementarla o no 🙄.
Saludos!
