### ISSUE TITLE
Comillas agregadas al leer archivo .csv

### ISSUE THREAD

**Issue by janwandter** [IIC2233/syllabus#65]
En 2 casos, se agregan comillas antes del usuario cuando leo el archivo "posts.csv". En estos 2 casos tienen en el cuerpo del prograpost comillas, que se duplican. Como puedo evitar que se agreguen?
Muchas gracias

**Comment by Tito0906** [comment]
Holaa @janwandter, probablemente estás tienes un error cuando transformas la línea del archivo y la tratas de separar entre usuario, fecha y post. Para ayudarte más, por favor específica cuál es el resultado del las líneas con problemas, ademas de mostrar cómo estás manejando las línas del archivo.

**Comment by janwandter** [comment]
'"jeschuw1rth', '2018/06/17', 'pal the only ""meltdown"" im having is my ice cream melting down into my hand while I lay on the beach & laugh while thinking about the trolls";'
Este es un caso en el que se le agregan comillas antes del usuario y en meltdown se duplican. Eso es antes del proceso de separación. Copio el codigo que tengo al respecto?

**Comment by Tito0906** [comment]
Ok, por favor añade el código que utilizas hasta esa parte.

**Comment by Tito0906** [comment]
Holaa @janwandter, por favor realiza un commit y push para actualizar tu repositorio con el código que llevas. El código era muy largo para ser publicado por acá, por lo que edite tu comentario anterior.

**Comment by janwandter** [comment]
Hola! ya lo subi

**Comment by Tito0906** [comment]
Holaa @janwandter, cuál es el sistema operativo de tu computador?

**Comment by janwandter** [comment]
Windows 10 - 64bits
Si todo funciona bien, solo que esos 2 casos van a aparecer en las funciones de ver prograposts

**Comment by Tito0906** [comment]
Holaa @janwandter , revisé tu código y lo corrí para probarlo pero nunca me dio ningún tipo de error.  Además, el sistema oparativo que usamos es el mismo, así que realmente no estoy seguro de que puede estar causando el error en este momento. Lo importante es que si no te presenta problemas para realizar todas las demás funcionalidades de la tarea, usalo con el error y todo. Asegurate de dejar claramente expresado en el README que el error existe y que trataste de solucionarlo. Además, cita esta issue en el README para que el ayudante que corrija no tenga problemas. 

Sobre otros errores, lo que si pude ver en tu código es que te recomiendo revises el argumento _maxsplit_ cuando separas las líneas del archivo posts.csv.

Saludos!

**Comment by Ajbarros1** [comment]
@janwandter  me pasaba lo mismo, pero se arreglo cuando actualicé los archivos .csv
