### ISSUE TITLE
Problema al hacer git clone

### ISSUE THREAD

**Issue by vicho1901** [IIC2233/syllabus#650]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

Hola! Hace un par de días tuve un problema en el pc y tuve que formatearlo, y debido a eso he tenido que descargar e instalar el software obligatorio nuevamente (Git, python, etc.), sin embargo he tenido problemas para clonar mi repositorio personal usando git clone dejando el Git Bash sin hacer nada por un rato. Esto solo me está pasando con el repositorio personal, ya que pude clonar el syllabus y los contenidos y hacer pull sobre estos. 

![image](https://user-images.githubusercontent.com/66710338/122999327-211ebc80-d37c-11eb-8d37-a9fe5eca1d83.png)

El Git Bash se queda así todo el rato, sin descargar nada, lo unico que hace es crear una carpeta vacía con el nombre de mi repositorio. Además, ya probé a reinstalar git y hacer git clone de los repositorios nuevamente unu

Muchas gracias de antemano, saludos!

**Comment by csantiagopaz** [comment]
Hola @vicho1901 , Yo en verdad nunca he tenido ese problema, lo que me ocurre es que 1 puede ser un problema con las credenciales de git, ya que ese es un repositorio privado te recomiendo ver si puedes hacer push/ en otros repositorios, o incluso volver a la primera clase y intenta configurar el git nuevamente, si eso no te funciona, me avisas y juntos buscamos otra solución.

**Comment by vicho1901** [comment]
Configuré nuevamente Git con el user.name y user.email y sigo sin poder hacer el git clone. Prové a crear un respositorio provado y hacer git clone y tampoco pude hacerlo :(

**Comment by danvillablanca** [comment]
Hola, tengo exactamente el mismo problema que presenta @vicho1901. Además, probé otras soluciones que me sugirieron como cambiar de red, reiniciar el computador y cosas así. Al igual que @vicho1901, pude clonar syllabus y contenidos, pero no mi repositorio personal. Además, al hacer git clone se crea la carpeta asociada al repositorio y su subcarpeta asociada al git, como se ve en la imagen adjunta. Dejé corriendo el git clone por 3 horas, para ver si era porque era mucha información que descargar, pero nada sucedió.

![ss](https://user-images.githubusercontent.com/66493692/123486317-caaeb980-d5d9-11eb-9707-db7d948a6fae.png)

**Comment by vicho1901** [comment]
Hola! Escribo aquí para saber si es que alguien ha encontrado una solución al problema, ya que yo aún no logro arreglarlo. Y en caso de no poder arreglarlo a quien debo escribir para informar de la situacion?
 Muchas gracias

**Comment by csantiagopaz** [comment]
Hola, primero de todo, disculpa la demora en contestarles, acá hay una posible solución:
![image](https://user-images.githubusercontent.com/42182095/123769183-04601880-d897-11eb-9875-814e90561513.png)
Quizas los pueda resolver con ese  comando
Para borrar la info del usuario (nombre, mail, cerrar sesión):
git config --global --unset-all

Otro posible problema puede ser que tu firewall esté bloqueando git a hacer la descarga y te recomiendo leer el tercero review de ese link https://stackoverflow.com/questions/8750930/git-clone-hangs-forever-on-github
Y si ninguna de esas alternativas funciona

**Comment by vicho1901** [comment]
No me funciona nada :( ya no sé que hacer, ahora mandé un correo a bienestar unu

**Comment by danvillablanca** [comment]
¡Hola! Con el profesor @cruz resolvimos este problema de un modo no tan ideal, pero funciona.


En resumen, dado que uso Windows, creé una máquina virtual con una versión reciente de ubuntu, le instalé Git e hice git clone pero con ssh (no con https), para lo cual también tuve que crear una ssh.


[Procedimiento General]
Como primera recomendación, sugeriría intentar hacer git clone con ssh en Windows, para lo cual hay que crear una ssh. Ver: https://docs.github.com/es/github/authenticating-to-github/connecting-to-github-with-ssh

Tuve problemas con este método porque por una razón aún no determinada, algunas carpetas que deberían haberse creado no se crearon. @cruz sospecha que pueda ser debido a que el terminal de Git en Windows emula el linux, por lo que tal vez hayan algunos problemas de compatibilidad entre la terminal de Git en Windows con el propio Windows.

Por esta razón, hice una máquina virtual con VMWare (hay otras alternativas gratuitas como VirtualBox y Hyper-V, entre otros), le instalé Ubuntu (dado que funciona con linux, podrían haber sido otras distribuciones como fedora, deepin, etc), instalé Git en la máquina virtual con Ubuntu, lo configuré, e hice git clone de syllabus y contenidos sin problemas. Cuando intenté hacer git clone usando https no tuve éxito, pero sí tuve éxito al hacer git clone usando ssh. 


[Consideraciones útiles]
NO hacer sudo git clone, TAMPOCO clonar siendo el superusuario, dado que el git queda configurado con permisos de superusuario y eso causa problemas.

Para pasar archivos desde el computador al ubuntu en la máquina virtual o viceversa, basta con arrastrar los archivos desde el lugar de origen al lugar de destino, teniendo a la máquina virtual como una ventana.

Considerar que la descarga de ubuntu, así como el de una máquina virtual, toman tiempo. 



Espero que esta propuesta pueda ser de ayuda para alguien que tenga estos problemas ahora o en el futuro. Quedo dispuesto a responder dudas en la medida de lo posible.

Saludos,
Dan Villablanca.

**Comment by nicolaspoli** [comment]
Hola! Yo tuve el mismo problema (de hecho lo tuve durante la AF6 y tuve que hacer commits a mano) y la verdad mientras intentaba lo que plantean arriba, encontré que una solución muchas cómoda era descargar y utilizar **GitHub Desktop** y clonar/pullear/commitear/pushear desde ahí. Lo acabo de probar haciendo un commit de prueba en una actividad antigua y sirve.

Se que tampoco es como una solución directa al problema, pero luego de intentar durante horas, probar con 2 distintos PC, reinstalar desde Python hasta Git en ambos y probar con dos conexiones a internet distinta, esta forma la verdad me parece satisfactoria y es la única que me ha resuelto el problema xd 

Ojalá que ha alguien mas le pueda servir. Saludos
