### ISSUE TITLE
Cambio de Lineas de Tareas

### ISSUE THREAD

**Issue by conyfernandezt** [IIC2233/syllabus#650]
Hola. Queria saber como funcionaba el tema del cambio de lineas para las tareas. Estaba revisando la correccion de la tarea y decia que podia cambiar hasta 20 lineas con el fin de poder subir la nota. Si es asi cual es el plazo y el descuento?

**Comment by OrregoSilva** [comment]
Hola!
Con respecto a eso, queria saber si las decimas descontadas por usar el cambio de lineas, se pueden anular con las decimas de des-descuento obtenidas con el README.

**Comment by gatochico** [comment]
Hola a ambos!

@conyfernandezt Se envió un aviso explicando cómo funciona la recorrección y el cambio de líneas, para que lo revises en detalle 🌟 .

@OrregoSilva El des-descuento de readme sí aplica para anular los cambios de línea. Los descuentos que no se anulan son librerías/built-ins prohibidos y entregas atrasadas.

**Comment by Mamunoz42** [comment]
Hola 😄 
Quería consultar si estos cambios de líneas incluyen agregar alguna línea de código 🤔

**Comment by gatochico** [comment]
Hola @Mamunoz42 , sí puedes agregar código siempre y cuando esté entre las 20 líneas permitidas 👍

**Comment by gatochico** [comment]
Claro, si un cambio de líneas mejora cierto ítem, ponlo en esa sección (si es un arreglo 'general', puede ir en recorreccion general).

**Comment by fernandareyesc** [comment]
Hola!
Cómo sería lo de los descuentos si es que el cambio que quiero hacer es mover una función de un módulo a otro? sin cambiar lo que tienen esas líneas.
Muchas gracias desde ya!

**Comment by gatochico** [comment]
Hola @fernandareyesc ! (disculpa la demora)
Si deseas mover una función de un módulo a otro, el descuento asociado será:
`techo(c_lineas/4)`

Con `c_lineas` siendo la cantidad de lineas que se van a mover en total (esto es, incluyendo el `def funcion(...)` ).

Saludos!

**Comment by sbcorrea** [comment]
Hola!
Si mi ReadMe no recibió las 5 décimas de des-descuento, ¿podría aplicar las correcciones al ReadMe, enviar a recorrección y mejorar ese "puntaje" asociado? ¿O no se reevalúa la calidad de un ReadMe en la recorrección? Además, si con un cambio de líneas elimino mi uso de una librería prohibida, ¿en recorrección se me dejaría de considerar ese descuento por mala práctica?
Gracias de antemano 😄

**Comment by gatochico** [comment]
Hola @sbcorrea ! (disculpa la demora 🙏 )

El cambio de líneas aplica a código, por lo que no podrías modificar tu README con ellas. 

Respecto a tu segunda pregunta, si tu cambio de líneas elimina completamente el uso de una librería prohibida se te eliminará el descuento por esa librería y podrás optar a puntaje en los items que se te dió 0 puntos debido a su uso.

Saludos!

**Comment by sbcorrea** [comment]
@gatochico perfecto, muchas gracias!
