### ISSUE TITLE
Error al instalar pyqt5 en windows

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2233/syllabus#650]
Me aparece esto y no se como solucionarlo. Alguna pista ?

![image](https://user-images.githubusercontent.com/62180259/81739859-0e903f00-946a-11ea-895c-ba1344775f78.png)

**Comment by aaossa** [comment]
Hola! ¿Podrías probar con `pip install pyqt5`? También podría ser `python3 -m pip install pyqt5` o `python -m pip install pyqt5` (dependiendo del output de `python --version` y `python3 --version`, ya que deberías usar el que corresponda a la versión que usamos en el curso).

**Comment by dsepulveda3** [comment]
No me tira nada cuando pongo python3 -m pip install pyqt5, ni  python -m pip install pyqt5

![image](https://user-images.githubusercontent.com/62180259/81742299-e30f5380-946d-11ea-9084-73b7173dac5b.png)

**Comment by dsepulveda3** [comment]
Tengo  Python 3.7 (64-bit)

**Comment by aaossa** [comment]
¿Has instalado otras librerías antes? Si es así, ¿cómo lo hiciste? No estoy seguro de por qué esos dos comandos no te dieron ningún *output* 😅

**Comment by dsepulveda3** [comment]
No nunca he instalado una libreria :/

**Comment by dsepulveda3** [comment]
Nose que hacer llevo desde las 3.30 y tengo que estudiar otros ramos :/ hice un par de cosas de unos tutoriales y aun asi no funciona. Me imagino que tengo que tener la libreria para la actividad del jueves o no?

**Comment by dsepulveda3** [comment]
Me funciono descargando python 3.8. Esta bien que use ese en vez del 3.7 que piden en el curso?

**Comment by entamburini** [comment]
Hola @dsepulveda3!

Lo que pasa es que no tienes pip dentro de los comandos que windows conoce. La solución más rápida era desinstalando python y volviendo a instalarlo marcando la opción "Add to PATH" al inicio de la instalación.

Lo de python 3.8 funcionará si y solo si no ocupas nada que esa versión permite que otras no. Esto no lo digo con la intención de que "seas pillo" sino que a veces python de una versión a otra empieza a permitir cosas que en versiones anteriores no. Así que ten mucho ojo si vas a usar esa versión :wink: 

En caso de que quieras ver cómo se arreglaba tu problema, [puedes ver este link](https://datatofish.com/add-python-to-windows-path/) que describen qué se puede hacer :D
