### ISSUE TITLE
Swap

### ISSUE THREAD

**Issue by cmarquez1** [IIC2233/syllabus#650]
La funcion balance() la podemos ocupar dentro de la funcion insert()? Porque me pasa que si la ocupo solo cuando ya he terminado de ingresar todos mis valores, solamente a un valor lo arregla o lo tira para arriba por dedir asi. Lo voy a explicarr con dibujos para que se entienda mejor.
Tengo mi arbol creado con los valores no ordenador: 
    5
/      \\
2       3
/\\
1 4

Si ocupo la funcion balance() al final de crear el arbol, solo me pasa esto:
    1
/      \\
5       3
/\\
2 4

Pero si la ocupo cuando agrego un valor me queda asi:
    1
/      \\
2       3
/\\
5 4

Que es como deberia ser un AlgarroboTree

**Comment by Hernan4444** [comment]
Hola, Si puedes.
Aunque también, recuerda que los 3 funciones a pedir las tienes que completar tu, puedes hacer que después de cada insert se haga un balance, lo cual también está bien. En ninguna parte condicionamos que el balance va después de cada insert, incluso el enunciado dice que después de cada inserción hagas los swap necesarios :D así que está bien lo que propones n.n

Saludos
