### ISSUE TITLE
Problema aún más bizarro :( 

### ISSUE THREAD

**Issue by jgramsch** [IIC2233/Syllabus#650]
Hola! salí de mi problema anterior que era el del los parents en distintos threads, para esto tuve que instanciar la widget en el constructor para que sean parte del mismo thread y luego hacer una inizialización hechiza jaja

de todas maneras salí de ese problema para estar 4 horas en otro aún más extraño,

QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)

eso me baja el programa cuando agrego datos a una tabla (QTableWidget) con el metodo tabla.setItem(f,c,obj)
he intentado todo y he aprendido mucho de los QMetatypes, pero aún no soluciono nada, literalmente me estancó todo el trabajo. :'( 

@Hernan4444  me han dicho que sabes mucho de interfaces ! ayudaa! 

saludos!

**Comment by Hernan4444** [comment]
@jgramsch podrias subir todo el código a tu repositorio?? Asi puedo ver mejor como se genera este error e intentar solucionarlo (Es la primera vez que veo algo así pero intentaré hacer lo que pueda :sweat_smile: )

Saludos!

**Comment by jgramsch** [comment]
Listo, esta en la repo, perdona mi estructura, de verdad que esta fea, 

el problema se encuentra especificamente en el método initialize de la clase RoomWidget en el modulo room.py a lo mejor tambien quieras revisar el modulo main que es donde se instancia por primera vez. Como ya mencioné es especificamente  tabla.setItem(f,c,obj).

Lo que averigué de QMetaClases es q se usan para crear widgets propios con comportamientos propios pero se pueden agregar a la interfaz y a los threads de esta transformandolos con QMetaclass 

Eso, gracias!!

**Comment by Hernan4444** [comment]
@jgramsch para empezar, tu tarea no tiene implementado ninguna señal, esto implica que cuando instancias algunos objetos desde el cliente haces que un objeto **No PyQt** instancie objetos PyQt y que los edite. Podrias partir por implementar señales y si se mantiene el error avisanos.

Saludos

**Comment by jgramsch** [comment]
Hola! 

hice lo que me dijiste, cambie cosas por señales y transformé client a un Qbject y me resultó ! 
mil gracias !
