### ISSUE TITLE
Diagrama de clases 

### ISSUE THREAD

**Issue by joaquineichholz** [IIC2233/Syllabus#650]
En el diagrama, debemos poner todos los atributos, botones, connects, geometrias entre otras cosas del  init_gui o solo ponerlo como un método?

**Comment by jmwielandt** [comment]
En caso de que haya que ponerlo, cómo se hace? .-.

**Comment by nachocontreras** [comment]
Hola!

No es necesario poner los métodos de pyqt. Sin embargo, tienen que recordar que el diagrama de clases debe tener métodos que más les servirá para que le demos feedback y para que les ayude a ustedes a distinguir entre backend y frontend.

Éxito! :smile:
