### ISSUE TITLE
AF7: duda sobre cierre del socket en el cliente

### ISSUE THREAD

**Issue by Pabloski100** [IIC2233/syllabus#651]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Me confunden un poco las instrucciones dadas para cerrar el cliente

Hola, tengo un  par de dudas sobre el momento en el que se tiene que cerrar el socket del cliente, si entiendo bien, el enunciado dice que hay que tener cuidado de cerrar el cliente tanto al final de `escuchar_servidor` y de `enviar `, sin embargo, eso haría que el socket se cerrara al recibir una primera respuesta del servidor, y no se podría enviar ningún mensaje después. En que momento convendría cerrar el socket para evitar eso?

**Comment by pabloist** [comment]
Hola buenas!

Se debe cerrar el socket del cliente exactamente en los momentos en los que se indica en el enunciado. **OJO** 👀, el enunciado no dice que se debe cerrar al finalizar la función enviar(), sino ante la presencia de una excepción.

Saludos!
