### ISSUE TITLE
[Semana 8, ejercicio 1.3]¿Por qué si omito el sleep en cuenta_3, el thread no se ejecuta inmediatamente?

### ISSUE THREAD

**Issue by Gsalinas1506** [IIC2233/syllabus#651]
### Prerrequisitos

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda
¿Debería usar la plantilla así o no :sweat_smile:?

### Duda

Hola!
Estaba haciendo el ejercicio propuesto 1.3 de la semana 8, y de paso me puse a jugar con él para ver que pasaba. Una vez ya terminado correctamente me pregunté que pasaría si omitía la condición de imprimir `"¡Todos terminaron en orden!"` una vez que ya todos terminaran, y en vez de eso ejecutar inmediatamente la función `cuenta_3` desde la cadena de threads que se nos entrega, omitiendo la linea de `sleep` de esta función. En la siguiente imagen se ve como quedaba mi código cuando surgió mi duda:
**SPOILER DEL EJERCICIO A CONTINUACIÓN**
**EDIT**: Imagen quitada por compartir código :(
(Se descomentamos las lineas verdes, cumple con el enunciado)

Al hacer esto, yo pensaba "Bueno, primero se inicia la cadena de threads al startear el thread que inicia con la función `contar_1`. Esa función redirije primero a `contar_2`  y luego a `contar_3`. Además, dado que comenté la linea que 'duerme' a la función, esta debería hacer su cuenta correspondiente de una sola corrida, para luego volver a la funcion `contar_2`. Una vez ahí, al 'dormirse' la función por primera vez, debería imprimirse el `"¡Todos terminaron en orden!"`. ". Sin embargo, al intentar correr el código, obtuve lo siguiente:
![image](https://user-images.githubusercontent.com/68198662/95007696-fa033d80-05e8-11eb-82d0-f7dcdf25a550.png)

Osea, primero se ejecutó el print de `"¡Todos terminaron en orden!"`, y luego la cadena de threads, cuando yo pensé que ocurría algo como esto:

> Contando de a 3: 1
Contando de a 3: 4
Contando de a 3: 7
Contando de a 3: 10
Contando de a 3: 13
Contando de a 3: 16
Contando de a 3: 19
Contando de a 3: 22
Contando de a 3: 25
Contando de a 3: 28
Contando de a 3: 31
Contando de a 3: 34
Contando de a 3: 37
-- ¡Terminó cuenta 3! --
¡Todos terminaron en orden!
Contando de a 2: 1
Contando de a 2: 3
Contando de a 2: 5
Contando de a 2: 7
-- ¡Terminó cuenta 2! --
Contando de a 1: 1
Contando de a 1: 2
Contando de a 1: 3
Contando de a 1: 4
Contando de a 1: 5
Contando de a 1: 6
Contando de a 1: 7
Contando de a 1: 8
-- ¡Terminó cuenta 1! --

Lo cual claramente no pasó...
¿Podrían explicarme cual fue el error en mi razonamiento por favor?

**Comment by aaossa** [comment]
Hola, @Gsalinas1506 , perdón por la demora 😅 .

A grandes rasgos, en teoría, tanto el *output* que obtuviste como el que esperabas podrían ser correctos. Con esto me refiero a que, dado que los `print` vienen de *threads* que ocurren en paralelo, el orden podría variar de manera casi aleatoria (por eso entran en juego los *locks*, cuando esto puede introducir problemas). Al parecer, lo que ocurre es que el proceso de iniciar todos los *threads* hasta llegar a `cuenta_3` es, para tu computador, mucho más lento que el avanzar e imprimir una línea (hay que crear variables, copiar memoria, etc.). De hecho, si es que antes del `print("¡Todos terminaron en orden!")` pones un `time.sleep(1)` puedes ver más o menos cuánto se demora esta operación.

Ojalá la respuesta te sea de utilidad, y si tienes cualquier otra duda no dudes en preguntar 👌 

**PS:** Eliminé la imagen de tu código. No por colocar "spoiler" deja de ser compartir código. Al hacer eso, podrías pasar a llevar la intención de otres de aprender haciendo el código por su cuenta, así que por eso la eliminé 😅 (Esta sí era la *issue*)
