### ISSUE TITLE
Error al instalar PyQt5 en Mac

### ISSUE THREAD

**Issue by Tsbalart** [IIC2233/syllabus#651]
Hola! Me aparece esto cuando trato de instalar la librreria, no se como se arregla ya que no me reconoce la libreria cuando intento importarla
![Captura de pantalla 2020-05-12 a las 16 33 40](https://user-images.githubusercontent.com/62150115/81742631-68930380-946e-11ea-9f66-f3d9f0cae68d.png)

**Comment by aaossa** [comment]
Hola! ¿Podrías probar instalando `wheel` también? Sería algo como `pip3 install wheel` y luego el comando que ya utilizaste

**Comment by Tsbalart** [comment]
![Captura de pantalla 2020-05-12 a las 16 40 06](https://user-images.githubusercontent.com/62150115/81743183-477ee280-946f-11ea-808d-270a70ea9779.png)
Me aparece eso, no se si significa que ya esta instalada

**Comment by aaossa** [comment]
Efectivamente, indica que ya fue instalada la librería. Prueba importando PyQt5 en tu editor, y si no funciona, prueba de nuevo después de hacer `pip3 install --upgrade pyqt5`. Ojalá funcione 🤞

**Comment by Tsbalart** [comment]
![Captura de pantalla 2020-05-12 a las 16 47 29](https://user-images.githubusercontent.com/62150115/81743853-5914ba00-9470-11ea-98b5-37dbde7b9a7d.png)
Aparece que se instalo correctamente, pero cuando intento importarla aparece el siguiente error:
![Captura de pantalla 2020-05-12 a las 16 49 11](https://user-images.githubusercontent.com/62150115/81743956-88c3c200-9470-11ea-8099-3cd484425610.png)

**Comment by aaossa** [comment]
Dejaré ligada la *issue* nueva que creaste para que no se pierda la relación con #654
