### ISSUE TITLE
Problema con error InvalidTree

### ISSUE THREAD

**Issue by Jbijit** [IIC2233/syllabus#651]
Puede ser que haya algún problema con algún test de InvalidTree?.
Cuando hago los test por test.py no me funciona, pero cuando lo hago directamente en el archivo main si.

**Comment by Hernan4444** [comment]
Hola, 

Puedes detallar que test es? E hiciste pull del repo? porque ayer se actualizó test.py y un archivo de invalid_tree.json (#648) porque había un test malo.

Saludos
