### ISSUE TITLE
Es continuo el movimiento de los enemigos?

### ISSUE THREAD

**Issue by sjkinast** [IIC2233/Syllabus#651]
Si no me equivoco en la ayudantía de la Tarea se dijó que el movimiento de los enemigos no era necesario que fuera continuo, esto significa que podría asumir que el movimiento del enemigo es de un cuadrante a otro cuadrante y no se queda entre dos ? o solo aplica para el tema de los sprites.

**Comment by rihanuch** [comment]
hola!

El movimiento debe ser continuo!

**Comment by Sforrego** [comment]
El movimiento tiene que ser continuo!

**Comment by aecanales** [comment]
En el punto 2.1.1 del enunciado se indican que el personaje principal y los enemigos tienen movimiento continuo y de la misma velocidad.

Saludos!

**Comment by naquiroz** [comment]
@rihanuch Es obligatorio que no queden entre celdas? Puedo optar por hacer el movimiento continuo en el sentido que pueda quedar entre dos casillas?

**Comment by sjkinast** [comment]
@aecanales entiendo lo que dice en el enunciado pero considerando lo que dice @rihanuch que el personaje si pasaria de cuadrante a cuadrante cuando se mueve ( pero visualmente recorrio todo el cuadrante)  la velocidad del enemigo seria la misma porque estaria definido que cuando se mueve avanza N/15 para que no quede parado entre dos casillas , estoy refieriendome al caso en que la medida del monito es igual al del cuadrado porque asi es en el juego que estaba en internet .

**Comment by jmwielandt** [comment]
@rihanuch Lo siento, pero esa restricción que acabas de colocar es inválida.
1. Movimiento continuo se llama precisamente a cuando el personaje avanza una distancia variable independientemente del tamaño de las casillas, es decir, cuando la mitad del cuerpo de un personaje puede estar en una casilla y el resto en otra, como en stardew valley. A lo que tú te refieres se llama "movimiento discreto por casillas" o grid locked movement en inglés, que es el estilo pokémon.
2. **Contradice EXPLÍCITAMENTE el punto 2.4 del enunciado**, donde se especifica: _"Como el movimiento del personaje es continuo (se avanza por pixeles), si hay dos casillas vacías seguidas el personaje puede tener una parte de su cuerpo en una casilla, y otra parte en la adyacente. "_
![image](https://user-images.githubusercontent.com/37153467/41007583-7234aa1c-68f4-11e8-8148-92abada1abe5.png)

Si tienen lo otro en la pauta de evaluación solicito que la corrijan desde ya para evitar tener que mandar a recorregir todas las tareas. Y considerando que estamos a prácticamente miércoles de la segunda semana, no considero justo, oportuno o buena idea que cambien lo que aparece en el enunciado.

@Hernan4444 hola

**Comment by Arcoirisky** [comment]
Holiiiii~ 
Les dejo un link que muestra lo que queremos :D Para que no queden dudas uwu
http://www.minijuegos.com/juego/playing-with-fire-2
