### ISSUE TITLE
[Semana 8, ejercicio propuesto 1.4b] ¿A que se refiere con sincronizar el contador?

### ISSUE THREAD

**Issue by Gsalinas1506** [IIC2233/syllabus#652]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

No entiendo bien a que se refiere en la parte B del ejercicio propuesto 1.4 de la semana 8 con _sincronizar el contador de DCCriptoMonedas con los mineros._ ¿Se refiere a imprimir en pantalla el total de monedas encontradas cada vez que un minero sale de la cueva? 

PD: ¿Podrían dar un hint de como hacerlo? se me ocurre que podría haber alguna variable que comunique los 3 threads sumando la cantidad de monedas de cada minero, pero con los contenidos de esa pura sección no se me ocurre como poder hacerlo, ¿Como podria extraer datos de uno de los threads para usarlo en el thread principal?

**Comment by aaossa** [comment]
Hola @Gsalinas1506 , a lo que se refiere esa parte es que no hay un contador único, compartido, entre las instancias de esa clase, sino que cada instancia cuenta por sí misma. Lo que se espera, es que se utilice un mismo contador, pero esto puede llevarte a problemas de sincronización si es que se intentan hacer dos actualizaciones de un valor muy cerca una de otra. En los contenidos vimos maneras de evitar estos problemas, relacionados con la sección crítica de código que sería la actualización del contador, así que se espera que ocupes eso 🔒 .

PS: Eliminé la imagen de tu código. No por colocar "*spoiler*" deja de ser compartir código. Al hacer eso, podrías pasar a llevar la intención de otres de aprender haciendo el código por su cuenta, así que por eso la eliminé 😅

**Comment by amahns1** [comment]
Hola @aaossa !

Al usar un lock, los mineros entran en orden. Mi duda es si existe una manera de usar locks sin quitar el paralelismo entre threads.
Creo que estoy un poco confundido en este punto.
Al usar locks, el programa ejecuta en orden los threads.
¿Eso es lo que se espera en el ejercicio? ¿O existe una manera de usar los locks manteniendo el paralelismo entre threads?

No sé si se entiende la pregunta jajajaja.

Un abrazo.

**Comment by aaossa** [comment]
Hola @amahns1 ,

Cuando estás usando *locks*, lo que haces es prohibirle a otros *threads* ingresar a la sección que estás protegiendo con el *lock* mientras haya otro *thread* dentro. Ojo que esto ocurre solo dentro de esa sección, no es como que al instanciar un `Lock` automáticamente los *threads* dejen de funcionar en paralelo, sino que solo dejan de hacerlo dentro del *lock*.

Puedes pensar en un *lock* de la siguiente manera. En una carretera (*thread* principal) van avanzando varios autos 🚗  (*threads*) a su propia velocidad y ritmo. Algunos tienen que detenerse en un punto de carga 🔌, pero mientras un vehículo está cargando ningún otro puede hacerlo, sino que tienen que esperar. Esto podrías hacerlo con un *lock*, ya que de esta manera solo puedes tener un *thread* (auto 🚗) a la vez en la sección crítica (punto de carga 🔌). Notar que los demás *threads* van a seguir funcionando de la manera normal, **solo aquellos que están intentando adquirir el *lock* quedan "pausados"**.

También puedes pensarlo de la manera opuesta. Si el paralelismo siguiera funcionando independiente de los *locks*, ¿para qué quieres usar *locks* entonces? La idea de los *locks* es evitar problemas de sincronización, pero si estos no ocurren (por ejemplo, no están accediendo o modificando memoria compartida) no es necesario utilizarlos.

Espero se entienda 😅 Si algo no queda claro vuelve a preguntar no más 👌

**Comment by amahns1** [comment]
Si se entiende!

Gracias :)
