### ISSUE TITLE
colisiones

### ISSUE THREAD

**Issue by santilaguna** [IIC2233/Syllabus#652]
Hola, tengo una duda respecto de las colisiones, se debe evaluar las colisiones entre jugadores (multijugador)  y las colisiones entre enemigos ? No aparece en el enunciado y he visto juegos con ambas formas de interacción, por lo que no sé que se espera en este punto

**Comment by santilaguna** [comment]
Gracias!

**Comment by Jj1martinez** [comment]
Hola! Las colisiones entre el personaje principal y algún enemigo, la colisión se refiere a que el programa sepa que perdió una vida? O que ninguno de los dos pueda avanzar en la dirección del otro, que se impida que estos se solapen.
