### ISSUE TITLE
Aparicion de objetos

### ISSUE THREAD

**Issue by ptflores1** [IIC2233/Syllabus#652]
En 4.5.2 del enunciado dice: 

> Las apariciones de cada objeto son aleatorias en tiempo uniforme entre 1 y 30 segundos

Estas apariciones son independientes ? es decir cada una tiene su propio tiempo de aparición o es el mismo tiempo para todos? en caso de que sea el mismo tiempo para todos la elección del objeto es aleatoria? (`random.choice`)
Gracias !

**Comment by hanavarrete** [comment]
Las apariciones deberían ser independientes, pero realmente no está especificado. Queda a tu criterio con lo que te parezca mejor. Saludos!

**Comment by ptflores1** [comment]
Gracias !

**Comment by mjgutierrez1** [comment]
¿Puedo cambiar los tiempos entre apariciones? Pregunto porque es distinto que aparezcan, por ejemplo, vidas extra a que aparezcan safe zones con distribución uniforme entre 1 y 30 segundos, ya que las primeras desaparecen cuando el jugador las usa, mientras que las segundas no. Esto podría provocar que el juego se llene de safe zone y sea incómodo.
