### ISSUE TITLE
Funcion 2

### ISSUE THREAD

**Issue by cmarquez1** [IIC2233/syllabus#652]
Hola, me sale que no funcionan mis test de la funcion 2, siendo que por ejemplo si creo un archivo con el path" student_solution\save_tree_1.json" y le hago un json.dumps ha este diccionario: "{'value': 1, 'left': {'value': 2, 'left': {'value': 5, 'left': None, 'right': None}, 'right': {'value': 7, 'left': None, 'right': None}}, 'right': {'value': 3, 'left': {'value': 6, 'left': None, 'right': None}, 'right': None}}
", lo cual segun yo esta bien escrito como se deberia.

**Comment by Hernan4444** [comment]
Hola,

En el enunciado se especifica que los `None` van con comillas, es decir, `"None"`y por eso el test puede que no te está funcionando.

Saludos ✌️
