### ISSUE TITLE
Como conectar servidor y cliente en dos computadores diferentes

### ISSUE THREAD

**Issue by DQPalomera** [IIC2233/syllabus#652]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola! 
Estaba probando los códigos de los contenidos de Networking 🌐, o en realidad los ejemplos dados, y los hice en mi computador y me funcionó bien, pero cuando traté de hacerlo en dos distintos en diferentes casas me dio ```TimeoutError``` bueno dado que la conexión de demoró mucho. Lo hice colocando la IP pública y local del computador en que inicializaron el servidor, pero no funcionó. Esto se puede hacer de otra manera?

También tenía dudas con este ejemplo porque nunca puedo terminar el socket, y no sé en que parte colocar un ``socket.close()`` osea me refiero a que en la consola me tira siempre a escribir un mensaje y no termina, me pregunto si se podría cerrar de alguna manera o debe quedar asi y cerrar la ventana de la consola no mas?

Muchas gracias de antemano

**Comment by Pablok98** [comment]
¡Hola! 

Con respecto a tu primera duda, esto es porque la conexión a través de la red "pública" (digamos) funciona un poco distinto a la red privada que tienes en tu casa. Existen distintos métodos para hacerlo funcionar, el más común es exponer algún puerto de tu red privada a internet, y luego asociar el `socket` a ese puerto que tienes público (puedes buscar más en internet sobre _port forwarding_ y como hacerlo con *sockets* de Python, aunque ten cuidado que puede tener riesgos de seguridad)

Con respecto a tu segunda duda, no estoy seguro si la entiendo, pero recuerda que si tienes algún `input()` en tu código, este podría estar programado independiente de tu `socket`, por lo que si cierras el `socket `tu programa podría seguir escuchando inputs. 

Si puedes especificar más tu segunda duda, quedo atento 😁

**Comment by DQPalomera** [comment]
Ahh yaya muchas gracias por la respuesta! Tendré cuidado, buscaré al respecto, pero quizás no lo implemente hasta averiguar su seguridad.
En relación a la segunda pregunta, era dado que generalmente cuando corro un código en la consola este en algún momento termina, y puedo volverlo a correr. El problema con este código de los ejemplos, es que ni el código cliente ni servidor terminan, por más input que le entregue al cliente y que llegan al servidor, entonces mi duda era si es que había alguna forma de terminar la ejecución, o si es que debería correr para siempre porque asi son los códigos no más. Estos no vienen con el ``socket.close()`` implementado, por eso me preguntaba si es que si lo implemento me funcionaría cerrarlos, sin embargo, los implmenté y no se cerraron. Y aqui me nació otra duda que era si es que no se podía omplementar, o si lo implementé incorrectamente que es lo más probable xD, entonces me gustaría saber como implementarlo o que sucede ahí.

**Comment by Pablok98** [comment]
Ahh, ya te entiendo, no me había percatado de que en los ejemplos de clases no se utilizaba. En la ayudantía vimos un ejemplo cerrando el socket! Están subidos, comentados y explicados, de seguro eso te ayuda. Si sigues con dudas, me dices nomas 😁

**Comment by DQPalomera** [comment]
Yap, los veré muchas graciass
