### ISSUE TITLE
[T6] Lag en el timer

### ISSUE THREAD

**Issue by aeperalta** [IIC2233/Syllabus#652]
Hola!

Tengo una duda. En el servidor hice un QThread que va actualizando el tiempo de cada uno de los clientes que están en las salas (mediante señales) y a la vez, cuando se reinicia el contador, cambia las canciones. El problema es que se lagea harto, a ratos anda bien y derrepente se demora mucho entre segundo y segundo. Lo hice de esta forma porque me asegura que todos los clientes estén sincronizados. También intenté con un par de QTimers  (uno de 20 seg para cambiar las canciones y otro que cada un segundo tira el tiempo restante que le queda al usuario para contestar) y pasa el mismo lag.

También había pensado, como segunda opción, en la posibilidad de mandar la señal solo cuando se reinicia el contador y que en cada uno de los clientes se corra el tiempo por sí solo, pero no sé que tan bueno será que los clientes no estén completamente sincronizados.

Alguna recomendación?

**Comment by hanavarrete** [comment]
Podrías probar haciendo lo último, dado que en nuestro caso siempre les llegará al mismo tiempo lo que envíes del servidor al cliente (porque estamos trabajando en un solo  computador), entonces deberían activarse casi al mismo tiempo.

**Comment by aeperalta** [comment]
Igual es extraño, si tengo dos clientes abiertos y clickeo las ventanas del uno y del otro continuamente, funciona perfecto. De todas formas, voy a probar la segunda opción.
Gracias por la rápida respuesta!
