### ISSUE TITLE
Problemas con instalación PyQt5 en Mac

### ISSUE THREAD

**Issue by tedroppelmann** [IIC2233/syllabus#652]
Hola al intentar instalar pyqt5 con homebrew me aparece lo siguiente:
<img width="567" alt="Captura de Pantalla 2020-05-12 a la(s) 16 43 31" src="https://user-images.githubusercontent.com/42807519/81743514-c2e09400-946f-11ea-82c8-5869eda2d655.png">
Por qué será que no me valida ese formato? también me a ocurrido con otros programas usando brew...
 
Encontre esto, pero no se si tendrá relación: 
https://github.com/Homebrew/homebrew-core/issues/31510

**Comment by tomasgv** [comment]
Hola @tedroppelmann!! 

Luego de una búsqueda no tan rápida por las [issues de homebrew](https://github.com/Homebrew/brew/issues/5732), noté que al método `install` ya no se le puede entregar como `option` el argumento `--with` , o al menos no desde el núcleo principal de _homebrew_. 

El link que enviaste habla del mismo tema: se removieron muchas de las opciones de las fórmulas de _homebrew_, en particular desde la versión `2.0.0`.

La solución más directa a tu caso es usar `pip3 install pyqt5` para asegurarte de estar instalando `pyqt5` con la versión correcta de Python.

Es posible usar _brew_ en conjunto a repositorios de terceros, más conocidos como [_taps_](https://docs.brew.sh/Taps), pero eso complicaría más de lo necesario esta respuesta.

Gracias por hacernos notar que esa línea está obsoleta, y te pedimos disculpas por el mal rato.

Actualizaremos la wiki de acuerdo a esto 👍 .
