### ISSUE TITLE
[T06] recibir informacion corrupta (diferente) del socket

### ISSUE THREAD

**Issue by legramsch** [IIC2233/Syllabus#653]
Tengo un problema muy raro.. 
Estoy tratando de enviar una lista del servidor al cliente, antes y despues de eso todo bien, pero al mandar este en particular, el cliente recibe un numero diferente..
esta es la parte del codigo del cliente:
        largo = self.usuario.recv(4)
        largo = int.from_bytes(largo, 'little')
        print(largo)
        canciones = self.usuario.recv(largo)
        canciones = pickle.loads(canciones)
        print('canciones: {}'.format(canciones))

Y este es el del servidor:
                canciones = pickle.dumps(dire) #dire es la lista que quiero enviar
                largo = len(canciones).to_bytes(4,'little')
                client_socket.send(largo)
                client_socket.send(canciones)

Me asegure que no quedan otros bytes restantes de antes, y al imprimir ambos largos, el cliente me da 13, y el servidor 230!!
al imprimir el largo justo despues de enviarlo, y justo despues de recibirlo, el del servidor es b'\xe6\x00\x00\x00', y el del cliente es b'\r\x00\x00\x00'

Por favor si alguien me puede ayudar :( Sin este error, funcionaba el 90% y ahora funciona como el 30% por esto :(

**Comment by aeperalta** [comment]
me pasaba lo mismo y lo solucioné enviando por partes desde el servidor y recibiendo por partes (al menos las canciones)

**Comment by legramsch** [comment]
Descubri que, el cliente recibe 345 bytes de informacion, aunque le puse (para probar) explicitamente que recibiera 230.. Alguien sabe por que puede ser esto?
