### ISSUE TITLE
[Semana 08][Mecanismos de Sincronización][Lock] Manejo de Lock

### ISSUE THREAD

**Issue by jarvasquez** [IIC2233/syllabus#653]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Mi problema surge al obtener los resultados los ejercicios propuestos. Por ejemplo cuando los threads atienden clientes es un restorán. Al añadir el lock donde supongo que es, los threads no se traslapan (como debe ser) el único problema es que solo uno está trabajando. Obteniendo esto:

![image](https://user-images.githubusercontent.com/68974390/95146625-af063900-0754-11eb-8096-9a675efa069b.png)

Y de esta manera se pierde la gracias del Threading. ¿Qué puedo hacer?

Muchas gracias por su tiempo y disposición, quedo atento.

Saludos,

**Comment by jarvasquez** [comment]
Esto también ocurre en un ejemplo de los contenidos luego de [Locks y Context Managers](https://github.com/IIC2233/contenidos/blob/master/semana-08/2-concurrencia.ipynb)

**Comment by aaossa** [comment]
Hola @jarvasquez creo que lo que ocurre es que no estás colocando el *lock* donde se espera que lo hagas. A partir del *output* que muestras, parece que un *thread* cubre todo el *while* 😱 , por lo que un solo *thread* se estaría encargando de atender todos los pedidos mientras hayan elementos en cola (pobre *thread* 😅). 

Sobre el comentario de los ejemplos, ¿podrías indicar cuál ejemplo? Además, en los mismos contenidos se recomienda que los ejemplos se prueben ejecutando el código desde una consola (o quizás tu IDE), en lugar de los Jupyter Notebooks, por lo que podrías probar con eso también 👌 Cuéntame cómo te va y mucho éxito ✨

**Comment by jarvasquez** [comment]
Siii!!! Descubrí que era. Yo puse el lock dentro del while encapsulando todo. El problema era que uno no sabe cuando los threads se van a ir intercambiando. Por lo que puse un time.sleep() fuera del lock y ahí se irán intercalando los threads. Creo que era eso 😅

**Comment by aaossa** [comment]
@jarvasquez en teoría, los *threads* se van a ir pasando el acceso al *lock* cada vez que este se desocupe. No debería ser necesario un `time.sleep`, a no ser que todo esté ocurriendo muy rápido, así que te recomendaría mirar bien el *output* que te muestra y, nuevamente, correrlo fuera de los Jupyter Notebooks 👌

**Comment by jarvasquez** [comment]
Perfecto! Muchas gracias!!
