### ISSUE TITLE
AF7: Duda sobre ConnectionResetError

### ISSUE THREAD

**Issue by Artaudd** [IIC2233/syllabus#653]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola!, tengo una duda respecto a la excepción ConectionResetError, que se nos pide tratar en los métodos escuchar_cliente() y escuchar_servidor(). Mi duda es la siguiente, **¿Esta excepción se levantará automáticamente al intentar recibir un mensaje inexistente o debemos levantarla nosotros mismos cuando detectemos que no se recibe ningún mensaje?**
De antemano muchas gracias!

**Comment by sperezmasri** [comment]
Hola @Artaudd, **ustedes deben levantar la excepción** ```ConnectionResetError``` cuando sea necesario según lo que se menciona en el enunciado para esos dos métodos. Espero que eso resuelva tu duda, saludos! 😁
