### ISSUE TITLE
Sobreescribir FileNotFoundError

### ISSUE THREAD

**Issue by nep0s** [IIC2233/syllabus#654]
Hola, en el enunciado dice que debemos ocupar excepciones personalizadas para el código.
Como python ya tiene por defecto una excepción que trata con paths inválidos, debemos simplemente levantar nuestra excepción como reemplazo cada vez que se levanta la original?
Saludos.

**Comment by Hernan4444** [comment]
Hola,

Es justo como indicas.

Saludos ✌️

**Comment by nep0s** [comment]
Gracias!

**Comment by danielauu** [comment]
Hola, 
¿FileNotFoundError también debe levantarse cuando el archivo no es de tipo json o no contiene un diccionario? ¿o sólo se levanta cuando el archivo no existe? Me quedó esa duda,

Saludos!

**Comment by Hernan4444** [comment]
Hola,

Cuando no existe. En caso de existir, será si o si un json bien formado.

Saludos :v:
