### ISSUE TITLE
designer imagen

### ISSUE THREAD

**Issue by movaldivia** [IIC2233/Syllabus#654]
Tengo problemas al poner en un Qlabel una imagen como texto enriquecido (Designer). Cuando veo el 'pre' ui se ve perfecto, pero una vez que lo traduzco no se ve la imagen. No sé si estoy haciendo algo mal o es una limitación del programa.

**Comment by iqacevedo** [comment]
Hola,

A que te refieres por "pre" y traducir? Podrías mostrar una foto (solo del Label en cuestión) de cuando se te ve perfecto y como se te ve cuando lo "traduces".

**Comment by naazocar** [comment]
Revisa el path con con el que estas cargando las imágenes en python, a mí me pasaba lo mismo y era por eso. Lo arreglé pasando el archivo .ui a .py y buscando donde se importaba la imagen y luego copiando esa linea en mi clase que usa al archivo .ui y poniendo el path bien. Suerte :D

**Comment by movaldivia** [comment]
@iqacevedo era lo que comentó @naazocar, gracias a ambos!
