### ISSUE TITLE
Problemas con QThreads

### ISSUE THREAD

**Issue by ljrodriguez1** [IIC2233/Syllabus#654]
al implementar un QThread y su método run() respectivamente cuando quiero hacer start() ha este para que empiece se me cae el programa, y lo único que me señala python es esto:
A mi también se me cae al hacer start() y no se porque, no me lanza ningún error solo esto:
Process finished with exit code -1073740791 (0xC0000409)
Haciendo la misma clase pero heredando de Thread funciona a la perfección, solo  que no me deja usar señales ya que estas son de Pyqt5

**Comment by akrebs2** [comment]
Me sucede lo mismo. El error que me lanza es

> QThread: Destroyed while thread is still running

**Comment by IchottMano** [comment]
@akrebs2 Hola!

Lo mas probable es que tu error suceda debido a la *garbage collection* de python, lo cual significa que python ve que tu objeto que hereda de thread no tiene mas referencias, por lo que lo elimina.
Para solucionar esto lo mejor es guardar una referencia a tu objeto en el **Widget** padre.
``` python
self.thread = MiQThread(*args, **kwargs)
```
De este modo evitas que python elimine tus threads automáticamente.

En cuanto a @ljrodriguez1 , podrías pushear tu código a modo de poder verlo para entender mejor tu problema?

Saludos!

**Comment by ljrodriguez1** [comment]
@IchottMano mi problema se soluciono al guardar mi QThread en el Widget padre como señalaste, muchas gracias!
