### ISSUE TITLE
AF7: ¿Qué tengo que serializar en la función enviar?

### ISSUE THREAD

**Issue by B-Birb** [IIC2233/syllabus#654]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

¡Hola! Me surgió una duda con respecto al enunciado. No me queda claro **que** es lo que me piden hacer con el largo del mensaje. ¿Cómo sería el orden de las "operaciones", y sobre que opero exactamente? 
A la hora de enviar: Me dicen que envíe el largo del mensaje junto al mensaje codificado. Ese largo, sería al cuál le aplicamos las operaciones? (es decir, el largo después de serializarlo)
![image](https://user-images.githubusercontent.com/22687150/123018143-052b1300-d39c-11eb-8c4a-2eb8aff8905e.png)

Muchas gracias de antemano c:

**Comment by pabloist** [comment]
Hola buenas!

La función enviar() trabaja sobre un mensaje, el cual debe ser serializado con el método indicado. Por otro lado, el largo que se indica es posterior al procesamiento del mensaje, es decir, sobre el objeto serializado.

Saludos!
