### ISSUE TITLE
Ejercicio Propuesto 2.2 de la semana 8

### ISSUE THREAD

**Issue by n4chin** [IIC2233/syllabus#654]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Holaa, en la pregunta 2.2 del ejercicio propuesto nos sugiere usar Event, sin embargo, para definir el Event, hay que hacerlo antes de la función y el ejercicio indica que solo se puede editar el código dentro de la función o después de muchas líneas abajo, ¿qué se supone que debería hacer?

**Comment by jarvasquez** [comment]
Según yo el Event ya está definido en el ejercicio, me venía esto a mi.

![image](https://user-images.githubusercontent.com/68974390/95201358-33d56f00-07b6-11eb-9cc5-0e13b4730ca5.png)
