### ISSUE TITLE
Error con PyQt5 en Mac OS x 10.12

### ISSUE THREAD

**Issue by Tsbalart** [IIC2233/syllabus#654]
Hola, me aparece este error a pesar de haber instalado correctamente la libreria, ya lo he intentado todo, no se que mas hacer.
![Captura de pantalla 2020-05-12 a las 17 34 43](https://user-images.githubusercontent.com/62150115/81748051-29b57b80-9477-11ea-861a-cdd00c9dad57.png)

**Comment by fdoflorenzano** [comment]
Hola @Tsbalart,

Este error lo hemos visto en semestres pasados, y parece surgir en versiones de sistemas operativos anteriores a Mac OS X 10.12. ¿Será tu caso?

Si es así, tienes dos opciones:
1. Actualizar el sistema operativo.
2. Desinstalar PyQt5 e instalar la versión 5.10.1 de PyQt5 con el comando
```bash
pip3 install PyQt5==5.10.1
```

Quedamos atentos al caso.
Saludos.

PD: Créditos a @jmwielandt que respondió [una duda muy similar](https://github.com/IIC2233/syllabus-2019-2/issues/319) el semestre pasado, de la cual me basé para responder 😊 .

**Comment by Tsbalart** [comment]
Hola, tengo la version 10.12, y no me he es posible actualizarlo, intente el comando que mencionado, pero aparecio este error, ya probe desinstalando python, y tampoco funciono.
![Captura de pantalla 2020-05-12 a las 17 58 31](https://user-images.githubusercontent.com/62150115/81749750-37b8cb80-947a-11ea-882c-dfbd8e8e981f.png)

**Comment by fdoflorenzano** [comment]
Hola @Tsbalart,

El error que te sale parece ser al ir a buscar el paquete a internet. ¿Si vuelves a intentar el comando, ocurre lo mismo? ¿Estás intentando con conexión a internet al mismo tiempo?

Saludos.

**Comment by Tsbalart** [comment]
Profe! Ya se arreglo, lo corri de nuevo y funciono, no se que paso, Muchas gracias!

**Comment by fdoflorenzano** [comment]
¡¡Qué bueno!!
