### ISSUE TITLE
Supuesto servidor T06

### ISSUE THREAD

**Issue by jnlarrain** [IIC2233/Syllabus#654]
Hola me pasa que los filtros demoran mucho en crear los archivos, por lo que estructure mi programa para que el servidor tenga todos los archivos creados cuando se inicie por primera vez. Suponiendo que el servidor deberia tener los archivos con anterioridad. Por lor que implemente una pantalla de espera que se ejecuta solo cuando el servidor se esta actualizando.

Mi pregunta es, puedo realizar este supuesto?, ya que esto significaria que la primera ejecucion del servidor es lenta( al rededor de 15 min en crear todos los archivos), pero luego es muy rapida.

**Comment by DiegoAndai** [comment]
Mientras lo justifiques y expliques en el README no hay problema.
