### ISSUE TITLE
[Semana 8][Ejercicio Propuesto 2.3][DCCueva] Explicación enunciado

### ISSUE THREAD

**Issue by jarvasquez** [IIC2233/syllabus#655]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola! El ejercicio propuesto 2.3 no entendí mucho que se debe. Sé que se debe completar con un sistema de señales pero no se como debería funcionar el programa.

Dejo a continuación ciertas preguntas que me surgen al ver el ejercicio.

¿Debemos definir un conjunto de suministros que se deben pedir para ir dejando en la DDCueva?
¿A qué hacen referencia el atributo de `SuperDrone` `peticion_suministros`? ¿Es una lista con objetos que se debe trasladar a la DDCueva? ¿Es un objeto de la clase Evento?
¿A qué hacen referencia el atributo de `SuperDrone` `peticion_resuelta`? ¿Es un booleano? ¿Para qué sirve? o ¿Es un objeto de la clase Evento?

Muchas gracias por su tiempo y disposición, quedo atento.

**Comment by aaossa** [comment]
Hola @jarvasquez , tal como dices, el ejercicio está algo confuso. También me costó entender lo que se pide, pero acá va una posible interpretación 🤔 . 

Creo que lo que se espera, es que se agregue código relacionado a dos eventos: `peticion_suministros` y `peticion_resuelta`. Puedes verlo como una conversación entre `DCCueva` (quien pide los suministros 🚧 ) y `SuperDrone` (quien los entrega 🛩️ ). Entonces, un mes normal iría de la siguiente manera: al empezar el mes, `DCCueva` pide los suministros y queda esperando a que `SuperDrone` los procese (lo que toma, por ejemplo, 2 días). Cuando los suministros estén listos, hay que avisarle a la `DCCueva` que la petición está resuelta, y así puede utilizar los suministros (por ejemplo, por 5 días). De esta manera, ambas clases van comunicandose por medio de dos eventos, y así saben cuándo pueden trabajar y cuándo no.

Con esto, creo que ya queda más claro lo que podrían ser las respuestas a tus preguntas, así que acá van:
* En este ejercició qué es un suministro o cómo se representa no importa, solo importa si se pidió o no (lo que se marca en el `Event`) 🎏 
* El argumento `peticion_suministros` es una instancia de `Event`
* El argumento `peticion_resuelta` es otra instancia de `Event`

En este ejercicio hay dos cosas que debes hacer: 1) ver dónde instanciar los eventos (fíjate en el `__init__` de cada clase y sabrás donde hacerlo) y 2) ocupar los métodos de `Event` apropiadamente para permitir una buena comunicación. Para que puedas guiarte un poco, el *output* del ejercicio como lo hice yo se ve así (para 3 meses, 5 segundos de trabajo y 2 de preparación de suministros):

```
Comienzan operaciones en la DCCueva!
DCCueva: Enviando petición de suministros (Mes 1)
SuperDrone: Esperando la petición de suministros
Resolviendo... 1/2
Resolviendo... 2/2
SuperDrone: Enviando la petición resuelta
SuperDrone: Esperando la petición de suministros
DCCueva: Esperando petición resuelta (Mes 1)
Trabajando... 1/5
Trabajando... 2/5
Trabajando... 3/5
Trabajando... 4/5
Trabajando... 5/5
DCCueva: Enviando petición de suministros (Mes 2)
Resolviendo... 1/2
Resolviendo... 2/2
SuperDrone: Enviando la petición resuelta
DCCueva: Esperando petición resuelta (Mes 2)
SuperDrone: Esperando la petición de suministros
Trabajando... 1/5
Trabajando... 2/5
Trabajando... 3/5
Trabajando... 4/5
Trabajando... 5/5
DCCueva: Enviando petición de suministros (Mes 3)
Resolviendo... 1/2
Resolviendo... 2/2
SuperDrone: Enviando la petición resuelta
SuperDrone: Esperando la petición de suministros
DCCueva: Esperando petición resuelta (Mes 3)
Trabajando... 1/5
Trabajando... 2/5
Trabajando... 3/5
Trabajando... 4/5
Trabajando... 5/5
```

Ojalá te sirva ✨ Si algo no queda claro pregunta no más 👌

**Comment by jarvasquez** [comment]
Pefecto! Muchas gracias Profesooor! Ahora me queda clarísimo.
