### ISSUE TITLE
Iniciar sesión github

### ISSUE THREAD

**Issue by barbaracalderonr** [IIC2233/syllabus#655]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

Hola!, nunca había tenido problemas con git, pero ahora para la actividad, estaba subiendo mis archivos al repositorio, y cada vez que hago push, me pide iniciar sesión, hay alguna forma de arreglar esto?, nunca me habia pasado:(

**Comment by joalonsosch** [comment]
A mi me viene pasando lo mismo hace un tiempo. No lo he sabido arreglar, pero si recibí un mail de github donde se explicaba que a partir de cierta fecha van a pedir que uno inicie sesión para hacer algunas acciones de gitbash (o al menos eso entendí). No solo te va a pasar con el push, también con el pull, para que sepas.

**Comment by Julius9** [comment]
Hola @barbaracalderonr @joalonsosch ! :smile: ¿de casualidad que sistema operativo tienen? ¿Han intentando probar la configuración de la [wiki](https://iic2233.github.io/wiki/software)? Pero bueno en resumen para configurar git y evitar que se nos pregunten siempre las credenciales, debemos introducir lo siguiente en la terminal:

```git config --global user.name "NOMBRE APELLIDO"```

```git config --global user.email correo_usado_en_git@uc.cl```

Si a pesar de esto, el problema persiste por favor nos cuentan por acá para poder darles otra solución

**Comment by joalonsosch** [comment]
Hola @Julius9 !
Mi sistema operativo es windows 10 home.
Si probé la configuración de la wiki, la hice al principio del curso (mucho antes de que se presentara el problema) y justo después de que comenzó a aparecerme. A pesar de haber hecho hartas veces esos dos comandos en ese orden y con mis datos, no se ha solucionado. En verdad llevo desde un poco antes de la entrega de la T3 con esto y no lo encuentro tan molesto tampoco. Si quieres me mandas tu mail y te comparto el que me llegó de github desde que partió el problema, tal vez eso te sirve para entender que es, porque yo lo leí y no decía como solucionarlo.

**Comment by barbaracalderonr** [comment]
Hola, yo también tengo windows 10, y yoo también probé lo de la wiki, sin resultado, me sigue pidiendo las credenciales... y a mi también me había llegado un mail desde github, algo de actualizar el token algo así, pero lo leí y no logré encontrar como solucionar lo de las credenciales.

**Comment by Julius9** [comment]
yap, entonces deben ejecutar el siguiente código en la terminal:

```git config --global credential.helper 'store'```

Con esto deberían tener que iniciar sesión una vez más y quedara listo.

**Comment by joalonsosch** [comment]
Lo ejecuto pero no pasa nada...

**Comment by Julius9** [comment]
Que raro, puedes reintentarlo con el metodo que se presenta en esta [pagina](https://www.freecodecamp.org/news/how-to-fix-git-always-asking-for-user-credentials/) o puedes crear un token de acceso como se describe en esta [pagina de github](https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token)
