### ISSUE TITLE
Problemas instalación PyQt5 windows

### ISSUE THREAD

**Issue by Francisco5674** [IIC2233/syllabus#655]
Hola buenas
Resulta que estoy teniendo muchos problemas para instalar PyQt5, resulta que lo instalaba correctamente, sin embargo siempre lo hacia en los archivos de la versión 3.8 de python la cual instale tiempo atras por error, y luego instale la versión 3.7 correspondiente, lo malo es que ahora no se como instalarlo para que funcione en la 3.7, he intentado toda la tarde sin solución, desinstale python 3.8 para ver si tomaba la 3.7 pero ahora es peor, ahora ni siquiera quiere instalarse, necesito una forma de cambiar el directorio de instalación que al parecer es diferente al directorio en el que me encuentro.

![Captura de pantalla (3)](https://user-images.githubusercontent.com/61996440/81748384-c710af80-9477-11ea-92de-872582f6d0b5.png)

**Comment by entamburini** [comment]
Hola @Francisco5674! :)

Lo que pasa es que al haber tenido dos versiones de python instaladas, Windows se queda con la última ruta donde tiene a python. Para arreglar ese problema, tienes que indicarle donde está el pip que tu quieres usar (para que sea el por defecto).

Te recomiendo que veas el método 2 de [esta guia](https://datatofish.com/add-python-to-windows-path/), está en inglés pero tiene dibujitos y son instrucciones bien claras. De todas formas si no entiendes cualquier paso puedes preguntarme por aquí :)

**Comment by Francisco5674** [comment]
Hola! sorry por no responder que onda, ayer tenia muchas cosas que hacer con otros cursos, por cierto ya intente lo que me dijiste, seguí la guía paso a paso y el problema persiste, estoy pensando en reinstalar Python 3.8 y usarlo con esta versión como ultimo recurso.

**Comment by Francisco5674** [comment]
Ahora el problema es que no reconoce el comando "pip"
![image](https://user-images.githubusercontent.com/61996440/81843518-b285f300-951b-11ea-85d6-462b4de9e414.png)

**Comment by Francisco5674** [comment]
Disculpen, todo solucionado, si funciono, son unos genios, por fin voy a poder practicar, muchas gracias!!!

**Comment by entamburini** [comment]
Seguiste el tutorial? :), genial que te haya funcionado :rocket:
