### ISSUE TITLE
Error en el ecualizador 

### ISSUE THREAD

**Issue by Nicolasvegam** [IIC2233/Syllabus#655]
Hola,
Tengo un error en el ecualizador, he tratado byte por byte revisándolo y según yo está bien. Le cambie el samplerate al head del wav, pero solo me funciona con multiplico por 1 la frecuencia ( que es dejar igual el sample rate ) y cuando lo pruebo con otro valor distinto el reproductor me tira error. Estoy manteniendo el largo samplerate cuando lo cambio pero aún así me falla.  Por otra parte probé la otra modificación de los canales y la única diferencia con el wav original (sin modificar el head) es que se escucha un ruido al principio.

**Comment by DiegoAndai** [comment]
Hola! la canción no debería fallar al cambiar el SampleRate, ¿estás seguro que no cambiaste nada más? No entendí que quiciste decir con "Estoy manteniendo el largo samplerate cuando lo cambio pero aún así me falla". Por último la modificación de los canales puede no notarse si se ocupan en bajos n. Intenta buscar en las muchas issues de ecualizador que se discutieron en la semana, quizás por ahí encuentres solución. Algunas son : #595, #628 y #619

**Comment by Nicolasvegam** [comment]
Ya las leí por eso abrí una issue:(
Mi problema es con el samplerate, primero lo saco del wav, y lo convierto a int con int.from_bytes y ejemplo me da: 44000 , eso lo multiplico por la frecuencia, dejo la parte entera y lo transformo a mi_int.to_bytes(len(samplerate), byteorder=little) y luego lo escribo (sin modificar el data) y me tira error excepto cuando lo multiplico por 1 :( no se porque soy al único que le pasa esto jjja

**Comment by negutierrez** [comment]
A mi me pasa que aunque el header este perfecto (identico al original), QSound no lo reproduce, mientras que optros programas si

**Comment by DiegoAndai** [comment]
@negutierrez ¿quizás modificaste el data y quedó inconsistente el largo con el largo que aparece en el header? es lo primero que se me ocurre.

@Nicolasvegam que raro, ocupaste byteorder = little para transformar desde los bytes también, ¿cierto?

**Comment by Nicolasvegam** [comment]
@DiegoAndai sip para transformar también :(
