### ISSUE TITLE
Problema con git pull 

### ISSUE THREAD

**Issue by rosariodominguezm** [IIC2233/syllabus#656]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

Hola! No sé bien qué hice alguna vez, pero no puedo hacer git pull. Me tira:

error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.

Y no sé como arreglarlo. Feliz si me pueden ayudar

**Comment by tomasgv** [comment]
¡Hola @rosariodominguezm! 

A continuación verás una respuesta un poco larga 😅 . Antes de leerla, **considera el repositorio en el que estás**. Si es el syllabus, nunca necesitarás hacer `push` de tus cambios locales, por lo que te recomiendo leer el primer y segundo punto de solución. En caso de que sea tu repositorio privado, posiblemente necesites hacer `push` de los archivos conflictivos, por lo que es de utilidad leer el tercer punto de solución. 

Ahora vamos al error:

Ese error indica que hay archivos que no han sido fusionados en tu rama de trabajo. Esto quiere decir que hay uno o más archivos esperando a ser fusionados manualmente antes de hacer `pull`. El problema de fusión (`merge conflict`) pudo haberse producido porque en algún momento anterior hiciste `pull` de cambios remotos, teniendo otros cambios localmente. Esto en algunos casos no puede ser solucionado automáticamente, quedando en un archivo sin fusionar, o `unmerged file`, como se menciona en el mensaje de error.

Existen distintas maneras de arreglar esto 🙌 . Primero, prueba haciendo `git status`. Git te debería mostrar el o los archivos que están teniendo problemas (busca la palabra `unmerged` y los archivos que se mencionen junto a eso). 

Comenzaré explicando las soluciones más cortas y rápidas, pero también mostraré otras soluciones que podrás aplicar en el futuro si te vuelves a topar con este problema.

- El primer método y más directo es llevarte los archivos conflictivos (los que se mencionan como `unmerged` al hacer `git status`) a otra carpeta, luego hacer `pull`, y finalmente reemplazar la versión del archivo traído por el pull con la que guardaste. En caso de que no quieras quedarte con los archivos conflictivos, puedes eliminarlos y quedarte con la versión del repositorio remoto. Ten en cuenta que los archivos conflictivos probablemente seguirán en la condición de `unmerged`, y la solución a eso se habla en el tercer punto.

- El segundo método es similar pero utilizando comandos de git, y consiste en probar la solución expuesta en #318. Esa secuencia de comandos indica guardar los cambios locales en el `stash`, hacer `pull`, y luego aplicar los cambios guardados del `stash`. Hay más información sobre `git stash` [aquí](https://git-scm.com/docs/git-stash). Nota que esto no es una solución definitiva y solo quita los cambios temporalmente para hacer `pull` y luego aplicarlos de nuevo. Si no quieres volver a aplicar los cambios, puedes no hacer `git stash pop`.

- Puede que lo anterior no funcione debido a algún caso borde (quizás hiciste `commit` de tus cambios en el estado `unmerged`), por lo que quedaría resolver manualmente los archivos con problemas. Si decides hacer esto, entra a los archivos que se mencionan al hacer `git status` y busca lo siguiente:
    ```
    <<<<<<< HEAD
    Aquí está tu versión del código
    =======
    Aquí está la versión remota del código
    >>>>>>>
    ```
    Llegados a este punto, debes decidir qué partes del código dejar. Puedes borrar libremente las marcas que Git hizo en tu archivo luego de esto. Habiendo terminado esto, ¡habrás resuelto un conflicto de `merge` de git manualmente! 🎉   Puedes darte una palmadita en la espalda y felicitarte por llegar tan lejos.

Perdón por la gran cantidad de texto 🙏  . 

¡Avísame cómo te va! 👀

**Comment by rosariodominguezm** [comment]
Hola! Me resultó! Muchas gracias por la explicación!!
