### ISSUE TITLE
duda Qsound

### ISSUE THREAD

**Issue by Dunkan1** [IIC2233/Syllabus#656]
para reproducir las canciones hago
```
def __init__():
 |
def ini_gui():
        self.a = QSound(path)
        self.a.play()
```
lo cual funciona bien, pero cuando intento cambiar la cancion, en una funcion aparte
haciendo

self.a.stop()
self.a = QSound(nuevo path)
self.a.play()

no toca nada, ya he intentado de muchas formas pero aun
no puedo hacer que toque la siguiente cancion 😭,
por favor necesito ayuda

**Comment by Okhan97** [comment]
Me pasa lo mismo, dependiendo de donde defina el QSound o toca o no toca D:

**Comment by Dunkan1** [comment]
necesitamos ayuda D,:

**Comment by DiegoAndai** [comment]
Hola, #634 o #608 no resuelve sus problemas?

**Comment by Dunkan1** [comment]
pero hay algo que no entiendo es necesario hacer una senhal,
porque la segunda vez que hago 

self.a.stop()
self.a = QSound(nuevo path)
self.a.play()

es una funcion de la misma clase, en la que lo hice primero
