### ISSUE TITLE
Grilla

### ISSUE THREAD

**Issue by Cschavez** [IIC2233/Syllabus#656]
Hola! El mapa debe ser si o si hecho en un QGridLayout?

Muchas gracias

**Comment by mfanselmo1** [comment]
Hola!
No necesariamente debe ser hecho asi. Lo que se acomode mejor a lo que hagas es lo mejor.

**Comment by Dyoma3** [comment]
Yo lo hice con grid pero me quedaron espacios entre cada grilla, alguien sabe como hacer para quede continuo?
