### ISSUE TITLE
Problema con DLL's de PyQt5 en Windows 

### ISSUE THREAD

**Issue by jirarrazaval** [IIC2233/syllabus#656]
Hola!
Recién ejecuté ```pip3 install pyqt5``` y se me había instalado, pero cuando probé el primer código del cuaderno de los contenidos me salió 

```
from PyQt5.QtWidgets import QWidget, QApplication
ImportError: DLL load failed: No se puede encontrar el módulo especificado
```

entonces me metí a los issues y en la #646  a otro alumno le pasó lo mismo donde la solución que pusieron era ejecutar 
```python -m pip install --upgrade pyqt5```
pero cuando lo ejecuté me salió algo de que se había desinstalado, y probé con el código del cuaderno a ver si funcionaba y no funcionaba, salía el mismo error.
Entonces traté de instalar denuevo el PyQt5 con ```pip3 install pyqt5``` y ahora me sale este error:

![image](https://user-images.githubusercontent.com/62080216/81752617-cd0a8e80-947f-11ea-843c-e559ac0315d5.png)

No sé qué hacer :( porque antes cuando ejecutaba ese mismo código sí funcionó instalarlo pero igual no me funcionaba el cuaderno 
He estado mucho tiempo en esto

**Comment by aaossa** [comment]
Hola, como primer paso al parecer hay que instalar "wheel": `pip3 install wheel`. Luego intenta instalando nuevamente "pyqt5": `pip3 install --upgrade pyqt5`. Si te vuelve a tirar el error del DLL al importar PyQt5, intenta reiniciar tu computador antes de volver a probar. Comentanos cómo te va, por si eso también sirve para más personas 🙌Esperemos que funcione 🤞

**Comment by jirarrazaval** [comment]
@aaossa  me sale esto, al parecer ya lo tengo instalado pero igual no funciona el codigo del cuaderno y sigue saliendo el mismo error!
![image](https://user-images.githubusercontent.com/62080216/81759706-6b541f80-9493-11ea-9274-70311d8528d3.png)

**Comment by entamburini** [comment]
Hola!

Este problema fue solucionado con @jirarrazaval, lo que sucedía era que tenía demasiadas versiones de python instaladas (2, una de 32 bits y otra de 64, y anaconda), lo que provocó ciertos conflictos.

La solución fue desinstalar y borrar todo lo que tenga relación con python (obviamente no los códigos propios), y volver a instalar la versión más actual de python 3.7 en 64 bits. Una vez hecho eso se pudo instalar PyQT de forma correcta. 

Lo dejo como solución por si alguien tiene el mismo problema :raised_hands:
