### ISSUE TITLE
Representación gráfica

### ISSUE THREAD

**Issue by depstein26** [IIC2233/Syllabus#656]
No me queda claro como deben ser los aprietes de los personajes, se debe tener uno igual para caminar y estar parado y otros 3 diferentes para atacar? O sea necesitaría 4 imágenes diferentes por personaje?

**Comment by tcgarrido** [comment]
Hola! 

En la sección 4.9 del enunciado dice que debes considerar al menos tres estados de movimientos para cada acción.

**Comment by depstein26** [comment]
Si lo leí pero sigo sin tenerlo claro, no entiendo bien a que se refiere con un estado. Debo tener 3 para atacar, una para estar detenido, una para moverse y que más.

**Comment by naazocar** [comment]
Según yo se refiere a esto: http://supermariobroscrossover.com/media/mario-super-mario-bros-3.150/full

En toda la fila de arriba (salvo el primer cuadro) salen los "estados" por los que pasa mario mientras hace una misma acción (correr). Al pasar esos fotogramas rápido parece que se moviera de verdad. 

Entonces son 3 sprites para cuando ataca y 3 para cuando se mueve (imagino que el de estar parado puede ser uno solo?)

**Comment by Arcoirisky** [comment]
@depstein26 escucha a @naazocar  :D  Un estado es una "imagen" de la fila. La idea es que el personaje se note como que está avanzando o atacando por decir algo.
