### ISSUE TITLE
AF7: No se abren las interfaces

### ISSUE THREAD

**Issue by B-Birb** [IIC2233/syllabus#656]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola! Al intentar correr ambos archivos main.py, por alguna razón no se están abriendo las interfaces del cliente. Fui probando, y (asumo) que el cliente se crea correctamente, ya que si se conecta con el servidor y el programa puede seguir avanzando correctamente. 
¿Qué podría estar haciendo mal?  ¿O es quizás un error del código? 
Gracias de antemano

**Comment by BenediktKd** [comment]
Me sumo a la duda

**Comment by Maxy15** [comment]
Me sumo también a la duda

**Comment by aaossa** [comment]
¡Hola! Sí, en el enunciado se nos pasó indicar que, si la conexión es exitosa, se debe "mostrar la interfaz utilizando el método `mostrar_login` de `self.controlador` (no recibe argumentos)". O sea, después de quedar escuchando los mensajes del servidor denen utilizar `self.controlador.mostrar_login()`. Actualizaremos el enunciado y el código pronto con este cambio 🙌 ¡Gracias por el aviso!

**Comment by franciscareti** [comment]
Hola! Agregando eso no me funciona bien. Me aparece la ventana de inicio de sesión pero al ingresar un usuario y presionar enviar, el programa se queda esperando el feedback del backend y nunca llega. No me queda claro dónde está ese backend al que se refieren en el código (ventana_inicio.py en la función recibir_feedback) y dónde se conectan las señales correspondientes entre frontend y backend en las ventanas, feliz si me pueden ayudar. Gracias!!

**Comment by aaossa** [comment]
Hola @franciscareti , el *feedback* se recibe por medio de la señal `recibir_feedback_signal`, la que se emite desde `manejar_mensaje` en `interfaz.py`, todo esto en la carpeta del cliente. El método `manejar_mensaje` debes invocarlo en `escuchar_servidor`. Te recomendaría revisar qué le llega de *input* al método `manejar_mensaje` (por si no le está llegando algo). Otra opción es que no le estés enviando la información al servidor, ya que debes tener el método `enviar` implementado (mira la señal `enviar_nombre_usuario_signal` en `ventana_inicio.py`, la que se conecta en `interfaz.py`)

**Comment by mjsifri** [comment]
Hola! a mi me pasa que agregando esa línea sigue sin mostrarme la interfaz! Que puede ser?
Saludos

**Comment by BenediktKd** [comment]
Hola, a mi tampoco me carga con el nuevo commit.

**Comment by aaossa** [comment]
Hola @mjsifri y @BenediktKd , es bien difícil decir qué podría ser. Les recomiendo agregar un par de `print` tanto en cliente como servidor para confirmar que los mensajes se están enviando correctamente entre uno y otro, y así identificar dónde está el error. Podrían ser muchas cosas y es código que hicieron ustedes, por lo que no puedo decir exactamente qué es 😅 . Podría ser que el cliente no está enviando bien las cosas al servidor, o que este no las decodifica bien. Si agregaron  a línea `self.controlador.mostrar_login()`, esta debería ejecutarse cuando se recibe la información correcta. ¿Saben si se ejecuta esa línea? También les recomiendo revisar eso.
