### ISSUE TITLE
Uso de Join para threads distintos de MainThread

### ISSUE THREAD

**Issue by ian-fell** [IIC2233/syllabus#657]
Hola. Me surgió una duda con respecto al join, y es que en los contenidos se usa el join solo para detener el MainThread. Con esto me refiero a que todas las veces que usan join solo se detiene el código principal, por ejemplo, usar T1.join() para que el MainThread espere a T1, pero como puedo hacer para que un thread cualquiera que yo creo pueda esperar a otro usando join()? Hacer por ejemplo que un thread T2 espere a un T3 usando join?

**Comment by aaossa** [comment]
Hola, en primer lugar, por favor no borres el texto de la plantilla, sino no tenemos cómo saber que hiciste lo que se pide. En cuanto a tu pregunta, la respuesta corta es que sí se puede, de hecho lo encontré textual en la documentación de Python. Sin embargo, lo primero que se me ocurrió fue intentar hacerlo por mi cuenta (lo que recomiendo harto) y llegué a este código de prueba que te comparto:

```python
import threading
import time


def trabajar(segundos, thread_amigo=None):
	print(f"{threading.current_thread()}: Voy a trabajar {segundos} segundos")
	if thread_amigo is not None:
		print(f"{threading.current_thread()}: Antes de partir, esperaré a {thread_amigo.name}")
		thread_amigo.join()
		print(f"{threading.current_thread()}: Parece que {thread_amigo.name} terminó así que ahora trabajaré yo")
	time.sleep(segundos)
	print(f"{threading.current_thread()}: Trabajé por {segundos} segundos")

t1 = threading.Thread(target=trabajar, args=(5,))
t2 = threading.Thread(target=trabajar, args=(5,), kwargs={"thread_amigo": t1})

t1.start()
t2.start()
```

Como puedes ver, hice una función `trabajar` que cada uno de los *threads* ejecutará por una cantidad determinada de segundos. Sin embargo, el *thread* `t2` esperará a que su `thread_amigo` termine de trabajar. Por lo tanto, si bien a ambos *threads* les pedimos que trabajen por 5 segundos, el código tarda aproximadamente 10 segundos en correr, ya que desde `t2` le hacemos *join* al *thread* `t1`.

Si algo no se entiende pregunta acá no más 👌 Buena pregunta ✨
