### ISSUE TITLE
Duda sobre argumento "" en socket.bind( )

### ISSUE THREAD

**Issue by Ignacioislae** [IIC2233/syllabus#657]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### ¿Que hace el argumento "" en socket.bind( "", puerto)?
En el material dice que "Con un string vacío como argumento del bind, indicamos que el socket es  alcanzable desde cualquier dirección que pueda tener el servidor", pero no entiende a que se refiere.

**Comment by tqmbanados** [comment]
Hola! En primer lugar, te recuerdo que el método ```bind``` recibe una **tupla**, es decir, el llamado correcto es ```sock.bind(("", puerto))```. Esta distinción es importante!
Ahora para tu pregunta real, no es algo con lo que debas preocuparte demasiado en el curso. Pero a grandes rasgos, un *server* puede tener más una dirección. Por ejemplo, "localhost", corresponde a una IP específica (127.0.0.1) que representa la conexión de tu computador "con si mismo". Es decir, si entregas como argumento "localhost", **sólo programas creados en el mismo _host_ (es decir tu computador) podrán conectarse a ese _server_**. Por el otro lado, también tienes una IP asignada por tu router, que usualmente es algo como ```192.168.0.1.```. Esta IP sirve para que otros computadores en la misma red local (es decir, compartiendo router) puedan conectarse a tu computador. También tienes la IP "real" con la cual te conectas a internet, y que es personal a tu computador (¡aunque puede cambiar!). 
Entonces, al entregar un string vacío,  le estas diciendo al socket que pueden llegar conexiones entrantes utilizando cualquiera de esas direcciones IP. En general, te recomiendo que especifiques la IP que va a ser usada. "localhost" es una buena opción si sólo te comunicarás ente programas de un mismo computador.

Espero que se te aclare un poco más con esta explicación! Cuentame como te va.

**Comment by Ignacioislae** [comment]
Si me quedo mucho mas claro! Gracias! 
¿Eso si siquisiera que computadores fuera de mi red local se conectaran con mi programa cual IP deberia usar?

**Comment by Ignacioislae** [comment]
Si me queda clarisimo. Gracias!
