### ISSUE TITLE
Heroku y Manejo Webhook

### ISSUE THREAD

**Issue by maxfreymo** [IIC2233/Syllabus#657]
En la documentación de la API de Github, específicamente a la hora de configurar el servidor, se habla de exponer nuestro servidor web local a internet (Ocupando ngrok). En nuestro caso, ¿esto no sería necesario porque ocuparíamos la app de heroku para tener nuestro servidor en internet? 

¿Es esto el objetivo de ocupar heroku: mantener nuestro servidor en la  web?
 
Si es así, ¿el payload URL que deberíamos colocar en el respositorio github creado es el entregado por heroku, el visto en la documentación de webservices o algún otro ? (ejemplo: https://git.heroku.com/heroku-maxfreymo1.git    o    http://localhost:8080/)

Por lo anterior estoy confundido de si escribir en el Procfile textualmente 
web: flask run --host=0.0.0.0 --port=$PORT
¿O debo modificar el host y/o el puerto?

Saludos :D!

**Comment by MainScientist** [comment]
Tu pregunta tiene varias cosas por que partiré desde el principio. El internet es un lugar grande (muy grande) y por esto cada dispositivo conectado a él cuenta con una dirección, de forma de que exista una forma comun de cómo encontrarse. Por eso existen las direcciones IP (Internet Protocol). Las direcciones IP  es un estándar que define cómo se encuentran estos dispositivos en internet. Es como la dirección de tu casa.

Parece simple (y en realidad lo es), pero este tema se complica un poco debido a que el internet no nos es proveído a nosotros directamente, es decir nuestros computadores no estás **directamente** conectados a internet, sino que se conectan a través de routers/modems (sí, ese que reseteas cada 2 semanas). Los routers crean una especie de sub ~~(sub sub sub sub)~~ internet dentro de nuestra casa, todo dispositivo que se conecte al router posee una IP, pero ésta IP es asignada por el router automáticamente. Esta IP es conocida como la **IP Local** es una IP que solo conocen quienes están conectados al router. Si tu computador necesita hacer una conexión a internet, entonces le pedirá al router que la haga por él. Esta petición tendrá la IP del router, que es la IP visible para todos o tambi;en tu **IP Pública**. Es como si ahora, en vez de vivir en una casa, vives en un condominio y la dirección de tu condominio es la dirección es como la dirección de tu router, que es la dirección que le das a todos tus amigos para que puedan llegar, y después quien está en la puerta del condominio se encarga de redirigir a los invitados hacia tu casa.

Los dominios (com  `github.com`, `google.com` o `uc.cl`) son nombres que se le asignan a las IPs. Estos se guardan en lo que se llama Servidores DNS (Domain Name Servers). Esto sirve para tener uan forma más humana de referirse a las direccioens IP (y más fácil de recordar). En el fondo estos servidores tienen una tabla gigante en que cada nombre está asociado una IP, que es la dirección a la que se refiere ese nombre.

Los puertos, como ya sabrán, son espacios dentro de un mismo dispositivo para que varios sockets puedan convivir simultáneamente. Cuando escriben `direccion.com:9090` se están refiriendo a la IP que corresponde a `direccion.com` en el puerto `9090`. ¿Por qué no hay puerto en mi barra de navegación? Por que por concenso se dice que el protocolo por defecto de `HTTP` es el `80`. Es decir, escribir `google.com` es lo mismo que escribir `google.com:80`. El protocolo por defecto de `HTTPS` que es el protocolo HTTP sobre una conexión segura es el `443`

¿Qué tiene eso que ver con esta tarea? Pues resulta que los webhooks no tiene mas ciencia que decirle a github o a telegram: Cada vez que pase cierto evento envíame un HTTP Post a esta dirección (dirección + puerto, si no hay puerto se usará el puerto por defecto). En esta dirección yo tengo una servidor HTTP que está escuchando en el puerto correspondiente a que le llegue un mensaje tuyo. De esta forma, cada vez que ocurre un evento en telegram o en github, serán notificiados mediante esta forma que el evento ocurrió.

¿Para qué usamos heroku? ¿Por qué no mejor usamos ngrok? Primero, ngrok es una herramienta que permite hacer **tunneling**. ¿Qué es tunneling? Pues (una de las formas de tunneling) es crear un tunel entre una dirección y otra (o lo que comunmente se llama un **proxy**). Si yo hago un tunel que va de X a Y, cada vez que le llegue una request a X, entonces X se la reenviará a Y, por lo que X actuará como un receptor **proxy** que redirigirá todo el tráfico a Y. ¿Qué gracia tiene esto? supongamos que X es una dirección publica de ngrok e Y es su computador local. Como existe una conexión **persistente** entre ngrok y su computador local, todo el tráfico que le llegue a ngrok será redirigido directamente a su computador local sin la necesidad de que este se encuentre expuesto directamente a la cruda internet. Por eso github recomienda usar este método a la hora de testear su aplicación con webhooks de manera local. ¿Por qué usamos heroku entonces? Heroku es un servicio que ofrece hostear sus aplicaciones web de manera remota (es decir, la aplicación no corre en su computador, sino que corre en los computadores de heroku) y les otorga una dirección (y un dominio) público. De esta forma ustedes pueden decirle a github y a telegram que sus webhooks apunten hacia su aplicación que corre en heroku (el dominio que les entrega heroku del estilo `flat-mountains-123.herokuapp.com`). ¿Podemos usar ngrok para testear nuestra aplicación en local? Sí, pero no olviden que su aplicación **debe** encontrarse hosteada en heroku a la hora de la entrega.

El Procfile le dice a heroku como correr tu aplicación. ¿Por qué `0.0.0.0`? Esto es debido a que los computadores también tienen una subnet que solo los contiene a ellos (y quizás a alguna máquina virtual). Esta subnet tiene la dirección `localhost` o `127.0.0.1`. Una aplicación que corre en localhost no puede ser accedida por otro computador, aunque este se encuentre conectado al mismo router. sin embargo si se usa la dirección `0.0.0.0` para levantar un socket, esto se refiere a que se use la IP de ese computador para que la aplicación pueda ser accedida desde otro computador (y de esta forma no corra exclusivamente en localhost). ¿Debo cambiar `$PORT`? No, debido a que esta es una variable que heroku usa para levantar su aplicación.

Por eso para setear el webhook en telegram o git debes usar la dirección entregada por heroku + la ruta en la que se estará escuchando tu aplicación. Es decir, si en heroku ustedes tienen la ruta `hola_git` que será la encargada de procesar todas las requests que les envía Github a través del webhook, ustedes setean el webhook como `https://direccion.herokuapp.com/hola_git`.

#### Bonus `$PORT`
Como se mencionó, existen diversos puertos con el fin de tener varias aplicaciónes simultaneamente. ¿Heroku tiene un servidor por cada aplicación que le suben? Dios, no. Heroku lo que hace es montar todas las aplicaciones que son subidas en distintos puertos y luego configura un servidor proxy cuyo trabajo es redirigir el tráfico hecho a heroku. El servidor principalmente dice (si me llega una request a app1.herokuapp.com) entonces debo redirigir el tráfico a `localhost:1012`, si llega a `app2.herokuapp.com` entonces debo redirigir el tráfico a `localhost:1013`. Por lo que la variable `$PORT` es crucial porque heroku espera que tu app esté corriendo en ese puerto en específico. De lo contrario (probablemente no te de permiso para usar otro peirto) o simplemente, heroku no sabrá dónde se encuentra tu aplicación.

**Comment by negutierrez** [comment]
@MainScientist Para la tarea anterior, si quisiera utilizar el juego en varios computadores, mi server tendria que ser host = '0.0.0.0' y los host de cada cliente mi direccion de ipv4? Ayer trate pero no logre que funcionara desde otro pc.

**Comment by MainScientist** [comment]
Si, deberia ser así. Si es qje no te funciona trata de hacer ping (desde la consola de comandos `ping 192.168.x.x`) para ver que efectivamente los computadores se pueden alcanzar. Alternativamente tambien puedes usar la ip del host en vez de poner `0.0.0.0`.
________________________________

**Comment by B-Dominguez** [comment]
Holaa, he leido mucho pero aun no entiendo lo siguiente: La api del bot de Telegram solo funciona para los PORT: 443, 80, 88 and 8443 
"We currently support the following ports: 443, 80, 88 and 8443. Other ports are not supported and will not work. Make sure your bot is running on one of those supported ports, and that the bot is reachable via its public address."
Como se supone entonces que funcione el listen al bot de Telegram?
@MainScientist

**Comment by acrojas2** [comment]
@MainScientist 
Hola!, creo que ya hice lo del heroku, pero dado a que no entiendo muy bien que está pasando y solo seguí los pasos que indican en el enunciado.  Quiero saber si para que todo funcione debo correr el main.py en pycharm (y tenerlo corriendo para que todo funcione). De no ser así, qué es lo que debo hacer. Saludos!

**Comment by akaminetzkyp** [comment]
Hola! Por lo que he visto, Heroku no tiene problemas con recibir solicitudes en esos puertos. Solo tuve que entregarle mi `url` a Telegram y mi servidor en Heroku empezó a recibir solicitudes correctamente.

**Comment by Hernan4444** [comment]
@B-Dominguez tal como dice @akaminetzkyp, Heroku no debería dar problemas, en lo personal nunca especifiqué un puerto en la tarea (deje que se me otorgara el puerto por default) y todo funcionó como corresponde,

Saludos!!

**Comment by acrojas2** [comment]
Hola! al seter el webhook de github me aparece este error. No tengo idea como arreglarlo!!! ayudaaa!!!!
<img width="774" alt="captura de pantalla 2017-06-26 a las 9 42 19 p m" src="https://user-images.githubusercontent.com/26121354/27567227-966f3eba-5ab8-11e7-8c63-6dc7c3c04697.png">

**Comment by Hernan4444** [comment]
@acrojas2 la forma que estás haciendo post no es la indicada, los argumentos se entregan de otra forma. 
Revisa [aqui](http://docs.python-requests.org/en/master/user/quickstart/) y verás como se hace un post con request.

Saludos
