### ISSUE TITLE
Animacion explosiones

### ISSUE THREAD

**Issue by jpmoraga1** [IIC2233/Syllabus#657]
¿Es necesario que las explosiones sean animadas, o podemos dejar la explosión como una sola imagen?

**Comment by monicabelen** [comment]
Hola! No es necesario que la explosión sea animada, basta con una imagen como la que se muestra en el enunciado.

**Comment by jpmoraga1** [comment]
Gracias por responder (: 
Me surgió otra duda, el tema es que estoy mostrando la imagen de la explosión como 2 imágenes superpuestas y se ve horrible, pero muestra a explosión en los cuadrados válidos (esto lo hago porque no he encontrado alguna forma de mostrar imágenes no rectangulares en pyqt5). ¿Es necesario que modifique la explosión para que se vea bien estéticamente?

**Comment by monicabelen** [comment]
Si se puede apreciar el efecto en los cuadrantes "válidos", es más que suficiente! No te preocupes tanto por la estética en este caso, saludos!
