### ISSUE TITLE
Plazo Recorrección T02

### ISSUE THREAD

**Issue by maogaz** [IIC2233/syllabus#657]
En cuanto al plazo para la recorrección de la T02 en el último mail sale lo siguiente:
![plazot02](https://user-images.githubusercontent.com/26102280/60365836-d1d56980-99b7-11e9-8b11-10a94708b14c.JPG)

Y en el cuestionario sale fecha 27/6:

![Captura](https://user-images.githubusercontent.com/26102280/60365929-17923200-99b8-11e9-99e5-037ce7c88951.JPG)

Cual es la fecha final?

**Comment by Hernan4444** [comment]
Viernes 28, Voy a arreglar el cuestionario 👍 

Saludos ✌️
