### ISSUE TITLE
Eventos y Señales: Diagrama de flujo

### ISSUE THREAD

**Issue by furcelay** [IIC2233/syllabus#657]
Hola,
En los contenidos de la semana 9, en `3-eventos-y-señales.ipynb` no aparece el diagrama de flujo que debería cuando dice *"La siguiente figura muestra una comparación, mediante diagramas de flujo, ..."*. (Al menos a mí no me carga :slightly_frowning_face:)

Supongo que se debe a que en la línea 24 aparece `"![](img/GUI-flowchart.png)\n",`, pero el archivo es `img/gui-flowchart.png`.

Saludos!

**Comment by fdoflorenzano** [comment]
Hola @furcelay,

Gracias por hacerlo notar, se subió una actualización con dos importaciones de imágenes.

Saludos.
