### ISSUE TITLE
Ataque, orientacion jugador

### ISSUE THREAD

**Issue by mesantamaria** [IIC2233/Syllabus#657]
Hola, 
Cuando hay una colisión entre jugador y enemigo y empiezan a atacarse, tienen que estar los 2 mirándose? Me refiero a orientados como si estuviera uno al frente del otro.
Lo digo porque a veces colisiona con más de 1 enemigo al mismo tiempo, entonces no sabría hacia donde orientarlo en el ataque.

**Comment by TomasSalvadores** [comment]
No es necesario que esten frente a frente para quitarse vida, puede ser desde la posición de la colisión. 👍🏻
Salu2!
