### ISSUE TITLE
funcion balance

### ISSUE THREAD

**Issue by StroveLight** [IIC2233/syllabus#658]
¿De la funcion balance se espera que balanceemos todo el arbol o solo el último valor agregado?

¿Es estrictamente necesario implementar esta funcion? (Ya que si se decide balancear en cada inserción del árbol [dentro de la funcion del insert], y se equilibra con cada inserción, esta funcion no afectaría al árbol, además de que, supuestamente, al árbol solo se le pueden agregar los valores con el insert)
[Es decir, ¿Podría hacer que la función tenga literalmente solo un _pass_ adentro, ya que supuestamente el árbol ya estaría balanceado?]

**Comment by Hernan4444** [comment]
Hola

Solo el último valor agregado, puesto que en el enunciado se indica que después de cada inserción es necesario balancear. Ahora respondiendo a tus dudas

> ¿Es estrictamente necesario implementar esta función?

No, podrías hacer que el insert después balancee el nodo agregado, pero a estas alturas del semestre ya se espera que sean capaces de modularizar ciertos métodos y por lo mismo, uno esperaría que hagan insert por un lado y balance por otro.

> ¿Podría hacer que la función tenga literalmente solo un pass adentro, ya que supuestamente el árbol ya estaría balanceado?

Si puedes y no tendrá ningún descuento asociado. Pero te invitó a aprovechar esta última evaluación (sin contar la actividad recuperativa) para intentar modelar lo mejor posible esta tarea, de este modo se forma el hábito de programar siguiendo buenas prácticas de modularización y en otros cursos te será más natural ir segmentando acciones de modo que facilita su programación 😃 .

Saludos ✌️

**Comment by StroveLight** [comment]
ありがとうございました、エルナン先輩、それをします。

**Comment by Hernan4444** [comment]
どういたしまして (¡De nada!) 😄 

Por si acaso, como mi nombre es Hernán (con tilde en la a), se escribe エルナーン para hacer un énfasis en la a n.n (o eso me enseñó un amigo japones jejej )

Saludos ✌️
