### ISSUE TITLE
Ayuda con el ejercicio propuesto 2.2

### ISSUE THREAD

**Issue by diego-ayala-2000** [IIC2233/syllabus#658]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

Hola.
Llevo mucho rato trabajando en el ejercicio propuesto 2.2 y no logro hacerlo solo poniendo código en la linea superior de la función, me podrían dar una ayudita porfa.

**Comment by aaossa** [comment]
Hola @diego-ayala-2000 , creo que te estás limitando innecesariamente. Lo que los comentarios indican es que puedes agregar código dentro de la función `jugar_nivel`, no solo al comienzo. Además, puedes agregar código después de la instanciación de los *threads* (incluso justo antes de `n1.start()`). Como *spoiler*/guía, con usar los métodos `set`, `wait` y `clear` de `Event`, deberías poder completar el ejercicio, así que ¡mucho éxito ✨💪!

**Comment by diego-ayala-2000** [comment]
Ah gracias, es que como en el enunciado dice "solo puedes agregar código dentro de la sección superior de la función jugar_nivel". Seguro que el ejercicio no va orientado a solo poner código en la parte superior de la función y después del comentario?

**Comment by aaossa** [comment]
Ah sí, toda la razón 😱 Es entre la declaración de la función y la línea `print(f"¡Jugando nivel {nivel}!")`. Pero lo importante es que también puedes hacerlo después del comentario (`# =========== SOLO AGREGAR CÓDIGO DESDE AQUÍ HACIA ABAJO =============`) 👌

**Comment by diego-ayala-2000** [comment]
Si por eso, llevo mucho rato tratando de hacerlo y no he podido, por si me podrías dar aun tip o ayudita.

Gracias

**Comment by aaossa** [comment]
Creo que una buena recomendación es que pienses que el *thread* principal también es un *thread*, y que con esto te hagas una especie de línea de tiempo como la del material, donde puedas ver cuándo ocurre qué cosa, y cuando necesitas esperar por el evento para activarse. Por ejemplo, antes de iniciar cualquier nivel del juego necesitas que el evento esté activado (con esto ya puedes identificar lugares para hacer `set()`), luego en algún momento necesitas esperar a que se termine el nivel anterior (`wait()`). Después de esto tienes otro problema, en algún momento tienes que "limpiar" la señal (`clear()`), y aquí te será útil la línea de tiempo que te decía al inicio. 

Lo que necesitas es (debería tomar aprox. 16 segundos, 4 por nivel):
```
¡Jugando nivel 1!
Batallando en el nivel 1
Terminando el nivel 1
¡Jugando nivel 2!
Batallando en el nivel 2
Terminando el nivel 2
¡Jugando nivel 3!
Batallando en el nivel 3
Terminando el nivel 3
¡Jugando nivel 4!
Batallando en el nivel 4
Terminando el nivel 4
```

Lo que tienes sin hacer cambios es (puede variar, pero la idea es que se note que todo ocurre al mismo tiempo, tomando 4 segundos ya que todos los niveles ocurren a la vez):
```
¡Jugando nivel 1!
¡Jugando nivel 2!
¡Jugando nivel 3!
¡Jugando nivel 4!
Batallando en el nivel 4Batallando en el nivel 2
Batallando en el nivel 3Batallando en el nivel 1


Terminando el nivel 3Terminando el nivel 2
Terminando el nivel 4
Terminando el nivel 1

```

De todas maneras, te dejo esta *issue* (https://github.com/IIC2233/syllabus-2019-2/issues/327) del 2019-2 donde justo alguien preguntó por este ejercicio y le respondieron con unos *spoilers* que puedes ver haciendo clic en las flechitas negras. Espero te sirva, pero de todas maneras puedes volver a preguntar acá si algo no queda claro 🙌
