### ISSUE TITLE
Entregable T05

### ISSUE THREAD

**Issue by FernandoPieressa** [IIC2233/Syllabus#658]
A continuación se muestra una serie de comentarios que surgieron tras leer los diagramas de clase que entregaron:

1) Recuerden que la idea de la tarea es una QThreads / QTimers, y por lo tanto, está hecha para usarlos más de una vez. Hay varias cosas que están pensadas para que sean alguno de estas clases, o al menos hereden de ellas. Piensen bien en cual usar para cada caso, en algunas ocasiones uno es la solución perfecta.
2) Usen señales para interactuar entre objetos, o su programa funcionará más lento o tendrá tendencia a caerse. Recuerden que puede conectar varios slots (funciones) a una señal.
3) En el modelamiento de muchos se pueden ver que, los métodos de su ventana principal y del jugador con los enemigos están pensados para que el jugador actualice su imagen, al igual que los enemigos. Más concretamente, la ausencia de métodos del estilo update_enemy_label, indica que no están pensando correctamente la comunicación entre el jugador, los enemigos y la ventana principal. Les recomendamos revisar nuevamente el material de señales, ya que la comunicación se realiza mediante el uso de estas.
5) Hacer métodos de una clase que llamen a métodos de su padre no está bien modelado ya que permite que cada elemento en la GUI pueda llamar a todos las instancias y funciones de ésta.
6) Recuerden que los enemigos también deben moverse mediante señales, que tengan los atributos correctos y movimientos aleatorios, si los ejecutan sin señales se mostrará como una teletransportación sin control y es probable que la tarea se caiga.
7) Si van a sacar fotos de sus entregables usen lápiz pasta :C </3 No se ve con mina
8) Cuidado con atributos no descriptivos. 
9) Puede que el juego en esencia sea un tablero, pero deben echarle una mirada de nuevo al enunciado, ya que los enemigos y el jugador principal deben tener movimiento continuo, piensen en la jugabilidad de su tarea.
10) La mejor manera de modelar un enemigo quizás no requiere un atributo para ver su estado (recuerden threads)
11) Recuerden que si a un widget en su init le pasan el parent, el widget va a vivir dentro del parent. Entonces si tienen sus personajes que van a vivir solo dentro de su tablero, sería bueno entregarles como parent el tablero y no la ventana principal. Esto les va ahorrar tener que calcular posiciones relativas a toda la ventana y solo tener que preocuparse por la posición dentro del tablero.
12) Intenten tener clara la división entre backend y frontend, puede que suceda que en cierto punto programen cosas en el frontend que no deberían estar ahí. Intenten que todo lo que son cálculos hacerlos en el backend y sólo usar el frontend para mostrar estos cambios.
13) Piensen en el backend como el cerebro de su programa. Además, piensen bien qué tipo de objeto de pyqt es el más útil para crear a los personajes. 

Saludos y éxito en la tarea ✌️

**Comment by jmwielandt** [comment]
Duda con el punto 1:
Eso implica que si uso threads normales en lugar de QThreads está mal? La documentación de Qt es tan mala que quiero evitar usar demasiadas cosas que no sé al final cómo funcionan :/
Ya estoy usando bastantes QTimers (y me costó entender cómo usarlos)...
Además, creo que no puedo hacer un objeto que herede de dos QObjects a la ves, pero sí de Thread y un QObject :D

Duda con el punto 3:
Te refieres al front_jugador o al back_jugador?
Yo hago que el frontend actualice su imagen pero tampoco tengo esos métodos :/

Duda con el punto 7:
Mi creatividad para los nombres es limitada, tienen algún generador de nombres o algo así? He pensado empezar a nombrar ```var1```, ```var2```, ```var3```, ```f1```... etc.

Aparte:
En mi entregable pedí feedback específico de lo que estaba haciendo... eso no va a ocurrir?

PD: Acabo de darme cuenta de que ya habían subido el feedback
