### ISSUE TITLE
AF7: problemas con el botón enviar de la interfaz

### ISSUE THREAD

**Issue by Pabloski100** [IIC2233/syllabus#658]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Pareciera que el botón enviar de mi código no hace nada

Hola, tengo (aparentemente) todas las funciones implementadas, tanto de server como de cliente, sin embargo, en la interfaz de inicio cuando coloco un nombre el botón enviar no hace nada ¿Por que podría pasar eso?

`REDACTED`

**Comment by aaossa** [comment]
¡Hola @Pabloski100 ! Primero que todo, no comentes detalles de tu solución. Esta es una evaluación del curso 😅 Sobre tu problema específico, ¿podrías probar con un usuario que esté en la lista de usuarios (creo que el archivo era `usuarios.json`). Podría arrepentirme de esto (?) pero prueba con el mio por ejemplo: "aaossa"

**Comment by Pabloski100** [comment]
Perdón! Creí que por ser algo extra que agregue no importaba, probare poner un usuario del json

**Comment by Pabloski100** [comment]
No, sigue sin hacer nada, me extraña mucho que no de ni un error como para indicar que algo esta mal

**Comment by aaossa** [comment]
Quizás lo que hiciste está bien en el lado del cliente (ojo se supone que el evento debería pasar por el método `enviar` de `Cliente`, podrías chequear eso), pero podría no estar siendo bien manejado por el servidor. Te recomiendo agregar un par de `print` en ambos lados, para asegurarte de que el mensaje sale y vuelve en ambos lugares (cliente y servidor)

**Comment by B-Birb** [comment]
Hola! Tengo el mismo problema. Revisando el archivo de interfaz.py, observé que hay la señal `enviar_nombre_usuario_signal` se envía a la función enviar del parent, es decir, del Cliente. Luego, la ventana principal se abre cuando se emite la señal `mostrar_ventana_principal_signal`, que se emite gracias a la función manejar_mensaje. Sin embargo, en el enunciado no dice que debamos aplicar la función de `manejar_mensaje` en  la función ` enviar`. Quizá estoy leyendo mal el archivo de interfaces, pero tengo el mismo problema.

**Comment by aaossa** [comment]
> 
> 
> Hola! Tengo el mismo problema. Revisando el archivo de interfaz.py, observé que hay la señal `enviar_nombre_usuario_signal` se envía a la función enviar del parent, es decir, del Cliente. Luego, la ventana principal se abre cuando se emite la señal `mostrar_ventana_principal_signal`, que se emite gracias a la función manejar_mensaje. Sin embargo, en el enunciado no dice que debamos aplicar la función de `manejar_mensaje` en la función ` enviar`. Quizá estoy leyendo mal el archivo de interfaces, pero tengo el mismo problema.

La función `manejar_mensaje` tienen que ocuparla en `escuchar_servidor`, si es que se recibe un mensaje del servidor. Lo que ocurre es que al presionar el botón enviar, se envía al servidor el nombre (parte de esto ocurre en `ventana_inicio.py`, en el método `enviar_nombre_usuario`) y el servidor indica si está todo OK o no, y según esa respuesta se pasa a la siguiente ventana.
