### ISSUE TITLE
Botón de salida - fin juego

### ISSUE THREAD

**Issue by B-Dominguez** [IIC2233/Syllabus#658]
_Botón de salida: al presionar este botón se reingresa al menú principal con un mensaje del puntaje obtenido hasta ese punto_

En este momento asumo que se le pregunta el nombre al jugador y la partida se da por terminada y que en el menú principal tiene las opciones de comenzar nueva partida o ver ranking puntajes. (De otro modo, sería simplemente una pausa).

Hago la issue solo para asegurarme que esto está bien, graciaas!

**Comment by Arcoirisky** [comment]
Está bien :D El botón de salida debe sacarte del juego <3
