### ISSUE TITLE
Error Invalid Tree y balance

### ISSUE THREAD

**Issue by dmelberg** [IIC2233/syllabus#659]
Hola, 
En el enunciado, cuando hay que levantar el error `Invalid Tree` dice que revisemos si cumple todas las reglas de AlgarroboTree, pero yo en mi funcion `search`, tras revisar si el path es valido, convierto el json a formato clases `Node` y `AlgarroboTree` (si es que el arbol entregado cumple con las caracteristicas estructurales de algarrobo tree) y lo hago haciendo `insert`. 
Mi problema: cada vez que hago `insert` se hacen los _swap_ correspondientes entonces nunca haria _raise_ de `InvalidTree` si los valores estan mal (cosa que iria en contra de las "reglas") pero la estructura esta bien, ya que el programa solucionaria esto haciendo _swap_.
Mi pregunta:  puedo hacer _raise_ de `InvalidTree` sin tener en cuenta los valores?

**Comment by Hernan4444** [comment]
Hola, no puedes, Se debe respetar al 100% el enunciado.

Saludos ✌️
