### ISSUE TITLE
Capacidad máxima de un puerto.

### ISSUE THREAD

**Issue by 0DASAC** [IIC2233/syllabus#659]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

hola, durante la materia de servidores me surgió la duda de si existe una capacidad máxima de datos que puede recibir un mismo puerto, lo que nos podría dar problemas al crear un server que tenga muchos usuarios simultáneos.

**Comment by Pablok98** [comment]
¡Hola @0DASAC!

Nop, no tiene una capacidad máxima. En términos de conexiones, un `socket` de Python no tiene límite de conexiones concurrentes, por lo que tu servidor puede tener infinitos clientes. Por otro lado, en términos de datos o flujo de información, depende de tu sistema operativo y el _hardware_ de tu computador.

Para temas del curso, no es algo de lo que te tengas que preocupar 😉

**Comment by Christian-Klempau** [comment]
Para complementar la respuesta, en teoría sí hay límites de sockets y puertos, pero son tan grandes que vas a tener otras limitaciones, antes de llegar a la limitación de conexiones: RAM o memoria utilizada sólo para mantenerlos va a ser gigante, y el acceso a disco va a colapsar, dada tantas conexiones, además de necesitar un ancho de banda casi imposible. El default de Linux por ejemplo, es de **2^16 ~ 65000** puertos, donde cada uno maneje la misma cantidad de conexiones únicas, para TCP.

 Ahora, hay trucos para aumentar esa limitación, pero en la práctica nunca lo vas a tener que hacer, ya que supongamos, que tienes todas las conexiones ocupadas, tendrías 65000^2 conexiones únicas, que equivale a **4 billones** ! (es decir, si cada conexión usa sólo 1kB de memoria, gastarías **4.4 TB** de memoria **sólo para mantenerlas vivas**. Aún así, hay servidores modernos que utilizan paralelismo junto a asincronía, para manejar millones de conexiones a la vez, en un sólo computador.

De igual manera, para servidores reales se prefiere distribuir la carga, ya que así no necesitas tanta memoria y almacenamiento en cada computador, además de hacer tu red más robusta, en caso que un servidor se caiga (ya que si todo está repartido, una caída afecta a menos usuarios).
