### ISSUE TITLE
Problemas al utilizar el módulo threading en VS al arrojarme un AttributeError

### ISSUE THREAD

**Issue by domingaward** [IIC2233/syllabus#659]
* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Al correr el código del primer ejemplo que se muestra en el primer archivo de los contenidos de la semana 8 acerca de los threading dentro de Visual Studio, específicamente el ejemplo de contar ovejas, me aparece el siguiente error (aún cuando hago copy paste del código):
**AttributeError: module 'threading' has no attribute 'Thread'**

Sin embargo, este no es problema cuando pongo *run and debug*
¿Qué debo hacer para que no me aparezca ese error?

**Comment by aaossa** [comment]
Hola @domingaward , creo que ese error ocurre si el archivo que estás ejecutando se llama `threading.py` 😅. Si es así, cambialo y prueba de nuevo, ya que Python se "confunde" y no puede acceder a la librería estándar por el tope entre nombres 🐍 . ¿Podrías confirmarme si es eso? Éxito ✨

**Comment by domingaward** [comment]
> Hola @domingaward , creo que ese error ocurre si el archivo que estás ejecutando se llama `threading.py` 😅. Si es así, cambialo y prueba de nuevo, ya que Python se "confunde" y no puede acceder a la librería estándar por el tope entre nombres 🐍 . ¿Podrías confirmarme si es eso? Éxito ✨

Sii perfecto! era eso mismo, muchas gracias!!. La cosa es que al tener ese archivo con ese nombre 🤦‍♀️ también el resto de los otros archivos dentro de la misma carpeta fallaban.
