### ISSUE TITLE
Ejercicio 2.2: Elementos básico en inicio de sesión

### ISSUE THREAD

**Issue by jmg-git** [IIC2233/syllabus#659]
Hola estaba haciendo este ejercicio y funciono todo excepto cargar la imagen. El código es este:
Que es lo que esta mal?
Python tira el error: argument 1 has unexpected type 'QPixmap'
*en ruta puse la ruta respectiva
# Agregar imagen:
        ruta_imagen = os.path.join('ruta', 'buyer-personas.jpg')
        # Cargamos la imagen como pixeles 
        pixeles = QPixmap(ruta_imagen)
        # Creamos el Label con la imagen.
        imagen = QLabel(pixeles)
        #imagen.setScaledContents(True)
        # Crea contenedor vertical para colocar los campos
        contenedor = QVBoxLayout()

        #Agregamos cada Layout horizontal creado, verticalmente.
        contenedor.addWidget(imagen)
        contenedor.addLayout(CampoRS("Usuario"))
        contenedor.addLayout(CampoRS("Correo"))
        contenedor.addLayout(CampoRS("Contraseña"))
        contenedor.addWidget(self.boton)
        self.setLayout(contenedor)

**Comment by igbasly** [comment]
Hola @jmg-git :smile:

Lo que pasa aquí, es que efectivamente Python no reconoce el *QPixmap* que le estás entregando al *QLabel* `imagen`, ya que los *QLabel* esperan como argumento un *string* o un *QWidget* padre.

Si bien, está correcta la definición del *QPixmap* en la variable `pixeles`, para asignar esta imagen a un label y poder mostrarla, se utiliza el método `setPixmap` de los *QLabel*.
Dicho esto, debes definir tu *QPixmap* como está hecho y definir el *QLabel* como un label vacío, es decir `QLabel("")` o `QLabel(widget)`, dependiendo el caso con el que estés trabajando, donde `widget` sería el widget padre del label (esto es opcional).
Una vez definidos los elementos, digamos que definiste el label en la variable `imagen` y el pixmap en `pixeles`, basta asignar el pixmap mediante el método `imagen.setPixmap(pixeles)`.

Espero que esto haya aclarado el problema, no dudes en escribirnos 😉 
Saludos.
