### ISSUE TITLE
Error al convertir .ui a .py

### ISSUE THREAD

**Issue by savelozo** [IIC2233/Syllabus#659]
![image](https://user-images.githubusercontent.com/8712664/32242333-3f490948-be51-11e7-820d-30d3b8932b87.png)

He estado toda la mañana intentando solucionar este problema y aún no lo logro abrir mi archivo.ui :( Dice que no existe el modulo 'resource_rc', pero ahí está (y en la misma carpeta, tanto el archivo .qrc, como el .py). Qué puedo hacer D:?

(Leí una issue de la tarea 3, pero no me ayudó; además googlé todo lo posible y también fallé. AYUDA!)

**Comment by sebacruzd** [comment]
Hola, en la documentación oficial de PyQt5 se menciona otra manera que podría ser más útil.
Con pyuic5 puedes transformar los archivos .ui a código .py y eso queda en un archivo.

Busca en google y encontrarás ejemplos de cómo usar pyuic. Ojalá te sirva.

Suerte!

**Comment by naazocar** [comment]
resource_rc es lo que usas en QtDesigner para importar imágenes? A mí me pasó lo mismo por hacer eso, si es ese el caso te recomiendo no hacerlo así, si no que importar directamente las imágenes desde una carpeta. Así me funcionó a mí al menos, ojalá te ayude.

**Comment by iqacevedo** [comment]
@naazocar es una buena manera hacerlo así, debes tener ojo con que la ruta a las imágenes sea relativa a la carpeta en la que estés programando. Si Qt te definió una ruta absoluta no podrá verse en otro computador que no sea el tuyo, puedes verificar cambiando tu programa a otra ruta (sin mover las imágenes con el) y si aún corre significa que son rutas absolutas (también puedes probarlo en otro pc).

Saludos !

**Comment by savelozo** [comment]
@naazocar Hola! Sí, ese el mi problema :( me podrías explicar un poco más sobre la manera de importar directamente las imágenes? te refieres a agregarlo directamente en mi código en python o a hay alguna manera de importar las imágenes directamente al Qt Designer?

Ojalá puedas ayudarme, gracias!

**Comment by vijuarez** [comment]
Hola, me quedan un par de dudas con tu problema:

1. De donde sacaste `resource_rc.py`? Lo creo QtDesigner?

1. Probaste poniendo `resource_rc.py` en la misma carpeta que `Main.py`?

Hasta donde tengo entendido, conseguir ese `resource_rc.py` desde el `resource_rc.qrc` ya es una mala experiencia. Así que si ya lograste obtenerlo la parte mala debería haber terminado.

Nos cuentas, saludos!

**Comment by savelozo** [comment]
@vijuarez jajaj es verdad, mi resource_rc.py ya fue mi dolor de cabeza pasado y creé el archivo convirtiendo el .qrc con el pyrcc.

Y sí, de hecho, el main.py está en la misma carpeta del resource_tc.py

Voy a seguir viendo como lo soluciono u.u

**Comment by vijuarez** [comment]
Y que pasa si lo intentas importar directamente? Algo así como un `import resource_rc` al principio del archivo. Te da el mismo error?

He estado tratando de recrear tu problema y no llego a nada 😫

Saludos, nos cuentas!

**Comment by savelozo** [comment]
@vijuarez parece que tenías razón en tu primer comentario, simplemente no estaban en la misma carpeta. Que gil, estuve horas cabezeándome u.u

Muchas gracias por el tiempo, de verdad!

**Comment by vijuarez** [comment]
Me alegro que se solucionara! 

Sigue fuerte con la tarea, saludos!
