### ISSUE TITLE
interacciones y señales

### ISSUE THREAD

**Issue by ciquezada** [IIC2233/Syllabus#659]
Hola!  por lo que entendí la interacción entre objetos se debe hacer a través de señales, mi pregunta es que si quiero que después de enviar la señal desde un objeto1 a un objeto2 haya un retorno como "respuesta" por parte del objeto2,  ¿seria valido que el objeto1 emita una señal con un evento que contenga la señal de retorno (así el objeto2 manejaría la información del evento que recibió para luego mandar una respuesta al objeto1 con la señal que venia contenida en el evento)?
**esto es pensando en evitar entregar la función del objeto2 al objeto1 porque me parece que hacer estaría malo ¿o me equivoco?**

una segunda pregunta menos importantes es que me parece que si la cabeza del personaje se superpone un poco (solo un poco) a las murallas que pueda tener arriba le da un bonito toque "3d", ¿es muy estricto que las colisiones sea al mas mínimo pixel o puede ser hasta sierto punto razonable (jugable)?

Gracias, saludos!

**Comment by Arcoirisky** [comment]
Hola c: 
Para tu segunda pregunta, no te preocupes por eso :D Mientras se entienda que no está chocando está perfecto xD Puede ser hasta cierto punto razonable :DD

Y sobre tu primera pregunta. Se supone que el objeto1 manda una señal al objeto2 y este es quien hace el cambio del objeto1. Lo que dices en negrita es cierto O: estaría malo porque estarías haciendo el llamado de forma circular. En cambio, si el objeto1 avisa que debe hacerse un cambio y objeto2 lo hace, está bien y se debería mostrar en la interfaz :D 

Espero que se entienda un poco más la idea de las señales o:!
