### ISSUE TITLE
Entrega nota tarea 5

### ISSUE THREAD

**Issue by fantineen** [IIC2233/Syllabus#659]
Hola quería saber cuándo iban publicar las notas de la tarea 5 para que así podamos analizar mejor la opción de hacer la tarea recuperativa. 
De ante mano gracias :)

**Comment by flobarrios** [comment]
Hola!! las notas estarán mañana en la tarde/noche. 
Saludos!!

**Comment by Okhan97** [comment]
soon ...

**Comment by Okhan97** [comment]
Decian :,c

**Comment by frvalenzuela** [comment]
);

**Comment by negutierrez** [comment]
Cuando van a subir el feedback?

**Comment by fdominguezclaro** [comment]
Me sumo a la pregunta de @negutierrez
