### ISSUE TITLE
Unidades evento metereológico: viento

### ISSUE THREAD

**Issue by malopez16** [IIC2233/Syllabus#66]
Hola!

En el punto 4.1.3 se define que el viento está en m/s en el archivo CSV, pero luego al calcular la incidencia en la propagación se utilizan km/h. 
Solo para confirmar que no es un error:
Esto implica que casualmente hay viento de más de 100 km/h (o más) en algunos lugares? (haciendo transformacion de unidades) o se referían a el valor en km/h en el csv ?
Gracias :)

**Comment by eiherrera** [comment]
Si, el viento esta en m/s.
Saludos!
