### ISSUE TITLE
Considerar mayúsculas al registrar usuarios

### ISSUE THREAD

**Issue by Ignacioislae** [IIC2233/syllabus#66]
Hola,
tenia la siguiente duda:
¿Al registrar usuarios considero las mayúsculas como un carácter diferente?
Por ejemplo si quiero registrar a un usuario llamado Alfonso8, y hay uno llamado alfonso8 ya registrado. ¿El programa lo debe tomar como error o registrar al usuario?

Saludos!

**Comment by jeschuwirth** [comment]
Hola @Ignacioislae,

Las mayúsculas son caracteres diferentes, por lo tanto los usuarios: ignacio e IGnaciO son distintos.

Suerte!

**Comment by Ignacioislae** [comment]
Dalee gracias!
