### ISSUE TITLE
Orden Ids y fechas de creacion

### ISSUE THREAD

**Issue by augustoas** [IIC2233/Syllabus#66]
Hola ! Una vez corriendo el programa, los nuevos order_id deberian quedar con el mismo orden de las fechas asociadas a esas ordenes?  Si es asi, entonces por que el metodo que genera y puebla las ordenes iniciales no cumple con esa correspondencia de orden entre ids y fechas de creacion? Gracias !

**Comment by iqacevedo** [comment]
Estimado,

Lo único realmente relevante es que los ids sean únicos, pero como tú dices queda más ordenado de esa manera por lo que te conviene hacerlo así. Ya subimos el script corrigiendo esto, ahora deberían estar ordenadas por fecha! 

Saludos !
