### ISSUE TITLE
Problema con el tutorial de VSCode (Linter)

### ISSUE THREAD

**Issue by ExRage2000** [IIC2233/syllabus#66]
Hola, tengo un problema con la parte 4 (ejecutar código) del tutorial de Visual Studio Code.
En el minuto 10:11 se hace un mal código para que el "Linter" lo señale, pero cuando yo hago el mismo código no me señala nada, a pesar de que hasta ese punto he seguido todos los pasos.

**Comment by aaossa** [comment]
Hola @ExRage2000 , cómo te ha ido con esto? Pudiste solucionarlo? 🤔

**Comment by ExRage2000** [comment]
No, no pude, sigo con la aplicación instalada pero como me quedé estancado terminé descargando sublime text 3 por ahora

**Comment by gatochico** [comment]
Hola! 
Si haces `Ctrl+Shift+P` y luego seleccionas la opción `Python: Run Linting`, funciona el Linter?

Quedo atenta !
