### ISSUE TITLE
Duda con cuantas columnas se pueden poner al tablero

### ISSUE THREAD

**Issue by jasilva-11** [IIC2233/syllabus#66]
La función print_tablero() de tablero.py printea las columnas con letras del alfabeto (ABC...).

El problema es que si se construye un tablero de más de ~26 columnas no quedan letras del alfabeto suficientes para printear.

Es necesario para mi programa prohibir un tablero con mas columnas, o puedo ponerlo simplemente en el REAMDE? (del estilo "no usar tableros de mas de 26 columnas")

**Comment by KnowYourselves** [comment]
Hola @jasilva-11!

Es por esto mismo que en la sección de guardar partida se especifica que las dimensiones del tablero (`N` y `M`) pertenecen al intervalo `[3, 15]`. Cabe recalcar que tu programa **no debe permitir que se creen tableros que no cumplan dicho intervalo**.

Espero haberte ayudado!

**Comment by jasilva-11** [comment]
Ok, muchas gracias!
