### ISSUE TITLE
Batalla es la invasion? Cuantos turnos? Atacan ambos?

### ISSUE THREAD

**Issue by naquiroz** [IIC2233/Syllabus#66]
Hola hay algo que no me queda claro a partir del enunciado. ¿ La sección de batalla, detalla lo que ocurre al momento de que un planeta invade a otro?. De ser así, cuantos turnos dura una batalla, solo 2 (uno por cada planeta: invadido y invasor), o mas de 2 (hasta que alguno se quede sin soldados/magos)?

**Comment by IchottMano** [comment]
@naquiroz Hola!
Las batallas entre ejércitos transcurren hasta que el atacante o el atacado se quede sin soldados, es decir que su vida sea menor o igual a cero.
Saludos!
