### ISSUE TITLE
Duda sobre formato archivos

### ISSUE THREAD

**Issue by ignaverb** [IIC2233/Syllabus#66]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/21)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/20)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola!
Tenía una duda con respecto al input del usuario, en el enunciado se dice que debe ser un archivo válido, podemos considerar esto como un nombre de archivo que viene con el ".txt" o sin este? Además, consideramos los archivos validos solamente a aquellos que se encuentran en la carpeta Archivos?

Saludos y gracias!!!

**Comment by joaquindm02** [comment]
Hola @ignaverb !

Para que el archivo sea válido, este debe estar guardado en la carpeta archivos, y debe tener el formato .txt.

Saludos

**Comment by ignaverb** [comment]
Entonces, todo input valido cumple eso? Ej. 7x7.txt no sería valido porque no está en la carpeta archivos? o 3x3 no sería válido por que no tiene el .txt?

**Comment by joaquindm02** [comment]
@ignaverb tu código, a la hora de buscar un archivo, buscará dentro de la carpeta archivos, por lo que si hay uno que se encuentra fuera de la carpeta, no se podrá encontrar, por lo que más que inválido, un archivo fuera de la carpeta archivos no te sirve mucho. Y dentro de la carpeta archivos, buscará aquellos con .txt, por lo que si un archivo no posee .txt, tampoco se podrá encontrar. Cualquier duda con eso, no dudes en avisarme.

Saludos

**Comment by joaquindm02** [comment]
@ignaverb Aaa pensé que solo me estabas hablando de los archivos! Cuando el usuario pone el nombre del archivo en el input, no es necesario que este tenga .txt, ya que tu se lo puedes agregar a la hora de buscarlo. Si pone en el input 3x3, tu buscas el archivo 3x3.txt de la carpeta archivos. Perdón por la confusión.

**Comment by ktherine0** [comment]
Hola! En otra issue se mencionó que "En el menú de inicio se debe ingresar el nombre del archivo con su extensión." y acá respondieron lo contrario. 
Un input del usuario correcto es "2x2" o  "2x2.txt", respecto a poder agregar la extensión al buscarlo, si lo correcto es la opción 2 agregar la extensión no encontrará nada. O son los dos correctos y debo identificar cuando agregarle la extensión?
Gracias.

**Comment by ignaverb** [comment]
@joaquindm02 Ok, gracias! Entonces creo que es mejor dejar ambas opciones, que sea válido tanto con .txt como sin el mismo (y después yo lo agrego)
