### ISSUE TITLE
Máximo de HP, IQ y fuerza de los soldados

### ISSUE THREAD

**Issue by fjhuanca** [IIC2233/syllabus#66]
Hola! Mi pregunta va enfocada al punto **4.2** del enunciado, cuando se van alcanzando las metas gracias a los puntos tecnológicos y se aumenta la fuerza de los soldados e IQ de los ayudantes, ¿se debe respetar el máximo dado en el archivo constantes? ¿o este es solo para la generación de las personas?

También al alcanzar la meta de medicina, cuando dice *"A los que ya estaban heridos se les aplicará la bonificación considerando su HP actual."* ¿se refiere a que el HP de las personas aumenta a un 150%?

**Comment by BFFV** [comment]
Hola!
1) El máximo y mínimo son sólo para la generación de personas, por lo que no se consideran al momento de aplicar la bonificación.
2) Se refiere a que se aplica la bonificación que aumenta el HP en un 50% sobre el HP actual de la persona, sin importar si su HP máximo era mucho mayor (queda con el 150% del HP actual).

**Comment by fjhuanca** [comment]
Ok el punto 1 me queda claro, pero ahora me surge otra duda respecto al cumplir la meta de medicina cuando dice *"Los avances en la medicina aumentan en un 50% el HP máximo de todos los trabajadores, soldados y ayudantes, tanto actuales como futuros."* ¿con HP máximo se refiere al máximo al momento de creación de la persona? ¿o al HP íntegro, es decir, sin haberse dañado esa persona?

**Comment by BFFV** [comment]
Se refiere al íntegro (sin haberse dañado). En esa parte del enunciado, cuando se habla de HP máximo se refiere al que tenía una vez ya creado, NO a la cota superior al momento de determinar el HP aleatoriamente. Además, con HP actual, me refería al HP que tiene incluyendo daños, no al íntegro (por si te quedó la duda con el punto 2).

**Comment by fjhuanca** [comment]
Aaaah perfecto, ahora me queda todo claro. Muchas gracias!

**Comment by isihirmas** [comment]
Pero la fuerza de los soldados aumenta la suma total o la de cada individuo en un 50%?

**Comment by BFFV** [comment]
Aumenta la suma total de la fuerza de los soldados, sin contar la bonificación específica de cada civilización.
