### ISSUE TITLE
Case sensitivity en nombres de usuarios

### ISSUE THREAD

**Issue by BirdHusband** [IIC2233/syllabus#66]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Al momento de registrar un usuario, ¿se debería o no distinguir entre mayúsculas y minúsculas? Por ejemplo, registrarse bajo 'BirdHusband' y 'birdhusband' debería permitirse o se debería indicar que el nombre ya existe?

**Comment by IgnaciaJ** [comment]
Hola Miguel, se puede asumir que el programa distingue entre mayúsculas y minúsculas, por lo tanto tu ejemplo debería permitir.
