### ISSUE TITLE
Link PEP8 del pdf entregado de la Tarea

### ISSUE THREAD

**Issue by ferperezh** [IIC2233/Syllabus#66]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]
Hola mi duda es que en el pdf de la tarea el link de guía que explica la parte de las reglas de PEP8 aparece un error y no se cuales son las normas que debo seguir.

**Comment by nanglada** [comment]
La idea es que, para indentar (no identificar jajaj), apretes la barra de espacio 4 veces en vez de utilizar la tecla "tab". De esta forma, la "sangría" en el código se ve igual sin importar el tamaño de la pantalla. 
Igual, esto se puede automatizar (cómo hacerlo depende del editor que estés usando). En la guía de estilos de los contenidos se menciona con más detalle.
Ojalá te haya quedado más claro!
Suerte
