### ISSUE TITLE
Mostrar tablero luego de perder

### ISSUE THREAD

**Issue by mvveram** [IIC2233/Syllabus#66]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Cuando se pierde se debe mostrar el tablero con los número que se encontraron más la posición de la bestia o solo las posiciones de las bestias o las posiciones de las bestias más todos los números.

Muchas gracias de antemano

**Comment by Emiliax16** [comment]
Hola @mvveram ! al momento de perder, se debe mostrar todas las casillas que ya habías encontrado previamente junto con **todas las casillas que contenían las bestias** . Por lo que sólo deben verse los números descubiertos y las N-bestias. Esto puedes verlo en el segundo párrafo de la sección 4 _Reglas_ del enunciado. Saludos 😺
