### ISSUE TITLE
Rango de visión

### ISSUE THREAD

**Issue by BibarelUsedFly** [IIC2233/Syllabus#660]
En el enunciado dice que el rango de visión es: _tamaño enemigo * 30_
pero esto se refiere a:
tamaño_enemigo_en_pixeles * 30 ? En este caso el rango es muy grande
valor_tamaño_enemigo (Entre 1 y 10) * 30 ? En este caso muy chico
El número resultante es en pixeles? o puedo dejarlo en unidades arbitrarias de modo que mi juego haga sentido?

Gracias de Antemano

**Comment by sebacruzd** [comment]
Hola,
Puedes hacerlo de la manera que dices.

Saludos!
