### ISSUE TITLE
Problema al subir la tarea

### ISSUE THREAD

**Issue by NicolasCourt** [IIC2233/Syllabus#660]
Estoy desde las 21:00 subiendo la tarea, como la velocidad de mi internet es tan lenta no alcanzara a ser subida a tiempo. Seria posible que den un par de horas extra?

**Comment by cilopez** [comment]
Tenias que subirla sin las canciones :/

**Comment by NicolasCourt** [comment]
ohh diantres, yaya lo acabo de hacer :( tengan piedad de mi
