### ISSUE TITLE
AF7:Error al implementar mecanismo en aceptar_cliente

### ISSUE THREAD

**Issue by Vabu77** [IIC2233/syllabus#660]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Duda en mecanismo de aceptar_cliente de la clase Cliente

[Hola! Al ejecutar en la consola el main.py de servidor y luego el main.py de cliente, luego de hacerse la conexión y pasar a aceptarla, al ejecutar el mecanismo que se pide en aceptar_cliente solo me acepta una thread y luego me sale el error que adjunto abajo,
<img width="646" alt="Sin título" src="https://user-images.githubusercontent.com/80866868/123135935-609ee480-d420-11eb-839d-6ebca735e907.png">

No entiendo a que se podría deber. Desde ya muchas gracias!]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by StroveLight** [comment]
Hola! Esto se debe a que le estás pasando el valor del parametro args como un int al crear un Thread, pese a que lo que espera recibir es un interable.
Por cierto, ¿te referías al ```aceptar_clientes``` de la clase ```Servidor```?

**Comment by Julius9** [comment]
Hola @Vabu77 :smile: Lo mas probable es que cuando creas el thread que escucha al cliente le estas dando en args un int, en vez de una tupla.  Por lo que si le estas dando el id debería ser ```args=(id,)``` tal como se menciona en los contenidos respecto a Threads

**Comment by Vabu77** [comment]
Ay si, me equivoque era Servidor, lo siento. Ahí se arreglo con lo que dijeron, muchas gracias!!
