### ISSUE TITLE
Threads y variables globales

### ISSUE THREAD

**Issue by amahns1** [IIC2233/syllabus#660]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Contenido

Antes tenía entendido que las variables globales eran una mala práctica. Por lo que aparece en el contenido de threading y queue, tengo la siguiente pregunta:

¿Las variables globales son consideradas como buena práctica para ciertas clases como locks o queues? ¿Cuándo es realmente útil y/o necesario usar variables globales?

Gracias :)

**Comment by aaossa** [comment]
Hola @amahns1 , tal como dices, en general las variables globales son una mala práctica. Sin embargo, para poder responderte mejor, ¿a qué variable global en los contenidos te refieres exactamente? A veces hay que simplificar el código para priorizar la explicación, pero en una de esas te refieres a un uso donde se justifica. Con eso podría responderte mejor 😅 ¡Gracias!

**Comment by amahns1** [comment]
`import threading
import time


# Tenemos dos eventos o señales.
# Esta es para avisar que el video ya está listo para ser reproducido.
video_cargado = threading.Event()
# Esta es para avisar que el audio ya está listo para ser reproducido.
audio_cargado = threading.Event()

def reproducir_video(nombre):
    print(f"Cargando video {nombre} en t={time.time():.6f}")
    # Supongamos que se demora 3 segundos
    time.sleep(3)
    print(f"¡Video cargado! en t={time.time():.6f}")
    # Avisamos que el video ya está cargado
    video_cargado.set()
    # Esperamos a que el audio ya se haya cargado
    audio_cargado.wait()
    # ¡Listo!
    print(f"Reproduciendo video en t={time.time():.6f}")
    
    
def reproducir_audio(nombre):
    print(f"Cargando audio {nombre} en t={time.time():.6f}")
    # Supongamos que se demora 5 segundos
    time.sleep(5)
    print(f"¡Audio cargado! en t={time.time():.6f}")
    # Avisamos que el audio ya está cargado
    audio_cargado.set()
    # Esperamos a que el video ya se haya cargado
    video_cargado.wait()
    # ¡Listo!
    print(f"Reproduciendo audio en t={time.time():.6f}")
    
    
t1 = threading.Thread(target=reproducir_audio, args=("'No Te Enamores' - Paloma Mami",))
t2 = threading.Thread(target=reproducir_video, args=("'No Te Enamores' - Paloma Mami",))

t1.start()
t2.start()

t1.join()
t2.join()`

Por ejemplo aquí `audio_cargado` y `video_cargado` son variabes globales. ¿Esto es para simplificar la explicación o es una buena práctica?

**Comment by aaossa** [comment]
Es para simplificar la explicación, ya que en general tus eventos quedarán como parte de una clase 👈 . Por ejemplo, podrías tener una clase `ReproductorMultimedia` que tenga los eventos como atributos, y que sea la que haga lo del código principal (instanciar los *threads*, iniciarlos y esperarlos), pasando los eventos como argumento a cada *thread* para que puedan coordinarse 🤔 . Al tener los eventos dentro de una clase, puedes controlar de mejor manera quien puede acceder a ellos, en lugar de quedar "sueltos" en tu código, y puedes ocuparlos para enviar y recibir notificaciones/eventos/señales a otros *threads*.

**Comment by amahns1** [comment]
Ya entiendo.

Gracias!!
