### ISSUE TITLE
Duda AF7

### ISSUE THREAD

**Issue by alvarocisternas** [IIC2233/syllabus#661]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ]x Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola!
Tengo un pequeño problema con la actividad.
Cuando realicé la ejecución del main de servidor y main de cliente me apareció un error en el método escuchar_servidor del archivo cliente.py , específicamente al utilizar el método recibir. El error era: TypeError: list indices must be integers or slices, not str.

Realicé un print para ver cómo era el mensaje, y era de este estilo: Mensaje recibido: [{'comando': 'ingreso_rechazado', 'comentario': 'Este usuario no está registrado en la base de datos'}, []] . No se por qué llega como lista y no como diccionario.

Para realizar el método recibir utilicé el mismo que se revisó en la ayudantía (aquí va el código de la ayudantía), con la diferencia que lo adapté en función de las características de la actividad. 

`REDACTED`

La solución "parche" que realicé fue obtener el primer elemento de la lista, ejemplo:
Si recibo: [{'comando': 'ingreso_rechazado', 'comentario': 'Este usuario no está registrado en la base de datos'}, []]
Para obtener el diccionario obtengo el primer elemento y me queda: {'comando': 'ingreso_rechazado', 'comentario': 'Este usuario no está registrado en la base de datos'}

Y ahí me funciona correctamente la actividad.

Mi duda es:
1) Dado el código con el que se nos enseñó en ayudantía, aquel puede poseer algún error? 
2) Si mi actividad funciona correctamente con la solución parche que realicé, puede considerarse como que está bien?

Sorry por mucho texto jajaja,

Quedo atento,

Saludos de antemano.

**Comment by aaossa** [comment]
Hola @alvarocisternas , primero que todo ten cuidado con el código que mencionas o describes de tu actividad. Es una evaluación, así que si compartes parte de tu solución podría considerarse copia (fue mi primera impresión al ver tu *issue*). Respondiendo a tus preguntas:

1. No debería tener errores, quizás tengas que adaptar el código de la ayudantía en lugar de usarlo directamente. Suena a que en alguna parte estás enviando el contenido incorrectamente.
2. No, tu código debe tener algún error porque lo que debería enviarse y recibirse es solo el diccionario, no una lista con el diccionario. Si lo dejas así, al corregir no tendrás el puntaje de esa parte.

¡Éxito con la actividad 🙌 !

**Comment by aaossa** [comment]
@alvarocisternas , podrías mirar #662 , tal vez tienes el mismo error

**Comment by alvarocisternas** [comment]
Primero, disculpe por compartir el código de la ayudantía (creí que se podía).
Segundo, muchas gracias @aaossa por la preocupación, veré si con la issue #662 lo logro resolver.

Saludos!

**Comment by alvarocisternas** [comment]
lo pude resolver @aaossa , efectivamente era el mismo error de mi compañero. Además de no percatarme que se actualizó el archivo logica.py

Saludos!
