### ISSUE TITLE
Semana 9: error al ejecutar programas con GUI

### ISSUE THREAD

**Issue by ElTurkos** [IIC2233/syllabus#661]
![Captura](https://user-images.githubusercontent.com/62064830/81867445-b5460f80-953e-11ea-9a53-41b1a08ab2c0.PNG)

**Comment by fdoflorenzano** [comment]
Hola @ElTurkos,

¿Qué código estás ejecutando? El error que te aparece no parece ser de interfaz gráfica específicamente, es más bien de *networking*... (conexiones con otros computadores, como con uso de internet)

Quedamos atentos.

**Comment by fdoflorenzano** [comment]
Hola @ElTurkos,

¿Qué código estás ejecutando? El error que te aparece no parece ser de interfaz gráfica específicamente, es más bien de *networking*... (conexiones con otros computadores, como con uso de internet)

Quedamos atentos.

**Comment by fdoflorenzano** [comment]
Hola @ElTurkos,

¿Qué código estás ejecutando? El error que te aparece no parece ser de interfaz gráfica específicamente, es más bien de *networking*... (conexiones con otros computadores, como con uso de internet)

Quedamos atentos.

**Comment by ElTurkos** [comment]
ya lo arregle, tenia algo mal copiado :/
