### ISSUE TITLE
Movimiento (WASD) v/s pausa (S)

### ISSUE THREAD

**Issue by caespinoza5** [IIC2233/Syllabus#661]
Quería preguntar si es que puedo (o se puede) cambiar la tecla de pausa a CTRL+P, dado que en caso contrario hay una tecla asociada a dos cosas o eventos distintos del programa.

**Comment by ifcarrera** [comment]
Hola, puedes hacerlo pero debes especificarlo en tu readme para que el ayudante sepa cómo hacerlo :)
Saludos

**Comment by caespinoza5** [comment]
Gracias!
