### ISSUE TITLE
Duda con el metodo clear() de Eventos

### ISSUE THREAD

**Issue by BFry712** [IIC2233/syllabus#661]
### Prerrequisitos
* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola! tengo una duda con el metodo ***clear()*** para los eventos, tengo claro cuando se usa wait() y set() pero no me queda claro que hace clear() ni cuando es recomendable usarlo

**Comment by aaossa** [comment]
Hola @BFry712 , me voy a apoyar en la siguiente figura de los contenidos:

![imagen](https://user-images.githubusercontent.com/10425834/95468780-3d490d80-0955-11eb-8bfd-e7f78f9a2f55.png)

Lo que hace `clear()` es devolver el evento a su estado "inactivo" (`False`). Esto te permite, de cierta manera, "liberar" el evento, de forma que puedas hacer `wait()` y `set()` nuevamente. Si no existiera `clear()`, los eventos quedarían activados para siempre, por lo que no podrías volver a esperar un mismo evento, ya que al hacer `wait()` el evento ya estaría activo y no se detendría la ejecución. Espero se entienda ✨

**Comment by BFry712** [comment]
Perfecto! Muchas graciaas!
