### ISSUE TITLE
Key Space

### ISSUE THREAD

**Issue by Cschavez** [IIC2233/Syllabus#661]
Hola! Tengo un problema al apretar la barra espacio: cuando la presiono no aparece en un KeyPressEvent, y se cierra todo el programa. Yo ya tengo implementado el método para que al apretar ctrl + E se salga del programa, y me di cuenta que extrañamente cuando aprieto la barra espacio se va hacia ese método incluso cuando cambio el retorno del método "salir", sin embargo, no he definido en ninguna parte alguna interacción con la barra espacio. No sé que pasa, ayuda por favoor :(

Gracias!

**Comment by joaquineichholz** [comment]
Yo tengo un problema similar, si lo primero que hago es apretar espacio, se aprieta el primer QPushButton que ponga en el init, independiente de cual sea y no se reconoce el espacio como un KeyPressEvent, por otro lado, si lo primero que hago NO es apretar espacio, el espacio pone bombas y funciona sin problemas el 80% de las veces y las otras veces aprieta el primer QPushButton que haya puesto en el init :(

**Comment by joaquineichholz** [comment]
@mfanselmo1 Muchas gracias!!!!

**Comment by Cschavez** [comment]
Hola! Perdón, sigo sin tener subido mi código, pero intenté eso que mencionaste y aún así no me reconoce la barra espacio cuando la aprieto como un keyPressEvent, y sin yo modificar nada empiezan a aparecer bombas (aún cuando el juego no ha empezado y en la posición 0,0).

**Comment by Cschavez** [comment]
corrección: el código está arriba
