### ISSUE TITLE
paso 7 Heroku

### ISSUE THREAD

**Issue by fantinee** [IIC2233/Syllabus#661]
hola me surgió una duda/problema al seguir los pasos para hacer el deploy con heroku(o en(?)). 
Tras seguir los pasos 1- 6 cuando escribo en el cmd 
` subtree push --prefix Tareas/T07 heroku master`  
me arroja lo siguiente
`git push using:  heroku master
No new revisions were found`
y no puedo completar exitosamente el paso 8 :(
Lo único distinto que hice al procedimiento descrito en el enunciado fue que en el paso 3 cree la app directamente desde la página de heroku con lo que se muestra en la imagen
![image](https://user-images.githubusercontent.com/26147098/27367168-00fadb80-5619-11e7-9de3-11d9d3e33dfa.png)

**Comment by rpalmaotero** [comment]
Hiciste el commit con los cambios que quieres pushear a heroku?

**Comment by fantinee** [comment]
emm... no(upps).... si, se me habia olvidado hacer eso gracias :)
pero ahora me sale lo siguiente:
`
git push using:  heroku master
fatal: 'heroku' does not appear to be a git repository
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
`

**Comment by rpalmaotero** [comment]
Ejecuta `heroku git:remote -a <nombre de tu aplicación>`.

**Comment by fantinee** [comment]
lo hice y me sigue tirando error... aunque ahora otro
` !     No default language could be detected for this app.
			HINT: This occurs when Heroku cannot detect the buildpack to use for this application automatically.
			See https://devcenter.heroku.com/articles/buildpacks
 !     Push failed`
al respecto si tengo el archivo runtime.txt con python-3.6.1 y el resto de los archivos para settear todo

**Comment by rpalmaotero** [comment]
Ingresando al link del error dice que debes ejecutar `heroku buildpacks:set heroku/python`.

NOTA: si alguien más entra a esta issue antes de hacer la tarea, por favor sigan las instrucciones del enunciado para evitar problemas de configuración. Al ejecutar `heroku create` se configuran automáticamente hartas cosas: se setea el remote de git, lenguaje de la aplicación, etc.

**Comment by ofvera** [comment]
No entiendo bien el paso 5, se refiere a programar lo que debe hacer el servidor con las api junto a un main que lo ejecute para que la app lo entienda?

**Comment by chuma9615** [comment]
Yo segui todos los pasos mencioandos pero no me deja subir a heroku! ayuda!
