### ISSUE TITLE
Video ayudantía 7

### ISSUE THREAD

**Issue by knight-who-say-ni** [IIC2233/syllabus#662]
Hola!! Queria saber si van a subir el video de la ultima ayudantia, ya que no pude ir y estoy con un par de dudas de la materia :/
Muchas gracias!!

**Comment by Drpinto1** [comment]
¡Hola!

El video de la ayudantía se subirá pronto y en cuanto esté disponible les mandaremos un anuncio para que lo puedan revisar. Mientras tanto puedes revisar la versión escrita en Syllabus.

Saludos :smile:

**Comment by Drpinto1** [comment]
Ya está arriba el video y se mandó el anuncio :full_moon_with_face:

¡Gracias por el interés en las ayudantías y ojalá te ayude con tu estudio!
