### ISSUE TITLE
Paso 5

### ISSUE THREAD

**Issue by ofvera** [IIC2233/Syllabus#662]
No entiendo bien el paso 5, se refiere a programar lo que debe hacer el servidor con las api junto a un main que lo ejecute para que la app lo entienda?
Al guardarlo en el paso 7 la app entiende que ese es el codigo?

**Comment by MainScientist** [comment]
Ustedes deben programar un servidor en Flask. En el material del curso se explica como hacer un servidor simple el cual tiene un archivo main.py cuyo objetivo es importar la instancia de su aplicacion y hacerla funcionar (con el metodo `app.run()`). El paso 5 es crear los archivos necesarios para que su aplicacion pueda ser ejecutada y correr como un servidor. La variable `FLASK_APP` debe decir cual de sus archivos debe ser ejecutado en pos de levantar su servidor web. Es recomendable que este archivo solo importe la instancia y llame a su metodo run y modularicen el resto te la logica de su servidor.

**Comment by malopez16** [comment]
Perdón pero leyendo el material del curso no logro encontrar lo que indicas :( :

> se explica como hacer un servidor simple el cual tiene un archivo main.py cuyo objetivo es importar la instancia de su aplicacion y hacerla funcionar (con el metodo app.run())

en todos los códigos se hacen directamente las requests desde el módulo y al final se hace un llamado al método run(). Lo que me confunde es que se indica que tenemos que hacer otro módulo, instanciar e código aparte y hacer el run, y luego se indica que hay un ejemplo de eso, pero como no lo encuentro creo que no lo estoy entendiendo bien. Todo esto mezclado con la implementación de Heroku me tiene medio mareado. Leí la otra issue pero no me dejó claro lo que cité :(

**Comment by MainScientist** [comment]
Perdón, creo que me expliqué mal. En el material del curso se crea una instancia del servidor y su lógica en el mismo archivo debido a que la aplicación es bastante simple. A lo que me refería a que el archivo `main.py` debe contener el método `app.run()`. Es importante que sepan que la lógica de la aplicación **no** se debe encontrar por completo en el archivo `main.py`, sino que este solo debe cumplir la función de configurar y levantar el servidor.
