### ISSUE TITLE
Mapa, Muros Indestructubles

### ISSUE THREAD

**Issue by ljrodriguez1** [IIC2233/Syllabus#662]
Podemos asumir que los muros indestructibles siempre estarán dispuesto de la manera que están en el mapa de ejemplo?

**Comment by ptflores1** [comment]
Hola!
No puedes asumir eso, todas las posiciones pueden cambiar
Saludos !

**Comment by PhilippePotin** [comment]
@ptflores1 por ultimo podemos asumir que va a ser un tablero **cerrado** por muros indestructibles?

**Comment by yoavnavon** [comment]
@ljrodriguez1 @PhilippePotin Hola! Queremos ser consistente con lo que dijimos en la sala de ayuda del enunciado, así que hay dos cosas que pueden asumir:
1. El tablero esta cerrado por muros indestructibles
2. Por lo menos estarán los muros indestructibles dispuestos como se muestra en el mapa de ejemplo. Es decir, fila por medio hay muros indestructibles y columna por medio también. Sin embargo, esto no quita que puedan haber más muros indestructibles aparte de los que vienen en el ejemplo. Espero haya quedado claro, saludos!
