### ISSUE TITLE
DUDA AF7 sobre el manejo de mensajes

### ISSUE THREAD

**Issue by santandergc** [IIC2233/syllabus#662]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

tengo una duda, creo que el manejo de mensajes esta erróneo, se supone que debería ser un diccionario y me entrega una lista donde el primer carácter es el diccionario y el segundo el id, entonces al manejar mensajes no funciona.

Acá se puede ver que me entrega un objeto de tipo lista y según la función debería ser un diccionario
![1](https://user-images.githubusercontent.com/80907322/123143084-28030900-d428-11eb-9cc6-661990baef34.PNG)
 
Y acá se puede ver que en el archivo interfaz.py debe recibir un dict pero recibe una lista.

![2](https://user-images.githubusercontent.com/80907322/123143174-47019b00-d428-11eb-9377-a98baa6a4e1c.PNG)

Al poner mensajes = mensajes[0] en la función manejar mensaje de interfaz.py  funciona correctamente todo, ya que no me tira error, pero no se si esto sea correcto en el programa. Al probarlo me funciona todo, el enviar mensajes y chatear con otro usuario, pero si tengo los dos chat abiertos y envio un mensaje, este se muestra en la interfaz del otro solo al apretar de nuevo el chat, como si tuviera que actualizarlo, no se si esto sea correcto. Si pudieran confirmarme, por favor.

**Comment by aaossa** [comment]
Hola @santandergc , ¿podrías subir tu código a tu repo? Al parecer tu cliente está efectivamente recibiendo una lista, por lo que es posible que haya un problema a la hora de enviar los datos desde el servidor. Avísame cuando subas tu código, ¡gracias! 🙌

**Comment by santandergc** [comment]
@aaossa lo acabo de subir con el la linea 121 de interfaz.py des comentada, que es "mensajes = mensajes[0]" para que así funcione

**Comment by aaossa** [comment]
Ya encontré el error, efectivamente está en tu servidor. Para guiarte un poco: fíjate bien en lo que retorna el método `manejar_mensaje` de la clase `Logica`, no retorna lo que en tu código asumes que retorna. El método se explica al inicio de la "Parte I" en el enunciado. Con eso creo que deberías poder arreglarlo 👀 ¡Éxito con la actividad 🙌 !

**Comment by santandergc** [comment]
muchas gracias! ya pude resolverlo
