### ISSUE TITLE
Duda Frontend - Backend

### ISSUE THREAD

**Issue by Javierdr** [IIC2233/Syllabus#662]
Hola,
tengo una duda dando vueltas hace mucho rato. Como diferenciar bien que es frontend y que es backend. Se que el frontend es todo lo que tenga que ver con la interfaz gráfica y el backend es todo lo que involucra calcular cosas pero aun así siento que hay muchas cosas que pueden entrar en ambas categorías. Se que no pueden decirme en la tarea que cosas son frontend y cuales backend (ademas que depende de la modelación de cada uno) pero me ayudaría muchísimo si me pudieran decir en el ejemplo que subieron (el de la pelota moviendose) que cosas debieran ir en backend y cuales en frontend ya que en el ejemplo esta todo en un mismo archivo. 
Saludos :v: :v: y feliz halloween :ghost: :jack_o_lantern: :ghost: :jack_o_lantern:

**Comment by Hernan4444** [comment]
@Javierdr En el ejemplo tenemos 2 clases principales, `Bastian` y `Character`. El Frontend, en general, se encarga solo de interactuar con el usuario y permitir visualizar todo lo que el Backend hace. Podrás notar que `Bastián` tiene un método para poner, en alguna posición de la interfaz, la imagen que le dan. Es por ello que `Bastian` es Frontend.

Por otro lado, `Character` tiene un atributo que es la imagen, pero él nunca se encarga de ver si la imagen está o no en la posición indicada, él solo tiene un método `run` en donde procesa una información (podemos decir que "piensa"), le manda sus resultados al Frontend y ahí se desliga de toda responsabilidad. Para el backend, la imagen ya está en la posición indicada sea o no así en el Frontend. Es por ello que `Character` es backend.

Es cierto que hay cosas que pueden entrar en ambas categorías, pero siempre ten en cuenta que el Frontend es solo una herramienta para mostrar lo que quieres, él es solo un canal que conecta al usuario con el backend. Lo mejor es dejar todo procesamiento al backend (aunque sea lo más absurdo), pero si  lo piensas en gran escala (una aplicación), si dejas que el frontend tenga el cálculo de algún detalle y eso está mal, ¿Qué tan fácil será darse cuenta que error está en el frontend y no en el backend?

Espero haber ayudado a diferenciar mejor estos conceptos.
Saludos ✌️

**Comment by augustoas** [comment]
Los eventos de apretar teclas se pueden hacer en el front end o es una mala practica? Tengo un mainwindow y estoy usando keyPressEvent desde ahi

**Comment by iqacevedo** [comment]
En general los eventos de apretar teclas se capturan ahí, en el frontend. Lo que pasa luego se maneja con el Backend (las acciones que desencadena apretar una tecla).

Saludos !
