### ISSUE TITLE
Juego se pega al crear enemigos

### ISSUE THREAD

**Issue by naazocar** [IIC2233/Syllabus#663]
Hola, bueno mi problema básicamente es el del título. Implementé un QTimer conectado a una función que se encarga de crear enemigos. Efectivamente los enemigos se crean, se mueven y todo, el tema es que por ejemplo si pongo un time.sleep(x) en la funcion, el juego se queda pegado por esos x segundos, luego se actualiza la imagen y se pega de nuevo :(

Busqué en internet y creo que el problema es porque se hace todo en el 'main thread', sin embargo no entendí como arreglarlo, intenté de varias formas y aún no puedo, ayuda :pray:

**Comment by iqacevedo** [comment]
Hola, 
Lo más probable es que sea un problema con como interactuan las señales en tu programa. Hace unos días se subio material extra de PyQt5 [aquí](https://github.com/IIC2233/contenidos/blob/master/semana-11/Extra/Se%C3%B1ales.ipynb).

Puedes revisarlo y ver si es lo que te está pasando.

Saludos !
