### ISSUE TITLE
Error pickle y json

### ISSUE THREAD

**Issue by diegonavarrovergara** [IIC2233/Syllabus#663]
Hola, en la tarea 6 (soy el alumno que por un caso especial le dieron más plazo), intento mandar mensajes desde el servidor al cliente mediante diccionarios y pickle o json. Los mensajes son algo de este estilo:

```
msj_final = {'tipo': 'cambio_cancion', "cancion": self.cancion ... }
msj_final_pickle = pickle.dumps(msj_final)
cliente_socket.send(msj_final_pickle)
```

La gran mayoría de mensajes funciona, pero de repente, especialmente cuando mando mensajes para cambiar de canción, me tira alguno de los siguientes errores:

`_pickle.UnpicklingError: unpickling stack underflow`
`_pickle.UnpicklingError: invalid load key, '	'`
`EOFError.`

Intenté cambiando de pickle a json y me tira los siguientes errores:

`ValueError: Extra data: line... column...`
`json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

Por el lado del cliente, recibo los mensajes así (porque ocupo pickle y json):

```
data = self.socket_cliente.recv(2048)
try:
     data_decoded = data.decode('utf-8')
     mensaje = json.loads(data_decoded)
except UnicodeDecodeError:
     mensaje = pickle.loads(data)

```
He googleado muchísimo y no he podido encontrar una respuesta. Por favor ayuda!!

**Comment by diegonavarrovergara** [comment]
Al parecer ya la solucioné. Tenía un problema con los threads y no creaba bien el mensaje. 
De todas maneras, me gustaría saber si mi manera de comunicar el servidor con el cliente es la correcta o si tiene algún problema. Gracias.

**Comment by jtagle2** [comment]
Está "bien" pero pinta para mal.
Si lo que quieres implementar es algo básico como un envío de mensajes pequeños (ej: un diccionario, puros strings, etc...) recibir 2048 bytes siempre, **podría** (no necesariamente) funcionar. Cuando pasamos a cosas más complejas como enviar archivos o cosas mas pesadas (en este caso, más pesadas que 2048 bytes), entonces el envío y recibo de datos se hace un poco más complejo también.
No se como lo estás haciendo, pero ¿Qué pasa si el archivo que te envía el servidor son 2049 bytes? Te haces cargo de eso? ¿Cómo estás recibiendo ese byte extra? ¿Cómo sabes que tienes que recibir 2049 bytes? ¿O que pasa si el cliente recibió un mensaje, y antes de que llegue a un  `recv` recibe otro más? ¿Cómo le dices que recibió dos mensajes y no uno?
A modo de hint, lo correcto es hacer un buffer e ir recibiendo la información de pedazos, y **ser exacto en la cantidad de datos que pides con recv** (ya no puedes decir 2048 siempre, porque hay veces que vas a necesitar mas y otras menos). Ahí va lo general, ahora google puede ser tu mejor aliado :+1: 
Saludos! y éxito en el fin de semestre
