### ISSUE TITLE
Test Funcion 3 incorrecto

### ISSUE THREAD

**Issue by Tomasalvarez15** [IIC2233/syllabus#663]
En el archivo json trees_route hay un error. Para los 3 ejemplos se usa la data
"data": [4, 7, 15, 10, 11, 12]
Lo que debería generar un arbol así:
                  4
          7            15
      10  11    12    None

Las soluciones deberian ser:
Para 11,10 = [11,7,10] Esta está correcta
Para 10,15 = [10,7,4,15] y está  [10,7,4,12,15] puesta como solución
Para 4,12 = [4,15,12] y está [4,12]

Claramente parece un error en que el 15 y el 12 están cambiados. Solo me quiero asegurar para no perder puntos.

**Comment by Hernan4444** [comment]
Hola, recuerda que el árbol se debe balencear despues de ingresar un nodo

> Lo que debería generar un arbol así:
4
7 15
10 11 12 None

Eso no está correcto. Porque cuando ingresas el 12, este se cambia por el 15 para seguir las reglas del AlgarroboTree. Lo que debería generar un árbol así:
```
         4
   7        12
10 11   15 None
```

Y por lo tanto, las rutas están correctas. Recomiendo revisar la sección de _swapping_ del enunciado donde se detalla todo esto.

Saludos ✌️

**Comment by Tomasalvarez15** [comment]
No sabía que se le tenía que aplicar. Gracias, ahora me funcionan todos los test.
