### ISSUE TITLE
Ayuda con flechas keyevent (si otro más de keyevent)

### ISSUE THREAD

**Issue by Calomi** [IIC2233/Syllabus#663]
Hola, ya vi q varios han tenido problemas con key event y el focus
a mi ya me funciona mas o menos bien, ya cache q con el
`self.setFocusPolicy(Qt.StrongFocus)`
hace q el keyPressEvent de mi ventana/widget sea el que capture las flechas en vez de los botones q andan por ahí.
Mi problema es que el keyPressEvent no me captura la primera vez q aprieto una flecha, pero a la vez el keyReleaseEvent si captura esa primera vez!! (puse un print después del isAutoRepeat en los dos eventos) entonces keyrelease hace lo suyo sin que se haya hecho el keypress antes y me tira error, solo la primera vez que aprieto una flecha (y esto hace que se me bugee el muestreo de los sprites(o al menos espero q sea eso jaja)), asigne las teclas ijkl como flechas (wasd es para el player2) (mandan la misma señal) y funcionan bien la primera vez, pero incluso después de ijkl, si uso una flecha, pasa lo mismo, no me captura el primer keyPress.. ., luego del primer press, los siguientes keyPress funcionan bien.

Si luego de apretar comenzar (aquí se ejecuta el setFocusPolicy) si hago click en la ventana y luego presiono una flecha, ahí funciona bien, entonces entiendo q en mi widget q captura las teclas, el setFocusPolicy no está haciendo bien su trabajo, pero porquee?.
Alguien que me pueda dar una idea de que pasa??  😢 
vi que pueden revisar el código de uno, puedo pedir lo mismo 🙏 ? 😃  en verdad no veo el problema :(

EDIT: mi isAutoRepeat lleva a un soltario return, que sería lo mismo que if not isAutoRepeat, además tambien puse un print antes del autoRepeat y ese tampoco se imprime, claro si lo dejo apretado se empieza a imprimir muchos, pero no el primero, (apreto y suelto antes que se empiece a repetir)

**Comment by jmwielandt** [comment]
isAutoRepeat en keyPressEvent parte con un False y después muchos True
isAutoRepeat en keyReleaseEvent parte con muchos True y al final un False

Creo que aquí está tu problema
#NoSoyAyudante

**Comment by Calomi** [comment]
o perdón, no especifique eso, mi isAutoRepeat lleva un soltario return, que sería lo mismo que if not isAutoRepeat, además tambien puse un print antes del autoRepeat y ese tampoco se imprime, claro si lo dejo apretado se empieza a imprimir muchos, pero no el primero, (apreto y suelto antes que se empiece a repetir), lo editaré
gracias igual :)
