### ISSUE TITLE
Accion tiene cierto tiempo para ser realizada

### ISSUE THREAD

**Issue by aayale** [IIC2233/syllabus#663]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda
Hola, en la AS02 me surgió la duda de ¿Cómo uno hace que una acción tenga cierto tiempo para realizarse? (ej.: tienes 5 minutos para reparar el celular)

**Comment by aaossa** [comment]
Hola @aayale , creo que hay más de una forma posible de hacerlo, así que intentaré mostrarte un par que se me ocurren ahora:

1. **Usando `Timer` (como en la AS02)**: Tal como en la actividad, una primera forma es utilizando un `Timer` que se ejecutará en cierta cantidad de tiempo. Al terminar la cantidad de tiempo, puedes verificar si se cumple la condición de término (en tu ejemplo, si se reparó o no el teléfono) y aplicar el comportamiento adecuado que corresponda.
2. **Utilizando un `Thread`**: Otra forma es utilizar un `Thread` que, volviendo a tu ejemplo, duerma por 5 minutos o haga algo durante esos 5 minutos (por ejemplo, ir imprimiendo una cuenta regresiva). Nuevamente, una vez que se cumpla el tiempo, podrás aplicar el comportamiento que corresponda.

Utilizar la primera opción o la segunda puede lograr el mismo efecto, pero ¿cuándo usar una o la otra? La primera, deja el *thread* en "reposo" y solo actúa cuando se cumple el tiempo, mientras que la segunda mantiene al *thread* activo por una mayor cantidad de tiempo. En estricto rigor, diría que es mejor la primera para tu ejemplo, pero hay casos donde la segunda hace sentido (si es que necesitas que el *thread* haga algo mientras).

Ojalá te sirva la respuesta, pero si quieres más detalle o tienes más dudas, pregunta de nuevo acá mismo no más 👌

**Comment by aayale** [comment]
pero si usará la opción del thread por ejemplo, ¿Cómo hago que haga (valga la redundancia) algo por 5 minutos?, ¿Cómo hago que después de esos 5 minutos no pueda seguir haciéndolo?

**Comment by aaossa** [comment]
@aayale si quieres que deje de hacer algo, simplemente tienes que dejar que el método `run` termine. Por ejemplo, con algo así:

```python
class Ejemplo5Minutos:

    def __init__(self, *args, **kwargs):
        # ...

    def run(self):
        # Como 5 minutos son 300 segundos...
        for i in range(300):
            sleep(1)
        # (Tambien podía ser sleep(300))
```

Después de 300 segundos, el código va terminar de ejecutar el método `run`, por lo que el *thread* llegará a su fin (y, por ejemplo, si otro *thread* estaba haciendo `join` a este, podrá continuar). ¿Es esto a lo que te referías?

**Comment by aayale** [comment]
siii, buenisimo. Muchas gracias!
