### ISSUE TITLE
AF7: error al ejecutar main del servidor

### ISSUE THREAD

**Issue by kvonstorch** [IIC2233/syllabus#663]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola, al ejecutar el main del servidor  me sale un error que dice lo siguiente: 
FileNotFoundError: [Errno 2] No such file or directory: './db/usuarios.json'

Todos los archivos indicados en el terminal, son archivos que no debemos modificar, llevo un buen rato viendo mi código para corregirlo, pero no encuentro una relaciona entre mi código y el error producido:

**¿Qué puede estar produciéndolo? y ¿Cómo lo puedo corregir?**

Agradezco de antemano.

**Comment by aaossa** [comment]
Hola @kvonstorch , ¿desde dónde estás ejecutando el archivo? Tu consola debería estar dentro de la carpeta del servidor y ejecutar el comando así `python3 main.py` (o `python`, depende de lo que ocupes). Si estás en otra ubicación las rutas relativas no funcionan como se espera. Avísame si es eso 🙌

**Comment by kvonstorch** [comment]
Lo estaba ejecutando en la carpeta de la actividad, ahora si me funciono.
Muchas gracias!
