### ISSUE TITLE
No me deja installar PyQt5-tools

### ISSUE THREAD

**Issue by CataSudo** [IIC2233/syllabus#663]
Hola, he tratado de installar  PyQt5-tools, pero me aparece esto. Porque no funciona, tengo un Mac, por si hace diferencia?
<img width="582" alt="Screen Shot 2020-05-13 at 18 00 13" src="https://user-images.githubusercontent.com/62016215/81870320-9bf39200-9543-11ea-88bd-46ce4d675aa2.png">

**Comment by aaossa** [comment]
Hola @CataSudo , una razón podría ser que no estás usando una versión de Python que tenga una versión de PyQt5 asociada. En primer lugar el comando que deberías utilizar es `pip3`, ya que `pip`, en tu caso, dirige a la versión de Python 2.7. ¿Podrías indicar el *output* de `pip3 --version` y de `python3 --version`? Debería aparecer que estás en Python 3.7.

**Comment by CataSudo** [comment]
Mi output es este
<img width="495" alt="Screen Shot 2020-05-13 at 18 57 41" src="https://user-images.githubusercontent.com/62016215/81874324-a580f800-954b-11ea-9307-0c5ecaf27dd4.png">

**Comment by aaossa** [comment]
Quizás se deba a la versión de PyQt5 que tienes, prueba con `pip3 install --upgrade pyqt5-tools` (ojo también que lo puse en minúsculas, por si es eso)

**Comment by fddelabarra** [comment]
Hola también tengo un problema con pyqt5
Al tratar de instalarlo me aparece "Requeriment already satisfied: PyQt5_sip(luego un path) (from pyqt5)"
Pero al intentar correr el código que nos dieron de ejemplo en el primer jupyter notebook de interfaces me dice 
Traceback (most recent call last):
  File "PyQt5.py", line 1, in <module>
    from PyQt5.QtWidgets import QWidget, QApplication
  File "PATH", line 1, in <module>
    from PyQt5.QtWidgets import QWidget, QApplication
ModuleNotFoundError: No module named 'PyQt5.QtWidgets'; 'PyQt5' is not a package
Pero si corro el archivo main.py de la ayudantía, funciona sin problemas, se abre la ventana de DCCorreo, que puede ser lo que pasa? :c

**Comment by aaossa** [comment]
@fddelabarra en tu caso es porque le pusiste a tu archivo de prueba el mismo nombre que la librería que intentas importar. Colócale otro nombre y debería funcionar 🤔 ¿Podrías probar eso?

**Comment by CataSudo** [comment]
Sigue sin funcionar, y también no entiendo bien el error, a que versión se refiere? 
<img width="495" alt="Screen Shot 2020-05-13 at 19 57 20" src="https://user-images.githubusercontent.com/62016215/81877773-fdbbf800-9553-11ea-935d-21822b825e76.png">

**Comment by fddelabarra** [comment]
> @fddelabarra en tu caso es porque le pusiste a tu archivo de prueba el mismo nombre que la librería que intentas importar. Colócale otro nombre y debería funcionar 🤔 ¿Podrías probar eso?

ahora me aparece "name 'sys' is not defined" jasjajs T-T, aunque no me habia dado cuenta de lo del nombre jajaja, gracias por eso! :s

**Comment by aaossa** [comment]
@CataSudo a todo esto, ¿ya intentaste con *brew*? Es lo que aparece en la guía [sección de *software* obligatorio de la wiki](https://iic2233.github.io/wiki/software) (`brew install pyqt5 --with-python3`). Si no es eso, ¿cómo instalaste Python? ¿Estás usando Anaconda?

@fddelabarra Asumo que ese error se debe a que olvidaste agregar el `import sys` al comienzo de tu código. ¿Para qué se usa `sys`? Tiene muchos métodos, así que depende de a cuál te refieras la verdad. Si te refieres a `sys.exit(arg)`, lo que hace es salir de Python y avisarle al sistema que terminó de ejecutarse Python (normalmente) con código que indica si terminó exitosamente o con algún tipo de error. En el contexto de interfaces gráficas, se utiliza para pasar el código de término de la ventana al sistema (algo de esto se comenta en el primer EP de esta semana)

**Comment by fddelabarra** [comment]
> @fddelabarra Asumo que ese error se debe a que olvidaste agregar el `import sys` al comienzo de tu código.
@aaossa es el codigo de ejemplo, si tenia escrito el `import sys` por eso no se porque no funciona :c , gracias por la explicacion, no sabia de su uso :)

**Comment by CataSudo** [comment]
Installe python 3 siguendo las instrucciones de la seccion de software obligatorio, pero sigue sin funcionar.
<img width="595" alt="Screen Shot 2020-05-14 at 10 53 54" src="https://user-images.githubusercontent.com/62016215/81950035-7614ce80-95d1-11ea-9da4-056417a773c5.png">

**Comment by arturobugueno** [comment]
Yo tuve el mismo error. Si estas en VSC, anda a ala sección de extension de Python que estas usando. Lo mas probable es que tengas mas de una, asi que prueba todas las que tienes hasta ver cual de todas es la que tiene instalada PyQt5. 
<img width="433" alt="Screen Shot 2020-05-14 at 11 07 13" src="https://user-images.githubusercontent.com/62082057/81951370-14556400-95d3-11ea-8759-573781511707.png">

Te recomiendo usar este ejercicio de la la sección de contenidos de esta semana. 
<img width="846" alt="Screen Shot 2020-05-14 at 11 08 46" src="https://user-images.githubusercontent.com/62082057/81951671-74e4a100-95d3-11ea-9ad8-7e4f2e1b2bec.png">

Acá te dejo lo que te debería salir.
<img width="949" alt="Screen Shot 2020-05-14 at 11 10 27" src="https://user-images.githubusercontent.com/62082057/81951726-875eda80-95d3-11ea-8b58-50f1171a4753.png">

**Comment by CataSudo** [comment]
<img width="971" alt="Screen Shot 2020-05-14 at 11 16 21" src="https://user-images.githubusercontent.com/62016215/81952369-63e85f80-95d4-11ea-9616-72ad5dfac770.png">
Si, tengo esta versión. Me da la ventana, pero no me deja descargar pyqt5-tools.

**Comment by DaHunterTime** [comment]
Tuve el mismo problema con pyqt5-tools y según lo que encontré en internet, pyqt5-tools no está disponible para mac (quizás estoy equivocado y también estoy haciendo algo mal), pero se puede instalar Qt Designer, o Qt Creator en caso de querer todas las herramientas, por separado
Encontré los siguientes links:
Qt Designer: https://build-system.fman.io/qt-designer-download
Qt Creator: https://www.qt.io/download

**Comment by CataSudo** [comment]
Gracias!
