### ISSUE TITLE
DelateLater / Deleteonclose

### ISSUE THREAD

**Issue by PIPEAPABLAZA** [IIC2233/Syllabus#664]
He estado investigando maneras eficientes de manejar las ventanas, de manera de limpiar las entidades creadas al cerrar una de estas ventanas, sin  embargo no consigo cerrar/eliminar/limpiar las entidades creadas desde una ventana padre.

Por ejemplo en una ventana principal tengo un atributo que consisten en una ventana hijo. pero al cerrar el padre la ventana hijo no se cierra y se mantiene procesando. Esto incluso si le aplico deletelater y deleteonclose a la ventana padre. Estaré haciéndolo mal? , habrá otra manera? , algún consejo?. 🍰

**Comment by iqacevedo** [comment]
Hola,

Lamento la demora, si aún no lo has hecho podrías emitir una señal que indique que las entidades deben eliminarse, las puedes eliminar con DeleteLater ahí. De esa manera te aseguras de que todo lo que esté conectado a la interfaz padre se elimine. No me manejo muy bien con Deleteonclose, pero hasta donde se deberías setear esa propiedad para cada entidad hijo de la ventana que se va a cerrar.

Saludos !
