### ISSUE TITLE
No sé qué hice, pero culparé a microsoft por comprar github [SOS][Mi repo no me quiere]

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#664]
Hola, 
No sé qué pasó pero el efecto de la compra se está haciendo notar en mi repo (?)
No me deja hacer push porque dice que las cosas se han bifurcado en mi rama principal (solo tengo esta)
![image](https://user-images.githubusercontent.com/37153467/41077824-f10315d4-69e6-11e8-9047-ea107ba01a5b.png)
Si hago git pull, como dice, me manda a esta pantalla y no tengo como salir ni nada, por mucho que escriba o apriete teclas al azar (se supone que esto siempre funciona 😱)
![image](https://user-images.githubusercontent.com/37153467/41077857-1cc9854a-69e7-11e8-95c0-afb126ff4854.png)
Escribir ^G, ^X y las otras cosas que salen abajo no ayuda en nada.

Este es el mensaje que me sale al intentar pushear
![image](https://user-images.githubusercontent.com/37153467/41077879-47ffd958-69e7-11e8-8b55-a7a7dcf1f44c.png)

Solo queda que facebook compre microsoft para que ahora tengamos publicidad y fake news issue por medio u.u

EDIT: ahora está así
![image](https://user-images.githubusercontent.com/37153467/41077956-ca662f3c-69e7-11e8-8f56-a17c7938e46d.png)
y acabo de cachar que en mi repo (a través de github) no aparecen los cambios que he hecho desde hace dos días

**Comment by rihanuch** [comment]
Hola!

Haz un git pull y luego en la pantalla que no te deja hacer nada escribe :wq (en ese orden) eso hara el merge

Saludos!

**Comment by rihanuch** [comment]
Haz un commit y luego un pull, si sigue saliendo la pantalla en que no puedes hacer nada escribe :wq . Esto finalizara el merge
