### ISSUE TITLE
Creacion de una repo desde Python

### ISSUE THREAD

**Issue by benjamimo1** [IIC2233/Syllabus#664]
```
credentials[0]="benjamimo1"
url = "https://api.github.com/{}/repos".format(credentials[0])
paramas= "un diccionario con los parametros
req = requests.post(url, data=json.dumps(params), auth=credentials)
```

Usando este codigo (extraido desde la notebook sugerido en el enunciado) me arroja error: 
```
404
{
    "message": "Not Found",
    "documentation_url": "https://developer.github.com/v3"
}
```
Y no se por que :(

**Comment by rpalmaotero** [comment]
El notebook está correcto. Revisaste la documentación de Github (https://developer.github.com/v3/repos/#create)?

HINT: Error 404 indica que un recurso no existe. Revisa la URL.

**Comment by benjamimo1** [comment]
usando  la url: "https://api.github.com/user/repos". No tengo problemas para usar un get, pero falla en el post :( , por lo que el problema no es exclusivamente url aiudaaa

**Comment by benjamimo1** [comment]
Literalmente copie y pegue el codigo y no funciona 🤔
```

import base64
import json
import requests

def print_pretty(jsonstring, indent=4, sort_keys=False):
    print(json.dumps(jsonstring, indent=indent, sort_keys=sort_keys))
    
credentials=("censurado")
url = "https://api.github.com/user/repos"
params = {
    "name": "dummy_repo",
    "description": "An example repo using GitHub API v3",
    "homepage": "{}.github.io".format(credentials[0]),
    "private": False,
    "has_issues": True,
    "has_wiki": False,
    "has_downloads": False,
    "auto_init": False
}
req = requests.post(url, data=json.dumps(params), auth=credentials)

print(req.status_code)
print_pretty(req.json())

if req.status_code == 201:
    repo_url = req.json()["url"]
    contents_url = req.json()["contents_url"]
```

**Comment by stephichau** [comment]
@benjamimo1 ```credentials``` lo tienes como ```(tu_nombre_de_usuario, token)``` ?

**Comment by benjamimo1** [comment]
@stephichau si! Una tupla, que funciona para get por ej. Asi que el problema no va por ahi.

**Comment by stephichau** [comment]
mm entonces, te fijaste bien en los permisos cuando creaste el token ?

**Comment by FernandoPieressa** [comment]
Hola! Intenta esto
self.credentials = (user, token)
url = "https://api.github.com/user/repos"
self.req = requests.post(url, auth=self.credentials)

la url va con user, no con el tuyo especifico. En manejo de api recuerda ver que los parametros que tienen un : significa que depende de un caso especifico.

Saludos!

**Comment by benjamimo1** [comment]
Asi como? El get por ejemplo funciona perfecto para ver info de mis repo.

**Comment by benjamimo1** [comment]
@FernandoPieressa Estoy intentando con el codigo copiado y pegado (solo cambio el credentials) y aun asi no funciona.
@stephichau asi como? El get por ejemplo funciona perfecto para ver las repos (por lo que las credentials funcionan)

**Comment by FernandoPieressa** [comment]
Acabo de probar el mismo con mis misma informacion y me crea correctamente el repositorio. Revisa en tus settings de github la personal access token a ver si tienes activado
