### ISSUE TITLE
Ejecutar codigo con dos ventanas ( o más)

### ISSUE THREAD

**Issue by jaimecoloma** [IIC2233/syllabus#664]
Hola! me pasa que tengo todo instalado y puedo hacer ejercicios y ver los ejemplos propuestos, sin embargo cuando toca abrir dos ventanas estas no se me abren simultaeamente, solamente cerrando una o minimizandola se puede ver la otra, esto es normal? y que puedo hacer para arreglarlo si no?

**Comment by fdoflorenzano** [comment]
Hola @jaimecoloma,

¿Me darías un ejemplo de programa donde te ocurra? Porque difícil entender si es para casos específicos o general. Mejor, te doy un caso yo, intenta con el más básico:

```python
import sys
from PyQt5.QtWidgets import QWidget, QApplication

class MiVentana(QWidget):
    def __init__(self, x, y):
        super().__init__()

        # Definimos la geometría de la ventana.
        # Parámetros: (x_superior_izq, y_superior_izq, ancho, alto)
        self.setGeometry(x, y, 100, 100)

        # Podemos dar nombre a la ventana (Opcional)
        self.setWindowTitle('Mi Primera Ventana')


if __name__ == '__main__':
    app = QApplication([])
    ventana = MiVentana(100, 100)
    ventana.show()
    ventana_2 = MiVentana(300, 100)
    ventana_2.show()
    sys.exit(app.exec_())
```

¿En este caso tampoco puedes ver ambas al mismo tiempo?
Quedamos atentos.

Saludos.

**Comment by jaimecoloma** [comment]
Hola, copie y pegue el codigo y me pasa lo mismo, que no me ejecuta ambas ventanas al mismo tiempo si no más bien es como que abre una, espera que la cierre o minimice en la barra de abajo y luego abre la segunda. Si minimizo la primera y despues la abro de nuevo puedo verlas al mismo tiempo pero me llama la atencion que no funcione :(

**Comment by fdoflorenzano** [comment]
Hola @jaimecoloma,

Qué raro... ¿tienes seguridad que las ventanas no se están escondiendo detrás de otros programas que tienes abiertos? ¿has intentado minimizar todo el resto? Es lo único que se me ocurre, si no a Googlear. Si agregas un `print` entre los `show`s del código, ¿aparece?

Saludos.

**Comment by jaimecoloma** [comment]
@fdoflorenzano no habia probado minizando VS! (lo ejecuto en un escritorio solo, era lo unico que podia ser) y efectivamente ahi estaba la muy .... jaja muchisimas gracias! quedo tranquilo :)
