### ISSUE TITLE
AF7: problemas con respuesta del servidor, destinatarios vacíos

### ISSUE THREAD

**Issue by Pabloski100** [IIC2233/syllabus#665]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Por alguna razón, la lista de id's me llega vacia siempre

Hola, anteriormente  hice un issue diciento que el boton de entrar del inicio aparentemente no funcionaba, después de colocar varios logs me acabo de dar cuenta que si bien se envían mensajes del cliente al servidor, el servidor nunca responde, y al hacer un log de la lista de destinatarios me di cuenta que siempre me aparece una lista vacía.

Me imagino que tal vez es porque se debe probar el servidor con varios clientes, y hasta ahora solo intentaba con uno, de todas maneras pregunto, ¿es normal que funciones asi?

**Comment by aaossa** [comment]
@Pabloski100 se actualizó el código con un 🐛 que había. Puedes ver el cambio aquí: https://github.com/IIC2233/syllabus/commit/7c69b44da8ad6c2fb35a39cb78929d36243ce48e

**Comment by Pabloski100** [comment]
Oh, no me había enterado, gracias!
