### ISSUE TITLE
Error correr la aplicación en heroku

### ISSUE THREAD

**Issue by bimartinez** [IIC2233/Syllabus#665]
Hola! he estado intentando correr una aplicacion de prueba en heroku y me arroja el siguiente error:
`Error: The file/path provided (main.py.) does not appear to exist.  Please verify the path is correct.  If app is not on PYTHONPATH, ensure the extension is .py` 
seguí todos los pasos correspondientes en el enunciado de la tarea pero no he podido corregir este error.

Saludos!

**Comment by MainScientist** [comment]
Al parecer copiaste el punto final. El archivo debe ser `main.py` (sin el punto al final).

**Comment by bimartinez** [comment]
Gracias!! exactamente eso era jajajaja
