### ISSUE TITLE
problemas instalando PyQt5 macOs

### ISSUE THREAD

**Issue by pabloalvarez67** [IIC2233/syllabus#665]
Hola, al ejecutar en terminal pip3 install pyqt5, me aparace esto:
![Captura de Pantalla 2020-10-10 a la(s) 11 05 46 a  m](https://user-images.githubusercontent.com/62023649/95657035-a6ad5580-0ae8-11eb-9029-26fc4ae26403.png)

Pero luego no puedo correr un archivo de python usando la línea import PyQt5 !!!

Además, después no puedo instalar Qt Designer ni usando pip3, ni descargándolo de la página recomendada:
https://iic2233.github.io/wiki/software

Que podría ser? alguien tuvo un problema similar?

**Comment by aaossa** [comment]
Hola @pabloalvarez67 , en primer lugar, por favor no borres el texto de la plantilla, sino no tenemos cómo saber que hiciste lo que se pide (por algo la armamos y les pedimos que no la borren 😅). 

**PyQt5**: ¿Cómo probaste ejecutando el archivo? ¿Usaste el comando `python3 archivo.py`? Por lo que se ve en tu captura, se instaló sin problemas, y deberías poder ocuparlo corriendo la versión correcta de Python y Pip. De paso, podrías comprobar que `pip3` esté "conectado" a la versión correcta de Python usando `pip3 --version`. 

**Qt Designer**: ¿Qué probaste exactamente y qué error te apareció? Con eso ya podemos ir descartando posibles soluciones y buscar una que te funcione 👌 

Avisa por acá lo que te funcione y lo que no 🙌

**Comment by pabloalvarez67** [comment]
> Hola @pabloalvarez67 , en primer lugar, por favor no borres el texto de la plantilla, sino no tenemos cómo saber que hiciste lo que se pide (por algo la armamos y les pedimos que no la borren 😅).
> 
> **PyQt5**: ¿Cómo probaste ejecutando el archivo? ¿Usaste el comando `python3 archivo.py`? Por lo que se ve en tu captura, se instaló sin problemas, y deberías poder ocuparlo corriendo la versión correcta de Python y Pip. De paso, podrías comprobar que `pip3` esté "conectado" a la versión correcta de Python usando `pip3 --version`.
> 
> **Qt Designer**: ¿Qué probaste exactamente y qué error te apareció? Con eso ya podemos ir descartando posibles soluciones y buscar una que te funcione 👌
> 
> Avisa por acá lo que te funcione y lo que no 🙌

Ooh, perdona por lo de la plantilla, hace tiempo que no hacia una issue.
Lo ejecuté en VSCode, y me tira el error de importación. use el comando python3 archivo.py y no pasa absolutamente nada jajaja. Luego comprobé la versión de pip3 y me dijo que estaba en python 3.7

Respecto a Qt Designer, me tira este error:
![Captura de Pantalla 2020-10-10 a la(s) 11 56 38 a  m](https://user-images.githubusercontent.com/62023649/95658303-b2504a80-0aef-11eb-9192-5de147835713.png)

luego, probe instalandolo por el link recomendado en caso de que ocurra eso, y me sigue tirando el mismo error.

Gracias!

**Comment by aaossa** [comment]
@pabloalvarez67 ¿Probaste cerrando VSCode y volviéndolo a abrir (típica solución jajaja Pero podría funcionar)? Además, si sigue sin funcionarte desde VS Code, te recomendaría probar con otras versiones de Python hasta encontrar aquella en la que se instaló:

![imagen](https://user-images.githubusercontent.com/10425834/95658402-85506780-0af0-11eb-88a6-869281b1b2ce.png)

En cuanto a `pyqt5-tools`, dijiste que ocupaste [este link](https://build-system.fman.io/qt-designer-download), ¿qué error te aparece exactamente? ¿Probaste revisando si ya tenías Qt Designer al instalar con el archivo del *link*?

PS: Obviamente con `python3 archivo.py` era un ejemplo donde en lugar de `archivo.py` tenías que poner el nombre de tu archivo (espero que lo hayas hecho 😅).

**Comment by pabloalvarez67** [comment]
> @pabloalvarez67 ¿Probaste cerrando VSCode y volviéndolo a abrir (típica solución jajaja Pero podría funcionar)? Además, si sigue sin funcionarte desde VS Code, te recomendaría probar con otras versiones de Python hasta encontrar aquella en la que se instaló:
> 
> ![imagen](https://user-images.githubusercontent.com/10425834/95658402-85506780-0af0-11eb-88a6-869281b1b2ce.png)
> 
> En cuanto a `pyqt5-tools`, dijiste que ocupaste [este link](https://build-system.fman.io/qt-designer-download), ¿qué error te aparece exactamente? ¿Probaste revisando si ya tenías Qt Designer al instalar con el archivo del _link_?
> 
> PS: Obviamente con `python3 archivo.py` era un ejemplo donde en lugar de `archivo.py` tenías que poner el nombre de tu archivo (espero que lo hayas hecho 😅).

Era la versión que estaba usando! jajajaj que pavo.
Si, obvio que lo corrí con el nombre mi archivo probandolo jajajaja se entendió el ejemplo.

El Qt Designer lo acabo de lograr instalar usando ese link de descarga, tengo la aplicación en mi Mac y todo, la puedo abrir bien inclusive. Eso significa que ya está listo? porque al correr el pip3 install pyqt5-tools me sigue tirando ese error.

Muchas gracias!

**Comment by aaossa** [comment]
Súper 👌 Lo que hace el archivo que descargaste es instalar Qt Designer, no es permitirte instalar `pyqt5-tools`, así que al parecer estás listo 🎉 Para confirmarlo, prueba con uno de los ejemplos de los contenidos y ve si VS Code te abre la ventana (eso sería PyQt5) y abre Qt Designer (eso confirma que Qt Designer está instalado)
