### ISSUE TITLE
Problema con rutas de acceso 

### ISSUE THREAD

**Issue by mariaignaciag** [IIC2233/syllabus#665]
Hola! he estado teniendo problemas con la ruta de las imágenes, ya revisé las issues pero por más que intento arreglarlo, no lo he logrado, resulta que cuando hago el print de os.path.exists(ruta_imagen), efectivamente me sale False, pero he llegado incluso a copiar la ruta de acceso de la imagen y me sigue tirando la ventana vacía, a lo que me refiero es que he puesto casi toda la ruta en el path.join y aun así nada me resulta, me ayudaría mucho si me dijeran que otro problema puede estar sucediendo, me he fijado que Solo me pasa con los archivos jpg y no así en el archivo png como los cuadritos azules y verdes, no creo que tenga algo que ver pero me llamó la atención que tampoco me funciono el de la serpiente, siendo que tenia casi la misma ruta que los cuadritos azules y verdes.  Muchas gracias!!

**Comment by fdoflorenzano** [comment]
Hola @mariaignaciag,

Me resulta difícil sin ver los casos específicos. Si dices que al ejecutar `os.path.exists(ruta_imagen)` te resulta `False`, entonces eso es indicación directa que desde el lugar de ejecución no tiene acceso a la imagen desde esa ruta, y tendría sentido si no aparece en la ventana. Igual me parece raro dado las diferencias de casos que mencionas, los casos que comentas también están en directorios distintos, entonces es difícil de diferenciar.

Algo a tener en cuenta es como/donde estás ejecutando tus programas. Recuerda que usar rutas relativas para archivos, estas son relativas al lugar de ejecución. Si usas un editor de texto para ejecutar con un botón, revisa desde qué directorio se ejecuta. A veces al tener abierto el editor en una carpeta que no es directamente la que contiene tu programa, pasan estas cosas. Puedes agregar la línea `print(os.getcwd())` para que te imprima el lugar el programa al ejecutarse y asegurarte. Si no, indicanos como ejecutas tus programas normalmente.

Estamos atentos/as,
Saludos.

**Comment by mariaignaciag** [comment]
Muchas gracias por responder, lo que pasa es que hace poco (la semana pasada) me cambié a VScode debido a la instalación de PyQt5 ya que mi otro editor se quedaba pegado cuando lo corría, hasta cambie el sistema operativo del Mac y borré muchas cosas para que quedara todo mejor, de hecho está en la issue #644 mi desesperación, así que probablemente sea un problema de como estoy ejecutando VsCode, ya que acabo de agregar la línea print(os.getcwd()) y no me imprime nada 😢, en las dos imágenes que voy a adjuntar dejé todo lo que me ha parecido un poco extraño y que quizás podría estar generando el error, lo intenté dejar lo más claro posible, lamento todas las molestias 😭 pero no he podido ver tutoriales para usarlo correctamente
![im2](https://user-images.githubusercontent.com/62075301/81890562-3d92d780-9574-11ea-9233-834cc416fc15.png)
![im1](https://user-images.githubusercontent.com/62075301/81890565-3ec40480-9574-11ea-88b9-b399ed3436d8.png)

**Comment by fdoflorenzano** [comment]
Hola @mariaignaciag,

No te preocupes, no es molestia. Este tipo de cosas pasan a veces :)

No te imprime nada `print(os.getcwd())` porque está después de `sys.exit(app.exec_())`. Esa línea pausa la ejecución del programa para que espere eventos y solo permite que termine. Mueve
`print(os.getcwd())` a antes de eso. Podría ser entre el `mi.show()` y `sys.exit(app.exec_())`.

Por tus fotos no alcanzo a ver el directorio que tienes abierto en VSCode (la primera pestaña de la barra lateral). ¿Es dónde está "nuevo"? Escribiendo eso noté que no tiene extensión el archivo (no tiene el `.py`). Agrégaselo para que VSCode te lo autodecte como archivo Python. 

Saludos, me avisas como te va.

**Comment by mariaignaciag** [comment]
Gracias!! ahora que lo pude imprimir, claro, me aparece (como adjuntaré en la imagen) que el directorio viene desde mi carpeta del curso, desde los contenidos, semana 09, creo que fue porque primero creé ahí el archivo, y luego lo moví a mi carpeta donde pruebo los códigos semana a semana, pero ni idea como solucionar esto y en esta foto puse la pestaña lateral con todos sus componentes.
![Captura de Pantalla 2020-05-14 a la(s) 00 21 43](https://user-images.githubusercontent.com/62075301/81892571-6d90a980-9579-11ea-9340-4021830baf5e.png)

**Comment by fdoflorenzano** [comment]
Hola @mariaignaciag,

Súper, tiene sentido. VSCode cuando ejecuta un programa, por defecto utiliza el directorio que tiene abierto actualmente como el directorio de ejecución. Entonces esa última ejecución fue de  el archivo `nuevo.py` (que está en otra carperta llamada `progrita` 😄 ), pero se ejecutó desde la carpeta `semana-09` de los contenidos.

¿Qué pasó con `os.path.exists(ruta_imagen)`? ¿Qué imprime ahora? ¿Qué pasa si imprimes la ruta misma? ¿Tiene sentido para el directorio **de ejecución**?

Saludos.
