### ISSUE TITLE
¿estoy haciendo modelamiento circular?

### ISSUE THREAD

**Issue by mjgutierrez1** [IIC2233/Syllabus#666]
Hola,
en la clase BackEnd tengo el metodo run en donde estoy creando a los enemigos en cada iteración del while según lambda_etapa. En el frontend tengo instanciado al backend así: self.backend = Backend(self), por lo que el init del BackEnd recibe un parámetro "parent" que es la interfaz.

Lo que quiero hacer es pasarle parent a cada enemigo, pero para eso en el init de Backend tendría que hacer self.parent = parent, ya que no puedo pasarle parent al método run desde el init, sino que sólo podría obtenerlo como un atributo self.parent de mi Backend. ¿Hacer eso estaría mal?

**Comment by iqacevedo** [comment]
Hola,

Si solo le pasas el parent para setear el parent en los enemigos está bien. Si lo usas para otras cosas se considera como modulación circular.

Saludos !

**Comment by mjgutierrez1** [comment]
Ok, ¡muchas gracias!
