### ISSUE TITLE
AF7: Duda sobre formato de mensajes

### ISSUE THREAD

**Issue by Pabloski100** [IIC2233/syllabus#666]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Dudas del formato de los mensajes

Hola (otra vez jeje), me surgió una duda sobre el formato de los mensajes, del enunciado había entendido que era como:
(5 bytes de tamaño en little endian) + (el mensaje)

Es este el formato? mi duda surge porque me sale un error en consola que dice "ERROR: mensaje de cliente 0 no cumple el formato.", sin embargo, se envían algunos mensajes antes sin causar ese error (también, el error ocurre después de avisar que el mensaje no se pudo decodificar, no se si ocurra por eso)

Damn, la issue 666

**Comment by aaossa** [comment]
El formato que describes es el correcto. No sabría decirte cuál podría ser el error la verdad 🤔 Asegúrate de estar usando el mismo *endianness* en ambos lados de la comunicación y que el largo del mensaje sea el mismo en ambos lados también.

**Comment by VichoAburto** [comment]
Hola!

Me pasa lo mismo, y revisé lo que dijo profe, pero lo tenía bien. Entonces, no sé a qué se debe.

**Comment by Pabloski100** [comment]
No se si ayude, pero seguí el consejo de ver los largos y resulta que en un momento llega un mensaje de largo 0, al menos en mi caso es medio raro, porque tengo un log cada vez que el cliente manda algo, y ese mensaje no lo manda el cliente

**Comment by VichoAburto** [comment]
Mmm, no te caché bien.

Pero lo que si caché es que el error:
```
ERROR: No se pudo decodificar el mensaje
ERROR: mensaje de cliente 0 no cumple el formato.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  [...]
     [...]
ValueError: not enough values to unpack (expected 2, got 0)
```

Se produce en la lógica cuando en la interfaz del cliente cierro la ventana. Ahora, ni idea cómo solucionarlo.🤔🤔

PD: Los ```[...]``` son por el path interno de mi pc y porque también está mi código.

**Comment by kvonstorch** [comment]
Me pasa exactamente lo mismo

**Comment by aaossa** [comment]
@VichoAburto , ¿podrías subir tu código a tu repositorio para ver qué podría ser? Avísame cuando lo hagas, ¡gracias 🙌 !

**Comment by VichoAburto** [comment]
Hola @aaossa !

Ya tengo subido el código 😉.

**Comment by aaossa** [comment]
@VichoAburto , creo que es justo lo que mencionaba @Pabloski100 . En el servidor imprime el largo de los mensajes recibidos. En algunos sistemas operativos, al cerrarse una conexión, se envía un *string* vacío. Tienes que manejar ese caso de manera independiente (basta con un `if`). Avísame si es eso

**Comment by VichoAburto** [comment]
Profe, no entendí muy bien a qué parte se está refiriendo. Porque cuando recibo el mensaje, la única forma de que este pase a ```self.logica.manejar_mensaje(...)``` es si pasó por el ```if``` que ya tengo, el cual solo deja pasar mensajes distintos a strings vacíos.

**Comment by aaossa** [comment]
Estoy casi seguro de que lo que te falta es lo que aparece en la **footnote* del enunciado 😅 Por como lo tienes ahora, no se sale del *loop* cuando un cliente se desconecta

**Comment by VichoAburto** [comment]
La verdad es que no comprendí bien ese _footnote_, debo hacer como un levantamiento dentro de otro levantamiento? Porque lo otro que se me ocurrió, es lo que acabo de cambiar (y subir) a esa misma parte. 

PD: Lo dejé comentado para que no vaya a afectar el código si es que no se me ocurre que hacer.

**Comment by aaossa** [comment]
Lo que debes hacer es levantar la excepción cuando identifiques que recibiste un *string* vacío, eso es lo que dice la *footnote*

**Comment by VichoAburto** [comment]
🤔🤔
Pero eso no es lo que ya tenía? No cachooo 😓😓

Porque según entiendo del enunciado, cuando el cliente se desconecte, se levatará el error ```ConnectionResetError```, el método recibir recibirá un string vacío, y después, según mi código, saldrá del loop, y se capturará la excepción.

O eso creo que estoy haciendo y realidad lo estoy implementando mal?

**Comment by aaossa** [comment]
En tu código no hay `raise`, tienes que levantar la excepción manualmente

**Comment by VichoAburto** [comment]
Mmm, pero esa función no corta el código de raíz? Por eso mismo supuse que no era esa la que había que usar.

**Comment by aaossa** [comment]
Mira, considero que ya respondí muy detalladamente tu pregunta inicial así que no voy a seguir dando más detalle de la implementación esperada 😅 Revisa bien lo que implementaste y lo que pide el enunciado

**Comment by VichoAburto** [comment]
Jajjaja, yaya, gracias igual profe. Voy a cachar bien.
