### ISSUE TITLE
Dudas de los layouts

### ISSUE THREAD

**Issue by 18638333** [IIC2233/syllabus#666]
Hola, cuando ocupo layouts, importa si es que los widgets los agregos al layout horizontal y después agrego el layout horizontal al vertical, o lo hago de manera inversa (creo primero el layout vertical, y después lo uno al layout horizontal)?

**Comment by fdoflorenzano** [comment]
Hola @18638333,

La diferencia que noto es la orientación de los elementos dentro de los *layouts*. Si los pones en el horizontal, seguirán orientación horizontal, y lo contrario con vertical. Es válido componer *layouts* entre ellos, si esa es tu pregunta. Así aseguras espaciado en ambas direcciones.

No estoy seguro si respondí tu duda, intenta aclarar tu pregunta si no.

Saludos.
