### ISSUE TITLE
Problemas con pyqt5 en mac os

### ISSUE THREAD

**Issue by cnillanes** [IIC2233/syllabus#666]
Hola! pude instalar pyqt5 con el comando pip3 install pyqt5 y lo de los tools falló tal cual lo explicaban en la wiki del curso asi que instalé QtDesigner (y no he echo nada con esto) 
El problema que tengo es que al intentar importar PyQt5 en VSCode me arrojá un error porque no reconoce que exista, pese a que si lo escribo en la terminal dice que ya existe. (Adjunto fotos)
Espero puedan ayudarme, gracias desde ya! :D 
![Captura de Pantalla 2020-10-10 a la(s) 15 30 39](https://user-images.githubusercontent.com/41082653/95662629-ae7ff080-0b0e-11eb-85a1-903e7e39ae3f.png)
![Captura de Pantalla 2020-10-10 a la(s) 15 30 56](https://user-images.githubusercontent.com/41082653/95662634-b6d82b80-0b0e-11eb-8e1f-148f68460c48.png)

**Comment by cnillanes** [comment]
Encontré la causa del fallo pero no se arreglarlo, asi que lo dejo igual por si ustedes saben ya que me pasó lo mismo en la Tarea 1 al no poder importar el beautifultable

Mi computador por defecto deja guardada la version 3.8 de python y por lo tanto, todo lo que instalo se guarda ahí pese a que yo descargué la versión 3.7 de python. En VSCode yo programo en la version 3.7 de python como nos sugirieron a principio del curso y por eso cuando importo PyQt5 no lo reconoce, pero si lo cambio a 3.8 si me permite importarlo.

Qué tan terrible es que programe en python 3.8 para esta tarea? cambian los comandos o algo así?
Quedo atenta!

**Comment by aaossa** [comment]
Hola, @cnillanes, por favor no borres el texto de la plantilla, sino no tenemos cómo saber que hiciste lo que se pide (por algo la armamos y les pedimos que no la borren 😅).

Que bueno que identificaste la causa del fallo, buen análisis 👌 Una forma de instalar librerías directamente en la versión de Python que quieres es especificar la versión de python directamente en el comando. A lo que me refiero es, en lugar de usar `pip3 install X` utilices **`python37 -m pip install X`**, de esta manera accedes primero a la versión de Python y luego al módulo que quieres usar (`pip`).

En cuanto a tu segunda pregunta, diría que **lo ideal es usar la versión pedida en el curso**, pero en general no es tan terrible utilizar una versión distinta, siempre que sea cercana a la oficial usada en el curso (3.7.*, o sea, cualquiera de Python 3.7). Les ayudantes utilizarán Python 3.7 para corregir, por lo que si utilizas algo que existe en Python 3.8 o que en esa versión funciona distinto les ayudantes verán un resultado distinto al tuyo. De todas maneras, es mejor irse a la segura y utilizar la versión del curso, aunque si no puedes/quieres es mejor que intentes tener ojo con no utilizar algo que solo existe en Python 3.8 (miré y al parecer son cosas chicas, pero nunca se sabe)

**Comment by cnillanes** [comment]
> Hola, @cnillanes, por favor no borres el texto de la plantilla, sino no tenemos cómo saber que hiciste lo que se pide (por algo la armamos y les pedimos que no la borren 😅).
> 
> Que bueno que identificaste la causa del fallo, buen análisis 👌 Una forma de instalar librerías directamente en la versión de Python que quieres es especificar la versión de python directamente en el comando. A lo que me refiero es, en lugar de usar `pip3 install X` utilices **`python37 -m pip install X`**, de esta manera accedes primero a la versión de Python y luego al módulo que quieres usar (`pip`).
> 
> En cuanto a tu segunda pregunta, diría que **lo ideal es usar la versión pedida en el curso**, pero en general no es tan terrible utilizar una versión distinta, siempre que sea cercana a la oficial usada en el curso (3.7.*, o sea, cualquiera de Python 3.7). Les ayudantes utilizarán Python 3.7 para corregir, por lo que si utilizas algo que existe en Python 3.8 o que en esa versión funciona distinto les ayudantes verán un resultado distinto al tuyo. De todas maneras, es mejor irse a la segura y utilizar la versión del curso, aunque si no puedes/quieres es mejor que intentes tener ojo con no utilizar algo que solo existe en Python 3.8 (miré y al parecer son cosas chicas, pero nunca se sabe)

Gracias por la respuesta :D
Utilicé el comando indicado pero arroja lo siguiente "**zsh: command not found: python37**" así que aún no logro instalarlo en la versión sugerida :(

Lo otro, existe algún manual donde pueda encontrar que cosas se implementan distintos en python 3.8 para ir fijándome en caso de tener que programar mi T02 en esa versión?

**Comment by aaossa** [comment]
Hola @cnillanes la verdad no estoy seguro de cómo arreglar lo del comando. Si instalaste Python 3.7 debería ser accesible de alguna manera, ¿quizás instalaste Python 3.8 después de Python 3.7 por lo que se sobrescribieron los comandos? En una de esas instalando nuevamente Python 3.7 se soluciona, pero la verdad no estoy seguro. No recuerdo si probaste, pero dado que desde VS Code puedes acceder a Python 3.7, quizás puedas usar `pip install` desde ahí.

La lista de cambios introducidos en Python 3.8 se puede ver [en la documentación oficial de Python](https://docs.python.org/3.8/whatsnew/3.8.html). Al parecer no hay cambios mayores o que afecten los contenidos vistos, así que en una de esas puedes programar sin problemas, pero como siempre hay una pequeña posibilidad de que haya algún cambio pequeño que afecte un resultado es que preferimos definir una versión dentro del curso.

Ojalá puedas cambiar a la versión de Python 3.7, pero si no puedes dale con 3.8 y esperemos que no haya un cambio pequeño por ahí que te cause problemas ✨

**Comment by cnillanes** [comment]
Al final pobré todas las opciones y no lo logré asi que le daré con 3.8 nomas pero gracias!
