### ISSUE TITLE
Duda comando get

### ISSUE THREAD

**Issue by frvalenzuela** [IIC2233/Syllabus#666]
"El bot debe enviar un mensaje con la issue correspondiente" 

A que se refiere con mensaje? Un comentario ? No sería lo mismo que post? 

Podría ver un ejemplo del comando get y como se diferencia con post ?

**Comment by hanavarrete** [comment]
Con el get debes recibir en telegram el número de la issue especificada. En cambio, con el post debes escribir la respuesta que se está entregando como argumento en la issue en github. Espero que haya quedado más claro! Saludos

**Comment by frvalenzuela** [comment]
Entonces sería:
/get 1 
Bot_respuesta: 1
/post 1 hola
(Bot postear una respuesta como hola)

No sería el comando get redundante ? O se necesita primero hacer get para luego hacer post ?

**Comment by stephichau** [comment]
@frvalenzuela  fijate en la sección 4.3.2;
En el chat:
```/get #1 ```
Respuesta:
```
[ < autor_issue > ]
[ #1 - < título > ]
< texto >
[ Link: < link > ]
```

**Comment by frvalenzuela** [comment]
@stephichau pero ese formato de notificaciones no es solamente para cuando se publica una issue en algún respositorio ? O es en ambos casos ?

**Comment by stephichau** [comment]
también se incluye en este caso :)

**Comment by frvalenzuela** [comment]
Ah entonces es para los dos casos, muchas gracias !!
