### ISSUE TITLE
Invalid_tree.json

### ISSUE THREAD

**Issue by miortiz1** [IIC2233/syllabus#666]
Hola! Cual es el error del invalid_tree.json? No lo logré ver

**Comment by Hernan4444** [comment]
Es el error generado cuando el json entregado no está modelando un AlgarroboTree, al inicio se explican las reglas que debe seguir un árbol para ser llamado AlgarroboTree, si no las cumple se genera esta excepción.

**Comment by miortiz1** [comment]
Me referia a como el test que se llama así. Estaba tratando de armalo dibujandolo y me quedo algo así:
                             4
                         /       \
                      7           12
                 /       \        /       \
            10         11    15         19
           /
       16
Y como no tiene nada a la derecha de un none y nada es menor que su parent no se por que es invalido o si o arme mal

**Comment by miortiz1** [comment]
Me referia a como el test que se llama así. Estaba tratando de armalo dibujandolo y me quedo algo así:
-------------4
-----------/ --- \
---------7--------12
-------/--- \---- -/ --\
-----10--- 11 --15-- 19
-----/
---16
Y como no tiene nada a la derecha de un none y nada es menor que su parent no se por que es invalido o si o arme mal

**Comment by miortiz1** [comment]
Me referia a como el test que se llama así. Estaba tratando de armalo dibujandolo y me quedo algo así:
-------------4
-----------/ --- \
---------7--------12
-------/---\ ---- -/ --\
-----10--- 11 --15-- 19
-----/
---16
Y como no tiene nada a la derecha de un none y nada es menor que su parent no se por que es invalido o si o arme mal

**Comment by Hernan4444** [comment]
Revisa la issue #648  ahí se define que ese 16 debía ser un 1 para que esté invalido.

Saludos ✌️

**Comment by miortiz1** [comment]
muchas gracias!
