### ISSUE TITLE
Uso de "&" en los nombres de QLabels o QPushButton

### ISSUE THREAD

**Issue by CatalinaGoldsack** [IIC2233/syllabus#667]
Hola!  como sale en los contenidos:
El uso del caracter & al inicio del texto de algún botón o menú permite que la primera letra del mensaje mostrado esté destacada. La visualización depende de la plataforma utilizada.
En mi caso esto no funciona, ¿esto se debe a mac o visual estudio? ¿
<img width="872" alt="Captura de Pantalla 2020-05-14 a la(s) 01 52 36" src="https://user-images.githubusercontent.com/62029175/81898095-fad9fb00-9585-11ea-8a0a-06752ee8d05e.png">
¿Cómo se debería ver?
Gracias :)

**Comment by igbasly** [comment]
Hola @CatalinaGoldsack :smile:

Esta es una funcionalidad un tanto rebuscada, pero útil de PyQt, dirigida principalmente a Windows. El uso de ampersand (&) por defecto hace que sea posible utilizar la primera letra junto al símbolo como una "llave" (*key*) para un atajo de teclado en referencia a ese elemento. En el caso de Windows viene por defecto en los elementos de la interfaz (principalmente *Label* y *Button*) una propiedad llamada mnemotécnica que permite automáticamente definir el atajo `ALT + key`, donde `key` es el prefijo que te había mencionado, en este caso, la primera letra junto a ampersand.

Este atajo permite llevar el foco de la ventana al elemento en cuestión, y en el caso del botón además presionarlo. Esto puede ser útil cuando a los *Label* se les asigna una campo de texto asociado mediante el método `setBuddy`, lo cual permite definir que ese *Label* corresponde un determinado *LineEdit* (como en un formulario). De esta forma uno puede aprovechar este atajo de teclado para moverse entre los campos.

Un ejemplo de la implementación de esto, sería una ventana `Window` con los elementos `Label`, `LineEdit` y `Button`.
```python
class Window(QWidget):

    def __init__(self):
        super().__init__()

        self.nombre = QLineEdit()
        label_nombre = QLabel("&Nombre")
        label_nombre.setBuddy(self.nombre)

        self.telefono = QLineEdit()
        label_telefono = QLabel("&Telefono")
        label_telefono.setBuddy(self.telefono)
        
        button = QPushButton("&Presionar")
```
La cuál luciría de la siguiente forma:

![Captura](https://user-images.githubusercontent.com/42249038/82009675-f7a24600-963d-11ea-91a6-18d7c34b9531.PNG)

Si te fijas, window destaca las primeras letras precisamente por lo que te menciono.
Por lo tanto, te puedes mover entre los campos de texto con los atajos `ALT + N` y `ALT + T`, como presionar el botón con `ALT + P`.

Si bien, esto es automático en Windows, en MacOS se puede habilitar estas extensiones importando la función `qt_set_sequence_auto_mnemonic` desde `QtGui`, la cual recibe un `boolean` para establecer estas propiedades. Esto lo puedes hacer en la sección donde se ejecute tu programa y se establezca el `QApplication`.

```python
from PyQt5.QtGui import qt_set_sequence_auto_mnemonic


qt_set_sequence_auto_mnemonic(True)
```

Espero que esto aclare el funcionamiento de esta propiedad y no dudes en preguntarnos en cualquier otro caso.
Saludos  :v:.
