### ISSUE TITLE
Duda ejemplo final ayudantia 11

### ISSUE THREAD

**Issue by maurobsp** [IIC2233/syllabus#667]
* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido
Hola revisando la ayudantía 11, quede con dudas respecto al método _escuchar_clientes()_ de la clase Servidor.
``` python
    def escuchar_cliente(self, socket_cliente):
        try:
            while True:
                # Recibir y manejar mensajes del cliente
                mensaje = self.recibir(socket_cliente)
                print("Mensaje recibido: ", mensaje)
                if mensaje != "":
                    respuesta = self.manejar_mensaje_recibido(mensaje, socket_cliente)
                    self.enviar(respuesta, socket_cliente)
        except ConnectionResetError:
            print("Error de conexión con el cliente")
```
específicamente en la linea.
``` python
                if mensaje != "":

```
debido a que mensaje el cual viene por el método _recibir()_ el cual viene de __decodificar_mensaje()__  solo puede ser un diccionario (mensaje -> recibir() -> decodificar_mensaje()). entonces no entiendo por que se intenta que no pueda ser un string vacio.
``` python
    def recibir(self, socket_cliente):
        # Recibir largo del mensaje
        largo_bytes_mensaje = socket_cliente.recv(4)
        # Decodificar largo del mensaje
        largo_mensaje = int.from_bytes(largo_bytes_mensaje, byteorder="big")
        # Recibir mensaje
        bytes_mensaje = bytearray()
        while len(bytes_mensaje) < largo_mensaje:
            bytes_a_recibir = min(4096, largo_mensaje - len(bytes_mensaje))
            bytes_mensaje += socket_cliente.recv(bytes_a_recibir)
        # Decodificar mensaje
        mensaje = self.decodificar_mensaje(bytes_mensaje)
        return mensaje

    def decodificar_mensaje(self, bytes_mensaje):
        try:
            # Deserializar el mensaje
            mensaje = json.loads(bytes_mensaje)
            return mensaje
        except json.JSONDecodeError:
            print("No se pudo decodificar el mensaje")
            return dict()
```
mensaje o es un json.load() el cual retorna un dict() o un dict(), eso es lo que entiendo con la lectura del código, me gustaría me aclaren si mensaje puede ser un string.

**Comment by tqmbanados** [comment]
Hola! Efectivamente, el método ```recibir``` debería retornar un objeto json, y nunca un string vacío. La línea ```if mensaje != "":``` debería reemplazarse por ```if mensaje != {}```. Se nos pasó porque inicialmente, los mensajes enviados serían ```str``` y no objetos json. ¡Gracias por notarlo!
