### ISSUE TITLE
.gitignore T05

### ISSUE THREAD

**Issue by depstein26** [IIC2233/Syllabus#667]
Hola! No entiendo bien por qué uno de los objetivos es el uso de gitignore, sería para los assets que se entregan? Porque en general todo deberíamos subirlo (interfaz, sprites, etc).

Gracias!

**Comment by FernandoPieressa** [comment]
Efectivamente, es para los assets que entregamos.

Saludos!

**Comment by depstein26** [comment]
Gracias! Y como se van a entregar? Para darle el path a mi programa

**Comment by rihanuch** [comment]
Me entro una duda, si el gitignore es para los assets que nos fueron entregados que pasaria entonces si estos sprites son los que usamos en nuestro programa? Especificamos la ruta en el readme y no los subimos, los subimos igual u otra opcion?

Gracias!

**Comment by iqacevedo** [comment]
Justamente, especifica donde deberían estar, de ese modo cuando te corrijamos podemos poner esos sprites en esa misma ruta. No debes subirlos.

Saludos !
