### ISSUE TITLE
Seteo y funcionamiento de Webhook Telegram

### ISSUE THREAD

**Issue by benjamimo1** [IIC2233/Syllabus#667]
Hola! Ya creé mi Bot y quiero setear su webhook por lo que me pide una url. Esta url es:
a) 200.73.239.249 (la publica)
b) http://127.0.0.1:8080 (local+puerto)
c) otra cosa ?
mas  " /telegram/input" (que defini como el subdirectorio receptor).
Hasta ahora ejecuto el server en el 8080, pero no recibe las PUTS del webhook, por lo que creo el url es el problema

**Comment by nivek0o0** [comment]
Hola, creo entender del enunciado que corresponde a la url que te entrega heroku para tu aplicación.

**Comment by benjamimo1** [comment]
@nivek0o0 Eso caché! Gracias man
