### ISSUE TITLE
Duda con elementos gráficos básicos

### ISSUE THREAD

**Issue by cnillanes** [IIC2233/syllabus#667]
Holaa! Estaba probando el material en vscode y me surgieron dos dudas respecto a este jupyter notebook
La primera es respecto al ejemplo de etiquetas y cuadros de texto: En qué parte del código le estoy diciendo que ponga el cuadro al lado de "Texto: ". Porque fui probando varias cosas y entiendo que esta parte crea el cuadro con esas dimensiones 
![Captura de Pantalla 2020-10-10 a la(s) 17 56 51](https://user-images.githubusercontent.com/41082653/95664905-f6f4d980-0b21-11eb-80d6-2c9eebc29f5a.png)
pero no entiendo porque "Texto:" aparece en la ventana con un espacio para un input y "Esta etiqueta es variable" no, cuando estan definidas del mismo modo ( o al menos yo no estoy notando la diferencia :c )
![Captura de Pantalla 2020-10-10 a la(s) 17 58 36](https://user-images.githubusercontent.com/41082653/95664932-34596700-0b22-11eb-85da-638ed9f18e91.png)

La segunda duda es con respecto a la imágenes puesto que copié el código exacto y se abre la ventana pero sin ninguna imagen. Probé descargando tambien la imagen del link y tampoco logro visualizar la imagen, solo la ventana sin nada cargado. Debo cambiar algo de la ruta_imagen o por qué no lo estoy logrando?
 
Gracias desde ya :D

**Comment by aaossa** [comment]
Hola @cnillanes , buena pregunta 👌 Intentaré responder ambas dudas:

1. ¿Dónde estamos diciéndole a cada *widget* dónde ubicarse? La respuesta está en el método `move`, ya que con eso le dices explícitamente dónde ubicarse utilizando el sistema coordenado explicado en el mismo cuaderno. `self.label1` está ubicado en `(10, 15)` y `self.label2` está en `(10, 50)`, o sea, ambos están en el mismo "x", lo que puedes confirmar cambiando el valor para uno de los dos `QLabel`s. Por otra parte, `self.edit` se ubica con `self.setGeometry` en `(45, 15, 100, 20)`, o sea, en `(45, 15)` se ubica un *widget* de tamaño `(100, 20)`, por lo que queda en el mismo "y" que `self.label1`. Si quisieras que `self.edit` quedara al lado de `self.label2`, solo tienes que cambiar su "y" a 50 en lugar de 15, llamando a `self.setGeometry` con `(45, 50, 100, 20)`, quedando algo así:

![imagen](https://user-images.githubusercontent.com/10425834/95666037-3aecdc00-0b2c-11eb-99ca-78ebb98f9dd0.png)

2. Lo que ocurre con las imágenes es que deben estar en una ruta accesible para tu programa. Por ejemplo, si quieres mostrar la imagen `foto.jpg` que está en la carpeta `img/` al lado de tu `ejemplo.py`, algo así:

```
|- ejemplo.py
|- img/
    |--- foto.jpg
```

Entonces en `ejemplo.py` tendrás que usar la ruta `img/foto.jpg` (haciéndolo correctamente sería `os.path.join("img", "foto.jpg")`.  Lo que te recomendaría es ver desde dónde estás ejecutando el código (si lo estás haciendo desde una consola, esto es dónde estás actualmente, lo que puedes ver con el comando `pwd` en mac/Ubuntu o con el comando `cd` en Windows) y utilizar en `ruta_imagen` la ruta desde esa carpeta hasta el archivo, de forma que tu código pueda encontrarla.

Si algo no queda dado o no te funciona, vuelve a preguntar por acá no más ✨ Éxito!

**Comment by cnillanes** [comment]
> Hola @cnillanes , buena pregunta 👌 Intentaré responder ambas dudas:
> 
> 1. ¿Dónde estamos diciéndole a cada _widget_ dónde ubicarse? La respuesta está en el método `move`, ya que con eso le dices explícitamente dónde ubicarse utilizando el sistema coordenado explicado en el mismo cuaderno. `self.label1` está ubicado en `(10, 15)` y `self.label2` está en `(10, 50)`, o sea, ambos están en el mismo "x", lo que puedes confirmar cambiando el valor para uno de los dos `QLabel`s. Por otra parte, `self.edit` se ubica con `self.setGeometry` en `(45, 15, 100, 20)`, o sea, en `(45, 15)` se ubica un _widget_ de tamaño `(100, 20)`, por lo que queda en el mismo "y" que `self.label1`. Si quisieras que `self.edit` quedara al lado de `self.label2`, solo tienes que cambiar su "y" a 50 en lugar de 15, llamando a `self.setGeometry` con `(45, 50, 100, 20)`, quedando algo así:
> 
> ![imagen](https://user-images.githubusercontent.com/10425834/95666037-3aecdc00-0b2c-11eb-99ca-78ebb98f9dd0.png)
> 
> 1. Lo que ocurre con las imágenes es que deben estar en una ruta accesible para tu programa. Por ejemplo, si quieres mostrar la imagen `foto.jpg` que está en la carpeta `img/` al lado de tu `ejemplo.py`, algo así:
> 
> ```
> |- ejemplo.py
> |- img/
>     |--- foto.jpg
> ```
> 
> Entonces en `ejemplo.py` tendrás que usar la ruta `img/foto.jpg` (haciéndolo correctamente sería `os.path.join("img", "foto.jpg")`. Lo que te recomendaría es ver desde dónde estás ejecutando el código (si lo estás haciendo desde una consola, esto es dónde estás actualmente, lo que puedes ver con el comando `pwd` en mac/Ubuntu o con el comando `cd` en Windows) y utilizar en `ruta_imagen` la ruta desde esa carpeta hasta el archivo, de forma que tu código pueda encontrarla.
> 
> Si algo no queda dado o no te funciona, vuelve a preguntar por acá no más ✨ Éxito!

Holaa :D
Entendí perfecto la primera respuesta, sin embargo, sigo con problemas respecto a los de las imágenes :/
Según veo tengo que si o si tener la imagen descargada y en lo posible guardada en una carpeta que además de contener el archivo .jpg deberia tener ademas el archivo.py en el cual estoy ejecutando el código y una vez resuelto eso uso path para darle la ruta y que cargue la imagen?
En este momento (que no está funcionando) tengo tanto la imagen (que le puse python.jpg) en Escritorio como el archivo ejemplo.py donde pegué el codigo del cuadernillo de contenidos pero no me muestra ninguna imagen al correrlo.. debería agruparlos en una carpeta que se llame img?

**Comment by aaossa** [comment]
Hola @cnillanes ,

Las imágenes deben estar sí o sí en tu computador ppara que tu programa pueda llegar a ellas utilizando este método. Lo más importante es que tu programa pueda llegar a las imágenes al usar `ruta_imagen`. Por ejemplo, si tienes la imagen y el código en el Escritorio, `ruta_imagen` sería `python.jpg`. Si eso te parece que está bien, ¿cómo estás ejecutando el código? Si estás usando VS Code debes moverte usando la consola hasta la carpeta donde tienes tu archivo *.py y ahí correr el código. Cuéntame si te funciona o si ya pudiste solucionarlo 👌

**Comment by cnillanes** [comment]
Gracias! si me resultó :D
