### ISSUE TITLE
Aumento tamaño texto

### ISSUE THREAD

**Issue by clementeross** [IIC2233/Syllabus#667]
Hola! ¿Cómo aumento el tamaño del texto de un QLabel?

**Comment by jfbahamondes** [comment]
Self.objetolabel.setFont(objeto QFont). Al objeto QFont que le entregues debes definirle el tamaño, si no me equivoco con el método setPointSize(un tamaño), antes de entregárselo al setFont().

Puedes googlear más o menos los comandos que te mencioné y puede que encuentres ejemplos.

Hazme saber si te funciona, saludos!

**Comment by clementeross** [comment]
@jfbahamondes me sirvió! Muchas gracias!

**Comment by jfbahamondes** [comment]
Perfecto 😄 ! De nada!
