### ISSUE TITLE
Acualizar heroku

### ISSUE THREAD

**Issue by chuma9615** [IIC2233/Syllabus#668]
Hola!. mi duda es, como puedo actualizar la app de heroku con los cambios que le vamos haciendo a nuestro server?

**Comment by nivek0o0** [comment]
Hola, yo creo que pushando a Heroku o no?

**Comment by MainScientist** [comment]
Haciendo push a heroku nuevamente con el comando `git subtree ...`

**Comment by chuma9615** [comment]
asi lo hice, el problema es que mi app no responde a ningun request que hago

**Comment by chuma9615** [comment]
Quiza puede ser porque me dice esto :  Warning: Your application is missing a Procfile. This file tells Heroku how to run your application.

Lo raro es que si tengo un Procfile creado, no se por que no me lo lee

**Comment by chuma9615** [comment]
Ahi me lo leyó!, pero igual la pagina no corre y me sale un error

**Comment by MainScientist** [comment]
¿Cuál sería ese error?

**Comment by chuma9615** [comment]
al ver el log de mi app mediante el comando `heroku logs ` me sale lo siguente 

![captura de pantalla 2017-06-23 a la s 16 14 03](https://user-images.githubusercontent.com/26102376/27498816-d14adbac-582e-11e7-9787-59f2e7aac98c.png)

**Comment by nivek0o0** [comment]
FLASK_APP debe ir separado por un espacio del nombre de la aplicación. Está mal el enunciado.

**Comment by chuma9615** [comment]
Buenisimo, ahi se subio!
