### ISSUE TITLE
Función balenceo

### ISSUE THREAD

**Issue by Jbijit** [IIC2233/syllabus#668]
Hola, es necesario utilizar la función balanceo o puedo hacer el balanceo en la función insertar nomas? y que tan factible es que pase todos los tests subidos y que me falle a la hora de que lo prueben con sus tests?

**Comment by Hernan4444** [comment]
Hola,
Deben utilizar la función balance, porque cuando se haga el testeo del árbol se esperará ejecutar ese método. Pero no hay problema que dentro del insert hagas un llamada a balance altiro, pero deben ser 2 métodos distintos.
