### ISSUE TITLE
AF7: lista de manejar_mensaje

### ISSUE THREAD

**Issue by FVivess** [IIC2233/syllabus#668]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido
Hola estaba probando el código de la actividad y al utilizar el método manejar_mensaje de la clase Logica, me pasa que la lista que devuelve solo contiene un elemento, y no el segundo como lo indica el enunciado (que sería el id del cliente objetivo de la respuesta). Por esta razón, al intentar enviarle el mensaje a ese cliente el programa me tira error. ¿Qué puedo hacer si no me entrega el id del destinatario? Entiendo que ninguna parte de mi código pudo afectar el funcionamiento de manejar_mensaje.

**Comment by aaossa** [comment]
Hola @FVivess , el método `manejar_mensaje` siempre retorna dos valores. El primero es la respuesta y el segundo es una lista. ¿A qué lista te refieres? El código entregado está bien, así que revisa que estés utilizando sus valores correctamente.

https://github.com/IIC2233/syllabus/blob/7c69b44da8ad6c2fb35a39cb78929d36243ce48e/Actividades/AF7/servidor/logica.py#L199

**Comment by FVivess** [comment]
Haciendo print del segundo valor que retorna manejar_mensaje, este me devuelve una lista con solo un valor (a diferencia de los 2 valores esperados).

**Comment by aaossa** [comment]
¿Por qué dices que son dos valores esperados? Si es solo uno, ese es el único destinatario 🤔

**Comment by FVivess** [comment]
El enunciado dice "Retorna una respuesta y una lista con ids: donde el primer elemento es el id del cliente que envió el mensaje, y el segundo es el id del cliente objetivo de la respuesta". Quizá estoy entendiendo algo mal.

**Comment by aaossa** [comment]
Toda la razón, debería decir algo como: "Retorna una respuesta y una lista con ids: **donde el primer elemento es el mensaje a enviar**, y el segundo es **una lista de ids de clientes objetivo de la respuesta**". Lo importante es que el código está bien 😅 Tal como dicen los nombres de variables, el primer valor es la respuesta y el segundo los destinatarios

**Comment by FVivess** [comment]
Ok, para estar 100% seguro, ¿hay que enviarle el mensaje (que es el primer elemento retornado de manejar_mensaje) a todos los que aparecen en la lista (segundo elemento de manejar_mensaje)?

**Comment by aaossa** [comment]
Sip
