### ISSUE TITLE
[Ejercicio propuesto 2.2] Problemas con agregar imagenes

### ISSUE THREAD

**Issue by aayale** [IIC2233/syllabus#668]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda
Hola, en los contenidos de la semana 09 enseñan como agregar imágenes a una ventana de PyQt y mi problema es que no lo logro. Escribo todo tal cual está ahí escrito en los contenidos y no me sale la imagen, lo intente hacer también como indica en ejercicio propuesto 2.2 y tampoco me sale. No se cual podría ser el por qué no me aparece la imagen. 

Este es mi código en la parte de la imagen:
self.label = QLabel(self)
self.label.setGeometry(50, 50, 50, 50)
ruta_imagen = os.path.join('Pictures', 'ig.jpg')
pixeles = QPixmap(ruta_imagen)
self.label.setPixmap(pixeles)
self.label.setScaledContents(True)

Aquí una foto de lo que me sale al correr el codigo:
![image](https://user-images.githubusercontent.com/69651451/95665913-eeed6780-0b2a-11eb-8e71-16865e6e8074.png)

**Comment by aaossa** [comment]
Hola @aayale , lo que parece que ocurre es que tu programa (tu `archivo.py`) no encuentra la imagen en la ruta que le diste. Te recomendaría revisar que estás corriendo el archivo "al lado" de la carpeta `Pictures` (ya que la ruta indica que tiene que ingresar a esa carpeta a tomar la imagen `ig.jpg`). Explico esto un poquito más en la segunda parte de mi respuesta en #667 , pero si sigue sin funcionarte o quedas con otra duda, pregunta por acá no más 👌 ¡Éxito con los ejercicios!

**Comment by aayale** [comment]
Muchas gracias! Efectivamente cambie de lugar mi foto y funcionó perfecto
