### ISSUE TITLE
podemos aumentar el limite de 80 caracteres por linea en PEP8?

### ISSUE THREAD

**Issue by Calomi** [IIC2233/Syllabus#668]
eso,
me pasó q me bajaron por eso en una tarea y me di cuenta que pycharm corregía por default el pep8 con un limite de 120 y no 80, my bad por no fijarme en eso 😢 
pero ahora que puse el limite a 80, lo encuentro muy estrecho, y me corta varias lineas así, entonces quería ver si podríamos aumentar el limite a 100 conciderando que PEP8 dice:

> Some teams strongly prefer a longer line length. For code maintained exclusively or primarily by a team that can reach agreement on this issue, it is okay to increase the nominal line length from 80 to 100 characters (...)
[https://www.python.org/dev/peps/pep-0008/#maximum-line-length](url)

ya que encuentro que algunas cosas son más comprensibles que estén en la misma linea además de la comodidad de tener más espacio
¿que opinan los ayudantes 😮 ?

**Comment by ciquezada** [comment]
También estoy de acuerdo :pray:

**Comment by jmwielandt** [comment]
Me sumo a la petición.

**Comment by Hernan4444** [comment]
Hola, para esta tarea las reglas de PEP8 se mantienen tal como están siempre, 80 caracteres (en realidad 79). Pero se va a evaluar el cambio para la tarea 6.

Saludos  ✌️

**Comment by Calomi** [comment]
oka!
una duda: ¿que tan estrictos/flexibles son con esto al momento de evaluarlo?
por ejemplo en algunas lineas, después de que pycharm me la arregla automáticamente, me queda un ")" o uno o dos caracteres más allá de la linea (y ahí tengo q arreglarlo manualmente), o en un comentario me paso por 2 o 5 caracteres incluso 10, pues trato de que los comentarios sean de una sola linea ya que creo q se ve mejor con menos lineas de comentario
