### ISSUE TITLE
Abrir GUI desde archivo en vez de IDE

### ISSUE THREAD

**Issue by tqmbanados** [IIC2233/syllabus#669]
### Prerrequisitos

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

He copiado el código directamente de ```2-elementos-gráficos-básicos``` en la carpeta de contenidos de la semana 09. Cuando ejecuto el archivo desde mi IDE, este funciona sin ningún problema, sin embargo, si lo ejecuto desde el explorador de Windows, parece abrirse una ventana para luego cerrarse inmediatamente. **¿Por qué ocurre esto, y cómo puedo solucionarlo?**

**Comment by aaossa** [comment]
Hola @tqmbanados , lo primero que se me ocurre es que es posible que cuando estás haciendo "doble clic" el archivo se ejecuta con una versión de Python distinta a la que estás usando en tu IDE, por ejemplo con una donde no tienes PyQt5 instalado, así que causa una excepción y se cierra de inmediato. Te recomendaría verificar qué versión de Python se ejecuta al abrir tus archivos con "doble clic", por ejemplo, con este programa:

```python
import sys


# Imprimimos la versión de Python
print(sys.version)
# Esperamos input para no cerrar la ventana
input()
```

Si no estás ocupando la misma versión, tienes que cambiar la versión por defecto con la que se abren los archivos de extensión *.py (clic derecho, "Abrir con", "Elegir otra aplicación" y marcar "Siempre ocupar esta aplicación").

**Importante:** De todas maneras, no es recomendable abrir los programas de esa manera a no ser que confíes en ellos, ya que si lo abres así se podría ejecutar código inesperado y además sin tener *feedback* sobre cuál fue la excepción o si hubo alguna 😅

**Comment by tqmbanados** [comment]
gracias! efectivamente tiene que ver con esto.
