### ISSUE TITLE
Duda notificación de creación de issues

### ISSUE THREAD

**Issue by frvalenzuela** [IIC2233/Syllabus#669]
¿ Podemos suponer que el envío automático de la creación de una nueva issue en el repositorio se hará una vez que el usuario haya hablado primeramente con el bot ?

**Comment by hanavarrete** [comment]
Si, debido a que de otro modo el bot no podría enviarle mensajes. Telegram funciona de esta manera debido a que así evita bot que hagan spam 😁

**Comment by frvalenzuela** [comment]
Ya y debemos guardar todos los usuarios que le han hablado al bot y enviar la notificación a todos los chat que se le ha hablado al bot o solo al último ?

**Comment by FernandoPieressa** [comment]
La idea es que envíen la notificación al usuario que ocupo el comando

Saludos!

**Comment by frvalenzuela** [comment]
Pero en el enunciado el 4.2 menciona "Github notifique la creación de issues en el repositorio, se debe hacer uso de los webhooks"

Por lo que yo entiendo que debe avisar automáticamente cuando se crea una issue sin la necesidad de ocupar /get

**Comment by hanavarrete** [comment]
La idea es que ambas estén. Se notifica siempre que se crea una nueva issue y además puedo revisarla denuevo con el comando /get. Saludos

**Comment by akaminetzkyp** [comment]
Como ya preguntó @frvalenzuela, ¿debemos notificar a todos los usuarios que le han hablado al bot o solo al último?

Saludos!

**Comment by TomasSalvadores** [comment]
Me sumo a la pregunta
Esta claro que además de con /get, debemos notificar automáticamente cuando se cree un issue.
La pregunta es a quien notificamos? A todo quien haya hablado con el bot?

**Comment by hanavarrete** [comment]
Por si aún no está claro, hay que notificar a todo el que haya hablado con el bot el nuevo evento. Además, se puede pedir una issue con el comando get. 

Saludos!

**Comment by frvalenzuela** [comment]
Ahora sí me quedo claro, gracias !
