### ISSUE TITLE
Problemas (creo) que de la lógica

### ISSUE THREAD

**Issue by VichoAburto** [IIC2233/syllabus#669]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola!

No estoy seguro si es que me está faltando implementar algo, o simplemente es así, pero tengo 3 consultas/problemas.
1. Es normal que las fotos de usuario se repitan y se mezclen, ya sea que le corresponda o no? Porque solo me aparecen como las mismas 4 fotos para todos los usuarios.
2. Los mensajes del chat y los likes no se están guardando en mensajes.csv
3. La "sesión" queda abierta cuando se cierra la ventana del cliente.

Debo hacer algo al respecto?

Saludos

**Comment by catalina-arcila** [comment]
Hola @VichoAburto, respecto a tu pregunta 1 les ayudantes que estaban dispuestos a salir en la actividad tienen foto de elles mismes o afin , por lo que si no subieron una foto les aparece una troll x así decirlo (hay 4 de esas fotos). Los mensajes se guardar al cerrar al cliente, no sé si lo corroboraste. Finalmente respecto a tu pregunta 3 está "bien", está configurado de cierta forma en que en un *servidor* solo acepte un usuario una vez.

**Comment by VichoAburto** [comment]
Hola!
Gracias por tu respuesta.

Me queda claro solo la 1.😓

En cuanto a la 3, lo que pasa es que si cierro la ventana que tengo abierta del usuario/cliente, si intento ingresa nuevamente con ese usuario, me dice que ya existe alguien conectado bajo ese nombre.
La 2 no caché bien.

Saludos.

**Comment by VichoAburto** [comment]
La 2 ya la entendí!🎉🎉

**Comment by catalina-arcila** [comment]
El programa está diseñado para que la "sesión" queda abierta cuando se cierra la ventana del cliente, solo se puede abrir la *cuenta*  del mismo usuario de nuevo si se vuelve a iniciar el servidor.

**Comment by VichoAburto** [comment]
Aaaah yaaa super. Muchas gracias @catalina-arcila !
