### ISSUE TITLE
Restriccion de la superposicion de entidades

### ISSUE THREAD

**Issue by Polea012** [IIC2233/Syllabus#669]
En el enunciado se menciona que los personajes no se pueden atravesar entre si. Teniendo eso en consideración, ¿Los enemigos con otros enemigos tampoco se pueden atravesar? 
Ademas, los enemigos no se pueden atravesar con entidades como las safe zone o el puntaje extra?

**Comment by iqacevedo** [comment]
Hola,

No deberían atravesarse, tienen que comportarse como una entidad “sólida”.

Saludos !

**Comment by Polea012** [comment]
Entendido, Gracias!
