### ISSUE TITLE
Colisiones con super velocidad

### ISSUE THREAD

**Issue by sjkinast** [IIC2233/Syllabus#669]
Hola! cuando el jugador esta con una velocidad muy alta y quiere avanzar hacia un lugar pero avazando todo lo que debiese quedaria adentro de un bloque no lo dejo avanzar o hago que avanze hasta que choque, me refiero al caso en que podria estar lejos de un bloque.

**Comment by jfbahamondes** [comment]
No sé si entendí bien tu pregunta. Pero tiene que avanzar hasta que tope con el bloque. Para controlar esto a velocidades altas podrías, en vez de aumentar el desplazamiento en pixeles (asumo que hiciste esto), disminuir el tiempo en que se entra a la función de mover el personaje. 

Si no entendí bien, podrías aclararte un poco más. Saludos!

**Comment by sjkinast** [comment]
Hola si es justo eso que aumentaba en pixeles pero  eso me surgen esas dudas, pero no entiendo bien eso de disminuir el tiempo que entra  ya que las veces que llama la funcion estan dadas por si apreta la tecla para avanzar.

**Comment by jfbahamondes** [comment]
Otra alternativa que pensé es que a la hora se hacer el desplazamiento, settee el máximo/mínimo entre el que quieres hacer y el permitido. Es decir, si en el pixel (0,100) empieza un obtáculo y estaba en (0,90) y me muevo + (0,30) por fracción de tiempo, entonces que quede en esos casos en (0+0, min(100 - var,90+30)). Puse esa "var", ya que podrías restringirle el ancho del personaje pero puede que ya tengas controlado esa parte.

**Comment by sjkinast** [comment]
Es que mi personaje lo hice  basado en la ayudantia un qQObject, eso esta mal?

**Comment by jfbahamondes** [comment]
Si te funciona no 😄. Pero entonces, cuando mantienes presionado una tecla como es que controlas cuantas veces se avanza? Si estás en la U estoy en ventana y te podría ayudar en persona.

**Comment by sjkinast** [comment]
No estoy en la U pero gracias igual , si mantengo la tecla apretada avanza hasta que se suelte o choque .

**Comment by jfbahamondes** [comment]
Si lo apretas, avanza porque cada cierto TIEMPO que lo mantienes presionado se mueve el objeto? Porque si es así a ese tiempo me refiero que puedes disminuir. O de cierta forma avanza por las veces que escribe la letra, es decir si lo apreto una vez avanza una vez? 

En fin, lo otro sería restringir las velocidades o cambiar el método en que hacer que avance por medio de teclas. Podrías hacer un keypress que active un thread que haga que avance por tiempo y un key reléase que mate el thread. Y ese tiempo (delay) vas a poder controlar.

Saludos.
