### ISSUE TITLE
Null a la hora de guardar como json file

### ISSUE THREAD

**Issue by nhorellana** [IIC2233/syllabus#669]
Hola! Estoy intentando guardar mi arbol y hasta ahora todo perfecto, pero cuando intento guardar todos los None se convierten en null y hace que fallen los tests. Como puedo evitar esto?

**Comment by Hernan4444** [comment]
porque el json tiene los None como string, debes guardar "None" y no None, (notar la diferencia de comillas)

Saludos

**Comment by nhorellana** [comment]
Muchas gracias!
