### ISSUE TITLE
Pregunta sobre citas y "parafraseo"

### ISSUE THREAD

**Issue by solebravo** [IIC2233/Syllabus#67]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola! tenia una duda acerca de los códigos creados por otras personas. Mi pregunta proviene de que tengo un codigo para una función que saque de internet que voy a utilizar en la tarea y se que tengo que poner de donde proviene en el README, pero quería saber si esta permitido cambiar algunas cosas dentro de tal código para que se ajuste a mi programa o tiene que ser exactamente igual (claro que en ambos casos lo citaría).

En resumen mi pregunta es si el código debe ser citado textual o puede ser una cita de parafraseo.

Saludos.

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by Juampisaez** [comment]
Holaa 👋 @solebravo
Así es, puedes utilizar **funciones** mientras este referenciado y este sea de acceso público, independiente si lo ocupas literal o lo editas, debes referenciarlo. Ojo, ten cuidado de no abusar con funciones externas, podrías caer en casos de copia y ahí es más compleja la situación 👀.

Quedo atento a cualquier duda 😉
