### ISSUE TITLE
Problema con .gitignore

### ISSUE THREAD

**Issue by elneitans** [IIC2233/Syllabus#67]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/20)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/19)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Para hacer el .gitignore me estoy basando en el siguiente sitio web: https://www.w3schools.com/git/git_ignore.asp?remote=github. Según lo entiendí, hay que escribir un archivo tarea1.gitignore donde en texto tenga escrito los nombres de los archivos que deseo ignorar, sin embargo cuando hago git push (de la carpeta T1 completa), se suben todos los archivos, incluyendo los que no quiero, no sé por qué. Si alguien me pudiera ayudar lo agradecería mucho.

**Comment by ChupeteBecker** [comment]
Hola, el .gitignore se crea con ese mismo nombre, para ignorar los archivos debes poner el nombre o ruta de los archivos que quieras ignorar.

Un problema común que puedes tener es que estés creando el .gitignore después de haber subido los cambios de archivos que querías ignorar, por lo que el .gitignore no eliminara esos cambios previamente subidos.
Una solución a este problema es mover los archivos que subiste antes de crear el .gitignore fuera del repositorio, hacer push a los cambios y luego mover de vuelta al repositorio los archivos y esta vez el gitignore los ignorará (valga la redundancia).

Avísame si esto soluciona tu problema o si tienes alguna duda extra sobre la explicación.

Saludos.

**Comment by ChupeteBecker** [comment]
Existe una solución más elegante a dicho problema, este se explica en el siguiente link:

https://stackoverflow.com/a/3469805

Si bien esta solución es menos mecánica, requiere un mejor manejo de la terminal por lo que implica un mayor riesgo de problemas si usas este método sin un buen manejo de la terminal.

Te recomiendo usar la solución manual por esta vez y mas adelante estudiar bien el método elegante.

Saludos.

**Comment by elneitans** [comment]
Ese link estuvo buenísimo, pude arreglarlo. Otra cosa que me ayudó fue que yo hice un archivo que se llamaba tarea1.gitignore, lo que no estaba bien. Hice eso porque cuando hacía touch .gitignore en la terminal, nada aparecía en el folder. Eso es porque estaba oculto, no porque no existiera: luego desde la terminal hice nano .gitignore lo que te permite editar .gitignore. Dejo eso por si alguien le sirve.

**Comment by ChupeteBecker** [comment]
Efectivamente como dije, era solo .gitignore, muy bien solucionado de tu parte.

Voy a dejar la issue como resuelta.

Saludos.
