### ISSUE TITLE
Ejercicio 7.1

### ISSUE THREAD

**Issue by ignaciovilla** [IIC2233/syllabus#67]
cuando quiero imprimir el resultado de una expresion, me imprime esto <generator object <genexpr> at 0x00574C30> , y no se como solucionarlo

**Comment by knight-who-say-ni** [comment]
Hola @ignaciovilla!!
 Lo que pasa es que estas imprimiendo un generador, que es algo que van a ver en un par de semanas 👀. Podrías enviar una foto de tu código para ver como arreglarlo???

**Comment by ignaciovilla** [comment]
![image](https://user-images.githubusercontent.com/62113032/90799394-284ee700-e2e1-11ea-8763-6f034e93ecf1.png)
ahi va una foto, muchas gracias!

**Comment by ignaciovilla** [comment]
Muchas gracias! Eso me resolvió las dudas
