### ISSUE TITLE
Verificar alcance de pieza explosiva

### ISSUE THREAD

**Issue by Jeremiah-PHP6** [IIC2233/Syllabus#67]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

En el enunciado, se nos dice que el alcance de la pieza explosiva no debe ser bloqueado por un peón. Por ejemplo, dado un tablero de 4x4, si la pieza explosiva R4 está en la posición (0, 0), un peón PP en (1,1), entonces R4 no tendrá alcance en (2,2). Por tanto, es necesario tener información de los peones presentes en el tablero para poder verificar el alcance de la pieza explosiva. Esta información no se puede obtener a priori con los argumentos del método "verificar_alcance"; habría que pasar una instancia completa del tablero a la pieza explosiva. Pero no estoy seguro si hacer esto para resolver el problema.

¿Es necesario verificar que no hayan peones bloqueando el camino para retornar True en la función, o se puede omitir y verificar aparte?

**Comment by Dominique236** [comment]
Hola!

Por lo que veo estás entendiendo mal lo que se busca hacer con el método _"verificar_alcance"_, este buscar verificar si dada una posición entregada, indicada por (fila, columna), la explosión de la PiezaExplosiva logra alcanzar dicha posición, esto **sin importar si existen peones entremedio**, en cuyo caso retorna _True_. Esto porque solo se busca verificar si dicha posición es alcanzable según el tipo de pieza explosiva (revisando si comparten fila, columna y/o diagonal según corresponda).

Cuéntame si se entiende, si no para explicarlo de nuevo 😊

**Comment by Jeremiah-PHP6** [comment]
Ok entonces la verificación de los peones estorbando se hace aparte

**Comment by Jeremiah-PHP6** [comment]
En otras palabras, la verificación es, en principio, independiente de las dimensiones del tablero y de los peones que puedan haber en este, verdad?

**Comment by Dominique236** [comment]
Tal como dices, es independiente de las dimensiones del tablero y de los peones en él. Y como señalas, luego se definen otros métodos que si consideran la existencia de peones en el tablero. 

Cuéntame si esto resuelve tu duda 👀

**Comment by bea-or** [comment]
Hola, yo también tengo una duda sobre esto. La verificación es independiente del número que acompañe a la pieza explosiva? Por ejemplo, si es que tengo la pieza V2, tendría que ver las piezas que solo tengan la misma posición vertical o que también esten dentro del alcance, en este caso 2?
