### ISSUE TITLE
Agregar opciones a los menús

### ISSUE THREAD

**Issue by drosselot** [IIC2233/syllabus#67]
¿Puedo agregar opciones que no aparecen en la rubrica a los menús? Esto porque donde piden volver al menu anterior y volver al menu de inicio es inconsistente en los distintos menus, lo que me confunde. Preferiría dar la opción de volver al menu anterior y al de inicio para que sea consistente y no me falten funciones por confundirme.

**Comment by gatochico** [comment]
Hola! En todas las tareas **nunca habrá problemas si decides agregar más funcionalidades de las pedidas, siempre y cuando se cumplan/no reemplazen a las mínimas descritas en el enunciado.** (:

En este caso no habría ningun problema, ya que poniendo las dos opciones por separado, ya estarías cubriendo el minimo pedido en cada menú.

Saludos y éxito!!! :bird:

**Comment by drosselot** [comment]
Vale, graciass

**Comment by gatochico** [comment]
PD: recuerda no cerrar las issues resueltas! Nosotros nos encargaremos de hacerlo cuando se acabe la tarea ;)
