### ISSUE TITLE
Error al realizar push

### ISSUE THREAD

**Issue by KrishnaChaparro** [IIC2233/Syllabus#67]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia
*
Buenas tardes, subí mi repositorio a la nube pero no me aparece lo que subí, pero cuando lo hice todo me salía correcto, no se que puso pasar y lo entregue antes de las 8 pm, me da miedo de que si trato de subirlo de nuevo me descuenten por atraso. ¿Será que aun no se actualiza la información ?

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**
![15b07740-2980-4ea6-ae54-f7222c853465](https://user-images.githubusercontent.com/80900635/160213227-75a7075a-ec1a-4bb8-ad23-8e3171b03a8a.jpg)
]

**Comment by KrishnaChaparro** [comment]
Disculpen :( me equivoque y con la desesperación puse git pull en vez de git push, me da pena que por ese error me bajen por hora pero fue mi culpa. Igualmente gracias.

**Comment by matiasmasjuan** [comment]
Hola @KrishnaChaparro !

A la hora de revisar el estado del repositorio, se revisa la hora del ***commit***, no del **push**, por lo que no deberías tener problemas. Ahora bien, tal como se menciona en el anuncio de **Canvas**, dentro de rato les debería llegar un correo señalando el **estado** del repositorio que se va a revisar. Por lo tanto, **debes** revisar que el estado de ese repositorio sea el mismo que quieres entregar para esta tarea, de lo contrario deberás rellenar el formulario correspondiente. Si consideras que el estado del repositorio es el correcto y quieres que esa sea el estado de la tarea a revisar, entonces no respondas el formulario.

Saludos! Y que tengas un buen fin de semana! 😄

**Comment by KrishnaChaparro** [comment]
Muchas gracias :3
