### ISSUE TITLE
Respuestas a controles

### ISSUE THREAD

**Issue by simonmb12** [IIC2233/Syllabus#67]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

[Describe tu duda de manera detallada, explicando los contenidos en cuestión y ojalá colocando código o un caso de uso de ejemplo]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by simonmb12** [comment]
Hola! Me gustaría saber si pueden poner las respuestas correctas del control Nº2.
Además, hay hartas preguntas que hace referencia a clases "abstractas" y relación entre clases... lo cual creo que no está en el material de esta semana.
Saludos.

**Comment by gatochico** [comment]
Hola @simonmb12 🤓 Respecto a tus dudas:

Respuestas de controles: como equipo docente decidimos **no liberar las respuestas a los controles,** debido a que buscamos que los utilicen como herramienta para su aprendizaje. En caso de tener una pregunta incorrecta, la idea es que vuelvan al contenido y repasen la materia nuevamente para poder tener la pregunta correcta en un próximo intento. Es por esto que los controles tienen intentos infinitos, y están configurados para mostrar cuáles respuestas están correctas y cuáles no. 

Preguntas de control OOP: El control de esta semana abarca la materia de la semana 2 (esta semana) y semana 3 (próxima semana) del curso, que son OOP 1 y OOP 2 respectivamente. Como ambas son Orientación Programada a Objetivos, preferimos juntar ambas en un solo control, por lo que si hay referencias a materia que no has visto en la semana 2, probablemente son contenidos que se ven en la próxima semana del curso. Una vez revisadas ambas semanas, podrías poder resolver todas las preguntas del control (el cual queda abierto de forma indefinida, cabe recordar).

Saludos 🐱
