### ISSUE TITLE
Duda crear_predios

### ISSUE THREAD

**Issue by catalinarozasf** [IIC2233/Syllabus#67]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [ x] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [x ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]
Al estar haciendo crear pedidos en la primera parte constantemente me salen errores de ruta de los test publicos, como puedo saber si el error es del codigo, un bug o algo por el estilo
[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by vgalfaro** [comment]
Hola! en en el enunciado dan los pasos a seguir para ejecutar los tests, recuerda que tienes que estar en la carpeta T1 y luego ejecutar el comando que aparece en el enunciado, hay una versión vieja del enunciado donde aparece "python3 -m unittest -v -b tests_publicos.test_00_crear_plano.py" que está incorrecto, pues es sin .py al final, si le problema persiste te pido que me adjuntes una captura del error. Saludos!
