### ISSUE TITLE
nameTuple Global?

### ISSUE THREAD

**Issue by naquiroz** [IIC2233/Syllabus#67]
Para la tarea, cómo es mas correcto representar en un diagrama UML una nameTuple que se utiliza en varias clases? Como una clase sin metodos o colocando como _type_ de la variable `namedTuple` ?

**_Ejemplo:_**
**Forma 1**
![image](https://user-images.githubusercontent.com/29825816/37865733-9e603314-2f5f-11e8-81aa-95e591a2d13c.png)

**Forma 2**
![image](https://user-images.githubusercontent.com/29825816/37865744-cb8d33aa-2f5f-11e8-9d49-cea6803c7c5f.png)

**Comment by santilaguna** [comment]
Tengo la misma duda!!

**Comment by Hernan4444** [comment]
Hola, "NamedTuple" no es un concepto de OOP, sino una implementación de python para hacer clases sin métodos, así que es necesario ver sus atributos.  Por lo que la forma 1 es la esperada para el diagrama.

Saludos

**Comment by santilaguna** [comment]
Oka gracias!
