### ISSUE TITLE
Duda acerca los chat regulares

### ISSUE THREAD

**Issue by martinletelier** [IIC2233/syllabus#67]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Holaa! Tengo una duda acerca los chat regulares.
Cuando envió un mensaje nuevo al chat, este debe ser agregado al historial de la conversación con ese contacto, modificando el archivo 'mensaje.csv'. **Con que formato debemos guardar este mensaje?** 
Ya que no tenemos la información de la fecha ni la hora, por lo que no lo podremos guardar en 'mensaje.csv'  de la misma forma que los demás. 
Gracias!!

**Comment by aljara97** [comment]
Hola, al momento de actualizar un archivo, en este caso `mensajes.csv` debes hacerlo con el mismo formato de los mensajes anteriores.
Te sugiero revisar la documentación de la librería [`datetime`] (https://docs.python.org/es/3.7/library/datetime.html), la cual tiene funciones que te permiten manejar la fecha y hora actual

**Comment by martinletelier** [comment]
Ok, gracias!

**Comment by aljara97** [comment]
De nada! por favor no cierres una issue, los ayudantes lo haremos cuando corresponda, por mientras puede ser de utilidad para otro compañer@
