### ISSUE TITLE
No puedo subir la carpeta "partidas" 

### ISSUE THREAD

**Issue by Jprampad** [IIC2233/syllabus#67]
Hola!
He intentado de diferentes maneras de subir la carpeta "partidas" mediante git, pero no he podido. Cualquier ayuda sirve!

**Comment by KnowYourselves** [comment]
Hola @Jprampad!

La respuesta a tu pregunta puede ser encontrada en la issue #27 👀, recuerda revisar las issues antes de preguntar!

Éxito!
