### ISSUE TITLE
Problema con pyqt5 en Mac

### ISSUE THREAD

**Issue by arielkauderer** [IIC2233/syllabus#670]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

Instalé correctamente pyqt5 en el terminal y QtDesigner a través del link y el primer ejemplo de los contenidos no corre en VsCode.

¿Qué podría estar pasando? 

![Captura de pantalla 2020-10-11 a la(s) 12 53 30](https://user-images.githubusercontent.com/66897088/95683517-2e1ac780-0bc2-11eb-829b-189749b1388d.png)

**Comment by tocococa** [comment]
Hola @arielkauderer ! PyQt5 por lo general no funciona correctamente desde Visual Studio, podrías correr el mismo programa desde la terminal? Si sigues con problemas podrías ejecutar `pip install PyQt5` para verificar que la librería esté correctamente instalada.

**Comment by arielkauderer** [comment]
Ya lo solucioné! Gracias de todas formas

Era un problema con la versión de PyQt5. Tuve que desinstalar la que tenía e instalar una anterior.

**Comment by nataliasuarez99** [comment]
> Ya lo solucioné! Gracias de todas formas
> 
> Era un problema con la versión de PyQt5. Tuve que desinstalar la que tenía e instalar una anterior.

holaaa como lo hiciste?? tengo el mismo problema :-(
