### ISSUE TITLE
Errores en la lectura del archivo .json en el main de servidores

### ISSUE THREAD

**Issue by FabiolousFabio** [IIC2233/syllabus#670]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Tengo un problema en donde con los imports de los diferentes módulos de la actividad no se me están cargando correctamente, lo cual produce que no se pueda cargar el código. Adjunto foto de un ejemplo de como se ven los imports y los errores que arroja dado que no encuentra el modulo. 
![image](https://user-images.githubusercontent.com/80774049/123175788-5c8abb00-d450-11eb-836f-b35ffa6e0221.png)
![image](https://user-images.githubusercontent.com/80774049/123175848-7a582000-d450-11eb-8c29-84ee7ee9dcdf.png)

**Comment by aaossa** [comment]
Creo que esto es un duplicado de https://github.com/IIC2233/syllabus/issues/663, ¿podrías confirmar si es lo mismo? ¡Éxito en la actividad 🙌 !

**Comment by FabiolousFabio** [comment]
sisi es lo mismo esq me recorri muchos issues y no encontraba la solución

**Comment by aaossa** [comment]
¿Te funcionó la misma solución?

**Comment by FabiolousFabio** [comment]
No me puedo correr el main desde la carpeta servidor, cada vez que lo corro vuelve atras a correrlo de la carpeta AF7

**Comment by aaossa** [comment]
🤔 ¿A qué te refieres? No sé cuál editor estás usando, pero si estás en la consola, deberías utilizar el comando `cd` hasta llegar dentro de la carpeta del servidor o del cliente. Así tiene que ejecutarse el archivo, como expliqué en la otra *issue*

**Comment by FabiolousFabio** [comment]
Ahi me funciono esq tengo el disco incriptado y necesitaba el key para entrar a la siguiente carpeta
