### ISSUE TITLE
Duda multiplayer y enemigos

### ISSUE THREAD

**Issue by frduran** [IIC2233/Syllabus#670]
Hola! Cuando se elige la opción multiplayer se deben poder arrastrar a los dos jugadores? Además, se sigue partiendo con 3 enemigos? 
Y en caso de un jugador (o dos) los 3 enemigos iniciales deben partir en lugares aleatorios permitidos o les puedo setear un lugar donde partir (ej las esquinas) ?
Gracias de antemano!

**Comment by nachocontreras** [comment]
Hola!

1) Sí, se deben poder arrastrar los dos jugadores y se parte con 3 enemigos.

2) Los enemigos deben partir en lugares aleatorios permitidos que cumplan la propiedad de:
**ser un espacio vacío y estar a una distancia minima del personaje que queda a criterio del desarrollador.**

**Comment by frduran** [comment]
@nachocontreras  gracias! Pensé que eso era solo para los enemigos nuevos y no los 3 iniciales :)
