### ISSUE TITLE
Flask dentro de una clase

### ISSUE THREAD

**Issue by akaminetzkyp** [IIC2233/Syllabus#670]
Hola!

He estado tratando de implementar `flask` dentro de una clase, pero estoy medio complicado. Por ejemplo, tomemos un programa muy simple.

```
import flask

app = flask.Flask(__name__)

@app.route('/')
    def home():
        return 'Hello world!'

app.run()
```

Intenté modelarlo como una clase, como se muestra a continuación.

```
import flask

class Website:
    def __init__(self):
        self.app = flask.Flask(__name__)

    @self.app.route('/')
    def home(self):
        return 'Hello world!'

if __name__ == '__main__':
    website = Website()
    website.app.run()
```

Un códiogo así me trae problemas con el `self` en el `@self.app.route('/')`. Intenté quitar el `self` pero tampoco funcionó.

¿Cuál es la forma correcta de utilizar `flask` dentro de una clase?

De antemano, muchas gracias!

**Comment by MainScientist** [comment]
Una buena forma de enfrentar este problema es **extendiendo** la clase `flask.Flask`. Un ejemplo de cómo se puede hacer esto:

```python3
import flask


class MyApp(flask.Flask):

    def __init__(self):
        super().__init__(__name__)
        self.configure_routes()

    def configure_routes(self):
        @self.route("/")
        def hello_world():
            return "Hello world!"


if __name__ == "__main__":
    app = MyApp()
    app.run()
```

De todas formas el código que tu pusiste tiene el error que el decorador se encuentra dentro de `self.app`, por lo que no tienes acceso a él de forma estática (es decir, no puedes acceder a `self` desde fuera de los métodos de tu clase). Lo que podrías hacer sería crear una variable estática dentro de tu clase que sea la aplicación de flask o tener un método `configure_routes` dentro de tu clase que use el decorador de forma parecida a como lo usé en mi ejemplo (Cambiando `@self.route` por `@self.app.route`).

**Comment by akaminetzkyp** [comment]
Buenísima! Voy a implementar lo que dijiste. Muchas gracias, Felipe!
