### ISSUE TITLE
Problema con las variables de entorno 

### ISSUE THREAD

**Issue by frvalenzuela** [IIC2233/Syllabus#671]
Al momento de setear las variables de entorno en heroku me tira el siguiente error:

!  FLASK is invalid. Must be in the format FOO=bar 

Ya lo google pero no encuentro una respuesta que aclare el porque FLASK es invalido

**Comment by Hernan4444** [comment]
@frvalenzuela el comando es super sensible y no acepta espacios, debes poner `FLASK_APP=main.py`, lo mas probable es que estas haciendo `FLASK_APP = main.py`. Al menos ese es el error que te indica.

Saludos

**Comment by frvalenzuela** [comment]
Si eso era muchas gracias Hernán !

**Comment by danyestay** [comment]
Hola, a mi me pasó que tras setear exitosamente (en teoría) la variable de entorno al parecer me tira un error con esa variable. Mi Procfile tiene `web: flask run --host=0.0.0.0 --port=$PORT`, requirements.txt tiene `Flask==0.12.2` y runtime.txt `python-3.6.1`. A todo esto ya hice push antes de realizar `heroku logs`

Una imagen de mi error (he googleado pero no he tenido exito):
![error](https://user-images.githubusercontent.com/20783397/27466143-797bb3ca-57a6-11e7-8eb3-16df1c549dc9.JPG)

**Comment by chuma9615** [comment]
Yo tengo el mismo error!

**Comment by danyestay** [comment]
Ya lo solucioné separando el server del main :)

**Comment by ofvera** [comment]
A mi me dice que no encuentra la app:

Couldn't find that app

**Comment by Minjor** [comment]
a mi tambien me dice que no encuentra la app xd
