### ISSUE TITLE
AF7: Problemas al interactuar con la opción "Ver perfiles"

### ISSUE THREAD

**Issue by B-Birb** [IIC2233/syllabus#671]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola! Tengo varios problemas al tratar de ver perfiles durante el programa. 

Al tratar de hacer match, me aparece en la consola del servidor: "ERROR: No se pudo decodificar el mensaje". 
Otras veces, al tratar de hacer match, me aparece el siguiente mensaje en la consola del usuario: 
![image](https://user-images.githubusercontent.com/22687150/123175861-804e0100-d450-11eb-9c98-a905edc36549.png)
También me ha aparecido un mensaje de "No se pudo decodificar el mensaje" en la consola del usuario cuando trato de hacer match. 

Por último, traté de probar ingresando con distintos usuarios. Por alguna razón, al colocar ciertos usuarios la consola me muestra  el mensaje "No se pudo decodificar el mensaje". 

¿Qué puedo estar haciendo mal? :(

**Comment by aaossa** [comment]
Considerando que el error se produce al deserializar y que el primer byte es el problemático, ¿separaste el largo del resto del mensaje a la hora de recibir el mensaje?

**Comment by MatiasDuhalde** [comment]
Hola @B-Birb !

Revisé tu código también :eyes: , y hay un error en la lógica que ocupas al momento de recibir el mensaje, debido a que no manejas correctamente el largo y la cantidad de bytes que recibes en el ciclo que implementaste. El método funciona bien para leer el primer chunk, pero hay problemas cuando el mensaje es más largo que 64. Es por esto que te puede funcionar cuando intentas hacer login con usuarios que tienen un nombre corto, pero es posible que falle para los nombres más largos, debido a que no se maneja correctamente el chunk. Recomiendo basarse en los ejemplos de los contenidos para completar esa parte!

Éxito :sparkles:

**Comment by B-Birb** [comment]
En efecto, era un problema de lectura y largos. Muchas gracias!!
