### ISSUE TITLE
Power ups

### ISSUE THREAD

**Issue by Cschavez** [IIC2233/Syllabus#671]
Hola! Un power up, cuando aparece solo se muestra por máximo un tiempo determinado o se queda ahí hasta que el jugador lo toque? 

Muchas gracias!

**Comment by monicabelen** [comment]
Hola! El power up estará en el juego hasta que el jugador lo toque o hasta que sea destruido por alguna bomba.

**Comment by Cschavez** [comment]
El enunciado dice que hay que ver las colisiones entre el personaje y los powers ups, pero esto no se refiere a que el bomberman tenga que dejar de caminar cuando encuentra uno cierto? sino solo "comérselo"?

**Comment by monicabelen** [comment]
Sí, exacto, debe considerar que el power up está en la casilla y atraparlo :)

**Comment by frduran** [comment]
Los enemigos deben ser capaces de pasar por encima de los power up o se produce una colisión?

**Comment by monicabelen** [comment]
Hola @frduran ! No debería producirse una colisión entre enemigos y power ups.
