### ISSUE TITLE
Error en Cierre AF04

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#671]
Hola!!
Resulta que viendo el video de resumen de la AF04, me dí cuenta de varios errores e intente corregirlos siguiendo la idea de lo que se muestra y habla en el video. Pero en el módulo "ventana_inicial.py" me sale un error que no sé cómo solucionarlo ..
Escribí lo mismo que sale en el video, que es algo como:
![error AF04](https://user-images.githubusercontent.com/59337116/82068998-bee78880-96a0-11ea-8c6e-58eb6fd5e7cd.PNG)
Y me sale el siguiente error:
![ERROR2 AF04](https://user-images.githubusercontent.com/59337116/82069056-cc9d0e00-96a0-11ea-8613-7624f2ea835a.PNG)

**Comment by fdoflorenzano** [comment]
Hola @Camila-sty,

Fue un error de escritura ahí, `scaled` es un método de `QPixmap`. En esa parte debería ser `QPixMap(ruta_logo)`, no `QLabel(ruta_logo)`. Si te fijas más adelante en el video, se setea correctamente para otra imagen. 

¡Gracias por hacerlo notar!

**Comment by Camila-sty** [comment]
Gracias!
