### ISSUE TITLE
Ejercicio propuesto 3.2 semana 9

### ISSUE THREAD

**Issue by denisseleiva** [IIC2233/syllabus#671]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola!! Tengo una duda con el ejercicio propuesto 3.2 de la semana 9. Entiendo el comportamiento que debe tener el programa, pero no encuentro la forma de acceder a la posición del evento para revisar si el clic fue dentro del cuadrado verde o no. Intenté hacer un GridLayout y buscar la posición del evento en el grid pero me tira error ya que al parecer no se puede usar grilla.getItemPosition(evento). Entonces, **¿Cómo puedo obtener la posición del evento para filtrar los clics que sean dentro del cuadrado y los que no?**
Además en el notebook de contenidos aparece que este ejercicio es para experimentar con el funcionamiento del método keyPressEvent. Intenté buscar info de ese método en internet pero no me apareció nada útil para resolver mi problema 😔

Muchas gracias 😊

**Comment by aaossa** [comment]
Hola @denisseleiva ,

Creo que este ejercicio en verdad es más para `mousePressEvent`, al parecer es un error en esa parte de los contenidos 😱 . Como invertiste tiempo buscando al respecto, mejor te explico un poco sobre el método. Lo que hace `mousePressEvent` es identificar cuando ocurre un evento del *mouse*, como es hacer clic sobre la ventana. Te dejo un mini ejemplo de cómo es la estructura para usar `mousePressEvent`:

```python
import sys
from PyQt5.QtWidgets import (QApplication, QWidget, QLabel)
from PyQt5.QtGui import (QPixmap, QColor)
from PyQt5.QtCore import Qt


class MiVentana(QWidget):
    def __init__(self):
        super().__init__()
        self.inicializa_gui()

    def inicializa_gui(self):
        self.show()

    def mousePressEvent(self, event):
        print("Alguien hizo clic con el mouse")

    def keyPressEvent(self, event):
        print("Alguien presionó una tecla del teclado")


if __name__ == '__main__':
    app = QApplication([])
    ex = MiVentana()
    sys.exit(app.exec_())
```

Cada vez que alguien haga clic sobre la ventana, se ejecutará el método `mousePressEvent`. Lo que debes hacer en el ejercicio es utilizar el evento que recibe la función para determinar la posición en la que se hizo el clic y comparar eso con la posición y tamaño del label para determinar si este fue dentro o no.

Otra forma de hacerlo, por si quieres probar así, es hacer tu propio `QLabel` (herencia 👀) que tenga el `mousePressEvent`, y así solo actúas ante los clics que ocurran dentro del `QLabel` y ya no tienes que determinar la posición del clic, sino que solo mover el `QLabel` cuando corresponda.
