### ISSUE TITLE
AF7: Duda sobre correr main.py

### ISSUE THREAD

**Issue by fcbahamondes** [IIC2233/syllabus#672]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido
Hola, he intentado probar mi código pero nunca me aparece la interfaz. Primero intente en la consola desde vscode, corriendo primero el servidor y luego el cliente pero me aparece el error de la primera imagen. Luego lo hice como se menciona en las issues, pero me aparece lo que sale en la imagen dos. 

<img width="1182" alt="Captura de pantalla 2021-06-23 a las 18 46 46" src="https://user-images.githubusercontent.com/80771151/123177976-4c74da80-d454-11eb-8061-61ffb4fa9960.png">

<img width="544" alt="Captura de pantalla 2021-06-23 a las 18 48 55" src="https://user-images.githubusercontent.com/80771151/123178000-57c80600-d454-11eb-9477-18b188092f84.png">

**Comment by MatiasDuhalde** [comment]
Hola @fcbahamondes !

Veo que para la primera imagen, tienes un problema de paths, donde el programa no detecta el path relativo de los usuarios, y la solución es efectivamente como lo hiciste para la segunda imagen.

Con respecto a la segunda imagen, ahí no hay ningún error, y se ve el comportamiento correcto que debería ocurrir al iniciar el servidor. Ten en cuenta que el servidor **no** tiene interfaz, es sólo la consola. El que tiene interfaz es el **cliente**. Para ejecutar el cliente, debes correr el archivo `main.py` del directorio "cliente". La interfaz se debería abrir si se cumplen las siguientes condiciones:
- El código para iniciar el cliente está implementado
- El servidor está actualmente corriendo (en otra consola)

Ojalá eso aclare un poco la duda! Mucho éxito! :sparkles:

**Comment by fcbahamondes** [comment]
También lo había intentado desde el directorio de clientes, pero aun asi me arroja un error. Por lo que me dices es un error al escribir el código, de qué manera puedo encontrar el error si el mensaje que me aparece es el mostrado y no tengo mucha más información de el. Solo revisando mi codigo??

<img width="566" alt="Captura de pantalla 2021-06-23 a las 19 07 33" src="https://user-images.githubusercontent.com/80771151/123179127-b0989e00-d456-11eb-9327-beb9d4e25639.png">

**Comment by MatiasDuhalde** [comment]
Fíjate que el mensaje de error te avisa que `No se pudo conectar a localhost:47365`. Esto puede tener dos causas:
- No tienes el servidor actualmente ejecutándose (tiene que estar corriendo en otra consola, distinta a la del cliente)
- Hay algún error en tu implementación cuando estableces la conexión del cliente con el servidor, que ocurre en `iniciar_cliente`

**Comment by fcbahamondes** [comment]
Entiendo, aun asi me quedan dos dudas. Primero es lo que habia que agregar self.controlador.mostrar_login(), va en la primera linea del metodo iniciar cliente?? Y lo otro, lo siento lo ignorante, como puedo tener una consola corriendo mientra abro otra??

**Comment by MatiasDuhalde** [comment]
Hola @fcbahamondes !

Para lo primero, la idea es que el login se abra **después** de haberse conectado en ese método :eyes:

Para la segunda, no estoy seguro como funciona en MacOS. En windows, puedes inciar varias consolas clickeando el ícono de la consola en el *Start Menu*, y en Linux, generalmente los emuladores de terminales permiten abrir una nueva pestaña directamente desde la consola, usando Ctrl+Shift+C. Intenta abrir otra consola de la misma manera en que abriste la primera, pero no estoy seguro si eso funcionaría.

**Comment by fcbahamondes** [comment]
Intente abrir dos consolas, primero corri el main.py del servidor y luego el de cliente pero no me reconoce la carpeta cliente :(
<img width="1147" alt="Captura de pantalla 2021-06-23 a las 19 41 22" src="https://user-images.githubusercontent.com/80771151/123181362-27379a80-d45b-11eb-9169-aa4c51ce464d.png">

**Comment by fcbahamondes** [comment]
ya lo logre!!

**Comment by MatiasDuhalde** [comment]
Hola! Al parecer tu terminal de la izquierda está en un directorio nada que ver :open_mouth: Al usar el comando ls, te debería mostrar las carpetas que tiene el directorio actual, pero no te muestra nada, por lo que está vacío. Para saber el directorio completo en el que se encuentra la terminal actualmente, puedes usar el comando `pwd`

PD: Justo estaba escribiendo la respuesta, la subo igual por si a alguien le sirve. :laughing:
