### ISSUE TITLE
Duda de teclas en "ventana_principal.py"/AF04

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#672]
Hola!
Después de ingresar un usuario aparece la ventana principal tal como lo pedían en el enunciado de la AF04, pero al presionar cualquiera de las teclas Q-W-E, la pantalla se cierra y no sucede nada más.. 
Qué podría estar no funcionando?

**Comment by aaossa** [comment]
Hola @Camila-sty , al presionar alguna de las QWE en dicha ventana tienen que ocurrir dos cosas: emitir la señala con los datos de la carta correspondiente y ocultar la ventana. Al parecer lo segundo ocurre sí o sí, por lo que quizás te falte algo relacionado con las señales. Si estás emitiendo la señal `senal_enviar_jugada`, esta debe estar conectada al método `jugar_carta` de la lógica. Si ya hiciste esto, otra cosa que podría faltarte es conectar la señal de `ventana_combate` (`senal_abrir_ventana_final`) que debe conectarse a un método de la ventana final. Quizás es alguna de esas cosas, cuéntanos cómo te va 🙌

**Comment by Camila-sty** [comment]
Cuando dices "Si estás emitiendo la señal ```senal_enviar_jugada```, esta debe estar conectada al método ```jugar_carta``` de la lógica" esto se hace en ```main.py``` ?

**Comment by Camila-sty** [comment]
Hice todas las conexiones de señales en ```main.py``` , pero aun no me sale nada después de seleccionar alguna tecla QWE. Quizás estoy conectándolo mal, puedo mandarles mi código de esta parte?

**Comment by aaossa** [comment]
@Camila-sty así es, toda conexión de señales se espera en el `main.py`. Puedo darle una mirada a tu código durante el día (espero no tan tarde 😅 ), ¿puedes subirlo a tu repositorio?

**Comment by Camila-sty** [comment]
Ya lo subí, gracias...

**Comment by Camila-sty** [comment]
Siii, ahí me funcionó todo, gracias!
Lo único malo de haber revisado esto es que me dí cuenta que hice todo mal en la actividad ayer jajaja.
Gracias! :smile:
