### ISSUE TITLE
Problema al importar desde PyQt5.QtWidgets

### ISSUE THREAD

**Issue by PedroFuenzalida** [IIC2233/syllabus#672]
Al copiar los códigos del notebook me tira estos errores:
No name 'QApplication' in module 'PyQt5.QtWidgets'pylint(no-name-in-module)
No name 'QWidget' in module 'PyQt5.QtWidgets'pylint(no-name-in-module)
No name 'QLabel' in module 'PyQt5.QtWidgets'pylint(no-name-in-module)
No name 'QLineEdit' in module 'PyQt5.QtWidgets'pylint(no-name-in-module)

**Comment by retamalcito** [comment]
¡Hola @PedroFuenzalida!

Por la descripción de tu error, me imagino que estás utilizando **VSCode** como editor de texto, ya que este suele tener ese problema. Sin embargo, no debes preocuparte, ya que a pesar de que te subrayará algunas líneas, tu código debería correr igualmente sin ningún problema :smile:, por lo que puedes ignorar esa advertencia.

¡Saludos! :wave:

**Comment by PedroFuenzalida** [comment]
Ahh ok gracias
