### ISSUE TITLE
Inconsistencias enunciado

### ISSUE THREAD

**Issue by rihanuch** [IIC2233/Syllabus#672]
Hola!
Dos preguntas del enunciado que son medias contradictorias
1) se dice que el personaje principal comienza con tamaño 2 y que los personajes tienen un tamaño maximo de 10, pero si se esta en el nivel 5 se tendria tamaño 11
Nivel-tam
1-2,3
2-4,5
3-6,7
4-8,9
5-10,11(?)

2) vida maxima: esta esta definida por tam actual*20 +100 +c, con c siendo las bonificaciones, pero después se dice que al comprar el item de vida se le aumenta en un 20% la vida maxima. Cual de los dos se usa?

Gracias!

**Comment by PIPEAPABLAZA** [comment]
La 1 la respondieron aquí #619 😃

**Comment by iqacevedo** [comment]
Como dice @PIPEAPABLAZA ya fue respondida 1).
2) Si el tamaño actual es 2, vida máxima es 2*20 + 100, a eso le saca el 20% y esa es la bonificación que se aplica cuando compras el item de vida.

Saludos !

**Comment by rihanuch** [comment]
De donde sale el +c entonces???

**Comment by iqacevedo** [comment]
+ c es el 20% extra.

**Comment by aurodriguez** [comment]
Pero se va acumulando en C el 20% de la vida máxima cada vez que se compre un ítem vida? O c toma un valor temporalmente solo cuando se compra y en luego se setea en 0?
