### ISSUE TITLE
Vidas enemigos

### ISSUE THREAD

**Issue by frduran** [IIC2233/Syllabus#672]
Los enemigos siempre tendrán 1 vida o es un parámetro que se puede cambiar y debemos incluirlo en parameters.py ?

**Comment by monicabelen** [comment]
Hola! Sí, siempre tendrán una vida. No es necesario incluirlo en parameters.py

**Comment by frduran** [comment]
@monicabelen gracias!

**Comment by jfbahamondes** [comment]
@frduran  De todas formas siempre es mejor dejar los parámetros de manera variable (por ejemplo definir una variable VIDAS_ENEMIGOS). Es una buena practica! Y podrías ir modificando tu juego para probar diferentes dificultades (una vez entregada la tarea, y claro, sólo si quieres 😆 ).
