### ISSUE TITLE
Error al hacer push

### ISSUE THREAD

**Issue by danyestay** [IIC2233/Syllabus#672]
Al intentar hacer push me tira un error al final. Qué estoy haciendo mal? :(
Este es el error: `failed to push some refs to 'https://git.heroku.com/agxapp.git'`

Dejo una imagen del push:

![captura3](https://user-images.githubusercontent.com/20783397/27464321-c5663366-579a-11e7-802d-afb44bf2174e.JPG)

**Comment by MainScientist** [comment]
Podrías mostrarnos lo que tienes exactamente en el requirements.txt y runtime.txt?

**Comment by danyestay** [comment]
Son archivos de una solo linea, en requirements.txt tengo `Flask==0.12.2` y en runtime.txt `python-3.6.1.`

**Comment by Hernan4444** [comment]
@danyestay intenta cambiar `python-3.6.1.` por `python-3.6.1` (notar que le saqué el punto final).

Saludos!!

**Comment by danyestay** [comment]
@Hernan4444 Magia!! justamente era el punto, ahí funcionó jajaj muchas gracias :)

**Comment by adisrael** [comment]
a mi me aparece el mismo error al final, revisé pero no tengo el punto final en ninguno de los 2 archivos:
- requirements.txt
requests==2.18.1
Flask==0.12.2
- runtime.txt
python-3.6.1

**Comment by Hernan4444** [comment]
@adisrael te aseguraste que el Procfile  también cumpla los requisitos, es decir, sin extensión y copiado sin puntos??

Saludos!

**Comment by adisrael** [comment]
@Hernan4444 mi procfile dice esto:
web: flask run --host=0.0.0.0 --port=$PORT

**Comment by dfvasquez** [comment]
Yo también tengo ese problema y tengo lo mismo que @adisrael 😢 en los archivos

**Comment by Hernan4444** [comment]
@adisrael y @dfvasquez pueden subir los archivos a su repositorio junto con un txt que diga todos los comandos que utilizaron?? así puedo ver donde está el error

Saludos!!

**Comment by dfvasquez** [comment]
@Hernan4444  hice push, gracias Hernán!

**Comment by Hernan4444** [comment]
1) solo para confirmar, después que editan los archivos hacen git add, git commit y luego git subtree push --prefix Tareas/T07 heroku master ?? o altilo hacen git subtree push --prefix Tareas/T07 heroku master??

2) No estoy seguro de esto pero en el main.py pongan el codigo dentro de un :
```
if __name__ == "__main__":
    app.run() #Sin indicar el puerto
```

3) Recordar que para setear las variables de entorno deben usar `heroku config:set --app mavrakis-bot FLASK_APP=main.py`  (agregar el guion bajo)

Junto a @MainScientist estamos viendo este error y si encontramos mas cosas que no calzan les avisamos

**Comment by dfvasquez** [comment]
1. Ahora lo hice con add y commit.
2 y 3. Lo tengo de esa forma
Ahora hice push y no me tira error al parecer, aparece esto:

![image](https://user-images.githubusercontent.com/20784077/27499095-277938e2-5830-11e7-83e0-7b214ec87088.png)

Y si hago heroku logs:

![image](https://user-images.githubusercontent.com/20784077/27499120-45adcb3e-5830-11e7-9299-9b4f73ece626.png)

Me sale el error 404 ahora al ingresar a mi página, aiuda, no se qué hice jajajaj  :(

**Comment by adisrael** [comment]
jajajaja a mi me paso lo mismo pero creo que es porque me faltan cosas en la app en si! gracias @Hernan4444

**Comment by dfvasquez** [comment]
Bueno si es por eso el error, muchas gracias @Hernan4444  jajajaj

**Comment by Hernan4444** [comment]
@adisrael verifica que toda libreria que importas esté en requeriment
@dfvasquez cuando te metes a tu pagina estas llamando a la route `"/"`, en tu caso no tienes ninguna pagina definida a esa ruta.

Eso es todo lo que puedo decir, ahora tienen que comenzar a debuguear su app pero no olviden que cualquier cambio que hagan se verá reflejado solo si hacen `git add`,` git commit` y luego `git subtree push --prefix Tareas/T07 heroku master`.

Saludos!

**Comment by ofvera** [comment]
Al intentar hacer el proceso de add, commit y push del subtree, me tira el siguiente error,
git push using:  heroku master
fatal: 'heroku' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
