### ISSUE TITLE
error no me deja subir tarea a mi repositorio

### ISSUE THREAD

**Issue by bedefrunner** [IIC2233/Syllabus#673]
Hola! Al tratar de hacer push de mi tarea a mi repositorio, me aparece este error en el terminal:
![screen shot 2017-11-02 at 00 11 27](https://user-images.githubusercontent.com/20782509/32308080-b1fbb51e-bf62-11e7-9199-cfba797d2f5e.png)

Lo que entiendo es que me dice que haga pull, pero al hacer pull me aparece esto:
![screen shot 2017-11-02 at 00 15 31](https://user-images.githubusercontent.com/20782509/32308152-241a5754-bf63-11e7-891a-ebede87eb7d8.png)

Por si de algo sirve, soy mac

**Comment by andresfdezc** [comment]
Tal vez [esto](https://stackoverflow.com/questions/41284031/how-to-solve-git-merge-error-swap-file-merge-msg-swp-already-exists) te pueda ayudar.
