### ISSUE TITLE
Duda: Como hacer webhook con telegram

### ISSUE THREAD

**Issue by KnowYourselves** [IIC2233/Syllabus#673]
Tengo la siguiente duda, Ya seguí los pasos con heroku y ya hice el bot con telegram pero no logro hacer el webhook.

Por lo que entendi del material y el enunciado para hacer el webhook tengo que hacer `request.post(link_telegram, diccionario) `

Mi problema es que no entiendo muy bien cual es la url que tengo que definir en el diccionario, tiene que ser mi link heroku mas algun route? por ejemplo link_heroku/rutax? 

Y una vez hecho esto tengo que definir a nivel de flask un app.route cuyo link sea el que le pase al webhook y su metodo "POST"?

**Comment by MainScientist** [comment]
Te recmiendo ver la issue #657 para saber cómo y hacia donde setear el webhook.
Sí, debes definir en flask una ruta cuyo link sea el que le pasaste a heroku diciendo que es a través de POST.

**Comment by KnowYourselves** [comment]
gracias!
