### ISSUE TITLE
Duda con implementación de “placeholder” con PyQt

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#673]
Hola!
No sabía cómo definir esta duda jaja.
En la actividad AF04 donde mostraban un ejemplo de cómo debería verse la ventana inicial. Me queda la duda de cómo puedo implementar lo siguiente:
![duda codigo](https://user-images.githubusercontent.com/59337116/82090732-1ba86a80-96c4-11ea-9503-f4f4201eafa7.PNG)
Me refiero al texto que está dentro del cuadro para editar (escribir)....

**Comment by igbasly** [comment]
Hola @Camila-sty :smile:

El texto que aparece por defecto en los campos de texto y que no funciona como un texto ingresado se llama *placeholder*. 
En el caso de los `QLineEdit` de PyQt, estos traen un método llamado `setPlaceholderText` que recibe un *string*, el cual te permite definir el texto que se mostrará en el respectivo campo de texto.
Ej:
```Python
edit = QLineEdit(self)
edit.setPlaceholderText('Ingrese su texto aquí')
```

Espero que haya quedado claro,
Saludos.

**Comment by Camila-sty** [comment]
muchas gracias :smile:
