### ISSUE TITLE
Ejercicio 5.1- Falta parte de código que despliega imagen de la segunda venta

### ISSUE THREAD

**Issue by ignaciomansuy** [IIC2233/syllabus#673]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda
Me parece que en este ejercicio falta la parte del código que permite visualizar la imagen de la segunda ventana, falta el **elif titulo == 'Segunda'**. En la primera foto de homero solo dice que debemos arreglar el método `abrir_ventana_1( )` ¿O nosotros también debemos escribir el código de **elif titulo == 'Segunda'**? 
```python
        if titulo == 'Primero':
            self.boton = QPushButton("Abrir Primer Botón", self)
            self.boton.clicked.connect(self.abrir_ventana_1)

            self.boton2 = QPushButton("Abrir Segundo Botón", self)
            self.boton2.clicked.connect(self.abrir_ventana_2)

            self.layout_principal.addWidget(self.boton)
            self.layout_principal.addWidget(self.boton2)    

        elif titulo == "Tercera":

            self.boton2 = QPushButton("Volver", self)
            self.boton2.clicked.connect(self.abrir_ventana_2)

            self.layout_principal.addWidget(self.boton2
```
Saludos y gracias de antemano :)

**Comment by aaossa** [comment]
Hola @ignaciomansuy , no se pide nada respecto a modificar esa parte del código, así que no falta nada ahí 😅 Solo dos de las ventanas tienen modificaciones, así que no te preocupes porque falte eso. Tienes que modificar solo la función que se pide modificar (y luego agregar las líneas que se piden cuando lo logres) 🍰 ✨  (no había emoji de donut)
