### ISSUE TITLE
AF7: Problemas con entrar en la aplicacion

### ISSUE THREAD

**Issue by kvonstorch** [IIC2233/syllabus#673]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola, estoy teniendo problemas al intentar ingresar al programa (al presionar entre ) me sale que el comando ingresado es invalido en clientes.py y luego que el mensaje no se pudo decodificar en servidor.py, pero al revisar e imprimir los mensajes decodificados estos cumplen con el formato, llevo harto rato intentando solucionar esto e identificar el error, pero no logro.
**¿Alguna sugerencia de que hacer o idea de que lo puede estar generando?**

**Comment by MatiasDuhalde** [comment]
Hola @kvonstorch !

El problema puede tener varias causas, pero es muy probable que el error esté al momento de recibir o enviar los bytes del mensaje. Si se genera un error de cdecodificación en el código, es porque alguno de los mensajes que recibes no cumple el formato JSON, por lo que se cae en esa parte. Un error común es que se incluyen los bytes que representan el largo del mensaje dentro del mismo mensaje a decodificar, lo cual es incorrecto. Intenta verificar lo que recibes con prints, justo antes de llamar a la función de `decodificar_mensaje`.

Otro error que te puede estar pasando es que no manejas correctamente en el servidor el output de `self.logica.manejar_mensaje`, y no le envías al cliente lo que te retorna el mensaje.

Ojalá eso aclare las dudas, y si sigues con errores, pregunta nuevamente!
