### ISSUE TITLE
Como ponerle un target a un Qthread? 

### ISSUE THREAD

**Issue by Kitaps** [IIC2233/Syllabus#674]
Hola, 

estoy tratando de hacer que los enemigos cuando estan en idle se den vueltas. Mi problema es que no logro que cambien de dirección cada 1 segundo.

Lo intenté con QTimers pero me tiró error de 
QObject::startTimer: Timers cannot be started from another thread
que no entendí las respuestas de google. 

Luego intenté hacerlo con Thread normal, pero ahí se queda pegado el Frontend y ahora lo estoy tratando de hacer con QThreads, pero estos no tienen la llave "target".

Como lo debería hacer?
Por ahora lo que tengo es que cada tick, el enemigo avanza en la dirección que esta mirando. Entonces lo que quería hacer es que el enemigo tenga un timer de que cada 1 segundo cambie su dirección.

Gracias

**Comment by iqacevedo** [comment]
@Kitaps al igual que cuando creabas clases con Thread, la función que ejecutan los QThreads es run.
Puedes heredar para definir que hará cada run como aparece en los ejemplos, si quieres probar rápidamente prueba con sobreescribir el método run del QThread con la función que quieres que ejecute. 

Ojalá te sirva !

**Comment by Kitaps** [comment]
See ahora estaba pensando hacerlo así. Onda crear un objeto que herede de QThread y que en su run haga lo que yo quiero. Gracias ;D

**Comment by Kitaps** [comment]
Oh no, 

lo que pasó ahora es que cree Timer que hereda de QThread y que recibe al parent (que es la Entidad Enemigo).

Entonces ejecuto y parte todo bien, (mientras que el run de Timer está en sleep) 
Pero en el momento que hago parent.cambiar_direccion deja de hacer los sleep, ya nada funciona. 

Nose como explicarlo, y no encuentro el error :S
