### ISSUE TITLE
AF7: No logro ingresar el usuario

### ISSUE THREAD

**Issue by piacabrera** [IIC2233/syllabus#674]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

Duda con ingresar usuario

Hola! al correr el código, logro llegar a poner el usuario. Al poner un usuario de los usuarios en usuarios.json me aparece "este usuario esta siendo ocupado por otro cliente" mientras que si pongo mi nombre me aparece "este usuario no esta registrado en la base de datos". Como puedo entrar?

**Comment by MatiasDuhalde** [comment]
Hola @piacabrera !

Los usuarios válidos son los usuarios de github de lxs ayudantes + jefes + profes! Puedes revisar los usuarios válidos en el archivo `db/usuarios.json`, o [acá](https://iic2233.github.io/tas/).

Además, si te sale el mensaje que ya está ocupado, es probable que tengas otra instancia del cliente ejecutándose, por lo que podrías cerrarla si la encuentras o reiniciar el servidor.

Ojalá eso te ayude! :sparkles:

**Comment by piacabrera** [comment]
Lo he cerrado varias veces, pero me sigue tirando el mismo mensaje para todos los usuario validos. Tampoco entiendo porque cada vez que llamo a self.logica.manejar_mensaje, me retorna el diccionario y la lista [0]. Sin importar que usuario ocupe la lista es siempre la misma .

**Comment by MatiasDuhalde** [comment]
El problema puede estar entonces al manejar el diccionario de `self.clientes_conectados` del servidor! Ten en cuenta que en escuchar cliente, tienes que obtener el socket desde ese diccionario con la `id_cliente` que recibe el método como parámetro. También el error podría estar al manejar el diccionario en otro lugar del programa, como al momento de aceptar los clientes.

**Comment by piacabrera** [comment]
Pero al imprimir el mensaje que se obtiene del socket del cliente (que se obtiene del diccionario de clientes),  me lanza todo bien. El mensaje tiene sentido y el usuario  es el correcto. Entonces el diccionario self.clientes_conectados si estaría funcionando.

**Comment by MatiasDuhalde** [comment]
Hola de nuevo!

Estuve revisando tu código, y el problema al parecer es que llamas a manejar_mensaje dos veces (una en un print). Lo que hace manejar_mensaje la primera vez es "inscribir" el usuario, por lo que la segunda vez que lo corras lo va a detectar como logueado y va a denegar el acceso.

**Comment by piacabrera** [comment]
eso eraaaaaa muchísimas gracias!!!!!
