### ISSUE TITLE
Colision entre jugador y enemigos

### ISSUE THREAD

**Issue by sjkinast** [IIC2233/Syllabus#674]
Hola ! quisiera saber que se evaluara en este punto, ya que la colisión con  bloques es mas clara, pero aqui no se si se espera que el pograma dectecte la colisión o también que no halla superposición de las imágenes.

**Comment by IchottMano** [comment]
@sjkinast Hola!

Esto se refiere a dos cosas, en primer lugar a que no se superimpongan las imágenes, es decir que no puedo "volar por sobre" el enemigo como si fuera algun fantasma.
Lo segundo es que el programa debe detectar cuando un jugador toca a un enemigo y acutar acorde a las reglas (perida de vida, entre otras cosas).

Saludos!

**Comment by sjkinast** [comment]
Entonces lo importante es regular que el jugador no pueda  ponerse sobre el enemigo pero no al reves? , es decir el jugador no puede seguir avanzado a la posicion que se encuentra el enemigo pero el enemigo se mueve libremente nomas

**Comment by santilaguna** [comment]
@IchottMano me surgió una duda, cuando un enemigo colisiona con un jugador pierde también una vida (y muere) o sólo es afectado por las bombas?

**Comment by sjkinast** [comment]
Hola! entonces visualmente que hago para representar esta situación que ambos ? podría hacer simplemente que el enemigo pase por sobre el jugador y el parpade o algo así para representar la colisión?

**Comment by Cschavez** [comment]
Hola! Tengo la misma duda y además en caso de que un enemigo hostil atrape al enemigo, lo sigue persiguiendo o se sigue movimiento aleatoriamente?
