### ISSUE TITLE
Versión de python en T07

### ISSUE THREAD

**Issue by akaminetzkyp** [IIC2233/Syllabus#674]
Hola!

Para todas las tareas hemos usado python 3.5.3. Sin embargo, en el enunciado de esta dice que escribamos `python-3.6.1` en el archivo `runtime.txt`. Además, he leído que Heroku se pone un poco mañoso con python 3.5.x.

¿Podemos usar python 3.6.1 para esta tarea?

Muchas gracias!

**Comment by stephichau** [comment]
@akaminetzkyp si, puedes :)

**Comment by akaminetzkyp** [comment]
Gracias!
