### ISSUE TITLE
Error al usar PyQt5 en Visual Studio

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2233/syllabus#674]
Hola! Cuando trato de importar pyqt5 en Visual Studio me corre errores , el código funciona y crea las ventanas pero no se por qué el error sigue apareciendo a pesar de que lee la librería.
![foto1](https://user-images.githubusercontent.com/62029138/82100131-fbce7200-96d6-11ea-9a07-7e12dc82d010.png)
![foto2](https://user-images.githubusercontent.com/62029138/82100155-0b4dbb00-96d7-11ea-9935-19c505b70114.png)

**Comment by KnowYourselves** [comment]
Hola  @RonaldoSosa!

Lo que sucede es que `pylint`, el linter  por default de Python en VSCode (el programa que te avisa en tiempo real de errores en tu código) tiene problemas para detectar correctamente a los módulos de PyQt (desconosco acerca de si es problema de PyQt o de pylint).

En si ese warning no afecta en nada tu programa. Es solo un falso positivo. Si quieres arreglarlo puedes seguir los siguientes pasos:

1. Dentro de VSCode apreta las teclas `ctrl + shift + p`, esto te abrira una pequeña ventana arriba en el centro.
2. Dentro de esa ventana escribe "> Open Settings" y selecciona la opción "Open Settings (JSON)" de la siguiente forma: 
![image](https://user-images.githubusercontent.com/26102039/82100639-90899d80-96e0-11ea-88b6-46c11a89706a.png)
3. Esto abre la configuración de VSCode (que no es más que un archivo JSON). A este archivo agregale la siguiente llave: 

```python
"python.linting.pylintArgs": [
    "--extension-pkg-whitelist=PyQt5"
],
```
4. Una vez guardado el archivo el linter debería dejar de lanzarte ese warning.

Espero haberte ayudado!

**Comment by RonaldoSosa** [comment]
Sii se arreglo el error con PyQt5,gracias :), pero aparecieron otros errores :( ,bueno no son errores tal cual pero no se como dejar de que me aparezcan estos mensajes,además quisiera saber si es común que te aprezcan estos. 
![foto3](https://user-images.githubusercontent.com/62029138/82102429-8914c500-96dd-11ea-811e-5c4492f95a83.png)

**Comment by KnowYourselves** [comment]
Esos no son errores, solo son warnings respecto a PEP-8 y correcta documentación, en general te recomiendo seguirlos, pero no hay ningún problema si los ignoras.

**Comment by RonaldoSosa** [comment]
Entendido , gracias!! :)

**Comment by TdelrioC** [comment]
Tenia este mismo error, fui a las configuraciones y me abrio un archivo con solo un par de llaves {} a las que le agregue 

"python.linting.pylintArgs": [
    "--extension-pkg-whitelist=PyQt5"
],

pero sigue saliendo el error, me imagino que  hice algo mal:
![Captura de pantalla 2020-05-19 a la(s) 17 49 48 (2)](https://user-images.githubusercontent.com/52587183/82382219-9c83a100-99f9-11ea-815b-30c96fc27eba.png)
