### ISSUE TITLE
2.3 Corte en la descripción de los botones 

### ISSUE THREAD

**Issue by Margarita-Paz** [IIC2233/syllabus#675]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

Cuando escribo la descripción en los botones se corta el texto

![image](https://user-images.githubusercontent.com/53887845/95799919-89d17780-0ccc-11eb-866d-254e1669b969.png)

![image](https://user-images.githubusercontent.com/53887845/95799806-35c69300-0ccc-11eb-85a5-ae1869d73c1c.png)

**Comment by aaossa** [comment]
Hola @Margarita-Paz ,

Creo que lo que ocurre es que el *widget* que contiene tus *checkboxes* es muy pequeño. ¿Usaste un `QHBoxLayout` o un `QVBoxLayout`? En ese caso, recuerda agregar los `QCheckBox` al layout y luego usar el *layout* en la ventana (`self.setLayout(layout)`). También podrías probar con un tamaño de ventana más grande en la definición de la clase, pero te recomendaría usar un *layout* si es que no lo estás haciendo ya. 

PS: Ojo con tus *checkboxes*, estás guardando cada instancia en el mismo atributo, por lo que luego no podrás acceder a cada una. Te recomiendo utilizar atributos distintos y usar un `QButtonGroup` (puedes ver [esta referencia](http://zetcode.com/pyqt/qcheckbox/), en particular la parte de "Exclusive QCheckBox")
