### ISSUE TITLE
Modo Invencible

### ISSUE THREAD

**Issue by benjadb** [IIC2233/Syllabus#675]
Cuando el jugador es invencible, puede atravesar a los enemigos o los debe chocar, pero no perder vida??
También, cuando el jugador se hace invencible, es necesario que haya un efecto visual o puedo dejarlo tal cual y que no pierda vidas (en el enunciado no piden hacer efecto visual)?
Muchas gracias

**Comment by Arcoirisky** [comment]
Hola~ 
Las colisiones se mantienen O: sólo no pierde vidas por 5 segundos al tocarlos o sentir las bombas.

Y no es necesario un efecto visual maravilloso pero sería bueno que pudiera saberse de alguna forma que eres invencible y que no sea sólo un error de programar O: 

Cualquier cosa, escribelo en el Readme :D

**Comment by santilaguna** [comment]
@Arcoirisky se podría utilizar el mismo efecto que si obtuviera el power_up juggernaut, sólo que por un tiempo distinto?

**Comment by Arcoirisky** [comment]
Claro c: no pasa por sobre el enunciado uwu

**Comment by naquiroz** [comment]
Cuando dices que las colisiones se mantienen, se refiere a que no puede atravesar el enemigo, tanto cuando tiene inmunidad y cuando no?
