### ISSUE TITLE
Manejo requests GitHub

### ISSUE THREAD

**Issue by maxfreymo** [IIC2233/Syllabus#675]
Al realizar una request desde GitHub a mi servidor en Heroku, en la página de mi app y en el código se lee un bytearray vacío (flask.request.data   = b''). Pero luego, reviso en el webhook de GitHub la respuesta enviada desde mi servidor y si contiene la información. 

Ejemplo: 
- Se abre una Issue
- Código main.py -->  return flask.request.headers.get('X-GitHub-Event') + 'probando comando'
En la página de https://heroku- ..... obtengo un error de unsupported operand type debido a que tengo **NoneType + 'probando comando'**
- Pero en el Response de la webhook de GitHub aparece correctamente **issues probando comando**

El problema es que no puedo manejar la información en mi servidor :(

**Comment by MainScientist** [comment]
Te recomiendo usar el método `request.get_json()`. Prueba usándolo y ve si el problema persiste.

**Comment by maxfreymo** [comment]
@MainScientist El problema persiste en cuanto a que en https://heroku- .... sigo obteniendo un NoneType , pero ahora si puedo trabajar la información en el servidor y por ende manejar los mensajes :D
