### ISSUE TITLE
loadUiType() error

### ISSUE THREAD

**Issue by ewaugh2** [IIC2233/Syllabus#675]
Cuando cargo mi ventana.ui con
`uic.loadUiType(nombre_ventana)`

me aparece el error
`ModuleNotFoundError: No module named 'imagenes_rc'`

Investigué, y averigüe que tiene que ver con las imágenes que le pongo como fondo. Para esto uso el "Resource Browser" del designer creando el archivo "imagenes.qrc", en el cual "grabo las imágenes.
En internet solo dicen que corra el comando
`pyrcc5 resource.qrc -o resource_rc.py`
con "imagenes" como "resource", pero no me funciona, la consola me devuelve el error
`C:\Users\Enrique\AppData\Local\Programs\Python\Python36\Scripts\pyrcc5: File does not exist 'imagenes.qrc'`

Nota: imagenes.qrc está en la misma carpeta que mi ventana.ui. Intenté moverlo a la carpeta
`C:\...\Scripts`
pero no me deja

Que puedo hacer? 
Gracias

**Comment by stephichau** [comment]
Hola! Agrega las imágenes como ```pixmap``` :)

**Comment by naazocar** [comment]
#659
