### ISSUE TITLE
VSC detecta problemas con PyQt5

### ISSUE THREAD

**Issue by ancontardo** [IIC2233/syllabus#675]
Al ocupar VSC, me aparece como problema de código las importaciones de pyqt, pero al correr el programa no me genera ningún problema y si se abren las ventanas, es decir todo bien... Pero es molesto que aparezcan como problema.
Alguien sabe que hacer para que VSC lo reconozca?

**Comment by KnowYourselves** [comment]
Hola @ancontardo!

Esto fue respondido en #674.
