### ISSUE TITLE
AF04 mal revisada

### ISSUE THREAD

**Issue by AAVP** [IIC2233/syllabus#676]
Hola, sé que los mensajes de issues que se abren para corregir nuestras actividades y tareas son automáticos, y es por eso mismo que quise avisar que abrieron una issue para revisar mi AF04 diciendo que estuve ausente en la actividad, cosa que es errónea puesto que ahí está el commit bien realizado en mi repositorio.
Debo decir que si bien no terminé la actividad por un problema personal que me surgió, sí pude avanzar la ventana inicial, por lo que al menos pido que se corrija esa parte.
Muchas gracias por su disposición. Espero su respuesta!
Saludos

**Comment by entamburini** [comment]
Hola @AAVP,

Para futuras referencias, este es una duda administrativa y como tal debe ser enviada a iic2233@ing.puc.cl.

En cuanto a tu problema, será solucionado, gracias por avisar! :wink:
