### ISSUE TITLE
AF7: Error al ingresar nombre y apretar botón "enviar"

### ISSUE THREAD

**Issue by DQPalomera** [IIC2233/syllabus#676]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Duda

Hola!
Tengo un problema al iniciar con ingresar el nombre, me aparece este error:
```python
...omera-iic2233-2021-1\Actividades\AF7\cliente\interfaz.py", line 121, in manejar_mensaje
    comando = mensaje["comando"]
TypeError: list indices must be integers or slices, not str
```
No estoy segura de que se trata o si es por ingresar mal los mensajes al serializar.
Muchas gracias

**Comment by camilagonzalezp** [comment]
¡Hola @DQPalomera!

Al parecer tienes un error en el formato en que se está haciendo el envío de mensajes. Podrías revisar las issues #661 y #662 en las que se tenía un error parecido. Avísame cómo te va!  :)

**Comment by DQPalomera** [comment]
No vi ninguna de esas issues cuando busqué en ningún momento, disculpa 😢 y Muchas gracias! lo logré hacer pero entregué unos minutos tarde xD .

**Comment by camilagonzalezp** [comment]
No te preocupes! Me alegro de que hayas podido hacerlo 😌 

¡Éxito! ✨
