### ISSUE TITLE
problema con el label de los enemigos

### ISSUE THREAD

**Issue by mjgutierrez1** [IIC2233/Syllabus#676]
Hola, cuando los enemigos van a pareciendo en la pantalla no aparecen con la imagen correcta, sino que se abren como una mini ventana. Esto ocurre a pesar de que el código que estoy usando es similar al de los ejemplo en la parte Extra del material de la semana 11, y de que para el personaje principal hice exactamente lo mismo y ahí sí me funciona.

Además el programa se empieza a quedar pegado y lo tengo que cerrar.

**Comment by hanavarrete** [comment]
Si estás siguiendo el ejemplo del material extra, revisa bien que estés entregándole el "parent" (o que está instanciado en la ventana principal). Por otro lado, si se queda pegado puede ser por 10000 motivos. En el material extra se ve que cuando no se usan threads y/o señales, o cuando haces muchas instancias y no las eliminas esto empieza a pasar. Revisa si está pasando alguno de esos casos y nos cuentas como te va. Saludos!

**Comment by mjgutierrez1** [comment]
Gracias por la respuesta.
Sí le estoy pasando el parent, al igual que como lo hice con el personaje principal (que sí funciona). Además la clase Enemigo hereda de QThread al igual que el tercer ejemplo del material extra, que es el ejemplo correcto. No he usado señales para la creación de los enemigos porque creo que no es lo que se debería hacer en este caso (sí lo hago para otras cosas), ya que los enemigos se están creando en el while del metodo run de mi clase BackEnd, que también es un QThread (sólo he implementado el método run de BackEnd, pero no el de los Enemigos aún ya que no quiero hacer nada con los enemigos todavía, sólo quiero que vallan apareciendo en la interfaz). Por último, dado que lambda_etapa es 1/10, al inicio sólo se alcanzan a crear más o menos 3 enemigos hasta el momento en que se empieza a quedar pegado el programa. Por lo anterior, no creo que esos sean los problemas.

Donde me tinca que pueden haber problemas es en:
1) posible modelación circular, pero que en este caso quizás se justifica. El problema es que hice una issue al respecto en https://github.com/IIC2233/Syllabus/issues/666 y no la han contestado todavía.
2) la clase Enemigo hereda de QThread y de Entidad, y no sé si la multiherencia quizás no será muy soportada cuando se usa PyQt5. La razón por la que hago multiherencia acá es porque también la clase PersonajePrincipal hereda de Entidad, ya que así en entidad puedo tener atributos de la posición y angulo para poder manejar bien el movimiento de las entidades (y que en el caso del personaje principal está funcionando perfecto).

**Comment by mjgutierrez1** [comment]
@hanavarrete ¿No podrá ser entonces el problema 2? O más fácil, ¿está bien que mi modelación sea que en el FrontEnd puse self.backend = Backend(), y que en el backend tengo esa clase Backend que es un QThread y que en el while de su método run va creando a los enemigos (que también son QThread)?, pregunto porque quizás estoy modelando mal el problema y por eso después de crear como 3 enemigos el programa deja de responder.

**Comment by mjgutierrez1** [comment]
Ya solucioné este problema
