### ISSUE TITLE
Duda sobre cargar imagenes

### ISSUE THREAD

**Issue by isidorabecker** [IIC2233/syllabus#676]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola, tengo problemas al crear la ventana con la imagen con el ejemplo del cuadernillo 2 de la semana 9, no se porque se me abre la ventana pero sin imagen.

**Comment by aaossa** [comment]
Hola @isidorabecker , en #667 se habla un poco de algo similar, ¿verificaste que tuvieras las imágenes en la misma carpeta o en una ruta relativa a tu código?

**Comment by isidorabecker** [comment]
Muchas gracias, pero ya logré solucionar mi problema !!!
