### ISSUE TITLE
Error con Heroku

### ISSUE THREAD

**Issue by KnowYourselves** [IIC2233/Syllabus#676]
Intentando solucionar mi problema de la issue #673 intente hacer commit y push en git para luego hacer un push en heroku, pero al finalizar el push me pide mis credenciales de heroku, pero me tira error, diciendo que haga heroku login y luego intente hacer el comando de nuevo. Una vez hecho heroku login (exitosamente) hago push de nuevo y me vuelve a pasar exactamente lo mismo.

**Comment by Hernan4444** [comment]
@KnowYourselves puedes mandar una foto con todos los comandos que ejecutas y su respectiva respuesta (o subir un archivo con eso)?? Así podemos hacer un seguimiento mejor a tu error.

Saludos

**Comment by MainScientist** [comment]
Investigando el problema puede ser que esta [pregunta de StackOverflow](https://stackoverflow.com/questions/27810419/git-push-heroku-master-is-still-asking-for-authentication) te ayude.

**Comment by KnowYourselves** [comment]
Bendito seas entre todos los ayudantes 👍
