### ISSUE TITLE
Puntaje por pasar de nivel

### ISSUE THREAD

**Issue by jerosalazar** [IIC2233/Syllabus#677]
En la sección de puntajes, se dice que se le entrega un bonus al personaje cuando pasa de nivel. Este bonus es de aproximadamente 1500 puntos (un poco mas). Si la experiencia necesaria para pasar de nivel es de 1000 puntos, esto quiere decir que cuando pasa de nivel, gracias al puntaje bonus se saltaría un nivel y pasaría directamente al siguiente. ¿Está eso bien o no debería ser así?

**Comment by iqacevedo** [comment]
Hola,

Los puntos que se le dan de bonificación son para gastar en la tienda, no puntos de experiencia, que son los necesarios para pasar de nivel.

Saludos !

**Comment by JaviFerrada** [comment]
Hola, 
No me queda claro el puntaje que se debe usar para comprar en la tienda. Es solo el puntaje especificado en la sección 4.6 Puntaje? El puntaje para pasar de nivel no se considera? Tampoco se considera el puntaje especificado en 4.6 en el puntaje para pasar de nivel?

**Comment by iqacevedo** [comment]
@JaviFerrada para comprar en la tienda se usa el puntaje especificado en la sección 4.6 y los puntos de bonificación.
En la sección 4.2.1 se habla de puntos de experiencia que son disitntos al puntaje normal, esos son los únicos que no se consideran para comprar en la tienda, ya que solo influyen en el progreso del nivel.

**Comment by JaviFerrada** [comment]
Gracias!
