### ISSUE TITLE
Qtimer no se "reinicia"

### ISSUE THREAD

**Issue by raespinoza4** [IIC2233/Syllabus#677]
Hola, estoy intentando implementar un qtimer que ejecute "algo" cada X segundos, y en su segunda iteracion se "muera", lo tengo implementado de la siguiente forma: (escribi el codigo lo mas general posible)

class Timer(QTimer):
    def __init__(self,):
        super().__init__()
        self.timeout.connect(self.run)
        self.start(1000)
        self.runs = 0
        self.daemon = True

    def run(self):
        self.runs += 1
        do_something()
        if self.runs == 2:
           self.stop()

Y lo llamo con:

timer = Timer()
timer.run()

El tema es que se ejecuta solo una vez el run, (que a mi parecer es cuando pongo timer.run())

Estoy iniciando mal el timer ?

**Comment by pcseisdedos** [comment]
No debiera ser timer.start() ?

**Comment by raespinoza4** [comment]
Gracias ! Ya lo logre resolver, efectivamente tenia que ver con el start() pero había que cambiar otra cosa, igual dejo la info por si a alguien le sirve:

Llamé al metodo start() desde afuera del init, pero al parecer lo que solucionó el problema fue guardar el timer en alguna estructura de datos del parent !
