### ISSUE TITLE
Duda ejerc prop 4 s-13 (I/O e imágenes)

### ISSUE THREAD

**Issue by JuanpaBC** [IIC2233/syllabus#677]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola, tratando de hacer este ejercicio, la imagen "imagen_recuperada.jpg" que crea la última función nunca me sale igual que la original, ni siquiera la puedo ver. Me parece que puede ser que elimino mal los ceros, pero la vdd no cacho bn cómo hacerlo bien y todo lo que he tratado hasta ahora me ha fallado,  por si me pueden echar una mano.

Por el momento así estoy quitando los ceros de los chunks en la segunda función:
![image](https://user-images.githubusercontent.com/80859173/123315038-438a1480-d4f9-11eb-9eb1-b991eb5eaafb.png)

Desde ya muchas gracias.

**Comment by tqmbanados** [comment]
Hola! Me parece que tu problema está en la manera en la que quitas los 0s de la imagen. Recuerda que si bien la mayoría de los 0s del chunk son parte de la corrupción y hay que quitarlos, es posible que hayan 0s **no corruptos**. En este caso,  las siguientes líneas también quitarían esos 0s: 
```python
minimo = min(chunk)   # resultado es 0.
while minimo in chunk:    # Mientras haya 0s en el chunk
    chunk.remove(minimo)   # Quita un cero
```
Es decir, tendrás que hacer uso de otros métodos o funcionalidades para hacer bien el proceso. Te recomiendo explorar el método ```strip()``` de ```bytearray```, que funciona igual que en ```str```. Esto puede generar un problema si un chunk parte o termina con 0, pero la probabilidad es mucho menor!

Prueba así y cuéntame cómo te va.
