### ISSUE TITLE
Problemas Instalando Pyqt5 tools Mac

### ISSUE THREAD

**Issue by conyfernandezt** [IIC2233/syllabus#677]
### Prerrequisitos

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)

### Problema

Hola, estaba tratando de instalar todo lo relacionado con PyQt5 pero tuve problemas al tratar de instalar las tools. Al tratar de hacerlo directo por el terminal me tiraba error y depsues cuando intente de descargarlo por la pagina sugerida en la pagina del curso (https://build-system.fman.io/qt-designer-download) y tira otro error

![Screen Shot 2020-10-13 at 3 35 50 PM](https://user-images.githubusercontent.com/69609564/95901979-85f43280-0d6a-11eb-98f5-585ea27f551e.png)
![Screen Shot 2020-10-13 at 3 34 07 PM](https://user-images.githubusercontent.com/69609564/95902006-8db3d700-0d6a-11eb-953d-195ba4cd1e28.png)

**Comment by aaossa** [comment]
Hola @conyfernandezt , perdón por no haber respondido antes pero no tengo ese sistema operativo 😅 Te recomendaría instalarlo de todas formas la verdad, ya que es una fuente de confianza recomendada por el curso. Si prefieres no instalarlo, la verdad no conozco otras formas alternativas de utilizar Qt Designer, por lo que te recomendaría dejar abierta la *issue* por si alguien conoce otra manera de instalarlo 🤔 

PS: Esperemos que gente con macOS se la juege 👀

**Comment by conyfernandezt** [comment]
Hola! No te preocuper :) El problema esque nisiquiera me da la opcion de instalarlo igual. Lo logro descargar pero cuando lo trato de abrir me sale un mensaje que se mide que borre el programa o cancelar la operacion de abrirla.

**Comment by aaossa** [comment]
Al presionar el ❔ no te aparecen más opciones? Lo único que encontré relacionado es [este artículo de Apple](https://support.apple.com/es-es/guide/mac-help/mh40616/mac). ¿Te funciona abriéndolo de esa manera?

**Comment by aaossa** [comment]
Hola @conyfernandezt , para terminar la *issue* (disculpa lo tarde), ¿al final pudiste instalar Qt Designer? Si es así, ¿cómo lo hiciste? De esta manera puede servirle a otras personas ✨ ¡Gracias!

**Comment by conyfernandezt** [comment]
Hola! si lo resolvi.En finder en las carpetas de aplicaciones uno tiene que buscar Qt despues de haberlo descargado y haber transferido el archivo a las aplicaciones. Luego se tiene que presionar cmd y abrir la aplicacion y ahi te dan la opcion de abrirla (si no me equivoco piden que autorices el proceso en ajustes) y ahi funciona

**Comment by aaossa** [comment]
Súper, gracias @conyfernandezt ✨
