### ISSUE TITLE
Usuario a hacer los cambios en el repo. 

### ISSUE THREAD

**Issue by KnowYourselves** [IIC2233/Syllabus#677]
Mi pregunta es la siguiente, cuando una persona le hable a mi bot con alguno de los comandos, que usuario de github debe realizar estos cambios?

Veo tres opciones:

- Hacemos los cambios con nuestra cuenta github
- Asociamos a nuestro bot con una cuenta github alternativa y esta hace los cambios
- Hacemos que una persona tenga que hacer un "login" via telegram con sus datos de github y que los cambios sean hechos con esa cuenta.

Cual de estas ocpiones seria la correcta? o queda a criterio?

**Comment by stephichau** [comment]
opción 2 :)

**Comment by LuisFros** [comment]
Estaba suponiendo que habia que hacerlo directamente desde nuestra cuenta del curso, con un token que tiene los permisos adecuados. Esto nunca se especifica que el repositorio publico debe pertenecer a otra cuenta GitHub. Debo cambiar todo lo que he implementado con respecto a eso?

**Comment by KnowYourselves** [comment]
@LuisFros  puedes crear una cuenta en github y usar esas credenciales, y desde la cuenta con la que creaste el repo le das todos los permisos a esa cuenta sobre el repo!

**Comment by chuma9615** [comment]
@KnowYourselves esto lo logramos haciendo colaborador de nuestra repo a nuestro nuevo usuario creado ? o tenemos que transferirle el repositorio?

**Comment by akaminetzkyp** [comment]
Yo creé una cuenta completamente nueva y el repo que modifico es el de esa.

**Comment by KnowYourselves** [comment]
@chuma9615 Transferirle el repo es más directo

**Comment by TomasSalvadores** [comment]
Dado que para verificar si los comandos del bot fueron ejecutados, solo se necesita necesita el link al repositorio, e incluso esto es lo unico que piden de el en el enunciado... No da lo mismo donde se encuentre el repositorio?
Veo innecesario el crearnos una cuenta nueva para el repo cuando puede ser en la nuestra...
Es obligatoria la creacion de una cuenta especial?

**Comment by chuma9615** [comment]
A mi me flaggearon mi cuenta recien creada con este metodo, ojo
