### ISSUE TITLE
PEP8: Triple "

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#678]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

Estaba recordando un ejemplo de intro, y es el siguiente
![image](https://user-images.githubusercontent.com/66154723/123490680-aacfc380-d5e2-11eb-8253-736b15c528c6.png)
Si quiero usar triple quotes para hacer un string de varias lineas, ¿Cómo puedo hacer para que quede en la misma identación, o esto no es posible? (asumo que si intento identarlo las triple quotes lo tomarán como parte del string)

**Comment by MatiasDuhalde** [comment]
Hola @fernandosmither !

Por defecto, Python toma todos los caracteres dentro de los triple-quotes en consideración al armar el string, esto contando los espacios, newlines, tabs, indentaciones, etc. Por lo tanto, tu string resultante si o si contendrá estos caracteres, y tendrás que tomar una de dos opciones: No indentar nada dentro de estos strings, o hacer cierto procesamiento luego de definirlas.

Para procesarlas, hay varios métodos que puedes usar, en el código a continuación se muestran 2:
```python
import re
from textwrap import dedent

if True:
    if True:
        MI_STRING = """
        Hola!
        Este es un triple-quote string

        En python!!!
        """

print("-"*10, "Comportamiento normal", "-"*10)
print(MI_STRING)

print("-"*10, "Método re", "-"*10)
print(re.sub(r"\n *", "\n", MI_STRING))

print("-"*10, "Método textwrap", "-"*10)
print(dedent(MI_STRING))
```
Output:
```
---------- Comportamiento normal ----------

        Hola!
        Este es un triple-quote string

        En python!!!
        
---------- Método re ----------

Hola!
Este es un triple-quote string

En python!!!

---------- Método textwrap ----------

Hola!
Este es un triple-quote string

En python!!!

```

El método re, funciona usando expresiones regulares, y hace matching de los espacios que hay después de un newline, y los reemplaza por sólamente un newline (carácter `\n`).

El método textwrap, hace uso de esta librería estándar de python, que contiene la función (dedent), la cual remueve las indentaciones antes de cada línea.

Se podrían implementar otros métodos usando `replace` de strings dentro de un loop, pero sería menos eficiente que los listados previamente.

**Comment by fernandosmither** [comment]
> Hola @fernandosmither !
> 
> Por defecto, Python toma todos los caracteres dentro de los triple-quotes en consideración al armar el string, esto contando los espacios, newlines, tabs, indentaciones, etc. Por lo tanto, tu string resultante si o si contendrá estos caracteres, y tendrás que tomar una de dos opciones: No indentar nada dentro de estos strings, o hacer cierto procesamiento luego de definirlas.
> 
> Para procesarlas, hay varios métodos que puedes usar, en el código a continuación se muestran 2:
> 
> ```python
> import re
> from textwrap import dedent
> 
> if True:
>     if True:
>         MI_STRING = """
>         Hola!
>         Este es un triple-quote string
> 
>         En python!!!
>         """
> 
> print("-"*10, "Comportamiento normal", "-"*10)
> print(MI_STRING)
> 
> print("-"*10, "Método re", "-"*10)
> print(re.sub(r"\n *", "\n", MI_STRING))
> 
> print("-"*10, "Método textwrap", "-"*10)
> print(dedent(MI_STRING))
> ```
> 
> Output:
> 
> ```
> ---------- Comportamiento normal ----------
> 
>         Hola!
>         Este es un triple-quote string
> 
>         En python!!!
>         
> ---------- Método re ----------
> 
> Hola!
> Este es un triple-quote string
> 
> En python!!!
> 
> ---------- Método textwrap ----------
> 
> Hola!
> Este es un triple-quote string
> 
> En python!!!
> ```
> 
> El método re, funciona usando expresiones regulares, y hace matching de los espacios que hay después de un newline, y los reemplaza por sólamente un newline (carácter `\n`).
> 
> El método textwrap, hace uso de esta librería estándar de python, que contiene la función (dedent), la cual remueve las indentaciones antes de cada línea.
> 
> Se podrían implementar otros métodos usando `replace` de strings dentro de un loop, pero sería menos eficiente que los listados previamente.

Sublime! Te lo agradezco un montón 👍

**Comment by aaossa** [comment]
Hola @fernandosmither , vengo a colaborar con otra forma. Primero, me llama la atención que el uso de `"""` sea un requisito, pero si es así entonces la solución que te dejaron funciona bien. Te dejo dos formas de hacer lo mismo que tu captura sin usar las tres comillas, y que creo que es más transparente y clara que utilizar `re` o `dedent`:

```python
# Forma 1
# Dentro de una clase...
    def __str__(self):
        return "\n".join([
            f"IntroWallet de {propietario}",
            f"Saldo de introcoin: {saldo_introcoin}",
            f"Saldo de bitcoin: {saldo_bitcoin}",
        ])
```

```python
# Forma 2
# Dentro de una clase...
    def __str__(self):
        return (
            f"IntroWallet de {propietario}\n"
            f"Saldo de introcoin: {saldo_introcoin}\n"
            f"Saldo de bitcoin: {saldo_bitcoin}"
        )
```

**Comment by fernandosmither** [comment]
> Hola @fernandosmither , vengo a colaborar con otra forma. Primero, me llama la atención que el uso de `"""` sea un requisito, pero si es así entonces la solución que te dejaron funciona bien. Te dejo dos formas de hacer lo mismo que tu captura sin usar las tres comillas, y que creo que es más transparente y clara que utilizar `re` o `dedent`:
> 
> ```python
> # Forma 1
> # Dentro de una clase...
>     def __str__(self):
>         return "\n".join([
>             f"IntroWallet de {propietario}",
>             f"Saldo de introcoin: {saldo_introcoin}",
>             f"Saldo de bitcoin: {saldo_bitcoin}",
>         ])
> ```
> 
> ```python
> # Forma 2
> # Dentro de una clase...
>     def __str__(self):
>         return (
>             f"IntroWallet de {propietario}\n"
>             f"Saldo de introcoin: {saldo_introcoin}\n"
>             f"Saldo de bitcoin: {saldo_bitcoin}"
>         )
> ```

Buena!, gracias por la preocupación, pero el uso de `"""` no fue requisito, lo mostré en ese contexto como ejemplo 😅, entonces por lo general profe evita utilizar `"""` ?

**Comment by aaossa** [comment]
La respuesta, como suele ocurrir, es depende. Para el caso que planteas, usar `"""` no es lo óptimo, por cómo se ve el código. Hay veces donde puede ser útil, pero en el ejemplo que diste, yo no lo usaría y tampoco me parece necesario usar librerías externas. Casi siempre ocurre que la solución más simple es también la mejor.
