### ISSUE TITLE
Nueva Semana Pausa Y Tarea 2

### ISSUE THREAD

**Issue by cncosta** [IIC2233/syllabus#678]
Hola que va a pasar con el curso con la semana de pausa que es del 25-30 de mayo?
Además ¿no se subía el enunciado de la Tarea 2 hoy?

**Comment by aaossa** [comment]
Hola @cncosta ambas cosas las anunciaremos a su debido tiempo 😅 La tarea se anunciará pronto, aún no iba ni la mitad del día al momento de esta pregunta (?) Sobre la Semana de Receso, anunciaremos los cambios de fechas necesarios durante la primera mitad de la semana. En todo caso, las fechas relacionadas con la T02 ya considerarán esta semana, como se explicará en el anuncio que recibirán pronto 👌
