### ISSUE TITLE
Duda Kick The Bomb

### ISSUE THREAD

**Issue by llloyola** [IIC2233/Syllabus#678]
Hola! ¿El Kick The Bomb puede activarse mediante alguna tecla? Me gustaría más poder activarlo a voluntad con un botón (estando lo suficientemente cerca de la bomba) que activarlo por proximidad.

**Comment by Sforrego** [comment]
Lo siento pero la idea es que se active por proximidad!

**Comment by llloyola** [comment]
:cries_in_bomberman:
Gracias :(
