### ISSUE TITLE
Problemas botones pausa y salir

### ISSUE THREAD

**Issue by Regenschrim** [IIC2233/Syllabus#679]
Tengo un problema en el juego al agregar los botones de pausa y salir. Resulta que mi personaje no se sigue moviendo porque las flechas (del teclado) están seleccionando los botones, entonces en vez de mover al personaje se están alternando entre los botones. Cómo son dos botones el movimiento del personaje queda limitado y solo se mueve en un cuadrado del juego. ¿Hay alguna forma de arreglar eso? No he podido encontrar información :(

**Comment by lily416** [comment]
Lo del `self.setFocusPolicy(Qt.StrongFocus)` de esta issue #663 me funcionó
Demás que a ti también te sirve :smile:
