### ISSUE TITLE
Conexiones optimas entre cliente servidor.

### ISSUE THREAD

**Issue by Ignacioislae** [IIC2233/syllabus#679]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### ¿Cuando se comnica con un servidor, puede ser optimo que un cliente tenga mas de un socket conectado con este, para comunicar distintos tipos de informacion? ¿O siempre es mejor utilizar 1 socket y solo identificar que tipo de informacion se esta recibiendo (a travez de los primeros bytes)?

Saludos

**Comment by pabloist** [comment]
Hola! 🙌

En general siempre será buena idea que cada cliente este relacionado con el servidor a través de un socket, particularmente por dos motivos:

1.- En una modelación donde contamos con múltiples clientes, incluso miles; los socket nos permiten individualizar a cada uno de ellos, algo así como un ID particular, permitiéndonos también controlar la cantidad de información que ingresa y sale del servidor de forma individualizada. Tener múltiples socket por cliente genera que esto sea mucho más difícil 😅.

2.- El tener un socket particular por cliente también nos permite ahorrar recursos; donde solo se mantienen la cantidad de sockets necesarios para mantener la conexión cliente-servidor. 👌

De todas formas y como sucede siempre en programación, la última palabra la tienes tú; si crees necesaria la utilización de múltiples sockets y los puntos anteriores no son relevantes, no hay nada de malo en que lo realices 🤞, de todos modos te recomendaría que la información de los paquetes venga inserto en ellos, en vez de realizar una modelación con múltiples sockets 💪.

Saludos!
