### ISSUE TITLE
Notificación de creación de Issue.

### ISSUE THREAD

**Issue by KnowYourselves** [IIC2233/Syllabus#679]
En el enunciado dice que al momento de ser creada una issue en el repo el bot tiene que enviar un mensaje.

Mi pregunta es, asumimos que el bot siempre estará asociado solo con un chat de telegram?, o mantemos registro de todas las personas que se han comunicado con el bot y enviamos la notificación a todas?

**Comment by hanavarrete** [comment]
la idea es mantener el registro de todas. Saludos!

**Comment by KnowYourselves** [comment]
Oh sorry, no había cachado!, gracias!
