### ISSUE TITLE
rango de explosion y rango en que te persiguen o escapan

### ISSUE THREAD

**Issue by nmaturana97** [IIC2233/Syllabus#679]
hola, queria saber si podia agrandar estos rangos (multiplicarlos por alguna constante) para que las bombas ataquen de mas lejos y los monstruos te persigan desde mas lejos.

**Comment by fnquinteros** [comment]
Hola! si lo ves necesario, agrega un archivo `constantes.py` con esas constantes y deja escrito en el readme qué hace cada una. De esta forma podemos habilitarlas/deshabilitarlas fácilmente para evaluar. 

Saludos!

**Comment by nmaturana97** [comment]
dale! gracias
