### ISSUE TITLE
instalacion de pyqt5 no me funciona

### ISSUE THREAD

**Issue by elchocman** [IIC2233/syllabus#679]
- **Sistema Operativo:** windows 10
- **Programa a instalar:** pyqt5

- Descripción del problema: instale pyqt5, y pyqt5-tools, cuando los trato de instalar nuevamente me sale "Requirements already satisfied: PyQt5 -sip<...". A la hora de hacer el importe en python y en vsc me dice "ModuleNotFoundError: No module named 'PyQt5' "

**Comment by igbasly** [comment]
Hola @elchocman
Por favor edita tu mensaje (o agrega un comentario) indicando el contexto del error o cual es problema generado :+1:. Ya que sin mayor información no tengo como ayudarte. 

Quedo atento a la nueva información :wink:.

**Comment by igbasly** [comment]
Gracias @elchocman :smile:
Con lo que mencionas se me ocurren dos posibles fuentes del error:
* Tienes más de una versión de python y no utilizaste `pip3` para instalar
* Estás trabajando en un editor, donde el entorno de desarrollo no utiliza python del sistema.

Te pido si me puedes dar más información acerca de como instalaste las librerías, que editor estás utilizando, como estas ejecutando el programa y la información de la versión de python que utilizas al ejecutar.

Espero que me puedas entregar esta información para intentar evaluar el problema 🙌 , quedo atento.

**Comment by elchocman** [comment]
gracias @igbasly , tengo el python version 3.7.8 , intente tanto en el python mismo como en visual studio en un archivo.py, y a la hora de instalar si utilice el pip3, las librerias las instale todas como sale en el istructivo, estoy ejecutando el programa haciendo: import PyQt5 y luego en la proxima linea puse print("hola") , el error que me retorna tanto en python como en visual studio es "ModuleNotFoundError: No module named 'PyQt5' "

**Comment by elchocman** [comment]
ahora descubri que si llamo a un archivo con un codigo que contiene el import PyQt5 desde el cmd de el computador me corre el programa (en este caso que el archivo creaba una ventana donde pedia nombre apellido contrasena etc... ), por lo que tengo entendido PyQt5 esta instalado perfectamente, el problema es que vsc no me lo esta "leyendo". ¿Alguna razon para que esto pase?

**Comment by igbasly** [comment]
@elchocman genial! Eso es una buena señal.
Si, efectivamente puede ocurrir que VSCode esté utilizando otra versión de Python para ejecutar los programas.
Para arreglar esto debes seguir estos pasos:
1. Primero identifica la versión de Python de tu sistema, para ello ingresa en la terminal de tu computador `which python` o el comando que hayas utilizado para correr el archivo que me mencionas (sin el nombre del archivo).
2. En VSCode ingresa `CRTL + SHIFT + P` y selecciona `Python: Select Interpreter`
3. Te aparecerá una lista de versiones y debes seleccionar la que coincida con lo mostrado en el paso 1.
4. Listo! :reside_hands: Ya puedes intentar ejecutar tu programa desde VSCode.

Intenta esto y avísame que tal :+1:
