### ISSUE TITLE
.gitignore oculto

### ISSUE THREAD

**Issue by adbakulic** [IIC2233/syllabus#68]
Hola,
Al crear el archivo .gitignore en pycharm quedó oculto, por lo que no se ve en la carpeta de mi tarea T00 que tengo en mi repositorio. En la terminal ocupé los comandos defaults write com.apple.finder AppleShowAllFiles TRUE  y KillAll Finder para ver si efectivamente estaba en mi repositorio y si está pero oculto. 
¿Qué debo hacer? ¿Dejar el archivo oculto u otra cosa?
Gracias!

**Comment by jeschuwirth** [comment]
Saludos!

Generalmente si un archivo comienza con "." significa que es un archivo oculto, esto es en parte para evitar que el usuario promedio elimine archivos importantes sin saber que hacen, por lo mismo es normal que el .gitignore sea oculto, por lo que no hay problema si lo subes así.

Te recomiendo trabajar con AppleShowAllFiles TRUE para ver siempre los archivos ocultos, pero considera que suelen ser importantes y no se deben alterar a menos que sepas para que sirven.

Suerte en la tarea!

**Comment by adbakulic** [comment]
Muchas gracias!
