### ISSUE TITLE
id orders

### ISSUE THREAD

**Issue by nmaturana97** [IIC2233/Syllabus#68]
Hola, queria saber si en el archivo orders sus ids siempre partiran del 0, es decir, si esque hay orders habra una con 0, otra con 1 y asi para adelante. (Da lo mismo que esten en desorden)

**Comment by stephichau** [comment]
No puedes asumir eso.
saludos!

**Comment by nmaturana97** [comment]
esq tecnicamente mi programa funciona con que se le asigna desde el 0 en adelante las orders y esta (aunque tenga match) queda siempre con el mismo id, por lo que no deberia haber otra cosa en la base de datos. O no puedo hacer mi tarea asi?

**Comment by stephichau** [comment]
La idea es que no hardcodees el código , por lo que te recomiendo ver otra forma de hacerlo
