### ISSUE TITLE
Entrega tarde de la tarea y el commit a elegir

### ISSUE THREAD

**Issue by JulianTR96** [IIC2233/Syllabus#68]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Resulta que ayer hice el último commit de mi tarea a las 9:35 pm y luego, 20 minutos tarde (10:20 pm) hice commit al README.md. Por ello tengo la duda de si el README entregado no se me será considerado y por lo tanto si en el formulario debo entonces escribir el commit que hice a las 9:35 pm o si sí se me considerará y debo colocar el commit de las 10:20 pm. Me parece que tengo hasta las 8 pm de hoy para responder el formulario, así que agradecería mucho una pronta respuesta. 

Sin más que agregar, 
Saludos y buen fin de semana

**Comment by matiasmasjuan** [comment]
Hola @JulianTR96 !

Dado que la hora de entrega del *commit* era hasta las 22:00 hrs, si deseas que el **README.md** **sea considerado** en tu evaluación, entonces deberás usar ese *commit* (22:20) para el formulario de entregas atrasadas. De otro modo, si quieres que el **README.md** no sea considerado, entonces deberás ingresar el *commit* de las 21:35. Por lo tanto, es tu responsabilidad decidir si vale la pena o no considerar el **README.md** sabiendo que la hora de entrega fue a las 22:20, según la guía de [Descuentos](https://github.com/IIC2233/Syllabus/blob/main/Tareas/Descuentos.md#entrega-atrasada-entre-5-20-d%C3%A9cimas-watch).

Saludos! Y que tengas un buen fin de semana! :smile:

**Comment by JulianTR96** [comment]
Muchas gracias Matías,
buen fin de semana.
