### ISSUE TITLE
Test rutas_posibles

### ISSUE THREAD

**Issue by josevalenzuelam** [IIC2233/Syllabus#68]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/20)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/19)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! quería preguntar sobre el test 0 de los test de pruebas para la función de rutas_posibles ya que la respuesta esperada es que sea igual a 2 pero viendo el ejemplo solo veo un posible camino. No se si es un error y debería ser 1 o efectivamente hay 2 posibilidades.
Quedo atenta,
Gracias.

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by SSParzival** [comment]
Hola buenas. 

Para el test_0, las rutas posibles son las siguientes:

D-E-A-B
D-E-C-B

Ello, dado que se pide que exista una cantidad intermedia de dos estaciones, con origen la estación D y final la estación B.

Por lo tanto, es correcto que la respuesta esperada sea 2.

Quedo atento por si tienes dudas sobre el funcionamiento del método `rutas_posibles`.

**Comment by josevalenzuelam** [comment]
Perfecto gracias!
