### ISSUE TITLE
Duda respecto a la creación de grupos

### ISSUE THREAD

**Issue by lfb1206** [IIC2233/syllabus#68]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Al momento de crear un grupo existe la regla de que hayan dos usuarios como mínimo en el grupo.
**¿Son dos usuarios aparte del que crea el grupo (3 usuarios en el grupo) o son dos usuarios contando al creador (usuario que crea grupo + otro usuario)?**

**Comment by IgnaciaJ** [comment]
Hola Lucas! Efectivamente los grupos pueden ser creados por dos usuarios contando al creador. Éxito en la tarea!

**Comment by Bizonte28** [comment]
Hola, en la misma función de crear grupo el enunciado menciona que "Posteriormente, deberás ingresar todos los usuarios que deseas ingresar al grupo separados por ";"
según el siguiente formato: usuario1;usuario2;....". Esto quiere decir que ese formato es una restricción al input, o el programa debe ordenarlo así de manera que cada usuario agregado es un input nuevo?

**Comment by sebvperezg** [comment]
Al añadir integrantes del grupo me pide verificar que existan en el programa. Eso se refiere que verifique si el integrante a añadir es un contacto del usuario? o basta con que este integrante se encuentre en el archivo usuarios?

**Comment by IgnaciaJ** [comment]
Hola @Bizonte28! Tal como tu mencionas es una restricción del input.

**Comment by IgnaciaJ** [comment]
Hola @sebvperezg! Se requiere verificar si el nuevo integrante se encuentre en el archivo usuarios.csv, no es necesario que sean parte de los contactos del usuario.
