### ISSUE TITLE
Authentication Error tratando de clonar mi repositorio a mi equipo

### ISSUE THREAD

**Issue by SebastianFerra** [IIC2233/syllabus#68]
Hola! Cuando trato de clonar mi repositorio a mi equipo, usando url y github desktop, me dice lo siguiente:

![image](https://user-images.githubusercontent.com/69606956/90778956-43aef780-e2cb-11ea-9b8a-9bf5b222a1d7.png)

Ingreso mis datos y me manda el mismo error denuevo, como lo puedo resolver o por que otro método puedo clonar mi repositorio?

**Comment by Juampisaez** [comment]
Hola @SebastianFerra 
No me queda claro como lo estas clonando, lo que deberias hacer es sencillamente copiar el link:

![image](https://user-images.githubusercontent.com/48323752/90814760-96060d80-e2f7-11ea-9c32-bd261ab33a32.png)

Y luego en el path donde quieras clonar la repo, realizar git clone:

![image](https://user-images.githubusercontent.com/48323752/90815234-61468600-e2f8-11ea-90e0-e7ca79a99d75.png)

Eso es lo que no resulta??
Quedo atento a cualquier cosa.

**Comment by SebastianFerra** [comment]
Si, así hice ahora, cuando publiqué esto estaba usando otra cosa muy random, pero ya me funcionó. (perdón por el show :/)

**Comment by Juampisaez** [comment]
Perfecto jajajjaja, que bueno que lo solucionaste
