### ISSUE TITLE
Sensibilidad Simulación

### ISSUE THREAD

**Issue by negutierrez** [IIC2233/Syllabus#68]
¿Qué tan sensible debe ser la simulación de los eventos con el paso del tiempo?... cada minuto, cada hora, etc... Pregunto porque al trabajar minuto a minuto claramente será mas lento que si se hace hora a hora

**Comment by FernandoPieressa** [comment]
Hola!

Los valores de aumento son enteros, es decir si en 1 hora aumenta en X cantidad, no significa que en media hora aumente en X/2, por lo tanto la sensibilidad de los eventos depende de los tiempos entregados en el enunciado.

Saludos!

**Comment by akaminetzkyp** [comment]
@FernandoPieressa no debería ser segundo a segundo? Saludos!

**Comment by FernandoPieressa** [comment]
@akaminetzkyp Buen punto, mi mensaje confundio un poco, me refería a que cada momento a través del tiempo porque es crecimiento continuo. Saludos!

**Comment by negutierrez** [comment]
Hay alguna consideración que se deba/pueda tomar para que no tarde tanto la simulación?

**Comment by rpalmaotero** [comment]
@negutierrez te recomiendo echarle una mirada a https://en.wikipedia.org/wiki/Lazy_evaluation.
