### ISSUE TITLE
Buscar y regar, detectar plagas. Clase DCCultivo

### ISSUE THREAD

**Issue by jtvvtj** [IIC2233/Syllabus#68]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Las funciones buscar_y_regar, detectar_plagas, solamente funcionaran cuando el predio tiene al menos 1 codigo_cultivo?

Ya que me surge la duda, ya que no le veo mucho sentido, que estas funciones se puedan usar, cuando no hayan cultivos presentes en un predio. Ya que regaremos solamente tierra? o detectaremos plagas solamente en la tierra? 

Gracias :)

**Comment by vgalfaro** [comment]
Hola! buscar_y_regar funciona independiente de si hay cultivos o no, pues son planos distintos, respecto a detectar_plagas, debes manejar el caso donde te den un predio y una coordenada donde no haya ningún cultivo, pues ahí no debes eliminar nada, por lo tanto, ambas se pueden usar cuando no hayan cultivos en plano. Saludos!

**Comment by jtvvtj** [comment]
Comprendo gracias por la aclaración, lo había leído aquel día, perdón por no responder !!! sí me había quedado claro antes con lo que me dijiste, gracias!!
