### ISSUE TITLE
Duda sobre el return de tablero_transformado()

### ISSUE THREAD

**Issue by martina-abello** [IIC2233/Syllabus#68]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Leyendo el enunciado, no me queda claro si hay que retornar el tablero original modificado, o un tablero "nuevo" que sea una modificación del antiguo.

Gracias de antemano.

**Comment by Hernan4444** [comment]
Hola,

Se crea un nuevo tablero con lo solicitado. El original (guardado en los atributos) no se debe modificar.

Saludos y mucho éxito con la tarea!

**Comment by martina-abello** [comment]
Oka, muchas gracias!
