### ISSUE TITLE
Nombre archivos

### ISSUE THREAD

**Issue by mvveram** [IIC2233/Syllabus#68]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Me confundí al escribir el nombre de un archivo, ya que le puse mayúscula al nombre, y cuando lo cambie a minúscula y lo mande (`git push`) en el repositorio sigue apareciendo en mayúscula.
¿Cómo puedo arreglar este problema?

Muchas gracias de antemano

**Comment by Emiliax16** [comment]
Hola @mvveram . Hay un comando para cambiar el nombre de un archivo que ya se encuentra en el repositorio. Debes ubicarte en la carpeta donde se encuentra este archivo y poner:
`$ git mv old_filename new_filename`
old_filename es el nombre del archivo y new_filename el nuevo nombre. Si después usas el comando `git status` te mostrará explícitamente que archivo cambiaste, por lo que debes hacer commit y pushear para que se guarden los cambios.
Avísame si esto soluciona tu problema. Saludos!

**Comment by mvveram** [comment]
Hola, al poner ese comando no se actualizo nada. Lo que pasa es que dentro de mi carpeta (repositorio computador) si sale el nombre correcto pero en el repositorio de este sitio, sigue con el nombre anterior.

Si tienes otra manera de cambiarlo sería genial,

Muchas gracias de antemano

**Comment by mvveram** [comment]
Me acaba de funcionar se me estaba olvidando el `.py`.

Muchas gracias
