### ISSUE TITLE
Método eval()

### ISSUE THREAD

**Issue by manuel-2112** [IIC2233/Syllabus#68]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

¿Se puede utilizar el método eval()? Gracias!

**Comment by mmunoz12** [comment]
Hola @manuel-2112! el método eval() se encuentra entre los built-in prohibidos ☠️ y su uso es un 1,0 en la tarea sin discusión 😣. En [este link](https://github.com/IIC2233/syllabus-2020-1/issues/591#issuecomment-616773839) se explica más detallado por qué esta prohibido. Para qué parte querías utilizarlo? Quizás te puedo dar otras opciones, quedo atenta!. Saludos y suerte!

**Comment by mmunoz12** [comment]
Me suena a que quizás no estas poniendo el paréntesis a la función, de la forma `print(registrar_usuario())`. Si tu función tiene `prints` adentro y/o retorna algo, debería aparecer sin problemas. Avísame si te funciona!
