### ISSUE TITLE
Derrota aunque gane la defensa/Bonificaciones de defensa sin utilidad

### ISSUE THREAD

**Issue by Oisangui** [IIC2233/syllabus#68]
Ejemplo: El DCC tiene 30 ayudantes y un B_D de 500. Luego, tiene un P_D de 3500, pero no hace ninguna diferencia si existe o no la bonificación del DCC, ya que al atacarlo con 3000, aunque el ataque sea menor, igual pasa todo el daño a sus otras unidades y edificios, y la cantidad de ataque que necesito para derrotarlo no cambia con esta bonificación. ¿Lo estoy viendo mal?¿deberían cambiar en algo los resultados de un ataque las bonificaciones de defensa de las civilizaciones en términos de daño y derrota?

**Comment by jalliende** [comment]
Quería preguntar lo mismo, la bonificación no te protege de ataques? Solo sirve como estadística?

**Comment by BFFV** [comment]
Hola!
En estos casos se deberá primero superar a la defensa extra que entrega la bonificación antes de empezar a dañar a las murallas:
1) DCC: Se debe superar la defensa extra que proporcionan los ayudantes, pero ellos NO reciben daño debido a esto.
2) La Comarca: Se debe superar la defensa extra de la cantidad de madera, y no afecta en ningún sentido a la cantidad de madera que tiene La Comarca (es decir, no se les quita madera por usar la barricada ni nada por el estilo).
3) Cobreloa: Se debe superar primero una defensa extra equivalente al 10% de la defensa base, antes de empezar a hacer daño.

**Comment by jalliende** [comment]
Es decir que parte del ataque es "absorbido" por la bonificación? La bonificacion reduce el ataque sin recibir daño? y luego si el ataque es mas grande que la bonificación entonces el poder real de ataque es (poder de ataque-bonificacion) ?

**Comment by BFFV** [comment]
Así es, recién después de que la bonificación absorba el ataque, se debe usar lo que resta de poder para hacer daño al oponente.
