### ISSUE TITLE
¿Qué pasa con el perdedor de una batalla?

### ISSUE THREAD

**Issue by llloyola** [IIC2233/Syllabus#68]
A la hora de finalizar una batalla:

1. si gano, el planeta perdedor pasa a ser conquistado?

2. si me ganan, mi planeta deja de ser conquistado?

**Comment by ptflores1** [comment]
Hola !

1. Se responde en 6.4.1 "Invadir el planeta"
2. Aqui no fomentamos la venganza de que el planeta invadido vaya por el tuyo, entonces no conquistas ni eres conquistado pero pierdes tus tropas, es decir te quedas con tu planeta pero sin nadie que lo defienda 😨.

Estos casos son considerando que tu estas invadiendo, si te están invadiendo (archimago)  a ti entonces:

1. No, al parecer este pobre ser no tiene planeta.
2. 8 "Invasion de archimago"

Saludos !
