### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by nmaturana97** [IIC2233/Syllabus#680]
Es realmente necesario añadirlo?
Yo, por mi parte, use otras imagenes y las agregue  a la carpeta Assets, por lo que para que se vea bien esta carpeta debe estar.

**Comment by fnquinteros** [comment]
Hola! Sí, es necesario el .gitignore. Si vas a utilizar imágenes nuevas no las incluyas en el .gitignore, pero incluye dicho archivo de todas formas para no subir todos los demás Assets o archivos innecesarios. 
Saludos!

**Comment by Bneya** [comment]
¿Si uso otras imágenes que están en una carpeta extra que yo cree fuera de **Assets**, le hago .gitignore a Assets, subo mi carpeta y chao?
