### ISSUE TITLE
Notificación acciones en GitHub

### ISSUE THREAD

**Issue by maxfreymo** [IIC2233/Syllabus#680]
¿Tengo que notificar cada vez que se asigne una etiqueta o solamente cuándo la asigno desde Telegram? ¿Puede quedar a mi criterio eso? :D 
La misma pregunta va para todos los comandos.

**Comment by legramsch** [comment]
Segun tengo entendido, cada vez que se ejecuta un comando, se notifica que se hizo..
Las notificaciones que llegan sin ningun comando son cuando se crea una Issue solamente..
Eso cache del enunciado, no estoy 100% seguro

**Comment by rpalmaotero** [comment]
@legramsch eso es correcto.
