### ISSUE TITLE
duda con pqty signal

### ISSUE THREAD

**Issue by feliperojas123** [IIC2233/syllabus#680]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x ] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

mi duda surge en el ultimo ejemplo de la semana 9 parte 4.. en donde en procesador al final usa if self.senal_actualizar:.... printie este self y es un objeto de pyqt etc. con lo cual no entiendo como es que pasa el if

**Comment by aaossa** [comment]
Hola @feliperojas123 ,

Si te fijas, el `if self.senal_actualizar:` verifica que en `self.senal_actualizar` haya "algo". Esto es porque en la definición de la misma clase, el valor del atributo se inicializa como `None` y solo se modifica al conectar las señales en el archivo de las ventanas. Esto, en general, se define de esta manera por dos razones:

1. Para que *front-end* y *back-end* puedan existir de manera independiente (por ejemplo, para que podamos usar el *back-end* sin tener un *front-end*, y
2. Para que el código del *back-end* funcione aún sin conectar la señal, lo que puedes comprobar quitando la línea del `if` y desconectando la señal (comentando la línea donde se hace el `connect`)

Con todo esto en mente, se ingresa al código del `if` solo si es que `self.senal_actualizar` no es vacío (no es `None`), lo que puedes comprobar (nuevamente) comentando la línea del `connect` (`# procesador.senal_actualizar = ventana.senal_actualizar`). Ojalá te sea de ayuda, pero si algo no queda claro pregunta por acá mismo no más 👌 ¡Éxito! ✨

**Comment by feliperojas123** [comment]
graciaaaas me sirvio ene.. te pasaste
