### ISSUE TITLE
pipreqs

### ISSUE THREAD

**Issue by ofvera** [IIC2233/Syllabus#681]
He intentado usar el comando pero no me permite hacer lo que dice en el enunciado.
Lo bajé correctamente, pero al escribir el comando con el path no hace nada,dice:
Usage:
    [option] <path>

**Comment by B-Dominguez** [comment]
ofvera lo solucionaste? y como? porque yo tengo el mismo problema
lo que hice por mientras fue hacerlo con freeze, pero me llena de cosas que no se cuales son innecesarias
