### ISSUE TITLE
Contenidos semana 11, en la T2

### ISSUE THREAD

**Issue by felipehen** [IIC2233/syllabus#681]
Dado que en contenidos ya están subidos los contenidos de la semana 11 desde hace algún tiempo, me había tomado la libertad de leerlos y aprender a usarlos. 

Gracias a esto, me e dado cuenta que pueden resultar útiles para la Tarea, incluso cuando esta fue publicada antes de dicha semana, por eso quería preguntar, ¿podemos usar dichos contenidos en la tarea 2?

**Comment by Alonsinho1** [comment]
Hola!

Algunos de esos contenidos son cruciales para resolver la tarea, por ende deberás utilizarlos :D

En general recuerda que puedes usar el contenido que desees, siempre y cuando no utilices librerías prohibidas.

Suerte!
