### ISSUE TITLE
Duda con metodo fill(Qt.color), en ejercicio propuesto 3.2.

### ISSUE THREAD

**Issue by diego-ayala-2000** [IIC2233/syllabus#681]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

Hola, no logro implementar el metodo fill(Qt.color). He tratado de muchas formas y buscado en internet pero no logro dar en el clavo. Me podrían dar una mano porfavor. 
Gracias

**Comment by sofiaolmedos** [comment]
Tengo la misma duda

**Comment by aaossa** [comment]
Hola @diego-ayala-2000 y @sofiaolmedos , asumo que se refieren al ejercicio 3.3 🤔 ¿A qué se refieren con que no logran implementar el método? El método `fill()` es un método de la clase `QPixmap`, por lo que podemos usarlo sobre una de sus instancias. ¿Quizás les esté faltando el colocarlo en un `QLabel`? Debería quedarles algo así el código:

```python
self.pixmap = QPixmap(100,100)
self.pixmap.fill(Qt.white)  # Qt.blue, Qt.red, etc.
self.label.setPixmap(self.pixmap)
```

Si no se refieren a eso o les falla por alguna otra razón expliquen el error que les produce y cómo se ve (o si no se ve). Éxito ✨

**Comment by diego-ayala-2000** [comment]
Ahí me funciono, muchas gracias. Que determinan los atributos 100,100 que se le ponen?

**Comment by aaossa** [comment]
@diego-ayala-2000 en general te recomiendo probar distintos valores para ver qué ocurre, y también ver la [documentación de `QPixmap`](https://doc.qt.io/qtforpython/PySide2/QtGui/QPixmap.html). Pero de todas maneras te responderé, ya que también lo probé: se refieren al ancho y al alto del `QPixmap`, respectivamente. Puedes comprobarlo cambiando el `(100, 100)` por un `(50, 300)` y viendo cuál es el lado más largo.

**Comment by domingo2000** [comment]
Hola, me funciona el metodo para cuando se instancia la ventana, pero al minuto de usarlo en el keyPressEvent no me cambia el color del cuadrado que defini
``    def keyPressEvent(self, event):
        """
        Este método maneja el evento que se produce al presionar las teclas.
        """
        code = event.key()
        codes = {'A': 65, 'B': 66, 'C': 67, 'D': 68, 'E': 69, 'F': 70, 'G': 71, 
                 'H': 72, 'I': 73, 'J': 74, 'K': 75, 'L': 76, 'M': 77, 'N': 78, 
                 'O': 79, 'P': 80, 'Q': 81, 'R': 82, 'S': 83, 'T': 84, 'U': 85, 
                 'V': 86, 'W': 87, 'X': 88, 'Y': 89, 'Z': 90}

        if code == codes["V"]:
            print("pintando verde")
            self.cuadrado.fill(Qt.green)
            self.label1.setPixmap(self.cuadrado)
            self.label1.setText("Verde")
        elif code == codes["A"]:
            self.cuadrado.fill(Qt.blue)
            self.label1.setText("Azul")
        elif code == codes["R"]:
            self.cuadrado.fill(Qt.red)
            self.label1.setText("Rojo")
        elif code == codes["B"]:
            self.cuadrado.fill(Qt.white)
            self.label1.setText("Blanco")
``
con ese metodo si me cambia el label del color pero no me cambia el color del pixmap, las definiciones de esos elementos las dejo a continuacion
``
        # BitMap
        self.layout_cuadrado = QHBoxLayout()
        self.layout_cuadrado.addStretch(1)

        self.label_cuadrado = QLabel()
        self.cuadrado = QPixmap(100, 100)
        self.cuadrado.fill(Qt.white)

        self.label_cuadrado.setPixmap(self.cuadrado)

        self.layout_cuadrado.addWidget(self.label_cuadrado)
        self.layout_cuadrado.addStretch(1)
``
``        # Label y su Horizontal-layout
        self.layout_texto = QHBoxLayout()
        self.label1 = QLabel("Blanco")
        self.layout_texto.addStretch(1)
        self.layout_texto.addWidget(self.label1)
        self.layout_texto.addStretch(1)
``

**Comment by aaossa** [comment]
@domingo2000 , al parecer lo que te falta es volver a asignarle el `QPixmap` al `QLabel` nuevamente (`setPixmap`). Imagino que esto es así para "notificarle" al `QLabel` que debe actualizarse en la interfaz.

**Comment by domingo2000** [comment]
Aaaa ok, ahi me funcionó gracias!, Y hay alguna razón de porque no se puede repintar el objeto ``QPixMap`` directamente??

**Comment by sofiaolmedos** [comment]
> Hola @diego-ayala-2000 y @sofiaolmedos , asumo que se refieren al ejercicio 3.3 🤔 ¿A qué se refieren con que no logran implementar el método? El método `fill()` es un método de la clase `QPixmap`, por lo que podemos usarlo sobre una de sus instancias. ¿Quizás les esté faltando el colocarlo en un `QLabel`? Debería quedarles algo así el código:
> 
> ```python
> self.pixmap = QPixmap(100,100)
> self.pixmap.fill(Qt.white)  # Qt.blue, Qt.red, etc.
> self.label.setPixmap(self.pixmap)
> ```
> 
> Si no se refieren a eso o les falla por alguna otra razón expliquen el error que les produce y cómo se ve (o si no se ve). Éxito ✨

Ahora me funcionó :D 
Lo unico que cambié fue que el tamño lo estaba estableciendo en el label y no en el pixmap. Pero no entiendo por qué no se podría.

**Comment by conyfernandezt** [comment]
Hola! Tengo el mismo problema implementando el fill. Trata de correr el codigo que señalaron pero me tira error donde dice que 'Qt' no existe.
![Screen Shot 2020-10-15 at 11 42 40 AM](https://user-images.githubusercontent.com/69609564/96145502-a7c0f700-0edb-11eb-80cf-7addfa4fddce.png)

**Comment by aaossa** [comment]
@conyfernandezt es porque no has importado `Qt`: ` from PyQt5.QtCore import Qt`
