### ISSUE TITLE
Problema QTimer

### ISSUE THREAD

**Issue by savelozo** [IIC2233/Syllabus#681]
Hola! Tengo un gran problema :( intento crear un Qtimer para una clase en el BackEnd y no la ejecuta. En teoría está bien definida, el timeout.connect también, pero al hacer start no ejecuta la función. No sé porqué pasa :/ AYUDAAAA!

**Comment by jeharcha** [comment]
Me pasa exactamente lo mismo.
Tengo una clase en el back_end que hereda de QTimer,  con un atributo self.timer que también es un QTimer.  Luego hago:

 self.timer.timeout.connect(metodo_de_clase)
 self.timer.star(1000)

Y cuando instancio la clase, nunca se ejecuta el metodo_de_clase. Es más, he probado con entregarle funciones que solo imprimen un strig en la consola para descartar que sea problema del metodo_de_clase.
Ayudaaaa
Graciasss
