### ISSUE TITLE
Aprender Qt designer

### ISSUE THREAD

**Issue by Juampisaez** [IIC2233/syllabus#682]
Hola, estuve viendo los contenidos de la semana 11, y queria saber si existe un tutorial bueno que se recomiende en el curso para aprender mas sobre Qt designer o si esto lo enseñaran en una ayudantía o algo parecido. Esto lo digo porque en el cuaderno correspondiente, le he dado varias vueltas a lo que dice, pero sigo sin entender bien su funcionamiento.

**Comment by Alonsinho1** [comment]
Hola!

Efectivamente en la ayudantia que viene se explicara su funcionamiento más detalladamente.

Te recomiendo aprenderla bien, ya que es muy util para interfaces! ahorra varias lineas de codigo !

**Comment by Juampisaez** [comment]
Perfecto, y existe algun tutorial recomendado para aprenderlo, los tutoriales que he encontrado en youtube son muy desordenados y no parte de cero.
Me ayudaría mucho para aprovechar el tiempo.

**Comment by Alonsinho1** [comment]
Te recomiendo esperar a la ayudantía con eso deberia ser suficiente. 

Desafortunadamente no conozco ningún tutorial particularmente bueno :/
