### ISSUE TITLE
[Telegram Bot] sendMessage error 401: Unauthorized

### ISSUE THREAD

**Issue by TamaraCucumides** [IIC2233/Syllabus#682]
He estado mucho rato tratando de enviarme un mensaje desde mi bot y me tira siempre el error 401: Unauthorized. 

El chat_id lo estoy obteniendo desde la información que llega cuando yo envío un mensaje al bot, asi que no sé donde puede estar fallando :(

p.d. Ya revisé también que no tengo al bot bloqueado

**Comment by MainScientist** [comment]
¿Verificaste que copiaste bien el access token de tu bot?
