### ISSUE TITLE
Commits a nombre de otro usuario

### ISSUE THREAD

**Issue by v4rgas** [IIC2233/syllabus#682]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Acabo de hacer push a los archivos que habia que subir de la ultima tarea y cuando fui al repositorio a revisar si se habia subido, me paso que el commit se hizo a nombre de un usuario que nunca habia visto.

Me deberia preocupar?

**Comment by lily416** [comment]
Hola @v4rgas, espero te encuentres bien c:

Puedes quedarte tranquilo, ya que según nuestro registro los _push_ de los _commits_ fueron realizados por ti: 
![image](https://user-images.githubusercontent.com/26393515/123868677-05786080-d8fe-11eb-9e45-6b15a531331d.png)

Lo que sí, ten en consideración que si compartes tu computador con otro persona, debes fijarte que al momento de hacer _commit_ y _push_ tu usuario se encuentre logueado de forma local (es decir en la carpeta de tu repositorio personal), ya que así los _commits_ quedarán a tu nombre. 

Saludos y que tengas una buena tarde 👋🤖
