### ISSUE TITLE
Error de "Violación de segmento (`core' generado)"

### ISSUE THREAD

**Issue by Pudindin** [IIC2233/Syllabus#682]
Hola,
A veces, y en cualquier momento durante la ejecución de mi programa, éste de pronto se detiene y en consola lanza el error: "Violación de segmento (`core' generado)". Estuve buscando, y al parecer es un error que se genera en C++ relacionado con punteros y asignación de memoria; pero de lo que no entiendo mucho como para saber cómo arreglarlo. 
Me sería muy útil si alguien pudiera orientarme en torno a cómo se podría generar este error, para solucionarlo, y que así no afecte tanto el desarrollo de mi tarea como su posterior correción.
De antemano, gracias!

**Comment by iqacevedo** [comment]
Hola, 

Antes de mostrar este error, la consola te indica algún _warning_, o algo similar? ¿Que otra cosa dice el error?.

Quedo atento !

**Comment by Pudindin** [comment]
No, la consola no indica ningún tipo de advertencia. No dice nada más. Sólo aparece lo puesto en el título de la issue, y el programa se cierra automáticamente.
Sin embargo, pensé que podría estar relacionado con el uso de QThreads (pues habían dicho que, a causa de estos, el pograma podía caerse; además de que en internet encontré varios foros en los que se hablaba de esta caída de programa con QThreads -todo en C++, con lo que no entendía mucho-). Parece que así fue, pues tan pronto dejé de usarlos (pasé a utilizar QTimers) el error no volvió a aparecer por más veces que corriera el programa. 
Desconozco, aún, a qué se debía el error; pero lo he evitado, de modo que ya no me aparece, y santo remedio.
