### ISSUE TITLE
Un ejemplo de un notebook no me corre en Visual Studio.

### ISSUE THREAD

**Issue by n4chin** [IIC2233/syllabus#682]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola, tengo un problema, en el ejemplo del notebook 3 (específicamente el primer ejemplo después del título Eventos de mouse, Press event) lo corro en Visual Studio y solo me aparece una página en  blanco, nada más, mientras que si lo corro directamente del notebook me corre bien.  Adjunto imagen de lo que me sale, y creo que eso no debería salir. Creo haber instalado bien Pyqt5, y aparte todos los demás ejemplos corren bien, así que me parece raro.

<img width="960" alt="2020-10-14 (1)" src="https://user-images.githubusercontent.com/69605533/96024865-ba2f2800-0e2a-11eb-8cf1-28783b86256c.png">

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by n4chin** [comment]
Dice ejercicio en el título, pero no es solo el nombre, el código es exactamente el mismo que hace el ejemplo, pues quería ver como se vería este.

**Comment by aaossa** [comment]
Hola @n4chin , al parecer es porque tu código no puede llegar a las imágenes desde donde creaste el archivo. Tienes que cambiar la ruta a las imágenes en el código o mover tu archivo *.py a la misma carpeta en la que están los cuadernos para que sea accesible. Esto lo expliqué un poco en la segunda parte de esta respuesta: https://github.com/IIC2233/syllabus/issues/667#issuecomment-706619007. En resumen, ten ojo con las rutas, ya que deberías usar una ruta relativa para que tu código llegue a las imágenes (se habla más de esto en [este cuaderno](https://github.com/IIC2233/contenidos/blob/master/semana-00/3-paths.ipynb) de la semana 0 👌 Si algo no queda claro o sigue sin funcionar, pregunta por acá mismo no más. ¡Éxito! ✨

**Comment by n4chin** [comment]
Muchas gracias!!
