### ISSUE TITLE
QtDesigner para Mac

### ISSUE THREAD

**Issue by raimundomartinez** [IIC2233/syllabus#683]
Hola, al intentar instalar QtDesigner con

pip install PyQt5-tools
y
pip3 install PyQt5-tools

me tiraba el siguiente error:
ERROR: Could not find a version that satisfies the requirement PyQt5-tools (from versions: none)
ERROR: No matching distribution found for PyQt5-tools

En la siguiente publicación de StackOverflow sale que QtDesigner no esta disponible para Mac, o por lo menos no se descarga con esos comandos

https://stackoverflow.com/questions/57512730/cannot-install-pyqt5-tools-could-not-find-a-version-that-satisfies-the-requir

Descargando una cantidad de cosa no se como llegue a tener QtDesigner, pero me hubiera gustado haber tenido una guia paso a paso de como instalarlo, e incluso ahora me gustaría tenerlo para estar seguro que tengo la version correcta.

Agradeceria mucho si suben algun documento asi.

**Comment by tedroppelmann** [comment]
Tengo el mismo problema en mi Mac :( aún no me atrevo a descargar otras opciones...

**Comment by jaimecoloma** [comment]
Estoy igual! Vine buscando si no era el unico, y no se que será mejor :(

**Comment by tomasgv** [comment]
Hola!
Hasta ahora solución más rápida parece ser descargarlo desde [este sitio](https://build-system.fman.io/qt-designer-download). La instalación de la app por este medio resulta más intuitiva que otras opciones, y posee las mismas funcionalidades (si no ven alguna barra de herramientas pueden hacer que aparezcan/desaparezcan desde la pestaña _View_).

Si tienen algún problema con esto no duden en comentar más abajo. Pedimos disculpas por ese comando que se ha vuelto obsoleto para Mac 😔.

¡Éxito con la tarea! ☕
