### ISSUE TITLE
¿Qué pasa si se corta la luz?

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#683]
Hola,
En mi casa está lloviendo y hay viento. Existe una probabilidad de que se corte la luz.
¿Qué pasa si por esto no alcanzo a mandar las últimas versiones antes de que termine el plazo?

Pregunto pensando en que se puede cortar hoy en la noche o durante mañana y eso serían muchas horas -> muchas cosas que puedo implementar y que hasta ahora no he hecho.
He estado haciendo commits y push una o dos veces al día, más menos.

**Comment by jerrymendoza** [comment]
Hola! misma duda...

**Comment by jfbahamondes** [comment]
No sé si se hará algo al respecto en estos casos. Pero una solución sería que te compartieras internet desde tu celular. Y asumo que tu notebook estará cargado para ese caso. Por lo tanto, no debería haber problema. 

Saludos.

**Comment by Hernan4444** [comment]
Hola, Por el momento no se hará ningún cambio en la entrega. Se recomienda que hagan _push_ más seguidos. 2 por día puede ser poco en este caso, recuerden que son gratis y pueden hacer muchos por hora ante cada cambio que hagan y que está funcionando.

**Comment by jerrymendoza** [comment]
Creo que mas que el tema de la entrega, es el poder avanzar... yo hasta hace un rato no tenia luz. Ojala pueden considerar dar unas horas mas.

**Comment by jmwielandt** [comment]
@Hernan4444 @jfbahamondes precisamente me refería al poder avanzar, más que a la entrega en sí, aunque un corte de luz oportuno puede matar el ultimo push 😕

**Comment by bcsaldias** [comment]
Estimad@s,

El plazo de la tarea se mantiene como oficialmente fue estipulado en el enunciado. No porque el mismo día de la entrega hayan habido algunos cortes de luz habrán excepciones. Hay que saber manejar los riesgos (sobre todo porque todos sabemos que estamos en invierno, y el tiempo se anuncia con varios días de anticipación).

Para que no haya problemas con la recolección de sus tareas, daremos hasta las 00:29 para subir. La recolección se hará a las 00:30, sin excepciones. Tienen esos minutos para mitigar los riesgos (carguen sus celulares, usen el paquete de datos, vean cómo subir la tarea en algún lugar, o simplemente hagan push tan antes como puedan).

Solo quedan dos semanas de clases.

¡Saludos y ánimo!
Belén
