### ISSUE TITLE
Extensión del Back End

### ISSUE THREAD

**Issue by paula-ds** [IIC2233/Syllabus#683]
Hola :)  es necesario que todo el código interno esté en el back end o puedo crear un archivo .py aparte e importarlo desde el front end? podría ser como un back end 2 pero no sé si es legal (es para que no quede tan extenso el back end :/)

**Comment by Arcoirisky** [comment]
Si puedes :D Si te refieres a crear más módulos que vayan a tu archivo backend o se comporten como tal. Puedes hacerlo :D

**Comment by paula-ds** [comment]
gracias!
