### ISSUE TITLE
Almacenar información en Heroku

### ISSUE THREAD

**Issue by akaminetzkyp** [IIC2233/Syllabus#683]
Hola!

Como tenemos que tener guardados a todos los usuarios que han hablado con nuestro bot, pensé guardar sus `id` en un archivo `.txt`. Sin embargo, me di cuenta que los servidores de Heroku son *read-only*, por lo que mi programa no puede crear ni modificar un archivo `.txt`.

La información se podría guardar en una variable dentro del programa, pero si este se llegara a caer se perdería toda.

¿Podemos simplemente guardarla como una variable? Si es necesario que la información no se pierda, ¿cómo podríamos almacenarla?

Saludos!

**Comment by MainScientist** [comment]
Sí pueden almacenar la información necesaria en variables. Es importante que expliquen cómo hay que interactuar con su bot para que este no se caiga por la falta de dichas variables. (Si es que hay que ejecutar un comando antes de otro, etc.)

**Comment by akaminetzkyp** [comment]
No habría que correr ningún comando extra. El tema es que si el servidor de Heroku se llega a reiniciar (manualmente o por algun error) se perderían los datos. ¿No hay problema con esto?

**Comment by MainScientist** [comment]
No hay problema.

**Comment by akaminetzkyp** [comment]
Perfecto. Muchas gracias!

**Comment by akaminetzkyp** [comment]
@MainScientist, en mi programa también guardo como variable una lista de las issues que el bot ha comentado (cuando encuentra una excepción). De esta manera, cuando se cierra una issue el bot solo solicita sus comentarios si ve que ya la ha comentado, ahorrándonos muchas solicitudes a Github.

Al igual que con las variables de los `id`, si el servidor de Heroku llegara a reiniciarse (cosa que no debería pasar) se perdería esta información, por lo que es posible que el bot no etiquete alguna issue.

¿Tampoco habría problema con esto?

Saludos! :)

**Comment by Hernan4444** [comment]
@akaminetzkyp como heroku no permite escribir archivos, no te preocupes si se reinicia el servidor. En caso de que pase eso, abriremos una nueva issue con un error de python, esperaremos que el bot la conteste y recién ahí cerraremos la issue para ver si la etiqueta y comprobar el bonus.

Saludos!!

**Comment by akaminetzkyp** [comment]
Muchas gracias Hernan! :)
