### ISSUE TITLE
Uso de sys.exit()

### ISSUE THREAD

**Issue by jorge-ovalle** [IIC2233/syllabus#683]
Para el caso de interfaces gráficas cuál es la diferencia entre escribir app.exec_() y sys.exit(app.exec_()) ? Probé y me resulta exactamente lo mismo.

**Comment by aaossa** [comment]
Hola @jorge-ovalle , muy buena pregunta 👌 . En primer lugar, debes considerar que PyQt5 está basado en Qt, una librería en C++ (otro lenguaje) para desarrollar interfaces gráficas, por lo que el manejo de memoria y otros elementos no depende solo de Python, sino que la misma librería Qt debe preocuparse de eso. Ahora, explicaré cada función, partiendo por la más fácil:

- `sys.exit()`: Lo que hace es simplemente salir de Python, terminando la ejecución del programa (y limpiando la memoria utilizada). Opcionalmente, recibe un argumento que indica el status de salida del programa: 0 si terminó bien, y un numerito distinto indicando si hubo una excepción o error en el programa (más de esto en el curso de Sistemas Operativos)
- `app.exec_()`: Esto es parte de PyQt5, y lo que hace es "ejecutar" la aplicación dando inicio al *loop* de eventos de la interfaz, por lo que tu código se mantendrá en esta línea hasta que cierres la aplicación (la ventana) (como un `join` de *threading* 😮). Puedes comprobarlo comentando esta línea. Verás que la ventana se abre por un tiempo muy pequeño y luego tu programa termina o al menos no funciona como se esperaría. Internamente, cuando termina, hace algo similar a `sys.exit()` y retorna el status de salida, pero de la aplicación/ventana, lo que puedes comprobar guardando el resultado de `app.exec_()` en una variable e imprimiéndola.

Al final, "lo único" que hace la línea `sys.exit(app.exec_())` es:

```python
# Ejecutar loop de eventos de la aplicacion
# (código "suspendido" mientras la aplicación se ejecuta)
status_aplicacion = app.exec_()
# Cuando termina de ejecutarse la ventana, quedamos con un status
sys.exit(status_aplicacion)
# Simplemente pasamos el status de la aplicación a Python para propagar errores si es que hubo
```

Espero que te sirva la respuesta y ahora sepas cómo funcionan estas dos funciones que a simple vista no hacen mucho 😅 Fue una buena pregunta, así que espero haberle hecho justicia con esta respuesta ✨ ¡Éxito con tu estudio de esta materia!
