### ISSUE TITLE
Semana-9: Duda con señales personalizadas y threads.

### ISSUE THREAD

**Issue by Mamunoz42** [IIC2233/syllabus#684]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Holaaaa 😄:

En la materia de la semana 9, archivo 3, al final hablan de *señales personalizadas con threads*, en esta parte no me queda muy claro porque no se crea una clase que herede de ```QObject``` para ahí definir la señal como se hace en los ejemplos anteriores a este.

**Comment by aaossa** [comment]
Hola @Mamunoz42 ,

En este ejemplo la señal no pertenece al *thread*, sino que el *thread* solo tiene acceso a ella, viene "de afuera". Cuando usamos una subclase de `QObject` las señales pertenecen a esa clase y son compartidas por otras, pero no vienen "de afuera". Entonces, para tomar una buena decisión sobre qué usar, en primer lugar tendrías que definir los comportamientos básicos de tus componentes (en este caso la ventana y el *thread*) y luego comunicarlos en una dirección que te haga sentido (en este caso, la ventana debe contener la señal porque es quien la maneja y la señal existe mientras exista la ventana, mientras que un *thread* solo existirá por un corto período de tiempo y solo debe emitir la señal, no contenerla).

Espero se entienda el mensaje, ya que puede ser algo confuso porque en parte también es cómo modelar el problema. Si algo no queda claro pregunta por acá no más 👌 ¡Mucho éxito con tu estudio ✨!
