### ISSUE TITLE
Duda enemigos hostiles

### ISSUE THREAD

**Issue by frduran** [IIC2233/Syllabus#684]
Cuando se dice que un enemigo hostil persigue al personaje principal cuando entra en su rango de visión hasta su muerte, significa que debe perseguirlo aunque después salga de ese rango de visión?

**Comment by ptflores1** [comment]
Hola !
Como se explico en la sala de ayuda, los enemigos hostiles persiguen solo mientras el personaje principal este dentro de su rango de visión, así que no, no debe perseguirlo luego de salir del rango
Saludos !

**Comment by frduran** [comment]
@ptflores1  gracias!
