### ISSUE TITLE
Personalización Labels

### ISSUE THREAD

**Issue by Francisco5674** [IIC2233/syllabus#684]
Hola a todos, me he fijado que en la tarea las imágenes que ejemplifican ventanas de la misma tienen labels con textos muy personalizados, ya sea la fuente, el color, el tamaño, etc, me pregunto si ustedes tendrán una guía con los comandos de personalización de los labels, para que se vean así de bonitos, ademas, ¿es parte de lo evaluado la originalidad de la presentación de la tarea, onda que sea estéticamente atractiva, o solo que se entienda?

**Comment by Alonsinho1** [comment]
Hola, por ahora no tenemos contemplado subir una guia respecto a eso o contenidos adicional al que ya esta subido. La idea es que en esta tarea usen google o otro buscador para aprender cosas nuevas.

Recuerda que no es necesario que tus ventanas se vean igual que las del enunciado, solo basta con que tu aplicación sea funcional

**Comment by Francisco5674** [comment]
OK, pero si hay algo que les agradecería bastante, y es como cambiar el tamaño de la fuente, googleando encontre la forma de centrar los Labels pero no para aumentar el tamaño, ya con eso me quedo tranquilo, muchas gracias!

**Comment by lily416** [comment]
Hola @Francisco5674 

Para personalizar los elementos de tu ventana te recomiendo investigar el método `setStyleSheet()`. 🎨 

Además, cuando instancias un `QFont` se le puede entregar como input el nombre de la fuente y **el tamaño que tendrá** 👀 pero además existen métodos de la misma clase que permiten ajustar el tamaño. Te recomiendo leer su documentación [aquí](https://doc.qt.io/qt-5/qfont.html).

Saludos y éxito en tu tarea 👋✨ 

PS: Si vas a buscar en google, te recomiendo consultar por Qt5 en vez de PyQt5, ya que comparten las clases y funciones, pero se habla mucho más del primero en los foros. 🤓
