### ISSUE TITLE
Error al ejecutar el paso 7

### ISSUE THREAD

**Issue by jiaranda** [IIC2233/Syllabus#684]
Hola,

No puedo terminar el paso 7 con el comando `git subtree push --prefix Tareas/T07 heroku master`, me aparece el siguiente mensaje:
![captura de pantalla 2017-06-23 a la s 19 37 04](https://user-images.githubusercontent.com/26118758/27503619-ae19bd02-584b-11e7-93ed-95408636d105.png)

PD: hice todos los pasos anteriores como dice en el enunciado.

**Comment by Hernan4444** [comment]
@jiaranda intenta poner en el Procfile que use python 3.6.1 y me avisas si funciona

Saludos

**Comment by MainScientist** [comment]
@jiaranda en el archivo `runtime.txt` especifica la versión de python como sale en el enunciado (`3.6.1`).

**Comment by malopez16** [comment]
También tengo un problema :( me aparece esto:
![image](https://user-images.githubusercontent.com/26126519/27505625-951efa98-5872-11e7-8042-f91ad11a352a.png)
![image](https://user-images.githubusercontent.com/26126519/27505631-a3c92190-5872-11e7-878b-8c743f774d78.png)
Hasta ahora he intentado lo siguiente:
-Seguí cada uno de los pasos del enunciado de la tarea, empezando de 0 varias veces (hasta me di cuenta de que Heroku permite tener hasta 5 apps gratis, luego hay que pagar).
-Probé heroku git:remote -a _nombre de mi app_
-Hice login nuevamente a Heroku

y no logro que funcione :(

**Comment by malopez16** [comment]
Aquí está paso a paso lo que hago, tal como dicen las instrucciones, pero me tira error .. Alguna sugerencia?? :
![image](https://user-images.githubusercontent.com/26126519/27505675-dd4a051e-5873-11e7-9d00-5e10e40f3f01.png)

**Comment by Hernan4444** [comment]
@malopez16 
1) si los comandos de esa consola son los únicos que hiciste, todavía no haces git add y git commit
2) el archivo runtime tiene un ligero error con el punto (no va)

Intenta con esas dos cosas y me cuentas.

Saludos!!

**Comment by malopez16** [comment]
Gracias!!
Corregí eso y tb hice la segunda respuesta de este link:
https://stackoverflow.com/questions/4269922/permission-denied-publickey-when-deploying-heroku-code-fatal-the-remote-end

Pero ahora me aparece el mismo error que el OP del issue:
![image](https://user-images.githubusercontent.com/26126519/27505989-9ecf414c-587c-11e7-897d-25956101f7e8.png)

**Comment by MainScientist** [comment]
@malopez16 al parecer tu archivo `runtime.txt` tiene un punto al final de la versión de python. Debería tener `python-3.6.1` sin el punto al final.

**Comment by malopez16** [comment]
Sí! gracias! @Hernan4444 me lo indicó en el comentario y ya lo corregí junto con el link que indiqué. Aunque lo corregí, tira el mismo error

**Comment by MainScientist** [comment]
hiciste `git add` y `git commit` después de modificar el archivo?

**Comment by malopez16** [comment]
@MainScientist Sí! Muchas gracias!
Para poder configurarlo si, hubieron dos temas (a alguien le puede servir):

- Si aparece el error de [éste](https://github.com/IIC2233/Syllabus/issues/684#issuecomment-310812934) comentario, se puede corregir [siguiendo estos pasos](https://stackoverflow.com/a/7993122)

-Recordar hacer git commit y git push

-Si los archivos id_rsa e id_rsa.pub quedaron por algún motivo, siguiendo la guía (que me pasó a mi) en el directorio madre de la repo, se pueden arrastrar directamente a la carpeta de la tarea y funciona.

-Hay que tener mucho cuidado con la syntax de los archivos anexos.

Saludos!

**Comment by felipesilvadv** [comment]
Tengo el mismo error, y al hacer lo que sale en el link que pusiste no se pq no tengo la carpeta .ssh, no esta ni en cd /.ssh ni en cd /home/user_name/.ssh (tengo ubuntu) no se donde más buscar la carpeta, o si saben de otra forma de resolverlo, ayuda porfa

**Comment by felipesilvadv** [comment]
Ahora logre hacer las key que salian, pero no logro hacer la parte en la que hay q usar la frase q piden crear, no se si no estoy entendiendo q hay q hacer o si no me esta funcionando, probe hacer git clone git@heroku.com:stark-dawn-1234.git -o heroku, tambien probe usando ssh-scankey con la key generada, pero ninguna de esas cosas hace algo util

**Comment by Dunkan1** [comment]
@felipesilvadv  prueba con heroku git:remote -a  app-name

**Comment by felipesilvadv** [comment]
@Dunkan1 eso hice y funciono muchas gracias !!

**Comment by jiaranda** [comment]
@Hernan4444 @MainScientist 
Hice el cambio y funcionó! Gracias!!
