### ISSUE TITLE
Problema pipreqs y paso 7

### ISSUE THREAD

**Issue by chapito96** [IIC2233/Syllabus#685]
Instalé la librería pipreqs, pero tengo problemas para el comando  pipreqs /path/a/T07.
Después usé py -m pipreqs /path/a/T07 (análogo a lo que hago cuando uso pip install) y me dice:
"No module named pipreqs.__main__; 'pipreqs' is a package and cannot be directly executed".
Finalmente decidí probar creando el requirements.txt manualmente con Flask==0.12.2 en la primera linea y pasar al paso 7. Al pushear no mostró error, pero al abrir en enlace aparece el "aplication error"

**Comment by MainScientist** [comment]
La libreria es solo para escribir el archivo requirements.txt. Puedes usar el comando `heroku logs` para ver por qué no funciona tu aplicación.

**Comment by chapito96** [comment]
Evito poner el pantallaso porque es enorme.
2017-06-24T00:34:30.358789+00:00 heroku[web.1]: State changed from crashed to starting
2017-06-24T00:34:35.290551+00:00 heroku[web.1]: Starting process with command `flask run --host=0.0.0.0 --port=22145`
2017-06-24T00:34:40.621716+00:00 heroku[web.1]: State changed from starting to crashed
2017-06-24T00:34:40.450815+00:00 app[web.1]: Traceback (most recent call last):

Luego en la parte que dice error de todas las lineas (asumo que eso tengo que buscar):
RuntimeError: Working outside of request context.

**Comment by MainScientist** [comment]
Qué tienes escrito en el archivo `Procfile`? Lo de working outside of request context me suena a que estás usando la variable `flask.request` antes de/durante el setup de la app.

**Comment by chapito96** [comment]
Dentro de Procfile tengo "web: flask run --host=0.0.0.0 --port=$PORT"
Me parece que tienes razon con lo del flask request, pero de igual manera no logro hacer funcionar la app

**Comment by asdegoyeneche** [comment]
Hola! Instalé `pipreqs` pero al ejecutar el comando "pipreqs path/a/T07" me retorna que no encuentra el comando:

> $ pipreqs "/Users/asdegoyeneche/Desktop/UC/2017 - 1/Programacion Avanzada/Github/asdegoyeneche-iic2233-2017-1/Tareas/T07"
> -bash: pipreqs: command not found
 
Busqué en google pero no entendí bien que hacer :s . Tampoco me funcionó el comando `heroku logs`

**Comment by chapito96** [comment]
Yo no logré usar el pipreqs, tuve que crear el archivo a mano (no es muy complicado).
Tanto pipreqs como heroku (incluido logs) se usan desde la cmd directamente, no desde un bash. Prueba con eso

**Comment by asdegoyeneche** [comment]
Buena dale, lo hice a mano alfinal también. Gracias!
