### ISSUE TITLE
mal funcionamiento de herencia y señales en una clase

### ISSUE THREAD

**Issue by mjgutierrez1** [IIC2233/Syllabus#685]
En mi clase Enemigo tengo una señal que informa al frontend cada vez que se mueve un enemigo para actualizar su posición. Además, mi clase enemigo hereda de QThread y de Entidad, donde Entidad es la clase de todos los personajes (enemigos y personaje principal). Sin implementar la señal, los enemigos se instancian correctamente. Al ponerle la señal como atributo a la clase Enemigo, cada vez que se instancia un enemigo tira el error "RuntimeError: super-class __init__() of type Enemigo was never called pyqtSignal".

Creo que esto pasa por la herencia, ya que si hago que Enemigo no herede de Entidad no ocurre ese error al implementar la señal. ¿Por qué está ocurriendo este problema?¿cómo lo puedo solucionar?

**Comment by hanavarrete** [comment]
Supongo que el problema es por la multiherencia, y a priori no sabría decirte el motivo en específico debido a que no se como lo implementaste. La solución parche sería que hagas una clase Entidad que herede de Qthread, y luego otra que herede de entidad, manteniendo el orden de la herencia. Con tan poca info no se de que otra manera puedo ayudarte :(

**Comment by iqacevedo** [comment]
Sé que no es el mismo error, pero tal vez [esta pregunta](https://stackoverflow.com/questions/12280371/python-runtimeerror-super-class-init-of-s-was-never-called) pueda servirte a entender mejor tu error.

Saludos
