### ISSUE TITLE
Archivos avance

### ISSUE THREAD

**Issue by mariagonthier** [IIC2233/syllabus#685]
Hola! En el enunciado sale que hay que cargar el mapa a partir de la información de datos.csv. ¿Puede ser que se referían al archivo mapa.csv? Si no es así, no entiendo bien como puedo utilizar la información de datos.csv en la cargada del mapa. 
Gracias!

**Comment by lily416** [comment]
Sí tienes razón debería salir `mapa.csv` en vez de `datos.csv`.
Prontamente subiremos una versión del enunciado con eso corregido.

Gracias por avisar 😄 
Saludos y éxito en la tarea 👋☕
