### ISSUE TITLE
Problema con Qlabel

### ISSUE THREAD

**Issue by nicolaszanni** [IIC2233/syllabus#685]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola, mi problema recae en un error que me tira VSC con  el Qlabel, lo importo correctamente como se menciona en los notebooks, añado lo de pylint en el settings.json que se meciono en una issue anterior y no cambia. Lo raro es que a veces me funciona y a veces no, por ejemplo, si ocupo un:
```python
self.fondo = Qlabel(self)
```
Me funciona correctamente
Incluso, cuando copio y pego algo de los notebook tipo:
```python
self.algo = Qlabel(texto, self)
```
Tambien me funciona correctamente, pero cuando lo hago yo(Lo que esta comentado):

![Captura de pantalla 2020-10-15 a las 00 46 08](https://user-images.githubusercontent.com/69498312/96074753-ca252700-0e7f-11eb-9ef1-a099fe4ca0aa.png)

Me tira el error `name Qlabel is not defined` .
Trato de ejecutarlo por el terminal pero el programa no se ejecuta. Es raro porque si comento tales lineas en la foto y `self.fondo = Qlabel(self)` se mantiene, el programa se ejecuta correctamente.

**Comment by aaossa** [comment]
Hola @nicolaszanni , creo que no estoy entendiendo bien el problema. ¿En un mismo código te funciona crear `QLabel`s en una parte pero en otra no? Me parece bastante raro, lo único que se me ocurre es que en el código del programa de la foto no estés importando `QLabel` (`from PyQt5.QtWidgets import QLabel`). Si no es eso, ¿podrías subir un ejemplo mostrando en qué parte el `QLabel` funciona y en cuál no? ¡Gracias!
