### ISSUE TITLE
Ayuda con QWidget y setParent()

### ISSUE THREAD

**Issue by CristobalHV** [IIC2233/Syllabus#685]
En mi tarea estoy trabajando con un QWidget al que le voy añadiendo child widgets y todo iba bien, hasta que intentando hacer aparecer los power ups en pantalla con un child widget, este no reconocen al widget padre.

En un intento de corregir esto, al child widget le paso en el __init__ el widget padre y en el mismo __init__ ejecuto el método self.setParent(widget_padre) pero ni siquiera así me deja establecer la relación, ¿que puedo hacer para solucionar esto? :(

**Comment by jerrymendoza** [comment]
No soy ayudante, pero si el widget lo guardas como self.widget_padre?

**Comment by CristobalHV** [comment]
en mi código tengo al widget padre y voy instanciando child widgets dentro de un diccionario ( self.diccionario[llave] = ChildWidget )

Esto me funciona con todos los widgets que llevo hasta ahora, excepto el que estoy tratando de implementar que corresponde a los power ups

**Comment by iqacevedo** [comment]
Hola! 

Podrías probar entregándole a los hijos el padre mediante `widget.parentWidget()` cuando Los instancias para que tengan el parent desde siempre. Si no funciona trata de probar esa función en los hijos y ve que te está retornando para ver cuál es su padre o si no tiene bien ninguno (retornarían 0).

Saludos !
