### ISSUE TITLE
Animacion de atacar

### ISSUE THREAD

**Issue by ciquezada** [IIC2233/Syllabus#686]
Hola!, ¿es necesario que haya una animación especial para atacar?, ¿no basta con solo poner la bomba y que esta sea animada?

**Comment by santilaguna** [comment]
yo pensé que se refería a que la explosión fuera animada, supongo que queda a interpretación de cada uno como no esta especificado¿?

**Comment by rihanuch** [comment]
¡Hola @santilaguna !

No, no es necesario que haya una animación para atacar

¡Saludos y éxito! 🍀
