### ISSUE TITLE
Problema al hacer git add

### ISSUE THREAD

**Issue by Fer5842** [IIC2233/Syllabus#686]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).

### Problema
 Hola, al intentar hacer git add me sale este problema:

PS C:\Users\ferny\OneDrive\Escritorio\Progra Avanzada\Fer5842-iic2233-2024-2\Tareas\T4> git add cliente/
fatal: Unable to create 'C:/Users/ferny/OneDrive/Escritorio/Progra Avanzada/Fer5842-iic2233-2024-2/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
PS C:\Users\ferny\OneDrive\Escritorio\Progra Avanzada\Fer5842-iic2233-2024-2\Tareas\T4>

Que puedo hacer para solucionarlo?

**Comment by vicho14** [comment]
Hola!, primero te recomiendo revisar si no tienes alguna otra consola de la terminal abierta además de la que estás ocupando para hacer push, porque en principio ese es el error que te está indicando. Prueba eso en primera instancia para ver si descartamos que sea ese el problema o es otro. Quedo atento a tu respuesta :).

**Comment by Fer5842** [comment]
Hola, revise y me parece que no tengo ninguna otra consola abierta.

**Comment by vicho14** [comment]
C:/Users/ferny/OneDrive/Escritorio/Progra Avanzada/Fer5842-iic2233-2024-2/.git/index.lock creo que este archivo está evitando que hagas commit. intenta borrarlo y hacer git add así

**Comment by Fer5842** [comment]
No lo había visto, pero al final (siguiendo una sugerencia de la profe) volví a clonar el repositorio y de ahí lo pude subir bien. En todo caso muchas gracias.
