### ISSUE TITLE
Funcion exec

### ISSUE THREAD

**Issue by raimundomartinez** [IIC2233/syllabus#686]
¿Porque el uso de funcion exec es automáticamente un 1,0 en la Tarea 2? Pense que era necesario usar esta función para que se ejecute la aplicación. En la Semana 9 lo usamos todo el tiempo y no hay nada que indique que es una mala práctica. Un ejemplo de su uso es el siguiente:

if __name__ == '__main__':
    app = QApplication([])
    ventana = MiVentana()
    ventana.show()
    sys.exit(app.exec_())

**Comment by DaHunterTime** [comment]
Según yo se refiere a que el built-in exec() no está permitido.
El método exec_() de tu aplicación es necesario para que funcione y por lo tanto si se puede usar.

Si quieres saber más sobre exec() (el built-in) revisa la documentación de python:
https://docs.python.org/3/library/functions.html#exec

**Comment by KnowYourselves** [comment]
Hola @raimundomartinez!

Lo que dice @DaHunterTime es correcto. La función exec de PyQt5 no tiene nada que ver con el _builtin_ de Python `exec`.

**Comment by raimundomartinez** [comment]
Dale. Gracias por la aclaración!
