### ISSUE TITLE
bonificacion de vida

### ISSUE THREAD

**Issue by bedefrunner** [IIC2233/Syllabus#686]
Hola! Mi pregunta se parece a la #672 pero no ha sido respondida. El enunciado dice:

>De este modo, la vida máxima se define como el _tamaño actual_ x 20 + 100 + C, donde C son las bonificaciones externas obtenidas durante el juego.

Y en la parte de objetos de la tienda, se dice:

> Vida: este objeto aumenta la vida total de tu personaje. Su precio es de 750 puntos y la bonificación que entrega es de 20 % sobre el valor actual.

Al parecer, el objeto "vida" de la tienda no aumenta la vida máxima, solo aumenta la vida actual en un 20%. Cómo aumentar, entonces, la vida máxima mediante bonificaciones? O es que el objeto "vida" de la tienda aumenta tanto la vida actual como la máxima en un 20%? Y qué pasa si se tienen dos o más objetos de "vida" de la tienda? Se aumenta la vida actual en un 20 x n % (siendo n la cantidad de objetos vida)?

**Comment by iqacevedo** [comment]
Hola,

Hace poquito respondimos #672. Es la vida máxima la que aumenta, respecto a si la vida actual aumenta con ella, esto no está especificado, por tanto queda a tu criterio (especificalo en el README).

En el caso de los dos objetos el aumento deberías ser algo así:
1. Vida actual sin objetos =  tamaño actual x 20 + 100
2. Con el primer objeto: 
Vida Actual = tamaño actual + 100 + 0.2 x (tamaño actual + 100)
3. Con el segundo objeto:
Vida Actual = tamaño actual + 100 + 0.2 x [tamaño actual + 100 + 0.2 x (tamaño actual + 100)].

Espero quede más claro.
Saludos !

**Comment by rihanuch** [comment]
al punto 2 y 3 no le falta el *20?

**Comment by iqacevedo** [comment]
@rihanuch siiii ya lo edite
Gracias !!!!

**Comment by rihanuch** [comment]
Ok gracias!!!

**Comment by JaviFerrada** [comment]
En el caso del 2 y 3  no debiese ser *20 también lo del paréntesis? 
  tamaño actual x 20 + 100 + 0.2 x (tamaño actual * 20  + 100) 
  tamaño actual x 20 + 100 + 0.2 x [tamaño actual * 20 + 100 + 0.2 x (tamaño actual * 20+ 100)]

**Comment by iqacevedo** [comment]
@JaviFerrada si tenía un error de arrastre ahí 😅.
Ya está corregido.

Gracias !!!
