### ISSUE TITLE
Pyqt5

### ISSUE THREAD

**Issue by FlorenciaSciaraffia** [IIC2233/syllabus#686]
- **Sistema Operativo:** Windos
- **Programa a instalar:** Pyqt5

- Foto del error:
<img width="689" alt="Captura de pantalla 2020-10-15 124721" src="https://user-images.githubusercontent.com/69690009/96153907-9a5c3a80-0ee4-11eb-88a9-f959fb907b19.png">
- Descripción del problema:
No me funcione el Pyqt5 importar los widgets y si tengo instalado pyqt5

**Comment by aaossa** [comment]
Hola @FlorenciaSciaraffia, puede ser que la versión de Python en la que instalaste `PyQt5` no sea la misma que estás usando en tu editor:

![imagen](https://user-images.githubusercontent.com/10425834/96154424-29695280-0ee5-11eb-90a9-6d36008538fc.png)

Prueba también corriendo el mismo programa desde fuera de VS Code, por ejemplo desde cmd. Si ninguna de esas cosas te funciona, avisa por acá mismo y seguimos probando cosas 👌

**Comment by FlorenciaSciaraffia** [comment]
<img width="538" alt="Captura de pantalla 2020-10-15 125945" src="https://user-images.githubusercontent.com/69690009/96155494-5cf8ac80-0ee6-11eb-9998-73730d57d2d8.png">
<img width="325" alt="Captura de pantalla 2020-10-15 125958" src="https://user-images.githubusercontent.com/69690009/96155498-5e29d980-0ee6-11eb-997c-c1a2995360fc.png">

<img width="674" alt="Captura de pantalla 2020-10-15 130053" src="https://user-images.githubusercontent.com/69690009/96155594-7b5ea800-0ee6-11eb-8883-532a7196655f.png">
No me funciona:(

**Comment by aaossa** [comment]
@FlorenciaSciaraffia parece que no estás corriendo el código como corresponde, sino que línea por línea. ¿Podrías revisar https://github.com/IIC2233/syllabus/issues/645 y ver si corriéndolo de esa manera funciona bien?

**Comment by FlorenciaSciaraffia** [comment]
ya habia intentado con el terminal! sigue sin correr 
osea se me abre la ventana pero no logra importar el pyqt5widgets

**Comment by FlorenciaSciaraffia** [comment]
Osea si corre, pero no me funciona el import de los widgets

**Comment by FlorenciaSciaraffia** [comment]
<img width="575" alt="Captura de pantalla 2020-10-15 131030" src="https://user-images.githubusercontent.com/69690009/96156786-dcd34680-0ee7-11eb-8c3f-a782454887b4.png">

**Comment by aaossa** [comment]
@FlorenciaSciaraffia esos parecen ser *warnings* de `pylint`, la ventana te funciona bien? Para esto podría servirte esta *issue*: https://github.com/IIC2233/syllabus/issues/664
