### ISSUE TITLE
T3: Problemas con connect() de TCP

### ISSUE THREAD

**Issue by amondinellir** [IIC2233/syllabus#686]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola! Estoy teniendo problemas al conectar el servidor con el cliente ya que no logra nada, e incluso intenté ejecutar los ejemplos que vienen para estudiar y tampoco funcionan, asi que no se que puede ser. Sé que el cliente y el servidor van en módulos distintos. Espero que me puedan ayudar.

**Comment by pabloist** [comment]
Hola!

Es difícil identificar el problema con la información que nos indicas 😅, ¿Podrías subir tu código a tu repositorio para echarle una mirada? Así podremos saber si existe a lo mejor algún problema con tu máquina en particular.

Saludos!

**Comment by amondinellir** [comment]
Ya lo subí. Espero que se solucione!

**Comment by pabloist** [comment]
Por lo que puedo ver el código está bien y funciona correctamente. ¿Qué error te aparece particularmente? ¿Has podido conectar clienta-servidor antes?

**Comment by amondinellir** [comment]
Si pude hacer esa conexión antes cuando estudié los contenidos de la semana. En mi código imprime "1" y después imprime "[Cliente] Ocurrió un error". Asi que me imagino que el error están en connect().
