### ISSUE TITLE
duda asignacion de labels

### ISSUE THREAD

**Issue by chuma9615** [IIC2233/Syllabus#687]
Me surgio una duda, en el enunciado sale lo siguente

![captura de pantalla 2017-06-23 a la s 22 10 33](https://user-images.githubusercontent.com/26102376/27504868-8e6d3546-5860-11e7-9645-28af23e2e47f.png)

en el comando 
`/label #num issue label`

podemos asumir que se le asignara una label ya creada en el repo?

**Comment by Hernan4444** [comment]
@chuma9615 no pueden asumir eso, la api de github posee todos los comandos suficientes para solucionar ese problema.

Saludos!!

**Comment by chuma9615** [comment]
Ok, otra cosulta, el comando `/get #num_issue` que debe ejecutar?, no es lo mismo que el comando `/post #num issue *respuesta` ?

**Comment by Hernan4444** [comment]
`/get #num_issue ` te da la información de esa issue. Puedes usar el mismo formato que está en el enunciado (autor, numero de issue, titulo, texto principal y link) o agregar mas cosas como numero de comentarios, ultimo comentario, etc.

`/post #num issue *respuesta` escribe un comentario en la issue indicada.

Saludos!!
