### ISSUE TITLE
Problema con Git

### ISSUE THREAD

**Issue by jamigone** [IIC2233/syllabus#687]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

Hola! Intenté hacer _git push_ para descargar el enunciado de la tarea 3, pero Git Bash me lanza el siguiente error (ver imagen). Este ocurre al intentarlo no solo en la carpeta Syllabus, sino también en las otras del curso. 😮

![imagen](https://user-images.githubusercontent.com/50121013/123871849-3eb2cf80-d902-11eb-960d-d9acf2c9a438.png)

**Comment by ivannateresa** [comment]
Hola! @jamigone 

Para actualizar el syllabus, para descargar el enunciado de la T3 tienes que hacer _git pull_ en la carpeta 😄.

**Comment by jamigone** [comment]
@ivannateresa  OHH, me traspapelé de comandos. Qué vergüenza jajjaja, muchas gracias 😅

**Comment by ivannateresa** [comment]
@jamigone  De nada! ✨😄✨
