### ISSUE TITLE
"Radio" en vez de "Size"

### ISSUE THREAD

**Issue by pnheinsohn** [IIC2233/Syllabus#687]
Como todas las entidades tienen un size (1 al 10), lo que debe ser reflejado en la interfaz gráfica, ¿No es mejor usar el radio de estas imágenes para ver los cálculos, por ejemplo la cercanía de las bombas, y la vision de los enemigos?? Lo anterior porque esta distancia toma el (x, y) de las entidades, entonces dichos rangos terminan siendo muy pequeños. Por ejemplo si tengo una bomba de 62x62, su radio de 10 (segun enunciado) implica que el daño de la bomba es menor a su tamaño, por lo que sería mejor usar una función, por ejemplo,

radio = 15.5 * size / 2,

para simular el área de efecto y ver distancias para los calculos.
Lo mismo aplicado al rango de escape, vision, etc.

**Comment by iqacevedo** [comment]
Hola,

Si consideras que tu programa queda mejor con ese ajuste en el cálculo, puedes hacerlo especificándolo en el README. En todo caso siempre es bueno que dejes ese tipo de variables en un archivo constantes.py, de tal manera que un ayudante pueda cambiarlos fácilmente al revisar (en caso de que quiera dejarlo como salía en el enunciado).

Saludos !
