### ISSUE TITLE
Explosión enemigos

### ISSUE THREAD

**Issue by Jj1martinez** [IIC2233/Syllabus#687]
Cuando hay mas de un enemigo dentro de la misma línea de explosión, deben morir todos? O solamente el primero con que choca, como si fuera un muro
Gracias

**Comment by ptflores1** [comment]
Hola !
Se pensó para que murieran todos, pero si quieres puedes hacer que muera solo el primero.
Saludos !

**Comment by Jj1martinez** [comment]
Dale dale
