### ISSUE TITLE
Clientes por mesa

### ISSUE THREAD

**Issue by M-Altamirano** [IIC2233/syllabus#687]
Hola! En el enunciado se dice que cada cliente puede usar solo una mesa. Era eso lo que querían decir o que cada mesa solo puede tener un cliente? Gracias!

**Comment by jitorcas** [comment]
Hola!
Queríamos decir que **cada cliente debe estar en una mesa** para ser atendido y cada mesa puede estar **usada por solo un cliente a la vez**. Eventualmente si una mesa se desocupa **puede recibir otro cliente**.
Saludos y espero haya respondido tu duda.

**Comment by M-Altamirano** [comment]
Si, la responde. Gracias!
