### ISSUE TITLE
Error al ejecutar archivos en vsc 

### ISSUE THREAD

**Issue by mleon17** [IIC2233/syllabus#687]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

[Describe tu duda de manera detallada, explicando los contenidos en cuestión y ojalá colocando código o un caso de uso de ejemplo]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by mleon17** [comment]
Hola! trato de correr los ejercicios de materia de jupyter en vsc pero muchos de ellos no se ejecutan correctamente. Como puedo saber si instale todo bien o me falta algo por instalar? Gracias

**Comment by aaossa** [comment]
Hola @mleon17 , ¿a qué te refieres con que no se ejecutan correctamente? ¿Aparece una excepción? (¿Cuál?) ¿O no se ven las imágenes?

**Comment by mleon17** [comment]
por ejemplo en el ejemplo de Emisión de eventos con información me aparece una ventana en blanco en la cual no puedo interastral y luego al cerrarla me aparece otra ventana con un solo mensaje en la que tampoco puedo interactuar. Por lo que tengo entendido srgun el enunciado de ese ejemplo debería ser distinto.

**Comment by aaossa** [comment]
Supongo que eso ocurre porque no tienes las imágenes en la ruta correcta, prueba moviendo tu código a la misma carpeta donde están el cuaderno (o las imágenes donde tengas tu código) 👌
