### ISSUE TITLE
Duda si es que la carpeta "sprites" debe ir en cliente o servidor

### ISSUE THREAD

**Issue by luzmagurzua** [IIC2233/syllabus#688]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/681)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Estaba leyendo el enunciado de la tarea, y en la sección 4.1.1 en que indican cómo separar el programa dice que la carpeta sprites debería ir dentro de la carpeta clientes, luego en la parte 6.1.1 en donde hablan de la carpeta sprites, dice que la carpeta "avatares" (que es una sub carpeta de sprites) debe ser almacenada por el servidor, entonces me surgió la duda si si es que al final 'sprites' debe ir en clientes, servidor ambas ? Adjunto imágenes para que se entienda más fácil lo que dije. 

![Captura de Pantalla 2021-06-29 a la(s) 17 59 14](https://user-images.githubusercontent.com/80796978/123873260-39568480-d904-11eb-972c-18084bbb3bc0.png)
![Captura de Pantalla 2021-06-29 a la(s) 18 00 46](https://user-images.githubusercontent.com/80796978/123873264-3bb8de80-d904-11eb-8dbd-48bbbee870dd.png)

Gracias de antemano.

**Comment by knight-who-say-ni** [comment]
Hola @luzmagurzua!!

Tu duda ya fue respondida en la issue #685

Saludos y exito programando!!
