### ISSUE TITLE
contenidos semana 10 y AF03 con Tarea 2

### ISSUE THREAD

**Issue by totoiii** [IIC2233/syllabus#688]
1. **Los codigos hechos por los ayudantes en esta actividad AF03 los podemos ocupar para la Tarea??**
2 **Me recomendarian primero leerme la semana 10 y despues partir con la tarea o al revés?**(en el caso de que llegue el dia de la tarea y aun no haya visto nada de la semana 10). Esto tiene que ver con la importancia que tiene la semana 10 para la tarea

**Comment by gatochico** [comment]
Hola @totoiii ! Respondiendo en orden:

1. Sí, pueden usar los códigos base de la AF03 para su Tarea **siempre y cuando los citen apropiadamente** (Esto es, tanto dentro del código como en su README). Te recomiendo más que tomarlos de forma directa y trabajar sobre ellos, los tomes como una inspiración a la hora de modelar tu tarea 🤓.

1. Personalmente, te recomendaría que antes de leer el enunciado de la Tarea le eches por lo menos una leída completa (no necesariamente que entiendas todo de inmediato, pero por lo menos leerla para saber qué contenidos vienen en esa semana.). Esto es ya que la semana 10 trae varios contenidos que son **esenciales** para el desarrollo de la Tarea 2. La recomendación de leer primero los notebooks de contenidos es para que cuando leas el enunciado de la tarea, puedas ir relacionando elementos que se piden en ella con elementos de los contenidos vistos hasta la fecha, y así no te sientas confundidx al momento de pensar cómo implementar ciertas cosas 🙀. 

Espero se haya entendido, y quedo atenta a dudas!
