### ISSUE TITLE
Error Interfaces II 

### ISSUE THREAD

**Issue by amparostevens** [IIC2233/syllabus#688]
Hola! 
Estaba leyendo el cuaderno 1 de interfaces II y cuando quise probar el código de la última parte en donde se deben crear múltiples threads y cambia la posición de QLabel no me salen las imágenes que deberían y en la carpeta img no hay imágenes de comida ni carpeta "food". 
Las imágenes deberían existir y visualizarse verdad?

**Comment by fdoflorenzano** [comment]
Hola @amparostevens,

Tienes toda la razón, el problema que pasó fue que las imágenes estaban en semana incorrecta, pero acabo de subir al repositorio de contenidos un cambio con las fotos en la carpeta correcta.
Gracias por hacerlo notar 😊.

Saludos.
