### ISSUE TITLE
velocidad de ataque

### ISSUE THREAD

**Issue by mjgutierrez1** [IIC2233/Syllabus#688]
Cuando hay un ataque son ambos participantes, enemigo y personaje principal, quienes se quitan vidas. Entonces no me queda claro qué pasa cuando el personaje principal mejora su velocidad de ataque. Si el personaje principal mejora la velocidad de ataque entonces podría atacar al enemigo en menos de un segundo, pero como el ataque es mutuo ésto sería equivalente a que el enemigo está atacando al personaje principal en menos de un segundo. ¿Entonces si el personaje principal mejora su velocidad de ataque, todos los enemigos también mejorarían su velocidad de ataque en la misma cantidad que el personaje principal?

**Comment by naazocar** [comment]
Como yo lo entiendo, si por ejemplo el personaje principal mejora su velocidad de ataque al doble (digamos, si atacaba una vez por segundo ahora ataca dos) cuando choque con un enemigo, por cada segundo que pase el enemigo le quitará 1 vez su ataque al personaje principal, mientras que éste ultimo en ese mismo segundo le habrá quitado 2 veces su ataque
