### ISSUE TITLE
Problema con señales

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#688]
Hola, estoy intentando hacer una señal que vaya desde mi back_end_mapa hasta mi back_end_jugador, pero no me está reconociendo los parámetros, atributos y otras cosas.

La situación es:
en Main instancio Map (que es frontend) al que le paso self
en Map instancio MapGrilla al que le paso el self del Main
y
en Main instancio back_player

La ruta del connect sería parent.parent.back_hero.metodo
pero al hacer el segundo parent en lugar de decirme que estoy en main, me dice que estoy en ```<built-in method parent of Map object at 0x0000021C11A98558> {}```

Entonces estoy teniendo que hacer señales intermedias, o sea, MapGrilla le manda una señal a Map, Map le manda una señal a Main y Main al jugador :(

**Comment by iqacevedo** [comment]
Hola lo que te está diciendo es justamente que estás accediendo al método parent de un objeto de PyQt. Si llamas a ese método obtendrás el parent, que es el que tú buscas, algo así como `parent.parent().back_hero.metodo`.

Me parece que todos los objetos de PyQt tienen el método parent, por lo que no necesitas guardarlo en una variable (lo cual no es bueno).

Saludos !
