### ISSUE TITLE
Correr app de forma local sin Heroku

### ISSUE THREAD

**Issue by benjamimo1** [IIC2233/Syllabus#688]
Hola! He tenido muchos problemas seteando Heroku lo que ha impedido avanzar. Si corro un server con la app de forma local, es posible vincular este al webhook de Telegram para asi empezar a probar comandos?
Si es asi, que url debiese usar? LocalHOST etc?

**Comment by MainScientist** [comment]
Para probar el servidor de forma local se puede usar ngrok. En la issue #657 se explica bien qué es, su uso no es complicado. ¿Qué problemas has tenido con heroku? Si siguen al pié de la letra no deberían tener problemas (los pasos fueron probados en mac y windows).

**Comment by benjamimo1** [comment]
@MainScientist Si bien la guia en el enunciado es detalla omite ciertos pasos (como la necesidad de commit) o por ejemplo que faltaba un espacio en `heroku config:set --app <Nombre de su app>FLASK APP=main.py.` Tras 2 dias de intentarlo me rendí por el momento.

**Comment by benjamimo1** [comment]
Mi servidor imprime: `* Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)`
Setee el webhook de Telegram en: `params = {"url": "http://127.0.0.1:5000/telegram/input"}`, donde telegram/input es llega a esta seccion de la app ```
@app.route('/telegram/input', methods=['POST'])  #Primer argumento es en que directorio estará, el segundo metodos que acepta
def telegram_input():
    print("Recibi algo de telegram")
```
Si le envio un mensaje al bot, por que la consola no esta ejecutando el `print("Recibi algo de telegram")`, que me falta? Aiuda D:

**Comment by akaminetzkyp** [comment]
El problema es que el servidor en `http://127.0.0.1:5000/` está corriendo de manera local. Para que Telegram sea capaz de acceder a tu servidor, debes "abrirlo" a internet. Esto lo podrías lograr con *Heroku* o *ngrok*.

**Comment by MainScientist** [comment]
Si lees la issue que te mencioné verás que `127.0.0.1` es una dirección local que solo entiende **tu** computador (es decir, si otro computador escribe `127.0.0.1` no llegará a tu computador nada). Al usar `ngrok` puedes crear un túnel hacia tu pc. Al correr `ngrok` éste te dará un nombre externo. Debes usar éste dominio como webhook de telegram. Entenderás que configurar esto no es algo más fácil que configurar heroku, pero probablemente enfrentes problemas tratando de usar `ngrok` también, por lo que te recomiendo responder aquí en detalle los errores que has tenido con heroku y yo intentaré ayudarte para que tengas tu app arriba y lista para empezar a programar :)

**Comment by benjamimo1** [comment]
@MainScientist lei todo todito del Issue pero como no vi comandos a seguir quede como varado. En los proximos minutos lo intentaré de nuevo y pondre los problemas que me vayan surgiendo. Muchas gracias

**Comment by KnowYourselves** [comment]
Para hacer la tarea con ngrok:

- Installa ngrok
- Ejecuta ngrok 
- Manda el codigo: `ngrok.exe http numero_puerto`
- Crea tu aplicacion flask con el puerto que ingresaste en ngrok
- Hace webhook con el link que ngrok generó
- ???
- profit.

**Comment by ofvera** [comment]
mi problema con hacerlo en heroku es que no se lo que esta pasando y por ende que cosas recibe y que cosas no, a diferencia de localmente que veo con prints distintos procesos.

**Comment by MainScientist** [comment]
Pueden hacer lo que recomienda @KnowYourselves, siempre y cuando tengan presente que el bot **debe** estar en heroku a la hora de la corrección.

**Comment by KnowYourselves** [comment]
@MainScientist Aprovechando yo también tengo problemas con heroku, en mi caso ya describi el mío en la issue #676 y todavía no he logrado solucionarlo 😢

**Comment by benjamimo1** [comment]
Sumado a los pasos de @KnowYourselves, hay que incluir el ejecutar la app en IDLE no?

**Comment by MainScientist** [comment]
De todas formas siempre pueden hacer `print` dentro de su programa y después consultarlos en heroku con el comando `heroku logs`

**Comment by ofvera** [comment]
buena! gracias!

**Comment by benjamimo1** [comment]
@KnowYourselves @MainScientist Si defino el metodo que recepciona el POST como un mero print ("hola")(sin procesar si quiera lo que me envian), debiese funcionar?
Tengo el ngrok corriendo, el webhook seteado a url/directorio del metodo/ y le mando mensajes al bot y nada 😪

**Comment by MainScientist** [comment]
@benjamimo1 eso era justo lo que quería evitar, que tuvieses problemas con ngrok. Encuentro que tu tiempo está mejor invertido tratando de hacer funcionar heroku en vez de tratando de hacer funcionar ngrok.

**Comment by benjamimo1** [comment]
Solo quiero dormir para siempre FML 🙃

**Comment by MainScientist** [comment]
¡No te desmotives! ¡Tú puedes! :smile:
