### ISSUE TITLE
Señales no emiten al aplicar emit :(

### ISSUE THREAD

**Issue by jpmoraga1** [IIC2233/Syllabus#689]
No sé cual es el problema, pero el tema es que cuando intento mover a un enemigo desde un Thread, éste no se mueve. Por ejemplo, si intento que el enemigo se mueva con un enemigo.move() al momento de crearlo, si hago un for para que se mueva x veces, se mueve las x veces. Pero si intento que se mueva desde un Thread que tengo para que los enemigos se muevan, el enemigo no se mueve, pero es porque en este caso pareciera que la señal no está emitiendo nada, ya que tengo un print() al principio del método enemigo.move() que en el primer caso se mostraba y en el segundo caso no :c

**Comment by behrmann97** [comment]
Hola, comprobaste que las threads estén corriendo?

**Comment by jpmoraga1** [comment]
Hola, si están corriendo los threads, cuando llamo a is_alive() retorna True  ):

**Comment by behrmann97** [comment]
hola, sube lo que llevas de la tarea a tu repositorio para poder ver tu código :)

**Comment by jpmoraga1** [comment]
Hice el push, y puse un readme para indicarte las líneas importantes. Gracias! :)

**Comment by behrmann97** [comment]
mmm mirandolo rápido si no me equivoco, no hiciste el connect del trigger. Avisame

**Comment by jpmoraga1** [comment]
Lo hago en el __init__ de NonHostileEnemy (línea 366). Igual ahora me di cuenta que los enemigos no reciben ninguna señal, para intentar matarlos tampoco reciben la señal que hace que desaparezcan del mapa. ¿Será por mi modelación con los Threads? No cacho bien cual podría ser el problema

**Comment by behrmann97** [comment]
Bueno, probando distintas soluciones diría que el problema está en intentar hacer el connect dinámicamente (cada vez que creas a un enemigo). No te puedo decir como hacerlo porque te estaría haciendo la tarea :(, pero recomendaría hacer en el init un connect a algo que al ser llamado mueve a todos los enemigos. En otras palabras, no intentes ir haciendo connects cuando creas enemigos, hazlos todos en el init del juego.

**Comment by jpmoraga1** [comment]
YESSSSS, me resultó, graciaaaaaas!!!!

**Comment by behrmann97** [comment]
No problem ;)
