### ISSUE TITLE
Tiempo Extra Tarea 5

### ISSUE THREAD

**Issue by Jamidd** [IIC2233/Syllabus#689]
Hola, mil disculpas lo patudo, pero con algunos compañeros queríamos pedirles si podían ver la posibilidad de darnos tiempo extra para la entrega de la tarea. La verdad es que no ha sido fácil y serviría bastante.
Queda a su criterio, si se puede fantástico, si no, no se perdía nada con preguntar.
Muchas gracias. 
Pd. PLZ!!
![image](https://user-images.githubusercontent.com/30701876/32417107-df115306-c232-11e7-9784-0be8ed633b01.png)

**Comment by colindom** [comment]
La contienda es desigual 😢

**Comment by pnheinsohn** [comment]
![640](https://user-images.githubusercontent.com/26394046/32417319-73e5ec82-c236-11e7-9dcb-92c1cea7f20d.png)

**Comment by FernandoPieressa** [comment]
Hola!

Lamentablemente no se podrá dar tiempo extra para la tarea 5, por un tema de que va quedando poco del semestre y estamos muy justos de tiempo para las correcciones.

Mucho animo con lo que quede de tiempo y ojala puedan lograr terminarlo. Recuerden que el plazo es hasta el lunes 6 hasta las 23:59.

Saludos!

**Comment by Jamidd** [comment]
Ni siquiera 1 día mas? o por último hasta el martes a las 13.59? No? :)

**Comment by mmsaavedra1** [comment]
@FernandoPieressa 

Espero no ser muy insistente, ni pasar a llevar la estructura de evaluación de los ayudantes, pero opino que dar un par de tiempo más, entregar la tarea mañana martes 13.59, no afecta en la corrección. Dudo que los ayudantes se pongan a revisar a las 00.00 la tarea, por lo que darnos este tiempo extra puede ser útil para muchos de nosotros ya que se pudieron haber juntado otras evaluaciones, por ej en mi caso tuve 2 pruebas: opti y electro en la semana, sin contar 2 entregas de tareas y proyectos. Todos sabemos que este contenido fue un poco más pesado por lo que necesitamos muchísimo estudio externo y en consecuencia más tiempo para escribir nuestro código.

Espero puedan entender la petición y replantear el darnos un par de hora más, para afinar detalles importantes de funcionalidad de la tarea.

Saludos!
