### ISSUE TITLE
Github Flaggeo mi cuenta nueva!

### ISSUE THREAD

**Issue by chuma9615** [IIC2233/Syllabus#689]
Github me notifico que habian flaggeado mi cuenta y que esta escondida al publico. esto afecta en algo?

**Comment by chuma9615** [comment]
Al parecer si afecta porque el repo ya no es publico, que hago?

**Comment by MainScientist** [comment]
Al parecer esto se debe al spambot de github. Debes mandar un email a support@github.com o accounts@github.com explicando la situación y aclarando que no harás spamming con la cuenta, que la creaste por motivos académicos.

**Comment by malopez16** [comment]
Considerando​ que puede que demoren en responder, podríamos hacer que el bot realice los cambios desde nuestra cuenta con una token que tenga los permisos adecuados? Como ya son activas desde hace un tiempo dudo que les hagan flag :)

**Comment by chuma9615** [comment]
Yo hice eso, siendo muy cuidadoso en lo que mandaba pa q no me flaggeen mi cuebta, no hay otra opción jajajaa

**Comment by chuma9615** [comment]
Sigo con mi cuenta flaggeada, Puedo usar mi repo original?

**Comment by rpalmaotero** [comment]
@chuma9615 a qué te refieres con tu repo original?
