### ISSUE TITLE
Problema con paths y import

### ISSUE THREAD

**Issue by jirarrazaval** [IIC2233/syllabus#689]
Hola! Para esta tarea quería ordenar los módulos mejor y he tenido muchos problemas con eso.

1. Paths de los sprites. No aparece la imagen. Quizás es por que estoy en una carpeta diferente y no en un archivo.py al mismo "nivel" que la carpeta sprites. Por ejemplo, yo estoy en el archivo 2:
```
--Sprites -- carpeta x  -- imagen
--Carpeta --- archivo  2 (yo estoy aca)
```
el path de la imagen que puse es:  ``` sprites / carpeta x / imagen.png ```. Pero no funciona. Qué se hace para que aparezca? Me sale este error:
``` QPixmap::scaled: Pixmap is a null pixmap```

2. "from archivo import elemento" No me funciona importar cosas si estoy en una carpeta mas como "adentro" (no sé cómo explicar) del archivo que quiero importar. Por ejemplo:
```
--Archivo 1
--Carpeta --- archivo 2
```
Como importo un elemento del archivo 1 al archivo 2??
No me funciona ni con ```from archivo import elemento ```, ni con ```from .archivo import elemento``` ni con ```from ..archivo import elemento```

3. Esto es independiente de los puntos de antes, lo explico con otro ejemplo.
```
--Archivo 1 (tiene importado un elemento de archivo 2)
--Carpeta -- Archivo 2 (tiene importado a un elemento de archivo 3)
                --Archivo 3
```
Cuando ejecuto el archivo 2 me funciona, pero cuando ejecuto el archivo 3 no. Porque me sale que no existe el archivo que estoy importando (en este caso seria el archivo 3). Pasa esto porque está en otra carpeta. No sé si se puede arreglar.

**Comment by lily416** [comment]
Hola @jirarrazaval 👋 

Primeramente fíjate en la ubicación desde la que estás ejecutando tus archivos, ya que eso tiene influencia en la lectura de los _paths_. Para ver esto, puedes tratar de ejecutar tu código desde consola.

En cuanto a tus dudas:
1. Por lo que entiendo de tu esquema, tu estas ejecutando tu código desde `archivo 2`, el cual se encuentra dentro de `Carpeta`. Para acceder a imagen tienes que poner `../Sprites/carpeta x/imagen`, los `..` indican en el _path_ que estás volviendo a la carpeta padre de donde te encuentras actualmente.

2. Por lo que entiendo de tu esquema estas tratando de importar `Archivo 1` desde `archivo 2`. Por lo que estuve viendo sobre importar módulos desde el directorio padre ([link](https://stackoverflow.com/questions/714063/importing-modules-from-parent-folder)) parece ser un tema bastante complicado, lo mejor es que le des una vuelta a la distribución de tus archivos y veas si esa es realmente la mejor forma.

3. No entiendo el por qué te falla al ejecutar el `archivo 3`, ya que según lo que muestras este archivo no importa ninguno de los otros 😓  Igual que en el punto anterior, no es mala idea reevaluar la forma en la que estructura de tus archivos.

Quedo atenta a tus comentarios 😉

**Comment by jirarrazaval** [comment]
@lily416  Quiero hacerte dudas más específicas en cuanto a cómo aconsejas que los ordene, pero como que no puedo por aquí porque no quiero como soplar nada jajajaj porque quizás hay una forma como recomendable que no se dice en los cuadernos o no sé.

**Comment by jirarrazaval** [comment]
Alfinal puse todo en la misma carpeta, como que me rendí eran demasiados problemas
