### ISSUE TITLE
Visual Studio y librería PyQt5

### ISSUE THREAD

**Issue by pvcortes** [IIC2233/syllabus#689]
### Problema

Cuando importo clases o funciones de la librería PyQt5 de la siguiente manera:

**from PyQt5.QtWidgets import EJEMPLO**

VSCode arroja el error:

**No name 'EJEMPLO' in module 'PyQt5.QtWidgets'.** 

No importa la función o clase o lo que sea que esté importando, siempre se produce el mismo error, eso si, **el programa SI corre**, y todas las funciones y gráficas de la librería se ejecutan a la perfección. Pero la interfaz de VSCode no deja de subrayar con rojo las líneas de importación, ni poner en rojo los archivos abiertos que las contienen, cada vez que realiza el debug automático del código.

Adjunto imagen  de como se veía la interfaz durante la actividad de hoy, para ilustrar un poco el problema y lo molesto que es:

![Captura de pantalla (134)](https://user-images.githubusercontent.com/67768053/96185834-e1602500-0f10-11eb-98f6-9fdce5cd5bb6.png)

Espero alguien sepa desactivar tal vez el debugging para esa librería en particular o si logran identificar algún problema con la instalación, sin embargo recalco que el programa corre perfectamente.

**Comment by aaossa** [comment]
Hola @pvcortes , no estoy seguro de si es lo mismo, pero quizás lo de #664 te sirva? Si no es eso, responde por acá no más nuevamente para pensar en otras opciones, pero indicando el erro específico (o una captura donde se vea) ✨ Ojalá lo puedas solucionar 🙌
