### ISSUE TITLE
diagrama de clases

### ISSUE THREAD

**Issue by nmaturana97** [IIC2233/Syllabus#69]
para el diagrama de clases hay que incluir __repr__ en los metodos?

**Comment by GustavPrudencio** [comment]
Los metodos magicos (__repr__) por ejemplo no se agregan en el diagrama

**Comment by jerosalazar** [comment]
Las properties hay que agregarlas? Si por ejemplo tengo un atributo interno vida, la property de vida y su setter, tengo que agregar las 3 al diagrama? 
gracias 😊

**Comment by Sforrego** [comment]
Tenia entendido que las properties se tenian que aregar como atributos. :)
