### ISSUE TITLE
fecha

### ISSUE THREAD

**Issue by movaldivia** [IIC2233/Syllabus#69]
Podemos suponer que la fecha ingresada por el usuario es siempre correcta en cuanto formato y logica (que no pueda poner 2015 si un incendio empezó un 2017)

**Comment by FernandoPieressa** [comment]
Hola!

No pueden asumirlo, deben evitar que se caiga su programa por culpa del usuario.

Piensa en una situación real: Si un usuario que no sabe nada de tu programa hace algo mal y lo bota por culpa de eso, seria muy malo. Siempre intenta considerar que el usuario no sabe absolutamente nada y que no puede botar el programa por culpa de eso.

Saludos!
