### ISSUE TITLE
Si me quedo con los ayudantes del DCC

### ISSUE THREAD

**Issue by Oisangui** [IIC2233/syllabus#69]
Si destruyo al DCC y me quedo con sus ayudantes, estos presentan el IQ mejorado del DCC?

**Comment by Oisangui** [comment]
En otro caso, si la civilización a la que destruyo tenía Educación, entonces me quedo con la mejora del ayudante?

**Comment by hbkim94** [comment]
Hola! 

Respecto al primer caso, queda a tu criterio si es que los ayudantes obtenidos presentan el IQ mejorado o no. Lo que sí es que tienes que especificar tu decisión en tu `Readme.md` al momento de entregar la tarea.

Respecto a lo segundo, no, no te quedas con la mejora del ayudante, porque el bonus de Educación depende del avance tecnológico de cada civilización.

Espero haber aclarado tus dudas. Saludos!
