### ISSUE TITLE
Dudas sobre el enunciado y el rol de la máquina en el juego

### ISSUE THREAD

**Issue by fjcroquevielle** [IIC2233/Syllabus#69]
Hola, tengo unas dudas importantes sobre el enunciado. Básicamente, acerca de cómo se manejan los planetas no conquistados por el jugador. En la descripción del Aprendiz, su habilidad especial es robar recursos, pero la habilidad es diferente si es el jugador el que está invadiendo o la máquina la que está invadiendo. Pero en ningún lugar del enunciado se describe en qué situación la máquina decide invadir un planeta.

Otras dudas similares: los planetas no invadidos tienen recursos y nivel de economía, y quizás cuartel también, pero no se indica cuál es el criterio para que la "máquina" cree soldados, ¿en qué situación hace eso? Se que el usuario puede "modificar una galaxia" y ahí aumentar la cantidad de soldados, pero no es claro si para eso tiene que usar los recursos del planeta o no. Tampoco me queda claro cuándo un planeta no invadido decide construir un cuartel o una torre. No sale mencionado en la parte de modificar una galaxia.

Básicamente, no entiendo cómo van cambiando los planetas no conquistados por el usuario, ni cuál es el rol de sus recursos, si es que esos planetas no pueden cambiar. ¿La máquina hace algo por sí sola? ¿O todos los cambios los hace el usuario, ya sea jugando o usando la opción de modificar una galaxia?

Gracias!

**Comment by rihanuch** [comment]
Hola @fjcroquevielle !!

Tu primera duda 1️⃣ fue respondida en una issue pasada 🔙 (no me acuerdo en este minuto en cual) 😅

Respecto a la segunda 2️⃣, los recursos se utilizan cuando se juega, las modificaciones no son parte del juego en si mismo, entonces ¡no consumen recursos! Además de esto, la "máquina" 💻 no hace nada, ¡sólo existe la probabilidad de un archimago!

¡Saludos! 😄

**Comment by emeiese** [comment]
Hola! También me interesa saber la respuesta a la primera pregunta. Ya busqué en las issues pero no encontré nada :( (y son varias así que si alguien que esté leyendo esto se acuerda de cual era, porfa que la referencie!)

**Comment by leolivares** [comment]
@emeiese #45 
Esta es la issue que responde tu duda!
