### ISSUE TITLE
Revisar que no hay tabs en mi código

### ISSUE THREAD

**Issue by FelipeA7** [IIC2233/syllabus#69]
Hay alguna manera de poder revisar si en alguna parte me equivoqué y usé un TAB en vez de 4 espacios? Ya tengo mi código listo y se ejecuta sin problemas, pero tengo la duda de que haya confundido en alguna parte y usado tab en vez de espacios.

Otra duda aparte, en vs code encontré la opción de configurar que 1 tab sea equivalentea 4 espacios. Esto significa que puedo usar tab y no seré penalizado o esta configuración no sirve?

**Comment by bimartinez** [comment]
Hola @FelipeA7!

Es probable que no tengas ningún problema de *tabs* y espacios, ya que si fuera así *Python*:snake:  no compilaría el código y te lanzaría un *Syntax Error* (puede que sea otro pero creo que es ese). 

En todo caso en *VS Code* existe la función de mostrar los espacios en blanco para ver si son *tabs* o espacios. Lo puedes habilitar desde la paleta de comandos (`Ctrl + Shift + P`) buscando la opción `View: Toggle Render Whitespace`.

Respecto a la opción de configurar un tab como 4 espacios, lo que hace eso en realidad es que al apretar la tecla `Tab` se escriban 4 espacios en este caso, exactamente lo mismo que apretar 4 veces la tecla `Espacio`. Así que no hay problema con el uso de eso, de hecho es lo mejor que podrías hacer!

Avisame como te va, saludos :smile:

**Comment by FelipeA7** [comment]
Gracias! Apliqué lo del ajuste, y funciona, eso sí no me queda muy clara la diferencia entra tabs y espacio. Al utilizar tabs y espacio (mezclándolos) nunca me ha salido ningún error, pero leyendo en internet se supone que en Python 3.x.x hay problemas al mezclar tabs con espacios. Probé esto en VS code y en Jupyter notebook y no tengo ningún problema. Puede ser que estos 2 programas reemplazan automaticamente los tabs por espacios y es por eso que no me salen errores?

**Comment by bimartinez** [comment]
Efectivamente, tanto *Jupyter Notebook* como *VS Code*  escriben espacios en vez de un *tab* al apretar esta tecla. Puedes probar lo del error al crear un archivo `.py` en el block de notas mezclando *tabs* y espacios y luego corriendolo.

Saludos!
