### ISSUE TITLE
Me falla la ejecución de los tests

### ISSUE THREAD

**Issue by martina-abello** [IIC2233/Syllabus#69]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Cuando intento ejecutar los tests en VSCode, me sale que no existen módulos llamados 'pieza_explosiva' o 'tablero' (siendo que mis archivos pieza_explosiva.py y tablero.py están presentes en mi carpeta T1).

¿Por qué ocurre, y qué puedo hacer para arreglarlo?

**Comment by ManuelV03** [comment]
Hola, usualmente los imports y los paths pueden fallar cuando se ejecuta directamente desde VSCode por lo que fuertemente recomendamos ejecutar tus archivos desde tu consola. Intenta con eso y avísame que tal.

**Comment by martina-abello** [comment]
Sí, en la consola me funciona, pero quería saber por qué directamente de VSCode no. No me pareció que el import fuera nada muy complejo, por eso que fallara me causó duda. Igual gracias.

**Comment by Jpdelaf** [comment]
hola, yo estoy teniendo el mismo problema, pero me pasa que desde la consola tampoco me funciona y también si me meto al archivo de donde importan los test, estos aparecen subrayados en amarillo. no se si es que estoy haciendo algo mal o que debería hacer si quiero probar si mi código esta bien.
![Captura de pantalla 2023-08-26 190403](https://github.com/IIC2233/Syllabus/assets/141885410/a1b8f321-afb9-44f3-8529-6b19f7ac1bff)
![Captura de pantalla 2023-08-26 190830](https://github.com/IIC2233/Syllabus/assets/141885410/bd72a4b7-baf3-4e2a-8096-7a89be93f5bd)
![Captura de pantalla 2023-08-26 191114](https://github.com/IIC2233/Syllabus/assets/141885410/22d6eea9-e0bd-43d8-98ba-6e7d174b626b)

**Comment by Jpdelaf** [comment]
a perfecto, muchas gracias
