### ISSUE TITLE
Volver a desplegar el menu actual/ volver al menu anterior

### ISSUE THREAD

**Issue by APeraltaS16** [IIC2233/syllabus#69]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

En la seccion 4.2.1 Menu contactos y 4.2.2 Menu grupos, cada uno de estos tiene la opcion de añadir contacto y grupo respectivamente. Cuando esta sea valida, ¿se debe volver al menu de contacto/grupo o ir al chat recien creado o volver al "menu" de crear contacto/grupo? Ademas si este no es valido sale que se debe volver al menu actual, con esto se refieren que ¿se muestra de nuevo el "menu" de agregar contacto/grupo o se vuelve al menu de contacto/grupo?

**Comment by aljara97** [comment]
Hola @APeraltaS16, si bien en el menú de contactos y en el de grupos especificamos qué pasará cuando se agrega un contacto o crea un grupo incorrectamente, no mencionamos qué pasará cuando esto se haga de forma correcta. Por tanto, puede quedar a tu criterio escoger cualquiera de las opciones que propones, siempre que no afecten un flujo correcto del programa.

Con respecto a continuar en el menú actual, nos referimos a que debes seguir permitiendo crear un grupo o agregar un contacto, es decir, debes seguir en el menú de esas funcionalidades y no ir a los menús de contacto y grupo según corresponda.

Mucho éxito y espero haber aclarado tu duda.

**Comment by aljara97** [comment]
Hola, debido a que queda poco para entregar la tarea, consideraremos ambas opciones válidas. Por tanto, puedes dejarlo como te indiqué y citar esta issue en tu Readme para que el o la ayudante que corrija tu tarea esté al tanto.

**Comment by rfigueroa314** [comment]
Perfecto, muchas gracias!
