### ISSUE TITLE
Commit a revisar README

### ISSUE THREAD

**Issue by benja420p** [IIC2233/Syllabus#69]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda:

Hola! Recibí mediante mail el commit a revisar, y a este le faltan unos cambios realizados en el README que se implementaron fuera del plazo para actualizar el repositorio (20:00) pero antes del plazo de la entrega del README (22:00). **¿Cómo puedo saber el estado del README que será evaluado?**

**Comment by JulianTR96** [comment]
Estoy en una situación medio similar y solo queda 1 hora :/

**Comment by matiasmasjuan** [comment]
Hola @benja420p !

Si al commit a revisar **solo le faltan** los cambios del **README.md**, pero estos fueron realizados antes de las 22:00,  debería estar bien. El **README.md** será recolectado igual siempre y cuando se haya realizado dentro del plazo, por lo que no deberías tener problemas.

Saludos! Y que tengas un buen fin de semana! :smile:

**Comment by benja420p** [comment]
Dale, muchas gracias!
