### ISSUE TITLE
Duda con tiempo de resolución del tablero 

### ISSUE THREAD

**Issue by criism0** [IIC2233/Syllabus#69]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/21)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/20)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Holaa! queria consultar respecto a si tenemos un limite de tiempo para que nuestra solución sea entregada correctamente  ya que mi código es capaz de encontrar soluciones pero mientras mayor es la extensión de el tablero, su tiempo de resolución crece exponencialmente, pero eventualmente encuentra una solución que cumple todas las condiciones de victoria, ¿es requisito que la solución se encuentre rápidamente? o se entiende que si mi código funciona, podre obtener la totalidad del puntaje del item, hago la pregunta ya que llevo muchas horas buscando maneras de optimizar mi codigo y replantear el problema para obtener soluciones más rápidas, consiguiendo grandes mejorias, pero pensando en tableros de gran extensión, la solución tardaria mucho. Muchas gracias de antemano

**Comment by joaquindm02** [comment]
Hola @criism0 !

Es normal que al aumentar el tamaño del tablero el código se demore más en resolverlo, por lo que no es un problema, lo importante es que el algoritmo logre resolver el tablero. No es requisito que la solución se encuentre rapidamente.

Saludos

**Comment by Hernan4444** [comment]
Hola @criism0 

Notamos que marcaste el primer checkbox de la issue donde dice: "Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues))." , pero la regla número 8 del foro dice:

> Cuando tu duda sea respondida házselo saber a tu ayudante y **deja la issue abierta**, ya que esto podría servirle a alguien más que tenga la misma duda o una muy similar. Nosotros nos encargaremos de cerrarla cuando sea el momento 😉.

Por favor si están haciendo check de que cumplieron con los ítems ya realizados, aplicarlos en la issue. Volveremos a abrir la issue para que los demás puedan ver la respuesta 😄 

Saludos c:
