### ISSUE TITLE
Restricciones y alcances; uso de contenidos de semana-02 (diccionarios)

### ISSUE THREAD

**Issue by njllanos** [IIC2233/Syllabus#69]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/20)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/19)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, en el punto 7 del enunciado de la tarea (Restricciones y alcances) se menciona que; "Esta tarea se debe desarrollar exclusivamente con los contenidos liberados al momento de publicar el enunciado", según esto entiendo que los contenidos de la semana-02 si estan permitidos ya que se subieron semanas antes. Sin embargo, la frase siguiente a la anterior; "No se permitirá utilizar contenidos que se vean posterior a la publicación de esta evaluación" me hace dudar, ya que estos contenidos son vistos (presencialmente en clases) esta semana. En especifico, mi duda va hacia si esta permitido el uso de diccionarios.

En resumen; **¿Esta permitido el uso de diccionarios en la Tarea 1?**

**Comment by Hernan4444** [comment]
Hola @njllanos 

Recomiendo revisar esta issue:
* https://github.com/IIC2233/Syllabus/issues/19

Ahí los estudiantes han preguntado por librerías y tambien por contenido, y justamente ya se consultó sobre utiliazr diccionarios, dando una respuesta positiva.

Si tienes dudas sobre otro contenido, en esa issue estaremos atento para aprobar o rechazar cualquier solicitud.

Saludosヾ(＾-＾)ノ
