### ISSUE TITLE
Duda sobre máximo de caracteres por línea

### ISSUE THREAD

**Issue by gBastias2001** [IIC2233/Syllabus#69]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola! El enunciado dice que no se pueden sobrepasar los 100 caracteres por línea de código, mi pregunta es ¿Esto corre también para los comentarios agregados para explicar el código? ¿Y para el archivo parametros.py (si tengo por ejemplo un string muy largo)?

Gracias :)

**Comment by nanglada** [comment]
Hola gBastias2001!
Sí a ambas preguntas jaja
La idea es que en ningún archivo .py haya una línea (incluyendo comentarios) que se pase de los 100 caracteres. 
Suerte con tu tarea 🙌
