### ISSUE TITLE
Inicio de la partida sobre una bestia

### ISSUE THREAD

**Issue by brunaldihno** [IIC2233/Syllabus#69]
* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

En el enunciado se menciona que las bestias tienen que estar en sectores aleatorios, sin embargo ¿Se puede Realizar de tal forma de que la primera casilla que uno seleccione no tenga bestias en ella? ¿y que tampoco tenga bestias alrededor?

**Comment by Emiliax16** [comment]
Hola @brunaldihno . No se puede. Las coordenadas de las bestias en el tablero deben ser completamente al azar, por lo que si en el primer turno justo descubres una bestias, debes perder de inmediato y mostrar todas las bestias del tablero. Saludos!
