### ISSUE TITLE
Semana 01, Ejercicio 7.2

### ISSUE THREAD

**Issue by amahns1** [IIC2233/syllabus#69]
¡Hola!

En el ejercicio 7.2 no entiendo cómo definir el segundo diccionario sin que sea un diccionario por comprensión.

Gracias :)

**Comment by Drpinto1** [comment]
¡Hola!

La idea de este ejercicio **no es** evitar que utilices comprensión, la idea es que puedas copiar el diccionario sin copiar su definición.

Con lo anterior me refiero a que hacer:
```
diccionario_1 = {str(i): 0 for i in range(100)}
diccionario_2 = {str(i): 0 for i in range(100)}
```

Estará incorrecto, pero si logras hacerlo de otra forma, **incluso si utilizas comprensión** probablemente estará correcto :wink:

Espero que esto te ayude :smile:

**Comment by amahns1** [comment]
Lo definí usando comprensión:

`diccionario_2 = dict.fromkeys([str(i) for i in range(100)], 0)`

Pero no estoy seguro si es distinto a hacer:

`diccionario_1 = {str(i): 0 for i in range(100)}`

**Comment by Drpinto1** [comment]
Si bien usaste un método diferente, sigues usando, de cierta forma, la definición del diccionario original.

Otra forma de pensar el objetivo del ejercicio es que puedas crear una copia del diccionario original sin ver la definición de este, es decir, sin saber absolutamente nada del `diccionario_1`, ni su largo, ni sus keys, ni nada más aparte del hecho de que es un diccionario.

Cabe señalar que puedes usar la variable en la que está guardado, es decir, iterar sobre `diccionario_1` está permitido.

Avísame si esto te aclara un poco más la idea :smile:

**Comment by amahns1** [comment]
Si!! Ahora entiendo. Lo dejé como:

`diccionario_2 = {key: 0 for key in diccionario_1}`

Muchas Gracias!!
