### ISSUE TITLE
Problema visualización Qt Designer Mac

### ISSUE THREAD

**Issue by cfernandek** [IIC2233/syllabus#690]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

[Tengo un problema al abrir Qt Designer desde mi computador (mac) no se visualiza la aplicación como sale en el contenido 3 de la semana 10. Me baje la aplicación desde este link [https://build-system.fman.io/qt-designer-download]() sugerido por el curso, dado que usar "pip3 install PyQt5-tools" me salía un error, mencionado en la issue #677 . Adjunto foto:  ]

<img width="1440" alt="Captura de Pantalla 2020-10-16 a la(s) 16 02 08" src="https://user-images.githubusercontent.com/69773929/96298653-31022780-0fc9-11eb-9d19-8be8ab76878a.png">

**Comment by igbasly** [comment]
Hola @cfernandek :v:
Como se ve QtDesigner es completamente normal 😅, por cómo funcionan las ventanas en MacOS los diferentes componentes del software se van a desplegar en ventanas distintas. Me parece mucho que el Designer que viene incluido en QtCreator para MacOS se ve como una sola ventana, pero no hay diferencia alguna.

No te preocupes, ya tienes QtDesigner 🙌 , mucho éxito!!

**Comment by cfernandek** [comment]
Muchas Gracias! Eso si no puedo ver las barras de herramientas que en el contenido 3 de la semana 10 se enumeran como 3,4,5,6. Como puedo arreglar esto?

**Comment by igbasly** [comment]
Todas las ventanas de herramientas y componentes para trabajar con los elementos las puedes activar y desactivar desde el menú `view` en la barra superior :+1:.

**Comment by cfernandek** [comment]
Perfecto! Gracias
