### ISSUE TITLE
Formato de errores en Issues googleables  

### ISSUE THREAD

**Issue by KnowYourselves** [IIC2233/Syllabus#690]
En el enunciado sale que si sale un error en algun bloque de python abría que googlearlo, etc.

Mi pregunta es, podemos asumir el formato del error como el que entrega IDLE? 

Y como segunda pregunta, no entendí muy bien el enunciado, apenas se cierre la issue hay que ponerle el tag googleable?, o si se cierra con un comentario no?

(imagen para referencia)

pd: Podemos asumir tambien que habrá un bloque markdown por error, o podrían haber múltiples?

![image](https://user-images.githubusercontent.com/26102039/27505605-22b51384-5872-11e7-9de4-40a825996590.png)

**Comment by akaminetzkyp** [comment]
Sobre la segunda pregunta, yo entendí que hay que etiquetar la issue con "Googleable" si esta es cerrada sin comentarios extra o con un comentario del creador (un gracias, por ejemplo).

**Comment by hanavarrete** [comment]
Si la issue se cierra sin ningún otro comentario aparte del realizado por el bot o alguno del autor de la issue (puede dar las gracias), ponerle a ésta el label Googleable. Es decir, si el bot responde y la issue se cierra, ponerle el label. En caso de que aparte de la respuesta del bot haya un comentario del creador dando las gracias, lo mismo. Para tu primera pregunta: claro, la idea es que asuman que en la última línea hay un error de python con ese formato. Saludos!

**Comment by KnowYourselves** [comment]
ty!
