### ISSUE TITLE
Pasar una ventana de QtDesigner con imágenes a Python

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2233/syllabus#690]
Hola!Cuando trato de pasar una ventana que cree en QtDesigner de la siguiente forma:
![imagen1](https://user-images.githubusercontent.com/62029138/82136066-c6f61400-97d7-11ea-9cd5-d9d005930f66.png)
![imagen2](https://user-images.githubusercontent.com/62029138/82136069-cbbac800-97d7-11ea-9d53-d473a3913521.png)
![imagen3](https://user-images.githubusercontent.com/62029138/82136072-ce1d2200-97d7-11ea-9895-d848e55c5e5a.png)
![imagen4](https://user-images.githubusercontent.com/62029138/82136075-d07f7c00-97d7-11ea-886b-e6c0385a9fe7.png)
![imagen5](https://user-images.githubusercontent.com/62029138/82136077-d37a6c80-97d7-11ea-91fa-e8c7b8d93f80.png)
![imagen6](https://user-images.githubusercontent.com/62029138/82136079-d70df380-97d7-11ea-98e0-66c44fcfb2bb.png)
![imagen7](https://user-images.githubusercontent.com/62029138/82136081-d8d7b700-97d7-11ea-80b6-b6e0f1ca4026.png)
Al hacerlo de esta forma no me permite pasarlo a python me tira un error:
No moduled named "enlace_rc" 
No entiendo muy bien el por que del error, quisiera saber si hay solución u otra forma de pasar una ventana con imágenes de QtDesigner a Python, o si solo puedo insertar imagenes directamente desde Python.

**Comment by Camila-sty** [comment]
Yo tengo el mismo error. Has podido solucionarlo?

**Comment by matiasmasjuan** [comment]
Hola @RonaldoSosa !

La verdad no sé como responder a tu pregunta, porque aún no entiendo muy bien cómo estas creando las imágenes dentro del **QtDesigner** y las importas a python.

La forma **habitual** de **hacerlo** es mediante ***Qlabels***, en donde seleccionas el *label* y le añades un *QPixmap* Para asignar una imagen. A continuación te daré los siguientes pasos.

Paso 1: Abrir **QtDesigner** y añadir un **QWidget**.

![Paso1](https://user-images.githubusercontent.com/48495638/82229167-16336600-98f8-11ea-80a0-66b1f0ac881e.PNG)

Paso 2: Añadir un ***Qlabel***

![paso2](https://user-images.githubusercontent.com/48495638/82229228-2f3c1700-98f8-11ea-8cb1-94d4b81688e9.PNG)

Paso 3: Seleccionar el **QPixmap** del ***label***

![paso3](https://user-images.githubusercontent.com/48495638/82229334-4da21280-98f8-11ea-94d7-5a58bae99b77.PNG)

Paso 4: Selecciona la **imagen**

![paso4](https://user-images.githubusercontent.com/48495638/82229411-66122d00-98f8-11ea-8cab-8ae9cb6b570e.PNG)

Paso 5: Observa cómo quedó el ***QWidget***

![paso5](https://user-images.githubusercontent.com/48495638/82229453-71fdef00-98f8-11ea-9003-b238418037e2.PNG)

Paso 6: Guarda el archivo en formato **.ui**
![paso6](https://user-images.githubusercontent.com/48495638/82229526-8fcb5400-98f8-11ea-8457-a914dfb94229.PNG)

Paso 7: Configura el **main.py**

![paso7](https://user-images.githubusercontent.com/48495638/82229582-a96c9b80-98f8-11ea-9739-916424b1b486.PNG)

Paso 8: Configura la **ventana_ejemplo.py**

![paso8](https://user-images.githubusercontent.com/48495638/82229636-bd180200-98f8-11ea-9390-b1f27154a4de.PNG)

Paso 9: Corre el **main.py** e **iluminate** con la **magia** de **QtDesigner**

![paso9](https://user-images.githubusercontent.com/48495638/82229806-e173de80-98f8-11ea-9598-11ac79e19680.PNG)

**IMPORTANTE**: El archivo **ejemplo.ui** debe estar **ubicado** en la **misma carpeta** que tu **proyecto**. Además, las **imágenes** **importadas** al **QtDesigner** deben estar en la ubicación correspondiente dentro de tu **proyecto**. Si mueves la ubicación de tus **imagenes**, o mueves la carpeta con las imagenes que utilizas en **QtDesigner**, es posible que se produzca un error.

Espero que esto te ayude a la elaboración de tu tarea utilizando **QtDesigner**

Saludos! 😄

**Comment by vsantelicest** [comment]
Hola! Siguiendo la línea de lo que preguntan en esta issue, me pasa lo siguiente. Al hacer paso a paso el widget y label con foto correspondiente, añado la foto y esta me queda gigante en comparación al tamaño de la ventana. Luego lo ajusto, pero al añadir otro label a la ventana, se vuelve a agrandar mucho. No entiendo como resolver esto.

**Comment by MINGOD24** [comment]
Hola @matiasmasjuan , yo lo hago tal como tu lo describes pero por alguna razón no me aparece la imagen al correr el codigo. El resto de la ventana se ve bien, pero la imagen no aparece. Porque puede ser?

**Comment by RonaldoSosa** [comment]
> Hola! Siguiendo la línea de lo que preguntan en esta issue, me pasa lo siguiente. Al hacer paso a paso el widget y label con foto correspondiente, añado la foto y esta me queda gigante en comparación al tamaño de la ventana. Luego lo ajusto, pero al añadir otro label a la ventana, se vuelve a agrandar mucho. No entiendo como resolver esto.

Lo que pasa es que tienes que dar click en donde dice "scaledcontents" esta abajo de pixmap

**Comment by RonaldoSosa** [comment]
> Hola @RonaldoSosa !
> 
> La verdad no sé como responder a tu pregunta, porque aún no entiendo muy bien cómo estas creando las imágenes dentro del **QtDesigner** y las importas a python.
> 
> La forma **habitual** de **hacerlo** es mediante _**Qlabels**_, en donde seleccionas el _label_ y le añades un _QPixmap_ Para asignar una imagen. A continuación te daré los siguientes pasos.
> 
> Paso 1: Abrir **QtDesigner** y añadir un **QWidget**.
> 
> ![Paso1](https://user-images.githubusercontent.com/48495638/82229167-16336600-98f8-11ea-80a0-66b1f0ac881e.PNG)
> 
> Paso 2: Añadir un _**Qlabel**_
> 
> ![paso2](https://user-images.githubusercontent.com/48495638/82229228-2f3c1700-98f8-11ea-8cb1-94d4b81688e9.PNG)
> 
> Paso 3: Seleccionar el **QPixmap** del _**label**_
> 
> ![paso3](https://user-images.githubusercontent.com/48495638/82229334-4da21280-98f8-11ea-94d7-5a58bae99b77.PNG)
> 
> Paso 4: Selecciona la **imagen**
> 
> ![paso4](https://user-images.githubusercontent.com/48495638/82229411-66122d00-98f8-11ea-8cab-8ae9cb6b570e.PNG)
> 
> Paso 5: Observa cómo quedó el _**QWidget**_
> 
> ![paso5](https://user-images.githubusercontent.com/48495638/82229453-71fdef00-98f8-11ea-9003-b238418037e2.PNG)
> 
> Paso 6: Guarda el archivo en formato **.ui**
> ![paso6](https://user-images.githubusercontent.com/48495638/82229526-8fcb5400-98f8-11ea-8457-a914dfb94229.PNG)
> 
> Paso 7: Configura el **main.py**
> 
> ![paso7](https://user-images.githubusercontent.com/48495638/82229582-a96c9b80-98f8-11ea-9739-916424b1b486.PNG)
> 
> Paso 8: Configura la **ventana_ejemplo.py**
> 
> ![paso8](https://user-images.githubusercontent.com/48495638/82229636-bd180200-98f8-11ea-9390-b1f27154a4de.PNG)
> 
> Paso 9: Corre el **main.py** e **iluminate** con la **magia** de **QtDesigner**
> 
> ![paso9](https://user-images.githubusercontent.com/48495638/82229806-e173de80-98f8-11ea-9598-11ac79e19680.PNG)
> 
> **IMPORTANTE**: El archivo **ejemplo.ui** debe estar **ubicado** en la **misma carpeta** que tu **proyecto**. Además, las **imágenes** **importadas** al **QtDesigner** deben estar en la ubicación correspondiente dentro de tu **proyecto**. Si mueves la ubicación de tus **imagenes**, o mueves la carpeta con las imagenes que utilizas en **QtDesigner**, es posible que se produzca un error.
> 
> Espero que esto te ayude a la elaboración de tu tarea utilizando **QtDesigner**
> 
> Saludos! 😄

Me funcionó! Gracias

**Comment by matiasmasjuan** [comment]
Hola @vsantelicest !

La idea es que cuando agregas una imagen, debes **ajustar** el tamaño del ***Qlabel***. Esto es **super importante**, ya que en realidad tu **no estás** ajustando el **tamaño** de la **imagen**, sino que estas ajustando el **tamaño** del ***Qlabel*** que contiene la imagen.

Ahora bien, con respecto al ajuste del tamaño, tal como dice @RonaldoSosa , (y se me olvidó ser más preciso en el paso 5 😅 ), este **ajuste** del tamaño del ***QPixmap*** del ***Qlabel*** lo realicé **activando** la casilla de **scaledContents**. Esto en realidad, es un **método** que tiene el ***Qlabel*** para ajustar el tamaño de la **imagen** al tamaño original del ***Qlabel***. Esto se puede hacer perfectamente sin **QtDesigner**.

Por ejemplo, aquí estoy desactivando la casilla. Y **además**, le estoy poniendo un **nombre** a mi ***Qlabel***. **Mucho ojo** con esto, ya que este **nombre** es el **mismo** nombre que se utilizará en nuestra **instancia** **EjemploVentana**.

![nuevo_paso](https://user-images.githubusercontent.com/48495638/82249358-a2a15100-9917-11ea-8ef9-f38c896a5d3d.PNG)

Si corro mi programa **sin** utilizar **ScaledContents** se ve de la siguiente manera:

![nuevo_paso_2](https://user-images.githubusercontent.com/48495638/82250107-e21c6d00-9918-11ea-98dc-fdf21bc68e32.PNG)


Ahora bien, yo puedo **modificar** mi ***Qlabel*** con el **mismo nombre** definido anteriormente, y le agrego el método de:

```python
self.cualquier_nombre.setScaledContents(True)
```

Lo que se puede ver en mi archivo de la siguiente forma:

![nuevo_paso_3](https://user-images.githubusercontent.com/48495638/82250094-dc268c00-9918-11ea-81f4-1dbca23f582d.PNG)


Y finalmente lo que se observa es lo siguiente:

![nuevo_paso_4](https://user-images.githubusercontent.com/48495638/82250081-d7fa6e80-9918-11ea-85f3-49b2c704c23f.PNG)

Espero que te haya podido ayudar, y mucho éxito con la tarea! 😄

**Comment by matiasmasjuan** [comment]
Hola @MINGOD24 !

Lo más probable es que la imagen este guardada en otra carpeta donde el archivo *ejemplo.ui* es incapaz de acceder. Si estás trabajando para la **T02**, se recomiendo almacenar la carpeta ***sprites*** en la misma que la de tu repositorio de la **T02**, y al momento de crear tu **archivo.ui** en el **QtDesigner** y escojas tu imagen de **QPixmap**, selecciones la **misma** imagen que necesitas dentro de la carpeta **sprites** dentro de la carpeta de tu **repositorio**.

Quedo atento en caso de que esto no resulte.

Saludos! 😄

**Comment by vsantelicest** [comment]
> Hola @vsantelicest !
> 
> La idea es que cuando agregas una imagen, debes **ajustar** el tamaño del _**Qlabel**_. Esto es **super importante**, ya que en realidad tu **no estás** ajustando el **tamaño** de la **imagen**, sino que estas ajustando el **tamaño** del _**Qlabel**_ que contiene la imagen.
> 
> Ahora bien, con respecto al ajuste del tamaño, tal como dice @RonaldoSosa , (y se me olvidó ser más preciso en el paso 5 😅 ), este **ajuste** del tamaño del _**QPixmap**_ del _**Qlabel**_ lo realicé **activando** la casilla de **scaledContents**. Esto en realidad, es un **método** que tiene el _**Qlabel**_ para ajustar el tamaño de la **imagen** al tamaño original del _**Qlabel**_. Esto se puede hacer perfectamente sin **QtDesigner**.
> 
> Por ejemplo, aquí estoy desactivando la casilla. Y **además**, le estoy poniendo un **nombre** a mi _**Qlabel**_. **Mucho ojo** con esto, ya que este **nombre** es el **mismo** nombre que se utilizará en nuestra **instancia** **EjemploVentana**.
> 
> ![nuevo_paso](https://user-images.githubusercontent.com/48495638/82249358-a2a15100-9917-11ea-8ef9-f38c896a5d3d.PNG)
> 
> Si corro mi programa **sin** utilizar **ScaledContents** se ve de la siguiente manera:
> 
> ![nuevo_paso_2](https://user-images.githubusercontent.com/48495638/82250107-e21c6d00-9918-11ea-98dc-fdf21bc68e32.PNG)
> 
> Ahora bien, yo puedo **modificar** mi _**Qlabel**_ con el **mismo nombre** definido anteriormente, y le agrego el método de:
> 
> ```python
> self.cualquier_nombre.setScaledContents(True)
> ```
> 
> Lo que se puede ver en mi archivo de la siguiente forma:
> 
> ![nuevo_paso_3](https://user-images.githubusercontent.com/48495638/82250094-dc268c00-9918-11ea-81f4-1dbca23f582d.PNG)
> 
> Y finalmente lo que se observa es lo siguiente:
> 
> ![nuevo_paso_4](https://user-images.githubusercontent.com/48495638/82250081-d7fa6e80-9918-11ea-85f3-49b2c704c23f.PNG)
> 
> Espero que te haya podido ayudar, y mucho éxito con la tarea! 😄

Gracias! Si me resulta si lo hago así, pero al poner un Layout vertical y dentro de el a la imagen, esta se agranda de nuevo y el scaled content no la ajusta. Que podria arreglar esto?

**Comment by MINGOD24** [comment]
> Hola @MINGOD24 !
> 
> Lo más probable es que la imagen este guardada en otra carpeta donde el archivo _ejemplo.ui_ es incapaz de acceder. Si estás trabajando para la **T02**, se recomiendo almacenar la carpeta _**sprites**_ en la misma que la de tu repositorio de la **T02**, y al momento de crear tu **archivo.ui** en el **QtDesigner** y escojas tu imagen de **QPixmap**, selecciones la **misma** imagen que necesitas dentro de la carpeta **sprites** dentro de la carpeta de tu **repositorio**.
> 
> Quedo atento en caso de que esto no resulte.
> 
> Saludos! 😄

Hola,

Tengo guardados los archivos .ui en una carpeta T02/gui/"file".ui y las fotos estan en T02/sprites/...  y pese a esto, cuando sigo el paso a paso que mencionas anteriormente, en el qt designer se ve bien, pero al agregar la ventana al programa esta aparece sin la foto.

**Comment by matiasmasjuan** [comment]
Hola @vsantelicest !

Cuando trabajas con Layouts es un poco distinto. Sin embargo, este problema está asociado más que nada porque la imagen del *Logo* de ***DCCafé*** es un poco grande 😅  y por eso se agranda tanto el ***Vertical Layout***. Te puedo recomendar dos situaciones:
* No utilizar un un *Layout* para trabajar con el **logo** del ***DCCafé*** (sólo usar un ***Qlabel***).
* Que **manualmente** edites el logo del ***DCCafé*** y lo guardes en tu repositorio.

En todo caso, es algo sumamente **particular** con respecto al **logo**, asi que esto no pasará con los demás **sprintes**.

Mucho éxito con la tarea! 😄

**Comment by matiasmasjuan** [comment]
Hola @MINGOD24 !

Perdón por la insistencia, pero también tuve el mismo problema es su momento 😅 . ¿Estás seguro que al momento en que cargas la imagen en **QtDesigner** (seleccionar **QPixmap**) es la misma que la **imagen** en tu repositorio y no la de la carpeta de **sprites** del **Syllabus**?

Saludos! 😄

**Comment by MINGOD24** [comment]
@matiasmasjuan holaa! estoi segurisimo, lo he revisado varias veces y lo acabo de revisar y me sale este path al elegir la foto (C:\Users\56979\Desktop\2020-1\progra avanzada\MINGOD24-iic2233-2020-1\Tareas\T02\sprites\otros). Tienes alguna idea de que mas puede estar sucediendo?

**Comment by matiasmasjuan** [comment]
Hola @MINGOD24 !

La verdad no se me ocurre que puede estar pasando. Generalmente esto pasa por estar seleccionando algo mal dentro de la ruta de los archivos. Si pudieras hacer un **push** a tu repositorio (evitando subir la carpeta *sprites* con el *.gitignore*) tal vez pueda revisar con mayor claridad lo que está sucediendo.

Saludos!

**Comment by MINGOD24** [comment]
> Hola @MINGOD24 !
> 
> La verdad no se me ocurre que puede estar pasando. Generalmente esto pasa por estar seleccionando algo mal dentro de la ruta de los archivos. Si pudieras hacer un **push** a tu repositorio (evitando subir la carpeta _sprites_ con el _.gitignore_) tal vez pueda revisar con mayor claridad lo que está sucediendo.
> 
> Saludos!

Hola @matiasmasjuan. ya subi lo que me pediste a mi repo. Gracias!

**Comment by matiasmasjuan** [comment]
Hola @MINGOD24 !

Revisé tu repositorio, y al parecer el error se debe a que tienes almacenados los archivos **.ui** en la carpeta **T02/gui**. El problema de esto es que no existe un ***path*** relativo para que el archivo **.ui** pueda acceder a los **sprites**. Debido a esto, te recomiendo simplemente dejar los archivos **.ui** **fuera** de la carpeta **/gui**, y que las dejes en la carpeta de tu repositorio en **/T02**. 

Luego de esto, abre nuevamente los archivos **.ui** y vuelve a **cargar** los ***Pixmap*** de los ***Qlables***, y vuelve a **guardar** los archivos. 

Al menos yo intenté eso y me funcionó.

Avísame como te va! 😄

**Comment by MINGOD24** [comment]
Hola @matiasmasjuan , ahi me resulto! eres un genio jajajajja! Muchisimas gracias!!!
