### ISSUE TITLE
Uso de ProgressBar

### ISSUE THREAD

**Issue by llloyola** [IIC2233/Syllabus#690]
Hola! Una consulta... Es necesario el uso de QProgressBar o puedo hacer la barra de vida de otra forma? Resulta que la hice de manera en que se entiende y representa bien la vida de cada personaje, pero surgió recién esta duda por un comentario que me hizo un compañero. Gracias de antemano.

**Comment by hanavarrete** [comment]
Hola! No es necesario mientras se represente y entienda bien como tu dices. Saludos!!
