### ISSUE TITLE
mejoras

### ISSUE THREAD

**Issue by ciquezada** [IIC2233/Syllabus#690]
Hola!,
¿las mejoras son stackeables?

**Comment by santilaguna** [comment]
@ciquezada no soy ayudante, pero en la sala de ayuda se hablo de que sólo las bombas son stackeables

**Comment by monicabelen** [comment]
Hola! Confirmo lo que dice @santilaguna . Además, la velocidad va multiplicada por 1,25 cada vez.

**Comment by ciquezada** [comment]
perdón pero, "la velocidad va multiplicada por 1,25 **cada vez**.", ¿osea que la velocidad se stackea tambien?

**Comment by monicabelen** [comment]
@ciquezada sí, **ambas** son stackeables (lo siento, no había leído el "sólo las bombas").

**Comment by santilaguna** [comment]
@monicabelen pero en la sala de ayuda se dijo que la velocidad no se stackeaba podemos implementarlo de ambas formas para que no se genere confusión?? (lo especificaré en el README de todas formas)

**Comment by monicabelen** [comment]
Sí, por supuesto! Ponlo en el readme para una mejor corrección.
