### ISSUE TITLE
Múltiples patadas

### ISSUE THREAD

**Issue by llloyola** [IIC2233/Syllabus#691]
¿Puedo asumir que la bomba puede ser pateada una sola vez? No me importa quién de los dos jugadores la patea, sino que sólo pueda ser pateada una vez, pues si tengo la bomba entre dos jugares que están sobre la misma fila o columna, la bomba rebotaría de un jugador al otro cada vez que colisiona con un jugador y no quiero que eso pase.

**Comment by leolivares** [comment]
Hola @llloyola 
No puedes asumir eso.
