### ISSUE TITLE
Valores parámetros y precio bocadillos

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#691]
Hola!
En el enunciado dicen que hay que dejar como parámetro ```PRECIO_BOCADILLO``` pero el valor de éste tenemos que nosotros determinarlo¿?
Además se supone que hay muchos bocadillos, entonces es posible crear una parámetro por cada bocadillo que elija que haya en el restaurante, y así mismo definir el precio de cada uno...¿?

**Comment by CataSudo** [comment]
Es lo mismo con los parametros? Tenemos que asignar algun valor x para todos los parametros?
Gracias!

**Comment by bvasquezm** [comment]
Hola @Camila-sty !

Como señala el enunciado, todos los valores descritos de la forma **VALOR_ALGO**, serán evaluados como parámetros. Por lo tanto, para todos aquellos valores que no les fueron entregados en primera instancia, se espera que los asigne el alumno. Tu segunda pregunta correspondería a otra issue, pero de todas maneras te recomiendo revisar con calma la sección de **entidades/bocadillos**.

**Comment by Camila-sty** [comment]
La segunda pregunta tiene que ver con lo mismo. Me refiero a que hay que definir todos los bocadillos como parámetros con su distinto precio¿?, o el precio es único para cada bocadillo?

**Comment by bvasquezm** [comment]
Entiendo tu pregunta, pero idealmente las issues responden a una sola pregunta, para no mezclar temas (por una cosa práctica). De todas maneras, a los bocadillos les corresponde un único precio. 

Saludos!
