### ISSUE TITLE
Formato issue [T07]

### ISSUE THREAD

**Issue by legramsch** [IIC2233/Syllabus#691]
Hola, una pregunta:
Las issues que se mandan al obtenerlas por el comando "/get", tienen el mismo formato que las notificaciones de issues? Tienen que mostrar los comentarios?

**Comment by hanavarrete** [comment]
Claro, la idea es que se mande el contenido y comentarios en caso de haberlos. Saludos!

**Comment by malopez16** [comment]
Colgándome de la consulta (y habiendo leído la issue #666) 

```
[ < autor_issue > ]
[ #1 - < título > ]
< texto >
[ Link: < link > ]

```

La parte que dice <texto> no me queda claro lo que se para cada comando. Hasta ahora entiendo que sería el comentario inicial del problema en la issue (si lo hicieramos con ésta, por ejemplo), sería 

> Hola, una pregunta:
Las issues que se mandan al obtenerlas por el comando "/get", tienen el mismo formato que las notificaciones de issues? Tienen que mostrar los comentarios?

Tb luego de eso tendríamos que agregar una parte final que fuera como

`[hice esto]`

quedando asi:

```
[ < autor_issue > ]
[ #1 - < título > ]
< texto >
[ Link: < link > ]
[hice esto]
```

O al menos eso entiendo yo luego de leer las issues y el enunciado. No está bien entonces?

**Comment by dfvasquez** [comment]
Me sumo a la pregunta de @akaminetzkyp y @malopez16

**Comment by rpalmaotero** [comment]
@akaminetzkyp No lo dice, disculpen la confusión. Cualquiera de las dos formas (incluyendo o no incluyendo comentarios) se considerará correcto.

@malopez16 te refieres a la notificación de que la acción se realizó? Con el comando `/get` el bot va a enviar un mensaje con el formato del enunciado, por lo que ese mensaje se podría considerar como la confirmación de la realización de la acción. Si deseas agregar un mensaje de confirmación separado, o bien, poner al final del mensaje `[hice esto]` no hay problema.

Con el resto de los comandos es más natural pensar que el bot debe enviar un mensaje de confirmación de realización. Basta con que envíe un mensaje del estilo "Cerré issue 123", etc.

**Comment by akaminetzkyp** [comment]
@rpalmaotero, no hay problema. Muchas gracias!
