### ISSUE TITLE
Ejercicios propuestos semana 10: 1.1 y 1.2 

### ISSUE THREAD

**Issue by denisseleiva** [IIC2233/syllabus#691]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola!!! Estaba intentando hacer estos ejercicios y me surgieron algunas dudas 😥

¿Puedo relacionar threads mediante señales con un mismo timer, o para cada thread tengo que hacer un timer diferente? En el caso que se pueda hacer con el mismo timer, ¿Se puede acceder al thread que está enviando la señal? Intenté usar sender() pero me devuelve el objeto que contiene al thread por lo que no me sirvió mucho

En el ejercicio 1.1, ¿La idea es que al hacer clic el movimiento sea como en cámara lenta sin usar QTimer? He intentado usar sleep en el thread que envía la señal de mover el cuadrado al hacer clic pero no obtengo ese efecto como de cámara lenta, sino que funciona parecido al ejercicio de mover el cuadrado de la semana 9. No sé si me pueden dar como un hint de cómo hacerlo uwu

Muchas gracias😊

**Comment by igbasly** [comment]
Hola @denisseleiva :v:

* **Ej 1.1:** Primero, recordar que la funcionalidad de QTimer es llamar a una función dada luego de acabar un tiempo, esto se puede hacer desde 1 hasta N veces dependiendo de como se configure. Ahora, para hacer el efecto de "cámara lenta" se podría pensar en el algoritmo que hay detrás, si estás ocupando QThreads, entonces podría aplicarse la lógica de "mover" -> "esperar" y repetir hasta conseguir lo logrado. Recuerda que `time.sleep` detiene el programa en ejecución, por lo tanto, si estás en thread la ejecución del programa (ventanas) no se verá afectada, en cambio si lo hacen dentro de la ventana misma, entonces el programa de la ventana se detendrá por el tiempo señalado.

* **Ej 1.2:** No estoy seguro a que te refieres con "relacionar threads mediante señales con un mismo timer", ¿hablamos de QTimers? Ya que al final ellos son una especie de Threads gatillados por tiempo. Pero respondiendo un poco a la lógica detrás, mediante la señal pueden enviar información como el Thread de origen, si eso ayuda un poco 😅 .

Espero que se entienda mi explicación, no dudes en preguntar cualquier cosa que no haya quedado claro y quedo atento a información nueva. Mucho éxito!!! :muscle:

**Comment by denisseleiva** [comment]
Holaaa @igbasly
jajajajaj quizás me expresé mal pero mi idea inicial era que los threads llamaran a una función empezar_timer() que partiera un Qtimer "compartido", pero eso no me funcionó y terminé haciendo dos QTimers. Después mi idea era hacer que la funcion empezar_timer() pudiera saber qué thread la llamó (mediante connect) y empezar el QTimer que correspondiera (eso tampoco me funcionó :c) así que hice dos funciones empezar_timer_1() y empezar_timer_2(). Preguntaba porque repetí el código y no quiero repetir código en la tarea jajajaaj

**Comment by igbasly** [comment]
Creo entender un poco más qué es lo que quieres hacer, de todas formas de puedo sugerir lo mismo, entregar algún parámetro mediante la señal a la función del timer, cosa de que sepa quién lo activó. Ahora, aún no me quedó claro si tienes un único timer o son dos, pero de todas formas aplica el mismo principio.

Quedo atento a cualquier cosa :wink:.

**Comment by denisseleiva** [comment]
Mi idea era hacer uno pero no me funcionaba así que pensé que quizás ese era el problema entonces hice dos y ahí funcionó bien jajaja pero le voy a dar una vuelta a lo que me dijiste, muchas gracias! @igbasly
