### ISSUE TITLE
Duda nivel y tamaño de enemigos

### ISSUE THREAD

**Issue by BeaGaete** [IIC2233/Syllabus#691]
Hola!! En la página 2 del enunciado dice que los enemigos con mayor tamaño que el personaje intentarán devorarlo y que los más pequeños intentaran escapar y los de igual tamaño tendrán que decidir en forma aleatoria. Pero en la página 5 del enunciado se habla del nivel para estas mismas instrucciones. Si fuera así todos (el personaje y los enemigos) tendrían el mismo nivel ya que a medida que el personaje gana experiencia sube de nivel y la decisión entre ataca o escapar sería siempre aleatoria no importando el tamaño del enemigo. Supongo que lo correcto es lo primero, es decir por tamaño. Me lo podrían confirmar?
Gracias

**Comment by iqacevedo** [comment]
Hola,

Importa el tamaño de los enemigos, estos no tiene nivel (fue un error hablar de nivel de enemigos).

Saludos !

**Comment by BeaGaete** [comment]
muchas gracias !!!
