### ISSUE TITLE
no reconoce push

### ISSUE THREAD

**Issue by Dunkan1** [IIC2233/Syllabus#692]
![duda](https://user-images.githubusercontent.com/26102365/27505841-fd947422-5877-11e7-8247-863eb35dec0f.PNG)

cuando intento pushear no me reconoce el comando, aunque todo lo anterior se resolvio sin problemas
asi que intente con el siguiente

![dduda](https://user-images.githubusercontent.com/26102365/27505884-ec06ab2a-5878-11e7-9d5f-6dd90691c140.PNG)
 y en este caso no me reconoce prefix 😭

**Comment by MainScientist** [comment]
Probablemente tengas git desactualizado. Intenta ver cuál es la última versión de git y cuál tienes tu e instálala.

**Comment by Dunkan1** [comment]
tengo la version 2.12 y la ultima es la 2.13
no creo que deberia haber un problema con una version tan cercana o si?

**Comment by MainScientist** [comment]
no creo. ¿Estás con la consola de windows?¿ Qué pasa si usas git bash? ¿Qué pasa si pones el path completo a tu carpeta T07?

**Comment by Dunkan1** [comment]
con el bash me ocurre esto
![new](https://user-images.githubusercontent.com/26102365/27506191-59df24a8-5881-11e7-9809-53f3faaaf558.PNG)
 y con el path completo pasa lo mismo

**Comment by MainScientist** [comment]
El error no son los archivos, el problema parece ser que tu versión de git no tiene instalado el plugin de `git-subtree`. Trata de clonar [este repo](https://github.com/apenwarr/git-subtree) y ejecutar `install.sh` desde la consola de git bash.

**Comment by MainScientist** [comment]
Si nada de eso funciona puedes tratar de desinstalar e instalar git otra vez.

**Comment by Dunkan1** [comment]
ejecute install.sh
![enviar_1](https://user-images.githubusercontent.com/26102365/27506663-55ecda34-588b-11e7-9f08-58e8d26d5ec8.PNG)
pero aun asi arroja el error
![enviar_2](https://user-images.githubusercontent.com/26102365/27506665-579aae10-588b-11e7-815c-d6d27ac8011e.PNG)
![enviar_3](https://user-images.githubusercontent.com/26102365/27506666-59a38d76-588b-11e7-91da-1961ab9828c8.PNG)
asi que vi si es que existia y no aparece
![enviar_4](https://user-images.githubusercontent.com/26102365/27506667-5b062d54-588b-11e7-8290-e1c25f019d8c.PNG)
luego reinstale git y intente nuevamente pero nada
![enviar_ult](https://user-images.githubusercontent.com/26102365/27506694-30496346-588c-11e7-9890-d0fee02cc28f.PNG)

ademas cuando hago install.sh abre una nueva terminal y sin hacer nada se sale

**Comment by MainScientist** [comment]
Intenta instalar git de nuevo. Pon atención si hay una opción de instalar plugins.

**Comment by Dunkan1** [comment]
![1](https://user-images.githubusercontent.com/26102365/27506775-9d51e812-588e-11e7-93d2-1579b912b987.PNG)
![2](https://user-images.githubusercontent.com/26102365/27506776-9e866eb0-588e-11e7-9688-927b48a27803.PNG)
![3](https://user-images.githubusercontent.com/26102365/27506777-a05d63b0-588e-11e7-8b18-793a28de9316.PNG)
![4](https://user-images.githubusercontent.com/26102365/27506779-a1d0048c-588e-11e7-9d94-f998de38d7ae.PNG)
![5](https://user-images.githubusercontent.com/26102365/27506781-a355c9fe-588e-11e7-8cd3-d61c877a9594.PNG)
![6](https://user-images.githubusercontent.com/26102365/27506782-a518efc8-588e-11e7-9756-5a03cfcbbdcd.PNG)
![7](https://user-images.githubusercontent.com/26102365/27506783-a6c76890-588e-11e7-87ae-d84927b929ca.PNG)

y nuevamente nada

![capture](https://user-images.githubusercontent.com/26102365/27506792-c2f8cac2-588e-11e7-94bc-9185881aa8d3.PNG)

**Comment by Dunkan1** [comment]
no hay una forma de hacerlo sin subtree

**Comment by MainScientist** [comment]
Lo que pueden hacer es tener una nueva carpeta (fuera de su repositorio) con el código de la tarea, hacen `git init`, `git add` y `git commit`. Luego repiten los pasos para crear la app y hacen el push con `git push heroku master`.

**Comment by Dunkan1** [comment]
ok voy a intentar eso, gracias por estar ayer hasta tan tarde

**Comment by Dunkan1** [comment]
si hago eso no me reconoce el repo de heroku

![capture](https://user-images.githubusercontent.com/26102365/27512493-f00ee65a-590f-11e7-80ab-265915b042a7.PNG)

**Comment by stephichau** [comment]
te falta el heroku create

**Comment by Dunkan1** [comment]
muchas gracias, ahora lo logre, tuve que hacer:
cree la carpeta
pasos del 1 al 6 del enunciado
git init
git add
git commit
git push heroku master
me aparecio el error:
```
          fatal: 'heroku' does not appear to be a git repository
          fatal: Could not read from remote repository.
```
asi que agrege
heroku git:remote -a app-name
hice git push heroku master nuevamente y me funciono 😄
