### ISSUE TITLE
Uso de threading en interfaces

### ISSUE THREAD

**Issue by aurodriguez** [IIC2233/Syllabus#692]
En los objetivos de la tarea sale textual:

"Aplicar conocimientos de threading en interfaces"

Solo quiero confirmar que se refiere a threading en general y no al uso de alguna clase de threading en especifico, como QThread, etc.

**Comment by jerosalazar** [comment]
Me agrego para preguntar si está bien ocupar solamente QTimers y no QThread, ya que ocupando unos 3 threads el programa empieza a tener problemas y caerse.

**Comment by SarahEverke** [comment]
+ 1

**Comment by iqacevedo** [comment]
Hola, 

Esperamos que utilicen alguna de las clases de threading que se han visto en el curso (QThread, QTimers, threading), pueden utilizar una, dos o todas, siempre que utilicen al menos una.

Saludos !
