### ISSUE TITLE
Drag and Drop

### ISSUE THREAD

**Issue by raimundomartinez** [IIC2233/syllabus#692]
Hola. En el Enunciado se dice que se debe usar 'drag and drop'.
¿Que esto y donde puedo encontrar contenido al respecto?
¿Es un event como el mouse event?
No lo encuentro en los contenidos, ¿no se encuentran en los contenidos? Y de ser así, ¿porque no se encuentran en los contenidos?

**Comment by jbulness** [comment]
Hola @raimundomartinez,

El "Drag and Drop" consiste en poder "arrastrar" un elemento de una ventana y  colocarlo en otro lugar, ya sea en la misma ventana o en otra. Un ejemplo de uso común de esta acción es cuando ordenas elementos en el escritorio, manteniendo apretado un archivo o carpeta y moviéndola a otro lugar.

Esto no se encuentra en los contenidos que veremos este semestre, por lo que deberán investigar para poder implementar esto. La razón por la que no se encuentra en los contenidos es para fomentar su capacidad de investigación independiente de distintas funciones, librerías, etc. Esto debido a la gran cantidad de herramientas que podemos encontrar en Python, siendo imposible poder pasar todos estos contenidos en un ramo, por lo que es muy importante que puedan aprender por su propia cuenta por si en el futuro llegan a necesitar implementar elementos nuevos.

**Comment by rldelafuente** [comment]
Hola! Siguiendo la linea de esta pregunta, ¿esto se puede implementar desde Qt Designer o se debe implementar de otra forma?

**Comment by jbulness** [comment]
Hola @rldelafuente,

No me atrevería a decirte que no se puede implementar desde Qt Designer, dado que no lo conozco lo suficientemente bien, pero la verdad es que nunca lo he visto implementado desde ahí y consulté con otros ayudantes y ellos tampoco lo habían visto. Lo que se hace es implementarlo en el código mismo.

Ahora bien, si descubres la forma de hacerlo desde Qt Designer estaría muy agradecido si compartes esa información.

**Comment by rldelafuente** [comment]
Muchas gracias!
Tengo otra duda con respecto a lo que dices... ¿Puedo implementar entonces cosas en Qt Designer y luego agregar o modificar esos labels, por ejemplo, a través del código?

**Comment by jbulness** [comment]
Sí
