### ISSUE TITLE
No se me abren las interfaces gráficas de la AF7

### ISSUE THREAD

**Issue by ValeskaSantos** [IIC2233/syllabus#692]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda
Holaa, por alguna razón cuando corro el código de la actividad formativa, no se me abre ninguna interfaz gráfica, me tira el siguiente error "QPixmap::scaleWidth: Pixmap is a null pixmap
No se pudo conectar a localhost:47365"
Pensé que era por un problema con mi código, pero luego revisando el cierre de la actividad y corrigiendo los detalles, sigue sin mostrarme nada, le agregué la línea de self.controlador.mostrar_login() y todo.
De todas formas, el código lo subí a mi repositorio. 

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by aaossa** [comment]
Hola @ValeskaSantos , perdón por la demora en responder 😅 ¿Aún tienes este problema? Probé con el código que está en tu repositorio y noté que en el cliente y el servidor estás usando números de puertos distintos, entonces el cliente no se puede conectar al servidor. Asegúrate de estar dándole al cliente el puerto en el que el servidor se encuentra. El error del QPixmap no me apareció 🤔 ¿Cómo estás ejecutando el archivo? En la consola, deberías estar dentro de la carpeta del cliente o servidor y ejecutar el archivo así: `python3 main.py` (no deberías tener que indicar `python3 carpeta/main.py`). Cuéntame si algo de esto te ayuda 🙌

**Comment by ValeskaSantos** [comment]
Holaa, había cambiado el puerto para probar con otro, pero si pongo los mismo en cliente y servidor sigue sin funcionar :(, ejecuto el main en cualquiera de las carpetas y me tira el mismo error. Si corre el código con los mismos puertos le funciona? Quizás es un problema de mi computador
![Captura de pantalla 2021-07-01 230155](https://user-images.githubusercontent.com/62099458/124214568-6fd8fe80-dac0-11eb-8232-e50dd7ffbaec.png)

**Comment by aaossa** [comment]
¿Estás corriendo el servidor antes que el cliente? El servidor debería estar corriendo al momento de ejecutarse el cliente. ¿Será eso? 🤔

**Comment by ValeskaSantos** [comment]
Ahora me abrió, creo que no corría bien el archivo del servidor al principio. Muchas graciasss
