### ISSUE TITLE
Problema con instalación Qt Designer

### ISSUE THREAD

**Issue by En-clases** [IIC2233/syllabus#692]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

Hola, intenté instalar Qt designer con el siguiente comando: ```pip3 install PyQt5-tools``` pero la instalación no se hizo correctamente. Intenté buscar "Designer" en el buscador y también en la ubicación: "C:\Users\[Tu usuario]\AppData\Local\Programs\Python\Python[version]\Lib\site-packages\pyqt5-tools\designer" pero no encontré nada en ninguna de las 2 formas.
![image](https://user-images.githubusercontent.com/69520590/96305750-c0f99e80-0fd4-11eb-9cab-5b9677e119b1.png)

**Comment by aaossa** [comment]
Hola @En-clases , probaste haciendo lo que indica el mensaje de error? El comando que tendrías que probar es `pip install PyQt5-tools --user`, para instalarlo solo en tu sesión, ya que al parecer no tienes permisos de admin en tu equipo. Otra opción es intentar instalarlo desde la sesión de admin, para que quede instalado globalmente 👌 Si te funciona o no avisa por acá y vamos buscando nuevas soluciones 🙌
