### ISSUE TITLE
Interpretación de comandos

### ISSUE THREAD

**Issue by rgriver** [IIC2233/Syllabus#693]
¿El bot debe ser flexible en la interpretación de los comandos? Por ejemplo:
```
/label                                             #14             Duplica3
/CLOSE #1
/get #693 ( ͡° ͜ʖ ͡°)
```
Para los comandos anteriores nuestro programa debería reconocer respectivamente `/label #14 Duplica3`, `/close #1`y `/get #693`?

**Comment by akaminetzkyp** [comment]
Muchos bots reales no son así de flexibles. Yo creo que no es necesario que tenga tanta flexibilidad.

**Comment by hanavarrete** [comment]
Esto queda a tu criterio, pero no les pedimos que sea flexible. Tal vez una buena práctica sería que avisara el formato del comando, y te avisara si está mal, pero esto queda a tu criterio. Saludos!

**Comment by rgriver** [comment]
OK. Gracias!
