### ISSUE TITLE
Dinero en pantalla

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#693]
Hola!
Con respecto al ejemplo de la ventana del juego que dan en el enunciado, aparece el dinero, pero este dinero es el que actualmente tiene el restaurante? o es el dinero que van ganando mientras pasa la ronda?
Me refiero a esto:
![duda_dinero](https://user-images.githubusercontent.com/59337116/82152807-d4d88300-9831-11ea-8605-bef712872252.PNG)

**Comment by jitorcas** [comment]
Hola! 

Tal como dice en el enunciado en la sección **3.6 Dccafé**, se te pide como mínimo que mantengas un registro de las **ganancias totales del Dccafé**, por lo que respondiendo a tu pregunta, debería ser el registro **total de dinero** que tiene el jugador, incluyendo los pagos y propinas por parte del cliente. 

Sin embargo, como te pedimos registrar estos datos, podrías hacer la diferencia en la ventana **post-ronda**, mostrando el dinero total y el acumulado en la ronda.

**Comment by Camila-sty** [comment]
ok, gracias
