### ISSUE TITLE
Error con Designer.exe

### ISSUE THREAD

**Issue by Kevinnevik** [IIC2233/syllabus#693]
# Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

Hola tengo un error al abrir el archivo Designer.exe
![Sin título](https://user-images.githubusercontent.com/69523294/96324283-69b8f580-0ff7-11eb-8a32-d1ae3bedccd6.png)

**Comment by aaossa** [comment]
Hola @Kevinnevik , antes de hacer algo más avanzado, ¿podrías probar con la sugerencia del mensaje de error? Pide que reinstales el programa, por lo que puedes usar el siguiente comando: `pip install --upgrade --no-deps --force-reinstall pyqt5-tools`. Si eso no funciona, es posible que haya que mover alguna carpeta a otra ubicación, pero dejemos esa opción solo en caso de que no te funcione reinstalar. Avísame si te funciona o si no funciona para que veamos qué hacer 🙌 ¡Mucho éxito ✨!
