### ISSUE TITLE
Bonus Sprites

### ISSUE THREAD

**Issue by JPSF** [IIC2233/Syllabus#693]
Respecto a la siguiente parte del enunciado:

_Cambio de sprite: debes buscar o crear tus propios sprites que incluyan la animación de movimiento y
que sean acorde a la temática del juego._

1.¿Se refiere para una temática que yo haya escogido o debe ser para la temática de las células? 
2.La misma pregunta pero para el bonus de los fondos

Gracias

**Comment by fnquinteros** [comment]
Hola! La idea es que busques algo con la temática de células o algo por el estilo. Tampoco es la idea que metas imágenes random 😅 pero si te pones creativo y tus imágenes dan a entender todas las funcionalidades que requiere la tarea (si quieres ser extra claro al respecto, está el readme), está bien 👍

Saludos!

**Comment by JPSF** [comment]
Gracias @fnquinteros

**Comment by bawas** [comment]
@fnquinteros ¿ y si entendí mal e hice toda mi tarea con otra temática? pense que se referían a buscar un tema distinto y que todo estuviera con un estilo de acuerdo a eso :C

**Comment by fnquinteros** [comment]
Da lo mismo esta vez, pero en siguientes ocasiones mejor pregunta al respecto 😅 En el enunciado salía que era con la misma temática.

**Comment by PIPEAPABLAZA** [comment]
yo también use otra temática 👎  ... el bonus incitaba a la imaginación/ creatividad.
