### ISSUE TITLE
Problema con interfaz 

### ISSUE THREAD

**Issue by radelamaza** [IIC2233/Syllabus#693]
Mi juego a veces se cae con el siguiente mensaje: Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
He buscado en internet y no he encontrado respuestas satisfactorias al problema.

**Comment by IchottMano** [comment]
@radelamaza Hola!

El error que te aparece es probablemente debido a algo conocido como una *segmentation fault*, que sucede cuando el programa intenta acceder a memoria que no es de él (memoria de otro proceso, del sistema operativo).
A primera vista es difícil decir en que te estás equivocando.
Podrías dar más detalles de tu código? (Que haces cuando se cae, poner prints para ver donde se está cayendo, entre otras cosas)

Saludos!

**Comment by radelamaza** [comment]
Tengo la impresión de que es cuando se agrega un enemigo al mapa (se crea un thread), pero no siempre ocurre.

**Comment by IchottMano** [comment]
Y como instancias esos threads? Como los agregas a tu interfaz?
