### ISSUE TITLE
Error con BothFather

### ISSUE THREAD

**Issue by Okhan97** [IIC2233/Syllabus#694]
![whatsapp image 2017-06-24 at 01 03 02](https://user-images.githubusercontent.com/26289334/27506017-6ca48b40-587d-11e7-9149-32ec370df853.jpeg)

Tengo un error cuando intento hablar con bothfather, no importa que le diga siempre me responde lo mismo D: 

Tampoco se por que me habla en italiano, mi iphone esta en español :/

**Comment by stephichau** [comment]
Busca por su alias : @BotFather :)
