### ISSUE TITLE
Problema con instalación de Qt Designer

### ISSUE THREAD

**Issue by felipe-stuardo** [IIC2233/syllabus#694]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

Holaaa, tengo un problema con la instalación de Qt Designer. Adjunto imagen para visualizar la situación. Se puede ver en el cmd que el archivo PyQt5-tools se encuentra pero con una desviación en su dirección hacia "Roaming" y no hacia "Local". Para ello intente copiar y pegar el archivo en "Local", no se si eso podría generar problemas. Además, al abrir designer.exe se abre una ventana que indica no encontrar un archivo específico (también se adjunta imagen). Busqué el archivo y no lo logro encontrar, no se que puedo hacer para reinstalar el programa. Muchas gracias por todooo!!!

![image](https://user-images.githubusercontent.com/69651465/96324850-2b710580-0ffa-11eb-8f08-9b35573977a5.png)
![image](https://user-images.githubusercontent.com/69651465/96324898-6d9a4700-0ffa-11eb-9081-123fac17e724.png)

**Comment by felipe-stuardo** [comment]
Logré solucionar el problema, muchas gracias de todos modos!

**Comment by aaossa** [comment]
Hola @felipe-stuardo , en primer lugar no deberías mover carpetas que fueron creadas durante la instalación de un programa. Verás, probablemente en alguna parte de tu sistema operativo hay una variable que le dice a Windows: "si quieres abrir este programa, tienes que ir a esta carpeta y correr este archivo", si mueves algo inesperadamente Windows no tiene cómo saberlo y al intentar ir a la carpeta y buscar el archivo va a encontrarse con que no existen, provocando un error. 

Te recomendaría intentar devolver los archivos a su ubicación original y luego volver a probar si funciona Qt Designer. ¿Esto te lanzaba una excepción y por eso decidiste moverlo? Si no funciona, prueba desinstalando y reinstalando, pero esta vez con `pip install PyQt5-tools --user` (lo importante es la última parte). Si te provoca un error o excepción, coméntalo por acá y lo tratamos de arreglar 👌 ¡Mucho éxito!

**Comment by felipe-stuardo** [comment]
Buenas tardes! Intenté desisntalar y reinstalar como usted me lo recomendó, sin embargo, me arroja la siguiente advertencia (adjunto imagen). Por ello decidí ir a la dirección indicada al final de la advertencia, y encontré todos los documentos que se mencionaban en la misma, y al ejecutar designer.exe se abre la aplicación, sin embargo, no se porque estos no se encuentran en la dirección que se nos indica en los contenidos (se desvian en la carpeta Roaming en vez de ir a Local). Lo bueno es que ahora puedo abrir Qt Designer, pero solo desde ese archivo y al crear atajos desde otras carpetas me arroja el mismo error de antes (el de la segunda imagen del issue anterior). No se como solucionar este problema, ya intenté desinstalar de nuevo, y volver a instalar, pero los archivos nuevamente se van a Roaming y no a Local. Muchas gracias por toda la ayuda 👍 

![image](https://user-images.githubusercontent.com/69651465/96346346-aa555500-1071-11eb-8882-8240ba8c6ff8.png)

**Comment by aaossa** [comment]
@felipe-stuardo solo por si acaso, si cierras la consola y la vuelves a abrir, ¿se abre Qt Designer con el comando `designer`? Lo otro, al final te funciona? No entendí si quieres seguir arreglándolo o estás bien con eso 😅

**Comment by felipe-stuardo** [comment]
Buenas!! Intenté desinstalar y reinstalar como me lo mencionó, sin embargo, no funcionó y los archivos por alguna razón se dirigían a roaming. Luego intenté el siguiente código `pip install --upgrade --no-deps --force-reinstall pyqt5-tools` el cual me permitió solucionar el problema e instalar bien el programa. Ahora me ocurre el mismo error que en el Issue #698 por lo que esperaré a esa respuesta (Adjunto imagen) pero al utilizar el comando `designer` en la consola si se ejecuta :), asi que creo que está solucionado el problema. Para crear un acceso directo en mi escritorio debo utilizar el designer.exe? Muchas gracias por toda la ayuda!!!

![image](https://user-images.githubusercontent.com/69651465/96346966-09689900-1075-11eb-8b8b-f1ae179244eb.png)
![image](https://user-images.githubusercontent.com/69651465/96347136-f1454980-1075-11eb-9fb3-590f3e80875a.png)

**Comment by aaossa** [comment]
Mmm lo que debe estar pasando es que el comando `designer` está apuntando a otro *.exe, no al que estás ejecutando. Te recomiendo utilizar el comando `where designer`, que te mostrará una ruta indicando dónde está el ejecutable abierto por ese comando. Si quieres crear un acceso directo para abrir Qt Designer más fácilmente, tiene que ser a ese *.exe 👌 Como referencia, en mi consola me muestra así el *output*:

![imagen](https://user-images.githubusercontent.com/10425834/96347186-716baf00-1076-11eb-9f40-dddda338a381.png)

**Comment by felipe-stuardo** [comment]
Tengo la misma dirección :). Creé el acceso directo y funciona a la perfección 😃. El único detalle es que no aparece con el icono de Qt si no que con un icono de Python pero es un detalle insignificante. Muchisimas gracias por toda la ayuda profe!! Se pasó 😊

**Comment by SebastianFerra** [comment]
Hola yo tengo instalado python en otro disco que  no es el principal C entonces no se como llegar a designer así, además no tengo idea de como desinstalarlo (probé en el panel de control -> desinstalar programas y solo me daba la opción de desinstalar python)
