### ISSUE TITLE
Iterables, Generadores y Excepciones en T02

### ISSUE THREAD

**Issue by Araos827** [IIC2233/syllabus#694]
Hola! quería saber si es que se espera que usemos estos contenidos de la T02 o si es que almenos lo recomiendan o no para tenerlo en cuenta al momento de modelar el juego :) gracias!

**Comment by fdoflorenzano** [comment]
Hola @Araos827,

Los contenidos no son mínimos para la tarea, pero si puedes utilizarlos para su implementación. Es difícil dar recomendaciones específicas, ya que son herramientas de uso general y se pueden aplicar en varios escenarios. Si no te acuerdas de ellos, puedes darles una leída rápida para recordar sus usos y ver si te ayudan con alguna cosa.

También, ojo que lo único prohibido en el caso de excepciones es hacer captura genérica de errores utilizando solamente `except` o `except Exception`. Eso se menciona en la _issue_ #680.

Espero quede claro, cualquier duda nos avisas.
Saludos.
