### ISSUE TITLE
Poderes en interfaz

### ISSUE THREAD

**Issue by llloyola** [IIC2233/Syllabus#694]
¿Es necesario tener que visualizar cada _power-up_ que adquiera el jugador durante la partida? ¿Puedo tener una especie de contador? Si el jugador juega mucho tiempo y recoge muchos _power-ups_ podría quedarme sin espacio para todos éstos en pantalla

**Comment by leolivares** [comment]
@llloyola La idea es poder visualizar todos los power-ups y poderes.
Si, podrías hacer un contador para ahorrar espacio. Recuerda que los poderes deben mostrarse solo mientras dure su habilidad.
