### ISSUE TITLE
Duda metodo recv()

### ISSUE THREAD

**Issue by tamyhan** [IIC2233/syllabus#695]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

Hola! Tengo una duda con el método recv de socket. Cuando uno lo llama más de una vez consecutivamente, se van leyendo los bytes que van quedando o se vuelve a leer desde el principio?
Por ejemplo, si tengo un mensaje de 10 bytes, y hago:
msg_1 = socket.recv(5)
msg_2 = socket.recv(5)

msg_1 y msg_2 van a ser iguales? O msg_1 son los primeros 5 bytes y msg_2 son los segundos 5 bytes?

**Comment by tqmbanados** [comment]
Hola! Lo correcto es la segunda opción, es decir, `msg_1` y `msg_2` serán distintos. 
Al leer bytes, el método `recv` los va sacando de la cola (o *stream*), algo como llamar sucesivamente el método `popleft` de un `deque`.  Eso quiere decir que una vez leídos, **ya no son parte del stream**.

**Comment by tamyhan** [comment]
Gracias!

**Comment by tamyhan** [comment]
Sii! Gracias!

**Comment by jesusotov** [comment]
Hola! Tengo una duda con la diferencia entre el método recv y el método read. 
Su principal diferencia es que uno es método de socket y el otro no, o tiene otra diferencia por ejemplo en el método de lectura que recv hace popleft

**Comment by tqmbanados** [comment]
Hola! @jesusotov, efectivamente, ambos métodos se comportan de manera muy parecida, pero como bien dices, son de clases distintas. 
Entre sus similitudes:
1) Al leer un elemento, se avanza al siguiente, es decir, **no se puede volver a leer el mismo elemento** (similar al "popleft").
2) Recibe como argumento cuantos elementos leer. 

Diferencias:
1) **Son de clases distintas**. Algo así como el `append` de `list` y el `add` de `set`, hacen cosas similares, pero en el fondo al ser clases distintas funcionan de otra manera. Por ejemplo, el tipo de excepciones que lanzan `read` y `recv` son distintas, y se lanzan por distintos motivos!
2) `recv` tiene argumentos adicionales que no usamos en el curso, que personalizan más la lectura.
3) `recv` siempre retorna `bytes`, `read` puede retornar `str`.

**Comment by jesusotov** [comment]
Perfecto! Muchas gracias!
