### ISSUE TITLE
Configurar barra de menús en QMainWindow

### ISSUE THREAD

**Issue by denisseleiva** [IIC2233/syllabus#695]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola!! Tengo un problema con la parte de QMainWindow. Corrí el ejemplo que dan en el notebook en vscode como un archivo .py y no encuentro los menús. ¿Tengo que instalar algo o falta hacer un setmenu o algo por el estilo?

Esto es lo que obtengo al ejecutar el código:

<img width="293" alt="Captura de pantalla 2020-10-16 a la(s) 22 55 38" src="https://user-images.githubusercontent.com/69520522/96325926-cf5eaf00-1002-11eb-888d-6a9729294424.png">

Es como que me aparece sólo la barra de herramientas y no los menús Archivo y Otro Menú 😥

Muchas graciassss😁

**Comment by igbasly** [comment]
Hola @denisseleiva :v:

Por lo que veo, utilizas MacOS, por lo cual me tiento a sugerir que los menús que estás buscando aparecerán en la parte superior de tu pantalla. A diferencia de la Windows, estos menús no aparecen en la ventana misma.

Dime si es que es esto lo que ocurre o si definitivamente no aparece. En cuyo caso podríamos ver el código que estás intentando ejecutar.
Quedo atento, saludos! :smile:

**Comment by denisseleiva** [comment]
jajajjajaja no te creoooo, ya aparecieron!!! Muchas gracias!!! @igbasly Creo que sería importante mencionar ese dato en los notebooks jajajaja

**Comment by igbasly** [comment]
Jajajaj Gracias a ti!! Definitivamente lo tendremos en consideración para los próximos semestres 🙌
