### ISSUE TITLE
Expovariate hostil

### ISSUE THREAD

**Issue by nicoparraguez** [IIC2233/Syllabus#695]
Me sucede que cuando le doy el lambda , esto puede provocar que aparezcan enemigos muy rápido,se puede poner un mínimo de valor para que no suceda que se llene de personajes hostiles.

Es decir min(expovariate()) y que tome por lo menos un valor minimo (resumido) 
de antemano,muchas gracias

**Comment by fringlesinthestreet** [comment]
Hola @nicoparraguez 

Puedes generar el tiempo y luego hacer `max(tiempo_generado, TIEMPO_MINIMO)`.

Espero te sirva!
