### ISSUE TITLE
Heroku again

### ISSUE THREAD

**Issue by berrazuriz1** [IIC2233/Syllabus#695]
Mi problema es que no puedo hacer push. He visto todas las issues y no lo he googleado y nada me ha funcionado. Tengo los archivos de configuración bien también, igual los pueden revisar en mi repo. El error que primero me arrojaba tratar de hacer push era que el lenguaje no estaba seteado, así que setié un buildpack de heroku/python, pero después de hacer esto me arroja:
![sin titulo](https://user-images.githubusercontent.com/26139774/27506131-2cd4964c-5880-11e7-838c-f5962e82704a.png)
No se si la imgen se ve. Pero la cuestion es que estoy creando la app con el comando heroku create y aun así, no funciona. Ayuda, no he podido avanzar nada por esto.

**Comment by MainScientist** [comment]
El comando para pushear a heroku debe ser el especificado en el enunciado.

**Comment by berrazuriz1** [comment]
Tambien trate con ese comando, y nada.

**Comment by MainScientist** [comment]
¿Qué error salió cuando usaste ese comando?

**Comment by berrazuriz1** [comment]
![git](https://user-images.githubusercontent.com/26139774/27506476-34f20dc2-5886-11e7-8095-7174d9c157ac.png)

**Comment by berrazuriz1** [comment]
pude ser que no tenga la version adecuada de python?

**Comment by MainScientist** [comment]
¿Puedo ver tus archivos `runtime.txt`, `requirements.txt` y `Procfile`?

**Comment by MainScientist** [comment]
Tienes un typo. El archivo es `requirements.txt` (en tu repo este archivo tiene mal el nombre). Además el archivo `Procfile` no lleva la extensión `.txt`.

**Comment by berrazuriz1** [comment]
Naaa, lo del procfile si tiene la extension de txt, lo voy a hacer de nuevo por si acaso, pero no me fije en el nombre de requirements. Gracias.

**Comment by MainScientist** [comment]
El archivo `Procfile` no debe llevar extensión. Quítasela.

**Comment by berrazuriz1** [comment]
Pero si tiene que ser un documento de texto, cierto?

**Comment by akaminetzkyp** [comment]
Contiene texto pero no tiene la extensión `.txt`.

**Comment by berrazuriz1** [comment]
Que grande, ahi salio, muchas gracias, era una tontera.
