### ISSUE TITLE
Layout: Alineacion Vertical y Horizontal

### ISSUE THREAD

**Issue by enriquemolinare** [IIC2233/syllabus#696]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

En los contenidos de la semana 9 en "elementos graficos" no me quedó muy claro el "display"  del layout. Entiendo que el layout horizontal (QHbox) toma todo los widgets  y los posiciona alineados de forma horizontal. Lo que no entiendo, es porque todos los widgets que toma los desplega  justo en el centro de la ventana - tal como se muestra en la imagen a) - pero en realidad  nunca se determinó la posición donde debía ser desplegado el layout. Al mismo tiempo, no entiendo porque en el layout vertical desplega todos los widgets en la parte inferior de la ventana.

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by aaossa** [comment]
Hola @enriquemolinare , los *layouts* intentan repartir equitativamente el espacio que ocupa un *widget*, por lo que si solo colocas uno, va a colocarlo al centro para que quede a igual distancia de los bordes (lo que puedes comprobar colocando un único elemento en un *layout* vertical dentro de uno horizonal). Es como si colocaras los *widgets* sobre una tela elástica (el *layout*) y luego intentaras estirar esta tela: aumenta el espacio hacia las orillas, pero también entre los *widgets* (efecto que también puedes comprobar cambiando el tamaño de la ventana manualmente cuando ya está abierta). 

Sobre por qué en el *layout* vertical los *widgets* quedan abajo, es porque en el código de ejemplo se ocupa un *stretch* grande sobre el *layout* horizontal, en la línea `vbox.addStretch(5)`. Lo que hace un *stretch*, tal como se indica en el mismo código, es agregar un espaciador, que puede tener distintas proporciones. La idea es que los ocupes para mantener la proporción que quieras en tu interfaz. Si no colocas espaciadores, quedará justo en el centro, tal como si agregaras la misma cantidad de espaciadores a cada lado (por ejemplo, uno arriba del *widget* y uno abajo). Prueba cambiando el *stretch* de 5 a otros valores y verás cómo se mueven los elementos pero se mantiene la proporción al cambiar el tamaño de la ventana. 

Ojalá esto aclare tu duda 👌 Si algo no se entienda pregunta por acá mismo. ¡Éxito ✨!

**Comment by enriquemolinare** [comment]
Perfecto, lo entiendo. Muchas gracias
