### ISSUE TITLE
Error interrupted by signal

### ISSUE THREAD

**Issue by felipecr00** [IIC2233/Syllabus#696]
He estado presentando un problema con mi tarea, el sistema me indica:
"Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)"
Mi computador genera este error inesperado, (el cual no comprendo porque sale). 
La pregunta es, si en algunas ocasiones el juego se cierra inesperadamente por algo que ya no puedo controlar, se puede justificar en el ReadMe? o alguien sabe el porque de este error?
Cambie de threads a Qtimer, a mezclas de ambos, pero de todas formas se presenta algunas veces este error.

Saludos!

**Comment by vijuarez** [comment]
Hola!

Hasta donde tengo entendido, el error 139 se refiere a una acceso inválido de memoria, donde tu programa esta tratando de leer RAM donde no le corresponde. Esto normalmente ocurre cuando tu programa  ocupa demasiada memoria, en especial si estas corriendo en un ambiente de poca RAM. 

Intenta buscar si no tienes una lista o recursión infinitas/extremadamente grandes, ya que esto puede generar errores así de forma silenciosa. También sirve monitorear el uso de ram, para ver si puedes descubrir en que momento se desencadena el error. Si no encuentras nada, puede ser que alguna librería este provocando el error por detras. En esos casos, mencionalo en el README y, si efectivamente no fue error tuyo, no debería llevar descuento.

Saludos

**Comment by Jamidd** [comment]
Intenta ver si desde algún thread llamas a una función de otro o del main sin ocupar señales, a mi me paso, agregue la señal correspondiente y funciona perfecto.
Pd. aparentemente no hay problema si el main llama a una función de un thread hijo pero no al revés.

**Comment by felipecr00** [comment]
@vijuarez , gracias por tu respuesta, efectivamente estaba relacionado con memoria.
@Jamidd hice lo que comentaste y nunca mas se pego jajajaja. Estaba usando un Thread para la animación y no estaba emitiendo señales, ahora funciona perfecto!! Muchas gracias. <3
