### ISSUE TITLE
Error al ejecutar pantalla creada en QtDesigner

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#696]
Hola!
Utilicé QtDesigner para crear una ventana, luego de haberla creado quise incorporar la interfaz a python siguiendo el código que presentan en los contenidos de la semana 11 (específicamente en contenidos de Qt Designer), luego al correr este código en VSC me sale el siguiente error:
![error-ventana1](https://user-images.githubusercontent.com/59337116/82157072-4d990880-984d-11ea-936c-fecf75dbeaf4.PNG)
Qué estará mal¿?
En la carpeta T02 guardé los siguientes archivos (mediante la creación de la ventana en Qt Designer) que se me pedían para poder usarlos en código python:
![archivos-designer](https://user-images.githubusercontent.com/59337116/82157161-d748d600-984d-11ea-87b9-fe5a30f03fdf.PNG)
Guardé bien los archivos¿?

**Comment by RenatoVWS** [comment]
Holaa yo también tuve ese problema y es por cargar las imagenes. Segun lo que vi en este video https://www.youtube.com/watch?v=4UTHNpiL-Mk tienes que convertir ventana1.qrc a un archivo .py para que lo corra.

Lo que hice para arreglarlo fue hacer la ventana sin las imagenes y luego se las cargue.

Ojalá te sirva :)

**Comment by Camila-sty** [comment]
Sip, puedo hacerlo sin cargar imagenes, pero mi idea era implementar la imagen altiro y poder pasarlo a python.
Gracias!!

**Comment by Camila-sty** [comment]
@RenatoVWS después de haber cargado la ventana sin la imagen en python, cómo agregas la imagen a éste código? 
Y use este código para cargar la ventana y poder verla en VSC, pero no se me ocurre cómo agregar algo a la misma ventana...
![cargarventana](https://user-images.githubusercontent.com/59337116/82230037-3283d280-98f9-11ea-9f50-329eb418314a.PNG)

**Comment by aaossa** [comment]
Hola, ojo que hay una pregunta muy similar en #690, por si les sirve la respuesta que está allá ✨ No cerraré esta issue para no cortar la conversación, pero si logran solucionarlo también comenten la otra *issue* plis 🙌 

PS: Para acceder a los *widgets* de una ventana creada con Qt Designer, pueden ver que en los últimos ejemplos del cuaderno de Qt Designer en los contenidos se accede a ellos de la forma regular (`self.nombre_widget`). Con esto, podrían colocar el `QLabel` en Qt Designer y colocarle el `QPixmap` desde su código 👌
