### ISSUE TITLE
Comando /label

### ISSUE THREAD

**Issue by alobatog** [IIC2233/Syllabus#696]
En el enunciado dice que cuando se le manda el comando /label al bot, este debe asignar la etiqueta a la issue correspondiente. Pero en el caso de que la issue ya tenga una etiqueta, esta se cambia por la nueva? o se agrega la nueva y queda con las dos?

**Comment by FernandoPieressa** [comment]
Se agrega la label y queda con dos

Saludos!

**Comment by alobatog** [comment]
Graacias!
