### ISSUE TITLE
Uso de comando en la terminal para pasar diseño de Qt Designer a Codigo 

### ISSUE THREAD

**Issue by mpenalozag** [IIC2233/syllabus#697]
Hola para pasar los diseños de Qt designer a codigo queria saber si esta permitido hacer lo siguiente en la terminal:

C:\Users\Usuario\pyuic5 -x nombre_archivo.ui

Lo anterior me convierte el diseño a código pero no se si es correcto o mala práctica.

Gracias de antemano

**Comment by Alonsinho1** [comment]
Hola, no se si sea mala practica o no la verdad, pero quizas estas sobrecomplicandote.

La gracia de hacer ventanas en Qt es que estas ya tienen "Codigo" definido de antes y este quedara utilizable cuando heredes la ventana.

Caso concreto, si en designer crear un label que se llame "label1" y luego heredas la ventana en tu codigo, es cosa de luego escribir self.label1 para llamar o utilizar a ese label que creaste en la ventana.

A lo que voy es que no es necesario pasarlo a codigo, solo necesitar el archivo .ui

Suerte!
