### ISSUE TITLE
 QlineEdit(): sin Self y sin dimensiones

### ISSUE THREAD

**Issue by enriquemolinare** [IIC2233/syllabus#697]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda
En los contenidos de la semana 9 en el modulo 2 en la última parte de CampoFormulario no me quedó muy claro cuando se crea la casilla de input  "campo = QlineEdit()".
 Primero, porque no se debe ingresar "self" en los parametros de   QlineEdit(). Quizás no me quedo muy claro a que se referian con esta frase "Prueba no entregando self a las instancias de QLabel y de QLineEdit, y observarás que no aparecen los elementos dentro de la interfaz. ¿Por qué? En ese caso, solo se crean instancias de los elementos, pero al no tener un widget padre al que pertenecen, no se visualizan". 
Segundo, **¿Por qué no ingresaron las dimensiones de la casilla "campo"?**

Codigo
```python
class CampoFormulario(QHBoxLayout):
    # Heredamos de Layout Horizontal para colocar cada campo.

    def __init__(self, texto, *args, **kwargs):
        # Llama al constructor de la clase madre
        super().__init__(*args, **kwargs)
        
        # Crea la etiqueta y cuadro correspondientes
        label = QLabel(f"{texto}: ")
        campo = QLineEdit("")
        
        # Los coloca dentro del Layout
        self.addStretch(1)
        self.addWidget(label)
        self.addWidget(campo)
        self.addStretch(1)
```

**Comment by igbasly** [comment]
Hola @enriquemolinare :v:

La situación que mencionas es algo compleja de explicar, pero intentaré hacer lo mejor 😅. 
Cuando  uno crea *Widgets* en PyQt debe asegurarse de que estos "prevalezcan en el tiempo", vale decir que si crearas una ventana simple como la siguiente:
```python
```

**Comment by igbasly** [comment]
Hola @enriquemolinare :v:

** ¿Por qué `self`?:**
La situación que mencionas es algo compleja de explicar, pero intentaré hacer lo mejor 😅. 
Cuando  uno crea *Widgets* en PyQt debe asegurarse de que estos "prevalezcan en el tiempo", vale decir que si crearas una ventana simple como la siguiente:
```python
class Ventana(QWidget):
    def __init__(self):
        super().__init__()
        self.setGeometry(200, 200, 200, 200)

        texto = QLabel("Hola")

        self.show()
```
Entonces obtendrás una ventana vacía. Esto ya que el *QLabel* que se instanció no tenía asignado un padre y quedó en una variable local que fue desechada posteriormente. Aquí es importante destacar que los padres de los *Widgets* deben ser *Widgets* y no *Layouts*.
Entonces, si solo quisiéramos desplegar nuestro *Label* del ejemplo, basta con agregar un `self` al final y se mostrará.
```python
        texto = QLabel("Hola", self)
```
Esto hará que el *Widget* quede en la esquina superior izquierda de la ventana, a menos que ocupemos `.move` para darle otra ubicación.

**Layouts: :framed_picture:**
Ahora, si además consideramos que podemos utilizar otros elementos como los *Layouts*  para darle forma y estructura a nuestras interfaces, entonces entramos a tratar en otro territorio. Como dije antes, si utilizas `self` para signarle un padre al *Widget*, entonces le estás diciendo que ese elemento estará dentro del padre en la posición `(0,0)`, pero con los *layout* la idea es que esto sea flexible, que la posición vaya cambiando. Aquí como se indica en el ejemplo que me muestras, utilizamos `.addWidget` para entregarle un elemento al *layout*.
Esto ya es una forma de hacer que el elemento se contenga, o sea, con eso ya estamos diciendo que el *Widget* estará contenido en el *layout*, por lo tanto, ya no es necesario agregar el `self`. Además hay que considerar que ahí se estaba modelando una clase *Layout* personalizada, por lo tanto, si le entregamos `self` al *Widget* obtendremos un error, ya que solo pueden recibir otro *Widgets* como padres.

Por último, si vemos la cadena completa, podemos observar que finalmente todo está contenido y estos elementos ya fueron asignados, por lo tanto, se mostrarán al momento de desplegar la ventana. Aquí ocurrió algo así:
`QLabel` -(.addWidget)-> `QHBoxLayout` -(.addLayout)-> `QWidget`
Donde no fue necesario agregar `self`, ya que los métodos utilizados manejaban eso por nosotros. Pero en el ejemplo que coloqué más arriba, fue algo así:
`QLabel` --> `QWidget`
Y tuvimos que recurrir al uso de `self`, ya que no había otra forma de asignar las relaciones.

**Conclusión: :bulb:**
Es importante siempre ir notando como se van formando las relaciones entre los elementos de nuestras interfaces, ya que podría ocurrir que no se estén signando bien y por lo tanto, no se estén desplegando como quisiéramos. Esto, va a depender directamente de que tipo de elementos estemos utilizado, lo cual nos indicará si es necesario agregar un `self` o simplemente utilizar un método de la clase.

Antes de terminar, respondiendo a tu segunda pregunta, esto es simplemente porque no es necesario, ya que la idea de utilizar *Layouts* es que el tamaño varíe y se adapte al tamaño de la ventana. De todas formas puedes establecer estas dimensiones si así lo quieres :+1:.

Espero que esto haya aclarado un poco el funcionamiento de estos elementos y tus dudas al respecto. Por supuesto si algo no quedó claro o tienes otra pregunta relacionada, no dudes en escribir de vuelta 🙌 . Mucho éxito en el estudio, saludos! :smile:

**Comment by enriquemolinare** [comment]
sii, muchas gracias por la respuesta.

**Comment by gaspcr** [comment]
Una pregunta con respecto al uso del **self** en los Widgets

`texto = QLabel("Hola", self)`

`self.texto = QLabel('Hola')`

¿Son ambas válidas a la hora de crear un Widget?

**Comment by enriquemolinare** [comment]
Me quedo una duda respecto a la afirmación " Aquí es importante destacar que los padres de los Widgets deben ser Widgets". A que se refiere que un Widget sea padre de otro Widget. Lo otro, todos los widget deben tener un padre?

**Comment by aaossa** [comment]
> 
> 
> Me quedo una duda respecto a la afirmación " Aquí es importante destacar que los padres de los Widgets deben ser Widgets". A que se refiere que un Widget sea padre de otro Widget. Lo otro, todos los widget deben tener un padre?

Respondido en https://github.com/IIC2233/syllabus/issues/716

**Comment by igbasly** [comment]
> Una pregunta con respecto al uso del **self** en los Widgets
> 
> 
> 
> `texto = QLabel("Hola", self)`
> 
> 
> 
> `self.texto = QLabel('Hola')`
> 
> 
> 
> ¿Son ambas válidas a la hora de crear un Widget?

Hola @gaspcr :v:
Respondiendo a tu dud ocurren dos cosa:
* `texto = QLabel("Hola", self)` hace referencia a entregar al mismo *widget* `self` como padre del nuevo label. Explicado más arriba y en la issue #716.
* `self.texto = QLabel('Hola')` hace referencia a crear un nuevo atributo del objeto, el cual se puede acceder mediante `self.texto` desde cualquier parte de la clase. A diferencia del ejemplo anterior donde solo es una variable local `text`.
