### ISSUE TITLE
Reemplazar item

### ISSUE THREAD

**Issue by Jiruiz2** [IIC2233/Syllabus#697]
Al momento de reemplazar un item el enunciado dice que se pierde el bonus que daba, pero por ejemplo si tengo 2 items de vida, los buffs que da cada uno no son iguales, por lo que mi pregunta es si debemos devolver el stat a cuando solo teníamos un item de vida o diferenciar cuanto aportó cada uno y quitar el bonus según corresponda.

**Comment by iqacevedo** [comment]
Hola, 

Es como si quedara con uno, no es que uno aporte más que el otro, solo que como uno se aplica después su efecto es mayor. De esta manera, cuando sacas un ítem de vida y tienes 2, quedara como si solo tuvieras uno.

Saludos !
