### ISSUE TITLE
Modularizacion de tarea

### ISSUE THREAD

**Issue by chuma9615** [IIC2233/Syllabus#697]
Es necesario modularizar esta tarea? ya que al ser corta no le veo sentido en modularizar cosas tan pequeñas. Saludos!

**Comment by MainScientist** [comment]
Sí, deben modularizar debido a que a pesar de que las cosas son pequeñas es importante tener las diferentes lógicas de la aplciación separadas (flask, telegram, github). De esta forma editar el código y extenderlo les es más sencillo en el futuro (y ese es uno de los aprendizajes que esperamos que logren).

**Comment by nivek0o0** [comment]
Hola, si modelo las lógicas separadas en clases distintas como tu dices y necesito llamar métodos de una clase a la otra. Es válido que cada una tenga una referencia a la otra?
