### ISSUE TITLE
Duda enunciado: clientes y bocadillos

### ISSUE THREAD

**Issue by furcelay** [IIC2233/syllabus#698]
Hola,
Por lo que entendí del enunciado no existe diferencia entre los bocadillos más que en parámetros que se definen por el chef que los prepara, y asimismo los clientes no hacen pedidos específicos sino que esperan a que les traiga un bocadillo cualquiera.

¿Es esto correcto o lo interpreté mal?

**Comment by bvasquezm** [comment]
Hola @furcelay!

Correcto. No hay diferencias aparte de lo que señalas.
