### ISSUE TITLE
404 Not Found en github 

### ISSUE THREAD

**Issue by fantineen** [IIC2233/Syllabus#698]
hola estaba tratando de hacer el webhook de github hacia mi route pero pese a que se creó el webhook sin problemas me sale el siguiente error, queria saber porque podria estar fallando en encontrar mi route
 :( 
`
404 Not Found
Not Found
The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again`

**Comment by MainScientist** [comment]
¿Puedes acceder a tu app de heroku desde el navegador? De ser así quizás el problema es que tu ruta no está configurada para recibir el método `POST`.

**Comment by fantineen** [comment]
estoy usando ngrok por el momento, pero se soluciono :D lo que pasaba era que cada vez que ejecutaba el codigo en sublime, yo estaba trabajando con la primera version que tenia (y que no tenia implementado el webhook) y como el puerto quedaba ocupado por esa primera version, las siguientes no se ejecutaban.
Al final cerre todo desde el task manager y ahi pude correr la version mas reciente. gracias :)
