### ISSUE TITLE
Problema ejecución designer.exe (Windows)

### ISSUE THREAD

**Issue by ignaciomansuy** [IIC2233/syllabus#698]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

Hola!
Cuando trato de abrir designer.exe, me lanza el siguiente error: 

![image](https://user-images.githubusercontent.com/64439029/96339975-5f860e00-106e-11eb-8720-ffc9eaf096e8.png)

Ya miré las issues relacionadas (#694 , #693 y #692) y corrí los comandos que mencionaron ( `pip install PyQt5-tools --user`  y `pip install --upgrade --no-deps --force-reinstall pyqt5-tools`). Sin embargo, el error persiste.

¡Muchas gracias de antemano!

**Comment by aaossa** [comment]
Hola @ignaciomansuy , estamos viendo un problema similar en #694 , puedes ver si el comando `designer` en cmd te abre Qt Designer?

**Comment by ignaciomansuy** [comment]
Hola! Siii, funcionó ese comando. ¡Muchas gracias!
