### ISSUE TITLE
Duda enunciado: reputación

### ISSUE THREAD

**Issue by furcelay** [IIC2233/syllabus#699]
Hola,
En la sección  de `Entidades`, `DCCafé` dice que `Calcular reputación` se ejecuta al final de la ronda, pero en la sección de `Interfaz`, `ventana de ronda` dice que la reputación se actualiza a medida que avanza la ronda.

¿Me quedo con esto último?

**Comment by bvasquezm** [comment]
Gracias @furcelay por tu comentario. La reputación se calcula únicamente al final de la ronda o post-ronda, así que lo primero que mencionas sería lo correcto. Si revisas la fórmula puede que te quede más claro. 

Saludos.
