### ISSUE TITLE
Error enunciado T06? formato multicanal

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#699]
Sé que es una cosa chica, pero el enunciado dice que solo usaremos midis con un único canal, mientras que en el punto 3.1 dice que solo usaremos el el valor 1 (multicanal).

Gracias~

PD: asumo que en esto no estamos contando el bonus.

**Comment by Hernan4444** [comment]
@jmwielandt precisamente usarán midis con un único canal, pero el formato tiene que ser el multicanal, pero solo tendrá 1.
