### ISSUE TITLE
Tiempo Aparición Elementos del Juego

### ISSUE THREAD

**Issue by simontoya** [IIC2233/Syllabus#699]
En el enunciado sale que las apariciones de cada objeto son aleatorias en tiempo uniforme entre 1 y 30. Esto se refiere a que cada objeto tiene un tiempo de aparición  independiente o todos tienen el mismo tiempo de aparición pero es aleatoria la elección del tipo de elemento que aparecerá?

**Comment by fringlesinthestreet** [comment]
Quizás la issue #652 te sirva :)
