### ISSUE TITLE
Problema de dependencia de packages para descargar QtDesigner

### ISSUE THREAD

**Issue by JanHellema** [IIC2233/syllabus#7]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

He seguido todas las instrucciones de software obligatorio, y he descargado todo lo que piden correctamente hasta PyQt5. Al momento de intentar descargar QtDesigner con el siguiente comando: pip3 install pyqt5-tools me tira error, adjunto imagen

![image](https://user-images.githubusercontent.com/80780539/111653784-ec342400-87e6-11eb-8b58-a0aa7703e0d0.png)

He intentado descargar QtDesigner del link que esta en las instrucciones, pero no me abre debido a que macOS no puede verificar si la app esta libre de software malicioso (podría abrirlo de todas formas pero no me quiero arriesgar)
También he intentado arreglar el problema apretando el link que aparece abajo en la foto, pero no sé cómo hacerlo.

**Comment by dfloreaa** [comment]
Hola! por lo que veo estas intentando descargar varias versiones de pyqt5 tools en tu computador y no solo una

![image](https://user-images.githubusercontent.com/62019645/111654786-d5da9800-87e7-11eb-8067-d415cf9137ef.png)

Intenta solamente corriendo el código ``pip install pyqt5-tools`` y me cuentas que tal te fue

**Comment by JanHellema** [comment]
Con el primer código que me diste me sale exactamente lo mismo, y con el segundo me sale esto:
![image](https://user-images.githubusercontent.com/80780539/111658731-61095d00-87eb-11eb-9086-b872af1e4fbb.png)

**Comment by dfloreaa** [comment]
Como dato, Python 3 no puede installar PyQt5 directamente con ``pip`` antes de su versión 3.5, antes que nada asegúrate de que tienes la versión 3.7.x (con x cualquier versión).

Quizás te funcione usando ``pip3`` en vez de ``pip``, podrías intentar con eso.

En caso contrario, te recomendaría descargarlo directamente desde [este sitio](https://build-system.fman.io/qt-designer-download), quizás es desde donde ya lo intentaste anteriormente, yo lo instalé desde ahí para cuando rendí el curso y no tuve problemas.

**Comment by JanHellema** [comment]
Tengo descargado python 3.7 en mis aplicaciones (tengo mac), pero me da esto:
![image](https://user-images.githubusercontent.com/80780539/111672930-33c3ab80-87f9-11eb-8763-d26b84cd84fe.png)

Intenté buscar en internet como desinstalar el 2.7 pero no pasa nada, no sé como hacerlo

**Comment by dfloreaa** [comment]
Eso significa que no desinstalaste las versiones que tenías de python antes de intstalar la 3.7, te recomiendo primero desinstalar todas las versiones de python que tengas **(todas)** y luego instalar la 3.7, luego checkear en la terminal que versión dice que tienes.

Ojala te sirva, cuéntame como te va! ☺

**Comment by JanHellema** [comment]
Lo logré hacer! muchas gracias!!

**Comment by dfloreaa** [comment]
Te sale solamente la 2.7.16 o tambien la 3.7.9?

![image](https://user-images.githubusercontent.com/62019645/111687621-3af2b580-8809-11eb-8204-b219c7e62b0b.png)

**Comment by JanHellema** [comment]
esto:
![image](https://user-images.githubusercontent.com/80780539/111688201-e439ab80-8809-11eb-87a2-ce6f7da3c7b1.png)

**Comment by dfloreaa** [comment]
Intentaste instalarlo con ``pip3`` verdad? Quizás tu comando ``pip`` conecta a ``pip2``

**Comment by JanHellema** [comment]
Hola! me aparece esto...
![image](https://user-images.githubusercontent.com/80780539/111782225-8b185900-8897-11eb-9515-60c2c524b5d2.png)

**Comment by dfloreaa** [comment]
Hola!

Te recomiendo como último recurso entonces descargar designer directo de la [pagina oficial](https://build-system.fman.io/qt-designer-download) de los creadores, el link es seguro y lo hemos compartido en el curso por años, lo siento que ha costado tanto solucionar el problema :(

Ojala te sirva! ☺️

**Comment by dfloreaa** [comment]
Hola @JanHellema , me preguntaba si todavía tienes tu problema? Puedo ayudarte con algo más? :))

**Comment by JanHellema** [comment]
Hola! Como ultima opcion lo descargue de la web, espero que despues me sirva! Muchas gracias por la ayuda!!

**Comment by dfloreaa** [comment]
Ningun problema, ojalá así sea, un saludo!
