### ISSUE TITLE
Instalación de python 3.5.x 

### ISSUE THREAD

**Issue by acrojas2** [IIC2233/Syllabus#7]
Instalé python desde la página que sale en la wiki (para Mac), pero antes tenía una versión más antigua ( Python 2.7.10) ¿Cómo quito la versión más antigua?¿Cómo hago que pycharm considere la nueva versión que instalé?

**Comment by andresfdezc** [comment]
Primero, no te recomiendo desinstalar Python 2.7, pues sigue siendo usado por muchos programas y es más o menos independiente de Python 3.5.

Segundo, puedes elegir la versión de Python que quieras usar en PyCharm por defecto en Preferencias:

![screen shot 2017-03-06 at 6 15 41 pm](https://cloud.githubusercontent.com/assets/11430184/23636060/015986c2-0299-11e7-8b23-6ce23f69037f.png)

**Comment by Dunkan1** [comment]
yo reinstale pycharm Edu y ahi el mismo programa me pregunto si descargaba la version 3.5 o la 2.algo
