### ISSUE TITLE
Error: Problema con PyQt6

### ISSUE THREAD

**Issue by maromero-21** [IIC2233/Syllabus#7]
Hola! En mi PC se pudo instalar correctamente tanto Python como Git como Jupyter como Requests, sin embargo al momento de instalar PyQt6 me sale el siguiente error:
Según tengo entendido el WARNING no es problema, pero si el mensaje posterior.
Muchas gracias por su tiempo y espero su respuesta!
![image](https://github.com/IIC2233/Syllabus/assets/89163594/c9275c2c-54cc-44c7-af13-23fe83977e24)

**Comment by Hernan4444** [comment]
Hola @maromero-21 

Estuve investigando este problema y al parecer la solución es instalar libGL. Para esto, intenta hacer 

```cmd
sudo apt install libgl1-mesa-glx
```

Luego, hacer `sudo python3.10 -m pip uninstall PyQt6` para desinstalar pyqt6, y luego volver a instalarlo.

Avisanos cómo te va con eso.😄
Saludosヾ(＾-＾)ノ

**Comment by dvillas28** [comment]
Hola, tuve un error  _muy similar_  tratando de importar los mismos modulos, la unica diferencia es que en mi caso, es la libreria **libEGL** la que no tenia instalada:

![duda](https://github.com/IIC2233/Syllabus/assets/128737225/7bde3cbb-87c6-4205-858c-47d915d7ae8f)

Logré resolverla usando los comandos de esta [pagina](https://bugs.launchpad.net/calibre/+bug/2000821), específicamente el comentario 2. Luego desinstale-instale PyQt6 como indicó @Hernan4444, y ahora parece funcionar correctamente.

Lo dejo aquí por si alguien tiene problemas con esa librería en especifico (No estoy seguro si deberia dejar mi comentario como una issue aparte? ya que no es _exactamente_ el mismo problema)

Saludos!

**Comment by Hernan4444** [comment]
Hola @dvillas28 

Muchas gracias por comentarlo. Está bien hacerlo aquí porque es un error muy similar. Solo para confirmar, en tu caso hiciste?

```cmd
sudo apt install  libegl1 libxkbcommon-x11-0 libopengl0
```

Quedo atento,
Saludosヾ(＾-＾)ノ

**Comment by dvillas28** [comment]
sip! esas 3 librerias de una

Saludos!

**Comment by maromero-21** [comment]
Hola profesor! Aparentemente no hay problemas con PyQt6. De igual forma ¿me podría responder con alguna línea de código para probar si está correctamente instalado?

Muchas gracias por la ayuda!

**Comment by maromero-21** [comment]
Seguí las instrucciones indicadas y ahora estoy con este error:
![image](https://github.com/IIC2233/Syllabus/assets/89163594/ae56ede6-fcb1-4317-b078-afd9ef22eea6)
En el siguiente [enlace](https://askubuntu.com/questions/1060903/importerror-libgthread-2-0-so-0-cannot-open-shared-object-file-no-such-file-o#:~:text=Try%20this%3A%20sudo%20apt-get%20install%20libglib2.0-0%20Then%2C%20run,computer%2C%20but%20the%20tool%20I%27m%20using%20uses%2032-bit.) se recomienda usar las siguientes líneas de código: 
![image](https://github.com/IIC2233/Syllabus/assets/89163594/a8a32861-09a2-44a7-a6cc-33c4d8bbdc91)
Me gustaría confirmar si es que están en el formato adecuado.

**Comment by joseinfantec** [comment]
Hola, descargué python y git pero tengo problemas con pyqt6. Me aparece el siguiente error
![error pyqt](https://github.com/IIC2233/Syllabus/assets/141949565/8b41ad3a-3f34-4a72-b59a-a2ac7d33889a)

**Comment by Hernan4444** [comment]
Hola @joseinfantec 

Puedes intentar primero escribir 

```cmd
python3 -m pip install --upgrade pip
```

Y luego volver a escribir el comando de pyqt6

En caso que te salga error, porfa manda todo el texto (si no cabe en una foto, puede ser más de una o puedes copiar el texto  en la issue) para poder ver todo el error y tener más pistas de qué puede estar pasando.

Estamos atentos,

**Comment by isidoragutierrez** [comment]
Hola! Tengo un problema parecido instalando PyQt6 en mi mac.
Intenté primero con el comando `python3 -m pip install pyqt6` pero no parece funcionar, por lo que intenté con `brew install pyqt6 --with-python3` y me sale el siguiente error:
<img width="580" alt="Captura de pantalla 2023-08-16 a la(s) 17 19 41" src="https://github.com/IIC2233/Syllabus/assets/111446584/704dd986-f621-48c9-a707-0744402a3ad0">
He intentado de solucionarlo pero no lo logro. ¿Algún tip? Todas las instalaciones anteriores no me presentaron ningún problema.

**Comment by Hernan4444** [comment]
Hola @isidoragutierrez 

Puedes mostrar qué aparece en consola cuando haces `python3 -m pip install pyqt6`

Quedamos atentos,

**Comment by maromero-21** [comment]
Hola @Hernan4444! 
Lamento la demora con mi respuesta, ayer finalmente instalé la última librería!
Hice un archivo de prueba con la línea de código disponible en la wiki:
![image](https://github.com/IIC2233/Syllabus/assets/89163594/aa0e4597-11c7-47dd-b166-9db9c3885397)

Luego abrí la terminal y ejecuté este archivo y no me salió ningún error, por lo que en teoría no debo tener más problemas :D

![image](https://github.com/IIC2233/Syllabus/assets/89163594/e4f95bbf-558d-4577-bfea-cc07c0f5fd3c)

Muchas gracias por las respuestas!

**Comment by Hernan4444** [comment]
Hola,

@isidoragutierrez puedes probar con `brew install pyqt6` (sin el `--with-python3`) y vér como te funciona. Quedamos atentos,

@maromero-21 Si, funciona todo bien, ahora solo debes acordarte de siempre (1) usar WSL, (2) usar CD para moverte en tu terminal y (3) cada vez que nosotros digamos "escriban python3" tu debes hacer "python3.10".

Saludos!

**Comment by isidoragutierrez** [comment]
Al ejecutar lo que usted me dice @Hernan4444 me aparece lo siguiente:

<img width="662" alt="Captura de pantalla 2023-08-22 a la(s) 15 10 36" src="https://github.com/IIC2233/Syllabus/assets/111446584/22c0bd6b-9e6a-46d0-90a7-a49a89346989">

**Comment by Hernan4444** [comment]
Hola @isidoragutierrez 

Veamos este caso el jueves durante el fin del segundo módulo o bien después de clases. Que creo que hay que intentar algunos comandos y por ejemplo, intentar reinstalar python, pero prefiero que primero puedas empezar a hacer la actividad y luego dejar esto solucionado.

Luego, subiré por aquí cuál era la solución al problema.

Saludos!

**Comment by isidoragutierrez** [comment]
@Hernan4444 perfecto, muchas gracias! El jueves lo vemos entonces.

**Comment by isidoragutierrez** [comment]
Hola! Ya resolví esto.

Para poder instalar Pyqt6 tuve que actualizar la versión del ios que tenía en mi Mac.
Al parecer solo funciona desde versiones macOs Big Sur en adelante.
Luego de actualizar el software seguí los pasos especificados en la Wiki del curso y todo me funcionó correctamente.

Muchas gracias!!
