### ISSUE TITLE
Compilado issues T00

### ISSUE THREAD

**Issue by lily416** [IIC2233/syllabus#7]
En la siguiente _issue_ encontrarás todas las _issues_ sobre la Tarea 0 que se han realizado hasta el momento, estas están divididas según diferentes temas. 
Antes de hacer una nueva _issue_, revisa si tu duda ya fue realizada, así evitamos las _issues_ duplicadas. :smile:

### Librerías permitidas, no permitidas y malas prácticas ✔️❌ 
1. Librerías permitidas/no permitidas en la T00: #4 

### Manejo de _posts_ 
1. Fecha _prograposts_: #12 
1. Eliminar _prograpost_: #17 
1. Visibilidad de _post_ propios en el Muro: #28
1. _Prograpost_ y todo tipo de caracteres: #36
1. Formato de fecha de los posts: #47
1. Flujo errores creación de _prograpost_: #48
1. Visualizar _prograposts_: #50 
1. Cantidad de publicación de _post_ al día: #55
1. Orden de los _posts_ T00: #57
1. ¿Espacios son considerados entre los 140 caracteres de un _post_?: #68
1. Mismo _post_ en un día: #70
1. Contenido _prograposts_: #72
1. Problema con el método `sort` e instancias de `datetime`: #76
1. Ordenar de forma ascendente y descendiente: #89
1. Formato fecha _posts_: #114
1. Duda con verificación de largo del _prograpost_: #128
1. Duda enunciado, eliminar prograposts #139
1. Duda como se guardan los prograposts: #151

### Seguidores 
1. Revisar quienes siguen por parte del usuario: #26
1. Seguir usuario inválido: #48
1. Alternativa al procedimiento para dejar de seguir a un usuario: #58
1. Seguir a alguien que ya sigue: #105

### Menús / Flujo programa
1. Transición entre menús T00: #13
1. Agregar opciones extras a los menús: #67
1. Menú de _prograposts_: Volver al Menú de inicio: #90
1. Fin del programa: #94
1. Organización Menús: #103
1. Menú de Seguidores: _loop_ para pedir _input_: #115
1. Dudas menú a prueba de errores: #150 

### Usuarios
1. Registro de usuario con espacios: #35
1. Considerar mayúsculas al registrar usuarios: #66
1. Nombre de usuario: Prohibir un carácter: #79
1. Tildes como carácteres alfanuméricos: #85
1. Usuarios ya creados, pero sin clave: #118 

### Archivos
1. En la base de usuarios hay un _user_ que no es alfanumérico: #6 
1. Directorio Archivos Entregados: #8
1. Duda archivo `posts.csv`: #9
1. Formato de la fecha en archivos T00: #14 
1. Método para abrir archivos `.csv`: #15
1. Error al abrir archivo `post.csv`: `UnicodeDecodeError`: #16
1. En `seguidores.csv` hay uno con una coma de más: #18
1. ¿Cómo trabajar con los archivos `.csv`? #30
1. Número de caracteres usuarios T00: #32
1. `"\n"` en cada linea de los archivos: #40
1. Actualización de archivos: #41
1. Usuarios nuevos en `seguidores.csv`: #59
1. Error `seguidores.csv`: #61
1. Comillas agregadas al leer archivo `.csv`: #65
1. Actualizar Archivos: #71
1. `PermissionError` al intentar escribir en `'usuario.csv'`: #73
1. Orden _posts_ en archivo : #82 
1. Comportamiento inesperado `open()`: #87
1. Archivo en blanco después de editarlo: #102
1. Archivo se escribe muy lento y no siempre se actualiza: #104 
1. Problema al leer archivos: `open(file, "a")`: #107
1. `PermissionError: [Errno 13] Permission denied: 'usuarios.csv'` al escribir en el, no para leerlo (archivo cerrado) #113
1. Se pueden abrir archivos con: `open(file, "a")`?: #124 
1. Seguir escribiendo en una línea existente: #137

### Git
1. Comando `git status` no reconoce cambios (Windows 10): #21
1. Eliminar archivos en `git`: #25
1. Eliminar archivo de github #135
1. `Permission to IIC2233/syllabus.git denied to alvaritions`: #27 
1. Problema para hacer `git pull`: #56
1. git no permite subir un archivo: #136 

### Buenas prácticas
1. #### PEP8
   1. Caracteres por línea (100): #20
   1. Indentación y PEP8: #29
   1. El limite de caracteres por linea es 100 o 79?: #86
   1. `docstring`: #100
   1. Máximo 400 lineas de codigo: #138
2. #### Modularización 
   1. ¿Qué es modularización? #146 

1. #### Código externo
   1. Citar códigos de 3ros: #45

### Descuentos
1. #### Path relativos y absolutos
   1. Problema _path_ relativo: #22 
   1. Problema con el `os.path`: #24
   1. _path_ relativo y absoluto: #170 
1. #### Malas prácticas
   1. Recursión en `import`: #108
   1. Importar variables de otro módulo: #110

### `.gitignore`
1. `git add .gitignore` #34
1. Carpeta `.gitignore` #38
1. Sacar archivos que no son de la tarea: #121
1. .gitignore no funciona con archivos ya subidos: #167

### `README`
1. Líneas de definiciones en `README.md`: #106
2. Fecha de entrega `README`: #197 

### Distribución de puntajes
1. Formato Fecha: #63
1. Pauta Tarea: #177

### Otras
1. Avance T00: #5
1. Archivos `.csv` en repositorio personal: #19
1. Uso de Clases: #44
1. `NameError: name 'utf8' is not defined`: #62
1. Uso de `[1:]` y `[:-1]` en listas: #84
1. Error al importar funciones de otros archivos py: #130
1. Error al importar módulos: #131

**Comment by Jairuru** [comment]
Hola!
Falta cambiar el usuario no alfanumérico en las otras bases.
Saludos n.n

**Comment by lily416** [comment]
@Jairuru ya se encuentran actualizados, perdón por la demora 🙇‍♀

**Comment by anamarn** [comment]
Hola!
Tengo una duda especifica, sobre el modo "w" y "r" al leer y escribir archivos.  Quiero modificar una linea especifica, me gustaría saber si me pueden dar algún consejo para operar.

En primer lugar itero sobre uno de los archivos en modo "r" y encuentro la linea
pero después quiero modificar esa linea (pd: también tengo abierto el doc en modo "w" en otra variable)...
tengo iterar sobre el doc en modo "w" para modificarla, o puedo hacerlo directamente ?como lo hago?

**Comment by lily416** [comment]
@anamarn el compilado de _issues_ no es para hacer preguntas 😞 
Haz una _issue_ indicando tu problema y un ayudante te responderá cuando pueda.
