### ISSUE TITLE
Uso de python 3.8

### ISSUE THREAD

**Issue by totoiii** [IIC2233/syllabus#7]
En las instrucciones del curso en el software mínimo debemos tener python 3.7.x . 
Con esto se refieren a que debemos tener esta versión como mínimo ( es decir que podemos tener por ejemplo la 3.8 ) o que debemos tener esta versión obligatoriamente

**Comment by retamalcito** [comment]
¡Hola @totoiii!

Con lo que dice en la _wiki_ del curso, nos referimos a que puedes utilizar cualquier versión de **Python 3.7**, es decir, **no** puedes utilizar Python 3.8.
Esto se debe a que la versión 3.8 es aún muy nueva, por lo que puede presentar problemas de estabilidad en algunos contextos. De todas formas, todo código que los ayudantes te revisen será ejecutado en Python 3.7, por lo que debes desarrollar tus programas en esta versión.

¡Saludos :wave:!

**Comment by Drpinto1** [comment]
¡Hola!

Complementando un poco la respuesta de @retamalcito, las diferencias entre python 3.7 y 3.8 son pequeñas, por lo que si haces tus programas en python 3.8, probablemente no tengas grandes problemas, así que si es muy complicado hacer el cambio en tu sistema operativo, podrías eventualmente usar python 3.8.

Dicho esto, **te recomendamos cambiarte a python 3.7**, pues podrías toparte con un caso borde en que en tu computador funcione perfecto tu código (3.8), pero al no estar en la misma versión de python, no le funcione bien a tu corrector/a (3.7) y eso te perjudique.

Si bien puedes solicitar una recorrección si es que esto te llega a pasar, la manera más simple de solucionar esto era reuniéndote con algún ayudante, pero (por razones obvias) este semestre será más complejo resolver un caso como este.

Si tienes dudas de cómo hacer el cambio de versión, te recomiendo googlear algún tutorial (para tu sistema operativo) y si algo no te funciona, puedes abrir una issue contándonos tu duda, tu(s) versión(es) de python, el tutorial que usaste y tu sistema operativo para que un ayudante de pueda asistir más personalmente :D

¡Saludos!
