### ISSUE TITLE
Type hinting en nameTuple?

### ISSUE THREAD

**Issue by naquiroz** [IIC2233/Syllabus#7]
Sé que en python es posible usar _type hinting_ de la siguiente manera:

```python
class Auto:
    def __init__(self, gasolina: int =0, marca: str = ""):
        self.gas: int = gasolina
        self.marca: str = marca
```

Si quisiera hacer eso en una namedTuple, como podria poner el type hinting ?

**Comment by contranton** [comment]
Debes importar NamedTuple del módulo _typing_. El módulo además tiene definiciones como _Union_ (Union[int, str] por ejemplo es que tanto int como str son tipos válidos), _Generator_, en caso de que crees generadores con yield en vez de return, etc.

**Comment by naquiroz** [comment]
Ah, si ubicaba el módulo _typing_ pero no sabía que habia un NamedTuple. Gracias!
