### ISSUE TITLE
Duda respecto a la cantidad de legos en tablero

### ISSUE THREAD

**Issue by galanfd** [IIC2233/syllabus#7]
Hola, en el enunciado de la tarea 00 dice que para calcular la cantidad de legos que habrán en el tablero se ocupa la fórmula N x M x PROB_LEGO, mi duda es qué pasa si es que el resultado a esta operación da un número decimal??? Ocupamos la parte entera del valor obtenido o redondeamos el número??
De antemano gracias!

**Comment by jeschuwirth** [comment]
Debes utilizar la función techo para calcular el L, es decir redondear siempre hacia arriba.
![image](https://user-images.githubusercontent.com/37160256/62829371-d3ef3280-bbc9-11e9-8941-fd70d507a396.png)

Recuerda leer los pies de página del enunciado

Suerte en la tarea! :D

**Comment by galanfd** [comment]
Ah perfecto, se me fue ese pequeño detalle.
Muchísimas gracias
