### ISSUE TITLE
[Windows] pip, instalación de librerías 

### ISSUE THREAD

**Issue by ploello** [IIC2233/Syllabus#7]
al momento de instalar las librerías desde cmd en windows, me presenta el error " "pip" no se reconoce como un comando interno o externo programa o archivo por lotes ejecutable ", ¿que puedo hacer en este caso para solucionarlo?

**Comment by jtagle2** [comment]
Primero, voy a asumir que ya instalaste Git.
Ahora, el problema es que ~somos windows~ muchas veces en windows cuando se instalan nuevos programas, en la instalación no se fija la variable de entorno asociada a la ejecución de dicho programa. En otras palabras, cuando pones `git` en la ventana de comandos, el sistema va a buscar la aplicación asociada a dicho comando. Como no quedó seteada la variable de entorno de dicho comando, te dice que "pip" no se reconoce como un comando interno o externo programa o archivo por lotes ejecutable ". Asique, hay que enseñarle al computador como se hace.

Para esto, se debe hacer lo siguiente.
1.- Ir a panel de control
2.- Ir a la sección "Sistema"
3.- Apretar donde dice "Configuración Avanzada del Sistema"
4.- En la ventana que aparece, apretar el botón que dice "Variables de Entorno"
5.- En las variables de usuario o del sistema (cualquiera de las 2, supongo que solo programarás en un usuario de tu pc y no en varios) debes encontrar una variable que se llama PATH o Path.
6.1 (para git) Debes agregar a la variable path, el path _C:\Program Files (x86)\Git\cmd_ (Si instalaste git en otra parte, es <Path a carpeta de git>\cmd.
6.2 (para pip) Debes agregar a la variable path, el path _C:\Python352\Scripts\_ (O bien, <Path a carpeta de Python>\Scripts).

Avisa como te va con eso.
Saludos!

**Comment by ploello** [comment]
pip.exe  no se encontraba en esa dirección, sin embargo logre encontrarlo y lo agregue, lo que con el primer y tercer código funciono perfecto `pip install --upgrade simpy ` y `pip install --upgrade matplotlib` respectivamente,

 sin embargo al momento de aplicar el segundo `pip install -i https://pypi.binstar.org/carlkl/simple numpy`, me da un error que no logro resolver, diciendo que el certificado no concuerda con el nombre del host y otros más.

copio el resultado para su evaluación (lamento la extensión).





`Collecting numpy`

  `Certificate did not match expected hostname: pypi.binstar.org. Certificate: {'subject': ((('organizationalUnitName', 'Domain Control Validated'),), (('organizationalUnitName', 'PositiveSSL Multi-Domain'),), (('commonName', 'anaconda.com'),)), 'issuer': ((('countryName', 'GB'),), (('stateOrProvinceName', 'Greater Manchester'),), (('localityName', 'Salford'),), (('organizationName', 'COMODO CA Limited'),), (('commonName', 'COMODO RSA Domain Validation Secure Server CA'),)), 'version': 3, 'serialNumber': '67DECDFB7CCA3B7951249D6BEB13DE22', 'notBefore': 'Apr 28 00:00:00 2017 GMT', 'notAfter': 'Sep 29 23:59:59 2017 GMT', 'subjectAltName': (('DNS', 'anaconda.com'), ('DNS', 'anacondacloud.com'), ('DNS', 'anacondacloud.org'), ('DNS', 'binstar.org'), ('DNS', 'wakari.io')), 'OCSP': ('http://ocsp.comodoca.com',), 'caIssuers': ('http://crt.comodoca.com/COMODORSADomainValidationSecureServerCA.crt',), 'crlDistributionPoints': ('http://crl.comodoca.com/COMODORSADomainValidationSecureServerCA.crl',)}`

  `Could not fetch URL https://pypi.binstar.org/carlkl/simple/numpy/: There was a problem confirming the ssl certificate: hostname 'pypi.binstar.org' doesn't match either of 'anaconda.com', 'anacondacloud.com', 'anacondacloud.org', 'binstar.org', 'wakari.io' - skipping
`
  `Could not find a version that satisfies the requirement numpy (from versions: )`

`No matching distribution found for numpy`


Cabe mencionar que al tratar de ingresar a la pagina por medio del buscador, este marca la pagina como no segura

**Comment by jtagle2** [comment]
Intenta poner simplemente `pip install numpy`

**Comment by ploello** [comment]
me funciono, muchas gracias
