### ISSUE TITLE
Mismo post en un día

### ISSUE THREAD

**Issue by Aloncarrasco** [IIC2233/syllabus#70]
Puede el mismo usuario publicar el mismo post en el mismo día?
 por ejemplo el 2020/5/6 felipe público "hola" en la mañana y público "hola" en la tarde.
sería irreconisible cual post es cual.

**Comment by KnowYourselves** [comment]
Hola @Aloncarrasco!

No hay problema con que el usuario publique lo mismo en el mismo día, ya que lo único que les pedimos es ordenar los pots por fecha. 

Éxito!

**Comment by IgnacioPorte** [comment]
Hola, o sea que si dos posts tienen la misma fecha no importa el orden entre ellos ?

**Comment by KnowYourselves** [comment]
Hola @IgnacioPorte!

Exacto. Ya que la fecha que te damos no tiene horas, la máxima precisión son los días. Como no hay forma de saber cual fue antes entre dos posts del mismo día, da lo mismo el orden que estos tengan entre si.

Éxito!

**Comment by IgnacioPorte** [comment]
@KnowYourselves Ok, gracias.
