### ISSUE TITLE
¿Error en test_tablero_desglose.py?

### ISSUE THREAD

**Issue by martina-abello** [IIC2233/Syllabus#70]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Revisando el archivo, me dí cuenta de que para todos los casos utiliza _tablero.desglose_, no _tablero.desglose()_, siendo que desglose es una función, no un atributo de la clase. Como resultado, al correr los tests aparece que en todos los casos _respuesta_ es _<bound method Tablero.desglose of <tablero.Tablero object at 0x00000222290C3EB0>>_.

Sé que esta es la causa del error, porque al añadir los paréntesis sí me funcionan los tests.

(Esto ocurre también con test_tablero_transformado, y me parece que en otros tests también, pero no he revisado a fondo.)

Me entra la duda de si es en verdad un error en el archivo, o es que se supone que cree un atributo de Tablero (self.tablero_transformado, por ejemplo) que sea el return de la función tablero_transformado().

**Comment by mtaguero** [comment]
Hola @martina-abello :)

La situación que estás experimentando no es un problema de test. Es posible que esto ocurra debido a que no estás trabajando con **properties**.

Espero que esto haya aclarado tu duda. 
¡Éxito! 🎈

**Comment by martina-abello** [comment]
Ahhh vale gracias.
