### ISSUE TITLE
Error al mostrar tablero

### ISSUE THREAD

**Issue by DomingoOrtuzar** [IIC2233/Syllabus#70]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/21)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/20)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Cuando imprimo el tablero, no se visualiza bien en la consola. Intenté con y sin utf-8, y de ninguna forma me imprime bien. **¿Cuál podrá ser el problema?**

Adjunto imagen:

![Captura de pantalla (19)](https://user-images.githubusercontent.com/127885032/227571415-72e6cf9a-bbd3-4e08-a9a3-d709b5184128.png)

**Comment by Arielmanriquez** [comment]
Revisa bien si estas entregándole a la función las variables en el formato correcto, en el caso de esta función necesitas una lista de listas.
Saludos, quedo atento a cualquier duda que siga.

**Comment by DomingoOrtuzar** [comment]
> Revisa bien si estas entregándole a la función las variables en el formato correcto, en el caso de esta función necesitas una lista de listas. Saludos, quedo atento a cualquier duda que siga.

Muchas gracias, lo pude solucionar!
