### ISSUE TITLE
Salir de Grupos a travez de comando especial

### ISSUE THREAD

**Issue by Ignacioislae** [IIC2233/syllabus#70]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

En el enunciado dice: "Además, deberás tener la opción de abandonarun grupo en cualquier momento mediante un comando especial. "¿Esto se refiere a usar un commando estilo Ctrl + 1 en la consola, o se refiere que al ingresar a las opciones del grupo haya una opcion para salir de este? ¿Y a que se refiere con en cualquier momento?

**Comment by Juampisaez** [comment]
Hola @Ignacioislae 
Cuando habla de comando especial, se refiere a las frases guardadas en el archivo de `parametros.py`. Por otro lado, cuando dice "en cualquier momento" se refiere estando dentro del chat del grupo (para salir o abandonar, se usan los comandos o frases que te explique antes).

Espero quede mas claro :)

**Comment by Ignacioislae** [comment]
Quede mas claro. Gracias!
