### ISSUE TITLE
Descuentos funcionalidad

### ISSUE THREAD

**Issue by bwertheim1** [IIC2233/Syllabus#70]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, no he logrado solucionar un problema con mi codigo cuando genero un tablero rectangular pero si funciona bien cuando lo tengo cuadrado. Queria saber (si es que se puede) de cuanto seria mas o menos el descuento asociado a esa falta de funcionalidad.

muchas gracias

**Comment by drcid98** [comment]
Hola! En la distribución de puntajes aparecen todos los puntajes asociados a cada funcionalidad y objetivo. En general, si cumples todo lo de un ítem se asigna puntaje completo, si tienes más de 50% con algunas fallas, tienes mitad de puntaje y con menos de 50% logrado en el ítem se asigna 0.

Saludos!
