### ISSUE TITLE
Comentarios en publicaciones propias

### ISSUE THREAD

**Issue by ElTioAndresCabezas** [IIC2233/Syllabus#70]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Saludos!
En la tarea, con respecto a colocar comentarios en publicaciones, un usuario debiese tener permitido escribir comentarios en sus propias publicaciones? o esto se debe restringir a que solamente otras personas comenten en esa publicacion?

**Comment by Juampisaez** [comment]
Hola @ElTioAndresCabezas!
No esta restringido, un usuario puede hacer comentarios a sus propias publicaciones, fijate que hay casos en los archivos donde esto ocurre.

Quedo atento si queda alguna duda
Saludos,

**Comment by ElTioAndresCabezas** [comment]
Muchas gracias por tu respuesta!
