### ISSUE TITLE
Opción de retractarse

### ISSUE THREAD

**Issue by jalliende** [IIC2233/syllabus#70]
Con la opción de retractarse del usuario, se refiere a que la acción tiene que poder ser hecha y después deshacer la acción o por ejemplo se podria preguntar por un input y luego de que lo introdusca preguntarle si esta seguro de que ese es el input que queria meter?

**Comment by Arcoirisky** [comment]
Hola, si te refieres a la interacción en el menú descrita en el enunciado:

![image](https://user-images.githubusercontent.com/26121402/55167271-66c58e00-514f-11e9-8099-804eaf491bfb.png)

Se refiere a que si elijo una opción del menú y en medio de esta me arrepiento, necesitas una forma de que pueda regresar sin la necesidad de realizar o terminar de escribir la acción. Pero, si en realidad solo me equivoqué al ingresar inputs, debe volver a preguntar.

El cómo vas a controlarlo queda a tu criterio pero debe cumplir con lo que dice el enunciado.
