### ISSUE TITLE
Problema con el path de la función cambiar_planos

### ISSUE THREAD

**Issue by maidazuniga** [IIC2233/Syllabus#70]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/20)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/19)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Estoy teniendo un problema al utilizar os.join.path( ). Al momento de unir la ruta, se está haciendo con doble backslash ( \\\ ) por lo que me arroja el error "No such file or directory: ". Nunca se abre el archivo ya que no existe ningún directorio que utilice \\\ .

Por ejemplo:
En vez de unir la ruta como: carpeta\archivo, lo hace como carpeta\\\archivo

**Qué podría estar generando este error?**

**Comment by Pablo-Gonzalez-Calderon** [comment]
Hola, @maidazuniga ✨

Para poder ayudarte mejor, te voy a pedir que hagas `git push` a tu tarea, para así poder ver tu código en tu repositorio y guiarte desde ahí.

¡Avísame cuando lo hagas!
Quedo atento 🍀🫡

**Comment by maidazuniga** [comment]
Listo!

**Comment by Pablo-Gonzalez-Calderon** [comment]
Hola!

Luego de revisar varias veces, finalmente me di cuenta de que **no hay ningún error en tu código.** Lo que pasa es que estás intentando abrir archivos que no existen. Por ejemplo, no se puede abrir `ciudad_T.dcc` porque no existe ese archivo (se llama `ciudad_T.txt`):
![image](https://github.com/IIC2233/Syllabus/assets/30756770/171da469-9e8d-437f-8338-5033e598cca2)
![image](https://github.com/IIC2233/Syllabus/assets/30756770/a184fd95-9291-4cec-aa13-889aa77d048d)

Así que tranquila, no hay problema en el código. ¿Entonces qué debes hacer? El enunciado, en la página 10, especifica aquello.

Espero haber podido responder tu duda 🍀🫡

**Comment by maidazuniga** [comment]
Perfecto, muchas gracias!
Ahí lo solucioné 😄
