### ISSUE TITLE
Ubicación del .gitignore y guía de cómo realizarlo

### ISSUE THREAD

**Issue by DonJavi-538** [IIC2233/syllabus#70]
Hola! intentando realizar el .gitignore recorde que existia una guia sobre cómo redactarlo pero olvidé donde se encuentra :( . Además me gustaría saber donde se debe ubicar dicho archivo para que funcione correctamente.

De antemano muchas gracias!

**Comment by jeschuwirth** [comment]
Hola!

Para crear el .gitignore tienes varias opciones que dependen según tu sistema operativo, primero que nada te recomiendo encender la opción de ver archivos ocultos, eso se hace de la siguiente manera:

**Windows** (seleccionas la siguiente opción en la pestaña vista de la carpeta):
![image](https://user-images.githubusercontent.com/37160256/63203993-4005e680-c061-11e9-9c3e-bd3b79feb458.png)

**MAC** Sigue el siguiente tutorial:
https://es.ccm.net/faq/26647-como-ver-archivos-ocultos-en-mac

**Linux**: Basta con apretar ctrl+h en el menú de una carpeta.


Luego de eso deberías ser capaz de crear archivos ocultos (que comienzan con ".") sin problemas

En cuanto a donde se ubica, tiene que estar en tu repositorio dentro de la carpeta T00 (para se más exactos tienes que estar en la misma carpeta o una superior a los archivos que quieres ignorar)

Suerte en la tarea!

**Comment by DonJavi-538** [comment]
Muchas gracias!

**Comment by etoteiza** [comment]
Hola! 
Tengo una duda. Supongamos que en una carpeta ( 'carpeta') tengo mis archivos, incluyendo el '.gitignore'. Dentro de 'carpeta' tengo 'subcarpeta', y quiero ignorar archivos dentro de 'subcarpeta' el '.gitignore' que está en 'carpeta' servirá, o debo crear otro '.gitignore' dentro de 'subcarpeta'.

Muchas gracias de antemano, espero que se haya entendido
