### ISSUE TITLE
Error al hacer add/commit/push

### ISSUE THREAD

**Issue by ofvera** [IIC2233/Syllabus#700]
Intento hacer el add y push a heroku pero me lo toma como si fuese en el repositorio de git
con el siguiente error:

fatal: 'heroku' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by felipesilvadv** [comment]
Tengo el mismo problema puedes revisar la issue #684 a mi no me resulta eso pq no encuentro la carpeta q dicen q hay q acceder, pero quiza te funciona  a ti

**Comment by rpalmaotero** [comment]
Probaste ejecutando `heroku git:remote -a app-name`?

**Comment by felipesilvadv** [comment]
@rpalmaotero ya lo resolvi muchas gracias, de hecho creo q fue haciendo eso que dices

**Comment by TomasSalvadores** [comment]
Hola, yo tuve el mismo problema, pero luego de hacer el `heroku git:remote -a app-name`, me lanza otro error:

remote: -----> Installing requirements with pip
remote:        /app/tmp/buildpacks/779a8bbfbbe7e1b715476c0b23fc63a2103b3e4131eda558669aba8fb5e6e05682419376144189b29beb5dee6d7626b4d3385edb0954bffea6c67d8cf622fd51/bin/steps/pip-install: line 7: /app/.heroku/python/bin/pip: No such file or directory
remote:  !     Push rejected, failed to compile Python app.
remote: 
remote:  !     Push failed
remote: Verifying deploy....
remote: 
remote: !	Push rejected to lenagitassistant.
remote: 
To https://git.heroku.com/lenagitassistant.git
 ! [remote rejected] 8b945f3eb0f1fb1f0aaf60f6206573bf8d2cb768 -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/lenagitassistant.git'

Aiuda :(

**Comment by Hernan4444** [comment]
@TomasSalvadores luego de hacer `heroku git:remote -a app-name` hiciste los add, commit? porque cuando cambias de app, se olviden los add y por lo tanto para heroku no hay existencia de un archivo requirements o cualquier otro archivo.

Saludos!
