### ISSUE TITLE
Problemas con tamaños de imagenes

### ISSUE THREAD

**Issue by Aloncarrasco** [IIC2233/syllabus#700]
Hola he intentado achicar el logo porque es muy grande, he probado con muchas formas pero simplemente no se achica (al final lo pongo en un layout, cuando no esta en un layout si se achica), probé con scaled, pero la deforma demaciado y la documentación aparece esto:
QPixmap::QPixmap(int width, int height)
pero no se como usarlo, lo intentado poner de varias formas y la dice que la sintaxis está mala, por favor ayuda, llevo demaciado tiempo en esto.

**Comment by kadroguett** [comment]
Hola @Aloncarrasco 
Te recomiendo revisar la documentación de la clase QPixmap:[https://doc.qt.io/qtforpython/PySide2/QtGui/QPixmap.html](url)
En donde puedes encontrar diferentes métodos para ajustar imágenes. Por otro lado, recuerda que mientras más pequeña haces la imagen más distorsionada se verá.

**Comment by Juampisaez** [comment]
No funciona el link, me lleva a esto
![image](https://user-images.githubusercontent.com/48323752/82242248-8a2b3980-990b-11ea-81f4-c61f5d1c78bc.png)

**Comment by aaossa** [comment]
@Juampisaez ya lo corregí, de todas formas la URL que se muestra es la que quieres, por lo que puedes copiarla y pegarla en tu navegador ✨

**Comment by FelipeLara00** [comment]
Tengo el mismo problema, esa pagina dice como editar imagenes fuera de los layout, pero el problema es que en los layout no toma los ajustes de tamaño que se hicieron a la imagen.

**Comment by kadroguett** [comment]
@FelipeLara00 estás editando el objeto QPixmap o el objeto QLabel? En el link existen funciones que te pueden ayudar a editar imágenes aún dentro del layout.

**Comment by FelipeLara00** [comment]
Logre hacer que se achicaran usando scaled y scaledtowidth, sin embargo con ambos se distorsiona mucho la imagen.

**Comment by kadroguett** [comment]
Prueba con valores más elevados, recuerda que mientras más pequeña haces la imagen más distorsionada se verá y eso es inevitable a, menos que la modifiques en un editor de imágenes.
![logo](https://user-images.githubusercontent.com/31357861/82264916-cffbf800-9933-11ea-8ee5-a5bba0897732.png)
(no es necesario que se vea perfecto el logo, si se ve así está bien)

**Comment by FelipeLara00** [comment]
Ahi me funciono, gracias!

**Comment by kadroguett** [comment]
De nada! Éxito en tu tarea 😺
