### ISSUE TITLE
Sobre la interfaz

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#700]
Hola, 
Los ejemplos de la interfaz de usuario, hasta qué punto son vinculantes? Es decir, para agregar notas, por ejemplo, puedo no tener ningún campo de texto y que sea todo con botones y cosas por el estilo?
Lo mismo para el resto de cosas.

Gracias.

**Comment by jfbahamondes** [comment]
Mientras cumpla con las funcionalidades pedidas no hay problema.

Saludos!

**Comment by Hernan4444** [comment]
Hola, acerca  de lo indicado de usar botones, como se te comentó, se puede, pero debes tener botones para todos los tipos de input. Para las notas pro ejemplo debe haber la opción numérica, opción co notas en ingles y opción en español. Te sugiero ver el excel con la distribución de puntaje para confirmar que se va a evaluar que se puede ingresar el input de las 3 formas posibles, y así con los demás inputs.
