### ISSUE TITLE
Duda existencial

### ISSUE THREAD

**Issue by Araos827** [IIC2233/syllabus#701]
for posicion, valor in zip(posiciones, valores):
            boton = QPushButton(valor, self)
            self.grilla.addWidget(boton, *posicion)
que significa ese asterisco antes de el argumento posicion, lo he visto en los notebooks pero no se por que debe ir ahi

**Comment by Nicobuzeta** [comment]
No soy ayudante, pero significa q estas unpacking los values de esa lista para que los pase como variables separadas al metodo. 
Por ejemplo:
`ls = ['var1', 'var2']`
`func(*ls)`
Es lo mismo que 
`func('var1', 'var2')`
[Aca puedes ver una explicacion mas profunda](https://www.geeksforgeeks.org/packing-and-unpacking-arguments-in-python/)

**Comment by Araos827** [comment]
Buenaaaa muchas thank you por tu answer  :)

**Comment by fdoflorenzano** [comment]
Hola,

Gracias por responer @Nicobuzeta. Quería agregar como recordatorio que la semana 1 de los contenidos del curso hablaban en extensión de este tema, en el [cuaderno de args y kwargs](https://github.com/IIC2233/contenidos/blob/master/semana-01/6-args-kwargs.ipynb).

Saludos.
