### ISSUE TITLE
UDP entre computadores?

### ISSUE THREAD

**Issue by naquiroz** [IIC2233/Syllabus#701]
Hola! En el material de _networking_, describen como hacer un servidor UDP y un cliente udp, sin embargo, el metodo que explican, sirve solo para establecer conexión entre un mismo computador. Como Puedo montar un servidor UDP disponible para todos los computadores en una misma red local? O mas aún, como puedo montar un servidor UDP disponible para todo el mundo?

**Comment by jecastro1** [comment]
Hola @naquiroz,

Debería ser suficiente con que en el cliente _setees_ adecuadamente la dirección a la que te quieres conectar en el código del **cliente**. Esto pues el _socket_ del lado del servidor está vinculado (_bind_) a cualquier dirección que pueda tener la máquina (mediante el _string_ vacío).

Por ejemplo, en mi casa tengo una red local interna. El computador desde el que escribo va a ser el cliente, y otro computador va a ser el servidor. Si ejecuto algún comando para ver la IP que tiene mi servidor dentro de mi red (`ipconfig` en Windows o `ifconfig` en Linux / macOS) me sale `192.168.1.39`.

Luego, en el código del cliente tengo que asegurarme que el host al que me conecte sea precisamente "192.168.1.39". En particular en el cliente UDP que se propone, es reemplazar la línea:

```python
server_name = socket.gethostname()
```
por:

```python
server_name = "192.168.1.39"
```

Eso, cualquier duda invitadísimo a seguir preguntando. Saludos

**Comment by naquiroz** [comment]
Me quedo clarísimo! Sin embargo, esto no resulta para conectarse a mi servidor si es que está en otra red o no? Estuve leyendo y parece que es necesario abrir un puerto o cosas asi (quizás esto se escapa un poco de lo que enseña el curso, pero tenía la curiosidad de cómo se hace dado que tengo que tengo un computador viejo en mi casa y pensaba ocuparlo como un servidor).

**Comment by jecastro1** [comment]
Efectivamente. En la mayoría de las situaciones la red de tu casa estará detrás de un _router_. El _router_ es el punto de entrada/salida de tu red local a internet. 

Este aparato normalmente rechaza conexiones entrantes a menos que lo configures para ello. La configuración incluye decir a qué computador de tu red local deben ir las _requests_ que se hacen a cierto puerto. 

Otra cosa que hay que tomar en cuenta es que la IP que es visible desde internet es distinta a la que puedes tener dentro de tu red local. Para conectarte a tu casa desde otra parte deberás averiguar la IP pública (se puede buscando "Public IP" en Google) y usar esa para conectarte.

Como nota final, para propósitos de este curso basta con que los programas funcionen dentro de la red local.

Saludos!

**Comment by ljrodriguez1** [comment]
Para ahondar en este tema, si quisiera usar un computador como server para subir una página web, esto se haría también con servers de phyton.
También como afectaría a mi internet si es que tengo un computador como server en mi casa
