### ISSUE TITLE
Duda eliminar/cambiar layout de la ventana, ejercicio propuesto 2.2

### ISSUE THREAD

**Issue by ignaciomansuy** [IIC2233/syllabus#701]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda
Al momento de mostrar el cronómetro quiero poder definir un nuevo _layout_ de la ventana (un `QVBoxLayout()` por ejemplo). El tema es que cuando inicializo la ventana, defino un `self.setLayout()` y luego cuando trato de volver hacer `self.setLayout()` python me tira el siguiente error: 
`QWidget::setLayout: Attempting to set QLayout "" on VentanaReloj "", which already has a layout` 

Busqué en la web, pero no encontré un método que permita eliminar/reemplazar/cambiar un _layout_ ya existente.

Salu2 y gracias de antemano!

**Comment by igbasly** [comment]
Hola @ignaciomansuy :v:

Efectivamente, los *widget* sólo permiten asignar un *layout*, por lo cual no hay algún comando que te permita cambiarlo o reemplazarlo directamente.
:bulb: Una buena opción es tener un _widget_ para cada layout e ir intercambiando estos _widgets_ en su lugar. Si utilizas un _QMainWindow_ tienes la opción de utilizar `.setCentralWidget` cuantas veces quieras, por otro lado siempre puedes jugar con los métodos `.hide()` y `.show()` de los _widgets_.

Espero que esto sea de ayuda y no dudes en preguntar cualquier cosa. Mucho éxito 🙌.
