### ISSUE TITLE
git subtree push --prefix Tareas/T07 heroku master, Cada vez se hace mas larga la espera

### ISSUE THREAD

**Issue by aSPCA** [IIC2233/Syllabus#702]
Me sucede que cada vez que realizo ese comando tengo que esperar aun mas para completarlo.
Al inicio partio en 1, luego aumentaba por cada vez que le aplicaba ese comando en 1, hasta que ahora tengo que esperar 60 segundos para realizar el comando.

Help

**Comment by MainScientist** [comment]
¿Qué es exactamente lo que imprime el comando?

**Comment by aSPCA** [comment]
![image](https://user-images.githubusercontent.com/26173407/27512261-57d65006-5911-11e7-89f9-8278da34d756.png)

**Comment by aSPCA** [comment]
cada vez aumenta en 1 el valor de la derecha del "/" en el ultimo codigo de la imagen

**Comment by Okhan97** [comment]
Me pasa igual!
