### ISSUE TITLE
T06 Enuciado notas

### ISSUE THREAD

**Issue by Bipavez** [IIC2233/Syllabus#702]
Hola!
En el enuciado te muestran una tabla (_figura 2_) en nomenclatura inglesa, pero después en la conversión (_Cuadro 1_) muestran otros valores numéricos, en especifico; en la tabla tenemos que el **Si**(**B**) es 11 y en la conversión muestran que el **Si _bémol_** (**B**___b___)  es el 11. 
¿Cual debemos incluir  en nuestras tablas?

**Comment by mfanselmo1** [comment]
Hola!
Tienes toda la razon, el cuadro 1 (Si = 12) tiene los valores corridos en 1. Usa la tabla de la figura 2.

**Comment by Hernan4444** [comment]
Hola, voy a corregir algo **importante** los numeros están bien, porque el **cuadro 1** es solo una forma de escribir la nota en la interfaz `do == c== 1` y luego de saber la nota y la escala, tienes que utilizar la **figura 2** para determinar el valor de la nota en el bytes. No confundir la nomenclatura de la interfaz y el valor en el midi.

Saludos ✌️

**Comment by Bipavez** [comment]
Sigo confundido, en la figura 2 no está el **B**___b___, ¿Qué hacemos? ¿Ignoramos el input del Si bémol?

**Comment by jabugmann** [comment]
De lo que recuerdo de música, **Bb** == **A#**, pero no estoy seguro

**Comment by Bipavez** [comment]
OH. Muchisimas Gracias!
