### ISSUE TITLE
Posible error ejercicio propuesto 2.2 semana 10

### ISSUE THREAD

**Issue by denisseleiva** [IIC2233/syllabus#702]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola!! Creo que en el ejercicio 2.2 de la semana 10 en el módulo reloj.py la línea 77 debería ser **if hora.count(":") == 2:** y no != 2
No entendía por qué no se me seteaba la hora al cambiarla y creo que ese es el problema, que alguien me corrija si el problema era otro y eso tiene que quedarse con != 😅

**Comment by aaossa** [comment]
Hola @denisseleiva , no me había dado cuenta de eso, pero tienes toda la razón. De hecho, el ejemplo del `QLineEdit` es justamente `"00:00:00"`, así que claramente se esperan exactamente 2 ":" 😅 ¡Muchas gracias por el aviso! No sé si lo actualicemos en el repo público para que no tengan problemas al hacer `git pull`, pero lo corregiré en nuestro repo interno para que en próximos semestres no exista el problema ✨ Muchas gracias y éxito con tu estudio 💪
