### ISSUE TITLE
Duda respecto a cargar el mapa

### ISSUE THREAD

**Issue by lewebe** [IIC2233/syllabus#702]
Hola, me gustaría saber qué entidad se espera que usemos sobre la cual pueda cargar mi mapa. En el archivo _mapa.csv_, se dan las coordenadas de dónde debe ir cada objeto, pero no me queda claro si usando un layout o quizás simplemente un QLabel se "reinician" las coordenadas y me toma la esquina superior izquierda de esa entidad como el (0,0) en lugar de que el (0,0) sea la esquina superior izquierda de toda la ventana.

**Comment by danckoo1** [comment]
hola!
en este caso la utilización de un layout me parece que sería bastante complicado para lograr 
ubicar las cosas en coordenadas exactas, por lo que para lograr tu objetivo de mover el centro de coordenadas podrías seguir una de las siguientes recomendaciones, ya que la carga del mapa 
queda mas bien a tu criterio:

- utilizar alguna clase a modo de contenedor, ya sea un qwidget, qframe u otro que encuentres adecuado.  Esta clase deberás instanciarla en la ventana y definir su geometría de forma tal que 
esta coincida con la región donde tu mapa se encontrará ubicado. Ahora, cada label que quieras incorporar al mapa, deberá utilizar al contenedor como su parent y de este modo al definir las coordenadas de tu label, el (0,0) se encontrará en la esquina superior izquierda de tu mapa.

- crear una función a la que le entregues las coordenadas de los labels y esta se encargue de sumarles un vector de traslación, de forma tal que el (0,0) coincida con la esquina de tu mapa.

espero se entienda, saludos!
