### ISSUE TITLE
Chunks

### ISSUE THREAD

**Issue by pascal1003** [IIC2233/syllabus#702]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

[Describe tu duda de manera detallada, explicando los contenidos en cuestión y ojalá colocando código o un caso de uso de ejemplo]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

Hola, 
No me queda claro para que sirven los chunks si es que de igual manera mandamos todos en un solo mensaje.

**Comment by matiasmasjuan** [comment]
Hola @pascal1003 !

Uno de los **objetivos** de esta tarea es poder darles una estructura dada para el envío de mensajes, y **evaluar** si es que ustedes son capaces de seguir con la misma especificación. Ahora bien, en los protocolos TCP la idea es que un conjunto de datos pueda ser enviada de forma ordenada. Sin embargo, para que este protocolo se lleve a cabo de forma correcta, es **necesario** saber con antelación la **cantidad** de *bytes* que el servidor envía, y que el cliente recibe. La gracia de los *chunks*, es que permiten fraccionar el mensaje completo de un largo indeterminado, a muchos subconjuntos del mensaje con un largo **conocido** tanto por el cliente como el servidor. Por lo tanto, si no utilizaramos *chunks*, el cliente nunca sabría cuántos *bytes* debe recibir en cada iteración.

Ahora bien, respondiendo a tu pregunta, los *chunks* son sumamente importantes y son utilizados en la práctica. Esto se debe a que en la realidad es muy complejo enviar mensajes de gran tamaño a través de un conjunto de *bytes*. Esto implicaría que el proceso de envío fuera mucho más lento, y en caso de cualquier error de conexión, se debería empezar **todo el proceso** de nuevo. En cambio, si enviamos la información por chunks y ocurre un error, solo basta con restaurar el envío desde el último chunks enviado, lo cual haría el proceso mucho más seguro. Ahora bien, para esta tarea se solicita el envío de imágenes. Estos se podrían considerar como conjuntos de *bytes* de gran tamaño, por lo que es **fundamental** que se envíe a través de *chunks*. De hecho, si intentas enviar imágenes en *python* a través de *sockets*, te darás cuenta que es altamente posible que la imagen no se reciba de forma correcta (puedes probar con enviar una imagen de 4 MB o más y ver lo que sucede). Por esta razón, para evitar cualquiera de estos problemas, se solicita usar este mecanismo para enviar tanto mensajes como imágenes.

Espero haber respondido a tu pregunta, y mucho éxito con la tarea! :smile:
