### ISSUE TITLE
Manejo de bytes y rgb en edición de imágenes

### ISSUE THREAD

**Issue by AndresGarciadelaHuerta** [IIC2233/Syllabus#703]
Hola! Tengo una duda de la sección de edición de imágenes. Lo que entiendo es que debemos pasar las imágenes a bytes y con eso poder obtener sus estructuras, IHDR, IDAT (qué no me queda claro si es uno o varios) e IEND. Pero después en convertir imagen a PNG se habla de la matriz de pixeles RGB y en crear el IHDR y el IDAT, pero según entiendo si paso las imágenes a bytes como que ya me vendrían ambos creados, con lo que solo necesito leerlos para obtener la información que necesito. Además no entiendo de donde podría obtener la matriz de pixeles RGB. Espero se entienda mi duda, gracias!

**Comment by vijuarez** [comment]
Hola!

Uno de los principales objetivos de la tarea es que uses manejo de bytes, lo cual incluye investigar por tu cuenta distintos formatos y tipos de archivos. El que puedas descubrir como funcionan los PNG e implementar estos mecanismos en tu código sera evaluado, por lo que no podemos decirte mucho. Con lo aprendido en el material y lo incluido en el enunciado debería ser suficiente.

Saludos y suerte!
