### ISSUE TITLE
Duda edición de canciones

### ISSUE THREAD

**Issue by llloyola** [IIC2233/Syllabus#703]
Al momento de estar creando una canción o editando una existente, ¿cada nota agregada debe realizar un cambio inmediato a los bytes de la canción en el servidor? ¿O se pueden agregar varias notas, terminar el proceso mediante algún botón "Listo" y finalmente alterar los bytes de la canción en el servidor?

Otra duda... ¿Nuestras ediciones sólo deben ser capaces de agregar notas y no quitarlas?

**Comment by nachocontreras** [comment]
Hola!

Sí, cada nota agregada debe realizar un cambio en tiempo real en los bytes de la canción en el servidor.

Aparte de añadir notas, también se debe poder eliminar notas.

Éxito!

**Comment by nachocontreras** [comment]
Hola!

Sí, cada nota agregada o eliminada debe realizar un cambio **en tiempo real** en los bytes de la canción en el servidor y en lo que ven los observadores de la sala de edición.

Aparte de añadir notas, también se debe poder eliminar notas.

Éxito!

**Comment by llloyola** [comment]
Gracias!

No me queda muy claro... Dijiste que:

- "cada nota agregada o eliminada debe realizar un cambio en tiempo real en los bytes..."
- "puedes manejar esa edición de otra forma dentro del servidor, mientras los demás clientes crean que las ediciones están en tiempo real"

Entonces yo podría hacer creer a los demás clientes que los cambios se están generando en vivo y alterar los bytes al final de la edición?

**Comment by llloyola** [comment]
Pero si llega otro cliente que quiere descargar la canción, deberá esperar a que ésta termine de editarse, no? Pues la única forma de descargar una canción es cuando está se encuentra en "Canciones listas", cosa que no va a ocurrir hasta que se termine de editar. Finalmente, si descarga la canción, quiere decir que siempre va a ser la versión más actualizada de ésta, no?

**Comment by llloyola** [comment]
Entonces... Siempre y cuando haga (y haga __CORRECTAMENTE__) el manejo de _bytes_, puedo hacerlo al final, haciendo creer a los demás clientes que los cambios son en vivo?

Puedo simplemente no realizar cambios en los _bytes_ si el cliente que está editando llegara a desconectarse repentinamente?

**Comment by Arcoirisky** [comment]
La idea es que los cambios se mantengan. Si te desconectaste pero justo alguien descargó la canción, ese alguien debería poder escucharla con los cambios.

**Comment by llloyola** [comment]
Me enredé... En el enunciado dice que un usuario sólo puede descargar canciones de _Canciones listas_, no? Ese "pero justo alguien descargó la canción" es justo antes o justo después de que el usuario se desconecte/caiga? De ser justo antes, sería imposible, pues la canción estaría en _Canciones en edición_ D:

**Comment by Arcoirisky** [comment]
No entres en pánico O: 

Se pide que sea un editado en vivo. Cómo dijo Hernán más arriba:

'''Imagina que alguien manda 5 notas y luego se desconecta el cliente y/o servidor, se puede perder los últimos cambios :s. Con edición en vivo, no pasará dicho problema.'''

Eso responde a tu última pregunta. No puedes simplemente eliminar la edición de alguien que se desconectó. 

Vuelve a leer el comentario de Hernán y las otras respuestas :D Tu puedes /o/
