### ISSUE TITLE
Utilizacion threading Tarea 2

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2233/syllabus#703]
Hola. Tengo una pregunta sobre la utilización de threading en la tarea 2.
Por lo que veo en la tarea, lo pedido es que usemos estos en interfaces. Me cuesta imaginarme usándolos ya que vimos threading separado de interfaces. Ahora mi pregunta es, es obligatorio usarlo en el front end o podría usarlo en el "codigo mismo" (back end) y recibir el puntaje por la utilización de estos de todas formas?

**Comment by jbulness** [comment]
Hola @dsepulveda3!

En los contenidos de la semana 11 se muestran ejemplos de la utilización de __threads__ en interfaces gráficas y como estos elementos se relacionan con el __back-end__ y con el __front-end__. Estos ejemplos se pueden ver tanto en los cuadernillos de contenido como en los ejercicios propuestos y te van a servir para poder imaginarte como usarlos en tu tarea.
