### ISSUE TITLE
Nuevos clientes cuando hay mesas llenas

### ISSUE THREAD

**Issue by knight-who-say-ni** [IIC2233/syllabus#704]
Tengo una duda con la llegada de nuevos clientes, ya que en el enunciado se dice que cuando estos aparecen llegan a alguna mesa vacía. Pero que pasa si no hay mesas vacias?? Debo crear una "lista de espera" con ellos?? y en ese caso, debo contabilizar ese tiempo de espera para ver si se enojan o se van??

Muchas gracias!!

**Comment by bvasquezm** [comment]
Hola @knight-who-say-ni! 

Claro. Los clientes pueden llegar en la medida que hayan mesas disponibles, es decir, si todas las mesas están llenas simplemente no deben aparecer clientes, te recuerdo que hay un máximo de clientes por ronda y que adémas existe una probabilidad de aparición asociado a los clientes. Mucho éxito!
