### ISSUE TITLE
Seccion 3.1.3 del enunciado vs header de los midis. 40 vs 160 en los ticks.

### ISSUE THREAD

**Issue by FJavierOss** [IIC2233/Syllabus#704]
En la sección 3.1.3 dice:

>Número de ticks por cuarto de tiempo musical. Este número representa el tiempo necesario que el
computador le otorga a “un cuarto de tiempo musical” en la melodı́a. Por defecto, esta tarea debe usar
40 ticks por cuarto de tiempo musical. 2 Esto se explica con más detalle en la sección 3.2.

Pero leyendo los archivos midi ("game of thrones" y el de "whenever, whenever") que nos pasaron, la cantidad de ticks que me aparecen son 160 en vez de 40, esto es, que en el tercer número correspondiente a la data del header obtengo 160, teniendo en cuenta que el primer byte es "0" y el segundo es "160". Quisiera saber si es error de lectura mio, o se suponia que esto debia ser así.

**Comment by Hernan4444** [comment]
hola, tuve un error y efectivamente es 160. En el MIDI se pone el número de ticks para representar **1 tiempo ** y no un cuarto Como el cuarto de tiempo es 40, entonces un tiempo es 160 como sale en el MIDI que leíste.

Se va a actualizar el enunciado para que en esa sección diga que el header tiene el **número de ticks para un tiempo musical**. La constante de un cuarto de tiempo == 40 se mantiene para que salga todo bien.

**Comment by FJavierOss** [comment]
A ok, gracias.
