### ISSUE TITLE
Material: Ejemplo Cliente UDP en Python

### ISSUE THREAD

**Issue by Kitaps** [IIC2233/Syllabus#705]
Hola en la primera parte del Cliente UDP en Python del material no logro hacer fucnionar el ejemplo. 

Traté varias cosas (inclusive tratar de correrlo localrmente, cambiar cosas y sigo con que se queda pegado esperando recibir algo (el recvfrom). 

Está malo el codigo o que cosa estoy entendiendo mal para ver eso en mayor profundidad? 

Gracias

**Comment by andresfdezc** [comment]
¿Estás corriendo el cliente y el servidor al mismo tiempo en archivos .py separados? ¿Si se imprime algún error, cuál es? ¿Probaste reemplazando `server_name = socket.gethostname()` por `server_name = "127.0.0.1"` si estás corriendo localmente?

**Comment by Kitaps** [comment]
> ¿Estás corriendo el cliente y el servidor al mismo tiempo en archivos .py separados?
si

> ¿Si se imprime algún error
no

>¿Probaste reemplazando server_name = socket.gethostname() por server_name = "127.0.0.1"
si

**Comment by andresfdezc** [comment]
Por favor, agrega `print(server_name, server_port)` en ambos archivos antes de las líneas `s.sendto()`. También agrega un `print("Enviado desde el servidor")` y `print("Enviado desde el cliente")` después de `s.sendto()` en cada archivo, respectivamente. ¿Qué se imprime?

**Comment by Kitaps** [comment]
Si hasta el recv funciona perfecto:

`127.0.0.1 15000
Enviado desde el servidor`

`127.0.0.1 15000
Enviado desde el cliente`

son los outputs, como esperaba, pero luego no pasa nada más.

**Comment by Kitaps** [comment]
Ohhh perdón ya caxe cual era mi problema. Andaba usando mal el codigo. 
(Igual no me funciona en Jupyter)

**Comment by Kitaps** [comment]
Ohhh perdón ya caxe cual era mi problema. Andaba usando mal el codigo. 
(Igual no me funciona en Jupyter)

**Comment by andresfdezc** [comment]
Este código NO funciona en Jupyter, pues se necesita correr 2 programas paralelamente y no en secuencia.
