### ISSUE TITLE
Errores con señales de PyQt5: "not callable" y "AttributeError emit"

### ISSUE THREAD

**Issue by sofiuni** [IIC2233/syllabus#705]
El codigo esta en la repo... no entiendo que hice mal, tengo un archivo aparte solo con la señal y un archivo para cada ventana (2), las dos heredan la señal. Una la emite en una funcion llamada al presionar un boton y el otro lo recibe en el init como dice en los contenidos. Por que me da error?

**Comment by fdoflorenzano** [comment]
Hola @sofiuni,

Los errores de tipo `"TypeError: ... is not callable"` en general se refieren a lo mismo, que es cuando se intenta tratar a un objeto que no es llamable, como llamable. Un objeto llamable es cualquiera que acepta la sintaxis: `objeto()`, como las funciones y las clases. Si por ejemplo tengo un objeto entero: `objeto = 1` e intento ejecutar `objeto()`, obtendré: `"TypeError: 'int' object is not callable"`.

En este caso es lo mismo con señales, estos objetos no son llamables ya que `"senal()"` no tiene sentido. Tienen métodos como `connect` y `emit` que si son funciones y son llamables. Una razón es que hayas intentado llamar a una señal como si fuera una función, o la hayas tratado como una en alguna parte.

Espero se entienda, nos avisas si te quedan dudas.
Saludos.

**Comment by sofiuni** [comment]
Mire mi codigo bastante y realmente no entiendo en que parte del codigo hice eso. Me pueden ayudar?

**Comment by fdoflorenzano** [comment]
Hola,

Lo que hiciste fue conectar un evento de clic de botón a una señal: `boton.clicked.connect(senal)`, en vez de a una función o método. Recuerda que `connect` recibe una función o método (objetos llamables), no señales. Al apretar el botón, Python ve a que está conectado el evento, intenta llamarlo, pero se encuentra con una señal y tira error.

Saludos.

**Comment by sofiuni** [comment]
Solucione eso, ahora me da este error: AttributeError: 'PyQt5.QtCore.pyqtSignal' object has no attribute 'emit'
el codigo esta arriba, segui una solucion de los foros de pyqt pero me da el error igual. Que estoy haciendo mal?

**Comment by fdoflorenzano** [comment]
Hola @sofiuni,

Revisando tu caso, tienes correctamente encapsulada la señal dentro de una clase que hereda de `QObject`, pero el detalle es que la estás intentando usar como atributo de clase, a través de la clase, no como una instancia de dicha clase. Solo al instanciar el objeto con la señal, la señal realmente se crea.

Me explicaré un poco más para cualquier persona que le interese la solución. Tu código se puede resumir a algo de este estilo:

```python3
from PyQt5.QtCore import QObject, pyqtSignal

class Senal(QObject):
    mi_senal = pyqtSignal()

Senal.mi_senal.emit()
```

Al intentar ejecutar ese código, arroja el error `AttributeError: 'PyQt5.QtCore.pyqtSignal' object has no attribute 'emit'`. Esto es porque las instancias de señales `pyqtSignal` solo cobran vida al instanciar efectivamente, entonces si funciona cambiándolo a:

```python3
from PyQt5.QtCore import QObject, pyqtSignal

class Senal(QObject):
    mi_senal = pyqtSignal()

instancia = Senal()
instancia.mi_senal.emit()
```

Espero se entienda, saludos.
