### ISSUE TITLE
Escuchar sonidos nuevos, o por editar

### ISSUE THREAD

**Issue by jerrymendoza** [IIC2233/Syllabus#705]
No encontré especificado si en algún lugar hay “emitir” el sonido de la nota que se está editando (agregando, eliminando o reemplazando) o solo se escuchará el archivo después de descargar? (En local, con un reproductor)

**Comment by mfanselmo1** [comment]
Hola!
Efectivamente, no hay que (o no es necesario) emitir el sonido. No se puede directamente con pyqt. Los puedes probar con la pagina que sale en el enunciado.
