### ISSUE TITLE
[Error paso 6]

### ISSUE THREAD

**Issue by Okhan97** [IIC2233/Syllabus#705]
![image](https://user-images.githubusercontent.com/26289334/27511963-e9d73996-58ff-11e7-9b6f-089a3c8a96bd.png)
Hola buenas, cuando intento hacer el ultimo sub-paso del paso 6 me tira el siguiente error D:

**Comment by Okhan97** [comment]
Edit: noté que faltaba un "_" entre FLASK y APP, pero cuando lo agregué me tira el mismo mensaje

**Comment by Okhan97** [comment]
![image](https://user-images.githubusercontent.com/26289334/27511999-ec4c8a2c-5900-11e7-9c62-f8789cc1d891.png)

Lo solucioné (me faltaba un espacio) pero ahora me dice que no encuentra la app, esta deberia ser algun archivo ?

![image](https://user-images.githubusercontent.com/26289334/27512005-11151b76-5901-11e7-9cad-3bd878cbff7c.png)

Eso es lo que hay en mi carpeta del repo de la T07, main importa de superduperapp tal como dice en el enunciado, que me falta ?

**Comment by MainScientist** [comment]
Al parecer el Procfile no se encuentra agregado a git. intenta hacer `git add .`. Lo otro parece ser que no se encuentra la app de heroku con el nombre que pusiste. ¿Estás seguro que tu app se llama así?

**Comment by Okhan97** [comment]
El nombre de la app no es lo que va en esta linea de codigo ? 
`import flask
app = flask.Flask("okhan_app")`

**Comment by MainScientist** [comment]
No, el nombre de la app es el nombre que te da heroku al hacer `heroku create`

**Comment by Okhan97** [comment]
Muchas gracias, ya lo arreglé seguiré trabajando, pero me quedó la duda, si el nombre de la app es lo que heroku nos da (y que podemos modificar) entonces que es lo que va dentro de flask.Flask() ???

**Comment by MainScientist** [comment]
De la documentación de Flask:
> This name is used to find resources on the filesystem, can be used by extensions to improve debugging information and a lot more.
No deben preocuparse por este nombre, el nombre importante es el de su aplicación de heroku.

**Comment by Okhan97** [comment]
Muuuchas gracias !
