### ISSUE TITLE
Botón de pausa ¿cambia de nombre?

### ISSUE THREAD

**Issue by Gustav2000** [IIC2233/syllabus#705]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/327)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/326)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]
En el enunciado dice que al presionar el botón de pausa el juego se detiene, y cuando se quiere continuar se vuelve a presionar el botón de pausa.
[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]
**Mi duda es si el botón tiene que cambiar de nombre (ej: continuar) o siempre tiene que decir pausa?**

**Comment by JuaniAndres** [comment]
Hola @Gustav2000 
Ambas opciones que planteas son válidas, lo importante eso si es que en la opción que elijas cuando aprietes el botón de pausar o la tecla P en tu teclado se note que el juego se pausa o continua.

**Comment by Gustav2000** [comment]
Gracias!
