### ISSUE TITLE
Get Issues Github

### ISSUE THREAD

**Issue by benjamimo1** [IIC2233/Syllabus#706]
Hola! Dentro de mi Git cree una Repo demo y un Issue demo dentro de esta. A la hora de hacer la request por issues de mi git, este me retorna una lista vacia. De que me perdí jajaja?

**Comment by benjamimo1** [comment]
Lo solucioné dando Assign manual al issue a mi usuario (sea lo que eso signifique). Asumiremos que en la revision los issues sobre los cuales se trabajan estarán asignados al usuario?

**Comment by lvvillarroel** [comment]
Es que el request que estás usando es para mostrarte solo las issues que tienen a tu usuario asignado, si ves ma abajo en la documentación hay otro para enlistar todas las issues del repositorio, que sería: GET /repos/:owner/:repo/issues

**Comment by iqacevedo** [comment]
@benjamimo1 es lo que dice @lvvillarroel, no puedes asumir que se probarán solo issues con un usuario asignado.

**Comment by benjamimo1** [comment]
Dale! Lo modifique ahora. Lo habia hasta específicado en el readme jaja
