### ISSUE TITLE
Importar módulos de carpetas superiores y problema con archivos .ui

### ISSUE THREAD

**Issue by Jamesmoreno21** [IIC2233/syllabus#706]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/327)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/326)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Estoy analizando algunas partes del enunciado y voy a requerir importar *parametros.py* en subcarpetas en relación a la que se encuentra:
-T02
|-->parametros.py
|-->main.py
|
|--> Carpeta1
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|--> archivo.py
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|--> archivo2.py
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|--> diseño.ui

En este caso buscaría importar *parametros.py* en *archivo.py* y *archivo2.py* ¿ Cómo se puede hacer? Lo intenté de varias formas y solo encontré mecanismos para importar lo opuesto (*archivos* en *parametros.py*) 

Mi otra duda es que, al intentar utilizar un archivo **.ui** como el del esquema de arriba tengo problemas con la importación de este, me ocurre que si en *archivo.py* cargo el archivo  *diseño.ui* en una clase ejecutando el programa directamente en la consola, funciona bien pero si importo la clase en *main.py* me señala que **no se encuentra el archivo .ui**, probé directamente en VSCode y si abro la carpeta T02 no funciona pero si abro exclusivamente Carpeta1 si me permite cargar el archivo *.ui*. Ojalá me puedan ayudar y desde ya muchas gracias! :)

**Comment by furcelay** [comment]
Hola!
Para hacer un import desde un directorio relativo al actual se utiliza la siguiente notación:
*  usa '.' para indicar que se encuentra en el mismo directorio (ej: `from .modulo import funcion_x` o `from . import modulo`)
*  usa un punto extra por cada nivel superior (ej: `from ..modulo import funcion_x` o `from .. import modulo` para un nivel más arriba)

Sobre tu segunda duda, los _paths_ durante la ejecución del programa son relativos al directorio donde abres el terminal. Considerando que vas a ejecutar el programa del mismo directorio que `main.py`, entonces debes usar los *paths* relativos a la ubicación de ese módulo (en tu caso `Carpeta1/dieño.ui`). Si quieres hacer pruebas dentro de un módulo en un directorio distinto tendrías que cambiar el *path* (puedes incluir un `os.chdir` dentro del *scope* `if __name__ == "__main__":` o con el comando `cd` en el terminal). Si usas *VSCode*, dependerá de tu configuración pero por defecto el terminal se ejecuta desde la carpeta que tienes abierta como proyecto.

Saludos!

**Comment by Jamesmoreno21** [comment]
Muchas gracias! Me quedó claro! :)

**Comment by Zenos-Paradox** [comment]
Hola, yo todavía tengo problemas importando archivos.ui . Debería habrir otra issue o pregunto acá mismo?

**Comment by furcelay** [comment]
> Hola, yo todavía tengo problemas importando archivos.ui . Debería habrir otra issue o pregunto acá mismo?
> EDIT: No importa, creo que lo solucioné

Súper, en todo caso, está bien preguntar por aquí si consideras que tu problema concuerda con el anterior

**Comment by pabloalvarez67** [comment]
> > Hola, yo todavía tengo problemas importando archivos.ui . Debería habrir otra issue o pregunto acá mismo?
> > EDIT: No importa, creo que lo solucioné
> 
> Súper, en todo caso, está bien preguntar por aquí si consideras que tu problema concuerda con el anterior (después de haber intentado con la respuesta)

Hola!! yo tengo una duda, los recursos que cree para importarle las imagenes a mi ventana de qtdesigner, como los importo en mi código? ya que importe mi ventana y me tira el siguiente error de módulo:

ModuleNotFoundError: No module named 'fondo_rc'

gracias!!

**Comment by aaossa** [comment]
> 
> 
> > > Hola, yo todavía tengo problemas importando archivos.ui . Debería habrir otra issue o pregunto acá mismo?
> > > EDIT: No importa, creo que lo solucioné
> > 
> > 
> > Súper, en todo caso, está bien preguntar por aquí si consideras que tu problema concuerda con el anterior (después de haber intentado con la respuesta)
> 
> Hola!! yo tengo una duda, los recursos que cree para importarle las imagenes a mi ventana de qtdesigner, como los importo en mi código? ya que importe mi ventana y me tira el siguiente error de módulo:
> 
> ModuleNotFoundError: No module named 'fondo_rc'
> 
> gracias!!

Pregunta movida a #799

**Comment by amanda1415** [comment]
Hola! Tengo el mismo problema por el que se creo la issue e intento resolverlo usando from . import modulo (tengo mas o menos la misma organización de archivos que pusieron mas arriba) pero no funciona y me lanza este error: 
ImportError: cannot import name 'parametros' from '__main__' (relative path del archivo desde donde lo corro)
(estoy corriendo el archivo.py siguiendo el esquema de mas arriba)

**Comment by furcelay** [comment]
hola @amanda1415, ¿como lo estás importando?

Creo que con la explicación de arriba deberías poder solucionar tu problema, si ejecutas tu programa desde `main.py` y `parametros.py` está en el mismo directorio, entonces desde cualquier módulo en tu programa puedes importar los parámetros como `import parametros` (o `from parametros import ...`).

**Comment by amanda1415** [comment]
Hola! creo que ya lo solucioné, pero muchas gracias!
