### ISSUE TITLE
Problema al instalar qtdesigner

### ISSUE THREAD

**Issue by vWing7** [IIC2233/syllabus#706]
Al instalar pyqt5-tools se realiza la instalación, pero cuando voy a la carpeta de tools, designer no está ahí. Al escribir designer en cmd lo puedo abrir, pero igual me gustaría saber donde está el programa.

Gracias

**Comment by kadroguett** [comment]
Hola @vWing7 
Puedes saber su ubicación buscando en inicio y luego con el click derecho seleccionar la opción "abrir la ubicación del archivo".

**Comment by vWing7** [comment]
Gracias, había ignorado el archivo que me salía al buscar porque no es el programa directamente, pero ese me sirvió
