### ISSUE TITLE
Inconsistencia enunciado vs ejemplo?

### ISSUE THREAD

**Issue by jabugmann** [IIC2233/Syllabus#706]
Hola,

Según el enunciado, punto 3.2, **Tiempo**, paso 3 de pasar a bytes:

> 3. De derecha a izquierda, a cada elemento de la lista, menos el primero, se le agrega un octavo bit al inicio con valor 1, y al primer elemento, se le agrega un un octavo bit al inicio con valor 0. Con el ejemplo anterior, la lista era: [0000101, 0000001]. Con estos nuevos bits, ahora queda: [10000101, 00000001]

Se dice que al primer elemento se le agrega un 0 y al resto un 1, pero en el ejemplo se hace al revés. Cúal es la forma correcta?

**Comment by Hernan4444** [comment]
@jabugmann dice **De derecha a izquierda**, osea el primer elemento que veremos es el último de la lista.

**Comment by jabugmann** [comment]
ok, gracias
