### ISSUE TITLE
Escribir a telegram

### ISSUE THREAD

**Issue by ofvera** [IIC2233/Syllabus#707]
Luego de generar la conexion con el webhook, recibir un mensaje y encontrar el id del chat, intento enviar un mensaje al chat de la siguiente forma:
url = "https://api.telegram.org/bot<Token>/sendMessage"
message = {"chat_id": ##, "text" : Mensaje}
req = requests.post(url, data=json.dumps(message))

y aun así me tira un error <Response [400]>
Pero no tengo a idea a que se debe este problema

**Comment by chapito96** [comment]
#No soy ayudante
Te falta el parámetro "headers=", revisa la domunetación de telegram.

**Comment by akaminetzkyp** [comment]
Justo después de `bot` en tu `url` tienes que poner el token de tu bot. Tu `url` debe quedar así: `https://api.telegram.org/bot<tu_token>/sendMessage`. Saludos!

**Comment by ofvera** [comment]
Si tengo el token, no lo puse para no escribir mucho texto nomas :P, no encuentro la documentacion donde habla del parámetro headers. Seguire buscando, pero por lo menos donde habla de los methods que existen no habla de eso

**Comment by ofvera** [comment]
lo encontre! :)
