### ISSUE TITLE
Chef Experencia

### ISSUE THREAD

**Issue by CataSudo** [IIC2233/syllabus#707]
¿Cuantos palatos intermedio necesitan un chef para pasar de principiante a intermedio? Y nosotros definimos que bocadillos son lo que permiten que suba de nivel?
Gracias!

**Comment by danckoo1** [comment]
Hola!
En el enunciado se menciona que la cantidad de platos necesarios es de `PLATOS_INTERMEDIO`, y se escribe en este formato debido a que es un parámetro que deberás incorporar a tu archivo `parametros.py`. En caso de que no se especifique el valor, deberás asignarlo a tu criterio, procurando que no dificulte la interacción con el programa; esto aplica para todo el resto de los parametros. 
Suerte
