### ISSUE TITLE
Sprites, carpeta figuras_ritmo

### ISSUE THREAD

**Issue by Gustav2000** [IIC2233/syllabus#707]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/327)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/326)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]
En el enunciado en la sección *6.1 Sprites* aparece la carpeta con nombre *figuras_ritmo*

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]
**Sin embargo, creo que esta carpeta es la que se llama simplemente *flechas*.**

PD: es algo sutil y que se entiende pero quizás sea bueno aclarar que el enunciado decía otro nombre de carpeta.

**Comment by JuaniAndres** [comment]
Hola @Gustav2000 
Efectivamente fue un detalle que se nos paso en el enunciado como mencionas debería aparecer como la carpeta flechas. Muchas gracias por avisar.

**Comment by gatochico** [comment]
Hola @Gustav2000 , se ha actualizado el enunciado con el nombre correcto de la carpeta (`flechas`). Gracias por avisar!

**Comment by Gustav2000** [comment]
De nada!!
