### ISSUE TITLE
Ayuda con Python Gurobi

### ISSUE THREAD

**Issue by ajahr95** [IIC2233/Syllabus#707]
En otro ramo (capstone investigación operativa) tengo que programar un modelo para resolverlo con la combinacion python-gurobi. Quería saber si algún ayudante tiene conocimientos de su uso y si fuera así, si tuviera algún momento (a coordinar) para poder enseñarme lo que pueda. Gracias de antemano.

**Comment by hanavarrete** [comment]
Yo he usado gurobi algunas veces. Lamentablemente no tengo tiempo a corto plazo para poder juntarme contigo, pero todo lo que aprendí lo hice viendo los ejemplos (son bien intuitivos y simples) de [acá](http://www.gurobi.com/resources/examples/example-models-overview)

**Comment by ajahr95** [comment]
@hanavarrete gracias!

**Comment by mmsaavedra1** [comment]
@ajahr95 
Estoy haciendo Opti y tuvimos que resolver el modelo en Gurobi. Mándame un correo y te reenvío el modelo con el archivo .py para que puedas ver como funcionan las cosas.

mmsaavedra1@uc.cl

Saludos!
