### ISSUE TITLE
[Canal] Transformación de duración a bytes 

### ISSUE THREAD

**Issue by diegoheg** [IIC2233/Syllabus#707]
En la sección 3.2, cuando dice:
![screenshot_1](https://user-images.githubusercontent.com/26411041/41365065-65c8176a-6f06-11e8-89b3-4e2886e56a96.png)
¿Con primer elemento se refiere al primero de la lista inicial o al primero de la lista inicial ya invertida (último de la lista inicial)?

**Comment by ptflores1** [comment]
Hola !
Se refiere al último de la lista inicial, ojo que la lista no se invierte realmente, es solo una manera de explicarlo.

Si la lista fuese `[a, b, c, d]` el elemento al que se le agrega el 0 seria `d`, resultaria algo de la **forma** `[1a, 1b, 1c, 0d]`

Saludos !

**Comment by diegoheg** [comment]
Gracias!!!

**Comment by clementeross** [comment]
@ptflores1 podrías dar un ejemplo de una transformación de duración de tiempo a bytes en la que la lista generada contiene 3 o más elementos? Gracias!

**Comment by ptflores1** [comment]
@clementeross 
Consideremos el numero 83526:

1. Transformandolo a binario &rarr; `10100011001000110`
2. Generando los fragmentos de 7 bits nos queda la lista `[101, 0001100, 1000110]` y luego al agregar _padding_ al último fragmento (de derecha a izquierda) es decir el primer elemento de la lista tenemos `[`**`0000`**`101, 0001100, 1000110]` &rarr; `[0000101, 0001100, 1000110]`
3. Luego debemos agregar el octavo bit al inicio de cada elemento de la lista `[`**`1`**`0000101, `**`1`**`0001100, `**`0`**`1000110]` &rarr; `[10000101, 10001100, 01000110]`

Los pasos tienen la misma numeración que en el enunciado, espero que haya quedado claro. Saludos!

**Comment by clementeross** [comment]
@ptflores1 Muchas gracias!!

**Comment by antoniacobo** [comment]
@ptflores1 tiene que ser en una lista, o un bytearray?
