### ISSUE TITLE
Problema de conexión de un socket de una máquina corriendo Windows consigo misma

### ISSUE THREAD

**Issue by Panckx** [IIC2233/Syllabus#708]
Hola! Jugando un poco con la materia de networking me topé con lo siguiente: cuando en mi computador corriendo Windows intento conectar un socket (no hacer bind, eso si funciona) a un puerto del mismo computador, me salta el siguiente error:

`OSError: [WinError 10013] Intento de acceso a un socket no permitido por sus permisos de acceso`

Sin embargo, si trato de conectar el socket a un puerto de otro computador corriendo Linux o si trato de conectar desde un computador corriendo Linux el socket a un puerto del computador corriendo Window o incluso si trato de conectar desde el computador corriendo Linux un socket a algún puerto del mismo computador, todo funciona perfectamente. Estoy asumiendo que lo que está pasando es que Windows no me deja conectarme a un puerto de donde se instanció el socket, aunque no estoy seguro porque no he probado conectarme entre dos computadores corriendo Windows.
Hay alguna razón en especial por la que pase? Es algún tipo de control de seguridad adicional que hace Windows para evitar algún tipo de problema? O hay algo que me falta hacer para que pueda conectarme con la misma máquina?
(Cabe decir que los scripts fueron ejecutados desde la consola de una cuenta con permisos de administrador y también desde la consola del administrador predeterminado del computador y el resultado fue el mismo en ambos casos)

**Comment by fgbruna** [comment]
Que número de puerto estás usando?
Podrías probar desactivando el firewall de Windows.
Cuéntame como te va!

**Comment by Panckx** [comment]
He usado de todo! 8000, 8080, 8001, 5001, 5000, 5300... Pero al correr el servidor desde Windows y conectarme en esos puertos desde Linux no tengo problema. También desactivé todos los firewall y antivirus en mi computador y nada...

**Comment by Arcoirisky** [comment]
Haz intentado con 'localhost' o '0.0.0.0' -otros dicen '127.0.0.1' o simplemente ' '-? 
Lo que pasa es que ve los puertos como ocupados :( 

A mí, cuando me sucedió, maté el Avast y se solucionó. Pero es un problema que aparece varias veces en Windows xD 

Buscando en internet salía que el puerto debía ser 50000 o + para Windows O:

¿Alguna mejora? xD Siempre puedes desactivar todo y probarlo de nuevo.

**Comment by Panckx** [comment]
Pero es que no los ve como ocupados porque desde un computador con linux accede perfectamente a ellos, es solo que cuando trata de acceder a si mismo como que no le gusta, y ya he probado con una cantidad relativamente variada de putertos (incluido el 55000) y no funciona :( en todo caso no me dificulta para nada para estudiar/hacer la tarea porque tengo el otro computador que puedo usar de servidor, solamente tuve la curiosidad de saber por qué no se quiere conectar consigo mismo. En todo caso, la parecer usar localhost o 127.0.0.1 solamente hacen una especie de loop en la máquina y son direcciones que sirven para probar conexiones sin necesariamente tener que estar conectado a una red (de hecho, usando esas direcciones puedo hacer funcionar el servidor y el cliente en el computador con Windows con la WiFi desactivada)
