### ISSUE TITLE
Limite busqueda github api

### ISSUE THREAD

**Issue by frvalenzuela** [IIC2233/Syllabus#708]
Para el comando '/get' ¿ podemos asumir que solo dará issues que estan abiertas, o en su defecto que este dentro de las últimas 30 issues?

Porque según la documentación solo podemos hacer 30 request de busqueda por minuto (https://developer.github.com/v3/search/#rate-limit), por lo que si por ejemplo mi usuario hace '/get #1' tira error porque el mi repositorio público tiene más de 30 issues abiertas y cerradas.

**Comment by FernandoPieressa** [comment]
Hola! 

En un request puedes solicitar mas de una issue, si vez la documentacion podras ver "Find issues by state and keyword. (This method returns up to 100 results per page.)"

La cosa es que tienes que activar cuantos resultados retornara en una busqueda de request

Saludos!

**Comment by frvalenzuela** [comment]
eso haré gracias !

**Comment by B-Dominguez** [comment]
Hola, tengo el mismo problema. La primera vez borre el repositorio e hice uno nuevo pero funciono por un rato nomas.  No sé cuál es la razón (ahora tengo una sola issue abierta, y si hago get desde afuera de la aplicación no hay problema). Creo que sirve autenticar la app (no pude hacer esto, en cambio usé un token en el método get)

Peeero ya que parece que  funciona lo del **search**, **¿Cómo lo uso para buscar por número?** Con qué parámetro? porque en la documentación encontré millones de criterios de búsqueda, excepto el número. 

Agradecería muuucho la ayuda!
@FernandoPieressa

**Comment by iqacevedo** [comment]
@B-Dominguez no puedes acceder con lo que sale [acá](https://developer.github.com/v3/issues/#get-a-single-issue) ??
