### ISSUE TITLE
.gitignore y pycache

### ISSUE THREAD

**Issue by isidorabecker** [IIC2233/syllabus#708]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/327)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/326)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Holaaa !!
Es necesario ignorar el archivo pycache en esta tarea ??? y si es así, como se hace en mac. 
Agradecería me pudieran ayudar !!!!

**Comment by syprent** [comment]
en .gitignore de la tarea 2 escribe la siguiente linea:
    __pycache__/ # Byte-compiled / optimized / DLL files
ojalá te sriva

**Comment by isidorabecker** [comment]
ok, muchas gracias !!

**Comment by aaossa** [comment]
Hola @isidorabecker , en general sí es bueno ignorar esos archivos. Te recomiendo darle una mirada al .gitignore del Syllabus, ya que también tienen una explicación sobre qué se está ignorando en cada línea 👌 

https://github.com/IIC2233/syllabus/blob/b8dffc27bf43d493486999e9e48b2540f1bf94f2/.gitignore#L11-L17

En general, todo lo que no sea necesario para que otras personas ejecuten tu código (y archivos grandes) debería estar en el .gitignore. Ojalá te sirva ✨
