### ISSUE TITLE
posibilidad de un segundo horario de consultas

### ISSUE THREAD

**Issue by inmadariaga** [IIC2233/Syllabus#708]
Quería consultar si existe la posibilidad de que realicen un segundo horario de consulta para los que tenemos otros ramos en ese modulo?

**Comment by Jiparavich** [comment]
La próxima semana sería ideal😅

**Comment by Jiparavich** [comment]
x2

**Comment by FernandoPieressa** [comment]
Hola!

Lamentablemente esta semana para la mayoría de los ayudantes está llena de varias interrogaciones y trabajos, por lo que solamente logramos coordinar un horario de sala de ayuda. 

Sin embargo siempre estaremos atentos a dudas en issues para los que no puedan asistir!

Saludos!
