### ISSUE TITLE
¿Por qué hay dos mapas distintos? 

### ISSUE THREAD

**Issue by CataSudo** [IIC2233/syllabus#708]
Hola! En la carpeta Sprites hay dos mapas, eso significa que cuando llegas a 5 estrellas se hace un upgrade desde mapa 1 a mapa 2? O no importa que mapa se use?
Gracias!

**Comment by jeschuwirth** [comment]
Hola @CataSudo,

Se les entregan dos mapas para que puedas personalizar más tu tarea, puedes usar cualquiera de los dos :)

También podrías hacer que el mapa cambie cuando llegas a las 5 estrellas, pero no lo recomiendo ya que te complicas sin necesidad.

Éxito!
