### ISSUE TITLE
Problema con las imagenes desde QT Designer

### ISSUE THREAD

**Issue by MINGOD24** [IIC2233/syllabus#709]
Hola, 

Cuando importo una ventana desde QT Designer con una foto, por alguna razon al correr el codigo la foto no aparece, pero el resto de la ventana aparece normal. Porque puede ser?

**Comment by tomasgv** [comment]
Hola @MINGOD24 !

Hay una respuesta a esto en #690 para que le eches una mirada :eyes:. Por favor comenta allá si esa _issue_ solucionó tu problema :+1:

Saludos! ☕
