### ISSUE TITLE
The request API endpoint was not found

### ISSUE THREAD

**Issue by rodrigozs** [IIC2233/Syllabus#709]
Hola, cree una app y al hacer 
`heroku config:set --app <Nombre de su app>FLASK APP=main.py`
me sale el siguiente error y la verdad no lo entiendo bien

<img width="1204" alt="problema" src="https://user-images.githubusercontent.com/20802825/27513198-0641ec7c-592b-11e7-848b-59bcdcc9c6e6.png">

**Comment by MainScientist** [comment]
El nombre es solo el nombre de la aplicación, no la url de tu página web.
