### ISSUE TITLE
Duda formato notas y conexión a la edición

### ISSUE THREAD

**Issue by julioag** [IIC2233/Syllabus#709]
Hola tengo 2 dudas que me quedaron de leer el enunciado, lo primero es que en ninguna parte (según lo que he leído) en el formato de canal y header existe algún parámetro que de información sobre que instante sonará la nota. Esto quiere decir que todas las notas empiezan a sonar desde el inicio de la canción?
La otra duda, es si todos los usuarios que quieran editar la misma canción estarán conectados a la edición de esta?

**Comment by ptflores1** [comment]
Hola !

- Las notas van a sonar en el orden en que se agregaron al canal
- No puede haber mas de un cliente editando la cancion al mismo tiempo, como se dice en 5.1.4, cuando un usuario elige editar una cancion, la cancion desaparece de la lista "Canciones listas" y pasa a la lista de "Canciones en edicion", recuerda que tambiene existe la opcion de espectar la cancion que se explica en 5.2

Espero haya quedado claro.
Saludos !

**Comment by julioag** [comment]
Gracias por la aclaración, lo que no me queda claro es como se determina a las personas conectadas para que aparezcan en el cuadro de conectados en la ventana de edición en el modo editor/espectador??

**Comment by ptflores1** [comment]
Debe aparecer quien este editando la canción y los espectadores de esa edicion
