### ISSUE TITLE
Parámetros que hay que incorporar en parametros.py

### ISSUE THREAD

**Issue by Gustav2000** [IIC2233/syllabus#709]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/327)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/326)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]
En el enunciado dice que todos los números y palabras que aparezcan con el formato azul (formato para parámetros) deben encontrarse en parametros.py
[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]
**Mi pregunta es si incluso valores como que la Flecha dorada viaja un 50% más rápido tienen que estar en el archivo ya mencionado, o simplemente puedo ingresar directamente ese número en la fórmula?**

**Comment by JuaniAndres** [comment]
Hola @Gustav2000 
Todos los números y nombres que aparecen con el color azul tienen que estar dentro de tus parámetros incluido el que mencionas de la flecha dorada por lo tanto en la formula tienes que ocupar el parámetro y no directamente el valor. La razón es porque imagínate que decides cambiar la velocidad en que viajan las flechas doradas, es mucho más simple tener que ir a tus parámetros y cambiarlo que tener que buscarlo en tu código. Por esa razón es una buena práctica parametrizar.

**Comment by Gustav2000** [comment]
Oka, muchas gracias.
