### ISSUE TITLE
¿Podrían por favor subir los archivos que usaron para evaluar la Tarea 4?

### ISSUE THREAD

**Issue by Pudindin** [IIC2233/Syllabus#709]
Hola,
El ayudante que corrigió mi tarea 4 dijo que el código se caía y que aparentemente era por error de lectura de los archivos. Como mi programa lee perfectamente los archivos que ustedes habían entregado junto con el enunciado, me gustaría poder ver los que usaron para corregir (con los que el programa se caía), y ver así si se puede apelar a una recorrección, o como mínimo entender qué hice mal.
Desde ya, gracias

**Comment by hanavarrete** [comment]
Hola, los archivos fueron los mismos que se subieron en un principio. Revisa bien si el commit que subiste a tiempo posee el mismo código que el que tienes en tu computador. La tarea se cayó en dos sistemas operativos distintos, por lo que te recomendaría revisar bien esos detalles, y sobre todo, dar encoding al abrir archivos. Por último, sobre tu primer punto, te recuerdo que los detalles de cada recorrección deberías subirlos por el formulario oficial. Saludos!

**Comment by Pudindin** [comment]
Acerca de tu último punto, sé que los detalles tengo que subirlos por el formulario oficial, la issue que creé no tenía intenciones de emular una recorrección; sino que sólo expliqué el problema de la caída de mi programa para dar contexto a la petición que hice (de subir los archivos), nada más. 
Y a todo esto, cuando dices "revisar bien esos detalles", ¿acaso pretenden que revise, para cada tarea, que mi programa corra en todos los sistemas operativos que hay? Porque eso entiendo yo, si lo dices justo tras anunciar que se cayó el programa en 2, en particular al tomar en consideración que en el mío no se cae.
