### ISSUE TITLE
Problema al importar otros funciones que he creado en otros archivos.py

### ISSUE THREAD

**Issue by pascal1003** [IIC2233/syllabus#71]
Hola, cuando intento importar una función desde otro archivo .py diferente al que estoy editando el programa me lanza un error el cual no logro entender.
esto es lo que me lanza la consola:

ic2233-2021-1/Tareas/T0/menus.pydorf$ /usr/bin/python /Users/pascal/pascal1003-i 
/usr/bin/python /Users/pascal/pascal1003-iic2233-2021-1/Tareas/T0/menus.py
Traceback (most recent call last):
  File "/Users/pascal/pascal1003-iic2233-2021-1/Tareas/T0/menus.py", line 1, in <module>
    import conversaciones
  File "/Users/pascal/pascal1003-iic2233-2021-1/Tareas/T0/conversaciones.py", line 5, in <module>
    x=str(input())
  File "<string>", line 1
    /usr/bin/python /Users/pascal/pascal1003-iic2233-2021-1/Tareas/T0/menus.py
    ^
SyntaxError: invalid syntax

**Comment by tqmbanados** [comment]
Hola! Lo primero es entender qué es una SyntaxError, como dice el nombre, un error de sintaxis al escribir código. Esto puede ser indentación equivocada, no escribir ":" cuando es apropiado, cosas así. Entonces te recomiendo partir por ahí, quizás te falta un espacio, suele ser algo chico. 
Lo segundo es que sería ideal que pegues un pantallazo del error, pues así es más fácil de interpretar.
Tercero, y esto relacionado a lo anterior, hay cosas que confunden un poco, pero parecen darme una idea de donde podría estar el error. 
Me refiero a que el error se encuentra *dentro* de la línea ```x=str(input())```, algo que no debería ocurrir normalmente pues solamente contiene funciones de python (que no presentan SyntaxError). Por lo que viene después, creo que ese ```input()``` está abriendo un archivo para conseguir el valor solicitado, y en ese archivo se encuentra el error. Hay varias cosas raras ahí, ```pues input()``` no debería conseguir información de un archivo al menos que se configure para eso,. Además, el archivo no tiene nombre (```File ""```) ni path, lo que también es sospechoso. Por último, el error cita una vez más el path de ```menu.py```, por lo que de alguna forma, ```conversaciones.py``` está llamando a ```menu.py``` lo que genera errores de recursion.
*Finalmente*, si el módulo importado tiene una línea con ```input()``` que no es parte de una definición, al importar el módulo el usuario deberá introducir input de teclado. Es posible que tu IDE se haga cargo de eso con un archivo "por defecto" para introducir el input, pero lo encuentro poco probable. De todas maneras, no te recomiendo hacerlo, pues hace más difícil entender el flujo de tu programa.
Espero haberte ayudado, si no logras encontrar el error, escríbeme con más detalles de lo que hace tu código, y ojalá un pantallazo.

**Comment by pascal1003** [comment]
Realice un par de cambios pero me sigue apareciendo este error
![Captura de pantalla 2021-03-28 a las 5 09 50 p m](https://user-images.githubusercontent.com/80788210/112769529-fc72ad00-8ff7-11eb-99b1-a5e6ba31b8cd.png)

**Comment by pascal1003** [comment]
Creo que encontré el problema: Si es que tengo un archivo **"A.py"** el cual tiene una función **"a(parámetros)"** la cual retorna a una función **"b(parámetros)"** contenida en el archivo **"B.py"** y esta función **"b(parámetros)"** retorna a su vez a la función **"a(parámetros)"**.
El problema que me ocurre es que si importo **"b(parámetros)"** a **"A.py"** cuando la función **"b(parámetros)"** retorna a la función **"a(parámetros)"** el programa no me reconoce esta ultima y si trato de importar  **"a(parámetros)"** a **"B.py"** no me deja

**Comment by tqmbanados** [comment]
Claro, ese es seguramente tu problema. El ImportError puede ocurrir por muchas razones, y una de ellas es un comportamiento circular entre los módulos importados: es decir, ambas requieren de la otra para funcionar. Lo que necesitas es que uno de los módulos sea completamente independiente de la otra, y te va a resultar.
tip 1: en el pantallazo ví que tienes una línea así: ```import conversacion_priv,conversacion_grupo``` acuérdate que en PEP8 debería ir un espacio luego de cada coma. 
tip 2: Funciones que retornan otras funciones es materia bastante avanzada! Si bien te felicito por usarlo y acostumbrarte al tiro a esas cosas, no es necesario para esta tarea.
