### ISSUE TITLE
Actualizar Archivos

### ISSUE THREAD

**Issue by maggiemunoz** [IIC2233/syllabus#71]
hola! cuando quiero agregar un dato a un archivo (por ejemplo registrar un nuevo usuario) se me borra toda la info del archivo usuarios.csv y no se como agregar algo sin afectar todo lo que está antes

**Comment by MatiasDuhalde** [comment]
Hola!

Cuando abres un archivo con la función `open(filename, mode)`, además de pasarle el nombre del archivo que vas a trabajar, puedes pasarle como argumento el "modo" en que quieres abrir el archivo. Los modos más comunes (y los que usaremos en el curso) son los siguientes:
- `"r"`: Te permite abrir los archivos en modo lectura, donde solo podrás leer la información contenida.
- `"w"`: Este "reinicia" el archivo (borra todos los contenidos), y te permite escribir nuevas lineas. Probablemente esto sea lo que estés haciendo en tu programa.
- `"a"`: Este te permite añadir líneas al final del archivo, sin cambiar las que ya están escritas. Este modo te puede servir!

_tip: recuerda que al crear un usuario tienes que revisar que este no exista, por lo que también deberías revisar el archivo en modo "r"_

Ojalá esto te ayude en tu tarea!

**Comment by maggiemunoz** [comment]
yaa buenisimo, me resultó, y hay alguna forma de reescribir una sola linea? (que no sea la del final)

**Comment by MatiasDuhalde** [comment]
Que bueno que te sirvió!

No existe una manera directa de cambiar solamente una línea. Una forma de hacerlo sería extraer las líneas del archivo usando el modo `"r"` y trabajar las líneas como si fueran una lista, y después abrir el archivo en modo "w" y reescribir los contenidos ya editados.

Salu2
