### ISSUE TITLE
Forma de mostrar validación de reglas

### ISSUE THREAD

**Issue by GuilleStanke** [IIC2233/Syllabus#71]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/21)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/20)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

En la acción [2] validar tablero, y [3] Revisar solución: se supone que se debe "notificar por consola" o "entregar una respuesta" de si las reglas correspondientes se cumplen o no.... Esto lo hago imprimiendo algo como "El tablero no es válido\nNo se cumple la regla X \n No se cumple la regla Y" o "El tablero cumple las reglas X e Y"??

**Comment by Arielmanriquez** [comment]
Hola, El enunciado no pide que se muestre que reglas se cumplen o se rompan, solo si es válido o no, pero no hay problema con que lo muestres asi que queda a tu criterio como mostrar el resultado.
Saludos :*)
