### ISSUE TITLE
Error en test_tablero_limpiar.py

### ISSUE THREAD

**Issue by martina-abello** [IIC2233/Syllabus#71]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

En el caso test_10x10_lleno, en la última celda de la quinta fila del tablero "correcto", hay un "PP" siendo que el tablero debería estar "limpio".

**Comment by Mcroquevielle** [comment]
Hola!! Efectivamente hay un error en ese test, el "PP" no debería ir ahí

**Comment by bgonzp** [comment]
Entonces es normal que tenga un fail en ese test? o ya esta arreglado?

**Comment by Mcroquevielle** [comment]
Hola!! Ya lo arreglaron, así que si actualizaste la versión debería estar bien. Si no, puedes sacarlo a mano y probarlo ahí
