### ISSUE TITLE
Problema al importar dcciudad

### ISSUE THREAD

**Issue by Chiseth** [IIC2233/Syllabus#71]
Desde ayer q llevo intentando solucionar un problema con la importacion de dcciudad.pyc, cree un folder para trabajar por lo que todos los archivos estan en la misma carpeta, sin embargo al parecer tengo un problema con el visualizador del archivo, lo que no me permite probar los test publicos para ir avanzando con la tarea ya que al tratar de correr algun test publico me dice "ModuleNotFoundError: No module named 'red'" y sipongo que debe ser por el problema de la importacion de dcciudad ya que no tengo nada de codigo escrito que no sea lo que ya venia con la tarea y aun asi no funciona :c
![PROBLEMA](https://github.com/IIC2233/Syllabus/assets/156480987/98e4583e-7a52-4acf-8f23-20abb380137d)

**Comment by Pablo-Gonzalez-Calderon** [comment]
Holaaa ✨

Varias personas han preguntado respecto al tema de dcciudad.pyc, por lo que te recomendaría fuertemente leer la siguiente Issue 
- #22 
  - (Se explica por qué sale en amarillo el import y por qué no puedes abrirlo con VSCode; y también qué hacer si te llegase a salir un error "ImportError: bad magic number in 'dcciudad': b'\xa7\r\r\n'")

Por su parte, respecto al error en el `import red`, te recomiendo leer las siguientes issues donde se detalla cómo ejecutar los _test_cases_ (de forma resumida, python no encuentra tu archivo red.py, por lo que debes cambiar el directorio en el que estás ejecutando tu tarea, de tal forma de que sea accesible):
- #24 
- #27 (donde se hace referencia a la Issue 24, igualmente)

Espero haber podido responder tu duda 🍀🫡

**Comment by Chiseth** [comment]
no entiendo muy bien como funciona el menu, ya que en la consola correran el programa por ejemplo así “python3.11 main.py plano_1 cobreloa” y no se como se supone que mi programa lea justo el archivo que le pasarán. 
Ya que necesito que mi programa abra un archivo de texto de esos contenidos en la carpeta data, pero o sabre especificamente cual será hasta que lo diga en la consola, por lo que o entiendo como hacer esa relacion consola-vscode para que pueda leer los archivos : c
