### ISSUE TITLE
Ayudante como persona

### ISSUE THREAD

**Issue by JoseAvanzada2019** [IIC2233/syllabus#71]
En el enunciado te dicen que ayudante es persona pero, en términos prácticos, sólo me importa su IQ. ¿Puedo no modelarlo como persona?

**Comment by roberto009** [comment]
Hola! 
La modelación del programa está a tu criterio, nosotros no ~~queremos 😈~~ podemos decirte que es lo mejor. 
Sin embargo, esta tiene que ser consistente con el enunciado.
Éxito en tu tarea!
