### ISSUE TITLE
Problema en acceso a repositorio personal

### ISSUE THREAD

**Issue by camirojasguajardo** [IIC2233/syllabus#71]
Hola!
Rellené el formulario y creo que mi repositorio está creado, pero no puede verlo y, por tanto, no puedo clonarlo:( 
No me llegó ningún link de invitación a mi correo tampoco. ¿Qué puedo hacer?

Saludos.

**Comment by Juampisaez** [comment]
Hola @camirojasguajardo 
Puedes mandar un mail a iic2233@ing.uc.cl comentando tu usuario de github y que te manden la invitacion para tu repo
