### ISSUE TITLE
mayoría de edad y currency

### ISSUE THREAD

**Issue by rihanuch** [IIC2233/Syllabus#71]
el enunciado dice que "Todos los usuarios nuevos que cumplan con la mayor ́ıa de edad reciben una cantidad inicial de 100.000 DCC, y tambi ́en 50.000 de las monedas respectivas (i.e. las dos divisas que componen un mercado) cuando se ingresa a un mercado espec ́ıfico, obsequio de parte de Nebil, el magnate benevolente." 

en la practica es lo mismo crear el usuario nuevo con la cantidad especificada y darle las currencies de cada mercado al acceder a el. 

Puede entregarse las currencies al momento de crear el usuario? 😬

**Comment by nmaturana97** [comment]
yo lo veo como que solamente si son mayores de edad al momento de crear el usuario les dan los 100000 DCC, si son menores no, y al momento de registrarse a en mercado les dan 50000 de cada divisa, sea cual sea.

**Comment by nachocontreras** [comment]
yo puse tambien que si cumplian 18 se les daba 100000 DCC

**Comment by Arcoirisky** [comment]
Lo que dice @nmaturana97  se acerca bastante. Si un usuario mayor de edad (sin importar si los cumplió inscrito o se crea un usuario nuevo como mayor de edad) entra en un mercado X por primera vez, se le dará este regalo de Nebil. ¿Se entiende? Todos los mayores de edad reciben el regalo **al entrar en un mercado nuevo** por primera vez.

Espero haberme dado a entender bien :sweat_smile:
