### ISSUE TITLE
Duda con medidas "ancho", "largo" y ejes a los que refieren

### ISSUE THREAD

**Issue by ignacio-agreda** [IIC2233/syllabus#71]
Según enunciado, "_N_" es **largo** y "_M_" es **ancho**... pero, sólo por confirmar, ¿a qué eje hacen referencias las medidas? es decir, ¿el **largo** es respecto al **eje "y" (vertical)** y el **ancho** respecto **al eje "x" (horizontal)**? ¿o al revés?

**Comment by jeschuwirth** [comment]
Hola!

Revisé el enunciado para asegurarme de que no estuviera explicito y efectivamente no se explica con mucho detalle, por esta razón queda a criterio tuyo como lo haces, desde mi punto de vista es lo siguiente:
 
- **largo** respecto al eje Y

-  **ancho** respecto al eje X

Pero como no queda claro del enunciado puedes hacerlo como quieras, te recomiendo explicar en el readme cual alternativa tomaste  y porqué para evitar cualquier problema.

Suerte en la tarea!

**Comment by ignacio-agreda** [comment]
¡Muchas gracias!
