### ISSUE TITLE
Duda importacion utils

### ISSUE THREAD

**Issue by juanriveraf** [IIC2233/Syllabus#71]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [ X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Estaba intentando importar utils y me sale que no se ha podido resolver la importación. Note que en el enunciado de la tarea sale que utils solo sirve para 3.11.x con x **mayor** que 7, pero en la presentación de la introducción del curso sale que la versión que podemos utilizar de python es 3.11.x con x **mayor o igual** a 7. Como yo estoy con la versión 3.11.7 quería confirmar que ese no sea el problema. Muchas gracias! Había una issue que tenia una pregunta parecida a la mía, pero estaba resuelta, entonces tuve que crear una nueva.

**Comment by juanriveraf** [comment]
Hola. Ahí lo probé y si me funciona. Lo unico que ocurre es que sale que no se importa bien, pero después funciona. Nose si eso es un problema o no. Adjunto la foto de lo que aparece ![image](https://github.com/user-attachments/assets/fd1fd635-45f5-4053-98c6-57a82344782d)
Lo único que sale es esa línea amarilla, y sale que no se puede resolver la importación utils.

**Comment by vgalfaro** [comment]
Es normal, no debería haber problema, como bien notaste, funciona al correrlo en la terminal, saludos!
