### ISSUE TITLE
Duda con código de "4-polimorfismo"

### ISSUE THREAD

**Issue by Dieguu21** [IIC2233/Syllabus#71]
### Prerrequisitos

* [x] Leí las reglas del foro
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido
* [x] Mi duda no se trata de un tema administrativo o personal
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola, me surgió una duda en el contenido de la semana 2: "4-polimorfismo".
Específicamente en este código:
```python
import math

class Vector: 
    """Vector desde el origen"""
    
    def __init__(self, x, y): 
        self.x = x 
        self.y = y
        
    @property
    def magnitud(self):
        return math.sqrt(self.x ** 2 + self.y ** 2)
    
    def __lt__(self, otro_punto):
        return self.magnitud < otro_punto.magnitud

v1 = Vector(2,4)
v2 = Vector(8,3)
print(v1 < v2)
```
**¿Por qué se le asignó como `property` a magnitud?**
Me confunde un poco porque pensé que se le ponía `@property` a un atributo de instancia que ya existía y era "privado", que es lo que se puede ver en "2-properties".

**Comment by tqmbanados** [comment]
Hola @Dieguu21! Como bien dices, uno de los usos más comunes de las properties es para trabajar con atributos privados. Sin embargo, tienen muchos más usos!

En este caso, por ejemplo, definimos una property que se comporta como un atributo cuyo valor existe **en función de otros atributos**. Esto puede servirnos para muchas cosas, dado que especialmente en la matemática, hay muchos conceptos donde un atributo depende de otros. La verdad yo no sé tanta tanta matemática, pero un ejemplo muy básico podría ser la altura de un triángulo.

Pero hay muchos usos más, y en verdad estos se acaban únicamente con la imaginación. Otra cosa que puede resultar super útil de las properties, es que permite que ejecutes código *cada vez que cambie un atributo*. Por ejemplo, podrías ejecutar un `print` que informa que se cambió el valor. 

( Lo de arriba quizás no parece tan útil, pero más adelante, cuando veamos eventos y señales, puede servirnos mucho para enviar una señal automáticamente cada vez que modificamos un valor )
