### ISSUE TITLE
actualización de cambios

### ISSUE THREAD

**Issue by movaldivia** [IIC2233/Syllabus#710]
En el enunciado sale que "actualización de cambios" es un elemento, que lo entiendo como un botón para enviar las modificaciones al servidor, pero dice el enunciado, también, que los cambios son a tiempo real. No me queda muy claro.

**Comment by iqacevedo** [comment]
Hola,

Los cambios deben ser enviados en tiempo real. **No** debe haber un botón que envíe las modificaciones, todo debe ser automático mientras se edita.

Saludos !
