### ISSUE TITLE
Condicionar conexión cliente-servidor

### ISSUE THREAD

**Issue by llloyola** [IIC2233/Syllabus#710]
Puedo hacer que el cliente primero defina su nombre de usuario para poder conectarse al servidor? Me explico... Mi plan es que La _Ventana de inicio_ de Prograband comience con:
- las opciones de editar, descargar y crear inhabilitadas
- las listas de canciones listas y canciones en edición vacías

Hasta que el usuario defina un nombre de usuario (que sea válido). Recién cuando defina un nombre de usuario podrá conectarse al servidor de Prograband, habilitando las opciones mencionadas y rellenando las listas anteriormente dichas.

Puedo hacer esto?

**Comment by Hernan4444** [comment]
Hola, no es posible hacer eso, puesto que en el enunciado no se condiciona el tener un nombre de usuario válido para recién observar la lista de canciones. Solo cuando se quiere editar una canción, descargar, crear o ver una en modo espectador, se debe verificar el usuario. Sin verificar mi usuario, igual puedo saber que cosas hay (considera que es un modo visitante)
