### ISSUE TITLE
problema al unir los dos modulos flask

### ISSUE THREAD

**Issue by rjdelrio** [IIC2233/Syllabus#710]
lo que pasa es que tengo dos modulos flask el que escucha de github y el que escucha de telegram y para que ambos puedan escucha al mismo tiempo los puse en dos thread distintos en un main, el problema es que con 1 solo ngrok corriendo no me deja hacer esto por que no me deja usar un tunel para escuchar a las dos partes al mismo tiempo entonces tuve que abrir otro ngrok, queria saber si estoi muy perdido o esta bien y si esta bn queria saber si tendre este problema con heroku, ojala se entienda mi pregunta

**Comment by MainScientist** [comment]
La verdad es que sí estás algo fuera del camino correcto. La forma correcta de hacer esto no es generar dos aplicaciones distintas. Lo que tienes que ahcer es generar **dos rutas** distintas dentro de tu aplicación. Cada una de estas rutas debería idealmente hacer llamados a otros módulos que son los encargados de procesar la logica de telegram y github por separado. Si no quedó claro me dices.

**Comment by rjdelrio** [comment]
con rutas te refieres a puertos? por ejemplo un flask.Flask(__name__).run(port=8080) y hacer luego otro pero flask.Flask(__name__).run(port=8081) eso? a eso te referias?

**Comment by KnowYourpotato** [comment]
@rjdelrio  Cuando tu haces flask.run creas un nuevo servidor, y como cualquier servidor este servidor tiene rutas.

Supongamos que tu servidor es https://potato.cl
Por default, cuando hagas run tu página no va a tener niuna ruta, pero cuando definas una función con el decorador app de la forma: `@app.route("/nombre_ruta")` ahora tu página pasara a tener una ruta llamada https://potato.cl/nombre_ruta.

Cual es la gracia de esto? que cuando tu haces webhook con cualquier API tu le pasas la ruta de tu server, es decir que cuando tu hagas webhook con telegram y le pases la ruta "https://potato.cl/nombre_ruta" telegram intentará enviar la información a esa ruta, que esta definida en tu código. 

Lo que dicen @MainScientist  entonces es que tu server tenga dos rutas, por ejemplo:

`@app.route("/potato1")` y `@app.route("/potato2")` de manera que tengas dos lugares separados donde tratar los mensajes que te llegaran de telegram y github.

En resumen solo necesitas **un** servidor, y dentro de este servidor dos rutas.
