### ISSUE TITLE
Duda con tipos de archivos a utilizar en la T02

### ISSUE THREAD

**Issue by ngsuarez** [IIC2233/syllabus#710]
* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/327)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/326)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

En el enunciado sale en la sección **12. Restricciones y alcances** que el programa debe estar compuesto sólo de uno o múltiples archivos ```.py```. Entonces, **¿nuestras interfaces no pueden ser cargadas a través de un archivo ```.ui```?**

**Comment by furcelay** [comment]
Hola!
Esa parte del enunciado se refiere al programa en sí y no a archivos de "soporte", básicamente quiere decir que los archivos que sean de la parte en Python deben tener el formato `.py` y no otro, y no pueden haber partes de tu programa en otros lenguajes de programación. 

Puedes usar los archivos `.ui` para cargar la interfaz!

Saludos!
