### ISSUE TITLE
Uso de archivos .pyw

### ISSUE THREAD

**Issue by benjavicente** [IIC2233/syllabus#710]
Al ejecutar un programa de interfaz gráfica en archivos `.py` desde el explorador de archivos se abre una consola y el interfaz. Ahora, como el programa solo necesita el interfaz gráfica, sería bueno ocultar la consola.

Encontré que **cambiando la extensión del archivo de `.py` a `.pyw`** permite esto.
¿Se puede usar en el curso?

- [stackoverflow: _.pyw files in python program_](https://stackoverflow.com/a/34739687)
- [python docs: _Executable Python Scripts_](https://docs.python.org/3.7/tutorial/appendix.html?highlight=pyw#executable-python-scripts)

**Comment by jbulness** [comment]
Hola @benjavicente,

Sigue trabajando con el archivo .py, ya que, de hecho, es mejor que se muestre la consola, dado que sirve para ver el resultado de los prints que se puedan usar para ver el estado de las entidades, es decir, para corroborar el comportamiento de estas durante la ejecución de tu código.

**Comment by benjavicente** [comment]
Hola, el titulo de mi issue fue cambiado de modo que no queda claro el problema de este, lo que dificulta encontrar cómo ocultar la consola en el compilado  😕

**Comment by lily416** [comment]
Hola @benjavicente,

En general tratamos de que los títulos de las issues sean lo más descriptivos posibles, para así facilitar su búsqueda y evitar las issues duplicadas. 

Si bien tu título era descriptivo en cuanto a no mostrar la consola al momento de ejecutar el programa, la issue se enfoca más en si esta permitido o no el uso de archivos `.pyw`. 

Espero que entiendas y no lo tomes como algo malo.
Saludos y éxito con la tarea 👋🍰
