### ISSUE TITLE
Cálculo de CRC

### ISSUE THREAD

**Issue by JPSF** [IIC2233/Syllabus#711]
Hola, leyendo el enunciado no me queda claro cómo se realiza este cálculo 
1.¿Qué se le debe entregar como argumento al método crc32? 
2. ¿Qué significado tiene el valor que retorna el método?

**Comment by MarceloSaldias** [comment]
@JPSF No se si has revisado la documentacion de la libreria, pero creo que ahi explican lo que preguntas.

Planteo otra duda con respecto a la redaccion de la parte de **CRC** en 5.1:
> El CRC se calcula con todos los bytes del bloque respectivo, __sin contar con la seccion de largo, a excepcion de los bytes de los bytes correspondientes al largo__.

Entendi que los 4 primeros bytes que corresponden al largo del chunk no son incluidos en el calculo del CRC, es esto correcto? Creo que es un poco rara la redaccion de esa oracion :c

**Comment by JPSF** [comment]
Por lo mismo estoy confundido

**Comment by Hernan4444** [comment]
@MarceloSaldias @JPSF el crc se calcula tal como indica Marcelo. los **4 primeros bytes que corresponden al largo del chunk no son incluidos **, el resto si.
Saludos ✌️

**Comment by JPSF** [comment]
Para el chunk IDAT 
¿ El CRC se calcula considerando el largo de la información comprimida o descomprimida?
En ambos casos al abrir la imagen png que creé no logra mostrarla porque dice que hay un error en el CRC de IDAT. No se que estoy haciendo mal

**Comment by Hernan4444** [comment]
@JPSF es el largo de la información comprimida (compress con nivel 9). 
¿Que estás considerando en el CRC?

**Comment by JPSF** [comment]
Para obtener el crc del IDAT ingreso al método zlib crc32  un arreglo con los bytes correspondientes al tipo de chunk(IDAT en este caso) y los que corresponden a la información del chunk.
Finalmente creo el IDAT con el largo,tipo,información comprimida y CRC recién calculado
