### ISSUE TITLE
Recursos comunes cliente-servidor

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#711]
Hola
¿Si mi cliente y servidor tendrán algunos recursos que les sean comunes debo poner una copia en cada carpeta o puedo ponerlo en algún lado desde el que ambos tengan acceso?

Sí, literalmente estoy en este caso con un built-in de los bytearrays.

**Comment by Hernan4444** [comment]
Tendrás que hacer una copia por carpeta, piensa siempre que esta tarea la podemos probar con dos pc donde uno solo tenga el servidor y el otro solo el cliente. 

Saludos :v:
