### ISSUE TITLE
Insertar Imagenes de QTDesigner

### ISSUE THREAD

**Issue by enriquemolinare** [IIC2233/syllabus#711]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/327)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/326)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
***¿Cómo puedo cargar imagenes en Qtdesigner con el objetivo que se despleguen en la ventana***

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by JadrinaDA** [comment]
Hola! 
Primero abres tu ventana en Qtdesigner, luego debes buscar en la parte izquierda donde dice Display Widgets. 
![image](https://user-images.githubusercontent.com/62019640/96449258-f546a800-11ea-11eb-8ba4-332184bfed38.png)
Ahí haz click en label y arrastraló a tu ventana. Una vez que tengas tu label, haz click sobre él otra vez  y ve a sus properties en la parte derecha (Property Editor). Baja hasta donde dice QLabel y busca el campo que dice pixmap.
![image](https://user-images.githubusercontent.com/62019640/96449241-f081f400-11ea-11eb-9a4e-d35c07ef5e30.png)
 Ahora solo tienes que cargar tu sprite. Te recomiendo que hagas check a scaled contents también. Haz click sobre el triángulo invertido y pon choose file. Ahí elige el archivo del sprite que desees y listo! 
![image](https://user-images.githubusercontent.com/62019640/96449192-e233d800-11ea-11eb-993c-768bc50c5847.png)

**Comment by enriquemolinare** [comment]
ok, muchas graciaaas!!
