### ISSUE TITLE
Parámetros del mapa

### ISSUE THREAD

**Issue by RenatoVWS** [IIC2233/syllabus#711]
Hola, tengo una pregunta sobre los parámetros LARGO_MAPA y ANCHO_MAPA. Cuando uno los cambia ¿Qué implica, que cambie el tamaño de la imagen "mapa.png" o que cambie por ejemplo el área por donde se puede mover el personaje? Tengo esa duda porque se me está complicando un poco definir esas áreas.

Saludos :)

**Comment by tomasgv** [comment]
Hola @RenatoVWS !

Esos parámetros definen ambos, el tamaño de la representación visual del mapa y también el área por donde se puede mover el personaje, de modo que colisione con sus bordes. Sin embargo, no te preocupes por eventuales cambios, ya que esas dimensiones **no serán modificadas** durante la corrección. Esto es para que no tengas que preocuparte por posibles problemas de visualización.

Saludos! :coffee:
