### ISSUE TITLE
Formato encoding: envío y recepción de datos 

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#712]
Hola,
Tanto en la ayudantía como en el material de la semana usan siempre el encoding "ascii", pero si quiero implementar el chat, nombres con tildes o lo que sea, el servidor se va a negro y el cliente se cae (ya lo probé), entonces necesito el UTF8.

¿Es mala idea usar utf8 en vez de ascii? Me refiero tanto para la tarea como para la vida.

Duda extra de material:
Si se cae mi servidor o cliente, los puertos quedan abiertos o cerrados?
Tengo alguna forma de pedir una lista de servidores/clientes a los que esté conectado?
o una lista de servidores/clientes en mi red local?

**Comment by rihanuch** [comment]
¡Hola @jmwielandt !

No, no es para nada mala idea, se puede hacer de la manera que más te acomode entre ```ASCII``` y ```UTF8```, simplemente se utilizan para cosas diferentes. En lo personal prefiero el segundo porque da mayor flexibilidad 😄

Cuando se te cae el servidor _local_, el puerto que seleccionaste queda abierto temporalmente. Respecto a cómo saber cuales puertos están abiertos, puedes ver [este link](https://www.speedguide.net/faq/how-to-find-listening-open-ports-on-my-computer-115), mientras que para ver todas las conexiones de tu pc con internet si usas Windows puedes usar el comando ```netstat -a```, tal como se especifica [acá](https://superuser.com/questions/11207/how-can-i-see-all-active-connections) 💻 .

¡Saludos! 🍀
