### ISSUE TITLE
Importar desde una carpeta anterior

### ISSUE THREAD

**Issue by Lord-Kelsier** [IIC2233/syllabus#712]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola, mi duda es respecto a si tenemos un directorio de esta forma:

```python
parametros.py
backend/ 
     main.py
spirites/
     foto.png
```
**¿cual es la sentencia para el ``import`` si quiero importar `parametros.py` y `foto.png` en `main.py`?**.  Viendo el codigo de la AF03 solo colocaron ``import parametros as p``, se que eso funciono porque la tarea no me arrojo ningun error, pero si ejecuto ese archivo VScode me arroja que la variable `parametros` no esta definida.

**Comment by YehudaGurovich** [comment]
Hola @Lord-Kelsier. https://stackoverflow.com/questions/1054271/how-to-import-a-python-class-that-is-in-a-directory-above Puede ser que te sirva.

**Comment by margavicunas** [comment]
Hola! Me fijé que en la AF03 agregaron archivos __init__.py en las carpetas y buscando en internet leí que fue eso lo que les permitió acceder a parámetros.py (afuera) desde las carpetas. Intenté hacer lo mismo pero no me funcionó y no he podido encontrar la solución en internet :( ¿Hicieron algún paso extra?

De antemano muchas gracias! :sunflower:

**Comment by aaossa** [comment]
Hola @margavicunas y @Lord-Kelsier ,

Lo que ocurre es que al ejecutar un archivo, Python intenta importar los módulos desde el archivo ejecutado. La mejor forma de trabajar con esto es pensando: ¿desde dónde quiero/espero que ejecuten mis archivos?

En el caso de la AF03, hay un `main.py` que es el archivo a ejecutar. Si ejecutan ese archivo no verán excepciones o problemas de importación, pero sí ocurre al ejecutar el archivo desde el interior de la carpeta. Esto es porque Python trabaja las rutas en relación al archivo ejecutado. Hay contenidos relacionados a esto en la semana 0 (en particular modularización y *paths*), pero no responden directamente esta duda así que intentaré responderla de una manera detallada.

Como dije, Python trabaja en relación al archivo que esperas que se ejecute, por lo que es bueno darle a ese archivo un buen lugar para acceder a todas las carpetas y archivos relevantes. Movamos `main.py` a un mejor lugar:

```
main.py
parametros.py
backend/ 
     __init__.py
     logica.py
sprites/
     foto.png
```

Ahora `main.py` puede "ver" directamente la carpeta de *sprites*, el *back-end* y `parametros.py`. ¿Y qué pasa si es que quremos usar un parámetro desde `logica.py`? Bueno, hay dos maneras:

```python
# logica.py - Opción 1
import parametros
def funcion():
    print(parametros.MENSAJE_IMPORTANTE)


# main.py
from backend.logica import funcion
funcion()
```

```python
# logica.py - Opción 2
def funcion(mensaje):
    print(mensaje)


# main.py
import parametros
from backend.logica import funcion
funcion(parametros.MENSAJE_IMPORTANTE)
```

###### (Ignoré PEP8 para priorizar la explicación, pero hay que dejar 2 líneas en blanco después de importar 👀 )

En la primera opción, importamos `parametros.py` normalmente. Esto no va a funcionar cuando se ejecute `logica.py` desde la carpeta, porque no hay un `parametros.py` junto al archivo, pero sí va a funcionar cuando se importe desde `main.py`, porque esa será la ruta relativa desde la que Python buscará los demás módulos (y `main.py` está junto a `parametros.py`).

En cuanto a la AF03, no hicimos nada especial. De hecho, hicimos lo de la "opción 1". Los archivos `__init__.py` se utilizan para declarar que los archivos en esa carpeta se tratan como un módulo en sí, entonces podemos importar las cosas como `from carpeta.archivo import Clase`. Creo que no tenemos un contenido al respecto, porque puede ser algo avanzado, pero me parece que podríamos intentar explicarlo a futuro 🤔 

Si algo no se entiende o no les funciona, pregunten por acá mismo 👌 ¡Éxito con sus tareas!

**Comment by Lord-Kelsier** [comment]
Hola, revisando el link de @YehudaGurovich  encontré una solución.

### Solucion

```python
import os
import os.path
sys.path.append(
    os.path.abspath(os.path.join(os.path.dirname(__file__), os.path.pardir)))
```
En particular la respuesta fue de [ aqui]( https://stackoverflow.com/a/1054293/14142662). Si escribes esto ya podras hacer el `import`, pero   esto, al menos yo, lo use solo para probar el código pues a la hora de ejecutarlo en el `main.py` del ejemplo de @aaossa esto no genera problemas

**Comment by aaossa** [comment]
Solo para complementar, me atrevería a decir que no es una muy buena práctica el modificar los archivos disponibles para importar de esa manera (estamos modificando la ruta desde la que se pueden importar archivos). El mecanismo de importación de Python permite importar lo que se necesite si es que se usa una estructura de archivos y carpetas apropiadas, a través del uso de `import` ✨ En general, si un código se ve complicado o no se entiende bien es porque: (1) hay una mejor manera de hacerlo, o (2) estamos frente a una mala práctica, y ahí es cuando es importante buscar y preguntar, así que muy bien todes por haberlo hecho 🤩. Lo que hace el código anterior no es intuitivo, por lo que debe haber una mejor manera de hacerlo: usando `import` 📦 . 

Python es un lenguaje bastante completo y eso permite hacer muchas cosas, pero el poder hacer muchas cosas no significa que todas sean correctas o que todas se deban hacer 😅 ("Un gran poder, conlleva una gran responsabilidad." - Tío Ben a les alumnes de Progra Avanzada)
