### ISSUE TITLE
Webhook Telegram y heroku

### ISSUE THREAD

**Issue by egromero** [IIC2233/Syllabus#712]
Como puedo saber que telegram en verdad está haciendo post a mi servidor? he intentado un millon de formas y siempre me sale al ingresar a mi link de heroku "Internal server error" la verdad es que igual estoy medio confundido con el funcionamiento de los webhooks y el codigo flask, ya lo setié a la url con el request a la api, y me salió correcto. Si me pudieran orientar por favor (pd: ya leí la #657 y me ayudó, pero aun sigo desorientado)

**Comment by akaminetzkyp** [comment]
Si tratas de entrar a tu `url` desde un browser te funciona?

**Comment by egromero** [comment]
Entro a la url y antes me salía "Internal server error" ahora lo modifiqué y me aparece "Method Not Allowed", estoy tratando de recibir los datos del webhook de github ahora y sale eso

**Comment by akaminetzkyp** [comment]
Hasta donde yo se, si dentro del decorador `@app.route...` pusiste `methods=['POST']`, está bien que no te permita realizar un `get`. Lo bueno es que sabes que tu servidor está corriendo.

Lo que hice para confirmar que llegaban los `post` de Telegram y Github fue poner un simple print en mi programa y después revisar los logs con el comando `heroku logs`.

**Comment by Okhan97** [comment]
@akaminetzkyp a que cosa le hiciste print exactamente ?

**Comment by akaminetzkyp** [comment]
Hice varios prints, pero el más útil fue `flask.request.get_json()`, ya que este método retorna la información recibida por el `post`.
