### ISSUE TITLE
Duda general sobre menús

### ISSUE THREAD

**Issue by Gjescalante** [IIC2233/syllabus#712]
Hola! escribo para preguntar por directrices adecuadas para los menús, en la T01 me complicó mucho trabajar los menús como clases porque no supe definir bien las opciones de escoger otro menú, o de volver atrás. 
Mi estrategia en la tarea 0 era algo parecido a esto (que dada la complejidad de la tarea me funcionó bien):
![image](https://user-images.githubusercontent.com/48481711/82245990-eee99280-9911-11ea-92c7-b96df9fb02a1.png)

Esto no me fue muy útil en la T01 por la cantidad de opciones y las variables que había que ir guardando, por ejemplo si obtenía la clase magizoologo en el menú 1, tenía que pasársela a todos los siguientes menús, y era muy caótico.

Mi enfoque en la tarea 1 fue hacer los menús más parecidos a funciones, que retornaran los objetos que necesitaba, pero tenía el mismo problema con los datos que había que ir guardando, algo como: 

![image](https://user-images.githubusercontent.com/48481711/82246278-5dc6eb80-9912-11ea-845f-a7b27b2b9d77.png)

Agradecería mucho cualquier pista o tip <3

**Comment by bvasquezm** [comment]
Hola @Gjescalante! 

En general no hay una única forma para trabajar con menús, en esta tarea de hecho no es de los objetivos más importantes, pero aún así entiendo tu preocupación. Yo te recomiendo que si estás complicado con el traspaso de información entre menús o la extensión de tu código, acudas a usar **clases**, en particular una clase y varios métodos que correspondan a los diferentes menús (pueden ser varias clases también). Sin embargo, como te mencionaba anteriormente, el flujo de esta tarea no está pensando para moverse en base a menús, más bien estos son una herramienta más dentro de todo el funcionamiento, por lo que tendrás que acudir a ellos solo unas cuantas veces (y de manera separada).

Espero haberte ayudado con tu pregunta, sino siéntete en la libertad de decirlo. Mucha suerte!!

**Comment by Gjescalante** [comment]
Gracias por el consejo, pero aún me queda la duda de cómo solucionar el volver atrás o el traspaso de variables en el caso de hacer una clase en donde sus métodos sean los distintos menús... debería pasar los datos a utilizar a todos los menus? Yo creo que a eso va mi duda, si es posible hacer una variable global que sea usada por todos los menús sin tener que pasarla como argumento cada vez que llamo a un menú o vuelvo atrás.

**Comment by bvasquezm** [comment]
Si haces uso de una clase única para todos tus menús (los menús como métodos) los atributos de dicha clase serán compartidos por todos, no tienes necesidad de pasarlos como argumentos. No tienes que definir variables globales. Atributos de ejemplo: `self.nombre_usuario
 self.edad
 self.mascotas
`
Al ser una clase para todos, puedes **llamarlos y actualizarlos desde cualquier menú**. Espero haberte aclarado mejor tu duda!

**Comment by Gjescalante** [comment]
Sii, muchas gracias <3
