### ISSUE TITLE
edición

### ISSUE THREAD

**Issue by movaldivia** [IIC2233/Syllabus#712]
Para cualquier edición deberías crear un botón? Es decir, como sabremos de que forma quiere editar el cliente?
En el balde el usuario de que forma elige el color?

**Comment by fnquinteros** [comment]
Eso queda a tu criterio. puedes mostrar una paleta con colores donde hace click y selecciona ese color, o seleccionarlo de una lista, etc... La idea no es que se queden pegados en la interfaz. Saludos!
