### ISSUE TITLE
Git no clona mi repo privado en mi compu nuevo

### ISSUE THREAD

**Issue by cegalleta** [IIC2233/syllabus#712]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

Hola!

Bueno, el título lo dice todo. No lanza error, sólo se queda cargando indefinidamente el repo. Borré los archivos pesados de la T2 entonces no debería tener problema para descargarlo, sin embargo, no lo hace uwu. 

Para settear el usuario y la contraseña usé lo de siempre:

git config --global user.name "cegalleta"

y lo mismo para la contraseña jeje

Les agradezco mucho la ayuda.

**Comment by aljara97** [comment]
Hola @cegalleta, de casualidad configuraste tu email? Te recomiendo usar el comando `git config user.email`, para probar si está configurado

**Comment by cegalleta** [comment]
> Hola @cegalleta, de casualidad configuraste tu email? Te recomiendo usar el comando `git config user.email`, para probar si está configurado

Hola!!

Había hecho eso desde la terminal, pero por alguna razón las credenciales de windows no eran las mismas. Reseteé todo y escribí las cosas directamente desde git config y al final funcionó :P
