### ISSUE TITLE
tamaño imagenes

### ISSUE THREAD

**Issue by movaldivia** [IIC2233/Syllabus#713]
Las imágenes las tendremos que abrir en tamaño original? Es decir si las adaptamos se estarían perdiendo píxeles o no? sobretodo al momento de editar

**Comment by cilopez** [comment]
Nosotros te dimos las imágenes así que puedes hacerlo como quieras, pero te recomiendo llevarte por el _principio de la parsimonia_.

**Comment by movaldivia** [comment]
@cilopez 
Entonces puedo asumir que no me darán fotos mas grandes a 1280x720 y que el ayudante tendrá una pantalla de 1360x 750 o así para poner los botones entre otras cosas?

**Comment by Jiparavich** [comment]
x2
