### ISSUE TITLE
¿Donde hacer preguntas relacionadas con malas prácticas?

### ISSUE THREAD

**Issue by mt-garcia** [IIC2233/syllabus#713]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

[Tengo una duda respecto a malas prácticas y no supe dónde hacer la issue, ¿Se hace **comentando** en la issue especial de eso? Porque al estar escribiendo mi issue en como "issues de la T02" al rellenar la plantilla salía como explícitamente que mi issue no tenía que ser nada relacionado a malas prácticas, y ahí me di cuenta que no sabía donde se hacía. Voy a escribir acá mi duda por si acaso, pero me gustaría saber en un futuro bien donde la tengo que hacer. 
Mi duda en específico era relacionado con las malas prácticas de la T02: uso de variables globales. No entendí bien a qué se refería con **variables globales** en sí, y como no sé a que se refiere en sí, tampoco entiendo porqué sería una mala práctica.]

**Comment by YehudaGurovich** [comment]
Hola @mt-garcia! https://github.com/IIC2233/syllabus/issues/700 es el compilado de issues de la T02
Las variables globales son consideradas malas prácticas desde el día 1 en todo caso.
https://github.com/IIC2233/syllabus/issues/699 En esta issue se hacen todas las preguntas relacionadas a librerias y malas prácticas.
