### ISSUE TITLE
Tiempo para que un cliente coma un bocadillo

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#713]
Hola,
¿Se debe considerar algún tiempo en particular en el que el cliente se come su bocadillo? o éste se retira inmediatamente al recibirlo?

**Comment by moquezada** [comment]
Hola @Camila-sty!

Como es algo que no está explícito en el enunciado queda a tu criterio el como lo puedes hacer. Si el cliente se queda un tiempo determinado para comer su bocadillo o si se retira inmediatamente son formas válidas de implementación.

Ten en cuenta que si decides que cada cliente demore un tiempo determinado para comer su bocadillo y luego retirarse, este tiempo **debe quedar guardado como un parámetro** 👀.

Saludos y suerte en tu tarea! 👨‍🚀
