### ISSUE TITLE
Posible Inconsistencia entre valores de 5.2.1 vs 3.2.4 en notas

### ISSUE THREAD

**Issue by FJavierOss** [IIC2233/Syllabus#713]
Tengo una duda, ya que la tabla de la sección 3.2.4 sugieren que las notas en nomenclatura inglesa al menos para la octava "0" varia sus valores númericos entre 0 y 11, con "C" para 0 y "B" para 11. Si eso se lleva operaciones matemáticas dentro de la tabla es fácil asumirlo así para poder generar el numero correcto para su posterior traspaso a byte o viceversa. El tema esta en que la tabla de la sección 5.2.1 los valores númericos van desde el 1 y al 12, con "C" asociado al 1 y "B" al 12. El punto es, ¿si desde un principio se quizo así para la ventana de edición y es cuestión de nomenclatura, por lo que tendremos que llevar una operación extra o simplemente fue una casualidad de indice que debío haber iniciado desde el 0 ahorrandonos así la operación extra?

**Comment by Hernan4444** [comment]
Hola, se hizo a proposito para que no mezclen el valor en bytes y la nomenclatura usada de input en la interfaz. Más detalle aquí #702

Saludos ✌️
