### ISSUE TITLE
Confusión en el envío de datos json en networkng y serialización

### ISSUE THREAD

**Issue by mjgutierrez1** [IIC2233/Syllabus#714]
No entiendo por qué si definimos que la serialización "se refiere al procedimiento de transformar cualquier objeto en una secuencia o serie de bytes", decimos que estamos serializando objetos con json al hacer json.dumps, si en realidad estamos transformando un diccionario a un string.

Y respecto al ejemplo del cliente que envía datos json en el material de networking, la razón por la que hacemos message.encode("UTF-8"), siendo que ya habíamos "serializado" el diccionario "diction", ¿es que en realidad json.dumps no serializa, sino que transforma a string, y que por eso mismo debemos nosotros transformar ese string a bytes?

**Comment by akaminetzkyp** [comment]
Ocurre exactamente lo que tú mencionas. Cuando uno ocupa `json.dumps`, se convierte a *string*, no a *bytes*. Se utiliza `un_string.encode` para convertir el *string* a *bytes*.

Saludos!
