### ISSUE TITLE
Duda Bonus

### ISSUE THREAD

**Issue by frvalenzuela** [IIC2233/Syllabus#714]
Para buscar los bloques de código de Markdown tenemos que simplemente ver los string que esten entre las comillas: <`> ¿o hay otro criterio que revisar en el string para revisar si es un bloque en ese formato?

**Comment by KnowYourselves** [comment]
Hay dos opciones.

- Markdown de multiples lineas:

```
a
b
c
d
```

- Markdown de una linea: 

`a b c d`

En el primer caso esta encerrado por "```" y en el segundo caso es como describes.

**Comment by frvalenzuela** [comment]
Gracias por la respuesta!

**Comment by frvalenzuela** [comment]
@KnowYourselves podemos asumir que la persona que habrá las issues que ponga triple comilla cerrará siempre las comillas? porque a diferencia de los markdown de una lines `como este` se tiene que escribir ´así ´ porque `así no funciona, en cambio con triple comilla si abró sin cerrar las comillas si aparece en formato markdown.
Haré esto por ejemplo:

"```"
(TEXTO)


```
Ejemplo
sin
cerrar
comillas
---

**Comment by KnowYourselves** [comment]
Mira #731 y de todas formas creo que se puede especificar en tu README en el peor de los casos!

**Comment by frvalenzuela** [comment]
Gracias !
