### ISSUE TITLE
Ventana Dentro de otra Ventana

### ISSUE THREAD

**Issue by enriquemolinare** [IIC2233/syllabus#714]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/327)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/326)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Estoy un poco confundido a como diseñar la ventana de juego. Intuyó que la ventana de juego debe ser una ventana principal. Sin embargo,  estoy perdido si las áreas deben ser otras ventanas? De ser así, se puede agregar como widget una ventana dentro de otra ventana?

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by sjlarrain** [comment]
Hola! Estoy con una duda parecida. Construyendo la ventana del Juego, para posicionar ocupé 4 QWidget para agrupar mejor Labels y Buttons. No se si esto es bueno ya que con los ejemplos de clase siempre ocupábamos uno. Por otro lado no se como poder acceder a cada uno para asignarle una clase a cada una para definir lo que cada una necesita. 

Muchas gracias de antemano
Santiago

**Comment by JuaniAndres** [comment]
Hola @enriquemolinare y @sjlarrain 
Respecto a la pregunta de enrique no es necesario que la ventana de juego sea una ventana principal igual si es que quieres ocupar una y cumples con lo que pedimos en el enunciado está bien. Es posible también crear varios QWidgets utilizando herencia para personalizarlos donde uno de ellos contenga a los otros. Un ejemplo simple de lo que te mencione que va a servir para responder  también la duda de sjlarrain es el siguiente:
````python
import sys
from PyQt5.QtWidgets import (QApplication, QWidget, QLabel, QHBoxLayout,
                             QVBoxLayout, QPushButton)

class Ventana(QWidget):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.init_gui()

    def init_gui(self):
        layout = QVBoxLayout()
        #Agregamos los grupos (Los widget que creamos)
        self.grupo1 = Grupo1(self)
        layout.addWidget(self.grupo1)
        self.grupo2 = Grupo2(self)
        layout.addWidget(self.grupo2)
        self.setLayout(layout)
        # Configuramos las propiedades de la ventana.
        self.setGeometry(50, 50, 250, 200)
        self.show()

class Grupo1(QWidget):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.init_gui()

    def init_gui(self):
        layout = QHBoxLayout()
        self.label = QLabel('Boton Grupo1:', self)
        self.boton = QPushButton("Push", self)
        layout.addWidget(self.label)
        layout.addWidget(self.boton)
        self.setLayout(layout)


class Grupo2(QWidget):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.init_gui()

    def init_gui(self):
        layout = QHBoxLayout()
        self.label = QLabel('Boton Grupo2:', self)
        self.boton = QPushButton("Push", self)
        layout.addWidget(self.label)
        layout.addWidget(self.boton)
        self.setLayout(layout)

if __name__ == '__main__':
    app = QApplication([])
    ventana = Ventana()
    sys.exit(app.exec_())
````
Lo que genera la siguiente ventana:
![ventanita](https://user-images.githubusercontent.com/48482216/96464844-b02c7100-11fe-11eb-98ce-575f0f7d5395.PNG)
Si se fijan en ese ejemplo tengo dos grupos cada uno con un boton y una label pero los grupos podrían contener cualquier otra cosa. Además en este caso ocupe un layout en la ventana pero también se puede especificar la geometría de cada grupo después de instanciarlo dentro de la clase ventana de esta forma ````self.grupo1.setGeometry(x, y, ancho, alto)```` .  Lo último si por ejemplo quiero obtener desde mi clase ventana el texto del label del grupo 1 lo puedo hacer de la siguiente forma ````self.grupo1.label.text()````.
Espero haber respondido ambas dudas igual me comentan si algo no se entendió muy bien.

**Comment by sjlarrain** [comment]
Perfecto, entonces no es considerado una mala práctica. Si me queda una duda que es como puedo acceder a ellos una vez que los diseñé en Qt Designer. Por que yo estoy trayendo una ventana que contiene estos cuatro QWidgets. Por lo tanto no se como acceder a cada un de ellos una vez que los cargo a traves de `uic.loadUiType` ya que eso me devuelve solo una tupla.

Espero que se entienda la pregunta!
Muchas gracuas de antemano

**Comment by JuaniAndres** [comment]
Sip no es una mala práctica. Respondiendo si cargaste la Ui de la misma manera que en el primer ejemplo de los contenidos de la [semana 10 parte de qt designer](https://github.com/IIC2233/contenidos/blob/master/semana-10/3-pyqt-qt-designer.ipynb), en QT Designer todos los label, botones ,line edit, etc llevan un nombre que aparece en la parte de designer que se llama Object Inspector. Después de haber ocupado setupUi en tu clase ventana puedes ocupar self.{nombre_objeto} para acceder a ese elemento esto es independiente si el elemento estaba dentro de algún widget de los que creaste dentro tu ventana.
Por ejemplo, tengo un Ui que contiene lo siguiente:
![ui](https://user-images.githubusercontent.com/48482216/96475781-cb04e280-120a-11eb-914c-a246efc68145.PNG)
En resumen, es una ventana que dentro tiene un QWidget y dentro de este último hay un QLabel. Por ejemplo si yo ya hice el setupUi puedo cambiarle el texto a la QLabel desde mi clase ventana de la siguiente manera ````self.label.setText("Texto bacan")```` (label es el nombre que le puse a la QLabel como aparece en la imagen pero podría ser cualquier otro)
Espero haber resuelto tu pregunta me avisas si te surge otra duda o si no te funciona.

**Comment by sjlarrain** [comment]
Casi, porque lo que quiero yo es recuperar ese QWidget para darselo a una clase. 
Entonces lo que me gustaria a mi es:
```
class Tienda (self.nombre_widget)
        def __init__(self, *args, **kwargs):
                 super().__init__(*args, **kwargs)
                  #Acceder aca a los labels prehechos y realizar las señales de ese Qwidget aca
```

No se si yo me estoy enredando de sobremanera o bien es preferible hacerlo de esta forma. O hay que hacerlo como se explico anteriormente. O estoy cofundido con el tema de las señales.

Muchas gracias

Saludos

**Comment by JuaniAndres** [comment]
Según lo que entiendo que estas tratando de hacer no debería ser necesario esa clase intermedia, sino que puedes hacerlo la conexión de las señales desde la misma clase ventana. Igual si quieres me escribes por discord para que me puedas explicar en detalle lo que quieres hacer así entenderlo mejor.

**Comment by sjlarrain** [comment]
Aaaa ya perfecto. No es necesario entonces hacer una clase para cada `QWidget`. Creo que voy a tratar de hacerlo como dices. Cualquier cosa te contacto por Discord. 

Muchas gracias por toda la ayuda. 

Saludos

Santiago
