### ISSUE TITLE
Sentido del reloj

### ISSUE THREAD

**Issue by Aloncarrasco** [IIC2233/syllabus#714]
Hola,
no entiendo el sentido del reloj, debe ir marcando la hora?
le debe decir a los otros objetos que hora es?
no pueden los otros objetos determinarlo independiente mente?

**Comment by Alonsinho1** [comment]
Hola, puedes hacer que con un reloj se defina el tiempo para todos los objetos, pero tambien puede hacer que cada objeto defina su propio tiempo.

Mientras el programa cumpla con lo pedido y sea consistente (Que no hayan relojes funcionando a una velocidad distinta) estara todo bien

Suerte !

**Comment by lewebe** [comment]
@Alonsinho1 Hola, sigo sin entender muy bien qué hacer con el reloj. Qué es exactamente lo que debe regular? Por ejemplo, si yo hago que mi mesero toque a un chef esto desencadenará que se ponga a cocinar. Qué parte de esto debiera estar regulada por un reloj?

**Comment by Alonsinho1** [comment]
Hola, perdon por la demora, no habia cachado que tenia la notificación desde la semana de descanso!

La gracia es que los personajes tiene una acción que es limitada por tiempo. Por ejemplo, el chef tiene un tiempo de preparacion de plato y los clientes tienen un tiempo de espera. Como las condiciones tienen que ser cumplidas son dependientes del tiempo, tiene que existir un reloj (o varios) que vayan contando el tiempo desde que el personaje comienza a realizar la accion hasta que esta se acabe.

Ejemplo:

Si el chef comienza a preparar un plato, el reloj comenzara a correr para el chef y una vez que este llegue al tiempo indicado en los parametros, el plato estara listo. 

En resumen, el reloj es la forma de verificar si ciertas acciones de los personajes deben ocurrir o no.
