### ISSUE TITLE
Resolución de Pantalla

### ISSUE THREAD

**Issue by vtunon7** [IIC2233/syllabus#715]
Hola! Quería saber si es que tendré algún problema con pyqt5 ya que la geometría de mi pantalla es distinta que los limites que muestran en los contenidos. En vez de ser (1600, 900) es (1920,1080), tendrá alguna consecuencia en el desarrollo de la tarea? Gracias!!

**Comment by vtunon7** [comment]
Por ejemplo, las ventanas de los ejemplos de los contenidos se me ven distintos, como esta
![image](https://user-images.githubusercontent.com/48421226/82265159-5b758900-9934-11ea-950e-28d9e74293c6.png)
Donde texto y el QLineEdit deberían estar separados

**Comment by kadroguett** [comment]
Hola @vtunon7 
No hay consecuencia si desarrollas tu tarea en una pantalla de (1920, 1080), puedes trabajar tranquilo adaptando las ventanas para esa resolución. Antes de la entrega de la tarea se envía un formulario preguntando por el tipo de pantalla que tiene cada estudiante para asignarle ayudantes que tengan el mismo tipo.
