### ISSUE TITLE
Duda nombre usuario

### ISSUE THREAD

**Issue by savelozo** [IIC2233/Syllabus#715]
En la parte de interfaz gráfica ¿Es necesario que el usuario ponga su nombre en la misma ventana en la cuál aparecen las canciones? Si ese no es el caso, podríamos crear un ventana inicial que le pida el nombre de usuario e inmediatamente verifique que dicho nombre sea único?

**Comment by Hernan4444** [comment]
Hola, revisa el #710 
Saludos ✌️
