### ISSUE TITLE
Flujo de información Cliente-Servidor

### ISSUE THREAD

**Issue by fgbruna** [IIC2233/Syllabus#715]
No me termina de quedar claro como se debería comunicar el cliente con el servidor, en términos de traspaso de información, especialmente en el caso de la tarea con el traspaso de las imágenes.Voy a tratar de enumerar los pasos que, según lo que yo entiendo, deberían seguir el cliente y servidor en una conexión a prograshop:

1. Se monta el servidor en mi computador en donde estarán *localmente* en formato png las primeras imágenes para los usuarios.
2. Se conecta el primer usuario, el cliente le notifica al servidor.

3. El servidor le envía en forma de `bytes` las imágenes al cliente.

4. El cliente reconstruye las imágenes para mostrárselas al usuario en la interfaz?.

5. El usuario edita una imagen y por lo tanto el cliente le envía de nuevo la imagen *modificada* en formato de `bytes`  al servidor para que este se las reenvíe todos los clientes de los usuarios conectados? Luego repito los pasos 3 y 4 para cada cliente conectado con esta nueva imagen?

En el fondo no me queda claro:
+ Quién debería ser el encargado de reconstruir las imágenes?, me parece lógico que fuera el cliente por que el servidor no tiene por qué estar viendo las imagenes(?)

+ Las imágenes se guardan en algún momento a nivel local en el servidor ?, supongo que una vez que se "desmonta" las imágenes se tienen que guardar en el servidor para enviarlas denuevo a los usuarios que se conecten la próxima vez(?)

Disculpar la extensión del post y gracias de antemano!

**Comment by cilopez** [comment]
1.  El cliente, ya que el servidor no tiene una interfaz gráfica y en realidad poco le importa reconstruirlas, por lo que estas en lo correcto
2.  Así es, tal como se puede desprender de la sección ventana de edición en el ítem actualización de cambios.

__Ojo__ que el cliente no envía la imagen actualizada, envía los cambios que se hicieron en esta

**Comment by fgbruna** [comment]
@cilopez entonces, si es que entiendo bien, en el fondo al momento de editar una foto, yo le envío al cliente la información que cambia en la imagen, luego el cliente después de procesar esta info  muestra la imagen editada y además se la envía al servidor y luego el servidor reenvía esa info a cada cliente conectado para este edite y muestre la imagen editada ? :grin:

**Comment by cilopez** [comment]
Asi es, tal  como se muestra en la workflow que está en la sección Cliente, envío de archivos! :+1:

**Comment by Kitaps** [comment]
No me queda claro como hacer para enviar solamente los cambios. Hago otra issue o pregunto eso por acá?

**Comment by Hernan4444** [comment]
@Kitaps la idea es que en base a las acciones que hace el usuario en la imagen, tu logres definir un "paquete de cambios" (como un evento de pyqt5) que tiene la información necesaria para que otro PC pueda replicar los cambios. El ¿que datos enviar para definir los cambios? queda  a tu criterio mientras no mandes toda la imagen de nuevo.
