### ISSUE TITLE
Zona de Captura: Imagen

### ISSUE THREAD

**Issue by enriquemolinare** [IIC2233/syllabus#715]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/327)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/326)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Revisé las imágenes entregadas en la tarea y no encontré la imagen de zona de captura. Dicha imagen nosotros tenemos que conseguirla?

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by JuaniAndres** [comment]
Hola @enriquemolinare 
La zona de captura que mostramos en el enunciado la armamos con lo que ofrece Pyqt5 por lo que no es necesario que ocupes una imagen. Sin embargo, si quieres implementar tu zona de captura utilizando imágenes creadas por ti puedes hacerlo, pero recuerda subir esos sprites.
