### ISSUE TITLE
Dead end: No puedo actualizar app de Heroku

### ISSUE THREAD

**Issue by kadawn0** [IIC2233/Syllabus#715]
Hola,

He estado probando Heroku con una app dummy antes de ponerme a crear webhooks porque necesito una URL y Heroku permite volver a hacer build de la misma app.
Eso mismo estaba haciendo ahora pero hay un error con la Procfile original que se llamaba "Procfile.txt".
La iba a cambiar pero luego de hacer build en el remote de heroku quedé con una discordancia entre branches que no me permite hacer el push subtree que necesito, y tampoco pull para solucionar la discordancia.
Lo que había en mi cmd está acá: https://hastebin.com/iciyuyokaj.tex
¿Cómo soluciono esto sin hacer una nueva app?

**Comment by rpalmaotero** [comment]
No es muy elegante pero prueba haciendo `git push heroku master -ff`.

**Comment by kadawn0** [comment]
Acabo de probar eso, pero tira el error "error: unknown switch `f'"

**Comment by iqacevedo** [comment]
Intenta agregar `--force` al `git push` (Como dijo @rpalmaotero no es muy elegante)

Saludos !

**Comment by kadawn0** [comment]
Gracias por la ayuda, pero al final hice una nueva app con la Procfile correcta y todo está funcionando :).
Voy a cerrar la issue ahora.
