### ISSUE TITLE
AF07 - Error de conexión [WinError 10053]

### ISSUE THREAD

**Issue by namadatzis** [IIC2233/syllabus#715]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola!
Estaba revisando la AF07 y corrigiendo errores que tenía para entender bien la materia y partir con la T3. Tengo dos consultas:

1. En el archivo `servidor.py`, en la función `escuchar_cliente` si hay un mensaje se debe "iterar en los ID de los clientes" pero no estoy segura sobre qué elemento iterar.

2. Después de revisar con el video de cierre y aparentemente tener todo ok me aparece el siguiente error:

![image](https://user-images.githubusercontent.com/26422815/124345817-20223200-dba9-11eb-8d4f-2061d32e0bf5.png)

Por lo visto es mi computador, no tengo otro pc donde probar mis archivos y aún estoy buscando solucionarlo. Podrían revisar mi código para ver si realmente está funcionando todo ok y ese es el único error?

Gracias!

**Comment by aerotecnia99** [comment]
Hola @namadatzis ! Debes iterar sobre los id de los clientes que les corresponde recibir el mensaje y enviárselo. En cuanto a ese error que te aparece es porque en tu cliente cuando envías un mensaje cierras el socket para la comunicación entre cliente y servidor, y no lo cierras sólo en caso de error de conexión. Espero haber aclarado tu duda :smile_cat:

**Comment by namadatzis** [comment]
Hola! Gracias @aerotecnia99 ,
Creo que te refieres a los finally? Los eliminé y dejé de tener el error. Y ya estoy iterando en los id, pero al abrir la interfaz del cliente e ingresar un usuario en la ventana inicio el botón enviar no realiza ninguna acción, por lo que no puedo comprobar si efectivamente se está escuchando al cliente. Revisé las issues que hablan al respecto pero según yo tengo esos aspectos ok y ya no sé como proceder :(

**Comment by aerotecnia99** [comment]
Hola @namadatzis, disculpa la demora. Tu servidor está teniendo un error en el método `escuchar_clientes` porque si bien estás iterandos sobre los id de los clientes, estás utilizando el método de logica.py `manejar_mensaje` , el cual como parámetros recibe un mensaje y un id de cliente. Por otro lado, la razón de iterar los los ids de los clientes es para poder identificar el socket respectivo y así utilizar el método `enviar` que implementaste, solo que este método también sólo recibe un socket de un cliente. Espero puedas resolver tu duda! :smile_cat:
