### ISSUE TITLE
Modelación con QGraphics

### ISSUE THREAD

**Issue by EduardoIllanes** [IIC2233/syllabus#716]
Hola tengo una duda/error, estoy utilizando QGraphicsScene para implementar el mapa y manejar de manera mas "sencilla"?) los movimientos y las colisiones. El problema es que cuando quiero agregar el widget (a través de la función .addWidget() ) que contiene el mapa me entrega el siguiente error:
`QGraphicsProxyWidget::setWidget: cannot embed widget 0x25538ca6ba0 which is not a toplevel widget, and is not a child of an embedded widget`

He buscado en internet como solucionarlo pero no he encontrado nada que me sirva.  Se me ocurre como solución agregar a la scene el mapa en forma de QGraphicItem en vez de forma de widget.
No se si alguien me puede decir a que se debe el error o si alguien me puede explicar el como transformar la foto en QGraphicItem ya que he estado leyendo la documentación y no entiendo bien como utilizarlo. Gracias!!

**Comment by jitorcas** [comment]
Hola! 

Para la modelación de la tarea se puede utilizar QGraphics, pero como no es un contenido que se abarque con profundidad en el curso, ante un error rebuscado podría pasar que los ayudantes no te podamos ayudar. Sin embargo, como experiencia personal cuando realicé el curso implementé una parte con Qgraphics y funcionó bastante bien. 

Primero te recomiendo investigar en la documentación sobre los métodos `view.addItem()` y `view.setScene()`. 

También debes considerar que `QGraphicsItems` es un simil a `Qlabel` que tienen métodos diferentes para hacer las cosas. por lo que si vas a usar `Qgraphics` debes ser consistente con tu modelación. 

Éxito!
