### ISSUE TITLE
Pasar de bytes a matriz RGB

### ISSUE THREAD

**Issue by FernandoPieressa** [IIC2233/Syllabus#716]
Hola!

Muchos el día de hoy en la sala de ayuda preguntaron como pasar la imagen PNG a matriz RGB.

Al igual que en el enunciado se habla de comprimir la matriz a través del método compress de la librería zlib, para conseguir la matriz RGB tienen que hacer el proceso inverso, utilizando el método decompress de la misma librería en la sección de información dentro del chunk IDAT.

Saludos!

**Comment by MarceloSaldias** [comment]
Que pasa cuando hay mas de un chunk IDAT? Se concatenan los bytes y se pasa por decompress?
Gracias por subir esto ;-;

**Comment by iqacevedo** [comment]
Las imágenes con las que tiene que trabajar en esta tarea solo tendrán 1 chunk IDAT.

Saludos !

**Comment by Hernan4444** [comment]
@MarceloSaldias si alguna de las imagenes llegara a tener más de un chunk en IDAT, te recomiendo concatenar el cuerpo de todos los IDATencontrados y de ahí hacer descompress. Al menos eso hicimos en nuestro código para poder encontrar imagenes PNG que funcionaran. Pero al momento de corregir, si o si nos aseguraremos que sean imagenes con 1 chunk IDAT, puesto que no se especificó que hacer en otro caso.

Saludos ✌️

**Comment by MarceloSaldias** [comment]
Lo anterior lo mencionaba porque al tomar los datos de Bowser.png hay unos 6 o 7 chunks IDAT seguidos.
Muchas gracias por sus respuestas! 😄

**Comment by Hernan4444** [comment]
@MarceloSaldias gracias por avisar!!! Si haces lo que dije, no deberías tener ningún problema.

Saludos ✌️

**Comment by BeaGaete** [comment]
Hola!!! Cuando abro algunos archivos .png, en particular Rick.png, me encuentro con algunos chunk que son de tipo sRGB, gAMA o pHYs, debo tratarlos como IDAT también????

**Comment by naazocar** [comment]
#706

**Comment by nlvargas** [comment]
Hola, 
Al tomar el len(decompress(bytes_IDAT))) me da un numero mayor (1596504) que utilizando la formula h * (3 * w + 1) = 1197560 para el caso de la imagen "Anime". 
¿Cómo puedo trabajar ese numero?
He comprobado que la cantidad de bytes_IDAT que le entrego a decompress() es el especificado en el largo_IDAT.

**Comment by BeaGaete** [comment]
misma duda!!

**Comment by Hernan4444** [comment]
estimados, puede ser que algunas imagenes, efectivamente venían con más de un IDAT, pueden:
1. Descartarlas
2. Concatenar lo cuerpos y a eso hacer descompress.

Saludos ✌️

**Comment by nlvargas** [comment]
@Hernan4444  Eso no responde mi duda. Estoy haciendolo con el único IDAT que aparece.

**Comment by Hernan4444** [comment]
@nlvargas acabo de revisar la imagen, lo que pasa es que la imagen no está en el RGB tradicional, sino que en RGBA, esto implica que son 4 byes por pixel, es decir, la formula verdadera sería ` h * (4 * w + 1) `, para trabajar este caso (si es que quieres). 

De todos modos me acabo de dar cuenta que la solución que tenemos para trabajar PNG abarca muchos más de los indicados en la tarea, por lo que te sugiero (por el momento) partir con `Knightmare.png`, esa imagen cumple con ser RGB y tener solo 1 IDAT. Ahora estoy identificando cuales imagenes no cumplen con lo solicitado en el enunciado para avisar que no es necesario que las usen.

Saludos ✌️
