### ISSUE TITLE
Formato informacion issue

### ISSUE THREAD

**Issue by jgramsch** [IIC2233/Syllabus#716]
Hola! 
está bien si cambié el formato en que las issues son se muestran a:
direccion: url

numero issue
Titulo
Autor

cuerpo

comentarios (si es que hay)

?
Es solo que siento que se ve mas ordenado así, pero no quiero que afecte mi nota,
Gracias!

**Comment by rpalmaotero** [comment]
Mientras tenga toda la información solicitada, no hay problema.

**Comment by acrojas2** [comment]
Hola! @rpalmaotero es necesario que en el cuerpo estén los comentarios?
Saludos!

**Comment by akaminetzkyp** [comment]
No es necesario! https://github.com/IIC2233/Syllabus/issues/691 :)
