### ISSUE TITLE
Convertir QWidget creada en Qt Designer a una QWidget personalizada

### ISSUE THREAD

**Issue by lewebe** [IIC2233/syllabus#717]
Hola! Quería saber si hay alguna manera de convertir un QWidget que ya cree en Qt Design a uno personalizado que creé en una clase. Por ejemplo, en Qt Designer cree un QPushButton con el nombre ```boton_1```. Pues bien, ahora me gustaría que ese botón tenga el comportamiento que yo creé en la clase ```MiBoton(QPushButton)``` sin que pierda la posición en la que lo creé ni los layouts en los que está, etc; bastaría con hacer esto en mi código?:
```python
class VentanaInicio(window_name, base_class):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.boton_1 = MiBoton(parametros)
```

**Comment by lewebe** [comment]
O en su defecto, me gustaría saber si puedo importar mis QWidgets a Qt Designer para trabajar con ellos.

**Comment by matiasmasjuan** [comment]
Hola @lewebe !

Generalmente, cuando tengas el código listo y tengas dudas si es que funciona o no, es mejor que lo compruebes por tu cuenta y veas qué sucede.

Con respecto a pregunta, no se puede importar ***QWidgets*** hechos en código y luego **importarlos** a **QtDesigner** (o al menos desconozco que se pueda). Sólo se puede hacer desde el **QtDesigner** y luego manejar el comportamiento de tus ***QWidgets***, ***Qlabels*** o ***Layouts*** creados en **QtDesigner** a tu **código**.
Por otro lado, no logro entender qué es lo que **concretamente** quieres lograr con esto. Si quieres que el *self.boton_1* creado en **QtDesigner** adopte ciertas características. Tienes dos opciones:
* Editar estas características de dimensiones, posición, tamaño, etc (en el mismo **QtDesigner**)
* Que modifiques el comportamiento de *self.boton_1* (creado en **QtDesigner** con ese **nombre**) en tu código. Por ejemplo, utilizando el comando *self.boton_1.setGeometry(posiciones)* para cambiar la posición de tu **QPushButton**.

Espero haber respondido a tu pregunta, y mucho éxito con la tarea! 😄
