### ISSUE TITLE
Problema Bonus Tarea 7: No hay apis de busqueda

### ISSUE THREAD

**Issue by legramsch** [IIC2233/Syllabus#717]
Hola, al buscar apis de busqueda para efectuar el bonus de la Tarea 7, no he encontrado ninguno que sea Gratis. Google y Bing necesitan suscripcion y pagar (Bing desde este año), DuckDuckGo no muestra links a paginas externas, solo informacion dentro de la pagina. No he logrado encontrar uno gratis y que no me pida la tarjeta jaja.
Si alguien encuentra una por favor me diga, necesito el bonus jaja 
Si no hay, entonces que pasa? no hay bonus nomas?

**Comment by KnowYourselves** [comment]
El de Google es gratuito (si bien tiene una opción pagada)

**Comment by chuma9615** [comment]
Yo tuve el mismo problema, para usar la api de google tienes que inscribir tu proyecto y pagar, como lo.hacemos? (Quizás usando un wrapper?)

**Comment by chapito96** [comment]
Tengo el mismo.problema,  duckduckgo es muy limitado por su sistema de "instant answer" en la api. Solo encuentra cosas simples como "Chile" y arroja un enlace a wikipedia en el mejor de los casos, pero si lo complicas un poco se pierde.
En el caso de bing me pide una cuenta de azure microsoft que como mínimo me pide registrar mi tarjeta del banco entre otras cosas para registrarme y espero no llegar a eso aún

**Comment by akaminetzkyp** [comment]
No es necesario pagar para usar el API de Google. No me acuerdo del link, pero en una página podías inscribir tu proyecto.

**Comment by rpalmaotero** [comment]
Google Custom Search Engine ofrece una modalidad gratis (100 consultas diarias). Otra opción menos amigable con DuckDuckGo es hacer `GET  https://duckduckgo.com/html/?q={query}` y parsear el HTML. Esto último retorna la búsqueda completa.

**Comment by legramsch** [comment]
Hola ya lo resolvi, para el que le siva, y entienda como lo escribo jaja:

https://cse.google.com/manage/all

ahi es donde se crea la custom search engine, pones las paginas, y pones buscar en toda la web priorizando las paginas, eso es gratis, despues de que se creó (es gratis, tienes que inscribir un proyecto y hay una opción gratis), aprietas el boton get code, y copias del codigo el cx, "un numero como así '008675764795148742003:pq6exbpjatg';
despues con eso haces un get del tipo:
https://www.googleapis.com/customsearch/v1?cx=[EL CX]&key=[LA KEY DE ACCESO QUE OBTIENES AL HACER EL PROYECTO]&q=[LA BUSQUEDA]'
el primer resultado es el `URL = busqueda['items'][0]['link']` del json 
Ojala se entienda algo

**Comment by nivek0o0** [comment]
Hola @legramsch hice exactamente lo que dices y la http request me arroja:
`Error 403: Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.`

¿Hiciste algo más aparte de crear un motor de búsqueda para obtener el cx y crear un proyecto para obtener la API key?
