### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by valeria-adasme** [IIC2233/Syllabus#717]
Hola, estaba leyendo el enunciado y al llegar a la sección del título de esta issue no entiendo muy bien qué es el dashboard ¿Sería algo así como el menú? ¿El 'cómo' se muestra lo que nos piden queda a criterio propio?

**Comment by Hernan4444** [comment]
@valeria-adasme precisamente es el menú luego de ingresar. El 'como' se verá queda a tu criterio mientras cumplas con todos los requisitos del enunciado.

Saludos ✌️
