### ISSUE TITLE
Error al instanciar Ventana que hereda de designer.py

### ISSUE THREAD

**Issue by En-clases** [IIC2233/syllabus#717]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/327)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/326)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola, he definido una clase de ventana que hereda de un archivo Designer que contiene algunos labels y botones. Además de esto, a dicha clase de ventana le agregué algunas funciones y unos labels para agregar imágenes con código python. Cuando instancio esta clase desde el mismo archivo en donde el código esta escrito, todo funciona bien. En la ventana emergente se pueden ver los botones y labels que creé mediante Designer y también las imágenes y funciones que agregué aparte. Sin embargo, cuando quiero instanciar esta clase de ventana desde otro módulo, haciendo un import de la clase, la ventana que emerge solo contiene los labels y botones que hice en el Designer. Todas las funciones e imágenes pertenecientes a la ventana que agregué con código no se muestran. Cuál podría ser el error?

**Comment by aaossa** [comment]
Hola @En-clases , si se te abre la ventana asumo que no ocurre una excepción directamente. De todas formas, ¿hay algún mensaje de error en la consola cuando ocurre esto? Lo que se me ocurre que podría ser es que **en la ventana colocaste las rutas relativas al archivo que contiene la ventana (desde, por ejemplo, `ventanas/ventana.py`) pero no desde `main.py`**, y por eso te funciona al correrlo de una manera pero no de otra. Prueba colocando las rutas en relación al archivo que esperas que se ejecute (`main.py`). Con esto estoy asumiendo que el archivo de tu ventana está en una carpeta distinta al archivo principal, pero sospecho que podría ser eso 👌 ¡Éxito con la tarea!

PS: Recuerda colocar las rutas en `parametros.py` y así tienes al tiro las rutas relativas desde el directorio correcto ✨

**Comment by En-clases** [comment]
Muchas gracias por la ayuda! Al final tuve unos problemas con los imports y ahora todo me funciona bien! 👍
