### ISSUE TITLE
Adaptar **áreas** al tamaño de Ventana de Juego

### ISSUE THREAD

**Issue by Francisco-Morales-R** [IIC2233/syllabus#718]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/327)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/326)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, ¿las 4 áreas mencionadas para la Ventana de juego deben adaptarse al tamaño en el que se deje esta ventana? O podemos dejar un tamaño por default de la ventana y que estas áreas tengan un tamaño predeterminado?

Esto se podría resumir en ¿Al corregir la tarea, irán cambiando el tamaño de las ventanas y moviéndolas o podemos dejarle un geometría predeterminada y que no necesariamente cambie?

**Comment by JuaniAndres** [comment]
Hola @Francisco-Morales-R 
Al corregir la tarea no vamos a cambiar las dimensiones de tus ventanas por lo que no es necesario que los elementos se adapten a esos cambios.  Así que si puedes dejar todas tus ventanas con un tamaño predefinido y por lo tanto también los tamaños de los elementos que contienen las ventanas.
En resumen, no tienes que preocuparte si al agrandar cualquier ventana pasa esto:
![ventana juego ampliada](https://user-images.githubusercontent.com/48482216/96453239-8d935b80-11f0-11eb-8095-5e9157739aae.PNG)
Espero haber aclarado tu duda

**Comment by Francisco-Morales-R** [comment]
@JuaniAndres Siii, me quedó mucho más claro. Graciaas!
