### ISSUE TITLE
Tarea 6 Manejo MIDI Ejemplo con 1 nota

### ISSUE THREAD

**Issue by Hernan4444** [IIC2233/Syllabus#718]
## Contexto

En la siguiente _issue_ se explicará paso a paso cómo construir un archivo (en formato MIDI) de un canal cuando tiene la siguiente nota:
- **Duración:** blanca
- **Nota:** Mi
- **Octava:** 5
- **Intensidad:** _ff_

## _Header_

Como la canción es de un canal, los números del `DATA` del _header_ son:

- Formato del MIDI: 1.
- Número de canales: 1.
- Número de _ticks_ por tiempo musical: 160.

Como cada número se representa con **dos** bytes, en formato _big-endian_. Utilizando `to_bytes()`, nos queda que:
- 1 = `b'\x00\x01'`
- 160 = `b'\x00\xa0'`

Con dicha información, la sección `DATA` será: `b'\x00\x01\x00\x01\x00\xa0'`. Esto utiliza 6 _bytes_; por lo tanto, el _header_ tendrá:

- _Type:_ `b'MThd'`
- _Length:_ `b'\x00\x00\x00\x06'` (claro, 6)
- _Data:_ `b'\x00\x01\x00\x01\x00\xa0'`

Finalmente, se concatena dicha información, la cual deja un _header_ así,
```python
b'MThd\x00\x00\x00\x06\x00\x01\x00\x01\x00\xa0'
```

## Canal

Ahora construiremos el canal. Como estamos asignando 1 nota, implica que debemos agregar un mensaje tipo _Note On_ y otro tipo _Note Off_. 

### Mensaje _Note On_ 

Recordar del enunciado que un mensaje tipo _Note On_ tiene tiempo igual a 0, pero el valor numérico de la nota y la intensidad corresponde a la nota que queremos agregar. En este caso, queremos un **Mi de la octava 5 con intensidad _ff_** (por si acaso, `MI == E`). Por lo tanto, debemos generar los _bytes_ de la siguiente información:
- Tiempo: 0
- Tipo de mensaje: 144 (_Note On_)
- Nota: 64 (E octava 5)
- Intensidad: 96 (_ff_)

#### Codificando el tiempo
En este caso, el tiempo es 0. Siguiendo la codificación: 
1. Pasar el número a binario. 0 en binario será 0000000
2. Separar de a 7 bits. [0000000]
3. **De derecha a izquierda**, agregar un octavo bit al inicio. El primero elemento se le agrega un 0 y al resto, un 1. [**0**0000000]

El resultado anterior, se puede ver tambien como: `[b'\x00']`.
Por lo tanto, este mensaje será:
- Tiempo: `b'\x00'` (1 byte)
- Tipo de mensaje: `b'\x90'` (1 byte)
- Nota: `b'@'` (1 byte)
- Intensidad: ```b'`'``` (1 byte)

Todo junto es ```b'\x00\x90@`'``` (4 byte)

### Mensaje _Note Off_ 

Recordar del enunciado que un mensaje tipo _Note Off_ tiene tiempo, valor numérico de la nota y la intensidad corresponde a la nota que queremos agregar. En este caso, queremos un **Mi de la octava 5 con intensidad _ff_ y su duración es una blanca** (por si acaso, `MI == E`). Por lo tanto, debemos generar los _bytes_ de la siguiente información:
- Tiempo: 320 (blanca)
- Tipo de mensaje: 128 (_Note off_)
- Nota: 64 (E octava 5)
- Intensidad: 96 (_ff_)

#### Codificando el tiempo.
En este caso, el tiempo es 320. Siguiendo la codificación: 
1. Pasar el número a binario. 320 en binario será 101000000
2. Separar de a 7 bits. [0000010, 1000000]
4. **De derecha a izquierda**, agregar un octavo bit al inicio. El primero elemento se le agrega un 0 y al resto, un 1. [**1**0000010, **0**1000000]

**Consejo:** Después de tener el binario, pasenlo a _integer_ 11000000 y finalmente usen `to_bytes()` para obtener el hexadecimal. En este caso,
- 10000010 = 130 = `b'\x82'`
- 01000000 = 64 = `b'@'`

 Por lo tanto, este mensaje será:
- Tiempo: `b'\x82@'` (2 byte)
- Tipo de mensaje: `b'\x80'` (1 byte)
- Nota: `b'@'` (1 byte)
- Intensidad: ```b'`'``` (1 byte)

Todo junto es ```b'\x82@\x80@`'``` (5 byte).

### Concatenando todo

Terminamos de generar las notas del canal. Ahora falta agregar el valores de cierre, que son: `[0, 255, 47, 0]`. Esto en _bytes_ será: `b'\x00\xff/\x00'`. Solamente pasé cada número a _bytes_ y los concatené.

Finalmente tenemos:
- Mensaje _On_ = ```b'\x00\x90@`'``` (4 byte).
- Mensaje _Off_ = ```b'\x82@\x80@`'``` (5 byte).
- Fin del canal = `b'\x00\xff/\x00'` (4 bytes)
Esto corresponde a la sección `DATA` la cual será: ```b'\x00\x90@`\x82@\x80@`\x00\xff/\x00'``` (13 bytes)

Por lo tanto, el canal tendrá:

- _Type:_ `b'MTrk'`
- _Length:_ `b'\x00\x00\x00\r'` (13)
- _Data:_ ```b'\x00\x90@`\x82@\x80@`\x00\xff/\x00'```

Finalmente, se concatena dicha información, la cual deja el canal como:
```python
b'MTrk\x00\x00\x00\r\x00\x90@`\x82@\x80@`\x00\xff/\x00'
````

# Archivo

Tenemos el _header_:
```python
b'MThd\x00\x00\x00\x06\x00\x01\x00\x01\x00\xa0'
```
Y el canal:
```python
b'MTrk\x00\x00\x00\r\x00\x90@`\x82@\x80@`\x00\xff/\x00'
````

El archivo al final será guardar la concatenación de ambos `bytearray`:
```python
midi = b'MThd\x00\x00\x00\x06\x00\x01\x00\x01\x00\xa0MTrk\x00\x00\x00\r\x00\x90@`\x82@\x80@`\x00\xff/\x00'

with open('cancion.mid', 'wb') as file:
    file.write(midi)

```

**Comment by joaquineichholz** [comment]
Hola, estoy haciendo el procesamiento inverso de leer una canción no entiendo como saber cual es el tiempo de  Game of Throne.mid

ya procese el header y me dio lo siguiente
header: {'type: b'MThd', 'lenght': 6, 'data': {'formato': 1, 'numero_canales': 1, 'ticks': 160}}

Al procesar el canal, lo primero que hago es generar un bytearray vació y agregarle bytes hasta encontrar el numero 128 o 144, en este caso encontré el numero 144 por lo tanto se trata de una nota Note On y me queda la siguiente secuencia: bytearray(b'\x00\x00\x018\x00') . Llevando esta secuencia a int haciendo int.from_bytes(s, byteorder='big') me da 79872 lo que no está ni cerca de ser 0



esta es la cancion en bytes: bytearray(b'MThd\x00\x00\x00\x06\x00\x01\x00\x01\x00\xa0MTrk\x00\x00\x018\x00\x90E`\x81p\x80E`\x00\x90>`\x81p\x80>`\x00\x90A`(\x80A`\x00\x90C`(\x80C`\x00\x90E`\x81p\x80E`\x00\x90>`\x81p\x80>`\x00\x90A`(\x80A`\x00\x90C`(\x80C`\x00\x90@`\x87@\x80@`\x00\x90C*\x81p\x80C*\x00\x90<*\x81p\x80<*\x00\x90A*(\x80A*\x00\x90@*(\x80@*\x00\x90C*\x81p\x80C*\x00\x90<*\x81p\x80<*\x00\x90A*(\x80A*\x00\x90@*(\x80@*\x00\x90>*\x87@\x80>*\x00\x90E`\x81p\x80E`\x00\x90>`\x81p\x80>`\x00\x90A`(\x80A`\x00\x90C`(\x80C`\x00\x90E`\x81p\x80E`\x00\x90>`\x81p\x80>`\x00\x90A`(\x80A`\x00\x90C`(\x80C`\x00\x90@`\x87@\x80@`\x00\x90C`\x81p\x80C`\x00\x90<`\x81p\x80<`\x00\x90A`(\x80A`\x00\x90@`(\x80@`\x00\x90C`\x81p\x80C`\x00\x90<`\x81p\x80<`\x00\x90A`(\x80A`\x00\x90@`(\x80@`\x00\x90>`\x87@\x80>`\x00\xff/\x00')

**Comment by Hernan4444** [comment]
Hola, recuerda que despumes de encontrar la secuencia del tiempo, tienes que hacer el proceso inverso a la codificación que se explica en el enunciado, no es solo utilizar `from_bytes`

**Comment by jerrymendoza** [comment]
Hola!, un detalle... en Note Off dice "Tipo de mensaje: 144 (Note on)" y unas lineas mas abajo dice "En este caso, el tiempo es 0" y debería ser tiempo: 320.

Duda, con el final [0, 255, 47, 0], en \x00\xff/\x00 el 47 esta representado por /, pero al buscarlo en bytes aparece como \x2F, quizás estoy ocupando algo mal? me preocupa que pueda pasar con otros números
gracias!

**Comment by Hernan4444** [comment]
@jerrymendoza gracias por los detalles, ya los corregí 👍 . Sobre el \x2F, exactamente ese es el hexadecimal, pero cuando haces print de los retonado por el `to_bytes`, aparecerá `b'/'`

**Comment by antoniacobo** [comment]
Hola! Entendí perfecto como se pasaba a MIDI, muchas gracias! Pero me quedo con la duda de cuando es más de una nota. Cuando lo pasemos debería ser header note_on note_off note_on note_off ... o header note_on note_off, header note_on note_off.

**Comment by Hernan4444** [comment]
>  header note_on note_off note_on note_off 

así, saludos ✌️

**Comment by sjkinast** [comment]
Hola no me queda claro en el ejemplo si la blanca son dos tiempos porque el numero de ticks en el header son 160 y no 320.

**Comment by jpmoraga1** [comment]
Hola! En caso de que una nota tenga puntillo, ¿vendrá indicado en un byte o debemos averiguarlo nosotros en base al número que sea? (Ej: Una negra con puntillo vendría con un valor de 240 o con 160 y un puntillo en otro byte)

**Comment by kdroppelmann** [comment]
Hola! Tengo un problema al leer los midi, específicamente al intentar de descodificar los bytes de tiempo de las notas en los Note Off. Se que tengo que hacer el proceso inverso a lo que indica el enunciado, pero cuando trato de pasar del paso 4 al 3, es decir, pasar de bytes a su respectivo binario, hay ciertos números que no quedan de 8 bits lo cual no debería pasar (asumiendo que ya se hicieron los 3 primeros pasos al codificar el tiempo) y con esto ya no puedo seguir descodificando. Que puedo estar haciendo mal?

**Comment by Hernan4444** [comment]
@sjkinast porque en el header se define el número de ticks **para un tiempo**, y en el canal se pone el tiempo de la nota, así el midi puede saber si la nota son 1, 2, 3 o n tiempos en base al número que tiene en el headers.
@jpmoraga1 no hay ningún bytes, solo lo sabrán por el valor (negra con punto tendrá 240 como tiempo)
@kdroppelmann con tu descripción, creo que estas leyendo mal el archivo, porque cada bytes es de máximo 8 bits. Si haces:
```python
with open('Game of Throne.mid', "rb") as file:
    for bytes_array in file.readlines():
        for bytes_ in bytes_array:
            print(bytes_)
```
Podrás ver que solo serán números entre 0 y 255, lo cual son valores que solo ocupan 8 bits.

**Comment by Mariana-Ortega-del-Rio** [comment]
Tengo la duda para el caso de varias notas si el canal va a ser: type length_nota_1 data_nota_1 length_nota_2 data_nota_2 ...
o si bien será: type length_todo_data data_todas_notas

Saludos!!
