### ISSUE TITLE
Fijar tamaño de las ventanas en QtDesigner

### ISSUE THREAD

**Issue by mpmunoz13** [IIC2233/syllabus#718]
Hola, 
Hay alguna forma de dejar fija la geometria de la ventana antes de pasarla? Al pasarla a mi código se cambian las dimensiones.

**Comment by mpmunoz13** [comment]
Al hacer preview en Qt design esta bien, pero al pasarlo a visual studio code se cambian las dimensiones.

**Comment by jbulness** [comment]
Hola @mpmunoz13,

No quiero sonar pesado, pero la verdad es que busqué tu pregunta en Google y la primera página que me mostró daba una respuesta a una pregunta casi exactamente igual a la tuya. Lo que quiero decir con esto es que trates primero resolver tu duda buscando información por tu cuenta, que es uno de los objetivos de esta tarea, y si ya llevas mucho tiempo sin encontrar una respuesta haz una issue. 

Por eso mismo, si sigues con problemas vuelve a comentar esta issue y feliz te ayudaré!

**Comment by mpmunoz13** [comment]
Hola @jbulness , 

Estas en lo incorrecto al asumir que no he tratado de resolverlo por mi cuenta. Si es que estoy haciendo una pregunta por acá, es porque necesito ayuda. Espero que me puedas ayudar, ya que llevo varias horas tratando de solucionar mi problema. 

Estoy pasando las ventanas como se explicó en el issue #690 pero al correr mi código la ventana se me achica y corta parte de el texto. Al hacer preview en Qt design no hay ningun problema, pero al correr main se cambia la geometría de mi ventana. Para fijar el porte de mi ventana en Qt design estaba haciendo que el porte maximo y minimo fueran lo mismo. Cuando hago eso, preview me deja el porte fijo y no me deja agrandarla o achicarla, pero sigo teniendo el mismo problema al correr main.

**Comment by jbulness** [comment]
@mpmunoz13 te pido disculpas por mi comentario y feliz te ayudo con tu duda.

La primera solución que se me vino a la cabeza y que era la misma que me salió en Google al buscar otras alternativas a tu problema fue usar `setFixedSize(largo, alto)`. Este método es propio de cada __widget__ y fija el tamaño de, por ejemplo, una ventana a las dimensiones de largo y alto que le des al llamar al método (no estoy si es largo, alto o alto, largo). Puedes probar configurando esto en tu código. Si sigues teniendo problemas usando esto por favor avisame para buscar otras soluciones.

**Comment by IvaniaArias** [comment]
@mpmunoz13 pudiste arreglarlo? Me pasa lo mismo :(

**Comment by mpmunoz13** [comment]
@IvaniaArias Al final agrandé el porte en Qt designer hasta un porte que me gustaba en visual studio.

**Comment by lily416** [comment]
Hola @IvaniaArias y @mpmunoz13 

Primero que todo siento lo tarde de esta respuesta, espero que aún les pueda ser de ayuda.

QtDesigner si permite definir los tamaños de las ventanas, basta que hagan _click_ derecho en el elemento que sale en el _Object Inspector_ y después seleccionar las opciones que salen a continuación:
![image](https://user-images.githubusercontent.com/26393515/83444513-80c8c380-a419-11ea-9bb4-e7e3df116bb5.png)

Esto les fijará el tamaño de la venta y posteriormente pueden cambiar estos valores en el _Property Editor_:
![image](https://user-images.githubusercontent.com/26393515/83444759-d9985c00-a419-11ea-8a06-4ecd2360cc40.png)

Ojalá aún les sea de ayuda y nuevamente lo lamento por lo tardío de la respuesta. 
Saludos y éxito en la tarea 👋🍫
