### ISSUE TITLE
Servidor y archivos subidos

### ISSUE THREAD

**Issue by valeria-adasme** [IIC2233/Syllabus#718]
En el inicio nos piden tener como mínimo 6 imágenes en el dashboard, sin embargo también se menciona que los usuarios que entran al server pueden subir sus propias imágenes.
Si todo esto lo controla el server, asumo que éste se ejecutará desde un computador 'fijo' y que siempre guardará los datos en ése computador o puede ir cambiando?

**Comment by FernandoPieressa** [comment]
Hola! Pueden considerar al servidor como si fuera un computador "fijo" sin embargo los clientes deberían poder funcionar perfectamente en distintos computadores.

Saludos!

**Comment by Polea012** [comment]
Si es que un usuario puede subir sus propias imágenes, en que seccion de la interfaz se controlaria?, no se especifica en ninguna parte del enunciado, tampoco se menciona si es que los otros usuarios pueden acceder a esa imagen.

**Comment by behrmann97** [comment]
Entonces las imagenes las tiene el servidor y se las envía codificadas  a los clientes cuando estos se conectan? No es que los clientes tengan las imagenes ya descargadas.

**Comment by Hernan4444** [comment]
@behrmann97 precisamente.

Saludos ✌️
