### ISSUE TITLE
Desconexión de Cliente

### ISSUE THREAD

**Issue by mmsaavedra1** [IIC2233/Syllabus#719]
Me nació una duda en que ocurre cuando cierra la interfaz de un cliente. Me apegaré a la ayudantía para explicar mejor mi inquietud.

Cuando creo un nuevo cliente y le asocio un thread, en el servidor, para que este escuchando constantemente lo que este cliente esta enviando. Al salir de la interfaz gráfica lanza el siguiente error.

![captura de pantalla 2017-11-10 a la s 13 01 18](https://user-images.githubusercontent.com/23617087/32666777-57a2b8f4-c617-11e7-8f5f-60e2b9b24dbb.png)

No entiendo porque client_socket.recv(4) recibe un string vacío cuando se desconecta, si se supone que nunca le envió información de forma explicita al servidor cuando salgo de la Gui del juego. 

![captura de pantalla 2017-11-10 a la s 13 01 43](https://user-images.githubusercontent.com/23617087/32666863-9fb0ec42-c617-11e7-8255-2310640f9aed.png)

Tenía entendido que cuando aplico recv() a un socket dentro de un thread, este método deja "pausado" en esa línea hasta recibir información. Le apliqué un print("hola") justo debajo, y cuando salgo de la Gui este print se ejecuta infinitamente dentro del loop. 

Quiero saber como funciona realmente dicho thread del servidor, y cuando se que debo cortar su ejecución. ¿ Apenas se cierra la Gui el socket del cliente siempre enviará un str vacío para identificarlo en el servidor, y así cortar su ejecución. O es simple casualidad y el servidor puede recibir un byte de largo cero cuando el cliente sigue conectado?

Saludos!

**Comment by vijuarez** [comment]
Hola!

Efectivamente, ese es el comportamiento esperado. Si se corta el programa que envía datos, el programa que los recibe tan solo devolvera un `b''` (string binaria vacia) en el método `recv`. Sería más intuitivo que levantara una excepción o se quedara esperando por siempre, pero este es el comportamiento que se usa como norma para sockets. Cuando tu programa reciba una string vacia, sabrás que se cortó la conección.

De hecho esta es la única forma de mandar una string vacía. Si intentas enviar algo como `"".encode('ascii')`, el programa encargado de recibirlo tan solo quedara esperando por siempre.

Saludos!
