### ISSUE TITLE
uso de código generado por qtdesigner

### ISSUE THREAD

**Issue by eliasbruchfeld** [IIC2233/syllabus#719]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/327)
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/326)
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Vi que hay una manera de que qtdesigner genere directamente un archivo .py con el código de lo que se quiere, en vez de cargar el archivo .ui desde el archivo .py en el que se esta trabajando, como dice en los contenidos. ¿Se puede usar esto en la tarea? Pregunto porque sería una cantidad bastante grande de código que, a pesar de haber generado, uno no escribió "a mano" y que usa una sintaxis un poco distinta a la que vimos.

**Comment by aaossa** [comment]
Hola @eliasbruchfeld , si se puede o no usar en la tarea creo que es mejor que lo respondan les ayudantes de tareas 😅, pero igual vengo a dejar un comentario que espero que te sea útil. Si armas una interfaz con un archivo *.ui, puedes utilizarlo directamente (como se muestra en los contenidos) y lograrás el mismo resultado que haciéndolo por código y con menos esfuerzo, por lo que no hay necesidad de transformarlo a código.

Como dices, se agrega una cantidad bastante grande de código... ¿es realmente necesario verlo como código? Yo diría que no es necesario transformarlo, a no ser que estés haciendo algo super específico. De todas maneras, recuerda que puedes acceder a los *widgets* que creaste en Qt Designer desde tu código, como se muestra en el último ejemplo del cuaderno respectivo. En general, yo prefiero usar Qt Designer solo para crear/diseñar la interfaz colocando los *widgets* y las imágenes y señales las manejo desde código, pero nunca transformo la interfaz a código 😅. Ojalá te sirva esta respuesta para darle una vuelta a si quieres o no convertirlo a código (y por qué) 👌 ¡Éxito con la tarea!

**Comment by gatochico** [comment]
Hola @eliasbruchfeld ! 
Para complementar la respuesta de @aaossa, recomiendo **fuertemente** que no generes los archivos` .py `y simplemente uses los `.ui` para cargar tu interfaz de Designer. Esto es ya que como notaron, la cantidad de código generada es bastante y no vale la pena tenerla como un` .py`.  

Ahora, respecto a tu pregunta en específico, no algo que esté prohibido en la tarea. Eso si, si llegas a proceder con esos archivos debes indicar en tu README cuáles son y explicar que son autogenerados a partir de un archivo .ui, para tener eso en cuenta a la hora de revisar.

Espero se haya entendido!

**Comment by jorge-ovalle** [comment]
Una pregunta respecto al código que tira Qt Designer. Si utilizo uno imagen como _pixmap_ en Qt Designer cómo puedo controlar la portabilidad del _path_ de dicha imagen para que no hayan problema cuando me revisen el código?

**Comment by furcelay** [comment]
Hola!
Respecto a tu pregunta se me ocurren dos métodos:
1.  No incluir las imágenes en QtDesigner e introducir las imágenes en el `__init__` de la ventana usando parámetros.
2.  Asegurarte de que al introducir las imágenes en QtDesigner el archivo .ui en el que estás trabajando se encuentre en el mismo directorio que `main.py` (o bien si abres QtDesigner desde un terminal que ese terminal esté en ese directorio) y solo usar imágenes que estén en el mismo directorio en que se van a usar en la ejecución del programa (por ejemplo en `T02/sprites`). De éste modo los *paths* que defina QtDesigner serán relativos a `T02` (suponiendo que ahí está tu `main.py`) hacia los archivos correspondientes (después podrías mover el archivo .ui si lo deseas, lo importante es hacerlo al momento de editarlo).

Saludos!
