### ISSUE TITLE
Acoplación notas-silencios

### ISSUE THREAD

**Issue by fpattillo** [IIC2233/Syllabus#719]
Hola!
Mi duda es que, como el "silencio" que sigue una nota contiene el tiempo de duración de la nota, ¿cada nota viene acoplada a un silencio? Es decir, se pueden agregar silencios por si solos, pero cuando uno agrega una nota, ¿está agregando la nota de tiempo 0 y el silencio de tiempo _tiempo_nota_?
Gracias!

**Comment by Hernan4444** [comment]
Exacto.

Saludos ✌️
