### ISSUE TITLE
Mapa avance

### ISSUE THREAD

**Issue by drosselot** [IIC2233/syllabus#719]
Hola, no me quedo claro como debe ser la interfaz para entregar en el avance. ¿Solo es necesario que cargue el mapa y sus objetos? ¿Puedo hacer que haya que apretar un botón para cargar el mapa, o tiene que cargarlo solo con correr el programa?

**Comment by jitorcas** [comment]
Hola!

La idea de los avances es que leas la tarea y comiences a modelarla lo más pronto posible, por lo que si deseas implementar la ventana de inicio con un botón que te lleve al mapa no hay ningún problema. 
Como dice el enunciado, lo mínimo requerido es el cargado visual del mapa a partir de la información contenida en el archivo **mapa.csv**, con un correcto uso de señales y una correcta separación entre *back-end* y *front-end*. 
En síntesis, lo requerido visualmente es que al correr tu programa se pueda visualizar el mapa con toda la información contenida en **mapa.csv**, no es necesario implementar un botón que haga que aparezca tu mapa a partir de la ventana del mapa.
Espero haberte ayudado!

**Comment by mpmunoz13** [comment]
Hola, 
Debemos crear un archivo que se llame avance y abra nuestro mapa con los datos contenidos en mapa.csv?
@jitorcas

**Comment by jitorcas** [comment]
@mpmunoz13 Así es, tal como te respondieron en la issue #735, se espera que puedas presentar un avance de lo que sería tu tarea. 
Te recomiendo comenzar a modelar inmediatamente con la estructura *back-end* y *front-end*, además de una correcta implementación de señales. Crear un archivo exclusivo para el avance sería sumar más trabajo a la tarea y no es lo que queremos, si no que puedas avanzar en la entrega oficial de la tarea.
