### ISSUE TITLE
Dónde colocar referencias a código externo

### ISSUE THREAD

**Issue by DonJavi-538** [IIC2233/syllabus#72]
Hola de nuevo! ajjaja me gustaría preguntar dónde y cómo citar código externo obtenido, por ejemplo, de una página.

Gracias por la ayuda =)

**Comment by jeschuwirth** [comment]
Hola!

Hace poco @lily416 subió templates de readmes (Syllabus -> Tareas -> Ejemplos Readmes). En la parte final de ellos está la sección **Referencias de código externo**, donde puedes citar el link y la razón por la que lo usaste.

![image](https://user-images.githubusercontent.com/37160256/63205495-f920ec80-c072-11e9-8af6-b9d5596cccfe.png)


Como recomendación, también agregaría un comentario en el lugar donde pegaste el código diciendo que lo sacaste de tal página y su link.

Suerte en la tarea !

**Comment by DonJavi-538** [comment]
Gracias por la ayuda! Ahora, si dicha función fue material de otro curso dictado en otro año, debería citarlo de todas formas? lo pregunto porque no tendría un link donde mostrar su fuente.

**Comment by jeschuwirth** [comment]
Intenta colocar un link para poder confirmar el código, pero si esta citado y explicas de donde lo sacaste no hay problema con que lo hagas sin el link 👌
