### ISSUE TITLE
Contenido prograposts

### ISSUE THREAD

**Issue by amparostevens** [IIC2233/syllabus#72]
Hola! 
En una issue anterior preguntaron si los espacios cuentan como caracteres y dijeron que si. Mi pregunta va a que si creo un post que contiene puros espacios en teoría no sería un post vacío pero no se va a ver nada, es eso válido como post?

**Comment by aljara97** [comment]
Hola @amparostevens!
Como se especifica en el enunciado, tu prograpost puede contener cualquier tipo de caracter, por tanto, un string con puros espacios y que cumpla con el largo pedido sería válido.
Mucho éxito con tu tarea :nerd_face:

**Comment by amparostevens** [comment]
Okii gracias!
