### ISSUE TITLE
Alcance máximo en property piezas_explosivas_invalidas

### ISSUE THREAD

**Issue by vichoassadi** [IIC2233/Syllabus#72]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

En el enunciado, se dice que para el alcance máximo no se deben tomar en cuenta los peones del tablero. Para explicar mi duda, voy a poner un ejemplo.
```python
lista_tablero = [
        ["--", "--", "--", "--", "--"],
        ["--", "PP", "PP", "--", "H4"],
        ["--", "--", "PP", "--", "--"],
        ["--", "--", "PP", "V5", "--"],
        ["--", "R8", "PP", "--", "--"]
    ]
```
En este caso, por lo que entiendo del enunciado, R8 tiene un alcance de 8, y sus celdas afectadas son 5. Cuando se habla de alcance máximo en la property piezas_explosivas_invalidas, en este caso sería de 13?

Muchas gracias

**Comment by Hernan4444** [comment]
Hola @vichoassadi 

Si, justamente, como dices en tu ejemplo, la R8 debe destruir 8 celdas (su `self.alcance` será 8), pero las celdas afectadas realmente son 5 en dicho tablero.  Y su alcance máximo es 13. 

Respecto a los _tests_, estos están bien, solo que el enunciado tenía un error. Una pieza explosiva es inválida cuando su `self.alcance` es mayor al alcance máximo, lo cual se traduce que no hay forma de poder solucionar esa pieza y por ello es inválida. Es lo mismo que estás haciendo tu, una pieza explosiva será valida si su `self.alcance` es menor o igual al alcance máximo.

Volviendo a tu ejemplo, si ese R8 fuera un R14, ahí si sería una pieza inválida, porque no será capaz de destruir la cantidad de celdas indicadas en dicho tablero.

Volviendo al enunciado, durante hoy o máximo mañana actualizaremos esa explicación y mandaremos un aviso notificando esta situación.

¡Muchas gracias por notar esto!
Saludosヾ(＾-＾)ノ

**Comment by oliviallanosj** [comment]
Hola, en este mismo caso, como voy a poder saber el alcanze maximo si no se la posición donde esta la pieza explosiva?
es decir en este mismo ejemplo: 
lista_tablero = [
        ["--", "--", "--", "--", "--"],
        ["--", "PP", "PP", "--", "H4"],
        ["--", "--", "PP", "--", "--"],
        ["--", "--", "PP", "V5", "--"],
        ["--", "R8", "PP", "--", "--"]]
depende donde este la pieza R8 para saber su alcanze maximo.
si la pieza estuviera en esta posición, su alcanze maximo seria distinto(por la cantidad de celdas en la diagonal)
 = [
        ["--", "--", "--", "--", "--"],
        ["--", "PP", "PP", "--", "H4"],
        ["--", "--", "PP", "--", "--"],
        ["--", "--", "PP", "V5", "--"],
        ["R8-", "--", "PP", "--", "--"]]

**Comment by Hernan4444** [comment]
Hola @oliviallanosj 

Tal como indicas, el alcance máximo de una pieza puede cambiar según su posición, pero recuerda que en esa _ property_ debes contar la cantidad de piezas explosivas inválidas del tablero, es decir, tienes acceso al tablero. Dado que tienes acceso a él, puedes ir recorriendo el tablero y sabiendo en qué posición está cada elemento que estás consultando.

Saludosヾ(＾-＾)ノ
