### ISSUE TITLE
Duda sobre Menú de Contactos si se ingresa el input VOLVER_FRASE

### ISSUE THREAD

**Issue by matiasparodic** [IIC2233/syllabus#72]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

Hola! Tengo una duda sobre lo que dice el enunciado si es que se ingresa como mensaje la palabra "VOLVER_FRASE". El enunciado dice que si es que esto ocurre, se debe volver al menú anterior con el listado de contactos, pero no sé a qué se refiere con esto.

**Comment by matiasparodic** [comment]
Entonces no es que tenga que volver a Menú de Chats, sino que tengo que volver a desplegar la lista de contactos?
Y ahí termina? o debo volver a pedir que elija un contacto y todo eso?

**Comment by Tsbalart** [comment]
Se supone que no debería terminar a menos que se seleccione "salir" en algun menu. Debes volver a mostrar la lista de contactos con la opción de volver a  elegir un contacto y la opción de volver al menú de chats.

**Comment by matiasparodic** [comment]
Buenísimo!

Muchas gracias! Te pasaste
