### ISSUE TITLE
Header CSV a Kwargs

### ISSUE THREAD

**Issue by Kitaps** [IIC2233/Syllabus#72]
Hola, lo que quiero hacer es pasar el header de los CSV a Keys para usar estos como Kwargs de las clases, pero no logro encontrar como hacerlo ya que en todos lados se recomienda usar la librería CSV, que tenemos prohibido usar.

Quiero hacer esto para no tener que hacer manualmente.
Porque lo que haría manualmente sería:
Separar el header
Ver en que segmento de la lista está cada key
Guardar el numero de cada key

Luego para cada parte la separaría igual que el header
luego para cada key una variable auxiliar que toma el lugar de la lista
limpiar
crear el objeto con las variables auxiliares.

Pero debe que haber una mejor forma de hacerlo no?

**Comment by sebacruzd** [comment]
Lo que dices en el primer párrafo es lo que deberías hacer exactamente si quieres usarlos así. No es necesaria la libreria csv para agarrar los argumentos.

Con lo que dices en el segundo párrafo te debería funcionar.
Utiliza el header y keys de la manera que dices.

Tip: Cómo puedes relacionar las keys a las posiciones de un elemento en una lista?

**Comment by Kitaps** [comment]
ya wena, 
tnx
