### ISSUE TITLE
Trabajadores ocupados durante una defensa

### ISSUE THREAD

**Issue by fjhuanca** [IIC2233/syllabus#72]
Hola! En caso de que una civilización defendiendo llegue a necesitar a sus trabajadores, **¿se daña también a los trabajadores ocupados en otras labores?** Es decir, si tengo trabajadores recolectando recursos y/o construyendo edificios, **¿se dañan? y de ser así y mueren, ¿qué ocurriría con los edificios en construcción?**

**Comment by Oisangui** [comment]
yo no los dañaría, porque están ocupados como los soldados

**Comment by Oisangui** [comment]
lo que yo haría sería, luego de asignación de daño, ver cuantos trabajadores quedan, y borrar acciones pendientes que no puedan seguir cumpliendose por falta de trabajadores, como obtención de recursos y construcción

**Comment by jeschuwirth** [comment]
Saludos, en cuanto a la recolección de recursos, la siguiente issue habla es acerca del tema. #38 

Como para los edificios en construcción tampoco esta explicito en el enunciado, queda igualmente a tu criterio. Es recomendable explicitar en el readme los supuestos que utilizaste para evitar problemas.

Si sigues con dudas, o no te quedo claro eso de explicar los supuestos sigue comentando la issue.

Suerte!

**Comment by fjhuanca** [comment]
Ok muchas gracias, me queda claro
