### ISSUE TITLE
Duda simulacion

### ISSUE THREAD

**Issue by anavarro01** [IIC2233/Syllabus#72]
Tengo una duda con el tema de simulación y la fecha que ingresa el usuario.
Supongamos que en una fecha X se simula la estrategia de extinción para el incendio Y.
Luego, el usuario ingresa la fecha Y - 5.

1) Si pide encontrar la estrategia de extinción para el mismo incendio y, como lo ingreso antes de que se aplique la estrategia, debería estar encendido. Entonces el programa debe encontrar otra estrategia para ese incendio? o debe decir que va a ser extinto en un futuro? Porque puede incluso puede que la forma mas rápida de extinguir el fuego en el día Y - 5 sea mas de 5 días y sea imposible de apagar sin que coincidan las fechas de las estrategias

2) Si el usuario consulta por los incendios apagados este no debería estar dentro de ellos cierto?

**Comment by rpalmaotero** [comment]
Hola,

1. Si se calcula una estrategia en el tiempo `t_0`, y luego el usuario ingresa algún tiempo `t_1 < t_0`, puedes considerar que la estrategia en `t_0` no existe.
2. Continuando el punto anterior, como la estrategia en `t_0` no existe, el incendio no está apagado.

**Comment by jorgeriesco** [comment]
1. puedo considerar que si existe?

**Comment by acrojas2** [comment]
entonces si es que apagara un incendio en t_0 cuando ingreso un t_1<t_0 el incendio reaparece?

**Comment by rpalmaotero** [comment]
@acrojas2 claro.

**Comment by asdegoyeneche** [comment]
Pero el problema estaría en que si la estrategia enviada en ```t_1``` apaga el incendio antes de ```t_0``` , porque en ```t_0``` se contradeciría el punto 5 del enunciado, en donde se menciona:

> No pueden movilizarse recursos cuya hora de llegada al incendio sea mayor a la hora en la que se extinguió el incendio.

Porque quien ingresa en ```t_0``` mandaría a movilizar recursos a un incendio ya apagado. Nose si me explico.. 

Saludos!

**Comment by pizquierdo2** [comment]
Me sumo a la pregunta de Alfredo.

Por otra parte, ¿Es posible poner la restricción de que cualquier fecha y hora que se ingrese sea mayor (posterior) a la última fecha de ingreso? Eso no sólo es una excelente forma de solucionar los problemas de integridad del modelamiento, sino que también hace que el problema planteado se aproxime más al de un programa funcional que está siendo usado por personas reales. 

Consideremos t0<t1 puntos del tiempo real. En la realidad nunca ocurrirá que si en t0 un usuario escribe como hora y fecha de ingreso t1’, después en t1 otro usuario escribiera como hora y fecha de ingreso t0' (con t0'<t1'). Pués de hecho t0=t0' y t1=t1' a menos que los usuarios estén mintiendo. Luego, no considerar la restricción propuesta implica no cerrar una posibilidad en la que es necesario que alguno de los usuarios mienta. Entonces, ¿Por qué no la consideraríamos, si lo que queremos son casos en los que nuestros usuarios no mientan?

**Comment by DiegoAndai** [comment]
@pizquierdo2 sobre tu duda, no, no se puede restringir. Ya que te pones en un hipotético caso real, si fueras a hacer un programa de registro, tienes que ponerte en el caso de cualquier imprevisto. Imagínate que en t0 se mide un incendio y se registra su magnitud. Luego en t1 se dan cuenta que la medición está mala. Ya que todos tus cálculos dependen del estado del incendio en t0, vas a tener que meterte al sistema, y sobre escribir los datos.

**Comment by TamaraCucumides** [comment]
@DiegoAndai qué pasa al final con lo que pregunta Alfredo?

**Comment by rpalmaotero** [comment]
@asdegoyeneche No está definido por lo que queda a tu criterio.

**Comment by asdegoyeneche** [comment]
@rpalmaotero perfecto, me parece, gracias!

**Comment by B-Dominguez** [comment]
Hola, en el caso de que genere una estrategia en t_1, luego ingrese al programa en una fecha t_0 < t_1 por lo que se borra tal estrategia, y finalmente vuelvo a ingresar en t_1 o en t_2 > t_1, asumo que el programa no debe recuperar la estrategia previamente calculada, cierto?
porque si se tuviera que volver a considerar, podría generar problemas con nuevas estrategias calculadas en t_0. 
Gracias!

**Comment by Hernan4444** [comment]
@B-Dominguez queda a tu criterio c:
Sobre el recalculo de datos, si está correctamente modelado, cada vez que se viaja al pasado, los cálculos no deberían ser un problema de eficiencia.

Saludos!
