### ISSUE TITLE
Consulta sobre el alcance de bombas cuando hay bombas en el camino

### ISSUE THREAD

**Issue by ignaverb** [IIC2233/Syllabus#72]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/21)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/20)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola!
Tenía la duda sobre el caso de tener bombas que se afecten entre sí en el tablero, como por ejemplo,
tablero = [
    ["-", "-"],
    [2,2]
]
En ese caso, se dríria que ambas bombas están afectando 3 casillas (afectan las casillas con bombas) o solo 2 (solamente afectan las casillas vacías.

Saludos y gracias!!!

**Comment by Hernan4444** [comment]
Hola @ignaverb 

Recuerda que la primera regla del foro es ver si alguien más preguntó esto 😄 . Si revisas la issue #24 (que fué referenciada en el compilado #21 ) verás que alguien ya preguntó sobre esto mismo que si las bombas afectan las casillas de otra bomba para contar su alcance.

Saludos c:

**Comment by cegalleta** [comment]
Hola!!

La definición que dimos es que las bombas afectan a su propia casilla y las casillas con la que compartan fila y columna, por lo tanto, cada una de esas bombas afecta a 3 casillas y las soluciones serían poner una tortuga en cualquiera de las celdas vacías. 

Avísame si encuentras alguna contradicción!

**Comment by ignaverb** [comment]
Hola, pero entonces en el ejemplo que mande no tendr;ia solucion cierto? por que quedarían dos tortugas juntas con tal de que ambas bombas tengan alcance 2 o no?

**Comment by ignaverb** [comment]
@Hernan4444 Se me había ido revisar más abajo, mil disculpas!

**Comment by Hernan4444** [comment]
@ignaverb no hay drama, solo lo indicamos para que tengan precausión en las siguientes issues :)

Sobre tu duda del tablero: efectivamente es un tablero que no tiene solución. 

Saludos c:
