### ISSUE TITLE
Uso de autopep8 para modificar codigo para que sea consistente con PEP8

### ISSUE THREAD

**Issue by Unknomads** [IIC2233/Syllabus#72]
Hola.
Leí en este link: https://stackoverflow.com/questions/14328406/tool-to-convert-python-code-to-be-pep8-compliant , que se puede usar una herramienta llamada autopep8 para convertir y arreglar todo el código para que sea consistente con  las reglas de PEP8. Mi pregunta es si es legal si uso este tool.
Saludos!

**Comment by Arcoirisky** [comment]
Hola! No es para nada ilegal pero, no te sugiero confiarte mucho en eso. Si el ayudante encuentra variables poco descriptivas, snake_case, entre otros, puede descontar por PEP8 de todas formas o:!
