### ISSUE TITLE
Ejercicio propuesto 3.3 semana 9 

### ISSUE THREAD

**Issue by Araos827** [IIC2233/syllabus#720]
Hola! estuve tratando de cambiarle el color a un QPixmap pero no lo logré y tampoco encontre referencia util :(. Como se usa el metodo fill para que funcione correctamente? sobre el pixmap vacio? sobre el pixmap con una foto? hay que importar algun modulo especial quizas? si me pudieran dar un ejemplo lo agradeceria, saludos!

**Comment by moquezada** [comment]
Hola @Araos827!

¿Estás utilizando solo un QPixmap o tienes un QLabel al cual seteas el QPixmap creado? 👀

**Comment by Araos827** [comment]
Trate con ambas cosas, y ninguna me funcionó D:

**Comment by moquezada** [comment]
¿Y puede ser posible que no le estés asignando un tamaño al QPixmap al momento de instanciarlo?

**Comment by Araos827** [comment]
hmmm al pixmap no le asigne un tamaño, si al label que lo contiene

**Comment by Araos827** [comment]
el pixmap lo insancie vacio, sin ningun arugumento, trate de hacerle setGeometry pero no tiene ese metodo

**Comment by Araos827** [comment]
import sys
from PyQt5.QtWidgets import (QApplication, QWidget, QLabel, QVBoxLayout, QHBoxLayout)
from PyQt5.QtGui import QPixmap, QColor
from PyQt5.QtCore import Qt

class MiVentana(QWidget):
    def __init__(self):
        super().__init__()
        self.inicializa_gui()

    def inicializa_gui(self):
        self.setGeometry(300, 300, 500, 500)
        self.setWindowTitle('Teclado')

        self.label = QLabel("Blanco", self)
        self.cuadro = QLabel('', self)
        self.cuadro.setGeometry(225, 225, 100, 100)
        self.pixmap = QPixmap()
        self.pixmap.fill(Qt.white)
        self.cuadro.setPixmap(self.pixmap)

        self.cuadro.setScaledContents(True)
        vbox = QVBoxLayout()

        vbox.addWidget(self.label)
        vbox.addWidget(self.cuadro)
        vbox.addStretch(1)
        
        self.setLayout(vbox)

        self.show()

    def keyPressEvent(self, event):
        """
        Este método maneja el evento que se produce al presionar las teclas.
        """
        if event.text() == "v":
            self.label.setText("Verde")
            self.pixmap.fill(Qt.green)
            self.cuadro.show()
        elif event.text() == "a":
            self.label.setText("Azul")
            self.pixmap.fill(Qt.blue)
        elif event.text() == "r":
            self.label.setText("Rojo")
            self.pixmap.fill(Qt.red)
        elif event.text() == "b":
            self.label.setText("Blanco")
            self.pixmap.fill(Qt.white)


if __name__ == '__main__':
    app = QApplication([])
    ex = MiVentana()
    sys.exit(app.exec_())

**Comment by moquezada** [comment]
Puedes intentar asignarle un tamaño al QPixmap de la forma `pixeles = QPixmap(100, 100)` y luego setearlo en un QLabel adecuadamente 🧙 Ten en cuenta que QPixmap representa un conjunto de pixeles y si no le asignas un tamaño es como si "no tuvieses nada" . Puedes encontrar más información al respecto en la documentación de Qt [aquí](https://doc.qt.io/qt-5/qpixmap.html#details).

Recuerda no compartir explícitamente tu código de los ejercicios 👀 La idea es que todos los realicen por su propia cuenta y así puedan sacarle el mejor provecho posible. Siempre puedes escribir pseudo-código o ejemplos que aludan a tu implementación pero que no revelen tu solución :)

Si sigues con dudas comenta esta misma issue!

**Comment by Araos827** [comment]
Gracias!!
