### ISSUE TITLE
Duda QtDesigner

### ISSUE THREAD

**Issue by fpattillo** [IIC2233/Syllabus#720]
Hola!
Hice una versión estática tanto de la interfaz principal como del editor para conectarlos manualmente, pero cuando conecto el botón editar con una nueva ventana de edición, aparece por un instante y se cierra sola. La interfaz ppal. es un QMainWindow y la ventana de edición es un QWidget.
Adjunto foto con mi código!
![captura de pantalla 11](https://user-images.githubusercontent.com/37159447/41474413-e61a8054-7089-11e8-85ef-804cd4a204b4.png)

**Comment by nachocontreras** [comment]
Hola!

Prueba con:
```
self.edit_window = Editor()
self.edit_window.show()
```
Y dime si te funciona

**Comment by fpattillo** [comment]
Perfecto, gracias!
