### ISSUE TITLE
¿Puede subir imágenes nuevas desde su computador el usuario?

### ISSUE THREAD

**Issue by vixolo** [IIC2233/Syllabus#720]
En el enunciado se da a entender que los clientes pueden subir sus propias imágenes para editarlas en el programa, pero ni en el _dashboard_ ni en ninguna parte aparece de nuevo. Tendríamos que incluir en el dashboard (por ejemplo) un botón "Subir imagen" que abriera un diálogo donde la puedan buscar en su computador? O algo por el estilo?

En la respuesta que dieron a la #713 me dio la impresión de que teníamos que solamente trabajar con las imágenes que nos dieron.

Muchas gracias,
Vicente.

**Comment by FernandoPieressa** [comment]
Hola! Efectivamente se debe poder abrir imágenes propias desde el cliente y cargarlas al servidor. La idea de las imágenes entregadas fue para asegurarnos que tengan imágenes donde estemos seguros de que tiene 1 IDAT. Podrían simular por ejemplo que algunas de las imágenes que les dimos no están en el servidor y que un cliente las quiere subir. Ahora, respecto a como se hace para subirlas, como no esta especificado queda a su criterio si es un botón o otra cosa.

Saludos!

**Comment by behrmann97** [comment]
Podemos asumir que las imagenes que suba son 1 IDAT?

**Comment by Hernan4444** [comment]
@behrmann97 si, puedes asumir eso.

Saludos ✌️
