### ISSUE TITLE
problema con jupyter notebook

### ISSUE THREAD

**Issue by betolguin** [IIC2233/syllabus#720]
Hola! realmente nose que pasó pero estaba leyendo los contenidos en jupyter, luego abrí los contenidos de otra semana y me aparece error de que el comando jupyter no existe, es muy raro, instale nuevamente jupyter pero me sigue apareciendo el mismo error..
si alguien me pudiera ayudar lo agradeceria muchoo!!

**Comment by aaossa** [comment]
Hola @betolguin , la verdad me parece bien raro tu problema. ¿Podrías revisar si cerrando todos los jupyter y la consola y luego abriendo nuevamente funciona? Si sigue sin funcionar, especifica tu sistema operativo 👌, pero ojalá sea suficiente con lo primero.

PS: No borres la plantilla, en la misma se pide que no lo hagan para que tengamos certeza de que sigan los pasos pedidos 👀

**Comment by betolguin** [comment]
Hola! lamentablemente no funcionó, mi sistema operativo es windows... y es super raro ya que lo estaba usando perfectamente y como escribí anteriormente intenté abrir contenidos de otra semana y me comenzó a salir el error... :(
feliz si me puedes escribir por discord para que lo podamos arreglar más rápido :)
usuario discord: betolguin#2199

**Comment by betolguin** [comment]
🆘

**Comment by aaossa** [comment]
Disculpa, se me pasó responderte nuevamente. ¿Puedes colocar una captura del *output* de escribir `pip install jupyter` (o el que sea que hayas utilizado) y luego inmediatamente escribir `jupyter notebook`? De casualidad, ¿qué consola utilizas (cmd, powrshell, otra)?

**Comment by betolguin** [comment]
<img width="960" alt="2020-10-20" src="https://user-images.githubusercontent.com/69482524/96632695-776bc500-12ee-11eb-8019-63215eadb7cf.png">
<img width="960" alt="2020-10-20 (1)" src="https://user-images.githubusercontent.com/69482524/96632710-7e92d300-12ee-11eb-9390-15df0c54b1f6.png">

espero que se hayan subido bien las imágenes!
quedo atento cualquier cosa
saludos

**Comment by aaossa** [comment]
¿Podrías probar con los siguientes comandos?

* `pip install --upgrade --force-reinstall jupyter`, para forzar la reinstalación de Jupyter
* `jupyter notebook`, y si no pasa nada con ese comando utiliza uno de los siguientes
* `python -m jupyter notebook` o `py -m jupyter notebook`

Al parecer lo que instalaste no etá en el PATH y no puedes acceder por medio de comandos 🤔 Lo raro es que antes si pudieras hacerlo, quizás se perdió con alguna nueva instalación. ¿Instalaste alguna versión de Python recientemente?

**Comment by betolguin** [comment]
ahí me funcionó con reinstall :) y respecto a la pregunta antes de instalar Pyqt5 salia que debía hacer un upgrade, quizás fue eso lo que produjo el error..
gracias por la ayuda!!
saludos

**Comment by aaossa** [comment]
Yay, que bueno 🙌 ¡Mucho éxito ✨!
