### ISSUE TITLE
Pipreqs, paso 7, variables d eentorno

### ISSUE THREAD

**Issue by maxjosecr** [IIC2233/Syllabus#720]
Hola, revisé todas las issue parecidas y ninguna me sirvió, hago una nueva porque no se como re-abrir las otras. 

El pipreqs no me funciono, ponía pipreqs path y me respondia: Usage:     pipreqs [options] <path>
Asique lo hice a mano, puse: Flask==0.12.2 

Ayer cuando setee las variables de entorno me funciono, hoy lo puse denuevo porque parti de cero y me dice:  !    Couldn't find that app.

Todas las veces que intente pushear a heroku me tiraba error, adjunto pantallazo
![image](https://user-images.githubusercontent.com/26102093/27518614-100320c8-59b2-11e7-855e-84a66c74d032.png)

**Comment by rpalmaotero** [comment]
Especificaste en el `runtime.txt` la versión de Python que aparece en el enunciado?

**Comment by maxjosecr** [comment]
si, pero puse la version que yo tengo: python-3.5.3, pongo la del enunciado?

**Comment by maxjosecr** [comment]
probe con la del enunciado y aun así me dice:  !    Couldn't find that app.

**Comment by nivek0o0** [comment]
@maxjosecr  debes actualizar tu repositorio al nombre de tu nueva aplicacion con
`heroku git:remote -a nombre_de_tu_nueva_aplicacion`
