### ISSUE TITLE
duda con Creacion de "n" imagenes

### ISSUE THREAD

**Issue by felipehen** [IIC2233/syllabus#721]
En mi codigo, al cargar "mapas.csv", lo que hice fue traspasar toda la informacion del archivo a una lista de listas, donde cada "mini-lista", contiene la información de una linea de "mapas".

Pero, dado que hay que agregar una imagen por cada linea de mapas, y el len de mapas es variable, no estoy seguro como podría crear n self.nombre = Qlabel, y que estas sean distintas entre si.

**Comment by kadroguett** [comment]
Hola @felipehen 
Una forma de hacer n labels que sean diferentes entre si es crearlas en un loop y almacenarlas en un diccionario o una lista, si realizas un print(diccionario) o print(lista) notarás que los Qlabels son diferentes.

**Comment by lewebe** [comment]
Y cómo entrego esa lista de QLabels y las defino dentro de mi ventana? Porque hacer un
```python
for qlabel in lista_qlabels:
    self.label = qlabel
```
solamente reescribiría el atributo ```self.label``` y al final de la iteración me quedaría con que este atributo corresponde al último QLabel de la lista. Cómo hacer que se creen distintos atributos con distintos nombre y a cada uno de ellos asignarle un QLabel distinto de mis n QLabels?

**Comment by kadroguett** [comment]
Hola @lewebe 
Para definir un Qlabel dentro de la ventana existen diferentes métodos, como las grillas o bien asignarle una posición utilizando la función move(int, int).
Por ejemplo en ese loop puedes agregarle un Qpixmap diferente a cada Qlabel y ubicarlos en posiciones diferentes utilizando cualquiera de los métodos mencionados anteriormente, sin necesidad de que cada uno tenga un nombre en particular.

**Comment by lewebe** [comment]
O sea, puedo nombrarlos todos como atributo ```self.label``` dentro de mi clase Ventana y no se van a sobreescribir?

**Comment by kadroguett** [comment]
Si, pero si deseas modificarlos en algún momento deberás almacenarlos en un diccionario o una lista
