### ISSUE TITLE
Mensajes Antiguos Telegram

### ISSUE THREAD

**Issue by egromero** [IIC2233/Syllabus#721]
Holaa, Tengo un problema de que telegram está constantemente enviandome los mensajes anteriores, por lo que recibe respuesta de comandos que ya fueron ejecutados.
Contextualizo: Antes de programar el servidor para que entendiera el metodo /get #numero había mandado mensajes del estilo "asfg" "/get 9" y cosas así, la cosa es que ahora que tengo el server arriba, telegram sigue mandando esos mensajes y mi programa procesandolos, cual es la forma correcta de decirle a telegram que ya no envíe mensajes anteriores? 

Gracias!

**Comment by legramsch** [comment]
Se me ocurren dos cosas:
la funciones del servidor Flask tienen que tener un return (Solo porque a Flask no le gustan las funciones sin return, eso decia en internet jaja), al menos eso me causaba a mi que la cosa se ejecutara una y otra vez y me mandaba 1000 mensajes

Lo otro es que cuando envias un mensaje de telegram, el webhook sigue mandando mensajes hasta que lo logra (y se rinde despues de un numero de veces), si re abres el servidor antes de que el webhook deje de intentarlo, al servidor le van a llegar varios post de telegram, llamando varias veces a la funcion.

**Comment by CheloRiveros** [comment]
No sé si colocar la solución en sí por que podrían tomarlo como soplar la tarea xD
Pero en sí la API de Telegram envía todas esas request porque tu programa en flask nunca le dice a la API que el mensaje efectivamente llegó, por eso la API sigue mandando y mandando continuamente las respuestas (después de ciertos intentos dejará de hacerlos, pero igual son muuuuuuuuuuchos)
Por eso, solo tienes que retornarle "algo" para que le confirmes que el mensaje llegó.
Ahora la tarea es buscar que es ese "algo".

Saludos!

**Comment by egromero** [comment]
Gracias a los dos!!

**Comment by B-Dominguez** [comment]
@CheloRiveros pero alguna pista? :) jajajaj por lo menos de si se hace con return, con flask.make_response o alguna opcion que aun no haya visto?

**Comment by egromero** [comment]
@B-Dominguez  me di cuenta que cuando "terminas" la solicitud, ya se deja de mandar los mensajes, es decir, tienes que darle una respuesta a telegram con alguno de sus metodos, al menos así me funcionó a mi
