### ISSUE TITLE
Pasos compuestos por el mismo tipo de flechas

### ISSUE THREAD

**Issue by Jamesmoreno21** [IIC2233/syllabus#721]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/327)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/326)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola! Mi duda es que si puedo asumir que un paso va a estar compuesto por el mismo tipo de flechas, es decir, si está en dificultad de aficionado, los pasos que vengan de a dos flechas deben ser del mismo tipo (2 Normales, 2 Doradas, etc...)
Gracias de antemano!

**Comment by knight-who-say-ni** [comment]
Hola @Jamesmoreno21 !!
Como no se especifica en el enunciado, si te acomoda puedes asumir que serán del mismo tipo. Si decides hacerlo así, recuerda mencionarlo en tu readme ;).

Saludos, y exito con la tarea!!

**Comment by Jamesmoreno21** [comment]
De acuerdo! Muchas gracias!

**Comment by knight-who-say-ni** [comment]
Holaa! Recuerda no cerrar las issues, ya que puede haber alguien con una duda parecida 😅.
