### ISSUE TITLE
Galería Dashboard - Actualización Bloqueadas

### ISSUE THREAD

**Issue by B-Dominguez** [IIC2233/Syllabus#721]
Holaa,

En el modo espectador, el cliente debe poder ver los cambios en la imagen en tiempo real. Es esto necesario también en la galería del dashboard? Es decir, debe actualizarse la imagen del dashboard marcada como bloqueada cada vez que se le realiza el cambio? O se actualiza cada vez que el usuario ingresa al dashboard.

Graciaaas!

**Comment by FernandoPieressa** [comment]
Hola! Basta con que se actualice en el modo espectador, el dashboard no hay problema si se actualiza solo cuando se ingresa.

Saludos!

**Comment by B-Dominguez** [comment]
Perfecto gracias!
