### ISSUE TITLE
Bonus Nota Simultáneas 

### ISSUE THREAD

**Issue by llloyola** [IIC2233/Syllabus#721]
¿Para este bonus, se deberá poder reproducir cualquier archivo _MIDI_ descargado de internet o algo por el estilo? Pregunto porque me puse a experimentar con un _MIDI_ descargado de internet y algunos de sus valores no me calzan con los del enunciado. Por ejemplo, de la primera nota del primer canal obtuve la siguiente información
```{'tiempo': 0, 'tipo': 255, 'nota': 81, 'intensidad': 3}```
Sin embargo, en el enunciado se especifica que:
- el tipo es 144 o 128
 - la intensidad es 8, 20, 31, 42, 53, 64, 80, 96, 112 o 127

¿Es posible que haya obtenido esos datos habiendo hecho todo bien o me equivoqué en el proceso? ¿Esos valores predefinidos para Tipo e Intensidad sólo pueden ser estrictamente esos valores? ¿Por qué sólo esos valores?

**Comment by Hernan4444** [comment]
@llloyola lo que pasa es que nosotros simplificamos el proceso del MIDI, por lo tanto es dificil que uno descargado de intener funcione. Para el bonus solo queremos que puedas crear desde la interfaz una canción con 2 o más canales. El fin de semana subiré un ejemplo de un midi con 2 canales para que puedas probar.

Saludos ✌️

**Comment by llloyola** [comment]
Aaaaaaah... Entonces el bonus está orientado a que el usuario pueda crear canciones con más de un canal? Pensé que probarían nuestra tarea con cualquier _MIDI_ o algo por el estilo jaja

**Comment by Hernan4444** [comment]
Nah jajajaj tranquilo. Vamos a probar con _MIDI_ que tengan 2 canales pero que fueron creados de la misma forma que debiste haberlos creado tu.

**Comment by llloyola** [comment]
Ya me estaba asustando con todo lo que leí en internet sobre qué cosas puede hacer un _MIDI_, pensando que tenía que hacerlo para el bonus jajja Gracias! :)

**Comment by Bipavez** [comment]
Para añadir,
¿Se cuenta como notas simultáneas tocar un acorde (de dos notas o mas)? ¿O tiene que ser a través de canales distintos?

**Comment by Hernan4444** [comment]
@Bipavez tiene que ser a traves de canales distintos.

![image](https://user-images.githubusercontent.com/15641721/41500794-4bdf0d38-7166-11e8-950a-b4e0283d2cf3.png)

El fín es que se pueda reproducir algo así en la interfaz.

Saludos ✌️

**Comment by Bipavez** [comment]
Gracias! c:
