### ISSUE TITLE
Error 403: 'dailyLimitExceeded'

### ISSUE THREAD

**Issue by fantineen** [IIC2233/Syllabus#722]
hola mi problema actual es que el api de google me arroja error porque supuestamente ya alcancé el límite de búsquedas, pero entiendo que según lo que dice la documentación, numéricamente aún no he llegado al límite por día. Creo que el problema partió cuando envié un request de search de algo que nunca me devolvió nada, entonces no se si se siguió mandando request por abajo hasta el infinito (aka hasta dejarme sin mas requests disponibles). Si es esto último, cuando intente realizar búsquedas mañana, me va a funcionar, sino como lo arreglo o aborto las busquedas fallidas?

**Comment by nivek0o0** [comment]
Yo tengo el mismo problema, solo que el error además incluye 
`Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.`
Y llevo el día completo buscando como autentificarme. Creé desde la consola de deevlopers de Google un id de OAuth 2.0 pero no encuentro cómo entregarlo en la request.

**Comment by mbfuster** [comment]
#no soy ayudante
A mi también me salía pero lo arreglé dentro del url al que le hago el get, un numero definido de busquedas(en mi caso solo puse 1) e inclui también una variable con la 'key' que te dan al hacer un proyecto en google, ademas del id del costume search machine y de la query (q).

**Comment by iqacevedo** [comment]
Hola

Si aún tienen problemas con la api de Google, pueden usar el explorador de APIs de Google entregándole parámetros de búsqueda para que les genere un url que debería ser el que ustedes enviarían en su consulta, junto con el Response de la API. De esta manera pueden fijarse que los urls que están enviando estén bien escritos y no tengan parámetros que le faltan o parámetros de más que provoquen este tipo de errores.

[Este es el link](https://developers.google.com/apis-explorer/?hl=es#p/customsearch/v1/search.cse.list)

Saludos !
