### ISSUE TITLE
Duda sobre QThreads

### ISSUE THREAD

**Issue by En-clases** [IIC2233/syllabus#722]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola, tengo 2 dudas relacionadas con la materia de QThreats.
- Creé una ventana que posee el evento ```KeypressEvent``` el cual, al ser activado, crea una instancia de una clase que hereda de QThread. el método ```run``` de esta instancia hace que se cree un label con una imagen por 1 segundo en la ventana, luego, el label se oculta. Sin embargo, cada vez que apreto una tecla y se hace ```run``` de la clase que se instanció, me aparece el siguiente mensaje:
```QObject::setParent: Cannot set parent, new parent is in a different thread```
Cabe destacar que todos los métodos de la clase funcionan correctamente, es decir, se muestra y oculta la imagen en la ventana.

- Por otro lado, **existe una forma de eliminar los QThreats que ya cumplieron su función pero siguen ejecutandose?** Por ejemplo: En el último ejemplo de la materia de la semana 10, en el archivo ```1-pyqt-qthreads.ipynb```, se escribe el código de una ventana en donde aparecen imágenes cada cierto tiempo y estas se van moviendo hasta salir de los límites de la ventana. Sin embargo (creo) el QThread de una imagen que ya esta fuera de los límites de la ventana sigue activo aunque no esté haciendo nada.

**Comment by furcelay** [comment]
Hola @En-clases !

Respondiendo a tus dudas:
*  Los QObjects tienen una jerarquía dada por el atributo `parent`, cada uno puede tener un *parent* que indica que está contenido dentro de este *parent*. El problema es que PyQt5 no controla que la información se mantenga actualizada de manera segura entre *threads* a menos que le especifiques cual es su *parent*. Entonces, en resumen, para que no te de ese error debes incluir el *parent* cuando inicializas el QThread, es decir `super().__init__(parent=ventana)` en el `__init__()` de la clase que creaste donde `ventana` es la ventana que inicializa a éste objeto.

*  Los QThreads terminan cuando acaban de ejecutar su método `run` de manera similar al caso de los `threads` normales. Si quieres que termine antes su ejecución debes incluir una condición de salida o una señal. Aunque si el método `run` es algo como:
```python
def run(self):
    while condicion:
        sleep(tiempo)
        self.hacer_algo()
```
Éso es lo mismo que hacer un QTimer que además poseen un método `stop()` para detener el thread entre intervalos.

Por último, como comentario de opinión personal, la manera en que estás creando el label quizás no es la mejor en lo que respecta a la separación *front-end* y *back-end* ya que la clase del thread parece ser del *back-end* pero se encarga de crear el label, lo mejor sería que éste le envíe la información al *front-end* para que cree el label por su cuenta y luego los datos para actualizarlo (mejor aún si ese label lo manejas como una clase).

**Comment by En-clases** [comment]
Muchas gracias por la respuesta! 
Eso si, sigo teniendo problemas con ```super().__init__(parent=ventana)``` 😢. 
Si instancio la clase Ventana (```ventana =  Ventana(...)```) desde el mismo archivo en donde tengo escrito el código, es decir, sin importar nada (solo las librerías), el mensaje que me aparece es el mismo de antes: ```QObject::setParent: Cannot set parent, new parent is in a different thread```.
Si importo la clase ```Ventana``` a un archivo main.py con ```from archivo... import Ventana```, y la instancio al igual que en el caso anterior pero en main.py el mensaje es distinto. Cuando intento hacer ```run``` me aparece: ```line 85, in __init__
    super().__init__(parent=ventana)
NameError: name 'ventana' is not defined```
Al parecer no se reconoce la instancia de ventana que realicé.
Desde ya muchas gracias!

**Comment by furcelay** [comment]
Creo que no estás dándole correctamente el atributo. El valor de `ventana` para `super().__init__(parent=ventana)` debes pasarlo como argumento al `__init__` de la clase y no como una variable global, te pongo un ejemplo muy simplificado:
```python
class MiQThread(QThread):
   
    def __init__(self, ventana):
        super().__init__(parent=ventana)
        self.start()

    def run(self):
        pass


class MiVentana(QWidget):

    def __init__(self):
        super().__init__()
        self.mi_qthread = MiQThread(ventana=self)


if __name__ == '__main__':
    app = QApplication([])
    mi_ventana = MiVentana()
    mi_ventana.show()
    app.exec_()
```

**Comment by En-clases** [comment]
Ahí si me funcionó 🤟 , gracias!!
