### ISSUE TITLE
Silencios aislados

### ISSUE THREAD

**Issue by mramirez7** [IIC2233/Syllabus#722]
Hola, por lo que entendí para producir un silencio el usuario debe ingresar nota == '0' e intensidad == '0', que pasa en el caso de que la intensidad sea 0 pero  nota != 0 ó viceversa? serían errores o los tomo como silencios?

**Comment by Hernan4444** [comment]
Hola, eso de `nota == '0' e intensidad == '0', ` es para el manejo de bytes. Como se ingresa un silencio por parte del usuario queda a su criterio. Pueden hacer que sea un botón, cuando ingresa un dato en especifico, etc. Solo tiene que asegurarse de asegurar que sea un silencio válido según el formato que ustedes deciden.
