### ISSUE TITLE
duda self.init_gui()

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2233/syllabus#722]
Hola me gustaria saber cuando usar y cuando no usar este comando en el init. Tambien saber cuando debo crear un metodo con este nombre.

**Comment by dsepulveda3** [comment]
Es como definir que va a ser lo que se va a "imprimir" si es que pongo self.show?
Tipo
class VentanaInicial(QWidget):
    def __init__(self, *args):
        super().__init__(*args)
        self.crear_pantalla()
significa que cuando ponga self.show en alguna funcion dentro de la clase VentanaIncial() se me va a mostrar lo definido el el metodo crear_pantalla()??

**Comment by moquezada** [comment]
Hola @dsepulveda3 :)

El método `init_gui` sirve principalmente para encapsular de mejor formar todo lo relacionado con las características que le das a tu QWidget. Además, el tener este método aparte y no colocar toda la inicialización en el init te permite decidir "cuando" darle todas estas características a esta ventana 👀 Quizás te encuentres en la situación de que realmente no quieres inicializar la ventana de forma inmediata al crear la instancia.

Considerando lo anterior, el saber cuando usar este método en el init dependerá del flujo de tu programa. Si realmente no quieres que la ventana se muestre inmediatamente y necesitas **esperar que otra acción termine previamente**, entonces quizás lo mejor sea que el `init_gui` no se encuentre en el init de tu QWidget 😲 Por otra parte, si necesitas que tu QWidget se muestre inmediatamente entonces puedes agregar dicho método en el init! En resumen, depende de como establezcas tú el control de flujo respecto a las necesidades de tu programa :)

Por las mismas razones dadas anteriormente, en general es bueno crear este método para realizar la inicialización de los atributos ya que así obtienes un mejor encapsulamiento y mayor versatilidad 😄 

Saludos!
