### ISSUE TITLE
Error con heroku (o la app ?)

### ISSUE THREAD

**Issue by Okhan97** [IIC2233/Syllabus#723]
Hola buenas, setee el webhook del bot  al link que aparece ahi, hice add , commit y push con heroku, pero cada vez que intento hacer heroku logs se me sigue repitiendo este error:
![image](https://user-images.githubusercontent.com/26289334/27519854-16b554c2-59cb-11e7-83e2-c3a1edffc886.png)

El problema dice que no hay app en mi main, pero mi main tiene esto: 
![image](https://user-images.githubusercontent.com/26289334/27519895-9a956cc8-59cb-11e7-8d30-86e8dc963929.png)

Entonces pensé que el problema era del otro modulo, pero ahi tengo:
![image](https://user-images.githubusercontent.com/26289334/27519898-a81659d4-59cb-11e7-8075-4d91c121d462.png)

No se que es lo que tengo mal, ayuda D:

**Comment by nivek0o0** [comment]
#678 espero que eso solucione tu problema

**Comment by Okhan97** [comment]
@nivek0o0 Hice eso mismo, pero efectivamente no es mi problema u.u

**Comment by ftvannievelt** [comment]
a mi me pasaba lo mismo. No se por que, pero me funciona sin problemas si no le pongo el app.run() ni el if __name__...
