### ISSUE TITLE
Por qué definen dos veces una property en un ejemplo?

### ISSUE THREAD

**Issue by Zenos-Paradox** [IIC2233/syllabus#723]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda
En uno de los ejemplos de la carpeta 1 de los contenidos de la semana 10, definen una propiedad privada y luego la definen de nuevo? Estoy confundido. Cuando definen self.posicion  después de self.__posicion, no está definido como property aún. Por qué definirlo dos veces?
(El código que incluyo está recortado para mostrar poco más las referencias a la duda)
```python
class Comida(QThread):

    actualizar = pyqtSignal(QLabel, int, int)

    def __init__(self, parent, limite_x, limite_y):
        """
        Una Comida es un QThread que movera una imagen de comida
        en una ventana. El __init__ recibe los parametros:
            parent: ventana
            limite_x e limite_y: Los límites rectangulares de la ventana
        """
        super().__init__()

        # Guardamos los limites de la ventana para que no pueda salirse de ella
        self.limite_x = limite_x
        self.limite_y = limite_y
        # Seteamos la posición inicial y la guardamos para usarla como una property

        *self.__posicion = (0, 0)*
        *self.posicion = (randint(0, limite_x), randint(0, limite_y))*

        self.label.show()
        self.start()

    @property
    def posicion(self):
        return self.__posicion

    # Cada vez que se actualicé la posición,
    # se actualiza la posición de la etiqueta
    @posicion.setter
    def posicion(self, valor):
        self.__posicion = valor
        self.actualizar.emit(self.label, *self.posicion)
```

**Comment by aaossa** [comment]
Hola @Zenos-Paradox , creo que tu confusión se debe un poco al orden en que ocurren las cosas. Al momento de ejecutar ese código, cuando se define la clase, se declara que `self.posicion` será una *property*. Luego, al momento de instanciar la clase, se define el valor "privado" para `self.__posicion` y luego se utiliza `self.posicion = (randint(0, limite_x), randint(0, limite_y))`. Esta última línea invoca al *setter* de `posicion` (ya está definido, desde que se definió la clase) y es desde este método donde se cambia el valor del atributo "privado" y se emite la señal. En resumen, al momento de ingresar al `__init__`, la *property* ya está definida y simplemente la utilzamos 👌 Espero que quede más claro, pero si no es así pregunta por acá mismo. ¡Éxito con tu estudio 🤓!

**Comment by Zenos-Paradox** [comment]
aah entiendo. Gracias!

**Comment by aaossa** [comment]
Dejaré la *issue* abierta un tiempo por si le es de utilidad a alguien, así es más fácil de encontrar 🔍 . Después de un tiempo la cerraremos 😎

**Comment by Zenos-Paradox** [comment]
ah, ok.
