### ISSUE TITLE
Ejemplo de crear un IDAT

### ISSUE THREAD

**Issue by JPSF** [IIC2233/Syllabus#723]
En el enunciado dice:
_Siendo la misma imagen del ejemplo de IHDR, su formato descompri-
mido serı́a de dos filas, cada una con 7 bytes, representados por el RGB de cada uno de los pixeles más
el 0 porque no tiene filtro. Es por esto que la sección de información da un largo descomprimido de 14
bytes_
La imagen del ejemplo de IHDR es de ancho=3 y alto=2.
1.¿ No sería que cada fila tendría 10 bytes?
2. En ese caso, ¿ Los bytes en las posiciones 12:14 corresponderían al primer pixel de la segunda fila?

**Comment by FernandoPieressa** [comment]
1) Tienes razón, deberían ser 10, si fueran 2 de ancho sería 7.

2)Si cada fila tiene 10 bytes, a partir del onceavo byte partiría el primer pixel de la segunda fila

**Comment by JPSF** [comment]
Pero en el onceavo byte iría un cero porque se está empezando una nueva línea sin filtro, y luego del 12 en adelante correspondería al RGB de los pixeles
¿Tengo razón o entendí mal el enunciado?
