### ISSUE TITLE
Uso MainWindow: botón en widget y tener más de un widget

### ISSUE THREAD

**Issue by jirarrazaval** [IIC2233/syllabus#724]
Hice una mainwindow y le inserté un ```self.setCentralWidget(self.mapa)```. He tenido muchos problemas con esto como los siguientes:

1.  Le puse un botón al centralwidget y no se apreta, y está bien puesto el comando porque me funciona en otras ventanas.

2. Le puse un layout al centralwidget y ahora le quiero poner un layout a la mainwindow, pero no me funciona porque sale que sólo puede haber uno layout. Entonces no sé qué hacer para que los dos estén con sus layouts.

* Estoy usando esto porque sale en la pauta que hay que usarlo en la parte de "Actividad Formativa 5"

**Comment by lily416** [comment]
Hola @jirarrazabal 

Ayer en la tarde noche se actualizó el enunciado de la T02 y junto con el la parte de la AF05. En la nueva versión de enunciado ya no es obligación utilizar `MainWindow`.

Si aún así quieres seguir utilizando `MainWindow`, avísame para ver cómo ayudarte en los puntos que mencionaste.

Quedo atenta a tus comentarios. 😸🍪

**Comment by jirarrazaval** [comment]
Siii me gustaría usarlo para aprender mejor!!

**Comment by lily416** [comment]
Lo siento la demora estaba preparando un pequeño ejemplo :)

1. Normalmente cuando se asigna el `centralWidget` no debería generar problemas con el funcionamiento de los botones, en el ejemplo podrás ver que no hago nada especial para hacer que los botones funcionen.

2. Como dices, solo puede haber un `centralWidget` en una misma ventana, para poner más de un `widget` o `layout` puede hacer un único `layout` que contenga a todo el resto. En el ejemplo hago que un `layout` contenga a dos `widget`.

<details>
  <summary>Código ejemplo</summary>
  ```python```
</details>

**Comment by lily416** [comment]
Espero que se alcance a ver bien, por desgracia github no deja agregar vídeos a los comentarios, pero los GIFS funcionan 👍 

![gif](https://user-images.githubusercontent.com/26393515/82376927-dbf9bf80-99f0-11ea-892b-08621489446a.gif)

Espero que con esto te haya quedado más claro y cualquier otra cosa no dudes en volver a comentar o hacer otra issue.

Saludos y éxito en la tarea 👋🍭
