### ISSUE TITLE
obtención de los bytes de una imagen png

### ISSUE THREAD

**Issue by mjgutierrez1** [IIC2233/Syllabus#724]
No me queda claro cómo se obtienen los bytes de las imagenes, ¿igual que como lo hemos hecho con cualquier archivo?

Suponiendo que lo anterior es correcto, hice:

    with open("imagen.png", "rb") as file:
        for i in file:
            print(i)

Eso me retorna lineas de bytes, donde todas las lineas terminan con el byte /n y la primera también tiene un /r. ¿Esos bytes son equivalentes al "/n" en los string?, es decir, ¿la representación en bytes de mi imagen sería el concatenamiento de todas esas líneas de bytes, eliminando los /n y /r?

**Comment by Kitaps** [comment]
En el issue #716 hablan de ese tema, demás ahí encuentres lo que buscas.

**Comment by mjgutierrez1** [comment]
Gracias, la verdad es que lo que explican en es issue es cómo usar los bytes de mi imagen una vez que ya los tengo, entonces no responde mi pregunta que se refiere a cuáles son los bytes de la imagen y cómo obtenerlos.
