### ISSUE TITLE
comando /label

### ISSUE THREAD

**Issue by rjdelrio** [IIC2233/Syllabus#724]
no se muy bien como funciona esto de los labels pero si es como yo creo solo se pueden poner en las issues los label que ya an sido creado antes, por lo tanto me quedan dos opciones cuando el label no existe, devolver un mensaje diciendo que ese label no existe o crear ese nuevo label? cual ago? o estoi muy perdido?

**Comment by KnowYourselves** [comment]
Ya se respondió en otra issue:

Si el label no existe se debe crear.

**Comment by rjdelrio** [comment]
y otra cosa el color del label  lo elijo yo o me lo daran en la informacion

**Comment by stephichau** [comment]
@rjdelrio eso da lo mismo :)
