### ISSUE TITLE
problemas al descargar PyQt5 en windows

### ISSUE THREAD

**Issue by josefabr** [IIC2233/syllabus#724]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

He intentado descargar PyQt5 en mi computador pero no lo he logrado, al escribir "pip install PyQt5" o con "pip3" me dice que pip no es un comando correcto.

**Comment by aaossa** [comment]
Hola @josefabr , vamos por partes:

* ¿Dónde estás ejecutando estos comandos (cmd, powershell, otra consola)?
* ¿Te funciona el comando `python --version` o `python3 --version`? Si es así, prueba con `python -m pip install PyQt5` o `python3 -m pip install PyQt5`, según cual sea el que te funcione.

**Comment by josefabr** [comment]
Estoy desde el cmd, pero no ocurre nada cuando escribo los comandos que me diste

**Comment by aaossa** [comment]
@josefabr, ¿podrías incluir una captura porfa? 🤔

**Comment by josefabr** [comment]
![Captura de pantalla (5)](https://user-images.githubusercontent.com/64439711/96512544-06b5a180-1237-11eb-95d7-54dc282bfeaa.png)

**Comment by aaossa** [comment]
¿Y con `python --version` y `python -m pip install PyQt5` ocurre lo mismo?

**Comment by josefabr** [comment]
si

**Comment by aaossa** [comment]
¿Cómo instalaste Python? Quizás lo instalaste por medio de Windows en lugar de utilizar los métodos recomendados por la [guía de software obligatorio](https://iic2233.github.io/wiki/software) 🤔 Si es así, te recomiendo seguir la guía.

**Comment by josefabr** [comment]
Revise el proceso que hice para instalar python y es el indicado en la guía

**Comment by aaossa** [comment]
¿Podría mostrarme el *output* de los siguientes comandos?
* `where python3`
* `python3`

**Comment by josefabr** [comment]
![Captura de pantalla (9)](https://user-images.githubusercontent.com/64439711/96604166-2b5b5900-12cb-11eb-8363-f5d7becfcc0e.png)
En el segundo output me abre la "tienda" para obtener python 3.8

**Comment by aaossa** [comment]
Creo que lo mejor es que vuelvas a instalar Python de la manera indicada en la guía de *software* obligatorio, pero teniendo especial cuidado de marcar la opción **Add Python 3.7 to PATH**. Luego, en una nueva sesión de la consola, debería funcionarte el comando `python` y/o `python3`. Aquí está la [guía de software obligatorio](https://iic2233.github.io/wiki/software).

![imagen](https://user-images.githubusercontent.com/10425834/96604508-9573fe00-12cb-11eb-94be-065b5baba4ba.png)

Lo que creo que está pasando es que está instalada la versión de Python que ofrece Windows en su tienda, y esa no tiene la opción de usar pip. También veo que el comando python3 no está ligado a una instalación de Python, por lo que al parecer no está instalado, o al menos no está accesible con ese comando (podrías confirmar con el comando `where python`, debería salir una ruta que no esté en la carpeta `WindowsApps`).

**Comment by josefabr** [comment]
Lo volví a instalar y me funciono, gracias, aunque la ruta me sigue saliendo dentro de la carpeta windowsapp, espero que no sea un problema para el futuro
