### ISSUE TITLE
Duda 4 Valores finales de cancion

### ISSUE THREAD

**Issue by ljrodriguez1** [IIC2233/Syllabus#724]
en el enunciado se señala que los cuatro valores finales de la canción deben ser [0, 255, 47, 0], sin embargo leyendo la canción de games of throne me queda esto:
[[0, 144, 69, 96, 240, 128, 69, 96], [0, 144, 62, 96, 240, 128, 62, 96], [0, 144, 65, 96, 129, 128, 65, 96], [0, 144, 67, 96, 129, 128, 67, 96], [0, 144, 69, 96, 240, 128, 69, 96], [0, 144, 62, 96, 240, 128, 62, 96], [0, 144, 65, 96]]
donde el final es [0, 144, 65, 96] lo que no concuerda con el final del enunciado.
Tampoco se si lo estoy leyendo bien ya que en mi representación de la canción guarda 5 Notas, cada lista dentro de la lista de lista, pero al reproducir games of throne esta tiene mas notas, entonces no se que podría significar, y si esto tiene algo que ver con los valores finales

**Comment by Hernan4444** [comment]
@ljrodriguez1 creo que estás leyendo mal puesto que la canción tiene como 30 notas, por lo tanto, si estás leyendo 5 implica que no estás agrupando como corresponde.
