### ISSUE TITLE
Ventana de editar

### ISSUE THREAD

**Issue by antoniacobo** [IIC2233/Syllabus#725]
Hola! En la ventana de editar tenemos que permitir que el usuario ingrese las notas, escala, intensidad y duración de cada nota. Para no tener que comprobar si los strings ingresados están bien, podríamos usar un `QComboBox`?

**Comment by nachocontreras** [comment]
Hola!

Sí, puedes usar un `QComboBox`, sin embargo, debes respetar el Excel de valores. 
Además, si yo no sé música y quiero poner las notas en forma de número, también se debe poder.

Éxito! 😃
