### ISSUE TITLE
Parámetro CLIENTES_INICIALES

### ISSUE THREAD

**Issue by retamalcito** [IIC2233/syllabus#725]
¿A qué se refiere el parámetro ```CLIENTES_INICIALES```? Pregunto porque en el enunciado se explica que el número de clientes por ronda está dado por el número de ésta.

¡Gracias!

**Comment by jitorcas** [comment]
Hola! 
`CLIENTES_INICIALES` se refiere a la cantidad de clientes con que parte el juego en la **primera ronda**. Sin embargo, como la cantidad de clientes por ronda está definido por una fórmula podrías no considerar el uso de `CLIENTES_INICIALES`.
Especifica esto en tu `README` y cita esta issue para que no tengas problemas. 
Éxito!

**Comment by retamalcito** [comment]
Ok, gracias!
