### ISSUE TITLE
Imagen PNG 

### ISSUE THREAD

**Issue by Hernan4444** [IIC2233/Syllabus#725]
# Estimades
  Para organizar un poco el tema de PNG, quiero dejar algunas aclaraciones y agrupar algunas respuestas sobre este formato.

## PNG de 1 IDAT
Para empezar, en el enunciado se indica que se usarán imagen PNG de 1 IDAT, de todas las subidas, solo 4  cumplen con eso:

1. Knightmare 
2. DragonBall
3. MickeyMouse 
4. Mushroom 

Por lo tanto, la tarea puede mostrar solo 4 imagenes (intentaremos buscar 2 imagenes más PNG de 1 IDAT, pero por el momento haganlo al menos con esas 4).

## Largo y CRC

El valor del largo del chunk al comienzo de éste sólo indica el largo de "Información", **no incluye el CRC** (la issue #722 tenía un error)

En el enunciado queda un poco difícil de entender el calculo del CRC, en este **solo se ocupa el tipo del chunk junto con la información**. En el enunciado se dice que un chunk se compone de:
1. Largo
2. Tipo
3. Información
4. CRC

El nuevo CRC se calcula siempre como Tipo + Información.

Para el caso del `IDAT`, el CRC se calcula en base a la información **comprimida**.

## Casos no explicitados del PNG

Entre las imágenes, tenemos casos que en el enunciado no se especificaron sobre el PNG y a continuación se explica cómo abordarlas. El primer caso **si o si deben implementarlo en la tarea**, los demás casos **son solo una opción**, por si alguien quiere hacer su código para todas las imágenes.

- Presencia de otros chunk: Existen chunks como _sRGB, gAMA, pHYS_, entro otros dentro del PNG, estos **deben ser ignorados** pueden agregarlos al PNG o sacarlos y no tendrá ningún efecto, pero no deben considerarlos en la matriz de datos.

- Imagenes en RGBA: hay algunas que no tienen 3 bytes por píxel, sino 4. Para eso solo deben leer de a 4 bytes cada fila pero el último lo **deben descartar después**, es decir, leen de a 4, pero solo usan los primeros 3 bytes para sus operaciones, olvidando completamente al cuarto.  Por lo tanto, la fórmula para saber el largo del IDAT, ahora sería `h * (4 * w + 1)`
- Múltiples IDAT: hay algunas imágenes que tienen más de un IDAT, para eso tienen que **concatenar cada información y luego descomprimir**. Por ejemplo. si tenemos 2 chunk tipo IDAT, entonces el IDAT final es: `IDAT, largo_1 + largo_2, cuerpo_1 concatenado a cuerpo_2, crc(nuevo cuerpo)`.

Las imágenes que están dentro de los últimos 2 casos son:

1. Anime - RGBA
2. Bowser - RGBA y tiene 6 IDAT
3. Rick - RGBA y tiene 20 IDAT
4. Squirtle - RGB pero tiene 2 IDAT
5. FlippyNips - RGB pero tiene 7 IDAT

Saludos y mucho exito en la tarea. ✌️

**Comment by mjgutierrez1** [comment]
@Hernan4444 muchas gracias por las aclaraciones. Sin embargo, sigo teniendo dudas previas a poder preocuparme de lo que aquí se explica en la issue https://github.com/IIC2233/Syllabus/issues/724 , que son también sobre el formato png.

**Comment by Kitaps** [comment]
Cual es el valor para RGBA, o como hacemos para saber eso? Xq segun lo que entendí RGB tiene valor 2. O solo está RGB y RGBA y si no es 2 entonces podemos asumir que es RGBA ?

**Comment by Hernan4444** [comment]
@Kitaps la forma de saber si es RGBA o RGB es mediante la fórmula:
  `número de bytes del idat = h * (3 * w + 1)`

Si esa formula no es igual, entonces es porque tienes más bytes por pixel (` h * (4 * w + 1)`) es decir, tienes un RGBA.

**Comment by nlvargas** [comment]
@Hernan4444 ¿También debemos trabajar los casos RGBA?

**Comment by Hernan4444** [comment]
@nlvargas no es obligación. Solo si es que quieres soportar más imagenes.

Saludos ✌️

**Comment by behrmann97** [comment]
El largo del IDAT es comprimido, o no?

**Comment by santi95** [comment]
@Hernan4444 Es mi idea o Anime.png también tiene solamente 1 IDAT?

**Comment by Hernan4444** [comment]
@behrmann97 si, es el comprimido
@santi95 si tiene, pero es RGBA. Por lo mismo no es obligatoria manejar esa imagen.

Saludos ✌️

**Comment by mjgutierrez1** [comment]
@Hernan4444 en el cálculo del CRC no me queda claro para qué sirven los 4 bytes de CRC que vienen en el archivo de la imagen, si se ha dicho que para calcular el CRC sólo se usará Tipo + Información.

**Comment by behrmann97** [comment]
Entonces puedo eliminar las otras 5 imagenes? Igual haría que se puedan  agregar más y en caso de haber al menos 6 imagenes, mostraría 6.

**Comment by Hernan4444** [comment]
@mjgutierrez1 los 4 bytes de CRC que vienen fueron los calculados en la vez anterior que se editó algún chunk. Pero al momento de leer, ese CRC no es de utilidad puesto que deberás crear uno nuevo si es que la parte de información fue editada.

@behrmann97 si, puedes eliminar esas 5 imagenes.
Saludos ✌️
