### ISSUE TITLE
Error Web process failed to bind to $PORT within 60 seconds of launch

### ISSUE THREAD

**Issue by Dunkan1** [IIC2233/Syllabus#725]
Tengo ese error al correr mi aplicacion en heroku
![aiuda](https://user-images.githubusercontent.com/26102365/27520177-f27be0aa-59d2-11e7-8d35-404f896cd61d.PNG)
ademas mi Procfile esta correcto ya que tiene  
web: flask run --host=0.0.0.0 --port=$PORT

 revice otras issues #678 donde tuvieron el mismo problema, asi que intente lo que agrego @nivek0o0
pero siguer fallando :sob:

**Comment by Okhan97** [comment]
TENGO EL EXACTO MISMO PROBLEMA D:

**Comment by Dunkan1** [comment]
que hacemos :sob:

**Comment by Okhan97** [comment]
He buscado en muchos lugares y ninguno me brinda una solucion 😞

**Comment by nivek0o0** [comment]
#678  de nada

**Comment by Dunkan1** [comment]
ese cambio no arreglo el problema 😞

**Comment by nivek0o0** [comment]
sorry, no leí la parte de abajo de tu publicación :(

**Comment by Okhan97** [comment]
#703  @Dunkan1  HICE ESO Y SE ME SOLUCIONÓ EL ERROR !!!

Intenta escribir el procfile a mano

**Comment by Okhan97** [comment]
Aunque me sigué saliendo app crashed :,c

**Comment by Dunkan1** [comment]
Lo unico que me funciono para arreglar el problema fue ademas de lo que aparece en @678 , modificar el Procfile:
```
              Modificar el Procfile a
                             web: python main.py
              agregar al main.py 
                             port = int(os.environ.get("PORT", 5000))
                             app.run(host='0.0.0.0', port=port)
```
no se si me dejen hacer esto ya que no es lo que aparece en el enunciado, pero es lo unico que me funciono en la tarea
