### ISSUE TITLE
Problemas descargando pyqt5-tools

### ISSUE THREAD

**Issue by alanpiket** [IIC2233/syllabus#725]
<img width="1018" alt="Captura de Pantalla 2020-10-19 a la(s) 5 38 03 p  m" src="https://user-images.githubusercontent.com/69634748/96509028-d91a2980-1231-11eb-84c9-70508f2cf18f.png">

### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]
Estimados, les ruego ayudarme. Estoy t
<img width="974" alt="Captura de Pantalla 2020-10-19 a la(s) 5 41 01 p  m" src="https://user-images.githubusercontent.com/69634748/96509360-4332ce80-1232-11eb-9e94-2bc112e324af.png">
<img width="1018" alt="Captura de Pantalla 2020-10-19 a la(s) 5 41 15 p  m" src="https://user-images.githubusercontent.com/69634748/96509388-504fbd80-1232-11eb-8178-0410fbf53515.png">

ratando de instalar pyqt5 tools para comenzar con el designer y no puedo hacerlo. Adjunto imagen del error y espero ojalá me puedan ayudar y ojalá poder evaluar la idea posponer el avance, ya que no logro comenzar independiente de ya estar listo para hacerlo.
Gracias.

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by aaossa** [comment]
Hola @alanpiket , ¿probaste con [este link](https://build-system.fman.io/qt-designer-download)? Es el *link* sugerido en caso de tener tu mismo error en la [guía de software obligatorio](https://iic2233.github.io/wiki/software):

> Si ves un error indicando que no hay una versión que coincida con pyqt5-tools (“ERROR: No matching distribution found for pyqt5-tools”), prueba descargando e instalando QtDesigner desde [este sitio](https://build-system.fman.io/qt-designer-download).

Si no te funciona avisa por acá mismo y vemos qué podría estar ocurriendo 🤔 ¡Ojalá te funcione!

**Comment by alanpiket** [comment]
Funcionó, gracias!
