### ISSUE TITLE
Cómo organizar la zona de ritmo

### ISSUE THREAD

**Issue by denisseleiva** [IIC2233/syllabus#726]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda/Recomendación

Hola!!! Más que una duda necesito una recomendación :( Estoy haciendo la parte de la zona de ritmo con un QGridLayout. Consideré que me otorgaba más orden para realizar esta parte, pero tengo problemas con la parte de mover las flechas ya que no he podido encontrar una forma de acceder a un determinado _widget_ del QGridLayout y cambiar su posición. Lo que estaba haciendo era cada vez que quería moverlo, eliminar el _widget_ del layout y  crear otro _widget_ en la nueva posición, pero encuentro que esto es poco óptimo (y de hecho no me funciona bien 😔)
Entonces mi duda es, ¿Me recomiendan usar un QVBoxLayout que me permitiría usar widget.move() pero perdiendo el orden de la grilla, o mejor continúo lo que estoy haciendo y encuentro una mejor forma de cambiar la posición del widget?

Muchas gracias 😅

**Comment by furcelay** [comment]
Hola @denisseleiva !
No puedo decirte mucho, pero considera que las flechas deben poder moverse de manera **continua** y **fluida**, es decir, no pueden moverse a saltos entre secciones.
Para la tarea eres libre de elegir el layout que vas a usar en cada parte pero debes distinguir en qué partes conviene un layout (el tipo queda más a tu disposición) y partes no.

Saludos!

**Comment by denisseleiva** [comment]
mmmm jajaaj quedé en las mismas 😔, pero sabes de algún método para acceder a la posición de un widget en un QGrdilayout? @furcelay

**Comment by furcelay** [comment]
En general un layout está pensado para añadir y quitar objetos pero no para desplazarlos. Personalmente no conozco una forma de acceder a la posición de un widget en el layout pero si lo necesitas lo que puedes hacer es almacenar la posición como un atributo y cuando necesites moverlo lo quitas del layout y lo reposicionas tal como decías en el primer comentario, actualizando el valor del atributo para tener un registro de su posición actual. 

Como ya lo probaste sabes que ésto no genera un movimiento fluido, ya que un layout siempre restringe las posiciones para que el widget quede centrado (sea verticalmente, horizontalmente o ambas), si quieres que el widget pueda moverse libremente lo mejor es simplemente no usar un layout.

Espero te haya quedado más claro! :smile:

**Comment by denisseleiva** [comment]
Yaaa genial, muchas gracias te pasastee!!! @furcelay
