### ISSUE TITLE
Problema generar archivo .mid

### ISSUE THREAD

**Issue by raespinoza4** [IIC2233/Syllabus#726]
Hola,

Estaba haciendo el ejemplo que aparece en las Issues y tengo problemas al generar el archivo .mid
Cuando llego por mis "metodos" a los bytes finales y los escribo en un archivo windows no me deja abrirlo, pero si copio directamente la parte final del ejemplo si lo puedo abrir y escuchar.
(Tambien intente dandole directamente al write el bytearray)

![bytes_fail](https://user-images.githubusercontent.com/30879736/41500338-698ed330-715d-11e8-9fe2-409fe1d9bed7.png)

Le estoy pasando de una forma erronea los bytes al write ?

**Comment by Hernan4444** [comment]
Hola, revisa el bytes del `b'Mtrk`, son distintos en ambos 😅. Avisame si con eso se arregla c:

Saludos ✌️

**Comment by raespinoza4** [comment]
![cereal_guy_escupiendo](https://user-images.githubusercontent.com/30879736/41500557-c195588e-7161-11e8-80c1-66cc812ba0b6.png)

Si, eso era 😅 nunca mas programo tan temprano
Gracias !
