### ISSUE TITLE
Agregar/cambiar sprites

### ISSUE THREAD

**Issue by mariajoseguerrero** [IIC2233/syllabus#726]
Hola! Quería saber si para la tarea se puede editar/agregar imágenes??

**Comment by jitorcas** [comment]
Hola! 
Si, podrías agregar las sprites que quieras, siempre y cuando no interfieran con el flujo general del juego. 
Éxito!

**Comment by lily416** [comment]
Ten en consideración que si creas o editas _sprites_, deberás subirlas a otra carpeta que no sea `sprites/` para que así no sean ignoradas por el `.gitignore`.

Saludos y éxito en la tarea 👋☕
