### ISSUE TITLE
Problema con Knightmare y Mushroom

### ISSUE THREAD

**Issue by caespinoza5** [IIC2233/Syllabus#726]
Al intentar descomprimir la información de imagen y luego comprimirla nuevamente después de haber hecho algunos cambios, las imagenes MickeyMouse y DragonBall funcionan bien. Sin embargo, con Knightmare y Mushroom, queda un rectángulo oscuro en la parte inferior. Quería preguntar si saben a qué se puede deber esto. A continuación el ejemplo:

![prueba 2](https://user-images.githubusercontent.com/26394948/32692699-97962646-c6fb-11e7-8bdf-e3543276dc98.png)

Gracias de antemano! (utilizo zlib.compress y zlib.decompress para hacerlo).

**Comment by jotramon** [comment]
creo que se arregla cambiando el level de la compresión, por defecto es -1, y yo puse 9 y funciona ahora bien :)

**Comment by caespinoza5** [comment]
Gracias!  Tienes razón.
