### ISSUE TITLE
seteo webhook github

### ISSUE THREAD

**Issue by benjamimo1** [IIC2233/Syllabus#726]
Hola! Estoy por crear el webhook de github para luego setearlo a mi repo y la documentacion requiere en los params de POST /repos/:owner/:repo/hooks: {name: , config: }
Que valores se esperan en config? Alguno en especifico?

**Comment by chapito96** [comment]
#No soy ayudante
Hola, config es un diccionario con {"url": url de heroku que recibe el hook, "content_type": "json"}

**Comment by benjamimo1** [comment]
Ahi caché! Gracias no ayudante
