### ISSUE TITLE
Problemas encontrando archivo designer.exe

### ISSUE THREAD

**Issue by burizar** [IIC2233/syllabus#727]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

Hola!
ya instalé pyqt5-tools y no logro encontrar el archivo designer.exe. Traté con la ruta que dan en el notebook sobre QT Designer pero me sale que no está.

![image](https://user-images.githubusercontent.com/69607342/96523395-f8be4b80-124b-11eb-81dc-56ce27ed8ec5.png)

Busqué los archivos que se encontraban en el directorio y traté con pyqt5_tools pero tampoco está.

![image](https://user-images.githubusercontent.com/69607342/96523662-a7628c00-124c-11eb-966b-6ac17bd9742a.png)

También intenté ocupando pip3 en vez de pip pero tampoco funciona.
Por favor que alguien me explique que hice mal o como solucionarlo.
¡Muchas gracias!

**Comment by kadroguett** [comment]
Hola @burizar, prueba buscando en inicio "designer" y ve si te sale algo como esto:

![image](https://user-images.githubusercontent.com/31357861/96524373-7420fc80-124e-11eb-9890-cbcc9bd467f0.png)

**Comment by burizar** [comment]
no, no me aparece :(

**Comment by kadroguett** [comment]
Prueba buscando en la carpeta `scripts` en lugar de `lib`

![image](https://user-images.githubusercontent.com/31357861/96524689-5c964380-124f-11eb-8094-0baafadefd07.png)

**Comment by YehudaGurovich** [comment]
Hola @burizar Cuando comenzó el curso tenía el mismo problema y me funcionó con el comando **pyqt5designer**

**Comment by burizar** [comment]
Hola @YehudaGurovich, donde escribes ese comando?

**Comment by gaspcr** [comment]
@burizar prueba escribiendo **designer** en la terminal (cmd), a mi me ejecuta la aplicación al hacerlo.

**Comment by YehudaGurovich** [comment]
@burizar yo lo hago en bash siempre, a pesar de tener windows uso bash para todo, incluso para instalar cosas con pip (no se si es bueno o malo usar bash para esto), pero debería funcionar de todos modos en la cmd o en la powershell.

**Comment by YehudaGurovich** [comment]
> @burizar prueba escribiendo **designer** en la terminal (cmd), a mi me ejecuta la aplicación al hacerlo.

@gaspcr si al buscar en el buscador de windows no le sale **designer** tampoco funciona el comando en la cmd (como era mi caso), por alguna razón la instalación es algo distinta y se instala el archivo con el nombre de **pyqt5designer** en vez de solamente **designer**

**Comment by burizar** [comment]
no me aparece en el buscador si busco designer

**Comment by YehudaGurovich** [comment]
Prueba buscar **pyqt5designer** como mencioné arriba a ver si te aparece.

**Comment by burizar** [comment]
tampoco aparece. En que parte escribias pyqt5designer? en que directorio?

**Comment by YehudaGurovich** [comment]
![image](https://user-images.githubusercontent.com/53883366/96531875-029e7980-1261-11eb-9ddd-9d86373c19ee.png)

**Comment by burizar** [comment]
> Prueba buscando en la carpeta `scripts` en lugar de `lib`
> 
> ![image](https://user-images.githubusercontent.com/31357861/96524689-5c964380-124f-11eb-8094-0baafadefd07.png)

Ahí si estaba! pero con nombre pyqt5designer.exe como dijo @YehudaGurovich 
Muchas gracias!
