### ISSUE TITLE
Reglas del foro - Bots version

### ISSUE THREAD

**Issue by stephichau** [IIC2233/Syllabus#727]
Estimad@s:
Les recuerdo que este foro es un medio oficial para que compartan sus dudas por lo que **no** pueden utilizar este repositorio para probar sus bots. Para hacer esto, **deben** crear un repositorio **público** tal como se especificó en el enunciado. Si no cumplen con esto, se les descontará en la nota final de la tarea.

Saludos! :)

**Comment by acrojas2** [comment]
Hola!
Si el repo publico que hice con mi cuenta ya tiene issues y pruebas en general de mi bot hay algún descuento por eso?
Saludos!

**Comment by Hernan4444** [comment]
@acrojas2 no hay ningún problema con tener issues y pruebas en ese repositorio. La idea era que hicieran eso, así que no tendrás ningún descuento :+1: 

Saludos!!
