### ISSUE TITLE
Transformar archivos ui en py

### ISSUE THREAD

**Issue by mariagonthier** [IIC2233/syllabus#727]
Hola! En un video vi que si se ejecutaba pyuic5 -x test.ui -o test.py en la consola te transformaba el archivo ui en uno py, y así podías editar el código directamente. ¿Se puede hacer? ¿Lo recomiendan?

**Comment by Alonsinho1** [comment]
Hola!

tal como respondi en la issue #682 no recomiendo hacer esto. 

La gracia que tiene qt designer (Ademas de facilitar la creación de la mayoría de las ventana) se basa en que se ahorran muchísimas lineas de código.

Una vez que heredas la ventana, ya puedes modificar como tu quieras los widgets establecidos mediante código.  (Esta un poco más detallado en la issue #682)

Exito :D !

**Comment by mariagonthier** [comment]
Gracias!!!
