### ISSUE TITLE
Duda lectura de canciones

### ISSUE THREAD

**Issue by ljrodriguez1** [IIC2233/Syllabus#727]
Al leer la cancion de "Game of Throne" obtengo lo siguiente: b'MThd\x00\x00\x00\x06\x00\x01\x00\x01\x00\xa0MTrk\x00\x00\x018\x00\x90E`\x81p\x80E`\x00\
de aqui segun lo que comprendi del enunciado el lenght del data del canal me lo entregarian los 4 siguientes bytes despues de MTrk, los cuales son b'\x00\x00\x018'.
Mi problema es que  esos cuatro bytes del lenght al recorrerlos en un for no parecerian estar en formato big endian, ya que ninguno de los 3 primeros bytes empiezan con un 1,
yo creo que hay algo que debo estar entendiendo mal, asi que agradeceria mucho una ayuda

**Comment by Dyoma3** [comment]
En big endian, '0 0 0 1' corresponde a 1;  '0 0 0 255' es 255; '0 0 1 0' es 256; '0 0 1 2' es 258 ...
Se entiende la logica?

**Comment by ljrodriguez1** [comment]
Mi problema es al hacerlo como en la issue de ayuda por ejemplo para 256, su binario es 100000000 luego este para cadificarlo debe ser separado en grupos de 7 osea obtengo [10, 0000000] entonces me queda que en bigendian 0 0 2 0 es 256
