### ISSUE TITLE
Semana 11 QTimer

### ISSUE THREAD

**Issue by NikiHV** [IIC2233/syllabus#728]
Hola! Leyendo el cuaderno 1 de la semana 11 me surgió la siguiente duda.

Cuando creamos `QThread`s personalizados creamos una subclase de esta, y heredamos sus funcionalidades. Pero en el ejemplo de la sección "QTimer" en el que se creó un `QTimer` no se usó herencia, se creó la clase `MiTimers` que heredó de `QObject` y se asignó un `QTimer` como atributo de este. ¿No se podría crear directamente una subclase de `QTimer`? ¿Sí o sí debe ser un atributo de otra clase?

En el ejemplo de la sección "QThreads y señales" del mismo cuaderno se creó nuevamente un `QTimer` como atributo de la clase `MyWindow`, pero aquí a diferencia del caso anterior se entregó `self` como parámetro al crear el `QTimer` ¿para qué es esto? ¿por qué en un caso se entrega `self` y en el otro no?

**Comment by lucasvsj** [comment]
> Pero en el ejemplo de la sección "QTimer" en el que se creó un QTimer no
> se usó herencia, se creó la clase MiTimers que heredó de QObject y se asignó 
> un QTimer como atributo de este. 
>¿No se podría crear directamente una subclase de QTimer? ¿Sí o sí debe ser un atributo de otra clase?

Primero que nada, este ejemplo si se uso herencia, solo que MiTimers hereda de QObject como tu muy bien dices. Este fue el metodo que se decidio para resolver este ejercicio (como sabes, en programación, un problema puede tener mas de una solucion) y no hay problema en resolver este caso creando tu propia clase que herede de QTimer. Aqui va un ejemplo:  

```python
class myTimer(QTimer):  

    senal_actualizar = pyqtSignal(int, str)

    def __init__(self, i, tiempo):
        super().__init__()
        self.indice = i
        self.tiempo = tiempo
        self.indice_actual = 0
        self.setInterval(tiempo * 1000)
        self.timeout.connect(self.enviar_dato)

    def enviar_dato(self):
        if self.indice_actual < 9:
            self.senal_actualizar.emit(self.indice, str(self.indice_actual))
            self.indice_actual += 1
        else:
            self.senal_actualizar.emit(self.indice, 'Status: timer terminado')
            self.stop()

    def sigue_andando(self):
        return self.isActive()
```

Como puedes ver aqui mi clase hereda de QTimer. Ya que modificamos una parte de la solucion del problema, debemos modificar lo que falta, para que el programa siga teniendo logica:

```python
def ejecutar_timers(self):    
        """
        Este método crea cinco threads cada vez que se presiona el botón en la
        interfaz. Los threads recibirás como argumento el índice del label 
        que les corresponde y el tiempo que toman entre cada iteración.
        """
        if len(self.timers) == 0 or not any([timer.sigue_andando() for timer in self.timers]):
            self.timers = []
            for i in range(1, 6):
                timer = myTimer( i, i / 10)
                # Se conecta la señal emitida por el timer
                # a un método de la ventana
                timer.senal_actualizar.connect(self.actualizar_labels)
                self.timers.append(timer)
                timer.start()
```

> En el ejemplo de la sección "QThreads y señales" del mismo cuaderno se creó
> nuevamente un QTimer como atributo de la clase MyWindow, pero aquí a
> diferencia del caso anterior se entregó self como parámetro al crear el QTimer
> ¿para qué es esto? ¿por qué en un caso se entrega self y en el otro no?

En cuanto a esta pregunta, aqui se le pasa el self, ya este sera el padre (parent) del QTimer. Esto se hace ya que asi si la ventana principal (MyWindow) es eliminada (cerrada), la insatncia de QTimer tambien será eliminada (ya que es su hijo). Es buena practica hacer esto a medida que tus programas se van complejizando. 
En el primer caso no le otorgamos el self, ya que no es del todo necesario (puedes hacerlo y no va a cambiar la solucion), ya que como llamamos a 
```python 
self.timer.stop()
```
el QTimer se dentendra en ese momento. Y si cierras la ventana antes que se detenga, tambien se detendra, debido  a que se ejecuta
```python 
sys.exit(app.exec_())
```
Lo que se encarga de eliminar todo lo relacionado con PyQt5

Si quieres saber mas sobre QTimer, aqui hay una muy buena explicacion [https://stackoverflow.com/questions/42279360/does-a-qtimer-object-run-in-a-separate-thread-what-is-its-mechanism](url)
Ademas, nunca hace mal revisar la documentacion misma: [https://doc.qt.io/qt-5/qtimer.html#details](url)

**Comment by tiaresagredo** [comment]
Hola, se puede hacer a QTimer un atributo self de una clase que hereda de QThread?

**Comment by Camila-sty** [comment]
Hola @lucasvsj , he intentado abrir los dos links que recomendaste, pero en ninguno me sale algo, solo me aparece otra pestaña de git pero vacía. Como debo abrirlos :thinking:  ¿?

**Comment by lucasvsj** [comment]
Hola @tiaresagredo 
Si tu pregunta es si puedes crear un atributo de clase de un QThread que sea un QTimer, si se puede y no habría problemas en hacerlo

**Comment by lucasvsj** [comment]
Hola @Camila-sty
Acabo de actualizar los links, ahora deberían funcionar. Perdón por el error 😆

**Comment by rldelafuente** [comment]
Hola! Siguiendo la linea de la pregunta, me quedan algunas dudas del funcionamiento del código de `myTimer(QTimer)`

Qué hacen las siguientes lineas:

`self.tiempo = tiempo`
`self.indice_actual = 0`
`self.setInterval(tiempo * 1000)` ¿por qué por 1000?

y ¿por qué se utiliza esto así: `timer = myTimer( i, i / 10), con i/10` ?

En otras palabras, tengo confusión con cuál es la variable que indica el tiempo para que termine su funcionamiento (el contar hasta 10), cuál es la variable que hace que luego de cierto tiempo empiece a funcionar el siguiente Thread.

Gracias!

**Comment by lucasvsj** [comment]
Hola @rldelafuente 

- > `self.tiempo = tiempo`


Aquí guarda el tiempo que se utilizara en `.setInterval`, es decir el tiempo que transcurre entre las activaciones del método que se entrega en `.timeout.connect()` (el método es `self.enviar_datos`)

-  >`self.indice_actual = 0`


Este es una variable que utilizará mas adelante en el método `enviar_datos(self)`

- >`self.setInterval(tiempo * 1000) ¿por qué por 1000?`


Aquí define el intervalo de tiempo que transcurre entre las activaciones del método que se entrega en `.timeout.connect()` (el método es `self.enviar_datos`. Éste se multiplica por 1000 porque lo que entra a esta función son milisegundos, entonces si digo que `tiempo = 5` y yo quería que estos fuesen segundos, al multiplicarlos por 1000, se transformarán en segundos. 

- >y ¿por qué se utiliza esto así: timer = myTimer( i, i / 10), con i/10 ?

Se utiliza i/10 porque el tiempo que se le pasa a `.setInterval()` depende de `i` (así, los mensajes se mostrarán con un espacio entre éstos, el primero saldrá después de que pasen 0.1 segundos, el segundo despues de 0.2, etc)

- > En otras palabras, tengo confusión con cuál es la variable que indica el tiempo para que termine su funcionamiento (el contar hasta 10)

La variable que indica el tiempo para que termine su funcionamiento (el contar hasta 10) sería en este caso `self.indice`, ya que si te fijas en `enviar_datos(self)`, una vez que se cumple que `self.indice_actual == self.indice` se llama al método `self.stop()` el cual se encarga de detener el `QTimer`.

- > cuál es la variable que hace que luego de cierto tiempo empiece a funcionar el siguiente Thread.


Si con siguiente Thread te refieres al siguiente QTimer, no hay una variable que determine que "se ejecute el siguiente QTimer", éstos son ejecutados una vez que se llama a `timer.start()` y (como mencione anteriormente) se detienen una vez que se cumple la condición.

Espero que estas explicaciones te hayan servido y disculpa por la demora, la U no esta de mi lado esta semana 😢 .
Cualquier duda que tengas pregunta no mas, estaré más atento y responderé más rápido
