### ISSUE TITLE
Request timeout Heroku

### ISSUE THREAD

**Issue by chapito96** [IIC2233/Syllabus#728]
Hola, mi bot funciona bien, pero de la nada deja de funcionar.
Hago heroku logs y aparecen errores de "Request timeout".
Después de un rato revive y empieza a responder a las peticiones acumuladas como corresponde.
Es muy aleatorio y me preocupa que "justo" se caiga cuando se deba corregir :/

**Comment by Hernan4444** [comment]
@chapito96 para aclarar un poco el error, los dynos son contenedores que Heroku entrega para correr las apps pero cuando uno solicita una cuenta gratuita, estos dynos se duermen luego de 30 minutos de inactividad por lo tanto el error fue que tu servidor como estaba dormido y se demora mas contestar las primeras request porque está "despertado". 

Así que no te preocupes por eso, no es un error que esperamos que manejen, cuando corrijamos vamos a tener paciencia con el primer comando que probemos y luego que responda esperaremos un bot mucho mas fluido :+1: 

Saludos!!

**Comment by chapito96** [comment]
Gracias @Hernan4444.
Hoy el bot se ha comportado especialmente bien, realmente parece aleatorio cuano se duerme
