### ISSUE TITLE
Keypressevent

### ISSUE THREAD

**Issue by n4chin** [IIC2233/syllabus#728]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola!, en la zona de Captura dice que cada vez que el jugador presione la tecla "a", el cuadrito que representa a la letra A tiene que cambiar de color, sin embargo, también dice que "al momento de dejar de presionarse el botón" se tiene que cambiar el color del cuadrito. Mi pregunta es si hay un metodo de keypressevent que analice este caso, o sea, el caso en que no se deje de presionar una tecla, pues para el event.text() para que cambie hay que presionar otra tecla y al agregarle un thread o un timer como que me empieza a parpadear el cuadrito y se ve raro. Googlié esto,  pero no entendí mucho lo que encontré, encontré algunos métodos como event.count(), event.text() (que es el ya visto) y entre otros que no entendí, o entendía pero no me salía el resultado esperado, al tratar de probarlos. De antemano gracias.

**Comment by aljara97** [comment]
Hola @n4chin, lamentablemente no podemos decirte qué método ocupar en esta ocasión ni cuál sería el correcto, ya que uno de los objetivos de la tarea es que ustedes sean capaces de averiguarlo por su cuenta. Sin embargo puedes averiguar sobre los distintos métodos de pyqt5 asociados a un evento en específico en sitios como [stackoverflow](https://stackoverflow.com/) o puedes averiguar más en la documentación de pyqt5.

Saludos y mucha suerte :D
