### ISSUE TITLE
Establecer función hook para excepthook de sys

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2233/syllabus#729]
Hola en la ayudantia instanciaban la sys.__excepthook__ = hook dentro del def hook pero en la actividad formativa fue al revés (afuera del def hook).

Cual es la diferencia ?

**Comment by igbasly** [comment]
Hola @dsepulveda3 

Lamentamos las molestias de lo ocurrido con la ayudantía 😓, esto fue un error de escritura. 
La idea de definir la función `hook` es sobre-escribir la que utiliza `sys` con tal de que nos muestre que está ocurriendo con PyQt. Es por esto, que primero hay que definirla y luego establecerla en `sys.__excepthook__`.

**Comment by dsepulveda3** [comment]
Perfecto gracias !
