### ISSUE TITLE
IHDR

### ISSUE THREAD

**Issue by movaldivia** [IIC2233/Syllabus#729]
Podemos suponer que el IHDR siempre va al principio? Leí la documentación y salía "shall".

**Comment by Hernan4444** [comment]
@movaldivia no puedes asumir eso.

Saludos ✌️

**Comment by Jiparavich** [comment]
@Hernan4444 
No entiendo por que no se puede asumir eso, si sale en la documentacion...
![image](https://user-images.githubusercontent.com/30678179/32987328-33e8a5de-ccc7-11e7-9736-870a4cfc84f2.png)
