### ISSUE TITLE
Duda respecto al contenido que guardo en el archivo de las partidas

### ISSUE THREAD

**Issue by Sebastian-Assereto** [IIC2233/Syllabus#73]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Lei las issue y no encontré alguna parecida a mi duda, y si es que ya lo hay pido las disculpas 
Mi consulta va respecto al contenido que almaceno dentro del archivo de guardar partida del jugador, ya que en el enunciado se habla de almacenar las posiciones descubiertas, con numero y posición de la bestia, en mi caso tenia la idea de guardar 2 cosas, 1 vendría a ser el tablero del jugador ( en el cual se vería que casillas tiene ya descubiertas y cuales son las ocultas) y el tablero final del juego, en el cual se encuentran todas las bestias en sus respectivas posiciones junto con los números que las rodean) esto con la intención de posteriormente solo cargar ambos tableros y que el jugador pueda continuar su juego con normalidad. Pero no se si esa forma de guardar el archivo este correcta o va en contra de lo que me piden ( yo creeria que estaria bien ya que permite el correcto flujo del programa) 

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by 3rdPix** [comment]
El enunciado menciona que se debe guardar **toda la información relevante** de la partida. Así, cualquier detalle que sea necesario para que un jugador vuelva (en una sesión posterior) exactamente al punto donde lo dejó, debe ser guardado. El formato **queda a tu criterio**.

**Comment by victoriaatria** [comment]
Hola! Como se menciona en el comentario de arriba, según el enunciado el formato queda a tu criterio, entonces efectivamente puedes guardar la información como la describiste. Eso sí, recuerda describir lo que hiciste en tu readme. Saludos!
