### ISSUE TITLE
Duda recoleccion de recursos

### ISSUE THREAD

**Issue by CmPoblete** [IIC2233/Syllabus#73]
Al recolectar los recursos se deben recolectar los recursos de todos los planetas conquistados o solo los del planeta que se esta visitando?

**Comment by emeiese** [comment]
Hola! Me sumo a esa pregunta, y agrego otras al respecto:
En la parte 6.3 Dice que hay que entregar información general del usuario, y mostrar la cantidad de deuterio y minerales de la galaxia. En ese caso, esta cantidad representará a la suma de deuterio y minerales de cada planeta, cierto? Y no es que se estén "recolectando" por lo que solo hay que mostrar cuánto deuterio y mineral se ha recolectado hasta la fecha. 

Por otro lado, en la parte 6.4, si el usuario decide "Realizar mejoras", el material disponible para realizar esto serían los 1000 deuterios/minerales del usuario + los deuterios/minerales disponibles del planeta?

**Comment by Hernan4444** [comment]
Hola, creo que hay un pequeño malentendido con los recursos. Para empezar, los recursos de la galaxia en la que se esta jugando representa los recursos que dispone en jugador. Cuando el jugador recolecta los recursos, estos se suman a los que tiene la galaxia y cuando gasta recursos en algún planeta, estos se restan de los que están en la galaxia.

Luego de esta aclaración
1. Los recursos se recolectan del planeta que se está visitando.
2. No existe la cantidad de deuterio y minerales por planeta, estos son de la galaxia y al momento de realizar la consulta, solo se consideran lo que está recolectado a la fecha.
3. Como no hay recursos en el planeta, el costo de las mejoras solo implica restar del monto que tiene la galaxia.

Imaginen que el jugador es el dueño de la galaxia y cuando visita un planeta, recolecta los recursos y los saca del planeta para guardarlos en un fondo común y como se indica en el enunciado, cada galaxia es independiente. Por lo tanto, cada galaxia posee su propio fondo de recursos.

Espero haber respondido sus dudas.
Éxito en la tarea!!

**Comment by jminostroza** [comment]
Si los planetas en sí no almacenan recursos, cómo sé cuánto podré recolectar al visitar un planeta ???
