### ISSUE TITLE
Tengo problemas subiendo la tarea y archivos comeplentarios a mi repositorio privado en Github

### ISSUE THREAD

**Issue by Fernanda1232123** [IIC2233/Syllabus#73]
### Prerrequisitos

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola,
Seguí los pasos de git status, git add y git push desde la terminal de mi tarea para agregarla a github, seguí todos los pasos como en el video de la clase. Cuanto hago git push me sale un mensaje de 'everything up to date', pero voy a mi repositorio privado en github y no están los archivos que subí. 
Los archivos de la tarea que estoy intentando subir los tengo en mi computador en tarea 0 de mi respositorio privado que antes había 'bajado' de github con git clone.
¿Por qué me puede estar pasando esto y como lo resuelvo?

![Screen Shot 2021-09-01 at 20 48 07](https://user-images.githubusercontent.com/89221305/131764553-4fc0d5aa-e218-4747-ae3d-ec2271b417a2.png)

**Comment by Emiliax16** [comment]
Hola @Fernanda1232123 😄 estás dentro de tu repo pero no dentro de la carpeta T0. Abre la consola de git desde la carpeta de la T0 e ingresa los mismos comandos:

git status (debería mostrarte cada archivo sin la ruta Tareas/T0)
git add archivo
git commit -m "mensaje"
git push

Coméntame cualquier cosa, saludos!

**Comment by Fernanda1232123** [comment]
Hola,

Hice lo que me dijiste, pero me sigue saliendo 'everything up to date' y no aparece en mi repositorio privado en GitHub.
![Screen Shot 2021-09-01 at 21 14 28](https://user-images.githubusercontent.com/89221305/131765975-30a95b8a-1ea9-4f5e-82d1-369ffa1c2739.png)
![Screen Shot 2021-09-01 at 21 15 38](https://user-images.githubusercontent.com/89221305/131765981-371e8546-6302-4011-a932-80d00e894e64.png)
 
¿Qué hago si de aquí a la clase de mañana no me funciona? Hay una actividad evaluada mañana donde voy a necesitar poder hacer esto.

**Comment by Fernanda1232123** [comment]
Hola,

Ya me funcionó!!

**Comment by Emiliax16** [comment]
que bueno!! sino me equivoco, te faltaba hacer `git commit -m "mensaje"` o no? (dado que eso es lo que te indicaba tu consola). Sería genial saber por si algún otre estudiante le sucede ❤️ 😸

**Comment by Fernanda1232123** [comment]
Lo que creo que me pasó fue que primero hice git add, git commit -m ' ', y git push, pero no estaba en subcarpeta dentro de mi repositorio privado donde tenia la tarea, sino que estaba donde entro en mi repositorio y veo todas las subcarpetas.
La segunda vez tuve problemas porque, aunque estaba en tarea 0 donde dentro de mi repositorio donde tenía mi tarea, no puse git commit -m. Por eso no me funcionaba
