### ISSUE TITLE
Dudas respecto al archivo parametros.py

### ISSUE THREAD

**Issue by nicolaspoli** [IIC2233/syllabus#73]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! He leído varias veces esa parte del enunciado, pero no logro entender el archivo parametros.py. Se supone que debo rellenarlo de manera que luego dichos frases clave realicen la acción? o simplemente que, por ejemplo, si escribo ABANDONAR_FRASE mi programa lo detecte como lo mismo que "\\salir"?

Ademas, el enunciado dice: "Si el programa detecta que se ingresó este input en cualquier conversación, debe volver al menú anterior", eso significa que si no esta un chat no debe aplicarse este parámetro? (Por ejemplo, en el inicio, ya que ahí no se está en una "conversación" aún). Hay un issue que habla del caso particular del menú de contactos, pero no responde para el resto de casos :c 

De antemano, muchas gracias :D

**Comment by RafaelEdwards** [comment]
Holaa!
El archivo parametros.py tiene la finalidad de guardar ciertas variables o parámetros que luego usarás en tu código, para lograr identificarlos y modificarlos de manera rápida. Por ejemplo: si quieres que tu nueva palabra clave para abandonar un grupo sea \abandonar, si tienes esta variable parametrizada sólo deberás cambiar su valor en parametros.py y no en cada lugar en que la utilizaste en tu código. 

Sobre cuándo aplica esta palabra clave en los input, ABANDONAR_FRASE aplica sólo cuando estás en un chat grupal y VOLVER_FRASE aplica en cualquier conversación. Por lo que cómo bien dices, si no estás en un chat, debes manejar estas palabras en los inputs como cualquier otro string que pueda ingresar el usuario.

**Comment by nicolaspoli** [comment]
Entonces no debo hacer nada en el archivo parametros.py? solo es para que reconozca ABANDONAR_FRASE como "\\salir" (por ejemplo)

**Comment by RafaelEdwards** [comment]
A menos que necesites agregar otro parámetro, debes dejarlo tal cual como está. De todas formas, si es que lo cambias recuerda subirlo a tu repositorio e indicarlo en el README.

**Comment by nicolaspoli** [comment]
Ok, muchas gracias por responder! :D

**Comment by olherreragz** [comment]
Para salir entonces el usuario debería incluir el caracter ```\``` en sus frases para... hechar a andar el comando por así decir, cierto??

**Comment by RafaelEdwards** [comment]
Hola @olherreragz , el \ es sólo parte del string que se guardó en los parámetros. ABANDONAR_FRASE podría ser "-Salir", "+Salir", o incluso simplemente "Salir".
