### ISSUE TITLE
Registro a mercado de usuario underaged

### ISSUE THREAD

**Issue by jerosalazar** [IIC2233/Syllabus#73]
Al registrarse a un mercado (en un usuario _trader_ o _investor_) se le hace entrega de 50.000 unidades de cada moneda del mercado en cuestión. 
¿Pasa lo mismo con los usuarios _underaged_?, es decir, ¿se les entrega el dinero aún cuando no pueden realizar _orders_?

**Comment by cilopez** [comment]
_"Todos los usuarios nuevos que cumplan con la mayoría de edad reciben
una cantidad inicial de 100.000 DCC, y también 50.000 de la moneda respectiva"_
