### ISSUE TITLE
Duda con "volver al menú"

### ISSUE THREAD

**Issue by kaihpy** [IIC2233/Syllabus#73]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/20)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/19)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola,
En el enunciado se indica que una vez realizada y ejecutadanuna acción válida (1, 2 o 3) en el menú de acciones, se debe regresar al menú de acciones. ¿Esto debe realizarse de manera automática o manual? Por ejemplo, se debe presentar el menú nuevamente inmediatamente después de realizar la acción correspondiente o se debe poner un paso intermedio (ej. "presione cualquier tecla para volver al menú")?

**Comment by MaxAl100** [comment]
Hola! Ya que no está definido explícito cualquiera de las dos maneras son válidas, siempre y cuando menciones esto en tu README. Puedes utilizar cualquiera sea más cómodo para tí.👍 
Eso sí, si te quieres asegurar, personalmente, me parece "más correcto" enviar automáticamente, ya que envía al usuario automáticamente. Por otro lado, puede ser más bonito/accesible al usuario no enviarle, sino que dejarle el resultado directo en la pantalla (aunque uno igual puede scrollear hacia arriba... 😅 )

**Comment by kaihpy** [comment]
Muchas gracias!
