### ISSUE TITLE
Duda entrega formulario

### ISSUE THREAD

**Issue by Alicia-TheOverthinker** [IIC2233/Syllabus#73]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* "[X]" Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* "[X]" Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* "[X]" Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* "[X]" De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola, estoy un poco nerviosa y asustada porque recuerdo que si no entregas un formulario tu tarea es invalida y no será corregida, buscando el formulario encontré uno que sale en la pauta de la tarea con el nombre de formulario de entregas atrasadas pero al abrirlo aparece que ya no se aceptan mas respuestas. ¿Que debo hacer?

**Comment by pacalein** [comment]
¡Hola! Si ese fue un error de comunicación, al menos en mi sección 5 mal interpreté la slide del formulario. La entrega normal es subir tu código final a tu repositorio, en cualquier fecha válida antes de la hora de entrega oficial, y eso es todo. El formulario de entrega atrasada es SOLO para quienes entreguen atrasados y vayan a usar o no cupones.
Espero quede mas confirmado de todas formas mandaremos un anuncio rectificando cómo se entrega la T1 cerca de la fecha.
