### ISSUE TITLE
Extensión de función que define el Juego mismo + Archivos válidos

### ISSUE THREAD

**Issue by vicenteCordero** [IIC2233/Syllabus#73]
### Prerrequisitos

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/21)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/20)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Buenas tardes, escribo porque tengo un par de dudas respecto al bonus "funciones atómicas" y a cuáles archivos son válidos y cuáles no,

1) El enunciado dice que toda función presente en la Tarea debe ser de largo <= 15. A partir de eso, si quise crear una función `juego()` que vaya formando el juego, los menúes y los input del usuario, y luego llamarla solo si `__name__ == "__main__"`, ¿esta función igual cuenta para el bonus? ¿O sea que si sobrepaso las 15 líneas en esta función pierdo el bonus?

2) Al momento de verificar si un archivo es válido, ¿puedo asumir que solo se me entregaran archivos ".txt" que dentro tengan escrito un texto en el formato especificado en la sección "Archivos" del enunciado? ¿O podría ocurrir que un archivo ".txt" dijera, por ejemplo, "hola"?

Gracias por la ayuda!

**Comment by Arielmanriquez** [comment]
1. Para el bonus de funciones atómicas, todas las funciones deben ser de menos 15 líneas, si tienen mas que eso te recomiendo ir haciendo funciones mas específicas y luego llamarlas desde la función principal en este caso juego().
2. Como debes ocupar los archivos que se te entregan puedes asumir que están en el formato correcto.
