### ISSUE TITLE
Al cargar partida . ¿debo crear los objetos nuevamente o hay maneras de guardar la información de los objetos?

### ISSUE THREAD

**Issue by cncosta** [IIC2233/syllabus#73]
ya pensando en la parte del menú en la que se debe crear una nueva partida o jugar una partida ya iniciada , me di cuenta que en la manera en la que se guarda la partida no hay manera de guardar los objetos de la partida, tal como el HP de las personas o edificios, y al cargar la partida estos objetos se crearan nuevamente como si fueran nuevos.
¿que hay que hacer en este caso? cada vez que se cargue una partida se crean objetos nuevos?

**Comment by roberto009** [comment]
Hola!
Existen maneras de guardar la información sobre un objeto, que se verán más adelante en el curso. Si te interesa eres libre de buscar información sobre esto, pero no te recomendamos aplicarlo para esta tarea.
Para efectos de la tarea tienes que crear los objetos de nuevo.
Éxito
