### ISSUE TITLE
Duda descuentos 

### ISSUE THREAD

**Issue by Tmsca** [IIC2233/syllabus#73]
Hola!

Los links dentro de la página de descuentos del syllabus me salen caídos cuando los clickeo(Page not found 404), pero sé que otros compañeros no tienen este problema. Cómo puedo arreglar esto?

**Comment by jeschuwirth** [comment]
Hola,

No hay una razón exacta de porque puede ser eso, necesitaría más información, pero puedes probar los siguientes medios para llegar al link:

- No estoy seguro cual link estas probando pero puedes intentar con el siguiente: https://github.com/IIC2233/syllabus/blob/master/Tareas/Descuentos.md

- Anda al syllabus del curso y muevete  mano por las carpetas hasta llegar a la guia:
(Syllabus -> Tareas -> Descuentos.md)

Avísame si ninguna opción te sirve para ayudarte !

**Comment by Tmsca** [comment]
> Hola,
> 
> No hay una razón exacta de porque puede ser eso, necesitaría más información, pero puedes probar los siguientes medios para llegar al link:
> 
> * No estoy seguro cual link estas probando pero puedes intentar con el siguiente: https://github.com/IIC2233/syllabus/blob/master/Tareas/Descuentos.md
> * Anda al syllabus del curso y muevete  mano por las carpetas hasta llegar a la guia:
>   (Syllabus -> Tareas -> Descuentos.md)
> 
> Avísame si ninguna opción te sirve para ayudarte !

Ninguna de las dos opciones me sirvió. Sí puedo acceder a la página de descuentos pero por ejemplo cuando intento ingresar a "guía de estilo" u otros links dentro de la página de descuento me tira el error 404.

**Comment by jeschuwirth** [comment]
Mmmmh, ¿puedes acceder al link en la sección de .gitignore que te lleva a una página distinta a github o también te levanta 404?

**Comment by Tmsca** [comment]
> Mmmmh, ¿puedes acceder al link en la sección de .gitignore que te lleva a una página distinta a github o también te levanta 404?

Sí puedo ingresar a este link. En particular los links que me arroja error son los de "guía de estilo" y "contenidos del curso"

**Comment by jeschuwirth** [comment]
Hola,

Había un problema en el archivo descuentos.md, acabo de arreglar los links. Prueba hacer git pull y apretar en los link para ver si se arreglaron :)

**Comment by Tmsca** [comment]
Ahora sí puedo acceder, excelente servicio! ✩✩✩✩✩
