### ISSUE TITLE
PermissionError al intentar escribir en 'usuario.csv'

### ISSUE THREAD

**Issue by lewebe** [IIC2233/syllabus#73]
Hola, al intentar añadir un nuevo usuario, se me pide que actualice el archivo 'usuarios.csv', sin embargo al hacerlo me arroja 
`PermissionError: [Errno 13] Permission denied: 'syllabus\\Tareas\\T00\\usuarios.csv'`

Cabe mencionar que estoy usando los archivos directamente de syllabus, es decir el path "syllabus"/ "Tareas"/"T00"/ "usuarios.csv"

**Comment by KnowYourselves** [comment]
Hola @lewebe!

1. Que sistema operativo estás utilizando?
2. Prueba revisando de que no tengas abierto `usuarios.csv`, ya sea en excel o porque tienes otro programa corriendo.
3. Prueba reiniciando tu IDE.

Quedo atento!

**Comment by lewebe** [comment]
Era que tenía el archivo abierto xd. Muchas gracuas!

**Comment by KnowYourselves** [comment]
Que bien :D!

Recuerda no cerrar las issues!

**Comment by nicogrecod18** [comment]
Hola, tengo el mismo problema, solo que si tengo el archivo cerrado. Lo raro es que hace un rato si me funcionaba y ahora no puedo correr el código porque me aparece el mismo error que al que posteó originalmente.
lo estoy intentando abrir con: excel_usuarios = open(ruta, "r+", encoding = "utf-8") 
si le borro el "+", me deja abrir el csv, pero no puedo abrirlo si quiero escribir en el.
mi sistema operativo es windows 10
