### ISSUE TITLE
Error en test_tablero_piezas_explosivas_invalidas.py

### ISSUE THREAD

**Issue by martina-abello** [IIC2233/Syllabus#73]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

En test_9x9_1_pieza_invalida(self), en la primera celda de la última columna del tablero_str, hay un "PP-" en vez de "PP".

**Comment by Hernan4444** [comment]
Hola @martina-abello 

¡Muchas gracias por notar este error!" Vamos a actualizar el test público del Syllabus sacando ese guión (junto a cualquier otro error que han notado de los tests públicos).

Saludosヾ(＾-＾)ノ

**Comment by Benjaminsolerp** [comment]
¿Hola, como están? tengo una duda con los tests (la escribo aquí porque hay muchas issues bloqueadas), ya que no me deja correr el código. ¿Para correr los tests es necesario colocar el archivo.py de codigo en la misma carpeta de los tests? Para que reconozca el import. Por ejemplo, en esto me arroja error siendo que si tengo definido ambos.
 Traceback (most recent call last):
  File "c:\Users\ACER\OneDrive\Escritorio\Avanzada-2023-2\Syllabus\Tareas\T1\tests\test_tablero_desglose.py", line 8, in <module>
    from tablero import Tablero
ModuleNotFoundError: No module named 'tablero'
