### ISSUE TITLE
Tiempos

### ISSUE THREAD

**Issue by gejohow** [IIC2233/Syllabus#730]
Al Momento de leer el canal, cuando se llega a un Note Off (128) que viene con un tiempo, se puede asumir inmediatamente el nombre del tiempo? Es decir, si sale 80 en el tiempo (80 ticks) que es 1/2 tiempo se asume directamente que es una corchea? 
Lo segundo es si la escala es lo mismo que la octava.
Saludos

**Comment by Hernan4444** [comment]
Hola, sobre la primera duda, si puedes asumir eso, puesto que dejamos como constante que 160 = 1 tiempo, entonces 80 si o si será medio tiempo.

Lo segundo: si, considera que son lo mismo.

Saludos ✌️
