### ISSUE TITLE
Respuestas siding

### ISSUE THREAD

**Issue by AmbrosioV** [IIC2233/Syllabus#730]
Que se supone que responda en cada una de las preguntas? En el que piden el repositorio supongo que sería el link de mi repositorio que cree especialmente para esta tarea, pero para el bot que se pide?
Es para asegurarme ya que no sé si se podrá introducir más de una respuesta (sobrescribirla)

**Comment by Hernan4444** [comment]
@AmbrosioV en repositorio publico de github es poner el link del repositorio que creaste y en la parte del bot es poner el alias del bot.
![image](https://user-images.githubusercontent.com/15641721/27552638-21b296a4-5a76-11e7-9270-2dd7193a2c25.png)

Para este caso sería `@BotFather`

Saludos!!
