### ISSUE TITLE
Uso args en init front end

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2233/syllabus#730]
Hola. En la actividad definian el init de la ventana incial como
```python
    def __init__(self, *args):
        super().__init__(*args)
        self.crear_pantalla()
```
Se para que sirve el args pero no entiendo su uso en este caso. Cuando voy a necesitar x cantidad de atributos y donde los uso.

**Comment by moquezada** [comment]
Hola @dsepulveda3 :)

Esto se hace precisamente para poder explotar las ventajas del uso de `args` tal como podría usarse en otros contextos. Por ejemplo, en un QWidget puedes darle como argumento `parent` y `WindowsFlags`. Este último sirve para setear los distintos`windowsFlags` de un QWidget. 

Para ver esto en detalle puedes ver la documentación de los QWidget y de los flags disponibles [aquí](https://doc.qt.io/qt-5/qwidget.html). En general, la documentación de Qt es muy completa y detallada así que puedes apoyarte mucho en ella para el desarrollo de la tarea (así lo hice yo cuando di el ramo) :)
