### ISSUE TITLE
No se debe permitir ingresar a dos usuarios con el mismo nombre 

### ISSUE THREAD

**Issue by Jiruiz2** [IIC2233/Syllabus#730]
En el enunciado dice "no se debe permitir ingresar a dos usuarios con el mismo nombre", esto significa que una persona no puede ingresar con el mismo nombre que una que ya está conectada o , en caso de que tengamos que tener guardados los nombres de usuario que han ido ingresando, que estos nombres de usuario no se pueden repetir?

**Comment by ifcarrera** [comment]
Hola! Significa que no pueden haber dos usuarios con el mismo username, es decir, lo segundo que mencionas

Saludos

**Comment by inmadariaga** [comment]
y si un usuario entra con un username, sale y quiere volver a entrar, con el mismo username?

**Comment by cjmunoz4** [comment]
Me sumo a la pregunta anterior, porque no le encuentro sentido lógico a que un usuario se conecte sólo una vez, y no se pueda volver a conectar

**Comment by Hernan4444** [comment]
Estimados, hubo un error. Lo más lógico es lo primero que se dijo, que al momento de ingresar, verificar que no exista otro usuario conectado con el mismo nombre. **No hay que tener guardados los nombres de usuario que han ido ingresando**

Saludos ✌️
