### ISSUE TITLE
Algún reemplazo para los threading.Event() en PyQt?

### ISSUE THREAD

**Issue by Gsalinas1506** [IIC2233/syllabus#730]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
 Cuando vimos Threads, vimos que existían los `event ` para evitar que los threads se solaparan unos con otros. **Existe un simil para estos Eventos en PyQt?**

**Comment by furcelay** [comment]
Hola @Gsalinas1506 !
Efectivamente existe un sistema de sincronización de QThreads en PyQt, puedes ver la [documentación](https://doc.qt.io/qt-5/threads-synchronizing.html).
*  [QMutex](https://doc.qt.io/qtforpython/PySide2/QtCore/QMutex.html) funciona como un lock con los métodos `lock()` y `unlock()` pero es para usarse en un único sector del código para evitar que múltiples threads accedan simultáneamente. 
*  [QSemaphore](https://doc.qt.io/qt-5/qsemaphore.html) es similar a un lock, posee métodos `acquire()` y `release()`, la diferencia con `QMutex` es que está pensado para ser usado en múltiples partes del código.
*  [QWaitCondition](https://doc.qt.io/qtforpython/PySide2/QtCore/QWaitCondition.html) funciona como un `Event` pero es un poco más complejo de usar ya que el método `wait` toma una instancia de `QMutex` como argumento, para que dejen de esperar se usa el método `wakeAll()`.

Puedes usar estas clases pero, aunque éstas son específicas para tratar con `QThreads` tienen algunas opciones más avanzadas que puede que no necesites y baste con usar las que vieron en los contenidos de módulo `threading`, que siguen siendo válidas.

Saludos! :smile:

**Comment by Gsalinas1506** [comment]
Ahh entiendo, gracias! Para usar las opciones que vimos en el módulo de `threading`, las importó como antes nomas? Sin meterle algo antes como `QEvent()` o `Qlock()` ?

**Comment by Zenos-Paradox** [comment]
Y un Thread normal, puede usar señales de pyqt5?

**Comment by furcelay** [comment]
> Y un Thread normal, puede usar señales de pyqt5?

No pueden! tienes que usar QThreads para eso, a lo que se refería éste hilo era a los eventos para sincronizar threads.

**Comment by kalarconvl** [comment]
> Hola @Gsalinas1506 !
> Efectivamente existe un sistema de sincronización de QThreads en PyQt, puedes ver la [documentación](https://doc.qt.io/qt-5/threads-synchronizing.html).
> 
> * [QMutex](https://doc.qt.io/qtforpython/PySide2/QtCore/QMutex.html) funciona como un lock con los métodos `lock()` y `unlock()` pero es para usarse en un único sector del código para evitar que múltiples threads accedan simultáneamente.
> * [QSemaphore](https://doc.qt.io/qt-5/qsemaphore.html) es similar a un lock, posee métodos `acquire()` y `release()`, la diferencia con `QMutex` es que está pensado para ser usado en múltiples partes del código.
> * [QWaitCondition](https://doc.qt.io/qtforpython/PySide2/QtCore/QWaitCondition.html) funciona como un `Event` pero es un poco más complejo de usar ya que el método `wait` toma una instancia de `QMutex` como argumento, para que dejen de esperar se usa el método `wakeAll()`.
> 
> Puedes usar estas clases pero, aunque éstas son específicas para tratar con `QThreads` tienen algunas opciones más avanzadas que puede que no necesites y baste con usar las que vieron en los contenidos de módulo `threading`, que siguen siendo válidas.
> 
> Saludos! 😄

Hola! Me explicarías cómo usar QSemaphore por favor? Hay que simplemente instanciar un objeto que herede de QSemaphore y poner acquire para pausar eventos? Y sobre esto, sirve para pausar cualquier evento o solo Qthreads? Me gustaría usarlo en 3 casos y no sé si se puede: 
- Para que, luego de finalizado el tiempo de la ronda, el Thread principal espere hasta que las flechas que están sobre el tablero terminen de bajar 
- Cuando se pone Pausa, para que las flechas se queden en su lugar y el QTimer que indica el tiempo de la ronda pare
- Cuando se pone salir, para parar las flechas y luego sacarlas del tablero no se cómo

**Comment by furcelay** [comment]
Hola @kalarconvl !
Los `QSemaphore` se usan de forma muy similar a los `Locks` (con `acquire` y `release`), pero están hechos para funcionar únicamente con `QThreads`. En general no es necesario crear una clase que herede de ellos, basta con crear una instancia que guardas como atributo del `QThread` al igual que hacían con los `Locks`. Ahora, recuerda que los locks se usan principalmente para asegurar que la información sea consistente entre threads, comúnmente en el caso en que más de un thread accede o modifica un recurso, evitando que lo hagan a la vez, y veo que ese no es tu caso...

En los casos respectivos:
*  Cuando finaliza la ronda y aún quedan flechas el main thread debería seguir recibiendo el input de usuario ya que aún debe poder atrapar flechas, pausar, etc., por lo que no deberías detenerlo con un `QSemaphore`.
*  Si usas un `QSemaphore` para mover las flechas básicamente estarías diciendo que el desplazamiento de las flechas es un recurso crítico y estarías evitando que más de una flecha pueda moverse a la vez. 
*  Si quieres sacar las flechas es necesario que su thread termine correctamente, si usas un `QSemaphore` se quedarán atascadas dentro del thread. (nota: como una ayudita para sacar las flechas, no se puede borrar un label, pero basta con ocultarlo con `hide()`)

Para los tres casos que mencionas podrías considerar usar señales y eventos, principalmente con las señales `pyqtSignal` que envíen la información asociada cuando ocurra un evento (ej: al pausar), pero quizás también puedes usar los `Event` de `threading`.

Saludos! 😄
