### ISSUE TITLE
LET del bonus tarea 7

### ISSUE THREAD

**Issue by benjamimo1** [IIC2233/Syllabus#731]
Hola! No entiendo esto "Cada vez que se abra una issue que contenga en su contenido algu ́n bloque de c ́odigo de Markdown que en su u ́ltima l ́ınea contenga alguna excepci ́on de Python, el bot debe comentar autom ́aticamente un enlace que pueda ser de ayuda para solucionar el problema que se plantea." 
Me podrian dar un ejemplo? 
Gracias!

**Comment by rjdelrio** [comment]
yo tengo la misma duda que tu, seria genial si dieran un ejemplo por favor

**Comment by iqacevedo** [comment]
Hola

Podría ser una issue de este tipo:

"Hola llevo mucho rato intentado resolver este error, tengo definida una variable `a = [1,2,3]` y otra `b="[4,5,6]"`, cuando intento sumar estas dos listas `a+b` me sale lo siguiente:

TypeError: can only concatenate list (not "str") to list"

Luego el bot podría comentar algo del estilo:

"Revistaste [acá](https://stackoverflow.com/questions/19398993/typeerror-can-only-concatenate-list-not-str-to-list) ? 
Saludos"

**Comment by nivek0o0** [comment]
Hola @iqacevedo, pero del enunciado se da a entender que se debe buscar un error en la última línea de un bloque de código.
¿Entonces no debería estar dentro de las comillas triples ´´´   ´´´ ?

**Comment by benjamimo1** [comment]
Basta entonces con buscar la palabra error en el issue,  y buscar las palabras siguientes?

**Comment by rjdelrio** [comment]
entonces busco explicitamente si sale la palabra error en la ultima linea y si sale busco la ultima linea en google por ejemplo

**Comment by benjamimo1** [comment]
Que tipo de errores ha de manejar? Todos?

**Comment by iqacevedo** [comment]
@nivek0o0 como dices debería estar dentro de un bloque de código, en markdown hay distintas formas de escribir código, pero solo pediremos que reconozcan cuando están escritas tal como dices, entre comillas, sin embargo las comillas son en la otra dirección `````` (arregle el ejemplo de arriba, gracias por notarlo).

@benjamimo1 con esto si deberías buscar que este dentro de un bloque de código y claro que sea uno de los errores que te pueden arrojar, debería poder manejar cualquier error, si los buscas no son muchos.

@rjdelrio debes verificar que este dentro de un bloque de código, luego buscar el error en un buscador, puede ser google tal como dices.

Cualquier cosa no duden en preguntar !

**Comment by frvalenzuela** [comment]
@iqacevedo debemos considerar el caso en que el usuario no cierre la triple comillas?

**Comment by akaminetzkyp** [comment]
@iqacevedo, no me quedó muy clara una cosa. En el enunciado, con "bloque de código markdown" se da a entender que el código estará dentro de comillas triples (```) y no simples (`). ¿Estoy en lo correcto?

Saludos!

**Comment by iqacevedo** [comment]
@frvalenzuela como el enunciado dice que sea en algún bloque de código, puedes solo buscar aquellos que tengan cerradas las triples comillas.
@akaminetzkyp si, basta con que consideres el caso en que el código estará dentro de comillas triples. 

Saludos !

**Comment by akaminetzkyp** [comment]
Muchas gracias!
