### ISSUE TITLE
Imagenes agregadas desde QtDesigner

### ISSUE THREAD

**Issue by Mamunoz42** [IIC2233/syllabus#731]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Holaaaaa! 😄 

Quería consultar sobre como se puede controlar que el ``path`` utilizado en el ``pixmap`` de QtDesigner no tenga problemas a la hora que sea revisado mi juego? O es recomendable agregar la imagen a través de código?

**Comment by bvasquezm** [comment]
Hola @Mamunoz42!

No hay problema con que lo hagas desde designer, sólo debes preocuparte de mantener tus sprites en la carpeta correspondiente, junto a los ``archivos.ui`` generados por designer. De esta manera podrá encontrar las imágenes a las cuáles hiciste referencia. Saludos!

**Comment by Mamunoz42** [comment]
Me surge otra duda, ya que la carpeta de los sprites debe ser ignorada, entonces no me queda claro donde debo ubicar los ``archivos.ui``.
También quería consultar si uno puede utilizar letras(fuentes) distintas las predefinidas por los sistemas operativos mientras yo ponga el instalador de esta fuente? O esto no es posible?

**Comment by bvasquezm** [comment]
Recuerda que todos los directorios y/o archivos que ignoras, luego se encontrarán en el directorio de tu ayudante corrector (como la carpeta sprites). Por otro lado, puedes elegir la fuente que desees para tus labels, si lo estás haciendo en designer no tienes que “descargar” nada en python (a menos que sea una fuente externa a ambos programas o al s.o como señalas), te recomiendo usar las que vienen por defecto.

**Comment by Mamunoz42** [comment]
Muchas gracias
