### ISSUE TITLE
Error al conectar señales

### ISSUE THREAD

**Issue by RenatoVWS** [IIC2233/syllabus#731]
Hola, 

Estoy tratando de conectar una señal que emite una clase Cargar del backend a una clase VentanaJuego en el frontend. El problema es que cuando conecto ambas clases en el main: 

_cargar.senal_cargar_mapa.connect(ventana_juego.configurar_mapa)_

No se me ejecuta el método _configurar_mapa_, a pesar de que que emití la señal antes.

¿Podría ser un error en la clase VentanaJuego que no recibe las señales o de instalación de un paquete quizás?

Espero que me puedan ayudar,
Saludos :)

**Comment by jeschuwirth** [comment]
Holaaa, es más sencillo resolver estas dudas si me entregas un código o pseudocódigo de lo que llevas, me puedes mostrar ambas clases y el emit porfa.

Te recuerdo "cerrar los otros métodos para no compartir mucho código"

**Comment by RenatoVWS** [comment]
Holaa, se me pasó mira este es mi problema:

Cuando conecto esto en el main: 
`cargar.cargar_mapa(pm.PATH_MAPA_CSV, pm.DIC_PATH_SPRITES)
  cargar.senal_cargar_mapa.connect(ventana_juego.configurar_mapa)`
La señal `senal_cargar_mapa` no me funciona. En cargar tengo:

> `registrado = Entidad(entidad[0], int(entidad[1]), int(entidad[2]), path)`

> `self.entidades.append(registrado)`

`self.senal_cargar_mapa.emit(self.entidades)`

Y el slot está en la clase VentanaJuego:
`def configurar_mapa(self, lista):`
		
> `self.mesas = list()`
	
> `self.chefs = list()`

¿Podría deberse a alguna configuración de VentanaJuego, porque está diseñada en Qt Designer y quizás no reconoce ese slot?

Gracias!

**Comment by fdoflorenzano** [comment]
Hola @RenatoVWS,

Eliminé tu comentario anterior ya que compartiste código explícito. Ten ojo por favor en no compartir código propio de tu tarea.  Intenta hacer un ejemplo con pseudocódigo para entender el problema. Intente generar clases vacias con nombres sin significado (como `A` y `B`), y emule lo que pasa con tus señales.

En el peor de los casos, indica las clases en tu repositorio con el problema, pero esto le tomará más tiempo al ayudante de revisar.

Saludos.

**Comment by jeschuwirth** [comment]
@RenatoVWS,

Para evitar problemas sube el código al tu repo y avísame comentando en esta issue para revisarlo :)

**Comment by RenatoVWS** [comment]
Hola, perdón por lo anterior. Ya lo subí a la repo

Gracias :)

**Comment by jeschuwirth** [comment]
Hola @RenatoVWS,

Tenías un problema muy pequeño, debes conectar la señal antes de emitirla, simplemente cambiando de lugar las líneas 19 y 20 de tu archivo main.py debería funcionar :)

Aprovecho de recordarte que se deben usar espacios en lugar tabs para la indentación, puedes instalar paquetes o cambiar la configuración la mayoría de los IDE para que estas hagan el cambio de manera automática en tu tecla de tab.

Éxito ! y avisa si no te funciona la solución :)

**Comment by RenatoVWS** [comment]
Si me funcionó. Muchas gracias por tu ayuda!
