### ISSUE TITLE
Duda Escritura Header

### ISSUE THREAD

**Issue by kenzoak** [IIC2233/Syllabus#731]
Como para la tarea el header siempre será igual (A menos que se haga el bonus) puedo simplemente agregar los bytes que corresponden a este formato en vez de tener que procesarlos cada vez? Con esto me refiero a tener un bytearray predefinido con la informacion del header.  O tendría que dejar estos parametros definidos para que puedan ser modificados? 
Gracias

**Comment by Hernan4444** [comment]
@kenzoak si no vas a hacer el bonus, si puedes dejarlo predefinido el bytearray.
Saludos ✌️
