### ISSUE TITLE
Código en Inglés

### ISSUE THREAD

**Issue by nicolaszanni** [IIC2233/syllabus#732]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Estoy escribiendo mi código en inglés para acostumbrarme como buena práctica. La duda que me surge es que la mayoría de los parámetros que se deben incluir están en español. ¿Hay algún problema en cambiar tales parámetros a su equivalente en inglés?

**Comment by danckoo1** [comment]
Hola, no habría ningún problema con que los pases a ingles, pero no olvides señalarlo en tu readme! para que quien te corrija este al tanto 😄
