### ISSUE TITLE
Ayuda D:

### ISSUE THREAD

**Issue by Okhan97** [IIC2233/Syllabus#732]
![image](https://user-images.githubusercontent.com/26289334/27541436-ea833270-5a51-11e7-9e1f-7ae81e022607.png)
 
Me sigue apareciendo el mismo error una y otra vez, ya no se que hacer 😭 

Es normal que intente iniciar el programa con varios puertos ?

**Comment by nivek0o0** [comment]
Probaste correr tu aplicación de forma local con ngrok?
De ese modo en la consola donde ejecutes el main puedes ver si el error está en el código.

**Comment by Okhan97** [comment]
@nivek0o0  Si, tal como dicen en el enunciado (me responde que se cambió y todo). Ya he estado muchos dias peleando con heroku, a falta de respuestas tendré que seguir con ngork

**Comment by iqacevedo** [comment]
@Okhan97 cuando seteaste la variable de entorno, ¿comprobaste que no tuviera el "." al final del comando?, si hiciste todo bien te salio un mensaje así cuando seteaste la variable?

![captura](https://user-images.githubusercontent.com/13748732/27551961-7d8fc44a-5a73-11e7-83c0-46f4fd5a907f.PNG)

Saludos !

**Comment by Okhan97** [comment]
@iqacevedo Efectivamente comprobé que no tuviera ese punto y me apareció ese mensaje

**Comment by iqacevedo** [comment]
Tu programa desde donde corres flask se llama main.py verdad ? Si tiene otro nombre debes poner ese nombre cuando seteas la variable.

Se solucionó tu problema ? O aún tienes el mismo error ?

**Comment by Okhan97** [comment]
Deje de intentarlo hace un rato, estoy avanzando en ngrok.

Revisaré en un rato, pero si, mi programa "main.py" importa de "superduperapp.py" y despues 
`app = misuperduperapp.app
 app.run(host='0.0.0.0',port=puerto)`
