### ISSUE TITLE
Duda interfaz + networking

### ISSUE THREAD

**Issue by fpattillo** [IIC2233/Syllabus#732]
Hola!
Antes de implementar cliente-servidor, hice la interfaz con QtDesigner y por si sola funcionaba todo, sin embargo cuando trato de inicializarla desde un cliente, se queda pegado en el super().__init__(). Qué podría estar pasando??

**Comment by Arcoirisky** [comment]
No debería de ocasionarte problemas la interfaz ya que Qtdesigner sólo hace la interfaz O: 

Fíjate en cómo haces la conexión cliente servidor, seguramente quedaste en un loop o un error se te está pasando a la interfaz. Si Ya Tienes el código atrapa errores que se les dió en la tarea pasada o: Prueba con conectar a tus clientes sin la interfaz de por medio :D

**Comment by fpattillo** [comment]
Sin la interfaz de por medio funciona la conexión (igual hice un servidor súper básico como el de comunicación básica de la ayudantía) y lo otro es que nunca me funcionó el código atrapa errores, lo traté de implementar ahora y tampoco... Para confirmar, es así o no??
![captura de pantalla 12](https://user-images.githubusercontent.com/37159447/41564368-95fb196e-7320-11e8-9c6a-9269d70d2fca.png)
