### ISSUE TITLE
Dimensiones de la ventana de edición vs dimensiones de la imagen original

### ISSUE THREAD

**Issue by ChayoPerez** [IIC2233/Syllabus#732]
Mi pregunta es: qué pasa si la imagen es más grande de lo que puedo mostrar en la pantalla? Porque si achico la imagen, sus pixeles cambian, algunos se pierden, y las modificaciones (específicamente el balde) que el usuario cree que está haciendo en pantalla y las que ocurren en la imagen original serían distintas

Gracias

**Comment by behrmann97** [comment]
Quería preguntar lo mismo... ¿Se puede poner scaled a la imagen que se muestra?

**Comment by Jiparavich** [comment]
x3

**Comment by Javierdr** [comment]
X4

**Comment by jvlara** [comment]
x5

**Comment by SarahEverke** [comment]
x6
