### ISSUE TITLE
desproporciones ventana inicial

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2233/syllabus#732]
Hola estoy usando self.setGeometry(500, 100, 500, 400) para setear el tamaño de la ventana. Resulta que cuando agrego la imagen con layouts se me desconfigura y se me abre una ventana gigante mas grande que mi pantalla con una imagen de DCCafe gigante. Como puedo solucionarlo?

**Comment by jbulness** [comment]
Hola @dsepulveda3!

Para que no te aparezca una imagen gigante que te desconfigure el tamaño de la ventana puedes fijar el tamaño de la imagen. Así también, puedes fijar el tamaño de la ventana (o de cualquier __widget__) para que se mantenga de un tamaño determinado. Esto último lo puedes hacer con el comando `setFixedSize(largo, ancho)` (o ancho, largo; no estoy seguro cual es el orden), así mantendrás el tamaño de tu ventana, pero la imagen seguirá siendo grande, por lo que deberás ajustar su tamaño también.

Tu problema pasa porque `setGeometry()` da un tamaño inicial a la ventana en una ubicación inicial de tu pantalla, pero no evita que esta ventana se pueda agrandar o achicar. 

Espero que te sirva esta respuesta. Si no es así, no dudes en comentar nuevamente!
