### ISSUE TITLE
ConnectionRefusedError: [WinError 10061]

### ISSUE THREAD

**Issue by gejohow** [IIC2233/Syllabus#733]
"ConnectionRefusedError: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión"

He intentado de todo para conectar el server con el client pero me sigue tirando este error, me gustaria saber si alguien sabe como solucionarlo.

**Comment by Arcoirisky** [comment]
Hay dos issues con El mismo error O: ¿Probaste algunas de esas soluciones?
