### ISSUE TITLE
Importar os en parametros.py para rutas

### ISSUE THREAD

**Issue by Jamesmoreno21** [IIC2233/syllabus#733]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Quería saber si se considera mala práctica utilizar el módulo *os* con *path.join()* en *parametros.py* para armar las rutas respectiva a archivos, fotos, etc. Actualmente hago una tupla en parametros.py y luego en cada modulo importo estas tuplas para redefinir rutas con *path.join()* en otro modulo *x.py* pero siento que es "poco óptimo" y que sería mejor importar directamente una ruta hecha de los parametros.py. Gracias de antemano

Saludos!

**Comment by knight-who-say-ni** [comment]
Hola @Jamesmoreno21 !! No solo está permitido, sino que recomendado :stuck_out_tongue_closed_eyes::stuck_out_tongue_closed_eyes: ya que asi se evitan los problemas que pueda causar cada sistema operativo en cuanto a rutas.

Exito programando!!
