### ISSUE TITLE
ocupar y agregar información de mapa.csv

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#733]
Hola!
No entiendo muy bien cómo manejar la información que hay en ```mapa.csv``` . Lo que entiendo es que las posiciones (x,y) del mesero, mesa y chef deben estar dentro del mapa? Entonces la posición del mapa es definida por uno mismo? mientras se cumpla que los objetos este en la posición que sale en ```mapa.csv``` ¿?.
Lo otro es que no sé cómo hacer esto, porque por ejemplo yo cargé mi mapa en una ventana creada en  Qt Designer, entonces mi pregunta es si es posible agregar objetos al mapa desde VSC en esta ventana creada en Qt Desginer? O tengo que agregar estos objetos en el mismo programa Qt Designer?

**Comment by kadroguett** [comment]
Hola @Camila-sty 
Si, las coordenadas que se dan de mesero y chef deben estar dentro del mapa.
Si te refieres a la posición de la ventana en la pantalla, si, tú decides dónde ubicarla. 
Si en lugar de la posición te refieres al tamaño, en el enunciado se explica que el mapa debe estar dentro de los parámetros ANCHO_MAPA y LARGO_MAPA. Por lo que si bien tú decides sus valores, deben estar en el archivo parametros.py, ahora sí realizas tu ventana de mapa en QtDesigner no podrás usar adecuadamente estos parámetros. 
Respondiendo a tu última pregunta, si es posible agregar objetos a la ventana por medio de VSC.

**Comment by Camila-sty** [comment]
Pero entonces no es recomendable hacer el mapa en QtDesigener? . Porque yo puedo sacar la medida que usé en QtDesigner y ponerlas en ```parametros.py``` ylisto. Pero si piden que utilice directamente el ANCHO_MAPA y LARGO_MAPA de ```parametros.py```, entonces ya no podría cargar la imagen de mapa en QtDesigner. La verdad es que estoy complicandome harto con esto, porque yo supongo que ustedes son dieron a conocer QtDesigner para crear ventanas y todo el tema, pero también piden respetar las medidas entonces no entiendo. Me podrías explicar esto porfa? , no entiendo cual es el sentido de tener estas medidas en```parametros.py``` , tengo que si o si usarlas dentro del código VSC?

**Comment by kadroguett** [comment]
Si tomas las medidas de la ventana y las únicas en 
`parametros.py` no estarías utilizando correctamente el parámetro, ya que solo estaría en el archivo sin importarse ni usarse. Es por esto que no se recomienda hacer está ventana en QtDesigner.
La idea de QtDesigner es la de crear ventanas que no presenten un tamaño variable, como es el caso de un par de ventanas presentes en la tarea (aunque igual se puede hacer mediante código, va a depender de la preferencia de cada uno).
Finalmente los valores presentes `parametros.py` si se deben utilizar en el código, ya que ese es el objetivo de este archivo.

**Comment by Camila-sty** [comment]
Ok, entendí. Gracias

**Comment by kadroguett** [comment]
De nada, Éxito en tu tarea!! 😺

**Comment by Camila-sty** [comment]
Consulta, si compro una mesa o un chef, esta información debo agregarla al archivo ```mapa.csv``` ?

**Comment by kadroguett** [comment]
Cómo se menciona en la sección archivos del enunciado, los archivos deben modificarse con cada ejecución del programa.

**Comment by Camila-sty** [comment]
Ya, puedo cambiar la posición de los objetos que están en ´´´mapa.csv´´´ ?

**Comment by kadroguett** [comment]
Te refieres a cambiarlas manualmente en el archivo?

**Comment by Camila-sty** [comment]
sí

**Comment by kadroguett** [comment]
Revisando las issues noté que te respondieron esa pregunta en la #734. A futuro trata de no duplicar issues y que las preguntas que hagas en una misma issue tengan relación con la pregunta inicial, de otro modo prefiere abrir una nueva
