### ISSUE TITLE
Actualización de galería visto desde el dashboard

### ISSUE THREAD

**Issue by ChayoPerez** [IIC2233/Syllabus#733]
Hola, tengo una duda. Según se editan las 6 imágenes que se pueden ver en el dashboard, un usuario que tiene abierto el dashboard las ve en tiempo real? O es válido si le muestro la última versión existente cuando ingresó? Quizás con un botón para actualizarlas si lo desea o que cada cierto tiempo se le pregunte al servidor si han habido cambios?

Gracias

**Comment by egromero** [comment]
Hola, 

Solo el espectador es obligatorio que se actualice en tiempo real. Es valido mostrar el dashboard con la ultima actualización existente cuando ingresó.

Ahora, cuando salgas de la ventana de edición. En el dashboard deben verse reflejado todos los cambios.

Si haces lo del botón, déjalo escrito en tu readme.

Saludos

**Comment by inmadariaga** [comment]
Como se puede trabajar solo con 4, es necesario que se sigan mostrando las 6 imagenes?

**Comment by FernandoPieressa** [comment]
@inmadariaga Si, porque las que les dimos es solo para facilitarles el trabajo de buscar nuevas, pero su programa debe poder aceptar nuevas imágenes, recuerda que el usuario puede ingresar imágenes al sistema!(Siempre con el formato PNG de las 4 imágenes que entregamos)
