### ISSUE TITLE
Setear webhook de github

### ISSUE THREAD

**Issue by lvvillarroel** [IIC2233/Syllabus#733]
Hola!
Cuando trato de setear la webhook de github, me tira error 404 y el diccionario: {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
He seguido todos los pasos de la documentación, pero sigue sin funcionar :(

**Comment by asdegoyeneche** [comment]
Hola! Me pasa lo mismo, como lo resolviste?

**Comment by acrojas2** [comment]
Hola, tengo un problema gigante con esto, seteo el webhook y todo pero al setearlo y poner que me notifique las issues (luego de hace esto) y revisar los webhooks de la repo me sale algo como esto y además no me están llegando las notificaciones de las issues nuevas. 
<img width="773" alt="captura de pantalla 2017-06-26 a las 7 55 20 p m" src="https://user-images.githubusercontent.com/26121354/27565075-db0d5c96-5aa9-11e7-93d1-c2cfbec52487.png">
@MainScientist ayudaaa!
saludos!

**Comment by akaminetzkyp** [comment]
¿No se puede ver por qué sale ese "!"?

**Comment by acrojas2** [comment]
Creo que es esto, pero no lo entiendo y no sé como arregarlo. @akaminetzkyp 
<img width="750" alt="captura de pantalla 2017-06-26 a las 8 10 06 p m" src="https://user-images.githubusercontent.com/26121354/27565307-8459f2ea-5aab-11e7-8743-3f6c2c458fc5.png">

**Comment by akaminetzkyp** [comment]
Mish, que raro. ¿Trataste de hacer `heroku login`, como dice ahí?
