### ISSUE TITLE
Backlash en bytes

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#734]
![image](https://user-images.githubusercontent.com/66154723/124525112-eed57c00-ddcb-11eb-9388-8d25d7f7e2e5.png)

**Comment by matiasmasjuan** [comment]
Hola @fernandosmither !

Para responder a tu pregunta, es necesario entender que **todo** tipo de valor que **interpreta** un computador, se realiza mediante una cadena de ***bits***. Cada *bit* puede tener un valor 1 o 0. Si bien ésta es la unidad básica de un computador, por lo general se utiliza el *byte* para representar una cadena de 8 *bits*. Teniendo en cuenta esto, es necesario entender que **todo** valor o caracter, número, float, etc, está representado mediante *bytes*. Esto quiere decir, que el *char* **"B"** que tu mencionas, es efectivamente, una serie de *bytes*. Ahora bien, lo que realiza el método ```int.from_bytes()``` es tomar esa secuencia de *bytes* e interpretarlos como si fuera un *int*. Esto quiere decir que si el *char* "B" es el *bytearray* ```b'\x80\x04\x95\x05\x00\x00\x00\x00\x00\x00\x00\x8c\x01B\x94.'```, entonces esa cadena de *bytes* también puede ser representada como el número **66** con el método ```int.from_bytes()```. Lo mismo aplica con el *char* **"\\"**. Esto también representa una cadena de *bytes*, y al juntarlo con el *char* "B" y se pasan a *int*, entonces equivalen al número 16988.

Con respecto al *byteorder*, en el enunciado de la tarea dejamos una *footnote* para que pudieran investigar por si tenian dudas.
![image](https://user-images.githubusercontent.com/48495638/124550011-062d5d00-ddfe-11eb-830a-30498cd48079.png)
El *byteorder* y los *endianness* tiene relación con el orden de lectura de los *bytes*. *little endian* significa que los *bytes* menos significativos se almacenan antes que los más significativos, y *big endian* es que los más significativos se almacenan antes que los menos significativos. Es sumamente importante tener claro el orden *little endian* y *big endian*, ya que como son *bytes*, en caso de que se cambie el orden de lectura y se pasan a valores enteros por ejemplo, pueden devolver un número completamente distinto al esperado.

A fin de cuentas, lo que interpreta una máquina como *bytes* puede ser realmente una infinidad de cosas. Un *byte* puede significar un número, una letra, un decimal, un color, un animal, etc. Es por esta razón que si uno interpreta un *byte* no de la forma esperada, uno recibe estos resultados.

Si tienes alguna duda o simplemente curiosidad sobre el tema, te invito a tomar el curso de **Arquitectura de Computadores** (**IIC2343**) ya que se profundiza mucho más acerca del tema.

Saludos, y mucho éxito con la tarea! :smile:

**Comment by fernandosmither** [comment]
> Hola @fernandosmither !
> 
> Para responder a tu pregunta, es necesario entender que **todo** tipo de valor que **interpreta** un computador, se realiza mediante una cadena de _**bits**_. Cada _bit_ puede tener un valor 1 o 0. Si bien ésta es la unidad básica de un computador, por lo general se utiliza el _byte_ para representar una cadena de 8 _bits_. Teniendo en cuenta esto, es necesario entender que **todo** valor o caracter, número, float, etc, está representado mediante _bytes_. Esto quiere decir, que el _char_ **"B"** que tu mencionas, es efectivamente, una serie de _bytes_. Ahora bien, lo que realiza el método `int.from_bytes()` es tomar esa secuencia de _bytes_ e interpretarlos como si fuera un _int_. Esto quiere decir que si el _char_ "B" es el _bytearray_ `b'\x80\x04\x95\x05\x00\x00\x00\x00\x00\x00\x00\x8c\x01B\x94.'`, entonces esa cadena de _bytes_ también puede ser representada como el número **66** con el método `int.from_bytes()`. Lo mismo aplica con el _char_ **"\"**. Esto también representa una cadena de _bytes_, y al juntarlo con el _char_ "B" y se pasan a _int_, entonces equivalen al número 16988.
> 
> Con respecto al _byteorder_, en el enunciado de la tarea dejamos una _footnote_ para que pudieran investigar por si tenian dudas.
> ![image](https://user-images.githubusercontent.com/48495638/124550011-062d5d00-ddfe-11eb-830a-30498cd48079.png)
> El _byteorder_ y los _endianness_ tiene relación con el orden de lectura de los _bytes_. _little endian_ significa que los _bytes_ menos significativos se almacenan antes que los más significativos, y _big endian_ es que los más significativos se almacenan antes que los menos significativos. Es sumamente importante tener claro el orden _little endian_ y _big endian_, ya que como son _bytes_, en caso de que se cambie el orden de lectura y se pasan a valores enteros por ejemplo, pueden devolver un número completamente distinto al esperado.
> 
> A fin de cuentas, lo que interpreta una máquina como _bytes_ puede ser realmente una infinidad de cosas. Un _byte_ puede significar un número, una letra, un decimal, un color, un animal, etc. Es por esta razón que si uno interpreta un _byte_ no de la forma esperada, uno recibe estos resultados.
> 
> Si tienes alguna duda o simplemente curiosidad sobre el tema, te invito a tomar el curso de **Arquitectura de Computadores** (**IIC2343**) ya que se profundiza mucho más acerca del tema.
> 
> Saludos, y mucho éxito con la tarea! 😄

Perfecto, me queda más claro!

Saludos
