### ISSUE TITLE
Issues de prueba en repo 

### ISSUE THREAD

**Issue by egromero** [IIC2233/Syllabus#734]
Holaa, no encuentro la forma de borrar las issues y los labels de prueba que hice en el repositorio público, hay algun problema con que queden ahí? otro, le dije a un amigo que probara mi bot y puso un par de chilenismos en las labels y bueno, lo mismo de arriba, no se como borrarlo, hay algún descuento por eso?

Gracias!

**Comment by stephichau** [comment]
@egromero te recuerdo que las entregas son formales, por lo que ten ojo con el vocabulario :) Para editar/borrar los labels, puedes revisar [este link](https://help.github.com/articles/creating-and-editing-labels-for-issues-and-pull-requests/).

Saludos
