### ISSUE TITLE
Color en ventanas QtDesigner

### ISSUE THREAD

**Issue by BFry712** [IIC2233/syllabus#734]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Holaaaa! queria saber si se puede y como se podria poner color por partes a la ventana en Qtdesigner para poder organizarla mejor. Saludos!

**Comment by jaimecoloma** [comment]
Hola @BFry712 !! Efectivamente si se puede poner color y de muchas formas ingeniosas si quisieras 😄, la forma más sencilla que se me ocurre es que agregues un Label sin texto y lo rellenes con color de fondo. Para esto cuando agregas el label a colorear, te vas al Property Editor, y en la parte de Qwidget, te vas a StyleSheet, luego allí aprietas donde sale Add Color / Background Color y allí puedes señalar el color que quieras (tienes paletas de colores) y QtDesigner te lo agrega con el nombre del color. Una vez lo hagas pon OK y listo! Deberias visualizarlo bien.
Te dejo un mini ejemplo, con otros Widgets encima.
![Captura de Pantalla 2020-10-20 a la(s) 12 14 38](https://user-images.githubusercontent.com/62038531/96606597-d4a34e80-12cd-11eb-92ff-97df073b2861.png)
Espero haberte ayudado! Si no es lo que buscabas no dudes en preguntarme de nuevo!

**Comment by BFry712** [comment]
Muchas gracias @jaimecoloma ! te pasaste

**Comment by betolguin** [comment]
hola! @BFry712  intenté hacer lo que respondiste, pero me aparece que es invalido :( feliz si me ayudas a resolverlo!!
gracias de antemano, saludos
![Uploading 2020-10-20 (2).png…]()

**Comment by Natydlb** [comment]
Hola! A mi también me apareció que no se puede pero creo que es porque antes tenía instalado anaconda y se configuró con eso, pero nose como cambiar esa “configuración”, ayuda:(
![Uploading image.jpg…]()

**Comment by aaossa** [comment]
@betolguin @Natydlb sus imágenes no se ven 😅 Tienen que darle unos segundos para que la imagen se alcance a subir. Les recomiendo editar sus mensajes para colocar las imágenes que querían 👌

**Comment by Natydlb** [comment]
Ahí si profe :) sorry

**Comment by jaimecoloma** [comment]
@Natydlb Es porque no se está especificando en donde agregar el color, para esto aprieta la flechita de Add Color y ahi te va a tirar opciones, luego señalando Background color lo va a asociar!
Es algo como: Background-color(rgb...)

**Comment by betolguin** [comment]
🆘

**Comment by aaossa** [comment]
> 
> 
> 🆘

@betolguin no es necesario que coloques mensajes así, les ayudantes también tienen cursos y todes tenemos otras responsabilidades 😅 Hacemos lo que podemos para atenderles lo antes posible y lo único que hacen respuestas así es agregar "ruido". No lo hagas de nuevo plis 🙏

**Comment by jaimecoloma** [comment]
Dejo fotos de como deberían ejecutar los últimos pasos.
![Captura de Pantalla 2020-10-20 a la(s) 19 22 44](https://user-images.githubusercontent.com/62038531/96650676-a2afdd80-1309-11eb-885e-1bdb62d3526b.png)
Aquí luego de seleccionar Background-color, deben elegir el color y debería devolverlos con lo siguiente.
![Captura de Pantalla 2020-10-20 a la(s) 19 23 19](https://user-images.githubusercontent.com/62038531/96650716-b78c7100-1309-11eb-8305-e26e7ce70235.png)

**Comment by betolguin** [comment]
> > 🆘
> 
> @betolguin no es necesario que coloques mensajes así, les ayudantes también tienen cursos y todes tenemos otras responsabilidades 😅 Hacemos lo que podemos para atenderles lo antes posible y lo único que hacen respuestas así es agregar "ruido" 🙏

Sorry! no era con mala intención.. saludos!!

**Comment by betolguin** [comment]
> Dejo fotos de como deberían ejecutar los últimos pasos.
> ![Captura de Pantalla 2020-10-20 a la(s) 19 22 44](https://user-images.githubusercontent.com/62038531/96650676-a2afdd80-1309-11eb-885e-1bdb62d3526b.png)
> Aquí luego de seleccionar Background-color, deben elegir el color y debería devolverlos con lo siguiente.
> ![Captura de Pantalla 2020-10-20 a la(s) 19 23 19](https://user-images.githubusercontent.com/62038531/96650716-b78c7100-1309-11eb-8305-e26e7ce70235.png)
> 
> Espero con esto ya no tengan problemas!

GRACIAS!!
aunque no me aparece el mismo menú, con el comando background-color me deja poner el color, sin embargo, no se "setea" en el label :( sabes por qué puede ser??
<img width="458" alt="Captura" src="https://user-images.githubusercontent.com/69482524/96738425-13500c00-1395-11eb-9a01-a99f6b0ac0c7.PNG">

**Comment by jaimecoloma** [comment]
@betolguin para que lo haga solo debes hacerlo en el mismo menú que mostraste en la primera foto! Si puedes acceder allí deberias poder. Lo otro es que me metí de nuevo para revisar como queda esa sección una vez que yo seteo el color y noté que la unica diferencia entre tu imagen y lo mío es que al final deberías agregar punto y coma ( ; ) podrías probar eso. De todos modos intenta igual lo primero que te dije porque es más fácil y puedes agregar colores en otras partes si quieres (como color de letra por ejemplo). Avisame como te va!

**Comment by betolguin** [comment]
> @betolguin para que lo haga solo debes hacerlo en el mismo menú que mostraste en la primera foto que mandaste al principio! Si puedes acceder allí deberias poder. Lo otro es que me metí de nuevo para revisar como queda esa sección una vez que yo seteo el color y noté que la unica diferencia entre tu imagen y lo mío es que al final deberías agregar punto y coma ( ; ) podrías probar eso. De todos modos intenta igual lo primero que te dije porque es más fácil y puedes agregar colores en otras partes si quieres (como color de letra por ejemplo). Avisame como te va!
