### ISSUE TITLE
utilidad del archivo mapa.csv para cargar el mapa

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#734]
Hola!
Las posiciones de los objetos contenidos en ```mapa.csv``` son las mismas que pusieron de ejemplo en el PDF publicado sobre "ejemplos de formas de cargar el mapa" ¿?. Si es así, cuál es la idea de ésto? Porque por ejemplo el chef queda bastante mal ubicado, yo lo dejaría en un borde del mapa de la tienda, entonces no entiendo cuál es la idea de respectar estas posiciones?.También leí por ahí que uno podría cambiar las posición de estos objetos y así modificar el archivo  ```mapa.csv``` , pero para poder hacer esto, necesito saber cuál es la idea del archivo y de que pidan esto en el avance¿?

**Comment by jitorcas** [comment]
Hola @Camila-sty 
Así es, se utilizaron los valores del archivo `mapas.csv`. 

El objetivo del archivo `mapas.csv` es que cuando un jugador decida **guardar la partida** y posteriormente **reanudarla**, tengas la información de la ubicación de los elementos en el mapa. Tal como dices, puedes editar el archivo a tu conveniencia, sin embargo tu programa debe ser consistente y capaz de situar los objetos dependiendo de la ubicación que salga en `mapas.csv`.

El archivo que subimos, es un ejemplo de mapa, en caso que desees editarlo toma en cuenta que no pueden existir colisiones entre los objetos.
