### ISSUE TITLE
Como se usa decompress de zlib?

### ISSUE THREAD

**Issue by AndresGarciadelaHuerta** [IIC2233/Syllabus#734]
Llevo harto rato tratando y buscando en internet como usar bien zlib.decompress() y no he logrado que me retorne la matriz de pixeles de Knightmare.png. Le estoy haciendo decompress a la sección de información del idat de la imagen, y lo que me imprime es:
![captura de pantalla 2017-11-13 a la s 17 00 49](https://user-images.githubusercontent.com/30664883/32746389-3af0c2b2-c894-11e7-94cf-e12b255a3b42.png)
Alguien sabe que puedo estar haciendo mal o que le haya pasado lo mismo?

**Comment by fgbruna** [comment]
Me sumo a esta pregunta, creía que había logrado obtener una matriz adecuada tomando de a tres bytes (Por lo que entendí del enunciado en la parte de hacer el proceso inverso, Matriz -> png) del resultado de decompress y metiendolos a una matriz, pero tuve los sgtes problemas:
+ Si tomo de a tres, me queda una entrada de la matriz con solo 2 valores, supongo que será un error de mi algoritmo si es que realmente se debe tomar de a 3 ?
+ Luego si intento obtener el IHDR  través de la matriz obtenida, no me queda claro donde está la información de las dimensiones de ésta en la matriz considerando que necesito esta info para reconstruir el IHDR, ya que obtengo una matriz con cada fila tres entradas de 0 a 255 cada una.

Ojalá algún ayudante pudiera hacer una explicación breve de como llevar a cabo el proceso inverso ya que creo no queda claro en el enunciado y no debería ser algo en que nos quedemos pegados, si no que deberíamos centrarnos en el aprendizaje de networking :cry: .
Gracias de antemano!
