### ISSUE TITLE
Número de flechas para el avance

### ISSUE THREAD

**Issue by Sofia-Arratia** [IIC2233/syllabus#735]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola!
Tengo una duda con la cantidad de flechas que se piden para el avance de la tarea, ya que el enunciado especifica que "deberás programar una Zona de ritmo con ancho de 1 carril, es decir, de tamaño para una única flecha", pero no me queda muy claro si esto también implica que se deberá generar una sola flecha, o varias en loop en este único carril.
Muchas gracias! ☺️

**Comment by jaimecoloma** [comment]
Hola @Sofia-Arratia, para el avance, basta con que una flecha cumpla con todo lo señalado, es decir, "dicha flecha deberá descender dentro de la interfaz de forma automática, y cuando esta colisione con su zona de captura correspondiente, la zona de captura deberá cambiar su color mientras se mantenga la colisión entre la flecha y la zona. Una vez la flecha salga completamente de la zona de captura, el color de esta debe volver al original." 
Te recomiendo que lo hagas como loop para que sea más visible para cuando un ayudante lo revise, pero si utilizas solo una flecha no habría problema, solo tener cuidado en que se debe *visualizar* bien!
Mucho éxito!

**Comment by Sofia-Arratia** [comment]
muchas gracias!
