### ISSUE TITLE
Contenido Avance

### ISSUE THREAD

**Issue by mpmunoz13** [IIC2233/syllabus#735]
Hola, 
Estoy un poco confundida con que debemos entregar para el avance. Hay que crear un archivo que se llame avance y cargue el mapa y las cosas de mapa.csv?

**Comment by jeschuwirth** [comment]
Hola @mpmunoz13,

Basicamente es lo que dices, deben subir archivos.py que el ejecutar el main cargue la ventana de mapa, se espera que cargue el fondo más toda la info de mapa.csv. Además de tener correctamente conectadas todas las señales que consideres necesarias.

**Comment by mpmunoz13** [comment]
@jeschuwirth 
Se tiene que poder mover el mesero?

**Comment by jeschuwirth** [comment]
No es necesario, basta con cargar el mapa. Sin embargo lo recomiendo para que te podamos dar feedback acerca de tu implementación del movimiento.

**Comment by RonaldoSosa** [comment]
El Drag and Drop debería estar hecho en el avance?

**Comment by jeschuwirth** [comment]
Nop, con solo cargar el mapa basta.

Te recomiendo lo mismo que a mpmunoz13, si tienes tiempo te recomendaría hacerlo para poder darte feedback :)
