### ISSUE TITLE
Formato de las notas en ventana edición 

### ISSUE THREAD

**Issue by FJavierOss** [IIC2233/Syllabus#735]
Son varias preguntas del formato
¿Puedo suponer que los usuarios quieren consistencia en las notas a la hora de ver las notas en la ventana de edición?
Por ejemplo, cada vez que se cargan las notas se prefiere usar la nomenclatura española.
O también, cada vez que se ingrese una nota y se agregue a la ventana, supongamos que el usuario entrega para la nota (nota, escala, intensidad, duracion) un (1, 5, ff, negra) y luego entrega otra nota con C, 5, ff, negra) y luego otra nota con (do, 5, ff, negra). En el fondo, ¿Puedo suponer que el usuario quiera consistencia y las notas que aparecen en pantalla solo estén en nomenclatura española, o sea, que puedo transformar lo ingresado por el usuario y solo mostrar nomenclatura española? Para asi evitar partituras inentendibles.
Y por último, en el formato en vez de representar las notas como aparece en el enunciado -> "Do 5 mf Negra", ¿puedo representarla como lowercase? o sea como, -> "do 5 mf negra"

Saludos

**Comment by mfanselmo1** [comment]
Hola!
Primero, si puedes mostrar solo un tipo de nomenclatura en la lista de notas, pero debes permitir ingresar todos los tipos.
Para lo segundo lo mismo, mientras te funcione y se entienda esta bien. Tambien recuerda que hay metodos en python para pasar un string a lowercase.

**Comment by FJavierOss** [comment]
Ya bacan, gracias
