### ISSUE TITLE
Datos guardados en la app

### ISSUE THREAD

**Issue by rgriver** [IIC2233/Syllabus#735]
Hola. Creo que luego de un cierto tiempo de inactividad la app se reinicia, por lo que los datos almacenados (los chats) se pierden. El usuario tendría que hablar nuevamente con el bot para que este lo reconozca otra vez. ¿Tengo que guardar la lista de los chats en otra parte?

**Comment by akaminetzkyp** [comment]
Hola! https://github.com/IIC2233/Syllabus/issues/683 :)

**Comment by rgriver** [comment]
@akaminetzkyp Gracias!!
