### ISSUE TITLE
Duda: Nombre único

### ISSUE THREAD

**Issue by jtcaraball** [IIC2233/Syllabus#736]
La condición de que el nombre del cliente sea único es para cada ventana de edición por separado
o si existe el nombre en alguna ventana, incluso si el cliente no quiere acceder a ella, cuenta como que el nombre ya esta ocupado?

Gracias!

**Comment by mfanselmo1** [comment]
Hola!
Como el nombre se pide solo cuando se entra a una ventana de edicion, este solo debe ser unico **por** ventana de edicion.
