### ISSUE TITLE
Blurry

### ISSUE THREAD

**Issue by movaldivia** [IIC2233/Syllabus#736]
En cuanto a los píxeles bordes, no se le aplica el efecto o se considera que si no tiene un determinado vecino, este pondera 0?

**Comment by ifcarrera** [comment]
Hola, considera que pondere 0.
Saludos

**Comment by cfernandez9** [comment]
a que se refieren con ponderar 0? a que el pixel vecino inexistente se considera blanco?

**Comment by ifcarrera** [comment]
A qué en vez de multiplicarlo por 2, es como si multiplicara por 0

**Comment by cfernandez9** [comment]
ah ok, muchas gracias!!

**Comment by inmadariaga** [comment]
@ifcarrera se sigue dividiendo por 16?
