### ISSUE TITLE
Regex y Heroku

### ISSUE THREAD

**Issue by vijuarez** [IIC2233/Syllabus#736]
Hola! Estoy tratando de implementar la busqueda automatica de solución y estoy atascado. Tengo un regex que me detecta si hay una exception y me devuelve el codigo de error, y cuando la corro local me funciona perfecto. Sin embargo, cuando lo hago desde heroku (con exactamente el mismo texto en la issue), el Regex no me hace match. Siento que el texto que subo a la issue no llega igual al servidor (que el 'body' llega diferente al texto que copio y pego) y ese cambio me destruye todo.

Subi a mi repo todos los cambios, para que algún ayudante me ayude. Estoy en las últimas :c 

La parte que recibe la issue cuando se publica esta en main.py -> payloadgithub()
La parte del regex es google.py -> extract_error()

El archivo test_error tiene el issue que uso como ejemplo y al final de google.py esta comentado un test que lee el archivo y da la solución que el bot deberia comentar. La issue que he subido varias veces para tratar tiene exactamente el mismo texto.

Gracias!

**Comment by akaminetzkyp** [comment]
Podrías poner un `print` de la información que llega y revisarla con `heroku logs`. Quizás ahí encuentras qué está fallando. Saludos!

**Comment by vijuarez** [comment]
Gracias! Al final no era problema de Heroku, si no que efectivamente le llegaban bien las issues. Regex sencillamente se niega a hacerle match a las issues descargadas. Algo debe cambiar en el encoding que mata el regex, no tengo idea que. Al final hice un hack feo sin regex para que me agarrara los errores, algo es algo.
