### ISSUE TITLE
Tengo instalado QtDesigner pero no puedo abrirlo

### ISSUE THREAD

**Issue by SebastianFerra** [IIC2233/syllabus#736]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

Hola! al comienzo del curso instalé QtDesigner como menciona la WIKI y se instaló bien (supongo), pero ahora que lo quiero abrir no me aparece en el buscador y cuando llego a la carpeta de la aplicación me lanza el siguiente error 
![image](https://user-images.githubusercontent.com/69606956/96625792-05db4900-12e5-11eb-9e8f-358e5efecd54.png)

y no sé como solucionarlo.

**Comment by aaossa** [comment]
Hola @SebastianFerra , ¿viste #694 ? Tenía el mismo mensaje de error y pudo solucionarlo reinstalando PyQt5 (aparece ahí mismo el comando), podrías intentarlo. Avisa por acá si te funciona o no 👌 ¡Éxito con la instalación!
