### ISSUE TITLE
bonus segunda parte

### ISSUE THREAD

**Issue by rjdelrio** [IIC2233/Syllabus#737]
no entiendo si es que hay otro comentario del creado dando las gracias cuando se cierra la issue le ponemos un label googleable como identifico que el autor esta dando las gracias o esta asiendo un pregunta en el comentario o otra cosa ahi miles de maneras de dar las gracias

**Comment by vijuarez** [comment]
Como yo lo entendi, el poner el label solo ocurre si cierran la issue. Si el autor puso un comentario y luego la cerro, si o si debe haber solucionado el problema (a excepción de que encontrara la respuesta por si mismo y estuviera avisando, aunque yo creo que no se considera este caso). Si hubo más de un comentario, entonces hubo más conversación antes de cerrar la issue. Lo más probable es que alguien la hubiera solucionado en esos comentarios, por lo que no se pone label de Googleable.

(no soy ayudante)

**Comment by rjdelrio** [comment]
es que no sale que el que la cerro tenga que ser el autor de la issue solo sale esto:
"Luego del comentario autom´atico, si la issue se cierra sin ning´un otro comentario aparte del realizado
por el bot o alguno del autor de la issue (puede dar las gracias), ponerle a ´esta el label Googleable"
entonces si fuese asi puede que el comentario sea un pregunta, una acotacion, o un comentario replanteando la pregunta y otra persona cierre la issue, por que el autor de la issue no es el unico que puede cerrar la issue, no se si me explico

**Comment by vijuarez** [comment]
Es que si cierran la issue, tiene que haber sido o un admin o el autor. Cualquiera de estos debería tener la autoridad y el juicio para decir que la pregunta esta respondida, por lo que no debería pasar que replantearan la pregunta y alguien llegara y la cerrara. Al menos así lo considere yo.

**Comment by rjdelrio** [comment]
aaaaa ya

**Comment by chapito96** [comment]
Complementando un poco, lo que yo entendí que si luego del link y el posterior comentario del autor se cierra, se asume que el último comentario fue de agradecimiento. Veo dificil hacer un algoritmo que detecte si fue agradecimiento o no dado las infinitas formas en que se puede agradecer.
