### ISSUE TITLE
Update de las ventanas

### ISSUE THREAD

**Issue by stgoct** [IIC2233/syllabus#737]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola!
Estoy teniendo problemas a la hora de que se actualice la ventana de juego. Estoy en la parte de mover las flechas hacia abajo usando un contador y un thread, pero solo se visualiza la primera iteración y la última, es decir que la imagen "se pega un salto"  hasta el final, lo de entremedio lo ignora. A qué se debe?

**Comment by furcelay** [comment]
Hola @stgoct !
Sin ver el código se me ocurren algunas posibles causas:
1.  El parámetro de la velocidad de la flecha es muy alto por lo que efectivamente da un salto.
2.  La región en que se mueve la flecha tiene limitadas posiciones en que ésta puede estar (por ejemplo debido a un layout que restrinja las posiciones).
3.  Por algún tema de *threading* la ventana no alcanza a actualizarse (puede pasar por ejemplo si el thread que desplaza a la flecha se repite con una frecuencia muy alta (hay poco tiempo entre iteraciones)).

Revisa si alguna de las opciones se ajusta a tu problema y en todo caso has un push de tu repositorio para tener una idea de tu implementación.

Saludos! :smile:

**Comment by sustancia** [comment]
> 
> 
> Hola @stgoct !
> Sin ver el código se me ocurren algunas posibles causas:
> 
>     1. El parámetro de la velocidad de la flecha es muy alto por lo que efectivamente da un salto.
> 
>     2. La región en que se mueve la flecha tiene limitadas posiciones en que ésta puede estar (por ejemplo debido a un layout que restrinja las posiciones).
> 
>     3. Por algún tema de _threading_ la ventana no alcanza a actualizarse (puede pasar por ejemplo si el thread que desplaza a la flecha se repite con una frecuencia muy alta (hay poco tiempo entre iteraciones)).
> 
> 
> Revisa si alguna de las opciones se ajusta a tu problema y en todo caso has un push de tu repositorio para tener una idea de tu implementación.
> 
> Saludos! 😄

Hola! me ocurre lo mismo :c he probado ajustar los parametros y nada :C

**Comment by furcelay** [comment]
@sustancia , revisando tu código veo que tienes algunas señales mal conectadas, por ejemplo conectas una señal con otra señal en vez de un método, y las flechas no aparecen porque no les llegan las señales necesarias. Además veo que en la clase `RondaCodigo` el *override* del método `run` tiene argumentos, recuerda que éste método solo puede tomar el argumento `self`.

Espero que puedas solucionar tu problema, saludos!
