### ISSUE TITLE
Byte \x00n ?

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#737]
![image](https://user-images.githubusercontent.com/66154723/124531351-4ed41e80-dddc-11eb-8d93-8a8eb4cc56ec.png)

Estaba practicando la materia de bytes, y por alguna razón si paso el int 110 a bytes lo transforma como n, y más raro aún, le pido 4 bytes pero me concatena 3, sin embargo al pedir la longitud me entrega que es 4.

¿Es este byte \x00n alguna representación especial de dos bytes juntos?

**Comment by tqmbanados** [comment]
Hola! \x00n son efectivamente **dos** bytes, `\x00` y `n`. Por lo tanto, sigue que la representación de `110` en 4 bytes usando big endian son estos 4 bytes: `\x00`, `\x00`, `\x00` y `n`. Es normal cuando conviertes un int a bytes que gran parte de los bytes sean `\x00`, así que no te preocupes por eso. Hay excepciones eso sí, por ejemplo si pruebas convertir `1024` a 4 bytes. Así que no te preocupes!

De el motivo de por qué funciona así puedo explicar lo más básico jajaja, no me manejo tanto tanto en el tema, pero no entra en el curso, por lo que esto es por si te da curiosidad de investigar más. En el fondo, hay que saber que cada **byte** está compuesto por una cierta cantidad de **bits**, en la gran mayoría de los casos, de 8 *bits*. El bit puede tener valor 0 o 1, según código binario, entonces cada *byte* puede tener 256 valores distintos. Por este motivo, para todos los `int` desde 0 a 255 inclusive, basta sólo **un** byte para representarlos, y el resto se rellena con `\x00`. Estos 256 números son usualmente representados usando el sistema *hexadecimal*, que permite **representar 16 valores en un caracter**, y como estamos usando dos caracteres (`\x00`), podemos representar 256 valores. Es por esto que a veces encontramos bytes con los valores `\xfa` o algo así.

Ahora, ¿por qué hay un byte que es solamente `n`? Aquí es donde mis conocimientos empiezan a ponerse en duda,  pero entiendo que ademas del sistema hexadecimal, se utiliza la tabla `ascii` para hacer la conversión. Si te fijas, el valor `110` en `ascii`, es justamente `n`! Mezclar ambos sistemas no es problema, pues al final solamenteki son representaciones "human readable" de strings de unos y ceros, pero en el fondo, si el caracter `ascii` es "printeable", se usa ese, si no lo es (como lo es el caso del salto de línea, enter, delete, etc etc) se usa el valor hexadecimal. 

Espero que se te aclare un poco más el tema, es bien interesante!

**Comment by fernandosmither** [comment]
> Hola! \x00n son efectivamente **dos** bytes, `\x00` y `n`. Por lo tanto, sigue que la representación de `110` en 4 bytes usando big endian son estos 4 bytes: `\x00`, `\x00`, `\x00` y `n`. Es normal cuando conviertes un int a bytes que gran parte de los bytes sean `\x00`, así que no te preocupes por eso. Hay excepciones eso sí, por ejemplo si pruebas convertir `1024` a 4 bytes. Así que no te preocupes!
> 
> De el motivo de por qué funciona así puedo explicar lo más básico jajaja, no me manejo tanto tanto en el tema, pero no entra en el curso, por lo que esto es por si te da curiosidad de investigar más. En el fondo, hay que saber que cada **byte** está compuesto por una cierta cantidad de **bits**, en la gran mayoría de los casos, de 8 _bits_. El bit puede tener valor 0 o 1, según código binario, entonces cada _byte_ puede tener 256 valores distintos. Por este motivo, para todos los `int` desde 0 a 255 inclusive, basta sólo **un** byte para representarlos, y el resto se rellena con `\x00`. Estos 256 números son usualmente representados usando el sistema _hexadecimal_, que permite **representar 16 valores en un caracter**, y como estamos usando dos caracteres (`\x00`), podemos representar 256 valores. Es por esto que a veces encontramos bytes con los valores `\xff` o algo así.
> 
> Ahora, ¿por qué hay un byte que es solamente `n`? Aquí es donde mis conocimientos empiezan a ponerse en duda, pero entiendo que ademas del sistema hexadecimal, se utiliza la tabla `ascii` para hacer la conversión. Si te fijas, el valor `110` en `ascii`, es justamente `n`! Mezclar ambos sistemas no es problema, pues al final solamente son representaciones "human readable" de strings de unos y ceros, pero en el fondo, si el caracter `ascii` es "printeable", se usa ese, si no lo es (como lo es el caso del salto de línea, enter, delete, etc etc) se usa el valor hexadecimal.
> 
> Espero que se te aclare un poco más el tema, es bien interesante!

Te comprendo, agradezco mucho la honestidad y humildad, y la verdad me hace todo el sentido del mundo tu explicación. Muchas gracias! 😄
