### ISSUE TITLE
Blurry calculo matriz 

### ISSUE THREAD

**Issue by mmsaavedra1** [IIC2233/Syllabus#737]
Cuando analizo un pixel (x,y) de la matriz RGB. Al momento de analizar su vecino por ejemplo (x+1,y) ¿debo considerar el valor anterior del cambio de (x,y) o su nuevo valor para efectos del calculo de (x+1, y) y así todos los pixeles de la imagen?

Saludos!

**Comment by ifcarrera** [comment]
Hola!
El blurry se calcula para todos los píxeles usando los vecinos "originales". Es recomendable que guardes una copia de la matriz original y calcules el efecto sobre esa matriz y la guardes en otra con los pixeles modificados. 
Saludos
