### ISSUE TITLE
Importar módulos en distintas carpetas

### ISSUE THREAD

**Issue by JavaBravo** [IIC2233/syllabus#737]
Hola, estaba intentando ordenar los archivos de la tarea en carpetas para que sea más simple navegar entre ellos, así que leyendo la documentación python, en la sección módulos, vi que se podía importar módulos entre carpetas. En mi caso el árbol se vería más o menos así:

* \T02
    * ```__init__.py```
    * ```main.py```
    * \ventanas
        * ```__init__.py```
        * ```ventana_inicial.py```
    * \auxiliares
        * ```__init__.py```
        * ```parametros.py```

Entonces, en caso de querer importar un parámetro de ```parametros.py``` desde ```ventana_inicial.py``` escribo: ```from T02.auxiliares.parametros import RUTA```, pero levanta el siguiente error: ```ModuleNotFoundError: No module named 'T02'```

Lo anterior ocurre con cualquier caso de importación entre carpetas. Si pudieran ayudarme con esto lo agradecería.

**Comment by KnowYourselves** [comment]
Hola @JavaBravo!

Congrats por investigar esta temática 🎉.

Lo que estas haciendo es crear **packages** (como _random_ y _math_). Lo que sucede es que al hacer el import desde `main.py` con `T02.ruta` Python busca un paquete llamado T02 pero no lo encuentra (No es capaz de reconocer que esta dentro de el y por ende el error). Si mal no recuerdo esa es una recomendación errónea que el linter _pylint_ usualmente da.

Para solucionar el problema haz `from auxiliares.parametros import PARAMETRO` (es probable que _pylint_ te alege)

Quedo atento!

**Comment by JavaBravo** [comment]
Gracias @KnowYourselves por contestar! 

La verdad es que desde ```main.py``` no tengo problemas al importar, pero a la hora de importar **packages** desde una rama, en este caso ```ventana_inicial.py```, no lo logro hacer, tirandome el error ya dicho. Entonces, lo que quiero es importar ```parametros.py``` en ```ventana_inicial.py```, y no puedo. Si me pudieras explicar porque no funciona desde las ramas y como hacerlo sería perfecto.

**Comment by KnowYourselves** [comment]
Dentro de las ramas puedes utilizar lo que se llama **Relative Imports**, que esta diseñado para ser usado exactamente en este caso de uso.

Desde `ventana_inicial.py` puedes hacer `from ..auxiliares.parametros import PARAMETRO`, es relativo de la misma forma que los _path relativos_ lo son. En este caso el ".." índica subir un nivel (al paquete general) y de ahí importar los parametros.

Sin embargo, esto **no va a funcionar** porque tu carpeta `T02` si bien es un _package_ al estar ejecutando el _main_ desde dentro de está, al hacer el import relativo y subir desde la carpeta `ventanas` a `T02` Python **no reconocera esta carpeta como un paquete** y te dará un error de importación.

En este caso la solución que te propongo es cambiar tu estructura a lo siguiente:

```bash
T02/
├── interfaz
│   ├── auxiliares
│   │   └── parametros.py
│   └── ventanas
│       └── ventana_inicial.py
└── main.py
```

De esta forma deste tu main.py puedes hacer los siguientes imports:`

1. from interfaz.ventanas import ventana_inicial` 
2. `from interfaz.ventanas.ventana_inicial import FUNCION`
3. Símil con otros subpaquetes.

Finalmente, desde `ventana_inicial` puedes hacer los siguientes imports:

1. `from ..auxiliares import parametros` 
2. `from ..auxiliares.parametros import PARAMETRO`
3. Símil para importar otros paquetes que esten más arriba o más abajo.

Finalmente, probablemente en tu caso de uso tus `__init__.py` están vacíos. Es decir, no corres ningún código de _setup_. En tal caso desde _Python3.3_ puedes omitir estos archivos (si es que están vacíos) y serán reconocidos implicitamente como paquetes.

Espero que te haya quedado claro!

**Comment by JavaBravo** [comment]
¡¡Ahora sí!! Muchas gracias @KnowYourselves, realmente me quedó clarísimo

**Comment by JavaBravo** [comment]
Ahora estoy recibiendo errores que no logro corregir. Esta vez entregaré el arbol casi completo para salir de las dudas inmediatamente, e intentar no seguir preguntando.

Mis archivos serían los siguientes: 

* T02
    * ```main.py```
    * codigos
        * back
            * ```auxiliar.py```
            * ```parametros.py```
            * ```proceso.py```
        * ventanas
            * ```ventana_inicial.py```
            * ```ventana_preronda.py```
            
Entonces los errores que me salen ahora serían:
1. Desde ```proceso.py``` al poner: ```import auxiliar as a```. El error es: ```ModuleNotFoundError: No module named 'auxiliar'```

2. Desde ```ventana_preronda.py``` al poner: ```from ..auxiliares import parametros as p```. El error es: ```ImportError: attempted relative import with no known parent package```

Al parecer, toda importacion relativa no la reconoce, y el error 1 y 2 han de ser el mismo, pues en caso del primero, ocurre al ejecutar el ```main.py```, pero si ejecuto el archivo ```proceso.py``` por sí mismo, ocurre el mismo error que el 2.

Lamento tener que volver, pero no logro resolverlo.

**Comment by KnowYourselves** [comment]
No te preocupes, es mi culpa por no haber sido suficientemente explicito.

## Respecto a 1.
Los _relative import_ solo aceptan el uso de `from`. En este caso debiéses hacer `from . import auxiliar as a`, que es lo mismo que decir "Del paquete actual (.) quiero importar `auxiliar`"

## Respecto al 2. 

Esto sucede porque tu import está mal. Al hacer `from ..auxiliares import parametros as p` estas asumiendo que un nivel más arriba de `ventana_inicial.py` existe un paquete llamado `auxiliares`, sin embargo este no es el caso. Debiése ser `from ..back import parametros as p`

Quedo atento a cualquier otra duda que tengas!

**Comment by JavaBravo** [comment]
Buenísimo! Algo que he notado, es que ahora, al ejecutar el código, todo _path_ queda relativo a la ubicación del archivo ```main.py```, ¿cierto? Porque en un principio tuve errores de _path_ al tratar de abrir un archivo ```mapa.csv``` desde ```auxiliar.py```, (en este caso ```mapas.csv``` se encuentra junto con ```main.py```). Entonces, cambiando el _path_, considerándolo desde ```main.py```, funcionó (el _path_ sería simplemente "mapa.csv") sin necesidad de hacerlo desde la ubicación de ```auxiliar.py```.

En resumen mi duda es, ¿desde ahora, todo _path_ se considera desde ```main.py``` como origen?

Gracias de antemano!

**Comment by KnowYourselves** [comment]
Nuevamente, excelente pregunta!

La respuesta la puedes econtrar detalladamente explicada en [este link.](https://stackoverflow.com/questions/1011337/relative-file-paths-in-python-packages)

El resumen de lo recomendado es utilizar la variable `__file__` para referirse a archivos relativos a ese módulo en general.

**Comment by JavaBravo** [comment]
En ese caso, se considera el uso de ```__init__.py``` para agregar la variable ```__file__```. Entonces ¿debería agregar el archivo: ```__init__.py``` en la carpeta que contenga el archivo desde donde quiero originar el _path_ ? Y, ¿es necesario si es que ya me funciona considerándolo desde la ubicación de ```main.py```?

**Comment by KnowYourselves** [comment]
No, no es necesario!, La variable `__file__` es seteada automáticamente por Python, no es una variable que debas agregar tu manualmente, por lo cual sigue siendo innecesario el uso de `__init__.py`.

De lo único que te debes asegurar es que tu paquete funcione correctamente considerando que algunos recursos podrían estar fuera de este (Fuera de la carpeta `codes`, dentro de la carpeta `T02`).

Cualquier otra duda o problema que te encuentres respecto a paquetes comenta esta issue!

Nuevamente, congrats por tomar la iniciativa de aprender respecto a la creación de paquetes propios 🎉

**Comment by JavaBravo** [comment]
Muchísimas gracias! En caso de tener más problemas, preguntaré.
