### ISSUE TITLE
Duda con KeyPressEvent y QComboBox

### ISSUE THREAD

**Issue by En-clases** [IIC2233/syllabus#738]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, tengo una duda acerca del KeyPressEvent. Definí el método tal que cuando se apreten las teclas A,W,S,D se mostrara un cuadrado. Todo funcionaba bien, los botones de Pausar, Salir y Comenzar que se muestran en la imagen también funcionaban correctamente. Sin embargo, ahora agregué las ComboBox de música y dificultad y sus distintos sub-Items. Con esto implementado, el método de KeyPressEvent ya no me funciona al comenzar la partida. Es como si las señales de mi teclado no se dirigieran a este evento. Qué puedo hacer para que funcione nuevamente?

![image](https://user-images.githubusercontent.com/69520590/96642383-7d68a280-12fc-11eb-845d-2ec8348bfb7d.png)

Pd: El evento KeyPressEvent solo vuelve a funcionar cuando hago pausar y reanudar el juego.

**Comment by furcelay** [comment]
Hola @En-clases !
El problema es que los `QComboBox` implementan una función para buscar contenido cuando se presiona una tecla, entonces los `keyPressEvent` son redirigidos a ellos. Para resolverlo lo más simple es simplemente desactivar el `QComboBox` mientras requieras que se reciba un input de teclado (la mayoría de los widgets se desactivan con el método `setEnabled(False)`).

Si requieres que el `QComboBox` siga funcionando mientras usas el teclado, la opción que recomienda PyQt5 es usar filtros de eventos pero considero que son algo difíciles de implementar (te dejo la [documentación](https://doc.qt.io/qtforpython/overviews/eventsandfilters.html#event-filters)). Como alternativa fácil puedes hacer una clase que herede de `QComboBox` y que los `keyPressEvent` que ocurran en él sean redirigidos a la ventana que quieres que maneje las teclas (básicamente que haga un llamado al `keyPressEvent` de la ventana dándole el evento correspondiente). 

Si quedas con alguna duda me cuentas,
Saludos! 😄

**Comment by En-clases** [comment]
Me quedó clarísimo, Gracias!

**Comment by ljgonzalez1** [comment]
Me di cuenta de este detalle entre la fecha de entrega y la fecha de entrega atrasado, por lo que no lo corregí en mi tarea. Supongo que puedo extender el problema aquí y hacer una pregunta sin abrir otra _issue_ puesto a que la causa parece ser la misma.

¿Por qué actúa de forma distinta dependiendo del sistema operativo en el que se ejecute? Uso KDE Neon 20.0.2 y no me percaté a tiempo de que era esto por lo que parte de mi código no funcionaba. Sin embargo, cuando le pasé el código a un amigo, que usa macOS 10.13, para que lo pruebe, reconocía todas las teclas y enviaba las señales correspondientes.

¿Tengo alguna forma de asegurarme de que no ocurran problemas similares asociados al OS que puedan no mostrarse en el mío y sí en el de algún ayudante más allá de enviar mi código a otras personas?

**Comment by furcelay** [comment]
Hola @ljgonzalez1 !

En general existen diferencias entre sistemas operativos cuando se trabaja con interfaces gráficas porque hay una mayor dependencia con recursos propios del OS, a diferencia de un script en el terminal. Muchas de esas diferencias se deben  a valores por defecto y se pueden arreglar con modificaciones en el programa por lo que mientras más parámetros manejes menos queda a la libertad del OS. Pero si vas a elaborar un programa con GUI (más allá de una tarea para el curso) lo ideal es que lo pruebes en distintos OS para ver que no ocurran esos problemas.

De todos modos en general se tratan de diferencias menores ya que el grueso del programa lo maneja Python, me extraña en particular tu caso, pero de todos modos tenemos en consideración el OS al momento de corregir, así que no deberías preocuparte por eso.

Saludos!
