### ISSUE TITLE
Clonar repositorio en otro computador

### ISSUE THREAD

**Issue by antoniafuica** [IIC2233/syllabus#738]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

Hola! Tuve un problema con mi computador, por lo que tengo que hacer la tarea en otro que ya tiene un usuario github en el terminal por lo que no me deja clonar mi repositorio en el computador. 
Como puedo hacer para eliminar el github anterior y poder clonar el mío?

**Comment by dfloreaa** [comment]
Hola, si mal no recuerdo, puedes correr el comando
``git config --global --unset-all```
Y con ello deberían borrarse todas las credenciales previas de git en tu computador, pudiendo asi ingresar las tuyas

Saludos! 🦝
