### ISSUE TITLE
CRC

### ISSUE THREAD

**Issue by depstein26** [IIC2233/Syllabus#738]
No entiendo qué es el CRC ni cómo se calcula, le he dado varias vueltas a las issues que encontré al respecto y al enunciado pero la verdad es que no lo entiendo.

De antemano gracias.

**Comment by Arcoirisky** [comment]
Hola! Disculpa la tardanza :c 

El CRC es un método, no necesitas calcularlo. Sólo debes tomar todos los bytes que indican el tipo de Chunk, tomar todos los bytes de la parte de información del Chunk, concatenar todo y a eso le aplicas el CRC O:

Si quieres saber más de él solo [mira aquí](https://es.wikipedia.org/wiki/Verificaci%C3%B3n_de_redundancia_c%C3%ADclica)
