### ISSUE TITLE
Header para token de Github

### ISSUE THREAD

**Issue by kadawn0** [IIC2233/Syllabus#738]
Hola,

Quiero hacer POST en issues de Github. Va todo bien pero necesito acceso con un token (no quiero usar usuario-contraseña, el token es más rápido y se le configuran los permisos).
He estado intentando varios headers que encontré en internet para enviar mis datos de identificación:

- {"authorization": "mi_token"} -> Retorna Bad Credentials

- {"authorization": "token mi_token"} -> Retorna "Invalid request.\n\nFor 'links/0/schema', nil is not an object."

- {"authorization": "bearer mi_token"} -> Retorna "Invalid request.\n\nFor 'links/0/schema', nil is not an object."

Resumen de intentos:

- `requests.post(direccion, headers={"Content-Type": "application/json", "Authorization": json.dumps("token {}".format(token))}, params={"body": texto})`

- `requests.post(direccion, headers={"Content-Type": "application/json", "Authorization": "token mi_token"}, params={"body": texto})`

- `requests.post(direccion, headers={'authorization': json.dumps({"user": token, "pass": 'x-oauth-basic', "sendImmediately": True})}, params={"body": ""})`

- `requests.post(direccion, headers={"Content-Type": "application/json", "Authorization": "token #{}".format(token), "User-Agent": "kadawn0"}, params={"body": texto})`

- `requests.post(direccion, "auth=(kadawn0, {})".format(token), headers={"Content-Type": "application/json", "Authorization": "token #{}".format(token), "User-Agent": "kadawn0"}, params=texto)`

¿Cómo se envía el token?

FINAL: LA RESPUESTA ES...
`url = url_base + "repos/{}/{}/issues/{}/labels".format("kadawn0", "telegram_bot_(mibot)", issue)
                        respuesta = requests.post(url, auth=credentials, data=json.dumps([respuesta]))`

**Comment by indonoso** [comment]
cómo se los estás pasando a la request?

**Comment by kadawn0** [comment]
`requests.post(direccion,
                                                  headers={"Content-Type": "application/json",
                                                           "Authorization": json.dumps("token {}".format(token))},
                                                  params={"body": texto}) `
Esta es la nueva forma que retorna Bad credentials.
La otra es:
`requests.post(direccion,
                                                  headers={"Content-Type": "application/json",
                                                           "Authorization": "token mi_token"},
                                                  params={"body": texto})`

**Comment by kadawn0** [comment]
`requests.post(direccion,
                                                  headers={'authorization': json.dumps({"user": token,
                                                                               "pass": 'x-oauth-basic',
                                                                               "sendImmediately": True})},
                                                 params={"body": ""})`
También usé esta y retornó Bad Credentials.

**Comment by LuisFros** [comment]
#No soy ayudante
Trata de argregar como argumento al post, el key "auth", este recibe una tupla con ("UsuarioGithub","Token)
Seria request.post(url,params={"body:""},auth=("UsuarioGithub","Token))

**Comment by kadawn0** [comment]
No me funcionó, retorna "Invalid request.\n\nFor 'links/0/schema', nil is not an object."

**Comment by kadawn0** [comment]
Flask está en la versión más reciente.

**Comment by kadawn0** [comment]
`requests.post(direccion,
                                                  headers={"Content-Type": "application/json",
                                                           "Authorization": "token #{}".format(token), "User-Agent": "kadawn0"},
                                                  params={"body": texto})`
Acabo de agregar User-Agent con mi nombre de usuario y luego con el de un nombre de aplicación que poseo. Todo retorna Bad Credentials.

**Comment by akaminetzkyp** [comment]
Intenta pasar ˋauth=(username, token)ˋ directamente como argumento del ˋpostˋ y no dentro de los headers. Saludos!

**Comment by kadawn0** [comment]
`requests.post(direccion, "auth=(kadawn0, {})".format(token),
                                                  headers={"Content-Type": "application/json",
                                                           "Authorization": "token #{}".format(token),
                                                           "User-Agent": "kadawn0"},
                                                  params=texto)`
Retorna "Requires authentication" si saco "Authorization" del header, y si lo dejo, es de nuevo Bad Credentials.

**Comment by Hernan4444** [comment]
@kadawn0 intenta hacer `requests.post(url, auth=credentials, data=json.dumps({"body": respuesta}))`

Donde **respuesta** es lo que quieres poner como comentario en la issue, **url** es la ruta que la api te dice que pongas y **credentials** en una tupla con tu usuario y tu token.

El error puede ser que estás entregando los argumentos del post con `params` pero `request.post` pide que eso lo hagas mediante `data`

Saludos!

**Comment by kadawn0** [comment]
Yep, funcionó con el código:
`url = url_base + "repos/{}/{}/issues/{}/labels".format("kadawn0", "telegram_bot_(mibot)", issue)
                        respuesta = requests.post(url, auth=credentials, data=json.dumps([respuesta]))`
