### ISSUE TITLE
request.status_code == 418

### ISSUE THREAD

**Issue by Okhan97** [IIC2233/Syllabus#739]
Hola,¿ cuando puede pasar que el status_code sea 418 ?

Quedé con la duda despues de leerlo en wikipedia: [https://es.wikipedia.org/wiki/Anexo:C%C3%B3digos_de_estado_HTTP](url)

**Comment by iqacevedo** [comment]
Hola según investigue no se utiliza mucho, ya que se había creado literalmente con programa que trabaja con una cafetera,  acá encontré información (ahora solo se usa para darle más humor a los errores creo):

http://www.josevazquez.net/codigo-de-estado-http-418-i%C2%B4m-a-teapot/
https://meta.stackexchange.com/questions/185426/stack-overflow-returning-http-error-code-418-im-a-teapot
