### ISSUE TITLE
La imagen se guarda mal

### ISSUE THREAD

**Issue by behrmann97** [IIC2233/Syllabus#739]
Al obtener la matriz RGB de las imagenes y luego volver a hacer la imagen PNG de esa matriz, se me guarda de manera incorrecta y no sé porqué.
Por ejemplo, al guardar el Mushroom.png se me genera la siguiente imagen:
![image](https://user-images.githubusercontent.com/26407766/32805592-a9327e62-c968-11e7-9763-4ef8228e3a4e.png)

Esto es sin haberle hecho cambios y siguiendo los pasos del enunciado :/

**Comment by ifcarrera** [comment]
Hola, es bastante probable que estés haciendo mal el proceso de armar los bytes de nuevo. Se te están corriendo las filas. Revisa bien cómo estás haciéndolo, deberías obtener la misma foto si es que tus bytes tiene la forma correcta. 
Saludos

**Comment by gkschuit** [comment]
Hola! A mi me paso lo mismo y descubrí que es por el valor de la profundidad de bits. En el enunciado se recomienda usar el valor de 16 codificado en 1 byte, pero en verdad debería ser de 8 codificado en 1 byte.

**Comment by behrmann97** [comment]
@gkschuit te amo <3 jajaja muchas gracias
