### ISSUE TITLE
Pagina no encontrada 404 - link enunciado

### ISSUE THREAD

**Issue by sebadelorenzo** [IIC2233/syllabus#739]
Hola! En la sección 4.1 del enunciado hablan sobre un bajo acoplamiento y en el pie de pagina nos entregan un link "Diseño de software: Front-end y Back-end" para este tema pero no funciona :( 

No sé si es un problema con el link o no, y si es el caso podrían subir otro link porfa!!

**Comment by fdoflorenzano** [comment]
Hola,
Sí, hay un problema con el enlace, se actualizará en algún momento. De todas formas, el enlace se refiere a un contenido del curso, el cuaderno 4 de la semana 9:

[https://github.com/IIC2233/contenidos/blob/master/semana-09/4-dise%C3%B1o-front-back.ipynb](https://github.com/IIC2233/contenidos/blob/master/semana-09/4-dise%C3%B1o-front-back.ipynb)

Saludos.

**Comment by lily416** [comment]
@sebadelorenzo ya se subió una versión del enunciado con el _link_ corregido. 👍 

Saludos y éxito con la tarea 👋🍫
