### ISSUE TITLE
Optimizacion recursos (tiempo)

### ISSUE THREAD

**Issue by Veenty** [IIC2233/Syllabus#74]
En cuanto a la optimizacion de tiempo, apagar el incendio lo mas rapido posible, al problema no le falta una restriccion? (para no mandar todo lo disponible)

**Comment by rpalmaotero** [comment]
Ojo con:

> No pueden movilizarse recursos cuya hora de llegada al incendio sea mayor a la hora en la que se extinguió el incendio.

**Comment by Veenty** [comment]
Pero igual estaria mandado todo lo que pueda

**Comment by rpalmaotero** [comment]
@Veenty a qué te refieres con "todo lo que pueda"?

**Comment by acrojas2** [comment]
¿Como se sabe la hora en que se apagara el incendio?

**Comment by hanavarrete** [comment]
@acrojas2  Tienes que calcularla tu en base a los puntos de poder de alguno. Saludos
