### ISSUE TITLE
Máximo de personas

### ISSUE THREAD

**Issue by juanpacl111** [IIC2233/syllabus#74]
¿Qué ocurre si el jugador intenta crear más personas de lo que sus recursos le permite? ¿Se hacen todas las personas que sea posible o no se ejecuta la acción?

**Comment by hbkim94** [comment]
Hola!

Queda a tu criterio el cómo tu programa manejará el caso. Lo que si recomendaría es que se detalle qué ocurrió (por ejemplo, que para el segundo escenario tu programa imprima en la consola que no se pudieron crear a las unidades por falta de recursos).

Y recuerda agregarlo a tu Readme para que sepamos cómo funcionará tu programa :)

Saludos!
