### ISSUE TITLE
Push antes de crear el .gitignore en la Tarea 1

### ISSUE THREAD

**Issue by ceojedab** [IIC2233/Syllabus#74]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Buenas. Había cometido el error de subir mi tarea al repositorio privado antes de crear el .gitignore, por lo cual se subió el enunciado, la carpeta apoyo adicional, los test y tablero.txt.
Pude remover esos archivos usando "git rm" y luego creé el .gitignore para incluir estos archivos y todos las demás carpetas y archivos que no deben subirse (los cuales no había subido, pues no había ejecutado el código aún).
Mi pregunta es **¿contará esto para el descuento de git?**

De ser así, ¿cómo podría evitar el descuento? 

Muchas gracias.

**Comment by Hernan4444** [comment]
Hola @ceojedab 

No te preocupes, nosotros no vamos a revisar tu secuencia de _commits_, sino que solo el último realizado dentro del plazo de la entrega. Y en ese último commit, nos interesa que (1) tengas el `.gitignore` creado y con los archivos indicados a ignorar y (2) que en el repositorio no estén dichos archivos. De este modo evaluamos que al final de todo lograste crear y utilizar correctamente el `.gitignore`. Si antes habías subido los archivos, pero los eliminaste, está bien, Te diste cuenta de tu error y lo arreglaste a tiempo.

Esto tambien aplica a otros ítems, por ejemplo, PEP8. Si subes un código que no sigue PEP8, pero lo cambias durante el transcurso de la tarea, nosotros no te vamos a penalizar porque "antes no estaba bien escrito". Sino que solo nos preocuparemos que la entrega final (último commit dentro del plazo) cumpla con todo lo solicitado.

¡Mucho éxito con tu tarea!
Saludosヾ(＾-＾)ノ
