### ISSUE TITLE
Duda sobre cargar partida.

### ISSUE THREAD

**Issue by rgmorales1** [IIC2233/syllabus#74]
Una consulta, cuando el jugador carga una partida y luego la termina, esta partida, ¿debo borrarla de los juegos guardados o puede cargar nuevamente la misma que había dejado guardada?

**Comment by jeschuwirth** [comment]
Saludos!

Como no se especifica en el enunciado queda a criterio del alumno, por lo que puedes hacer lo que más te acomode. Recuerda especificar en el readme cual opción tomaste para que el corrector no se sorprenda si se le eliminan archivos.

Suerte !

**Comment by rgmorales1** [comment]
Muchas gracias!! c:
