### ISSUE TITLE
Duda sobre la opción "Salir"

### ISSUE THREAD

**Issue by verobaeza** [IIC2233/Syllabus#74]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Cuando en el Menú de inicio se selecciona la opción "Salir", la idea es que llamemos a una función que finalice el programa?

**Comment by Maxy15** [comment]
Hola verobaeza! La idea es que de alguna forma termines tu programa, puede ser con alguna variable, una librería o una función. Queda a tu criterio 👀 Espero te sirva!

**Comment by verobaeza** [comment]
Sí me quedó claro, muchas gracias 😊
