### ISSUE TITLE
Como borrar archivos en repositorio github después de incluirlos en .gitignore

### ISSUE THREAD

**Issue by Bjnazar** [IIC2233/Syllabus#74]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! 
Ya había subido archivos a mi repositorio de github, por lo que se subieron todos, y ahora hice el archivo .gitignore para no volver a subir enunciado/archivos que no importen en la entrega.
Ahora cuando subo los avances no se suben los archivos de .gitignore, pero siguen estando los que subí al principio al repositorio, cómo los borro? Ya intenté con git rm --cached path/to/file (poniendo el path absoluto creo) y me apareció:
fatal:  "path hasta la carpeta donde esta el repositorio" is outside repository at "path repositorio"
Y si lo intento hacer con el path relativo(poniendo el path del archivo a ignorar partiendo del repositorio) aparece:
 No such file or directory 
fatal: pathspec 'Bjnazar-iic2233-2022-2\Tareas\T0\parametros' did not match any files (lo probé con y sin .py)
Gracias de antemano!

**Comment by panchouc** [comment]
A mi me funcionó con `git rm -r --cached .` . Luego hay que hacer lo del git add, commit y el push.
