### ISSUE TITLE
Aclaración en habilidad asesinos

### ISSUE THREAD

**Issue by Regenschrim** [IIC2233/Syllabus#74]
En la parte del enunciado donde habla de la habilidad de los asesinos hay una incongruencia con los datos:

> Habilidad: Solo la pueden ocupar cuando invaden un planeta y en cada ataque hay un 40% de probabilidad de realizar el doble de daño. Por ejemplo, si durante la invasion de los Asesinos a otro planeta, los soldados tienen 3 intentos y estos hacen en total un daño de 40, en cada intento hay un 30% de hacer 80 de daño.

¿Usamos 30% o 40%?

Por otro lado, dice que en total hacen 40 de daño, pero ¿no debería ser ese el daño por ataque para que se le aplique el doble?

**Comment by IchottMano** [comment]
@Regenschrim Hola!
Esta pregunta se respondió en #32 .
Saludos!
