### ISSUE TITLE
Archivo parametros.py

### ISSUE THREAD

**Issue by catalinamirandah** [IIC2233/Syllabus#74]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola!

¿Está subido el archivo parametros.py de la tarea 1? Es que no me aparece :(

**Comment by matiasmasjuan** [comment]
Hola @catalinamirandah !

Tal como dice el enunciado:

![image](https://user-images.githubusercontent.com/48495638/161389909-f8735bed-37c0-4413-a396-d258e797617f.png)

Por lo tanto, **no les daremos** un archivo ***parametros.py*** predefinido, sino que ustedes deberán **crearlo** y darle valores a esas variables como ustedes estimen conveniente.

Saludos! Y mucho éxito con la tarea! :smile:

**Comment by catalinamirandah** [comment]
Ahh no había entendido bien eso, muchas gracias :D
