### ISSUE TITLE
Opción salir del programa

### ISSUE THREAD

**Issue by VicenteIgnacioSotoGonzalez** [IIC2233/Syllabus#74]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/20)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/19)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Buenas tardes, junto con saludar quería preguntar sobre el apartado de menú. Se nos solicita que creemos cuatro acciones que el usuario pueda realizar, respecto de la que finaliza el programa, ¿Se debe incluir algún comando que cierre automáticamente la consola o se puede colocar un print que indique que cierre el programa? Gracias de antemano.

**Comment by IanZmen** [comment]
Hola, buenas noches. Puedes colocar un print, pero la idea es que termines la ejecución del programa, como por ejemplo finalizando un loop.

**Comment by VicenteIgnacioSotoGonzalez** [comment]
Ahhh yaya, perfecto, osea no es necesario que se cierre la consola automáticamente al caer en ese caso?

**Comment by IanZmen** [comment]
Correcto!!

**Comment by VicenteIgnacioSotoGonzalez** [comment]
Perfecto, muchas gracias!
