### ISSUE TITLE
Problema con el repo: Repository not found

### ISSUE THREAD

**Issue by KnowYourselves** [IIC2233/Syllabus#740]
Intentando hacer mi app funcionar con heroku me di cuenta que todavia no habia hecho push con mis programa a git, pero al momento de hacerlo me tiro error fatal diciendo que mi repo no existia. Decidi eliminar el clon de mi repo de mi pc y hacer clone, pero al hacer git clone tambien me dice que el repo no existe

**Comment by iqacevedo** [comment]
Puedes indicar todo lo que te sale?
Yo si pude clonar tu repo sin problemas.

Saludos !

**Comment by KnowYourselves** [comment]
![image](https://user-images.githubusercontent.com/26102039/27563103-cb7335f0-5a9d-11e7-9565-066ac22c0679.png)

Lo que me parece raro es que me dejo hacer add y commit y luego al momento de hacer push me salio ese mismo error

**Comment by indonoso** [comment]
Como haces la autentificación?

**Comment by iqacevedo** [comment]
solo para probar quitale el `.git`, escribe `git clone https://github.com/IIC2233/KnowYourselves-iic2233-2017-1`

**Comment by KnowYourselves** [comment]
@indonoso  A que te refieres exactamente?
@iqacevedo  Nope, mismo error

**Comment by KnowYourselves** [comment]
Todavía no funciona:(

**Comment by fringlesinthestreet** [comment]
Puede ser un problema de autenticación.
Prueba con esta sintaxis: git clone https://username:password@github.com/usernamex/privat-repo.git

obviamente reemplaza username por KnowYourselves y la clave por la clave. También el link

**Comment by KnowYourselves** [comment]
@fringlesinthestreet Ya había intentado usar ese comando, al final decidí cambiar mi contraseña git y por razones que desconozco funcionó
