### ISSUE TITLE
Rutas realativas img con QTDesigner 

### ISSUE THREAD

**Issue by diegobustosk** [IIC2233/syllabus#740]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola mi consulta surge porque cuando utilizo QTDesigner las imagenes que agregue aparecen como rutas relativas pero con el / (utilizo mac). Tengo que utilizar el os.path.join? Como lo hago si es un archivo .ui
O simplemente lo dejo tal cual como esta?

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by danckoo1** [comment]
Hola! primero que todo (nada), el os.path.join no podrias usarlo dado que los .ui no son archivos como tal de python, y segundo no te preocupes de esto, dado que los archivos que designer crea pueden ser ocupados en distintos OS sin problema alguno, asi que dejar los / no causara ningun problema en la corrección, saludos!
