### ISSUE TITLE
ConnectionResetError AF7 

### ISSUE THREAD

**Issue by catalinacarter** [IIC2233/syllabus#740]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido
Hola! Estoy arreglando ciertas cosas de la AF7 para utilizar algunas partes en mi tarea (citando obviamente) y tengo un problema para iniciar las interfaces. Revisé todas las issues del tema pero no hay nada parecido y me pasa que **después de enviar el nombre de usuario, se resetea la conexión y aparece un ConnectionResetError lo que hace que no se abra ninguna otra ventana**. He hecho varios print en mi código para cachar de donde puede venir el error, pero no tengo idea.
**¿Por qué puede estar pasando esto?**
Gracias!

**Comment by tqmbanados** [comment]
Hola! Esa excepción se levanta cuando el socket es cerrado desde uno de los dos lados de la arquitectura *client-server*, causando un error en el otro lado. Es decir, en tu caso me parece que `server` está cerrando la conexión, causando un error en el `client`. Revisa bien tu manejo de *threads* en el `server`, tus ciclos `while` y algún otro detalle que pueda estar causando que el socket se cierre prematuramente. 
Espero que te sea de ayuda esto por último para guiarte a encontrar el problema. Cuéntame si te va bien!

**Comment by antoniafuica** [comment]
Hola!  A mi me pasa lo mismo, supiste donde estaba el problema?
