### ISSUE TITLE
ComectionResetError: [WinError 10054] 

### ISSUE THREAD

**Issue by DanielCarrascoFalcon** [IIC2233/Syllabus#740]
El server no funciona, llega a la funcion recv() y me lanza el error:
ConnectionResetError: [WinError 10054] Se ha forzado la interrupción de una conexión existente por el host remoto
Intenté sin internet, corte el firewall, cambie los puertos, puse "localhost", "0.0.0.0" y nada...
Acepta al cliente y se cae :c 
Alguna idea?

**Comment by Arcoirisky** [comment]
Desactivaste los antivirus? Y/o el firewall de Windows??

**Comment by ljrodriguez1** [comment]
A mi me ocurre el mismo problema y no creo que sea tema del antivirus, ya que yo al conectar al cliente mando un mensaje al servidor y luego se cae, de hecho si al conectar el cliente mando mensajes en un loop infinito, este no se cae, me da la impresion que el problema es porque se cae el cliente entonces el servidor tira ese error

**Comment by ljrodriguez1** [comment]
a mi se me cae el cliente con el siguiente error
Process finished with exit code -1073740791 (0xC0000409)

**Comment by ljrodriguez1** [comment]
El problema esta en que se cierre, a mi se me cerraba ya que mi cliente creaba una interfaz y no tenia en mi codigo el:
app = QApplication([])
app.exec_()
por lo tanto se caia con la interfaz, te recomiendo buscar porque es que se esta cayendo tu cliente
