### ISSUE TITLE
Error PyQt5 en Visual Studio

### ISSUE THREAD

**Issue by TdelrioC** [IIC2233/syllabus#740]
Al ejecutar un archivo desde la terminal de VS me sale el error

    import PyQt5.QtGui as gui
ModuleNotFoundError: No module named 'PyQt5'

Pero al ejecutarlo desde la terminal desde el computador si se ejecuta.
Alguien sabe porque pasa esto?

**Comment by KnowYourselves** [comment]
Hola @TdelrioC!

Esto fue respondido en #674

**Comment by TdelrioC** [comment]
Gracias
