### ISSUE TITLE
Designer la ventana aparece más chica que en el editor

### ISSUE THREAD

**Issue by jirarrazaval** [IIC2233/syllabus#741]
Hola estaba haciendo la ayudantía 5 para aprender a usar designer y diseño una ventana con QWidget, pero después cuando ejecuto mi código la ventana aparece mucho más chica. Cómo se arregla esto para que quede a la misma escala?

De hecho en la opción de preview en designer me aparece la ventana bien pero en python no :(
y no es un problema del editor de texto porque si la ejecuto del sistema también me sale igual de chica

**Comment by lucasvsj** [comment]
Hola @jirarrazaval 
Debo decir que tu caso me parece un poco extraño (si solo lo que hiciste fue implementar tu archivo .ui en tu programa).  Necesitaría mas información para poder seguir ayudándote, como que me muestres el archivo .ui, junto con la forma en que implementas el QWidget en tu programa.
Por ultimo, existe el método `setGeometry(int, int, int, int)` que recibe 4 integers, donde los primeros 2 son las coordenadas x e y iniciales de tu QWidget y los otros 2 son para el width (ancho) y el height (alto) respectivamente.
Ojalá esto te sirva y quedare atento a cualquier información adicional
