### ISSUE TITLE
Press Event

### ISSUE THREAD

**Issue by kalarconvl** [IIC2233/syllabus#741]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola! Me queda una duda del ejemplo de press event (semana 9). Qué es ```event.y()```? Es como la posición en el eje y de la ventana en el que se hace click?

**Comment by knight-who-say-ni** [comment]
Holaa @kalarconvl !!

En el caso de **mousePressEvent**,  `event.x()` y `event.y()` retornan la posicion del mouse relativo a la ventana en que te encuentres.
Por eso en el ejemplo ponen `if event.y() <= 255`, ya que en ese ejemplo el color del label es cambiado si se presiona con el mouse sobre él   (el label es de altura 255, ocupa todo el ancho de la ventana y esta entre la altura 0 y 255).

Espero que haya quedado claro, si no avisame ;)

**Comment by kalarconvl** [comment]
Holaa @knight-who-say-ni  
Sii! Me bajó la duda porque en el ejemplo solo lo ponen sin comentario explicando qué significa. Muchas gracias!
