### ISSUE TITLE
Numero 0 en matriz

### ISSUE THREAD

**Issue by depstein26** [IIC2233/Syllabus#741]
Hola, perdón pero me surgen dudas del enunciado. El 0 que se debe agregar al principio de cada fila para el idat, ya está agregado verdad?

**Comment by ifcarrera** [comment]
Hola!
Al momento en que formes tu matriz de bytes debes asegurarte de agregarlo. 
Saludos

**Comment by depstein26** [comment]
Pero en la matriz que calculo al sacar el idat, dado el largo que me da, debería tenerlo agregado

**Comment by ifcarrera** [comment]
Sí viene agregado en la foto, lo que debes asegurarte es de ponerlo en el lugar que corresponde
