### ISSUE TITLE
Es necesario hacer otra cuenta de github para ejecutar las acciones de telegram?

### ISSUE THREAD

**Issue by jgramsch** [IIC2233/Syllabus#741]
y otra pregunta, 
la tarea hay que subirla al repo de prueba aparte del repo de las tareas?

**Comment by akaminetzkyp** [comment]
Esto quizás te ayude. https://github.com/IIC2233/Syllabus/issues/677

Saludos!

**Comment by iqacevedo** [comment]
@jgramsch no es necesario, basta con que este en tu repo privado en que has subido todas tus tareas (obviamente también debes subirla a heroku).

Saludos !

**Comment by jgramsch** [comment]
Hay hartas cosas q no especifican en el enunciado jaja
