### ISSUE TITLE
Guardar Canciones

### ISSUE THREAD

**Issue by ljrodriguez1** [IIC2233/Syllabus#741]
No me queda claro del enunciado como funciona exactamente la edición y principalmente guardado de las canciones,
yo al cargar la canción, del midi, creo una clase Midi en donde se guardaran todas las notas y información de la canción, ahora lo que no se es que cuando un cliente se meta a editar dicha canción cada vez que este edite una nota debo reescribir el archivo midi y volver a cargarlo para tener una nueva clase de mi cancion, o puedo guardar la nota en la lista de notas y solo reescribir el archivo midi cuando el cliente presiona un boton que se llame guardar, (Este boton no existe en su ejemplo de interfaz y por eso pregunto), si lo hago de la segunda forma esto significaria que si no se presiona guardar los cambios no se reflejaran en la cancion

**Comment by Arcoirisky** [comment]
Holi~ Mira la issue #703 uwu Puede ser interesante a propósito de tu pregunta ouo

**Comment by ljrodriguez1** [comment]
justo lo que buscaba, perdon por no verlo

**Comment by Arcoirisky** [comment]
No te preocupes <3
