### ISSUE TITLE
Data del canal y caso extraño

### ISSUE THREAD

**Issue by Regenschrim** [IIC2233/Syllabus#742]
Tengo una duda con respecto a la data del canal. Al leerla uno obtiene con los primeros 4 bytes el tipo, con los 4 siguientes se obtiene el largo de la data y con ese valor, se obtiene la data. El problema es que se cortan mis datos. A modo de ejemplo, si obtengo los 2 primeros datos, me sobran 312 bytes, pero el largo dice que debo tomar solo 156, así corto la data. El problema es que los últimos dos bytes son 0 y 144, por lo que no se tiene la nota ni la intensidad. ¿Es problema de como estoy leyendo el archivo o no tengo que ocupar el largo que obtengo?

En cuanto al caso extraño, me pasa que con la canción de shingeki me sobre un byte en el data. No sigue el orden que debería, parte con un byte cualquiera, luego el del tiempo y luego el del tipo del mensaje :s y solo me pasa con esa canción.

Gracias de antemano!!

EDIT 1: Probe todo lo que se me dijo abajo, arregle el tema de los largos, pero me sigue pasando que con la canción de Shingeki me sobra un byte al principio de la data, y es solo con esa cancion. Me he asegurado de leer byte por byte los archivos y que los printee, además de revisar los largos cuando obtengo el tipo, el length y la data. No se que es lo que pasa con esa canción. Ayuda plis :(
Esto es lo que me imprimen los bytes del data de shingeki:
131
96
128
0
0
120
128
0
0
Ese 131 es el que no se de donda sale o a que corresponde :(

**Comment by Pipelao** [comment]
Hola
No soy ayudante, pero debes estar leyendo mal los archivos porque efectivamente con el largo se ve hasta dónde llega la data, en todo caso, si no realizas el bonus siempre será hasta el final del canal. Quizás podrías ver bien cómo recorres cada uno de los bytes, te recomiendo que los imprimas e identifiques qué es cada uno. Por último, ve bien cómo transformas de byte a número y qué bytes estás tomando, quizás estás tomando más o menos de los que corresponden y por eso no te da el número.

Saludos
