### ISSUE TITLE
Error paso 7

### ISSUE THREAD

**Issue by emontecinos** [IIC2233/Syllabus#742]
hola, tengo el siguiente error
![image](https://user-images.githubusercontent.com/26130693/27566872-f9f55cd8-5ab5-11e7-852e-542f704440ad.png)
que puede estar saliendo mal?

**Comment by Hernan4444** [comment]
@emontecinos 
1) te aseguraste de hacer git add y git commit antes de hacer git push? 
2) Te aseguraste de cumplir con los archivos solicitados, esto incluye que tengan la extensión que se pide y adentro esté el comando sin punto final?

Saludos!

**Comment by emontecinos** [comment]
si, hice git add y git commit antes de git push
tambien tengo los archivos bien escritos

**Comment by Hernan4444** [comment]
@emontecinos según tu repo el procfile tiene extension .txt y no debe tener. Intenta eliminar su extension.

**Comment by emontecinos** [comment]
estoy viendo las propiedades del archivo y aparece
![image](https://user-images.githubusercontent.com/26130693/27567531-5e118f44-5aba-11e7-9249-f30e8d654ff8.png)

**Comment by Minjor** [comment]
tengo exactamente el mismo problema

**Comment by Hernan4444** [comment]
pueden hacer push para ver el repo mas actualizado?
@Minjor tu archivo Procfile está incompleto

**Comment by emontecinos** [comment]
si, ya esta hecho

**Comment by Hernan4444** [comment]
por si acaso tienes el comando que usaste para setear las variables de entorno?? que en el enunciado le faltaba un espacio y sin ese espacio el comando no funciona. (Si hago muchas preguntas es que intento descargar los posibles errores :sweat_smile: )

**Comment by emontecinos** [comment]
no traqui, le puse el espacio al comando y aparecio el mensaje de seteo correcto
el problema no va por ahi

**Comment by LuisFros** [comment]
Me paso algo parecido, pueden ser ser 3 cosas.
-1) tu requirements.txt no tiene a todas las liberias instaladas por pip. Desde windows puedes hacer el comando "pipreqs T07" por ejemplo estando en la carpeta de Tareas de tu repositorio. Si te dice que ya existe el archivo , haces "pipreqs T07 --force" el cual reemplaza tu archivo existente.( si no tienes pipreqs, " pip install pireqs")
-2) No estas haciendo el Add-Commit y Push que esta en el enuncido, este tiene que ser desde el nodo padre de to repositorio . 
-3) Tu procfile no esta bien seteado, pero como no te esta tirando ese error, lo mas seguro es que sean algunas de las anteriores. Sino, dese Windows puedes usar el comando 
-echo "primera linea Procfile " >Procfile
( asegurate de que la primera linea del archivo sea la del enunciado con el espacio que falta)

**Comment by LuisFros** [comment]
Tambien, trata de ver que te dicen los logs de heroku. Haciendo "heroku logs" , te dice que esta ocurriendo mas en detalle y cuando este este seteado correctamente
