### ISSUE TITLE
Actualizacion de cambios

### ISSUE THREAD

**Issue by JPSF** [IIC2233/Syllabus#742]
¿ Se debe enviar todos los datos del programa al usuario cada vez que este se conecte o el usuario debe guardar información(datos del programa, imagenes,etc) de la última vez que se conectó?

**Comment by Arcoirisky** [comment]
Hola! Eso queda a tu criterio O: Puedes hacerlo de la forma en que más te acomode, enviarlo todo o ir actualizando. 

Suerte!!
