### ISSUE TITLE
Interacción mesero con chef y cliente 

### ISSUE THREAD

**Issue by CataSudo** [IIC2233/syllabus#742]
Para que el mesero pueda hacer un pedido con el chef solo tiene que estar en su misma posición o podemos hacer que el usuario le haga click al chef para iniciar la secuencia? Tengo una duda similar con los clientes, en especial cuando chocan con el mesero, hay una interacción de usuario para que se lleven el plato o es por geometría? 
Muchas gracias y quedo atenta a sus respuestas

**Comment by kadroguett** [comment]
Hola @CataSudo 
Como dice el enunciado, el mesero debe colisionar con el mesón del chef. Si el jugador se para al frente del mesón y sigue caminando en esa dirección, el chef deberá comenzar a cocinar (a menos que el chef haya preparado un bocadillo, en cuyo caso el mesero deberá recoger la comida).
Al igual con los clientes, se deben entregar los pedidos sólo si el mesero colisiona con ellos. El uso de clicks u otro tipo de interacciones no correspondería en estos casos.
