### ISSUE TITLE
Uso de & en primera letra y sizeHint()

### ISSUE THREAD

**Issue by kalarconvl** [IIC2233/syllabus#742]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola! No me queda claro de los contenidos cómo funciona el signo **&** cuando se pone antes de la primera letra y del método **sizeHint()**. Dicen que:

_El uso del caracter & al inicio del texto de algún botón o menú permite que la primera letra del mensaje mostrado esté destacada. La visualización depende de la plataforma utilizada. El método sizeHint provee un tamaño sugerido para el botón._

Pero si no las pongo queda exactamente igual. ¿Cómo se usan o cómo se hacen funcionar? 
Lo mismo sobre el ejemplo de *Eventos del teclado*. Si comento la línea ```self.resize(self.etiqueta.sizeHint())``` queda exactamente igual.

**Comment by kadroguett** [comment]
Hola @kalarconvl, ese comentario no se refiere al `sizeHint()`, sino que a la etiqueta que lleva el botón:

![image](https://user-images.githubusercontent.com/31357861/96660020-dba67d00-131e-11eb-98ed-0d59ace081bd.png)

**Comment by kadroguett** [comment]
Así se ve el botón finalmente:

![image](https://user-images.githubusercontent.com/31357861/96660253-7737ed80-131f-11eb-99f6-59c897736c3f.png)

Al ejecutarlo y apretar la tecla `alt` (esto va a depender de la plataforma utilizada como dice el comentario) la letra inicial del botón se subraya.

**Comment by kalarconvl** [comment]
Yaa perfecto gracias! Y de qué sirve sizehint?

**Comment by kadroguett** [comment]
Es para darle un tamaño recomendado al widget

**Comment by kalarconvl** [comment]
Gracias!!
