### ISSUE TITLE
Cómo se activan los eventos de teclado y mouse

### ISSUE THREAD

**Issue by kalarconvl** [IIC2233/syllabus#743]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola! En el ```keyPressEvent``` y ```mouseMoveEvent``` no entiendo cómo se activan las funciones si no se llaman en ningún lado. Estas reciben un parámetro ```event```, es por eso? En ese caso, la palabra ```event``` está reservada para un evento por parte del teclado o del mouse? Y si pasa un event automáticamente se activa la función?

**Comment by danckoo1** [comment]
Hola! la forma en que yo lo entiendo es que dichas funciones vienen por defecto conectadas a una señal, y dicha señal es activada cada vez que ocurra el evento correspondiente, osea si que si aprietas una tecla se dispara la señal correspondiente, y como esta esta conectada al metodo keyPressEvent este se ejecuta. 
Ahora lo que tu mencionas del parametro event, es lo que la señal le envia al metodo  y en los casos que mencionas, dicho parametro será un objeto del tipo PyQt5.QtGui.QMouseEvent o PyQt5.QtGui.QKeyEvent segun corresponda, ahora si quieres saber mas sobre estos podrias buscarlos en la documentacion, para asi ver que metodos tienen asocidos, etc. Espero se entienda 😄

**Comment by kalarconvl** [comment]
@danckoo1 Ahh o sea que si le cambio el nombre a la función ```mousePressEvent``` no funciona porque es una función "predeterminada" por así decirlo? Acabo de probar y definitivamente no funciona si lo cambio. Pensé que en el código se estaba definiendo el método jajaja muchas gracias!

**Comment by danckoo1** [comment]
exacto, tal como te diste cuenta los metodos no se estan creando, sino que es un override de un metodo que pyqt ya implemento en sus clases

**Comment by sjlarrain** [comment]
Hola! Estoy con un problema en el mismo metodo de `keyPressEvent` en la tarea. Cuando apreto ciertas `keys`, no funciona y con otras si. Por ejemplo el `ENTER`  funciona, sin embargo todas las letras no estan funcionando. He buscado en stackoverflow y lo más cercano que he encontrado esta en [este link](https://stackoverflow.com/questions/25438616/pyqt-not-recognizing-arrow-keys).

Creo que la issue esta cercano a lo que pido. Si es necesario abrir una Issue la abró sin problemas.

Muchas gracias

Santiago

**Comment by danckoo1** [comment]
@sjlarrain lo siento Por tardar! Sería mejor si creas una nueva issue por si a alguien más le ocurre y te respondo a la brevedad

**Comment by sjlarrain** [comment]
@danckoo1 logre que funcionara pero solo cuando "inicio" el juego y no la consola.  Ahora solo me gustaría entender el porque de esto nomas.  Voy a aprovechar la clase de hoy para preguntar de todas maneras. 

Solo para complementar, la estructura que tengo definida es una `QWidget` con 4 `Qwidget` en el interior. No se si eso afectara que solo funcionen ciertas teclas y no todas.

Muchas gracias!

Santiago

**Comment by danckoo1** [comment]
No entendí a qué te referías con iniciar el juego y no la consola 😅. De todas formas consultarlo en clase será lo mejor ya que a priori no se me ocurre el porque, la única idea que se me viene a la mente es que quizás algún otro widget está atrapando los eventos, en vez de ser el widget en que hiciste el override del `keyPress`, por lo que daría la impresión que los eventos no funcionan. Saludos!

**Comment by sjlarrain** [comment]
Con la consola me refiero al juego en general (que es este `QWidget` grande), el iniciar juego es activar la caida de las flechas (que es un `Qwidget` dentro de la "consola"). Me hace sentido el caso que al hacer el override  quede atrapado en un `Qwidget`, sin embargo no se porque pasaba si lo hice para la ventana en general y no para este en especifico.

**Comment by gatochico** [comment]
Hola @sjlarrain ! Pudiste resolver tu duda en clases? Si todavía tienes la pregunta, te recomiendo hacer una issue nueva para que no se pierda!

**Comment by sjlarrain** [comment]
@gatochico  si pude resolverla en clases. Muchas gracias por la preocupación.
