### ISSUE TITLE
Números como parámetros

### ISSUE THREAD

**Issue by amparostevens** [IIC2233/syllabus#743]
Hola! 
Los números que aparecen en el enunciado en azul también se tienen que incluir en `parametros.py`?

**Comment by jitorcas** [comment]
Hola! @amparostevens

Los números que forman parte de las fórmulas no son necesario que se consideren como parámetros, ya que por ejemplo la reputación máxima siempre será 5. Sin embargo, si quieres tomarlos como parámetro **debes** especificarlo en el README.

Ten en consideración que todos los parámetros siguen **ESTE_FORMATO** y si utilizas algún otro valor constante en tu programa  también debería seguir **ESTE_FORMATO** y ponerlo en `parametros.py`

Éxito!
