### ISSUE TITLE
Clientes conectados desde distintos computadores

### ISSUE THREAD

**Issue by cjmunoz4** [IIC2233/Syllabus#743]
Hola! Para esta tarea es posible asumir que sólo se conectarán usuarios de distintos computadores? Es decir, que en un mismo computador no se conectarán dos usuarios a la vez, lo cual parece totalmente lógico. La pregunta va a que las imágenes las guardaré en una carpeta, y si dos usuarios se conectan desde el mismo computador podría haber problemas con las imágenes. Muchas gracias de antemano.

**Comment by egromero** [comment]
Hola, 
No puedes asumir eso, se deben poder manejar varios usuarios en un mismo computador.

Saludos!
