### ISSUE TITLE
Cerrar el server

### ISSUE THREAD

**Issue by inmadariaga** [IIC2233/Syllabus#744]
mi duda va en que si estoy corriendo el servidor, le agrego un comentario a una imagen (desde un user) y luego "mato" el servidor, el comentario se pierde, ¿esto va a ser penalizado?, ¿tengo que arreglarlo?

**Comment by egromero** [comment]
Holaa,

Los comentarios deben perdurar entre las sesiones, por lo que cuando reinicias el servidor, deben aparecer los que fueron hechos con anterioridad.
Es decir, debes arreglar lo que dices.

Saludos!

**Comment by AndresGarciadelaHuerta** [comment]
@egromero las ediciones de las fotos también deben guardarse si se cierra el server? O comienzan como al principio de nuevo nomás?

**Comment by egromero** [comment]
Hola,

Lo primero que dices, la idea es que las ediciones perduren en el tiempo. Si vuelvo a ingresar, debe mostrase como estaban en la ultima sesión del server, es decir con la ultima edición.

Saludos y ánimo 🙌🏾

**Comment by AndresGarciadelaHuerta** [comment]
@egromero Perfecto, gracias!
