### ISSUE TITLE
Duda enunciado T06 lista de notas

### ISSUE THREAD

**Issue by Mariana-Ortega-del-Rio** [IIC2233/Syllabus#744]
Hola!

En la ventana edición y/o espectador si se está editando una canción SOLO se pueden añadir notas al final de la lista y eliminar notas? Es decir, no se permite agregar notas entremedio, solo al final de la lista?
También quería aclarar porque no me quedó tan claro del enunciado si solo puede haber 1 usuario editando a la vez una canción.

Saludos!
Mari

**Comment by Arcoirisky** [comment]
Holaa~ buenos días :D

Principalmente deben preocuparse por las que se agregan/eliminan al final. Si quieres que se modifiquen las del medio sin borrar todo lo anterior, queda a tu criterio uwu

Y si, sólo uno edita mientras los otros que entren serán espectadores que puedan descargar la canción en cualquier momento :D

**Comment by Arcoirisky** [comment]
Todo lo contrario. Si los observadores desean descargarla mientras se edita, se descarga la canción con todos los cambios existentes hasta el momento de presionar "descargar". 

La edición es en vivo y las descargas se permiten en todo momento :D 

Ánimo! :DDD

**Comment by Arcoirisky** [comment]
Pd: Todas las canciones que están sin tocar están como en una lista a parte, listas para descargar. Pero, si uno presiona editar, esa canción desaparece de la lista de descargas y sólo se puede mirar (si no eres el editor)
