### ISSUE TITLE
Problema con vs code y python

### ISSUE THREAD

**Issue by sebadelorenzo** [IIC2233/syllabus#745]
Hola! Cuando abrí vs code hoy me apareció en la esquina inferior derecha que python no estaba instalado! Pero he trabajado con python todo este tiempo. De hecho en el status bar en la izquierda aparece python 3.

<img width="1153" alt="Captura de Pantalla 2020-05-19 a la(s) 19 24 16" src="https://user-images.githubusercontent.com/61999157/82388270-3736ac80-9a07-11ea-8de8-696b5503eb83.png">

Que puede ser? Me afectará en algo? Gracias de antemano

**Comment by lucasvsj** [comment]
Hola @sebadelorenzo 
Este mensaje no se refiere que no tenga instalado Python en tu computador, sino que se refiere a que no posees la Extension Python (podriamos decir que es como una libreria de VSCode) instalada.
![image](https://user-images.githubusercontent.com/37182459/82388855-9c3ed200-9a08-11ea-9dec-08ca63bcebd0.png)
Esta Extension te da ciertas ventajas al programar en con Python, no es requisito del curso que la tengas, pero nunca esta de más tenerla.

**Comment by sebadelorenzo** [comment]
Gracias!

**Comment by lily416** [comment]
Hola @sebadelorenzo, 

El mensaje que te aparece tiene relación con la [extensión para Python](https://marketplace.visualstudio.com/items?itemName=ms-python.python) de VSCode. Esta trae ciertas funcionalidades que facilitan el trabajar con archivos .py, pero no es necesaria para utilizar VSCode ni correr archivos .py.

Siento la demora de la respuesta y espero que te sea de ayuda.
Saludos y éxito en la tarea 👋🍭

PS: Cada vez que trabajes con un nuevo tipo de archivo te pueden salir esos mensajes, pero solo son recomendaciones de extensiones. Igual te recomiendo revisarlas ya que hay algunas que son bastante útiles 😉🤓
