### ISSUE TITLE
Largo canciones

### ISSUE THREAD

**Issue by santilaguna** [IIC2233/Syllabus#745]
Hola! 
¿puedo establecer un largo máximo para el nombre de las nuevas canciones (indicándolo en el README)? de lo contrario ¿puedo no mostrar el nombre completo de la canción? pues me genera problemas para seleccionar las canciones...
Edit: ¿podemos además restringir el largo mínimo del nombre de la canción a 1 carácter?

**Comment by mfanselmo1** [comment]
Hola, no hay problema con ninguna de las 2 restricciones.
