### ISSUE TITLE
Eliminar archivo que subi a mi repositorio sin querer

### ISSUE THREAD

**Issue by diego-ayala-2000** [IIC2233/syllabus#745]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola como puedo eliminar de mi repositorio los sprits que subí sin querer.

**Comment by kadroguett** [comment]
Hoola @diego-ayala-2000, si quieres borrar una carpeta debes escribir:
`git rm -r "nombre carpeta"`
Luego debes hacer el commit
`git commit -m "descripción del commit"`
Y finalmente debes hacer push a los cambios
`git push`

Me cuentas si te funcionó

**Comment by Zenos-Paradox** [comment]
@kadroguett Y si es un archivo dentro de una carpeta?

**Comment by kadroguett** [comment]
Hola @Zenos-Paradox tienes dos opciones:
Si quieres eliminar el archivo del repositorio pero aun quieres conservarlo en tu carpeta debes escribir:

`git rm --cached dir/file.py`

siendo `dir` el nombre de la carpeta, `file` el nombre del archivo y `.py` la extensión de este.

En cambio si quieres eliminar el archivo tanto del repositorio como de tu carpeta simplemente escribes:

`git rm dir/file.py`

Y finalmente en ambos casos escribes:

`git commit -m "descripción del commit"`

y 

`git push`
