### ISSUE TITLE
Envio de datos TCP

### ISSUE THREAD

**Issue by jvlara** [IIC2233/Syllabus#745]
Hola, estoy teniendo un problema en el momento en que el servidor envia al cliente las imagenes, resulta que los mensajes se "solapan" ya que se las envio seguido, lo que hace que el socket cliente deje de recibir información (Como que se bloquea y ya no recibe nada). Tuve que poner un time.sleep(0.1) en el servidor para que se las enviara de manera más lenta, y así funciona perfecto ¿Hay alguna manera de que un mensaje quede en espera hasta que el otro termine?.

**Comment by ifcarrera** [comment]
Hola, los mensajes no deberían "solaparse", probablemente estás enviando algunos mensajes de manera errónea. Pues en el protocolo TCP, la información va a quedando en una cola, y un mensaje solo se envía cuando ya se envió completamente el anterior. 
Poner un sleep no es una solución segura para nada. No obstante aquello, si te funciona todo bien agregándolo no hay problema, puedes hacerlo.
Saludos :D
