### ISSUE TITLE
Objetos en mapa.csv

### ISSUE THREAD

**Issue by Etienne99** [IIC2233/syllabus#746]
Hola! Al cargar los objetos de mapa.csv ¿Se puede asumir que estarán dentro de los límites del mapa y en posiciones en que no colisionen entre ellos? Pregunto esto sobre todo por el avance, ya que estoy cargando los objetos y ubicándolos en el mapa sin programar todavía interacciones como la de arrastrar objetos al mapa (comprar), en las que claramente habría que considerar los casos que mencioné.

**Comment by kadroguett** [comment]
Hola @Etienne99 
Si, puedes asumir que los objetos presentes en el archivo `mapa.csv` estarán en casillas válidas. Sobre los límites del mapa, para eso se deben utilizar los parámetros LARGO_MAPA y ANCHO_MAPA, ya que de esta forma si los objetos están fuera de tus parámetros iniciales, solo basta con modificarlos.

**Comment by Etienne99** [comment]
Ok, gracias!

**Comment by kadroguett** [comment]
De nada, éxito en tu tarea!!

**Comment by Camila-sty** [comment]
El LARGO_MAPA viene siendo el eje x?

**Comment by kadroguett** [comment]
@Camila-sty haz otra issue con esa pregunta ya que no se relaciona directamente con lo que se pregunta acá. Esto es para que todo quede más ordenado y sea más sencillo encontrar preguntás repetidas.
