### ISSUE TITLE
Problema al crear canciones

### ISSUE THREAD

**Issue by CmPoblete** [IIC2233/Syllabus#746]
Hola, por alguna razon mi programa tiene problemas si la primera accion que se hace al iniciarlo es crear una nueva cancion, pero si edito otra antes de crear una si funciona. Es importante arreglar este problema?

**Comment by leolivares** [comment]
Hola @CmPoblete 
Se espera que el programa sea a prueba de errores, por lo tanto, lo mejor seria solucionarlo.
Sin embargo, si consideras mas importante priorizar otras funcionalidades, podrías dejarlo para el final. En caso de no solucionarlo, explicarlo en el ReadMe, para facilitar la corrección.
Saludos.
