### ISSUE TITLE
Diferencia en tamaño de ventana que se muestra en preview de QtDesigner y ejecución desde VSCode

### ISSUE THREAD

**Issue by camirojasguajardo** [IIC2233/syllabus#746]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola!

Cuando veo la preview de mi ventana en Qt Designer, aparece de un tamaño y en una ubicación de la pantalla distintas a cuando ejecuto el codigo desde VSCode. ¿Por qué podría ser? A la vez, en las coordenadas de la ventana, en qtdesigner (en la parte de "Geometry", se indica la posición (0,0), pero se abre en otra parte de la pantalla:( 

De antemano, agradezco su ayuda. Saludos!

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by manearaya** [comment]
Hola @camirojasguajardo! 

Se me ocurre que quizás no estás guardando el archivo a medida que vas editando, por lo que no se estaría actualizando el archivo .ui que tiene tu ventana.

También te puede servir usar `setGeometry` o `move` para definir de nuevo las dimensiones de la ventana.

Ojalá te sirva!

**Comment by camirojasguajardo** [comment]
me sirvió hacer de nuevo setGeometry! gracias:)
