### ISSUE TITLE
Error en blurry

### ISSUE THREAD

**Issue by savelozo** [IIC2233/Syllabus#746]
Al intentar aplicar el efecto blurry sobre la foto de Mushroom, la foto se me corta:

![image](https://user-images.githubusercontent.com/8712664/32874522-85fdef12-ca71-11e7-9300-55d6ad381c63.png)

Sin embargo, al realizar el mismo algoritmo a la foto de DragonBall obtengo la foto completa:

![image](https://user-images.githubusercontent.com/8712664/32874533-9b111352-ca71-11e7-9f18-6831da89fe4b.png)

Cuando intento abrir el nuevo archivo de la foto Mushroom me sale el siguiente error: UnicodeDecodeError: 'utf-8' codec can't decode byte 0x95 in position 0: invalid start byte

Es extraño porque la foto de Dragon Ball es más grande que la foto de Mushroom y uno podría pensar en que se corta porque la iteración es muy larga o algo similar, pero en este caso no tendría sentido. He buscado en internet por el error o algún ejemplo similar y no encuentro nada. Cabe mencionar que al imprimir el valor del los últimos bytes que estoy agregando a mi matriz de Mushroom nuevo, la consola me muestra (255, 255, 255). Alguien sabe por qué podría cortarse de esa manera la foto?

PD. Debo ver qué mejorar en mi código para que el blurry funcione correctamente jaja

**Comment by fgbruna** [comment]
@savelozo  pudiste solucionarlo ?

**Comment by savelozo** [comment]
@fgbruna aún no, me estaba estresando demasiado con eso así que opté por dejarlo en stand by y seguir con otras funcionalidades :/

**Comment by movaldivia** [comment]
@savelozo me pasó lo mismo pudiste solucionarlo?

**Comment by ajahr95** [comment]
@savelozo me paso lo mismo, alguien te respondio?

**Comment by movaldivia** [comment]
@ajahr95 @savelozo Mi problema fue con el largo, mantenía el original, pero al descomprimir y volver a comprimir el largo cambia. Espero que les sirva !
