### ISSUE TITLE
[Descuento por ngrok]

### ISSUE THREAD

**Issue by Okhan97** [IIC2233/Syllabus#746]
Hola buenas, me gustaria saber que tanto descontarán por usar ngrok en vez de heroku.

Estuve todo el finde (no es broma) peleandome con heroku y no pude avanzar casi nada ya que me tiraba error tras error. El domingo en la noche decidí empezar todo denuevo pero esta vez usar ngrok para poder hacer algo. Finalmente termine a la tarea (sin bonus) el Lunes como a las 23:00.

Sinceramente no creo poder conectar todo con heroku pues lo he intentado una vez mas y me vuelven a salir errores (ahora unos que no me habian salido antes).

Dado todo lo anterior me gustaría saber que tanto puede afectar en mi nota el no-uso de heroku, y que si es posible pedir un poco de consideracion para que este descuento no sea muy duro.

**Comment by Hernan4444** [comment]
Su situación será considerada y lo mas probable es que se les pedirá que asistan a la re-corrección final para ver sus tareas en sus computadores.

Saludos!!!

**Comment by Okhan97** [comment]
Siempre se puede dejar el pc prendido por semanas 😆
