### ISSUE TITLE
Error 404 API microsoft

### ISSUE THREAD

**Issue by IchottMano** [IIC2233/Syllabus#747]
Cuando intento acceder al servidor de microsoft
'https://westcentralus.api.cognitive.microsoft.com/face/v1.0'
el servidor me tira error 404 :c

**Comment by egromero** [comment]
Hola, solo debían conseguir el token, en la actividad se les dará mas detalles!

Saludos!

**Comment by IchottMano** [comment]
Muchas gracias!
