### ISSUE TITLE
Problema para instalar QtDesigner

### ISSUE THREAD

**Issue by Benjamin-Pedraza** [IIC2233/syllabus#747]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

Hola, tengo el mismo problema que el de la issue #694 y otras relacionadas, ya ocupé los posibles comandos que se sugieren en ellas (al ejecutar `designer` en CMD no ocurre nada) y reinstalé PyQty5, PyQty5-tools y Python. Así que me quedé sin ideas de como arreglar esto. Gracias de antemano :) .

**Comment by YehudaGurovich** [comment]
@Benjamin-Pedraza Quizá la issue #727 te sirva.

**Comment by Benjamin-Pedraza** [comment]
@YehudaGurovich hice lo de la issue #727 y me funcionó, gracias :)
