### ISSUE TITLE
URGENTE

### ISSUE THREAD

**Issue by B-Dominguez** [IIC2233/Syllabus#747]
NO ME FUNCIONA EL PUSH
no sé, creo que tengo que usar subtree o esas cosas pero no sé como hacerlo, y creo que no se estpan haciendo los commits a mi repo sino solo lo de heroku y para más no me funciona bien el internet ayuda por favor

**Comment by B-Dominguez** [comment]
Después logré pushear un commit que estaba guardado de antes de las 00:00, pero como que no contiene los archivos, y ahora el push me tira fatal error
![image](https://user-images.githubusercontent.com/26129405/27570715-5ce10ee2-5ace-11e7-83a6-e6373dd1e623.png)

**Comment by B-Dominguez** [comment]
Probé incluso con otro clone del repo, pero tampoco me dejó (llevo más de una hora intentado esto :'( )
![image](https://user-images.githubusercontent.com/26129405/27570936-e2ad62fe-5acf-11e7-80b1-e3c096985d8d.png)

**Comment by iqacevedo** [comment]
Hola 

Prueba escribiendo antes de hacer el commit `git add --all` , si no te resulta intenta con `git commit -am "un commit" `

Saludos !

**Comment by B-Dominguez** [comment]
Hola, ya había intentado todo eso, pero gracias! finalmente lo acabo de lograr subir en otra carpeta nomás porque las formas que empecé a encontrar que quizás funcionarían implicaban borrar todo el historial del módulo, lo que no me convendría si creo que tengo opciones de que me corrijan :(

**Comment by iqacevedo** [comment]
Que bueno que pudiste subirlo !

Saludos!
