### ISSUE TITLE
problema con abrir archivo en el archivo main.

### ISSUE THREAD

**Issue by felipehen** [IIC2233/syllabus#747]
Logre terminar lo de cargar archivos, y se que funciona, o al menos funciona cuando lo hago en mi archivo "Ventana", pero cuando lo importo al Archivo Main.py, me salta el siguiente error

if(linea == archivo[0]):
TypeError: '_io.TextIOWrapper' object is not subscriptable

siendo archivo[0] la primera linea del archivo datos

**Comment by moquezada** [comment]
Hola @felipehen,

Esto sucede porque no se puede indexar un objeto `_io.TextIOWrapper`. ¿Probaste usando el método `readlines()`? 🤔
