### ISSUE TITLE
Plazo tarea

### ISSUE THREAD

**Issue by mjgutierrez1** [IIC2233/Syllabus#748]
Hola, ¿es posible que den un día más para hacer la tarea? Lo pregunto porque justo el lunes es el examen de matemáticas discretas y seguramente hay varios a los que les topan estas dos cosas.

**Comment by stephichau** [comment]
Hola!
Tal como dijo @FernandoPieressa en la issue #689, no les podemos dar más tiempo porque nosotros estamos muy justos con el plazo de las correcciones :(.

**Comment by vixolo** [comment]
Y el martes es el examen de Arqui!! jaja pero se entiende igual
