### ISSUE TITLE
Una señal para múltiples receptores

### ISSUE THREAD

**Issue by lewebe** [IIC2233/syllabus#748]
Hola, si emito una señal, puedo conectarla a más de un método/respuesta? O se recomienda/necesita que exista una señal por cada respuesta que quiero obtener?

**Comment by jbulness** [comment]
Hola @lewebe,

Sí puedes conectar una señal a más de un método o respuesta y no hay problema con que lo hagas, siempre y cuando se muestren las conexiones de las señales, es decir, que quede lo más claro posible lo que hace tu código y como lo hace.

**Comment by lewebe** [comment]
Bacán! Y de manera análoga, puedo conectar un receptor con distintas señales? Es decir, que un método se active con distintas señales?

**Comment by jbulness** [comment]
Eso nunca lo he intentado, pero no veo por qué no podría hacerse. Eso sí, ten mucho cuidado con que pueda colapsar una función si le llegan dos señales que podrían ser contradictorias o algo por el estilo. Te recomiendo buscar ejemplos de esto en Google también. Si tienes muchos problemas no dudes en consultar nuevamente!
