### ISSUE TITLE
Subida a github

### ISSUE THREAD

**Issue by benjamimo1** [IIC2233/Syllabus#748]
Una duda, no vi mi t07 actualizada en mi repo privada, esta bien eso?
Por cuanto la subimos a un subtree es el comportamiento esperado no?
De todos modos copie la carpeta entera y la resubí a la repo privada a modo de respaldarme en caso de que no sea asi.

**Comment by benjamimo1** [comment]
Bueno, de todos modos el bot esta operativo ahora mismo. No se como mas respaldar la entrega de la tarea. Espero esté bien, saludos.

**Comment by Hernan4444** [comment]
cuando pones heroku master en el push solos e sube todo al git de heroku, tienes que hacer el push tradicional (git push) para subir las cosas en tu repo privado.

Saludos

**Comment by benjamimo1** [comment]
Vale! Hice el push en el 0:00 cuando me percaté. Espero no haya problemas :)
