### ISSUE TITLE
Designer, widgets dentro de otro heredan el estilo

### ISSUE THREAD

**Issue by Zenos-Paradox** [IIC2233/syllabus#748]
* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola, estoy intentando hacer el riel con las flechas pero, al tratar de poner una QLabel con la imagen de Flecha asociada, esta aparece como un cuadrado del color de fondo del QWidget padre. Solo la noto, y se que no es simplemente transparente, porque el QFrame en el que está, tiene un borde. A parte de eso, parece estar funcionando bien la relación entre los QWidgets.

incluyo el código que define la imagen de la flecha:

[código]

**Comment by JuaniAndres** [comment]
Hola @Zenos-Paradox 
En primer lugar, trata de evitar poner código en las issues que este muy relacionado con la tarea es mejor que nos trates de explicar en detalle el problema o lo que hiciste. Si entendí bien el problema que tienes es que los widgets dentro de ese widget padre están tomando el mismo estilo del padre o es otro el problema. También si me puedes comentar si estás haciendo el riel con Qt designer o directamente en Python.

**Comment by Zenos-Paradox** [comment]
Hola, puedo borrar el código si es un problema, pensé que era lo suficientemente poco. 
Creo que mi problema es, de hecho, el que entendiste: que lo widgets están heredando el estilo o algo asi. Creé el padre en Qt designer, incluí la flecha en python. Incluyo una foto, 
*la discontinuidad en el borde del rectángulo debería ser una flecha*
![Screenshot (119)](https://user-images.githubusercontent.com/69649197/96665513-7016dc80-132b-11eb-9e1e-5cae28922a7a.png)

**Comment by JuaniAndres** [comment]
Perfecto, una forma de solucionarlo es sobrescribiendo el estilo de todos los elementos dentro de tu rectángulo para que tengan un fondo transparente pero una mejor alternativa es que hoja de estilo de tu QWidget rectángulo especifiques en detalle a quien se le aplicara el fondo. Te voy a mostrar un ejemplo de lo último:

La siguiente ventana tiene el mismo problema tuyo, el botón del centro tiene el mismo fondo de la ventana:
![ventana](https://user-images.githubusercontent.com/48482216/96667279-27f9b900-132f-11eb-8dd0-9d41f047ed26.PNG)

Si hacemos la siguiente modificación al stylesheet se observa lo siguiente:
![ventana2](https://user-images.githubusercontent.com/48482216/96667339-46f84b00-132f-11eb-9748-6ad98266bd89.PNG)

Lo que le agregue al stylesheet de la ventana significa pyqt agrégale el fondo celeste al QWidget con el nombre de objeto "rectangulo" (La notación es ````{Clase}#{nombre_objeto}````) .  Como la ventana es el único QWidget que tiene ese nombre se le aplica solamente a esta el fondo. Así es como luce el Object Inspector de la ventana que te mostré donde puedes ver el tema del nombre: 
![Object](https://user-images.githubusercontent.com/48482216/96667855-3b595400-1330-11eb-905b-0784285bcb37.PNG)

Igual lo que te menciono debería solucionar el problema que tienes con la discontinuidad, pero me parece que la flecha no te está apareciendo por otra razón probablemente los paths de la imagen o la forma en que la agregaste a la label.
Me comentas si te funciona o si algo no se entendió

**Comment by Zenos-Paradox** [comment]
Casi funciona jaja. Ahora la flecha es invisible, quizá lo que dices de un problema del path? pensé que me saldría un error de ser así. Otro problema que surgió ahora es que no puedo cambiar el color de la pantalla en sí, pongo QDialog#Dialog{color}  pero no se aplica.

**Comment by JuaniAndres** [comment]
Genial, respecto a lo segundo si quieres agregarle un fondo quizás deberías modificar lo que pusiste por ````QDialog#Dialog{background-color: color}````. No entendí mucho a que te refieres con tu pregunta "cómo un widget grande de fondo afectaría el layout" quizás me puedes mostrar un ejemplo y que bueno que se te soluciono lo de la flecha lamentablemente si el path es incorrecto, pyqt5 no entrega una alerta sino que simplemente no muestra nada.

**Comment by Zenos-Paradox** [comment]
> No entendí mucho a que te refieres con tu pregunta "cómo un widget grande de fondo afectaría el layout"

Me refería a si el layout se mantendría dentro del widget, pero ya me di cuenta de que sí. 

> Genial, respecto a lo segundo si quieres agregarle un fondo quizás deberías modificar lo que pusiste por `QDialog#Dialog{background-color: color`

Y si, era exactamente eso. Gracias :)
