### ISSUE TITLE
tamaño mensajes

### ISSUE THREAD

**Issue by cmgainza** [IIC2233/Syllabus#748]
Hola, lo que pasa es que cuando envio un mensaje desde el cliente y pido su tamaño, es 62 (le avisa al servidor que va a enviar un mensaje de 62 bytes). Pero cuando el servidor lo recibe y consulto el tamaño del mensaje recibido, es 45 bytes. 
¿Por cuál me debo regir para enviar menos de 1024 bytes?
Entonces si le digo "te voy a enviar 2000 bytes", recibe primero unos pocos y despues un segundo paquete pero sumando el tamaño de ambos no alcanza a sumar 2000. Así, el servidor se queda esperando eternamente que le lleguen 2000 bytes que nunca van a llegar porque ya se envió el mensaje entero.

**Comment by jtagle2** [comment]
@cmgainza, cuando estás enviando o recibiendo bytes, debes asegurarte de pedir como máximo, la cantidad necesaria para no recibir ni un byte más ni menos de los que deberías recibir, por lo que el receive no puede ser de un tamaño fijo. El por qué se origina esta situación y cómo se soluciona se discutió durante la ayudantía de networking, por lo que algunas cosas del código que se subió te podrían ayudar quizás.

Saludos
