### ISSUE TITLE
Duda con el tamaño de los bytes al enviar archivos

### ISSUE THREAD

**Issue by norman123123** [IIC2233/Syllabus#749]
Se tiene que enviar un mensaje con el tamaño del archivo que se enviará despues, pero este tamaño debe ser el tamaño en bytes? o puede ser el numero de chunks que se enviarán? 

La segunda opción me parece mas útil y en el enunciado queda abierto a interpretación.
saludos.

**Comment by ptflores1** [comment]
Hola !
El mensaje previo debe ser la cantidad de bytes que enviaras en el mensaje que se enviará despúes.
Saludos !

**Comment by antoniacobo** [comment]
Hola! Para cuando es un archivo de más de 1024 _bytes_, por ejemplo, 2035 _bytes_, hay que primero mandar un mensaje que diga que voy a mandar un archivo de 2035 _bytes_, luego uno de 1024 _bytes_ y luego otro de 1011 _bytes_ (los restantes)?

**Comment by Hernan4444** [comment]
@antoniacobo asi es 👍 

Saludos ✌️
