### ISSUE TITLE
Al usar setGeometry se corre 25 pixeles 

### ISSUE THREAD

**Issue by diego-ayala-2000** [IIC2233/syllabus#749]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola. 
Tengo un problema al agregar un  widget dentro de otro widget. Al hacerlo y colocarlo en cierta posicion con SetGeometry el widget queda cerca de esa posicion pero no en esa. 
<img width="1101" alt="Captura de Pantalla 2020-10-20 a la(s) 22 12 51" src="https://user-images.githubusercontent.com/69765490/96660969-67b9a400-1321-11eb-9197-2244a24da698.png">

Trato de que quede al medio, pero aunque con setGeometry(x,y,ancho,alto) pongo en x la distancia a la que lo quiero siempre queda 25 pixeles corrido. 

A que se podria deber.

De antemano muchas gracias.

**Comment by danckoo1** [comment]
hola! esta dificil saber el problema a priori, pero estas seguro que el punto de referencia con el cual crees estar trabajando es el correcto?, en este caso la esquina superior izquierda de tu widget parent debería ser el (0, 0).

**Comment by diego-ayala-2000** [comment]
hola! si tome como punto de referencia
<img width="469" alt="Captura de Pantalla 2020-10-21 a la(s) 07 26 38" src="https://user-images.githubusercontent.com/69765490/96707839-c5c0a880-136e-11eb-933e-8151550b8c6c.png">
<img width="260" alt="Captura de Pantalla 2020-10-21 a la(s) 07 26 53" src="https://user-images.githubusercontent.com/69765490/96707874-cf4a1080-136e-11eb-8cc8-e2eb1535e1c3.png">

 ese punto.

**Comment by danckoo1** [comment]
Supongo que el parent es la ventana y el widget que te aparece desplazado es la pista de baile, si ese es el caso lo más probable es que como la estás agregando a un layout el setGeometry no está moviéndola, ya que el layout se esta encargando de posicionarlo, intenta no agregarlo a un layout y dime si te funciona 👀

**Comment by diego-ayala-2000** [comment]
Ahí si me funciono, gracias te pasaste
