### ISSUE TITLE
Problema con el archivo tableros.txt

### ISSUE THREAD

**Issue by ItsSancer** [IIC2233/Syllabus#75]
* [ x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Mi problema es que al leer el archivo tableros.txt para el método reemplazar de la clase tablero, el nombre del primer tablero se lee de la siguiente forma: _ejemplo_chico_sin_soluciÃ³n_ por lo que al intentar llamar al método con el nombre correcto no lo encuentra.

**Comment by Benjeeeh** [comment]
Hola!
Lo más probable es que al leer el archivo no le estés aplicando un _encoding_, y no te está reconociendo las tildes (también afectaría a las ñ). El encoding específico que se necesita al momento de leer un archivo es el utf-8, y debes añadirlo en tu función open().
En la [siguiente documentación](https://docs.python.org/3/library/functions.html#open) puedes revisar todos los parámetros que puede aceptar la función open(). Enfocate en el tercer parámetro que recibe, que es 'encoding='. Ahí debes escribir utf-8.

Avísame si te sirvió!

**Comment by ItsSancer** [comment]
Si, eso lo solucionó. Muchas gracias!
