### ISSUE TITLE
Jupyter y ubuntu...

### ISSUE THREAD

**Issue by Felipehanckes** [IIC2233/Syllabus#75]
cuando trato de abrir jupyter en la consola mediante el comando:
jupyter notebook
la consola me dice: jupyter: 'notebook' is not a jupyter command.

lo otro, me dice que 
super().llamar() #definido en la ayudantía 2
requiere de un argumento para super y no se a cuál se refiere.

**Comment by Felipehanckes** [comment]
Al correr el codigo en python me tira esto

Traceback (most recent call last):
  File "herencia.py", line 30, in <module>
    s.llamar()
  File "herencia.py", line 25, in llamar
    super().llamar()
TypeError: super() takes at least 1 argument (0 given)

**Comment by andresfdezc** [comment]
@Felipehanckes Lo de la ayudantía debería corresponder a otra issue. Sin embargo, ¿a qué ayudantía te refieres?

**Comment by Felipehanckes** [comment]
me equivoque, no es de la ayudantía, es del material de estudio
https://github.com/IIC2233/contenidos/blob/master/semana-2/02-Herencia-Multiherencia.ipynb

**Comment by andresfdezc** [comment]
¿Estás seguro de que estás corriendo el código con python 3? Tu error es típico de python 2.

**Comment by Felipehanckes** [comment]
Ya me lo explicaron jaja era eso
gracias viejo
