### ISSUE TITLE
Duda variables de clase

### ISSUE THREAD

**Issue by BenjaPrograma** [IIC2233/Syllabus#75]
Tengo una duda con la respuesta que aparece en la pauta de un control de semestre anterior.

**1) (3 pts.) Explique brevemente la diferencia entre los atributos `a` y `b` de la clase mostrada a continuación**
```python
class Foo:
    a = 0
    def __init__(self, value):
	self.b = value
	Foo.a += 1

i1 = Foo(5)
i2 = Foo(3)

print(i1.b)
print(i2.b)
print(i2.a)
```

El atributo `a` es un atributo perteneciente a la clase mientras que el atributo `b` es de la instancia. **(1.5 pts)**. Un atributo perteneciente a la clase comparte su valor con todas las instancias de la clase, **si alguna lo modifica su valor, se cambia en todas las instancias también**. El valor de un atributo de la instancia puede variar según la instancia y es propio de ésta. **(1.5 pts)**

Segun lo que tengo entendido, si una instancia cambia el valor de la variable de la clase, se cambia SOLO para esta instancia, por ej i2.a = 5, alteraria el valor solo para i2, pero si hago print(Foo.a) esta no tiene el valor cambiado, entonces no entiendo porque dice que si alguna instancia cambia su valor, se cambia para todas.

Saludos,
Benjamín

EDIT: Edite tu issue para que el código se viera mucho mejor y mas entendible. Atte Hernan4444

**Comment by jtagle2** [comment]
Eso es, porque al hacer i2.a=5, estas creandole un atributo a la instancia, que se llama igual que la variable de la clase. Para ver lo que ocurre con las variables de clase, fíjate en el siguiente código (sabiendo que el atributo `__dict__` de una clase/instancia retorna todos los atributos/funciones de dicha clase.
```python
class A:
    var1 = "ATRIBUTO DE LA CLASE"
    def __init__(self):
        print("El diccionario de mi instancia es: {}".format(self.__dict__))
        print("El diccionario de mi clase es: {}\n\n".format(A.__dict__))
        print("Busco el atributo var1 desde la instancia (self). Como no esta en el __dict__ de la instancia, voy al de la clase y ahi lo encuentro, por lo que entrego ese:")
        print("{}\n\n".format(self.var1))
        self.var1 = "Creo que le cambie el valor al atributo de la clase, pero en verdad python le agrego un atributo nuevo a mi instancia "
        print("CHEQUEANDO LOS __dict__ DE AMBOS")
        print("__dict__ instancia: {}".format(self.__dict__))
        print("__dict__ clase: {}".format(A.__dict__))
        print("\n\nAhora busco el atributo var1 desde la instancia (self), y lo encuentro ahi mismo, por lo que dejo de buscar y no voy a las variables de la clase")
        print("{}\n\n".format(self.var1))
        print("Y veo que efectivamente... la variable de la clase no cambio:")
        print(A.var1)

A()
```
Ahora, el funcionamiento es el siguiente: Si una instancia llama a un atributo, lo primero que hará será buscar en su propio __dict__. En caso de no encontrarlo, irá a buscar al __dict__ de su clase. Si está ahí, retornará eso, si no, tira el clásico error _\* has no attribute \*_ (dejemos de lado la herencia, pero si hubiera, después va a buscar a las clases padre).
Ahora, el cambio de atributos (recién respondiendo tu pregunta jajaja), es un poco distinto. Al modificar un atributo, se modifica el \_\_dict\_\_ (lógico) del objeto desde donde llamé al atributo. Luego, si yo hago `instancia.atributo = 5`, se modifica el \_\_dict\_\_ de la instancia, pero si yo hago `Clase.atributo = 5`, se modifica el \_\_dict\_\_ de la clase.
Espero se entienda, cualquier cosa no dudes en preguntar
Saludos!
