### ISSUE TITLE
Si usuario pierde, se guarda o no

### ISSUE THREAD

**Issue by adbakulic** [IIC2233/syllabus#75]
Hola!
Si un usuario, por ejemplo juan, comienza una partida y en un instante guarda y sigue jugando. Si luego pierde, la idea es que pueda cargar el archivo que guardó anteriormente para volver a jugar desde donde quedó antes de perder, o se debe eliminar el archivo de este usuario dado a que perdió y debe iniciar una nueva partida?
Gracias!

**Comment by jeschuwirth** [comment]
Hola!

En el enunciado no se especifica si los archivos guardados se deben borrar al terminar la partida o no, por lo que queda a criterio del alumno. Te recomiendo hacer que no se borren para que el corrector pueda usar la misma "savefile" durante la corrección y que no tenga que jugar constantemente desde 0.

Suerte!
