### ISSUE TITLE
problema con #comentarios con tilde

### ISSUE THREAD

**Issue by cristobal-larach** [IIC2233/syllabus#75]
Hola, VScode no me está corriendo las funciones de la actividad 00, pero si borro los comentarios que venían en el código (específicamente los con tilde) si corre. Alguna configuración que deba mover?

**Comment by dfloreaa** [comment]
No se si te sirva de algo, pero abajo en VSCode, fijate de que estes codificando con UTF-8
![image](https://user-images.githubusercontent.com/62019645/90833625-703c3100-e316-11ea-9db9-941145532d48.png)

**Comment by cristobal-larach** [comment]
Había bajado una extensión para VSC que ejecutaba con una versión anterior de python, ya está solucionado. Muchísimas gracias igual!
