### ISSUE TITLE
Consulta añadir contactos [4.2.1.2]

### ISSUE THREAD

**Issue by alvarocisternas** [IIC2233/syllabus#75]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

En la parte de **añadir contactos [4.2.1.2]** me queda claro que se debe añadir el contacto en el bulit-in que yo haya estimado si cumple con las reglas, lo que no me queda claro es si se debe realizar una modificación del archivo **contactos.csv** agregando el nuevo contacto.

**Comment by matiasmasjuan** [comment]
Hola @alvarocisternas !

De acuerdo a lo señalado en el enunciado:

![screen_flujo](https://user-images.githubusercontent.com/48495638/112735471-0b3f5e00-8f2b-11eb-859a-36d3d96eb836.png)

Por lo tanto, todas las acciones realizadas deben quedar **registradas** en los archivos correspondientes. Esto incluye modificar el archivo ```usuarios.csv``` al crear un nuevo usuario, modificar el archivo ```contactos.csv``` al agregar un nuevo contacto, modificar el archivo ```grupos.csv``` al crear un grupo o cuando un usuario abandona un grupo, modificar el archivo ```mensajes.csv``` cuando un usuario emite un mensaje a otro usuario a un grupo, etc.

Espero haber respondido a tu pregunta, y mucho éxito con la tarea! :smile:

**Comment by alvarocisternas** [comment]
muchas gracias !!
