### ISSUE TITLE
Cambio del contenido de una variable tras pasar una condición

### ISSUE THREAD

**Issue by Stomicicp** [IIC2233/Syllabus#75]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido
Hola, en mi código definí una variable que quiero que se actualice luego de pasar por una condición, pero no lo hace y no se por qué pasa eso. Cuando llamo a la variable en otro punto del código, se utiliza el valor asignado originalmente e ignora el cambio que se le hizo en la condición (la cual sí se cumple).

Cuando voy a ver el error de la variable sale **"variable" is not accessed**

**Comment by Emiliax16** [comment]
Hola @Stomicicp . Me da la impresión que la condición por la que pasa la variable está dentro de una función.  Si tienes algo del estilo:

`x = 3`

`def suma(x):`
    `   .. x += 5`
    `   .. print(x)`
    
`suma(x)  #Esto imprime 8`

`print(x)  #Esto imprime 3`

Si efectivamente la condición está dentro de una función, el valor de la variable sólo es modificado dentro de la misma función. Si tratas de usarlo fuera de ella, sigue manteniendo su valor original, pues la variable original no ha sido modificada. Avísame si se entiende. Saludos 😄

**Comment by Stomicicp** [comment]
Si, es eso mismo. Existe alguna forma de que la función cambie el valor de la variable de afuera?

**Comment by Emiliax16** [comment]
Hay maneras de hacerlo que requieren unos pasos extras, como usar clases o hacer que la función retorne el valor y re-asignarlo a la variable. 

**Solución rápida**: Una manera directa sería definir una variable global, ya que esas variables si pueden ser modificadas por funciones, **PERO** su uso en este ramo implica descuento (revisar distribución de puntaje, sección: descuentos). 😞
