### ISSUE TITLE
Mi avance funciona cuando quiere

### ISSUE THREAD

**Issue by Gsalinas1506** [IIC2233/syllabus#750]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Estoy intentado trabajar en el avance y de vez en cuando logro que la flecha baje por la ventana. Digo **de vez en cuando** porque hay veces que ejecuto el programa y la consola me arroja el mensaje de `QThread: Destroyed while thread is still running`. Otras veces, la flecha baja por la pantalla con total normalidad. A que se puede deber?

**Comment by danckoo1** [comment]
Dado el error que mencionas, el problema radica en que la variable en que guardas el thread se borra ,o remplaza por algo mas,  antes de que el thread termine de ejecutarse por completo. Quizas si haces un push a tu repositorio para ver el codigo podría indicarte de mejor manera por donde va tu problema 👍

**Comment by Gsalinas1506** [comment]
Hola, acabo de hacer push a mi repositorio, gracias

**Comment by danckoo1** [comment]
Efectivamente ocurre que la variable se destruye antes de que el thread acabe. Lo que te recomiendo hacer por la forma en que lo estas modelando, es que crees un atributo en tu ventana que sea tipo lista, luego cada vez que creas una flecha la apendeas a la lista, y dado que esta es un atributo de la clase nunca se va a destruir y podrá finalizar correctamente. 
Avísame si te funciona!

**Comment by Gsalinas1506** [comment]
Hice lo que me dijiste de agregar a una lista la flecha que se genera, sin embargo la flecha ahora baja a tirones (derrepente acelera y otras veces frena), osea, no va fluido...

pd: a que te refieres cuando dices que la variable de "destruye" antes de que el thread acabe? ¿Y porqué se acaba? si el `run()` nunca deja de funcionar a nivel de método?

**Comment by danckoo1** [comment]
si te fijas en el metodo creador_flecha de tu ventana, este crea un thread y lo almacena en una variable llamada flecha, pero esta variable solo existe dentro del scope del metodo, por lo que apenas llegues al final de este metodo la variable deja desaparece, que era a lo que me referia con que se destruye

**Comment by Gsalinas1506** [comment]
No había cambiado nada, pero le aumente el tiempo que demoraba la flecha en bajar  y ahi empezó a correr fluido... a lo mejor es algo de mi computador... gracias !!

**Comment by kalarconvl** [comment]
Hola!! Recién me empezó a pasar lo mismo ni idea por qué y si tengo la lista que guarda los QThreads
