### ISSUE TITLE
Ayudantía Examen

### ISSUE THREAD

**Issue by acrojas2** [IIC2233/Syllabus#750]
Hola! 
Con respecto a la ayudantía de este viernes:¿ Podrían informar el horario, sala y temas a tratar?.¿Harán un solo modulo de ayudantía?
Saludos!

**Comment by indonoso** [comment]
Según el mail del 16 de junio

> Estimados,
>En el siguiente formulario podrán sugerir el horario y los temas a repasar en la Ayudantía para el Examen que se realizará el Viernes 30 de Junio: https://goo.gl/forms/DKyR8hvKhDpbWzas2 (https://goo.gl/forms/DKyR8hvKhDpbWzas2)
>Recibiremos respuestas hasta las **21:00 hrs. del día Miércoles 28 de Junio.** Pueden contestar ahora y editar sus respuestas más adelante por si con su estudio cambian los temas que quieran repasar.
>Adicionalmente, les aviso que no habrá ayudantía este Martes 20 de Junio.
>Saludos.
>Andrés

**Comment by acrojas2** [comment]
Hola! 
Me refería a los resultados de ese form.
Saludos!

**Comment by jtagle2** [comment]
@acrojas2,
@indonoso te puso en negrita la razón de por qué aun no se ha informado nada. La encuesta para ver el horario y los contenidos de la ayudantía aún no se cierra (Cierra hoy a las 21:00).
Saludos!

**Comment by acrojas2** [comment]
Hola!
No lo había notado, gracias por la respuesta.
Saludos!
