### ISSUE TITLE
Assets del cliente

### ISSUE THREAD

**Issue by behrmann97** [IIC2233/Syllabus#750]
Para la interfaz, ¿puedo hacer que el cliente tenga que tener una carpeta de assets descargada? De esta manera puedo utilizar imagenes para distintos botones y fondos de la interfaz sin tener que mandarselas a través del servidor, ya que esto último se demora mucho (estas imagenes NO son las que se editan).

**Comment by sebacruzd** [comment]
Hola, si puedes 😁
