### ISSUE TITLE
Duda Lectura_paths_2016-1.pdf

### ISSUE THREAD

**Issue by Dunkan1** [IIC2233/Syllabus#751]
Tengo una duda con el siguiente ejercicio

![captura de pantalla de 2017-06-30 23-40-16](https://user-images.githubusercontent.com/26102365/27758876-b7648250-5ded-11e7-8c52-2def4de4d1a8.png)
lo que pasa es que segun yo '.' en verdad no hace nada ya que solo hace referencia al directorio actual
asi que en el ejercicio no deberian ser invalidas tanto A como D?
![captura de pantalla de 2017-06-30 23-40-54](https://user-images.githubusercontent.com/26102365/27758890-f2d8028a-5ded-11e7-9efa-14754df33b2c.png)

**Comment by andresfdezc** [comment]
Hola,

Disculpa por la tardanza. Efectivamente en a) `.` hace referencia al directorio en el que ya se está y en ese path largo no debería afectar. Por lo menos yo también creo que no es válido y no veo cómo podría llegar a `Cancer Man.avi` si lo único que hace es retroceder. 

Saludos.

**Comment by Dunkan1** [comment]
buena, gracias :smile:
