### ISSUE TITLE
Pasos multiples con flechas especiales

### ISSUE THREAD

**Issue by JoMarchant** [IIC2233/syllabus#751]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

En el enunciado se habla de que existen pasos combinados dependiendo de la dificultad, pero también se habla sobre distintos tipos de flecha con distintas velocidades de caída.

**Si es un paso combinado, ¿deben todas las flechas ser del mismo tipo para que se mantengan siempre a la misma altura?**

**Comment by jaimecoloma** [comment]
Hola @JoMarchant, como esto no quedó especificado en el enunciado queda a tu criterio como hacerlo pero debes especificarlo en el readme, podrías verificar la velocidad a la que va al momento que cruzan la zona de baile o bien ver cuantas flechas están al mismo tiempo en la zona de baile (u otra forma de implementarlo si tienes).
Mucho éxito!
