### ISSUE TITLE
Tiempo Calculo Ediciones - Tiempo reaccion editor

### ISSUE THREAD

**Issue by B-Dominguez** [IIC2233/Syllabus#751]
Hola,

Llevo mucho tiempo tratando de bajar el tiempo en que se realiza una edición desde que se ordena. Ahora que no he podido seguir bajando el tiempo, me pregunto si es realmente necesario.
Es un problema si la reaccion del programa a una orden de edición es un poco lenta (sobre todo para blurry, y también un poco para algunos casos de balde)? 
Como referencia, hacer un blurry de Mickey Mouse se demora aprox 8 segundos

Muchas Graciaas

**Comment by iqacevedo** [comment]
Hola, 

Mientras sean tiempos aceptables está bien, cercano a un minuto estaría mal. De todas maneras, se espera que la interfaz no se quede pegada mientras se aplican los cambios, cuando se haga uno debería poder seguir haciendo otras cosas como seleccionar botones, recortes, (todo).

Saludos !
