### ISSUE TITLE
Error "ModuleNotFoundError: No module named 'files_rc'" 

### ISSUE THREAD

**Issue by tomytable** [IIC2233/syllabus#752]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda:

Hola, al intentar abrir un archivo .ui desde python me aparece el error "ModuleNotFoundError: No module named 'files_rc'". Estoy bastante seguro que tengo bien instalado QT Designer porque puedo editar ventanas en este y puedo correr los códigos que vienen como ejemplo en los contenidos de la semana y no sé a que puede deberse. 

Busqué en internet el mismo error pero no la verdad no entiendo las soluciones que dan ni a que se debe

**Comment by aaossa** [comment]
Hola @tomytable , ¿podrías subir el archivo a tu repo para darle una mirada? Hay un problema similar que ocurre a veces que requiere "transformar" el archivo, entonces quiero verlo bien para ver si es lo mismo 🤔 ¡Gracias!

**Comment by JoaquinVilla** [comment]
Hola, tengo el mismo el problema. Se sabe algo?

**Comment by aaossa** [comment]
@JoaquinVilla lo mismo que puse 😅 ¿Podrías subir el archivo a tu repo y avisar cuando lo hagas?

**Comment by JoaquinVilla** [comment]
Listo! @aaossa

**Comment by aaossa** [comment]
Hola @JoaquinVilla , creo que ya pillé lo que puede ser. Cuando agregas una imagen en Qt Designer, crea un archivo con esos recursos. El tema es que Python no puede acceder a esos recursos directamente (no basta con los archivos *.ui o *.qrc), sino que tienes que transformarlos con un comando:

```
# archivo_rc.py es el archivo que vamos a generar, el que busca Python
# archivo.qrc es el archivo que ya tienes, que quieres transformar
pyrcc5 -o archivo_rc.py archivo.qrc

# Fuente: https://stackoverflow.com/a/55972951
```

Esto te va a generar un nuevo archivo (`archivo_rc.py`), que es el que Python necesita para poder acceder a los recursos que colocaste en Qt Designer. Ojo con ponerle el mismo nombre (`archivo.qrc` pasa a ser `archivo_rc.py`, `mi_ventana.qrc` pasa a ser `mi_ventana_rc.py`, etc.), para que Python pueda acceder directamente. 

En tu caso @JoaquinVilla , tuve que usar el comando dos veces (una por cada *.qrc) y me funcionó bien 👌 Ojalá te funcione, así que avisame si te funciona o si no te funciona 👀 ¡Éxito con la T02!

**Comment by JoaquinVilla** [comment]
Ahí me funcionó. Gracias!

**Comment by amorande1** [comment]
Hola! Tuve el mismo problema, pero al intentar utilizar el comando me tira un SyntaxError apuntando a la 'c' de 'archivo_rc.py'. ¿Se les ocurre cómo solucionarlo?

**Comment by aaossa** [comment]
@amorande1 fijate bien dónde ocurre el `SyntaxError`, probablemente sea algo que viene de antes de la definición del *string* que mencionas 🤔

**Comment by amorande1** [comment]
Quizás estoy ubicando mal el comando 'pyrcc5 -o archivo_rc.py archivo.qrc'. ¿Dónde debería ir?

**Comment by aaossa** [comment]
@amorande1 tienes que ejecutarlo en la consola, no colocarlo en tu código de Python. También recuerda reemplazar "archivo" por el nombre de tu archivo 👌

**Comment by amorande1** [comment]
Ejecutándolo en consola me está devolviendo: File does not exist 'logo.qrc' 
Cabe destacar que ese archivo está en la carpeta sprites. ¿Se te ocurre cómo solucionarlo?

**Comment by aaossa** [comment]
Tienes que moverte con la consola a la misma carpeta en la que se encuentra el archivo, sino el comando no tiene cómo encontrarlo.

**Comment by Zenos-Paradox** [comment]
@aaossa Hola! tengo el mismo problema, pero no me funcionó ejecutar el comando :(
en la carpeta veo mi  `archivo_rc.py` y `archivo.qrc`, pero al ejecutar no los encuentra.

**Comment by aaossa** [comment]
@Zenos-Paradox puedes mostrarme una captura ejecutando el comando?

**Comment by Zenos-Paradox** [comment]
Al tiro

**Comment by Zenos-Paradox** [comment]
![Screenshot (118)](https://user-images.githubusercontent.com/69649197/97753106-0093b080-1ad4-11eb-8c40-f99bc5d8c38e.png)

**Comment by Zenos-Paradox** [comment]
no, espera

**Comment by Zenos-Paradox** [comment]
![Screenshot (121)](https://user-images.githubusercontent.com/69649197/97753192-215c0600-1ad4-11eb-951b-584edd034eca.png)
 subí uno antiguo sin querer

**Comment by aaossa** [comment]
El comando no muestra ningún error, o sea que logró la conversión 🤔 Prueba eliminado el archivo `fondos_rc.py` para crearlo nuevamente con el comando

**Comment by Zenos-Paradox** [comment]
Creo que ya lo solucioné: Los archivos `*.ui` , `*.qrc` y `*_rc.py` estában dentro de una carpeta; moví `*.qrc` y `*_rc.py` a la carpeta del `main.py` y ahora parece funcionar.
