### ISSUE TITLE
Problemas al cargar sprite, se corta la imagen

### ISSUE THREAD

**Issue by lewebe** [IIC2233/syllabus#752]
Hola, cargando los sprites segun el archivo ```mapa.csv``` me encuentro con que todas las sprites cargan correctamente excepto la del chef. Estoy usando la misma manera de cargar para todos, que es de la forma ``` qlabel.setPixmap(QPixmap(PATH_SPRITE).scaled(dim_x_sprite, dim_y_sprite))```.
Las dimensiones que tengo seteadas para el chef son exactamente del mismo tamaño que la imagen original (59x69, y como se puede puede observar, el código funciona bien para las otras sprites. No estoy seguro cuál es el problema.
![image](https://user-images.githubusercontent.com/62037289/82401749-a7a1f580-9a28-11ea-8559-c4688553caf1.png)

**Comment by lily416** [comment]
Hola @lewebe 

Intenta cambiar las dimensiones del _label_ que contiene la imagen, específicamente el alto, ya que probablemente es la causa de que se corte la imagen.

Avísame si te resulta o si sigues teniendo problemas después de cambiar las dimensiones del _label_.
Saludos y éxito en la tarea 👋🍫

**Comment by lewebe** [comment]
Hola, gracias por responder! Hay algo que no me queda claro.
* El método .scaled no ajusta mi _label_ a las dimensiones que le entrego? Qué es lo que hace entonces? 
* Cuál es el tamaño por defecto al crear un _label_ nuevo? 

Asumí que cada _label_ que creo es por defecto de un tamaño menor a cualquiera de mis sprites, y con .scaled modifico tanto el tamaño de mi _label_ como el _QPixmap_ que contiene

**Comment by Camila-sty** [comment]
Hola! @lewebe , una consulta, cargaste tus ```sprites``` de chef,mesa y mesero con las posiciones X,Y entregadas en ```mapa.csv``` ? o las tuviste que cambiar para que quedarán así como muestras arriba?

**Comment by lily416** [comment]
@lewebe para responder tus dudas me voy a apoyar un poco en la documentación de los [`QLabels`](https://doc.qt.io/qt-5/qlabel.html), [`QFrames`](https://doc.qt.io/qt-5/qframe.html), [`QWidgets`](https://doc.qt.io/qt-5/qwidget.html) y las [`QImages`](https://doc.qt.io/qt-5/qimage.html), donde se explican con detalle los métodos que tiene cada clase.

* El método `scaled` pertenece a la clase `QImage` y se encarga de escalar la imagen que cargas. 
En el caso de los _labels_ y sus clases padre y abuelo (`QFrame `y `QWidget` respectivamente) ninguno contiene el método `scaled`, por lo que para ajustar su tamaño tienes que usar `setGeometry` o algún otro método que te permita cambiar el alto y ancho.

   Me llama la atención que hayas podido utilizar `scaled` en los _labels_ ya que no aparece dentro de la documentación de las clases relacionadas con los _labels_. 🤔 

* Sobre el tamaño por defecto de los _labels_, según está [página](https://myprogrammingnotes.com/size-qt-widgets-determined.html) es de (5,13).



Trata de darle una vuelta a lo que te comente y si sigues con dudas con gusto te responderé. 😉 
Saludos 👋🥞

**Comment by lewebe** [comment]
> Hola! @lewebe , una consulta, cargaste tus `sprites` de chef,mesa y mesero con las posiciones X,Y entregadas en `mapa.csv` ? o las tuviste que cambiar para que quedarán así como muestras arriba?

Hola! Disculpa la demora, cargué mis sprites sumando las posiciones X,Y del archivo `mapa.csv` con la posición X, Y del punto de origen que yo definí, ubicado donde comienza el suelo pegado al árbol superior izquierdo del mapa

**Comment by lewebe** [comment]
@lily416 Perfecto, me queda muy claro! Lo de scaled lo saqué de la ayudantía 8. Ya arreglé el tamaño de las _labels_ y funcionó bien. Gracias queen 👸  🙌

**Comment by Camila-sty** [comment]
@lewebe Gracias.
Sabes que ahora tengo el mismo problema que tú, pero me pasó con todos los sprites, y utilicé este código para mostrar las imágenes:
```sprite = QLabel(self)```
```sprite.setPixmap(QPixmap(ruta_sprite).scaled(30, 40))```
Lo que me sucede es que la imagen se corta para un determinado valor de X,Y, pero para valores chicos de X,Y no sucede esto, y me gustaría agrandar los sprites ya que se ven muy chicos si lo dejo con valores chicos de X,Y. Entonces, al intentar con números más grandes, los sprites salen cortados, cómo fue que lo solucionaste?
No entendí mucho la explicación de @lily416 , ya que no entiendo que es lo que hay que ajustar...
