### ISSUE TITLE
Mostrar imagen en interfaz SIN descargarla al PC

### ISSUE THREAD

**Issue by vixolo** [IIC2233/Syllabus#752]
Hola! Estoy intentando mostrar imágenes que recibió del cliente en la interfaz del cliente, y no he logrado hacerlo. Sé que los bytes están llegando íntegros al cliente porque puedo guardarlos en un archivo y leer la imagen perfecto con algún programa como el Visor de Imagenes, pero no logro mostrar esos bytes en un label en la interfaz.

Probé usando self.mi_label.setPixmap(QPixmap().loadFromData(los_bytes)), pero se cae Python y no sirve. Si la descargo y hago self.mi_label.setPixmap(QPixmap("imagen_descargada.png")) ahí funciona.

Alguna ayudita?

Muchas gracias,
Vicente.

**Comment by ifcarrera** [comment]
Hola! En Python existen maneras de “emular” un archivo, es decir, hacerle creer a tu función que está recibiendo un archivo pero que en realidad no lo tienes descargado en tu computador, podrías averiguar sobre eso. 
Otra opción posible sería crear carpetas temporales para cargar las imágenes y borrarlas luego de eso.
Espero que te sirva, saludos :D

**Comment by gkschuit** [comment]
Hola! Usando self.mi_label.setPixmap(QPixmap().loadFromData(los_bytes)) el programa se cae porque QPixmap().loadFromData(los_bytes) no retorna un pixmap, sino True. Prueba con:
pixmap = QPixmap()
pixmap.loadFromData(los_bytes)
self.mi_label.setPixmap(pixmap)
Espero te funcione, saludos ;)

**Comment by vixolo** [comment]
@ifcarrera Finalmente la modificación en como usar el loadFromData lo solucionó, pero gracias de todas formas!
@gkschuit Muchísimas gracias!! Precisamente era ese el error, ahí se solucionó. Te pasaste!

Saludos!
