### ISSUE TITLE
Uso del método recv()

### ISSUE THREAD

**Issue by mjgutierrez1** [IIC2233/Syllabus#753]
En el material de la semana 14, en la sección "Ejemplo Práctico: Servidor con manejo de múltiples clientes en forma concurrente", se muestra un ejemplo en que al recibir datos se leen los cuatro primeros bytes que representan el largo del mensaje, y después se reciben datos de 256 bytes hasta que el mensaje llegue al largo correspondiente.

Me quedan una duda:
- Por qué razón se hace:

          while len(response) < response_length:
                response += self.socket_cliente.recv(256)

Si en la variable response_bytes_length guardé el largo del mensaje que recibiré, ¿No bastaría con hacer response += self.socket_cliente.recv(response_bytes_length)?

**Comment by jtagle2** [comment]
No, no bastaría con eso. El parámetro que recibe el método  `recv ` es el número máximo de bytes que permite sacar al método. El funcionamiento del método es algo así como lo que sigue:

1.- Se hace `recv(n)`, y al socket no le había llegado nada todavía, entonces el programa se queda esperando a recibir algo.
2.- Se hace `recv(n)`, y al socket ya le habían llegado `k`bytes, (con k un número menor a n). En este caso, el método queda feliz con los que recibió, y solo se lleva esos k bytes.
3.- Se hace `recv(n)` y al socket le habían llegado exactamente n bytes. En este caso, el método se comportaría como dices tu. El problema, es que la probabilidad de que pase esto en su tarea es cercana a cero por varias cosas (la rapidez de transferencia no es infinita, se están enviando muchas cosas de manera simultánea, entre otras cosas).
4.- Se hace `recv(n)` y al socket le habían llegado más de n bytes. En este caso, el `recv` saca los n bytes que le dijimos, y los otros quedarán esperando a que llegue un nuevo receive.

Luego, al ir recibiendo los datos no podemos hacerlo siempre de un número fijo, porque no podemos asumir que el método `recv(n)` va a recibir exactamente la cantidad de bytes que le damos como parámetro.
**hint para tu tarea** El código que muestras ahí, no sirve 100% para la tarea, puedes debes tener presente que cada vez que llames a receive, debes recibir a lo más la cantidad de bytes que te faltan por recibir. De lo contrario, podrías mezclar dos paquetes de información que no tienen nada que ver entre ellos.
Espero te aclare tu duda, cualquier cosa no dudes en preguntar.]
Saludos! Y éxito con el fin de semestre.
