### ISSUE TITLE
De que sirve .setGeometry(Qrect())?

### ISSUE THREAD

**Issue by Gsalinas1506** [IIC2233/syllabus#753]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

He visto que en algunas partes de los contenidos para el `set.Geomtry()` de algunos widget se les da como argumento un `QRect`. ¿Cual es la diferencia entre darle como argumento este objeto, en vez de las coordenadas normales como aparecen en los contenidos 1 de la semana 9 (dando el vertice, ancho y alto)?

**Comment by bvasquezm** [comment]
Holaa @Gsalinas1506!

En términos de “diferencia” no hay distinciones notables, pero el detalle está en que puedes sacar provecho de los atributos de algunos de tus ``QWidgets`` para agilizar y/o facilitar el proceso. Particularmente estos objetos tienen el atributo ``rect`` que les entrega un objeto ``QRect`` con las dimensiones del widget, creo que entiendes por dónde va la cosa 🙃. En todo caso reitero, estos no tiene mayores diferencias más allá de la comodidad u otros objetivos más ambiciosos que pueden requerir de funcionalidades más avanzadas. Saludos!
