### ISSUE TITLE
cargar objetos dentro del mapa

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#753]
Holaaa!
Esto va para los ayudantes y/o para mis compañeros que puedan ayudarme.
Resulta que cree mi ventana de juego, con el mapa obviamente incluido, mi problema es que no sé como agregar los objetos contenidos en ```mapa.csv```  a mi mapa (dentro del límite LARGO_MAPA y ANCHO_MAPA). En la materia del curso he estado buscando algo similar, pero no lo encuentro, además creo que en la última ayudantía (hoy) se vio un poco eso, pero no he podido entender cómo lo hacen. Me pueden dar una idea de dónde podría aprenderlo y así aplicarlo a mi ventana? Me refiero exactamente a poner un objeto dentro de mi mapa con las posicione declaradas en el archivo  ```mapa.csv```. 
pd: He buscado en internet, pero creo que no sé buscar, entonces también me gustaría que me recomendaran la forma de buscar esto..

**Comment by fdoflorenzano** [comment]
Hola @Camila-sty,

No estoy completamente seguro si entendí bien, pero me parece preguntas como posicionar elementos en un sistema coordenado. Para eso, tal vez te será de ayuda el método `move` que `QWidget`. Si te fijas en el [segundo cuaderno de la semana 9](https://github.com/IIC2233/contenidos/blob/master/semana-09/2-elementos-gr%C3%A1ficos-b%C3%A1sicos.ipynb), en el segundo ejemplo del cuaderno, que habla de etiquetas y cuadros de texto, hay un ejemplo donde se usa ese método. Si es el caso, te recomiendo probar eso, cambiar los argumentos al usar `move` para ver que pasa en la ventana. Puedes intentar combinar eso con _labels_ con imágenes a su vez.

También, en Canvas se subió una nueva página al final del módulo de la semana 9 con más videos respondiendo dudas, donde uno habla sobre *widgets* y el sistema coordenado, que te puede ser de ayuda.

Si esto no responde tu duda, puedes responder y aclararla e intentamos de nuevo.

¡Saludos!

**Comment by Camila-sty** [comment]
Gracias, lo voy a ver! :+1:
