### ISSUE TITLE
Recorreción T06

### ISSUE THREAD

**Issue by Nicolasvegam** [IIC2233/Syllabus#753]
Hola quería preguntar el por qué de la recorreción presencial, además me recalcar que me parece extraña la cantidad de rojos de qué hay, yo termine toda la tarea y apenas alcance un 2, me parece bastante extraño. Por último, me gustaría saber cuándo estará disponible el feed back de la tarea, 
Gracias

**Comment by Hernan4444** [comment]
@Nicolasvegam los feedback estarán durante la tarde. A modo general hubo muchas tareas que no corrían en nuestro computador y por lo mismo tienen un 1.0 pero solicitando que se pruebe su tarea en su computador. Sobre la recorreccion presencial, esto es porque el tiempo no da para que respondan un formulario y nosotros los revisemos antes de la fecha tope, por eso es mas fácil para ustedes como para nosotros realizar esa recorreccion presencial de la T06 y T07.

Saludos

**Comment by Dunkan1** [comment]
Cuando suben las notas de la T07?

**Comment by maxjosecr** [comment]
Dado que son al rededor de 60 1's en la tarea 6, no puede haber otra instancia para recorregir? ya que habrá que revisar desde 0 muchas tareas, y quizás no alcance el tiempo para corregir otras cosas.

**Comment by iqacevedo** [comment]
@maxjosecr como la recorreccion es presencial, se realiza mucho más rápido que corregir una tarea normal, ya que nos pueden explicar los problemas de su código directamente. No te preocupes por el tiempo, este será suficiente para corregir todo. No tenedremos otra instancia para corregir ya que estamos en fin de semestre.

Saludos !

**Comment by negutierrez** [comment]
Hay posibilidad de recorregir otro dia? No se si sea el único, pero no voy a estar el 6, por lo que necesito agendar para antes

**Comment by Hernan4444** [comment]
@negutierrez , los ayudantes todavía tenemos corregir la T07 y los examenes, es por ello que para evitar tantas instancias de recorreccion, se realizará el día 6 para todo. Si no puedes asistir, puedes mandar a otra persona en tu lugar.
Saludos!!

**Comment by negutierrez** [comment]
@Hernan4444 Tal vez el mismo día del examen podría hacerse? Todavía tengo que re-corregir la tarea 5 por lo mismo, y creo que enviar a otra persona a explicar mi tarea tal vez no sea lo mejor...
Honestamente no entiendo por qué se espera hasta cierto día para mandar todos los feedbacks, me parece que sería mucho más óptimo comunicarse al tiro cuando haya algún error en una tarea, y así coordinar 1 a 1 más fácilmente

**Comment by indonoso** [comment]
La recorrección de tareas, examen y actividades que corresponda se hará el día 6 de julio desde las 14hrs hasta las 18hrs. Si no pueden ir, pueden mandar a alguien en su lugar (compañero, hermano, abuelita, etc). **No hay** otra instancia para recorregir.
