### ISSUE TITLE
Duda: Cuadro de notas

### ISSUE THREAD

**Issue by jtcaraball** [IIC2233/Syllabus#753]
Hola, tengo una duda sobre las notas que el cliente puede ingresar. En la sección del trabajo de archivos midi la tabla de notas con la que trabajamos contiene a las notas: 
C, C#, D, D#, E, F, F#, G, G#, A, A#, B,   y 11 octavas del 0 al 10.
mientras que en la sección 5.2.1 el cuadro 1 nos da el formato de las notas:
C, C#, D, Eb, F, F#, G, G#, A, Bb, B
cual usamos? D:

Gracias!

**Comment by mfanselmo1** [comment]
Mira [702](https://github.com/IIC2233/Syllabus/issues/702)
