### ISSUE TITLE
Seccion de comentarios

### ISSUE THREAD

**Issue by ptflores1** [IIC2233/Syllabus#754]
Hola ! En el enunciado en la sección 6 dice:

> Al ingresar a la sección de comentarios, se muestran todos los comentarios...

Esta sección es una diferente a la de edición, es decir, una exclusiva para comentarios? o se refiere a la misma ventana de edición? Gracias !

**Comment by Arcoirisky** [comment]
Hola~ Se supone que debe ser en la misma ventana de edición pero, si lo haces en otra exclusiva, estaría bien de todas formas :D
