### ISSUE TITLE
LARGO_MAPA y ANCHO_MAPA

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#754]
Hola, me confundí y quisiera que me aclararán si el LARGO_MAPA corresponde al eje "x" y ANCHO_MAPA corresponde al eje "y" ?

**Comment by kadroguett** [comment]
Hola @Camila-sty 
En la imagen puedes ver los parámetros con sus respectivos ejes.
![alto y ancho](https://user-images.githubusercontent.com/31357861/82405413-d4a6d600-9a31-11ea-9cfa-0dcc3c790f5d.jpg)

**Comment by kadroguett** [comment]
Hola @Camila-sty 
Lo siento por borrar la respuesta anterior, había escrito mal el eje y. En la imagen puedes ver los parámetros con sus respectivos ejes.
![alto y ancho](https://user-images.githubusercontent.com/31357861/82405643-834b1680-9a32-11ea-99af-486a6525ae8e.jpg)

**Comment by Camila-sty** [comment]
Gracias!

**Comment by kadroguett** [comment]
De nada, éxito en tu tarea!!

**Comment by Camila-sty** [comment]
Hola, 
Qué pasa si LARGO_MAPA y ANCHO_MAPA son modificados por un ayudante mediante la revisión de la tarea. El mapa debe adaptarse a este cambio¿?.
Porque yo definí estos valores, y de acuerdo a esto empecé a ver cuales iban hacer los limites del mapa (pero no lo veo a nivel de código, es algo que yo consideré aparte sin escribirlo en código) .
Entonces si fuese así, de que cambian el tamaño del mapa, debe hacer bastantes cambios en el código y me gustaría saber esto luego :D
Gracias
