### ISSUE TITLE
Commit equivocado en la corrección de mi T06

### ISSUE THREAD

**Issue by diegonavarrovergara** [IIC2233/Syllabus#754]
Hola, hubo un error en el commit que me revisaron.

El problema es que me dieron más tiempo para entregar la tarea, hasta el sábado, pero me revisaron el commit que subí el lunes anterior.

Me gustaría saber si es posible que vuelvan a revisar mi tarea sin tener que ir a la recorrección presencial.

Gracias.

**Comment by FernandoPieressa** [comment]
Hola!

Para casos personales como este tienes que utilizar el formulario de contacto que puedes encontrar en https://iic2233.github.io/contacto/

Saludos!
