### ISSUE TITLE
agregar canciones

### ISSUE THREAD

**Issue by gtquiroga** [IIC2233/Syllabus#754]
En el programa la unica forma de agregar canciones es mediante la interfaz del cliente? O se pueden agregar canciones como archivos midi en la carpeta midis del servidor y este debe ser capas de leerlos y agregarlos como canciones? Si es esto ultimo, como sabriamos el nombre de la cancion.

**Comment by Hernan4444** [comment]
@gtquiroga porque el nombre de la canción es el nombre del archivo. Así que deben ser capaces de hacer lo segundo también.
