### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory:

### ISSUE THREAD

**Issue by martinalar** [IIC2233/syllabus#754]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda
Al utilizar el comando uic.loadUiType(archivo.ui) para mi archivo creado en QtDesigner me arroja el error FileNotFoundError: [Errno 2] No such file or directory

**Comment by JadrinaDA** [comment]
Hola! Ese error significa que tu programa no está encontrando el archivo.ui, asegúrate que el archivo esté en la misma carpeta que el código y que el nombre es el correcto. También puedes usar un path relativo para acceder a una carpeta en que está en el mismo lugar que el archivo . Por ejemplo si tienes ese archivo en una carpeta llamada archivos_uis, pondrías uic.loadUiType("archivos_uis/archivo.ui").  
Avísame si te sirve o si sigues con problemas. Éxito!

**Comment by martinalar** [comment]
Hola!, el archivo está en la misma carpeta donde esta mi código y el nombre está bien escrito.

**Comment by JadrinaDA** [comment]
Buscando en internet encontré que el path que le entregas a loadUiType debe ser relativo al directorio de trabajo es decir donde estás corriendo el archivo. Estás corriendo el archivo desde la misma carpeta en que está o usando un path para correrlo de otro lugar? Si lo estás corriendo desde otro lugar debes poner el path relativo al archivo desde esa dirección. Además me puedes decir que editor estás usando por favor?

**Comment by martinalar** [comment]
Sii, estoy corriendo el archivo desde la misma carpeta, y estoy usando vscode

**Comment by JadrinaDA** [comment]
Ok, creo que puede ser que VSCode esté con un working directory en otra parte. Para asegurarte que estés en el lugar correcto puedes usar os.getcwd() de la librería os. Además puedes usar el comando os.chdir() para asegurarte que estés en la carpeta correcta al momento de acceder el archivo (ver primer link).  Si no quieres cambiar el working directory puedes pasarle a loadUiType el resultado de un os.path.join() entre os.getcwd() y el nombre de tu archivo.

 Si no es eso, también se me ocurre que podría ser porque no estás usando comillas para describir el nombre del archivo, al menos que las hayas omitido en tu post anterior no más. Deberías usar uic.loadUiType("archivo.ui"). 

El siguiente link contiene información de como usar os para buscar y cambiar la working directory.
https://note.nkmk.me/en/python-os-getcwd-chdir/
Este muestra una setting que puedes cambiar para que VSCode corra automáticamente de la dirección del archivo.
https://github.com/microsoft/vscode-python/issues/12173

**Comment by martinalar** [comment]
Muchas gracias!, en vs code habia abierto la carpeta de T02 para trabajar, y dentro de esa carpeta tenia otra carpeta de frontend, en esa carpeta frontend tenia el archivo .py y el arhivo .ui que estaba tratando de abrir. Saque el archivo .ui de la carpeta frontend y lo puse en la de T02 y funciono!. Gracias!
