### ISSUE TITLE
metodo intersects() de QRect

### ISSUE THREAD

**Issue by cnillanes** [IIC2233/syllabus#755]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! no entiendo bien como funciona el método intersects que sugieren en el número 6 de la tarea. Busqué en internet y me aparece esto:
![Captura de Pantalla 2020-10-21 a la(s) 10 40 38](https://user-images.githubusercontent.com/41082653/96727770-d0d50200-1389-11eb-97ea-c816d1b970c8.png)
y no sé que parámetro darle porque necesito saber cuando la flecha intersecta con la zona de captura (ambos labels) pero me pide pasarle solo un r(?)

Espero puedan ayudarme:( 
Gracias!

**Comment by jaimecoloma** [comment]
Hola @cnillanes ! El método intersects lo que busca es revisar que dos elementos Qrect estén intersectando entre sí, retornando un bool True o False según dependa. 
No puedo decirte mucho pero este método es propio de un Qrect (es decir, se puede llamar como: ```QRect.intersects()```y el parámetro que recibe es otro Qrect.
Te dejo un link para que veas un poco más de Qrect que podría servirte 😉 https://doc.qt.io/qtforpython/PySide2/QtCore/QRect.html

**Comment by cnillanes** [comment]
Gracias! ya me funcionó:D

**Comment by jaimecoloma** [comment]
@cnillanes Que bueno! 👏  Recuerda no cerrar tus issues para que otros estudiantes puedan verlas si lo necesitan 😄
