### ISSUE TITLE
Modificar la METADATA

### ISSUE THREAD

**Issue by JuanGalilea** [IIC2233/Syllabus#755]
se puede modificar la metadata de una imagen para guardar informacion?
por ejemplo llevar un conteo de las versiones de las imagenes cosa de que si alguien se conecta se le haga un check a las versiones de sus imagenes y si no esta actualizado actualizarselas?

**Comment by Arcoirisky** [comment]
Holaaa~

No puedes hacer eso :( Si cambias el METADATA la extensión de tu imagen también cambia :( 
Puedes mandarlo como quieras pero si no tiene el formato real al momento de guardarla, entonces no se podrá ver u-u
