### ISSUE TITLE
Error al cargar sprites de clientes

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#756]
Hola!
Haciendo la ventana de juego (muy similar a la que ponen de ejemplo en el enunciado), quise que se mostrara el sprite de cliente hamster y perro en mi ventana. Pero al cargar la ventana me aparece bien la imagen del logo y la del mapa, pero no la de los clientes, siendo que escribí el mismo código para las que funcionaron bien, la única diferencia es el término "scaled(x, y)". Entonces, aparece mi ventana, pero sin estas dos sprites, y me tira el siguiente error;
![error_cargar_clientes](https://user-images.githubusercontent.com/59337116/82405893-2439d180-9a33-11ea-992f-2035f3070abd.PNG)
¿Cuál es el error?

**Comment by danckoo1** [comment]
A primera vista pareciera ser un error asociado al path de las imágenes, por lo que asegúrate que esa parte esté correcta, y sino cuéntame en más detalle como utilizaste el método scaled:)

**Comment by Camila-sty** [comment]
sí, eso era, cargé mal el path :laughing:
Gracias!

**Comment by danckoo1** [comment]
Denada!
