### ISSUE TITLE
Feedback T05

### ISSUE THREAD

**Issue by jnhasard** [IIC2233/Syllabus#756]
Hola, no se si mi caso es particular pero aun no me suben el feedback de la tarea 5. Quería saber si esto solo me estaba pasando a mi o en caso contrario cuando los subirán.

Saludos

**Comment by Hernan4444** [comment]
@jnhasard ahí se subió el feedback a tu repositorio de forma manual. Recuerda que las recorreciones de esta tarea serán el jueves 6.

Saludos!!

**Comment by fdominguezclaro** [comment]
@Hernan4444 Me sumo a la misma pregunta... Tampoco me lo han subido
Gracias!!

**Comment by Hernan4444** [comment]
@fdominguezclaro debió haber pasado un error que tu feedback no se subió.... Acabo de subirlo de forma manual.

Saludos!!
