### ISSUE TITLE
Prob Aparicion Flecha

### ISSUE THREAD

**Issue by enriquemolinare** [IIC2233/syllabus#756]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
No entiendo muy bien sobre las probabilidad de aparición de las flechas.  Si nos situamos en el caso del principiante la aparicion de una flecha es cada 1 segundo. Entonces en cada segundo tengo que determinar si la flecha es normal con Prob_normal o es especial con 1 - Prob_Normal. En el caso que sea especial puede ser flecha 2X, dorada o hielo.

**Comment by danckoo1** [comment]
Hola! Debes notar que las 4 probabilidades suman 1, entonces en un caso simple en que son todas equiprobables, como tú decías cada 1 segundo deberas ver cuál flecha se crea y cada una tiene probabilidad 1/4.

**Comment by enriquemolinare** [comment]
perfecto, muchas graccias

**Comment by nicolecll** [comment]
Hola, respecto a esto me queda la duda si es que aparte de la probabilidad de las flechas para cierto tipo, ¿tambien debo calcular la probabilidad de que sean de cierta direccion de forma diferenciada?, o puedo asumir que siempre existirá la misma probabilidad para cada dirección (izquierda, derecha, arriba o abajo)?

**Comment by kalarconvl** [comment]
Hola! Tengo una duda sobre cómo hacer que esto funcione. Hay una función de numpy que retorna un objeto de un arreglo o lista cuyas partes tienen cierta probabilidad:
```b = numpy.random.choice(["A", "B", "C", "D"], p=[0.1, 0.2, 0.5, 0.2])```

Esto sería muy útil para determinar qué flecha va a aparecer, pero la librería numpy está prohibida. No pude encontrar una función similar de random, ¿qué función permitida puede ser útil o dónde me recomiendan buscar?

**Comment by danckoo1** [comment]
@nicolecll yo diría que también lo hagas de forma diferenciada y las escribas como parámetros, no olvides que sumen 1 dichas probabilidades :)

**Comment by danckoo1** [comment]
@kalarconvl hola quizás te puede servir `choices()` del módulo `random`, el cual es distinto del método `choice()` saludos!

**Comment by kalarconvl** [comment]
@danckoo1 gracias!!
