### ISSUE TITLE
QLCDNumber de PyQt5.QtWidgets

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#757]
Hola.
Cree una instancia de QLCDNumber de la siguiente manera:
n = QLCDNumber(self)
Mi duda va a cómo podría editar el número dentro del recuadro? 
O si me pueden recomendar alguna página para encontrar esto, ya que sólo he encontrado cómo manejar el largo de cuadro pero no cómo editar su número.

**Comment by jbulness** [comment]
Hola @Camila-sty ,

Para editar el número del recuadro debes poner dentro del paréntesis de `QLCDNumber(self)` el atributo o valor que quieras que se muestre. Por ejemplo, si tienes un atributo `self.experiencia` debes poner `QLCDNumber(self.experiencia)`.

 En Google podrías buscar "qlcdnumber set value". Con esto aparecen varias páginas con ejemplos de como implementarlo, de hecho en stackoverflow aparece un ejemplo sencillo en las respuestas. Si sigues con problemas vuelve a comentar para ayudarte.

**Comment by Camila-sty** [comment]
Gracias, me funcionó bien usando ```n.display(valor)```
