### ISSUE TITLE
No se muestran los errores en consola

### ISSUE THREAD

**Issue by pahaeussler** [IIC2233/Syllabus#757]
Hola, haciendo la tarea me percate que mi script si tiene algun error no me lo muestra en pantalla ni se cae el programa. Probé agregandole el hook y sacandoselo, pero sigo con el mismo problema. ¿Alguna idea 💡 para solucionarlo?

**Comment by rihanuch** [comment]
Hola! 

Tienes tu codigo subido en tu repositorio?

**Comment by pahaeussler** [comment]
Si, ya lo subí

**Comment by pahaeussler** [comment]
Por favor ayudar, avanzo muy lento sin saber que errores voy teniendo en el camino.

**Comment by pahaeussler** [comment]
Solucionado
