### ISSUE TITLE
zlib error

### ISSUE THREAD

**Issue by movaldivia** [IIC2233/Syllabus#757]
Tras editar una imagen puedo abrirla y ver los cambios con un programa externo como paint. Pero cuando la intento de abrir como bytes me sale el siguiente error: `zlib.error: Error -5 while decompressing data: incomplete or truncated stream` . Algún compañero o ayudante sabe porque me sucede esto?

**Comment by jgespinosa10** [comment]
Me sumo a la pregunta, cuando trato con imagenes como Mushroom.png, MickeyMouse.png o Anime.png no tengo ningún problema pero cuando trato de descomprimir el resto me pasa el mismo error. Como puedo arreglarlo?

**Comment by movaldivia** [comment]
@jgespinosa10 en lo personal, tenía un problema con el largo. Lo mantenía porque mi lógica me decía sigue teniendo la misma cantidad de píxeles. Pero al descomprimir y comprimir el largo cambia. Ese puede ser tu problema. Saludos

**Comment by jgespinosa10** [comment]
@movaldivia Gracias, pero mi problema no es con el largo. Es que que con algunas imagenes al descomprimir el IDAT tira error por lo que no me deja trabajar con esas imagenes.
