### ISSUE TITLE
Como editar el color de un Qrect

### ISSUE THREAD

**Issue by Natydlb** [IIC2233/syllabus#757]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! He estado buscando como cambiarle color a los Qrect, pero no encuentro información sobre ello :(
**Hay algun metodo que pueda utilizar para cambiarle el color a un Qrect?**

**Comment by jaimecoloma** [comment]
Hola @Natydlb ! Un elemento Qrect no pertenece a la misma categoría que un Qlabel o un Qwidget y según entiendo, su uso es más "matemático" que algo visual, por lo que no creo que haya forma de cambiarle el color.
Te dejo a continuación un link con la clase Qrect para que veas todo lo que puedes hacer con ella 
😄  https://doc.qt.io/qtforpython/PySide2/QtCore/QRect.html

**Comment by Natydlb** [comment]
Pero es que no entiendo 😫 porque para poder trabajar esos atributos con el método intersects tienen que ser del tipo Qrect porque como Qlabel no sirven, pero luego para cambiar el color tengo que trabajarlo como qlabel, ** debería volver a cambiarlo entonces como qlabel?**
Porq por ejemplo yo tenía el qlabel y lo cambié a qrect 
Self.hola= qrect...
Luego debería hacer esto?
If... :
self.hola =qlabel

**Comment by jaimecoloma** [comment]
No puedo decirte mucho pero tu idea no está  mala, como tip recordarte que en la sala de ayuda se habló de que todo aquello lógico debe ir en el back-end  y lo relacionado a actualizar interfaz va en el front-end... Entonces ¿Quizás puedes usar ambas? Recuerda el uso de señales!
