### ISSUE TITLE
_pickle.UnpicklingError: pickle data was truncated

### ISSUE THREAD

**Issue by mjgutierrez1** [IIC2233/Syllabus#758]
Hola, estoy teniendo el problema del título de esta issue. Buscando por qué ocurre me encontré con una solución en https://stackoverflow.com/questions/44637809/python-3-6-socket-pickle-data-was-truncated , pero aunque probé hacer ese arreglo el problema sigue ocurriendo.

La razón de por qué estoy usando pickle es que traté de mandar las imágenes desde el servidor al cliente mediante el mensaje {"status": "imagen", "data": bytes_de_alguna_imagen}, siguiendo el formato de la ayudantía del cachipún. El problema es que este mensaje no soporta que se le haga json.dumps debido a que tiene bytes. Por eso ahora traté con pickle, ya que probé mandar bytes en un diccionario serializado mediante pickle y sí me funcionó. El tema es que en el caso de las imagenes son tantos bytes que el pickle se trunca...

¿Es mala la forma en que estoy tratando de enviar mis imágenes?¿Cómo podría solucionar esto?

**Comment by jtagle2** [comment]
No sé como estás manejando el envío de datos, pero basándome en tu otra issue (#753), supongo que lo que te está pasando, es que estás enviando todo el mensaje, y no lo estás recibiendo entero. Ve lo que te respondí en la otra issue, dale una vuelta al envío/recibo de información, y si ya estás seguro que está bien y el error persiste, vuelve a preguntar (en esta misma issue).
Para ver si estás mandando y recibiendo todo, te recomiendo imprimir en pantalla el largo del mensaje al enviarlo desde el servidor (cliente), y después el largo del mismo mensaje cuando lo recibes en el cliente (servidor).
Saludos!

**Comment by mjgutierrez1** [comment]
@jtagle2 Excelente explicación en la otra issue. Muchas gracias, con eso solucioné el problema.
Saludos!
