### ISSUE TITLE
Pixeles del recorrido de la Flecha

### ISSUE THREAD

**Issue by enriquemolinare** [IIC2233/syllabus#758]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
***¿Cuantos pixeles debe  ser el recorrido de la flecha?*** 
[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by JuaniAndres** [comment]
Hola @enriquemolinare 
Si con el recorrido te refieres a cuanto es el tamaño del carril por donde se mueven las flechas eso queda a tu criterio depende de cómo tengas organizado el resto de tu ventana, pero obviamente trata de que no sea tan corto para que a las flechas les tome algo de tiempo llegar a la zona de captura. Si tu pregunta iba más relacionada con cuanto se van moviendo las flechas eso lo defines con el parámetro ````VELOCIDAD_FLECHA````.
Espero haber resuelto tu duda, éxito en la tarea.

**Comment by enriquemolinare** [comment]
graciaaaas
