### ISSUE TITLE
Nota 1.0 en feedback de la AC14

### ISSUE THREAD

**Issue by akaminetzkyp** [IIC2233/Syllabus#758]
Hola!

Varios de mis compañeros y yo tenemos un 1.0 en el feedback de la actividad 14, mientras que en la planilla esta se muestra correctamente. :)

Saludos!

**Comment by Okhan97** [comment]
me sumo al comentario

**Comment by jnhasard** [comment]
por lo menos tienen feedback :(

**Comment by egbusch** [comment]
Estoy igual para la AC14 y además en la AC15 me enviaron un mensaje de ausente.... pero luego aparece el feedback y la nota correcta en la planilla.

**Comment by andresfdezc** [comment]
@akaminetzkyp Revisaremos qué pasó con los feedbacks. Recuerden que la recorrección de esta actividad será presencial el jueves a las 14:00.

@egbusch Sobre la actividad 15, pueden ignorar la primera issue con nombre "AC15" que dice que estuvieron ausentes.

**Comment by akaminetzkyp** [comment]
Gracias!

**Comment by NachoCasta** [comment]
Arreglados los feedbacks de los que comentaron

**Comment by jnlarrain** [comment]
@NachoCasta  yo tambien tengo este problema

**Comment by asdegoyeneche** [comment]
Hola! A mi también me falta ese feedback :o 
@djcontador @jnlarrain tambien ustedes si?
