### ISSUE TITLE
Como implementar ventana al Client?

### ISSUE THREAD

**Issue by sicorrecto** [IIC2233/Syllabus#758]
Hola!

Estoy tratando de copiar la modelación de la actividad 13, donde el Client tiene un atributo ventana que corresponde a una clase Pyqt importada de otro modulo.

Resulta que tengo un código muy similar al dado en la actividad 13, pero al correr client.py aparece el icono de la ventana y la ventana no aparece. He intentado de todo, pero no logro hacerlo funcionar, por lo que pido ayuda a algún ayudante.

Tengo mi repositorio actualizado en git, y entre los posibles problemas usé QtDesigner y tengo un Mac.

La ventana funciona perfecto si la corro desde su propio python.

**Comment by nachocontreras** [comment]
Hola!

El problema es que tienes un while True que hace que nunca se termine de llamar la funcion repl().
Tienes que crear un thread del servidor asociado a la función self.repl, e iniciar ese thread. Hice eso y funcionó.

**Comment by nachocontreras** [comment]
Hola!

El problema es que se ejecuta un while True debido a repl().
Lo que puedes hacer, al igual que con el listen, es crear un thread asociado a la funcion repl(). Eso permitirá que se ejecuten las otras funciones.

Éxito! 😃

**Comment by FJavierOss** [comment]
¿Esto podría estar relacionado con #768 ? Pprque en algun momento me paso lo mismo pero no lo solucione con un thread asociado a la funcion repl(), la verdad es que ni se cm hice que funcionara.

**Comment by sicorrecto** [comment]
@nachocontreras Muchas gracias! Era eso.
