### ISSUE TITLE
Diferencia entre zona de captura final y la del avance.

### ISSUE THREAD

**Issue by DomingoCarvajal** [IIC2233/syllabus#759]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola!

Para la tarea final, en el enunciado aparece que el color de la zona de captura debe cambiar mientras se presiona la tecla correspondiente a cada casilla. Sin embargo, en el avance nos piden que cambiemos el color de la casilla en los momentos en que la flecha pase por encima.

Quería saber si podía entregar el avance con el funcionamiento de la tarea final, es decir que el color cambie cuando se presiona la tecla correspondiente, ya que me hace más sentido que el avance tenga el mismo funcionamiento para además poder usarlo después en el programa completo.

**Comment by jaimecoloma** [comment]
Hola @DomingoCarvajal ! Para el avance y lo que mencionas, son cosas diferentes, ya que lo que se quiere evaluar no es el uso del KeyPressEvent, si no más bien cómo cuando la flecha pasa por la zona de captura tu programa detecta esto. Ambos deberás de todos modos implementarlo bien para que tu programa funcione, ahora si lo que querías decir es que tu programa hará ambos o más de lo que pedido en el avance, si puedes.

**Comment by DomingoCarvajal** [comment]
Ok Gracias!
