### ISSUE TITLE
Food

### ISSUE THREAD

**Issue by rgriver** [IIC2233/Syllabus#759]
Hola. En el calendario del curso se indica que el examen es desde las 8:30 hasta las 11:30. Si mis habilidades aritméticas siguen intactas, el examen tendría una duración de 3 horas. En ese caso (en cualquier caso en realidad), ¿se podría llevar alguna bebida o algún snack para comer durante la prueba?

**Comment by indonoso** [comment]
Pueden comer/tomar cualquier cosa que no tenga mucho olor ni que suene mucho. Lleven agua :)
