### ISSUE TITLE
Octava en silencio

### ISSUE THREAD

**Issue by sjkinast** [IIC2233/Syllabus#759]
Hola! cuanto vale la octava en un silencio ?  ya que no dice nada en el enunciado. Como la nota vale 0 pongo que la octava vale 0 también ?

**Comment by nachocontreras** [comment]
Hola!

Cuando es un silencio, el valor numérico de la nota es 0, por lo tanto, no tiene octava. Podrías asumir que es 0, para obtener el valor correspondiente en la Figura 2.
