### ISSUE TITLE
Complicacion al cargar una segunda mesa

### ISSUE THREAD

**Issue by MINGOD24** [IIC2233/syllabus#759]
Hola, cuando trato de cargar la segunda mesa (asumo que me pasaria lo mismo si fuera otra entidad) se me borra de la imagen la primera mesa. ¿Porque puede ser?

**Comment by jbulness** [comment]
Hola @MINGOD24,

Revisa si no estás "sobreescribiendo" la `Label` donde tienes la primera mesa, es decir, que solo estas cambiando el valor de la mesa implementada en un principio, por lo que no estarías agregando otra mesa. Esto te podría pasar si, al "agregar" otra mesa, la estas definiendo el atributo con el mismo nombre que la anterior, sin tener "respaldo" de la primera mesa.

**Comment by MINGOD24** [comment]
hola @jbulness, si esoo debe ser lo que me esta pasando. Porque tengo una función desde el backend para agregar los objetos, y  en esta funcion utilizo el mismo nombre. Pero como puedo hacer para que vaya variando el nombre del label? Lo otro que no entiendo es que de igual manera ocupo el mismo nombre para definir al mesero y al chef(misma funcion pero separadas por un if) , porque estos no se remplazan entre ellos? Voy a subir al repo mis archivos por si te ayudan a contestarme mejor. :)

**Comment by jbulness** [comment]
Más que ir variando el nombre del `Label` debes guardar los `Label` creados, ya sea en una lista, diccionario, etc. lo que te acomode más y creas que te va a ser de mayor utilidad después.

Con respecto a lo segundo, el chef te va a traer el mismo problema dado que también se deben poder agregar más. Sin embargo, dependiendo si haces o no el bonus, el mesero puede que no te traiga problemas, ya que lo tendrías que "crear" solo una vez

**Comment by MINGOD24** [comment]
hola, ahi lo logre muchas gracias!
