### ISSUE TITLE
duda con compress y decompress

### ISSUE THREAD

**Issue by depstein26** [IIC2233/Syllabus#759]
Hola, con las imágenes de MickeyMouse y DragonBall, no se por qué si hago decompress y luego compress (en nivel 9), los resultados que obtengo son diferentes a cuando recibo la imagen sola, he estado viendo varias opciones de por que me pasa esto pero aún no lo descifro por si pudieran ayudarme. Cuando ejecuto el código que pongo, para Mushroom y Knightmare, me sale 'bien', pero para las dos mencionadas antes, me sale 'mal'.

Gracias!
<img width="373" alt="captura de pantalla 2017-11-18 a la s 16 43 54" src="https://user-images.githubusercontent.com/30672947/32984163-e4982960-cc7f-11e7-8384-511a2d4cf4bf.png">

**Comment by inmadariaga** [comment]
(no soy ayudante) sacale el ",9" y funcionara, me paso algo similar, no se porque pasa

**Comment by savelozo** [comment]
Puede ser porque hay que declarar que el 9 es para el level o no? es decir:

compress(info, level=9)

**Comment by depstein26** [comment]
No funciona ninguno de los dos casos :( Muchas gracias por la preocupación de todas formas. Alguien más tiene alguna idea de algo?

Gracias!

**Comment by Jiparavich** [comment]
Pudiste solucionarlo? me paso lo mismo

**Comment by FernandoPieressa** [comment]
Hola!

Lo que tienes en tu imagen esta correcto, por lo que yo creo que tu error podria estar en los bytes a los que les estas aplicando el decompress, asegurate que sea solo la seccion de informacion!
