### ISSUE TITLE
Duda con piezas explosivas

### ISSUE THREAD

**Issue by GitCross135** [IIC2233/Syllabus#76]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

**Cómo tengo que tratar a las piezas explosivas en los métodos de mi código?** Eso ya que hay un método que transforma las piezas explosivas en Objetos de la clase PiezaExplosiva, sin embargo, cuando en los demás métodos quiero referirme o encontrar una pieza explosiva, no sé si hacerlo asumiendo que son objetos o simplemente strings.

**Comment by Dominique236** [comment]
Hola!
Recuerda que la clase Tablero tiene un atributo llamado _tablero_ que es por enunciado "una lista de listas de _strings_", por lo tanto siempre que utilices este atributo se mantendrá ese formato porque en ningún método/property se pide cambiar el tipo de dato del atributo o dentro de él.

Si bien, como mencionas, la property _tablero_transformado_ busca transformar cada pieza explosiva del atributo _tablero_ en una instancia de la clase PiezaExplosiva debes notar que el fin de esta property es **retornar** el tablero transformado y **no reemplazar o cambiar** el atributo. 

Cuéntame si esto resuelve tu duda si no para abordarlo de otra forma 😊

**Comment by GitCross135** [comment]
Mmm creo que entiendo, en ese caso tendría que crear una "copia" del tablero original, para modificar esa copia y no el tablero original y luego retornar la copia?

**Comment by GitCross135** [comment]
> Hola! Recuerda que la clase Tablero tiene un atributo llamado _tablero_ que es por enunciado "una lista de listas de _strings_", por lo tanto siempre que utilices este atributo se mantendrá ese formato porque en ningún método/property se pide cambiar el tipo de dato del atributo o dentro de él.
> 
> Si bien, como mencionas, la property _tablero_transformado_ busca transformar cada pieza explosiva del atributo _tablero_ en una instancia de la clase PiezaExplosiva debes notar que el fin de esta property es **retornar** el tablero transformado y **no reemplazar o cambiar** el atributo.
> 
> Cuéntame si esto resuelve tu duda si no para abordarlo de otra forma 😊

Mmm creo que entiendo, en ese caso tendría que crear una "copia" del tablero original, para luego modificar a la copia y no al original, y finalmente retornar la copia?

**Comment by Dominique236** [comment]
Claro, esa es una forma de como abordarlo. Solo debes recordar cumplir la función que se pide del método/property (en este y los otros casos).

**Comment by GitCross135** [comment]
Yaa muchas graciass te pasaste :))
