### ISSUE TITLE
Problema con el método "sort" e instancias de "datetime"

### ISSUE THREAD

**Issue by felipehen** [IIC2233/syllabus#76]
al intentar usar la librería permitida, para ordenar fechas, pero da lo mismo como escriba el código siempre me sale el mismo mensaje:
estoy ocupando la configuración del sort de la forma "%Y/%d/%m", pero sigue saliendome el mismo mensaje, sin importar cuanto intente editar el archivo

ValueError: unconverted data remains: 7

**Comment by igbasly** [comment]
Hola @felipehen!
Para poder entender bien tu problema y el error generado, por favor confírmame si estás utilizando la librería `datetime` para tratar fechas y explícame a qué te refieres con “la configuración del sort” 👍

**Comment by felipehen** [comment]
si, efectivamente estoy ocupando dicha librería, para poder tratar las fechas.

y con configuración de sort, me refería todos los caracteres que van después de él, como por ejemplo lambda o esto "%Y/%d/%m".

**Comment by igbasly** [comment]
Entiendo, bajo lo que me estás planteando puedo detectar dos factores importantes.

Primero, como ya sabrás, el método `sort` ordena una lista en base a sus elementos, siempre y cuando ellos sean “ordenables” (por ejemplo números), cuando estamos trabajando con clases creadas por nosotros y no definimos que sean “ordenables” podemos utilizar el método `sorted`con el *keyargument* `key` para agregar una función (como `lambda`) que nos ayude a ordenarlas en base a algún atributo como puede ser una fecha.
Aquí cabe mencionar que las instancias del tipo `datetime` sí son “ordenables”, por lo tanto, si tienes una lista solo de elementos `datetime` está se puede ordenar solo utilizando `sort`.

Para ejemplificar tendremos una lista llamada `lista` que contiene instancias de una clase propia no "ordenable", pero que posee un atributo `fecha` que es un `datetime`, el cual nos sirve para ordenar.
```python
lista.sorted(key=lambda e: e.fecha)
```
En la función `lambda`, `e` representa los elementos de la lista, qué dijimos eran instancias de una clase ficticia.
Puedes encontrar más acerca de esto en la web de [Python](https://docs.python.org/3.7/howto/sorting.html).

Segundo, cuándo mencionas este formato "%Y/%d/%m", este se utiliza directamente en las instancias `datetime` como un formato para representar esa fecha en un `string` o por el contrario, para convertir un `string` en una instancia `datetime. Al igual, puede encontrar más acerca de esto en la web de [Python](https://docs.python.org/3.7/library/datetime.html).

Espero haberte aclarado la situación y no dudes en preguntar cualquier inquietud 😉
