### ISSUE TITLE
Puedo hacer no hacer una clase edificios?

### ISSUE THREAD

**Issue by perezpefaur** [IIC2233/syllabus#76]
Uno de los criterios de evaluación es la correcta modelacion de la clase edificios, que a mi me parece innecesaria, ya que los unicos atributos que me interesan son su existencia y su hp. Solo en el caso de muralla lo necesito.

**Comment by roberto009** [comment]
Hola!
Igual que en la Issue #71 , nosotros no podemos decirte como modelar tu problema, pero es importante que este __sea consistente con el enunciado__
Suerte
