### ISSUE TITLE
Duda 5.4 Cantidad Edificios + 7. Vida Ejercito

### ISSUE THREAD

**Issue by emeiese** [IIC2233/Syllabus#76]
Hola! En la sección 5.4 se especifica que se puede crear un cuartel y una  torre de defensa, pero no especifican si solo se puede tener uno de cada uno o no.

Respecto a la sección 7,  en el primer párrafo dice 

> "Cada ejército se comporta como una entidad cuyo ataque es la suma de los ataques de **todos sus soldados** y su vida es la suma de la vida de **todos sus soldados**"

En este caso, cuando hablan de _soldados_ ¿se refieren a los guerreros de un planeta? Es decir, se refieren **tanto a los soldados comunes como a los magos**? 

Desde ya, muchas gracias! :)

**Comment by leolivares** [comment]
Hola!
1) Sale en la sección 5.2, en el apartado de "Edificios". Un planeta solo puede tener uno de cada uno.
2) Sí, se refiere a ambos.
De nada!
