### ISSUE TITLE
duda imports

### ISSUE THREAD

**Issue by Afro27** [IIC2233/syllabus#76]
Se descuenta puntaje por importar modulos despues de las funciones que defini en un modulo? ya que tengo 2 modulos que se importan mutuamente y lo unico que se me ocurre para solucionarlo es que uno se importe despues de definir las funciones. En todo caso, esto lo hare solo para que se pueda volver del menu de juego al menu de inciio que tampoco es tan necesario.

**Comment by jeschuwirth** [comment]
Hola,

Generalmente que dos archivos se importen mutuamente es un problema a la hora de querer cambiar uno de ellos, ya que puede causar que el otro deje de funcionar o no puedan correr en absoluto, por lo que se debería codificar teniendo esto en cuenta y que sólo uno de ellos importe al otro. En tu caso probablemente sería el menú de inicio el que importe al menú de juego

Para seguir las reglas de PEP8 completas deberías importar todos tus módulos al comienzo del archivo, sin embargo para el curso sólo les pedimos que cumplan con lo pedido en la [guía de descuentos](https://github.com/IIC2233/syllabus/blob/master/Tareas/Descuentos.md), por lo que no es necesario que lo hagas (aunque es muy recomendado).

Te recomiendo cambiar tu código para que el menu de inicio importe al de juego y no viceversa, si no lo logras, entonces importa en ambos sentidos, y si eso no funciona importa debajo de las funciones.

Suerte!
