### ISSUE TITLE
Incongruencias entre archivo juegos.csv y archivo Enunciado.pdf

### ISSUE THREAD

**Issue by MaxAl100** [IIC2233/Syllabus#76]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
En el archivo juegos.csv existen ciertos valores de apuesta mínima y máxima que no calzan con las definidas en el enunciado.

Por ejemplo, en el juego cara o sello, la apuesta máxima es 100 mientras que en el enunciado dice que la apuesta máxima es un valor que varía entre 700 y 1500.
O, en el caso de blackjack, la apuesta mínima detallada en el .csv es de 300, pero en el enunciado se dice que la apuesta mínima máxima es de 200.

Significa esto que tenemos que actualizar este valor máximo o es un error en el enunciado?

**Comment by Gsalinas1506** [comment]
Hola!

Efectivamente era un error del enunciado :sweat_smile: para evitar confusiones quedate con que lo que manda es el archivo .csv

En breves se subira una versión del enunciado con este error corregido. Muchas gracias por hacerlo notar!

Exito con la Tarea! 🎲️🃏️
