### ISSUE TITLE
Cambio archivos.cvs

### ISSUE THREAD

**Issue by sebabitar** [IIC2233/Syllabus#76]
Note que al bajar de nuevo Orders.cvs desapareció la columna precio, porque es esto? ademas de cambiar bid por bird.

**Comment by Hernan4444** [comment]
@sebabitar fue un error mio 🙊, solucionando un tema de los Ids no me percaté que en la version que arreglé el problema todavíá estaba el tema de bird 🐦  y precio 💵 . Acabo de subirlo bien, si hay otro error comentalo por favor 😅 

Saludos!!
