### ISSUE TITLE
Duda sobre nombre_archivo

### ISSUE THREAD

**Issue by masoto22** [IIC2233/Syllabus#76]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/21)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/20)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola 😄 escribo porque a pesar de haber otras issues sobre los archivos, no encontré alguna similar a lo que busco:( Me surgió una duda sobre nombre_archivo, que se le entrega tanto a cargar_tablero como a guardar_tablero. Tenemos que asumir que el nombre entregado incluye el .txt? Por ej. cargar_tablero("2x2.txt") o guardar_tablero("2x2_sol.txt"), la que más me hace dudar es sobre guardar tablero, entiendo que una vez entregado en consola podría agregarse la extensión para la función, pero dado que se va a corregir probando estas funciones, preferí asegurarme si va a considerar o no la extensión 😕 

Gracias! Espero que se entienda

**Comment by Hernan4444** [comment]
Hola @masoto22 

Esas funciones deben hacer únicamente lo pedido. Guardar tablero recibe el nombre de un archivo y un tablero. Luego se guarda en dicho archivo el tablero siguiendo el formato del enunciado. En ninguna parte hay que pensar en la extensión. Solo guadar con el formato del tablero pedido en el archivo indicado. Con esto quiero decir que la función pedida es bien primitiva y directa de completar. 

Por ejemplo:
* Si yo hago `guardar_tablero("gatito.txt", tablero)`. Se deberá crear el archivo "gatito.txt"  que adentro tendrá el tablero.
* Si yo hago `guardar_tablero("hola", tablero)`. Se deberá crear el archivo "hola" que adentro tendrá el tablero.
* Si yo hago `guardar_tablero("musica.mp3", tablero)`. Se deberá crear el archivo "musica.mp3" que adentro tendrá el tablero.
* Si yo hago `guardar_tablero("tablero.txt.txt.txt", tablero)`. Se deberá crear el archivo "tablero.txt.txt.txt" que adentro tendrá el tablero.
* Si yo hago `guardar_tablero("Hola/tablero.txt", tablero)`. Se deberá crear el archivo "tablero.txt" dentro de la carpeta "Hola" y dicho archivo tendrá el tablero.

Al final, la extensión es solo una parte más del nombre y que para la función es irrelevante. Solo debes tomar el "nombre_archivo" y usarlo tal como viene para escribir el archivo con el comando necesario (`open`).

Ahora bien, ¿qué cosas si se pueden asumir? 
Que dentro de la carpeta Archivos, todos los archivos dados serán .txt, por lo tanto en la consola te daremos algún archivo con esa extensión. Por ejemplo, "2x2.txt" y luego, el cómo proceses la información dentro de tu programa es decisión tuya. Solo debes asegurarte que al momento de pedir la solución del tablero, esta solución se deberá guardar como "2x2_sol.txt", pero todo ese calculo del nombre se debe realizar **antes** de llamar a `guardar_tablero`. Una vez que ya tengas el nombre definido (junto con su extensión), recién ahí usa la función `guardar_tablero` con el nombre que calculaste + el tablero a guardar.

Ojalá se haya entendido lo que queremos con esta función, sino responde este hilo 😄 
Saludos c:

**Comment by masoto22** [comment]
Gracias! Ahí caché mejor 😸
