### ISSUE TITLE
Archivo parámetros

### ISSUE THREAD

**Issue by barbaracalderonr** [IIC2233/syllabus#76]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola!, tengo una duda acerca el archivo parámetros, nosotros podemos editarle y agregarle más parámetros o es como intocable?
Gracias

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by IgnaciaJ** [comment]
Hola Barbara! La idea del archivo parámetros es agregar todas las variables que se mantienen fijas a lo largo del funcionamiento del programa, por lo que si tu crees que necesitas incluir otras variables aparte de las que vienen especificadas en el enunciado(las que se encuentran en azul y mayúsculas) puedes hacerlo. Un ejemplo de esto puede ser poner en este archivo los path de los csv como parámetros.
