### ISSUE TITLE
Consulta sobre detalles no especificados

### ISSUE THREAD

**Issue by Cartterr** [IIC2233/Syllabus#76]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Se van a evaluar todas los detalles que no se especificaciones sobre la tarea? Por ejemplo al abrir una publicación, tengo las opciones "Hacer un comentario" y "volver", pero si el usuario coloca un valor inválido, lo devuelve a la lista de publicaciones en lugar de mantenerlo ahí.

Aunque de todas formas no se especificó que necesariamente tenga que mantenerse en la misma página, o esa es la idea?
Mi código hace todo lo demás correctamente (creo).

**Comment by Juampisaez** [comment]
Hola @Cartterr!
Como bien te pudiste dar cuenta ese caso en particular no esta especificado en el enunciado y de hecho tampoco se evalúa como tal en la distribución de puntaje. Por lo tanto queda a tu criterio la forma de implementar esta parte. Como recomendación, te sugiero colocar todos los supuestos que realizaste (como este) en el Readme, para que tu ayudante este informado sobre los detalles de tu programa.

Espero este mas claro,
Cualquier duda, pregunta nomas :)

**Comment by Cartterr** [comment]
Perfecto, y por ejemplo la modulación también es necesaria? Ya que no aparece especificado y decidí definir todas las funciones dentro de un mismo .py

**Comment by Juampisaez** [comment]
La modulación siempre es una buena práctica porque asi separas tu programa y cada archivo contiene elementos que se relacionan. Sin embargo no es necesario para esta tarea, aunque si se recomienda para que te familiarices con esto.
