### ISSUE TITLE
Tamaño mapa

### ISSUE THREAD

**Issue by tedroppelmann** [IIC2233/syllabus#760]
Hola. En mi juego a modo de que no se deformara tanto la página de juego, fije los tamaños del widget. Es posible hacer eso? Es decir, no puedo agrandar ni achicar la ventana. Pero lo tamaños se ven mejor y siempre en el mismo lugar. Con ello el tamaño del mapa es siempre el mismo.

**Comment by matiasmasjuan** [comment]
Hola @tedroppelmann !

No es necesario que fijes los tamaños del widget para que no se deforme la ventana de juego. Si observas el **enunciado**, en la sección **6.4 parametros.py** te darás cuenta de que estos problemas sí están considerados.

![info_parametros](https://user-images.githubusercontent.com/48495638/82454612-f464eb00-9a7f-11ea-864a-57ef66e6d9d7.PNG)

Sin embargo, es necesario **destacar** que estos **parámetros** de **dimensiones** se **deben** encontrar en **parametros.py**, y deben ser **importados** a tus **módulos** de las **ventanas** para que puedan ser **utilizados**.

Saludos! 😄

**Comment by tedroppelmann** [comment]
Ya lo fije... No es considerado mala práctica? También tengo otra duda. Dentro de las dimensiones del mapa cree un espacio aún más pequeño para el Drag and Drop con el fin de que al agregar el mesonero y las mesas estos no queden con un pedazo fuera del mapa. Agrego todas estas dimensiones a parámetros.py?

**Comment by matiasmasjuan** [comment]
Con respecto a fijar la imagen. No es que sea **mala** **práctica**, pero se **debe** poder modificar el **tamaño** de la **ventana** al cambiar ese **parámetro**. Este **parámetro** se **modificará** en la evaluación para asegurarnos de que estén **utilizando** correctamente los **parámetros**. Sin embargo, entendiendo que esto también modifica las dimensiones e interacción con otros *labels*, se **restaurará** a la normalidad una vez evaluado este **criterio**. 

Con respecto a tu segunda pregunta, por favor realiza otra ***Issue*** respecto a eso, ya que se tratan de temas distintos.

Saludos! 😄
