### ISSUE TITLE
Tamaños y posiciones de ventana en Parametros.py

### ISSUE THREAD

**Issue by isidorabecker** [IIC2233/syllabus#760]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, los datos de tamaños y posiciones de las ventanas que van en setGeometry igual deben estar incluidos en parametros.py o pueden estar solo en setGeometry.

Muchas Gracias !!!

**Comment by jaimecoloma** [comment]
Hola @isidorabecker! En el enunciado se señala lo siguiente sobre parametros.py: "Es posible que los ayudantes modifiquen estos parámetros durante la corrección, pero los que hagan referencia a dimensiones de ventanas, dimensiones de elementos de la interfaz o rutas a sprites no serán modificados para no complicar la visualización de estos. Sin embargo, debes agregarlos al archivo de igual modo." Por lo que parametros respecto a tamaños y posiciones para el setGeometry de las ventanas **sí** deben ir.
Mucho éxito con la tarea!

**Comment by isidorabecker** [comment]
Ok, muchas gracias !!

**Comment by Zenos-Paradox** [comment]
Y si las ventanas son hechas  desde qt Designer? también hay que ponerlo en parametros.py? cómo se podría hacer la conección si ya está creado el archivo.ui? debemos modificar el tamaño y posición de estos widgets en el código?

**Comment by jaimecoloma** [comment]
@Zenos-Paradox buena pregunta, si usaste QtDesigner no es necesario que los agregues, en cambio para código, como usar parámetros es una buena practica se deberían agregar. Si quieres al momento de escribir tu Readme puedes citar esta issue señalando porqué no incluyes esos parametros en el archivo.

**Comment by Zenos-Paradox** [comment]
Perfecto, gracias :)
