### ISSUE TITLE
Respecto a las preguntas del examen

### ISSUE THREAD

**Issue by aeperalta** [IIC2233/Syllabus#760]
Hola, no sé si será una pregunta invalida, pero igual va:

En el examen del 2016-2 me di cuenta que piden la "idea" del código más que la sintaxis en sí. Por lo mismo, me gustaría saber si este examen va por el mismo lado o se enfocarán más en un código que funcione 
PD: Es para ver si los otros exámenes anteriores, que no siguen este mismo estilo (como el de 2016-1), los respondo de esa forma para agarrar ritmo.

**Comment by Dunkan1** [comment]
no soy ayudante, pero en la ayudantia hicieron ejercicios semejantes(en los que pedian la idea del codigo) asi que supongo que si

**Comment by andresfdezc** [comment]
No te puedo decir cómo será el examen, pero por lo menos puedes tener la certeza de que no vamos a probar tu código en un computador al corregir.

**Comment by aeperalta** [comment]
gracias, saludos!
