### ISSUE TITLE
Libpng error: Read Error

### ISSUE THREAD

**Issue by savelozo** [IIC2233/Syllabus#760]
Tengo un problema al intentar abrir nuevamente el archivo png que guardé, ya que Python me tira "Libpng error: Read Error".

Teóricamente el archivo está bien guardado ya que puedo visualizarlo en el computador y los cambios se ven reflejados. Googlié y no encontré nada sensato, qué podría ser?

**Comment by FernandoPieressa** [comment]
Esta prohibido subir código en issues para evitar copias. Imagenes borradas

Respecto a tu problema, probablemente tienes errores dentro de la creación de la cadena de bytes. Python es muy sensible respecto a la lectura de imagenes, a diferencia de los lectores normales que pueden interpretar errores pequeños y de igual forma mostrar la imagen correcta.
