### ISSUE TITLE
Definición de atributos [materia]

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2233/Syllabus#761]
Hay una forma de definir atributos para las clases (u objetos, ya no se) que es la siguiente para atr1:

```
class p:

    atr1 = 2

    def __init__(self):
        self.atr2 = 4

        self.atr1 += 1

        p.atr1 = 5

        p.atr2 = 6

i = p()

print(i.atr1, i.atr2)
```
La pregunta es ¿Cual es la diferencia en definirlo dentro del init y fuera del init?

Me surge una segunda pregunta en el mismo código que puse. ¿Por que tiene sentido y no tira error el hecho de escribir p.atr1 o p.atr2? ¿Que es lo que cambia si yo los seteo? 

El print imprime 3 4, es decir, no imprime el cambio hecho al escribir p.atr1, sino imprime el cambio hecho al escribir self.atr1.

Ojalá se entienda la duda y mientras más completa la respuesta en cuanto a si incluso se puede aportar algo más que no agregué sería genial y se agradece.

**Comment by jicortes2** [comment]
Hola! Respecto al código que subiste de ejemplo, hay una diferencia entre los atributos de la clase (que será el mismo para todas las instancias de esa clase) y los atributos de las instancias (que serán distintos entre todas las instancias).
Cuando haces el print lo que estas imprimiendo son los atributos de la instancia
```
class p:
    atr1 = 2
    def __init__(self):
        self.atr2 = 4
        self.atr1 += 1
        p.atr1 = 5
        p.atr2 = 6

print(p.atr1)  # 2
i = p()
print(i.atr1, i.atr2)  # 3, 4 porque son los atributos de la instancia
print(p.atr1, p.atr2)  # 5, 6 que son los atributos de la clase
```
Respecto a 

> ¿Cual es la diferencia en definirlo dentro del init y fuera del init?

La diferencia es que cuando esta dentro del init, necesitas haber creado una instancia para que ese atributo de clase exista, es decir, el siguiente código tendría un error ya que atr1 no existe:
```
class p:
    def __init__(self):
        self.atr2 = 4
        self.atr1 += 1
        p.atr1 = 5
        p.atr2 = 6

print(p.atr1)  # Error porque no tiene atr1
```
Mientras que al estar afuera, no requiere que se haya instanciado algo antes (como el primer codigo)
> ¿Por que tiene sentido y no tira error el hecho de escribir p.atr1 o p.atr2?

Lo que hace es que cada vez que instancies algo setearas estos atributos de clase en 5 y 6, no hay ningún problema en esto como para que tire error.

Animo con el estudio!

**Comment by Arcoirisky** [comment]
¿cuál es atributo de clase e instancia en este caso? 
El de la clase sería p.atr1 y p.atr2 y el de la instancia es cuando hacemos una variable extra y le asignamos la clase?

¿Por qué es importante tener atributos en la clase tipo p si puedo dejarla como algo interno con los "__" o simplemente si no lo toco al momento de usarlo? Por ejemplo, si tengo una clase CuerpoHumano y al momento de hacer el init sólo tomo el nombre y el sexo. Cuando creo a juanito y a pedrito es ¿mejor tener todos sus organos como CuerpoHumano.<organo> o simplemente self.<organo> si es que no pienso tocarlos ni nada? Y, en el caso que cambiara algo ¿Cambiaría para todas las instancias?

**Comment by Dunkan1** [comment]
revisa el siguiente link:
https://es.stackoverflow.com/questions/936/c%C3%B3mo-son-los-m%C3%A9todos-de-una-clase-python-por-defecto

es tu misma pregunta pero con metodos y queda muy bien explicado :smile:
