### ISSUE TITLE
duda de self.frame en AY08

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#761]
Hola!
Revisando el código de la solución de la AY08, me surge la duda del significado de ```self.__frame```, por qué usan éste atributo y que significa ¿? 
Específicamente lo ví en el módulo ```classes.py``` en ```Morty()``` ..

**Comment by lucasvsj** [comment]
Hola @Camila-sty 
Usamos `self.__frame` como un "id" de las imagenes que van apareciendo en el juego. 
Voy a explicar `self.frame` para ojalá dejarlo lo mas claro posible (me basaré en Morty, pero esta explicación sirve para cualquier caso):
Primero se crea el atributo y lo dejamos con un valor de  0:
`self.__frame = 0`
Hacemos esto ya que así (como sale comentado en la ayudantia) determinamos el frame (sprite) inicial de Morty (el cual será morty_0.png)
Luego, como `self.frame` es una **property**, determinamos su **getter** y **setter**.
**getter**: No tiene mucha ciencia, solo obtenemos (retornamos) el valor de `self.__frame`
```python
    @property
    def frame(self):
        return self.__frame
```
**setter**: Aquí es donde nos preocupamos de que el valor fluctúe entre 0 y 2, ya que, como puedes ver en los sprites, estos van desde 0 a 2 (ejemplo: morty_0.png, morty_1.png, morty_2.png) 
```python
    @frame.setter
    def frame(self, value):
        if 2 < value:
            self.__frame = 0
        else:
            self.__frame = value
```
Espero que con esta explicación te haya quedado mas claro el uso de este atributo, de lo contrario dime que es lo que aún te complica y feliz te lo explicaré

**Comment by Camila-sty** [comment]
Entiendo lo del setter y getter. Pero aún me queda la duda de por qué de creo este atributo?
No entiendo cual es la idea de crear esto para sacar las sprites de Morty...

**Comment by lucasvsj** [comment]
Continuare explicando el flujo de `self.frame`, ahora con la conexión con el **frontend**, para ver si así se aclara tu duda.
Ya que tenemos la property frame completa, ahora voy a explicar como la usamos (cual es su función):
Supongamos que `self.frame = 0` y que Morty se ha desplazado en el eje X
**BACKEND:**
Si te fijas en el **setter** de la property **x** tenemos lo siguiente (usaré **x** de Morty, pero esto se cumple para cualquier caso en que exista movimiento, tanto eje X, como eje Y):
```python
    @x.setter
    def x(self, value):
        if -40 < value < self.display_x - 48:
            self.__x = value
            self.update_position_signal.emit(
                {'char': self._id,
                 'x': self.x,
                 'y': self.y,
                 "frame": self.frame,
                 "sprite": "morty_normal" 
                 })
```
Como puedes ver, dentro del diccionario que emitimos con la señal **update_position_signal** se encuentra lo siguiente:
```python
"frame": self.frame
```
Aquí estamos enviando la información de `self.frame` al **frontend**.
**FRONTEND:** (main_window.py)
Aquí se encuentra el siguiente método, el cual se encarga de actualizar el forntend (en este ejemplo, de Morty):
```python
    def update_position(self, event):
        char = self.characters[event["char"]] #Accedemos al QLabel correspondiente
        if event.get("sprite"): #Usamos event.get() ya que event es un diccionario y get() es un metodo seguro de acceder a una key del diccionario
            pixmap = gui.QPixmap(
                f"sprites/{event['sprite']}_{event['frame']}.png")
            pixmap = pixmap.scaled(32, 32)
            char.setPixmap(pixmap)
        elif event.get("delete"):
            char.setPixmap(gui.QPixmap(None))
            return
        char.move(event['x'], event['y'])
        self.update() 
```
En este método voy a detenerme en las siguientes lineas de código:
```python
            pixmap = gui.QPixmap(
                f"sprites/{event['sprite']}_{event['frame']}.png")
```
Como puedes ver aquí estamos definiendo el `QPixmap` que irá dentro de nuestro `QLabel` (en este caso nuestro `QLabel` lo accedemos con `char`, ya que ahí es donde lo guardamos). Como tenemos que pasarle el path de la imagen a `QPixmap()` lo hacemos en el siguiente `string`:
```python
                f"sprites/{event['sprite']}_{event['frame']}.png")
```
Donde, si traducimos este `string` (reemplazando los valores de las variables) obtendremos:
```python
                f"sprites/morty_normal_0.png")
```
Es por esto que anteriormente me referí a `self.frame` como un "id" (identificador) de imagenes. Ya que si te fijas en la carpeta `sprites` tenemos las siguientes imagenes relacionadas al movimiento de Morty en el eje X:
**morty_normal_0.png**
**morty_normal_1.png**
**morty_normal_2.png**
Ojalá al explicar la conexión del **backend** con el **frontend** se haya aclarado tu duda.

**Comment by Camila-sty** [comment]
Sí, entendí, gracias :smile:
