### ISSUE TITLE
Duda sobre requisitos avance

### ISSUE THREAD

**Issue by sofiaolmedos** [IIC2233/syllabus#761]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Quería saber que cosas tiene que tener el avance además del funcionamiento. Por ejemplo, si es necesario que el código esté separado en back y front, o que los parámetros que se usen esten en parametros.py.

**Comment by jaimecoloma** [comment]
Hola @sofiaolmedos !! Para el avance no debes preocuparte 100% de esos aspectos, es decir basta con cumplir lo señalado explicitamente para recibir las dos decimas. Ahora la idea es que desde el principio sean capaces de separar el código en back y front end, hagan uso correcto de parametros.py y usen señales para conectar, pero de lo contrario, lo que mencioné irá como feedback para que cambien o sepan que tan bien encaminados van.
Espero haber resuelto tu duda!
Mucho éxito 😄

**Comment by sofiaolmedos** [comment]
@jaimecoloma muchas gracias!!
