### ISSUE TITLE
borrar notas

### ISSUE THREAD

**Issue by joaquineichholz** [IIC2233/Syllabus#761]
hola, en la pauta aparece "Hacer click en una nota la elimina de la canción", es valido poner un boton que borre la nota que esta seleccionada? o ¿debo hacerlo específicamente de esa manera?

gracias!

Pd: ya lo tengo implementado...

**Comment by leolivares** [comment]
Hola! @joaquineichholz 
Si, lo puedes implementar de esa manera.

**Comment by mplazadelosreyes** [comment]
Hola! Tengo una pregunta parecida, en la pauta dice "Hacer click en una canción permite abrir
la ventana de edición de la canción en modo espectador". 
Puedo crear un botón que abra la sala de edición en modo espectador de la canción seleccionada, en vez de que sea solo con un click?

Gracias!!

**Comment by leolivares** [comment]
@mplazadelosreyes Hola. No hay problema, mientras cumpla con los requerimientos pedidos en el enunciado y sea claro en la interfaz.

**Comment by mplazadelosreyes** [comment]
Ok gracias!!
