### ISSUE TITLE
libpng error: PNG unsigned integer out of range

### ISSUE THREAD

**Issue by mjgutierrez1** [IIC2233/Syllabus#762]
Cuando entro al dashboard mando los bytes de las imágenes desde el server al cliente y del cliente a su interfaz a través de una señal. Luego en el frontend se guardan las imágenes. Todo eso ocurre bien (llegan la misma cantidad de bytes que fueron enviados; las imágenes se guardan bien y es posible abrirlas).

El problema ocurre cuando a los 6 labels que tengo en la interfaz les agrego un pixmap, específicamente al hacer "pixmap = QPixmap(path).scaled(141, 141)". Las imágenes originales se agregan bien en el label, pero  algunas imágenes editadas por mi no se agregan y se levanta el error del título de la issue. Esto es muy raro, ya que como dije antes esas imágenes editadas por mi se guardan correctamente y es posible abrirlas y verlas bien. Además ocurre que estos errores no impiden que el programa siga corriendo.

Busqué este error pero no he podido solucionar el problema.

**Comment by SarahEverke** [comment]
lo pudiste solucionar? Que me pasa lo mismo :(

**Comment by mjgutierrez1** [comment]
Lamentablemente no lo pude solucionar
