### ISSUE TITLE
Que pasa cuando el que esta editando una canción cierra la sala de edición

### ISSUE THREAD

**Issue by ljrodriguez1** [IIC2233/Syllabus#762]
Hola mi duda es la siguiente, como quieren que modelemos las salas de edición.
Si el que esta editando que seria como el admin cierra la ventana de edición debo echar a todos los que están observando diciendo que el que edita se ha salido o ellos pueden continuar en la sala.
¿si es que pueden continuar, uno de ellos debe poder editar?, ¿que ocurre con los mensajes?: si la sala es cerrada ya que no queda nadie dentro se pierden los mensajes y se eliminan o cada canción debe ademas tener una sala asociada que guarde los mensajes por ejemplo en un archivo de texto.

**Comment by leolivares** [comment]
Hola! @ljrodriguez1 
1. Si el usuario que se encuentra editando se retira, queda a tu criterio que hacer con los otros usuarios.
2. Si es que continuan en la sala, también queda a tu criterio que ocurre. Puedes seleccionar a uno para que edite, como propones.
3. Los mensajes del chat deben visualizarse siempre, quedan registrados, aunque todos se retiren.
Espero haber aclarado tus dudas. 

Saludos.
