### ISSUE TITLE
Ignorar archivos .ui

### ISSUE THREAD

**Issue by amparostevens** [IIC2233/syllabus#762]
Hola!
En el `.gitignore` se deben ignorar los archivos `.ui` que usé para crear las ventanas o también deben subirse?

**Comment by Alonsinho1** [comment]
Hola deberas subirlos, ya que si no los subes no se podrá revisar si hiciste la ventana o no.

Alfinal es parte de tu código y no es solo una imagen.

Debes subir todas las cosas que hayas hecho tu (Posibles sprites, ventanas, etc)
