### ISSUE TITLE
Bonus: Cheatcode adicionales

### ISSUE THREAD

**Issue by enriquemolinare** [IIC2233/syllabus#762]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
En la seccion de cheatcodes adicionales. No me quedó claro a que se refieren con " Además, siempre aparecerá una sola flecha por fila al utilizar estos comandos especiales". Es decir, una vez que se usa el cheatcode especial en una fila, en esa fila no puede aparece otra flecha de cheatcode especial? 

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by jaimecoloma** [comment]
Hola @enriquemolinare ! A lo que se refiere el enunciado es que si usas cualquiera de esas combinaciones debe aparecer **sólo una** flecha especial en ese instante, es decir que para el segundo t que se usa el cheatcode no deben aparecer 2 flechas especiales, debes generar sólo una, pero si se puede volver a ocupar el cheatcode y que aparezca en el mismo carril.
Espero haberte ayudado! Mucho éxito 😃
