### ISSUE TITLE
threading - locks [ejemplo]

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2233/Syllabus#762]
No entiendo por que solo se imprimirá "thread - 1" en este código, ya que por lo que veo hay un momento en que ninguno de los locks esta´n ocupados y podría ahí meterse el thread 2 y la impresión podría ser bastante aleatoria. En definitiva no entiendo que me dice claramente que nunca se ejecutará el print del thread 2.
```
def thread_f(lock1, lock2, name):
    while True:
        with lock1:
            with lock2:
                print(name)


x_lock = threading.Lock()
y_lock = threading.Lock()

t1 = threading.Thread(target=thread_f, args=(x_lock, y_lock, "thread - 1"))
t1.daemon = True
t1.start()

t2 = threading.Thread(target=thread_f, args=(y_lock, x_lock, "thread - 2"))
t2.daemon = True
t2.start()
```

**Comment by jgramsch** [comment]
Lo que creo, 
es que primero pasa es que el thread uno toma el lock x, luego el lock y hace print y toma el x de nuevo, etc.
con esto el thread que ya está esperando el lock y puede tener una oportunidad de tomarlo cuando el thread 1 solo tiene el lock x. 
Pero para que el thread 2 obtenga el lock x  el thread 1 tiene que soltarlo y podriamos decir que nunca pasa por que el 1 lo va a tener siempre dado que es su Lock_1.

Eso es lo que se me ocurre en verdad jaja no sé si estará bueno.
Que la fuerza te acompañe!

**Comment by Dunkan1** [comment]
no se si te sirva pero yo lo entendi asi
piensalo como una carrera el thread 1 tiene 2 puertas primero esta la 1 y luego la 2
el thread 2 tiene primero la puerta 2 y luego la 1
ambos son igual de rapidos pero el thread 1 parte con ventaja

![captura de pantalla de 2017-07-03 16-28-32](https://user-images.githubusercontent.com/26102365/27807195-36476300-600d-11e7-94df-6bb6001f4d50.png)

ademas la carrera tiene un tiempo muy corto(como son daemons cuando acabe el programa principal ambos threads mueren)
el thread 1 juega y  para cuando  el thread 2 logra empezar el juego ya acabo :sob:

caso 2) le quitas los daemons
ahora el juego no tiene porque acabar
(si lo haces en consola el thread 1 sigue siendo el unico que imprime)
el thread 1 le bloquea dos entradas, la entrada 1 y la entrada 2 al thread 2
luego escribe su nombre en una hoja y libera la entrada 2 y luego la 1,
para cuando el thread 2 parte puede que tenga que esperar hasta que se desbloquee la entrada 2
cuando pasa el la bloquea luego sigue a la entrada 1 y sorpresa esta bloqueada por el thread 1 que aun sigue jugando y ha bloqueado su primera puerta
el thread 1 por su parte luego de bloquear la puerta 1 va hacia la puerta 2 y sorpresa esta bloqueada
por el thread 2 en este caso tienes un deadlock y el programa no termina nunca lo unico que queda impreso es lo que hizo el thread 1 antes que el 2 comenzara

**Comment by jorgeriesco** [comment]
@Dunkan1 me gustó la explicación, gracias

**Comment by MainScientist** [comment]
Este tema toca cosas que no corresponden a este curso, pero que de todas formas es interesante saber. El problema es que los threads en python no corren en cores paralelos por los que el sistema operativo los tiene que coordinar (es decir, el sistema operativo elige que thread correr y lo hace tan rapido que pareciera que corren simultáneamente).

El problema aquí es que el sistema operativo por lo general no se entromete en los programas que están corriendo, sino que espera a que estos ejecuten lo que se suele llamar como una *interrupción de software*. No estoy seguro de lo que voy a decir, pero parece que al hacer `lock.acquire()` y `lock.release()` tan rápido que el `thread-1` no *"le da tiempo"* al `thread-2` (en realidad al sistema operativo) de darse cuenta que el lock por el que espera fue liberado.

¿Por qué lo digo? Vean los siguientes códigos:

#### Código 1: Normal
```python3
def thread_f(lock1, lock2, name):
    while True:
        with lock1:
            with lock2:
                print(name)
        time.sleep(1)


x_lock = threading.Lock()
y_lock = threading.Lock()

t1 = threading.Thread(target=thread_f, args=(x_lock, y_lock, "thread - 1"))
t1.daemon = True
t1.start()

t2 = threading.Thread(target=thread_f, args=(y_lock, x_lock, "thread - 2"))
t2.daemon = True
t2.start()
```

En este código todo funciona bien, asumo porque esto le da tiempo al `thread-2` de ser ejecutado sin ningún problema mientras el `thread-1` descansa. *NOTA: time.sleep y print generan interrupciones de software*

#### Código 2: Deadlock
```python3
def thread_f(lock1, lock2, name):
    while True:
        with lock1:
            with lock2:
                print(name)
            time.sleep(1)


x_lock = threading.Lock()
y_lock = threading.Lock()

t1 = threading.Thread(target=thread_f, args=(x_lock, y_lock, "thread - 1"))
t1.daemon = True
t1.start()

t2 = threading.Thread(target=thread_f, args=(y_lock, x_lock, "thread - 2"))
t2.daemon = True
t2.start()
```

Usando el ejemplo de @Dunkan1 esto se podría ver como que ambos threads esperan en la mitad de la puerta, por lo que el thread 1 va, escribe su nombre y al devolverse 'espera' entre la puerta 1 y la puerta 2, esto hace que `thread-2` entre por la puerta 2 y espere a que el `thread-1` libere la puerta 1, pero como el thread 1 la libera y la vuelve a tomar, de nuevo, muy veloz mente. el `thread-2` se queda esperando cuando el `thread-1` vuelve a entrar por la puerta 1 y, como `thread-2` ya había entrado por la puerta 2, ambos se quedan esperando a que estas sean liberadas.

#### Código 3: Starving
```python3
def thread_f(lock1, lock2, name):
    while True:
        with lock1:
            with lock2:
                print(name)
                time.sleep(1)


x_lock = threading.Lock()
y_lock = threading.Lock()

t1 = threading.Thread(target=thread_f, args=(x_lock, y_lock, "thread - 1"))
t1.daemon = True
t1.start()

t2 = threading.Thread(target=thread_f, args=(y_lock, x_lock, "thread - 2"))
t2.daemon = True
t2.start()
```
Esto es lo mismo que el código inicial, el `thread-1` toma los locks tan rápido que no le deja espacio de ejecución al `thread-2`.

Lo que me causa confusión es que el llamado a `lock.acquire()` y `lock.release()` debería también ejecutar una interrupción de software, pero (de mas probable a menos probable)
1. Derechamente no la está haciendo.  
2. La hace, pero cuando el sistema operativo cree que es momento de quitar `thread-1` por `thread-2` el lock que este espera se encuentra tomado y por lo tanto `thread-2` no se ejecuta. 
3. La hace y el sistema operativo cree que nunca es momento de cambiar `thread-1`.
4. La hace, pero las interrupciones de locks no llaman al scheduler.

#### Bonus: The more you know
Las interrupciones de software son llamados al sistema operativo para que éste haga algo por el programa (leer un archivo, escribir un archivo, time.sleep, etc.). El sistema operativo aprovecha estos llamados para cambiar el thread que se está ejecutando y también para cambiar procesos (cambiarlos de core, ponerlos en espera o reanudarlos). Cuando un programa en python hace `while True` sin ningún llamado a una interrupción de software este se apoderará de su cpu y usará el 100% (si tienen más de un core este porcentaje se distribuirá entre ellas).

```python3
c = 0
while True:
    c += 1
```

**Comment by MainScientist** [comment]
### Código 3: ¿Deadlock?

Creo que lo tengo. Vean los siguientes dos códigos:

##### Codigo 3.1: Deadlock ✔️
```python3
def thread_f(lock1, lock2, name):
    while True:
        with lock1:
            with lock2:
                print(name)


x_lock = threading.Lock()
y_lock = threading.Lock()

t1 = threading.Thread(target=thread_f, args=(x_lock, y_lock, "thread - 1"))
t1.daemon = True
t1.start()

t2 = threading.Thread(target=thread_f, args=(y_lock, x_lock, "thread - 2"))
t2.daemon = True
t2.start()
```


##### Codigo 3.2: Deadlock ❌ 

```python3
def thread_f(lock1, lock2, name):
    c = 0
    while True:
        with lock1:
            with lock2:
                c += 1
        print(name, 'c=', c)


x_lock = threading.Lock()
y_lock = threading.Lock()

t1 = threading.Thread(target=thread_f, args=(x_lock, y_lock, "thread - 1"))
t1.daemon = True
t1.start()

t2 = threading.Thread(target=thread_f, args=(y_lock, x_lock, "thread - 2"))
t2.daemon = True
t2.start()
```

En el código 3.1 sí ocurre el deadlock, pero en el código 3.2 no! ¿Por qué? No sé xD, pero mi intuición es la siguiente.

Primero, el sistema operativo le asigna un tiempo a los threads, es decir, antes de cambiar un thread por otro, verifica que este thread se haya ejecutado durante **al menos** N segundos/ciclos de CPU.

Segundo, este tiempo es ínfimo, realmente pequeño. Sin embargo `c+=1` es aun más pequeño, mientras que `print` probablemente demore mucho más tiempo que el mínimo asignado a los threads.

Tercero, por esto, cuando se ejecuta el `print` el sistema operativo lo unico que quiere es cambiar de thread, por lo que en el código 3.1, apenas pueda cambiar a `thread-1` lo hará (esto es, apenas libere su lock 2, por lo tanto, al liberarlo pone al `thread-2` quien toma su lock1 y se genera el deadlock). Como c+=1 toma tan poco tiempo, solo al ejecutar `print`, el sistema operativo creerá que es hora de cambiar de thread, por lo tanto el deadlock no ocurrirá.

## Conclusión final
La idea de este ejemplo es mostrarles que los threads no deben ser tomados a la ligera, existen muchos casos en los que es muy difícil ver si se puede generar o no un deadlock, por lo tanto, la idea es que esto les sirva para tenerles respeto a los threads y tratar de detectar todas las posibles complicaciones que les podrían surgir. Este tipo de deadlocks en que se adquieren locks con órdenes distintos puede no ocurrir bajo ciertas condiciones, pero por lo general siempre es muy probable que ocurra, ergo el énfasis en que deben preocuparse el triple al escribir código que usa threads y locks.
