### ISSUE TITLE
README.md y .gitignore en el avance

### ISSUE THREAD

**Issue by lewebe** [IIC2233/syllabus#763]
Hola! He avanzado con más cosas que solo cargar el mapa. En específico, Hice una ventana inicial que al presionar el botón "Reanudar Partida" te lleva a otra ventana con el mapa cargado. Todo esto se debe correr desde un archivo ```main.py```. Mi pregunta es si al momento de subir mi avance debo hacerlo con un ```README.md``` para especificar lo que hay que hacer para conseguir cargar mi mapa y que el ayudante no se confunda y crea que no lo he logrado. Aprovechando, me gustaría preguntar también si debo subir un ```.gitignore``` con mi avance.

**Comment by jbulness** [comment]
Hola @lewebe,

No es necesario que subas un `README.md`, ya que, por lo que dices, al seguir el flujo de tu programa finalmente se llegará a lo pedido. Lo que sí, puedes agregar comentarios en tu código para señalar ciertas cosas que quieras que queden claras o que el/la ayudante tenga en consideración al revisar tu avance.

Con respecto al `.gitignore`, si bien no se evalúa en el avance, si se considera una buena práctica que lo implementes en todo momento.

**Comment by lewebe** [comment]
Gracias! Y tenemos que subir la carpeta "sprites" o los archivos .csv?

**Comment by jbulness** [comment]
Depende, si usas sprites propias debes subirlas, pero si solo ocupas las que nosotros te damos no es necesario. Los archivos .csv no es necesario que los subas.

**Comment by Camila-sty** [comment]
@jbulness pero si las coordenadas del archivo ```mapa.csv``` fueron cambiadas, necesitaría subir este archivo para que cargaran bien la imágenes.. se puede hacer esto?
