### ISSUE TITLE
Puntaje intermedio tarea 06

### ISSUE THREAD

**Issue by meretamal** [IIC2233/Syllabus#763]
Hola, en el punto 3.4 se menciona que: "Para tener el puntaje en cada ítem, su código debe realizar todo el proceso de forma exitosa. No se dará puntaje intermedio por realizar algunas partes del ítem, pero otras no". Quería preguntar si esto solo se toma en cuenta para este punto específico (Evaluar MIDI), o es para cada punto de la tarea.

Gracias de antemano.

**Comment by leolivares** [comment]
Hola! @meretamal 
Sí, es para ese punto en específico.
