### ISSUE TITLE
formulario recorreccion

### ISSUE THREAD

**Issue by eliasbruchfeld** [IIC2233/syllabus#763]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

Hola! en el formulario de recorrección de la tarea 1, al final dice si quiero recorregir T00: Descuentos...supongo que deberia decir T01 o no? o los descuentos de la T01 se van a recorregir despues.

**Comment by lily416** [comment]
Hola @eliasbruchfeld,
 
Tal como dices, eso corresponde a un error, debería salir T01 en vez de T00. Si quieres mandar a recorregir algo relacionado a los descuentos en la T01, debes rellenar esa sección.
 
Ya se corrigió el error en el formulario, por lo que ya no debería causar más confusión.
 
Muchas gracias por avisar 🙇. 
Saludos y que tengas una buena semana 👋🗻.
