### ISSUE TITLE
Metaclases

### ISSUE THREAD

**Issue by Arcoirisky** [IIC2233/Syllabus#763]
¿Por qué funciona como Metaclases una clase cualquiera que no hereda de Type pero que tiene los métodos __new__, __init__, __call__? (El ejercicio lo saqué de la guía de estudio del semestre pasado)

**Comment by jorgeriesco** [comment]
No soy ayudante, pero según entiendo, todo hereda de type, a menos que especifiques que herede de otra cosa. Por lo tanto cuando especifican que hereda de type, me parece que es redundante y lo harían para que resaltar esa idea. Pero esto es solo una conjetura jaja.

**Comment by rfenzo** [comment]
No me queda claro porque el siguiente codigo no funciona:
`class Meta):

    def __new__(cls, name, parents, dict):
        return super().__new__(cls, name, parents, dict)


class A(metaclass=Meta):
    pass`

**Comment by stephichau** [comment]
@rfenzo Meta debe heredar de type!

```
class Meta(type):

    def __new__(cls, name, parents, dict):
        return super().__new__(cls, name, parents, dict)

class A(metaclass=Meta):
    pass
```

**Comment by Dunkan1** [comment]
@rfenzo  no te funciona?
![captura de pantalla de 2017-07-03 19-11-25](https://user-images.githubusercontent.com/26102365/27810022-722fc36a-6023-11e7-8ef5-64afdab6d33e.png)

**Comment by andresfdezc** [comment]
@jorgeriesco Todo hereda de `object`, no de `type` necesariamente. Por su parte, `type` es la metaclase por defecto de cualquier clase, es decir, toda clase es una instancia de `type` en algún grado.

**Comment by rfenzo** [comment]
Sé que nos enseñaron heredando de type, pero quien originó ésta issue dice que en un examen practicamente afirmaban que no era necesario, o al menos eso entendí jaja.

**Comment by fringlesinthestreet** [comment]
@Arcoirisky Todas las clases en python pueden sobreescribir los métodos \_\_new\_\_, \_\_init\_\_ y \_\_call\_\_. 
La diferencia ocurre cuando una clase hereda de type. 

En la guía para el examen del semestre pasado, la clase Examen no se comporta como una Metaclase.

**Comment by Arcoirisky** [comment]
@fringlesinthestreet oooooooh, que trampa O:!
Gracias!!
