### ISSUE TITLE
Logo en gigante

### ISSUE THREAD

**Issue by Mario-uc** [IIC2233/syllabus#764]
Cuando hago layout de todos los elementos (un layout  horizonta entre el logo y layouts verticales ) el logo me aparece en gigante.  Cual(es) podría(n) ser la(s) posible(s) causa(s)?

**Comment by matiasmasjuan** [comment]
Hola @Mario-uc  !

Creo que tu problema es similar a uno de los comentarios de la **Issue** #690 .

Al parecer, este problema está asociado más que nada porque la imagen del Logo de DCCafé es un poco grande 😅 y por eso se agranda tanto el Vertical Layout. Te puedo recomendar dos situaciones:

* No utilizar un un Layout para trabajar con el logo del DCCafé (sólo usar un ***Qlabel*** si estas trabajando con **QtDesigner**).
* Que **manualmente edites** el logo del DCCafé volviéndolo más **pequeño** y lo guardes en una carpeta nueva en tu repositorio. Si quieres darle un nombre **reconocible**, puedes nombrar esta como **assets**, y ubicar las **imagenes** **tuyas** (y por ende no en la carpeta ***sprites***) allí.

En todo caso, es algo sumamente particular con respecto al logo, asi que esto no pasará con los demás sprites.

Mucho éxito con la tarea! 😄
