### ISSUE TITLE
Jupyter Notebooks para PyQt5

### ISSUE THREAD

**Issue by tomasnusser** [IIC2233/syllabus#764]
Hola, tengo un problema usando Jupyter. La verdad es que no lo había usado en otras instancias del curso ya que no lo vi necesario pero ahora con interfaces gráficas estoy muy complicado y por eso quise usarlos. 
La cosa es que al entrar no entiendo como hacerlos funcionar porque al parecer PyQt5 no corre en Jupyter entonces no entiendo como usarlo para poder ver los ejemplos que están incluidos en los contenidos.

**Comment by knight-who-say-ni** [comment]
Hola @tomasnusser !!

Como se menciona en el primer notebook de la semana 9 "Lamentablemente, Jupyter no fue creado con la intención de ejecutar código de GUIs de escritorio, por lo que se hace difícil ejecutar e interctuar con las interfaces a través de esta herramienta. Para entender los ejemplos de código presentados en el material de esta semana, recomendamos fuertemente que ejecutes los scripts de interfaces gráficas desde tu propio computador, y NO en este notebook."

Así, si quieres probar el codigo, deberás crear otro archivo .py, copiar y pegar el codigo del Jupyter Notebook y ejecutar este otro archivo ;).  Saludos!!
