### ISSUE TITLE
Percepción del efecto blurry al ver imagen

### ISSUE THREAD

**Issue by vixolo** [IIC2233/Syllabus#764]
Hola! 

Creo que estoy siendo capaz de aplicar el efecto _blurry_, pero como el algoritmo que nos propusieron hace la ponderación del color a nivel pixel y las imagenes que nos entregaron tiene una resolución relativamente alta, no solo se demora en funcionar sino que la imagen "blurreada" se ve prácticamente igual a la original. Lo hice siguiendo las indicaciones del enunciado y tomando los pixeles originales como se indica en la #737 .

En una imagen de 15x15 el efecto sería mucho más notorio, pero para que realmente se viera más borroso habría que ir ponderando áreas más grandes en estas resoluciones. Cuando se hace zoom a la imagen de alta resolucion se puede ver que las fronteras donde cambia el color se ponen más difusas.

Lo comento porque en la interfaz no se va a poder apreciar bien cuando se le haga "blurry" a una imagen.

Saludos

**Comment by Kitaps** [comment]
Pero si le vas aplicando blurry varias veces a la misma imagen se va viendo mas blurry cada vez. Demás haya que hacer eso?
