### ISSUE TITLE
Problema con caida de flechas

### ISSUE THREAD

**Issue by BFry712** [IIC2233/syllabus#765]
### Prerrequisitos

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Holaa! necesito ayuda con un problema de mi codigo. El problema que tengo es que el thread que va controlando las flechas cuando caen, no va eliminando las flechas de arriba. Saludos!

**Comment by manearaya** [comment]
Hola @BFry712!

Si te refieres a que las flechas no desaparecen una vez terminado su recorrido, quizás te falta un método para que estas desaparezcan de la ventana, ya que programar solo el movimiento no necesariamente cubre esto.

Mucho éxito!
