### ISSUE TITLE
Recorrección final con otro alumno

### ISSUE THREAD

**Issue by vijuarez** [IIC2233/Syllabus#765]
Hola! Estoy fuera de Santiago y me es imposible ir a la recorrección del jueves, pero un compañero del curso está dispuesto a ir por mi y echarle una mirada al examen (nada muy raro, solo ver que hayan revisado todos los ítems y si no hay ningún error muy grande). Es posible que le den a el mi examen o estoy condenado a que nadie lo revise? 

Muchas gracias!!

**Comment by flobarrios** [comment]
Puede ir tu compañero ! 
Saludos
