### ISSUE TITLE
Problema importación archivo ui (ModuleNotFoundError)

### ISSUE THREAD

**Issue by AAVP** [IIC2233/syllabus#766]
Al momento de querer inicializar mi ventana diseñada en Qt Designer a través de Python, la consola me arroja el siguiente problema:

![Captura de Pantalla 2020-05-20 a la(s) 13 53 54](https://user-images.githubusercontent.com/62061212/82480155-63067080-9aa1-11ea-97e0-411b6672e531.png)

Según yo el código está bien implementado pero no sé qué hacer para continuar con el trabajo. La verdad daría más información pero imagino que es info personal, así que cualquier cosa estoy disponible por correo electrónico o discord (aavalenzuela1@uc.cl, AAVP es mi username en Discord)

**Comment by aaossa** [comment]
Hola @AAVP , asumo que tienes una imagen en tu código, quizás te sirva ver la *issue* #690 . 

PS: También, según tu *path*, parece que estás usando Python 3.8. Recuerda que en el curso usamos Python 3.7, así que ojo por si tienes algún problema o no estás seguro si algo está en Python 3.7 😅
