### ISSUE TITLE
Como matar un QTimer despues de determinado tiempo

### ISSUE THREAD

**Issue by diegobustosk** [IIC2233/syllabus#766]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola mi duda es como puedo matar un QTimer despues de pasado x Cantidad de segundos. Y tambien al matar el QTimer hay alguna señal que se dispare cuando muere ?

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by bvasquezm** [comment]
Hola @diegobustosk!

Si buscas “matar” un ``QTimer`` después de determinado tiempo, podrías pensar en usar un ``QThread`` en su lugar, pero si lo que buscas es que realice un cierta cantidad de rutinas, existen algunos métodos que te pueden permitir hacer eso. Particularmente puedes investigar los métodos ``deleteLater()``, ``setSingleShot()`` o incluso ``start()``. Revisa documentación o páginas como stackoverflow para que te quede más claro (te dejaría un link, pero por alguna razón se borra jajaj). Saludos!
