### ISSUE TITLE
Quitar notas de una canción

### ISSUE THREAD

**Issue by llloyola** [IIC2233/Syllabus#766]
En el enunciado, dice que un usuario deberá poder eliminar una nota de una canción, haciendo click en ésta. Sin embargo, ¿cómo podemos hacer que el usuario en cuestión pueda agregar una nota en medio de la canción, si al hacer click en la posición deseada, termina eliminando una nota?

¿Puedo agregar un botón "Quitar Nota"? Mi idea es que al clickear una nota, el usuario pueda:

1. Eliminar dicha nota, mediante el botón "Quitar Nota"

2. Agregar una nueva nota entre la seleccionada y la siguiente, usando el botón "Agregar Nota"

**Comment by leolivares** [comment]
Hola! @llloyola 
No se espera que puedan agregar notas en medio de otras, solo al final.
En cuanto al botón para eliminar, si se puede. Se mencionó en la issue #761.
Si te encuentras con tiempo y quieres agregar notas entre otras, indícalo en el ReadMe.

**Comment by llloyola** [comment]
Como diría un alumno PUC promedio, "mató, perro" jajajaj Gracias :)
