### ISSUE TITLE
Nota mínima de aprobación examen 

### ISSUE THREAD

**Issue by fantinee** [IIC2233/Syllabus#766]
hola, como ya subieron puntaje de 3 preguntas del examen quería saber si podrían dar el dato de con cuantos puntos se alcanza el 3.5  
gracias :)

**Comment by iqacevedo** [comment]
Hola

Con 50 puntos.

Saludos !

**Comment by Dunkan1** [comment]
y todavia falta la pregunta 1 o esas son todas?
