### ISSUE TITLE
Editar labels de qtdesigner

### ISSUE THREAD

**Issue by jaimecoloma** [IIC2233/syllabus#767]
Hola! Tengo ya hecho el mapa vacío del juego junto con la tienda y los botones y datos de arriba, sin embargo tengo la duda (y el miedo) de que nose si se pueden editar los labels que usé al crear la ventana. Esto porque ahora trabajando en python no se como acceder a ellos. Ya tengo el codigo con al archivo importado .ui pero no se como modificar por ejemplo el nivel de reputación (como acceder al label para editarlo con código me refiero) o al dinero generado. He estado buscando información pero no he encontrado mucho y me quede un poco pegado :(

**Comment by matiasmasjuan** [comment]
Hola @jaimecoloma !

El gran **beneficio** de utilizar **QtDesigner** es que te permite **acceder** rápidamente a los **nombres** de los ***Qlabels*** creados en él y **modificarlos** cuando lo estimes necesario.

Por ejemplo, si creamos un documento **.ui** en **QtDesigner** notaremos que se es necesario escribir el **nombre** de los **atributos** que se **utilizarán** en nuestro **código**. En este caso, los nombres de dos labels son: *label_logo* y *label_1*.

![editar_1](https://user-images.githubusercontent.com/48495638/82482533-00af6f00-9aa5-11ea-83c5-1060967c6775.PNG)
 
Si corremos el archivo, notaremos que se abre la ventana creada.

![editar_2](https://user-images.githubusercontent.com/48495638/82482867-7e737a80-9aa5-11ea-82bb-20aa6b62fe51.PNG)

Ahora bien, si modificamos los **atributos** de la ventana a través de código, también se modificarán en la ventana. **Notar** que utilizamos los mismos nombres definidos en **QtDesigner**.

![editar_3](https://user-images.githubusercontent.com/48495638/82483046-bc709e80-9aa5-11ea-81ac-301ac0e15fda.PNG)

Y se podrán **observar** los cambios.

![editar_4](https://user-images.githubusercontent.com/48495638/82483078-ceead800-9aa5-11ea-99b8-36f5211ce0ef.PNG)

Lo mismo se puede hacer para cambiar las **imagenes**, o cualquier otro **método** del **Qlabel**.

![editar_5](https://user-images.githubusercontent.com/48495638/82483128-e9bd4c80-9aa5-11ea-9748-88180c87af56.PNG)

Espero que te sirva de ayuda, y mucho éxito con la tarea! 😄

**Comment by jaimecoloma** [comment]
Muchisimas gracias! Como VS Code no me los mencionaba pensé que quizas tendría algo malo, ahi me funcionó!

**Comment by tcouso** [comment]
Hola! Tengo dudas con algo semejante. Quiero sobrescribir algunos métodos (en vez de atributos, como se muestra aquí) de un label que definí en qtdesigner, específicamente para implementar drag'n drop. Basicamente, me interesa poder personalizar labels creados en qtdesigner (he encontrado algunos recursos para hacer esto en la documentación de Qt, pero estaban especificados para C++). Se agradece mucho cualquier ayuda!

**Comment by matiasmasjuan** [comment]
Hola @tcouso !

Lamentablemente, no conozco la forma en la que puedas sobrescribir los métodos de un **QLabel** directamente (y lo más probable es que no se pueda). Lo que te recomiendo, si es para trabajar con *Drag'n Drop*, es definir otra clase que herede de *Qlabel*. De esta manera, puedes definir este label como una instancia de esta clase, y tendrás los mismos métodos que la clase *Qlabel* ya que esta heredando de ella, además de que puedes agregar y sobrescribir los métodos que estimes conveniente. Si bien es cierto que esto impediría su creación a través de *QtDesigner*, la diferencia no es más que dos o tres líneas de código extra, ya que a través de código puedes definir las coordenadas, colores, *Pixmap* y toda la personalización que tenías en el *Qlabel* hecho con anterioridad en *QtDesigner*.

Saludos y mucho éxito con la tarea! 😄

**Comment by tcouso** [comment]
Perfecto, estaba pensando usar esa aproximación. Encontré una manera de hacerlo a partir de **_QGraphicsScene_** , una de las clases incluidas en _QtWidgets_. Está permitido su uso? Pienso de antemano que no, al formar parte de _PyQt5_, pero aún así prefiero asegurarme.

Gracias por la ayuda!! Saludos!!

**Comment by matiasmasjuan** [comment]
**Sí**, puedes hacer uso de ***QGraphicsScene*** para esta tarea. Te recomiendo que ojalá este tipo de dudas las realices mediante la *Issue* #680 que especifíca con mayor detalle las librerías permitidas y las no permitidas.

Finalmente, te recomiendo de que antes de que empieces con la implementación, mires esta la *Issue* #716 ya que te podría otorgar información acerca del uso de ***QGraphicsScene***.

Mucho éxito con la tarea! 😄
