### ISSUE TITLE
Insertar objeto de otra clase en VentanaPrincipal

### ISSUE THREAD

**Issue by daniela-carreno** [IIC2233/syllabus#767]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, mi duda es que para la ventana de juego cree un objeto VentanaJuego y dado que constantemente estaré creando flechas decidí crear otro objeto, Flechas. Pero ahora estoy complicada en cómo insertar este nuevo objeto en el layout de la otra clase.  Encontré varias respuestas en google que creo me podrían servir pero no están en python y me cuesta hacer la transformación de sintaxis a pyqt5. Encontré este [post](https://stackoverflow.com/questions/32874989/accessing-a-pyqt-widget-outside-its-class/32876329#32876329) en stackoverflow y sugieren que el segundo objeto (en mi caso Flechas) herede del primero (Ventana) como se muestra a continuación:

```
 class MainWin(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1127, 880)
        [ window set up ]


 class SecondWindow(QMainWindow):
    def __init__(self, firstwindow, parent=None):   <----- (:sos: 1)
        super(SecondWindow, self).__init__(parent)
        self.firstwindow = firstwindow
        ...            

    def addTemplate(self):
        data = self.textBrowser.toPlainText()
        self.firstwindow.addText(data)  <---- (:sos: 2)
```

Mi problema es que no está funcionando. Para empezar me reclama por tener dos instancias (:sos: 1), traté sacando el ```parent``` y nada. ¿Para qué si la respuesta habla de herencia no lo hace en la linea de ```class```?¿Porqué explicita que el parent es ```None```?

Además, el método de la segunda clase que se supone añade el "algo" (:sos: 2) utiliza ```addText``` que también me arroja error (¿quizás estoy dejando fuera la librería específica que contiene a ese método?). En este caso ¿cómo añado un label a mi ventana? Hasta ahora había usado  ```addWidget``` pero no estoy usando un layout como (vbox, hbox o grids)  sino que ubico directamente mis objetos en la ventana con ```setGeometry(QRect(bla, bla, bla, bla))```. ¿Alguna sugerencia?

Por último, como input, hice todo el diseño desde python, ya que desde QtDesigner al convertir los archivos a extensión ```py``` me arrojaba error para ejecutar el archivo, asique preferí seguir avanzando directo desde python.

**Comment by aljara97** [comment]
Hola @daniela-carreno, entiendo lo que quieres hacer, pero me quedan dudas en la forma en que defines la clase de la ventana principal, podrías decirme si la ventana principal hereda de alguna instancia de pyqt5 y comentar los errores que te arroja la consola en los casos que describiste?

**Comment by daniela-carreno** [comment]
La ventana hereda de `QMainWindow` . Pucha, seguí avanzando y ya no tengo error, pero sigue sin funcionar. Estoy haciendo algo asi:

```
class Ventana (QMainWindow):
    (bla bla)
    
    def addImagen(self, imagen):
        [guardo imagen un self, asocio este self a un label y cambio su aspecto]
        [creo un QTimer y llamo al metodo changePosition]

    def changePosition(self):
        [tomo el self guardado anteriormente y le cambio su posición en la ventana]
        self.update()

class Flecha():
    __init__ (atributos)
    [no tiene metodos asociados]
```

Desde el main creo los objeto Flechas y hago `ventana.addImage(flecha_creada)`
Esta es mi búsqueda de referencia [aqui](https://stackoverflow.com/questions/41732808/how-to-move-a-point-across-the-screen-in-pyqt5)

**Comment by aljara97** [comment]
Podrías intentar llamar al método `show()` en la clase flecha para ver si te las muestra en pantalla, ya que, al heredar de una `MainWindow` tendrá sus métodos y propiedades. De lo contrario te invito a cuestionarte si hay alguna razón en específico por la cual la flecha se comportaría como una venta y ver si es que es más adecuado que la flecha contenga métodos y propiedades de otra de las entidades vistas en los contenidos del curso.

Mucho éxito y de ahí me cuentas cómo te va

**Comment by daniela-carreno** [comment]
Hola, creo que me expliqué mal. La clase Ventana hereda de QMainWindow, la clase Flechas no hereda de nada. Solo guardo sus atributos en self. ¿Quizás debería heredar de Ventana?

Entonces lo que hice fue crear un método **en** la clase Ventana que recibiera de input un objeto y lo asociara a un Qlabel en la ventana.  El error dice `could not parse stylesheet of object QLabel(*)`.

**Comment by aljara97** [comment]
Perfecto, entonces en la ventana tienes un QLabel al que le entregas atributos de tu clase ventana, estuve averiguando y probablemente no le estés pasando los atributos correctos y eso sea lo que produzca el error ¿Qué método de pyqt5 usas para asociar el objeto al QLabel de la ventana?

**Comment by daniela-carreno** [comment]
Tengo un método en la clase Ventana que es para agregar imagen. Epic fail!! Me di cuenta que nunca llamo a ese método. Agregué una línea para llamarlo desde el main.py con:
`ventana_juego. metodo_para_agregar_cosas(objeto_por_agregar)`
Y mutó mi error. No se si el anterior persiste. Este es el nuevo error:
`fbox is not defined`

Se donde está el error pero tampoco he podido resolverlo. Trataré de explicarlo con el menor spoiler de código posible:

```
Clase Ventana (QMainWindow):
    (...)

Def init_gui(self):
    (...)
    fbox = QFormLayout()
    Cualquier_widget = self.agregar_widgets()
    fbox.addRow(QLabel(), Cualquier_widget)

Def metodo_para_agregar_cosas (self, flecha):
    self.objeto = flecha
    self.objeto = QLabel()
    (...)
    fbox.addRow(QLabel(), self.objeto) <-- error
    self.update()

```

Como puedo meter a mi layout este nuevo widget?

Gracias

**Comment by aljara97** [comment]
Hola, el problema es que no estás instanciando el fbox como un atributo propio de la clase, sino que se instancia solamente en la función, es decir, debes guardarlo en `init_gui` como  `self.fbox = QFormLayout()`. De lo contrario solo se guardará de manera local y no podrás llamarlo en `metodo_para_agregar_cosas (self, flecha)`.

Con respecto al acoplamiento, este se refiere al fenómeno que ocurre cuando una clase depende de los procesos de otra, es decir, requerirá información de otra clase y no funcionará de manera independiente. No puedo decirte si acá hay acoplamiento, ya que es uno de los objetivos de la tarea. Intenta solucionando el problema de la manera que te dije y me cuentas si te funciona.

**Comment by daniela-carreno** [comment]
Funciona! Muchas gracias
