### ISSUE TITLE
Re-Re-Re-Corrección Tarea 2

### ISSUE THREAD

**Issue by KnowYourselves** [IIC2233/Syllabus#767]
Hace unos meses atrás tuve problemas con mi tarea 2 pero fueron arreglados, el tema es que todavía no ha cambiado mi nota en el excel 😢

**Comment by rpalmaotero** [comment]
**Para consultas de carácter personal debes usar el formulario de contacto**. Efectivamente, hubo un error de transcripción el cuál ya fue rectificado.
