### ISSUE TITLE
Envío imagen entre cliente-servidor

### ISSUE THREAD

**Issue by Fhguinez** [IIC2233/Syllabus#767]
Sé que ya han respondido en otras issues que la idea es enviar un "paquete de cambios"  y no toda la imagen. Pero el aplicar las ediciones demora unos segundos, mientras que enviar las imágenes es prácticamente instantáneo, por lo que mi programa iría más rápido si solo aplicara la edición en el servidor y después enviara la imagen editada a todos los clientes.
¿Hay algún problema con que haga esto?

**Comment by B-Dominguez** [comment]
Me sumo a la misma preguntaa, estaba mandando sólo un comando como (cut, pos, pos), pero es mucho mas lento que mandar la imagen. Sería considerado como "sólo la info necesaria" el IDAT? O la matriz? Porque mandar solo los pixeles involucrados implica enviarlos con identificador y es más complejo (y pesado)!
