### ISSUE TITLE
Juntar .ui en una sola ventana

### ISSUE THREAD

**Issue by difischer** [IIC2233/syllabus#768]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, creé distintas partes de la UI, como la barra de estado y la tienda, de forma separada en  Qt Designer y me gustaría saber si es que se **pueden cargar distintos archivos .ui dentro de una misma ventana**, en vez de hacerlos aparecer en ventanas separadas

**Comment by kadroguett** [comment]
Hola @difischer, si es posible hacerlo. Para esto al crear el UI que quieras agregar a la ventana deberás escribir:
```
BarraEstado(window_name, base_class):

def __init__(self, parent):
    super().__init_(parent)
```
Y al instanciar el widget en la ventana  deberás agregar `self`:
`self.wid = BarraEstado(self)`

De esta forma se te cargará dentro de la ventana luego de agregarlo en un layout.

**Comment by difischer** [comment]
Hmm, pensé que había hecho eso, voy a revisar, creo que me faltó agregar parent :)
¡Muchas gracias!

**Comment by kadroguett** [comment]
De nada !! Avísame si te funciona y si no igual para ver qué puede estar saliendo mal

**Comment by difischer** [comment]
Efectivamente me faltaba poner _parent_ en la función. 
¡Te pasaste, gracias!
