### ISSUE TITLE
problema al cargar sprite

### ISSUE THREAD

**Issue by TdelrioC** [IIC2233/syllabus#768]
Hola, tengo un problema a la hora de cargar el sprite de la mesa del chef, (tambien me pasa cuando trato de cargar el sprite con el chef incluido), solo se carga parcialmente.
<img width="659" alt="Screenshot at May 20 14-05-09" src="https://user-images.githubusercontent.com/52587183/82481388-3a7f7600-9aa3-11ea-8fef-999798996782.png">

**Comment by lily416** [comment]
Hola, se habla del mismo problema en la _issue_ #752.

Recuerda revisar las _issues_ antes de crear una nueva, puede que tu problema ya se haya comentado y/o resuelto.

Saludos y éxito en la tarea 👋🍰
