### ISSUE TITLE
Problema al descomprimir 

### ISSUE THREAD

**Issue by tanavarrete** [IIC2233/Syllabus#768]
He estado buscando como solucionar el siguiente error:
zlib.error: Error -5 while decompressing data: incomplete or truncated stream
pero no he encontrado ni una solución, que podría estar pasando?

**Comment by jtagle2** [comment]
De dónde salen los datos que quieres descomprimir? Son los datos que estás enviando y recibiendo o son datos que tienes al armar un archivo jpg?

**Comment by tanavarrete** [comment]
Son los datos del IDAT, para formar la matriz RGB
