### ISSUE TITLE
Error al cargar objetos al mapa

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#769]
Hola!
Resulta que he querido agregar los objetos que están en ```mapa.cvs``` a mi ventana ya creada del mapa, el tema es que la ventana del mapa es en una función distinta a la función donde intento de agregar estos objetos a la ventana. Me basé en un método que hicieron de la jeringa de la AY08
![image](https://user-images.githubusercontent.com/59337116/82481898-0789b200-9aa4-11ea-8152-08a34b3da9b7.png)
Hice algo muy parecido.La ruta dela imagen la cambié a la correspondiente e hice otro diccionario que tome el lugar de ```self.characters``` . Pero al cargar la ventana no se muestran estos objetos. Pero la función sí es llamada, pero no genera que se muestren los objetos. Qué estoy haciendo mal?

**Comment by moquezada** [comment]
Hola @Camila-sty!

Para solucionar tu problema primero verificaría que estás seteando adecuadamente el `parent` de cada  objeto y que además lo estés mostrando "por sobre" el mapa mediante el método `raise_`. Este también se ocupa en la ayudantía para que veas como funciona 👀 

Avísame como te va :)

**Comment by Camila-sty** [comment]
me faltó el ```raise_```, ahí empezaron a aparecer.
Gracias!
