### ISSUE TITLE
Notas examen ¿Dónde?

### ISSUE THREAD

**Issue by Arcoirisky** [IIC2233/Syllabus#769]
¿Alguien ha encontrado las notas? El correo decía en el exel pero no me aparece actualizado D:

**Comment by rfenzo** [comment]
https://docs.google.com/spreadsheets/d/1T6qOUvIItHvonTxXBvwAeJ4t_KAD7X-i7GxcZ0sI1DA/edit#gid=1120413644

**Comment by Arcoirisky** [comment]
;-; Pero no hay notas de exámenes ;-;

**La pera y ansiedad se sienten**

**Comment by andresfdezc** [comment]
Revisen la columna AY

**Comment by Arcoirisky** [comment]
Juro que está vacía. Sólo están los puntajes de las tres últimas preguntas y la AY está junto a la que dice EX que están ambos vacíos ¿De verdad no se me actualizó?

**Comment by Arcoirisky** [comment]
Juro que está vacía. Sólo están los puntajes de las tres últimas preguntas y la AY está junto a la que dice EX que están ambos vacíos ¿De verdad no se me actualizó?

**Comment by Arcoirisky** [comment]
![screenshot_2017-07-06-00-44-06](https://user-images.githubusercontent.com/26121402/27895951-3160cd6a-61c3-11e7-8012-a8b159159208.jpeg)

(Creo que acabó de subir una imagen)

**Comment by andresfdezc** [comment]
Por favor, abre el [siguiente enlace (https://docs.google.com/spreadsheets/d/1T6qOUvIItHvonTxXBvwAeJ4t_KAD7X-i7GxcZ0sI1DA/) en un navegador en incógnito. Estás viendo una versión que quedó guardada en la memoria caché de tu celular.

**Comment by Arcoirisky** [comment]
Ahí aparecieron!
¡Gracias!
