### ISSUE TITLE
Git carpeta .idea

### ISSUE THREAD

**Issue by SarahEverke** [IIC2233/Syllabus#769]
Al subir mi T06, apareció en el repositorio una carpeta llamada .idea
¿Qué hago con ella?

**Comment by akaminetzkyp** [comment]
No te preocupes. Esa carpeta es creada por Pycharm para guardar archivos con ajustes del proyecto.

Saludos!

**Comment by ifcarrera** [comment]
Hola! Siempre puedes usar .gitignore para evitar que se suban estas carpetas que se van creando solas, como .idea o .DS_Store.
Saludos :D

**Comment by akaminetzkyp** [comment]
También puedes evitar que se suban archivos que no quieres evitando el uso de `git add --all`. Siempre es mejor usar `git add` solo con los archivos que quieres subir.

**Comment by SarahEverke** [comment]
Muchas gracias!!!!
