### ISSUE TITLE
no aparece correctamente el backgroud-color al instanciar un Qwidget personalizado dentro de otro.

### ISSUE THREAD

**Issue by mmontecino** [IIC2233/syllabus#769]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Tengo creadas para la ventana juego varios QWidget personalizados donde se representan la zona de estadisticas, la tienda, la pista y asi. Y estas al correrlas solas tienen un color de fondo. Sucede que cuando las instancio dentro de una clase que cree que representa como toda la ventana de juego (que hereda de QWidget ) no mantienen su color de fondo y este solo queda en los botones o al rededor de los labels del QWidget que se instanció. Como puedo arreglar esto para que quede al final toda la seccion mantenga el color(como un cuadro (como en los ejemplos del enunciado)).

**Comment by JuaniAndres** [comment]
Hola @mmontecino 
Te refieres a que cuando agregas los QWidget a tu ventana estos como que quedan con el mismo color de fondo que tiene la ventana o es otra cosa?
Como por ejemplo esto:
![ej](https://user-images.githubusercontent.com/48482216/96925446-9010e200-148a-11eb-901d-d99b09132c64.png)

**Comment by JuaniAndres** [comment]
Hola @mmontecino 
Lo que te esta pasando es que los QWidgets que estas poniendo a la ventana esta quedando con el mismo color del fondo de tu ventana?
Algo como esto:
![ej](https://user-images.githubusercontent.com/48482216/96926539-10841280-148c-11eb-89a8-b2f0cfdde0d3.png)
O es otra cosa?

**Comment by mmontecino** [comment]
no tan asi, cree este ejemplo simple para que se viera, a la derechaesta el QWidget que despues se instancia dentro del de la izquierda. Este tiene fondo y se encuentra dentro de un VBoxLayout en el de la izquierda. Lo que espero es que se vea toda la mitad de arriba del color de las labels, no como se ve que solo las labels guardan el color. Si no es problema, puedo adjuntar el codigo, es mas, este lo cree solo para esta issue.
![WhatsApp Image 2020-10-22 at 20 59 12](https://user-images.githubusercontent.com/69608795/96941748-a2e6df00-14a9-11eb-90fa-876decf25217.jpeg)

**Comment by JuaniAndres** [comment]
Ya entendí el problema que estas teniendo. Estuve probando bastante e investigando porque pasa eso lo raro que en Qt Designer hacer lo mismo no genera problemas. También lo que te está pasando solo ocurre con widgets que tienen otros dentro. Voy a seguir investigando y si descubro algo te aviso por aquí. Por mientras una solución parche es que el fondo de tu widget de la derecha lo hagas con un Qpixmap pintado del color que quieres y que tenga las dimensiones que necesites.

Éxito en la tarea y espero tener alguna noticia pronto.
