### ISSUE TITLE
Modificar print_tablero

### ISSUE THREAD

**Issue by isajofre** [IIC2233/Syllabus#77]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! 
Es posible modificar la función print_tablero? El cambio sería modificar las letras de las columnas por números ya que pido las coordenadas a descubrir en formato n_fila, n_columna.
Desde ya gracias!

**Comment by vicentethomas** [comment]
Hola! Lamentablemente **no** puedes modificar este archivo de ninguna forma, ya que así se explica en el enunciado
![image](https://user-images.githubusercontent.com/80768650/186544926-1f54b861-8fc5-46ed-ba7a-1d595e039d64.png)
En esta tarea se espera que sean capaces de procesar ambos tipos de datos 👍.

Si tienes problemas con esto, vuelve a preguntar y lo tratamos de solucionar! Saludos
