### ISSUE TITLE
Problema con el directorio de vscode

### ISSUE THREAD

**Issue by Fuentes149** [IIC2233/Syllabus#77]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

Al correr mi codigo en vscode corre por otro directorio en vez de el directorio en el que esta mi codigo, entonces no puede exportar los archivos que estan en la carpeta de mi codigo.

**Comment by kunafuego** [comment]
¡Hola! Para solucionar tu problema lo que debes es abrir la terminal desde vs code, y ocupando el comando `cd` (change directory) navegar hasta la carpeta donde se encuentra tu tarea, y desde ahí correr tu código. Te recomiendo también investigar los comandos `pwd` y `ls`, ambos son muy útiles a la hora de moverse entre directorios en la terminal.

**Comment by Fuentes149** [comment]
Hola, ya hice eso pero cada vez que corro el código se cambia automaticamente el directorio al que estaba antes.

**Comment by kunafuego** [comment]
Intenta corriendo el código desde la terminal. Para hacer esto debes navegar hasta la carpeta de la tarea, y ahí escribir `python main.py` (suponiendo que main es el archivo que deseas correr).
Me cuentas!
