### ISSUE TITLE
Duda **Kwargs

### ISSUE THREAD

**Issue by Dnpoblete** [IIC2233/syllabus#77]
Al crear una clase con lo siguiente:

    def __init__(self, **kwargs):

        super().__init__(**kwargs)

        self.parametro1 = parametro1
        self.parametro2 = parametro2
        etc

y heredarlo a una clase que tiene esto: 

    def __init__(self, **kwargs):

        super().__init__(**kwargs)

y entregarle los parametros me entrega el siguiente error:

    super().__init__(**kwargs)
TypeError: object.__init__() takes no parameters

y si le quito el **kwargs de la super clase me dice que los parametros no estan definidos :(

Alguien sabe como lo puedo arreglar?

**Comment by Polea012** [comment]
Hola! Por lo que entiendo del código que muestras acá, el error de los parámetros no definidos puede ser porque no estas desempaquetando los parámetros que vienen en **kwargs.

Esto también explica el TypeError: object.init() takes no parameters. Cuando llegas al super().__init__(**kwargs) de la superclase, **kwargs todavía contiene parámetros que no se han ocupado en los __init__ anteriores a él.  super().__init__(**kwargs) intentar llamar a la clase *object* de Python y se cae al entregarle parámetros.

Hay varias formas de recuperar los parámetros de **kwargs. Lo puedes hacer ocupando a **kwargs igual que un diccionario o definiendo los key arguments que recibe la clase en el __init__. 

Espero haberte ayudado! Si no queda claro no dudes en preguntar!

**Comment by Dnpoblete** [comment]
Es lo que salen como parametros se supone que son los argumentos de **kwargs que recibe o no?

**Comment by Polea012** [comment]
Si te refieres a parametro1, parametro2,.... entonces una solución a tu problema es indicar que son parámetros con key argument de la siguiente forma:

```
    def __init__(self, parametro1="", parametro2="",...., **kwargs):
        self.parametro1 = parametro1
        self.parametro2 = parametro2
        etc
```

**Comment by Dnpoblete** [comment]
Ahora si me funciono!!!, muchas gracias :)

**Comment by Polea012** [comment]
Excelente! Me alegra haberte ayudado!
