### ISSUE TITLE
Cargar partida

### ISSUE THREAD

**Issue by HghSpc** [IIC2233/syllabus#77]
Tengo un gran problema en este apartado, al guardar la partida yo guardo mi lista que representa al tablero, pero como es un archivo de texto (.txt), tengo que guardar esta en forma de string. Al cargar la partida, tengo que traer ese string y transformarlo a lista nuevamente, y no encuentro la forma de hacerlo, ya que usando los típicos métodos .strip(), .split(), pero no he encontrado la solución, ¿alguna ayuda?

**Comment by jeschuwirth** [comment]
Hola!

Esta tarea es para recordar los contenidos de introducción a la programación, la idea de hacer que ustedes guarden y carguen el tablero como quieran es que practiquen esa materia.

Un pequeño consejo que te puede ayudar es printear **todo** lo que estas leyendo de tu archivo (cuado lo lees y cuando lo conviertes a lista) y hacer un strip("\n") para evitar los saltos de linea ocultos que puedes tener.

Suerte y espero que el consejo anterior te sirva :)
