### ISSUE TITLE
Duda de archivos

### ISSUE THREAD

**Issue by MaxAl100** [IIC2233/Syllabus#77]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
En la imagen incluida se advierte que debe funcionar con otros archivos **distinto**, pero no detalla en qué se diferenciarían. Supongo que se refiere que la información pudiera estar en otro orden, pero ya que no está explicado prefiero preguntar por aquí.
![image](https://user-images.githubusercontent.com/43099597/161392610-2e6ff5da-1f1e-4b31-8661-e20d9489fd01.png)

**Comment by Gsalinas1506** [comment]
Hola!
Efectivamente. Si bien los .csv que tienen ustedes tienen un orden de _headers_, los archivos con los que probemos su tarea podrían tener otro orden en los _headers_.

Por ejemplo, `juegos.csv` tiene el formato <html>
<html>
<body>


nombre | esperanza | apuesta minima | apuesta maxima
-- | -- | -- | --
  cara o sello | 50 | 0 | 100
  ruleta de la suerte | 20 | 40 | 230


</body>
</html>

pero los ayudantes podriamos probar su tarea con un archivo que venga de la siguiente manera:

<html>
<body>


esperanza| apuesta mínima| nombre| apuesta maxima
-- | -- | -- | --
  50 | 0| cara o sello  | 100
   20 | 40 |  ruleta de la suerte | 230

</body>
</html>

Por lo tanto, su tarea debe ser capaz de tratar estos escenarios.

Exito con la tarea! 🎲️🃏️

**Comment by Dvckhv** [comment]
¿como se espera que podamos estandarizar la creación de la clase "Jugador" si tiene 10 parametros y estos se encontraran ubicados aleatoreamente en la linea de archivo y ademas no estan posicionados como kwargs?

**Comment by Gsalinas1506** [comment]
> ¿como se espera que podamos estandarizar la creación de la clase "Jugador" si tiene 10 parametros y estos se encontraran ubicados aleatoreamente en la linea de archivo y ademas no estan posicionados como kwargs?

Podrías tener una función que analice en que orden están los _headers_ y que en función de ese orden se vayan leyendo las características de los jugadores para crearlos. Si bien el orden de las columnas es arbitrario, sabes que en totas las columnas el orden será el mismo. Es decir, si ves que en el _header_ sale, por ejemplo, `nombre;energía;confianza`, ese orden se mantendrá para todo el .csv, no ocurrirá que en una columna haya otro orden.

**Comment by benja420p** [comment]
Hola! ¿El nombre **(no el orden)** de los _headers_ siempre va a ser el mismo? Es decir, no nos vamos a encontrar con una situación en que el nombre de los headers pase a ser algo así:
`nombre,esperanza,apuesta minima,apuesta maxima` -> `Esperanza,apuesta mínima,Nombre,apuesta maxima`
¿O debemos considerar esa caso además de un orden distinto para los headers?

**Comment by Gsalinas1506** [comment]
Sí, el nombre en los headers siempre será el mismo

**Comment by RicciOff** [comment]
En este caso, para cumplir con los requerimientos dichos más arriba de funcionar independiente del orden de columnas, mi código para abrir archivos ocupa muchas líneas del código principal, en ese caso puedo traspasar este contenidos a mi archivo parámetros.py?

**Comment by Gsalinas1506** [comment]
A que contenido te refieres? Podrías darme un ejemplo por favor? En cualquier caso recuerda que en parametros.py solo deben ir **constantes** de la ejecución de tu programa, pero que pueden variar de una ejecución a otra

**Comment by nhi1016** [comment]
Hola! si bien el orden de los _headers_ puede cambiar, el nombre de los archivos puede cambiar tambiés, o se mantienen constantes, es decir, juegos.csv siempre mantendrá su nombre?
