### ISSUE TITLE
Duda efecto de pronosticos en incendios

### ISSUE THREAD

**Issue by gbordoni** [IIC2233/Syllabus#77]
En #61 mencionan que, dada una cierta fecha, se deben considerar todos los efectos meteorologicos en el incendio, independiente de que si estos ya se hayan acabado. 
Mi duda es, entonces como puedo interpretar lo mencionado en el enunciado de que "si dos efectos meteorologicos del mismo tipo coinciden en un incendio se considera solo el mas reciente" ? Por ejemplo, si mientras en la "historia" de un incendio hay 3 veces viento (con fechas de inicio/termino disjuntas), al momento de simular considero solo el efecto de la ultima? O de las 3 por separado dado que ocurrieron en intervalos de tiempo distintos?

**Opinion personal** : Si es que la respuesta fuese considerar las 3, hacer eso con cada evento meteorologico requeriría una simulacion **hora por hora** desde el inicio del incendio hasta la fecha ingresada, para poder establecer "en tiempo real" la tasa de propagacion del radio en cada intervalo y asi calcularlo sin errores. Y creo que, sin la libreria datetime, esto se escapa un poco de los objetivos de la tarea.

**Comment by rpalmaotero** [comment]
@gbordoni en el ejemplo que pones debes considerar las 3 por separado. La acotación del enunciado se refiere a pronósticos que coincidan al mismo tiempo en un incendio. Sobre la opinión personal, recuerda que conoces a priori los pronósticos meteorológicos, trata de pensar cómo aprovechar bien esa información.

**Comment by chuma9615** [comment]
Respecto a esa pregunta, es necesario tener que simular todo? o hay otra forma menos compleja de solucionarlo?

**Comment by asdegoyeneche** [comment]
Pregunta, la información contenida en meteorología es un pronóstico del tiempo o solo es la información de lo que va ocurriendo en cada momento?

Con esto me refiero por ejemplo a:
- un usuario ANAF podría ver lo que ocurrirá más adelante respecto a meteorología
- para realizar los planes de extinción debemos / podemos usar la información de meteorología para obtener el óptimo plan? (con su criterio respectivo).  O son solo imprevistos al momento de actuar (por ejemplo se envía un avión sin saber que habrán nubes y mientras está en en camino o en el incendio aparecen nubes... por lo que se debe devolver por la condición meteorológica que apareció)

Saludos!

**Comment by rpalmaotero** [comment]
@asdegoyeneche Conoce los pronósticos a priori. Esa es una de las ventajas que tienen que aprovechar para determinar las estrategias.

**Comment by asdegoyeneche** [comment]
@rpalmaotero gracias!

**Comment by Hernan4444** [comment]
@asdegoyeneche como no está especificado en el enunciado queda a tu criterio pero no olvides especificarlo en el Readme.

Saludos!!
