### ISSUE TITLE
problema al instalar pyqt5

### ISSUE THREAD

**Issue by PedroFuenzalida** [IIC2233/syllabus#77]
Hago la instalación de la librería, pero cuando trato de ejecutar el setup_test.py sale no se puede encontrar el módulo especificado.

**Comment by gatochico** [comment]
Hola! El problema persiste? Si es así, podrías mandarnos pantallazos de cómo corres el programa y el error que te sale?

**Comment by PedroFuenzalida** [comment]
Ya lo arregle. Era un problema con los paths porque al instalarlo por
Microsoft Store no me dejaba elegir esa configuración al instalarlo
