### ISSUE TITLE
Duda sobre archivos (+ duda sobre archimago, asteroide y habilidad especial maestros)

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#77]
Al conquistar un planeta 🌐, todos los soldados/magos 👥 de la raza ganadora aumentan en 10 puntos su vida y en 5 su ataque. 
Asumo que:
1. el boost ⏫ puede pasar del máximo 🌟 de vida o ataque de la unidad según su raza.
2. el boost ⏫ también afecta a magos.
3. al reanudar la partida guardada el boost ⏫ se debe conservar (progreso en la "historia" 📜). 

En esta línea, a los archivos les falta poder guardar los boosts ⏫⏫ en cuestión.
Está bien lo que estoy asumiendo? 🚥
Puedo crear un tercer archivo 📄 .csv donde guarde las unidades 👤? (aunque en el enunciado diga que no 🙅 es necesario).

PD: duda final. Imaginemos que el archimago 👾 ataca mi planeta donde tenía el cuartel y 35 soldados aprendices. Por tanto, la vida 🍃 total de mi ejército es 700 * 35 + 5000 = 29500 puntos de vida 🍃. Al final, mi ejército quedó en 14000 puntos de vida 🍃. Siguiendo la fórmula del enunciado, ahora mi ejército tiene solo  20 soldados. ¿Es esto correcto? 🚥 Y el cuartel, ¿sigue en pié o hay condiciones para que se destruya además de las referentes al evento Asteroide 🌠? 🚥

PD2: tanto con el evento asteroide 🌠 como con la habilidad de los maestros ⚡️, muere la mitad del ejército. ¿Es esto equivalente a recortar la vida del ejército a la mitad y luego recalcular el número de unidades supervivientes? 🚥 (para efectos del curso y la tarea).

**Comment by Hernan4444** [comment]
Hola,  si revisas la sección **6.4.2. Guardar cambios**, ahí se indica que el ataque y vida de los soldados/magos se vuelve a generar el ataque, es decir, se pierde el boost. Por lo que el supuesto 3 no está correcto, pero si quieres crear un .csv para guardar eso, no hay problema mientras se cree durante la ejecución de tu tarea, no puedes asumir que existe desde el inicio.

Pd: En el enunciado no se indica ningún otro evento aparte del asteroide que afecte el cuartel, por lo que no hay nada más y sobre la cantidad de soldados, no te puedo decir si está bien, puesto que la vida de cada soldado es distinta y ahí dejamos un poco a su criterio que "vida" utilizar para la división.

Pd2: No, solo dividir la cantidad de soldados en 2.

Espero haber respondido tus dudas.
Saludos!!
