### ISSUE TITLE
Problema con testcases

### ISSUE THREAD

**Issue by vvialbarros** [IIC2233/Syllabus#77]
* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [ X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola, cuando uso los testcases, me dice "fail" a pesar de que mi output es igual al esperado.

Stdout:
Predio.plano
[1, 1, 7, 7, 'X', 9, 'X', 2, 'X']
[1, 1, 6, 6, 'X', 9, 'X', 'X', 3]
['X', 'X', 0, 0, 0, 0, 3, 4, 4]
['X', 'X', 0, 0, 0, 0, 'X', 4, 4]
Predio esperado
[1, 1, 7, 7, 'X', 9, 'X', 2, 'X']
[1, 1, 6, 6, 'X', 9, 'X', 'X', 3]
['X', 'X', 0, 0, 0, 0, 3, 4, 4]
['X', 'X', 0, 0, 0, 0, 'X', 4, 4]

======================================================================
FAIL: test_4 (tests_publicos.test_01_plantar.TestPlantar.test_4)

        Caso complejo donde solo cabe un cultivo determinado. Plano 6x10, código_predio = 9.
        codigo_cultivo = 9, dimensiones 4x3, plantar en (2,5).

Eso es lo que me dice por ejemplo en el test 4 de la funcion plantar.

**Comment by ignacio-sp** [comment]
Hola @vvialbarros, el output que muestras corresponde al test número 3 de `test_01_plantar.py`, que como puedes ver está correcto. Sin embargo, el error que te arroja la terminal corresponde al test número 4, el cual puedes observar en el código que tiene un output esperado distinto al que estás mostrando, por lo que el problema está cuando quieres plantar en ese caso.

Espero haber resuelto tu duda, cualquier cosa estoy atento a tu respuesta!
