### ISSUE TITLE
Definición, declaración, referencia 

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#770]
Hola!, estaba profundizando un poco los conceptos más teóricos, y me tope con "Definition, declaration & reference" de una función. Intenté buscar en internet respuestas, pero solo encontré ejemplos con C++, los cuales no me dejan tan claro si se extrapola bien a python. En definitiva, no lo entiendo bien. 😞 (Principalmente qué son y sus diferencias)

**Comment by tqmbanados** [comment]
Hola! Efectivamente, es algo más de lenguajes compilados como C y C++. Te voy a contestar por mientras dentro de mis conocimientos, pero creo que esto lo explicará mejor alguien que sabe más de esos lenguajes! 
* **Declarar** una función es explicitar que tal función existe, que parámetros recibe y que retornará, pero *sin incluir la función en sí*. 
* **Definir** una función es entregar **todo el contenido de una función**, tanto sus parámetros, lo que hace con ellos, y lo que retorna. Es lo que hacemos en python.
* **Referenciar** tiene que ver con apuntar al espacio de memoria donde se encuentra la función, en vez de entregar la función en sí. Esto también corre para variables; en python todas las variables son *referencias* a un espacio de memoria, no un objeto en sí. Por esto también es importante la mutabilidad e inmutabilidad en python! (explicaré más de esto más abajo).

En python, la diferencia entre declarar y definir no es necesaria, pues el intérprete de Python no necesita saber que existe una función para usarla. Acá es donde me pierdo un poco en *por qué* ocurre esto, pero tengo entendido que tiene justo que ver con el hecho que las variables son referencias y son dinámicas. (Dinámica quiere decir que puede cambiar su tipo, referencia es lo que explicamos más arriba). 
Entonces, si el intérprete de python ve la siguiente línea: `funcion()`, irá al espacio de memoria al que apunta `funcion`. Si ahí se encuentra una función, la realizará y todo bien, si no es una función, levantará un `TypeError`. Es decir, el problema es que la variable **no es de tipo función, entonces no puede tratarse como tal**. Si la variable `funcion` no existe, levantará un `NameError`.  Recuerda lo que vimos de "duck typing": si puede tratarse como función, es una función. 

En un lenguaje con typing *estático*, es importante que el compilador u intérprete sepa qué tipo tiene cada variable para poder usarla. Entonces, si quieres usar una función que no está definida en el mismo archivo, de todas formas tienes que declarar que es una función. Sobre esto mejor que explique alguien que tiene más conocimiento de lenguajes estáticos!

Sobre las *referencias* en python, hay que saber que en algunos lenguajes no todas las variables se tratan como referencias. De lo poco que sé de C, a una función puedes pasarle argumentos *como valor* o *como referencia*. En el primer caso, lo que ocurra con las variables dentro de la función no cambiará a las variables que le fueron entregadas por fuera. Es decir:
```python
# Ocuparé syntaxis de python para entendernos mejor,
def funcion(lista):
     lista.append("uwu")

example_list = ["ejemplo", "muy"]
funcion(example_list)
```
En el ejemplo anterior, si pasamos la variable **como valor**, la función es en efecto inútil, pues cambia una variable que sólo existe dentro de la función, y no retorna nada. Sin embargo, sabemos que python recibe variables **como referencia**, es decir que el argumento `lista` en la función apunta al mismo espacio de memoria que `example_list`, por lo tanto, la función estaría realizando los cambios sobre la lista definida en `example_list`. En python **todos los argumentos se pasan como referencia**, por lo que hay que tener en cuenta esas cosas al trabajar con objetos *mutables*, como listas, diccionarios, o la mayoría de las clases personalizadas (si no sabes bien la diferencia entre mutable e inmutable avisa!).

### ¿Cómo se resume todo?
La manera en que se mezclan estos tres conceptos para las funciones de python es bastante bonita. Ya sabemos que los nombres de las funciones son en verdad variables que apuntan a una función. Por eso podemos tener código así: (te invito a probarlo!)
```python
def funcion():
    # Definición de una función. Esta función se guardará en un espacio de memoria, 
    # y la variable "funcion" apuntará a ella.
    return "soy una función"
variable = "soy una variable"
print(funcion)   # printea algo como <function __main__.funcion()>
print(funcion())  #printea "soy una función"
print(variable)  # soy una variable

# Ahora la parte "rara"
placeholder = funcion  # guardamos la referencia a funcion en una variable auxiliar
funcion = variable  # cambiamos el valor de funcion, por el valor que tenía variable
variable = placeholder   # cambiamos el valor de variable por el valor que tenía funcion!
try:
    print(funcion())
except TypeError:
    print("funcion ya no es una función!!!!")
    print(variable())   # Esto imprime "soy una funcion"
```
Entonces, dado que cada variable puede en el fondo tener *cualquier tipo* (`str`, función, `list`, infinito etc...), no es necesario **declararlas**, sólo que estén **definidas**!

**Comment by Christian-Klempau** [comment]
Para completar la respuesta:

### Declaración y definición
Primero, debemos entender qué significa es _compilado_: C y C++ son lenguajes compilados, es decir primero se transforma todo el código a instrucciones del computador (compilar), y luego se corre el programa de manera independiente, con el código independiente (un archivo).
Por otro lado, Python es un lenguaje _interpretado_, es decir se compila **en el momento** (en tiempo de ejecución). Esto te da libertades de ejecución, pero te hace perder eficiencia.

Primero, en C sí existe la diferencia entre declaración y definición: la definición, le dice al programa (compilador) que habrá una función más adelante, que tenga ese nombre, con tales parámetros y retorne algo específico (con sus tipos de datos respectivos). Como el programa se analiza y compila de manera lineal (línea por línea), si la línea en la que se llama va antes de la declaración, el programa no funcionaría. Por lo mismo, me sirve primero declararla (decir que existe), luego escribir código que la llama (aunque todavía no esté definida), y después definirla. Como C es un lenguaje compilado, el programa necesita saber en ese mismo momento, que la función existe. Por esta razón, las operaciones de definir y declarar, son independientes en C.

En Python, la declaración y definición se hacen en **conjunto**. Es decir, cuando yo escribo:
```
def funcion():
   pass
```
Estoy definiendo `funcion` y declarandola a la vez. Es imposible hacer las cosas por separado, ya que van de la mano.

### Referencias
Con respecto a la parte de referencias, @tqmbanados, lo explicó muy bien!
Para desarrollar, en Python hay elementos que se entregan a funciones como **referencias**, mientras que otros por **valor**. Por ejemplo, si yo le paso un `int` a una función, se pasa el valor de dicho int, pero no la variable de este. Por lo mismo, es imposible modificar una variable int dentro de una función (los strings se comportan igual). En este caso, la variable se queda dentro de la función y se deshecha al terminar.

Por otro lado, hay elementos que se pasan por referencia: por ejemplo, las listas, diccionarios, instancias de clase, etc. Es decir,  si se modifican dentro de una función, dicha modificación **sí** perdurará fuera del llamado de la función.

Muchos de estos detalles pueden ser un poco abstractos, ya que tienen que ver con el lenguaje de C. Si te interesa, el ramo de **estructuras de datos y algoritmos** profundiza el tema! Cualquier duda, puedes seguir preguntando :)

**Comment by fernandosmither** [comment]
Muchísimas gracias a ambos por tales respuestas sublimes! Ya me preguntaba por qué en python mi IDE hacía lo mismo cuando le pedía las definiciones y referencias. 😄
