### ISSUE TITLE
Algun alma caritativa va a la lloraton?

### ISSUE THREAD

**Issue by chuma9615** [IIC2233/Syllabus#770]
Buena cabros, ando fuera de santiago y no tengo a nadie a quien mandar a llorar, algun alma caritativa que vaya mañana a la lloraton podrá ir por mi a esclarecer un problema chico? nada de vida  muerte, solo reconocer una pregunta del examen. De antemano gracias!

**Comment by andresfdezc** [comment]
En la pregunta 4 hay solo 2 respuestas sin nombre. Si el otro alumno que no tiene puntaje en esa pregunta reconoce su respuesta, asumiremos que la otra es la tuya.

**Comment by chuma9615** [comment]
Y si no llega?? jajajaja

**Comment by andresfdezc** [comment]
Pon atención a tu correo en ese caso.

**Comment by chuma9615** [comment]
Te acabo de mandar una descripcion de mi pregunta a tu mail. yo creo que con eso la van a reconocer
