### ISSUE TITLE
Dinero inicial

### ISSUE THREAD

**Issue by sebastianbreguel** [IIC2233/syllabus#770]
Hola, cuando un jugador ingresa su el nombre y comienza una partida, comienza con un dinero inicial para colocar el pirigüin inicial.

**Comment by JadrinaDA** [comment]
Hola! 
El enunciado dice que el primer pinguirin no tiene costo asociado. Así que no necesitas un dinero inicial para poder comprarlo. Podrías crear un parámetro DINERO_INICIAL = 0 por consistencia pero con lo anterior deberías estar bien.
