### ISSUE TITLE
problemas con posicionar los objetos en el mapa

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#770]
Hola!
Cargé los objetos de ```mapa.csv``` con las misma posiciones que entregaron, pero me quedan mal ubicados;
Mi ventana se ve así:
![image](https://user-images.githubusercontent.com/59337116/82485563-a238bf80-9aa9-11ea-84e4-e06b1d31cdfd.png)
Qué tengo que hacer para que quedén bien? debo cambiar el tamaño de la ventana? o del mapa?, o debo editar las posiciones de los objetos dadas en ```mapa.csv``` ..

**Comment by Camila-sty** [comment]
Incluso ni siquiera alcanza a aparecer el chef ...

**Comment by jitorcas** [comment]
Hola @Camila-sty !

Tu ventana está quedando muy bacán! Te recomiendo editar las posiciones de los elementos en el archivo `mapa.csv` y utilizar alguna de las técnicas que se subieron en el archivo `Ejemplos formas de cargar el mapa.pdf` en la carpeta de la `T02`. 

Avisa como te va! Éxito

**Comment by Camila-sty** [comment]
Graciaas! :smile: 
Sí, he revisado ese PDF que subieron y entiendo la idea que dan. Pero me surge la duda de cómo yo puedo saber cual es la coordenada de ese punto naranjo que sale en la siguiente foto?
Yo cree una ventana donde la información del juego y el mapa fueron acomodadas tal como se muestra en la foto anterior, entonces yo de por sí no le di la posición al mapa, solo le definí el tamaño de LARGO_MAPA y ANCHO_MAPA
![image](https://user-images.githubusercontent.com/59337116/82487162-00ff3880-9aac-11ea-8de4-becdb9116cc3.png)

Entonces, puedo puedo saber que coordenada es la que apuntan con el circulo naranjo?

**Comment by jitorcas** [comment]
La idea es que tu puedas definir cual quieres que sea tu punto de coordenada inicial de las tres opciones que te dan y desde ese punto calcular las posiciones de los objetos en el mapa. Si quieres puedes hacer un push para observar como lo estás haciendo!

**Comment by Camila-sty** [comment]
Si, me quiero quedar con el punto que mostré en la imagen anterior, pero no se cómo saber que coordenada es esa...
Acabo de hacer git push.
La ventana está en el módulo ```ventana_mapa.py```

**Comment by jitorcas** [comment]
@Camila-sty 

Primero al correr tu código me apareció el siguiente error, que yo creo que tiene que ver con que no te aparezca el oso chef. 
```python
File "/Users/Jorshitc/Desktop/camila-sty-iic2233-2020-1/Tareas/T02/ventana_mapa.py", line 153, in agregar_objeto
    chef = self.dicc_instancias[f'chef_{cuenta_mesas}']
KeyError: 'chef_2'
```
Segundo, se subió un nuevo archivo de *sprites* , donde se cambió el nombre de los mapas, para que ocupes ese. 

Ahora para responder tu duda principal, tienes dos opciones:

1. Siguiendo la lógica actual de tu programa, tu eje principal comienza la ventana de juego (en el extremo superior izquierdo) , por lo tendrías que sumarle a cada coordenada que te damos en `mapa.csv` la posición donde comienza el mapa en relación a la ventana que lo contiene, para que así tus objetos queden dentro del mapa. (cuidando las proporciones) 

2. Puedes crear un Widget que sea tu mapa del juego (donde ocurren todos los sucesos) y lo puedes poner como un centralWidget en una MainWindow. En este caso funcionaría independiente de la ventana que la contenga, y puede ser más sencillo para manejar el mapa y sus movimientos.

A la larga, la opción 2 es una forma más correcta de manejar el mapa, sin embargo si buscas rapidez la opción 1 te podría servir, y ambas se consideran como opciones válidas. Para ambos casos te invito a investigar que te conviene más y las formas de implementarlo. 
Espero haya solucionado tu duda, éxito!

**Comment by Camila-sty** [comment]
Entiendo.
Por mientras, hice la opción dos.
Tengo un problemas con ese error del chef, la verdad que no he podido solucionarlo, pero a simple vista, y considerando que pusiste una foto del error, por qué podría estar pasando?
Y otro, al colocar los objetos bien posicionados dentro del mapa, me pasa que cuando aumento el tamaño de ```scaled(x, y)``` el sprite se corta, pero cuando ajusto esto a rangos mas pequeños, se muestra bien, pero siento que no es el tamaño apropiado ya que se ve muy chico, cómo puedo arreglarlo, para que cuando aumenta ```x```` e ```y``` el sprite se pueda visualizar bien y no cortado?
