### ISSUE TITLE
Duda QThreads y QTimer

### ISSUE THREAD

**Issue by Zenos-Paradox** [IIC2233/syllabus#771]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X]  De ser necesario, colocaré código simple que permita explicar mi problema o duda

Hola,

estoy tratando de instanciar un QTimer dentro de un QThread para hacer un par de cosas periódicas pero el QTimer no está ejecutando la funcion que conecté a su .timeout... puede que el loop del QThread lo esté interrumpiendo? 
mi codigo es básicamente así:

```
def run(self):
        creo el QTimer asociado a self.funcion
        while del QThread
def funcion(self): no se ejecuta
```

**Comment by Zenos-Paradox** [comment]
O, Hay alguna forma de instanciar un QTimer dentro de un QThread? o debería iniciarlo a parte del QThread?

**Comment by Zenos-Paradox** [comment]
Ya no importa. Por si alguien más tiene esta duda:
Traté de tesolverlo haciendo una clase heredando de QObject donde se instanciaban y manejaban los QTimers; esa es la forma que usaron en la carpeta de contenidos. No me funcionó... Pero, con eso, agregué un self.exec_() al principio del run() del QThread y ahora funciona. Quiza eso habría bastado en un principio.

**Comment by igbasly** [comment]
Hola @Zenos-Paradox :v:

Lo que mencionas me hace pensar que quizás no iniciaste el _QThread_ luego de instanciarlo no hiciste `.start()`, lo mismo aplica al _QTimer_.

De todas formas avísame si efectivamente lograste arreglar el error o si aún persiste, quedó atento :smile:.
Mucho éxito!

**Comment by Zenos-Paradox** [comment]
si había hecho .start() al QThread... no debería entonces necesitar poner .exec_()?

**Comment by Zenos-Paradox** [comment]
si había hecho .start() al QThread... no debería entonces necesitar poner .exec_()?

**Comment by igbasly** [comment]
@Zenos-Paradox lamento la demora 😓, efectivamente no debería ser necesario que utilices `.exec_()`. Con `.start()` del QTimer no deberías tener problemas.
