### ISSUE TITLE
Proporción tamaño mapa y objetos

### ISSUE THREAD

**Issue by totaurt** [IIC2233/syllabus#771]
Hola! Tengo una duda con la proporción de los objetos dentro del mapa, ya que en el PDF "Ejemplos formas de cargar el mapa" los objetos como el mesero ocupan casi 1/6 de las baldosas del piso (son muy pequeños), en cambio en el enunciado se muestran casi del tamaño de una baldosa. Quería saber si se tenía que hacer de una forma u otra, o simplemente no importa. Para el avance lo hice como en el segundo caso.
Gracias!!

**Comment by moquezada** [comment]
Hola @totaurt,

Las proporciones quedan a criterio de ustedes como aspecto de diseño. Eso si, ten en cuenta que **todos los elementos deben poder distinguirse claramente** y que las proporciones entre los elementos tenga sentido (por ejemplo, no tener un mesero infinitamente más grande que una mesa o viceversa). Siempre hay que tener en cuenta que la interfaz debe ser lo más clara y cómoda (dentro de lo posible) para el usuario, por lo que bajo esta premisa es buena idea seguir lo mostrado en el enunciado 👀

Saludos :)

**Comment by totaurt** [comment]
Gracias por la aclaración:) saludoss
