### ISSUE TITLE
Duda con leer_midi.py

### ISSUE THREAD

**Issue by Unknomads** [IIC2233/Syllabus#771]
Hola! 
Mi duda es que no comprendo cuando se debe usar el modulo leer_midi.py (que lee un archivo midi y retorna los datos de las notas de la canción) en la interfaz. Por lo que yo entiendo hasta ahora sólo se genera un archivo midi de una canción creada en la interfaz cuando se selecciona la canción en la lista de "canciones listas" y se apreta el botón descargar. Entonces si es que no se ha apretado el botón descargar y por lo tanto no se ha generado un archivo midi para esa canción, y se quiere editar esa canción entonces no habrá una lectura de su archivo midi ya que no existe.

Mi duda principal, por si no quedó claro, es ¿cuando se debe leer un archivo midi?.
Saludos!

**Comment by Hernan4444** [comment]
@Unknomads si un usuario desea editar una canción midi que está en la lista de "canciones listas", se deberá desplegar todas sus nota y ahí deberás leer el midi desde el servidor para que le mande las notas al cliente.

**Comment by Unknomads** [comment]
Ok entiendo. Pero suponer que creamos una canción, la editamos y paramos de editarla. Esta canción se mueve de la lista de "canciones en edición" a la lista de "canciones listas". Si es que no se descarga es canción lista y por lo tanto no se crea su archivo midi, si aún así intentamos editar esa canción denuevo, no habrá un archivo midi de esa canción para leer. ¿Que se debe hacer en un caso asi? ¿Solo se pueden editar las canción si es que existe un archivo midi para esa canción?

Gracias

**Comment by Hernan4444** [comment]
creo que estás confundiendo las cosas que puede hacer el cliente y el servidor. Cuando tu creas una canción y la editas, **el servidor debe guardar dicha información en tiempo real**, por lo tanto no es necesario que el cliente tenga que descargar el archivo midi para editarlo.

**Comment by Unknomads** [comment]
Una duda: Cuando dices "el servidor debe guardar dicha información en tiempo real", esto significa guardar la información en un archivo midi en tiempo real?

**Comment by Hernan4444** [comment]
@Unknomads idealmente, pero no es estrictamente necesaria, puedes hacerlo en un txt por ejemplo. El fin es que el cliente crea que su canción fue guardada y puede volver a editarla y cuando ya está satisfecho la puede descargar y ahí escucharla.

**Comment by Unknomads** [comment]
@Hernan4444 perfecto me quedo todo claro. Muchas gracias!

**Comment by shantifabri** [comment]
@Hernan4444 Puedo guardar la información de la canción en un objeto canción (de una clase creada por mi) y que el servidor maneje esos objetos en vez de en un txt?

**Comment by Hernan4444** [comment]
@shantifabri si, no hay problema, mientras cuando uno quiera descargar el midi, no le mande la clase al cliente.

**Comment by shantifabri** [comment]
@Hernan4444 entendido. Muchas gracias!
