### ISSUE TITLE
PyQt no me permite recibir el keyPressEvent de más de tres teclas a la vez

### ISSUE THREAD

**Issue by tqmbanados** [IIC2233/syllabus#772]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola, al modelar el modelamiento de la zona de cáptura, me encontre con un problema. Logro que al presionar una tecla, se "active" la zona de cáptura correspondiente, sin embargo, si presiono más de dos teclas, el teclado se bloquea y deja de enviar eventos a PyQt. Específicamente, las teclas ``w`` y ``s`` pueden apretarse al mismo tiempo, pero si agrego la tecla ``a`` o ``d``, estas no son recibidas por el handler keyPressEvent. Si no resuelvo este problema, no podré implementar que se puedan activar tres cajas a la vez. *¿Cómo se logra que el teclado envíe señales de 3 o más teclas presionadas a la vez?*

**Comment by kadroguett** [comment]
Hola @tqmbanados, este problema lo suelen tener muchos teclados y es debido a su fabricación. Para solucionar esto puedes cambiar la combinación de teclas que usas para encontrar una combinación de 3 teclas que te funcione correctamente.

**Comment by tqmbanados** [comment]
Hola, lástima que pase esto. No será problema aunque sea para seleccionar las flechas (que idealmente sería con combinación WASD)

**Comment by kadroguett** [comment]
Por este mismo problema se dejan como parámetros las flechas en el enunciado, éxito en tu tarea!

**Comment by tqmbanados** [comment]
gracias!
