### ISSUE TITLE
Hacer que los child widgets no hereden el stylesheet

### ISSUE THREAD

**Issue by drosselot** [IIC2233/syllabus#772]
Hola, estoy tratando de usar el método setStyleSheet() y para esto cambié el background-color de la ventana. Lo que ocurre es que todos los widgets dentro de este, también cambian su background-color. Sé que puedo cambiar cada uno, pero no hay una forma más fácil de que todos mantengan el stylesheet por default, menos la ventana? Busqué en google, pero todo dice que lo cambie uno por uno. Muchas gracias :)

**Comment by kadroguett** [comment]
Hola @drosselot 
Una forma de arreglar esto es utilizar un Qlabel del tamaño de la ventana y agregarle el background-color que desees, solo se mantendrá en ese Qlabel y no en los demás.

**Comment by drosselot** [comment]
Ahí me funciono perfecto, gracias :)

**Comment by kadroguett** [comment]
De nada, éxito en tu tarea!!

**Comment by furcelay** [comment]
Hola!
Si no quieres que los contenidos se hereden en el StyleSheet tienes que especificar en qué instancia se va a aplicar. Te muestro la diferencia:

1. StyleSheet se hereda a todos los contenidos de este widget:
```
background-color: rgb(140, 140, 140);
```

2. StyleSheet se hereda a todos los contenidos de este widget de la clase QWidget (o que hereden de esta):
```
QWidget {
background-color: rgb(140, 140, 140);
}
```

2. StyleSheet solo se aplica a esta instancia:
```
QWidget#nombre_de_este_widget {
background-color: rgb(140, 140, 140);
}
```
