### ISSUE TITLE
¿Cuando usar backend?

### ISSUE THREAD

**Issue by daniela-carreno** [IIC2233/syllabus#773]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola, [**les quería preguntar por algún tip de cómo identificar la separación de fronend y backend; y tip para modularizar una gui.**]  PD. la clase 9.3 no es suficiente

Por ejemplo, tengo una clase VentanaJuego en una carpeta de front. Actualmente ahí tengo todo lo relacionado al juego y aún me faltan desarrollos. En total sería: la interfaz, un método que va contando el tiempo transcurrido, reproducir la canción, hacer que las flechas aparezcan con su probabilidad asociada y que además se muevan, detectar las teclas apretadas, llevar el conteo de puntaje, el avance de las estadísticas y los pingüinos bailando.  Entonces con todo eso en el mismo archivo, casi segura que quedará de +400 líneas y además pésima cohesión y acoplamiento.

**Comment by knight-who-say-ni** [comment]
Holaa @daniela-carreno !!

Un buen tip para diferenciar que va en que parte es el siguiente: 
En el **front-end**, va todo lo que tenga relación con la **interacción con el usuario**, esto es, la visualizacion, recibir inputs del usuario, etc...

Por otro lado, en el **back-end** va todo lo que tiene que ver con la la lógica detras del programa:  determinar si una acción se puede o no realizar, calculos de formulas, etc...

Además, en una buena modelación ahi una separación clara entre backend y frontend (casi como si fueran programados por distintas personas). Por ello, es necesario una forma de conectar ambos pero que mantenga esta separación lo más posible, y es ahi donde aparecen las **señales**.

Ahora, ¿Como modularizo mi front-end (y no me paso de las lineas)?

Aqui ya depende de tu manera de programar, quiza tienes métodos de backend en front-end, y estos te ocupan lineas, o tienes metodos que distintos que podrias mezclar en uno solo, ya que manejan situaciones parecidas. Si aun así sigues con muchas lineas y no usaste QDesigner para crear la ventana, quiza sea buena idea usarlo, ya que asi te ahorras harto codigo ;).

Espero que te haya aclarado las dudas, cualquier cosa me avisas!!
