### ISSUE TITLE
Duda sobre BackEnd y FrontEnd

### ISSUE THREAD

**Issue by ancontardo** [IIC2233/syllabus#773]
Hola, tengo una duda sobre una posible mala practica....
Hasta ahora yo cree 3 archivos .py, estos son frontend.py, backend.py y main.py.
En el primero creo todas las ventanas y señales, en el backend.py proceso la informacion y cree algunas clases y en el main.py instancio al backend y frontend y conecto las señales para iniciar mis ventanas y comenzar a ocupar el juego...
Mi pregunta es: ¿Puedo conectar una señal del frontend.py directo con la de backend.py? ¿y no necesariamente conectarlas en el archivo main.py?

**Comment by lucasvsj** [comment]
Si haces esto, quiere decir que instanciaste una clase del **backend** en tu **frontend**. Esto no esta mal, pero no estarías siendo  consistente con el formato que elegiste para elaborar tu programa, ya que este formato (backend, frontend, main) consiste en:

- Definir todas las clases relacionadas con el **backend** en `backend.py`
- Definir todas las clases relacionadas con el **frontend** en `fornted.py`
- Instanciar todas las clases en el `main.py` y realizar las **conexiones de señales**

Vuelvo a reiterar, no estaría mal, ya que es posible, pero se podría decir que es mala practica al elegir este método como modo de realizar tu programa.
