### ISSUE TITLE
Restringir acciones del usuario

### ISSUE THREAD

**Issue by llloyola** [IIC2233/Syllabus#773]
Hola! Me gustaría saber si lo que estoy haciendo está bien o no. Mi interfaz parte con:

- Un QLineEdit vacío para el nombre de usuario 

- Un QLineEdit __inhabilitado__ para el nombre de una canción nueva

- Botones __inhabilitados__ para editar (en particular, este botón también sirve para ser espectador, dependiendo de la canción seleccionada), descargar o crear una canción

- Las listas _Canciones listas_ y _Canciones en edición_ vacías

Una vez que el cliente se conecta con el servidor:

- Añado a _Canciones listas_ y _Canciones en Edición_ los strings (nombre de canciones) correspondientes

Una vez que el usuario ingresa un username válido y el servidor compruebe que es único (si alguna de estas cosas no se cumple, le hago saber el usuario mediante un QMessageBox la condición que no se cumplió y se ve forzado a volver a intentar definir su username):

- Reemplazo el QLineEdit del nombre de usuario con un QLabel con el username que ingresó (para que no vuelva a cambiarlo durante su conexión). ¿Puedo hacer esto? Yo asumí que el usuario debía cerrar la aplicación si quiere ingresar con otra "cuenta". Si no me equivoco, en ninguna parte del enunciado dice que se deba permitir el cambio de un usuario a otro en la misma interfaz

- Habilito todos los widgets (QPushButtons y QLineEdit) que estaban inhabilitados, pues el enunciado dice que el usuario sólo podrá optar a realizar acciones si su username es válido. ¿Está bien esto? ¿Hay algo que el usuario pueda hacer sin la necesidad de ingresar un username?

Si el usuario quiere crear una canción (__lo cual sólo puede ocurrir si ingresó un nombre de usuario válido__):

- En el cliente, confirmo que el nombre de la canción tenga mínimo 6 carácteres

- Confirmo, a través del servidor, que el nombre de la canción sea único

- Si se cumplen las restricciones anteriores, le permito comenzar a crear la canción en una nueva ventana

¿Hay algo malo en lo que estoy haciendo o en las cosas que asumí? ¿Hay alguna cosa innecesaria? ¿Debería quitar o agregar un paso/algo a mi forma de enfrentar el "problema"?

Gracias de antemano
Sorry for long issue, here's a potato 🥔

**Comment by Hernan4444** [comment]
Hola, está casi bien.

> ¿Está bien esto? ¿Hay algo que el usuario pueda hacer sin la necesidad de ingresar un username?

Lo único que puede hacer es ver la lista de canciones listas, en edición **y descargar una canción de la lista "canciones listas"**. En el enunciado se especifica que se comprueba el username solo cuando quiere crear una canción, editar y cuando hace click en una canción de la lista "canciones en edición, y esas cosas si estás cumpliendo. Por lo tanto, si permites que en esa interfaz se pueda descargar la canción sin poner mi usuario, entonces está todo bien, en otro caso, estás haciendo un supuesto que contradice el enunciado.

Saludos ✌️

**Comment by llloyola** [comment]
Mmm...

![potato](https://user-images.githubusercontent.com/30671859/41813107-7d315124-76fd-11e8-937b-7f304a9ead82.gif)

Bkn! Gracias totales 😄
