### ISSUE TITLE
Duda Designer y Layouts

### ISSUE THREAD

**Issue by Zenos-Paradox** [IIC2233/syllabus#774]
* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

Con Designer, se puede definir una proporción entre los widgets dentro de un layout?
En código se puede:
```
hbox = HQBoxLayout()
hbox.addWidget(widget1, 1)
hbox.addWidget(widget2, 2)

```
Aquí, widget2 usaría el doble de espacio que widget 1, según entiendo. Hay alguna forma de hacer esto con Designer?

**Comment by furcelay** [comment]
Hola @Zenos-Paradox !
Si se puede!!
En las propiedades del *Widget* que tiene el *layout* hay una sección específica del *layout* y ahí hay un parámetro llamado *laout stretch* que tendrá números separados por comas (uno por cada widget contenido en el *layout*), cada número representa la proporción relativa o el % del layout que usa (es el mismo argumento que le pasas al método en tu ejemplo).

Adjunto una imagen de ejemplo:
![image](https://user-images.githubusercontent.com/61999313/96936982-85137d00-149d-11eb-874e-df0aa5637e21.png)

Saludos! :smile:
