### ISSUE TITLE
Archivos semana 11

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2233/syllabus#774]
Hola me meto a contenido y cuando clickeo en la semana 11 me aparece un error, de que no hay nada dentro de la carpeta.
![image](https://user-images.githubusercontent.com/62180259/82499425-a4a61400-9abf-11ea-8940-39797ebff436.png)

**Comment by DaHunterTime** [comment]
Hola, cambiaron el nombre de la semana 11 a semana 12 para ser consistentes con la semana de pausa, de igual forma aquí te dejo el [link](https://github.com/IIC2233/contenidos/tree/master/semana-12)
