### ISSUE TITLE
Interfaz distinta al enunciado

### ISSUE THREAD

**Issue by mlvinay** [IIC2233/Syllabus#774]
Disculpen, queria preguntar si es posible hacer alteraciones a la interfaz comparada la que se muestra en el enunciado (.pdf).

Para ser especifico, en la ventana de edicion, puedo agregar 2 radio buttons para el modo espectador - editor?

Por otra parte, es posible el uso de spin boxes para las notas, intensidad, duracion, etc? Esto eliminaria la posibilidad de que el usuario ponga un input erroneo (lo que podria ir en contra  de lo que desean que hagamos, por ende pregunto).

**Comment by Hernan4444** [comment]
Hola, la interfaz no tiene que ser exactamente como está en el pdf, pueden agregar y editar mientras no esté en contra de lo solicitado. En el caso de spin boxes, si no mal recuerdo, eso solo permite números, pero nosotros solicitamos que su interfaz maneje además otros tipos de inputs diferentes a solo números y si revisas la distribución de puntaje, se evalua que seamos capaces de ingresar todos los tipos de inputs diferentes.

**Comment by mfanselmo1** [comment]
Hola!
No hay problemas con que hagas cambios a la interfaz dada en el enunciado mientras tenga todo lo que se pide. Por otro lado, no entendi lo de los radio buttons, ya que se tiene que elegir desde la ventana principal si se quiere editar una cancion, y luego siempre van a ser espectadores.
Con respecto a los spin boxes, tampoco hay problemas con eso, mientras se puedan ingresar todos los tipos de inputs.
