### ISSUE TITLE
Actualización de readme

### ISSUE THREAD

**Issue by JPSF** [IIC2233/Syllabus#774]
Olvidé enviar la última actualización de mi readme de la tarea 6 ¿Cómo puedo indicarle al ayudante que corregirá mi tarea que considere la última actualización (que fue después del plazo)? Ya que de esta forma le sería mucho más fácil realizar la corrección.

**Comment by ifcarrera** [comment]
Hola! 
Recuerda que el plazo para el README de la T06 es hasta hoy a las 23:59, por lo que aún estás a tiempo de subirlo.
Saludos :)

**Comment by JPSF** [comment]
No sabía jajaj
Muchas gracias
