### ISSUE TITLE
ventanas como parametros

### ISSUE THREAD

**Issue by knight-who-say-ni** [IIC2233/syllabus#775]
Tengo una duda con el archivo parametros.py. Yo estoy creando las ventanas en QTDesigner, y para crearlas en el código, hay que crear parametros ventana, base_class:

ventana, base_class = uic.loadUiType("nombre.ui")

ventana y base_class debería estar en parametros.py?? O puedo tenerlos en el mismo archivo donde creo la ventana??

Muchas gracias!!

**Comment by cristozille** [comment]
Hola! "nombre.ui" debería estar en parametros.py, pero como ventana y base_class son llamados de funciones y no son constantes van en el frontend :)

**Comment by knight-who-say-ni** [comment]
Gracias!!!
