### ISSUE TITLE
no aparece en python ventana de QtDesigner

### ISSUE THREAD

**Issue by aayale** [IIC2233/syllabus#775]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola, estoy usando QtDesigner para la tarea y cree una ventana y al llamarla como nos enseñaron no me sale nada, luego la cambié a la carpeta de sprites (pensando que podia ser que no la ubicaba) y me sale que no existe mi archivo.ui (sprites está en gitignore pero me encargue que ese archivo no fuera ignorado). Entonces no se a que se puede deber este error, ni que hacer al respecto

**Comment by kadroguett** [comment]
Hola @aayale, puedes subir el archivo.py donde intentas abrir el archivo.ui para ver que puede estar fallando, por favor

**Comment by aayale** [comment]
El archivo es un archivo de prueba, por lo que literalmente tengo escrito solo código necesario para que aparezca esta ventana de QtDesigner. Pondré el codigo aquí:

    from PyQt5 import uic
    from PyQt5.QtWidgets import QApplication
    import sys
   
    window_name, base_class = uic.loadUiType('prueba.ui')

    class MainWindow(window_name, base_class):

    def __init__(self):
        super().__init__()
        self.setupUi(self)
        

    if __name__ == '__main__':
       app = QApplication([])
       form = MainWindow()
       form.show()
       sys.exit(app.exec_())

Como dije, en estos momentos el archivo 'prueba.ui' está dentro de la carpeta sprites y al correrlo sale el siguiente error:
**FileNotFoundError: [Errno 2] No such file or directory: 'prueba.ui'**

Pero cuando lo tenia fuera de la carpera sprites me aparecia una ventana en blanco

**Comment by kadroguett** [comment]
Comprendo, primero el error que te sale es porque al escribir `uic.loadUiType('prueba.ui')` estás considerando que el archivo está en la carpeta actual, así que deberás devolverlo o bien cambiar el path.  En segundo lugar, el archivo `prueba.ui` que tenía que no se muestra al abrirlo en python?

**Comment by aayale** [comment]
aaaaa ok, voy a probar cambiando el path. 
Y esto era lo que intentaba mostrar: (así me aparece en QtDesigner)

![image](https://user-images.githubusercontent.com/69651451/96938789-a8402b80-14a1-11eb-973a-e63811694bd7.png)

**Comment by kadroguett** [comment]
Tienes creado el archivo `resource.qrc`? si ese es el caso debes transformarlo a resource_rc.py. 
Esto lo haces abriendo cmd en la carpeta donde se encuentra `resource.qrc` y escribiendo el siguiente comando:
`pyrcc5 resource.qrc -o resource_rc.py`
Si creaste resource.qrc antes de agregar las imágenes a Qtdesigner tendrás que crearlo de nuevo.
Por otro lado, si te sigue apareciendo el `PermissionError`, puedes probar borrando `sprites` del `.gitignore` y ver si te funciona así, pero no olvides agregarlo más tarde.

**Comment by aayale** [comment]
ok, voy a probar. Muchas graciaaas!

**Comment by kraksiplus** [comment]
Me agrego a la consulta, tanto en la tarea como en los ejemplos de la semana 10 cuando intento embeber el .ui a mi .py, vscode no me encuentra el archivo, cambie el path, pero nada :c

**Comment by aaossa** [comment]
Hola @kraksiplus , para poder trabajar de mejor manera con estas cosas tienes que fijarte que los la ruta a los *.ui sea relativa al archivo que vas a ejecutar y también que la consola esté en el directorio que contiene al archivo que vas a ejecutar. Tal vez lo que te falta es mover la consola de VS Code. De todas maneras, en general lo mejor es correr el código desde la consola del sistema operativo, fuera de VS Code, así que prueba con eso también. Si no es eso, ¿podrías agregar una captura del error? ¡Éxito con la tarea! ✨

**Comment by kraksiplus** [comment]
@aaossa En la frustracion me cambie de OS para tener finalmente el mimso problema jaja xD, te anexo pantallazo del error tanto el de la termina de ubuntu como el de Vscode 

![image](https://user-images.githubusercontent.com/68204942/97222970-e2fdd880-17ad-11eb-92c4-73c3fc30b1cf.png)

![image](https://user-images.githubusercontent.com/68204942/97223036-fc068980-17ad-11eb-913b-f3dee8de4830.png)

**Comment by kadroguett** [comment]
@kraksiplus si estás corriendo tu `main.py` y tus carpetas están ordenadas de esta forma:
```
main.py
parametros.py
--> frontend
    --> ventana_de_inicio.ui
    --> archivo.py
```
Intenta cambiando el path que se encuentra en la línea 6 por:
`"frontend\\ventana_de_inicio.ui"
`
Me cuentas si se arregla tu problema.

**Comment by mzigm** [comment]
Hola @kraksiplus, me pasa lo mismo. Intente hacer eso pero tampoco me funcionó. 
Gracias

**Comment by kadroguett** [comment]
Hola @mzigm, tienes el mismo error que @kraksiplus? Si es así puedes subir a tu repositorio lo que llevas para revisar bien el problema por favor.

**Comment by mzigm** [comment]
@kadroguett ahí lo subí

**Comment by kadroguett** [comment]
Te aparece este error `ModuleNotFoundError: No module named 'front_end'` ?
Si es así debes cambiar esto:

![image](https://user-images.githubusercontent.com/31357861/97255072-92f33600-17ee-11eb-9cbc-d72bf54b47aa.png)

Por esto:

![image](https://user-images.githubusercontent.com/31357861/97255096-9f778e80-17ee-11eb-8971-c0bce20f12e2.png)

Ten en cuenta que debes poner el nombre exacto de las carpetas y estas no llevan el "_". Si no es este el problema me avisas para seguir revisando.

**Comment by mzigm** [comment]
No me funciona importar 'Ventana_juego_qt.ui' del qt designer. En el modulo 'Ventana_juego.py' del frontend lo trato de importar pero me sale el error: FileNotFoundError: [Errno 2] No such file or directory: 'frontend\\Ventana_juego_qt.ui'

**Comment by kadroguett** [comment]
Comprendo, en el caso de que ejecutes el módulo `ventana_juego.py` el path debe ser `Ventana_juego_qt.ui`, mientras que si ejecutas el main e intentas importar el archivo `ventana_juego.py` el path deberá ser `frontend\\Ventana_juego_qt.ui`.

**Comment by mzigm** [comment]
Intente así también pero tampoco me funciona importarlo
.

**Comment by kadroguett** [comment]
Lo intenté de las dos formas, ejecutando el archivo `ventana_juego.py` y ejecutando `main.py` importando el módulo de ventana juego y me funciona en ambos casos. Qué error tienes al importarlo?

**Comment by mzigm** [comment]
El error: FileNotFoundError: [Errno 2] No such file or directory: 'Ventana_juego_qt.ui'

**Comment by kadroguett** [comment]
Si estas ejecutando el `main.py` e intentas importar este archivo tienes que cambiar el path en `Ventana_juego.py` para que quede de esta forma: 

![image](https://user-images.githubusercontent.com/31357861/97256635-53c6e400-17f2-11eb-8e7f-ed84aa8c36a4.png)

**Comment by mzigm** [comment]
Lo estoy tratando de correr en la misma ventana('Ventana_juego'), no en el Main.

**Comment by kadroguett** [comment]
Como te dije más arriba, si lo corres en el archivo `Ventana_juego.py`, el path debe ser `Ventana_juego_qt.ui`. De esta forma:

![image](https://user-images.githubusercontent.com/31357861/97257564-12840380-17f5-11eb-8861-71544881d8d8.png)

**Comment by mzigm** [comment]
Sisi, lo hice así al principio pero me sale el mismo error que te comente antes.

**Comment by kadroguett** [comment]
Estás seguro de escribir bien el nombre del archivo? al ejecutarlo me anda bien y se abre la ventana:

![image](https://user-images.githubusercontent.com/31357861/97257773-afdf3780-17f5-11eb-862b-beb6cee4d341.png)

**Comment by mzigm** [comment]
Seguro. 
Ahora logre que me funcione debuggeandolo de otra manera.
Gracias por la ayuda!

**Comment by kraksiplus** [comment]
@mzigm podrias explicar bien superficial como debugeaste?, ahora estaba en otra tarea y no podia enfocarme full progra 

Gracias de antemano :3

**Comment by FernandoLarrea** [comment]
hola, tengo el mismo problema, @mzigm cómo lo solucionaste?? 😿

**Comment by mzigm** [comment]
Antes estaba apretando la flecha verde arriba a la derecha en VS, ahora lo debuggeo con F5 o apretando Run -> Run Without Debugging(arriba a la izquierda)
