### ISSUE TITLE
Cantidad de paises y ciudades

### ISSUE THREAD

**Issue by nachocontreras** [IIC2233/Syllabus#775]
Para la planilla de Google Sheets con las ciudades:

¿existe una cantidad mínima o máxima, de paises y ciudades, que debamos tener? 

Porque luego de hacer las consultas a Google Maps sobre la ubicación de las ciudades, si es que hay muchas (+50 por pais), aparece el error `OVER_QUERY_LIMIT`

**Comment by nachocontreras** [comment]
En Google Maps.

**Comment by ifcarrera** [comment]
Estás haciendo un For o un While y obteniendo TODAS las coordenadas para todas las ciudades o algo por el estilo?

**Comment by ifcarrera** [comment]
Te recomiendo revisar este [https://developers.google.com/maps/premium/previous-licenses/articles/usage-limits?hl=es](link). Habla sobre el límite de `querys` que se pueden hacer por intervalo de tiempo. Es probable que estés en un loop, entonces estás haciendo todas las consultas en poco tiempo y se te acabó el límite.

**Comment by nachocontreras** [comment]
sí, un for sobre las ciudades de cada pais para obtener sus coordenadas

**Comment by vixolo** [comment]
La API de Google Maps permite hasta 50 request por segundo y 2500 por día!

**Comment by ifcarrera** [comment]
No entiendo a qué te refieres con segundos de espera
