### ISSUE TITLE
leer_midi y generr_midi

### ISSUE THREAD

**Issue by Pipelao** [IIC2233/Syllabus#776]
Hola buenas,
Una pregunta, las funciones de escribir y leer los midi, ¿los pueden ocupar tanto el servidor como el usuario o sólo el servidor? Digo por ejemplo para que del servidor al cliente se le envíen las notas en string (no como bytes) y luego en el cliente decodificarlas y escribir el archivo pasándolas ahí a bytes.

Gracias de ante mano

**Comment by Hernan4444** [comment]
@Pipelao se espera que solo en el servidor. Tal como se indica en el enunciado

> El servidor se debe encargar de la lógica del sistema y la música creada es parte de la lógica de esta tarea.

Saludos ✌️

**Comment by Pipelao** [comment]
Ok, gracias.

**Comment by santilaguna** [comment]
@Hernan4444 ¿pero podemos mandar los bytes del midi y re armar la canción en el cliente no?, ¿o debemos enviar el archivo completo?

**Comment by Hernan4444** [comment]
@santilaguna para mandar el archivo, tienes que mandar los bytes 🤔. No entiendo cual es la diferencia en tu pregunta 😞

**Comment by santilaguna** [comment]
@Hernan4444 que había visto formas de mandar el midi completo, sin necesidad de leerlo, pero al final como nos evalúan la lectura del midi lo haré de la forma habitual nomás.

**Comment by Hernan4444** [comment]
Solo para dejar las cosas claras, la lectura del midi se va a evaluar cuando nos digas las notas de los midis previamente generados (los que dimos de ejemplo). Porque mandar un archivo es solo abrirlo en forma de bytes y mandar eso,  no implica saber cómo es la estructura del midi para que el cliente pueda tener el archivo, pero si se requiere saber la estructura del midi al momento de pedir las notas de este.
