### ISSUE TITLE
Problema con Layouts

### ISSUE THREAD

**Issue by vtunon7** [IIC2233/syllabus#776]
Hola! Estoy teniendo problemas con los Layouts, creo un QVBoxLayout, luego un QHBoxLayout en donde le agrego con `addLayout(vbox)` y despues hago el `setLayout(hbox)` y al momento de correr el codigo me aparece una ventana así:
![image](https://user-images.githubusercontent.com/48421226/82500934-63fbca00-9ac2-11ea-90ef-c3f418468ce4.png)
Al parecer se amontonan todos los widgets en la esquina, y lo unico que he modificado en los widgets es el porte con `sizehint` y el logo con `scaledContens`

**Comment by moquezada** [comment]
Hola @vtunon7!

Perdón la demora 😅 ¿Te aseguraste de hacer el `show` luego de setear los layouts? Tuve el mismo error en su momento y fue por realizar el `setLayout` después del `show` 👀

**Comment by vtunon7** [comment]
Si, le pongo `self.show()` despues de setear todos los layouts. No se si puedo mandar esa parte del codigo para mostrar. Es como que no estuvieran entrando al Layout los widgets

**Comment by moquezada** [comment]
@vtunon7, quizás podrías escribir un código de ejemplo sobre lo que estás haciendo para poder ayudarte mejor :) lo otro sería que subas tu código a tu repositorio y así poder ver en detalle lo que puede estar produciendo un error 👀

**Comment by vtunon7** [comment]
Gracias por responder a esta hora! Voy a subir mi codigo al repositorio mejor, pero ahora mi problema es otro, se me hace el layout pero la imágen se hace gigante, no funciona haciendole `setGeometry` ni `setScaledContents`.

**Comment by moquezada** [comment]
Qué bueno que lograste solucionar tu anterior problema! :D Dado que ahora tienes una duda que es distinta a la anterior, recomiendo que hagas otra issue al respecto :) Pero antes te recomiendo ver la issue #732 que se relaciona con tu nuevo problema 🧙

**Comment by vtunon7** [comment]
Muchas Gracias!
