### ISSUE TITLE
 QLineEdit para recibir los CheatCodes

### ISSUE THREAD

**Issue by totoiii** [IIC2233/syllabus#776]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [si ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

**Puedo crear un LineEdit para recibir todos los CheatsCodes??**
Obviamente activando y desactivando cada cheatcode cuando sea pertinente.

**Comment by furcelay** [comment]
Hola @totoiii !
No puedes, la idea es hacerlo manejando los eventos de teclado correspondientes sin un campo de texto,

Saludos! 😄
