### ISSUE TITLE
Latitud y longitud en twitter

### ISSUE THREAD

**Issue by NicolasSalgado** [IIC2233/Syllabus#776]
Estoy buscando información en la Api de twitter para la obtención de _trending topics_ , pero, si bien había una cuya descripción calzaba perfecto con lo requerido, si uno veia la **API Reference** está no ocupaba la latitud y longitud sino un número de un cierto sistema **WOEID** y por lo que estuve buscando para poder transformar de (latitud, longitud) a WOEID necesitaría entrar en la API de Yahoo.
¿Está bien esto?, ¿esto es lo que se espera que hagamos, o existe otra forma solo mediante la API de twitter y que ocupe la latitud y longitud?(llevo un buen rato buscando y no encuentro nada 😓)

**Comment by ifcarrera** [comment]
Hola! Efectivamente necesitas el `WOEID`, el cuál puedes conseguir utilizando la misma API de Twitter. Sigue buscando y encontrarás como obtenerlo! 
Saludos y ánimo 😄

**Comment by fedetaladriz** [comment]
@ifcarrera podemos ocupar la api de yahoo para encontrar el woeid?

**Comment by ifcarrera** [comment]
Holi! Lamentablemente no se puede. Lo bueno es que con la de Twitter es suficiente 😄 .
Saludos
