### ISSUE TITLE
Duda sobre QSound

### ISSUE THREAD

**Issue by francoschiaffino** [IIC2233/syllabus#777]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola, tengo una duda sobre el uso de la librería QSound. He buscado en la lista de las funciones que contiene esta librería y no he logrado encontrar ninguna que permita pausar la canción que se está reproduciendo, solo encontré "stop()", que para directamente la canción y hace que esta comience denuevo. Esto me pareció extraño teniendo en cuenta que se nos recomendó usar esta librería para reproducir las canciones.  Entonces, ¿Existe realmente una forma de pausar la canción y que no comience denuevo con esta librería o debo simplemente usar la librería QMediaPlayer? Gracias de antemano

**Comment by JadrinaDA** [comment]
Hola! Tienes razón en que QSound no tiene una forma de pausar realmente. Sin embargo, no hay problema con que se reinicie la canción al ponerle play de nuevo. Si quieres un mayor control sobre el audio QMediaPlayer es una herramienta más poderosa que QSound pero no es necesario. Depende de lo que tu quieras para tu tarea. Éxito!

**Comment by francoschiaffino** [comment]
Ok. Muchísimas gracias. Saludos!

**Comment by JoseTomasSoto** [comment]
como se usa QMediaPlayer ?

**Comment by JadrinaDA** [comment]
Hola! Parte de esta tarea es aprender a investigar como usar las herramientas que las librerías de Python te dan para trabajar. Por lo tanto no te puede decir como de usa QMediaPlayer pero sí te puedo decir dónde empezar tu búsqueda. Siempre es una buena idea partir por la documentación cuando buscas información de una clase como QMedia player, [aquí](https://doc.qt.io/qt-5/qmediaplayer.html) está el link. Buena suerte!
