### ISSUE TITLE
Edición de canciones 

### ISSUE THREAD

**Issue by sjkinast** [IIC2233/Syllabus#777]
Hola! tengo dos dudas, la primera es que no me queda claro si al editarse una canción esta edición debe sobreescribir los archivos que tiene el servidor de la canciones o simplemente es algo que ven los conectados a esa edición y el editor. La otra duda es de la issue #776, ya que en el enunciado dice que el cliente es el encargado de verificar si al ingresar una nota esta bien o no , por lo menos en mi caso aprovecha de verificar y transformarla a un formato a como se encuentrarn las notas en la figura 4. Mi duda es si es lo que dice la issue anterior se refiere a la decodificación de las notas en terminos de bytes ,o también que yo no podría pasar una nota en el cliente de formato ingles a formato español (porque para verificar si es valida igual tengo que consultar la nomenclatura).

**Comment by leolivares** [comment]
Hola, @sjkinast.
Al editar una canción, el cambio debe ser reflejado en el servidor, de tal forma que los otros usuarios vean las modificaciones.
El cliente debe verificar que el input del usuario sea correcto, para luego mandar al servidor el cambio realizado. De esta manera, el servidor es el encargado de trabajar con la información a nivel de bytes, para posteriormente transmitir el cambio a todos los usuarios.
Espero que te ayude.

**Comment by sjkinast** [comment]
Es que estoy medio confundido se supone que los cliente solo visualizan las canciones y sus notas  como de manera online sin tenerlas, a menos que la descarguen cierto? entonces no entiendo si alguien modifica esa cancion esa modificación   es permanente osea en la memoria del servidor yo agrego bytes al archivo mid ?

**Comment by leolivares** [comment]
@sjkinast Si, los clientes no tienen los archivos (a menos que los descarguen).
Si alguien modifica la canción, sería permanente, ya que modificaría el archivo en el servidor.
