### ISSUE TITLE
Formato de escritura stylesheet

### ISSUE THREAD

**Issue by drosselot** [IIC2233/syllabus#777]
Hola, si queremos usar setStyleSheet() dentro del código hay algún formato que debamos seguir? Pregunto esto porque en mi código estoy escribiendo todo en la misma línea y separandolo por \ :

`self.boton_nueva_partida.setStyleSheet('background-color: #e76f51; \
        border-style: solid; border-width: 5px; border-color: #D66449;\
         padding: 20px; color: #4A0907;')`

Esto no se ve muy ordenado y no se si me descuenten puntos por eso, además que me gustaría ordenarlo un poco más pero no sabría como me conviene.

**Comment by furcelay** [comment]
El formato que se usa es CSS (el mismo que se usa para dar forma a las páginas web en html), hay mucha información de este formato en internet si necesitas algo específico. Si lo escribes en python te va a quedar así de feo (creo que los `\` los interpreta como `\n`), pero puedes definirlo en QtDesigner (click derecho edit stylesheet o en el editor de propiedades):
![Screenshot from 2020-05-20 18-01-28](https://user-images.githubusercontent.com/61999313/82501940-1a13e380-9ac4-11ea-99d1-bdaec7839b30.png)

**Comment by fdoflorenzano** [comment]
Hola @drosselot,

Como bien dice @furcelay, el lenguaje de especificación que usa `setStyleSheet` es CSS, que es su propia forma de escribir reglas de estilo. Como no es un lenguaje que revisemos en este curso, no esperamos que escriban de cierta forma específica su contenido. 

Ahora, puedes hacer lo que dice @furcelay, y hacer las definiciones es Designer para evitar definirlas en Python. Pero si deseas usarlas en código, como aún estamos usando Python para hacer estas declaraciones mediante *strings*, para efectos de la tarea se sigue esperando respetar el largo máximo de línea solamente. Puedes definirlos como quieras mientras respetes eso.

Por ejemplo, tal vez separando por líneas las declaraciones para algo más ordenado:
```python
estilo = (
    'background-color: #e76f51; '
    'border-style: solid; '
    'border-width: 5px; '
    'border-color: #D66449; '
    'padding: 20px; '
    'color: #4A0907; '
    )
elemento.setStyleSheet(estilo)
```
Pero claro, esto ocupa varias líneas de código. También puedes considerar migrar estas definiciones de estilo a `parametros.py` al tratarse de un atributo estético de una ventana que no cambia necesariamente durante la ejecución del programa. Pero depende de lo que quieras hacer con este.

Espero se entienda,
Saludos.
