### ISSUE TITLE
Diferencia en paths Windows/Linux con QtDesigner

### ISSUE THREAD

**Issue by furcelay** [IIC2233/syllabus#778]
Hola!
Para mi programa tengo una estructura como la siguiente:
```
T02
├── main.py
├── backend
│      ├── cafe.py
│      └── entidades.py
├──  frontend
|      ├── labels_mapa.py
|      ├── ventana_ronda.py
|      └── ventana_ronda.ui
└──  sprites
        └── sprite_x.png
```
El problema que tengo es que estaba trabajando con **Windows** y definí en `ventana_ronda.ui` 
(archivo de QtDesigner) los paths de los `pixmaps` para distintos `labels` **relativos a `T02`**, por ejemplo: `sprites/sprite_x.png`.

El archivo `ventana_ronda.ui` se carga en  `ventana_ronda.py`. 

Al probar el mismo código en **Linux** no me cargaban las imágenes (los paths en `ventana_ronda.ui` usan `/` y no `\` independientemente del OS) y noté que si cambiaba los paths **relativos a `frontend`** si los cargaba , por ejemplo `../sprites/sprite_x.png`.

¿A qué se debe esta diferencia? ¿ Acaso el comando `window_name, base_class = uic.loadUiType(path_a_ ventana_ronda.ui)` funciona distinto dependiendo del OS?

El programa se corre desde `main.py` en `T02` por lo que, según entiendo, todos los paths deberían ser relativos a este directorio...

Puedo solucionar el prolema si muevo el archivo  `ventana_ronda.ui` a `T02` o bien definiendo todos los `pixmap` en Python en vez de en QtDesigner pero de todos modos me gustaría entender el problema si es posible.

**Comment by matiasmasjuan** [comment]
Hola @furcelay !

Investigando al respecto, no creo que los comandos
```python
window_name, base_class_name = uic.loadUiType(path_a_ventana.ui)
```
Difieran con respecto al OS. Si ese es el caso, lo más apropiado sería utilizar la librería **os** para utilizar el **método**: *os.path.join()* de la siguiente forma:
```python
import os
window_name, base_class_name = uic.loadUiType(os.path.join('nombre_carpeta', 'archivo.ui')
```
De tal manera en que no hayan problemas con los ```/``` o ```\```.

El problema **radica** en que **QtDesigner** no es capaz de **acceder** a los **QPixmap** en otras carpetas que no correspondan dentro de su ***path*** **relativo**. Por esta razón, si ubicas el archivo ```ventana_ronda.ui``` a ```T02``` si va a poder acceder a los ***sprites*** y con ello **cargar** las imagenes. Otra forma de solucionarlo es ubicando los ***sprites*** **dentro** de la carpeta ```frontend```. De esta manera, ```ventana_ronda.ui``` si va a poder acceder a ellos mediante un ***path*** **relativo**. Otra solución, de manera quizás mas tediosa, es como tu bien señalas, definir los **QPixmap** en tu **codigo** ya que tecnicamente los ***Qlabels*** si existen, sólo que no fueron capaces de **cargarse** **correctamente** los **QPixmap**.

Espero que esto haya aclarado un poco más el problema.
Mucho éxito con la tarea!

**Comment by furcelay** [comment]
Al final dejé `ventana_ronda.ui` en `T02` y se resolvión el problema. 
Gracias!
