### ISSUE TITLE
cuando se guarda una cancion en edicion?

### ISSUE THREAD

**Issue by naquiroz** [IIC2233/Syllabus#778]
Hola! Si mal no lei, el enunciado no explicita cuando se deben guardar canciones en edicion, asi que por lo tanto, la forma de notificar un termino de edicion queda a mi criterio?

**Comment by Hernan4444** [comment]
Hola, la edición de las canciones son en tiempo real, tu ingresas o eliminas una nota y el servidor ya tiene guardada dicha información. Sobre notificar el termino de edición, si, queda a tu criterio.

**Comment by naquiroz** [comment]
@Hernan4444 Oka! Gracias!

**Comment by naquiroz** [comment]
@Hernan4444 Pero, los cambios deben ser guardados de manera instantanea como midi?

**Comment by Hernan4444** [comment]
@naquiroz no necesariamente, es ideal si lo guardas altiro como MIDI, pero puedes guardarlo como estimes conveniente (por ejemplo un txt o en otra parte). Mientras te asegures que al editar una canción, el cambio debe ser reflejado en el servidor, de tal forma que los otros usuarios vean las modificaciones.

**Comment by naquiroz** [comment]
@Hernan4444 claro, pero, no basta con cambiar la informacion en el backend(en clases respectivas)? es necesario guardarlo en un archivo?

**Comment by Hernan4444** [comment]
@naquiroz piensa en caso que un cliente edita muchas notas, el cambio "se hizo en tiempo real" y el servidor se apaga. Al momento de prender, ¿se pierden dichas notas?. Por eso hago énfasis siempre en un archivo para asegurar la persistencia de datos.
