### ISSUE TITLE
Ubicar pingüirines en la zona de baile

### ISSUE THREAD

**Issue by n4chin** [IIC2233/syllabus#778]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
No entendí muy bien en qué zona se ponen los pinguinos. O sea, ¿tienen que estar en la cuadrícula de baile?, a esto me refiero que si agarro un pingüino y lo quiero poner en la posición c, este debe quedar centrado en el cuadrado central donde se encuentra c? O simplemente, es suficiente que se encuentre dentro de la zona de ritmo?
<img width="960" alt="2020-10-22" src="https://user-images.githubusercontent.com/69605533/96937769-45e62b80-149f-11eb-92a1-10967e075e43.png">

**Comment by knight-who-say-ni** [comment]
Hola @n4chin !! Con que este en la pista de baile basta. Además, como esta no es un cuadrado perfecto, puedes asumir que lo es para que te sea mas facil.

Exito programando!!
