### ISSUE TITLE
Google Maps API

### ISSUE THREAD

**Issue by santi95** [IIC2233/Syllabus#778]
Hola!
Cual API usamos? Busqué Google Maps API y me ofrece 6 :(

![captura de pantalla 10](https://user-images.githubusercontent.com/13787476/33108815-ea4197bc-cf1c-11e7-87d7-64c3b6362f0b.png)

**Comment by ifcarrera** [comment]
Hola! Cuando ingresas al link que está puesto en el enunciado puedes acceder fácilmente a los Servicios Web de la Geocoding API, intenta entrar por ahí. 
Saludos

**Comment by santi95** [comment]
@ifcarrera Entré por ahí y me muestra las mismas 6!

**Comment by santi95** [comment]
https://console.developers.google.com/apis/api/geocoding-backend.googleapis.com/overview?project=dogwood-jet-186803
Supondré que es esta!

**Comment by ifcarrera** [comment]
Cuando entras te da una serie de opciones como: Android, iOS, Web, Servicios Web. Necesitas entrar y leer la documentación de la de Servicios Web.
