### ISSUE TITLE
Acceder a edicion

### ISSUE THREAD

**Issue by Regenschrim** [IIC2233/Syllabus#779]
Según sale en la tabla de puntajes dice que para editar una canción se debe clickear sobre ella, ¿Es esta la única forma de hacerlo o está abierto a otras posibilidades?
Mi programa funciona de la forma en que uno selecciona la cancion y luego clickea en el botón editar para pasar a la ventana de edición, además de preguntar si quiere entrar en modo espectador o editor.

Gracias!!!

**Comment by leolivares** [comment]
Hola @Regenschrim . Como se mencionó en la issue #761, mientras se cumpla con lo solicitado, la interfaz esta abierta a otras posibilidades.
Ten en cuenta que si alguien esta editando, otro usuario no debe ser capaz de entrar como editor.
