### ISSUE TITLE
Subir archivo mapa.csv modificado

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#779]
Hola!
Yo modifiqué el archivo ```mapa.csv``` para que estuviera dentro del mapa que cree en una ventana. Como cambie estos datos, debería subir este archivo? (no considerarlo en el gitignore)

**Comment by tomasgv** [comment]
Hola @Camila-sty !

Efectivamente, si modificaste el archivo `mapa.csv` no es necesario ignorarlo. Además de esto, menciona en tu Readme este cambio para que el ayudante que te corrija lo tenga en cuenta :+1:. 

Si aún así quieres ignorar el archivo, puedes especificar en tu Readme las posiciones que se deben modificar para visualizar los elementos correctamente.

Saludos! ☕ 🐱
