### ISSUE TITLE
Flechas a veces aceleran o frenan

### ISSUE THREAD

**Issue by burizar** [IIC2233/syllabus#779]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola!
Tengo el mismo problema con el avance de las flechas que se menciona en la issue #750. A veces aceleran y otras veces se frenan. Me gustaría saber como arreglarlo sin tener que bajarle la velocidad a la que bajan las flechas.
Gracias!

**Comment by danckoo1** [comment]
hola! de casualidad ese error esta presente en el avance que entregaste o es un error nuevo?, porque al mirar tu avances en mi computador todas las flechas se mueven a la misma velocidad, sin acelerar ni frenar, lo cual sería raro si es que a ti te esta dando problemas 👀

**Comment by burizar** [comment]
No en mi avance no me pasaba y de hecho ahora dejó de pasar
