### ISSUE TITLE
README T06

### ISSUE THREAD

**Issue by inmadariaga** [IIC2233/Syllabus#779]
Puedo subir una actualización a mi readme? para así facilitar la corrección?

**Comment by ifcarrera** [comment]
Mientras sea para facilitar la corrección puedes hacerlo, pero claramente tu nota será en base al último que subiste a la hora. 
Saludos :D

**Comment by sebacruzd** [comment]
No pierdes nada subiéndolo, yo siempre reviso el último que se ha subido 😊
