### ISSUE TITLE
Duda sobre path

### ISSUE THREAD

**Issue by solebravo** [IIC2233/Syllabus#78]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, para la instancia donde se quiere acceder a una partida guardada, quería utilizar paths para que el programa encontrase el la carpeta partidas y luego el archivo con el nombre del usuario, pero estoy un poco confundida sobre como crear un path relativo debido a lo que salía en el modulo de la semana 0 acerca de los problemas que se podían generar al abrirlo con otros sistemas operativos y, a partir de esto, tampoco sabia si se podía usar _os_ en la tarea.
Muchas gracias.

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by Lord-Kelsier** [comment]
Primero, la libreria `os` esta permitida como puedes ver en #21. 

Para los paths relativos siempre se considera el origen desde el archivo de ejecución, por ejemplo:
Tenemos los siguientes archivos:
```
Tarea
├── 📂clases
│   ├── juego.py
├── 📂partidas
│   ├── jugador1.txt
└── main.py
```
`juego.py` contiene:
![image](https://user-images.githubusercontent.com/69614275/186546431-82c3117f-1fc8-4bb2-8c20-c9a59c55a8f2.png)
y  `main.py` contiene:
![image](https://user-images.githubusercontent.com/69614275/186546527-6ff8781e-ce1b-48d1-8e53-7542bcd359c2.png)

Observa que para llegar desde `juego.py` hasta `jugador1.txt` hay que salir de la carpeta `clases`  y entrar a `partidas`.
Sin embargo, el path que esta en `juego.py` solo entra a `partidas` esto debido a que estamos ejecutando `main.py` y ese es el recorrido para ir desde `main.py` hasta `jugador1.txt`
