### ISSUE TITLE
Problema con los Path relativos

### ISSUE THREAD

**Issue by ClaudioSapelling** [IIC2233/syllabus#78]
Vi los otros Issues sobre este tema pero sigo sin poder solucionarlo
Cree un codigo.py en la misma carpeta en la que tengo los archivos (T00) pero al hacer el comando:
nombres_de_usuarios = os.path.join('usuarios.csv')
with open(nombres_de_usuarios,'rt') as excel_usuarios:

Me da el error:
Exception has occurred: FileNotFoundError
[Errno 2] No such file or directory: 'usuarios.csv'
  File "C:\Users\Sebastian\Desktop\progra\ClaudioSapelling-iic2233-2020-1\Tareas\T00\sheet2.py", line 3, in <module>
    with open(nombres_de_usuarios,'rt') as excel_usuarios:

**Comment by igbasly** [comment]
Hola @ClaudioSapelling 😄
En la issue #22 tratan varias posibles situaciones que pueden generar ese error, comprueba primero si estás dentro de alguna de ellas, de lo contrarío te pediría un poco más de información acerca de cómo estás corriendo el programa y que editor estás ocupado.

Saludos ✌️

**Comment by ClaudioSapelling** [comment]
Revisé el issue 22 pero no se como hacer correr el codigo desde la carpeta T00 
Estoy usando Visual Studio Code
![problema path](https://user-images.githubusercontent.com/62029178/77008450-f0640200-6944-11ea-8921-cf01a9e63782.png)

**Comment by igbasly** [comment]
@ClaudioSapelling, especificamente en este [comentario](https://github.com/IIC2233/syllabus/issues/22#issuecomment-599742141) de la issue #22, explica como correr desde la carpeta de la Tarea, por otro lado, cabe mencionar que siempre puedes correr tu programa directamente desde la consola, en la carpeta mencionada.

Espero haberte ayudado y no dudes en escribir cualquier otra duda 👍

**Comment by ClaudioSapelling** [comment]
Ya habia probado eso pero no me funciona aun abriendo mi archivo de esa manera.

**Comment by igbasly** [comment]
Según el *screenshot* que enviaste, VSCode tiene abierta la carpeta `progra`, por lo que tienes que abrir la carpeta `T00` directamente. 
Intenta con eso y me comentas .

**Comment by ClaudioSapelling** [comment]
Era eso!!! muchas gracias!! En el Issue anterior no habia entendido como abrir directamente la carpeta, ahora funciona perfe, gracias.
