### ISSUE TITLE
Duda sobre uso de git pull y perder archivos

### ISSUE THREAD

**Issue by EnzoMorata** [IIC2233/Syllabus#78]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola, tengo una duda sobre el funcionamiento de git pull, concretamente es cuando podría ocurrir que al ejecutar el comando pueda perder archivos o que se sobreescriban. Por ejemplo, si dentro del repositorio remoto tengo únicamente un archivo, pero en mi working directory tengo ese mismo archivo al día, pero además tengo otros archivos que no están en el repositorio; al hacer git pull esos archivos serían eliminados? o únicamente podrían verse modificados si existe una versión distinta del mismo archivo en el repositorio remoto?. Hasta el momento he trabajado con bastante cuidado y respaldando archivos para evitar cualquier problema.

**Comment by tqmbanados** [comment]
Hola @EnzoMorata! No te preocupes, `git pull` no borraría los cambios que has hecho en tu computador, así que en la mayoría de los casos puedes hacer `git pull` sin problemas. Si es que hubiera un problema (cosa que a mi nunca me ha pasado), git te informaría. Los problemas con mas comunes al usar `git push` cuando tu repositorio no esta actualizado con los cambios del repositorio remoto. 

Algo útil para entender de git, es que cada commit no guarda *la totalidad* de los archivos, **sólo guarda los cambios**. Entonces, al hacer `git pull`, no estás copiando una carpeta remota en tu carpeta personal, si no que sólo estas diciéndole a git "Los cambios que se han realizado en el repositorio remoto, aplícalos también acá". 

Espero que te sirva esta explicación!

**Comment by EnzoMorata** [comment]
Si, muchas gracias!
