### ISSUE TITLE
Problemas al subir tarea 0 a GitHub

### ISSUE THREAD

**Issue by PaulaGrune** [IIC2233/syllabus#78]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola!! Ayer comencé a trabajar en la tarea 0 y para guardar mi avance hice git add, commit y push. Hoydia después de avanzar intente hacerlo de nuevo pero me decía que no había cambios nuevos que subir. En ese momento revisé mi repositorio en GitHub y me di cuenta que ayer sí se subió mi archivo pero este esta vacío. Ahora he seguido avanzando en la tarea y he guardado los cambios en mi computador pero no sé por qué al hacer git status dice que no hay cambios, por lo que al hacer git add, commit y y push no se sube nada nuevo a mi repositorio de GitHub. 

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by RafaelEdwards** [comment]
Holaa, te recomiendo revisar si guardaste los cambios de tu archivo en VSC (asumiendo que estás trabajando ahí) correctamente. Para verificar esto, puedes chequear si el archivo en tu repositorio local también se encuentra vacío.

Saludos y espero haberte ayudado. :)

**Comment by PaulaGrune** [comment]
Ahora lo logré!! Muchas gracias por la ayuda :)
