### ISSUE TITLE
Regla 3 - Rellenado de tortugas.

### ISSUE THREAD

**Issue by TwoB-2B** [IIC2233/Syllabus#78]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/21)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/20)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Regla 3 - Rellenado de tortugas.

No entiendo mucho en que caso se incumpliría esta regla. Según el enunciado en ningún momento nos entregaran un tablero de la siguiente forma:

"2,2T,-,-,-"

Dado que solo puede ser int, T o -.

*** Entonces la regla 3 es solamente si por si acaso al intentar solucionar el tablero coloco una tortuga con una bomba? ***

**Comment by pedrozavalat** [comment]
Hola @TwoB-2B!,
En tu issue destacaste que marcaste el tercer elemento donde dice: "Revisé el compilado de dudas de la tarea y no encontré una issue similar a la mía ([click aquí para ir al compilado](https://github.com/IIC2233/syllabus/issues/21))." Sin embargo, en la issue #56 se respondió tu misma pregunta. 

* #56

Por favor, para las próximas issues que hagas, revisa el compilado y verifica que otra persona no hayan realizado una pregunta igual a la tuya. En el caso, que no encuentres ninguna respuesta que resuelva tu duda, realizas una nueva issue. Así evitamos tener preguntas duplicadas.  

Dejaremos esta issue cerrada para cualquier duda relacionada en
