### ISSUE TITLE
Error test_pieza_explosiva.py

### ISSUE THREAD

**Issue by gaspar-mr05** [IIC2233/Syllabus#78]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola. Tengo una duda con uno de los test de test_pieza_explosiva.py. Resulta que en el test llamado test_pieza_R_celda_derecha de la linea 107. retorna como respuesta correcta un True. Para este test se ocupa una pieza "R4" con posicion [1, 3], y se aplica verificar_alcance(1, 9). Según yo debería retornar False, ya que la pieza tiene alcance 4 y como máximo llega a la posición (1,7) horizontalmente, no llega a (1, 9), y el metodo justamente verifica eso, si es que la posicion es alcanzable o no, así que según yo debería retornar False (a no ser que yo haya entendido mal el enunciado).

**Comment by Mcroquevielle** [comment]
Hola, al igual que como se explicó en la issue #58, el método "verificar alcance" solo revisa si la posición es alcanzable por el tipo de bomba, sin importar el número. En este caso, comparten la misma columna, por lo que una bomba tipo "R" si puede alcanzar esa posición.

![image](https://github.com/IIC2233/Syllabus/assets/127401753/17bd758d-982c-4861-a1ff-36e435168f6d)
