### ISSUE TITLE
Duda con guardar puntajes en puntajes.txt

### ISSUE THREAD

**Issue by Juan379** [IIC2233/syllabus#78]
Hola!
Respecto a los puntajes que se deben guardar y que **todos los puntajes deben ser guardados** en el archivo puntajes.txt tengo la siguiente duda:

- Deben ser guardados todos los puntajes de todas las partidas independiente de si se guardo la partida o no? Es decir: si perdí, gane, sali con guardar o sali sin guardar se deberían guardar los puntajes obtenidos en el archivo puntajes.txt independiente del caso?

**Comment by gatochico** [comment]
Hola! 

La única condición para que una partida se guarde es que esta **se haya acabado**, ya sea por que se **perdió o ganó la partida**. Cualquier otro caso (como salir con o sin guardar) no debería tener su puntaje guardado en `puntajes.txt`

Espero haber aclarado tu duda!
