### ISSUE TITLE
Derrotar a Civilizacion y traspaso de ayudantes

### ISSUE THREAD

**Issue by jalliende** [IIC2233/syllabus#78]
Que pasa cuando una civilización derrota a otra y al "sortear" la cantidad de ayudantes a traspasar, con esa cantidad la ciudad vencedora supera el limite de población. Se puede superar el limite o sorteamos la cantidad dentro de los margenes para que no se supere el limite.

**Comment by jeschuwirth** [comment]
Saludos, como eso no sale explicito en el enunciado queda a criterio del alumno (mientras se deje explicito en el readme no deberían tener problemas).

Dicho esto, por comodidad te recomendaría no superar el límite de población.

Suerte en la Tarea!
