### ISSUE TITLE
Respecto a los paths

### ISSUE THREAD

**Issue by Daniel-Guajardo** [IIC2233/Syllabus#78]
Respecto a esta parte del planteamiento

![image](https://user-images.githubusercontent.com/101299560/161403696-b1a506f9-04a7-4477-9995-d3980ff93cb3.png)

No me queda claro si debo obligatoriamente incluir todos los _paths_ en el archivo de parámetros o no.

**Comment by jtvaldivia** [comment]
Hola, 
Como dice en el enunciado en parametros.py debes dejar cualquier valor constante. Por esta razon, los path que son variables constantes deben tambien ir escritos en el archivo parametros.py para ser ocupados en el codigo.
