### ISSUE TITLE
Error al hacer git push

### ISSUE THREAD

**Issue by MagyarSplit** [IIC2233/syllabus#78]
Hola, al momento de tratar de aplicar el comand **git push** me tira el seguiente error:
**remote: Permission to IIC2233/syllabus.git denied to MagyarSplit.
fatal: unable to access 'https://github.com/IIC2233/syllabus.git/': The requested URL returned error: 403**

Creo que se puedo haber generado porque use git pull al syllabus directo a mi carpeta de la actividad, cuando quería obtener los archivos de la actividad, y no se debia hacer asi.

Intente borrando el syllabus y reintando pero no funciono.

Gracias.

**Comment by tocococa** [comment]
Hola @MagyarSplit ! Eso pasa porque estás intentando hacer `git push` en la carpeta del _syllabus_ hacia el repositorio del curso, cuando en realidad para subir tu actividad lo deberías estar haciendo desde y hacia tu repositorio privado. 
Lo que tienes que hacer es copiar los contenidos de la actividad a tu repo personal y de ahí hacer `git add`, `commit` y `push`.

**Comment by MagyarSplit** [comment]
Lo logre, muchas gracias por tu ayuda. Saludos
