### ISSUE TITLE
Git error 'everything is up to date with origin\master'

### ISSUE THREAD

**Issue by yerkko** [IIC2233/Syllabus#78]
Al intentar hacer backups de mi tarea git me entrega el siguiente mensaje. 
```
C:\*\T01>git add *
C:\*>git commit -m '*'
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean

```
El repositorio remoto no está actualizado, le faltan archivos y no tiene las últimas modificaciones por lo cual no podría estar up-to-date. En stackoverflow se recomienda hacer git pull pero no me soluciona el problema.

**Comment by iqacevedo** [comment]
Hola ! 

Si intentas con `git add -all`se te soluciona el problema ? 

Saludos !

**Comment by andresfdezc** [comment]
Esto no es un error. Git te está avisando que no hay ninguna diferencia entre el nuevo commit que estás haciendo y el anterior.

Puedes hacer `git status` para ver qué cambios podrías agregar a tu staging area.

**Comment by yerkko** [comment]
```
`C:\*\T01>git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean`
```
Entiendo lo que comentas, pero a lo que voy es que si entro con el navegador a la carpeta en el remoto, los cambios no se han realizado, hay un archivo que no aparece, etc.

**Comment by andresfdezc** [comment]
Recuerda que no basta con hacer commit para que los archivos se suban. Debes hacer `git push` para que el repositorio remoto (en tu navegador) reciba el último commit.

**Comment by andresfdezc** [comment]
En particular, ¿qué tipo de archivo no se sube? Puede que sea alguno de los que git ignora.

**Comment by fringlesinthestreet** [comment]
Si agregas una carpeta vacía debes subirla con un archivo con nombre `.keep`. Así reconoce git reconoce la carpeta.

**Comment by yerkko** [comment]
No puedo realizar `git push` debido a que me tira el mismo mensaje de que no hay cambios, son archivos .py con código nuevo, no carpetas vacías ni nada. Intenté forzarlo con `git push -f ` pero tampoco funciona.

```
C:\*\T01>git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
```

**Comment by andresfdezc** [comment]
¿Puedes ver con `git log` el nombre del último commit que hiciste y compararlo con el último commit que te aparezca en tu repositorio remoto para tener algo más de contexto?

**Comment by yerkko** [comment]
De los más recientes, me aparece este triplicado.

```
:...skipping...
commit e6fa4535d5fc466698742b71339ca0fb7a695789 (HEAD -> master, origin/master,
origin/HEAD)
Author: YERKO CHAVEZ <yachavez@uc.cl>
Date:   Wed Aug 16 01:05:05 2017 -0400

    uh?

:...skipping...
commit e6fa4535d5fc466698742b71339ca0fb7a695789 (HEAD -> master, origin/master,
origin/HEAD)
Author: YERKO CHAVEZ <yachavez@uc.cl>
Date:   Wed Aug 16 01:05:05 2017 -0400

    uh?

:...skipping...
commit e6fa4535d5fc466698742b71339ca0fb7a695789 (HEAD -> master, origin/master,
origin/HEAD)
Author: YERKO CHAVEZ <yachavez@uc.cl>
Date:   Wed Aug 16 01:05:05 2017 -0400

    uh?

```

En la página me aparece esto

`1 parent c8c4245                commit e6fa4535d5fc466698742b71339ca0fb7a695789 @yerkko yerkko committed 21 hours ago`


Aún siendo este el último commit, ya había tenido problemas para actualizar los archivos y creo que tuve que hacer `git reset`

**Comment by andresfdezc** [comment]
Bueno, todo lo que indica git es que no tienes absolutamente nada nuevo dentro de la carpeta local. Te pido que por favor revises que los archivos que quieres subir estén efectivamente dentro de tu repositorio local, porque sería muy raro que git los esté ignorando completamente.

**Comment by andresfdezc** [comment]
En el peor de los casos, te sugiero que lo revises con un ayudante al inicio de la actividad de mañana, después de haber corroborado lo anterior.

**Comment by fringlesinthestreet** [comment]
@yerkoo Lograste resolverlo? Hoy un alumno le pasaba lo mismo y era porque estaba trabajando en otro directorio (por lo que en su repositorio no habían cambios).

**Comment by yerkko** [comment]
@fringlesinthestreet 

lol...

Sí, hice `git reset --hard` y se pudo arreglar
