### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by cjmunoz4** [IIC2233/Syllabus#780]
Hola! Tengo este error cada vez que intento importar requests, sin embargo, cuando lo intento instalar con pip me sale "Requirement already satisfied: requests in...." y no sé qué hacer para que no me tire ese error.

**Comment by egromero** [comment]
Hola, probaste con `pip3` en vez de `pip`?

**Comment by cjmunoz4** [comment]
Ya lo arreglé! Por alguna razón la consola no me detectaba que tenía instalado pip3, así que me fui a la carpeta de python desde ahí instalé requests, pero esta vez no me decía que ya estaba instalado y ahora funciona. Gracias de todos modos!
