### ISSUE TITLE
Backend como atributo de una clase de Frontend ¿Mala práctica?

### ISSUE THREAD

**Issue by Jamesmoreno21** [IIC2233/syllabus#780]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola! Quería saber si es una mala práctica o va en contra de lo pedido en acoplamiento o cohesión en la tarea que defina una clase de backend para distintos objetos y luego estas sean atributos de una clase de frontend para el mismo objeto, considerando que hay señales que van entre ellos.
Un saludo y gracias de antemano!

**Comment by jaimecoloma** [comment]
Hola @Jamesmoreno21 !! Relacionar ambos de esa forma iría en contra de lo que se espera, te dejo a continuación un poco la idea de  lo que se entiende alta cohesión y bajo acomplamiento sobre front-end y back-end.
Cohesión: Cada una de las componentes del software debe realizar **solo las tareas para las cuales fue creada**, delegando otras tareas a otras componentes según corresponda. Por ejemplo, si tengo una clase ```SimulaciónDeParque```, un diseño altamente cohesionado incluiría métodos como ```iniciar_simulación()``` o ```detener_simulación()```, pero no métodos como ```limpiar_atracción()``` o ```ingresar_clientes_a_restaurant()```, ya que la clase ```SimulaciónDeParque``` fue diseñada para administrar la simulación y no para hacerse cargo de métodos que deberían ser ejecutados (delegados a) otras clases de la simulación.
Acoplamiento: Cuando la modificación de una componente implica que es necesario modificar otra componente para que la implementación del cambio sea correcta y completa. Por ejemplo, si al modificar los atributos de una clase A, también se deben modificar los atributos de otra clase B, se dice que hay alto acoplamiento entre las clases A y B. Un **buen diseño intenta reducir el acoplamiento entre clases.**
En tu caso, al intentar juntar ambas clases con una que posea de atributo a la otra estás fallando con el bajo acomplamiento, por lo que te recomendaría lo separes. Como recomendación, para cumplir facilmente con este requisito, deberías preocuparte de contectarlos exclusivamente con señales!
Si te quedó una duda cuentame, éxito con la tarea!
