### ISSUE TITLE
Numero inicial de Chefs

### ISSUE THREAD

**Issue by CataSudo** [IIC2233/syllabus#780]
Hola! Siempre se parte con sólo un chef, o pueden haber varios?

**Comment by bvasquezm** [comment]
Hola @CataSudo!

Asume que siempre comenzarás con un solo chef. Los demás deberás ir comprándolos a medida que avanza el juego. Saludos.

**Comment by Jairuru** [comment]
Hola, no se debería partir con CHEFS_INICIALES?

**Comment by lily416** [comment]
Hola @Jairuru,

Sí, lo correcto sería que la cantidad de chef iniciales dependa de un parámetro, por lo que si se llegara a cambiar el valor del parámetro, entones se debería ver reflejado al reiniciarse la partida.

Saludos y éxito en la tarea 👋🧇
