### ISSUE TITLE
Importar modulo desde otro directorio

### ISSUE THREAD

**Issue by eitandv** [IIC2233/Syllabus#780]
Hola!
Mi duda es básicamente si existe una manera de importar módulos de un directorio distinto al cwd. Por ejemplo, quiero importar un modulo desde el directorio server, desde un modulo en client, siguiendo la estructura del enunciado. 

Gracias de antemano!

**Comment by leolivares** [comment]
Hola! @eitandv 
En esta tarea, importar un modulo del server, desde el cliente (o viceversa), estaría mal. Principalmente debido a que en un caso normal, el cliente y el server no se encuentran juntos. Toda la interacción entre cliente y server ocurre mediante network.

**Comment by eitandv** [comment]
Ah, claro. Perdón por la pregunta estúpida! 
Gracias!
