### ISSUE TITLE
Ejecutar desde la terminal integrada en VSC

### ISSUE THREAD

**Issue by BelenSilva1204** [IIC2233/syllabus#781]
Holaa, no sé que paso pero creo que tengo la ruta de la terminal incorrecta como para poder ejecutar desde VSC una ventana creada en Qtdesigner, de todas maneras he intentado ejecutar desde la terminal directamente y tampoco puedo, no sé que estaré haciendo mal o como debo cambiar la ruta en VSC :(
![SmartSelectImage_2020-05-20-19-18-25](https://user-images.githubusercontent.com/62078553/82506768-4c264500-9ac6-11ea-8f8c-edd10b80a0bc.png)

**Comment by lucasvsj** [comment]
Hola @BelenSilva1204 
Por lo que puedo ver estas trabajando en el syllabus, lo cual no es recomendado.
Si éste no es la ruta en que tienes los archivos que quieres probar, puedes dirigirte a la carpeta que quieras de la siguiente forma (lamentablemente mi VSCode esta en ingles, asi que quizás mis traducciones no sean del todo correctas):

- Val a **Archivo** (**File**)
- Luego haces click en **Abrir Directorio** (**Open Folder**) (si no me equivoco en Windows el shortcut por defecto es `Ctrl+K+O` debes apretar `Ctrl+K` y mientras los tienes apretados ahí apretar la `O`)
- Eliges la carpeta en la cual quieres trabajar y luego presionas **Ok**

Al hacer esto, tu terminal integrada estará ubicada en la carpeta que quieres trabajar.
Ojalá esto te sirva

**Comment by BelenSilva1204** [comment]
Ya cambie la carpeta de trabajo, gracias! pero seguí tus pasos y aún no pasa nada con la terminal
![SmartSelectImage_2020-05-20-19-40-48](https://user-images.githubusercontent.com/62078553/82508043-7b8a8100-9ac9-11ea-8b05-5086bf7921fa.png)

**Comment by lucasvsj** [comment]
Cierra esa terminal (aprieta el símbolo del basurero) y luego:

-  **View**
- **Terminal** (si no me equivoco en Windows el shortcut es `Ctrl+ñ`

Si ésto no llegase a funcionar (lo cual encontraría raro) puedes moverte con el comando `cd` en la terminal integrada de VSCode.

**Comment by BelenSilva1204** [comment]
He intentado también con eso y tampoco resulta :(

**Comment by lucasvsj** [comment]
Trata con lo siguiente:
**File** -> **Preferences** -> **Settings**
En la barra de busqueda pega esto:
`terminal.integrated.cwd`
Luego aparecera algo así:
![image](https://user-images.githubusercontent.com/37182459/82510370-57826c00-9ad8-11ea-8628-137b4e823e4b.png)
En la barra escribe:
`${fileDirname}`
Elimina la terminal y reinicia VSCode, luego abre una nueva terminal.

**Comment by BelenSilva1204** [comment]
También he estado buscando y la verdad es que ya no se muy bien que hacer porque ni en la terminal externa funciona, gracias por seguir averiguando!
![SmartSelectImage_2020-05-20-20-39-52](https://user-images.githubusercontent.com/62078553/82511007-b85a7600-9ad1-11ea-9f27-7fcfd2f4383b.png)

![SmartSelectImage_2020-05-20-20-35-52](https://user-images.githubusercontent.com/62078553/82510805-1e92c900-9ad1-11ea-960d-0c58d377ed26.png)

**Comment by lucasvsj** [comment]
Puedes mostrarme una foto de archivo que estas tratando de ejecutar por favor

**Comment by BelenSilva1204** [comment]
![SmartSelectImage_2020-05-20-20-47-51](https://user-images.githubusercontent.com/62078553/82511381-c8268a00-9ad2-11ea-930e-845963d021e7.png)

**Comment by lucasvsj** [comment]
En el `self.setupUi()` debe ser `self.setupUi(self)`

**Comment by BelenSilva1204** [comment]
Me sale lo mismo que en las fotos de arriba, permiso denegado o simplemente no ejecuta nada :(

**Comment by lucasvsj** [comment]
Puedes pushear tu código por favor

**Comment by BelenSilva1204** [comment]
Listo

**Comment by lucasvsj** [comment]
En el `__init__` te faltan los ultimos `__`

**Comment by BelenSilva1204** [comment]
Lo revisé tantas veces y pase por alto eso, ahora funciona, muchísimas gracias enserio!
