### ISSUE TITLE
ImportError: cannot import name 'discovery'

### ISSUE THREAD

**Issue by BeaGaete** [IIC2233/Syllabus#781]
Hola, tengo este error al tratar de correr el ejemplo de google spreadsheets. En stackover flow me dice que haga esto: sudo pip install --upgrade google-api-python-client
pero me sale esto en la terminal: 
The directory '/Users/Beatriz/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
También he instalado y desinstalado apiclient varias veces, pero no me resulta. 
No he tenido problemas con las otras APis, pero en esta hasta ahora no he podido hacer nada, hay otra manera de acceder a la API de spreadsheet?

**Comment by ifcarrera** [comment]
Con pip3 tampoco te funciona ?

**Comment by BeaGaete** [comment]
ya lo solucioné; gracias! :)
