### ISSUE TITLE
Terminar un thread 

### ISSUE THREAD

**Issue by denisseleiva** [IIC2233/syllabus#781]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola! Quería saber si existe una forma segura de terminar un thread. ¿Se puede usar terminate()? Si no se puede usar, ¿Hay otra forma para poder terminar el thread?

Gracias!

**Comment by kadroguett** [comment]
Hola @denisseleiva, no existe una manera segura de utilizar `terminate()`, es por esto que se considera una mala práctica y es siempre recomendable dejar que el `thread` termine por si mismo. Esto se debe a que el `thread` está utilizando recursos que deben ser cerrados apropiadamente. 
Para terminar apropiadamente un thread existen diferentes opciones, una de ellas es la de agregar una condición que interrumpa el loop de este, como se puede ver en el siguiente ejemplo:

```
import threading
import time

stop_threads = False

def run():

    while True:
        print('thread running')
        if stop_threads:
            break

t1 = threading.Thread(target=run)
t1.start()
time.sleep(1)
stop_threads = True
t1.join()
print('thread killed')

# Código basado en ejemplo mostrado en el siguiente link:
# https://www.geeksforgeeks.org/python-different-ways-to-kill-a-thread/ 
```

Si quieres profundizar más en esto te recomiendo leer esta pregunta en stackoverflow: 
https://stackoverflow.com/questions/323972/is-there-any-way-to-kill-a-thread

**Comment by denisseleiva** [comment]
Bacan, gracias!
