### ISSUE TITLE
Abrir nueva ventana una vez corriendo el Client

### ISSUE THREAD

**Issue by eitandv** [IIC2233/Syllabus#781]
Hola!
Tengo un problema. Al abrir una ventana de edición corriendo el cliente, esta se congela y no me lanza ningún error, solo no responde y mi task manager se pone nervioso. No es error de la ventana ya que si la corro por separado todo funciona bien. ¿Que puede estar fallando?
Gracias!

**Comment by Arcoirisky** [comment]
Quizás está ejecutando algo por detrás después de abrir la ventana. Si te quedas esperando pacientemente ¿Continúa pegada?

**Comment by Arcoirisky** [comment]
El Thread que dices es sólo el que escucha entre cliente-server ¿no?

Se me ocurre que deba ser la forma que modelas el editado de una canción. Ya que debes leer el archivo midi, mostrarlo en la interfaz y quedar atento ante cualquier cambio de la canción. Es muy simple lo que te diré pero prueba haciendo Print en cada paso antes de abra la ventana edición y después. En alguna parte no debes de estar entrando y es una forma sencilla de saber qué está bloqueado.

Es lo que te puedo decir sin saber cómo estás modelando esa parte de tu tarea o:

**Comment by eitandv** [comment]
Si, es ese thread. Ya trate el método de los prints y entra a todo y sale de todo. Mi editor de canción recibe un objeto 'Canción' desde el Server via pickle y en base a eso se abre con los datos correspondientes. No se si con eso quede mas claro el error.

**Comment by tomvalenz** [comment]
A mí me pasa lo mismo. Al  abrir la ventana de edición se congela sin lanzar ningún error, pero puedo seguir haciendo cosas en la otra ventana. También probé con prints pero todo aparece y muestra que funciona, no entiendo qué puede ser.

**Comment by eitandv** [comment]
Al final reestructure mi código para que las interacciones sean solo vía señales pyqt. Ademas implemente un par de trys y excepts en los threads y algunos lock por ahi. Ahora todo funciona relativamente bien. No se si ayude, pero por si acaso jaja.
