### ISSUE TITLE
Error al abrir google sheet

### ISSUE THREAD

**Issue by SarahEverke** [IIC2233/Syllabus#782]
Cuando corro el ejemplo de https://developers.google.com/sheets/quickstart/python#troubleshooting , no tengo problema.
Sin embargo, cuando a ese ejemplo le cambio spreadsheetId por un id de un spreadsheet mío, python me muestra el siguiente error 
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://sheets.googleapis.com/v4/spreadsheets/1isxmCFsa55nOecRufatS-H-dhiobfpNCzJpj7Y0Y4e4/values/Class%20Data%21A2%3AE?alt=json returned "Unable to parse range: Class Data!A2:E">

¿Que puedo hacer?

**Comment by ifcarrera** [comment]
Hola! 
Ese error te aparece porque estás intentando leer las casillas del sheet anterior. Debes cambiar todos esos parámetros para que lea TU sheet y no el del ejemplo (no debes cambiar solo el id).
Saludos

**Comment by SarahEverke** [comment]
Gracias :D

**Comment by BeaGaete** [comment]
Hola! Me hice mi propia spreadsheet y no tengo problema para leerla, pero tengo el siguiente error cuando trato de escribir en ella: 
googleapiclient.errors.HttpError: <HttpError 403 when requesting... returned "Request had insufficient authentication scores
Tengo puesto el scope 'https://www.googleapis.com/auth/spreadsheets' que se supone que es para leer y escribir. Que estaré haciendo mal?

**Comment by ifcarrera** [comment]
Se me ocurre que tu scope está mal, según yo debería ser el link a tu sheet. 
Por otra parte, si te retorna el error 403 significa que estás autentificando mal, puedes ese error indica `Acceso prohibido`. Intenta cambiar el link y me cuentas como te va. 
Saludos

**Comment by BeaGaete** [comment]
No, no es el link a mi sheet, me sigue tirando el mismo error. En la documentación de la API dice que se debe poner como scopes alguna de estas:

SCOPES = 'https://www.googleapis.com/auth/spreadsheets'
SCOPES = 'https://www.googleapis.com/auth/drive.file'
SCOPES = 'https://www.googleapis.com/auth/drive'

Pero las tres me tiran el error 403

**Comment by ifcarrera** [comment]
Hola!
En SCOPE debe ir la primera que mencionas: [https://www.googleapis.com/auth/spreadsheets](https://www.googleapis.com/auth/spreadsheets). 

Te tira el error 403 porque no le has dado permiso para que escriba, solo para que lea.

Si es que primero hiciste correr el _Quickstart_ de la API, se te creó un archivo en el directorio `~/.credentials/sheets.googleapis.com-python-quickstart.json`. Bien, ese archivo `json` debes borrarlo, pues se te creó con el scope `https://www.googleapis.com/auth/spreadsheets.readonly`
lo que significa que estabas dando permisos solo para leer la sheet, no para escribir. Borra ese archivo y vuelve a ejecutar tu código con el nuevo scope y te debería funcionar, pues ahora sí le das los permisos necesarios. 

Saludos 😄

**Comment by BeaGaete** [comment]
OHHH  muchas gracias, me escribió :)

**Comment by JPSF** [comment]
Hola! Llevo horas tratando de hacer funcionar google sheets con un sheet propio y no lo consigo. Estoy usando el código de ejemplo para esto. Cambié el scope por "https://www.googleapis.com/auth/spreadsheets" cómo dijeron en esta issue. Puse el id de cliente en APPLICATION_NAME, hice CLIENT_SECRET_FILE = 'client_secret.json'. Cambié el id del sheet por el que corresponde. @ifcarrera cuando dices " Debes cambiar todos esos parámetros para que lea TU sheet y no el del ejemplo" ¿Qué otros parámetros habría que cambiar? ¿ Hay algo que esté haciendo mal? Gracias de antemano

**Comment by ifcarrera** [comment]
¿Qué error te sale? 
¿Hiciste lo que mencioné sobre borrar el archivo creado en el directorio `.credentials`?. 
Respecto a los parámetros, debes cambiar cosas como el scope, el id de la sheet, las casillas que vas a leer, si es que vas a escribir debes cambiar los métodos para que lo hagan, etc. 
Cuéntame como te va. Si te aparece un error específico te recomiendo abrir otra issue para que sea más fácil de encontrar para tus compañeres. 

Saludos :D

**Comment by JPSF** [comment]
Lo acabo de solucionar! Lo que hice fue cambiar rangeName = 'Class Data!A2:E' simplemente por rangeName=A2:E, aunque no tengo idea de por qué esto funciona
Muchas gracias de todas formas :)

**Comment by B-Dominguez** [comment]
@JPSF Hi Stranger. Es porque lo que está antes del ! es el nombre del _sheet_ dentro del _spreadsheet_ (sirve para cuando tienes varias hojas). Al borrarlo estay entrando simplemente a la primera hoja (creo jajaj). Pero fíjate que si poni el nombre de tu hoja también funciona (debe ser 'Hoja 1'

**Comment by vamarambio** [comment]
Hola, yo cuando trato de ejecutar el codigo de quickstart me sale este error:

![image](https://user-images.githubusercontent.com/26117424/33226932-3c04a2c2-d177-11e7-824e-8183ae6eddbf.png)

No se si tiene algo que ver con el codigo en si o algun error de algun modulo. Gracias de antemano.

**Comment by aurodriguez** [comment]
Hola. He tratado con lo que dices tres veces y no me deja escribir. Me imagino que el error es el mismo, pero he probado harto rato y nada.
<img width="1218" alt="screen shot 2017-11-27 at 23 18 39" src="https://user-images.githubusercontent.com/28511788/33299254-8e3f2df6-d3c9-11e7-84a0-a6e4ff8c8993.png">
