### ISSUE TITLE
Problemas al cargar imagenes

### ISSUE THREAD

**Issue by LeoMo-27** [IIC2233/syllabus#782]
hola!
Mi problema es al cargar los sprites de las mesas o cosas asi sobre mi main_window, ya que al "Crear" los labels no me aparecen en ninguna parte, al final es como si no los hubiera creados, el tema es que les pongo show, y les pongo raise, para que no queden abajo, no se si me explico bien, pero creo que mi forma de crear los labels y luego moestrarlos esta mal, el tema esque no se como arreglarlo.

Gracias!

**Comment by moquezada** [comment]
Hola @LeoMo-27 :)

¿Te aseguraste de entregarle un `parent` a cada label? 👀 Quizás por ahí podría estar el error dado que ya estás haciendo el `show` y el `raise` 🤔
