### ISSUE TITLE
Envío de mensajes cliente-servidor

### ISSUE THREAD

**Issue by Clemente24** [IIC2233/Syllabus#782]
En el enunciado dice: 

> Para cada mensaje a enviar, primero es necesario mandar otro mensaje previo que indique el tamaño
del mensaje que se enviará

Puedo agregarle el largo del mensaje, en bytes, al mismo mensaje que voy a enviar y mandarlos juntos? O es obligatorio que sean mensajes separados?

Gracias

**Comment by ptflores1** [comment]
Hola !
No puedes enviar todo junto, debes hacerlo como se indica en el enunciado.
Saludos !

**Comment by santilaguna** [comment]
@Clemente24 igual no te compliques es simplemente enviar dos mensajes seguidos (es lo mismo de hecho no entiendo la necesidad de separarlo, pero bueno)
