### ISSUE TITLE
Problema al abrir link de Twitter

### ISSUE THREAD

**Issue by aurodriguez** [IIC2233/Syllabus#783]
Hola, 

He tratado varias veces de abrir la documentación de twitter que sale en el enunciado, se demora en cargar y después me sale esto:
<img width="561" alt="screen shot 2017-11-22 at 17 10 12" src="https://user-images.githubusercontent.com/28511788/33147831-281c069a-cfa8-11e7-808e-d635486a4704.png">

No se si es problema de mi computador o algo de la pagina, pero encontré este link: https://developer.twitter.com y no me queda que API usar ya que aparecen DirectMessage API, SearchAPI, AdsAPI, EngagementAPI, etc. 

Gracias!

**Comment by ifcarrera** [comment]
Efectivamente el link del enunciado está malo, gracias por avisar!
El correcto es el que mencionas: [éste])](https://developer.twitter.com/). Cuando bajas dice "Go to Docs". Ahí puedes encontrar la documentación. Saludos
