### ISSUE TITLE
Importación de módulos y múltiples carpetas.  

### ISSUE THREAD

**Issue by benjavicente** [IIC2233/syllabus#783]
Tengo un problema al usar múltiples carpetas para ordenar la tarea.

No puedo usar funciones y clases de de un archivo `.py` en `main.py` ya que no encuentra un módulo donde defino algunos parámetros. Funciona perfecto si uso las funciones y clases dentro de el archivo donde las defino (utilizando `__name__ == '__main__'`).

---
Una versión muy simplificada de lo que me pasa es:
```
proyecto
├── main.py
├── carpeta
│   ├── programa.py
│   ├── parametros.py
```
**`main.py`**
```py
from carpeta import programa
programa.foo()
```
**`programa.py`**
```py
from parametros import x
def foo():
    print(x)
if __name__ == "__main__":
    print(x)
```
**`parametros.py`**
```py
x = 'hola'
```
Al ejecutar `programa.py`: `hola`
Al ejecutar `main.py`: `ModuleNotFoundError: No module named 'parametros'`

---

Encontré que cambiando `from parametros import x` a `from .parametros import x` soluciona el problema para `main.py`, pero hace que `programa.py` no funcione.
**¿Cual es la manera correcta de importar módulos cuando se trabaja en múltiples carpetas/directorios?**

**Comment by jbulness** [comment]
Hola @benjavicente,

En la issue "Importar módulos en distintas carpetas" (#737) se responde una duda similar de manera muy detallada. Espero que te sirva.
