### ISSUE TITLE
Duda crear metodos en qtdesigner

### ISSUE THREAD

**Issue by totoiii** [IIC2233/syllabus#783]
Creé los Label de los puffles y los pinguinos en qt designer y resulta que invesigando supe que para poder arrastrarlos necesito crearles un metodo mouseMoveEvent() pero no sé como crearlo en qtdesigner,y tengo que crearlo ahi ya que creo que no se puede crear metodo de cosas que ya creaste en el designer. LLevo harto tiempo buscando :( aiura

**Comment by JadrinaDA** [comment]
Hola! El mouseMoveEvent() no tiene que ser propio del label sino que de la clase de la ventana en que se encuentra el label por lo que no tienes que agregarle un método a este. Debes reescribir este método en tu clase ventana_algo para poder realizar en drag-n-drop. Espero haber aclarado tu duda!

**Comment by totoiii** [comment]
intenté buscar info acerca del mouseMoveEvent() para QWidgets pero no la encuentro y lo que encuentro son otras formas que me complican mucho mi codigo D: podrías enviarme un link para orientarme o algo por el estilo? :(

**Comment by JadrinaDA** [comment]
Claro, aquí está la documentación para QWidget con que contiene el metodo mouseMoveEvent(), el link redirecciona altiro a este último. 
 https://doc.qt.io/qt-5/qwidget.html#mouseMoveEvent
