### ISSUE TITLE
Pausa; reinicia el tiempo a la siguiente flecha?

### ISSUE THREAD

**Issue by Zenos-Paradox** [IIC2233/syllabus#784]
* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Si, por ejemplo, faltaban 0.3 segundos para que se generara la siguiente ronda de pasos al apretar el botón `Pausa`, al des-pausar, debemos respetar eso o puede salir en 1 sec? (en el caso de la dificultad de aficionado).

**Comment by manearaya** [comment]
Hola @Zenos-Paradox!

Como dice en el enunciado (sección 5.4), al des-pausar el juego se tiene que reanudar tal cual como fue pausado. Esto implica que se debe respetar el tiempo restante que había antes de pausar.

Éxito con la tarea!

**Comment by Zenos-Paradox** [comment]
ok, gracias.

**Comment by Zenos-Paradox** [comment]
pero espera, hay alguna forma de que un Qthread se pause a la mitad de un time.sleep()? pensé que necesitaría completar la función

**Comment by manearaya** [comment]
Hola! Perdón la demora, no había visto el comentario. 

Según lo que encontré, no hay manera de pausar un time.sleep(). Lo que sí te puede servir es usar una alternativa como QTimer, ya que se puede pausar y reanudar de buena manera.

**Comment by JoMarchant** [comment]
Respecto a usar un QTimer, lo estuve probando pero el método stop que trae por defecto, reinicia el intervalo que uno le asigna.
Así que si llevaba 0.5 segundos y se iba a activar justo al 1, si uso stop parte desde 0 hasta llegar a 1 otra vez, esperando un total de 1.5 s en vez de los 0.5 que faltaban. ¿Qué alternativa hay?

**Comment by manearaya** [comment]
Hola @JoMarchant!

Lo que te podría servir es el método remainingTime() de QTimer(), que retorna el tiempo restante hasta el próximo timeout. Luego puedes usar esta información para que el timer se reanude con el tiempo indicado.
