### ISSUE TITLE
Problema al ejecutar código en Atom

### ISSUE THREAD

**Issue by sscontreras** [IIC2233/syllabus#784]
Hola buenas, hoy intenté instalar Atom para empezar a utilizarlo, seguí al pie de la letra las instrucciones, pero me apareció un error que no me permite ejecutar los archivos.
![image](https://user-images.githubusercontent.com/62116064/82507403-230ab200-9ad0-11ea-8627-e781b9586fda.png)
Y según estuve investigando era por que no estaba en el path, pero lo tuve que agregar anteriormente para poder ejecutar pip en el cmd, 
![image](https://user-images.githubusercontent.com/62116064/82507487-6402c680-9ad0-11ea-99f0-00f1f2cc3089.png)
Todos estos problemas me vienen creo, debido a que modifiqué la ruta de instalación de python a mi disco duro secundario, me gustaría saber que puedo hacer para solucionarlo.

**Comment by Drpinto1** [comment]
¡Hola!

Tal como dices es probable que el error se esté produciendo por la ruta que tiene python en tu computador. Hace bastante tiempo que no uso Atom, pero podemos intentar encontrar y arreglar el error.
¿Estás ejecutando el código desde Atom? ¿Qué comando estás usando para hacerlo?
