### ISSUE TITLE
usar properties para el getter de un diccionario

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#784]
Me gustaría saber como implementar un 'diccionario falso' utilizando el getter de properties.

Por ejemplo, asumiendo un caso hipotético donde tengo las variables A y B, donde la llave del diccionario "C" sería la suma de estas y "D" sería A - B de un a forma dinámica. (Quizás en este ejemplo se podría implementar de mejor manera, pero es la idea base de lo que quiero hacer)

Ejemplo
```python
A = 4
B = 3

__dict_falso = dict()
...


print(dict_falso["C"])
print(dict_falso["D"])
```
```css
7
1
```

**Comment by Christian-Klempau** [comment]
Hola @fernandosmither!
Primero, quiero decirte que sí es posible hacer lo que tú quieres y más adelante te lo mostraré.
Eso sí, respecto a la modelación, no creo que sea muy correcto 😮 Si quieres lograr algo de este estilo, mi recomendación personal es lo siguiente: 
- Puedes utilizar una clase (o namedtuple) que haga lo que tú quieres, es decir que guarde dichas variables, estas sean modificables, y luego tengas otro atributo (C) que mediante un setter y getter, modifique dinámicamente su valor utilizando las otras dos (A,B) como referencia.
- Puedes usar un diccionario común, pero cuando quieras utilizarlo, lo pases a través de una función que recalcule las llaves. Análogamente, podrías utilizar una clase "maestra" que ya tengas en tu programa, y que el atributo diccionario tenga un getter y setter.

Ahora, ya que te intriga la respuesta ;) puedes hacer lo siguiente, a modo de demostración, ojo que no te lo recomiendo como modelación pero queda a tu criterio:

Puedes lograr lo que tú dices si creas una clase personalizada, que herede de `dict`:

```python
class DictDinamicoFalso(dict):
    def __init__(self, A, B):
        super().__init__()
        self.A = A
        self.B = B

    def __getitem__(self, key):
        if(key == "C"):
            return self.A + self.B
        elif(key not in self.keys()):
            raise KeyError
        else:
            return self[key]
```

```python
A = 5
B = 3
dict_falso = DictFalso(A, B)
print(dict_falso["C"])
```

```
output: 8
```
(puedes hacer algo análogo para otras keys, y también para el método `__setitem__`)
Ahora, un detalle: al constructor de la clase, se le pasan los **valores** de los `int` A y B, no las referencias. Es decir, si cambias, fuera del contexto de la clase sus valores, no se actualizará en el diccionario (a menos que sea una variable global, pero claramente no es recomendable). Para esto debes cambiar los valores de A y B **dentro** de la instancia. La única manera de _bypassearlo_ sería entregarle una lista u otro diccionario, que guarde las referencias a las variables, aunque nuevamente, no considero esto una solución muy ideal. 
La última manera que se me ocurre, es con una clase que almacene el diccionario como atributo, y dicho atributo se modifique en el `getter`:

```python
class DictDinamico:
    def __init__(self):
        self._dicc = {"a": 1, "b": 2, "C": 0}
        self.A = 5
        self.B = 3

    @property
    def dicc(self):
        self._dicc["C"] = self.A + self.B
        return self._dicc


dict_dinamico = DictDinamico()
print(dict_dinamico.dicc)
dict_dinamico.B = 4
print(dict_dinamico.dicc)
```

```
output:
{'a': 1, 'b': 2, "C": 8}
{'a': 1, 'b': 2, "C": 9}     
```

La solución anterior la encuentro bastante más elegante, pero tal vez sea un poco _overkill_ tener una clase **solo** para un diccionario y nuevamente, tendría más sentido que esto sea parte de una clase "más grande".
Espero haya quedado claro, sino puedes preguntar!

**Comment by fernandosmither** [comment]
> Hola @fernandosmither!
> [...]
> La solución anterior la encuentro bastante más elegante, pero tal vez sea un poco _overkill_ tener una clase **solo** para un diccionario y nuevamente, tendría más sentido que esto sea parte de una clase "más grande".
> Espero haya quedado claro, sino puedes preguntar!

Buenísima, te entendí perfecto. Ahora entiendo que al final como la mejor forma de implementar el "dict dinámico" depende de crear una nueva clase heredera y de algunos overrides, veo que puede no ser lo más eficiente. I'll stick to your firsts suggestions.

Gracias 😄 


<details>
  <summary>No pescar esto</summary>

~Entonces, ¿la única forma de hacer esto sería mediante un override a una clase heredera de `dict`?
Mi pregunta me hacía más sentido porque yo hasta ahora hacía un truco parecido (por ejemplo) para almacenar en una """variable""" dinámicamente cuántos elementos "X" hay en una lista.~

```py
class Servicio:
    def __init__(self):
        self.tipo_usuarios = ["fumador", "fumador", "chad", "uwu", "fumador", "owocólico"]

    """ Imaginemos que la lista anterior cambia constantemente en el código,
    de esa manera no se podría guardar un .count 'estático' aquí"""

    # Imprimir la cantidad de usuarios fumadores, chad's, uwus, etc...
    fumadores = 0

    @property
    def fumadores(self):
        return self.tipo_usuarios.count("fumador")

    @property
    def chads(self):
        return self.tipo_usuarios.count("chad")

    @property
    def uwus(self):
        return self.tipo_usuarios.count("uwu")

    @property
    def owocolicos(self):
        return self.tipo_usuarios.count("owocólico")


service = Servicio()
print(f"Hay {service.fumadores} fumadores, {service.chads} chads, {service.uwus} uwus, {service.owocolicos} owocolico(s).")
```
~Output:~
```
Hay 3 fumadores, 1 chads, 1 uwus, 1 owocolico(s).
```

~Pero, mi idea era si en vez de tener estas 4 properties (podrían ser muchísimas más hipotéticamente), podría hacerlo igual pero con una property que reciba la solicitud de get como si fuera un diccionario (Que ahora entiendo que se puede hacer como explicabas tú)~
</details>
