### ISSUE TITLE
Separando dos drops

### ISSUE THREAD

**Issue by CataSudo** [IIC2233/syllabus#785]
<img width="787" alt="Screen Shot 2020-05-20 at 21 19 37" src="https://user-images.githubusercontent.com/62016215/82512967-a1228500-9adf-11ea-9d0c-13aaf1b6488a.png">
Hola, al intentar drop el chef o la silla se me mezclan los dos. Hay una forma de separarlos? Por que al final el Drop Event no toma en consideración algún indentificador. Dejo un ejemplo de lo que me refiero.

**Comment by kadroguett** [comment]
Hola @CataSudo 
Debes tomar en cuenta que en en los eventos Drag y Drop se puede traspasar diferente información utilizando QMimeData, puedes manejar esta información haciendo _override_ sobre el método dropEvent().
Te recomiendo revisar la documentación sobre **Drag and Drop**: https://doc.qt.io/qt-5/dnd.html
