### ISSUE TITLE
Problema con time.sleep()

### ISSUE THREAD

**Issue by Zenos-Paradox** [IIC2233/syllabus#785]
* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

Cuando intento usar la función time.sleep() con un float, me tira un TypeError, diciendo que requiere un int. Toda la documentación que he leído indica que puede recibir floats. ¿Alguna idea?
```

self.sleep(self.step)
TypeError: sleep(int): argument 1 has unexpected type 'float'
```

**Comment by tocococa** [comment]
Hola @Zenos-Paradox ! El método `sleep()` de PyQt no es lo mismo que `time.sleep()` (por el snippet que pusiste me tinca que es eso). Si bien es correcto que `time.sleep()` puede recibir un float para entregar mayor precisión, el método `sleep()` de QThread recibe un int. 
Puedes revisar la documentación de sleep [acá](https://doc.qt.io/qt-5/qthread.html#sleep) y qué es un `unsigned long` [acá](https://www.tutorialspoint.com/cplusplus/cpp_data_types.htm).

**Comment by Zenos-Paradox** [comment]
aah tienes razón. Use self.sleep sin darme cuenta de que eso iba a llamar al sleep del QThread en el que estaba. Gracias :)
