### ISSUE TITLE
Error al abrir ventana de edición

### ISSUE THREAD

**Issue by akrebs2** [IIC2233/Syllabus#785]
Hola
Llevo como 3 horas pegado en un problema que no he podido resolver. Cada vez que intento abrir la ventana de edición, una vez que se valida el usuario, la gui se queda "pegada" y en consola me aparece este error:
QObject::killTimer: Timers cannot be stopped from another thread

He buscado pero nada me ha servido. Por favor ayuda!

**Comment by eitandv** [comment]
Me pasaba lo mismo y al final lo solucione interactuando con la gui solo a través de  pqtsignals (y un par de sacrificios a los dioses oscuros). Esta mejor explicado en la ayudantia de networking! Ojala te ayude!!
#NoSoyAyudante
