### ISSUE TITLE
Definir ciudades y países en base de datos

### ISSUE THREAD

**Issue by savelozo** [IIC2233/Syllabus#785]
Hola!

Entendí que debemos crear, por nuestra cuenta, una base de datos para utilizarla posteriormente en nuestro programa. Mi duda es: ¿Cómo definimos qué ciudades y países deben estar?¿Cuántos países y ciudades deberíamos tener en ella?

Saludos!

**Comment by ifcarrera** [comment]
Hola! 
Queda bajo su criterio qué países y ciudades (y en cuánta cantidad) poner para que puedan probar su tarea. Pero deben poder soportar **cualquier número** de países y ciudades al momento de subir su tarea.
Saludos

**Comment by savelozo** [comment]
No entendí a que te refieres con: "Pero deben poder soportar cualquier número de países y ciudades al momento de subir su tarea". Te refieres a que nuestro programa debe estar diseñado para (teóricamente) tener una base de datos "infinita" y trabajar eficientemente con ella, a pesar de que nosotros solamente tengamos 10 países y 10 ciudades en ella?

**Comment by TomasSalvadores** [comment]
Claro! 
Por limitantes físico-matemáticas, no probaremos el caso de valores infinitos, pero tu programa debe estar preparado para recibir una cantidad indefinida de paises y ciudades, puesto que no pueden saber de que dimensiones serán las sheets con las que los probaremos.
Good luck!
