### ISSUE TITLE
Faltan imagenes de algunos pasos de baile ?

### ISSUE THREAD

**Issue by sperezmasri** [IIC2233/syllabus#786]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! En en los  ```sprites``` en las imagenes relacionadas a los pasos de baile de los pinguinos creo que falta una imagen para el paso "arriba_abajo" y el paso "izquierda_derecha". De lo que entendí del enunciado los pasos de baile pueden ser cualquier combinación de las cuatro flechas, por lo que me pareció raro no encontrar dichas imagenes.

**Comment by danckoo1** [comment]
hola 👋 efectivamente no hay una sprite para todas las combinaciones de teclas posibles, por lo que en aquellos casos que encuentres que no tienen una sprite podrás asignarles cualquiera, ya sea repetir alguna de las utilizadas o si lo crees necesario, puedes crear una nueva por tus medios y subirla con tu entrega ( **no** debe ser ignorada por tu .gitignore a diferencia del resto de los sprites). Es importante que no olvides mencionar tu decisión en el readme para que no hayan confusiones.
saludos!

**Comment by sperezmasri** [comment]
Gracias!!
