### ISSUE TITLE
Duda QTimer

### ISSUE THREAD

**Issue by mpenalozag** [IIC2233/syllabus#786]
Usar QTimer cuenta como usar threading ?
gracias de antemano

**Comment by fdoflorenzano** [comment]
Hola @mpenalozag,

Sí, lo consideramos como uso de *threading*.

Saludos.

**Comment by Camila-sty** [comment]
@fdoflorenzano  con respecto a tu respuesta se considera como uso de threading si la clase donde ocupo ```QTimer``` debe heredar de ```QThread``` ? . Si esto es así, puedo hacer que ésta misma clase no implemente el método ```run()``` ?

**Comment by fdoflorenzano** [comment]
Hola @Camila-sty,

Suena raro lo que preguntas, ¿para qué heredaría de `QThread` si no implementa `run`? ¿cómo lo ocuparías como *thread*? Si es el `QTimer` que tiene lo que lo hace *thread*, entonces la respuesta anterior sigue aplicando, independiente de lo que herede la clase contenedora.

Saludos.

**Comment by Camila-sty** [comment]
Sí. Es que me confundí por algunos errores que tenido al hacer ````run()``` con ```QTimer```. Pero entiendo. Gracias :+1:

**Comment by Camila-sty** [comment]
@fdoflorenzano holaa. Aún tengo la duda de la afirmación " ```QTimer``` cuenta como usar threading". Esto se refiere al hecho de usar ```QTimer``` nomas?. O hay que hacer que la clase donde se implemente ```QTimer``` debe heredar de ```QThread```?
