### ISSUE TITLE
Uso de código de internet

### ISSUE THREAD

**Issue by isidorabecker** [IIC2233/syllabus#787]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, tengo una duda respecto al drag an drop, ya que encontre un codigo en internet que me dio una idea de como hacerlo, quiero saber si lo puedo poner, y de ser así que debo hacer para implementarlo.

Muchas gracias !!!

**Comment by JuaniAndres** [comment]
Hola @isidorabecker 
Si, puedes utilizar el código que encontraste para tu tarea lo importante es que quede super claro en donde lo ocupaste, de donde lo sacaste y quien fue el autor del código (si es de un foro especificar el usuario y cual de todas sus respuestas). Para referenciar debes dejar lo que te dije escrito en tu readme  y si quieres dejarlo aun más claro puedes además dejar un comentario en tu código en la parte que lo utilizas con la misma información.
Si tienes más dudas me avisas

**Comment by isidorabecker** [comment]
Ok, si es de un video de youtube, agrego el link igual ?

**Comment by JuaniAndres** [comment]
si puedes poner el link, el autor del video y en que parte ocupaste el código.

**Comment by isidorabecker** [comment]
Muchas gracias !!

**Comment by ignaciomansuy** [comment]
Hola @JuaniAndres, también quiero referenciar un código. A isidora le dijiste que habías escrito en su Readme cómo referenciar ("_debes dejar lo que te dije escrito en tu readme_"), podrías explicarme a mí también por favor?
Saludos! :)

**Comment by JuaniAndres** [comment]
Hola @ignaciomansuy 
Me refería en esa parte  a esto  "_que quede super claro en donde lo ocupaste, de donde lo sacaste y quien fue el autor del código (si es de un foro especificar el usuario y cual de todas sus respuestas)_"  con esas tres cosas escritas en tu readme queda super claro la cita. Lo anterior  lo escribes en la sección ````Referencias de código externo````  de tu README.
