### ISSUE TITLE
Juntando ventanas

### ISSUE THREAD

**Issue by Agonzd** [IIC2233/syllabus#787]
Hola!
Tenia una duda acerca de la unión de distintas ventanas creadas (como QWidgets).
Para el caso de la ventana de juego, opte por crear una ventana que maneje el mapa, otra ventana que contenga las estadísticas (como dinero) y una ventana general que contenga a ambas. Sin embargo, no logro agregar correctamente ambas ventanas a la ventana final y siempre aparecen como dos ventanas separadas o se superponen.
¿Hay alguna forma de agregar dichas ventana y luego poder manejarlas dentro de la principal con move() por ejemplo?
Intente hacerlo con QVBoxLayout y algo funcionaba, pero se superponen las ventanas y solo se ve bien en pantalla completa o sucede que un elemento no se muestra correctamente.
¿Seria mas conveniente dejarlo todo en una sola ventana? Lo digo porque encuentro mas ordenado tener las cosas separadas.
Gracias de antemano!

**Comment by danckoo1** [comment]
hola!
sobre que metodo es mas conveniente depende mas que nada de tu preferencia personal, ya que ambas opciones son viables. Si quieres poder incorporar una ventana dentro de otra siempre es posible definir la ventana principal como el `parent` de tu ventana secundaria y luego para posicionarla correctamente dentro de la ventana principal puedes utilizar `move` tal como lo mencionas. 
Si no queda claro podrías hacer un push a tu repositorio para observar como lo implementas y darte un feedback mas completo :)

**Comment by Agonzd** [comment]
Creo entender eso de la ventana principal como parent, pero no se bien como implementarlo.
Subí mi avance al repositorio y al ejecutar main.py se puede ver mi problema.
Agradecería mucho ese feedback! :)

**Comment by danckoo1** [comment]
Acabo de verlo y estas casi listo, tan solo que cuando defines la clase `Stats` deberías hacerlo de igual forma que como lo haces con la clase `Mapa`, utilizando (`*args` y `**kwargs`) para que ambas puedan recibir un parent. Luego cuando creas las instancias de `Stats` y `Mapa` como atributos de la ventana de juego, tan solo tienes que entregarles el parent, que en esta caso sera `self`; ya que lo estas haciendo dentro del init del parent. Hecho esto estas listo para ubicarlas con algun metodo como `move()`.  Ojo que el label que contiene el fondo de color puede tapar los stats y el mapa ya que lo creas después, por lo que te puede resultar de gran ayuda el metodo `raise_()`, espero te sirva!

**Comment by Agonzd** [comment]
Perfecto, muchas gracias!
