### ISSUE TITLE
¿Error enunciado?

### ISSUE THREAD

**Issue by ljrodriguez1** [IIC2233/Syllabus#787]
En seccion 5.2.1 sale que la nota 4 es mib o Eb, pero esta nota no esta en la tabla de valores de seccion 3.2 en la parte Nota, segun lo que tengo entendido esa nota no existe, tambien quisera saber es si es posible en vez de empezar en 1 para do como en tabla de seccion 5.2.1, pudieramos partir en 0 para que los numeros concuerden con los de la seccion 3.2

**Comment by Hernan4444** [comment]
@ljrodriguez1 mib == la# por si acaso. Y no es posible segundo.  En la interfaz usan el cuadro 1, y el manejo de bytes usan la figura 2. Queremos que separen ambos valores y por ello no es posible empezar de 0
