### ISSUE TITLE
Error para enviar mensajes

### ISSUE THREAD

**Issue by antoniacobo** [IIC2233/Syllabus#788]
Hola! Estoy pegada en un error hace mucho tiempo y no sé como resolverlo. Estoy usando un protocolo para enviar los mensajes entre mi cliente y servidor que es basicamente hacer un diccionario con el request y los parametros a enviar, pasarlo a json, codificarlo y enviarlo con sendall (que me ha funcionado con todo) ahora lo implemente con una nueva funcion y dejo de funcionar para todo. Hice prints para revisar donde se queda pegado y los mensajes salen del cliente pero nunca llegan al servidor. No se me ocurre cual puede ser el problema y no puedo seguir con nada. 

Por favor ayuda!!

PD: si vuelvo para atras hasta mi ultimo commit si funciona todo, solo cuando agrego esta funcion deja de funcionar.

**Comment by Wamedina** [comment]
Tengo exactamente el mismo error y llevo demasiado tiempo en lo mismo, por favor si alguien lo pudo arreglar que avise!
