### ISSUE TITLE
ModuleNotFoundError pero módulo está en la misma carpeta

### ISSUE THREAD

**Issue by burizar** [IIC2233/syllabus#788]
### Prerrequisitos

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola!
Estoy tratando de importar parametros.py a otro módulo A y funciona bien pero cuando importa A en el main para correrlo me tira el error ModuleNotFoundError para el módulo A. Tanto parametros como el módulo A se encuentran en la sub carpeta frontend de la tarea y main.py se encuentre en la carpeta T02.

**Comment by kadroguett** [comment]
Hola @burizar, como haces el import del `módulo A` en `main.py`?

**Comment by burizar** [comment]
from frontend.moduloA import ClaseA

**Comment by kadroguett** [comment]
Estás seguro de que no omitiste ningún espacio en los nombres o bien un tilde?

**Comment by burizar** [comment]
muy seguro

**Comment by kadroguett** [comment]
puedes subir a tu repositorio los archivos para revisarlos mejor, por favor

**Comment by burizar** [comment]
Igual tuve que crear dos módulos parametros, uno para el frontend y otro para el backend porque no encontré una forma de importar parametros directo de la carpeta T02, quizás eso tiene algo que ver.

**Comment by burizar** [comment]
subo altiro mis archivos a mi repositorio

**Comment by kadroguett** [comment]
Hola de nuevo, estuve buscando el problema y se debe a que python no busca en los directorios nuevos que creaste (`frontend y backend`). Para solucionar esto debes agregar el path de los nuevos directorios para que python los busque adecuadamente, a continuación puedes ver una imagen de como agregar el path:
![image](https://user-images.githubusercontent.com/31357861/97065108-9d5cc800-1581-11eb-9f23-69045a9a0cfe.png)

En la imagen puedes ver que se hace `sys.path.append` dos veces, solo con hacerlo una vez basta, la primera opción te la muestro para que veas como se agrega el path, pero la segunda es la adecuada para evitar descuentos y problemas al utilizar tu código en diferentes equipos. 

Luego probablemente te aparezca un error de que el archivo `ventana-juego.ui` no existe, para arreglar esto debes cambiar el path en el archivo ventana_juego.py de esta forma:

![image](https://user-images.githubusercontent.com/31357861/97065167-2d027680-1582-11eb-8155-c4565d53bd50.png)

Prueba arreglando ambas cosas y me dices como te va.

**Comment by burizar** [comment]
Ese path lo debo agregar al main.py? 
No me había dado cuenta del otro error, cambie el path en el uic.loadUiType y me tiro el error igual, pero si lo corro desde el cmd no me lo tira.

**Comment by kadroguett** [comment]
El código 
```
ruta = os.getcwd()
ruta = ruta + "\\fronted"
sys.path.append(ruta)
```
Debes agregarlo al inicio del archivo `main.py`

**Comment by burizar** [comment]
Ahí funcionó! Gracias!
