### ISSUE TITLE
Duda QRect y colisiones

### ISSUE THREAD

**Issue by lewebe** [IIC2233/syllabus#788]
Hola, estoy viendo el tema de las colisiones con el mesero y en el enunciado recomiendan el uso de **QRect** y su método **.intersects()** para comprobar colisiones. Sin embargo, por la documentación estoy entendiendo que este método detecta intersección entre dos QRects. Para hacerlo funcionar, debo definir un QRect "encima" del mesero que lo siga a todos lados y que revise si hay colisión entre los otros objetos que también tienen un QRect "encima"? O debo reemplazar todos mis objetos de frontend que tengo definidos como _QLabels_ por QRects y cargar las imagenes en el QRect (no se si eso se puede) ? Estoy un poco perdido con las colisiones

**Comment by furcelay** [comment]
Todos los `QWidget` tienen un atributo `rect` que corresponde a un `Qrect` con la posición y tamaño actuales del widget, entonces si tienes dos `QLabels` puedes hacer `label_1.rect.intersects(label_2.rect)` que retorna `True` si se intersectan.

Espero que te sea de ayuda!

**Comment by MINGOD24** [comment]
Hola @furcelay, estaba intentando de utilizar el metodo intersects, pero me sale el siguente error: 'builtin_function_or_method' object has no attribute 'intersects'. Lo busque en internet pero sin mayor exito. Me falta importar una libreria? o porque sucede?

**Comment by furcelay** [comment]
Perdón, cometí un pequeño error :sweat_smile:
Estuve probándolo y me di cuenta que `rect` no es un atributo de `Qwidget` sino un método (que tiene sentido ya que debe cambiar de posición/tamaño con el widgwet), entonces debes hacerlo como `label_1.rect().intersects(label_2.rect())`.

Saludos!

**Comment by lewebe** [comment]
Gracias por la respuesta! Sabes si hay alguna manera de chequear la intersección de `label_1.rect()` con _cualquier_ otro rect, y no con uno específico? se me ocurre iterar sobre mi lista de entidades y chequear una a una si se está intersectando con mi label, pero me parece que sería demasiado poco eficiente... 🤔

**Comment by furcelay** [comment]
Lo veo difícil, por lo que entiendo un label no sabe de la existencia de otros labels en la ventana. Creo que lo mejor sería iterar sobre todas las entidades como mencionas. Sería algo lento si hubiesen demasiadas entidades en tu ventana, pero como la cantidad está limitada por espacio no creo que lleguen a haber tantas como para que tarde más de unos milisegundos, así que creo que para este caso funcionaría bien. 

Te recomiendo probarlo de todos modos.

**Comment by lewebe** [comment]
@furcelay Hola! Estoy haciendo probando eso  con un código de tipo 
```python
for entidad in self.entidades.values():
            print(mesero.rect().intersects(entidad.rect()))
```
donde `self.entidades` es un dict que guarda **todos** los objetos del mapa como qlabels, incluyendo al mesero. El output que me da son puros `True`, siendo que el único `True` que me debería arrojar es cuando `mesero` intersecciona consigo mismo en la primera iteración de `self.entidades`

**Comment by furcelay** [comment]
Prueba imprimir los rectángulos con `.getRect()` que te entrega una tupla `(x, y, ancho, alto)`:
```python
print("rectángulo mesero: {mesero.rect().getRect()}")
for i, entidad in enumerate(self.entidades.values()):
    print(f"Rectángulo {entidad.rect().getRect()} intersecta: {mesero.rect().intersects(entidad.rect())}")
```
Puede que efectivamente se estén intersectando...
