### ISSUE TITLE
Formato Sheet Paises - Ciudades

### ISSUE THREAD

**Issue by B-Dominguez** [IIC2233/Syllabus#788]
Holaa, sólo quiero asegurarme. Dado que el enunciado dice "_Dada una planilla de Google Sheets con el siguiente formato:_", podemos asumir que el formato de la planilla será correcto cierto? Con país en la primera columna, datos empiezan en 2da fila y sin filas vacías?

**Comment by ifcarrera** [comment]
Sí, pueden asumir eso. Ojo que podrían haber ciudades no existentes también. 
Saludos

**Comment by Fhguinez** [comment]
¿Con ciudades no existentes te refieres a casillas de ciudad vacías? ¿o a ciudades que podrían no dar resultado al ser buscadas en la API de Maps?

**Comment by ifcarrera** [comment]
A lo segundo, pueden asumir que no habrán casillas vacías en un listado de ciudades. Pero si podría haber una ciudad con el nombre “wenawenamrion”.

Salu-primer dígito del año en que estamos
