### ISSUE TITLE
Spreadsheet - Consulta única / consultas separadas

### ISSUE THREAD

**Issue by B-Dominguez** [IIC2233/Syllabus#789]
Holaa,
Podemos realizar la consulta a sheets una sola vez y guardarlo en el programa? O se espera que las consultas sean en tiempo real / se evite usar espacio de memoria, y se consulten las ciudades cada vez que se elija un país?

**Comment by ifcarrera** [comment]
Disculpa la demora. Consúltalas siempre, por si alguien de la nada agrega más ciudades a un país. 
Saludos

**Comment by fgbruna** [comment]
@ifcarrera a que te refieres con hacerla todo el rato? a que frecuencia debería corresponder más o menos? Y con hacerla todo el rato lo dices por si alguien agrega información al sheet *mientras se está ejecutando la aplicación* :o?

**Comment by ifcarrera** [comment]
síp, cada vez que se seleccione un nuevo país haz la consulta para saber qué ciudades tiene.
