### ISSUE TITLE
Subir canciones

### ISSUE THREAD

**Issue by AlexanderBarrera** [IIC2233/Syllabus#789]
Hola, no me queda claro un tema con respecto si es que se suben las canciones al guit, dado que las canciones a la carpeta midis del servidor, y se facilita mucho la recorreccion. Las subo, o no?

**Comment by Hernan4444** [comment]
@AlexanderBarrera si, se pueden subir los midis, pero recuerda que tambien nosotros podemos ingresar otros como los del ejemplo.
