### ISSUE TITLE
Video ayudantía 8 (2020-1)

### ISSUE THREAD

**Issue by Gustav2000** [IIC2233/syllabus#789]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

[Agrega aquí lo que quieras aportar o preguntar]
Hola, he estado revisando la ayudantía 8 del semestre pasado (2020-1) y quería saber si es que aún tienen en alguna parte el link del video (pregunto porque me dijeron que se había subido un video de esa ayudantía) es la de Rick & Morty. 

Pd: la encontré muy útil para entender mejor los conceptos necesarios para la T02

**Comment by gatochico** [comment]
Hola @Gustav2000 !

Lamentablemente no tenemos disponibles los videos de ayudantías de semestres pasados. Esto se debe a que el curso está en constante desarrollo, lo que significa que materiales como los contenidos o ayudantías se van renovando semestre a semestre según lo que creamos son las mejores prácticas en ese momento. Esto hace que material pasado vaya quedando obsoleto y puede que posea prácticas o formas de realizar funcionalidades que ya no consideramos como las más óptimas, por lo que preferimos inhabilitar ese material para evitar confusiones o problemas a futuro.

De todas formas, lo que si queda disponible son los syllabus de semestres anteriores 🙌. En ellos podrás encontrar el código entregado de ayudantías pasadas si quieres revisarlas. Nuevamente, cuando lo hagas ten en cuenta que es material antiguo y puede que hayan prácticas que hayan quedado obsoletas o tengan versiones actualizadas en el syllabus de este semestre 😉.

Saludos y espero se entienda!

**Comment by Gustav2000** [comment]
Okaa, gracias.
