### ISSUE TITLE
Duda sobre subir archivos al repositorio de una actividad cerrada

### ISSUE THREAD

**Issue by EnzoMorata** [IIC2233/Syllabus#79]
### Prerrequisitos

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Ayer fue la AF1 en donde había que subir los archivos .py a nuestro repositorio personal, lo que sucede es que en su momento no incluí un archivo .gitignore para evitar subir el archivo .csv que nos entregaban, y ahora trabajando en otra carpeta de mi repositorio personal al utilizar git status me indica esa diferencia. Entonces, mi duda es si sería aconsejable que yo ahora crease un archivo .gitignore señalando este archivo .csv, y además hacer commit y push del gitignore a la carpeta de la actividad cerrada? o simplemente debería eliminar el .csv para evitar estos problemas?

**Comment by kunafuego** [comment]
¡Hola! Te recomiendo que crees el archivo .gitignore en la carpeta de la AF1 para que te vayas acostumbrando a su uso y aprendas sobre su funcionamiento. De todas maneras, como fue la primera actividad no se evaluará el uso de este. Eliminar el archivo csv también funcionaría, pero sería una solución menos elegante.

Sobre lo de hacer push y commit en la actividad cerrada, es completamente legal. Nosotros evaluaremos lo que hay en tu repo a una determinada hora, pero eso no impide que tu puedas seguir trabajando en ella después.

**Comment by EnzoMorata** [comment]
Ya, muchas gracias!
