### ISSUE TITLE
Duda ejerc. prop. 2.3 (DCCgram)

### ISSUE THREAD

**Issue by JuanpaBC** [IIC2233/syllabus#79]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola, estoy muy perdido en este ejercicio, sobre todo porque la clase "Usuario" del código base tiene 4 properties que comparten su nombre con un atributo público de la misma clase ("username", "mail", "edad" y "rut"), lo cual me confunde bastante.

Esto fue lo que entendí al principio en el código base: los atributos públicos de la clase "Usuario" contienen los datos del usuario, mientras que las properties son para determinar altiro si los datos de los respectivos atributos públicos son válidos o no para que el usuario sea agregado a la plataforma DCCgram. 

Pero luego me pasaba que no sabía donde establecer las condiciones de validez de los datos del usuario ni donde definir el valor de verdad de las properties (en los metodos getter, en los setter, en el __init__ mismo o en la función "agregar" de la clase "DCCgram"). Adicionalmente, no sabía como llamar específicamente a una property o a un atributo público de un objeto "Usuario" fuera del código que define su clase, ya que ambas cosas siempre comparten el nombre.

Desde ya gracias.

**Comment by cristobalnic** [comment]
Hola @JuanpaBC!

En este ejercicio en particular se plantea que cualquier instancia de la clase Usuario siempre tenga sus atributos dentro de las condiciones que plantea el enunciado. Por ello, en el init de la clase, se crean tanto atributos públicos como atributos internos (con doble guión bajo). ¿Para qué se hace esto? Para que tanto al modificar un atributo como al crear una nueva instancia desde cero, todos los atributos pasen por las properties y cumplan con las restricciones que estas imponen.

A continuación te dejo un ejemplo conciso con una property que mantiene las notas de los alumnos entre 0 y 7:
![image](https://user-images.githubusercontent.com/48327806/112874094-e10bae80-9098-11eb-9514-a659cf44ae56.png)

Como se observa en el init, la nota se recibe en el atributo `self.nota`, cuyo valor luego pasa por la property y se guarda en el atributo interno `self.__nota`. En cambio, si comento la línea con el "duplicado" de nota, pasa lo que se ve a continuación:

![image](https://user-images.githubusercontent.com/48327806/112875278-5fb51b80-909a-11eb-975f-be393b8d7ece.png)

Debes fijarte en que al crear las properties estés alterando el valor del atributo interno y no del público, ya que este después se encuentra sobreescrito por las properties del mismo nombre y ya no podrá ser llamado tras haber instanciado la clase. 

Entonces, respondiendo a tu pregunta:

1) Las properties tienen un getter (que sirve para obtener información del atributo respectivo) y un setter (que sirve para darle un nuevo valor al atributo). Dadas esas definiciones y que el ejercicio está ideado para que utilices properties, debes definir las condiciones de validez para cada atributo en su **setter** respectivo, y no en otro lugar dentro del código. (Puedes guiarte en el ejemplo, o en los que hay dentro de los contenidos de la semana-02).

2) Al tener ambas el mismo nombre, como se define primero el atributo público y luego la property, este nombre aplicará solo a la property (sobreescribe el atributo anteriormente creado). Por ello, al llamar al atributo de una instancia "Usuario" estarás **accediendo** a los valores guardados en los atributos internos a través del **getter** de la property o **modificándolos** a traves de su **setter**.

Espero que esto haya resuelto tus dudas! :)

**Comment by JuanpaBC** [comment]
Mil gracias Cristóbal por la explicación y por el ejemplo que hiciste (me ayudo mucho a entender)! me quedó super claro!

**Comment by minsoos** [comment]
Hola, entiendo que ya lo explicaste, pero no lo entendí. ¿Qué hace internamente el código al agregar un atributo con doble underscore = None y posteriormente el normal = variable?
Gracias de antemano

**Comment by cristobalnic** [comment]
Hola @minsoos!

El código en esa parte permite que cuando se crea una instancia de Alumno, al momento de asignarle un valor al atributo `self.nota`, el valor ingresado (nota) pase por las restricciones impuestas en la property y se guarde finalmente en `self.__nota`.

De esta forma, ocurre la siguiente secuencia:
1) Se crea una instancia de alumno con su nombre y su nota.
2) El **nombre ingresado** pasa directamente al init y se guarda en `self.nombre`.
3) La **nota ingresada** NO entra al atributo `self.__nota` sino que este se guarda como vacío (None).
4) La **nota ingresada** se guarda en el atributo `self.nota`, el cual al ser alterado, activa su property.
5) Como la property lo indica, el valor de la nota pasa por las restricciones impuestas (Que sea mayor que 1.0 y menor a 7.0) y si no las cumple, se modifica para que lo haga.
6) Finalmente el valor que devuelve la property es guardado en `self.__nota` (pasa de ser *None* a ser el valor resultante de pasar por la property).

En resumen, el atributo "normal" o público (`self.nota`), en este caso solo sirve para guardar la variable ingresada (nota) al inicializar una nueva instancia de Alumno, pero finalmente es el atributo privado (`self.__nota`) el que termina guardando la nota del alumno durante el resto del programa.

Ojalá que esto te haya servido y cualquier otra duda puedes volver a preguntar!

**Comment by minsoos** [comment]
Hola,
leí la issue #192 y con esto me quedó súper claro, lo pego a continuación por si alguien lee después esta issue:
"en el __init__(), la línea que dice self.nota = nota no es la definición de un atributo, es una referencia a la property ya creada con la clase"
Muchas gracias Cristóbal!
