### ISSUE TITLE
Nombre de usuario: Prohibir un carácter

### ISSUE THREAD

**Issue by Cadutodalcielo** [IIC2233/syllabus#79]
En gran parte de mi código uso la "," para hacer split ¿puedo prohibir que el usuario escriba en su nombre una ","?

Gracias 👍

**Comment by Tito0906** [comment]
Holaa @Cadutodalcielo, el nombre de los usuarios debe ser alfanumérico, por lo que su nombre no llevará elementos de puntuación. Por lo mismo, las "," no deben estar en el nombre. Acuérdate de que al registrar un usuario nuevo, debes asegurarte de que el nombre del usuario debe cumplir con ciertos requisitos que están en el enunciado. 
Saludos!

**Comment by aljara97** [comment]
Hola @Cadutodalcielo, por favor no cierres esta issue, puede ser de utilidad para otro compañero, nosotros lo haremos cuando corresponda. 

Éxito con tu tarea
