### ISSUE TITLE
Duda sobre el balance y orders históricos de in Investor

### ISSUE THREAD

**Issue by MrEarle** [IIC2233/Syllabus#79]
Cuando en el enunciado dice:

> [Los Investors] También poseen permisos especiales: pueden ver su balance histórico y las orders históricos

Se incluyen los balances y orders que tuvieron cuando eran Traders? O solo desde que son Investors?

Saludos!

**Comment by hanavarrete** [comment]
No está especificado así que queda a tu criterio. Agrega al readme tu decisión! Saludos
