### ISSUE TITLE
Descuento "Cambio de líneas"

### ISSUE THREAD

**Issue by bozziuc** [IIC2233/Syllabus#79]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/20)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/19)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Entre los descuentos para la Tarea 1, aparece "Se descuentan 1-5 décimas por cambio de líneas.". ¿Qué quiere decir eso?
Muchas gracias

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by bozziuc** [comment]
Disculpe, vi que era una pregunta de mala práctica. Estoy intentando eliminar esta issue.

**Comment by MaxAl100** [comment]
Hola! Este cambio de líneas es una posibilidad de, después de entregar la tarea, poder cambiar unas líneas para arreglar, por ejemplo, el import. Esto significa que cambia el puntaje en otro aspecto de la tarea para perder décimas en este aspecto.
Es situacional y puedes observar si te conviene o no cambiar líneas.

También puede ser usado por un ayudante si la tarea no está funcionando y **requiere** este cambio de líneas para funcionar.

Si no te quedo claro, dime y puedo intentar explicarlo de otra manera. 😄
