### ISSUE TITLE
 duda path absoluto o relativo

### ISSUE THREAD

**Issue by Pdesolmi** [IIC2233/syllabus#79]
hola, ya hice casi toda la tarea y para crear o editar archivos usé el path absoluto, pero dependiendo de la persona que ejecute el código, es decir usé el método os.getcwd() y con eso cree y edité los archivos de puntajes o partidas guardadas, amigos me están diciendo que parece que no había que usar el path absoluto sino que el relativo, pero yo uso el path dependiendo quien corre el programa, está bien? o tengo que cambiarlo.

**Comment by jmwielandt** [comment]
Hola!

Debes cambiarlo. Tal como se menciona en la [sección de descuentos](https://github.com/IIC2233/syllabus/blob/master/Tareas/Descuentos.md#formato-de-entrega-hasta-5-d%C3%A9cimas-inbox_tray), usar paths absolutos en lugar de relativos tiene un descuento asociado. 😢 

Puedes ver más issues al respecto para saber lo que se ha hablado.

Saludos~

**Comment by Pdesolmi** [comment]
Es que se que el path absoluto no se puede usar porque en otro computador no se correría el programa, pero como uso os.getcwd() que me entrega el path absoluto de la persona que corre el programa funciona para cualquier persona y computador. en los descuentos no se referirá al path absoluto personal??
adjunto un pedazo pequeño de lo que me refiero
```python
path_tarea0 = os.getcwd()
if not os.path.exists(os.path.join(path_tarea0, "partidas")):
    os.mkdir("partidas") 
```

**Comment by jmwielandt** [comment]
Hola!

Lo que haces es innecesario, siento que te estás complicando más de la cuenta y no es el objetivo :cry:Te recomiendo mirar la issue #81 , ahí acabo de explicar algo respecto a los paths relativos que te puede ser de utilidad y usar paths relativos por simplicidad. A efectos de ejecución en principio no debería haber una diferencia notable, pero para eso mejor usa paths relativos y ya. :smile:

Saludos~
