### ISSUE TITLE
Duda con el menú principal

### ISSUE THREAD

**Issue by Daniel-Guajardo** [IIC2233/Syllabus#79]
Basándome en este ejemplo de "menú de principal" que aparece en el enunciado,

![image](https://user-images.githubusercontent.com/101299560/161403914-09627568-3ac8-4a85-86a9-e92f0e347379.png)

Considerando que ya había escogido un jugador representante, mi duda es: al seleccionar la opción de "volver" y regresar a "opciones de jugador", ¿qué pasa con el jugador que había escogido? ¿deja de ser mi representante y puedo escoger un representante nuevo en la misma partida?

**Comment by jtvaldivia** [comment]
Hola, 
Como dice en el enunciado uno al elegir un personaje se inicia una partida. De esta forma, cada vez que elige un jugador se comienza una partida nueva, de este modo borrando la partida anterior

**Comment by IgnacioHqz** [comment]
Hola! quisiera sumarme a la pregunta. Si es que uno elige la opción "Volver", esto significa que se volverá al menú que estaba antes siempre? o Volver significa retroceder a lo que estaba justo antes?? Me explico, por ejemplo, si se decide iniciar partida, se mostrarán a continuación todos los personajes. Luego se escogerá uno de ellos y después se mostrará el Menú Principal. En esté menú aparece la opción de Volver tal como se muestra en la foto que subió mi compañero en su issue. Pero si se selecciona esta opción, hay que retroceder directamente al Menú de Inicio o retroceder al momento en donde se muestran todos los personajes para luego seleccionar uno de ellos?? Saber esto me sirve para saber como se considera este botón para otros menús que también traen esta opción de volver. Gracias!

**Comment by jtvaldivia** [comment]
Hola, 
se debe volver al menu de inicio.

**Comment by isidoraabumohors** [comment]
Hola! Me sumó a la duda anterior. Si bien ya fue respondida, no me queda tan claro. A lo largo del programa se muestran reiteradas veces las opciones de Volver y Salir. Independientemente del lugar en el que se encuentre el jugador, Volver siempre va a volver al menú inicio (es decir, sale el jugador y se tiene que volver a elegir un jugador), y Salir va a terminar el programa? 
Perdón por repetir la consulta pero quiero asegurarme que entendí bien. 
Gracias!

**Comment by jtvaldivia** [comment]
Hola, 
perdon por el malentendido yo me referia en el caso de estar en el menu principal, debido a que la issue originalmente era en ese contexto. En caso de elegir volver la idea seria que retrocedieras al menu anterior y en caso del menu principal al menu de inicio. Mientras que la opcion de salir es para finalizar como bien dicen.

**Comment by isidoraabumohors** [comment]
Gracias!!
