### ISSUE TITLE
Duda respecto a función crear_predios de la clase DCCultivo

### ISSUE THREAD

**Issue by Igufu** [IIC2233/Syllabus#79]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Saludos, tenía una duda respecto a la función `crear_predios(self, nombre_archivo: str) -> str:`. El archivo que se le solicita a la función (y que *existe*) siempre será llamado `"predios.txt"`o puede tener cualquier nombre? (en los tests cases solo tiene el nombre `"predios.txt"`) Gracias.

**Comment by ignacio-sp** [comment]
Hola @Igufu, el archivo que es utilizado para cargar los predios siempre tendrá el nombre `predios.txt`, tal como se indica en el apartado 4.2 del enunciado, el contenido de este archivo puede variar, pero se mantiene el formato, esto incluye el nombre de este. Saludos!

**Comment by Igufu** [comment]
Gracias! Eso resuelve mi duda :)
