### ISSUE TITLE
Recursos al inicio de la partida

### ISSUE THREAD

**Issue by jalliende** [IIC2233/syllabus#79]
Cuando la partida parte de cero, asumimos que las civilizaciones parten con 0 de cada material o podría ser que tuvieran material previamente.

**Comment by jeschuwirth** [comment]
Saludos, eso sale en el enunciado, seccion 6.1.1

![image](https://user-images.githubusercontent.com/37160256/55204396-92776100-51ad-11e9-9f1e-7de410c61356.png)

El archivo civilizaciones.csv tiene la información de los recursos iniciales.

Suerte!
