### ISSUE TITLE
generacion de archivos (columnas aleatorias)

### ISSUE THREAD

**Issue by Pelaysen** [IIC2233/Syllabus#79]
al generar los archivos galaxias.csv y planetas.csv mediante el generar_archivos.py los archivos csv generan aleatoriamente el orden de las columnas, se debe tomar los primeros archivos generados y adecuar el programa a estos primeros, o se debe modificar el programa para que pueda aceptar cualquier orden de columnas?

**Comment by ptflores1** [comment]
Hola !
La idea es que su programa puede admitir cualquier orden en las columnas.
Saludos !
