### ISSUE TITLE
Año mayor a 9999

### ISSUE THREAD

**Issue by akaminetzkyp** [IIC2233/Syllabus#79]
Hola!

Vengo con una duda un poco ridícula. Podemos suponer que nunca se va a ingresar un año mayor a 9999? De esta manera, los años siempre van a tener cuatro dígitos.

Gracias!

**Comment by hanavarrete** [comment]
La idea es que tu programa pueda manejar cualquier tipo de errores, así que no puedes suponer eso.
Saludos!

**Comment by akaminetzkyp** [comment]
Mi programa no se caerá si ponen una fecha fuera de rango. :)

Me refiero que si el usuario ingresa, por ejemplo, el año 12000, el programa le dice que el año esta fuera de rango.

Saludos!
