### ISSUE TITLE
Dimensiones tablero 

### ISSUE THREAD

**Issue by TarekHirmas** [IIC2233/Syllabus#79]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! En la tarea se habla de que tanto el largo [X] como el ancho [Y] están contenidos en el conjunto [3,15].

En el caso que ambos sean 3, el tablero seria de 4x4 (pensando que python cuenta desde 0, entonces: 0, 1, 2,3) o seria un tablero de 3x3? (0, 1, 2).

Gracias

**Comment by Lord-Kelsier** [comment]
Hola, seria de 3x3
