### ISSUE TITLE
Se puede importar la librería 'copy' de Python?

### ISSUE THREAD

**Issue by GitCross135** [IIC2233/Syllabus#79]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Puedo importar la libreria 'copy' de Python? Para realizar la copia del tablero y modificar esta sin modificar al original.

**Comment by Dominique236** [comment]
Hola!
La issue #55  fue creada para informar las librerías permitidas y las prohibidas, como también para consultar sobre una librería que no esté en el listado. De todas formas, la librería _copy_ se encuentra dentro de las librería permitidas ✅

**Comment by GitCross135** [comment]
Aaa graciass, no tenía idea de la existencia de esa issue perdón ;(
