### ISSUE TITLE
ejemplos para verificar_alcance_bombas

### ISSUE THREAD

**Issue by LunaGarces** [IIC2233/Syllabus#79]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/21)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/20)).
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### para el código del tablero que esta en functions.py 
    resultado = verificar_alcance_bomba(tablero_2x2, (0, 1))
    print(resultado, 'por revisar, alcance bomba, 2')  # Debería ser 2

    resultado = verificar_alcance_bomba(tablero_2x2, (0, 1))
    print(resultado, 'alcance bomba, 3')  # Debería ser 3

para verificar el alcance de las bombas tengo en los dos test las mismas coordenadas, entonces no se el resultado correcto es correcto o si el ejemplo de bajo se debe probar con tablero_2x2_sol (ya que no he modificado nada de esa parte (creo))

**Comment by Arielmanriquez** [comment]
Hola, no estoy entiendo muy bien tu pregunta(quizás es la hora), pero si estas revisando la misma casilla en ambos casos el resultado debería ser el mismo en ambos casos. Tambien recuerda que la funcion verificar_alcance_bomba() retorna el alcance total de la bomba, osea cuantas casillas alcanza antes de llegar con una pared o una tortuga.
Espero que haya resuelto tu duda, y si no, quedo atento al issue.
Saludos =)

**Comment by Hernan4444** [comment]
Hola @LunaGarces 

Recomiendo revisar esta issue 
* #50 

Cómo indica el título, esa parte hay un error, y en dicha issue se explica todo.
