### ISSUE TITLE
Problema con .raise_()

### ISSUE THREAD

**Issue by based-on-what** [IIC2233/syllabus#790]
Hola a todos, basándome en la ayudantía 8, quise "levantar" el sprite del mesero sobre el mapa, pero tengo el siguiente problema:
![noraise](https://user-images.githubusercontent.com/62000495/82531043-93cfbf80-9b0c-11ea-921e-0604ed748cda.PNG)

Es casi un copy&paste de la ayudantía 8, pero no logro entender por qué pasa esto, por lo mismo no he podido avanzar más allá en la tarea.

Saludos y muchas gracias.

**Comment by fdoflorenzano** [comment]
Hola @based-on-what,

El error que te lanza es bastante directo, estás intentando llamar a un método de un **atributo que no existe** en la clase `Mapa`. En la ayudantía se hace algo similar con un atributo `rick_label`, pero este si existe porque fue definido previamente con ese nombre en Qt Designer. Si también estás cargando algo de Qt Designer, fíjate que el nombre del label que creaste corresponda efectivamente al que esperas: `mesero_label`.

Espero se entienda,
Saludos.

PD: Edité tu pregunta debido a que incluiste código explícito de tu código de la tarea. Recuerda tener ojo con eso, e intenta en el futuro adaptar los ejemplos que muestras para simular tus errores.

**Comment by based-on-what** [comment]
> Hola @based-on-what,
> 
> El error que te lanza es bastante directo, estás intentando llamar a un método de un **atributo que no existe** en la clase `Mapa`. En la ayudantía se hace algo similar con un atributo `rick_label`, pero este si existe porque fue definido previamente con ese nombre en Qt Designer. Si también estás cargando algo de Qt Designer, fíjate que el nombre del label que creaste corresponda efectivamente al que esperas: `mesero_label`.
> 
> Espero se entienda,
> Saludos.
> 
> PD: Edité tu pregunta debido a que incluiste código explícito de tu código de la tarea. Recuerda tener ojo con eso, e intenta en el futuro adaptar los ejemplos que muestras para simular tus errores.

Muchísimas gracias, ahora va bien.
