### ISSUE TITLE
Uso de path de las imagenes

### ISSUE THREAD

**Issue by kalarconvl** [IIC2233/syllabus#790]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Al momento de poner las imagenes en las ventanas me surgió la duda de cómo debemos ingresar su path. 
¿Es bueno que las clases del frontend reciban un parámetro ```ruta_imagen``` y en el archivo ```main.py``` agregamos el path relativo desde la carpeta de la tarea? Me surge la duda porque la carpeta sprites la tengo dentro de la carpeta frontend. ¿Cuál será el orden de carpetas que van a usar? O cómo puedo evitar problemas con esto?

**Comment by knight-who-say-ni** [comment]
Holaa @kalarconvl !!
Lo más probable es que el ayudante que te corrija ponga las carpetas de sprites y songs en tu carpeta principal. Sin embargo, si las prefieres tener en otra parte, hay 0 problema, mientras lo menciones en el readme. (Y si se te olvida mencionarle, una lectura del codigo le va a decir al ayudante donde debe estar, pero mejor asegurarse).

En cuanto a como deben ir parametrizadas, la verdad es que lo puedes hacer como mas te acomode: si quieres puedes tener el path relativo en parametros, si quieres puedes tener solo el nombre de la imagen y crear el path entre modulo, etc... Mientras funcione (y este parametrizado) todo ok 👌.

Espero haberte aclarado las dudas, exito programando!!

**Comment by kalarconvl** [comment]
@knight-who-say-ni Buenísimo muchaaas gracias!! 😃
