### ISSUE TITLE
Google Sheets API "Discovery"

### ISSUE THREAD

**Issue by nlvargas** [IIC2233/Syllabus#790]
Hola, al seguir los pasos del quickstart de Google Sheets me funciona todo bien si ejecuto el programa desde la consola. Pero si ejecuto desde Pycharm el código, me sale que no detecta la carpeta Discover en el móldulo apiclient. 

¿Qué puede estar pasando? 

![screen shot 2017-11-23 at 6 03 34 pm](https://user-images.githubusercontent.com/16806150/33188469-c9d775c0-d078-11e7-85c4-d2a9c6469180.png)

**Comment by ifcarrera** [comment]
¿Puedes subir una foto del error que te tira cuando lo ejecutas, por favor?
Saludos

**Comment by nlvargas** [comment]
![screen shot 2017-11-23 at 6 19 38 pm](https://user-images.githubusercontent.com/16806150/33188726-cc50f248-d07a-11e7-84bd-e38513ae1008.png)

**Comment by ifcarrera** [comment]
Hmm... solo para descartar, ejecutaste el comando:

`sudo pip install --upgrade google-api-python-client` ?
o prueba también con 
`sudo pip3 install --upgrade google-api-python-client`.

Y tienes configurado el proyecto para que se ejecute con Python 3.6 verdad?

Saludos

**Comment by nlvargas** [comment]
Cambié el interprete a 3.6.3 y me funcionó. Estaba en 3.6.2 (que raro).
Muchas gracias

**Comment by ifcarrera** [comment]
De nada :D
