### ISSUE TITLE
Problema con objetos superpuestos en tablero

### ISSUE THREAD

**Issue by sofiuni** [IIC2233/syllabus#791]
Ayer subi mis avances pero tuve un problema. Al correr el programa y ir al mapa los objetos cuyas posiciones x e y son las entregadas en el archivo se superponen en vez de ir a las direcciones indicadas. Por que pasa esto?

**Comment by fdoflorenzano** [comment]
Hola @sofiuni,

No me queda muy claro cual es el problema. ¿Podrías explicar un poco más lo que ocurre y lo que esperas que pase? ¿Antes funcionaba y ya no? ¿Qué cambió? Puedes adjuntar una foto de lo que te resulta en la ventana de mapa si quieres también.

Saludos.

**Comment by sofiuni** [comment]
Quedan unos sprites sobre otros
![image](https://user-images.githubusercontent.com/48592386/82578921-0f585d80-9b5b-11ea-9e15-68e6dd5b162c.png)

**Comment by fdoflorenzano** [comment]
Hola @sofiuni,

Es porque los elementos en las ventanas se agregan en cierto orden, entonces siempre se colocan unos sobre otros. Si las dimensiones de los objetos que cargas y las posiciones leídas son tales, puede pasar lo que muestras. 

Como se menciona en otras _issues_, el tema de los tamaños, proporciones y posiciones quedan a criterio suyo para que haga sentido en los marcos que ustedes definan. En las issues #770 #771 hablan de eso.

Espero eso responda tu duda,
Saludos.
