### ISSUE TITLE
Problema al tratar de settear más de un Layout

### ISSUE THREAD

**Issue by Gsalinas1506** [IIC2233/syllabus#791]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola. Tratando de modelar la parte del ranking, ocurre que cuando intento acceder por primera vez a esta pestaña desde la pantalla inicial todo va normal, y al volver también todo Ok. Sin embargo que cuando quiero acceder otra vez a la pestaña de ranking, se buguea esa pestaña y aparece en consola este error:

`QWidget::setLayout: Attempting to set QLayout "" on VentanaRanking "", which already has a layout`

y así es como se me mi pantalla luego de intentar acceder por segunda vez al ranking. El botón de volver a la pantalla de inicio no me trae problemas...

![image](https://user-images.githubusercontent.com/68198662/97069837-4d91f700-15a9-11eb-93e0-aad1b34e64f6.png)

¿Que puede ser?
Me tinca que puede ser un error intentado settear más de un Layout... ¿Es posible 'unsettear' un Layout?

**Comment by aljara97** [comment]
Hola, al parecer el problema es que al momento de actualizar el ranking insertas nuevamente un layout en la ventana y este hace conflicto con el existente. Hay varias cosas que podrías, la primera es buscar una forma de eliminar el layout que existe o simplemente instanciarlo anteriormente en el init de la ventana y solamente encargarte de actualizar el contenido de este cuando quieras mostrar el ranking.

Espero haberte ayudado, cualquier duda quedo pendiente

**Comment by Gsalinas1506** [comment]
Intenté hacer lo que me dijiste de instanciar el Layout en el init, y efectivamente, ya no ocurre el problema de antes. Sin embargo, ahora siempre que ingreso a la ventana de ranking el layout se queda con los valores anteriores también, sin eliminarlos, haciendo que se acumulen:
![image](https://user-images.githubusercontent.com/68198662/97087469-e4d66900-1600-11eb-80b5-a1238dc7dcca.png)

De esto deduzco que hay que hacer una de dos: 1) Eliminar el Widget o reiniciarlo de alguna manera para que siempre tome datos nuevos. 2) Borrar los labels que contienen los puntajes que están metidos en este Layout... Pero como lo puedo hacer?

Como puedo hacer para eliminar el Layout existente? o para borrar los elementos que contiene? Lo he intentado con `layout.removeWidget()` pero se me superponen los elementos del Layout...

(La forma en la que agrego los Qlabel al Layout es instanciarlos y luego agregarlos, pero todos tienen el mismo nombre (lo hago con un `for` ))

**Comment by aljara97** [comment]
Si puedes darte cuenta, siempre tendrás 5 labels que representen los 5 mejores puntajes. Por tanto, no sería necesario que los elimines, ya que, puedes de alguna otra forma tendrás que volver a instanciarlos cuando quieras abrir nuevamente el ranking y no sería algo eficiente en términos de modelación. 

Yo te aconsejo que busques una forma de actualizar el contenido del label cuando muestras un ranking con el método `setText("some text")` de QLabel o lo otro es que puedes utilizar el método `setVisible(bool)` en caso de que quieras que los labels no se muestren en la pantalla.
