### ISSUE TITLE
Nombre de la Sheet

### ISSUE THREAD

**Issue by mmsaavedra1** [IIC2233/Syllabus#791]
Hola para efectos de lectura podemos asumir que las hojas siempre tendrán un nombre establecido. 
Ej Sheet 1 es la única hoja que contendrá los valores

Saludos!

**Comment by ifcarrera** [comment]
Sí, puedes asumirlo. Aunque si quieres hacer más dinámico tu programa, podrías poner un input y que el usuario ingrese el nombre de la Hoja. 
Saludos
