### ISSUE TITLE
Crear una clase sin sobreescribir __init__

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#792]
Siempre hemos visto (incluso en intro) clases en donde siempre se comienza sobreescribiendo el __init__, mi consulta es, está mal visto crear clases donde no se haga overwrite al init? (una clase así podría servir por ejemplo solamente para alojar ciertas funciones, donde no necesariamente guarde variables, o si las guarda, podrían ser guardadas simplemente como variables de clase)

**Comment by pabloist** [comment]
Hola buenas!

No pasa nada con no hacer override del método __init__,  en general en los cursos IIC1103 y IIC2233 siempre se realiza debido a que nuestras clases tienen variables que definen y representan a la instancia de clase.

De todos modos y entendiendo que el objetivo de una clase es representar un objeto tanto en sus variables como en sus métodos, te recomiendo simplemente crear funciones en una librería y llamarlas desde ahí (si la clase no tiene variables de clase, no tiene mucho sentido definirla). En caso de que necesites almacenar variables de clase, no hay problema con no definir el __init__.

Saludos!

**Comment by fernandosmither** [comment]
> Hola buenas!
> 
> No pasa nada con no hacer override del método **init**, en general en los cursos IIC1103 y IIC2233 siempre se realiza debido a que nuestras clases tienen variables que definen y representan a la instancia de clase.
> 
> De todos modos y entendiendo que el objetivo de una clase es representar un objeto tanto en sus variables como en sus métodos, te recomiendo simplemente crear funciones en una librería y llamarlas desde ahí (si la clase no tiene variables de clase, no tiene mucho sentido definirla). En caso de que necesites almacenar variables de clase, no hay problema con no definir el **init**.
> 
> Saludos!

Buenísima! Gracias.
