### ISSUE TITLE
Cantidad de tweets a analizar

### ISSUE THREAD

**Issue by savelozo** [IIC2233/Syllabus#792]
Al generar un request a Twitter solo puedo obtener, como máximo, 100 tweets desde una ubicación. Basta realizar el análisis de TT con esos 100 datos?

**Comment by ifcarrera** [comment]
Sí, deben realizarlos con los que te retorne la consulta por defecto. 
Saludos

**Comment by savelozo** [comment]
O sea, por defecto son 15, pero lo puedo setear al máximo (100). Muchas gracias!
