### ISSUE TITLE
Credenciales GMAIL

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#792]
Hola, hay muchas opciones y no sé qué necesito elegir (ni qué es cada cosa).
Pueden hacer un paso a paso de qué opciones marcar para las credenciales que necesitamos para la T07.

Gracias.

**Comment by rihanuch** [comment]
¡Hola @jmweilandt !
 
Parte de la idea de esta tarea es que aprendan a utilizar documentacion externa. Por lo mismo te recomiendo ir a la de la api, ahi todo esta mas claro 📑

Adicionalmente, recuerda que casi todos los pasos se encuentran en las imágenes del enunciado. No debería haber complicaciones si sigues esos pasos

¡Saludos y suerte en los exámenes! 🍀
