### ISSUE TITLE
KeyPressEvent en dos ventanas distintas (o Widgets)

### ISSUE THREAD

**Issue by jorge-ovalle** [IIC2233/syllabus#792]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

[Describe tu duda de manera detallada, explicando los contenidos en cuestión y ojalá colocando código o un caso de uso de ejemplo]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by jorge-ovalle** [comment]
Considerar un caso hipotético en el que tenga dos ventanas que reaccionan cuando se presiona el teclado, es decir, se corra una función en ambas cuando se presiona una tecla en específico. Si escondo una de las ventanas con el método hide() y apreto la tecla  en cuestión, ¿la ventana escondida seguirá pendiente a dicha señal y actuará conforme? Mi pregunta va si apretar el teclado es siempre una señal única y si presiono una tecla todas las ventanas creadas (incluso las escondidas) que tengan funciones que reaccionen al teclado se verán activadas.

**Comment by igbasly** [comment]
Hola @jorge-ovalle :v:

Lamento la demora en responder, primero hay que entender que la señal de tecla presionada o click del mouse son únicas, es decir se emiten una sola vez y hacia la ventana que esté activa en tu computador. Digamos que esto es algo que lo maneja el sistema mismo.
Ahora, bajo esta lógica puedes tener dos ventanas desplegadas y visibles, pero **máximo una** estará "activa" al usuario, ya que puede ocurrir que pese a que se ven las ventanas, estés trabajando en otra aplicación. De esta forma, la señal de tecla presionada o  cualquier otro input de ese estilo llegará únicamente a la ventana activa y será manejada por su respectiva función.
:bulb: Pero esto no evita que el ingenio de los programadores no actúe para intentar hacerlo diferente, ya que por ejemplo, podrías tener señales internas que se encargues de que cuando un evento de esta clase llegue, se replique a todas las ventanas de tu programa.

Espero que esto aclare tu duda, cualquier cosa quedo atento.
Mucho éxito con el estudio!! :muscle:
