### ISSUE TITLE
Error al instanciar el Ui desde Qt Designer

### ISSUE THREAD

**Issue by kipasten** [IIC2233/syllabus#792]
al hacer el tipico setupUi() me aparece este error
`TypeError: argument 1 has unexpected type 'QPushButton'` 
Después de buscar mucho en internet no encontre nada, para contexto, hice un QWidget en Qt Designer para hacer una ventana de inicio tal como habian hecho en la ayudantía, y el __init__ del super y el set up estan iguales pero no me funciona :(

**Comment by furcelay** [comment]
No soy ayudante, pero me pasó algo similar al correr el programa en un enviroment que no tenía instalado `pyqt5-tools`, pruba si te resulta instalándolo con `pip3 install pyqt5-tools`.

**Comment by kipasten** [comment]
Si lo tengo instalado... 
Como ejemplo tengo escrito esto en el archivo 
`nombre_ronda, clase_ronda = uic.loadUiType(RUTA['Ventana_inicial'])

class Inicio(nombre_ronda, clase_ronda):

    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.show()`
en el Widget tengo 3 botones, el logo (Qlabel) y un mensaje(Qlabel) pero me lanza el error antes mencinado

**Comment by fdoflorenzano** [comment]
Hola @kipasten,

Estuve un buen rato mirando, ya que me tiraba el mismo error que a ti. El problema es que asignaste el mismo nombre para dos elementos distintos en Qt Designer. Específicamente, llamaste tanto a un botón como `Configuracion`, y en la conexión pusiste que se accionara `Configuracion()`, ya que defines un método con ese mismo nombre. 

Cambié en el `.ui` alguno de estos nombres y empezó a correr. Intuyo `setupUI` va definiendo en cascada cada elemento con las definiciones que se hacen, y al tener dos elementos con el mismo nombre, intentó conectar el clic de un botón con un botón, no con un método, y por eso tu error.

Te sugiero editar en Designer los nombres de los elementos de tal forma que no hayan colisiones.

Saludos.

**Comment by kipasten** [comment]
Muchas gracias!!!!  🙇 en verdad era todo lo que había que cambiar, seré mas cuidadoso en el futuro. 🤔
