### ISSUE TITLE
Archivo de texto que se debe crear

### ISSUE THREAD

**Issue by BeaGaete** [IIC2233/Syllabus#793]
En la página 6 del enunciado, parte 6.4 dice que se debe crear un archivo de texto para guardar los resultados del logging. ¿Puede ser un archivo de texto simulado con StringIO o tiene que ser un .txt?

**Comment by TomasSalvadores** [comment]
Un .txt
Averigua sobre las herramientas del modulo logging! Hacer ese txt es mas simple de lo que parece.
Suerte!
