### ISSUE TITLE
Se borran las imagenes en Qt Designer - T02

### ISSUE THREAD

**Issue by ignacioarteaga99** [IIC2233/syllabus#793]
Hola, tengo una duda. Cuando cierro las ventanas en el editor de Qt, al volver a abrirlo se me borran las imágenes. Continúan estando los labels y las rutas a las imágenes, sin embargo, estas no se ven.
¿A qué se puede deber?

**Comment by JuaniAndres** [comment]
Hola @ignacioarteaga99 
Por casualidad entre que cerraste y abriste nuevamente tu ventana cambiaste la ubicación del archivo Ui o tus imágenes? Porque la razón más probable de que no te están apareciendo es porque el path a las imágenes cambio o no es el correcto. Una última pregunta las imágenes no te aparecen al cargar la ventana y en QT Designer?.
