### ISSUE TITLE
¿Qué versión de mi tarea recolectaron?

### ISSUE THREAD

**Issue by llloyola** [IIC2233/Syllabus#793]
Hola! ¿Hay alguna forma de saber cuál versión de mi tarea tienen ustedes para corregir? Pues fui haciendo unos cuantos commits y push seguidos y no sé con cuál versión de mi tarea se habrán quedado. Me gustaría (y creo que necesito) saber cuál es porque sospecho que podría tener algún error que necesito especificar en el README.

Gracias de antemano.

**Comment by rihanuch** [comment]
¡Hola @llloyola !

Puedes revisar eso en tus issues, ahi se encuentra el commit a revisar

Saludos
