### ISSUE TITLE
Interacción mesero/a con chef/clientes

### ISSUE THREAD

**Issue by CataSudo** [IIC2233/syllabus#793]
Hola, me encuentro perdida en como lograr hacer que el mesero interactue con el chef/cliente, ¿Se usan QThreads? O lo estoy pensando mal.

**Comment by jbulness** [comment]
Hola @CataSudo ,

Para la interacción entre el/la mesero/a debes implementar lo pedido en la sección 5.3.2 del enunciado de la tarea, que corresponde a __colisiones especiales__. Una colisión consiste en que se "toquen" las imágenes correspondientes a las entidades implicadas en cada caso y esto debe gatillar un evento si se cumplen ciertas condiciones. Al pie de página se hace mención a un método (`intersects`) de la clase `QRect` que te podría ayudar.
