### ISSUE TITLE
Canción suena entrecortada al implementar flechas con threads

### ISSUE THREAD

**Issue by denisseleiva** [IIC2233/syllabus#794]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola!! Implementé las canciones con QSound y todo funcionaba bien hasta que comencé a hacer las flechas con QThreads y ahora al tener la canción y las flechas funcionando al mismo tiempo, la canción se empieza a entrecortar. Creo que puede ser porque tengo **muchas** cosas corriendo al mismo tiempo. ¿Será un problema para la corrección?, ¿Hay manera de arreglarlo?

Gracias!

**Comment by furcelay** [comment]
Hola @denisseleiva !
En general tu computador no debería ser un problema poder correr las flechas y la música a la vez, hoy en día podemos ejecutar una enorme cantidad de tareas simultáneamente y todas de forma fluida. Probablemente hay un problema con uno o más `QThreads` que impide que la música se reproduzca de manera correcta. Para lograrlo `QSound` requiere acceder muchas veces al procesador y si hay un thread que ocupe un exceso de tiempo en el CPU se escuchará entrecortada. Revisa si hay un `QThread` que se ejecute de forma continua (dentro de un loop `while` por ejemplo) y con un tiempo de `sleep` muy corto (más aún si no tiene `sleep`!! :persevere:) y extiende su `sleep` (nota: el `while` no es el problema, solo que si hay `while` debe haber `sleep`). 

Si eso no soluciona tu problema has un *push* de tu repositorio y haz un comentario por aquí para ver qué puede estar causando el error. 
Saludos! :smile:

**Comment by denisseleiva** [comment]
Holaaa @furcelay Le acumenté el tiempo a un thread que tenía poco sleep, pero ahora me surgió otro problema :( no sé por qué de repente los botones me dejan de funcionar, como que se convierten en labels y no son "apretables".  Hice push a mi repositorio recién, no sé si me podrías ayudar :c

**Comment by furcelay** [comment]
No estoy muy seguro de a qué te refieres, al correr tu tarea me da un error porque estás intentando usar el `setPlaceholderText` en instancias de `QComboBox` que no poseen ese método, si comento las líneas correspondientes todo corre bien. Si te refieres a que los botones no son presionables ésto es por las condiciones impones (que haya una dificultad y una canción, lo que está muy bien porque es parte de lo que se exige en el enunciado), si escojo la canción y la dificultad los botones se habilitan.

**Comment by denisseleiva** [comment]
jajajaj ohh no sé me pasa algo muy extraño a veces como que no puedo apretar los botones, pero si te funcionó quizás sea mi compu o algo (debe estar agotado de tantas veces que he corrido el código). Gracias por avisarme del error!! Y arreglaré lo del sleep.

Muchas gracias! Te pasasteee @furcelay

**Comment by denisseleiva** [comment]
Holaa @furcelay quedé dando vueltas con lo que me mencionaste del QComboBox y el método setPlaceholdertext y busqué en la documentación, y me aparece como que es un método válido 🤔 y de hecho a mí no me tira error al correr el código. ¿Será que te tira error porque quizás tienes una versión más antigua de pyqt o algo así? jaajajaj

<img width="1296" alt="Captura de pantalla 2020-10-26 a la(s) 10 51 14" src="https://user-images.githubusercontent.com/69520522/97180922-7537b980-1779-11eb-852a-40dfcb81d7c9.png">

**Comment by furcelay** [comment]
Hola @denisseleiva , tienes toda la razón!! tenía la versión 5.14 y fue introducido en la 5.15 😣 , perdón por el inconveniente 😅
