### ISSUE TITLE
Error 34 Twitter

### ISSUE THREAD

**Issue by mmsaavedra1** [IIC2233/Syllabus#794]
Hola!

He estado provando el trending Topic, cuando llego a la obtención del id del lugar según sus coordenadas va todo bien, pero cuando entrego dicho id para obtener el trending Topic del lugar se me cae el programa. He buscado y buscado y no encuentro nada): A que se debe este error?

Saludos
![captura de pantalla 2017-11-24 a la s 00 56 58](https://user-images.githubusercontent.com/23617087/33194961-6e659c64-d0b2-11e7-9f0e-e48127170a58.png)

**Comment by ifcarrera** [comment]
Hola!
Le estás entregando mal el ID, por eso no reconoce qué lugar le estás consultando. Debes averiguar por qué no le está llegando el parámetro ID a la solicitud. 

Saludos

**Comment by mmsaavedra1** [comment]
@ifcarrera Me resulta extraño, ya que la librería dice que se le pasa el parámetro id. Siguiendo eso:

_data = {"id": *id obtenido en el paso anterior*}

https://developer.twitter.com/en/docs/trends/trends-for-location/api-reference/get-trends-place

):

**Comment by ifcarrera** [comment]
Mmm... al parecer lo estás haciendo bien. Quizás no estás consiguiendo bien el ID en el paso anterior. Intenta ver si funciona poniéndole un ID específico manualmente (busca alguno en la documentación y se lo pones ahí en el "id").

**Comment by mmsaavedra1** [comment]
Acabo de probar poniendo id=1 (como en la documentación) y funciona. Para le paso anterior ocupe /geo/search. Por diccionario me devuelve dos id, probé con ambos y nada):

https://developer.twitter.com/en/docs/geo/places-near-location/api-reference/get-geo-search

**Comment by ifcarrera** [comment]
Ah ya, efectivamente estás buscando el id erróneo... leíste #776 ?

**Comment by mmsaavedra1** [comment]
Mala mía, me faltó un paso. Gracias!

**Comment by ifcarrera** [comment]
😅
