### ISSUE TITLE
Probabilidad aparición cliente

### ISSUE THREAD

**Issue by furcelay** [IIC2233/syllabus#794]
Hola!
¿Debo considerar que la llegada de un **cliente relajado** y un **cliente apurado** son dos **eventos independientes** (`if` `if`)? 
Es decir, cada `LLEGADA_CLIENTES` podría llegar un cliente de un tipo, dos clientes de tipos distintos o bien ninguno.

¿O considero que **si no llega uno entonces llega el otro** (`if` `else`)? 
Es decir, siempre llega un cliente cada `LLEGADA_CLIENTES` de alguno de los dos tipos hasta completar el número de clientes de la ronda.

Deduzco que es el segundo caso porque sino no tendría mucho sentido que las probabilidades sumen 1, pero no estoy del todo seguro...

**Comment by danckoo1** [comment]
hola! efectivamente al leer el enunciado quedo un tanto ambiguo, sin embargo tu intuición es correcta. Se espera que cada `LLEGADA_CLIENTES` si o si llegue un cliente, y mediante las probabilidades veas de que tipo será, por lo que modelarlo con un (`if` `else`) estaría correcto :)

**Comment by furcelay** [comment]
Super!
Muchas gracias!!

**Comment by mmunoz12** [comment]
> hola! efectivamente al leer el enunciado quedo un tanto ambiguo, sin embargo tu intuición es correcta. Se espera que cada `LLEGADA_CLIENTES` si o si llegue un cliente, y mediante las probabilidades veas de que tipo será, por lo que modelarlo con un (`if` `else`) estaría correcto :)

Hola! perdon que llegue tarde a esta issue jaja, pero entonces prob_relajado y prob_apurado siempre sumaran 1? solo es para asegurarme :)

**Comment by dlmed** [comment]
> > hola! efectivamente al leer el enunciado quedo un tanto ambiguo, sin embargo tu intuición es correcta. Se espera que cada `LLEGADA_CLIENTES` si o si llegue un cliente, y mediante las probabilidades veas de que tipo será, por lo que modelarlo con un (`if` `else`) estaría correcto :)
> 
> Hola! perdon que llegue tarde a esta issue jaja, pero entonces prob_relajado y prob_apurado siempre sumaran 1? solo es para asegurarme :)

sip, eso dice en el enunciado
