### ISSUE TITLE
Obtención de TT

### ISSUE THREAD

**Issue by savelozo** [IIC2233/Syllabus#795]
Me surgió una duda leyendo algunas issues.

En la parte de obtención de TT, lo que debemos es crearlos a partir de nuestra muestra de tweets obtenidas desde el request (y todo el proceso de conteo de hashtags posteriores) o debemos hacer un request a Twitter que me devuelva los TT del momento en esa zona?

**Comment by ifcarrera** [comment]
Es lo segundo que mencionas, hacer la request y analizar los TT que te retorne. Saludos
