### ISSUE TITLE
Problema con ejecución de ventana QtDesigner

### ISSUE THREAD

**Issue by rosariodominguezm** [IIC2233/syllabus#795]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola!! Cuando copio los códigos desde el jupyter de la semana 10 a mi vscode, la parte 3 (QtDesigner), me corre bien y se abre la ventana, pero cuando tengo que interactuar al apretar el botón no ocurre nada y solo funciona si es que clickeo cualquier otra cosa fuera de la ventana.
Por ejemplo, el de fideos o pizza, pongo el botón "ver" y no aparece nada, solamente aparece si es que clickeo cualquier otra cosa fuera de la ventana y ahí me aparece "Preferencia:....".
 No sé que puede ser.

Gracias!

**Comment by aaossa** [comment]
Hola @rosariodominguezm , disculpa lo tarde, ¿pudiste solucionar este problema o sigue funcionando así? Si lo solucionaste, ¿cómo lo hiciste? ¡Gracias ✨!

**Comment by rosariodominguezm** [comment]
Holaaa!!! Me atrasó haarto pero sí! Lo arreglé haciendo como 4 ventanas iguales y de repente funcionó. 
Lo que sí, me falto un link en el readme, que hago?? De un codigo de internet.

Saludos

Enviado desde mi iPhone

**Comment by aaossa** [comment]
Hola @rosariodominguezm , en ese caso basta con que lo agregues en tu README  👌 No hay problema con que lo agregues ahora porque solo es una referencia, y nos sirve más para el análisis posterior que para la corrección en sí 🔍

**Comment by rosariodominguezm** [comment]
Gracias profesor! Ya lo subí!

Enviado desde mi iPhone
