### ISSUE TITLE
Labels más grande de lo necesario

### ISSUE THREAD

**Issue by MINGOD24** [IIC2233/syllabus#795]
Hola, 

![image](https://user-images.githubusercontent.com/62083817/82588889-65340200-9b69-11ea-94fd-a682a4ae1fd3.png)

Como se ve en la foto, cuando me intento de mover en esa posicion a la izquierda no me lo permite (me imagino porque el label es mas grande que la foto). Como puedo hacer que el label quede del mismo tamaño que la foto?

**Comment by Francisco5674** [comment]
puedes usar .scaled() a la hora de crear el Pixmap, y los parametros de scaled deben ser los mismos que los de la geometría del label, de esa forma al menos yo me aseguro de que los labels y los pixmaps sean exactamente iguales

**Comment by MINGOD24** [comment]
@Francisco5674 Muchas gracias! ahi me funciono!
