### ISSUE TITLE
gmail API, to-sender

### ISSUE THREAD

**Issue by ValentinaAlvarezG** [IIC2233/Syllabus#795]
Para la tarea 7, no me queda muy claro como tiene que funcionar el mandar el mail al usuario. Por lo que he podido encontrar logré mandarme un mail a través de python, pero  desde una cuenta especifica a otra. Para efectos de la tarea está bien que le mande los reportes del tiempo pedidos desde por ejemplo mi mail uc? o en verdad se hace de otra manera? o debería crear otro mail? :c

**Comment by ptflores1** [comment]
Hola !
Esta bien que se mande desde tu correo, cuando descargas el archivo`client_secret.json`, creas las credenciales y te pide autorización estas haciendo que se manden desde tu correo porque con ese correo creaste el proyecto, a la hora de revisar nosotros cambiaremos el archivo `client_secret.json` por uno nuestro. Ojalá que tu tarea lea siempre las credenciales para que asi cuando nosotros pongamos las nuestras, tambien funcione.
Saludos !

**Comment by jmwielandt** [comment]
@ptflores1 en relación a eso, cómo va a funcionar lo de las credenciales de openweather? un json? credenciales.py? Van a poner las suyas cuando sea el momento?
Gracias.
