### ISSUE TITLE
Relacion nombre-correo

### ISSUE THREAD

**Issue by ValentinaAlvarezG** [IIC2233/Syllabus#796]
Por lo que entiendo de la tarea 7 debería guardar la información de un usuario más que nada para guardar sus configuraciones. Como hay que pedir nombre y correo al usuario cuando inicie sesión, se debe verificar que el nombre corresponda al correo? Es decir, si la primera vez que se mete hace la relación correo@algo.cl y nombre Juan, si se mete de nuevo y pone otro nombre con ese mismo correo debería tirar algún error? o da lo mismo?

**Comment by ptflores1** [comment]
Hola !
Creo que te respondimos en la sala de ayuda pero lo respondo igual para que todos lo vean. No deberia haber un error, una vez que se cierra la sesión el programa se "olvida de todo", no es necesario que haya persistencia de datos.
Saludos !

**Comment by kenzoak** [comment]
Entonces ninguna configuracion el usuario, o la información que pida que se le mande se guarda? Es decir, no se guarda nada entre ejecuciones del programa?
