### ISSUE TITLE
Entrega Actividad Formativa 05 y Tarea 02

### ISSUE THREAD

**Issue by Francisco5674** [IIC2233/syllabus#796]
Hola, sorry lo chato quizá esta en un mail o algo, pero no lo encuentro, estoy un poco perdido con la entrega de la actividad formativa 5, ¿revisarán un commit de la tarea como actividad formativa?, o ¿acaso tengo que entregarla aparte?, estoy perdido con eso.

**Comment by fdoflorenzano** [comment]
Hola @Francisco5674,

Sí, en la misma entrega de la tarea 2 se considerará como la entrega de actividad formativa 5. No es necesario entreguen algo aparte. Si realizan la tarea 2 e implementan los requisitos de actividad formativa 5, estás listo, no es necesario separarlo del resto.

Tu segunda duda debería ir en otra *issue*, como se estipula en las reglas del foro.

Saludos.

**Comment by Francisco5674** [comment]
Tienes razón, se me olvido el detalle de dudas diferentes en issus diferentes.
Muchas gracias!
