### ISSUE TITLE
Combinación de pasos y flecha dorada

### ISSUE THREAD

**Issue by denisseleiva** [IIC2233/syllabus#796]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (htps://github.com/IIC2233/syllabus/issues/699)
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola!! Tengo una duda con la combinación de pasos, ya que yo podría setear que empiecen a caer por ejemplo dos flechas a la vez, pero qué pasaría si se lanza una flecha dorada y cae en la zona de captura justo al mismo tiempo que mi combinación de dos pasos que había seteado, ¿En ese caso la combinación sería de tres pasos? ¿O la combinación de pasos no incluye las flechas doradas? Pregunto porque como tiene velocidad distinta, me complica manejar ese tipo de flechas con los pasos combinados. 

Gracias!

**Comment by JuaniAndres** [comment]
Hola @denisseleiva 
Como esto no está definido en el enunciado queda a tu criterio como abordarlo. Puedes considerar la flecha dorada como un paso a parte o también puedes asumir que las tres flechas forman un solo paso combinado si se capturan al mismo tiempo. Lo importante si es que dejes anotada tu decisión en el readme.
Quedo atento si tienes más dudas y éxito en la tarea 😄

**Comment by denisseleiva** [comment]
dalee gracias! @JuaniAndres
