### ISSUE TITLE
No puedo implementar keyPressEvent en un widget adentro de otro widget

### ISSUE THREAD

**Issue by diego-ayala-2000** [IIC2233/syllabus#797]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

<img width="1207" alt="Captura de Pantalla 2020-10-24 a la(s) 13 25 15" src="https://user-images.githubusercontent.com/69765490/97086869-5c55c980-15fc-11eb-8cbf-c972e91ccffc.png">

En la foto se ve como es mi tares, lo que pasa es que al implementar un key press event en el widget de la zona de ritmo no pasa nada, no se ejecuta. En el avance de mi tarea funcionaba perfecto. A que se podria deber?. 
De antemano gracias por la ayuda .

**Comment by manearaya** [comment]
Hola @diego-ayala-2000!

Creo que, como tienes más de un Widget, el 'foco' de los inputs están en otro widget y por esto no responde el widget de la zona de ritmo. 

Si ese es el problema, debería funcionar apretar la zona de ritmo para cambiar el foco, y que esta reconozca cuando apretas una tecla.

Ojalá te haya ayudado! Quedo atenta cualquier cosa.

**Comment by diego-ayala-2000** [comment]
Ya lo pude implementar, gracias
