### ISSUE TITLE
Sala de ayuda

### ISSUE THREAD

**Issue by clementeross** [IIC2233/Syllabus#797]
Hola, cómo quedó el horario de sala de ayuda? Martes o miércoles a las 10:30? 
Gracias!!

**Comment by Hernan4444** [comment]
Martes (y es a las 11:30 según el primer aviso)
Saludos ✌️

**Comment by jmwielandt** [comment]
@Hernan4444 no puedo ir :/ ¿Pueden abrir una issue con las cosas importantes que mencionen y sean un criterio de corrección, cosas que no podamos presuponer y demás? 😞
