### ISSUE TITLE
Ciudades - verificar o no

### ISSUE THREAD

**Issue by B-Dominguez** [IIC2233/Syllabus#797]
Holaa,
Debemos verificar si las direcciones encontradas son efectivamente 'Locallity'? O podemos simplemente quedarnos con si existe o no la dirección buscada?
Graciaaas

**Comment by ifcarrera** [comment]
Deben manejar las respuestas de la API, de tal manera que si una ubicación no existe, su programa le haga entender eso al usuario. 
Saludos
