### ISSUE TITLE
Auto-ajuste de ventanas

### ISSUE THREAD

**Issue by Francisco5674** [IIC2233/syllabus#797]
Hola! Ahora si, sobre la otra duda, para la Tarea 2, ¿es necesario que los sabelas ajusten su definición a la pantalla, al igual que lo hace un layout? por ejemplo, en mi juego del DCCafé, si tu quieres agrandar la pestaña, solo se escalaran con la pestaña los elementos de la tienda y la barra de estado, pero no el mapa de juego, ¿este también debe ajustarse o da lo mismo mientras sea cómodo jugar en ese tamaño?

**Comment by kadroguett** [comment]
Hola @Francisco5674 
Como no se especifica en el enunciado queda a tu criterio hacerlo o no ajustable al agrandar la ventana, recuerda indicar en tu README si lo implementaste o no.

**Comment by Francisco5674** [comment]
Bkn, muchas gracias por aclararlo.

**Comment by kadroguett** [comment]
De nada, éxito en tu tarea!!
