### ISSUE TITLE
Separación cliente - servidor

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#798]
Hola, 
No sé muy bien cómo abordar la relación entre el cliente y el servidor para la validación de inputs y manejo de las configuraciones. 

**Opción 1**
  - cliente valida los inputs y maneja las configuraciones, luego cuando el usuario quiera que le envíen el reporte, manda el paquete completo al servidor (nombre, correo, localizaciones y configuración) para que el servidor haga lo de las apis.

**Opción 2**
  - cliente manda TODO al servidor, quien lo procesa, guarda las configuraciones ad infinitum de todos los usuarios que se han conectado y procesa los inputs del cliente y responde según el caso.

De momento estoy abordándolo según la opción 1 porque es más fácil y una lección que aprendí de la tarea 6 es evitar la comunicación cliente - servidor tanto como sea posible.

Gracias.

**Comment by emeiese** [comment]
Hola! Yo igual estoy teniendo problemas para entender cómo modelar la separación cliente-servidor, asi que me cuelgo de esta issue.
Yo modelaría las cosas como sigue (corrijanme si estoy mal ajaja)

- **Una interfaz** (en este caso, esta correspondería al 'cliente' al que se refieren en el enunciado, pero también contiene la información de la interfaz. Dentro de esta es donde se chequean que los inputs estén correctos. Si es que lo están, se comunica con:
- **El servidor**: Este *es* la api (tiene nombre Servidor, porque así es como me lo imagino). La interfaz es donde se ejecutan los requests en base a los inputs de la misma, y aquí es donde llegan estas requests. A su vez, esta api pide lo correspondiente en las apis de Gmail y OpenWeather. 

Hago la pregunta de si esta estructura está bien porque para la tarea 6 teníamos un cliente y un servidor distintos, en el sentido de que ambos tenían métodos para enviar y recibir. En este caso, el cliente 'pide' mediante _requests_ lo que necesita, y no va mandando por chunks de bytes ni nada de eso.

Estoy un poco confundida, y no pude asistir a la sala de ayuda por tener una evaluación. Así que también agradecería mucho si pueden subirse un resumen de lo conversado durante la sala de ayuda :cry: 
Gracias!

**Comment by jmwielandt** [comment]
@rihanuch ahora que lo pienso, viendo que sockets no está en las librerías permitidas, a qué se refieren exactamente con que "el servidor provee una api" en el enunciado?
El servidor **es** la api o deben ser entidades independientes y el servidor y cliente se comunican a través de sockets?

**Comment by rihanuch** [comment]
@emeiese , en general en un modelo cliente servidor siempre ambos tienen métodos para enviar y recibir, la diferencia es la cantidad de información que va para cada lado. Respecto a la estructura, como dije antes, queda a tu criterio. 
Adicionalmente, como dije antes, en la vida real se modela haciendo toda la validacion en el servidor, pero no es necesario para esta tarea. El resto del modelamiento _a primera vista_ esta bien.

@jmwielandt socket es más para tener una conexión directa, por ejemplo, jugar un juego online. El enfoque de esta tareas en el formato recibir y proveer informacion entre apis y clientes actuando como api intermediaria
