### ISSUE TITLE
Cómo importar un archivo.py que está en otro lugar del mismo directorio.

### ISSUE THREAD

**Issue by gaspcr** [IIC2233/syllabus#798]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Estoy parametrizando algunas cosas de mi T02 y me encontré con un problema para importar mi _parametros.py_ en un archivo de mi **frontend**, mi estructura de archivos es la siguiente.

T02
├── backend
│      └── archivo1.py
│       
└── frontend
│      └── archivo2.py
└── main.py
└── parametros.py

En mi caso deseo importar _parametros.py_ en **archivo2.py**, ¿Existe alguna manera de hacerlo?.

- Leí todos las issues que hablan respecto al tema (de que se debe hacer colocando "." según cuántos niveles desde tu archivo deseas retroceder para importar), pero intentando de todo nada me resultó :(, puede ser que no haya entendido correctamente como establecer correctamente los imports en estos casos.

**Comment by JadrinaDA** [comment]
Hola! Debes asegurarte de que estés corriendo tu tarea desde tu carpeta T02. Si la corres desde ahí podrás simplemente hacer import parametros.py porque el path es relativo al directorio desde que se esté ejecutando tu programa, no de donde se encuentre el archivo. Si corres desde T02 y quieres importar el archivo2 en alguna parte ahí tendrías que usar frontend.archivo2.py. Espero que te funcione.

**Comment by gaspcr** [comment]
Estoy corriendo tan solo la parte del frontend (es decir, ejecuto el archivo2.py que se encuentra en T02/frontend, no estoy ejecutando desde el main.py pues solo quería probar que funcionase.

**Comment by JadrinaDA** [comment]
Cuando estas corriendo desde el archivo mismo no puedes hacer un import relativo desde arriba por lo tanto si solo quieres probarlo te recomiendo que muevas temporalmente el archivo parametros.py a la misma carpeta que archivo dos. Tu tarea siempre se va a correr desde el main por lo tanto al momento de corregir si podrás usar imports relativos.

**Comment by gaspcr** [comment]
Oh ya perfecto muchas gracias!
