### ISSUE TITLE
Movimiento QRect y colisión

### ISSUE THREAD

**Issue by milosoria** [IIC2233/syllabus#798]
Hola! Estoy teniendo un problema con las colisiones y el movimiento del mesero. Estoy utilizando:
`not self.l_mesero.rect().intersects(self.chef.rect())`  como condición para que el mesero se mueva, pero la condición se cumple con el mesero y el chef en lados opuestos del mapa (en culaquier posición del mapa sucede lo mismo) . Imprimí los rect y tienen ambos coordenadas (0,0) para los label respectivos y el tamaño es el mismo que el de los labels. No logró encontrar información en la web.
![image](https://user-images.githubusercontent.com/61996784/82591347-34ee6280-9b6d-11ea-989e-89b9aca44d21.png)
Imprimí `self.l_mesero.rect().intersects(self.chef.rect())` para ver si se cumplía y se cumple en todo momento, por lo tanto el mesero no puede moverse.

**Comment by bvasquezm** [comment]
@milosoria,

Creo que ya resolviste tu duda, pero de todas formas te comento que los **QLabel** se mueven de forma independiente a su **QRect**, por lo cual deberás mover tanto el label como su rect. Inicialmente rect() siempre comienza en posición (0,0). Espero que haya quedado claro, cualquier cosa consulta!

**Comment by milosoria** [comment]
Sí, muchas gracias! Ahora estoy teniendo problemas moviendo el rect, estoy utlizando el método setTopleft, pero no mueve al rect. Debiese estar ocupando otro método?

**Comment by bvasquezm** [comment]
No hay una única forma de moverlo, la clase **QRect** tiene más de un método asociado a movimiento. Te recomiendo que revises la [documentación ](https://doc.qt.io/qt-5/qrect.html#)de la clase. Si el problema aún persiste, quizás puedas probar usando el método `geometry()` correspondiente también a la clase **QWidget**, pero no debiese ser el caso. QRect cumple con las funcionalidades. Saludos!

**Comment by lewebe** [comment]
@milosoria Hola! Cómo editaste los colores en tu ventana? está muy bonita 😮

**Comment by milosoria** [comment]
@lewebe Hola! Gracias, la hice con Qtdesigner y cada Widget lo personalice en la parte de stylesheet. Por ejemplo para el color de fondo, usé: `QMainWindow#MainWindow{background-color:rgb(102, 73, 106)}`.

**Comment by lewebe** [comment]
O sea lo hiciste en el mismo Qt Designer?

**Comment by lewebe** [comment]
Otra cosa, respecto a tu duda de Qrect, no se si la solucionaste, pero me di cuenta que usando el método `.geometry()` para un QLabel, este retorna un QRect como el que buscas, con la misma posición y tamaño que tu QLabel sin que tengas que modificar nada. Espero que te sirva

**Comment by milosoria** [comment]
@lewebe Sí, en el mismo qtdesigner, aunque también se puede en python con setstylesheet. Si caché, muchas gracias de todas formas!
