### ISSUE TITLE
Hora solicitud de tweet

### ISSUE THREAD

**Issue by mmsaavedra1** [IIC2233/Syllabus#798]
Cuando obtener un tweet de una ubicación al momento de obtener "created_at" me aparece que la hora de creación es mucho más adelantada a la actual. En la especifica de la imagen el tweet fue creado a las 7:18 pero el dict obtenido no posee esa hora si no que 15:18.

¿A que se debe esto, debo considerar de todas formas el tweet? 😢 
![captura de pantalla 2017-11-24 a la s 12 20 08](https://user-images.githubusercontent.com/23617087/33216651-7898eee6-d113-11e7-949f-8d66ded75179.png)

**Comment by ifcarrera** [comment]
Eso se debe al huso horario, eso está en +0000; pásalo al huso chileno (creo que es -0400) y ahí podrás comparar bien todo. 
Saludos :D

**Comment by mmsaavedra1** [comment]
Gracias! Y en cuanto el tweet mismo, las respuestas que hace el usuario son contadas como tweets? (No soy usuario de twitter :c)

**Comment by ifcarrera** [comment]
Sí, una respuesta a otro tweet sí es un tweet. Saludos :D

**Comment by estebanmb** [comment]
@ifcarrera Hola  aún me queda la duda ¿Le debo restar 3 o 8  hrs al filtrar la fecha del tweet?

Zona horaria de Chile : UTC-03:00

**Comment by ifcarrera** [comment]
Restarle 3, aunque da lo mismo el huso horario que ocupes, 48 horas siguen siendo 48 horas aunque las corras.
