### ISSUE TITLE
Importación archivos ui: error de módulo

### ISSUE THREAD

**Issue by pabloalvarez67** [IIC2233/syllabus#799]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola, los recursos que cree para importarle las imagenes a mi ventana de qtdesigner, como los importo en mi código? ya que importe mi ventana y me tira el siguiente error de módulo:

ModuleNotFoundError: No module named 'fondo_rc'

gracias!!

**Comment by aaossa** [comment]
Hola @pabloalvarez67 , viste la respuesta de #752 ? Parece que tienes el mismo problema que esa *issue*. Si te funciona, avisa por acá mismo y si no vamos viendo posibles soluciones 👌

**Comment by pabloalvarez67** [comment]
> Hola @pabloalvarez67 , viste la respuesta de #752 ? Parece que tienes el mismo problema que esa _issue_. Si te funciona, avisa por acá mismo y si no vamos viendo posibles soluciones 
Buena Antonio muchas gracias! probé ejecutando los comandos y logre crear los 2 archivos.py que necesitaba.
Ahora debo de hacer algo además para poder ejecutar el código? aún no me funciona.

**Comment by aaossa** [comment]
@pabloalvarez67 debería funcionar si tienes todos los archivos juntos donde deberían estar, en la ruta que le indicas desde tu código. El error que te aparece es exactamente el mismo?

**Comment by pabloalvarez67** [comment]
@aaossa Si, el mismo error de módulo

**Comment by aaossa** [comment]
¿Puedes subir tu código para darle una mirada? Otra idea mientras: si es que estás importando el archivo desde un *.py que está en una carpeta, recuerda utilizar una ruta relativa al `main.py` (bueno, al archivo que estés ejecutando), no una relativa al archivo en el que la importas.

**Comment by pabloalvarez67** [comment]
@aaossa creo que tengo un problema de importación, antes no estaba importando nada.
Lo subiré a mi repositorio! leí esta issue también https://github.com/IIC2233/syllabus/issues/706 pero no sirvió para mi caso.

**Comment by gatochico** [comment]
Hola @pabloalvarez67 ! 

Otra idea para evitar tu problema inicial tiene que ver con cómo agregas tu imágen a la ventana en designer. Cuando en designer le añades un pixmap a un label, si presionas en la flechita hacia abajo te deberían salir las siguientes opciones:

![image](https://user-images.githubusercontent.com/37161120/97096102-bcb92b00-163d-11eb-8443-e45b90346888.png)

Es probable que inicialmente agregaste la imagen mediante **Choose resource**, que necesita crear archivos `.qrc` o `rc` para funcionar. Sin embargo, si añades mediante la segunda opción **Choose file**, designer por detrás solo añade una **ruta relativa a la imagen real** para poder incluirla en tu .ui

Abre tu archivo .ui en designer y elimina tu imagen de fondo y vuelvela a agregar con la opción Choose File, y debería funcionar. Si tu programa corre, pero no se ve la imagen, podrías revisar en el archivo .ui que el path relativo a la imagen esté correcto (y lo puedes arreglar a mano en ese archivo si no lo está). De todas formas, si necesitas ayuda con esto último puedes volver a comentar y te explicamos en más detalle.

Saludos y avísanos como te va!

**Comment by pabloalvarez67** [comment]
@gatochico ahi volvi a subirle las imágenes en designer usando qpixmap, no me corre el código todavía, aún me tira error de módulo.
ojalá solucionar esto lo antes posible que estoy parado jajajaja

**Comment by pabloalvarez67** [comment]
@aaossa  @gatochico logré solucionar mi problema, muchas gracias igualmente!

**Comment by YehudaGurovich** [comment]
Hola! Me pasa que en designer al colocar los archivos .ui en distintos directorios no se me muestran las imágenes, y estoy utilizando la opción de Choose File.
