### ISSUE TITLE
Cantidad de clientes

### ISSUE THREAD

**Issue by ibaeza1** [IIC2233/Syllabus#799]
Una duda, se asume que hay solo un cliente a la vez y que no habria que usar threads?

**Comment by ptflores1** [comment]
Hola !

Tiene que soportar mutiples clientes pero no es necesario el uso de threads. Piensa en tu API hecha en Flask como un modulo de funciones que al hacer un *request* (`GET`, `POST`,...) es como si estuvieras usando la funcion de ese modulo. 

Por otro lado, Flask, por si solo, maneja los request como multiples clientes. Si pruebas creando mas clientes que consuman la "API" que esta en el archivo `example.py`, a todos les va a devolver lo mismo `"Hello world"`.  Flask acepta varios clientes pero los va "atendiendo" de a uno por uno.

En resumen, su api debe soportar multiples clientes pero para eso no es necesario hacer nada en especial, no usar thread. Solo tienen que hacer que las "funciones" de su api no vayan almacenando la configuración de un usuario, puesto que eso obliga a que otro usuario pueda alterar dicha configuración.

Saludos!
