### ISSUE TITLE
WOEID twitter

### ISSUE THREAD

**Issue by JPSF** [IIC2233/Syllabus#799]
Por lo que he leído sólo hay un par de WOEID's disponibles para usar con twitter para la parte de los trending topics. 
¿ Es válido usar el WOEID del lugar más cercano al que estamos buscando o debe ser específicamente los que corresponden a la ciudad buscada?

**Comment by ifcarrera** [comment]
Claro, hay una consulta que puedes hacerle a la API que te retornará el WOEID de la ubicación más cercana a las coordenadas que le entregues. Ocupa ese para el resto de las consultas. 
Salu24.500-03

**Comment by JPSF** [comment]
Tanto en la parte "6.3.1.Trending topics de una ubicación" como en  "6.3.2.Tweets en una ubicación" ¿se debe usar el WOEID?

**Comment by ifcarrera** [comment]
Eso debes averiguarlo leyendo la documentación. Ahí sale qué parámetros se deben entregar para que funcionen.

**Comment by JPSF** [comment]
Perfecto! Muchas gracias @ifcarrera
