### ISSUE TITLE
Duda enunciado: Ventana de juego

### ISSUE THREAD

**Issue by felipehen** [IIC2233/syllabus#799]
Al leer nuevamente el enunciado, descubrí que se consideran como 2 puntos distinto, las ventana, pre-ronda, y la ventana ronda, y de ahí surge mi duda:

¿es 100% necesario que estas 2 ventanas sean distintas? o ¿se puede tener una ventana que funcione como ambas?

para el segundo caso, cabe mencionar que las funcionalidades debiesen funcionar bien, ademas de que se muestra si esta en "pre-ronda" o "ronda" en la pantalla

**Comment by kadroguett** [comment]
Hola @felipehen 
Si bien quedó un poco ambiguo en el enunciado, se refiere a dos estados distintos en el juego, no precisamente a dos ventanas diferentes (con esto me refiero solo a pre-ronda y ronda).

**Comment by felipehen** [comment]
Ya perfecto, mucha gracias

**Comment by kadroguett** [comment]
De nada, éxito en tu tarea!!
