### ISSUE TITLE
Ayudantía 7 de Marzo

### ISSUE THREAD

**Issue by akaminetzkyp** [IIC2233/Syllabus#8]
Hola! Quisiera saber si mañana hay ayudantías en el módulo 4. Gracias!

Salu123,
Alejandro Kaminetzky

**Comment by sguerra2** [comment]
Sí hay! Trabajaremos con git, la plataforma que ocuparemos durante todo el curso ;)

**Comment by akaminetzkyp** [comment]
Vale, gracias!
