### ISSUE TITLE
Error en Tablero.py

### ISSUE THREAD

**Issue by Luckbox314** [IIC2233/syllabus#8]
Me di cuenta que en el archivo Tablero.py falta la "N" en el string que nombra las columnas.
Es 'ABCDEFGHIJKLMOPQRSTUVWXYZ' y debería ser 'ABCDEFGHIJKLM**N**OPQRSTUVWXYZ'
__
¿Es un error o fue a propósito? algo así como cuando diferencian martes de miércoles con una M y una W, es decir, la N y la M se parecen un poco
En el caso de que fuera un error, ¿puedo cambiarlo y agregar la "N" que falta?

**Comment by lily416** [comment]
Gracias por avisar, fue un error que se nos pasó 😄 
Ya se encuentra subida la nueva versión del archivo en el syllabus. 😉 

Saludos y éxito con la tarea 👋

**Comment by Luckbox314** [comment]
muchas gracias :relieved:
