### ISSUE TITLE
Consulta pass/continue.

### ISSUE THREAD

**Issue by etoteiza** [IIC2233/syllabus#8]
Hola! Repasando introducción a la programación me encontré con la siguiente duda:
Cuál es la diferencia entre usar un "continue" con un "pass", en ciclos como while, for, etc.
Gracias de antemano

**Comment by KnowYourselves** [comment]
Hola!

### Pass:

`pass` es lo que se conoce como una **operación nula**, es una línea de código que en términos prácticos no hace nada. Sirve para marcar lugares en tu código que eventualmente programarás. Por ejemplo:

```python3
class Auto:
    def __init__(self):
         pass
    ...
``` 
De esta forma en tu código dejas declarado que existirá eventualmente una clase auto. Si no utilizaras pass y dejaras esa linea vacía te saldría error.

### Continue:

`continue` solo se puede utilizar dentro de un _loop_ (`for` o `while`) lo que hace es **pasar inmediatamente a la siguiente iteración**. Por ejemplo:

```python3
for i in range(10):
    if i % 2 == 0:
        continue
    print(i)
```

En este código iteramos los números del 0 al 10, sin embargo si el número es par entramos a `continue`, cuando esto pase iremos directamente a la siguiente iteración, por lo cual no se ejecutará `print` el resultado es que este programa imprime solo los números impares.

Hay veces donde dada una condición te interesa pasar inmediatamente a la siguiente iteración. Par a eso se puede utilizar `continue`.

Espero haber solucionado tu duda!
