### ISSUE TITLE
Autoevaluación de diagnostico 

### ISSUE THREAD

**Issue by davidbehar5** [IIC2233/syllabus#8]
Hola! Viendo la ruta de aprendizaje para la semana 0, sale que hay una autoevaluación de diagnostico, ¿donde esta publicada? y si no está, cuando la publicarán?

**Comment by lily416** [comment]
Hola @davidbehar5

La evaluación de diagnóstico es un cuestionario que se publicará durante la cátedra del día de hoy.

En el caso de las secciones 1, 2 y 3, la podrán encontrar en los módulos de Canvas.
En el caso de la sección 4, su profesor les dará acceso a un NearPod.


Saludos y éxito en la primera clase 👋👨‍🏫

**Comment by davidbehar5** [comment]
Gracias! resuelto!
