### ISSUE TITLE
Typing en UML?

### ISSUE THREAD

**Issue by naquiroz** [IIC2233/Syllabus#8]
Hay alguna forma de poner union de tipos en uml? Por ejemplo
`+ saldo: Union[int, float]` ?

**Comment by bcsaldias** [comment]
Hola,

Quieres decir que "saldo" puede ser int o float?
"int" es un tipo numérico, donde el número es sin punto decimal
"float" es un tipo numérico, donde el número sí tiene un punto y dígito
decimal. Este se usa cuando se quiere mayor precisión.

El número 10 puede ser guardado tanto como "int" como "float", así que si
bien el "float" usa más espacio en memoria que el "int", puede verse como
una generalización. En este caso, bastaría con decir que es un "float", ya
que incluiría al "int".

Espero haber sido clara.

Saludos!
Belén


2018-03-11 12:43 GMT-03:00 naquiroz <notifications@github.com>:

**Comment by naquiroz** [comment]
Hola! Si, estoy de acuerdo, quizas seria buena idea en el ejemplo usar solo `float` pero mi objetivo en la pregunta era otro. Trataré de ser mas explícito ahora.

Es posible usar clases de modulo `typing` , como por ejemplo `Union`  (que representa la union de 2 o más tipos de objetos distintos para una misma variable) en los diagramas uml?

Un ejemplo quizas más explicito.

` + electro_dependiente : Union[int, str]`

**Comment by bcsaldias** [comment]
Hola!

Ahora entiendo mejor el punto. Es una muy buena pregunta.

Las convenciones de los diagramas UML van evolucionando en el tiempo, pero
se basan en su mayoría considerando lenguajes tipados. Que un lenguaje sea
fuertemente tipado significa que al definir el tipo (type) de una variable,
no se puede guardar en esa variable algo de otro tipo, a menos que se
cambie de tipo. Estos diagramas UML forman parte de la documentación de una
pieza de software, para hacer buen mantenimiento y uso del código en
general.

En el caso de Python 3.x, lenguaje de tipado dinámico fuerte (podemos
entrar en más detalle si quieres), no hay una convención para indicar tipos
en los diagramas, ya que por definición no se indican los tipos de las
variables, entonces prácticamente podría todo ser de cualquier tipo.

Existen dos tipos de variables: primitivas y por referencia (podemos entrar
más en detalle si quieres). Todas las por referencia heredan de object, por
lo que si quieres poder asignar "Union[Clase 1, Clase 2, Clase 3]", sería
correcto usar "Object" o la clase más particular que incluya a las 3. Ojo
que "[]", indica indexación.

Para responder tu pregunta específica de variables primitivas, y dejar
claro tu diagrama, se podría utilizar: + electro_dependiente : str|int ,
indicando en el título del UML que se trata de un diagrama enfocado a
Python 3.x.

Avísame si quieres entrar en más detalles en algún punto que no esté muy
claro.

Saludos!
Belén

**Comment by naquiroz** [comment]
Me quedo, muy claro. Gracias!
