### ISSUE TITLE
Directorio Archivos Entregados

### ISSUE THREAD

**Issue by jitorralba** [IIC2233/syllabus#8]
Hola! Para trabajar con los archivos entregados debo asumir que los ayudantes los tendrán en el mismo directorio que el código? O en algún otro directorio en específico?

**Comment by aljara97** [comment]
Hola, puedes asumir que al momento de probar tu código los archivos csv se encontrarán en la misma carpeta que los archivos de python necesarios para la ejecución de tu tarea.

Mucha suerte con tu tarea ☺️

**Comment by Francisco5674** [comment]
![image](https://user-images.githubusercontent.com/61996440/76691153-b33aff80-6626-11ea-8e83-8e411f21d07b.png)
En e archivo de los posts, aquel en fomato csv en la linea 36 hay dos posts compartiendo la misma linea, es eso normal?

**Comment by DCCollao** [comment]
@Francisco5674 Hola!

Tu duda debería ir en otra issue, ya que no está directamente relacionada con la que comentaste. Por favor, abre una nueva para preguntar!

**Comment by Francisco5674** [comment]
oh sorry
