### ISSUE TITLE
Utilizar versión 3.8.2 de Python

### ISSUE THREAD

**Issue by miguel-mrtnez** [IIC2233/syllabus#80]
Ayer actualicé Python de su versión 3.7.4 a la 3.8.2. ¿Puedo trabajar con esta última versión en el curso?

**Comment by igbasly** [comment]
Hola @miguel-mrtnez 😄
En general no recomendamos que trabajes con la última versión 3.8,  ya que al ser una versión tan nueva y no tan probada como la 3.7, puede presentar ciertos errores en el funcionamiento. Esto no significa que no puedas utilizarla para programar, pero debes estar consciente de que los ayudantes **siempre** correremos tu código en la versión 3.7, por lo tanto, cualquier tipo de incompatibilidad queda bajo tu responsabilidad.

Saludos ✌️

**Comment by miguel-mrtnez** [comment]
Entendido. Muchas gracias!
