### ISSUE TITLE
Que pasaria en este caso?

### ISSUE THREAD

**Issue by nmaturana97** [IIC2233/Syllabus#80]
que pasaria si una persona pone a comprar 1DCC a 100 pesos
luego alguien pone a comprar 1DCC a 110 pesos
y luego alguien pone a vender 1DCC a 90 pesos? con quien haria match? teniendo en cuenta de que la oferta a 100 pesos se realizo antes que la de 110?
a que precio se vende?

**Comment by hanavarrete** [comment]
Lo correcto sería que haga el match con la primera orden (en llegada) que satisface el precio de venta.

**Comment by hanavarrete** [comment]
edited ^
