### ISSUE TITLE
Duda sobre ordenar por fecha de creación

### ISSUE THREAD

**Issue by Dieguu21** [IIC2233/Syllabus#80]
### Prerrequisitos
* [x] Leí las reglas del foro
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
**Hola, en el enunciado de la tarea sale que hay que ordenar como se muestran los comentarios o las publicaciones de forma ascendente o descendente según su fecha de creación, pero no entiendo cómo se puede hacer eso. No se me ocurre cómo hacerlo, me podrian dar algun tip ? por favor ☹️**

**Comment by tqmbanados** [comment]
Hola @Dieguu21! Hay varias maneras de hacerlo, pero una de las más fáciles/simples es usar la función `sorted`. En [ésta página](https://www.w3schools.com/python/ref_func_sorted.asp) hay una guía bastante clara de como usarlo. Vas a tener que usar el atributo `key`!
