### ISSUE TITLE
Función con mas de 100 caracteres 

### ISSUE THREAD

**Issue by Tmsca** [IIC2233/syllabus#80]
Hola!

Pasa que definí una función con varias variables y  excede los 100 caracteres por línea. Cómo puedo arreglar esto sin tener que cambiar el nombre de mis variables y dejen de ser aclarativas?

**Comment by benjastraub** [comment]
Hola, si es que tu función se alarga porque tienes muchas variables definidas, como 
```
def mi_funcion(argumento1, argumento2, ..., argumenton):
    pass
```
puedes aprovechar que Python permite separar en múltiples lineas elementos que se encuentran en paréntesis ```()```, brackets ```[]``` o braces ```{}```

por lo que puedes escribir
```
def mi_funcion(argumento1, argumento2,
               argumento3, argumento4,
               ..., argumenton):
    pass
```

No es necesario alinear los argumentos de las nuevas lineas a la altura del primer argumento para que el código corra, pero si es una recomendación de [PEP8](https://www.python.org/dev/peps/pep-0008/#indentation)

**Comment by jmwielandt** [comment]
Hola!

Tal como dijo Benjamín, eso es parte de lo que considera pep8. Lo puedes leer [acá](https://www.python.org/dev/peps/pep-0008/#indentation).

Te recomiendo revisarlo completo al menos una vez, ya que tiene bastante información de cosas por el estilo y más.

Saludos!
