### ISSUE TITLE
fecha segundos

### ISSUE THREAD

**Issue by movaldivia** [IIC2233/Syllabus#80]
Me acabo de dar cuenta que todos los tiempos de los archivos tienen los segundos = 0, podemos considerar que el tiempo pasa en minutos?

**Comment by rpalmaotero** [comment]
Sí, puedes asumir eso.

**Comment by akaminetzkyp** [comment]
@rpalmaotero esto significa que podemos decirle al usuario que solo ingrese hora y minuto? Sin segundos?
