### ISSUE TITLE
Expiró la invitación de mi repositorio de GitHub

### ISSUE THREAD

**Issue by sofiaguerreroc** [IIC2233/Syllabus#80]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).

Hola! Tengo un problema porque llené el formulario para crear el repositorio de GitHub y me llegó la invitación, pero no la abrí y expiró, así que ahora no puedo ingresar al repositorio para hacer las actividades. Intenté rellenar el form de nuevo pero no me deja enviar otra respuesta.
No sé como poder resolver este problema, espero me puedan ayudar, ya que sin el repositorio no puedo avanzar con las actividades del curso. De antemano muchas gracias y estaré atenta a la respuesta.

**Comment by ChupeteBecker** [comment]
Hola, @sofiaguerreroc, te pido por favor que escribas a coordinación para que te generen una nueva invitación.

coordinacion.iic2233@gmail.com

Saludos!!

**Comment by sofiaguerreroc** [comment]
Les acabo de mandar el correo, muchas gracias :)
