### ISSUE TITLE
Guardar una partida / nombre del usuario

### ISSUE THREAD

**Issue by NatachaP** [IIC2233/syllabus#80]
Hola!, en la sección 6.2.1 dice:
"civilizaciones.csv: este archivo tendrá el estado actual de cada civilización, por lo que deberás actualizar la información del archivo original y guardarlo en su nueva carpeta (el archivo que se utilizó para cargar o crear la partida debe mantener su estado original)".

Mi pregunta es: si debo mantener un archivo que el usuario ya había guardado, ¿entonces debo pedirle otro nombre al usuario para agregarlo a un directorio distinto en save? o ¿de qué otra forma podría resolver esto si el usuario no desea cambiar su nombre?
Gracias!

**Comment by roberto009** [comment]
Hola!
Si ya tenias una partida guardada y quieres volver a guardar, queda a tu criterio como lo manejas. Puedes sobrescribir el archivo o pedirle un nuevo nombre. No te olvides de especificarlo después en el Readme.
Éxito con tu tarea!
