### ISSUE TITLE
Duda acerca de importar desde pieza_explosiva.py para el README

### ISSUE THREAD

**Issue by martina-abello** [IIC2233/Syllabus#80]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Para poder definir tablero_transformado, necesito importar la clase PiezaExplosiva desde pieza_explosiva.py. Por lo que entiendo eso no es una librería externa, pero tampoco es un módulo que haya creado yo, estaba de antes, entonces ¿en qué parte del README lo pongo?

**Comment by Dominique236** [comment]
Hola!
En este caso, como se trata de código que se les está entregando, nosotros ya esperamos que este dentro de la entrega y entonces no se trata de un archivo/función/módulo/código nuevo. Por tanto no es necesario que esté en el _readme_, ya que no documenta algo que nos pueda sorprender durante la corrección.
Cuéntame si esto resuelve tu duda 😊

**Comment by martina-abello** [comment]
Me parece que sí, muchas gracias.
