### ISSUE TITLE
Duda sobre Añadir Contactos y viceversa

### ISSUE THREAD

**Issue by mignacia** [IIC2233/syllabus#80]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola, en el enunciado, en la parte 4.2.1, la opción de añadir contacto especifica que si la opción es valida y el usuario existe debo añadir al contacto y "viceversa". Con este viceversa se refiere a que al contacto que agregué también debería agregársele como contacto el usuario que recién lo agregó? Es un poco enredado, pero me refiero a que si yo agrego un usuario como contacto, este también deberá agregarme a mi automáticamente?
Ojala se entienda, muchas gracias! :D

**Comment by Tsbalart** [comment]
Hola @mignacia! claro! es como tu dices, si agregas un usuario como contacto, ese contacto debe agregarte a ti como contacto también. Espero que quede claro :) Exito con la tarea!
