### ISSUE TITLE
Duda con namedtuple

### ISSUE THREAD

**Issue by Mati-are** [IIC2233/syllabus#80]
En namedtuples de la semana 1 (listas-tuplas), se tiene un ejemplo que dice lo siguiente:
```python
from collections import namedtuple

# Asignamos un nombre a la tupla (Register_type), y los nombres de los atributos que tendrá

Register = namedtuple('Register_type', ['RUT', 'name', 'age'])

# instanciación e inicialización de la tupla
c1 = Register('13427974-5', 'Christian', 20) 
c2 = Register('23066987-2', 'Dante', 5)

print(c1.RUT)
print(c2.RUT)
print(type(c2)) 
```
El que funciona perfect, pero si le pongo un espacio al atributo name en Register (' name') me tira error. Debido a esto no he podido realizar la función crear ayudantes en la actividad de simulacro, ya que me tira los atributos de con espacios.

**Comment by bvasquezm** [comment]
Hola @Mati-are! 

Efectivamente, pero ojo que no hay una única forma de entregar los atributos a la hora de crear un **namedtuple**, en algunas si se permiten espacios 👀. Pero mi recomendación sería que lo hagas como te salga más cómodo, siempre puedes arreglar los strings, listas o lo que sea para que queden a tu gusto :) 

¡Espero haberte ayudado!
