### ISSUE TITLE
Mantenimiento de la información

### ISSUE THREAD

**Issue by MaxAl100** [IIC2233/Syllabus#80]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Durante el progreso de una partida es necesario ir actualizando la información del jugador que uno seleccione, pero no se menciona si esta información tiene que ser guardada en el archivo jugadores.csv o no. Ya que no es mencionado, supongo que todo se reinicia cuando se selecciona de nuevo un jugador, pero prefiero preguntar por aquí por si acaso.

**Comment by Gsalinas1506** [comment]
Hola!

`jugadores.csv` solo almacena información acerca de los distintos jugadores que pueden ingresar al DCCasino. Una vez ingresan a este, como dice el enunciado sus características pueden cambiar producto de las acciones que realicen. Ahora, esto **no significa que las características deban ser cambiadas en `jugadores.csv`**. El archivo sirve únicamente para que al momento de jugar los jugadores tengan "stats basales" que luego pueden modificarse al jugar, pero al iniciar una partida nueva las características deben empezar con sus valores originales.

Exito con la tarea! 🎲️🃏️
