### ISSUE TITLE
Consulta acerca de .gitignore ( Verificación y contenidos)

### ISSUE THREAD

**Issue by monesti** [IIC2233/Syllabus#80]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.

### Contenido
¡Hola! Esperando que se encuentren bien, mi duda es relacionada con .gitignore. Estuve investigando su uso y hallé que existen **muchísimos** archivos que uno puede evitar subir para evitar utilizar espacio innecesariamente.  En ese sentido, no me queda completamente claro cuáles debo evitar específicamente (Revisé el enunciado pero tampoco me deja tranquilo si acaso no me quedará algún archivo por excluir) . ¿Puedo simplemente copiar y pegar un archivo .gitignore estándar (de alguien más) y subirlo? Además, me gustaría comprobar que efectivamente no subí ningún archivo no deseado. ¿Hay alguna forma de revisar eso? Las veces que he hecho git push no he encontrado la carpeta __pycache__ , por ejemplo, pero puede que no haya revisado completamente bien.

¡Muchísimas gracias por la ayuda y buen fin de semana!

PD: No usé emojis porque no encontré :(

**Comment by Juampisaez** [comment]
Hola @monesti !
Respondere a tus dudas:

1. Para la T0 en particular, les pedimos que solo ignoren las carpetas `__pycache__/` y las generadas por las interfaces de desarrollo o los entornos virtuales. Sin embargo, **para las tareas futuras se les pedirá que ignoren el enunciado y archivos que se les entregue y no deban modificar**, como lo es en este caso el `tablero.py`.

2. Para crear el archivo .gitignore, puedes basarte en el link que aparece en la sección .gitignore del enunciado de la T0.

3. Para verificar los archivos que subes a github, basta con utilizar el comando git status. Este te permitirá saber que archivos están disponibles para subir. Si tu .gitignore esta bien implentado, los archivos a ignorar no te debiesen aparecer en el resultado del comando.

Espero te quede mucho más claro, si no, quedo atento.
Saludos,

**Comment by monesti** [comment]
¡Muchas gracias! Logré que funcionara correctamente (Al menos a priori) 😄 

Nos vemos en la próxima Issue 👋
