### ISSUE TITLE
Duda respecto al uso de la librería time

### ISSUE THREAD

**Issue by cristobalstrange** [IIC2233/Syllabus#80]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola! Estaba puliendo un poco mi programa y como detalle quiero usar la función sleep del módulo time para no mostrar mucho texto de una sola vez, por lo tanto:
**¿Está permitido usar el módulo time?**

**Comment by Lord-Kelsier** [comment]
Debido a que al momento de corregir tendremos que ejecutar varias veces tu tarea te pediríamos que no uses el `sleep`.

**Comment by victoriaatria** [comment]
Recuerda que todas las preguntas sobre librerías y modulos permitidos se deben hacer en la issue #21
