### ISSUE TITLE
No puedo importar un módulo que se encuentra en la misma carpeta

### ISSUE THREAD

**Issue by Gsalinas1506** [IIC2233/syllabus#800]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

- Mi módulo principal es `main.py`
- Este llama a un módulo llamado `frontend_ventana_principal` que se encuentra en una carpeta llamada `frontend`. Lo importo con from frontend import frontend_ventana_principal. Hasta ahí todo bien
- `frontend_ventana_principal` llama a otro módulo llamado `frontend_zona_estadistica` que se encuentra en el mismo directorio (`frontend`). Como están en el mismo directorio intento usar `import frontend_zona_estadistica`. Acá viene el problema

Cuando intento ejecutar main.py salta el siguiente problema:

> Traceback (most recent call last):
  File "c:/Users/gusta/Desktop/ING UC/2020-2/Programación Avanzada/Repositorios/Gsalinas1506-iic2233-2020-2/Tareas/T02/main.py", line 3, in <module>
    from frontend import frontend_ventana_inicio, frontend_ranking, frontend_ventana_principal
  File "c:\Users\gusta\Desktop\ING UC\2020-2\Programación Avanzada\Repositorios\Gsalinas1506-iic2233-2020-2\Tareas\T02\frontend\frontend_ventana_principal.py", line 5, in <module>
    import frontend_zona_estadistica
ModuleNotFoundError: No module named 'frontend_zona_estadistica'

Que puede estar pasando?

**Comment by furcelay** [comment]
Hola @Gsalinas1506 !
Los imports son siempre relativos a la ubicación del módulo en ejecución (a menos que especifiques lo contrario), en tu caso `main.py`, por lo tanto debes importarlo de la misma manera que lo hiciste en `main.py`, es decir `from frontend import frontend_zona_estadistica`.
En caso de tener muchos subdirectorios puedes hacer imports relativos, puedes ver más sobre ellos en la issue #706.

Saludos!
