### ISSUE TITLE
Subi el Readme Tarde!

### ISSUE THREAD

**Issue by ljrodriguez1** [IIC2233/Syllabus#800]
Se me olvido subir el Readme para la tarea 6 ayer por lo que lo he tenido que subir hoydia. Existe alguna posibilidad de que sea tomado en cuenta para que asi sea mas facil corregir la tarea?
Muchas Gracias

**Comment by Arcoirisky** [comment]
¡Hola!
Eso depende si te han revisado o no o:
Pero quédate tranquilo ouo)/ <3
