### ISSUE TITLE
No se encuentra módulo 'httplib2' desde consola

### ISSUE THREAD

**Issue by fedetaladriz** [IIC2233/Syllabus#800]
Hola!
Tengo un error que me ha tenido harto rato estancado. 
Para mis tareas que incluyen interfaces gráficas, siempre las he ejecutado desde consola de mi pc para detectar errores (desde pycharm se queda pegado). Sin embargo, en esta tarea al ejecutarla desde consola, no me reconoce una de las librerias utilizadas en el ejemplo de sheets (httplib2). Lo raro es que si ejecuto el mismo módulo desde pycharm, si me la reconoce y no tengo problema. Intenté desinstalando y reinstalado la librería y nada.
Alguna ayuda? Busqué en internet y no encontré nada :(

Adjunto una captura de lo que me sale
![img](https://user-images.githubusercontent.com/26395403/33221862-ad609bce-d131-11e7-9e3c-e4e480967173.png)

**Comment by ifcarrera** [comment]
Cuántas versiones de Python tienes instaladas? Cuáles? Qué intérprete tienes configurado para el proyecto en Pycharm?

**Comment by fedetaladriz** [comment]
@ifcarrera Solo tengo la version 3.6.2, y tengo como interprete el tipico archivo python.exe. En mi caso esta en C:\Program Files (x86)\Python36-32\python.exe. Debe ser un problema de pycharm, porque desde idle igual me lo reconoce.

**Comment by fedetaladriz** [comment]
Dudo que sea un problema de pycharm, porque desde IDLE igual me lo reconoce :/

**Comment by ifcarrera** [comment]
Sigamos descartando:
- Qué comando estás ejecutando para instalar la librería? 
- Lo haces directamente desde la consola? 
- Utilizas pip o pip3?
- Intenta instalarla pero abriendo la consola con "Ejecutar como administrador"

Quedo atento, salu3

**Comment by fedetaladriz** [comment]
Solucionado! No se por qué, pero tenia un bug relacionado con anaconda. Lo tenía instalado hace tiempo pero nunca lo había usado. En alguna parte lo tenía enlazado seguramente
Gracias igual @ifcarrera !

**Comment by ifcarrera** [comment]
Genial!

**Comment by cgiic2233** [comment]
También estoy teniendo este problema, tanto con httplib2 como con apiclient. Probé desinstalando y volviendo a instalar desde PyCharm, usé pip y pip3 y nada. Tengo python 3.5.3 y 3.6.2, intenté abrir el archivo con ambos y el problema persiste. Lo único que aún no he probado (dentro de las opciones que se han mencionado aquí) es esto: "Intenta instalarla pero abriendo la consola con 'Ejecutar como administrador'", @ifcarrera, porque no supe cómo hacerlo jajaja.

**Comment by ifcarrera** [comment]
Haciéndole click derecho te aparece la opción de ejecutar como administrador :D.
Por otro lado, el error te lo tira al ejecutar en Pycharm o en la consola? o en ambas partes?

salu-(el primer número que aparece en tu nick)

**Comment by cgiic2233** [comment]
Desinstalé nuevamente e instalé como administrador y sigue ocurriendo :'(

![imagen](https://user-images.githubusercontent.com/30679639/33246465-6f38dd34-d2f3-11e7-88d3-e12f2e7f81ff.png)

El error ocurre únicamente desde la consola, en Pycharm y en el Idle no tengo problemas con importar la librería.

¡Saludos! (No, no soy tan creativo como para cambiar el 'dos' por algo nuevo en cada comentario jajaja)

**Comment by ifcarrera** [comment]
Mmm... no puedes trabajar desde Pycharm solamente? No se me ocurre qué puede ser. 
PD: Podías decir el segundo dígito de tu username.

**Comment by cgiic2233** [comment]
En eso estoy, desde Pycharm, sólo que como ya estaba la issue aproveché de preguntar 😄
