### ISSUE TITLE
Usar Layouts y fondos, Widgets sobre elementos

### ISSUE THREAD

**Issue by Christian-Klempau** [IIC2233/syllabus#800]
Hola! 
He estado tratando y  no se me ocurre una manera de hacer una interfaz con Layouts, la única manera es colocar los elementos en su posición de manera directa pero quiero tener una ventana autoajustable.
Mi problema es el siguiente: Si tengo un fondo, sobre el fondo debo agregar una casilla de otro color, sobre la casilla de color debo agregar un botón.
Mi idea original era hacer un estilo general para el fondo, y luego usar un HBox para la casilla superior. Luego estilizar ese HBox y agregarle los elementos como el botón. El problema es que 1. no puedo estilizar un Hbox. 2. si uso un Widget como fondo y estilizo eso, luego si agrego el botón este se desplazará y no se colocará **sobre** el Widget que contiene el color de fondo superior. El mismo problema me ocurriría en el Layout del mapa con sus elementos y de la Tienda.
Tal vez existe un elemento o mecanismo que no conozco que me pueda servir.
Alguna idea de cómo abordar este problema? Estoy obligado a programarlo con coordenadas, o tal vez en el Designer se pueda solucionar?
La imagen 1 muestra lo que quiero logar, la imagen 2 muestra lo que tengo (usé paint porque es más fácil jajajaj)

![layouts](https://user-images.githubusercontent.com/62039719/82596359-25731780-9b75-11ea-9ff9-7bf42428c97f.png)
![layouts](https://user-images.githubusercontent.com/62039719/82597025-56078100-9b76-11ea-833c-d2ce0ea9c480.png)

**Comment by jitorcas** [comment]
Hola! @Christian-Klempau 

¿Estas utilizando Designer?, ¿Qué quieres decir con respecto a 'estilo general para el fondo'?
Para evitar lo que te está pasando podrías utilizar Designer ya que puedes situar los elementos sobre otros y previsualizar directamente la manera en que está quedando tu ventana.

**Comment by Christian-Klempau** [comment]
No, por el momento no estoy usando Designer. La verdad no sé que tan necesario es pero debido a estos problemas creo que no me queda otra jajaj. Me refiero a que quiero tener un estilo para el fondo de toda la ventana, por ejemplo un color distinto a blanco/gris. Pero lo que no logro hacer es poner un widget sobre otro dentro de un Layout, de una manera que no sea programarlo forzadamente con valores x, y. Pero en ese caso mi ventana no sería reactiva a cambios de tamaño.

**Comment by jitorcas** [comment]
@Christian-Klempau Te recomiendo mucho usar QtDesigner, te solucionará muchos problemas que puedas tener ahora y en el futuro. 
Con respecto a lo que me comentas, estoy seguro que se puede solucionar con QtDesigner y utilizarás menos tiempo programando las ventanas. Me comentas que decides para buscar la forma si no decides usar QtDesigner.

**Comment by Christian-Klempau** [comment]
@jitorcas Al final con Designer lo pude solucionar! gracias :)

**Comment by jitorcas** [comment]
@Christian-Klempau  me alego! éxito en la tarea 😄
