### ISSUE TITLE
"No Module Named PyQt5" a veces

### ISSUE THREAD

**Issue by DiegoPollack** [IIC2233/syllabus#801]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

Buenas tardes, tengo un problema con el módulo PyQt5. Cuando intento correr un script desde la capreta de asociada a mi repositorio personal "DiegoPollack-iic2233-2020-2", me aparece el error "No module named 'PyQt5'", pero si muevo el script a mi escritorio y lo intento correr desde ahí el módulo funciona bien (mismo código, en un lugar funciona y en el otro no). Existe la probabilidad de que al subir mi código el corrector tenga un problema similar? Hay alguna manera de arreglarlo? Muchas gracias.

**Comment by knight-who-say-ni** [comment]
Hola @DiegoPollack !!

De casualidad lo estás corriendo en VScode?? Si es así, prueba corriendolo desde la consola de tu pc (asi es como el ayudante lo va a correr). VScode no se lleva muy bien con pyqt5 ni con los paths absolutos, asi que te recomiendo siempre correr tus programas desde la consola. De hecho, en un par de semanas esto va a ser necesario.

Saludos!!!
