### ISSUE TITLE
contenidos semana 10

### ISSUE THREAD

**Issue by nmaturana97** [IIC2233/Syllabus#801]
¿que paso con la carpeta de la semana 10, en contenidos?

**Comment by akaminetzkyp** [comment]
Hola!

Qué paso con esa carpeta? Yo la veo bien. :)

Saludos!

**Comment by nmaturana97** [comment]
bah! que raro, cuando hacia git pull no me descargaba la carpeta. Lo soluciones clonando de nuevo Contenidos. Gracias.
