### ISSUE TITLE
Error al comenzar QThread del metodo keypressevent

### ISSUE THREAD

**Issue by BFry712** [IIC2233/syllabus#802]
### Prerrequisitos

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! necesito ayuda porque la comenzar el qthread de la flecha y tener el pinguino en la pista de baile, al apretar los botones de movimiento ya no se mueve :c he intentado arreglarlo y nada
Saludos!

**Comment by manearaya** [comment]
Hola @BFry712!

Tu código está actualizado? Leí lo que tienes en tu repositorio y me parece que no tienes conectadas las señales que manejan el movimiento del pinguino.

Quedo atenta a tu respuesta!

**Comment by BFry712** [comment]
Hola @manearaya !
lo acabo de subir! c: 
Tengo algunos movimientos en keypressevent y cuando comienza la partida va a la función comenzar_partida, pero cuando comienzo la partida ya no lo puedo mover.
Saludos!

**Comment by manearaya** [comment]
Hola de nuevo!

Estoy trabajando en el por qué ocurre esto, pero lo que hace que la ventana no reciba el input del teclado es cuando desactivas el botón de comenzar partida en la función en la función comenzar_partida (línea 73). Lo comenté y el pingu se mueve perfecto!

**Comment by BFry712** [comment]
perfecto! ahi corre sin problemas, entonces no es necesario desactivar el boton de comenzar partida(cuando comienza una partida) para la tarea?
saludos y muchas gracias!

**Comment by manearaya** [comment]
Sí es necesario que no se pueda interactuar con el botón: puedes desactivarlo o sacarlo de la ventana.

**Comment by manearaya** [comment]
Creo que encontré el problema:

Cuando defines el centralwidget en QtDesigner, el focuspolicy está en **NoFocus**. Esto debería ser lo que está provocando que la ventana no "escuche" los inputs. Cambiándolo a **StrongFocus** es posible desactivar el botón sin problema.

Avísame si te funciona!

**Comment by BFry712** [comment]
Ahi si! Muchas gracias te pasaste! @manearaya
