### ISSUE TITLE
Reinicio de partida; orden mesones

### ISSUE THREAD

**Issue by jaimecoloma** [IIC2233/syllabus#802]
Hola! En el enunciado se menciona que  "las mesas y mesones con los que se inicia una nueva partida deberán comenzar en posiciones aleatorias dentro del mapa". Es necesario hacer que los mesones aparezcan así? Digo pensándolo porque como jugador no me gustaría tener un mesón en la mitad o "mal ubicado" más que nada, me gustaría saber si pueden los mesones quizás partir aleatorios pero en un área designada (como área de cocina algo así en la derecha de la pantalla por ejemplo).

**Comment by kadroguett** [comment]
Hola @jaimecoloma 
Como dice el enunciado deben ser posiciones completamente aleatorias, por lo que no se pueden utilizar áreas designadas. Pensando como jugador esto puede añadirle más gracia al juego, ya que así uno debe pensar en como ubicar de mejor forma las mesas para repartir más rápidamente los pedidos.

**Comment by milosoria** [comment]
@kadroguett Hola! Si las mesas se distribuyen aleatoriamente para que el usuario las administre como quiera, entonces no tiene sentido que al iniciar una nueva partida se comience en la fase RONDA. Si se generan los labels de forma aleatoria, pueden quedar "juntos" sin intersectarse y entonces el mesero podría colisionar con ambos a la vez...

**Comment by kadroguett** [comment]
@milosoria Disculpa la demora, el mail que me notifica se me había perdido entre tantos correos. Sobre la pregunta, no le veo problema a eso, la probabilidad de que pase no es tan alta y de ocurrir solo sería una dificultad añadida al jugador, la cual no afectaría a la evaluación
