### ISSUE TITLE
Información a mostrar de cada tweet, filtro de datos, nueva sheet, dimensiones sheet

### ISSUE THREAD

**Issue by fedetaladriz** [IIC2233/Syllabus#802]
Hola de nuevo jajaja
Me quedan varias dudas respecto al enunciado:

1. Cuando se selecciona una ciudad y un país, hay que entregar los resultados de las dos consultas de twitter(trending topics y 20 tweets en la ubicación) o se debe permitir al usuario elegir cual de las dos se quiere obtener?
2. Que datos hay que entregar sobre cada tweet en el caso de la segunda consulta? Solo el str del tweet o algo mas? (usuario, fecha de publicación...?) 
3. En la última parte, se escribe sobre la misma sheet que se sacó la información de las ciudades y países o se crea una nueva?
4. Se puede asumir que la sheet tendrá determinadas dimensiones o hay que hacerlo para el caso general? Se que es un poco obvio que debería ser general, pero me entró la duda porque en el enunciado se dice que se trabajará con una sheet creada por mi mismo.
5. A que se refieren con que se debe seleccionar/filtrar los datos que se quieren obtener(En la sección GUI del enunciado)? Cuando se entreguen los resultados hay que tener algo así como un buscador de los resultados obtenidos?
Gracias!!

**Comment by ifcarrera** [comment]
Hola! Primero que todo, cuando tengas múltiples dudas relacionadas a diferentes temas, lo mejor es que crees una issue para cada una, así es más fácil de encontrar por tus compañeros. Dicho esto:

2) Dado que te pedimos una restricción de tiempo y que ordenes los tweets según los seguidores, sería bastante útil que pusieras la fecha de creación y el número de seguidores del autor.
3) Está en el enunciado.
4) No puedes asumir las dimensiones, pues todos los paises tienen diferente número de ciudades. Debe ser para el caso general; se probarán diferentes dimensiones (de tamaño indefinido), por lo que tu programa debe poder leerlas todas. La Sheet creada por ti mismo es para que puedas probar tu programa en los diferentes casos :)

**Comment by ifcarrera** [comment]
5 y 1. Debes mostrar solo lo que el usuario quiera ver. Si quiere ver solo los tweets le muestras los tweets, si quiere ver tweets Y TT le muestras ambas cosas. Cabe destacar que debe ser solo del país y ciudad que desee.

**Comment by JPSF** [comment]
¿Cuando se habla de mostrar los tweets o mostrar los trending topics se refiere al nombre del tweet o al contenido(como texto) de este o a ambas cosas? Aún no me queda claro porque no está especificado. Pienso que quizás sea más práctico poner el nombre y su link respectivo pero no lo sé

**Comment by ifcarrera** [comment]
Al contenido

**Comment by JPSF** [comment]
¿Pero para la parte de los trending topics entonces deberíamos entregar el contenido de todos los tweets de cada uno de esos 5 trending topics(serían miles)?

**Comment by ifcarrera** [comment]
En la parte de TT, solo se te pide que muestres los TT ordenados según el número de menciones 🤔
