### ISSUE TITLE
Leer city.list.json.gz

### ISSUE THREAD

**Issue by JorgeBdelaT** [IIC2233/Syllabus#802]
Holaa, estoy tratando de leer el json con las ciudades y al hacer json.load(archivo), me arroja el siguiente error:

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

Busque en internet y no encontre como solucionarlo :(

**Comment by mfanselmo1** [comment]
Hola, asegurate de ponerle el encoding='utf-8' para que funcione.

**Comment by rihanuch** [comment]
Estas poniendo enconding=“utf-8” como parametro en load?

**Comment by JorgeBdelaT** [comment]
si, sigue arrojando el mismo error

**Comment by mfanselmo1** [comment]
Intenta con [esto](https://stackoverflow.com/questions/20199126/reading-json-from-a-file), pero en el `with open(file) as ...` pon `with open(file, 'r', encoding ='utf-8') as ...`, asi me funciona a mi.

**Comment by JorgeBdelaT** [comment]
no estaba descomprimiendo el archivo, use la libreria gzip y ahora funciona, gracias!!
