### ISSUE TITLE
Ciudades con nombres repetidos

### ISSUE THREAD

**Issue by Drpinto1** [IIC2233/Syllabus#803]
Saludos, en el archivo `city.list.json` existen 209.579 ciudades, todas con id único, sin embargo existen 47.563 ciudades cuyos nombres están repetidos y 5.962 ciudades cuyas coordenadas están repetidas. (ambas cuentas solo corresponden a las coincidencias, sin considerar a las "originales", es decir si un nombre está 3 veces, figura dos veces en la cuenta dada y para una ciudad que está 2 veces, solamente aparece una)

Dado que debemos ser capaces de encontrar una ciudad dado su nombre, ID o coordenadas, al pedirse una que esté repetida (tanto para nombres como para coordenadas), cuál debemos ocupar?

Gracias de antemano :smile:

**Comment by rihanuch** [comment]
@Drpinto1 , si se pide por nombre se debe especificar el país, por lo que ahí no debería haber conflicto. Respecto a las coordenadas queda a criterio tuyo, solo recuerda poner en el código que decisión tomas

saludos!

**Comment by Drpinto1** [comment]
Incluso especificando el país, existen 40.759 duplicados, 6804 menos que sin indicar la ciudad, pero aún bastantes; intenté calcular cuantos se repiten al menos tres veces, pero se demora bastante mi algoritmo, editaré la respuesta cuando termine de calcular
saludos :D

**Comment by Drpinto1** [comment]
Haciendo una inspección más detallada de los datos, me encontré con que están incluídos lugares como "Provincia de Santiago", "Región de Coquimbo", "Republic of Chile", que claramente no son ciudades; esto también se cumple para otros países, por ejemplo, "United States" aparece como ciudad para el país "US". Lo anterior puede explicar las localizaciones duplicadas, pues para un País/Estado/Región, puede que su localización sea la correspondiente a su capital.
No estaba seguro de si abrir otra issue sobre este tema o comentarlo aquí, pero como creo que sigue la misma lógica que el problema anterior decidí dejarlo aquí.
Como debemos proceder para estos casos?, debemos incluírlos en las opciones? (tanto para su ID como para sus nombres)

Gracias de antemano :smile:
