### ISSUE TITLE
Problema de pre visualización en QtDesigner

### ISSUE THREAD

**Issue by eliasbruchfeld** [IIC2233/syllabus#803]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda
Hola! 

Haciendo la tarea, me di cuenta que en qt designer tengo problemas cuando quiero hacer una vista previa de lo que estoy haciendo (ctrl + R). 
Esto es lo que tengo hecho
![Captura](https://user-images.githubusercontent.com/69616086/97094662-2846cc80-162d-11eb-80ae-9c8e657c9bb2.PNG)

Y cuando le pongo ctrl+r me aparece así:
![image](https://user-images.githubusercontent.com/69616086/97094682-55937a80-162d-11eb-8437-f0db88405e1b.png)
Ya probe poniendole "send to back" a lo celeste y no paso nada. No le saque foto pero hace un rato tambien me pasaba con los layouts. Todo lo que estaba adentro de los layouts dejaba de verse cuando corria lo que habia hecho, al punto de que elimine todos los layouts y ordene las cosas "a mano". 
Probe tambien corriendo directo mi archivo main.py y se veia igual que cuando hacia ctrl+r asi que supongo que es un problema de como estoy añadiendo las cosas(?).

**Comment by kadroguett** [comment]
Hola @eliasbruchfeld, revisé tu repositorio y viendo el archivo `ventana_juego.ui`, la vista previa se ve bien. Lograste solucionar tu problema?

**Comment by eliasbruchfeld** [comment]
O sea se "arregló solo" por decirlo así. De repente dejó de pasar.

**Comment by kadroguett** [comment]
Ok, si te vuelve a pasar comenta esta issue. Éxito en tu tarea!
