### ISSUE TITLE
Conectar señal a atributo

### ISSUE THREAD

**Issue by lewebe** [IIC2233/syllabus#803]
Hola, estoy tratando de conectar una señal que emite un `bool` directamente a un atributo de mi clase `Mesero` , sin embargo me arroja un error. Las señales deben ser conectadas siempre a un método/función, o sí me deberían dejar modificar directamente un atributo y mi error está en otra parte?

**Comment by kadroguett** [comment]
Hola @lewebe 
Por lo que tengo entendido no se puede conectar una señal a un `bool`, en lugar de eso te recomiendo crear un método que se encargue de modificar el atributo del `Mesero`.
