### ISSUE TITLE
"tweet_volume" : None

### ISSUE THREAD

**Issue by ajahr95** [IIC2233/Syllabus#803]
Cuando hago la consulta para obtener los TT hay varios que dentro de sus valores de "tweet_volume" me retorna None. ¿Que debo hacer con ellos ? Hasta ahora los estoy considerando como si fuera 0, por ende, no los tomo en cuenta para los primeros 5 TT. 

Otra pregunta respecto a esto es que dentro de los nombre de los TT algunos tienen el # al comenzar la palabra y otros no, se consideran ambos?

**Comment by ifcarrera** [comment]
Sí, los None considéralos 0.

Con gato o sin gato ambos son TT.

Salu10 (binario)
