### ISSUE TITLE
Error con quickstart de la api de gmail

### ISSUE THREAD

**Issue by valerojasm** [IIC2233/Syllabus#804]
Hola! Cuando intento instalar la google client library con `pip install --upgrade google-api-python-client` me da el siguiente error:

`pyasn1-modules 0.2.1 has requirement pyasn1<0.5.0,>=0.4.1, but you'll have pyasn1 0.1.9 which is incompatible.`

Le hago upgrade pero:

`Cannot uninstall 'pyasn1'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.`

Busqué en internet e intenté algunas cosas pero en verdad no cacho como arreglarlo... Tips? Gracias!

**Comment by ptflores1** [comment]
que pasa si lo haces con `pip3 install --upgrade google-api-python-client`en vez de `pip install --upgrade google-api-python-client`?

**Comment by valerojasm** [comment]
Lo mismo :(

**Comment by ptflores1** [comment]
tienes instalado anaconda ?

**Comment by valerojasm** [comment]
no se que essssss

**Comment by valerojasm** [comment]
no me funciona el example.py que subieron tampoco y si instale flask?

**Comment by valerojasm** [comment]
ALOOOOO sigo con el mismo problema

**Comment by cilopez** [comment]
Descarga anaconda [aquí](https://anaconda.org/),  anaconda permite utilizar e instalar librerías que a veces tienen problemas en otros editores. Para instalar una librería simplemente debes escribir en la linea de comando de Anaconda `pip install libreria`
