### ISSUE TITLE
Archivo config.py

### ISSUE THREAD

**Issue by dvogaz** [IIC2233/Syllabus#804]
No entendí bien como funciona el archivo config.py:
1° ¿el usuario debe ingresar sus credenciales modificando este archivo directamente o debe ingresarlas en la interfaz y este archivo debe procesarlas/guardarlas? 
2° ¿la función get_credentials del ejemplo de Google Sheets iría en este módulo? 
3° ¿las constantes que contienen las keys/tokens tendrían que estar en este archivo?

**Comment by ifcarrera** [comment]
Velo así, si yo tengo tus api key/token podré hacerle consultas a la API bajo tu nombre, por lo que podría hacer cosas malvadas, como publicar tweets desde tu cuenta, etc. Si las tienes en tu código todos las podremos ver.
La idea del config.py es que mantengas todas las credenciales (passwords, keys, tokens) en otro módulo. Cada persona debe modificar ese archivo a mano para hacer las consultas desde su cuenta y tú puedas mantener tu privacidad. 

SaluII (romano)

**Comment by dvogaz** [comment]
ahhh ya, graaacias. Una duda que me surgió ahora, la tarea tengo que subirla sin mis keys/tokens? o en este caso da lo mismo?

**Comment by aleuribej** [comment]
Hola! Queria sumarme a la duda para saber si es necesario subir client_secret.json. ¿Ese archivo lo debe generar el ayudante? ¿O igualmente se debe subir al repositorio?

**Comment by ifcarrera** [comment]
Como quieran, pueden no subirlo y el ayudante generará el suyo.

**Comment by aleuribej** [comment]
Gracias 😄!
