### ISSUE TITLE
Problema con múltiples teclas del teclado

### ISSUE THREAD

**Issue by Jamesmoreno21** [IIC2233/syllabus#804]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X]  Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X]  Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X]  Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X]  Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X]  Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X]  De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Tengo un problema con el tecleo múltiples para las flechas, actualmente logré implementar que si presiono teclas, la zona de captura cambia su color, **logro que funcionen combinaciones de pares y la mitad de tríos, pues dos combinaciones no funcionan  que son**: 
1. las teclas W, A y S 
2. las teclas W, S y D

Pero las combinaciones W, A, D y S, A, D sí lo hacen, no sé porqué cuando presiono esta combinación el programa no captura ni siquiera la KeyPressEvent, hace como si nada pasa, en cambio con otras combinaciones todo funciona correctamente. No sé si dependerá de mi computador quizás pero lo encuentro bastante extraño, además **solo ocurre cuando junto S y W**😕. 
Agrego además que si las tecleo una por una (manteniendo todas presionadas) solo llego hasta dos teclas de las tres (AW, AS, AD, WD, WS, DS), en cambio para la combinación W, A, D y S, A, D funcionan las tres con tecleo directo y secuencial 😢 
Ojalá puedan ayudarme, desde ya gracias!

**Comment by knight-who-say-ni** [comment]
Hola @Jamesmoreno21 !!
Hay varios teclados que tienen problemas con la combinacion de algunas teclas al mismo tiempo. Por ello en el enunciado se pidio que las teclas a apretar sean parametros: asi puedes elegir la combinacion que a ti te funcione!! (Y la que le funcione a la persona que le toque corregirte).

Así, si prefieres usar las flechas del teclado, o cualquier otra combinacion que si te funcione, no hay problema alguno, **pero recuerda mantenerlo parametrizado**.

Saludos, y exito programando!!
