### ISSUE TITLE
Tweets Radio coordenadas

### ISSUE THREAD

**Issue by B-Dominguez** [IIC2233/Syllabus#805]
Holaa
De las ciudades hay que buscar las coordenadas lat, long, pero con qué radio usamos la búsqueda de los tweets?

**Comment by ifcarrera** [comment]
Déjalo a tu criterio, especificándolo en el readme. La idea es que sea lo suficientemente grande para  que te retorne varios tweets.

**Comment by ifcarrera** [comment]
Saluβ (griego)
