### ISSUE TITLE
Agregar sonidos y fuentes de letra

### ISSUE THREAD

**Issue by javiermarhuich** [IIC2233/syllabus#805]
Hola.
Es posible agregarle a la tarea una fuente de letra y/o sonidos cuando se realiza una acción (como agregar mesas o al entregar un plato a un cliente).

En la letra pensaba usar archivos TrueType (```.ttf```) pues son fáciles de encontrar (Google Fonts, FontSquirrel, etc). Para el sonido estaba revisando la librería ```playsound``` y buscar audios sin copyright. La procedencia de estos elementos lo especificaré en el README y en una ventana aparte dentro de la tarea.

Si es posible al menos las fuentes de letra también me gustaría saber cómo podrían agregarse a PyQt ya sea en código directamente o en QtDesigner.

Sorry lo repentino de preguntar esto, en realidad pensaba hacerlo con el desarrollo más avanzado 😅.

**Comment by jitorcas** [comment]
Hola! @javiermarhuich 

Con respecto a tu pregunta, conversamos entre los ayudantes y llegamos a la conclusión que podrías implementar sonido, sin embargo este debe ser sencillo de **"desimplementar"** ya que si al ayudante corrector le genera un problema, este no debiese impedir la corrección general de la tarea. 

Con respecto a la instalación de nuevas fuentes, si no vienen por defecto tienes que especificar la manera en cómo lo implementaste (en el README) y pasar el **archivo** o **link**. A pesar de lo anterior, el ayudante corrector tiene la posibilidad de no querer instalar nada ajeno, por lo que tu programa debiese tener una **opción B** en caso que eso pase. 

Personalmente nunca he implementado una fuente externa, ya que en QtDesigner existe una gama muy grande de distintas fuentes que puedes utilizar. Te recomiendo revisarlas todas, y si no te gusta ninguna y quieres implementar la fuente externa puedes mirar esta [issue](https://stackoverflow.com/questions/41282158/pyqt4-how-to-import-and-change-custom-font-for-painted-text) que si bien está en `PyQt4` te puede servir para tener una idea.

Valoramos mucho las formas creativas de hacer las tareas, espero que esto no te desanime! 
Éxito :boom:

**Comment by javiermarhuich** [comment]
Hola.
Con respecto al sonido no hay problema, creo que puedo hacer un ```try/except``` con las excepciones ```ModuleNotFoundError``` y```NameError```, de esta forma sólo habría que comentar el import a la librería en caso de error.

Con respecto a las fuentes de letra... sigo buscando una forma que no pida instalar pero por ahora usaré sans-serif pues parece reconocerlo en los tres sistemas principales. De todos modos también buscaré una forma para usar ```try/except``` y cargar la fuente si está disponible

Saludos.

**Comment by jitorcas** [comment]
Me parece una buena idea! recuerda explicitar en el **README** todo lo que hagas para que el ayudante que te corrija esté en conocimiento. 

Saludos y éxito en la tarea!
