### ISSUE TITLE
Duda con efectos flecha hielo

### ISSUE THREAD

**Issue by margavicunas** [IIC2233/syllabus#805]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! En el enunciado dice que cuando la flecha hielo es atrapada la velocidad de todas las flechas se reduce, ¿eso aplica a las flechas "futuras" o sólo considera a las que se encuentran en pantalla? Es decir, ¿flechas nuevas también reducirán su velocidad durante 0.2xduracion_nivel?

Gracias 🌻

**Comment by manearaya** [comment]
Hola @margavicunas!

El enunciado se refiere a que todas las flechas se moverán a la mitad de la velocidad por cierto tiempo. Es decir, mientras dure el efecto de la flecha hielo, todas las flechas  que aparezcan en pantalla se deberán mover más lento, y cuando acabe el tiempo del efecto deberán volver a su velocidad normal.

Por lo tanto, sí se aplica a flechas futuras si es que cuando estas aparecen todavía está el efecto de la flecha hielo.

Éxito con la tarea!

**Comment by margavicunas** [comment]
Muchísimas gracias ❤️

**Comment by jorgetf-desing** [comment]
Hola tengo una duda, esto incluye la generación de nuevas flechas? Es decir, que se generen más lento las futuras flechas o sólo cambian de velocidad? Sino pasa que se amontona arriba al parecer

**Comment by Sofia-Arratia** [comment]
Hola! Tengo la misma duda que @jorgetf-desing 😅

**Comment by manearaya** [comment]
Hola! Está en el issue #924

**Comment by Sofia-Arratia** [comment]
Muchas gracias!
