### ISSUE TITLE
Error base64 al querer enviar un mail

### ISSUE THREAD

**Issue by jeharcha** [IIC2233/Syllabus#805]
Hola!

Para enviar un mail busqué  en la gui de la API de Gmail, encontré el código, y al momento de ejecutarlos, levanta una excepction. Este error ocurre al momento de crear un mail con "create_message(sender, to, subject, text)" (Yo le entrego todos los argumentos como strings), el traceback me indica un error con la libreria base64. 
¿Qué podría estar pasando?

Estoy atento, muchas gracias

**Comment by ptflores1** [comment]
Hola !
Si no me equivoco es porque necesitas pasarle `bytes`al metodo de `base64` y no un `string`.
Saludos !

**Comment by jeharcha** [comment]
Gracias ! 
No pensé que el código de google no funcionaria 🤕

**Comment by jeharcha** [comment]
Disculpa volver  molestar, pero ahora se me levanta otra exception. 
Teóricamente ya tengo el "raw message" creado con la función anteriormente decrita, luego al pasárselo a la funcion "send_message(service, me, message)", me levanta error el mismo message recién creado. 
El traceback comienza en mi código, en el argumento "message",  y pasa por:
Python36-32\lib\site-packages\googleapiclient\discovery.py"
Python36-32\lib\site-packages\googleapiclient\model.py"
Python36-32\lib\site-packages\googleapiclient\model.py"
Python36-32\lib\json\__init__.py"
Python36-32\lib\json\encoder.py
Python36-32\lib\json\encoder.py"
Python36-32\lib\json\encoder.py"
    TypeError: Object of type 'bytes' is not JSON serializable


Y lo estoy haciendo como Google me dijo :(

**Comment by jeharcha** [comment]
Jose Manuel, usted es diabólico!! 😮 
Muchas Gracias
El return lo habia cambiado hacia ".as_bytes()", pero no el resto !!

**Comment by Unknomads** [comment]
Hola. Al hacer todo lo que dicen en este thread igual se me levanta un HttpError 400.
El error especifico que se levanta es: An error occurred: <HttpError 400 when requesting https://www.googleapis.com/gmail/v1/users/me/messages/send?alt=json returned "Recipient address required">
Alguna idea de por que pasa esto.
Gracias!
