### ISSUE TITLE
API yoda

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#806]
Hola, jugando a intentar hacer funcionar la api del bonus me tiró varias veces seguidas el output 
```<Response [400]> {'error': {'code': 400, 'message': 'Bad Request: text is missing.'}}``` porque no sabía cómo pasarle el texto. Al final se me ocurrió una forma, y pasó esto:
```<Response [429]> {'error': {'code': 429, 'message': 'Too Many Requests: Rate limit of 5 requests per hour exceeded. Please wait for 56 minutes and 54 seconds.'}}```

Además de que siento curiosidad por cómo van a hacer para revisar las tareas en caso de que varias personas decidamos hacer el bonus, el DCC no quiere gastar US$5 en esto? (y nos pasan la credencial en una issue en los repos previa inscripción, aununcio vía siding o lo que sea)
Es que intentar hacer cualquier cosa en condiciones de "solo puedes probar 5 veces tu código en 60 minutos" es horrible, y de verdad no sé cómo lo van a corregir antes de que cierre el semestre (en caso de que suficientes personas hagan el bonus).

![image](https://user-images.githubusercontent.com/37153467/41950020-2728fc7c-7992-11e8-8359-a2a4f2749e8a.png)
link donde sale: http://funtranslations.com/api/yoda

PD: es gracioso porque si uno se pasa en las consultas de una traducción se bloquean todas, pero no sé si comprando la licencia de yoda sea válida para todas las traducciones 🐡 🚀 🍝 🦆

**Comment by jmwielandt** [comment]
PD2: soy el único al que le hace gracia que el bot etiquete las issues como de tarea 3 cuando son de la 7? jajaja

**Comment by JorgeBdelaT** [comment]
Tengo una duda con respecto a esta API, le debemos entregar todo el texto que sera el mensaje? de ser asi, la API no podra procesar el texto, pues casi todo esta en español y si le paso ciertas palabras que me retorna OpenWeather las unicas que podria alterar serian las de la descripcion.

**Comment by mfanselmo1** [comment]
Hola @JorgeBdelaT , @Bipavez 
Las dos cosas que preguntan quedan a su criterio, mientras que se note el claro uso de la api de yoda, junto con todo lo que sale en el enunciado.
@jmwielandt En el enunciado sale que tengan cuidado con la cantidad de requests que hacen a la api, no te preocupes por como lo vamos a corregir.

**Comment by Bipavez** [comment]
Ehm, hola denuevo!
Primero, gracias por la respuesta.
Tengo otro problema, resulta que el API de Yoda recibe hasta cierto largo de texto y después se cae el request. ¿Esta considerado en el bonus pasar sobre esto? Lo que pasa es que si tengo que partir los requests que le hago a la API llego muy rápido al límite de 5 requests por hora, pero por otro lado no puedo hacer textos traducidos de mas de 2-3 ciudades distintas

**Comment by mfanselmo1** [comment]
Hola!
Estuve probando lo que me dices, y si, despues de cierto largo de texto retorna error [414](http://www.checkupdown.com/status/E414.html), que significa que el servidor no va a aceptar mensajes tan grandes. Me funciono pasarle textos de hasta 7644 caracteres (probablemente un poco mas), que es bastante largo asique ahi vas a tener que ir probando y ver que cosas traducir y que cosas no.
Por otro lado, me paso que tuve que cambiar los saltos de linea y los espacios por el caracter '%20', tal como sale en el ejemplo de la documentacion de la api.
No entendi a que te refieres con que no recibes ningun json de la request, yo si lo recibo y en este formato:
```
{'success': {'total': 1}, 'contents': {'translated': 'contenido traducido', 'text': 'contenido original', 'translation': 'yoda'}}
```

**Comment by Bipavez** [comment]
Gracias! Ehm, cuando le envío un texto muy largo me manda un json.decode.JSONDecodeError diciendome que el request es NoneType, pero ahí veré. ¡Saludos!
