### ISSUE TITLE
No se visualizan clientes en el mapa, pero se puede colisionar con ellos

### ISSUE THREAD

**Issue by felipehen** [IIC2233/syllabus#806]
Intentando crear clientes, los logro crear, pero no se ven sus imágenes. Se que estan ahi, por distintas cosas de mi programa, incluyendo que choco con ellos, pero no puedo verlos.

cabe mencionar que los creo ocupando el mismo proceso que ocupe para crear los otros elementos, como mesas y jugadores, y solo estoy teniendo problemas con los clientes

**Comment by danckoo1** [comment]
A primera vista se me ocurren dos posibles problemas que deberías revisar, el primero es que quizas escribiste mal los `path` de los sprites y deberia aprecerte un mensaje similar a `QPixmap::scaled: Pixmap is a null pixmap`  en consola; mi otra idea es que quizas tus clientes están siendo tapados por otros objetos de la ventana, por lo que algunos metodos que podrian resultarte utiles son `isVisible()` y `raise_()`, por lo que te sugiero buscarlos.

**Comment by felipehen** [comment]
muchas gracias, investigando sobre esos metodos solucione mi problema
