### ISSUE TITLE
Logging al importar datos

### ISSUE THREAD

**Issue by savelozo** [IIC2233/Syllabus#806]
Dentro de los eventos a considerar en nuestro logging debemos incluir aquellos relacionados a la extracción de datos desde nuestra googlesheet? Si es así, qué sería una 'Búsqueda exitosa' para esos casos? :)

**Comment by ifcarrera** [comment]
Sí, pon en los logs que pudiste obtener exitosamente las coordenadas desde Google maps y obtener la lista de países y ciudades desde google sheets.
