### ISSUE TITLE
BackEnd Objetos

### ISSUE THREAD

**Issue by enriquemolinare** [IIC2233/syllabus#807]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Estoy un poco confundido sobre en que momento mi programa utiliza el back end para procesar información y en que momento es el front end. Entiendo que el front end solo se usa para mostrar la interfaz y el back end para procesar información recibida del front. 
Mi duda es que si la comunicacion debe ser entre señales, los objetos que tienen el método de señales son del tipo Front-End. Entonces me pierdo si uso señales para comunicar a las ventanas con otros objetos que tambien usan señales. Entonces siempre sería Front End.

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by JadrinaDA** [comment]
Hola! Creo que te estás confundiendo entre lo que es parte del front-end y lo que utiliza la librería PyQt5. El front-end es todo lo que el usuario puede ver e interactuar con como tus ventanas, labels y botones. Estos tienen la posibilidad de emitir señales que luego son capturadas por objetos del back-end que pueden ejecutar ciertas acciones basadas en las señales que reciben. Todo objeto que herede de un QAlgo como por ejemplo QObject o QThread puede emitir señales al igual que las partes del front end pero como el usuario nunca ve estos objetos y no puede interactuar directamente con ellos se consideran parte del back-end de tu programa.  Tu back-end puede procesar una acción del usuario y crear el cambio correspondiente en el front-end vía una señal.  Por ejemplo al mover un personaje el usuario apreta una tecla y ve que el avatar o label del personaje se mueve, eso es front end, pero en el back-end un QObject podría estar enviando una señal al front-end diciendolé que el movimiento es válido y que mueva el label. Te queda más claro?
