### ISSUE TITLE
Carga de imágenes en ventanas creadas en Qt Designer

### ISSUE THREAD

**Issue by Miguel-Cox** [IIC2233/syllabus#807]
Hola, tengo una duda respecto a cuando cargo mis archivos ui.
Lo que pasa es que una vez creada mi Window, con todos los sprites correspondientes, las cargo en python y al abrirlas por ahí, solo aparecen los labels sin sprites.
Ya he probado con "show" y "raise_()", y al experimentar note que el label si existe (Probe hacerle setText y me aparecio el texto en el lugar correspondiente).

**Comment by milosoria** [comment]
@Miguel-Cox Me sucedió lo mismo! Lo que sucede es que desde Qtdesigner cuando cargas archivos desde la carpeta sprites, el path no queda: sprites/blabla, es decir "asume" que estas dentro de la carpeta sprites. Entonces cuando abres el archivo en python, no encuentra la carpeta respectiva (ejemplo: mapas). Si abres el archivo ui (el que guardas desde Qtdesigner) en tu editor de texto podrás ver el código xml del ui. Busca cuando carga los pixmap y agregale a los paths en el inicio: "sprites/".

**Comment by Miguel-Cox** [comment]
@milosoria Revisé los paths y estos me parecen correctos. (Quizas te entendi mal)
![Captura](https://user-images.githubusercontent.com/61402941/82615326-22d5e980-9b98-11ea-89cb-92d13eda22af.JPG)

**Comment by Miguel-Cox** [comment]
Borre el path completo y deje solo sprites/blabla y me funcionó.
Muchas gracias por la ayuda @milosoria !!.

**Comment by milosoria** [comment]
@Miguel-Cox Buenaa!!
