### ISSUE TITLE
Error Permiso Insuficiente

### ISSUE THREAD

**Issue by ibaeza1** [IIC2233/Syllabus#807]
Hola tengo un problema. Copie el codigo send_message(service,user_id,message)para mandar un mensaje del link que estaba en el enunciado  y mi service es service = build('gmail', 'v1', http=creds.authorize(Http())) y el scope es 'https://www.googleapis.com/auth/gmail.send' y me sale este error "<HttpError 400 when requesting https://www.googleapis.com/gmail/v1/users/ignaciabaeza.i%40gmail.com/messages/send?alt=json returned "'raw' RFC822 payload message string or uploading message via /upload/* URL required">"  y no se que significa porque deberia funcionar
Muchas gracias

**Comment by HenryBlairG** [comment]
Yo también tengo un problema similar. Traté con todos los scopes que recomiendan en la página y siempre me sale el siguiente error:

An error occurred: <HttpError 403 when requesting https://www.googleapis.com/gmail/v1/users/me/messages/send?alt=json returned "Insufficient Permission">

AYUUUDAA :(

**Comment by kenzoak** [comment]
Hola, no soy ayudante pero tuve el mismo problema. Tuve que cambiar el scope del codigo a `'https://mail.google.com/'` Este da permiso para hacer cualquier cosa con el mail. Para que funcionen tienen que borrar el archivo que se creo antes, si no seguirá usando otro
