### ISSUE TITLE
Problema al instalar Qt Designer

### ISSUE THREAD

**Issue by santiagoolivos** [IIC2233/syllabus#808]
No he podido instalar correctamente Qt designer. En un principio se me instalo pero solo se abría cuando apretaba el código de python que se descargo en al instalar PyQt5-tools, es decir, cuando trataba de abrir Qt designer desde la aplicación misma no me funcionaba. Para solucionar esto intente desinstalando PyQt5 y PyQt5-tools e instalandolos nuevamente, luego intente de instalarlos desde la pagina web, pero en ambas ocaciones me salían las siguientes advertencias:
![WhatsApp Image 2020-05-21 at 18 23 09](https://user-images.githubusercontent.com/62113105/82612892-020a9580-9b92-11ea-944e-50a36406204c.jpeg)
![WhatsApp Image 2020-05-21 at 18 03 37](https://user-images.githubusercontent.com/62113105/82612916-164e9280-9b92-11ea-96b8-0709bfb9ec25.jpeg)

**Comment by santiagoolivos** [comment]
Se me olivdo poner que luego de desinstalar PyQt5-tools por primera vez, nunca más pude abrir Qt designer y siguo sin poder hacerlo

**Comment by fdoflorenzano** [comment]
Hola @santiagoolivos,

Para tener un poco más de información, ¿cómo lo estás desinstalando? ¿has revisado si quedan archivos en tu computador del programa después de desinstalar?

Ojalá lo puedas solucionar,
Saludos.

**Comment by santiagoolivos** [comment]
Ya logré solucionarlo, gracias
