### ISSUE TITLE
Flechas se sobreponen con el fondo de su contenedor

### ISSUE THREAD

**Issue by kalarconvl** [IIC2233/syllabus#808]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! No entiendo bien cómo funciona VELOCIDAD_FLECHA. Puse que la velocidad de la flecha es 2, su posición se actualiza cada 0,1 segundos y aparece una flecha nueva cada 1 segundo y me pasa esto:

![Ventana de Juego 25-10-2020 12_34_52](https://user-images.githubusercontent.com/68581172/97111596-840d6600-16be-11eb-8629-a0b5668a9da3.png)

Funciona bien pero se sobreponen entre ellas. ¿Algún consejo? ¿ O será solo porque está muy baja la velocidad?

**Comment by JuaniAndres** [comment]
Hola @kalarconvl 
El parámetro ````VELOCIDAD_FLECHA````  sirve para especificar cuanto se va moviendo la flecha en pixeles por segundo. Respecto a lo segundo que widget ocupaste para hacer el área de la izquierda y que método ocupaste para darle fondo?

**Comment by kalarconvl** [comment]
Hola @JuaniAndres ! Para los cuadrados morados usé Frames en QtDesigner y el fondo se lo puse con setstylesheet ¿por qué?

**Comment by JuaniAndres** [comment]
Ya perfecto lo que está pasando es que todos los elementos dentro de tu Frame están heredando el estilo y por lo tanto se están sobrescribiendo los fondos transparentes de tus labels con el fondo morado del Frame. Para arreglarlo te recomiendo revisar la siguiente [issue](https://github.com/IIC2233/syllabus/issues/748) o la otra es que a cada flecha le especifiques que su fondo sea transparente para sobrescribir el fondo morado.
Me cuentas si te sirvió y cualquier duda que tengas.
Éxito con la tarea

**Comment by kalarconvl** [comment]
@JuaniAndres Recién pude verlo y me funcionó lo de la otra issue de poner QFrame#nombre{...} muchaas gracias!
