### ISSUE TITLE
Acceso APIS

### ISSUE THREAD

**Issue by Kitaps** [IIC2233/Syllabus#808]
Hola, 

tenía una duda respecto a como tenemos que acceder a las APIS

Por ejemplo para sheets, está el quickstart que editandolo un poco facilmente puedes acceder a la info que necesitamos.

Por otro lado, tratando de armar lo mismo pero en requests no me resulta para nada, me tira miles de errores que no me hacen setnido. 

Llevo harto rato intentando hacerlo funcionar y bueno, supongo que tenemos que hacerlo funcionar con requests pero puede que esté equivocado.
Como tiene que ser? 

|------------------------------------------------------------|
|En caso de que si tenga que ser con requests: |
|------------------------------------------------------------|
Cuando al head le paso un diccionarió me tira:
TypeError: expected string or bytes-like object
Pero cuando le paso un string (lo que no deberá ser pero como eso esperaba probé) me tira:
AttributeError: 'str' object has no attribute 'items'

Google me dice que lo segundo está mal (como suponía) pero no logro encontrar respuesta frente al primer error. Que estaré haciendo mal?

**Comment by ifcarrera** [comment]
Con la de Google Sheets sí puedes usar el wraper, por lo que puedes basarte en el _Quickstart_, para la de Maps y Twitter debe ser mediante `requests`. ¿Son estas últimas las que no te funcionan?
Salu-two

**Comment by Kitaps** [comment]
Nono era la de sheets precisamente, muchas gracias :)

**Comment by ifcarrera** [comment]
Puedes autentificarte con OAuth, pero para hacer las solicitudes tienes que ocupar `requests`

**Comment by inmadariaga** [comment]
😢
