### ISSUE TITLE
Diccionario de Información Tiempo Ciudades

### ISSUE THREAD

**Issue by emeiese** [IIC2233/Syllabus#808]
Hola! En la sección 3.1.2 del enunciado dice que hay que poder consultar como mínimo esas características de la 1 a la 8. Sin embargo, por lo que me di cuenta, el diccionario de una ciudad entrega 39 observaciones para un día, que corresponden a las observaciones de esas características de 5 días cada 3 horas. Es decir, dado un día tenemos la 'temperatura maxima' para las 6 de la mañana, 9 de la mañana, etc... hasta el final del día, para cada día).
En ese caso, si nos piden retornar la temperatura máxima de un día en cierta ciudad, deberemos sacar el promedio? o escogemos una hora random del día?.
Por otro lado, qué hacemos con el tipo de observaciones descriptivas? por ejemplo, lasasociadas a 'weather description'? Porque también tendré 39 de esas. (Lo mismo ocurre con wind 'speed', y 'clouds')

De antemano, muchas gracias! :smile:

**Comment by rihanuch** [comment]
Hola, para eso esta temp_max, no debes sacar el promedio

Analogamente debes hacer lo mismo para cada cosa que se pide, utiliza la informacion directa del diccionario y no la otra

Respecto a las descriptivas, retorna todas

**Comment by emeiese** [comment]
@rihanuch 
![image](https://user-images.githubusercontent.com/37163233/41951909-4c4ffb1e-799b-11e8-89f6-500de72a0a6c.png)
Si te fijas, temp_max es distinta para cada momento del día :( Esas corresponden a las observaciones entre 3 y 24 del primer día más o menos :( (Igual es una medida rara, no debería cambiar si es exactamente el máximo. Pero asumo que con eso se refieren al 'pronóstico del máximo' en ese momento del día, o algo aśi. En ese caso, tendría más sentido sacar el promedio. Lo mismo ocurre para la temp_min) 

Con respecto a lo último que dijiste, cuando el usuario me pida el pronóstico a 5 días de 6 ciudades, voy a tener que retornar entonces las 39*6 observaciones?

**Comment by JorgeBdelaT** [comment]
+ 1!!

**Comment by nachocontreras** [comment]
Queda a su criterio los valores a utilizar, sea promedio, máximo, moda (en el caso de descripciones), u otra.

Y sobre la cantidad de observaciones a retornar cuando sea pronóstico, se debe retornar todas los parámetros elegidos, por cada día.

**Comment by emeiese** [comment]
@nachocontreras No sé si te entendí bien. Corrígeme si estoy mal: El diccionario me entrega una lista con aprox 40 observaciones totales: 8 observaciones por día (con observaciones me refiero a a la lista de todos los parámetros de temp_min, temp_max, etc), que corresponden a 8 momentos del día. **Para entregar la informacion asociada al pronóstico del día X, se puede utilizar, para las estadísticas cuantitativas, el promedio (o máximo), y para las cuantitativas, la moda correspondiente a las 8 observaciones del día.**
Finalmente, el programa debe retornar las 5 listas asociadas a estos 5 días, que contengan el promedio/maximo, y las modas para cada parámetro.

**Comment by nachocontreras** [comment]
@emeiese Correcto 👌
