### ISSUE TITLE
Formato fecha reportes UV

### ISSUE THREAD

**Issue by CmPoblete** [IIC2233/Syllabus#809]
Hola, no entiendo cual es el formato de la fecha que entrega el reporte UV?

**Comment by JorgeBdelaT** [comment]
Tengo la misma duda, porque date da un numero que no se relaciona con ninguna fecha a simple vista, mientras que date_iso si lo hace, 2018-06-27T12:00:00Z, que formato debemos seguir?

**Comment by JorgeBdelaT** [comment]
Ademas, al pedir el pronostico del indice UV, se salta un dia, el primer dia que me entrega es el 29
