### ISSUE TITLE
Contenido BackEnd y FrontEnd

### ISSUE THREAD

**Issue by milosoria** [IIC2233/syllabus#809]
Hola! tengo la duda si es que el proceso de definir si es posible que el mesero se mueva o no, a través de colisiones tiene que ir en el backend y enviar la posición final hacia el frontend o es posible tenerlo dentro del metodo keyPressEvent en el frontend.
De antemano, gracias!!

**Comment by cristozille** [comment]
Hola! Verificar si un movimiento es válido corresponde a relaciones de lógica, por lo que tiene que estar en el backend. Te refieres a eso?

**Comment by milosoria** [comment]
Sí, gracias!
