### ISSUE TITLE
Duda sobre comentarios en publicación

### ISSUE THREAD

**Issue by pepinofdz** [IIC2233/Syllabus#81]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Holaa! Tengo una duda sobre la distribución de puntaje, da lo mismo si es que en vez de imprimir los comentarios junto a su publicación, se da la opción de ver comentarios por separado? Puedo dejarlo especificado en el readme si es necesario.

De antemano, muchas gracias

**Comment by catalina-arcila** [comment]
Hola @pepinofdz, obvio que puedes! como dice el enunciado puedes crear todos los submenús que consideres necesarios. Lo importante es que mantengas los menús pedidos en el enunciado y que expliques en tu _README_ los que agregaste.
