### ISSUE TITLE
Sobre polimorfismo y clases abstractas

### ISSUE THREAD

**Issue by juacob** [IIC2233/Syllabus#81]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola me gustaria saber si implementar un metodo abstracto contaria como polimorfismo, encontre este link: https://www.freecodecamp.org/news/polymorphism-using-abstract-class-and-interface/#:~:text=As%20long%20as%20all%20the,or%20interface)%20is%20called%20Polymorphism.
que dice que si contaria pero queria confirmarlo. Muchas gracias!

**Comment by Gsalinas1506** [comment]
Hola! Perdón por la demora en responder :disappointed_relieved:

Según la definición de polimorfismo, tienes _overriding_ si dado un input con una estructura definida (por ejemplo, una lista, un objeto de tipo definido, etc...), este se puede procesar en objetos de tipo distinto y darte un output.

Un método abstracto es un método que las clases hijas deben implementar para poder ser instanciadas.

Por lo tanto, si tu método abstracto definido para distintas clases hijas puede recibir inputs de estructura similar, y darte un output, este **sí** contaría como polimorfismo 😄 ya que cada clase "trata" de forma distinta al input.
