### ISSUE TITLE
Duda con respecto a paths

### ISSUE THREAD

**Issue by FelipeA7** [IIC2233/syllabus#81]
Ya terminé la tarea y veo que está funcionando sin problemas.
Para guardar y cargar partidas, utilicé el comando `open("partidas.txt", "a")`, sin utilizar en ningún momento paths relativos ni absolutos. Mi duda es, considerando que voy a subir "partidas.txt" a mi repositorio y que además va a estar en la misma ubicación que el código principal, es correcto no haber utilizado paths cierto? Es decir, si el archivo que estoy abriendo está en exactamente la misma ubicación de mi código, no es necesario usar paths?

**Comment by jmwielandt** [comment]
Hola!

Antes que nada, eso es un path relativo. Básicamente dice "en el directorio actual, busca el archivo/directorio con este nombre/ruta a partir de este". 😄 

A nosotros nos harán llegar sus carpetas T00 pero renombradas con sus nombres de usuario. Lo que pongan dentro nos va a llegar. Aclaro esto para que estén más tranquilos.

Saludos~

**Comment by FelipeA7** [comment]
Gracias!

**Comment by Eryimmy** [comment]
> Hola!
> 
> Antes que nada, eso es un path relativo. Básicamente dice "en el directorio actual, busca el archivo/directorio con este nombre/ruta a partir de este". 😄
> 
> A nosotros nos harán llegar sus carpetas T00 pero renombradas con sus nombres de usuario. Lo que pongan dentro nos va a llegar. Aclaro esto para que estén más tranquilos.
> 
> Saludos~

Hola, yo tengo una duda con respecto  a eso, ¿eso de ahi es un path relativo sin importar que estamos usando  especificamente "/" ? 
O sea yo hice eso mismo y me funciono en otro computador pero creo que funciona bien porque tenia el mismo sistema operativo.
Para el tema de la tarea vale con dejarlo como "/" simplemente o no? 
Salu2

**Comment by jmwielandt** [comment]
Hola!

¿A qué te refieres con estar usando "/"? Cuando comienza con un "/" (o "C:/", o "C:\"), es absoluto, de lo contrario, es relativo. Si quieres asegurarte, puedes iniciar tu path relativo con `./` (`./partidas`). El punto representa al directorio actual, del mismo modo que los dos puntos (`..`) representan al directorio padre del actual.

La librería `os` de python provee un string especial que contiene el separador de paths del sistema operativo en el que estés ejecutándolo. Este es `os.sep`.

Por último, también puedes usar el método os.path.join de la librería os. :smile:

Saludos~

**Comment by Eryimmy** [comment]
> Hola!
> 
> ¿A qué te refieres con estar usando "/"? Cuando comienza con un "/" (o "C:/", o "C:"), es absoluto, de lo contrario, es relativo. Si quieres asegurarte, puedes iniciar tu path relativo con `./` (`./partidas`). El punto representa al directorio actual, del mismo modo que los dos puntos (`..`) representan al directorio padre del actual.
> 
> La librería `os` de python provee un string especial que contiene el separador de paths del sistema operativo en el que estés ejecutándolo. Este es `os.sep`.
> 
> Por último, también puedes usar el método os.path.join de la librería os. 😄
> 
> Saludos~

Me refiero a que por ejemplo:
¿Es valido simplemente colocar ` open('partidas/puntajes.txt', 'a')` usando simplemente el "/" ?
o es obligatorio que usemos "os" para que quede para cualquier sistema (ya sea "\\" o el "/"). 
Esa era mi duda Salu2

**Comment by jmwielandt** [comment]
Hola!

No es obligatorio, pero sí recomendado para evitar a toda costa tener problemas. Las versiones más recientes de w10 aceptan "/" como separador válido, sin embargo no tengo información sobre versiones anteriores.

Saludos~
