### ISSUE TITLE
Consulta sobre el tablero con el que se trabaja después de solucionarlo en el menú y sobre el tablero

### ISSUE THREAD

**Issue by ignaverb** [IIC2233/Syllabus#81]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/21)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/20)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola!
Tengo las siguientes dudas, si me pueden ayudar se los agradecería muchsimo!

1.- Al estar trabajando en el menú de acción con, por ejemplo el archivo 3x3.txt, y decido solucionar el tablero ([4]), luego si el usuario decide seguir en el menú de acción y quiere, por ejemplo [2] Validar bombas y tortugas o [3] validar solución, el tablero respecto al cual se hacen estas acciones es el original (3x3.txt) o el nuevo, solucionado en la acción [4]?

2.-Mis funciones están hechas para trabajar con tableros creados a partir de la función cargar_tablero, donde aquellos strings con números los transformo a enteros, lo cual funciona en el menú de acción, mi duda viene pues en el archivo que subieron de ejemplo_tableros.py los tableros vienen con los números tipo str, puedo especificar en mi readme que en el caso de que se quieran testear mis funciones con tableros aislados sin la necesidad de realizar cargar_tablero estos deben tener los números tipo str?

Saludos y gracias!!!

**Comment by Hernan4444** [comment]
Hola @ignaverb 

* Sobre la duda 1, revisa esta issue #51 
* Sobre la duda 2, cómo se indica en el enunciado (adjunto foto) los tableros serán con `str`.
![image](https://user-images.githubusercontent.com/15641721/227722874-77280dfb-a055-4812-b164-b813fd3a52a2.png)

Si quieres trabajar con `int`, lo que recomiendo es tener una función auxiliar que al inicio de cada función transforme cualquier `str` que sea dígito (buscar sobre `isdigit`) a un `int`. Así partes de la base que el tablero tendrá únicamente str como sale en enunciado.

Saludos c:

**Comment by ignaverb** [comment]
@Hernan4444 Gracias!
Había pensado lo de la función auxiliar, pero no aumentaría el tiempo de computo, por ejemplo en una función recursiva, demasiado?

Saludos!

**Comment by Hernan4444** [comment]
Además,

Recuerda seguir las reglas de las issues. La regla 7 dice:

> Evita el hacer issues en que en se traten varias dudas de temas desligados, ya que esto crea conflictos al querer buscar un tema en específico 😬. Mejor crea dos issues distintas si los temas no están relacionados 👍.

Esto es porque así podemos asignar correctamente la issue a la temática que corresponde en el compilado y es más facil buscar después para los demás estudiantes.

Saludos c:

**Comment by Hernan4444** [comment]
@ignaverb 

Para este caso no, sino igual puedes hacer que **nuestra función** aplique los cambios indicados con tu función auxiliar para pasar a `int` y luego llame a **otra función** encargada de solucionar un tablero, pero que esta segunda función asume todo con int, con eso no tiene que aplicar ninguna transformación en la parte recursiva.

Saludos c:
