### ISSUE TITLE
contenidos: composición, agregación y herencia

### ISSUE THREAD

**Issue by mjgutierrez1** [IIC2233/Syllabus#81]
¿cuando tenemos clases con relaciones de composición, agregación y herencia, hay formas específicas de programar cada una de esas relaciones (formas de programar que python identifica como composición, agregación o herencia)?

Por ejemplo, si creo las clases Persona y Profesor, donde la clase Persona tiene como método comer() y la clase profesor hereda ese mismo método de la clase Persona, ¿hay una forma estándar de programar eso, tal que python reconoce que la clase Profesor debe heredar el método comer de la clase Persona?¿o yo al programar tengo que definirle a la clase Profesor los métodos que hereda de la clase Persona, como comer(), de la misma manera que se define cualquier método para cualquier clase?

**Comment by mjgutierrez1** [comment]
Lo pregunto porque además de las diferencias entre composición, agregación y herencia al momento de hacer diagramas de clase, no hemos visto nada de cómo porgramar para esas cosas, por lo que siempre asumí que sólo era un concepto para hacer un diagrama de clases y así ordenarse antes de ponerse a programar.

Pero me entró la duda porque en los contenidos de esta semana dice "Duck typing es una característica de algunos lenguajes que hace que el polimorfismo sea menos atractivo, ya que el lenguaje por sí sólo es capaz de generar comportamiento polimórfico **sin la necesidad de implementar el polimorfismo a través de la herencia**." Entonces, como ahí sale implementar algo a través de la herencia, pensé que la herencia debería tener una forma específica de ser implementada al programar.

**Comment by mjgutierrez1** [comment]
Perdón lo largo de la duda, pero quiero agregar otra cosa para preguntar todo: la duda anterior me hizo pensar que a lo que se referían en la frase "Duck Typing es una..." es que cuando implementaron polimorfismo en la clase Variable y la clase Ingreso, esa es justamente la forma de implementar herencia, poniendo Ingreso(Variable), de donde python entiende que la clase Ingreso es heredera de la clase Variable al poner a esta última dentro del paréntesis (y que por lo tanto, la clase Ingreso hereda el atributo self.data de la clase Variable), ¿eso es así o estoy suponiendo cosas nada que ver?

**Comment by mjgutierrez1** [comment]
Acabo de cachar que eso viene explicado en el otro documento de esta semana... yo no tengo dudas

**Comment by andresfdezc** [comment]
Para que todo lo que escribí no se pierda, lo voy a dejar aquí igual:

1. Python en particular no tiene como diferenciar sintácticamente entre agregación y composición. Sin embargo, es completamente explícito en como se define la herencia. Por ejemplo:

```python
class ClasePadre:
    def __init__(self, apellido):
        self.apellido = apellido:
    
    def caminar(self):
        print("Estoy caminando")


class Hijo(Padre): # Se ponen entre paréntesis las clases desde donde hereda hijo
    def __init__(self, nombre, apellido):
        self.nombre = nombre
        super().__init__(apellido)
```
Esto lo repasamos en la ayudantía virtual en #57 y es una de las materias que se evaluarán mañana. En resumen, la clase `Hijo` que hereda de `Padre` recibe todos los métodos y atributos definidos en esta clase. Es decir, tendrá el método `caminar()` sin necesidad de redefinirlo. Es útil para no repetir código cuando necesitamos hacer una clase que es una versión más específica de otra.

2. Sobre polimorfismo, este es un concepto que describe la situación en que varias clases (digamos `B`, `C` y `D`) heredan de una misma clase (`A`) que tenía algún método (`mover()` por ejemplo), pero que al menos una de las clases pudo haber redefinido. Es decir, el mismo método con el mismo nombre puede funcionar de muchas (poli) formas (morfismo) dependendiendo de qué clase sea el objeto sobre el que se ejecuta.

Esto nos permite tener una lista con objetos de clases `A`, `B`, `C` y `D`,  y poder llamar al método `mover()` sin tener que preocuparnos de cómo esté definido en cada uno.

```python
for objeto in lista_variada:
    objeto.mover() # Este objeto puede ser de cualquier clase que herede de A
```
3. Podrás notar que al final el polimorfismo es solo una cosa de nombre, por lo que se pueden poner objetos en la lista anterior que no hereden de A. Lo único que se necesita es que tengan implementado un método con el nombre `mover()`.
