### ISSUE TITLE
Uso de property tablero_transformado en property piezas_explosivas_invalidas

### ISSUE THREAD

**Issue by emivenezian** [IIC2233/Syllabus#81]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hice primero la property tablero_transformado, y ahora estoy haciendo piezas_explosivas_invalidas. **Mi pregunta es, se puede usar la primera property para facilitar el codigo de la segunda?**

 El enunciado dice:
"def piezas_explosivas_invalidas(self) -> int:
Property que utiliza el tablero guardado como atributo y cuenta la cantidad de piezas explosivas que no son válidas para el tablero."

Si bien dice que utilizemos el tablero del atributo, cuando implementamos la property tablero_transformado estamos indirectamente usando el tablero original. Lo que yo estoy haciendo es trabjar incialmente con el original, pero cuando el codigo requiere tratar con las fichas explosivas, creo una variable con el tablero con objetos. Si no, igual se puede hacer con el orginal, pero es mas largo, porque habria que buscar cada atributo de la pieza de otra manera, en vez de usar la clase ya definida.

**Comment by ManuelV03** [comment]
Hola, si es posible hacer uso de otras funciones que te faciliten el trabajo en otro método o property, de hecho, este es uno de los beneficios que trae el trabajo con métodos y funciones. Mientras no alteres el formato del método o de la property todo debería estar bien. Avisame si se aclaró tu duda.
