### ISSUE TITLE
TimeTuple, dst value

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#81]
Hola, estoy haciendo el conversor de fechas a segundos para el programa y así trabajar con las tasas de producción de recursos, pero no sé cómo lidiar como los cambios de hora, porque si recolectan recursos el 12 de mayo a las 23:30 y luego lo hacen 45 minutos después, es decir a las 23:15 del mismo día (cambio al horario de invierno) entonces el programa reconocería que el tiempo transcurrido fue de -900 segundos. El DST value arreglaría eso pero necesito poder calcular el día, mes y año del 2º sábado de mayo y de agosto, pero no encuentro nada relacionado que sirva (encontré algo pero era en C# usando un módulo de C#).

¿Qué puedo hacer?

**Comment by jachavarri** [comment]
Hola, si no me equivoco, si usas datetime para el formato de las fechas, dia y hora, puedes simplemente restarlas para obtener la diferencia.

Espero que te sirva :P

**Comment by jmwielandt** [comment]
Gracias, solo que eso no arregla el problema de los cambios de hora que sumarían o restarían 3600 segundos :(

**Comment by Pipelao** [comment]
Según yo eso es muy específico, pero si quieres averiguar puedes buscar esto del huso horario, del utc y mantenerlo igual en ambas fechas.

Saludos.
