### ISSUE TITLE
Feedback AC02 - OOP

### ISSUE THREAD

**Issue by Hernan4444** [IIC2233/syllabus#81]
# Feedback General
A continuación se detallan errores comunes encontrados en las actividades entregadas para la AC02. No duden en comentar dudas o postear issues con dudas relacionadas a esta. Pueden etiquetar issues al usar el signo gato (#) y el número de la issue. En este caso, #81. 

## Errores en la definición de clases:
- No definir correctamente atributos dentro de una clase. Recuerde que deben utilizar `self` para que el valor quede asignado a un atributo de la instancia. (`self.atributo = valor`). De lo contrario, el valor desaparece una vez que termina el método.

- Acceder de forma errónea a los atributos y métodos. Dentro de la declaración de la clase, para acceder a un atributo o método de la instancia, se accede mediante `self.nombre_de_lo_que_accedo`. Fuera de la declaración de la clase, se hace sobre el objeto en vez de `self`. Por ejemplo:
```python
class Persona:
    def __init__(self, nombre, edad):
        self.nombre = nombre
        self.edad = edad

    def cumplir_años():
        edad_nueva = self.edad + 1  # la variable edad_nueva solo existe mientras se llama el método
        self.edad = edad_nueva     # aquí se usa self.edad para actualizar el atributo de la instancia

c = Persona(“Cristian”, 39)
print(c.nombre)
c.cumplir_años()        # aquí se usa el objeto
```

- Confundir la declaración de herencia de una clase con los atributos de la instancia.
```python
class Gaseosa(Bebestible): # en la línea de class se declara la herencia de la clase completa
    def __init__(self, marca): # recibe, al instanciar, algo llamado marca
        super().__init__() # aquí llama al constructor de la clase madre, que es Bebestible
        self.marca = marca # la marca de la gaseosa se guarda como un atributo de la instancia
        ...
```
- Una instancia de una clase puede tener como atributo un valor que sea una instancia de otra clase, y eso funciona. Es más, esto permite relacionar clase. Un Plato puede recibir una instancia de Bebida y una instancia de Pizza.
```python
class Plato:
    def __init__(self):
        self.pizza = None
        self.bebestible = None
```
Y un Chef puede hacer:
```python
class Chef(Persona):
    def armar_plato(plato):
        b = elegir_bebestible()    # b es un objeto de tipo bebestible
        p = elegir_pizza()            # p es un objeto de tipo pizza
        plato.pizza = p                # plato es un parámetro de Chef, no es un atributo de Chef, no lleva self
        plato.bebestible = b        # como plato es un Plato, tiene atributos pizza y bebestible
```

## Properties
- Deber ser usadas correctamente. Es incorrecto llamar directamente al atributo (`_calidad`) dentro de la clase, en lugar de la property `calidad`. Necesitan repasar el uso de **setters**. Por ejemplo:
```python
class Pizza:
    …
    def revisar_tiempo(self):
        if self.tiempo_de_preparacion >= 30:
            self._calidad -= 30
```
El efecto que se apunta es correcto, pero se modifica directamente el valor del atributo “escondido” `_calidad`, cuando la property `calidad` es aquella encargada de obtener y modificar ese valor. Incluso, si la calidad de la pizza hubiese sido menor a 30, esa línea puede bajarlo a negativo, cuando la calidad era siempre positiva (y de eso se aseguraba el `setter` de `calidad`). Entonces, hubiese sido más correcto cambiar la última  línea por `self.calidad -= 30`, así, se utiliza el setter para asignarlo. (Para una mejor explicación véase la [issue #28](https://github.com/IIC2233/syllabus/issues/28))

## Herencia
- Si heredan de una clase sin `__init__()` no es necesario el `super().__init__()` en las clases hijas.
- Este ejercicio no tenía multiherencia, las `Persona` no heredaban de `Personalidad`, sino que contenían una (composición). Y solo era la clase `Ayudante` la que debía recibir una instancia de personalidad en su constructor:
```python
class Ayudante(Persona): # ayudante es una persona, entonces tiene el comportamiento de Persona
    def __init__(self, nombre, personalidad): # recibe una personalidad de clase Personalidad.
        super().__init__(nombre)
        self.personalidad = personalidad # es parte del ayudante su personalidad, un atributo
```
- Cuando una clase hereda de otra, esta obtiene **también las properties**. Es decir,  las pueden usar en la clase hija y no volver a definirlas. Estas se comportan igual que como escritas en la clase madre. (Por ejemplo, la property `calidad` de `Bebestible` que se hereda automáticamente a `Agua` y `Gaseosa`)

## Requerimientos incorrectos
Lean bien los enunciados para entender los requerimiento, si no los entienden, pueden preguntar.
- Utilizan strings para las personalidades siendo que en el `main.py` aparecen como clases y en los requerimientos del enunciado también. El código que escriban debe ser compatible con el código que se entrega.
- Se piden nombres específicos de clases para hacer los archivos funcionar, adherirse a esos nombres; de lo contrario, puede que no funcionen las partes de código que se entregaron y no se podrá corregir su entrega..
- Los platos no son pizzas, sino que tienen pizzas (composición/agregación), lo mismo con los bebestibles.
- Hacen que la comida la hagan los platos o la misma comida, pero quien hace la comida es el `Chef`. Por ejemplo, aparece cosas del estilo:
```python
class Pizza:
    def __init__(self):
        posibles_ingredientes = ['pepperoni', 'pina', 'cebolla', 'tomate', 'jamon', 'pollo']
        self.ingredientes = []
        for i in range(3):
            ingrediente = random.choice(posibles_ingredientes)
            self.ingredientes.append(ingrediente)
        ...
```
El algoritmo para escoger los ingredientes es correcto, pero no es responsabilidad de `Pizza` el escogerse los ingredientes, es el `Chef` el que elige. Luego, esa porción de código debió escribirse en el método `cocinar` de `Chef`, y una vez escogidos los ingredientes, se creada la instancia de pizza: `pizza = Pizza(ingredientes)`. Lo mismo corría para la elección de marca de gaseosa y al escoger entre agua y gaseosa.

## PEP8
- No se evalúa en las actividades, pero deben practicar para las tareas y las futuras AC's formativas. (Revisar reglas consideradas  [aquí](https://github.com/IIC2233/syllabus/blob/master/Tareas/Descuentos.md))

**Comment by biaguilera** [comment]
Hola, ¿que sucede si en el excel aparece mi numero de alumno repetido una vez con Falso y otra con Verdadero? Mi numero de alumno es 17203546

**Comment by Hernan4444** [comment]
@biaguilera problema solucionado 👍 

Saludos ✌️

**Comment by biaguilera** [comment]
@Hernan4444 Gracias por la solución :D
