### ISSUE TITLE
Caracteres prograpost

### ISSUE THREAD

**Issue by Juampisaez** [IIC2233/syllabus#81]
Hola, segun el enunciado, un prograpost puede tener cualquier caracter. Pero que pasa si mis caracteres son solo espacios, esta permitido?

**Comment by aljara97** [comment]
Hola @Juampisaez, esta duda ya fue resuelta en la issue #72. Recuerda revisar las issues anteriores antes de publicar una. Además puedes revisar el detalle de en la issue #7 

Mucha suerte con tu tarea :bird:

**Comment by Juampisaez** [comment]
gracias, habia buscado y tal vez no lo vi
