### ISSUE TITLE
Problemas con editores de código

### ISSUE THREAD

**Issue by Juan-Carlos-Ferrer-Barros** [IIC2233/syllabus#81]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

Hola, tengo un problema con los editores de código. En Sublime Text 3, al correr mi código, éste se queda "pegado" en el primer input() que se encuentre, en otras palabras, cuando llega a algún input(), al escribir algo, pongo Enter y no pasa nada. Por otro lado, en VSCode, si me funcionan los inputs, pero no logra encontrar los archivos .csv. Me sale "No such file or directory".

**¿Cual podría ser el error en cada editor de código?**

Gracias de antemano.

**Comment by Tsbalart** [comment]
Hola @Juan-Carlos-Ferrer-Barros, el error de sublime no sabria decirte. Pero el error de Vscode, te recomendaria comprobar que estas abriendo toda la carpeta con el programa al ejecutar los archivos .py.

**Comment by ajuanchuto** [comment]
¡Hola!

Yo no uso Sublime Text 3, pero si uso VSCode. Puede ser que en VSCode te esté pasando que no tienes tu `archivo.csv` en la misma parte que tu `archivo.py` o también que el path que estás usando para intentar abrir el `archivo.csv` no esté correcto. 

Revisa esas dos cosas y dime si te funciona, suerte 😄
