### ISSUE TITLE
Duda de lo que va a entregar el usuario en la línea de comando para el menú

### ISSUE THREAD

**Issue by cataruze** [IIC2233/Syllabus#81]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/20)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/19)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Holaaa, en la parte del menú, no me quedo claro si el usuario me puede dar el nombre de una estación de dos palabras, por ejemplo: San Joaquin ? Y si esto ocurre debó ejecutar el menú o lo tomo como un error del usuario?

**Comment by CrisHD935** [comment]
Hola! Puedes asumir que la estación siempre tendrá sólo una palabra

**Comment by karlamunoz14** [comment]
Hola y cuando el cliente elige la opcion de asegurar_Ruta y debemos pedirle una estacion de destino, tambien podemos asumir que sera una sola palabra? ademas, el como yo asumire que el usuario me entregara el input puedo comentarlo en el codigo? o debe ir en el redme?Muchas gracias

**Comment by CrisHD935** [comment]
Si, también puedes asumir eso, y como dices mejor comentar dicha asunción en el readme.
