### ISSUE TITLE
Entrega Tarea 7

### ISSUE THREAD

**Issue by DquezadaO** [IIC2233/Syllabus#810]
Los que no vamos a entregar la tarea 7 tenemos que hacer algo para no tener el 1 o simplemente no entregamos y nos quedamos con las notas que tenemos?

**Comment by sebacruzd** [comment]
Hola,
No tienes que inscribirla y no tendrás problemas.

**Comment by matiasreyes121213** [comment]
Cuando te refieres a que "No tienes que inscribirla" me surgió la duda, ¿Había que inscribir la tarea? D:

**Comment by sebacruzd** [comment]
Se hará un cuestionario pronto y se hará un anuncio respectivamente en relación a eso.
