### ISSUE TITLE
self.frame ayudantia 8

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2233/syllabus#810]
Hola no entiendo muy bien para que se usa el self.frame en la ayudantia 8. Vi el video pero no me quedo muy claro.

**Comment by Alonsinho1** [comment]
Hola! Espero que te encuentres bien!

Mira aqui esta una respuesta super detallada explicando que era self.frame  #761

**Comment by dsepulveda3** [comment]
Vale gracias
