### ISSUE TITLE
Agregar elementos a un json

### ISSUE THREAD

**Issue by ValentinaAlvarezG** [IIC2233/Syllabus#810]
Hola! estoy teniendo unas dudas con respecto al manejo de archivos json. Por que por ejemplo quiero guardar las configuraciones de los usuarios en un json, como diccionarios, pero por ejemplo cuando agrego cosas quedan como asi {blabla:blabla} {blabla:blablabla}, entonces despues cuando los quiero leer me tira el error: json.decoder.JSONDecodeError: Extra data: line 1 column 26 (char 25)

No sé si en verdad tengo que hacer algo extra para leerlo bien

**Comment by mfanselmo1** [comment]
Hola!
Primero que nada, como se dijo en la sala de ayuda y en [796](https://github.com/IIC2233/Syllabus/issues/796), no es necesario guardar las configuraciones de los usuarios entre sesiones.
Ahora, si quieres guardar diccionarios en un json, solo es necesario el metodo `json.dump(tu_data, file)`. Como dice [aqui](https://stackoverflow.com/questions/12309269/how-do-i-write-json-data-to-a-file).
Probe con eso, luego cargandolo con `json.load(file)` y no tuve ningun problema.

**Comment by ValentinaAlvarezG** [comment]
Eso estaba intentado pero por ejemplo si quiero ir guardando cosas sucesivamente, en el
with open ("archivo", "a") uso "a" para ir agregando cosas después, no de una vez, entonces ahí es que se genera el problema. porque si agrego algo con una corrida queda {}, si lo corro de nuevo {}{} y ahí después no me deja usar el load.

**Comment by mfanselmo1** [comment]
Estuve investigando y parece que no es buena practica hacerle directamente otro dump al mismo archivo json. Encontre varias soluciones, y la que mas me gusto fue esta:
```
def append(file, data):
	with open(file, 'r', encoding='utf-8') as f:
		antiguo = json.load(f)
	antiguo.update(data)
	with open(file, 'w', encoding='utf-8') as f:
		json.dump(antiguo, f)
```
Al final cada vez que quieres agregar algo al json, lees lo que habia antes y lo reescribes, no escribes directamente sobre el archivo json, ya que eso tira el error que dices.

**Comment by ValentinaAlvarezG** [comment]
Intentaré con eso, pero estoy casi segura de que tambien lo intente hacer así pero como que no se hacía el update entonces solo se agregaba un null, pero lo revisaré de nuevo c:
