### ISSUE TITLE
Editar en python objetos creados en Designer

### ISSUE THREAD

**Issue by notyourlasagna** [IIC2233/syllabus#810]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola! En Designer hice un QVBoxLayout, llamado verticalLayout, y me gustaría añadirle otros widgets a base de cuando corran ciertas funciones que hice en Python. Pero no sé si es posible acceder a este Box desde Python y modificarlo, ni cómo. Como para meterle un QLabel cuando ocurra cierta acción por ejemplo, desde una función en Python.

**Comment by bvasquezm** [comment]
Hola @notyourlasagna!

Los objetos creados en designer efectivamente son manipulables dentro de python, al igual que cualquier otro objeto, les asignas un nombre al cual tendrás que referirte si quieres editarlo. Al cargar el archivo.ui dentro de tu Widget, también referencias a este último con el self dentro de 
```python 
uic.loadUi(‘algo.ui’, self)
```
Por lo tanto, sí es posible referirte a cualquier objeto qt, que hayas creado dentro de designer, siempre y cuando lo hayas cargado en tu widget (atributos como cualquier otro). Ahora, sí tu intención es **agregar** cosas a un layout ya creado, podrías tener que pensar en crearlo de otra forma con previamente. Espero haya quedado claro :)

**Comment by notyourlasagna** [comment]
Hola @bvasquezm 
Gracias por tu ayuda, pero no me queda claro lo último que dijiste. Yo tengo un QVBoxLayout que creé en designer y le quiero agregar un QLabel cuando se ejecute una función,  que es justo lo que mencionaste al final, pero no pude entender bien lo de 'crearlo de otra forma con previamente'. El QVBoxLayout lo nombré como Vbox. Y en esta linea, 

uic.loadUi(‘algo.ui’, self)

ese algo.ui sería el archivo de mi ventana, y sería todo?

**Comment by notyourlasagna** [comment]
La verdad tampoco entendí bien cómo modificar los objetos ya creados que no son layouts, ya sean qlabels o lo que sea. Cómo puedo modificar por ejemplo un QLabel que creé en Designer, en VSC?

**Comment by bvasquezm** [comment]
Claro, el archivo.ui correspondería al de tu ventana. Para referenciar los QObjects dentro tu QWidget, simplemente los llamas como te señalaba, algo del estilo ``self.nombre_objeto``. Te recomiendo revisar la documentación sobre QWidgets y sus layouts, ahí podrás averiguar muchísimo sobre lo que puedes y no puedes hacer con ellos, en particular creo que te puede servir revisar el método ``setLayout()``. Saludos!
