### ISSUE TITLE
Caída del programa al correrlo en terminal

### ISSUE THREAD

**Issue by fedezang** [IIC2233/syllabus#811]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, al ejecutar el archivo de mi tarea en la terminal, funciona bien. Pero cuando quiero comenzar la fase de ronda, el programa se cae y devuelve el siguiente mensaje:
zsh: segmentation fault  python3 main.py
No entiendo que significa esto o por qué se cae mi programa.
¿Cuál podría ser el problema?

**Comment by gatochico** [comment]
Hola @fedezang !

Añadiste el _hook_ de errores incluido en la semana 09 del curso? Dejo el [link](https://github.com/IIC2233/contenidos/blob/master/semana-09/1-interfaces-gr%C3%A1ficas.ipynb) del notebook, se encuentra al fondo. Al ser incluido en tu código, este permite dar un mensaje de error más detallado de tu programa.

Saludos y avísanos cómo te va!
