### ISSUE TITLE
Creación de señales

### ISSUE THREAD

**Issue by tedroppelmann** [IIC2233/syllabus#811]
Hola! Quería saber si las señales si pueden ir creando a medida que corre el programa, i.e, que no estén desde el comienzo pero que se creen al activar algo...

**Comment by jitorcas** [comment]
Hola! @tedroppelmann 

Puedes crear funciones que **conecten** señales y otras funciones que las **emitan**. No sé si efectivamente esa era tu duda con ir creando señales a medida corre el programa. ¿Para que necesitas ir creando señales a medida avanza el programa?

**Comment by tedroppelmann** [comment]
En mi programa instancio una clase (personaje) dentro de la función de otra clase (juego), pero luego en otra función intento conectar señales pero no se conectan unas con otras. No sé si me explico

**Comment by tedroppelmann** [comment]
Sorry, ya solucione el problem... me faltaba un super.__init__ :v gracias de todos modos!

**Comment by jitorcas** [comment]
Genial! jaja justo estaba respondiendo. 

De todas formas si ocurre de nuevo, podrías verificar si recibes correctamente las instancias en las funciones. 

Éxito! :100:
