### ISSUE TITLE
Caída programa al correr ejemplo semana-10 en terminal

### ISSUE THREAD

**Issue by fedezang** [IIC2233/syllabus#812]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola, al correr el último ejemplo del archivo 1-pyqt-qthreads.ipynb de la semana-10 en vscode, este funciona perfectamente.
Al correrlo en la terminal se producen cerca de 100 unidades de comida, el programa se cae y envia lo siguiente:

QThreadPipe: Unable to create pipe: Too many open files
Has creado 136 unidades de comida

QEventDispatcherUNIXPrivate(): Cannot continue without a thread pipe
zsh: abort      python3 ejemplo.py

¿Cuál es el problema y cómo podría solucionarlo?
Gracias de antemano

**Comment by aaossa** [comment]
Hola @fedezang , al parecer es un problema relacionado con que ese proceso (el iniciado con el comando `python3 ejemplo.py`) está abriendo muchos archivos, una vez por cada instancia de `Comida`. En mi caso no tuve problemas para abrirlo varias veces, pero quizás en tu sistema operativo ese límite es menor, no es algo relacionado con el código en sí. La verdad dudo que sea algo que te afecte durante la tarea, y al menos la idea de ese ejemplo era mostrar que, en general, el uso de señales en conjunto a *threading* permite evadir potenciales problemas de concurrencia. ¿Te ocurrió lo mismo con el penúltimo ejemplo?
