### ISSUE TITLE
Elección país en filtro de información

### ISSUE THREAD

**Issue by fgbruna** [IIC2233/Syllabus#812]
Es necesario poner una opción para que el usuario pueda elegir solo el país y no una ciudad en específico,obteniendo así las estadísticas para el país en general?

**Comment by ifcarrera** [comment]
La idea es que de la lista de países, el usuario elija uno, luego le despliegas la lista de ciudades de ese país y elige uno. Las consultas deben ser para esa ciudad de ese país.

**Comment by fgbruna** [comment]
Gracias! @ifcarrera
