### ISSUE TITLE
Obtener pronostico diario

### ISSUE THREAD

**Issue by JorgeBdelaT** [IIC2233/Syllabus#812]
Hola, estoy viendo de obtener el pronostico diario, sin embargo, con la versión que no se paga, el resultado son por horas del dia. Se entregan los datos cada 3 horas, por lo qye hay 8 valores para cada parametro. En este caso, debemos promediar los valores o tomar alguna hora fija? y que pasa con la descripcion? Saludos!

**Comment by nachocontreras** [comment]
Hola!

Se está hablando de eso en la issue [808](https://github.com/IIC2233/Syllabus/issues/808)

**Comment by JorgeBdelaT** [comment]
pero tampoco han respondido :(
