### ISSUE TITLE
Setear punto de referencia

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2233/syllabus#813]
Hola me gustaría saber como setear como punto de referencia del mapa la esquina superior izquierda de la grilla. Al cargar la info de mapa.csv el mesero me queda fuera de mi grid, quiero poder solucionar esto.

**Comment by fdoflorenzano** [comment]
Hola @dsepulveda3,

Una forma de hacerlo es componiendo *widgets* dentro de otros, ya que las posiciones son relativas entre *widgets*. En uno de los videos subidos esta semana se habla de este tema, que te puede ser de ayuda. Está en Canvas, Módulo Semana 9, Página "Más dudas anónimas", el segundo video.

Saludos.
