### ISSUE TITLE
Agregar un Qlabel que no estaba definido en Qdesigner y no aparece

### ISSUE THREAD

**Issue by chineseJack564** [IIC2233/syllabus#813]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola, yo hize la venta principal del juego en Qdesigner y todos me aparecen bien, sin embargo, ahora quiero implementar el drag an drop de los elementos de la tienda.
Para eso, defini un clase de Draglabel y Droplabel a como subclase de Q label, ambos funciona bien solo.

Pero el problema llega cuando quiero que estos aparecen en la ventana principal tambien, definino en el init :
`def __init__(self):
        super().__init__()

        # definicion pinguinos drag
        self.pin1 = DragLabel([1100, 240, 91, 91], path_p1)
        self.pin1.show()
        
        #definicion de cuadrados drop
        self.c1 = DropLabel([670, 560, 51, 51])
        self.c1.show()
        self.setupUi(self)`
Y ambas aparecen en ventanas separadas
Si empiezo con el setupUi, no aparecen nada.

No se como puedo resolver este problema.
Saludos!

**Comment by furcelay** [comment]
Hola @chineseJack564 !
Me parece que el problema está en que las clases que creas no saben en qué ventana están contenidas. Recuerda que al instanciar un `QLabel` dentro de una ventana se hace por ejemplo de la forma `self.label = QLabel('texto', self)`, como puedes ver se le pasa la ventana (`self`) al `QLabel`, que el `QLabel` toma como atributo `parent` para saber en qué ventana está contenido.

Lo mismo debes hacer cuando creas tu propia clase, en el init debes pasarle el parent como `super().__init__(parent)`. Como no lo estás haciendo ellos creen que son 'libres', y aparecen cada uno en su propia ventana.

Espero que eso resuelva tu problema, saludos! 😄
