### ISSUE TITLE
UnicodeDecodeError al ejecutar el ejemplo

### ISSUE THREAD

**Issue by vamarambio** [IIC2233/Syllabus#813]
Hola, cuando trato de ejecutar el codigo de ejemplo de la API de Google Sheets me arroja el siguiente error  con este traceback:
![screenshot_2](https://user-images.githubusercontent.com/26117424/33236392-c6b51ffa-d230-11e7-9100-79c071a89ed0.png)

Busque en Google la excepción en la libreria especifica de la API y no encontre nada. Gracias de antemano.

**Comment by Arcoirisky** [comment]
Hmmmm ¿Intentaste poner arriba del programa?:

#!/usr/bin/env python
# -*- coding: utf-8 -*-

Te alega por utf-8. Intenta con eso O: Es una idea :S Cualquier cosa dime.

**Comment by vamarambio** [comment]
Lo intente y sigue saliendo el mismo error :(

**Comment by ifcarrera** [comment]
Qué sistema operativo tienes?
Qué versión de Python estás usando?
Si lo corres por la terminal te tira el mismo error?
Saludos

**Comment by vamarambio** [comment]
En orden:
- Windows 7 Professional SP 1
- Python 3.6.2
![image](https://user-images.githubusercontent.com/26117424/33237112-bf2e1012-d248-11e7-93ff-8a285e6d7b3a.png)

**Comment by ifcarrera** [comment]
puedes hacer push de tu codigo? avísame

**Comment by vamarambio** [comment]
Listo, el codigo esta en quickstart.py y por si acaso subi el client_secret.json por si el error esta ahi dentro

**Comment by ifcarrera** [comment]
Viendo el error que te tira desde la terminal, es porque ese directorio no existe. 
Prueba cambiar la línea del _quickstart_: 
`credential_dir = os.path.join(home_dir, '.credentials')`
por
`credential_dir = './credenciales'`

Si esto funciona, debería crearte el archivo `sheets.googleapis.com-python-quickstart.json` dentro de la carpeta `credenciales` que se debería crear en la misma carpeta de tu tarea. 

Quedo atento, saludos

**Comment by vamarambio** [comment]
Nop, pasa lo mismo. El problema viene cuando se ejecuta la linea `credentials = tools.run_flow(flow, store, flags)`
Gracias igual

**Comment by ifcarrera** [comment]
Sí, pero eso para porque estás leyendo el archivo que se crea en el path `.credentials`. En la terminal te arroja `No such file or directory`, va por ahí el error. Trata de cambiar el path.

**Comment by Arcoirisky** [comment]
Hola!!!
Al hacer lo que se les pide me ocurrió lo siguiente o:

![photo4960723631479039970](https://user-images.githubusercontent.com/26121402/33237428-966772ae-d252-11e7-93c3-f337d5b6c5a7.jpg)

Después de dejar corriendo un poco el programa te pide que aceptes desde tu cuenta google el acceso al sheet mientras Python entrega un link.

¿Aceptaste lo anterior? Quizás lo rechazaste sin querer el permiso, entonces intenta leer cosas que retornan vacío y, por ende, no puede leer utf-8. Porque está vacío! O:!!! 

Fíjate si es eso O: Es una idea xD Después de aceptarlo todo funciona perfecto :D
