### ISSUE TITLE
Nombre ciudad y países

### ISSUE THREAD

**Issue by valerojasm** [IIC2233/Syllabus#814]
Hola!

Se supone que hay que ingresar ciudad y país, y chequear si esta ciudad está en el json. Tengo varias preguntas sobre esto: Hay que chequear que esta ciudad exista con el país ingresado asociado a ella? El país se va a ingresar en el formato del json (sigla)?

Ya preguntaron algo como esto pero no me quedó claro.
Gracias

**Comment by naquiroz** [comment]
Tengo la misma duda!

**Comment by Clemente24** [comment]
+1! Misma duda respecto a los países!

**Comment by Unknomads** [comment]
+1 Misma duda!

**Comment by rihanuch** [comment]
Hola!

Hay que verificar la que la ciudad exista en el pais ingresado, ya que sino se esta pidiendo algo que no existe
Respecto al formato de los paises, se puede asumir que se entrega en el formato eel json, por ejemplo, Chile->CL
