### ISSUE TITLE
Los pingüirines deben hacer caso a los pasos incorrectos?

### ISSUE THREAD

**Issue by Gsalinas1506** [IIC2233/syllabus#814]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! En el enunciado se dice que los pingüirines deben moverse acorde a las flechas que oprime el usuario, pero no se especifica si el pingüino debe moverse **aún cuando** el paso de baile comandado por las teclas haya sido incorrecto. ¿Debemos asumir entonces que el pingüirin se moverá acorde a las teclas apretadas, aún cuando un paso de baile sea marcado como incorrecto?

**Comment by aljara97** [comment]
Hola @Gsalinas1506, los pingüirines deberán cambiar su sprite solo cuando se realiza un paso correcto. En caso de que realicen un paso incorrecto deben mantenerse en su posición neutra.

**Comment by Gsalinas1506** [comment]
ok, gracias!
