### ISSUE TITLE
Problema de fluidez

### ISSUE THREAD

**Issue by Aloncarrasco** [IIC2233/syllabus#814]
Hola,
cuando mi personaje se mueve se ve muy poco fluido, porque puede ser?

**Comment by Alonsinho1** [comment]
Hola! Podrias explicar a que te refieres con fluidez?

Probablemente estas haciendo que el personajes se mueva mucho en una direccion en especifica.

**Comment by Aloncarrasco** [comment]
Si, era algo asi, mi problema era que programe una animación de movimiento pero no espere a que se terminara esa animacion para que el personaje se siguiera moviendo, entonces el procesador movia al personaje super rapido y se saltaba las animaciones. ahora hice  que el back end esperara a que terminara la animación y queda más fluido, gracias igual. Lo dejare por si a alguien le sirve.
