### ISSUE TITLE
Hoja nueva dentro de la planilla

### ISSUE THREAD

**Issue by JaviFerrada** [IIC2233/Syllabus#814]
Podemos asumir que la hoja estará creada y solo tenemos que rellenar con los datos o hay que crearla?

**Comment by ifcarrera** [comment]
Hola! Deben crearla :). 
Salu10 (hexadecimal)

**Comment by ajahr95** [comment]
@ifcarrera a que hoja hace referencia? nuestra hoja de logging, de la base de datos o de un link ajeno que se nos entregue  ?

**Comment by ifcarrera** [comment]
La hoja donde deben escribir los logs.

**Comment by B-Dominguez** [comment]
Se puede crear manualmente? O debe ser desde el programa? y es una hoja dentro del mismo spreadsheet que la hoja de las ciudades?

**Comment by ifcarrera** [comment]
Debe ser creada por su programa. Lo segundo está en el enunciado. 
Saludos

**Comment by B-Dominguez** [comment]
Graciaas y ciertoo perdón por lo segundo!

salu pez/2

**Comment by JaviFerrada** [comment]
Esta hoja debe contener solo la información de una ejecución del programa, o es un histórico?

**Comment by ifcarrera** [comment]
La idea es que sea histórica. 
Salu-(la cámara secrete en la secuencia de Harry Potter)
