### ISSUE TITLE
Crear nueva hoja

### ISSUE THREAD

**Issue by nlvargas** [IIC2233/Syllabus#815]
Hola, 
Estoy definiendo asi la nueva sheet, siguiendo el ejemplo de https://developers.google.com/sheets/api/samples/sheet#add_a_sheet

Pero estoy teniendo problemas con la autentificación. Cuando ejecuto mi código desde el simulador de python de esta pagina https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/get me funciona perfecto cuando ocupo Google OAuth 2.0 como autentificación, pero no sé cómo realizar esa autentificación en Python. 

Finalmente, en esta página (https://developers.google.com/api-client-library/python/guide/aaa_oauth) hablan de cómo realizar la autentificación con Python pero no sé qué poner en "redirect_uri".

En resumen, desde la linea en que defino "spreddsheetID" está todo bien para abajo. El problema es la autentificación. Y por si acaso SÍ cambié SCOPES a: 
SCOPES = ["https://www.googleapis.com/auth/drive",
          'https://www.googleapis.com/auth/spreadsheets',
          "https://www.googleapis.com/auth/drive.file"]

Por favor ayuda :( He perdido todo el fds en esto y hay otros ramos que pasar jajaja

**Comment by ifcarrera** [comment]
La autentificación es la misma que para leer la sheet.
PD: NO subas trozos de código.

**Comment by ifcarrera** [comment]
Por qué scopes lo tienes definido como una lista?

**Comment by nlvargas** [comment]
Leí que se podían poner múltiples scopes usando una lista, pero igual lo he probado con cada uno de ellos (que son los que salen en la documentación). Utilizando exactamente la misma función get_credentials() del ejemplo, no me deja autenticar. Me aparece el siguiente error:

> raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://sheets.googleapis.com/v4/spreadsheets/1swfWGq0is5PKvn2Y3qeCR4jkR-tOcszAFDC4kHlEEQc:batchUpdate?alt=json returned "Request had insufficient authentication scopes.">


>

**Comment by ifcarrera** [comment]
Leíste #782?

**Comment by nlvargas** [comment]
Recién! Ahora me funcionó. Muchas gracias
