### ISSUE TITLE
Desaparición de flechas en paso combinado

### ISSUE THREAD

**Issue by JoMarchant** [IIC2233/syllabus#815]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

En el enunciado se indica que si un paso combinado no se presiona a la vez, se considera como paso incorrecto.
Tengo dos dudas:

**¿Se capturan las flechas aunque haya habido un paso incorrecto?, ¿Hay un intervalo de tiempo máximo para que se consideren presionadas a la vez?**

**Comment by knight-who-say-ni** [comment]
Hola @JoMarchant !!

En el enunciado, justo antes, dice que "Una flecha es acertada si hay una sección de esta dentro de la zona de captura en el momento en que el jugador presiona la tecla, para esto considera que la flecha tiene una altura ALTO_FLECHA y la zona de captura ALTO_CAPTURA. Deberás cambiar el color de la zona de captura correspondiente a la tecla presionada, ya sea si la jugada es correcta o no (ver la Figura 9), y las flechas acertadas deben desaparecer de la pantalla".

Como puedes ver, la desaparición no considera si las flechas son parte de un paso correcto o no, asi que deberían desaparecer independiente de ello. 
Exito programando!!

**Comment by JoMarchant** [comment]
Muchas gracias!! Y que pasa respecto a mí segunda duda?, hay un márgen de tiempo maximo para que sea realizado "a la vez"?

**Comment by knight-who-say-ni** [comment]
Eso aparece en la sección de pasos de baile del enunciado: "deberás apretar las teclas
correspondientes en el teclado, presionando **simultáneamente** las teclas en el caso de que haya más de una
en la fila, y según esto determinar si se acertó a las flechas".

Así, deberán estar presionadas al mismo tiempo 👍. Para reconocer esto, el método KeyRelease te podría ser de ayuda :eyes:.
