### ISSUE TITLE
Volver a iniciar un QThread

### ISSUE THREAD

**Issue by jirarrazaval** [IIC2233/syllabus#816]
Si tengo una clase ```class Thread(QThread)``` y en otra clase le hago ```start()```, se ejecuta lo que dinfiní en ```run(self)``` del thread.
Mi duda es que esto sólo ocurre una vez. Cómo puedo hacer que este thread vuelva a como startear??? He tenido muchos problemas con esto porque sólo me funciona una vez y despés nunca más y necesito que funcione como cada vez que pase algo, no sólo la primera vez. :( Qué se hace en estos casos o cómo puedo solucionar esto??

**Comment by kadroguett** [comment]
Hola @jirarrazaval 
Antes de contestar necesito saber algo, lo que definiste en el `run(self)` se terminó de ejecutar o quieres reiniciarlo mientras está andando?

**Comment by jirarrazaval** [comment]
Se terminó de ejecutar lo que quería, de hecho incluso intenté ahora en el final del ```run(self)``` ponerle un ```self.quit()``` pero sigue estando igual.  No sé en todo caso si hay que poner algo como explícito para terminar de ejecutar el thread. Sabes cómo solucionarlo??

**Comment by kadroguett** [comment]
Que buena! sorry no responderte antes, estaba investigando que podía ser

**Comment by jirarrazaval** [comment]
Muchas graciass enserio ajajjaj no me habia dado cuenta!

**Comment by kadroguett** [comment]
De nada, éxito en tu tarea!!
