### ISSUE TITLE
Validación correo

### ISSUE THREAD

**Issue by meretamal** [IIC2233/Syllabus#816]
Hola, en el enunciado se menciona que puede tener solo un punto en el dominio. Este puede estar al principio o al final del dominio, o solo puede estar a la mitad? Además, cuando se dice que después de un punto solo pueden haber caracteres del abecedario, esto incluye mayúsculas y solo cuenta para el punto al final del dominio?

Gracias de antemano.

**Comment by shantifabri** [comment]
hola, @leolivares
una pregunta, que pasa con las mayúsculas? nunca se aclara muy bien si pueden ir o no mayúsculas en el correo y si es así en que partes si y en cuales no?

**Comment by leolivares** [comment]
@shantifabri No se especifica nada de mayúsculas, por lo tanto es suficiente con que cumpla con lo pedido.

Sin embargo, por lo general, antes del "@" la dirección es _case insensitive_, por lo tanto no hay diferencia se se ingresan mayúsculas. Por otro lado, después del "@", es _case sensitive_, por lo que se espera que sea todo en minúsculas.
