### ISSUE TITLE
keyPressEvent no me funciona cuando las flechas aparecen o después de esto

### ISSUE THREAD

**Issue by SebastianFerra** [IIC2233/syllabus#816]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, no llevo mucho de la tarea, pero logré que cuando clickeo comenzar bajen flechas por los 4 carriles y desaparezcan cuando llegan abajo, además antes de apretar comenzar logré que si clickeo una tecla de WASD esa caja cambie de color en la zona de ritmo pero esto solo funciona antes de que aparezcan las flechas, una vez aparecen las flechas (las cuales implementé con un código muy parecido al de los contenidos de la semana10 parte Qthreads) el keyPressEvent deja de funcionar pero el keyReleaseEvent funciona relativamente bien, a qué se puede deber y como puedo solucionarlo?

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by furcelay** [comment]
Hola @SebastianFerra !

Estuve probando tu código y el problema parece estar relacionado con los `QComboBox`, puedes probar que si seleccionas el dorpdown de dificultad ya no cambiará el color en la zona de captura porque ser redirige a ese `QComboBox`. Revisa la issue #738 que es sobre ese tema.

Saludos! :smile:

**Comment by SebastianFerra** [comment]
Hola, resolvió en parte mi problema, ahora noté funciona antes de darle a comenzar pero cuando le doy a comenzar debo apretar cualquier boton (con o sin uso) para que vuelva a funcionar, esto genera un problema porque no debería tener que deshabilitar el botón de pausa para poder jugar

**Comment by furcelay** [comment]
Encontré una mejor solución a la que mencioné antes, ahora PyQt5 incluye un método de focus que indica a donde son dirigidos los eventos de teclado, el problema es que por defecto los dirige a los QComboBox o a QPushButton cuando están activos (al hacerles click) y por eso no llegan a tu zona de ritmo. 

Para resolver éste problema basta cambiar la política de focus del Widget que cause problemas, en código puedes hacerlo con el método `setFocusPolicy` cambiandolo a *Not Focus*:
```python
mi_widget.setFocusPolicy(Qt.NoFocus)
```
Puedes hacerlo también en QtDesigner:
![image](https://user-images.githubusercontent.com/61999313/97193186-7ec81e00-1787-11eb-816c-d516ecc5fa18.png)

Si lo aplicas a los botones y al selector de dificultad debería funcionar bien.

Saludos!

**Comment by SebastianFerra** [comment]
Muchisimas gracias, veré como me va!
