### ISSUE TITLE
Consulta 2, ¿filtrar según fecha o número de seguidores?

### ISSUE THREAD

**Issue by matiaseche** [IIC2233/Syllabus#816]
Me queda una duda sobre esta consulta:
Se piden 20 tweets escritos en la ubicación el los últimos 2 días.
¿Deberíamos obtener los 20 tweets más recientes y luego ordenarlos según la cantidad de followers?
Otra forma sería obtener la mayor cantidad posible de tweets para el ese intervalo de días (creo que es 100) y obtener los 20 tweets con mayor cantidad de followers (del usuario).

**Comment by ifcarrera** [comment]
Lo segundo es lo correcto.
Salu-área de un cuadrado de lado sqrt(2)

**Comment by matiaseche** [comment]
En ese caso, podría pasar que se repita un usuario que haya hecho varios tweets. En caso de que esto ocurra lo vuelvo a mostrar o cualquier aparición repetida se omite?

Gracias!

**Comment by ifcarrera** [comment]
Queda a tu criterio, menciónalo en tu readme.

**Comment by dvogaz** [comment]
@ifcarrera Se consideran los tweets emitidos en las últimas 48 horas exactamente?, o solo los emitidos ayer y hoy sin importar la hora en que hago la consulta?

**Comment by ifcarrera** [comment]
Diría que 48 horas es lo mejor, de todas maneras ponlo en tu readme

**Comment by dvogaz** [comment]
Vale, gracias 😄

**Comment by bedefrunner** [comment]
@ifcarrera no encuentro la forma de que twitter me retorne 100 tweets de las últimas 48 horas, solo es capaz de enviarme 100 tweets de los últimos 7 días. Hay alguna forma de hacerlo? O simplemente obtengo los 100 tweets de los últimos 7 días y selecciono 20 que cumplan con que fueron posteados en las últimas 48 horas, para finalmente ordenarlos según numero de followers del usuario?

**Comment by ifcarrera** [comment]
@bedefrunner lo segundo.
