### ISSUE TITLE
Drag and Drop

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2233/syllabus#817]
Hola!Cuando se implementa el drag and drop, más específicamente cuando se arrastra el chef o mesa y se coloca en el mapa , el chef o mesa debe quedar en la posición a la que se arrastro o puede simplemente quedar en una posición valida aleatoria?

**Comment by kadroguett** [comment]
Hola @RonaldoSosa 
 El chef o la mesa deben quedar en la misma posición en la que se sueltan

**Comment by RonaldoSosa** [comment]
Entendido!Gracias

**Comment by kadroguett** [comment]
De nada, éxito en tu tarea!!

**Comment by dlmed** [comment]
En el mismo hilo, me está pasando lo mismo. En qué parte de los métodos se le debe pasar la "posición relativa" a la cual se clickeó el QLabel al hacer el drag?
