### ISSUE TITLE
Notificar sucesos de log en la interfaz

### ISSUE THREAD

**Issue by Fhguinez** [IIC2233/Syllabus#817]
Hola! En una parte del enunciado dice: 
> deberás notificar, a través de la interfaz, los sucesos anteriormente descritos
>
refiriéndose a los sucesos de log.
¿Es esto correcto? Porque al ser un simple seguimiento orientado al programador, no tiene relevancia para el usuario ver eso, ¿será más correcto imprimir en la terminal los sucesos?

Saludos

**Comment by fgbruna** [comment]
Concuerdo en que me hace **mucho** más sentido que se comunique por la terminal, y si no es así, en que parte de la interfaz deberíamos comunicarlos?

**Comment by fgbruna** [comment]
Up :(?

**Comment by TomasSalvadores** [comment]
Efectivamente, lo ideal es que sea por la consola.
Debido a que en enunciado sale lo contrario, se aceptarán ambas formas! Sin embargo se les recomienda que notifiquen por consola. Notarán que es mucho mas sencillo además de las razones que ustedes indican.

Disculpen las molestias y suerte con lo que queda!

**Comment by fgbruna** [comment]
Muchas gracias @TomasSalvadores  !

**Comment by Fhguinez** [comment]
Gracias!
