### ISSUE TITLE
Duda punto 3.1.2, requests a nuestra api

### ISSUE THREAD

**Issue by kenzoak** [IIC2233/Syllabus#817]
En este punto dice: 

> El lugar para el que se piden los reportes deberá poder ser recibido por tu API de las siguientes maneras: 
> 1. Nombre de ciudad
>  2. ID de ciudad, según un JSON que puede ser encontrado en este enlace
> 3. Coordenadas geográficas (latitud y longitud)

Mi duda es si podemos elegir una de estas 3 formas para llamar a nuestra api, o si tenemos que crear 3 métodos distintos (con urls distintas) para cada manera de pedir un reporte?
Gracias

**Comment by Bipavez** [comment]
Y otra pregunta, ¿Puedo verificar del lado del cliente (al ingresar una nueva ciudad a la lista) si es válida y que ese ingreso acepte los tres tipos de parámetros?  _Y por lo tanto estandarizar la forma en que la API recibe los requests_

**Comment by shantifabri** [comment]
Y otra pregunta mas, ¿las ciudades que ingrese el cliente en que formato serán? ¿el nombre y país?¿ el id de la ciudad?¿ o a eso se refiere en realidad el punto 3.1.2, que el cliente puede ingresar una ciudad de esas formas?
