### ISSUE TITLE
Diferencia ventana qt designer con ventana ejecutada en vs code

### ISSUE THREAD

**Issue by sigualt** [IIC2233/syllabus#817]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, tengo una duda de porque al ejecutar la ventana en qtdesigner se me visualiza la ventana como quiero, pero al importar el archivo.ui en vscode y ejecutarlo, la ventana disminuye bastante su tamaño y hay cosas que salen cortadas. Intenté usar el set.geometry que vi una issue para redimensionar la ventana, pero este solo me cambia el tamaño de la ventana y no todo para que quede igual a la ventana de qtdesigner. En otras palabras, la ventana no solo se encoge, sino que también algunos labels no aparecen igual que en el qtdesigner. Adjunto imágenes para que se visualice el problema. Saludos, y gracias de antemano!

<img width="721" alt="2020-10-25 (1)" src="https://user-images.githubusercontent.com/69644598/97122834-6e705e80-1707-11eb-9a27-bcbfbbb3fc8a.png">
<img width="1080" alt="2020-10-25 (2)" src="https://user-images.githubusercontent.com/69644598/97122839-74663f80-1707-11eb-95b5-d2761c3f6679.png">

**Comment by YehudaGurovich** [comment]
Me pasa lo mismo, pero me basé en las medidas de vsc. No estoy seguro cual es la manera correcta.

**Comment by bibustos** [comment]
Holaa, a mi me paso lo mismo, y lo arregle cambiando la resolucion de mi computador,  creo que cuando tienes una resolucion distinta a la que trae designer por defecto las relaciones de aspecto se bugean y no funcionan bien.

**Comment by sigualt** [comment]
Hola, no me funciono cambiar la resolución alguna otra cosa mas que se pueda hacer??

**Comment by gatochico** [comment]
Hola @sigualt !

Probaste cambiando la configuración de tamaño de texto de tu computador?

Si vas a configuración > pantalla, te debería salir esta opción:

![image](https://user-images.githubusercontent.com/37161120/97437577-72b49b80-1902-11eb-8f09-ea22528509dc.png)

Trata poniendola en 100 y cuéntanos cómo te va!

**Comment by sigualt** [comment]
Ahí me funciono!! Muchas gracias!!
