### ISSUE TITLE
Layouts y QWidgets

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2233/syllabus#818]
Hola! Cuando defini una imagen y delimite su posición y tamaño con el metodo resize y move respectivamente , cuando inserte esta imagen en un layout este ignoro las medidas que habia implementado previamente, hay alguna forma de que el layout no haga esto?

**Comment by fdoflorenzano** [comment]
Hola @RonaldoSosa,

Sí, eso ocurre al usar ingresar *widgets* directamente en *layouts*, ya que estos último se encargan del posicionamiento y tamaño, por lo que ignora otras cosas. No estoy completamente seguro si se puede prevenir ese comportamiento de *layouts*, ya que es el punto de usar *layouts*, habría que investigar en la documentación. 

Si no quieres que ocurra, una opción entonces es no usar *layouts*. Otra opción es que si tu problema es específico a imágenes, lo que puedes hacer es alterar los pixeles mismos. Un *layout* afecta sus hijos directos, como el *label* donde tienes una imagen, pero no necesariamente los pixeles. Tal vez escalando los pixeles en vez del *label* encontrarás lo que necesitas.

Saludos.
