### ISSUE TITLE
enlaces a las sheets de ciudades y log

### ISSUE THREAD

**Issue by BeaGaete** [IIC2233/Syllabus#818]
Hola! Cuando apretó estos enlaces en la interfaz el navegador me solicita entrar a mi mail uc y recién ahí me deja verlas. La duda que tengo es que cuando revisen la tarea uds van a poder acceder con su mail a estas sheets?

**Comment by ifcarrera** [comment]
Si la sheet la vuelves pública también te pide entrar?

**Comment by BeaGaete** [comment]
No, con la púbica no, entonces la vuelvo pública :) ?

**Comment by BeaGaete** [comment]
solo habilito read o read y edit ?

**Comment by ifcarrera** [comment]
Read y edit para que se pueda escribir sobre ella.

**Comment by BeaGaete** [comment]
Muchas gracias!!!
