### ISSUE TITLE
case sensitive

### ISSUE THREAD

**Issue by ciquezada** [IIC2233/Syllabus#818]
Hola!, ¿hay algún input que sea case sensitive?

**Comment by rihanuch** [comment]
Hola! Te refieres a qlguba seccion en especifico?

**Comment by ciquezada** [comment]
no no, me refiero a cualquier sección, ya que me parece que para el correo no importan las mayúsculas y también creo haber escuchado que para las ciudades tampoco importan, entonces para aclarar que no me esté equivocando con esto, ¿Hay algo que sea case sensitive? (ya que priori me parece que no)

**Comment by rihanuch** [comment]
Si no sale en la documentacion de cada api entonces no deberias tener conflictos.
En general es bueno echarle un ojo a la documentacion de las apis que se usan para asi poder entender mejor como funcionan

Saludos!
