### ISSUE TITLE
Movimiento puffles

### ISSUE THREAD

**Issue by antoniaalcayaga** [IIC2233/syllabus#818]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola, 

En el enunciado dice que los puffles se mueven solo al presionar correctamente las flechas hacia la derecha y hacia a la izquierda. Tengo duda frente a 2 situaciones en las que no se si el puffle se debería mover o como se debería mover.

1. Si dentro de un paso hay flechas hacia la derecha y hacia la izquierda, y este fue ejecutado correctamente. **¿Hacia donde se mueve el puffle?**

2. Si un paso fue ejecutado incorrectamente, pero dentro de el habían flechas hacia la derecha o la izquierda, y fueron capturadas (es decir contadas, a pesar de que el paso completo estuviera incorrecto), **el puffle se debe mover? o por ser el paso incorrecto debe quedarse quieto al igual que los pingüinos?**

Ambas situaciones se solucionan si lo que quieren es que el puffle SOLO se mueva ante PASOS (en el enunciado dice flechas) correctos hacia la derecha y hacia la izquierda (con esto me refiero a que no sean combinados, que contengan solo una flecha hacia la derecha o la izquierda)

Gracias! :)

**Comment by gatochico** [comment]
Hola @antoniaalcayaga !

Efectivamente, el puffle solo deberá reaccionar antes pasos que estén compuestos **únicamente por una flecha a la derecha o una flecha a la izquierda**.

Saludos y éxito programando!
