### ISSUE TITLE
buena manera de evitar "Rate limit exceeded"?

### ISSUE THREAD

**Issue by rjgalvez** [IIC2233/Syllabus#819]
En la parte de hacer los request a twitter me ha pasado un par de veces, por lo que pregunto cual seria una manera eficiente de evitar esto?
He buscado en internet y no he encontrado nada que realmente pueda usar.

**Comment by ifcarrera** [comment]
La mejor manera es hacer las request solo cuando el usuario quiera consultar algo, y hacerle la request específicamente para conseguir ese algo.

**Comment by rjgalvez** [comment]
Entonces, digamos que obtuve todas las coordenadas de las google sheets.. Para las request de trending topics y de tweets en una ubicacion, tendría que pedirle al usuario que elija de que ubicacion? de esta manera enviaria el request de esas coordenadas.
Si no fuera asi tendría que enviar request de **todos** los lugares que tenga, me imagino que seran muchos por lo que serian muchas request y obtendria Rate Limit Exceeded o no?

**Comment by ifcarrera** [comment]
En el enunciado está como debe ser la interacción con el usuario. Te recomiendo volver a leerlo con mayor detalle.

**Comment by rjgalvez** [comment]
Toda la razon jajaj, me quede pegado en la parte de la api de twitter y no lei de nuevo la parte de la GUI! gracias por la ayuda
