### ISSUE TITLE
Problema con señales: UnicodeEncodeError

### ISSUE THREAD

**Issue by TriniVial** [IIC2233/syllabus#819]
hola, cuando creo una señal dentro de las clases que importo desde Designer me sale un error que no se como arreglarlo.
UnicodeEncodeError: 'ascii' codec can't encode character '\xf1' in position 2: ordinal not in range(128)

**Comment by danckoo1** [comment]
Hola, por casualidad no utilizas la letra ñ al nombrar la señal?, que por lo general al hacer variables con la ñ surge este error y solo basta con cambiar la ñ por cualquier otra letra para solucionarlo

**Comment by TriniVial** [comment]
siii! graciasss
