### ISSUE TITLE
Pasos incorrectos en formula de aprobación y combo actual

### ISSUE THREAD

**Issue by antoniaalcayaga** [IIC2233/syllabus#819]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, 

Tengo una duda respecto a que son los pasos incorrectos en la formula de la aprobación. En especifico mi duda es si dentro de los pasos incorrectos o fallidos se cuenta cuando el usuario marca una tecla y no hay ninguna flecha para atrapar, pero la marca igual. En teoría se marco mal pero eso no provoco que un paso creado por el programa fuera incorrectamente ejecutado.  Si no es así, solo se deben contar dentro de los pasos incorrectos a los pasos creados por el programa y que no fueron bien ejecutados por el usuario?

En esta misma linea quiero preguntar si el combo actual debe ir a cero si hago lo mismo que dije arriba (apretar la tecla no habiendo flechas, sin afectar a pasos creados por el programa)

Gracias :)

**Comment by manearaya** [comment]
Hola antoniaalcayaga!

Efectivamente, si se apreta una tecla sin que esté la flecha correspondiente se considera como un paso incorrecto. Cuando se haga esto el combo debería volver a 0. 

Con respecto a los pasos creados por el programa que el usuario no hace, si se ignoran completamente estos no se consideran como correctos ni incorrectos: por lo que no afectan al combo. Ahora, si ignoras sólo una flecha de un paso combinado entonces esto se consideraría como paso incorrecto. Puedes ver ejemplos de esto en la sección 5.2 del enunciado.

Espero haber respondido tu pregunta!

**Comment by antoniaalcayaga** [comment]
Holaa, gracias por responder.
Me queda solo una duda. Entonces si yo mantengo una flecha apretada todo el rato y no hay flechas que pasen por ahí, se contara como inifinitos pasos incorrectos o un paso incorrecto hasta que sea soltada? (entendiendo a infinito como un numero muy grande)

**Comment by manearaya** [comment]
Si aprietas una tecla, provocando un paso incorrecto, y la mantienes apretada debería contar como un (1) paso incorrecto. 

Esto porque según la sección 3.1 un paso es incorrecto cuando se **presiona** una tecla y no hay una flecha en la zona de captura correspondiente, o no se acierta a todas las flechas de un paso combinado.

Éxito con la tarea!
