### ISSUE TITLE
Duda interfaz y API

### ISSUE THREAD

**Issue by ciquezada** [IIC2233/Syllabus#819]
Hola,
El enunciado dice que las consultas a la API pueden hacerse por nombre, ID o por coordenadas pero de la interfaz solo menciona que se agregan ciudades al reporte solicitado por medio del nombre y país si es que aparecen en city.list.json. EDIT: ¿es la interfaz la que debe tener el city.list.json o debiera ser la API la que manejara esta informacion y retorne un success o fail si es que la consulta es valida?

¿Hasta que punto la interfaz o cliente debe asegurar una consulta correcta?

**Comment by ciquezada** [comment]
@Hernan4444  perdon por etiquetarte pero estoy muy confundido sobre esto y no queda tanto tiempo

**Comment by pcseisdedos** [comment]
Quizás lo que sale en #798 te sirva
