### ISSUE TITLE
Git detached head commit

### ISSUE THREAD

**Issue by pulpaulaa** [IIC2233/Syllabus#82]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/21)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/20)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
(No entendí cómo agregar la label de git a la issue)

Hola, iba a hacer mi primer commit y push para subir lo que llevo de la tarea, pero apreté mal varias cosas en el terminal y terminé creando una detached head (creo que así se llama) y sin querer hice commit ahí así que creo que ya no están en la branch master porque cuando hice checkout ya no existían los archivos, así que volví a hacer checkout a la detached head y ya no sé qué hacer para volver a lo que estaba haciendo antes y subirlo a mi repositorio :(
En google salía que debería crear una branch nueva temporal y hacer merge en la master, pero recuerdo que nos habían dicho que no hagamos más branches así que no sé qué hacer.

Ayuda por favor necesito seguir haciendo la tarea :c

**Comment by pulpaulaa** [comment]
(Lo que hice que hizo que pasara lo de detached head creo que fue cuando hice commit y se me olvidó poner -m y el mensaje entonces me pidió que pusiera un mensaje pero no me dejaba escribir así que impulsivamente cerré el terminal y después pasó eso cuando lo volví a abrir)

**Comment by Hernan4444** [comment]
Hola @pulpaulaa 

Lo más fácil y rápido para esta instancia es 
1. Clonar tu repo privado en otra parte de tu computador.
2. Copiar todos los archivos de la Tarea a ese nueva carpeta que clonaste en (1)
3. Hacer los comandos que enseñamos (git add, git commit -m"mensaje", git push)

Y luego eliminar la carpeta viaje que tiene el detached head. ¿Hay otras formas de solucionarlo? Si, pero requerirá un poco más de asistencia e iteraciones porque necesitamos ver expecíficamente qué cosas aparecen en tu consola. 

Saludos c:
