### ISSUE TITLE
warning: LF will be replaced by CRLF in Tareas/T00/menu.py

### ISSUE THREAD

**Issue by MGome** [IIC2233/syllabus#82]
Al subir la los archivos de mi tarea me salta el siguiente error al hacer git commit. Esto traerá algún problema al correr el código una vez subido? 
![image](https://user-images.githubusercontent.com/48321270/63215539-1054ee00-c0f6-11e9-844d-891a92654a98.png)

**Comment by jeschuwirth** [comment]
Hola!

LF y CRLF representan los finales de línea de tu sistema operativo, linux utiliza el LF, mientras que windows utiliza CRLF, esto se ocupa para saber cuando termina una línea de texto en tu archivo (el "\n").

La mayoría de los editores de texto modernos detectan automáticamente cual final de línea estas usando y te muestra la forma correcta, por esta razón no hay problema con que subas los archivos de tu tarea con esa advertencia.

Buena pregunta :)
