### ISSUE TITLE
Mayoría de edad

### ISSUE THREAD

**Issue by Jiruiz2** [IIC2233/Syllabus#82]
Asumimos que los usuarios que son underaged no cumplirán la mayoría de edad o tenemos que calcular si son o no mayores de 18 cada vez que inicien sesión?

**Comment by sebacruzd** [comment]
Hola, como cada vez que se inicia sesión se debería crear la instancia, es necesario revisar si son o no mayores de edad. Puede que justo haya cumplido 18 antes de iniciar, y en este caso, ya no debería ser un usuario _underaged_.

**Comment by mebruna** [comment]
Y qué pasa si el usuario se creó la cuenta con 17, queda registrado como underaged y se registra en 2 mercados, pero como es menor de 18 no recibe los 50000 de los mercados, pero más tarde inicia sesión con 18 años. Recibe los 50000 de los mercados antes registrados?

**Comment by stephichau** [comment]
@mebruna sí, recibe los 50.000 de los mercados
