### ISSUE TITLE
Sobre avance

### ISSUE THREAD

**Issue by juacob** [IIC2233/Syllabus#82]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola queria saber si es necesario hacer algo en especial para entregar el avance o basta con subirlo, en mi caso cree una carpeta llamada avance en la carpeta T1 de mi repositorio, esta bien? Ademas queria preguntar si se puede explicar en el mismo diagrama lo que se hizo (en un cuadro de texto grande). Gracias!

**Comment by catalina-arcila** [comment]
Hola! Tanto la ubicación como la explicación de tu avance recomiendo ponerla en un _README avance_ para que quede todo claro
