### ISSUE TITLE
Año mayor a 9999

### ISSUE THREAD

**Issue by akaminetzkyp** [IIC2233/Syllabus#82]
Hola!
Vengo con la misma duda que el issue #79, pero explicada un poco mejor. Quisiera saber si puedo limitar el año más alto al año 9999. Mi programa no se caerá si se ingresa un año mayor a 9999, sino que le dirá al usuario que vuelva a ingresar una fecha. Si aceptamos años mayores a 9999, el formato AAAA-MM-DD HH:MM:SS cambia completamente.

Saludos!

**Comment by Hernan4444** [comment]
@akaminetzkyp ¿Qué pasará cuando la humanidad llegue al año 10000? ¿Insinúas que no viviremos hasta esa fecha :c ? Luego de discutirlo decidimos aceptar tu opción de preguntar la fecha de nuevo si es que ponemos un año mayor a 9999.

Saludos!

**Comment by akaminetzkyp** [comment]
Gracias! :D

En el año 10000 probablemente estemos apagando incendios en otros planetas. 😏

Saludos!
