### ISSUE TITLE
Error en tests de solucionar

### ISSUE THREAD

**Issue by vichoassadi** [IIC2233/Syllabus#82]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola,

Probando en los tests del método solucionar, me entrega el código que está erróneo cuando en realidad las respuestas son correctas. Puede ser porque estoy ocupando comillas simples para definir, por ejemplo, 'PP' o 'VX' y los test cases usan comillas dobles ("PP", "VX"). No sé si sea un error posible para la corrección final de la tarea.

Gracias

**Comment by vichoassadi** [comment]
![image](https://github.com/IIC2233/Syllabus/assets/133837937/9e07caa2-028d-4e44-86fc-7ba5fc10b272)

Ahí hay una imagen del test case y de lo que entrega la consola (a la derecha de los tres puntos imprimí las filas de la lista de listas que entrega mi función, que no debiese afectar el resultado).

**Comment by vichoassadi** [comment]
Lo pude arreglar. Era porque se me modificaba igual el tablero original. De todas maneras (pregunta de contenido), yo copiaba la lista del tablero para crear un tablero_copia, de esta manera:

tablero_copia = Tablero(self.tablero[:])

De igual manera se me modificaba el tablero, aún cuando le agregué el [:]. Por qué pasa esto?
Lo pude solucionar importando deepcopy de copy.

**Comment by ManuelV03** [comment]
Hola, efectivamente el error era porque se modificaba el tablero original, esto se debe a que como self.tablero es una lista de listas al hacer self.tablero[:] (que sería equivalente a usar el método .copy()) estas realizando una copia de la lista "de más afuera" de tu lista de listas, pero esta copia va a seguir teniendo en su interior referencias a las listas que están en tu self.tablero original, haciendo que cuando cambies algo en tu nuevo tablero "copia" también se cambie en el original. A esto se le llamaría una shallow copy en cambio, lo que hace deepcopy() es no solo crear una copia de la lista de "más afuera" sino que además crear una copia para cada lista que hay dentro de la anterior de manera recursiva para que así no se guarde ninguna referencia a tu lista de listas anterior en tu nueva copia. Puedes encontrar más información aquí https://www.geeksforgeeks.org/copy-python-deep-copy-shallow-copy/ Avísame si se aclaró tu duda.

**Comment by vichoassadi** [comment]
Perfecto. Muchísimas gracias!
