### ISSUE TITLE
Nota entregable?

### ISSUE THREAD

**Issue by naquiroz** [IIC2233/Syllabus#82]
Hola! Tengo una duda respecto a la evaluación del entregable.

**_1-_** Cuanto porcentaje de la nota vale el entregable?
**_2-_** Los dos (tanto el preliminar como el final) son evaluados?
   **_2.1-_** Si ambos son evaluados, significa que para tener la nota maxima debo tener ambos entregables 
   **completamente** buenos desde un principio?
   _**2.2-**_ Si solo el final es evaluado, el preliminar sirve para las sugerencias unicamente?

**Comment by FernandoPieressa** [comment]
Hola! Contestando tus dudas:

1) El entregable está contenido dentro del 8% del diagrama de clases

2) Ambos son evaluados

2.1) No, de hecho, la finalidad del primer entregable es darles feedback de su modelación para que pueda mejorar, por lo que basta un diagrama preliminar que represente correctamente como están modelando actualmente. El segundo se espera que este completamente correcto con todo detalle  y no es necesario que mantenga la misma relación usada en el preliminar, se puede modificar.

2.2) -

Espero haber respondido tus dudas!

Saludos!

**Comment by Mariana-Ortega-del-Rio** [comment]
Del 8% del diagrama de clases, cuánto de ese % equivale al entregable preliminar y al final?

**Comment by Arcoirisky** [comment]
@Mariana-Ortega-del-Rio No podemos dar tal información :c
