### ISSUE TITLE
Duda tarea 1, clase dccultivo, método crear predio 

### ISSUE THREAD

**Issue by danogajardo** [IIC2233/Syllabus#82]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Cuando ejecuto los testcases del método crear predio me arrojan el caso en que el archivo no existe pero revisando el test4_crear_predios.py me di cuenta que es porque el archivo "predios.txt" está en la carpeta data. **Es necesario que uno le agregue, al implementar el metodo, está parte de la ruta** o cuando se este revisando la tarea no surgirá este problema?

**Comment by ignacio-sp** [comment]
Hola @danogajardo, para la implementación de funciones que hacen uso de `predios.txt` es necesario considerar que este archivo estará dentro de la carpeta `data` que estará ubicada dentro de la carpeta `T1` correspondiente, por lo que se debe manejar la ruta del archivo en la función de crear predios de ser necesario.

No sé si con eso habrá quedado más claro, estoy atento!
