### ISSUE TITLE
¿Cómo se debe visualizar el tablero?

### ISSUE THREAD

**Issue by rodridelafuente** [IIC2233/Syllabus#82]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Logré crear la lista del tablero que se debe ingresar en la función "print_tablero" según el enunciado. El problema es que **no me queda del todo claro cómo mostrarle el tablero al jugador**, ya que con esta función el tablero se imprime mostrando las letras "N", que representa las casillas que contienen bestias. Por lo tanto, el jugador jamás elegiría el las casillas que contengan una letra "N", ya que se puede ver gráficamente. Entonces no sé si mostrar el tablero de otra manera, no mostrarlo o quizás no estoy entendiendo bien el funcionamiento del juego.
No sé si mi pregunta será muy básica pero realmente no me queda claro solo con el enunciado, así que agradecería mucho su ayuda :)

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by Emiliax16** [comment]
Hola @rodridelafuente . Si la función `print_tablero()` del módulo `tablero.py` muestra el tablero con las bestias incluidas, entonces debes pensar en una forma de implementar el juego de tal manera que sólo cuando el jugador elija una coordenada en la que se encuentra una bestia, entonces le pases el tablero con todas las bestias incluidas a la función `print_tablero()`. Mientras se esté jugando una partida, puedes utilizar tu tablero normalmente e ir modificando los lugares que se van descubriendo, pero sólo cuando se escoge una bestia las puedes agregar a tu tablero. Quedo atenta por si te quedan dudas. Saludos!
