### ISSUE TITLE
Duda uso del .gitignore

### ISSUE THREAD

**Issue by jyvo28** [IIC2233/Syllabus#82]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

###DUDA
**QUÉ SE SUBE A MI REPOSITORIO? ES NECESARIO USAR GITIGNORE EN ESTA TAREA?** Tengo una duda con esto, porque leí el enunciado y no sale ninguna pauta para la entrega, como por ejemplo, si se usa o no gitignore. Solo actualizo los archivos de t0 ? Estoy confindida

**Comment by catalina-arcila** [comment]
Hola @jyvo28, en esta tarea no se evaluará el uso de ._gitignore_, sin embargo es altamente recomendable para aprender y dar instancia a que los correctores te entreguen _feedback_, por si hay errores o si lo hiciste perfect 😉.
En el archivo ._gitignore_ se deben encontrar los archivos indicados en el enunciado, es decir, todos los archivos dentro de la sección de Archivos deben ir en el ._gitignore_, lo cual incluye parametros.py. Ahora bien, si añadiste más parámetros además de los pedidos, entonces debes subirlo, ya que sino habrían problemas con el código 😄
