### ISSUE TITLE
orden posts archivo

### ISSUE THREAD

**Issue by mariovaldesa** [IIC2233/syllabus#82]
Hola! se puede cambiar el orden en que estan los posts en el archivo posts.csv?

**Comment by gatochico** [comment]
Hola! Puedes hacerlo, sin embargo toma en cuenta que al momento de evaluar tu tarea, **utilizaremos los archivos csv originales que se entregaron junto con el enunciado**. Si tu programa funciona con esos archivos, estará todo ok. 

Saludos y éxito!

**Comment by mariovaldesa** [comment]
perfecto, gracias!
