### ISSUE TITLE
Duda Flask

### ISSUE THREAD

**Issue by Clemente24** [IIC2233/Syllabus#820]
Hola, no estoy entendiendo muy bien qué rol cumple Flask en la tarea. Alguien me podría explicar mejor pliss? Tampoco entiendo muy bien cómo va relacionado con el servidor o cliente, estoy un poco perdido ahí.

Gracias!

**Comment by ptflores1** [comment]
Hola !
Cualquier API, como la de OpenWeather por ejemplo, posee código que corre en el servidor que puede estar escrito en `python`, `javascript`, `ruby`, etc, la idea es que cada vez que llega una consulta `HTTP`al servidor, que no es más que otro computador que esta funcionando en alguna parte del mundo, este servidor utiliza el código para manejar y procesar las consultas de la manera que se desee, en el caso de la API de OpenWeather lo que hace es procesar la informacion que le estas pidiendo, ya sea el clima, pronostico, radiacion uv, la ciudad, etc. para que así pueda devolverte la información que te interesa a ti. Flask es un [framework](https://es.wikipedia.org/wiki/Framework) que te ayuda a crear este código que corre en el servidor, hace muchas cosas por detrás para que no te tengas que preocupar de como llega la consulta al servidor si no que te deja disponible la información que viene con la consulta y te permite retornar lo que tu decidas para cada consulta que llegue al servidor. Para esta tarea no es necesario subir el código a un computador remoto, solo les pedimos que el código corra localmente, asi como lo hicieron para la tarea 6, esto se puede hacer tan simplemente como ejecutar una aplicación creada en Flask porque éste crea un servidor local que es capaz de manejar consultas HTTP y funciona igual que como cualquier API que este en la web solo que va a estar funcionando en tu propio computador.

El cliente que debes crear debe consumir tu API tal como tu lo estas haciendo con OpenWeather o Gmail, imagina que la API que creaste en realidad no la hiciste tu si no que la hizo otra persona, entonces tu tienes que poder consumirla tal como lo haces con las otras (OpenWeather, Gmail).

Explicación de la ultima función que aparece en `example.py`:

`@app.route("/parametros", methods=["GET"])`  este decorador lo que hace es redirigir todas las consultas `HTTP` que sean `GET` que lleguen a /parametros es decir, la consulta se veria como: `http://127.0.0.1:5000/parametros`donde `http://` indica el protocolo, `127.0.0.1` indica la dirección del servidor, en este caso `127.0.0.1` es lo que equivale al `localhost`y es lo que uds deben utilizar ya que solo es necesario que funcione en el computador en que se esta ejecutando el programa, luego el `5000` inidica el puerto al cual se están conectando y finalmente `/parametros` es la información que queremos obtener, es la manera de decirle al servidor que es lo que queremos. Tambien existen otras maneras de mandar informacion al servido en las rutas y es de hecho lo que utiliza la API de OpenWeather.

`http://api.openweathermap.org/data/2.5/uvi/forecast?lat=-33.472691&lon=-70.64724&appid=API KEY`, analicemos esta ruta. Nuevamente se parte con el protocolo luego viene `api.openweathermap.org` que equivale a `127.0.0.1:5000` porque se usa el [DNS](https://es.wikipedia.org/wiki/Sistema_de_nombres_de_dominio) que traduce `api.openweathermap.org` en algo como `127.0.0.1:5000`, luego viene `/data/2.5/uvi/forecast` que define que le estamos pidiendo a la API, cada API define sus rutas como quiera y tu tambien debes buscar una forma de definirlas que te sirvan para poder hacer consultas posteriormente, y finalmente viene `?lat=-33.472691&lon=-70.64724&appid=API KEY` que es información que la API necesita (lo sabemos por su documentacion).

Volviendo a Flask, el argumento `methods=["GET"]` nos permite definir que metodos `HTTP` vamos a aceptar en esta ruta, si se intenta, por ejemplo, hacer un `POST` tendriamos un error. La función que decoremos será la función que se ejecutará cuando se estén haciendo  consultas a la ruta especificada, en este caso `"/parametros"`. Cuando llega una consulta nueva al servidor y efectivamente vemos que la ruta es `"/parametros"` se ejecutara la función que hayas definido y la información de la consulta se guardara en `flask.request`, hay diferentes formas de obtener la información de la consulta dependiendo de como se haya mandado desde el cliente, una manera de obtener lo que el cliente envia en forma de url es haciendo `flask.request.args.get('username')` suponiendo que el cliente hizo una consulta como `requests.get("http://127.0.0.1:5000/parametros?username=ptflores1")`.

Finalmente nuestra API debe retornar algo, como habrás notado la mayoria de las API en la web retornan información en formato `json` porque es un formato agnostico al lenguaje y esto permite mejor interacción, pero tambien se podria retornar texto plano o [HTML](https://es.wikipedia.org/wiki/HTML) que es lo que retornan las paginas web. Sea lo que sea que retornes esto le va a llegar al cliente en forma de respuesta a su consulta.

[Este video](https://www.youtube.com/watch?v=zRwy8gtgJ1A) puede ayudarte a entender como utilizar Flask. [Aqui](https://stackoverflow.com/questions/10434599/how-to-get-data-received-in-flask-request) explican un poco mas como obtener en Flask la informacion enviada por el cliente de diferentes maneras. Te dejo tambien la [documentacion oficial](http://flask.pocoo.org/) que puede ser de mucha ayuda


Espero que quede más claro, saludos !

**Comment by Clemente24** [comment]
Perfecto, me quedó bastante claro! Me queda sólo una duda, respecto a la estructura servidor-cliente; dado que al crear una app en Flask estoy creando un servidor y que desde el cliente puedo hacer consultas a este servidor, ¿es necesario/obligatorio/esperable implementar la estructura cliente-servidor como lo hicimos en la tarea 6?

**Comment by Pipelao** [comment]
Hola @ptflores1 
Sabes que estoy bien perdido con cómo interactúa el cliente con la API (que sería nuestro servidor si no me equivoco) y con las APIs de Open Weather y GMAIL. Por ejemplo, ¿corro el cliente y recibo la información en la misma consola de python? como en la tarea 1, ¿recibo el nombre y correo en un input y lo verifico en una función de otro módulo que sería el server y si está bien, realizo la consulta a OpenWeather?; si fuera de esta forma, ¿en qué momento interactúo con mi API?, ¿en qué momento utilizo el módulo Flask?, o, como se muestra en el vídeo que comentaste, ¿debemos hacer una ventana de HTML que reciba info del usuario (una especie de interfaz gráfica pero en HTML) y esa info enviarla a las APIs correspondientes? Espero que sea de la primera forma que plantee, pero si es así, no entiendo cómo y para qué utilizar Flask, además de que no veo cómo interactúan cliente y servidor.
Gracias de ante mano

**Comment by Pipelao** [comment]
Ohhh creo que entendí, estuve haciendo unas pruebas y me funcionaron, muchas gracias, me quedó clarísimo. Una pequeña duda @ptflores1, ¿entonces tendré que importar el módulo requests en ambos módulos? digo en el módulo del Server para hacer get a las apis de OpenWeather y GMAIL y en el del cliente para hacer get a nuestra API?
Muchas Gracias :)

**Comment by ptflores1** [comment]
Sii !

**Comment by pcseisdedos** [comment]
No entiendo bien como le debo hacer requests a mi api,
si hago `requests.get("http://127.0.0.1:5000/prueba")` obtengo `<Response [200]>` siendo que yo puse en la parte de `@app.route("/prueba", methods=["GET"])` una consulta de ejemplo y que la retornara en forma de string :/

**Comment by Pipelao** [comment]
Gracias @ptflores1 
@pcseisdedos tienes que hacer variable = requests.get("http://127.0.0.1:5000/prueba"), y luego variable.json()
Saludos

**Comment by pcseisdedos** [comment]
Hice algunos cambios en la funcion, en lo que retornaba y despues usé lo que dijiste @Pipelao  y ahora funciona pero se demora como 10 secs, será normal?

**Comment by Pipelao** [comment]
@pcseisdedos Mmm, la verdad que no lo sé, no he probado el request completo, pero si te funciona, yo 
que tú seguiría no más, y lo especificaría en el README y después si te queda tiempo lo corriges si es que hubiera algún error. Quizás si le preguntas a algún ayudante te podría decir qué onda.
Éxito en la tarea :)
