### ISSUE TITLE
Duda sobre movimientos de chef

### ISSUE THREAD

**Issue by MINGOD24** [IIC2233/syllabus#820]
Hola, tengo entendido que el chef comienza descansando cuando no hay pedidos. Pero mi pregunta es si durante que cocina debe tener varios frames o con uno que muestre que esta ocupado basta?

**Comment by kadroguett** [comment]
Hola @MINGOD24 
Como dice el enunciado, mientras el chef cocina esto se debe reflejar en cambios de sprite, por lo que debe tener diferentes frames.

**Comment by MINGOD24** [comment]
Hola, entonces solo para confirmar, una vez que el chef recibe el pedido, no debe solo tener 1 frame mientras cocina, sino que debe tener varios frames, y una vez que esté termine debe quedar con el plato servido en la mesa. Eso es lo correcto?
