### ISSUE TITLE
Pinguino no vuelve a posicion neutral

### ISSUE THREAD

**Issue by Gsalinas1506** [IIC2233/syllabus#820]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola. Estoy modelando a los pingüinos para que cambien su sprite dependiendo de que tecla de aprete mediante un `keyPressEvent`. 

Cuando se inicializa el pingüino, este se muestra en su posición neutra mediante un **método** que establece en un Qlabel el .png con esa posición. Luego, dependiendo de que tecla se aprete, se modifica la imagen de este mismo label mediante el `keyPressEvent`. Luego intento que, luego de cambiar su sprite al de la posicion correspondiente, se vuelva a su posición inicial invocando a este mismo **método** que mencioné antes (establecer el Qlabel como la posición neutra), pero esto no ocurre.

He intentado de todas las maneras para que el pingüino vuelva a su posición inicial, invocando al **método** al principio del `keyPressEvent`, al final de este, y después de cambiar el sprite correspondiente a la posición de la tecla oprimida (un mismo `keyPressEvent` identifica que tecla se oprime y en función de eso cambia el sprite ). Sin embargo nada funciona. También he tratado dando tiempo de reposo con `time.sleep()` y `keyReleaseEvent`, pero nada pasa... ¿Que puede ser?

PD: El modelo del pingüino esta en mi repositorio

**Comment by JadrinaDA** [comment]
Hola! Tenías una buena intuición al intentar agregar un delay con time.sleep() pero hay un problema, time.sleep() es un "blocking delay" es decir mientras estas en el sleep tu interfaz se bloquea y no muestra los cambios. Lo que puedes hacer para crear ese delay es usar un timer que espere un segundo y que en el el timeout de este se llame la función settear_original. El timer no funciona de manera paralela al resto de tu programa y por lo tanto no va a bloquear tu interfaz. Probé esto en tu código y me funcionó. Si necesitas más ayuda para implementarlo avísame, saludos!

**Comment by Gsalinas1506** [comment]
Sii, ahora lo probe y me funcionó! muchas gracias
