### ISSUE TITLE
Bocadillos como entidad

### ISSUE THREAD

**Issue by raimundomartinez** [IIC2233/syllabus#821]
Hola! No entiendo para qué sirven los bocadillos. No tienen atributos y todos su métodos se pueden aplicar en otros objetos. ¿Es necesario crear una entidad Bocadillo? Lo único que se me ocurre es que podrían ponerse encima de otros sprites como decoración y para esto no necesito crear una entidad.

**Comment by jbulness** [comment]
Hola @raimundomartinez,

Si bien se podría no crear una entidad Bocadillo y aplicar sus métodos directamente en los métodos de otras entidades, les pedimos que creen estos elementos como entidades ya que de esta forma se puede ver más fácilmente que cosas están relacionadas a los Bocadillos, es decir, sirve para organizar mejor tu código, teniendo una "sección", por así decirlo, de estos elementos, por lo que si quieres editar cualquier cosa relacionada a estos o revisar si tienes un problema, resulta más fácil hacer esta edición o revisión. Así también, esto le otorga flexibilidad a tu programa, ya que si después se necesita implementar nuevos bocadillos, agregar nuevos atributos o crear nuevos métodos se te hará más fácil cambiarlo directamente en la clase que ir buscando y modificando las partes de tu código donde implementaste la forma alternativa de esto. Todo esto es una buena práctica que esperamos que adopten, ya que ayudan al manejo de su código y a la lectura por parte de otras personas. 

Por último, ojo que sí tiene atributos esta entidad, por ejemplo `PRECIO_BOCADILLO`, el cual debe estar en el archivo `parametros.py`.
