### ISSUE TITLE
Cantidad de dias del pronostico y error request uv

### ISSUE THREAD

**Issue by ibaeza1** [IIC2233/Syllabus#821]
Podemos asumir que el pronostico del clima siempre sera de los proximos 5 dias y el de los rayos uv de los proximos 8? ya que en el enunciado dice solo eso pero no dice 5 o mas dias o 8 o mas dias.
Tambien tengo otra duda si hago esta request
**r = requests.get('http://api.openweathermap.org/data/2.5/uvi/forecast?appid={2}&\lat={0}&lon={1}&cnt=8'.format(lat, lon, apikey))
        return (r.text)**
me sale este error 
    **Lat field is not valid: actual - 0, expected - required**
y no se que significa ya que le estoy dando los parametros bien
Gracias :)

**Comment by Pipelao** [comment]
Tienes que poner en orden el format, es decir, appid={0}, lat={1}, lon={2}.format(apikey, lat, lon)
Saludos
