### ISSUE TITLE
Actualización sheet de sucesos: costantemente vs solo al final

### ISSUE THREAD

**Issue by Fhguinez** [IIC2233/Syllabus#821]
Hola, 
¿La idea es ir actualizando constantemente apenas ocurran los sucesos en la hoja de google sheets o basta con enviar todos los sucesos juntos una vez que se cierra el programa?

**Comment by ifcarrera** [comment]
Hola, queda a su criterio. Pero tengan en cuenta que si lo dejan para el final y se cae su programa en mitad de ejecución, podría no escribirse en la sheet. Es bajo su responsabilidad el cuándo lo hagan.
Salu2.0 (float)

**Comment by fgbruna** [comment]
@ifcarrera  entonces en cada ejecución de nuestro programa debemos verificar si la hoja de logs ya existe? o  podemos contar con que el usuario va a borrar la hoja de logs antes de correr el programa?.
Esto lo pregunto por que no he podido encontrar un método "formal" de la api de sheets para saber si una hoja existe,<sup>o sí existe :astonished: ?<sup>

**Comment by fedetaladriz** [comment]
@fgbruna puedes hacerlo con un try: si intentas crear una hoja con un nombre que ya esté ocupado se te levanta una excepción
