### ISSUE TITLE
Duda funcion exec_()

### ISSUE THREAD

**Issue by mpenalozag** [IIC2233/syllabus#822]
La funcion exec_() que se utiliza en dragging es lo mismo que el built prohibido exec() ? 
Gracias de antemano !

**Comment by jbulness** [comment]
Hola @mpenalozag,

La función `exec_()` no es lo mismo que el `built-in` prohibido `exec()`, por lo que no hay problema con que esté en tu dragging. En la siguiente issue (#686) se indica más información acerca de la función y del `built-in`.
