### ISSUE TITLE
obtener woeid

### ISSUE THREAD

**Issue by tanavarrete** [IIC2233/Syllabus#822]
Estoy usando Yahoo! Where On Earth ID para obtener el woeid pero me tira el siguiente error:
requests.exceptions.ConnectionError: HTTPConnectionPool(host='where.yahooapis.com', port=80): Max retries exceeded with url: /geocode?location=37.42,-122.12&flags=J&gflags=R&appid=zHgnBS4m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000006D39D70F28>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Es problema de la página o estoy haciendo algo mal yo?

**Comment by ifcarrera** [comment]
Hola!
Como se dijo en issues anteriores, no puedes utilizar la api de Yahoo!.
El woeid se puede obtener con la api de Twitter.
No te compliques más usando más api's. 
Saludos

**Comment by naazocar** [comment]
No puedes usar Yahoo, lo dijeron en otra issue, te recomiendo buscar bien en la de twitter, en la parte de Geo, por ahí dice como conseguir el woeid, suerte !

**Comment by tanavarrete** [comment]
Gracias!
