### ISSUE TITLE
Uso API Yoda

### ISSUE THREAD

**Issue by JorgeBdelaT** [IIC2233/Syllabus#823]
Hola, estoy usando el traductor a yoda para las descripciones del tiempo, que es lo unico en ingles, pero al retornar la consulta, el texto queda igual, solo que la primera letra se vuelve mayuscula. Si lo uso de este modo, contara para el bonus?

**Comment by mfanselmo1** [comment]
Hola, eso no es suficiente para el bonus. Si pruebas la api de yoda con frases en ingles, hay mas cambios de los que tu dices.

**Comment by JorgeBdelaT** [comment]
Bastaria con un texto mas largo? Al estilo de una bienvenida por parte de yoda, pero lo demas este en español
