### ISSUE TITLE
Como hago para ver los tweets de una posición?

### ISSUE THREAD

**Issue by Kitaps** [IIC2233/Syllabus#823]
Tengo el WOEID, pero eso parece que solo sirve para los trends

Y cuando lo hago a travéz de search no me resultá.

Lo que intenté es dejar la query así como cuando buscas directo en twitter:
q=geocode%3A-33.4488897%2C-70.6692655%2C50km
Pero eso solo funciona con tweets en estados unidos parece, porque en todo santiago me retorna un solo tweet (en ingles)

Como habría que hacerlo bien?

**Comment by naazocar** [comment]
Yo lo hice con el place_id, aunque creo que era mejor con los parametros lat, long y radius como lo tienes. Pero estás seguro de que le puedes pasar el geocode como query? Según lo que entendí eran cosas aparte D:

**Comment by Kitaps** [comment]
Nose, esque en search te lo dan como filter.
Igual así como lo puse funciona, pero funciona masomenos.

Pero igual como va a ser que para una cosa te pidan el WOEID, para una el place ID y para otra el geocode?

**Comment by Kitaps** [comment]
Porque lo que estamos buscando son Tweets generales verdad? Igual como los trends? 

No tweets geolocalizados.

Lo otro que se me ocurrió es:
Dada una posición buscar los trends
De los trends sacar los querys
Usar esos querys para buscar los tweets
Filtrar los tweets por posición

Pero debe haber una mejor manera de hacerlo

**Comment by Fhguinez** [comment]
Yo uso WOEID para los trends y lat, lng para los tweets. En el fondo el paso del WOEID es algo extra que solo debes hacer al pedir trends.
No creo que sea buena idea sacar los querys de los trends, porque estarías perdiendo todos los tweets sobre cosas que no son tendencia.

**Comment by Kitaps** [comment]
> No creo que sea buena idea sacar los querys de los trends, porque estarías perdiendo todos los tweets sobre cosas que no son tendencia.

Claro eso pense

> lat, lng para los tweets

Como? Llevo caleta rato tratando caxar como hacer eso
Lo haces así también?
q=geocode%3A-33.4488897%2C-70.6692655%2C50km

**Comment by dnalfaro** [comment]
Estaba tratando de ocupar GET geo/reverse_geocode para obtener ids, pero cuando pongo el id en GET trends/place me dice que el enlace no existe. Para corroborar que el place_id fuese válido, usé GET geo/id/:place_id
Alguien que sepa por qué me dice {'errors': [{'code': 34, 'message': 'Sorry, that page does not exist.'}]}

**Comment by Fhguinez** [comment]
"q" no recibe un geocode, se deja vacío porque no queremos filtrar por contenido.
"geocode" se trata como otra variable, a la cual tu le entregas lat,lng,rad.

**Comment by Kitaps** [comment]
como se deja vacío?
De todas las maneras que hice me tira algún tipo de error.

**Comment by Fhguinez** [comment]
al menos a mi me funciona así:
`?q=&geocode=`
según yo igual es raro, pero q no era argumento opcional jajaja

**Comment by Kitaps** [comment]
y te resulta? :O
Si por ejemplo tengo uno que si me funciona pero es especifico:
`url = "https://api.twitter.com/1.1/search/tweets.json?q=%22Rafael+Nahuel%22&result_type=popular&count=2&geocode=-37.271425 -72.7194906 50mi"`

Y lo dejo como tu dices:
`url = "https://api.twitter.com/1.1/search/tweets.json?q=&result_type=popular&count=2&geocode=-37.271425 -72.7194906 50mi"`

Me tira error

**Comment by Fhguinez** [comment]
Lo único  diferente que veo es que entre hay espacios en vez de comas en el geocode🤔

**Comment by Kitaps** [comment]
buxa había probado con comas pero tmpoco funcionó, 
igual intentaré denuevo

**Comment by Kitaps** [comment]
url = "https://api.twitter.com/1.1/search/tweets.json?q=&result_type=popular&count=20&geocode=-37.271425,-72.7194906,50mi"

Nop, no me fucniona

Igual gracias

**Comment by Kitaps** [comment]
Ojalá un ayudante me pueda ayudar .-.

**Comment by aleuribej** [comment]
a mi también me fallaba con q=&, lo que me funciono fue probar con q=? , también lei que con null podria servir pero ese ultimo no lo probé.  Ojala te sirva!

**Comment by Kitaps** [comment]
Me tira error con:
`url = "https://api.twitter.com/1.1/search/tweets.json?q=?&result_type=popular&count=20&geocode=-37.271425,-72.7194906,50mi"`

**Comment by aleuribej** [comment]
y con q=null?

**Comment by Kitaps** [comment]
tmpoco

**Comment by Kitaps** [comment]
@ifcarrera ayuda pls

**Comment by Kitaps** [comment]
O acaso hay que solo recolectar tweets con geotagging?
no verdad?

**Comment by ifcarrera** [comment]
Hola, lo que preguntas es parte de los objetivos de la tarea: aprender a hacer requests a una API entregándole los parámetros de la forma en que te piden. No puedo darte la respuesta a eso, lamentablemente :(

**Comment by ifcarrera** [comment]
Por otra parte, creo que sería mejor que le entregues los parámetros dentro de `params` y no dentro de la URL misma, así es más ordenado y entiendes qué y cómo le estás pasando los parámetros; es posible que estés intentando pasarle parámetros que no son necesarios 👀 .

**Comment by Kitaps** [comment]
dle gracias

**Comment by Kitaps** [comment]
era eso de pasarselo como params

pero porque eso? 
Si en la documentación sale que hay que pasarselo como link
Además cuando en el link trataba de pasarselo como q="" me tiraba error, 
pero ahora se lo paso en el diccionario de params como q="" 
y funciona
Sabes porque podría ser?

**Comment by ifcarrera** [comment]
En general, en web, cuando una URL tiene un signo de pregunta `?`, lo que viene a continuación son parámetros que se le entregan. En la documentación de Twitter aparecen en la URL, porque efectivamente son parámetros que tú puedes modificar para ajustar la consulta a lo que quieres obtener. Respecto a lo último, no sé por qué podría ser :c.

Saludos

**Comment by Kitaps** [comment]
gracias

**Comment by Kitaps** [comment]
otra pequeña duda:

sabes porque cuando le meto 
"result_type": "popular"
deja de funcionar (me retorna statuses vacío)
Si es un parametro de la documentación no?

**Comment by ifcarrera** [comment]
No sé bien qué considerará Twitter como "popular", quizás justo en esa zona no hay tweets populares.
