### ISSUE TITLE
Conflicto entre threads

### ISSUE THREAD

**Issue by kikobarros** [IIC2233/syllabus#823]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Mi programa se cae a veces al jugar, pero no me tira ningún error. Me imagino que debe haber algun tipo de conflicto entre threads pero no se como verificar.  
**Hay algún modo de encontrar lo que hace que mi programa se caiga?**

**Comment by JuaniAndres** [comment]
Hola @kikobarros 
Con pyqt5 puede pasar eso de que tu programa se caiga por algún error y que no te muestre ningún error en consola sin embargo existe una manera de capturar esos errores para que te aparezcan en consola.
Te recomiendo probar con el siguiente código que aparece al final de los contenidos de la semana 9 interfaces graficas:
````python
if __name__ == '__main__':
    def hook(type, value, traceback):
        print(type)
        print(traceback)
    sys.__excepthook__ = hook

    app = QtWidgets.QApplication([])
    ventana = MiVentana(*args)
    ventana.show()
    app.exec()
````
Básicamente ese hook que agregamos en la parte donde llamamos a las ventanas ayuda a capturar esos errores y a mostrarlos en consola.
Trata de hacer una prueba con eso y si no te funciona me avisas.

**Comment by kikobarros** [comment]
Lo corri con ese código y aún así se me cae en  difcultad "Maestro cumbia" sin tirarme error :(

**Comment by JuaniAndres** [comment]
Puedes subir lo que tienes a tu repositorio para echarle una mirada

**Comment by kikobarros** [comment]
ahi subí lo que llevo. Se cae al iniciar la ronda en dificultad "maestro cumbia". Hay veces que se cae en otras dificultades pero es más raro.

**Comment by kikobarros** [comment]
muchas gracias

**Comment by kikobarros** [comment]
ejecuta el modulo "MW" para ir directo a la ventana de juego.

**Comment by JuaniAndres** [comment]
Hola @kikobarros 
Varios ayudantes revisamos tu código y pensamos que el problema que te está pasando se puede deber por dos razones:
1) Hay algunos threads que no estas borrando con deletelater o que no estas terminando que hacen que tu programa colapse y se caiga

2) Quizás tu programa está muy acoplado (frontend y backend muy mezclados)

Respecto a lo primero un consejo que tengas cuidado con la duración de los threads ya que si estos no terminan y los dejas corriendo van a terminar causando problemas. Lo ideal es que una vez que el thread cumplió su función este se detenga y después se borre.
Respecto a lo segundo te recomiendo ocupar señales para separar más las partes de tu código ojalá evitar mandar Qlabel a través de señales quizás hay mejores formas de lograr lo mismo.
Échale una revisada a tu código quizás encuentras algunas partes las cuales puedes mejorar o que no son tan necesarias.
Éxito programando :smile:
