### ISSUE TITLE
Sprites con pixeles transparentes asumen el color del fondo

### ISSUE THREAD

**Issue by sofiuni** [IIC2233/syllabus#823]
![image](https://user-images.githubusercontent.com/48592386/82706836-bebf2e00-9c48-11ea-9467-11bbc28de294.png)
Como puedo hacer que los pixeles transparentes de los .pngs se visualisen correctamente?

**Comment by lucasvsj** [comment]
Hola @sofiuni 
Estuve revisando tu código y esto ocurre porque usas `self.setStyleSheet("background-color: lightblue;")` para hacer que el fondo de tu ventana de juego sea de ese color. Lo que pasa aquí es que como el Qlabel es un .png y haces que el parent sea el QWidget que es tu ventana de juego, su fondo se torna del mismo color.
Esto lo puedes solucionar fácilmente seteando el color de fondo de los QLabels como transparente, con el siguiente comando:
```python
.setStyleSheet("background-color: transparent;")
```
Ojalá esto te sirva y suerte en tu tarea.

**Comment by benjavicente** [comment]
Creo que una mejor solución es **establecer que el estilo de la ventana no sea heredado** para no tener que añadir transparencia a cada objeto _hijo_ que la necesite.
En la [documentación de estilos](https://doc.qt.io/qt-5/stylesheet-syntax.html#selector-types) especifican como hacerlo.

**Comment by sofiuni** [comment]
Como hago eso en Python?

**Comment by benjavicente** [comment]
La implementación es la misma que en C, tienes que establecer en el _styleSheet_ que las propiedades de la ventana principal no se hereden (en link que mandé muestra como hacerlo).

El _styleSheet_ (el parámetro del método `setStyleSheet`) es un `str` en formato [css](https://es.wikipedia.org/wiki/Hoja_de_estilos_en_cascada) que define los estilos que toma todos los elementos dentro del objeto. [Puedes ver ejemplos aquí de como se usa](https://doc.qt.io/qt-5/stylesheet-examples.html) (en python, se usa `.` en vez de `->`)
