### ISSUE TITLE
place_id Twitter

### ISSUE THREAD

**Issue by dnalfaro** [IIC2233/Syllabus#824]
Estaba tratando de ocupar GET geo/reverse_geocode para obtener ids, pero cuando pongo el id en GET trends/place me dice que el enlace no existe. Para corroborar que el place_id fuese válido, usé GET geo/id/:place_id
Alguien que sepa por qué me dice {'errors': [{'code': 34, 'message': 'Sorry, that page does not exist.'}]}
Hasta el momento, solo he encontrado soluciones que implican una librería de twitter para python o Tweepy

**Comment by ifcarrera** [comment]
Cómo estás haciendo la request? qué parámetros le estás entregando el .get()?
Saludos

**Comment by dnalfaro** [comment]
Le estoy ingresando 2 parámetros: 
la url por que sale en el ejemplo de la página de la API:
"https://api.twitter.com/1.1/trends/place.json?id=1"(A este le cambio el id)
y  la autorización

**Comment by ifcarrera** [comment]
y si se lo entregas como parámetro en vez de entregárselo en la url? Por otro lado, leíste #776 y #794?

**Comment by dnalfaro** [comment]
Sigo teniendo el mismo error

**Comment by ifcarrera** [comment]
El error 34 es porque estás dándole mal el ID, estás seguro que se lo pasas bien?

**Comment by dnalfaro** [comment]
es raro, ya que comprobé que la id corresponde con el get al que se le pasa el id y me entrega los datos del lugar.
params={"id": id_obtenida}

**Comment by ifcarrera** [comment]
Cómo dijiste que obtenías el id_obtenida?

**Comment by dnalfaro** [comment]
Poniendo la latitud y longitud como dice en:
https://developer.twitter.com/en/docs/geo/places-near-location/api-reference/get-geo-reverse_geocode
Probé con todos los ids

**Comment by ifcarrera** [comment]
Creo que ese es tu error... vuelvo a preguntar:  leíste #776 y #794?

**Comment by dnalfaro** [comment]
SI las leí, pero no he llegado a nada :(
