### ISSUE TITLE
¿Dónde corresponde el movimiento de las flechas? (front-end, back-end)

### ISSUE THREAD

**Issue by Sofia-Arratia** [IIC2233/syllabus#824]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

**¿Es incorrecto que las flechas se muevan por si solas en el front-end del programa?**
Me pasa que al atribuir la creación de las flechas **y** el movimiento de cada una al back-end, no encuentro la manera de conectar todas estas cosas correctamente mediante señales, manteniendo las flechas como objetos independientes. Lo único que se me ocurre para el correcto funcionamiento de las flechas es que estas se muevan por si solas, con un método de su propio objeto (y es lo mismo que se le ha ocurrido a un par de personas con las que he hablado). No se si esto aporta a que el programa sea menos cohesivo, o si es "legal" hacerlo, y si no lo es, me podrían guiar un poco o dar algun tip para abordar esto? 😞 
Gracias de antemano!

**Comment by aljara97** [comment]
Hola @Sofia-Arratia, toda funcionalidad que tenga que ver con el manejo de la lógica del programa (en este caso el uso de threads) debe ir en el backend. Por tanto, incluir el thread que hace que las flechas se muevan en la ventana en un archivo de frontend es una mala modelación, para evitar estos errores debes conectar el thread correspondiente con el método que actualiza las flechas mediante señales

Si tienes dudas puedes revisar las issues #807 y #773 en donde se habla de la separación de backend y frontend. Espero haberte ayudado, si te queda alguna duda coméntame acá 🐧

**Comment by Sofia-Arratia** [comment]
Ok! Muchas gracias ☺️
