### ISSUE TITLE
Permiso insuficiente al enviar mail

### ISSUE THREAD

**Issue by JorgeBdelaT** [IIC2233/Syllabus#824]
Hola, estoy haciendo un codigo de prueba para enviar un mail, pero me arroja un error de permisos. En la carpeta donde esta el codigo se encuentran los archivos credentials y client_secret, trate cambiando el scope pero arroja lo mismo. Subi el codigo a mi repositorio por si lo pueden mirar, gracias!

**Comment by rihanuch** [comment]
¡Hola, @JorgeBdelaT !

Lo más probable es que tengas que cambiar los permisos de tu mail, y no que el código esté malo

¡Saludos! 🍀

**Comment by JorgeBdelaT** [comment]
sii, ya lo solucione, gracias!!
