### ISSUE TITLE
Dudas con Qt Designer

### ISSUE THREAD

**Issue by fddelabarra** [IIC2233/syllabus#824]
buscandolo en el ordenador, me aparece en scripts de la carpeta de python y no en pyqt5_tools, me aparece con un icono de python, eso causa algun problema? al menos se abre sin problemas (aun no he intentado usarlo)

**Comment by fdoflorenzano** [comment]
Hola @fddelabarra,

La verdad es difícil saber para todos los casos. Intentaría usarlo primero y ver como va. Ahí cuéntanos tú si tienes algún problema.

Saludos.
