### ISSUE TITLE
Problemas al cargar archivos .ui: ModuleNotFoundError

### ISSUE THREAD

**Issue by sebaelsaca** [IIC2233/syllabus#825]
Al escribir el código:

window_name, base_class = uic.loadUiType("designer_ventana_inicial.ui")

Me aparece: ModuleNotFoundError: No module named 'designer_ventana_inicial_rc'

Y sin esto no puedo ocupar Qt Designer

**Comment by lucasvsj** [comment]
Hola @sebaelsaca 
Veo una discrepancia de nombres entre 
`window_name, base_class = uic.loadUiType("designer_ventana_inicial.ui")` 
y 
` No module named 'designer_ventana_inicial_rc'`
Te recomiendo revisar los nombres de tus archivos (que estés cargando el archivo correcto). Trata esto y avísame como te va.

**Comment by Nicobuzeta** [comment]
@lucastack 
Por si acaso el _rc es el prefix que le pone el modulo uic a los archivos resource.
[Docs](https://doc.bccnsoft.com/docs/PyQt5/designer.html)

**Comment by sebaelsaca** [comment]
El archivo estaba dañado, cree uno nuevo desde cero y ahora funciona bien
