### ISSUE TITLE
Problema para abrir qt designer en Mac

### ISSUE THREAD

**Issue by javiermingo** [IIC2233/syllabus#825]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

Hola! al descargar qt designer lo abrí y me apareció el siguiente mensaje en una ventana
"No se puede abrir “Qt Designer” porque no se puede confirmar la identidad del desarrollador", por lo que no puedo trabajar ahi. **¿que debería hacer hacer?**

**Comment by jaimecoloma** [comment]
Hola! @javiermingo Los computadores de Mac tienen sistemas de seguridad muy altos los cuales buscan evitar que uno descargue virus involuntariamente, por esto el mensaje que te sale, sin embargo, puedes darle acceso a la aplicación. Para esto puedes intentar esto que encontré buscando: https://support.apple.com/es-es/guide/mac-help/mh40616/mac
Si no te funciona, creo que otra solución es irte a preferencias del sistema, privacidad y seguridad y si intentaste abrir la app recientemente en accesibilidad podrás darle acceso, para esto apreta el candado y pon tus datos de usuario, y luego autoriza dando un click en el recuadro vacío de QtDesigner.
Avisame si no te funciona ninguna de las dos, puedes buscarlo en Google de todos modos y hay videos que quizás lo explican mejor que yo 😄
