### ISSUE TITLE
archivos que ignorar con gitignore

### ISSUE THREAD

**Issue by shantifabri** [IIC2233/Syllabus#825]
Hola, no tengo muy claro que hay que poner en el gitignore y que no.
Hay que ignorar todos los .json o hay que subir algunos, por ejemplo client_secret.json?

Muchas Gracias!

**Comment by ptflores1** [comment]
Hola !
Debes ignorar por lo menos `client_secret.json`, `city.list.json` y `credentials.json`
Saludos !

**Comment by shantifabri** [comment]
Ya perfecto, gracias!
