### ISSUE TITLE
Guardar nivel_chef

### ISSUE THREAD

**Issue by Mjtala** [IIC2233/syllabus#826]
Hola,
tengo una duda sobre si puedo modificar el archivo  datos para guardar el nivel del chef ya que este no esta almacenado en ninguno de los archivos entregados
Gracias!

**Comment by jitorcas** [comment]
Hola! @Mjtala 

No es necesario guardar el nivel del chef ya que en el archivo `datos.csv` guardas _platos_preparados_chef_x_ por lo tanto podrías calcular cual es el nivel de cada chef que posees mediante estos datos. 
Saludos y éxito en la tarea! 💥
