### ISSUE TITLE
Error strptime al convertir fechas de tweets

### ISSUE THREAD

**Issue by fgbruna** [IIC2233/Syllabus#826]
He buscado por todas partes y no puedo encontrar la causa de este error:
Las fechas que devuelve la api de twitter se ven de la sgte forma:
`Mon Nov 27 16:54:32 +0000 2017`
Si tomo ese mismo string y le aplico la sgte función en la terminal:
`print(datetime.datetime.strptime('Mon Nov 27 16:54:32 +0000 2017', '%a %b %d %X %z %Y')`
Me devuelve esto: `2017-11-27 16:54:32+00:00` como representación del objeto date, y luego puedo cambiarle el offset y obtengo una fecha local.
El problema es que cuando trato de aplicarlo en mi código en sí, cada vez que recupero la primera fecha y le hago `.strip()` para sacarle cualquier *escape character*  y le aplico la función recién mencionada , python me tira este error:
`ValueError: time data 'Mon Nov 27 16:54:32 +0000 2017' does not match format '%a %b %d %X %z %Y'`

**Comment by matiaseche** [comment]
Me sumo a esto. Tengo el mismo problema.
Guardo una fecha (que es un string) y luego se lo paso a strptime con esos mismos parámetros y no funciona.
Pero si pongo exactamente la misma fecha (en string) y los mismos parámetros del format bajo el
```python
if __name__ == "__main__":
```
 Funciona de la manera esperada y me retorna la fecha como un datetime object.

Obtengo el siguiente error cuando lo uso dentro de un método de alguna clase:
`ValueError: time data 'Mon Nov 27 18:05:02 +0000 2017' does not match format '%a %b %d %H:%M:%S %z %Y'`

**Comment by fgbruna** [comment]
@matiaseche  pudiste resolverlo?

**Comment by matiaseche** [comment]
@fgbruna No :-1:

**Comment by Kitaps** [comment]
D: me pasa lo mismo que a @matiaseche 
@fgbruna 
Lo pudieron resolver ? O pudieron encontrar a que se debe el problema?
 
Yo no encuentro nada, onda solo problemas de overload pero si esque tuviera problemas de overload también debería tenerlo al momento de correrlo desde el modulo mismo...

**Comment by fgbruna** [comment]
No pude resolverlo, al final lo deje con la hora que entrega la api nomás.

**Comment by Kitaps** [comment]
dle gracias
