### ISSUE TITLE
Reporte tiempo, reporte uv

### ISSUE THREAD

**Issue by ValentinaAlvarezG** [IIC2233/Syllabus#826]
Hola!, según el enunciado creo que podría pasar que una persona al cambiar su configuracion diga que no quiere ningún reporte del tiempo (ni actual ni 5 días) y que no quiere reporte uv (ni actual ni 8 días). ¿Qué pasaría en ese caso? se manda un mail con nada? no se manda el mail? o no puede quedar una configuración donde ambas sean ninguna?

**Comment by ptflores1** [comment]
Queda a tu criterio, saludos !
