### ISSUE TITLE
Valor visible en barra aprobación y progreso 

### ISSUE THREAD

**Issue by denisseleiva** [IIC2233/syllabus#826]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola!! Quería preguntar si es necesario que en las barras de aprobación y progreso se vea el valor de la barra. Pregunto porque al implementarlas les pongo settextvisible(True) e igual no veo los valores, entonces lo setee en False ya que como no lo puedo ver no sé si se está viendo bien. Destaco que la barra sí se va actualizando como debería,  ¿Afectará esto la correción? 

Gracias!

**Comment by aljara97** [comment]
Hola, podrías subir los últimos cambios que has hecho a tu repositorio? Para poder probar tu código y ver si es un problema de tu computador o de la forma en que defines la barra de progreso 🐧

**Comment by denisseleiva** [comment]
Holaaa @aljara97 ahí lo subí!

**Comment by aljara97** [comment]
Dejando las barras de progreso con `setTextVisible(True)` no tuve problemas para ver el porcentaje de ambos widgets. Probablemente se trate de un problema de tu computador que impide que se ejecute de manera incorrecta. Te recomiendo indicar esto en tu readme para que el o la ayudante que corrija tu tarea lo tenga en consideración.

Te dejo una foto para que puedas observar cómo veo la ventana en mi computador.
![imagen](https://user-images.githubusercontent.com/42227563/97205747-9eb30e00-1796-11eb-8a26-ceed104fadbe.png)

**Comment by denisseleiva** [comment]
okaa, muchas gracias!
