### ISSUE TITLE
Tarea 02 Parámetros Iniciales

### ISSUE THREAD

**Issue by Francisco5674** [IIC2233/syllabus#827]
Hola! En el enunciado dice que las primeras mesas y mesones cuando comienzas una nueva partida deben estar en ubicaciones aleatorias, mi pregunta es ¿No tendría más sentido que al inicio no tengas nada en el mapa a excepción de ti y un monto de dinero más grande para partir el negocio con un par de mesas y un chef? de ese modo el usuario podría ponerlas donde se le de la gana, me lo permiten o ¿tienen que ser obligatoriamente aleatorias?

**Comment by kadroguett** [comment]
Hola @Francisco5674 
Recuerda que el enunciado dice que se debe empezar en la etapa de **ronda** y no en **pre-ronda** por lo que si no hay mesas ni mesones no podrás atender a los clientes. Con respecto a la última pregunta, si deben ubicarse de forma obligatoria en posiciones aleatorias.
