### ISSUE TITLE
Problema con correr un metodo de una clase

### ISSUE THREAD

**Issue by Natydlb** [IIC2233/syllabus#827]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola! intentando correr mi código me sale este problema "invalid syntax" en la linea 26 self.run() y he mirado por todas partes el código pero no entiendo cual es el problema, además que como todas las demás funciones presentan problema, pero no entiendo por que D: podrían ayudarme revisando cual es el error que tira mi código ? porfis he intentado de todo, el problema esta en el archivo pista_baile.py en la linea 26

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by aaossa** [comment]
Hola @Natydlb , el problema está un poco más arriba (línea 23 del mismo archivo): `self.posicion = (50, randint(0, limite_y)`, te falta un paréntesis 🐛 Ojalá sea eso y que puedas seguir avanzando en tu tarea ✨ ¡Mucho éxito!

**Comment by Natydlb** [comment]
jajajaj muchas gracias y perdón!!

**Comment by Natydlb** [comment]
hola, lo siento por hablar de nuevo pero ahora me sale "Pista_baile' object has no attribute 'resize'" pero nada tiene resize ni el archivo .ui ni la clase Pista_baile

**Comment by aaossa** [comment]
@Natydlb creo que es porque estás pidiéndole mucho a tu clase `Pista_baile` (ojo con PEP8 también, esto no está en *CamelCase*). Heredas de `QThread` y al mismo tiempo es un elemento gráfico que hiciste con Qt Designer. Me parece que es algo separable. En cuanto a tu duda en sí, es porque `QThread` no tiene el método `resize`, así que pude arreglarlo cambiando el orden de la herencia (dejando `QThread` al final), pero como dije, yo tendría ojo con si quieres hacer eso realmente 😅, me parece que no necesitas que sea un `QThread`. Ojalá te sirva. ¡Éxito con la T02!

PS: Ojo que esta duda no es relacionada con tu duda inicial, así que en casos así es mejor hacer una nueva *issue* 👌
