### ISSUE TITLE
Sobre configuración

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#827]
Hola, en el enunciado dice
```o si no quiere ver ninguna información respecto al tiempo.```
Esto tiene que ser una opción en sí o puedo hacer que desactive las que quiera y si desactiva ambas ya está?

**Comment by leolivares** [comment]
Hola! @jmwielandt 
Si, puede ser a tu criterio.

**Comment by jmwielandt** [comment]
Gracias~
