### ISSUE TITLE
Que entregar T07

### ISSUE THREAD

**Issue by ewaugh2** [IIC2233/Syllabus#827]
Hola, me preguntaba que debíamos entregarles cuando les subamos la tarea. 
Específicamente:
- Les subimos el "secret_client.json"? Y los archivos de texto y jsons que generemos durante el programa?
- Les subimos nuestro código con nuestras api_keys, y tokens? O les dejamos las variables para que ustedes rellenen con los suyos?

Gracias y Saludos.

**Comment by dvogaz** [comment]
En la issue #804 dijeron que podíamos no subirlos o subirlos
