### ISSUE TITLE
Dos flechas de un mismo carril llegan a la zona de captura al mismo tiempo

### ISSUE THREAD

**Issue by ignaciomansuy** [IIC2233/syllabus#828]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola! 
Me surgió la duda de qué debe ocurrir en el caso de que dos flechas de un mismo carril lleguen a la zona de captura al mismo tiempo, por ejemplo:
![image](https://user-images.githubusercontent.com/64439029/97189757-b46b0800-1783-11eb-9d4a-a7669a953fbe.png)

En este caso, si el usuario apreta la tecla _W_ se deben marcar como atrapadas las dos flechas de una sola vez o se debería marcar como atrapada solo la flecha que está más abajo?

Saludos!

**Comment by aljara97** [comment]
Hola, como esto no se especifica en el enunciado puede quedar a tu criterio, eso sí es necesario que indiques este supuesto en tu readme y cites esta issue.

Mucha suerte 🐧
