### ISSUE TITLE
Duda con QThreads

### ISSUE THREAD

**Issue by jirarrazaval** [IIC2233/syllabus#828]
Hola, tengo una gran confusión con las ```class MiClase(QThread)```

1. No puedo crear varias instancias de esta clase que se starteen al mismo tiempo. Sólo comienza a startear una vez que termina el que venía antes (todo esto lo probé con ejemplos simples y descubrí que nunca podían como correr todas juntas al mismo tiempo). Cómo puedo lograr esto??

2. Tengo otra clase QThread que tiene dos instancias, que al principio funcionan bien pero una vez que ambas se ejecutaron con start, despúes como que se sincronizan y hacen todo al mismo tiempo, aunque sólo quiero que se haga en una. No sé cómo arreglar esto, quizás es porque como son threads, se ejecutan una vez y como que sus instancias no se guardan?? No sé si me explico bien esque es muy raro no entiendo por qué pasa

**Comment by fdoflorenzano** [comment]
Hola @jirarrazabal,

¿Podrías compartir el código de ejemplo que probaste? Ya que todo lo que dices suena bastante específico y es difícil entender sin muchas más información.

Ten ojo si se trata de código de tarea, en cuyo caso adaptalo para no compartir código de tu tarea.

Saludos.
