### ISSUE TITLE
que hace esta expresion en regex?

### ISSUE THREAD

**Issue by nmaturana97** [IIC2233/Syllabus#828]
me preguntaba que hace esta expresion, entiendo que lo unico que hace es convertir el string en una lista con ese string, pro quiero entender el paso por paso de '(<[^>]+>)'.
l = re.split('(<[^>]+>)', "hola")
Muchas gracias

**Comment by andresfdezc** [comment]
La expresión regular `(<[^>]+>)` va a capturar un grupo (con su inicio y fin marcados con los paréntesis`()`) que empiece con un `<` y termine con un `>`. Lo que queda al centro (`[^>]+`) indica que ahí pueden haber caracteres que no sean `>` (el `^` significa no en regex) y que pueden ser muchos (el `+` significa que debe haber al menos uno de los caracteres indicados entre `[]`).

En resumen, esa expresión regular sirve para detectar strings como estos (conocidos como tags): `<b>`,`</b>`, `<hola>`, `<strong>`, `<body>`, `</div>`.

En consecuencia, `re.split('(<[^>]+>)', "algún <strong>texto</strong> más interesante")` retornará una lista con substrings separados por los tags. Como la expresión regular indica un grupo, lo capturado también se incluirá en la lista (si no hubiesen paréntesis `()` no se incluirían).

```python
>>> import re
>>> re.split('(<[^>]+>)', "algún <strong>texto</strong> más interesante")
['algún ', '<strong>', 'texto', '</strong>', ' más interesante']
>>> re.split('<[^>]+>', "algún <strong>texto</strong> más interesante")
['algún ', 'texto', ' más interesante']
```

Puedes leer la documentación de `re.split()` para aprender más: 

https://docs.python.org/3/library/re.html#re.split

**Comment by andresfdezc** [comment]
En particular, respecto a `l = re.split('(<[^>]+>)', "hola")`, como `"hola"` no tiene ningún tag, no hay ningúna parte donde separar. Por eso es que retorna simplemente una lista `["hola"]`.

**Comment by nmaturana97** [comment]
gracias!
