### ISSUE TITLE
En Narnia hay 26,56°C y nubosidad parcial, debo verificar que los lugares existan?

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#828]
Hola, por probar le pedí a la api que me dijera el tiempo actual en Narnia y me dijo esto:
```{'coord': {'lon': 89.6, 'lat': 24.2}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}], 'base': 'stations', 'main': {'temp': 26.56, 'pressure': 1014.24, 'humidity': 91, 'temp_min': 26.56, 'temp_max': 26.56, 'sea_level': 1015.88, 'grnd_level': 1014.24}, 'wind': {'speed': 3.96, 'deg': 196.004}, 'clouds': {'all': 56}, 'dt': 1530321929, 'sys': {'message': 0.0217, 'country': 'BD', 'sunrise': 1530314204, 'sunset': 1530363219}, 'id': 1185121, 'name': 'Narnia', 'cod': 200}```

Cuando el usuario ingrese lugares nuevos, tengo que verificar que los lugares que ingrese estén en cities.list.json? Por lo de errores de tipeo y todo eso, como que alguien escriba "Santgo" en vez de "Santiago".

En King's Landing no saben cómo está el tiempo porque openweather responde ```{'cod': '404', 'message': 'city not found'}```, lo que me parece muy mal. Daenerys necesita los pronósticos para planificar su invasión... :/

**Comment by leolivares** [comment]
Se menciona en el enunciado.
![image](https://user-images.githubusercontent.com/26394273/42120155-81e13d2e-7be4-11e8-8e60-e10a98706ff9.png)
