### ISSUE TITLE
Sprite de mesa ocupada por cliente

### ISSUE THREAD

**Issue by raimundomartinez** [IIC2233/syllabus#829]
Hola! Que en los sprites que nos enviaron no existe una mesa (o mesa con silla) ocupada por alguien. Entonces, ¿cómo representamos una mesa ocupada por un cliente? 
Se me ocurre poner la sprite del cliente encima del sprite de la mesa pero segun yo eso va a quedar muy feo. ¿Tienen alguna recomendación que me puedan dar?

**Comment by jitorcas** [comment]
Hola @raimundomartinez!

Para representar una mesa ocupada por un cliente tienes dos opciones que describiré a continuación:

1. Tal como lo dijiste, puedes sobreponer el _sprite_ del cliente sobre la mesa desocupada, cuidando proporciones. De esa manera lo hicimos nosotros para dar el ejemplo en las ventanas adjuntadas en el enunciado, por lo tanto no debería quedar feo si cuidas las proporciones. 

2. Puedes crear una _sprite_ que represente la mesa ocupada por un cliente. En internet hay muchas páginas que te pueden ayudar a crear un _sprite_, o si lo prefieres puedes descargar Photoshop (dan 7 días de prueba gratis) y editar los _sprites_. 

Ambas opciones son válidas, si decides la opción 2 debes **subir una carpeta aparte** con las sprites que creaste tu. 

Éxito en la tarea :boom:  y espero haber respondido tu duda.
