### ISSUE TITLE
Velocidades de flechas varían, pese a que deberían moverse a la misma velocidad

### ISSUE THREAD

**Issue by ignaciomansuy** [IIC2233/syllabus#829]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Tengo un problema parecido al de la issue #779, resulta que todas mis flechas (independiente del tipo que sean) tienen la misma velocidad.
Sin embargo, cuando elijo el nivel _Aficionado_, en un principio todas las flechas se mueven a la misma velocidad, pero una vez que utilizo el botón de _pausar_ y luego el de _reanudar_, la velocidad de las todas las flechas que ya habían sido creadas disminuye, pero las flechas que se empiezan a crear, después de reanudar la partida, se mueven a velocidad normal.

Esto mismo me pasa con el nivel _maestro cumbia_. Pero también ocurre que pese a que no utilizo el botón _pausar_ hay flechas que se crean y que se mueven a menor velocidad que el resto. 

Como dije al principio, todas mis flechas se mueven (en principio) a la misma velocidad (es un parámetro, no depende del tipo de flecha) y como esto ocurre tanto cuando ocupo el botón _pausar_ como en casos en donde no lo utilizo me inclino a pensar que este problema se podría deber a las preferencias de acción que tienen los QTimer/QThreads en el computador.
Cabe recalcar que este error no ocurre en el nivel _principiante_ en donde la cantidad de flechas (i.e. QThreads) creados por segundo es menor que en los otros niveles.

Espero que me pueda ayudar a encontrar una solución a este problema, 
Saludos! :)

**Comment by danckoo1** [comment]
hola! mmh podrias hacer un push a tu repositorio para ver como implementaste todo y probar si ocurre lo mismo en mi computador, ya que suena a un problema bastante especifico :)

**Comment by ignaciomansuy** [comment]
Hola! Ya hice el push, puede correr directamente el archivo front_juego.py

**Comment by danckoo1** [comment]
mil disculpas por la tardanza, acabo de darle una mirada a tu codigo, y  es debido a como implementas la logica del movimiento de las flechas, una forma facil de solucionar este problema es implementando un qthread en vez de un qtimer en tu clase `Flecha` del backend, ya que de esta forma lograras que las flechas sean absolutamente independientes entre si y no vayan "frenando" (lo probe y funciona 👌 ).  En cuanto al porque del problema te actualizare cuando lo termine de comprender.
saludos!

**Comment by ExRage2000** [comment]
Hola, tenia un problema similar con que uso un qtimer para generar las flechas y estas se frenan, lo intenté solucionar con esto 
> implementando un qthread en vez de un qtimer en tu clase
Pero cuando hago eso el programa no me deja ponerle un carril "parent" a las flechas

**Comment by danckoo1** [comment]
@ExRage2000 qué te refieres con que no te deja? Se levanta algún error o algo por el estilo
