### ISSUE TITLE
Nombre galaxias/planetas?

### ISSUE THREAD

**Issue by naquiroz** [IIC2233/Syllabus#83]
~~Debido a que los nombres de las galaxias y los planetas deben ser unicos y seguir un formato particular, puedo yo, definir los nombres de cada galaxia y cada planeta? O debo permitrle al usuario ingresar los nombres segun sus gustos?~~

### EDIT

Creo que el enunciado explicita que debemos permitir al usuario ingresar un nombre tanto para las galaxias como los planetas. El problema, es que queda medio ambiguo con el hecho de que:
 > El programa puede manejar diversas galaxias y, por lo tanto, es necesario que cada galaxia tenga un identificador único. Este debe ser una palabra con m´ınimo 6 letras o números.

1. Nombre e identificador son lo mismo?
2. De ser lo mismo, qué debe ocurrir en caso que se ingrese un nombre ya existente? Debemos pedirle otro nombre o decir que no se pudo crear el planeta?
3. Puedo asumir que los nombres de los planetas/galaxia en el csv inicial no estan duplicados?

**Comment by leolivares** [comment]
Hola.
1) Si, nombre e identificador son lo mismo.
2) En caso de que ingresen uno ya existente, puedes volver a pedirle un nuevo nombre e informar que el nombre ya esta en uso.
3) Claro, puedes verlo como que ese archivo inicial fue producto de una ejecución anterior, y por lo tanto ya se verificó que ninguno se repetía al momento de ser creado.
