### ISSUE TITLE
Archivo civilizaciones.csv

### ISSUE THREAD

**Issue by aacamhi** [IIC2233/syllabus#83]
Hola, dos preguntas con respecto a este archivo:
Puede venir de partida algún edificio aparte del centro urbano?
Pueden venir otras personas aparte de los trabajadores, y en caso de que sí, pueden venir sin los edificios necesarios para crearlos?

**Comment by gatochico** [comment]
Hola!

Tal como se indica en el enunciado:
-Las civilizaciones sólo parten con centro urbano, no pueden partir ni con DCCowork ni con Cuartel.
-Las civilizaciones comienzan con 3 trabajadores, y ninguna otra persona.

Saludos! :cat:
