### ISSUE TITLE
Duda sobre Buscar y plantar 

### ISSUE THREAD

**Issue by dani-oviedo** [IIC2233/Syllabus#83]
* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

hola resulta que al comprobar con el test_case_06_buscar_y_plantar tengo una duda por se supone que este respeta las reglas del enunciado donde describen como se debe plantar, es decir que se debe buscar por ejemplo el "X" que este más a la izquierda y arriba,  pero mi duda es con el siguiente caso, que es el único que me tira error, al correr el código. 

Adjunto lo que aparece en la terminal

test_4 (test_05_buscar_y_plantar_facil.TestBuscarYPlantarFacil.test_4)

        Caso de esquina. Solo un predio en self.predios.
        plano_9 5x5, código_predio = 9.
        codigo_cultivo = 0, dimensiones 2x3.
         ... FAIL

Stdout:
0
DCCultivo.predios
Predio 9
[1, 1, 7, 'X', 'X']
[1, 1, 6, 6, 'X']
['X', 'X', 'X', 3, 3]
['X', 4, 'X', 'X', 'X']
[2, 'X', 'X', 'X', 'X']
DCCultivo.predios esperados
Predio 9
[1, 1, 7, 'X', 'X']
[1, 1, 6, 6, 'X']
['X', 'X', 'X', 3, 3]
['X', 4, 0, 0, 0]
[2, 'X', 0, 0, 0]

Donde por lo que entendí no se podría plantar el bloque de ceros, ya que los primeros "X" por fila serían en las posiciones [0,3] , [1,4] , [2,0] , [3,0] , y [4,1] pero en ninguna de esas cabe el bloque, de antemano muchas gracias por la respuesta.

**Comment by Agusrush21** [comment]
Lo que respecta al enunciado, este lo que quiere indicar es que crees tu bloque a partir de la esquina superior izquierda.
Tomando como ejemplo el test que presentas, vas revisando cada "X" y tomando como base para empezar a construir/ insertar el bloque tomas esa celda como la **esquina superior izquierda**.
Siguiendo esto si intentas construir tu bloque a partir de las posiciones dichas no podrás. Pero recalcando lo anterior no es que tomes la "X" mas a la izquierda disponible sino que al momento de construir tu bloque lo hará a partir de esa esquina.

Así entendí el enunciado, así lo aplique y así me funciono correctamente. Espero haber contestado tu duda
Un saludo de antemano
