### ISSUE TITLE
Archivos a incluir en el .gitignore

### ISSUE THREAD

**Issue by Bjnazar** [IIC2233/Syllabus#83]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola!
Si el codigo de mi tarea va a usar los archivos de tablero.py y parametros.py, pero estos no se van a modificar, deberían estar incluidos en el .gitignore? Y si es que deberían estar incluidos, pero ya había hecho commit, los tengo que borrar de mi repositorio de github?
Gracias de antemano

**Comment by TomasAlcalde** [comment]
Hola, tal como dice en el enunciado los archivos de parámetros y tablero deben ser omitidos mediante el documento .gitignore, por lo mismo es recomendable que los agregues en dicho documento y los elimines de tu repositorio.
Una buena práctica es diseñar y desarrollar el .gitignore en primera instancia, antes de actualizar los repositorios para evitar tener que estar borrando archivos posteriormente.
Espero esto resuelva tu duda, saludos!
