### ISSUE TITLE
Duda conteo y cantidad de tortugas juntas

### ISSUE THREAD

**Issue by Kareen45** [IIC2233/Syllabus#83]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/21)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/20)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

¿Pueden haber más de dos tortugas seguidas en la misma fila? ¿Y si es así, cómo se cuenta en la función de verificar_tortugas()?. (En el caso de 3, 4 tortugas, por ejemplo?

**Comment by pedrozavalat** [comment]
Hola @Kareen45!,
Para toda issue que realices, verifica que no se repita en el [Compilado de Issues T0](https://github.com/IIC2233/Syllabus/issues/21), ya que otro estudiante realizó la misma pregunta.

* #28 

Por favor, para las próximas issues que hagas, revisa en el compilado y verifica que otra persona no haya realizado una pregunta igual a la tuya. En el caso que no encuentres ninguna respuesta que resuelva tu duda, realizas una nueva issue. Así evitamos tener preguntas duplicadas. Ademas, debes marcar los Prerrequisitos para toda issue que realices. 

Saludos :)
