### ISSUE TITLE
función rutas posibles

### ISSUE THREAD

**Issue by connandiaz** [IIC2233/Syllabus#83]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/20)).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/19)).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

¿Puedo asumir que las rutas para el caso de la función rutas posibles es siempre de izquierda a derecha?

**Comment by pedrozavalat** [comment]
Hola @connandiaz 😄 !
Si, debes asumir las rutas posibles es de izquierda a derecha. La función `rutas_posibles` debe retornar una cantidad de rutas posibles desde una estacion inicial hasta otra final con una cantidad específica de estaciones intermedias, pero no al revés. Por ejemplo, si tenemos la siguiente matriz de conexiones:
```python 
conexiones = [
    [0, 1, 0],
    [0, 0, 1],
    [1, 0, 0]
]
estaciones = ["A", "B", "C"]
```
Al verificar las rutas_posibles("A", "C", 1)  (con solo 1 estacion intermedia) te retornará 1, ya que existe la ruta "A" -> "B" -> "C". Sin embargo, para el caso contrario (de derecha a izquierda), no existe ruta con una estacion intermeda de "C" hasta "A" ("C" -> "A" es la unica ruta posible y no presenta estaciones intermedias), por lo tanto retornaría 0 en este caso.

Saludos!
