### ISSUE TITLE
Duda: Referencias de código externo (README)

### ISSUE THREAD

**Issue by anais-mv** [IIC2233/Syllabus#83]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola!, tengo una duda sobre lo que hay que escribir en las referencias de código en el README. 

Por lo que entiendo debemos especificar en qué parte de nuestro código está implementado esto, diciendo _está implementado en ´´´función()´´´_, debemos decir en qué línea se encuentra la función o en qué línea dentro de la función estamos usando el código externo? o ambas?

**Comment by catalina-arcila** [comment]
Hola @anais-mv, la verdad mientras mayor explicación mejor jaja. Pero si tu código está ordenado, comentando en la función que está implementado y mencionando su respectiva linea debería bastar 😄.

**Comment by anais-mv** [comment]
ok gracias!
