### ISSUE TITLE
Duda sobre importe de clases

### ISSUE THREAD

**Issue by gaspar-mr05** [IIC2233/Syllabus#83]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola. Está permitido importar Clases en archivos creados por uno mismo? Por ejemplo hice un archivo para definir funciones, y quiero ocupar instancias de clases en esas funciones, en ese caso puedo importar Clases en ese archivo? Lo mismo me pregunto para los archivos de las mismas clases, puedo por ejemplo importar la clase PiezaExplosiva en el archivo de la clase Tablero?

**Comment by ManuelV03** [comment]
Hola, si puedes importar tus clases a otros archivos, ya sean los que se te piden u otros creados por ti. Avísame si se resolvió tu duda.
