### ISSUE TITLE
Acceso métodos clase a través de clase que la compone.

### ISSUE THREAD

**Issue by fgbruna** [IIC2233/Syllabus#83]
En la [AC02 2017-1]( https://github.com/IIC2233/Syllabus-2017-1/blob/master/Actividades/AC02/Enunciado_AC02.pdf)se debe crear la clase `Personality` que debe acceder,si es que interpreto bien el enunciado, a ciertos métodos de otra clase llamada `Client`,es decir se debe evitar acceder al atributo personality a través de la clase cliente.
La pregunta es,es posible hacer eso? ,Si es que se puede como de haría,o no estoy entendiendo bien el enunciado?

**Comment by fringlesinthestreet** [comment]
En el enunciado se dice que el cliente posee un atributo `personality` en donde se debe tener un objeto de clase `Cool` o `Hater`, los cuales (se puede inferir) heredan de la clase `Personality`.
El enunciado también exige que la clase `Client` posea el método `eat`, en donde se debe calcular la calidad promedio del plato para ver si está feliz (`im_happy`) o enojado (`im_mad`). Sin embargo, para estos dos métodos no se exige que los tenga la clase `Client`. Como la reacción de estos métodos depende del tipo de personalidad, éstos deben pertenecer a la clase `Personality`. Además, como las reacciones deben ser distintas entonces cada subclase debe sobrescribirlo.

Por lo tanto, __no__ es necesario que la clase `Personality` acceda a métodos o atributos de la clase `Client`.

**Comment by fringlesinthestreet** [comment]
Ahora bien, sí es posible que la clase `Personality` pueda acceder a ciertos atributos o métodos de la clase `Client`. La manera intuitiva que uno podría pensar sería que `Personality` tenga como atributo a su objeto cliente asociado, sin embargo esto es incorrecto porque se generaría una modelación circular. 
Si quieres saber más puedes revisar esta [issue](https://github.com/IIC2233-2016-1/syllabus/issues/481) de un semestre pasado donde se explica esto en mayor detalle.

**Comment by fgbruna** [comment]
Gracias!,me estaba complicando más de lo necesario.
Pero si me encontrara con una situación en donde quiera hacer lo que dije,es posible? O no tiene mucho sentido?

**Comment by fgbruna** [comment]
Muchas gracias por la aclaración!

**Comment by fringlesinthestreet** [comment]
Ese no es el problema. Uno puede instanciar la otra clase en el `__init__` de la compuesta y pasarle `self` como argumento (esto entregaría el objeto a la clase que se instancia, que puede ser guardado en un atributo). Un ejemplo:

```
class ClaseB:
    def __init__(self, clase_a):
        self.clase_a = clase_a

class ClaseA:
    def __init__(self):
        self.clase_b = ClaseB(self)

```

El problema ocurre porque la clase `ClaseB` tiene acceso sin restricción a los atributos y métodos de la clase `ClaseA`, por lo que puede cambiar atributos y estados (lo cual en una situación real no tiene sentido). Revisa la [issue](https://github.com/IIC2233-2016-1/syllabus/issues/481) que te presenté donde salen más detalles.

**Comment by fgbruna** [comment]
Ok!, ahí si me quedó claro!
