### ISSUE TITLE
como controlar el cwd

### ISSUE THREAD

**Issue by SamWeinstein** [IIC2233/syllabus#83]
Hola, estoy programando la parte en que debemos cargar una partida guardada, sin embargo, me da un error: not a directory: {path relativo}. Mediante el uso de os.getcwd() noté que tenia este problema porque mi programa se estaba corriendo desde "\~". El problema se soluciona **AVECES** al moverme manualmente por el terminal hasta el directorio correspondiente (T00), pero no siempre funciona. Como puedo asegurarme que al llegar a esta parte el código se ejecute desde la carpeta T00 y no "~"? O basta con especificar en el README que el código debe correrse desde ese directorio? 
PD: esto es para leer un archivo que esta en T00/partidas y el archivo .py donde esta mi programa esta en T00

**Comment by jeschuwirth** [comment]
Hola,

Para corregir tu tarea siempre se va a correr desde el directorio, es muy raro que se ejecute un programa en un directorio donde no te encuentras actualmente.

En el siguiente [link](https://thispointer.com/how-to-change-current-working-directory-in-python/) te recomiendan el commando os.chdir(path) para elegir la carpeta en la que estas trabajando actualmente y así no te tengas que mover a ella a mano para ejeutarla.

![image](https://user-images.githubusercontent.com/37160256/63216296-5794ac00-c101-11e9-900d-d4be85c9a654.png)

Suerte!

**Comment by SamWeinstein** [comment]
Gracias! Usé otro comando que encontré en internet del mismo estilo. Debo referenciarlo? Como comentario o en el README?
Gracias nuevamente.

**Comment by jeschuwirth** [comment]
Si es una función o clase librería permitida, entonces no es necesario citarlo :)
