### ISSUE TITLE
Duda practica (no se cual seria un buen titulo)

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2233/Syllabus#83]
¿Es computacionalmente muy pesado (o no recomendable) si toda la información de los archivos la almaceno de alguna forma al inicio de mi programa y no me relaciono mas con los archivos, sino hasta el final por si quiero actualizar la información?

**Comment by FernandoPieressa** [comment]
Hola! Cuando son archivos muy grandes (como millones) es mala practica por la cantidad de memoria que usara tu programa, por lo tanto lo mejor es trabajar con información que después pueda ser borrada luego de ser utilizada en tu programa. Mas adelante en el curso veras generadores donde podrás hacer esto de manera efectiva.
Para el caso de la tarea esta bien hacer lo que dices.

Saludos!
