### ISSUE TITLE
Duda saldo de deuda

### ISSUE THREAD

**Issue by MaxAl100** [IIC2233/Syllabus#83]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Siendo el objetivo principal de esta tarea **pagar la deuda**, me dí cuenta de que nunca es mencionado en el enunciado **como** es que se paga esta. Tiene el jugador que escojamos tener más dinero que el valor de la deuda total? O se puede ir pagando de a poco? Tal vez tiene que tener un interés cada cierta cantidad de turnos? Se puede pagar cierta cantidad en cualquier momento?

Nada de esto es mencionado en el enunciado y por eso estoy haciendo un issue del tema.

**Comment by jtvaldivia** [comment]
Hola, 
![Captura de Pantalla 2022-04-03 a la(s) 11 31 24](https://user-images.githubusercontent.com/80768875/161435548-574a5926-4975-4169-afb3-39f5012ce1f3.png)
Como se dice en el enunciado tu objetivo es conseguir el dinero necesario para pagar la deuda, de esta manera uno al llegar a este dinero o superarlo ganara de manera automática el juego.

**Comment by MaxAl100** [comment]
> Hola, ![Captura de Pantalla 2022-04-03 a la(s) 11 31 24](https://user-images.githubusercontent.com/80768875/161435548-574a5926-4975-4169-afb3-39f5012ce1f3.png) Como se dice en el enunciado tu objetivo es conseguir el dinero necesario para pagar la deuda, de esta manera uno al llegar a este dinero o superarlo ganara de manera automática el juego.

En ese momento se finaliza el juego o simplemente se da la opción de finalizar?
O se da un mensaje y se vuelve al menú de inicio?
O se cierra el juego? 😅

**Comment by jtvaldivia** [comment]
Deberas dar un mensaje de que gano, y luego terminar la simulacion.

**Comment by MaxAl100** [comment]
Yap, muchas gracias!

**Comment by nicolasgarciaes** [comment]
Otra pregunta relacionada con este tema, el valor para saldar la cuenta es un parámetro que yo establezco?
