### ISSUE TITLE
Drag and drop funciona a veces

### ISSUE THREAD

**Issue by tomytable** [IIC2233/syllabus#830]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, estoy implementando el Drag and drop para los pingüinos pero me pasa que a veces me funciona y otras no. Ayer en la noche me funcionaba y hoy intenté avanzar un poco más con la tarea (intentando hacer que los pingüinos de la pista bailen) y me dejó de funcionar. No estoy seguro si agregué algo que pueda haber interferido en el correcto funcionamiento.

Hice push de mis archivos actuales para que tengan acceso a mi código.

**Comment by danckoo1** [comment]
hola! por casualidad tu problema aun persiste?  ya que revice tu archivos actuales y el drag and drop me funcionaba perfecto 👀

**Comment by tomytable** [comment]
Hola, sí, aún tengo el problema. A eso me refería con que a veces funciona y a veces no. Estoy trabajando desde Mac y Visual Studio por si esa información fuera útil.

**Comment by tomytable** [comment]
Al final guardé mi archivo de QtDesigner como una copia de si mismo con el "guardar como" y al usar la nueva copia me permite hacer el drag and drop. ¿Sabes por qué pasa esto? @danckoo1

**Comment by gatochico** [comment]
Hola! @tomytable , No sé si tienes los dos archivos .ui (el original que no funcionaba y el nuevo), si es así podrías abrirlos y comparar qué es lo que cambió (no son complejos de leer y analizar). Una idea que se me ocurre es que el original tenía paths relativos incorrectos y al usar "guardar como", el archivo nuevo se guardó con el path relativo correcto 🤔
