### ISSUE TITLE
Fechas Tweets - GMT

### ISSUE THREAD

**Issue by B-Dominguez** [IIC2233/Syllabus#830]
Holaa,
Debido a que los tweets son de ciudades alrededor de todo el mundo (con distintas zonas horarias) supongo que está bien dejar el formato de las fechas de los tweets con gmt +0 ?
Porque entrar a cambiar a la hora local de cada tweet creo que escapa de esta tarea, y convertir a la hora local del programa no tiene mucho sentido porque es engañoso con la hora que realmente se hizo el tweet (el usuario pensaría por ejemplo que tweets que son en el día en verdad son en la noche).

Graciaaas
pd: ya, es cierto, también sería un cacho menos jajjajaja

**Comment by ifcarrera** [comment]
Sin importar la zona horaria, dos días son 48 horas en todo el mundo. Así que da lo mismo. 
Saludos

**Comment by B-Dominguez** [comment]
Claroo, esque me refería para imprimir la fecha en el tweet, pero me acabo de acordar que eso ni siquiera era requerimiento del enunciado (lo puse porque me pareció buena info), así que lo voy a dejar así nomás
Gracias!

**Comment by ifcarrera** [comment]
:D

**Comment by fgbruna** [comment]
Pero en [#802](https://github.com/IIC2233/Syllabus/issues/802) recomendaron poner esa información,
>Dado que te pedimos una restricción de tiempo y que ordenes los tweets según los seguidores, sería bastante útil que pusieras la fecha de creación y el número de seguidores del autor.

Entonces no se considera para el puntaje de la tarea :grinning: ?

**Comment by bedefrunner** [comment]
@ifcarrera sigo sin poder resolver este problema de diferencias de zona horaria. Entiendo que 2 días son 48 horas en todo el mundo, pero para obtener 20 tweets que se hayan posteado dentro de los 2 ultmos dias, necesariamente tengo que comparar la hora de posteo del tweet con la hora actual, y esta hora actual es la hora de aquí en santiago.

Un ejemplo de un problema que esto podría generar:
en algún lugar del mundo la hora va por delante de la nuestra por 2 horas. Alguien publicó un tweet en la fecha 25 de noviembre 09:00am hora local, es decir, el 25 de noviembre 07:00 hora en chile. El programa se corre aquí en Chile el dia 27 de noviembre a las 08:00. Considerando el huso horario, ese tweet no cumple con la restriccion, pues fue publicado hace 49 horas. Sin considerar el huso horario, el tweet cumple con la restricción pues fue publicado hace 47 horas.

Cómo lo hacemos para no caer en inconsistencias de horario?

**Comment by ifcarrera** [comment]
Hola, no te compliques tanto en esa parte. Puedes asumir cualquiera de las dos formas (0000 o -0300), siempre y cuando seas consistente y lo pongas en tu README
