### ISSUE TITLE
Flechas normales a veces caen a distinta velocidad

### ISSUE THREAD

**Issue by n4chin** [IIC2233/syllabus#831]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Holaa, tengo el mismo problema que en la issue #779  y la issue #750. Las flechas a veces bajan la velocidad de forma drástica y no sé porque. Antes habían veces que me decía: **QThread: Destroyed while thread is still running**. Pero leyendo la issue que mencioné anterior pude arreglar eso, sin embargo me siguen cayendo flechas a velocidades distintas. 
[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by ExRage2000** [comment]
A mi me sucede algo parecido, las flechas se ralentizan de vez en cuando y luego vuelven a la normalidad, pero como el "cooldown" de las flechas nuevas no se detiene, algunas flechas terminan avanzando mas juntas que otras
![Captura de pantalla (75)](https://user-images.githubusercontent.com/69613733/97220171-d6778100-17a9-11eb-8aaa-e9b664c5b7ea.png)

La única diferencia es tal vez que flechas de distintos threads no avanzan a distintas velocidades entre si, pero eso creo que tiene mas que ver con cuantos timers usé (no creo que sea suficiente como para abrir una issue aparte)

**Comment by aaossa** [comment]
Hola, en #931 el problema se solucionó con un cambió chico, ¿podrías ver si te funciona?

> (...) creo que lo que ocurre es que tus QThread no tienen el mismo "ciclo de vida" que su parent. En tu caso, para arreglarlo debes asegurarte de pasarle el parent a través del super: super().__init__(parent). (...)
