### ISSUE TITLE
Validaciones

### ISSUE THREAD

**Issue by ciquezada** [IIC2233/Syllabus#831]
Hola, como no respondieron la issue pasada, en mi código hice que el cliente cargara el archivo json para validar cualquier consulta. ¿Es correcto hacer eso?

por otro lado:
¿Seria correcto que el cliente solo verificara formato, por ejemplo que la ciudad esté escrita solo con letras y la id solo con números y que sea la API la que cargue el json para validar?

**Comment by ptflores1** [comment]
Hola ! revisa #798

**Comment by ciquezada** [comment]
ahh gracias, entonces para confirmar, lo que propongo está bien para esta tarea, no así para un caso mas real
