### ISSUE TITLE
Error luego de crear log

### ISSUE THREAD

**Issue by naazocar** [IIC2233/Syllabus#831]
Holaa, luego de crear mi módulo con lo que involucra al log, al ejecutar mi programa (sin si quiera importar log), y darle el url de la google sheet, me tira este error.

No entiendo de donde sale, pero el problema comenzó luego de crear el módulo log, y si lo comento entero deja de suceder. Ayuda :C

![screenshot from 2017-11-27 17-58-29](https://user-images.githubusercontent.com/30675195/33288971-b8aba8da-d39c-11e7-85df-b09376ebbf2a.png)
![screenshot from 2017-11-27 17-58-19](https://user-images.githubusercontent.com/30675195/33288975-bae7f252-d39c-11e7-8f4a-bc1e55f65c4d.png)

**Comment by fgbruna** [comment]
Hola!, me pasó lo mismo, es un conflicto del wrapper de sheets con esa librería si no me equivoco, solo tienes que agregar el sgte parametro al metodo `build` de `discovery`:
```python
cache_discovery=False
```

**Comment by naazocar** [comment]
Buenísima ! Gracias :D
