### ISSUE TITLE
error 32 en twitter api

### ISSUE THREAD

**Issue by mundurragac** [IIC2233/Syllabus#832]
me aparece este error cuando intento hacer un request
{"errors":[{"code":32,"message":"Could not authenticate you."}]}

**Comment by andresfdezc** [comment]
En ese link la gente ha escrito varias razones de por qué les ha aparecido ese error. En un inicio, puede ser simplemente porque no estás pasando el token indicado para hacer la request.

https://twittercommunity.com/t/errors-message-could-not-authenticate-you-code-32/1223/80
