### ISSUE TITLE
Problema con la contabilización del tiempo

### ISSUE THREAD

**Issue by BFry712** [IIC2233/syllabus#832]
### Prerrequisitos

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Holaa! necesito ayuda, ya que cuando la partida comienza, me funciona todo bien sin mandar la señal para contar el tiempo segun el nivel de dificultad, pero si mando esta señal hacia el backend las flechas no caen, la musica no suena y solo aumenta la barra de progreso. He intentado arreglar esto pero no he podido :c 
Saludos!

**Comment by knight-who-say-ni** [comment]
Hola @BFry712 !!

¿De casualidad estás poniendo un `time.sleep()` en alguna parte del front_end, no acoplado a ningún thread independiente?? Si es así, esto detendría toda la ejecución del programa...

Lo otro que puede estar pasando es que cuando envías la señal esta provoca que se termine algun thread, o impide que se inicia algún metodo.

Espero que lo logres arreglar!! Estaré atento 👌

**Comment by BFry712** [comment]
Hola @knight-who-say-ni ! 
Debe ser la segunda opción :c porque al comenzar la partida emito las señales y eso lo veo en el backend que ahi si implemento time.sleep().
Cuando inicio el programa asi, este se me cae y debo forzar el renicio de vs code.

**Comment by knight-who-say-ni** [comment]
Pero ese `time.sleep()` lo provoca la señal en cuestion?? Porque si ese es el caso, y el tiempo se pausa en el código principal en vez de un thread propio se va a pausar todo 👀 

Lo otro, es preferible que corras tu programa desde la consola de tu PC en vez de la terminal de VSCode, ya que está última tiene varios problemas con el manejo de paths y pyqt5 😄
