### ISSUE TITLE
Borrar un QLabel

### ISSUE THREAD

**Issue by lewebe** [IIC2233/syllabus#832]
Hola, hay algún método para borrar de forma instantánea un QLabel? Lo que pasa es que hice una funcion en mi frontend que carga a las entidades como QLabels en el mapa ya sea por medio del archivo `mapa.csv` o por el drag & drop. Sin embargo, debo crear la QLabel primero con las dimensiones y posición apropiadas y **después** chequear que esa nueva QLabel no colisione con las ya cargadas dentro del mapa. Lo que quiero hacer es que en caso de que efectivamente esta nueva QLabel colisione con una ya cargada, pueda eliminar la nueva y que no se cargue. Hay alguna manera de hacerlo?

**Comment by matiasmasjuan** [comment]
Hola @lewebe !

Desconozco la forma en que puedas **eliminar** un ***QLabel*** además de **redifinirlo** con el uso de ```self.label_que_quiero_borrar = None```. Tampoco tengo claridad de qué método en específico te pueda ser útil, ya que los métodos de ```label.clear()```, ```label.hide()```, ```label.show()```, ```label.deleteLater()```, limpian el contenido del ***QLabel***, pero no la existencia de él, por lo que no se si pueda serte útil de acuerdo a tu modelo. Quizás algún método dentro de la [Guía de QLabels](https://doc.qt.io/qtforpython/PySide2/QtWidgets/QLabel.html) pueda servirte de ayuda. Si ese no es el caso, intentaría buscar otras soluciones para que puedas implementar tu idea, como usar ***QLabels*** auxiliares o cosas de ese estilo.

Saludos y mucho éxito con la tarea!

**Comment by lewebe** [comment]
Gracias por la respuesta, pero si no se puede borrar un QLabel, ¿cómo voy a hacer algunas de las cosas que me piden en el enunciado? Por ejemplo, eliminar una mesa al hacerle click en la preronda, o que un bocadillo "desaparezca" de la mesa del chef si colisiono con ella

**Comment by matiasmasjuan** [comment]
Hola @lewebe !

Existen múltiples formas de lograr esto a través de los métodos que señale con **anterioridad**. Ahora bien, **depende** de **tu** **implementación** el **cómo** haces uso de estas **herramientas** para lograr los objetivos que quieras, como de que al hacer click en una mesa, "desaparezca", o que los bocadillos también "desaparezcan" al momento de colisionar, o cuándo saber si puedes "colisionar" con un ***Qlabel*** o no, etc.

Lamento mucho no poder dar más información, pero uno de los objetivos de esta tarea es que ustedes sean capaces de pensar en cómo realizar estas funcionalidades a través de las herramientas de **PyQt**.

Mucho éxito con la tarea! 😄
