### ISSUE TITLE
Duda, cliente-servidor

### ISSUE THREAD

**Issue by jerrymendoza** [IIC2233/Syllabus#832]
No me queda muy claro si todas las opciones deben funcionar a través de la api propia, o puede en el cliente guardar todas las opciones y solo generar las consultas tiempo y uv y posterior envió por mail.
Por ej, en el cliente verificar que existe la ciudad al registrarla (localmente, buscando en el json), definir las opciones a buscar y luego al ingresar a la opción de enviar el correo, que se envié la petición a la api propia
o por otro lado, al ingresar una ciudad desde el cliente, verificar con la api propia si existe esa ciudad (aca el json lo leería el servidor)... y guardar la opción localmente si es valido

espero se entienda
Gracias!

**Comment by rihanuch** [comment]
Hola, ya hay una issue sobre eso
