### ISSUE TITLE
Drag n Drop: obtener pixmap de QLabel

### ISSUE THREAD

**Issue by dlmed** [IIC2233/syllabus#833]
Hola, estoy tratando de implementar el drag and drop, pero lo único que no se hacer es cómo pasarle el pixmap del QLabel que le estoy haciendo drag al QMimeData definido en el mouseMoveEvent() del QLabel. Si alguien me pudiera iluminar sería genial. Gracias de antemano!

Quizas otra forma sea que el path sea guardado como parámetro del QLabel y este sea pasado al setText() del QMimeData (?) Pero siento que esto lo haría más complicado, siento que si se pudiera pasar el pixmap sería mucho más simple.

**Comment by dlmed** [comment]
Quizas otra forma sea que el path sea guardado como parámetro del QLabel y este sea pasado al setText() del QMimeData (?)

**Comment by danckoo1** [comment]
Hola! Si quieres obtener el `Qpixmap` de algún label podría resultarte útil el método `pixmap()` que poseen los `QLabel`. En la documentación está explicado su funcionamiento por si buscas más detalles :)

**Comment by dlmed** [comment]
Si se que se puede retornar un QPixmap con .pixmap(), pero el tema es cómo pasarselo al QMimeData. De todas formas, creo que no sería la solución más óptima de hacer drag n drop (o no? jaja).

**Comment by danckoo1** [comment]
Mmh quizás podrías obtener el pixmap, luego convertirlo a una `QImage` y así pasárselo al QMimeData, para lo que te resultarían útiles los métodos de `toImage()` Del pixmap y `setImageData()` del Qmimedata. 
En cuanto a si es lo más óptimo no sabría decirte, ya que yo igual he ocupado este camino para implementar el drag n drop 🤷🏽‍♂️

**Comment by dlmed** [comment]
Gracias!!
