### ISSUE TITLE
Fecha pronóstico UV

### ISSUE THREAD

**Issue by Panckx** [IIC2233/Syllabus#833]
Hola! No entiendo bien para qué sirve que rescatemos la fecha de la respuesta del pronóstico uv si es obvio para qué día es cada pronóstico (aparte que es mucho más fácil usar cuna librería como time para calcular el día de cada request sabiendo que siempre van a ser del mismo día u ocho días más)

**Comment by rihanuch** [comment]
Hola, es pra que se use la api

**Comment by pcseisdedos** [comment]
En el enunciado sale que debemos rescatar `date` pero creo que sería mejor rescatar `date_iso` porque es mas entendible, pueden mirar este ejemplo[`{"lat":37.75,"lon":-122.37,"date_iso":"2017-06-27T12:00:00Z","date":1498564800,"value":10.1}`](https://samples.openweathermap.org/data/2.5/uvi/forecast?lat=37.75&lon=-122.37&appid=b6907d289e10d714a6e88b30761fae22)
