### ISSUE TITLE
Verificacion de partida y QComboBox

### ISSUE THREAD

**Issue by nicolecll** [IIC2233/syllabus#833]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola, me surgió la duda sobre si **el programa debe verificar la partida incluso si las opciones elegidas son las primeras dentro de los QComboBox de canciones y dificultad**, ya que por ejemplo si el usuario escoge Canción 1 y Principiante, los ComboBox ya se encuentran con esa opción por defecto (son las primeras). En este caso ¿es necesario que el usuario haya clickeado directamente estas opciones, para que la partida sea autorizada?

**Comment by aljara97** [comment]
Hola, es válido que el usuario pueda iniciar una partida si es que la empieza con las opciones por defecto de los QComboBox. Lo importante es que se verifique que correspondan a opciones válidas y que el usuario pueda cambiarlas si así lo desea.

Espero haber aclarado tu duda 🐧
