### ISSUE TITLE
Flechas se generan a frecuencia inconstante

### ISSUE THREAD

**Issue by Sofia-Arratia** [IIC2233/syllabus#834]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola!
 Me pasa que, a pesar de haber definido un intervalo de tiempo fijo para la generación de flechas, las flechas se generan a una frecuencia inconstante. Supongo que será un problema de threads, pero no se bien que hacer para arreglarlo. Además tengo un error al intentar borrar las flechas, pero supongo que tendría que poner esto en otra issue. No se bien como explicar mi implementación de threads acá para encontrar el origen del (o de los) problema :c espero alguien sepa por qué pasa.
Muchas gracias de antemano!

PD: habrá alguna otra instancia de sala de ayudantía? teniendo mas avanzada la tarea, a mi y varios compañeros nos han surgido varias dudas y problemas, sería muy bueno si se pudiera dar una instancia así denuevo ☺️

**Comment by furcelay** [comment]
Hola @Sofia-Arratia !

Perdón por la demora, he estado haciendo pruebas en tu tarea y todo parece correr bien, las ejecución del generador de flechas ocurre a intervalos constantes y no veo problemas con tus threads (aunque el sleep de las flechas es muy pequeño entonces se ve que se mueven a "saltitos", te recomiendo bajar el valor de `self.t_interval`). 

Lo que creo que ocurre es que como no has implementado todos los tipos de flecha cuando una flecha no es del tipo '*simple*' el generador no hace nada y por eso no hay flecha en la ventana y pareciera que el intervalo de generación es constante. Para verificarlo puedes hacer prints dentro de `generate_arrows` con el tiempo transcurrido desde la última generación (por ejemplo `print(time.time() - self.time_ref)` en `run` y con `self.time_ref = time.time()` en el `init` de la clase para tener un tiempo de referencia), puedes ver que siempre se ejecuta cada 1 segundo pero solo aparece una flecha si es del tipo '*simple*'.

Espero que eso haya resuelto tu problema, saludos! 😄

**Comment by Sofia-Arratia** [comment]
OOOOOOOOH que pava jajajaj, se me habia olvidado que quería implementar los espacios de las decimas extra 😅 por lo menos ahora se que debo hacer un intervalo mas pequeño jajaj ¡Muchas gracias! Perdón por hacerte perder el tiempo 😬 (Te cuento que también logré resolver borrar las flechas jajaj) Que estés muy bien ☺️
