### ISSUE TITLE
Error con API weather

### ISSUE THREAD

**Issue by ValentinaAlvarezG** [IIC2233/Syllabus#834]
Hola! :c ayuda por favooor! la tarea en general me estaba funcionando super bien pero ahora me esta tirando el sgte error:
"requests.exceptions.ConnectionError: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?id=1857578&units=imperial&appid=f108bf31a1fc838cc2e7fe8aa157257b (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x03D0FBB0>: Failed to establish a new connection: [WinError 10060] Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder',))

No entiendo por que habla de que se ha excedido la cantidad maxima de reintentos con la pagina de weather :'(

**Comment by CristobalHV** [comment]
no soy ayudante, pero supongo que la api de weather te bloqueó por acceder demasiadas veces a ella

ni no recuerdo mal se supone que es temporal, pero no se por cuanto tiempo :/

**Comment by jmwielandt** [comment]
tampoco soy ayudante, a mí me tiró otro error (me echaron desde el host remoto) pero cambié la key y creo que está funcionando.
Supongo que es por lo de evitar un ataque DDoS... a todo esto, banner tiene ese tipo de protecciones? Porque tiene que tener un margen muy alto pero al mismo tiempo puede ser suficiente como para romper algo, no?
