### ISSUE TITLE
Qt Designer dejo de funcionar

### ISSUE THREAD

**Issue by Francisco5674** [IIC2233/syllabus#834]
Hola, les cuento, resulta que ya use Qt Designer antes para construir la ventana inicial del juego, y todo funcionaba perfecto, después me encargue de crear la IA del chef, los clientes, gran parte del back end, pero me doy cuenta que necesito más front end para hacer la ventana de resumen de la post ronda y cambiar algunos aspectos visuales del juego que son un poco toscos, abro el Designer para trabajar, me dispongo a setear stylecheet y el programa se congela, no muestra opciones ni nada, deja de responder absolutamente, he buscado en internet y nada, lo que pienso pudo haber pasado es que hace un par de días se actualizo mi windows, lo que debió haber detonado este problema ya que al instalar PyQt5 y tools había tenido problemas antes, tuve que hacer unas cosas de una guía que mandaron en una issue anterior para poder trabajar. 
Lo malo es que necesito trabajar y el Designer no funciona, como ultima opción pensaba en hacer las ventanas que quedan a base de código, claro que serán sumamente feas en comparación que como lo hacía con Designer.

**Comment by fdoflorenzano** [comment]
Hola @Francisco5674,

La verdad es difícil saber que hacer sin mucha más información. Puede sonar tonto, pero intentaría reiniciando el programa, el computador completo, o desinstalando y volviendo a instalar el programa, si nada funciona.

Como mencionas, si nada funciona, siempre puedes hacer las ventanas a partir de código. Anticipar que sean feas es algo injusto, ya que depende de ti como se vean, y tampoco es realmente el foco. En ese caso buscaría primero funcionalidad y luego arreglos estéticos.

Saludos.

**Comment by Francisco5674** [comment]
Intentaré reinstalarlo, es lo único que no he probado, solo que tenia algo de miedo ya que cuando tuve que instalarlo me costo mucho debido a problemas en los path de instalación, si no puedo, creo que crearé esa ultima ventana a mano y listo, muchas gracias por su tiempo! Saludos

**Comment by Francisco5674** [comment]
Ya esta solucionado!!, lo reinstale y funciono normal nuevamente, muchas gracias!
