### ISSUE TITLE
Rate limit

### ISSUE THREAD

**Issue by behrmann97** [IIC2233/Syllabus#834]
Al intentar obtener los woeid de los tweets, me dice el siguiente error:
{"errors":[{"message":"Rate limit exceeded","code":88}]}

Según lo que leí, es que el API tiene un límite de consultas por tiempo. ¿Esto sucede porque adquirí mal los tokens?

**Comment by ifcarrera** [comment]
Eso te ocurre al hacer UNA consulta o luego de hacer varias ?

**Comment by behrmann97** [comment]
Luego de hacer 15, con tiempos de 15 minutos

**Comment by ifcarrera** [comment]
En ese caso tranquilo, tendremos cuidado en hacer menos de 15 en 15 minutos, es lo que permite hacer la api de Twitter para que no colapsen sus servidores.
Ahora sí estás en un ciclo haciendo muchas requests al mismo tiempo sí es un problema. 
Saludos
