### ISSUE TITLE
Información sobre drag and drop

### ISSUE THREAD

**Issue by fedezang** [IIC2233/syllabus#835]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, quería saber si existe alguna pagina donde pueda encontrar buena información sobre Drag and Drop, ya que el enunciado no da alguna sugerencia sobre esto. La verdad ya he buscado bastante pero no encuentro información buena y entendible. Y no he logrado implementar esto en mi tarea.

**Comment by eliasbruchfeld** [comment]
x2

**Comment by gatochico** [comment]
Hola @fedezang !

Uno de los objetivos de esta tarea es que aprendan a investigar sobre una librería externa, en este caso PyQt5, por lo que no puedo darte links directos a implementaciones 😓 

Te puedo dejar como base para tu búsqueda la documentación de Drag and Drop de QT (la librería original en que se basa PyQt5): [Documentacion](https://doc.qt.io/qt-5/dnd.html). Si te fijas, esto está implementado en C++, sin embargo la lógica general debería aplicar también a python. 

Saludos y éxito en la tarea!
