### ISSUE TITLE
Threading - webscrapping

### ISSUE THREAD

**Issue by dlmed** [IIC2233/syllabus#835]
Hola, estoy **tratando** de hacer un proceso de webscrapping más eficiente con threading, pero me encuentro que el resultado es más lento que sin threading jajaja yo creo que probablemente algo estoy haciendo mal, por eso les pido si alguien me puede iluminar. (La idea es que como tengo que procesar varias pags web, pensé que se podían hacer por threads de forma más rápida). Este es mi main.py generalizado:

```python
lista = list()

class ClaseThread(threading.Thread):
    def __init__(self, argumentos):
	super().__init__()
	self.argumentos = argumentos

    def run(self):
        # proceso de webscrapping y procesamiento de esos datos

threads = list()
for sitio in sitios:
    # aquí antes hacía:  # proceso de webscrapping y procesamiento de esos datos
    thread = ClaseThread(argumentos)
    threads.append(thread)

for x in threads:
    x.start()
for x in threads:
    x.join()

# más procesamiento, pero ahora usando lista, en donde se van appendeando los resultados de cada thread

```

EDIT: Comparando de mejor forma (con más volumen de threads), ahora me doy cuenta que el método con threading se demora **1.949 s**. y el método sin threads, **4.582**.
Entonces, mi pregunta sería, es esta la forma más eficiente de aplicar threads en este caso?

**Comment by fdoflorenzano** [comment]
Hola @dlmed,

Es algo ambigua tu pregunta, ya que se podrían hacer muchas preguntas para especificar ¿Más eficiente en términos de **qué**? ¿Qué hace cada método `run`? ¿Accede a distintas páginas o tiene cosas en común?

Por contexto asumo que buscas sea más eficiente en términos de tiempo. Y si esa es tu meta, entonces es difícil de encontrar un **optimo** con el uso de *threads*, ya que esto no necesariamente implica que trabajo sea simultaneo y disminuya el tiempo de computo. Si recuerdas bien, solo si tu máquina tiene múltiples procesadores, es capaz de separar trabajo simultaneo, si no, entonces aunque lo separes en múltiples *threads*, el único procesador de todas formas tendrá que hacer las operaciones. Incluso puede ser más costoso separar el trabajo en *threads* que tenerlo en un único flujo, ya que el cambio de contexto entre hilos puede ser costoso. Además, si tienes múltiples procesos andando en tu máquina al mismo tiempo, también eso puede afectar su eficiencia en tiempo.

Si quieres mejorar su tiempo de ejecución, primero revisaría el algoritmo que ejecuta cada *thread* e intentaría mejorar eso antes.

Saludos.

**Comment by dlmed** [comment]
yap, gracias!
