### ISSUE TITLE
Problema de captar la flecha en la casilla

### ISSUE THREAD

**Issue by BFry712** [IIC2233/syllabus#836]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! tengo dudas porque ejecutando mi codigo, al momento de ver si el usuario apreta la tecla correspondiente en la casilla correspondiente, a veces la capta y otras veces no(lo vi con el metodo intersects()) a que se podria deber este problema en que a veces capta el label que viene del qthread?(para que capte la flecha correcta, debo apretar a veces 2 veces la tecla)

**Comment by furcelay** [comment]
Hola @BFry712 !

Estuve revisando tu código y me costó bastante encontrar el problema (por favor intenta acortar los métodos!! 😣  hay varios que repiten lo mismo 4 veces) tienes dos problemas, uno de ellos es el de las flechas que efectivamente no siempre se capturan y el otro es con una señal que causa que el programa se 'quede pegado'.

Sobre el segundo problema no lograba encontrar que era hasta que vi tu comentario  `#con esta se me cae todo` 😆  justo después emites una señal que no está conectada a ninguna parte... :eyes:

Sobre las flechas el problema es que en tu modelamiento solo tienes una flecha como atributo `self.flecha` que va cambiando continuamente cada vez que una flecha se actualiza. Entonces cuando revisas la intersección con `self.flecha` solo lo haces con la última flecha actualizada que podría ser cualquiera de las flechas visibles por lo que es muy poco probable que sea justo la que está en la zona de captura. Cambiando esto te aseguro que puedes atraparlas con un 100% de certeza.

Espero que te haya sido de ayuda, saludos! :smile:

**Comment by BFry712** [comment]
Hola @furcelay ! Espero te encuentres bien!
* Con respecto al segundo problema, que lo haga en el main thread te refieres al mismo archivo .py del Qthread que ejecuto?
* Con respecto al primer problema no lo habia pensado como dices, y lo pude arreglar con una lista pero no se si será la forma más optima jajaja
***Muchas gracias y saludos!***

**Comment by furcelay** [comment]
*  Con el main thread me refiero a que no creas un thread dedicado a esa acción en específico, entonces cuando se ejecuta el sleep afecta a todo el programa.
*  En general usar una lista no te debería generar problemas de rendimiento mientras no sea demasiado extensa (por ejemplo si acumula flechas ronda tras ronda y nunca se vacía).

**Comment by BFry712** [comment]
Perfecto! muchas gracias!
