### ISSUE TITLE
Uso de getCoords()

### ISSUE THREAD

**Issue by Juampisaez** [IIC2233/syllabus#836]
Hola, no entiendo como se usa QRect::getCoords(int *x1, int *y1, int *x2, int *y2)
Lo que quiero es obtener las coordenadas del label para compararlos con los de otro label.

**Comment by matiasmasjuan** [comment]
Hola @Juampisaez !

Te recomiendo usar el método ```label.geometry()``` que retorna un ***QRect*** con las coordenadas y dimensiones del **Label**. De todas formas, existe una pregunta similar en la Issue #788 . Además, puedes revisar la documentación de [QLabels](https://doc.qt.io/qt-5/qlabel.html) o de [QRect](https://doc.qt.io/qt-5/qrect.html) por si necesitas información de manera mas detallada.

Saludos! 😄

**Comment by Juampisaez** [comment]
oka, gracias. Al final es lo mismo que necesitaba
