### ISSUE TITLE
existe un cuaderno de ejercicios para el examen?

### ISSUE THREAD

**Issue by bedefrunner** [IIC2233/Syllabus#836]
Hola! @indonoso nos dijo que existe un cuaderno de ejercicios para el examen que alguien hizo hace algún tiempo. Es verdad o le entendí mal? Si es verdad, dónde lo puedo encontrar? Sería de graaaaaan ayuda!

**Comment by indonoso** [comment]
Hola! No es un cuaderno :) es una guía de ejercicios. La pueden ver [aquí](https://github.com/IIC2233-2016-02/Syllabus/blob/master/Examen/GuiaExamen.pdf). Son ejercicios de exámenes anteriores a ese semestre clasificados según dificultad.

**Comment by bedefrunner** [comment]
Muchas gracias miss Ivania! :D

**Comment by ajahr95** [comment]
hay algun solucionario de esta guia de ejercicios?
