### ISSUE TITLE
Formato de entrega del mail

### ISSUE THREAD

**Issue by ibaeza1** [IIC2233/Syllabus#836]
Una duda. El mail que hay que mandar si o si tiene que ser con el formato que esta en el enunciado?
Ej: Santiago: Temperatura 50 grados y asi o queda a criterio tambien ?? 
Osea poder mandar un mail que diga :
La temperatura de hoy en Santiago son 50 grados

**Comment by nachocontreras** [comment]
Hola!

Queda a criterio, mientras el formato acepte múltiples ciudades o cualquier configuración
