### ISSUE TITLE
Validación correo de gmail

### ISSUE THREAD

**Issue by Regenschrim** [IIC2233/Syllabus#837]
Además de validar el correo de tal forma que cumpla la estructura del correo, ¿hay que validar la existencia del correo mediante la api de google o eso no se puede hacer? LLevo un rato tratando de ver como se puede hacer, pero no se si es necesario (algo como lo que hicimos en la actividad 14).

Gracias!

**Comment by cilopez** [comment]
No es necesario validar que existe el correo, simplemete basarse en las reglas de validación
