### ISSUE TITLE
Diferentes sprites para clientes apurados y relajados

### ISSUE THREAD

**Issue by tedroppelmann** [IIC2233/syllabus#837]
Hola! En mi front-end tengo que mostrar la diferencia entre un cliente apurado y uno relajado, por ejemplo, que uno sea un perro y el otro un hámster? o puedo solo cambiar su comportamiento interno pero que sea representado por el mismo personaje?

**Comment by jbulness** [comment]
Hola @tedroppelmann,

Como esto no se indica en el enunciado queda a tu criterio si muestras una diferencia en imágenes entre los personajes. Eso si, acuérdate de indicar en el `README.md` tu decisión y como lo representas finalmente. También recordarte que de igual manera debes hacer un cambio en las sprites según el estado del cliente.
