### ISSUE TITLE
Importación de archivos que importan otros archivos

### ISSUE THREAD

**Issue by pabloalvarez67** [IIC2233/syllabus#837]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola, mi duda es el como importar en este caso, dentro de T02 tengo:

|main.py
|parametros.py
|
|carpeta
-------->|archivoX
-------->|archivoY
---------|...

Resulta que quiero ejecutar mi codigo en main.py.
de main.py quiero importar a archivoX. Este último importa para hacer sus funcionalidades a archivoY.

Cuando ejecuto en archivoX anda todo perfecto, pero cuando corro el main, archivoX no puede importar a archivoY ya que supuestamente el módulo no existe.

Hay algua solución? de momento para seguir avanzando con mi código meti todo lo de archivoY en archivoX, pero me encantaría no hacerlo, ya que suma muchas líneas de código.

Saludos! leí la issue https://github.com/IIC2233/syllabus/issues/706 pero no me fue de utilidad.

**Comment by danckoo1** [comment]
Dentro del archivo x cuando importas el archivo y, intentaste escribiendo `carpeta.archivoy `, ya que si tú módulo principal es el main los paths que lee en los imports son con respecto al módulo principal, avísame si funciona!

**Comment by pabloalvarez67** [comment]
@danckoo1 funciono perfect! no tenía idea de ese detalle, muchas gracias!

**Comment by n4chin** [comment]
En este mismo ejemplo en el archivoX no podría importar el archivo parametros.py? O esto es ilegal??
