### ISSUE TITLE
Pausar diferentes threads

### ISSUE THREAD

**Issue by tedroppelmann** [IIC2233/syllabus#838]
Hola! En mi programa utilizo varios thread al mismo tiempo. Mi duda es si existe alguna forma de pausar todos al mismo tiempo? Saludos!

**Comment by fdoflorenzano** [comment]
Hola @tedroppelmann,

Si tu pregunta es si existe un método `pausa`, la respuesta es no. Ahora, hay formas de simular pausa, si te las ingenias con utilizando atributos y recursos de espera para extender el funcionamiento base de un *threads. 

Saludos.

**Comment by mpmunoz13** [comment]
@fdoflorenzano hay forma de obtener un lock para todo el sistema? Estoy tratando de implementar pausa y me pausa solo las acciones de el documento en el que estoy definiendo pausa... Hay alguna forma de obtener un global_lock que aplique para todos mis archivos?

**Comment by fdoflorenzano** [comment]
Hola @mpmunoz13,

Como dices, el punto es usar el mismo *lock* si quieres que todo el sistema siga la misma pausa. Puedes crear una sola instancia de `Lock` en tu programa, pero debes preocuparte de pasar la referencia a esa instancia por todo lo que necesite mirarlo. Cómo obtenerlo depende de tu programa, dale una vuelta como puedes crear un único *lock* que todo el programa pueda observar.

Saludos;
