### ISSUE TITLE
Qsound al pausarlo y despues detenerse vuelve a reproducir todo denuevo

### ISSUE THREAD

**Issue by diegobustosk** [IIC2233/syllabus#838]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola en el qsound cuando utilizo el método play(), lo escucho perfecto, pero cuando utilizo el metodo stop() y despues play(), lo vuelvo a escuchar todo denuevo y no donde la canción había quedado. Intente utilizar QMediaPlayer pero la documentación esta en C y no se como pasarla a python 

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by mhrobles** [comment]
Creo que es mejor usar QMediaPlayer, ahi hay una funcion que es .pause(), que si presionas se detiene donde queda y luego al dar .play() otra vez se puede continuar donde quedó, pero busca un tutorial de como usarlo

**Comment by JuaniAndres** [comment]
Hola @diegobustosk 
En la siguiente [issue](https://github.com/IIC2233/syllabus/issues/777) se habla de tu misma pregunta para que la revises. Respecto a lo que mencionas al final generalmente si a la clase que buscas en internet le específicas que es ````pyqt5 python````generalmente te entregara un resultado que es la documentación de pyqt5 en python de esa clase, en tu caso te dejo el [link](https://doc.qt.io/qtforpython/PySide2/QtMultimedia/QMediaPlayer.html) para que investigues.
Éxito en la tarea
