### ISSUE TITLE
Duración examen

### ISSUE THREAD

**Issue by jotramon** [IIC2233/Syllabus#839]
hola, tengo dos dudas, la primera, cuánto dura el examen?, me han dicho 3 y 2.5 horas, pero prefiero preguntar. Y segundo, las salas del Examen serán las mismas que las de los jueves?
gracias de antemano :)

**Comment by rihanuch** [comment]
Aprovecho de preguntar también a que hora es?😅

**Comment by naazocar** [comment]
#653

**Comment by andresfdezc** [comment]
El examen partirá mañana a las 15.30 **puntualmente** y dura 3 horas.

**Comment by andresfdezc** [comment]
Será en las salas K201 y K202. Les llegará un mail indicando a cuál de las dos deben ir.
