### ISSUE TITLE
Duda yoda api

### ISSUE THREAD

**Issue by CmPoblete** [IIC2233/Syllabus#839]
Hola, la api de yoda solo me esta moviendo de lugar unas frases sin modificarlas y me agrega frases como "Yeesssssss! The dark side I sense in you!". Esto es suficiente para tener el bonus?

**Comment by CmPoblete** [comment]
Seria suficiente si mando el reporte usando la api de yoda y el reporte sin la api para que se vean las diferencias?

**Comment by Arcoirisky** [comment]
Tranquilo xD Está bien usada la api así xD puedes conseguir el bonus tranquilo :D <3

**Comment by julioag** [comment]
Hola , con respecto a al bonus, todas las frases tienen que estar modificadas o sirve si tomo una sola frase del texto? ya que el texto que tengo tiene muchas oraciones y eso puede agotar la api muy rápido.
