### ISSUE TITLE
Clientes que quedan sin mesa

### ISSUE THREAD

**Issue by jirarrazaval** [IIC2233/syllabus#839]
En el enunciado dice que aparece un cliente cada LLEGADA_CLIENTES y que aparecen en las mesas desocupadas. Pero qué pasa si no hay mesas desocupadas? Dónde esperan?

**Comment by jbulness** [comment]
Hola @jirarrazaval! 

Si no hay mesas desocupadas no deben aparecer nuevos clientes. En la issue #704 se dan más detalles a cerca de esto.
