### ISSUE TITLE
subclase necesaria o innecesaria

### ISSUE THREAD

**Issue by ciquezada** [IIC2233/Syllabus#84]
Hola, si se me ocurrió definir una clase abstracta como "integridad" con un solo atributo, algo asi como puntos de vida, pero si luego me gustaria que una subclase, por ejemplo, "mueble" heredara este atributo y no tiene ningun otro atributo propio. ¿Es correcto definir esta nueva subclase o esta de más? y ¿definir toda una clase abstracta solo para un atributo está bien?

**Comment by IchottMano** [comment]
@ciquezada Hola!
Disculpa la tardanza al responder esta issue, sin embargo la pregunta que estás haciendo está directamente ligada al modelamiento del problema, por lo que lamentablemente no podemos responderla.
En resumen, queda a tu criterio si la subclase está de mas o no. Trata de ver cual es la solución óptima para el problema.
Saludos!
