### ISSUE TITLE
Duda de enunciado: Cómo solucionar un tablero - def solucionar(self)

### ISSUE THREAD

**Issue by kitofito** [IIC2233/Syllabus#84]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda de enunciado: Cómo solucionar un tablero (def solucionar(self))

En el enunciado se presenta lo siguiente:

-  _"Para generar dicha solución, se deben posicionar los peones que sean necesarios para que cada pieza explosiva cumpla la Regla 1 y cada peón cumpla la Regla 2 y 3."_: Esto se debe hacer cuando se entrega un tablero sin peones? No vi que hayan tableros sin peones en los test entregados. Cómo se podría testear de forma automática esto con los archivos que entregan ustedes?

-  _"Si el tablero ya incluye peones, estos no pueden ser retirados o desplazados a otra celda. La solución se debe generar a partir del tablero entregado."_: Vi que todos los tableros entregados contienen peones. Entonces, este punto significa que si tiene peones, es verificar que la disposición de ellos genera una solución correcta? No se debe limpiar el tablero, guardando los peones y dar una nueva solución según la cantidad de peones que se entregó originalmente?

Saludos.

**Comment by ManuelV03** [comment]
Hola, la gracia del método solucionar() es que, a partir de un tablero, este pueda retornar un tablero resuelto (que cumpla las reglas solicitadas). Lo importante es que para resolver el tablero solo puedes poner nuevos peones (no se pueden ni mover ni quitar los peones ya existentes en el tablero). Cabe destacar que puedes poner cuantos peones necesites para la solución. Respecto a los testcases estos si abarcan tanto tableros iniciales sin peones como tableros iniciales con peones. Avísame si se aclaró tu duda.

**Comment by kitofito** [comment]
Muchas gracias Manuel, ahí me quedó claro /._./
