### ISSUE TITLE
a que se refiere con normalizar??

### ISSUE THREAD

**Issue by Dunkan1** [IIC2233/Syllabus#84]
'Recursos mas efectivos: 
se mostrara una lista de recursos ordenados de manera descendente de
acuerdo a su coeficiente de eficiencia. El coeficiente de eficiencia corresponde a la razon entre puntos de
poder extintos por el recurso y el tiempo trabajado. Se deben |normalizar| los puntos de poder extintos
con la tasa de extincion del recurso'

**Comment by sebacruzd** [comment]
Con normalizar, se refiere a dividir los puntos de poder por la tasa de extinción para luego poder calcular la razón mencionada.

**Comment by Dunkan1** [comment]
gracias
