### ISSUE TITLE
Se cambia el type de un metodo

### ISSUE THREAD

**Issue by lfuenzalida2** [IIC2233/syllabus#84]
me pasa que estoy tratando de hacer que un metodo de una clase mapee (utilice map) sobre una lista y me sale un error en donde dice que el metodo es una tupla, estuve revisando con type en que punto es que cambia mi metodo a type y es cuando le agrego las variable al metodo, por ejemplo:

clase.clasesecundaria.metodo()   #me dice type method
clase.clasesecundaria.metodo("hola", algo)  # me dice type tuple

tambien trate agregando solo una de las 2 variables, para ver que es lo que pasaba y me reconocia el metodo como tal y me decia que le falta 1 varaible. 

que puedo hacer para que me lo tome como un metodo?

**Comment by roberto009** [comment]
Hola! 
Si es que entendí bien tu problema estás tratando de hacer algo así 
```python
class Prueba:
    @staticmethod
    def usar_map(parametro):
        # hago algo al parametro
        return parametro 
lista = [ "a","b","c"]
prueba= Prueba
lista_cambiada = map(prueba.usar_map, lista) #ojo que prueba_map no lleva paréntesis 
```
Si es que eso te está diciendo que es una tupla, recuerda que no debes ponerle los paréntesis al método cuando lo colocas en el map. Espero que eso fuera lo que te estaba pasando!
Avísame si te funciona

**Comment by lfuenzalida2** [comment]
el problema que hay ahí es que en el caso que pusiste, el metodo usar_map tiene 1 parametro que es el que cambia, yo a mi metodo tengo que entregarle 2 parametros que se necesitan para poder ejecutarlo, son parametros que modifican el valor antes de retornarlo, entonces al momento de utilizar map, tengo que definir los parametros

**Comment by lfuenzalida2** [comment]
igual muchas gracias!

**Comment by roberto009** [comment]
Cuando quieres usar map con dos parámetros debes hacerlo así:
```python
class Prueba:
    @staticmethod
    def usar_map(parametro1, parametro2):
        # hago algo al parametro1 y 2
        return parametros_modificados 
lista1 = [ "a","b","c"]
lista2 = ["d","f","g"
prueba= Prueba
lista_cambiada = map(prueba.usar_map, lista1, lista2)
```
Si aun no te funciona me avisas!

**Comment by lfuenzalida2** [comment]
lo que pasa es que los parametros que le entrego no estan en la lista, son parametros externos a ellos, lo que quiero es hacer una lista(con map) que ejecute mi metodo ya definido con sus 2 variables (independientes de las listas)  a todos los objetos dentro de la lista, mi metodo recibe parametros que no tienen nada que ver con los objetos de la lista, pero que son necesarios para poder ejecutar el metodo

**Comment by roberto009** [comment]
Ok entendí tu problema. Para esto quizá no te conviene usar map, sino que una lista por comprensión (las vieron en el taller del jueves). Algo así:
```python
class Prueba:
    @staticmethod
    def cambiar_lista(parametro_fijo1, parametro_fijo2,parametro_variable):
        # hago algo a los parametros
        return parametros_modificados 
lista_por_modificar = [ "a","b","c"] # esta es la lista que quieres modificar 
parametro_fijo1 = #algo
parametro_fijo2 =  #algo
prueba= Prueba
lista_cambiada = [prueba.cambiar_lista(parametro_fijo1, parametro_fijo2, parametro variable) for parametro_variable in lista_por_modificar ]
```
Ahí le estas aplicando la función `cambiar_lista` a `lista_por_modificar` y mantienes tu parámetros fijos de la función.

**Comment by lfuenzalida2** [comment]
eso me funciono! muchas graciass
