### ISSUE TITLE
duda sobre el uso de .gitignore

### ISSUE THREAD

**Issue by etoteiza** [IIC2233/syllabus#84]
Hola!
Tengo una duda. Supongamos que en una carpeta ( 'carpeta') tengo mis archivos, incluyendo el '.gitignore'. Dentro de 'carpeta' tengo 'subcarpeta', y quiero ignorar archivos dentro de 'subcarpeta' el '.gitignore' que está en 'carpeta' servirá, o debo crear otro '.gitignore' dentro de 'subcarpeta'.

Muchas gracias de antemano, espero que se haya entendido

**Comment by gatochico** [comment]
Hola!

Para estos casos, también se utilizan los **paths relativos**. Por ejemplo, si tienes:
```
T00
│   README.md
│   .gitignore    
│   programa.py
└───subcarpeta
│   │   basura.txt
│   │   nobasura.txt
```
Y quieres ignorar el archivo `basura.txt` dentro de `subcarpeta`, dentro de tu .gitignore principal deberías escribir:
```
subcarpeta/basura.txt
```
Finalmente, **ojo si es que al ignorar los archivos en un subdirectorio, dejas dicho subdirectorio vacío**. Siguiendo el ejemplo anterior, si es que en tu gitignore desearas ignorar tanto `basura.txt` como `nobasura.txt`, el directorio `subcarpeta` quedaría vacio! Y por lo tanto, no se subirá al repositorio remoto :warning: Para contrarrestar esto, puedes hacer dos cosas:

1. Pedir al ayudante en tu README que cree el subdirectorio antes de ejecutar tu tarea. Debes indicar como llamar a la subcarpeta y donde ubicarla correctamente :eyes: y seguiremos tus instrucciones al pie de la letra.
2. Revisar la issue #27 , donde hay instrucciones de como subir una carpeta vacía.

Espero haber resuelto tu duda! :computer:

**Comment by etoteiza** [comment]
Muchas gracias! me quedó mas claro sobre el funcionamiento de ´.gitignore´
