### ISSUE TITLE
Uso de [1:] y [:-1] en listas

### ISSUE THREAD

**Issue by sofiuni** [IIC2233/syllabus#84]
Uso eso en mi codigo en `main.py` en la linea 37, y funciona bien para las listas de mas de dos o menos pero las de dos no funciona, en vez de elegir el ultimo objeto elije el primero, por que ocurre esto?

**Comment by MatiasDuhalde** [comment]
Holaa  👋 

Lo que hace el slicing `[:-1]` es **seleccionar todos los elementos menos el último**, es por eso que al usarlo sobre una lista de largo dos te va a retornar sólo el primer elemento,
La sintaxis general del slicing es `[inicio : final : step]`, por lo tanto si quieres seleccionar todos menos el primero basta con usar `[1:]`.

Por ejemplo:
```python
mi_lista = ["a", "b", "c", "d", "e"]
print(mi_lista[:-1]) # muestra ["a", "b", "c", "d"]
print(mi_lista[1:]) # muestra ["b", "c", "d", "e"]
```

Ojalá eso aclare un poco tus dudas :)

**Comment by sofiuni** [comment]
OH! Ahora funciona. Gracias!
