### ISSUE TITLE
Plazo para entrega de avance

### ISSUE THREAD

**Issue by lfb1206** [IIC2233/syllabus#84]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

En clases nos mencionaron que existe un plazo para enviar un avance, sobre el cual nos entregan creo que consejos o cosas a corregir. 
Si es que existe esto, ¿Hasta cuando es el plazo?

**Comment by RafaelEdwards** [comment]
Holaa, como esta tarea es corta en relación a las demás, no hay avance. De todas formas, para las tareas con avance, toda la información sobre este se especificará en el enunciado
