### ISSUE TITLE
Duda sobre Entidades

### ISSUE THREAD

**Issue by Thevma** [IIC2233/Syllabus#84]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Una pregunta pequeña, si es que no creé a las Entidades tal y como dicen en el Enunciado (definiendo exactamente a Usuarios, Publicaciones y Comentarios) pero modulé bastante de forma ordenada y además el programa funciona excelente, ¿me pueden descontar? Cuando leí el enunciado entendí mal a qué se referían con Entidades (no programaba hace 6 semestres), supuse que eran elementos que eran imprescindibles para el programa (los cuales creé de forma directa e indirecta) pero no que exactamente tenían que ser definidos.
A todo esto pregunté vía mail donde me dijeron que el uso de Clases era más una opción que una necesidad.
¡Saludos y buen fin de semana!

**Comment by catalina-arcila** [comment]
Hola @Thevma, como te dijeron en el correo, no es necesario el uso de _Clases_ en la tarea. Por lo que mientras se demuestre en la consola que están implementadas las entidades, tendrías el puntaje 😄.
