### ISSUE TITLE
Duda si puedo modificar archivos para probar

### ISSUE THREAD

**Issue by sbarriag** [IIC2233/Syllabus#84]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/21)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/20)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, me surgió una duda sobre la carpeta entregada "Archivos", se supone que esa es una carpeta para que podamos probar nuestras funciones y no será necesariamente la misma que se utilizará para corregir la tarea, considerando eso, puedo modificar los tableros que se me entregan ahí para poder probar si mis funciones están funcionando (valga la redundancia) en otros casos, por ejemplo cambiar valores de bombas, colocar algunas tortugas o cosas así? 

Saludos

**Comment by Arielmanriquez** [comment]
Hola, si no debería haber problema con que modifiques esos archivos para probar otros casos.
saludos :)
