### ISSUE TITLE
Problema con archivo "jugadores.csv"

### ISSUE THREAD

**Issue by YoSoyJaime** [IIC2233/Syllabus#84]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, tengo una duda acerca del archivo "jugadores.csv", en el archivo hay 2 jugadores que tienen más parámetros de los que indica el enunciado, por lo cual no calza con lo que se entrega. Me explico ; el archivo entrega 10 parámetros :
 **nombre, personalidad, energia, suerte, dinero, frustracion, ego, carisma, confianza, juego favorito**, mientras que, por ejemplo, el primer personaje de la lista entrega 15 ; **jtvaldivia, Ludopata, 23, 2, 777, 9, 3, 5, 6, 2632, 93, 9, 10, 19, cara o sello**.

¿Se trata de un error o aparece en alguna parte del enunciado?

Gracias de antemano.

**Comment by 0wulf** [comment]
tengo la misma duda, creo que es un error

**Comment by jtvaldivia** [comment]
Hola, 
al ser día domingo no se responden issues, pero por ser un error de enunciado se va a subir un archivo con las correcciones necesarias a la brevedad, para que hagan git pull al syllabus y se resuelva el error.
