### ISSUE TITLE
Varias dudas de la materia

### ISSUE THREAD

**Issue by bedefrunner** [IIC2233/Syllabus#84]
Hola! Tengo algunas preguntas:

1. En polimorfismo, entendí bien cómo aplicar overriding pero siento que al aplicarlo estamos haciendo overloading, ya que la definición de overloading es "la capacidad de definir un método con el mismo nombre pero con distinto número y tipo de argumentos". En los ejemplos de la materia, hacemos overriding con el método __add__, pero al hacer eso estamos definiendo un método que ya existe pero con distintas variables y outputs. Eso no es overloading?

2. En herencia, no entiendo por qué se dice que "en Python el orden de las clases va de izquierda a derecha dentro de la lista de super-clases desde donde hereda la sub-clase" siendo que en los ejemplos se imprimen los prints de las clases en el orden "clase de mas a la derecha - clase de mas a la izquierda". Hago copy paste de lo que se imprime.

Llamando método en Clase B
Llamando método en Subclase Derecha
Llamando método en Subclase Izquierda
Llamando método en SubclaseA

3. En AbstractBaseClass dice que "existen entonces dentro de una clase abstracta: los métodos abstractos que funcionan distinto dependiendo de la subclase, por lo tanto deben ser implementados en cada subclase; y los métodos normales, que funcionan igual para todas las subclases y deberían estar implementados en la clase abstracta". Pero los métodos abstractos igual se implementan en las clases abstractas, tal como se ve en los ejemplos, simplemente no se pueden llamar.

**Comment by fringlesinthestreet** [comment]
Con respecto a tu duda del segundo punto lo que sucede es que el orden es de izquierda a derecha pero los `print`'s vienen después del llamado a `super()`. 

Lo que sucede primero es que se llama al `__init__` de la clase `SubclaseA`, el cual llama al `super().__init__()`. El resto del método de la clase `SubclaseA` queda _stand by_. `super()` ordena los llamados de la siguiente manera: `Clase A`, `SubclaseDerecha`, `SubclaseIzquierda` y `ClaseB`. Como los métodos van quedando _stand by_,  el primer método en terminar de ejecutarse va a ser de la clase `B`. Es por esto que ese es el primer mensaje que se muestra.

Prueba agregando un `print` antes del llamado a `super()` en cada clase.

**Comment by fringlesinthestreet** [comment]
Con respecto a tu duda del primer punto lo que mencionas __no__ es overloading.
Overloading es definir dos veces un método en una clase con el mismo nombre pero con distinto numero de argumentos que recibe (y probablemente distinto comportamiento). Python permite que exista un solo atributo o método con un nombre específico. Si no me equivoco, quedaría definido el método que se declara después.
En otros lenguajes como java o C++ es permitido.

**Comment by fringlesinthestreet** [comment]
Con respecto a tu duda del tercer punto, la idea de que un método sea abstracto es obligar a que las subclases deban realizar _overriding_. Es opcional implementer en el mismo un funcionamiento estándar pero, como va a ser sobreescrito en la subclase, debe ser llamado luego con el super() en el método de la subclase.

**Comment by indonoso** [comment]
Vamos a explicar el primer y tercer punto en la clase.

**Comment by indonoso** [comment]
Voy a responder parte por parte.

> En polimorfismo, entendí bien cómo aplicar overriding pero siento que al aplicarlo estamos haciendo overloading, ya que la definición de overloading es "la capacidad de definir un método con el mismo nombre pero con distinto número y tipo de argumentos". En los ejemplos de la materia, hacemos overriding con el método add, pero al hacer eso estamos definiendo un método que ya existe pero con distintas variables y outputs. Eso no es overloading?

Hay un error en el material. En verdad lo que está explicando en el material es *Operator Overloading* no existe el *Operator Overriding*. Lo que se está haciendo es que un operador (`+`, `-`, etc) pueda ejecutar la operación con diferentes tipos de datos. Por eso se llama *Operator Overloading*.

#### ¿Por qué se llama así si en verdad estamos escribiendo el método `__add__`? ¿No debería ser *overriding*?
*Overriding* es cuando **sobreescribimos** un método que hemos **heredado**. `__add__` no es un método que esos objetos estén heredando. Aquí es donde hacemos uso de *duck typing*: el operador `+` puede sumar cualquier objeto que implementa `__add__` sin importar cómo esté implementado `__add__`.

> En herencia, no entiendo por qué se dice que "en Python el orden de las clases va de izquierda a derecha dentro de la lista de super-clases desde donde hereda la sub-clase" siendo que en los ejemplos se imprimen los prints de las clases en el orden "clase de mas a la derecha - clase de mas a la izquierda". Hago copy paste de lo que se imprime.

El ayudante ya lo explicó. 

> En AbstractBaseClass dice que "existen entonces dentro de una clase abstracta: los métodos abstractos que funcionan distinto dependiendo de la subclase, por lo tanto deben ser implementados en cada subclase; y los métodos normales, que funcionan igual para todas las subclases y deberían estar implementados en la clase abstracta". Pero los métodos abstractos igual se implementan en las clases abstractas, tal como se ve en los ejemplos, simplemente no se pueden llamar.

Claro. Cuando marcamos un método como *abstracto*, este **debe** ser implementado en la clase que hereda de la clase abstracta. 

``` python
class A(metaclass=ABCMeta):
    @abstractmethod
     def metodo_abstracto(self):
         print("Método abstracto, nunca se va a ejecutar esto porque obligamos"
                  + "a implementar una nueva versión en la clase que herede de A")
     def metodo_no_abstracto(self):
          print("Este se ejecutará de la misma forma en todas las clases que 
                   + "hereden de A, a menos que sea sobreescrito")
class B(A):
    def metodo_abstracto(self):
         print("Esta nueva implementación sí se ejecutará")
```
Cuando llamemos al método `metodo_abstracto` un objeto de la clase `B`, **siempre** se ejecutará el método implementado en `B`. Cuando llamemos a `metodo_no_abstracto` de un objeto de la clase `B` se ejecutará la versión de la clase abstracta `A` porque `B` no lo sobreescribe.
