### ISSUE TITLE
Problema VSC

### ISSUE THREAD

**Issue by benjazuloaga** [IIC2233/Syllabus#84]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Estoy teniendo un problema al momento de correr mi tarea que no he tenido durante toda la semana. Al hacer correr la tarea no ocurre nada, como si nunca hubiera apretado el run o hacer ctl+alt+N. Luego lo trate de hacer por la terminal y me aparece lo siguiene:

Microsoft Windows [Versión 10.0.19044.1889]
(c) Microsoft Corporation. Todos los derechos reservados.

C:\Users\benja\OneDrive\Escritorio\2022-2\ProgramacionAvanzada\benjazuloaga-iic2233-2022-2\Tareas\T0>python3 desarrollo_tarea0.py
No se encontr¾ Python; ejecuta sin argumentos para instalar desde Microsoft Store o deshabilita este acceso directo en Configuraci¾n > Administrar alias de ejecuci¾n de la aplicaci¾n.

**Comment by Juampisaez** [comment]
Holaa 👋 @benjazuloaga 
Estoy casi seguro que es porque el comando `python3`, no existe en tus variables de entorno. 
Prueba corriendo:
`python desarrollo_tarea0.py`.

Quedo atento si te resulta 👀
