### ISSUE TITLE
No me funciona el codigo en (rutas_posibles)

### ISSUE THREAD

**Issue by FelipeEscobarA** [IIC2233/Syllabus#84]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/20)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/19)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

¿Hay alguna forma más simple de resolver esta funcion sin una funcion recursiva? he estado todo el dia tratando de programar la funcion de ese modo pero no me sale

**Comment by IanZmen** [comment]
Hola! en teoría todo problema que se pueda resolver por recursividad también se puede resolver de manera iterativa. Ahora, si tu enfoque es la recursividad (no estoy diciendo que sea el enfoque correcto ni el incorrecto) asegúrate de tener un buen caso base (para que termine) y que la función cumpla su función. Darte la solución no puedo, pues la idea es que lo resuelvas tu.... Mucho éxito!!!!!!!!
