### ISSUE TITLE
Pausar Flechas ya creadas

### ISSUE THREAD

**Issue by totoiii** [IIC2233/syllabus#840]
Hola, he estado una forma de pausar un QThread ya que decidi usar esto para las flechas, pero no encuentro, puedo pausar el Qtimer para dejar de generar flechas, pero las flechas (que son qthreads) no las puedo detener en su posición en la que están.

**Comment by bvasquezm** [comment]
Hola @totoiii!

Esperando que estés teniendo una buen inicio de semana, te comento que lo que estás buscando lo puedes encontrar en la documentación relacionada con los métodos ``QMutex`` (que son básicamente locks optimizados para PyQt5) y ``QWaitCondition`` (muy bueno combinado con QMutex), incluso podría servirte investigar un poco sobre el método ``QSemaphore`` si buscas pausar múltiples flechas a la vez. Espero puedas encontrar lo que buscas allí, muchas suerte!

**Comment by kalarconvl** [comment]
Hola @bvasquezm! Estoy con el mismo problema y leyendo la documentación de QMutex y QWaitCondition no entiendo bien cómo se pueden combinar estas clases con un QThread. Hay que armar otra clase que se encargue de parar a los Threads?

**Comment by kalarconvl** [comment]
Porque mutex() es un método para una instancia de QMutex, no para QThread

**Comment by bvasquezm** [comment]
> Porque lock() es un método para una instancia de QMutex, no para QThread

Claro es un método de QMutex, pero es exactamente un objeto del tipo QMutex o QSemaphore lo que debería manejar la concuncurrencia dentro de tus QThreads correctamente. Para que entiendas mejor sobre sincronización te dejo el siguiente [link](https://doc.qt.io/qt-5/threads-synchronizing.html). Espero te sirva!

**Comment by kalarconvl** [comment]
@bvasquezm Gracias! Entonces hay que hacer una clase grande que herede de QMutex y otra que cree las flechas y herede de esta clase QMutex? Pero tiene que heredad de QThread, no entiendo cómo puede manejar la concurrencia :(

**Comment by kalarconvl** [comment]
Encontré esto, pero no entiendo su forma de programar (me pasa lo mismo leyendo la documentación de Qt). No entiendo cómo incorporan QMutex en el Qthread

![Qt5 Tutorial QThreads - QMutex - 2020 y 10 páginas más - Personal_ Microsoft​ Edge 27-10-2020 15_01_00](https://user-images.githubusercontent.com/68581172/97342667-47c83a00-1865-11eb-9088-d1c9a183bec3.png)

**Comment by bvasquezm** [comment]
@kalarconvl Creo que te puede quedar mucho más claro con este ejemplo: 

- Usando Lock() 
```python
import threading

self.candado = threading.Lock()
```

- Usando QMutex
```python
from PyQt5.QtCore import QMutex

self.candado = QMutex()
```
Los métodos de liberar, adquirir o cerrar el "candado", tienen nombres distintos dependiendo del objeto. Espero con esto haya quedado más claro (lo relacionado a locks lo puedes encontrar en los contenidos de threading).
