### ISSUE TITLE
Otra duda api yoda bonus help

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#840]
Hola, el enunciado dice esto:

>Como bonus para tu tarea, debes consultar esta API para entregar los resultados de tus consultas acerca del tiempo en lenguaje Yoda.  Debes entregar una frase que contenga alguna de las palabras entregadas por la API de OpenWeatherMap, para que esta sea convertida a lenguaje Yoda y posteriormente enviada por la API de Gmail. El formato de las oraciones es libre (queda a tu elección el contenido de cada una)

Pero si el usuario tiene una ciudad y lo único que quiere saber es el índice uv, openweather responderá algo como esto: ```{'lat': -33.44, 'lon': -70.65, 'date_iso': '2018-07-01T12:00:00Z', 'date': 1530446400, 'value': 2.13}```
¿Qué palabra uso? Intento decirle "I like date with value 2.13" y su respuesta es "I like date with value 2. 13" entonces no sé qué hacer. La api está bien conectada y todo pero **que su respuesta sea la misma que lo que les enviamos no es culpa nuestra** (lo digo en referencia a la respuesta del ayudante en la issue #823 ). **Al final nos están evaluando la materia de web services, no hacer un programa que estructure oraciones en inglés que otro programa entienda a partir de unas cuantas palabras.**

Y además, si le doy algo como "I like {description}" me responde: "I like broken clouds" (cuando description era "broken clouds".

**Comment by CmPoblete** [comment]
Pasale frases mas largas. Ahi la api te la deberia desordenar un poco o por lo menos agregarte frases.
PD: No soy ayudante

**Comment by ibaeza1** [comment]
Me pasa lo mismo, si le doy la frase en español no cambia nada, pero si se la doy en ingles si. Eso significa que hay que pasar el reporte en ingles?

**Comment by leolivares** [comment]
@jmwielandt @ibaeza1 
Como se mencionó en la issue #806, solo deben demostrar que la usan. Pueden pasarle algo que arroje un cambio, e informar en que linea realizan el request. Saludos.
