### ISSUE TITLE
Conexión señal con instancia de una clase

### ISSUE THREAD

**Issue by jirarrazaval** [IIC2233/syllabus#840]
Hola! Tengo una clase que crea instancias de otra clase. Aquí tengo una señal que conecta esta clase en que estoy con una función de cada instancia que creé.
La cosa es que descubrí que cuando emito esta señal, le llega a todas las instancias y no sólo a una, siendo que la conecté con cada una. Cómo arreglo esto para que cuando la emita le llegue sólo a la instancia en que la conecté??

**Comment by bvasquezm** [comment]
Hola @jirarrazaval :) 

¿Podrías mostrarme una foto de tu código para poder entender mejor tu problema?
