### ISSUE TITLE
Error "tupla" en una señal

### ISSUE THREAD

**Issue by Natydlb** [IIC2233/syllabus#841]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola! me sale el error "argument 1 has unexpected type 'tuple' " pero en si el argumento no es una tupla, es una función, puede ser porque esta es el setter de un property, pero de ser así no sabría como arreglarlo, hay alguna forma de arreglarlo?

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by aaossa** [comment]
Hola @Natydlb , el error es justamente lo que supones: aparece porque estás conectando un atributo a una señal, que por más que sea una *property* actúa como atributo. Si lo que queires es que la señal modifique un atributo, creo que lo mejor es que hagas un método o función auxiliar que haga el cambio 👌 (Te respondí porque me salió el mismo error cuando miré tu código por otra *issue* 😅 ). Ojalá te sirva la respuesta y que sigas avanzando ✨ ¡Mucho éxito!

**Comment by Natydlb** [comment]
Avance! pero me volvi a estancar porque ahora hice una señal que llamara a una función y esa función llamara al property y este lo editara pero no me funciono por el mismo problema de la tupla :( pero no entiendo es como si no le pudiera dar una tupla a una función

**Comment by aaossa** [comment]
Hola @Natydlb , ¿cómo estás pasándole los valores a la señal al emitirla? Fíjate en el último ejemplo de [este contenido](https://github.com/IIC2233/contenidos/blob/master/semana-10/1-pyqt-qthreads.ipynb), la señal se declara como `actualizar = pyqtSignal(QLabel, int, int)`, se emite con `self.actualizar.emit(self.label, *self.posicion)` y la función que se conectó se declara con `def actualizar_label(self, label, x, y):`. De esta manera, en lugar de pasar una tupla, simplemente pasas los valores por separado. Avísame si te funciona 🙌

**Comment by Natydlb** [comment]
Es que creo que esa parte la tengo bien, lo que no me funciona en una función que hace lo siguiente " return self.posicion(valor)" TypeError: 'tuple' object is not callable, valor es una tupla y self.posicion() es el setter que creo que también lo consideran como tupla

**Comment by aaossa** [comment]
Ahh claro, recuerda que para Python todo lo que sea una *property* se comporta exactamente como un atributo, por lo que en ese caso tienes que hacer `return self.posicion` 😅

**Comment by Natydlb** [comment]
muchas gracias !!
