### ISSUE TITLE
Persistencia de Datos en Configuración de Reporte

### ISSUE THREAD

**Issue by simontoya** [IIC2233/Syllabus#841]
Hola!
En la sección 4.4 sale que se debe mostrar un menú con opciones donde estaría la opción de ver la configuración actual del reporte. En términos de como guardar esa configuración esta bien guardarlo en un archivo .txt o se puede implementar el hecho de que el servidor le de sesiones al usuario y luego guardarlas según la sesión, asumiendo que el servidor estaría corriendo de manera constante para no perder los datos.

**Comment by cilopez** [comment]
Cualquiera de las dos opciones es correcta, mientras lo menciones como supuesto en el readme
