### ISSUE TITLE
RecursionError con posiciones aleatorias de nueva partida

### ISSUE THREAD

**Issue by totaurt** [IIC2233/syllabus#841]
Holaa! Tengo un problema con un método que cambia las coordinadas que se generan al momento de comenzar de nuevo. Este es parte de mi clase Lógica y lo llamo cuando en la MainWindow se superponen dos QLabels (de las entidades) con el método label_1.geometry().intersects(label_2.geometry()) que mencionaban en una issue. 
Específicamente el error dice: maximum recursion depth exceeded. Busqué y entendí que es porque se ejecuto una función recursiva con entradas muy grandes, pero no entiendo por qué sucede esto en mi código ni cómo implementar la no superposición de los objetos en el mapa si no es de esa manera:(
Ojalá me puedan ayudar, espero su respuesta. Gracias!

**Comment by danckoo1** [comment]
Hola! Si quieres comprender en detalle porque se levanta dicho error te sugiero visitar la siguiente [Pagina](https://www.google.cl/amp/s/www.geeksforgeeks.org/python-handling-recursion-limit/amp/), y en cuanto a la implementación, si bien es posible hacerlo con recursion quizás sería más simple (aunque más largo) que lo implementes mediante una función y loops, pero depende más que nada de tu preferencia :)
