### ISSUE TITLE
QTextEdit

### ISSUE THREAD

**Issue by dlmed** [IIC2233/syllabus#842]
Hola! quería saber cómo se hacer para poner un texto de fondo en un QTextEdit o QLineEdit. Esos que se ven con poca opacidad y que cuando se clickea el cuadro de texto, desaparecen. No pude encontrar info online :(

**Comment by danckoo1** [comment]
Hola!, para eso te puede resultar útil el metodo `setPlaceholderText()` de ambos objetos que mencionas. Para más información acerca de cómo funciona puedes consultar la documentación :)
