### ISSUE TITLE
Punto 3.1,2 y formato ciudades

### ISSUE THREAD

**Issue by shantifabri** [IIC2233/Syllabus#842]
Hola, podrian por favor responder estas issues:
#817 
#835 
#838 

Si es que no, estas son las preguntas:
Como se ingresan las ciudades en el cliente? Nombre y pais? id? Se eliminan de igual forma?
Se puede hacer el llamado a mi api con lo que yo estime conveniente?
Gracias!

**Comment by Arcoirisky** [comment]
Hola!!
1)
Las ciudades en el cliente deben poderse aceptar según tu propio criterio. Recuerda que debe aceptar las 3 formas O:!! 

2) 
La forma en la que eliminas ciudades queda a tu criterio :D

3) Si, mientras tú api se encargue finalmente de mandar el mail. Lo que sí deberías tener cuidado, es que si almacenas datos, en cómo diferencias los Requests de diferentes clientes.

Espero que responda a tus preguntas :D Mucho éxito en lo que queda!! :D

**Comment by ibaeza1** [comment]
Puede ser que el cliente pueda ingresar el nombre id o coordendas pero que haga el request solo con el nombre de la ciudad transformando por ejemplo el id en nombre?
Por ejemplo el cliente ingresa el id de una ciudad pero yo tengo una funcion que al ingresar el id de la ciudad me retorna el nombre asi siempre hago los requests igual pero el cliente puede ingresar las tres formas.
@Arcoirisky 
@Hernan4444 sorry por etiquetarlos pero necesitos respuesta porfis :(

**Comment by Regenschrim** [comment]
A mi me queda igual la duda jaja perdón :( Entonces, el input del usuario puede ser de las 3 formas y la api la trabajamos como estimemos conveniente? Solo quiero estar 100% seguro. Gracias!

**Comment by Arcoirisky** [comment]
Si :D
