### ISSUE TITLE
Ayuda con documentación en ingles de drag and drop 

### ISSUE THREAD

**Issue by diego-ayala-2000** [IIC2233/syllabus#842]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola. Me podrían orientar un poco con lo del draw and drop. No soy muy bueno con el ingles y llevo mucho tiempo tratando de implementarlo, he visto videos y leídos muchos códigos en internet pero no logro dar en el clavo. Me he estado basando en esta pagina https://doc.qt.io/qt-5/dnd.html, pero entre que mi ingles es malo y me cuesta cambiarlo a python me ha tomado demasiado tiempo.

**Comment by JuaniAndres** [comment]
Hola @diego-ayala-2000 
Lamentablemente no te puedo explicar mucho sobre el drag and drop ya que la idea de esta tarea es que lo investigues por tu cuenta, pero si te puedo dejar algunos consejos que te pueden servir. El primer consejo es que la mayoría de los navegadores tienen herramientas para traducir el contenido de las páginas web a un idioma que te quede más cómodo para que investigues como activarlo. Si bien esa traducción no es perfecta yo creo que te va a ayudar a entender las ideas y los métodos. También puedes buscar algunos ejemplos en python que utilicen drag and drop para analizarlos, fíjate que característica tienen los widgets que participan del drag and drop.
Éxito con la tarea que tú puedes 😄

**Comment by diego-ayala-2000** [comment]
Ok gracias.
