### ISSUE TITLE
Peso de flecha espacio

### ISSUE THREAD

**Issue by BFry712** [IIC2233/syllabus#843]
### Prerrequisitos

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola! tengo una duda sobre cual seria el peso de la flecha espacio en el calculo del puntaje para suma_flechas?
Saludos!

**Comment by furcelay** [comment]
Hola @BFry712 !

Tal como dice el enunciado, los puntos que otorga la flecha espacio son 4 veces los de una flecha normal,
Saludos!

**Comment by BFry712** [comment]
Hola @furcelay !
Muchas gracias! no me habia dado cuenta
Saludos!
