### ISSUE TITLE
Agregar labels en el frontend desde python y no QtDesigner

### ISSUE THREAD

**Issue by sebaew98** [IIC2233/syllabus#843]
hola, cree el widget de mi programa desde QtDesigner agregando los labels, botones y todo sin problemas. El tema es que estoy tratando de agregar nuevos labels desde el codigo y no me los esta mostrando, ya probe utilizando raise_() para ver si ese era el problema pero no. Eso si, si creo un label desde el QtDesigner y lo edito desde el codigo no tengo problemas pero necesito crear nuevos labels dependiendo de la partida cargada anteriormente y no modificando los ya existentes.

**Comment by fdoflorenzano** [comment]
Hola @sebaew98,

¿Podrías agregar un ejemplo de código simplificado de como intentas agregarlos? A ver si será un *bug* de código.

(Ojo con no copiar y pegar tu código de tarea, puedes sacar cosas no relevantes y cambiar nombres de cosas)

Saludos.

**Comment by sebaew98** [comment]
Hola! Respondere con la lista de pasos que sguir
1- Creo el label
2- Seteo su geometria
3- Defino el pix map
4- Seteo el pix map
5- Escalo los contenidos
6- Probe haciendo un raise
Todo esto en la clase de la ventana de juego cuando quiero cargar una partida, en este caso agregar el label del mesero para partir.
Gracias!

**Comment by fdoflorenzano** [comment]
¿Y el código de esos pasos específicos? (solo esos pasos)

**Comment by sebaew98** [comment]
self.lab_mesero = QLabel(self)
        pos_x_mesero = int(lista_mesero[0][0])
        pos_x_mesero_relativa = pos_x_mesero + self.x_origen_map
        pos_y_mesero = int(lista_mesero[0][1])
        pos_y_mesero_relativa = pos_y_mesero + self.y_origen_map
        tam_x_mesero = dict_parametros['mesero']['TAM_X_MESERO']
        tam_y_mesero = dict_parametros['mesero']['TAM_Y_MESERO']
        self.lab_mesero.setGeometry(pos_x_mesero_relativa, pos_y_mesero_relativa, 
                                     tam_x_mesero, tam_y_mesero)
        pixmap_mesero = QPixmap(parametros_mesero['RUTA_MESERO'])
        self.lab_mesero.setPixmap(pixmap_mesero)
        self.lab_mesero.setScaledContents(True)
        self.lab_mesero.raise_()

**Comment by fdoflorenzano** [comment]
Súbelo a tu repositorio mejor :)

**Comment by sebaew98** [comment]
actualizo mi tarea en el respositorio?

**Comment by fdoflorenzano** [comment]
Sí. (Deberías hacerlo seguido siempre, veo que no subes nada hace un tiempo 👀 )

**Comment by sebaew98** [comment]
listo :D 
Gracias!

**Comment by fdoflorenzano** [comment]
Estimade,

En mi caso la ruta de acceso a la imagen estaba mal especificada, imprime la ruta de acceso y fijate.

Saludos.

**Comment by sebaew98** [comment]
toda la razón profe, ya lo habia revisado pero pase por alto un slash.
Muchas gracias por su tiempo :)
