### ISSUE TITLE
Creación de flechas involuntariamente

### ISSUE THREAD

**Issue by YehudaGurovich** [IIC2233/syllabus#844]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

No logro entender por qué se me crean un par de flechas random en la esquina superior izquierda y llevo un par de horas intentando solucionarlo. No identifico mi error de código que hace que se creen estas.
Ya hice git push (lo menciono porque en algunas issues piden que hagan git push)
El error deberia estar en flechas.py o juego_window.py. (correr el programa en el main)

Update: Puse un print en la consola cada vez que se crea una flecha, pero esas de la esquina se estan creando de otra manera ya que no se imprime esa parte cuando se crean. 

Update2: Aprovecho de hacer otra pregunta. Estoy utilizando el método intersects y no estoy seguro por que no me cambia el color del background cuando se intersectan. Las señales estan bien conectadas dado que al colocar un print en el método se imprime, pero nunca entra en el if ...intersects(...): por lo que sospecho que no se está actualizando la posición de la flecha pero no se por qué pasa (quizá es algun .emit() mal puesto pero no logro encontrar el error.

![image](https://user-images.githubusercontent.com/53883366/97246705-bc0acb00-17dc-11eb-9502-474b8990276a.png)

**Comment by kadroguett** [comment]
Hola @YehudaGurovich, estuve revisando tu código y las flechas que aparecen en la esquina superior izquierda son las mismas que luego bajan, lo que pasa es que al momento de crearlas usas `setGeometry(0, 0, x, x)` entonces al darle la posición 0, 0 se muestran en esta esquina. Si le cambias la posición inicial a las flechas verás como ya no aparecen en esta zona.

**Comment by YehudaGurovich** [comment]
Hola @kadroguett, muchas gracias por la ayuda. Hice algunos arreglos por lo que comienzan en el lugar correcto, pero aun se quedan quietas en su lugar, en vez de bajar. Aun sigo sin entender como es que son las mismas flechas dado que al contar los prints en la consola calzan con las flechas que bajan pero hay un monton de flechas random que se crean que simplemente se quedan ahi. (Hice nuevamente push)

**Comment by kadroguett** [comment]
Viendo tu código noté un par de problemas, primero tienes un `self.label.show()` y el `self.start()` en el `init` de cada flecha, por lo tanto cuando instancias las flechas en `juego_window.py` en las `líneas 39 a 43`, los `Qthreads` comienzan inmediatamente en todas las flechas. Para evitar esto te recomiendo que crees un método en cada flecha que contenga show y start de esta forma:

![image](https://user-images.githubusercontent.com/31357861/97350178-2ff5b380-186f-11eb-9511-0fc77476a985.png)

Y luego este método lo llames en `juego_window.py` luego de seleccionar la flecha, es decir después de la `línea 47` 

![image](https://user-images.githubusercontent.com/31357861/97350577-692e2380-186f-11eb-8a7b-8f6fed008a5b.png)

Finalmente, el problema de las flechas que quedan sin moverse se debe a que esta creación de flechas comienza antes de iniciar la ventana de juego, por ende cuando estás ingresando el nombre se están creando flechas. Para evitar esto te recomiendo conectar una señal que indique que se comiencen a crear flechas solo cuando se haya iniciado la ventana de juego.

**Comment by YehudaGurovich** [comment]
@kadroguett Te pasaste! Estube dandole vueltas y ya lo solucioné, tus comentarios me sirvieron mucho. El problema de las flechas sin moverse era porque estaba instanciando todos los tipos de flechas para seleccionar una que es la que baja y al instanciarlas todas estas aparecian en la pantalla.
