### ISSUE TITLE
Duda Clientes sin mesa

### ISSUE THREAD

**Issue by Francisco5674** [IIC2233/syllabus#844]
Hola!, se que ya respondieron esto antes, pero todavía no me queda claro, entonces ¿Si hay que hacer una fila de espera? o acaso ¿los clientes que llegan y ven que no hay mesa los pierdes definitivamente?, o ¿tienes que simularlos pero sin mesa, haciendo que una vez pase el tiempo de espera los pierdas?, o ¿simplemente los sientas a medida que pasen LLEGADA _CLIENTES segundos?, el enunciado no especifica nada de eso.

**Comment by jbulness** [comment]
Hola @Francisco5674,

Si no hay mesas disponibles simplemente no deben llegar más clientes hasta que se desocupe una mesa. Una vez que se desocupe una mesa puede llegar otro cliente, pero no hay que crear una lista de espera ni nada por el estilo.

Si aún tienes dudas vuelve a comentar acá!

**Comment by Francisco5674** [comment]
¿entonces pierdes clientes al no tener suficientes mesas?, por ejemplo, si tengo 1 mesa y 2 clientes en una ronda, cada uno llega cada 5 segundos, esperan como mucho 15 segundos por su comida, y me tardo 10 en atender a un cliente, ¿logro atender solo a 1 y el otro lo pierdo?

**Comment by jbulness** [comment]
No. Siguiendo tu ejemplo, debes esperar a que se desocupe la mesa y luego debe aparecer el 2 cliente.

**Comment by Francisco5674** [comment]
Pero entonces, ¿cual es el incentivo para comprar más mesas? Es decir, para ganar siempre, solo necesito tener 1 mesa,  ya que no importa la cantidad de clientes que tenga que atender estos siempre esperarán que la mesa se vacie, porque si se me ocurre comprar mas mesas corro el riesgo de que no alcanze a atender a clientes de otras mesas, sorry si molesto mucho, pero todavia no entiendo :(

**Comment by jbulness** [comment]
Tienes razón en que no tiene mucho sentido, pero hay varios elementos como ese que se quitaron para simplificar la tarea y pueden que no hagan sentido, perdón por la confusión. Puedes pensar que agregando más mesas puedes acabar la ronda más rápido.

**Comment by Francisco5674** [comment]
Hola, ya la ultima, es que mi código esta estructurado para funcionar de la manera en que pierdes clientes si no tienes mesas para atenderlos, de esa manera se incentiva la compra de las mesas ya que existe un intercambio de oportunidades, es decir, es verdad que una mesa adicional te otorga la posibilidad de perder menos clientes ya que tendrán donde sentarse, pero al mismo tiempo aumenta la dificultad del juego ya que no sabrás si podrás atender a todos los clientes, de esa manera el juego se torna un tanto más estratégico a la hora de tomar la decisión de comprar o no comprar mesas adicionales, el donde instalarlas e incluso te incentiva a comprar más chefs para tener más chances de ganar y pasar a la siguiente ronda, la cuestión es, ¿Puedo hacerlo de esa manera? o ¿estoy obligado a hacerlo como ustedes dicen?.

Muchas gracias !! 
sorry por molestar tanto, son super buena onda

**Comment by jbulness** [comment]
Hola @Francisco5674,

Perdón lo tardía de la respuesta y espero que hayas aprovechado tu semana de pausa.
Dado que no sale explícitamente en el enunciado, queda a tu elección como hacerlo. La verdad es que nosotros recomendábamos la primera opción porque era más fácil, pero encuentro buenísimo que hayas implementado esa nueva forma y que no te haya causado mayores problemas. Eso si, recuerda mencionar todo lo que hiciste en el `README.md` para que el/la ayudante corrector/a no se encuentre con sorpresas, ya que si le dificulta la corrección puede que te descuenten décimas.

Ánimo con el resto de la tarea!
