### ISSUE TITLE
Superposición de flechas

### ISSUE THREAD

**Issue by totoiii** [IIC2233/syllabus#845]
**Pueden las flechas superponerse?**
Si la respuesta es si, entonces si se da el caso de que N flechas están dentro de un cuadro, puedo sumar N veces el puntaje que te dá el acertar una flecha?

Si la respuesta es no, o si decido hacerlo de esta forma (es decir imponer que las flechas no pueden intersectarse), un caso es que baje una flecha y despues (por este mismo carril) baje una durada y debido a su velocidad estas naturalmente se intersectarían, puedo hacer que cuando justo llegue a casi intersectar una flecha haga que la flecha dorada tenga la misma velocidad que una normal?

**Comment by JuaniAndres** [comment]
Hola @totoiii 
La respuesta es que si, pueden ocurrir casos en que llegue más de una flecha junta por ejemplo una normal y una dorada en ese caso tienes que detectar todas flechas capturadas y manejarlo correctamente (sumar el puntaje que corresponde por cada flecha).
Espero haber aclarado tu duda, me avisas si te surge otra.
