### ISSUE TITLE
Es necesario crear una clase Clientes?

### ISSUE THREAD

**Issue by lewebe** [IIC2233/syllabus#845]
Hola, es necesario modelar a cliente como una clase? Me acomoda mucho más modelar la clase "Mesa" y que dentro de ella aparezca el cliente que toque según las probabilidades. Obviamente lo especificaría en el `README.md`, pero quería saber si hacerlo de esta manera me descontaría puntaje

**Comment by Francisco5674** [comment]
Hice exactamente lo mismo que tu XD, espero que no descuenten puntaje

**Comment by jbulness** [comment]
Hola @lewebe,

Sí es necesario crear al cliente como una entidad y esto se evalúa tal como se muestra en la distribución de puntajes. Les recomiendo mucho que se fijen en ella, porque podrían perder puntos innecesariamente.

**Comment by lewebe** [comment]
@jbulness Gracias por tu repuesta. Sin embargo, si me apego solamente a la distribución de puntajes, mi clase "Mesa" hace todo lo que se pide de la clase "Clientes", por lo que técnicamente con solo cambiar el nombre de la clase contaría para tener ese puntaje, o no?

**Comment by jbulness** [comment]
Si tu nueva clase `Clientes` cumple con lo pedido en el enunciado (y por lo tanto en la distribución de puntajes) respecto a la entidad `Clientes` y no la mezclas con lo que se pide en otras clases, es decir, las otras entidades pedidas poseen los métodos y atributos pedidos para cada una, entonces estás bien. Cómo implementas lo pedido queda a decisión tuya, siempre y cuando se respete lo pedido no solo en esta entidad, si no que también en el resto de las entidades.
