### ISSUE TITLE
impresión en mi terminal al ejecutar con qt desinger

### ISSUE THREAD

**Issue by Margarita-Paz** [IIC2233/syllabus#846]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola!
Cuando ejecuto mi programa se imprime en la terminal "Unknown property font-color"

**Comment by kadroguett** [comment]
Hola @Margarita-Paz, puedes subir lo que llevas a tu repositorio para revisarlo mejor por favor.

**Comment by Margarita-Paz** [comment]
listo! 😄

**Comment by kadroguett** [comment]
Ejecuté tu programa y no me aparece el `print` que me dices, pero revisando el archivo `ventana_juego.ui` noté que agregas un `stylesheet` a un form:

![image](https://user-images.githubusercontent.com/31357861/97253824-e1530580-17eb-11eb-89d3-4bb0cd40238a.png)


Si borras lo que está en el cuadro rojo debería dejar de aparecerte ese `print`, cuentame si te funciona.

**Comment by Margarita-Paz** [comment]
Sii, toda la razón
Muchas gracias!
