### ISSUE TITLE
Transformar QLabel  a QDrag

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2233/syllabus#846]
Hola. Me gustaria saber como transformar un QLabel  a QDrag.
Lo que me pasa es que cree mi ventana principal a traves de Qt Designer. La importe a pyhton y lo que estoy tratando de hacer es transformar mi chef de la tienda (self.chef digamosle), que es un QLabel, a un QDrag para que el metodo mouseMoveEvent y mousePressEvent me permitan arrastrarlo. 
Como puedo hacer esto??

**Comment by dsepulveda3** [comment]
Actualmente mi chef es QLabel y cuando defino los metodos mousePressEvent y mouseMoveEvent no puedo mover nada en mi ventana

**Comment by fdoflorenzano** [comment]
Hola @dsepulveda3,

Tu pregunta original es difícil de contestar ya que revisando la documentación de PyQt, `QDrag` es algo bien distinto de un `QLabel`, entonces es raro de ver como transformar uno en otro. El problema parece ser más bien algo sobre  la interacción de *drag and drop* a implementar. ¿Has podido avanzar en esto desde entonces? 

Saludos.

**Comment by dsepulveda3** [comment]
Jajaja si cache! Finalmente no use los QDrags use los MouseEvents de pyqt5 está bien?

**Comment by fdoflorenzano** [comment]
No se espera una implementación específica para el *drag and drop*, mientras funcione como se espera, debería estar bien.
