### ISSUE TITLE
QLabels en Qwidget

### ISSUE THREAD

**Issue by Miguel-Cox** [IIC2233/syllabus#847]
Intente hacer lo mismo que en el video numero 2 de respuestas a dudas anonimas, en donde se crean 2 Labels dentro de un mismo Widget.
Resulta que intento hacer esto mismo en mi codigo, pero al momento de llamar por segunda vez al Widget de la forma:
label = QLabel(QWidget), me tira error diciendo que el Qwidget indicado no esta definido.

**Comment by fdoflorenzano** [comment]
Hola @Miguel-Cox,

El error parece ser más bien algo de falta de definición de una variable o falta de importar algo. ¿Pudiste solucionarlo?

**Comment by Miguel-Cox** [comment]
Logre solucionarlo agregando el Widget a un diccionario y llamandolo desde ahí.
Muchas gracias por responder.
