### ISSUE TITLE
Terminar QThreads

### ISSUE THREAD

**Issue by fedezang** [IIC2233/syllabus#847]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Quería saber cómo me puedo asegurar que los qthreads terminan. Ya que al realizar una ronda, mis flechas funcionan bien y desaparecen cuando las atrapo en la zona de captura. Pero cuando intento jugar por segunda vez, aparecen muchísimas flechas en la zona de ritmo. He visto mi código varias veces pero no logro encontrar el error, ya que deberían eliminarse todas las flechas de la primer ronda ¿Es quit() una forma de terminar qthreads?

**Comment by YehudaGurovich** [comment]
No se cual es la diferencia entre quit() y exit().

**Comment by manearaya** [comment]
Hola!

Una manera de saber si un thread ha terminado es usando el método` .isRunning()`, que retorna True cuando el thread sigue activo y False cuando no. También es muy útil hacer prints en la consola para tener una noción de qué está pasando con tu código: por ejemplo, cuando empieza el thread, cuando llega a su fin o en algún _checkpoint_.

Con respecto a los métodos para terminar un thread: es una mala práctica terminar un thread antes de que termine solo, porque significa que no ha completado lo que está hecho para hacer y esto puede traer problemas a tu código. Para asegurarte de que termine puedes agregar otra condición, como en el ejemplo del issue #781 (este es un thread y no un QThread, pero es la misma idea).

Con respecto a quit() y exit(): ambos son métodos que manejan un QEventLoop (provocan que se salga de este), y si un QThread no tiene un QEventLoop entonces van a provocar nada.  La diferencia entre ellos es el exitcode, que para efectos prácticos del curso no tiene mucha importancia. Si quieren saber más, siempre pueden revisar la documentación de Qt para [QThreads](https://doc.qt.io/qt-5/qthread.html#quit) y [QEventLoops](https://doc.qt.io/qt-5/qeventloop.html). 

Espero que les haya ayudado!
