### ISSUE TITLE
Duda sobre variables globales en el main.py

### ISSUE THREAD

**Issue by martin-iturralde** [IIC2233/syllabus#848]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Es que leí lo prohíbido en la tarea y dice que no puedo usar variables globales. Sin embargo, para poder conectar las señales e instaciar las clases, necesito que sean globales.... Me bajarían décimas si es así? Si este fuera el caso, cuántas serían?
O lo mejor sería hacer una clase que englobe todo?
Muchas gracias!

**Comment by gatochico** [comment]
Hola @martin-iturralde ! (disculpa la demora)

El descuento por variables globales aplica cuando defines variables en tu código fuera de funciones o clases, con el fin de llamarlas dentro de estas sin tener que pasarlas como argumento (funcionando de forma similar a un parámetro, pero sin ser un parámetro.).  Como tu mismo indicas, la mejor práctica sería englobar las cosas en funciones o en clases y no tener código 'suelto', por decirlo así. 

Por la definición de arriba, si instancias estas clases para conectar las señales (en un formato similar al `main` de la AF03), no estarías rompiendo con lo que buscamos evitar al usar variables globales. Trata de usar como referencia la AF03 para la conexión de señales y no habrá problema 👌 .

Saludos!
