### ISSUE TITLE
¿Qué es el reloj?

### ISSUE THREAD

**Issue by lewebe** [IIC2233/syllabus#848]
Hola, aún no me queda claro qué es el reloj interno. Debe ser una clase? Un _QTimer_? Debe mostrarse al usuario? No entiendo la idea detrás del reloj, y las otras _issues_ no me lo dejaron muy claro.

**Comment by jitorralba** [comment]
Hola! No soy ayudante pero según entendí, el reloj es lo que permite regular los tiempos en el juego cuando es necesario. No creo que sea necesario mostrarlo en pantalla, ya que para eso se realizan los cambios de _sprites_ cuando los clientes cambian de estado a modo de notificar al jugador que se le está acabando el tiempo para atenderlos.

**Comment by lewebe** [comment]
@jitorralba Gracias por contestar! Respecto a lo de los cambios de sprites, los planeo implementar dentro de la clase `Clientes`, para que así cada instancia cambie de sprite según el momento que llega/el tiempo que debe esperar/etc. Lo único que se me ocurre que se debe regular por un "reloj" sería la llegada de los clientes...

**Comment by jitorralba** [comment]
Creo que asi queda bien, es como para lo unico que se usa

**Comment by fdoflorenzano** [comment]
Hola @lewebe,

La intuición que dio @jitorralba es correcta. Como queda en tu programa depende bastante de como lo modeles, así que no necesariamente se verá de la misma forma para todos los programas. El punto es que el "tiempo" del juego sea consistente entre sus distintas entidades .

Saludos.
