### ISSUE TITLE
¿Es necesario usar QtDesigner?

### ISSUE THREAD

**Issue by Mario-uc** [IIC2233/syllabus#849]
Es obligatorio o necesario usar Qdesigner para la tarea 2? Es que hice el avance y la pantalla de partida (donde sale si continuar o crear nueva partida) con código. Sería recomendable continuar con designer o empezar de 0 con designer?

**Comment by jbulness** [comment]
Hola @Mario-uc,

No es necesario usar QtDesigner para hacer la tarea. Personalmente yo nunca lo usé cuando dí el ramo, porque perdí mucho tiempo instalándolo y seguí solo con código y no tuve problemas. Ahora bien, se recomienda su uso, ya que facilita y agiliza la creación de ventanas y permite una posterior personalización en código.
