### ISSUE TITLE
Intersección de dos QWidgets mediante QRect

### ISSUE THREAD

**Issue by tcouso** [IIC2233/syllabus#849]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### ¿Cómo puede implementarse un evento personalizado de intersección entre dos `QRect`?

Estoy implementando la zona de atrapado de flechas, y me ha costado diseñar un mecanismo para detectar la coincidencia entre la intersección de una flecha con la zona de atrapado correspondiente y la activación de dicha zona al presionar su respectiva tecla *en el caso particular de cuando hay más de una flecha, o más de una tecla activada*. Se me ocurre como método diseñar un evento personalizado dentro de la zona de atrapado que se active cuando exista una intersección entre la zona de atrapado y un `QRect` de cualquier flecha superpuesta, de manera tal que pueda emitirse un código que describa las cuatro casillas de atrapado simultáneamente. Algo así como: **[1,0,0,0] para la flecha izquierda activada y todas las demás desactivadas** (actualmente mí código sólo describe una casilla a la vez, de modo que falla en ese último punto). Revisando la documentación descubrí la clase `QEvent` como potencial solución, pero he tenido problemas para entender su forma de implementación, por lo que agradezco cualquier ayuda a este respecto.

Saludos!

**Comment by aljara97** [comment]
Hola @tcouso, en la página 11 del enunciado se habla del método [`intersects`](https://doc.qt.io/qt-5/qwidget.html#geometry-prop) de `QRect`, este recibe otro `QRect` y retorna un booleano si es que ambos se intersectan. También les damos la pista de que puedes obtener el QRect de un QWidget mediante el método [`geometry`](https://doc.qt.io/qt-5/qwidget.html#geometry-prop). Te invito a que le eches una mirada a la documentación de estos métodos y me comentes si te quedan dudas.
