### ISSUE TITLE
Otra duda del bonus

### ISSUE THREAD

**Issue by valerojasm** [IIC2233/Syllabus#849]
Hola!

Como varios pusieron en las issues, lo único que está en palabras para cumplir el requerimiento del bonus es la descripción del tiempo. Le agregué una frase más larga para que efectivamente funcionara la yoda api, esto cuenta para el bonus o hay que agregar algo más?

Gracias!

**Comment by shantifabri** [comment]
Hola! @leolivares,
para el bonus basta poner por ahi algo como una frase de bienvenida traducida a yoda en vez de cambiar el reporte mismo? ya que esto ultimo se presta para que no se entienda la información o si se hiciera solo con la descripción del tiempo son frases muy cortas entonces no las cambia (ademas de agotarse el uso de la api).
Gracias!

**Comment by leolivares** [comment]
Hola! @shantifabri 
Si, no hay problema.

**Comment by ciquezada** [comment]
No habria problema entonces en poner una frase de bienvenida y despues ponerla denuevo pero dicho por yoda??  (digo porque habrá confianza entonces en que no fuimos nosotros lo que la escribimos como yoda) (quiza podemos poner el readme la linea donde se hace el request)

**Comment by leolivares** [comment]
@ciquezada. Claro, la idea es simplemente que utilicen la API. También podrían crear una frase con los datos de OpenWeather, y pasárselo a la API de Yoda. Especifíquenlo en el Readme para facilitar la corrección. Saludos.

**Comment by ciquezada** [comment]
@leolivares graciaaaas!!!
pero creo que me quedo con esto : "Claro, la idea es simplemente que utilicen la API"
porque para traducir, en el puro pronostico se agotan los usos de la API, traducir una frase de bienvenida creo que es lo mejor
