### ISSUE TITLE
Asumir respecto a incendios

### ISSUE THREAD

**Issue by gbordoni** [IIC2233/Syllabus#85]
Buena cabros, queria preguntarles si es que puedo asumir que al momento de calcular la estrategia de extincion y de mandar los recursos, despues de que los recursos llegan al lugar el radio del incendio deja de crecer en el futuro?
Esto porque es un poco contradictorio que llegue uno o más recursos al incendio, y que mientras estos le quitan puntos de poder, el incendio siga ganando radio (y por ende ganando puntos de poder).

Saludos

**Comment by Hernan4444** [comment]
@gbordoni no le encuentro lo contradictorio a ese caso, si hay un incendio enorme y se manda un carro de bomberos, claramente este se seguirá expandiendo puesto que con un carro no se lograría combatir el incendio. En respuesta a tu pregunta, no puedes asumir que dejará de crecer. Pero recuerda que un incendio extinguido es aquel que tiene 0 puntos de poder, en ese momento puedes suponer que ya no hay mas propagación.

**Comment by rgriver** [comment]
Yo pensaba usar la siguiente fórmula:
![expr](https://cloud.githubusercontent.com/assets/22522629/24076271/3a49ba4e-0c0b-11e7-961c-0bf64643d284.gif)
Donde N son los puntos de poder que el recurso quita por unidad de tiempo, P es la potencia del incendio, x_{i}^{t} es una variable binaria que indica si el recurso i se usa para apagar el incendio durante la unidad de tiempo t, \Delta^{t} es el efecto del tiempo y r^{t} es el radio del incendio al final de t que se usa para calcular los puntos de poder del incendio al final de t. Un incendio se considera apagado si sus puntos de poder son cero (radio cero o negativo). Del enunciado entendí que los puntos del recurso modifican los puntos de poder y este valor depende únicamente del radio. amirite?

**Comment by Hernan4444** [comment]
@rgriver te recomiendo ir a la issue #59, ahí se explicó bien los incendios.

Saludos!
