### ISSUE TITLE
Duda sobre archivos (maxsplit y orden id)

### ISSUE THREAD

**Issue by J0SEF4** [IIC2233/Syllabus#85]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
1. Pregunta respecto a Maxsplit:
En el enunciado aparece que se puede usar maxsplit, para el caso de las comas que hay en publicaciones.csv y comentarios.csv. Mi pregunta respecto a esto es que esto no es obligatorio usarlo, es solo una sugerencia cierto?

2. Pregunta respecto orden ID:
El id del archivo csv de publicaciones. Cuando elimino una publicación, ¿el id debe volver a ordenarse o lo puedo dejar que ese id desapareció?

**Comment by mmunoz12** [comment]
Hola @J0SEF4!

Para tu primera pregunta, como tu dices, no es obligatorio usar la función `maxplit()`, esta sólo se da como recomendación ya que facilita el manejo del archivo _comentarios.csv_, sobretodo para separar correctamente los comentarios de los demás atributos.
Y sobre tu segunda duda, esto mismo se respondió en la issue #72, para que le eches una miradita (en resumen, los ids no debiesen cambiar, solo eliminar el que se quiere eliminar).

 Avísame si te quedan dudas! ☺️ Suerte en tu tarea!
