### ISSUE TITLE
Problema en la utilizacion de testcases en la actividad 1

### ISSUE THREAD

**Issue by maximmmb** [IIC2233/Syllabus#85]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.

### Contenido

Hola, buenas tardes, el problema que presento es que no se como probar los testcases de la actividad 1 para poder comprobar que testcases esta pasando y cuales no mi archivo

Saludos

**Comment by Dvckhv** [comment]
Debes ejecutar el archivo test.py
