### ISSUE TITLE
Determinación del turno al cargar una partida

### ISSUE THREAD

**Issue by fjhuanca** [IIC2233/syllabus#85]
Hola! Mi inquietud es que si por algún motivo no hay ninguna acción pendiente al momento de guardar la partida (y por ende el archivo *acciones_pendientes.csv* está vacío) no es posible determinar el turno en el que se guardó la partida. **Dado que el turno es importante para ganar por turnos, al cargar una partida ¿cómo se determina este? ¿se asume como turno 0? ¿o en el archivo** *acciones.csv* **solamente contendrá las acciones restantes a partir del turno guardado y se determina gracias a eso?**

**Comment by jeschuwirth** [comment]
Saludos!

Como puedes ver en la siguiente foto del enunciado 
![image](https://user-images.githubusercontent.com/37160256/55266791-78955700-525d-11e9-9a1d-fb2f83a93564.png)

El archivo acciones.csv sólo guarda las acciones futuras, por lo tanto puedes ver el primer dato de la primera columna y obtendrás el turno actual de la partida.

Entiendo que está algo oculto en el enunciado y no era simple de ver a la primera, así que buena consulta.

Suerte en la Tarea!

**Comment by fjhuanca** [comment]
Oooh  perdón se me pasó y estaba explícito jaja muchas gracias. Aprovecho de resaltar la issue #72 que aún no me queda clara :)
