### ISSUE TITLE
partir con galaxia al correr programa

### ISSUE THREAD

**Issue by santilaguna** [IIC2233/Syllabus#85]
¿Podemos asumir que, al momento de correr el programa, existirá al menos una galaxia? de lo contrario, ¿podemos al iniciar el programa, en caso de que no exista una galaxia, obligar al usuario a crear su primera galaxia?

**Comment by leolivares** [comment]
Hola.
No puedes asumir que existirá una galaxia desde el inicio.
Tampoco es necesario obligar al usuario a crear una, simplemente no podrá realizar ninguna de las funcionalidades principales, hasta que decida crear alguna.

**Comment by santilaguna** [comment]
Oka gracias!
