### ISSUE TITLE
Duda sobre comisión

### ISSUE THREAD

**Issue by jadiaz6** [IIC2233/Syllabus#85]
Cual es la comisión de cada mercado? La inventamos?

**Comment by fnquinteros** [comment]
Cualquier cosa que no esté especificada en el enunciado queda a tu criterio, a menos que tu criterio pase a llevar alguna otra restricción 😅 la tasa de cada mercado debe ser un número entre 0 y 1 y esta determina la comisión dependiendo del monto transado. 

Saludos!
