### ISSUE TITLE
Uso .gitignore

### ISSUE THREAD

**Issue by juanriveraf** [IIC2233/Syllabus#85]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Acabo de hacer un commit de mi tarea 1 con el archivo de .gitignore.  De todas formas, yo ya había hecho un commit sin .gitignore, por lo que los archivos que no se tenian que subir se subieron igual en otro commit, pero no en el ultimo que hice. Tengo entendido que se corrige solo el ultimo commit que uno hace, pero queria confirmar si esta bien que se hayan subido estos archivos antes, si de todas formas ahora si tengo el .gitignore. Muchas gracias!

**Comment by ChupeteBecker** [comment]
Hola @juanriveraf, los archivos que deben ir en el .gitignore mencionados en el enunciado no deben ser subidos a github, el .gitignore es el archivo que debe encargarse de eso, pero no funciona si es que ya habías subido los archivos anteriormente.

Te recomiendo que revises la issue #53 donde doy una solución a esto.

Saludos!!

**Comment by ChupeteBecker** [comment]
El .gitignore debería verse en ambos lugares, estás seguro que te metiste a la carpeta de la T1 cuando abriste la carpeta del repositorio desde tu escritorio?

De todas formas no debería ser un problema mientras el .gitignore esté funcionando y aparezca en github

**Comment by Hernan4444** [comment]
Hola @juanriveraf 

Solo para complementar, lo que pasa que como el archivo se llama `.gitignore` (todo está despues del nombre), es un archivo oculto que por defecto el explorador no ve. Si buscas, según tu sistema operativo, cómo ver los archivos ocultos, ahí verás que existe el `.gitignore`.

🦖
Saludosヾ(＾-＾)ノ

**Comment by juanriveraf** [comment]
Hola @Hernan4444 , recien veo su mensaje. Muchas gracias por la respuesta, despues de investigar solo encontre un comando para encontrarlo en la carpeta (cmd shift punto en mi caso).

Muchas gracias!
