### ISSUE TITLE
Posibles errores del jugador

### ISSUE THREAD

**Issue by ivan-sandoval** [IIC2233/syllabus#85]
Hola, una pregunta, lo que sucede es que en la mayoria de mi tarea definí las variables numericas, por ejemplo, el número de filas o columnas del tablero,  como :
 variable = int(input("Ingrese un número")) ;
En el caso de que el jugador ingrese una letra o bien no ingrese ningun valor al input, Python tiraría error, debo corregir eso o bien suponer que el jugador ingresará los valores pedidos?

**Comment by cotefon** [comment]
puedes usar isdigit() para ver si ingreso una letra, pero tengo entendido que tiene que ser a prueba de cualquier error (eso dice en el enunciado)

**Comment by gatochico** [comment]
Hola!

Tal como dice @cotefon , efectivamente estamos pidiendo que tu consola sea a prueba de errores. No podrás asumir que siempre ingresaremos todo de forma 100% correcta :scream: 

Saludos!

**Comment by ivan-sandoval** [comment]
Bueno, muchas gracias
