### ISSUE TITLE
Problemas con PEP8 en VScode (macOS)

### ISSUE THREAD

**Issue by rosario-frugone** [IIC2233/syllabus#85]
* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

Hola! Estoy utilizando Visual Studio Code y no me reconoce los errores (PEP8), ya traté:
- Python Select Linter pycodestyle (también intenté con flake 8)
- Settings: Python › Formatting: Provider "autopep8"
- sudo pip3 install pylint
- "python.linting.pycodestyleEnabled": true to ~/Library/Application Support/Code/User/settings.json
- Borrando e instalando de nuevo VScode

ayuda por favor 😭

**Comment by pedroriosg** [comment]
Hola @rosario-frugone ✌️ 

Sigue los siguientes pasos y cuéntame como te va:

1. Abrir VSCode y presionar `Ctrl + Shift + P` (`Cmd + Shift + P en MacOs`).
2. Escribe en el buscador json y selecciona la opción que dice `Preferences: Open Settings (JSON)`. Se les va a abrir un archivo con extensión`.json`, que contiene en él un diccionario.
3. Escribe las siguientes líneas en tu diccionario: 
`"python.linting.pycodestyleEnabled": true,`
`"python.linting.pycodestyleArgs": ["--max-line-length=100"],`

4. Guarda los cambios realizados en el archivo.

Se debería ver de la siguiente manera:

<img width="458" alt="Captura de Pantalla 2021-03-29 a la(s) 13 08 24" src="https://user-images.githubusercontent.com/69609154/112866163-db5d9b00-908f-11eb-8e12-0aa064bedff0.png">

Con eso, tendrán el linter configurado y listo para tu tarea.

Espero que te sirva! Saludos!
