### ISSUE TITLE
Duda con la diferencia entre la acción "jugar" de Casino y la acción "apostar" de Jugador

### ISSUE THREAD

**Issue by StoicSilver** [IIC2233/Syllabus#85]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
 
En la descripción de las acciones de cada entidad, hay dos acciones con nombres distintos (una para implementarse en Casino y la otra en Jugador), que tienen descripciones muy parecidas y no sé si debo implementar ambas o si podré simplemente omitir una y así no entorpecer el flujo de mi código.
Adjunto fotos con las descripciones de la acción **jugar** de **Casino** y la acción **apostar** de **Jugador**. 

## Casino:
![image](https://user-images.githubusercontent.com/101607537/161442436-60cb5981-dafd-4d9d-83ae-8455a0d9204e.png)

## Jugador:
![image](https://user-images.githubusercontent.com/101607537/161442572-d38d69b7-d477-4d3e-b8f3-2fff892d1ac8.png)

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by antoniablanco** [comment]
Hola, al estar definidas como parte de identidades distintas es necesario que existan para cada una. Pero puedes ver como escribir tu codigo de tal forma que no sean exactamente lo mismo.

**Comment by nicolasgarciaes** [comment]
Hola, la verdad es que no entiendo muy bien la particularidad de la acción Jugar de la entidad Casino, esta acción se le debe aplicar a un jugador en particular? es decir, con el que se inicio la sesión o se debe realizar sobre un jugador al azar, y por otro lado, el juego debe ser seleccionado de manera aleatoria?
