### ISSUE TITLE
Tildes como carácteres alfanuméricos

### ISSUE THREAD

**Issue by nachobascar** [IIC2233/syllabus#85]
Los carácteres alfanuméricos incluyen los tildes??

**Comment by aljara97** [comment]
Hola @nachobascar, efectivamente una letra con tilde es considerado un caracter alfanumérico (por ejemplo áéíóúwúúúú podría ser considerado un nombre de usuario válido en tu programa). Recuerda que hay funciones de python que te pueden ser útiles para detectar si un string cumple con estas condiciones :eyes:

Éxito con tu tarea 🐦

**Comment by nachobascar** [comment]
Gracias!!

**Comment by aljara97** [comment]
De nada, por favor no cierres una issue cuando se resuelva tu duda, puede ser de ayuda para otro compañero 🤓
