### ISSUE TITLE
Usar código de laberinto.py

### ISSUE THREAD

**Issue by blampasona18** [IIC2233/Syllabus#85]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/21)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/20)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola **se puede usar algo del código que subieron en Ayuda para la tarea?** Siempre y cuando lo cite correctamente.

**Comment by terelopezc** [comment]
Hola @blampasona18!! Sii no hay problema en que lo uses, pero es muy importante que esté citado para que tu ayudante se de cuenta! Te recomiendo agregarlo en la parte sugerida en el Readme y además cómo comentario en la parte del código.

**Comment by blampasona18** [comment]
Perfecto gracias!
