### ISSUE TITLE
Api Key y user_id

### ISSUE THREAD

**Issue by ibaeza1** [IIC2233/Syllabus#850]
Una duda. Para poder mandar mails necesitamos un user_id que es el mail que use para sacar mi api key. Ese es el mismo mail que va a mandar el correo del reporte? Porque al principio el usuario ingresa su nombre y su mail pero ese es el mail que va a recibir el reporte no el que lo va a mandar. Y lo otro: Tengo que dejarlo como parametro cosa que despues cuando sea corregido puedan cambiarlo?
Muchas gracias :)

**Comment by leolivares** [comment]
Hola! @ibaeza1 
Si, la idea es que este como parámetro, para que sea fácil de modificar al momento de corregir.
Saludos.
