### ISSUE TITLE
[RegEx] + vs *

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#850]
Por qué en este ejemplo los operadores + y * traen resultados distintos?

![image](https://user-images.githubusercontent.com/66154723/126091619-f2fc7a7f-10ed-45b6-9f18-2040bb05a289.png)

![image](https://user-images.githubusercontent.com/66154723/126091650-1704ea6d-18f0-4122-8c15-5af117cf217e.png)

**Comment by aaossa** [comment]
Hola @fernandosmither , recuerda que `^` marca el inicio de un *string* y que `*` y `+` son cuantificadores. Mi primera impresión fue que tu regex no está bien definida, porque lo que dices en el primer caso es "busca el inicio del *string* y después algo (?) que esté 1 o más veces justo antes del final" y en la otra dices "busca el inicio del *string* y después algo (?) que esté 0 o más veces justo antes del final".

Dándole otra vuelta, creo que lo que ocurre es que para Python ese "algo (?)" es justamente el inicio del *string*:

1. **"Busca que el inicio del *string* esté 1 o más veces justo antes del final"**: Esto solo es posible si el *string* tiene largo 0. Probé ese caso y justamente lo marca como *match*, así que vamos bien 👌 
2. **"Busca que el inicio del *string* esté 0 o más veces justo antes del final"**: Como Python puede ver todos los casos como si el inicio del *string* estuviera 0 veces justo antes del final, esta expresión se reduce a "es un *match* si es que el *string* tiene final", o sea todos los *strings* posibles.

Espero se entienda 😅

**Comment by fernandosmither** [comment]
> Hola @fernandosmither , recuerda que `^` marca el inicio de un _string_ y que `*` y `+` son cuantificadores. Mi primera impresión fue que tu regex no está bien definida, porque lo que dices en el primer caso es "busca el inicio del _string_ y después algo (?) que esté 1 o más veces justo antes del final" y en la otra dices "busca el inicio del _string_ y después algo (?) que esté 0 o más veces justo antes del final".
> 
> Dándole otra vuelta, creo que lo que ocurre es que para Python ese "algo (?)" es justamente el inicio del _string_:
> 
> 1. **"Busca que el inicio del _string_ esté 1 o más veces justo antes del final"**: Esto solo es posible si el _string_ tiene largo 0. Probé ese caso y justamente lo marca como _match_, así que vamos bien 👌
> 2. **"Busca que el inicio del _string_ esté 0 o más veces justo antes del final"**: Como Python puede ver todos los casos como si el inicio del _string_ estuviera 0 veces justo antes del final, esta expresión se reduce a "es un _match_ si es que el _string_ tiene final", o sea todos los _strings_ posibles.
> 
> Espero se entienda 😅

Me hace todo el sentido del mundo, muchas gracias!

Una duda emergente, cómo probó que un string vacío le diese match? no se vería un output vacío, al igual que cuando no se encontró nada?

**Comment by aaossa** [comment]
Usé tu mismo código (cambié el primer elemento en la lista por un *string* vacío), entonces se imprimió ` cumple con el patrón`. Esto significa que el patrón sí encontró algo, solo que "coincidió" con que `s` era vacío.

**Comment by fernandosmither** [comment]
> Usé tu mismo código (cambié el primer elemento en la lista por un _string_ vacío), entonces se imprimió ` cumple con el patrón`. Esto significa que el patrón sí encontró algo, solo que "coincidió" con que `s` era vacío.

Toda la razón, Gracias! 😄
