### ISSUE TITLE
Duda tiempo partida y pasos fallados

### ISSUE THREAD

**Issue by Jamesmoreno21** [IIC2233/syllabus#850]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Tengo una duda sobre cómo ha de entenderse el tiempo de las partidas exactamente, por ejemplo si es dificultad principiante la partida debe durar 30 segundos y se generan flechas cada 1 segundos, por lo que uno esperaría formar 30 flechas, pero no todas de estas serán "capturables" porque algunas recién habrán sido formadas y no llegarán a la zona de captura, lo que dificulta por ejemplo el conteo de pasos generados en la aprobación, por lo que mi duda es ¿ qué tan rígido es el factor tiempo de partida? ¿ puedo generar una flecha cada 1 segundo y esperar a que sea capturada, fallada u omitida y completar así 30 flechas? en esto último demoraría un poco más de 30 segundos pero el nivel terminaría con las flechas o ¿es más recomendable que genere menos flechas de modo que la última pase por la zona de captura lo más cercano posible al segundo 30?

Mi otra duda es si puedo asumir, que si genero un paso y viene cayendo por la zona de de ritmo y el usuario presiona una/s tecla/s antes del tiempo ¿puedo contabilizarlo automáticamente como erróneo y hacer desaparecer la flecha?, ya que actualmente considero que el paso que esté más abajo en la zona de ritmo es el próximo a capturar (esto antes de la zona de captura, si la pasa aunque presione no ocurrirá nada y seguirá bajando), entonces, por ejemplo, si viene un paso a mitad de camino y  y el usuario presiona una tecla, al no estar en la zona de captura queda como erróneo y elimino la flecha ¿es válido?.

Gracias de antemano! 😃

**Comment by jaimecoloma** [comment]
Hola @Jamesmoreno21  en el **enunciado** se especifica lo siguiente: "Una vez transcurrido el tiempo del nivel se dejarán de generar nuevas flechas y el nivel terminará cuando ya no queden flechas en pantalla, sea porque el jugador las capturó o porque pasaron de largo sin ser capturadas." Por lo que es correcto que esperes a que bajen y alli el usuario las capture, falle u omita.
Sobre tu segunda duda, en el enunciado también se menciona con ejemplos los tipos de pasos correctos e incorrectos, sería bueno que menciones de todos modos en tu readme cómo definiste esta parte.
Si tienes más dudas, adelante! Mucho éxito!

**Comment by chineseJack564** [comment]
Hola, sobre esta misma situacion, que pasa si uno usa el cheatcode de terminar? Los flechas que esta en la pantalla debe desaparecerse de una? O tambien hay que esperar que cae todos noma?
Y si yo implemento de alguna forma que cuando termino la cancion, las flechas desaparecen altiro estaria malo?

**Comment by jaimecoloma** [comment]
@chineseJack564 para el cheatcode de terminar, si te fijas en el enunciado, se especifica que los calculos de puntaje, aprobación y todo se calcula con todo lo guardado hasta la última flecha capturada, por lo que,  lo importante es que se utilice bien esa parte del cheatcode (y que no caigan más flechas y se detenga la canción). Como no se especifica podrias hacerlas desaparecer o dejarlas caer, pero si las dejas caer **no** se deben poder capturar ya que no se cumpliría correctamente el cheatcode. De todos modos sería bueno que también lo señales en tu readme para que quien te corrija entienda como lo implementaste, pero debes respetar lo que mencioné.
¡Ánimo!

**Comment by cnillanes** [comment]
Hola! sigo media enredada con esto :( 
Si se acaba la canción y quedan flechas en pantalla debo esperar que terminen de bajar para finalizar el nivel o las hago desaparecer enseguida?
En el caso que espere que bajen, el usuario puede seguir sumando aprobacion pese a que el progreso ya será 100%? 

Gracias desde ya!

**Comment by jaimecoloma** [comment]
@cnillanes el nivel termina cuando bajen todas las flechas que se deben generar en el tiempo del nivel. Lo segundo es correcto, pueden seguir sumando aprobación a pesar que el progreso de la canción sea 100%, ya que ese indicador solo es respecto a la canción y no sobre aprobación o puntaje. Espero te quede más claro con eso! Si no puedes seguir preguntando sin ningun problema!
