### ISSUE TITLE
RegEx

### ISSUE THREAD

**Issue by ctronp** [IIC2233/syllabus#851]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/681)
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola. Una sola duda, Donde se puede encontrar la tarea de RegEx?
O esta es una actividad similar a las AS? si es asi sera el dia jueves?

Gracias

**Comment by fernandosmither** [comment]
Hola, vi en el anuncio de canvas que decía "La duración de la actividad será de 5 días y será desde este lunes 19 de Julio hasta el viernes 23 a las 20:00 horas. ", entonces supongo que la publicarán hoy más tarde, pero de paso agradecer a los profes por agregar el contenido de regex y web services que es tan importante. 👍

**Comment by aaossa** [comment]
Ya se publicó el enunciado y otros archivos en la carpeta `Bonus/` del Syllabus 👌 ¡Éxito con la actividad! ✨
