### ISSUE TITLE
Botones con Qt Designer

### ISSUE THREAD

**Issue by Francisco5674** [IIC2233/syllabus#851]
Hola!
Me di cuenta que en Qt Designer cuando creas Qpushbuttons estos tienen por default el keypressevent de que cuando presionas espacio, todos se activan al mismo tiempo, ¿Hay alguna forma de desactivar esa opción por defecto?

Gracias!

**Comment by fdoflorenzano** [comment]
Hola @Francisco5674,

Intenté replicar lo que indicas en mi caso y no lo logré, no se me activan en conjunto al presionar espacio. ¿Pudiste resolverlo desde entonces?

Saludos
