### ISSUE TITLE
retorna error con ```[\w ]+```

### ISSUE THREAD

**Issue by ctronp** [IIC2233/syllabus#852]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

me pasa que al hacer  ```[\w ]+``` en algunas ocaciones (usualmente cuando debo colocarlo dentro de variables) me arroja el siguiente error, :
```
trailing unparsed: '{[\w ]+}'
```
no es al azar sino que depende de como lo escriba, si escribo ```[a-zA-Z_ ]``` funciona bien.

**Comment by aaossa** [comment]
Hola @ctronp , ¿podrías especificar mejor tu duda? No se entiende si esto es una excepción o *warning*, si viene desde Python o rematch, ni cuál línea produce el error (es compile o es en otra parte). Con eso sería más fácil responder la duda. Gracias 🙌

**Comment by nicovsj** [comment]
Hola @ctronp,

El problema de tu consulta es que no asociaste una variable a ella. La sintáxis correcta sería `!x{[\w ]+}` (lo que capturará el output de la expresión `[\w ]+` en una variable `x`).

Saludos!

**Comment by nicovsj** [comment]
@ctronp Disculpa, acabo de notar que en realidad el error que parece que tienes es que estás usando `\w` dentro de una _charclass_ (lo que se expresa en corchetes: `[expr]`). Esto no está soportado en REmatch actualmente, si quieres una expresión que captura lo mismo puedes usar `(\w| )` o bien `[A-Za-z0-9 ]`. 

Gracias de todas formas, esto es algo que nos sirve para ir mejorando la librería. 

Saludos!

**Comment by ctronp** [comment]
@nicovsj gracias, me funciona perfecto si ocupo ```[A-Za-z0-9_ ]```. voy a probar a usar ```(\w| )``` y quizas dejo el codigo mas limpio.

**Comment by nicovsj** [comment]
Genial. Ojo que el equivalente a `[A-Za-z0-9_ ]` sería `(\w|_| )` (o bien, `(\w|[ _])` que es lo mismo).
