### ISSUE TITLE
Como implementar si cliente da propina

### ISSUE THREAD

**Issue by amparostevens** [IIC2233/syllabus#852]
Hola! En el enunciado sale que el cliente puede o no dejar propina pero no sale cómo hay que implementarlo. Alguna idea?

**Comment by Christian-Klempau** [comment]
No soy ayudante, pero en el enunciado dice que a partir de la fórmula "Calidad del pedido", el resultado se traduce en la probabilidad de que el cliente te entregue propina o no, donde PROPINA es un elemento de parametros. Eso encontré, buena suerte!

**Comment by amparostevens** [comment]
@Christian-Klempau Muchas gracias!! No había cachado jaja

**Comment by Christian-Klempau** [comment]
De nada!

**Comment by fdoflorenzano** [comment]
¡Gracias @Christian-Klempau!
