### ISSUE TITLE
El valor de 'respuesta' debe ser una lista

### ISSUE THREAD

**Issue by ctronp** [IIC2233/syllabus#853]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Cuando intento entregar consulta siempre obtengo un json con el siguiente mensaje:
```{'message': "El valor de 'respuesta' debe ser una lista"}```
el problema es que la respuesta ya esta con tipo lista, no se si el error querrá decir que la lista esta errónea o no se.

Gracias.

**Comment by aaossa** [comment]
No estoy seguro de qué podría ser si efectivamente estás enviando algo de la forma:

```
{
    "respuesta": [...],
}
```

El chequeo que se hace es que el valor de respuesta sea una lista 🤔 ¿Podrías revisar si sigue ocurriendo? De ser así, sube a tu repositorio tu código y le doy una mirada. Gracias 🙌

**Comment by ctronp** [comment]
Gracias. Aun ocurre.
ya subi mi codigo, estoy usando el archivo ```test_2.py``` como un test de aceptacion, me arroja error al llamar a la funcion ```entregar_consulta```, en la linea ```18```.

**Comment by aaossa** [comment]
¿Podrías probar utilizando el método `requests.post` de esta manera?

```python
requests.post(URL, json=datos)  # Usando `json` en lugar de `data`
```

**Comment by ctronp** [comment]
me retorna el siguiente error:
```
requests.exceptions.MissingSchema: Invalid URL '8a955fcf83e5724b831ba6037e3be19a': No schema supplied. Perhaps you meant http://8a955fcf83e5724b831ba6037e3be19a?
```

**Comment by aaossa** [comment]
Entonces funcionó el cambio, ese error es algo de tu código más adelante.
Fíjate en (1) la variable que estás usando para hacer la solicitud y (2)
que la URL tenga el formato correcto.

**Comment by ctronp** [comment]
Gracias por la ayuda, ahorita lo pruebo y veo si funciona.

**Comment by ctronp** [comment]
Gracias ahora si funciona
