### ISSUE TITLE
Como des-seleccionar una Qcombobox?

### ISSUE THREAD

**Issue by Gsalinas1506** [IIC2233/syllabus#853]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Para la tarea ocupo dos `QComboBoxes` para seleccionar dificultad y canción del nivel. Me ocurre que cuando recién inicio la ventana principal, una de las cajas queda "seleccionada" (queda azul) hasta que realizo otra interacción con la interfaz (por ejemplo apretar un botón).
![image](https://user-images.githubusercontent.com/68198662/97318034-3291e200-184a-11eb-9c71-5081812248be.png)

Este hecho de que la QComboBox quede seleccionada hasta que haga otra cosa me dificulta para instaurar los cheatcodes de la tarea y en general otras interacciones con la interfaz, porque no puedo realizar otra interacción hasta esa Qcombobox se "des-seleccione" **¿Como se puede hacer?**

**Comment by knight-who-say-ni** [comment]
Hola @Gsalinas1506 !!

Ese problema se arregla facilmente con el método `QComboBox.setFocusPolicy(False)` 😄 .

Exito en la tarea!!
