### ISSUE TITLE
sprites mapa

### ISSUE THREAD

**Issue by mariovaldesa** [IIC2233/syllabus#853]
hola!, se puede poner la foto del mapa o hay que ir creándolo con sprites independientes? (me refiero ir agregando los cuadrados del suelo por ejemplo)

**Comment by Camila-sty** [comment]
hola!
No soy ayudante, pero por lo que he entendido puede llegar y poner la foto del mapa..

**Comment by mariovaldesa** [comment]
Gracias, y para qué sirven los Sprites del piso entonces? Yo ya los puse dentro de una grilla... está bien? O se tiene que poner la foto?

**Comment by Camila-sty** [comment]
@mariovaldesa tu puedes hacer lo que quieras con las sprites, mientras cumplas con lo que te piden. Yo creo que está bien!

**Comment by tomasgv** [comment]
Hola!!
Efectivamente, es como menciona @Camila-sty :tada:

Tienen tres opciones distintas, entre las cuales usar solo _sprites_ del piso es válido. Hay más información respecto a esto en [este pdf](https://github.com/IIC2233/syllabus/blob/master/Tareas/T02/Ejemplo%20fromas%20de%20cargar%20el%20mapa.pdf).

Saludos!! ☕
