### ISSUE TITLE
¿Cuenta el puntaje de flechas de pasos combinados si se presionan en momentos distintos? 

### ISSUE THREAD

**Issue by Sofia-Arratia** [IIC2233/syllabus#854]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! 
En issues anteriores he leido y comprendido que un paso combinado no se cuenta correcto si se presionan las teclas correspondientes en distintos momentos, y esto afectaría en la aprobación, sin embargo no me queda claro si el puntaje asociado a la captura de estas flechas como individuales también es anulado o si se considera en el puntaje final independientemente de haber fallado el paso en si.
Muchas gracias! ☺️

**Comment by danckoo1** [comment]
hola 👋  creo que a lo que te refieres es al ejemplo (d) de la sección 5.2 del enunciado,  de ser así, como el paso de baile se considera incorrecto, no se le debería asignar puntaje al jugador, saludos!

**Comment by enriquemolinare** [comment]
Con respecto, el enunciado dice "Cada flecha acertada le dará puntos al jugador" Una flecha acertada es cuando la zona de captura es presionada y la flecha se encuentra ahi. Independiente si corresponde a un paso o no. Incluso en el ejemplo 2 dice que el paso es incorrecto pero que la flecha si fue acertada. "5d) Paso incorrecto: se acierta a solo una de las flechas del paso"

**Comment by danckoo1** [comment]
Hola tienes razón! Efectivamente en el enunciado dijimos eso, en ese caso pueden dar puntaje por las flechas apretadas pese a que el paso sea incorrecto, tambien para que no haya confusiones no olviden señalarlo en su readme 👌

**Comment by Sofia-Arratia** [comment]
Aaaah perfecto. Mi duda iba a lo que mencionaba @enriquemolinare, pero con la última respuesta me quedó claro. Muchas gracias!
