### ISSUE TITLE
agrandar ventana

### ISSUE THREAD

**Issue by mariovaldesa** [IIC2233/syllabus#854]
hola!, cuando agrando mi ventana se deberia agrandar el mapa tambien? si es asi como se hace en qdesigner? ya que mi mapa esta en un layout pero cuando agrando la ventana no se me agranda el mapa.

**Comment by Christian-Klempau** [comment]
Encontré que en otro issue un ayudante respondió que quedaba a nuestro criterio:
Issue https://github.com/IIC2233/syllabus/issues/797

**Comment by mariovaldesa** [comment]
Gracias

**Comment by Christian-Klempau** [comment]
De nada!
