### ISSUE TITLE
Cambiar una recorrección

### ISSUE THREAD

**Issue by antoniacobo** [IIC2233/Syllabus#854]
Hola! Mande a recorregir mi T05 antes de que subieran el comentario general de la tarea (supe después de mandar la recorrección que faltaba el comentario general). Ahora leí el comentario general y quiero cambiar mi formulario de recorrección. ¿Tengo que mandar otro?

Gracias!

**Comment by Hernan4444** [comment]
@antoniacobo si, tienes que mandar otro.
