### ISSUE TITLE
Buscar hasta el primer \n

### ISSUE THREAD

**Issue by v4rgas** [IIC2233/syllabus#854]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Como hago para buscar hasta el primer \n?

Tomando como texto:
```
1. Perro Perro
2. Gato
3. Empanada
```
Al hacer  ```'1. !var{.+}\n'```, me da todas las combinaciones que cumplen con esto como:
```
['1. Perro Perro', '1. Perro Perro\n2. Gato' ... ]
```
Quizas necesitaria una forma de hacer algo como ```'1. !var{[a-zA-z ]}\n'```
significando todas las letras de la a-z más espacios

**Comment by v4rgas** [comment]
(\w| ) funcona en este caso!

**Comment by nicovsj** [comment]
Hola @v4rgas,

Otra alternativa es usar una _charclass negada_. Por ejemplo `[^\n]` hace _match_ con cualquier cáracter que NO sea un salto de línea. La sintáxis es `[^{rangos de caracteres}]` (e.g. `[^a-etv9]` hace match con caracteres que no sean `abcdetv9`). 

El ejemplo que pusiste `(\w| )` hace _match_ con cualquier caracter alfanúmerico o un espacio, por lo que si te topas con otro tipo de caracteres (e.g. `.,;/&%$`) no se hará _match_.

Espero que se entienda, saludos!
