### ISSUE TITLE
¿Qué debe retornar la consulta cuando existe más de 1 match?

### ISSUE THREAD

**Issue by jamigone** [IIC2233/syllabus#855]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Tengo una duda, quizás para confirmar porque el enunciado no me deja 100% seguro: ¿la lista a retornar **debiese tener tantos elementos (tipo _dict_) como match encuentre**, donde cada _dict_ tiene las keys: contenido y posición?

**Comment by aaossa** [comment]
> Hola! Tengo una duda, quizás para confirmar porque el enunciado no me deja 100% seguro: ¿la lista a retornar debiese tener tantos elementos (tipo dict) como match encuentre, donde cada dict tiene las keys: contenido y posición?

Es justo eso 👌 Sería algo de la forma:

```python
respuesta = [
    {"contenido": ..., "posicion": ...},
    {"contenido": ..., "posicion": ...},
    {"contenido": ..., "posicion": ...},
]
```

**Comment by jamigone** [comment]
Genial! Tengo otra duda sobre lo mismo jajaja, en particular en la consulta 1: se pide **obtener "el título" del documento**. ¿Se puede asumir que será solo 1 como el del ejemplo?

**Comment by aaossa** [comment]
Nop, podrían haber más y podría estar en más líneas además de la primera

**Comment by jamigone** [comment]
Okis, gracias 🎈😃

**Comment by Giolguin** [comment]
Hola! No me sigue quedando muy claro si para el caso de obtener los títulos y los subtítulos/subsubtítulos, ¿Podemos asumir que será un string para el título, y dos strings para los subtítulos?

**Comment by aaossa** [comment]
> 
> 
> Hola! No me sigue quedando muy claro si para el caso de obtener los títulos y los subtítulos/subsubtítulos, ¿Podemos asumir que será un string para el título, y dos strings para los subtítulos?

A qué te refieres con uno y dos *strings*? A la cantidad de palabras? Si es eso, no pueden asumirlo, pueden tener cualquier cantidad de palabras
