### ISSUE TITLE
Sprites en Bonus Multijugador

### ISSUE THREAD

**Issue by cnsfeir** [IIC2233/syllabus#855]
Hola!
Tengo una duda con el bonus de multijugador:
Cuando el mesero recoge un platillo ya preparado, ¿se espera que los meseros lleven platillos o se supone que carguen el icono de algún bocadillo al azar?
Me surge la duda, porque para el caso de la mesera (jugador N° 2), ¿cómo puedo saber cuando lleva un platillo? A diferencia mesero (jugador N°1) donde tengo dos tipos de sprites distintos: con y sin platillo, para la mesera solamente tengo el sprite de ella  caminando.

Muchas gracias!

**Comment by furcelay** [comment]
Hola!
Me encontré con el mismo problema. En `sprites/otros` hay una imagen de un plato, una idea es crear un nuevo sprite pegándoselo a los sprites de la mesera o cambiar el color del jugador 1. No queda muy bien pero soluciona el problema.

Saludos!!

**Comment by lewebe** [comment]
@furcelay Hola! Cómo pegas sprites entre sí? 🤔

**Comment by furcelay** [comment]
Puedes simplemente usar un editor de imágenes como gimp, creo que es más simple que poner el plato en otro label e intentar calzarlos

**Comment by tomasgv** [comment]
Hola!!
Como dice @furcelay, tienes esas dos opciones para implementar la visualización de llevar un bocadillo. No es necesario que se muestre un bocadillo aleatorio, sino que basta con mostrar un cambio de estado, como los _sprites_ llevando el platillo. 

Puede ser que demores más tiempo usando un editor de imágenes, pero depende de qué tan detallados hagas los _sprites_ (~nosotros nos demoramos bastante~ 🙈 ).

Saludos! ☕
