### ISSUE TITLE
Ayuda con drag and drop en mi computador 

### ISSUE THREAD

**Issue by diego-ayala-2000** [IIC2233/syllabus#855]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola. Llevo demasiadas horas tratando de implementar el drag and drop en la tarea, y durante este tiempo he corrido varios codigos de internet, casi ninguno me funcionaba y recién ahora se me ocurrió preguntarle a un amigo si a el le funcionaban en su compu, y a el le funcionan perfecto. A que se puede deber, porfavor ayuda he perdido demasiado tiempo tratando de implementar esto. Tengo un codigo de drag and drop escrito para la tarea que supongo que no funciona por eso, porque lo he revisado 100 veces en busca de errores

**Comment by JuaniAndres** [comment]
Hola @diego-ayala-2000 
Lograste resolver el problema que tenias?

**Comment by diego-ayala-2000** [comment]
Al parecer si, gracias por la preocupación
