### ISSUE TITLE
Eliminar QObjects

### ISSUE THREAD

**Issue by Francisco5674** [IIC2233/syllabus#856]
¡Hola!
He buscado por todas partes como eliminar un QObject de la interfaz visual, ya que necesito borrar QLabels y QRects cuando es necesario eliminar una mesa o mesón en la pre-ronda, ¿hay alguna forma de eliminar para siempre esas entidades?

**Comment by furcelay** [comment]
Hola! ya respondieron eso en otra issue (https://github.com/IIC2233/syllabus/issues/832), en resumen no puedes eliminarla pero sí ocultarla visualmente con `objeto.hide()`.

**Comment by Francisco5674** [comment]
Muchas gracias!

**Comment by fdoflorenzano** [comment]
¡Gracias @furcelay!
