### ISSUE TITLE
Probabilidad de aparicion de flechas en cada pista

### ISSUE THREAD

**Issue by chineseJack564** [IIC2233/syllabus#856]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola,
He estado leyendo el enunciado, solo sale que la aparicion entre paso normal y paso combinado es random, pero no dice nada respescto sobre la aparicion de flecha en las 4 pistas distintas, como se espera modelar la aparicion de flecha en cada pista?
Por ejemplo, si aparece flecha cada 1 sec, al pasar 1 sec, es 1 flecha en cualquera de las 4 pista?

**Comment by knight-who-say-ni** [comment]
Hola @chineseJack564 !!

Efectivamente, la elección de que flecha (o que combinación de flechas) debe ser aleatoria.

Saludos y exito en tu tarea!!

**Comment by chineseJack564** [comment]
Hola, 
respecto a las flecha tengo otra consulta,
![image](https://user-images.githubusercontent.com/69604944/97334561-a7b9e300-185b-11eb-9121-a60d6fec0f5c.png)
en los ejemplos, no me quedo muy claro si uno no acierta una flecha, la flecha sigue adelante y puede acertarlo otra vez? O desaparece de una?
por ejemplo en la c me puede decir si los siguientes cosas pasan?:
1. desaparece la flecha en S
2. Puedo apretar otra vez en S y atraparlo
3, El combo se descontinua
4. La flecha correspondiente siguiente de W desaparece pq apreto W

Saludos!

**Comment by knight-who-say-ni** [comment]
@chineseJack564 Mejor haz esa consulta en otra issue, así puedes ayudar a alguien que tenga esa misma duda 😬
