### ISSUE TITLE
Sobre feedback tarea 5

### ISSUE THREAD

**Issue by jmwielandt** [IIC2233/Syllabus#856]
Hola, en el feedback me pusieron que no implementé al pj principal como thread/qthread/qtimer pero no sé qué haría como thread (o lo que sea) por su cuenta, porque para el movimiento tenía qtimers (1 por cada dirección), la interfaz ya tiene threads por dentro que revisando los inputs y mandan las señales y todo eso y al final no me queda nada por implementarle así.

Los enemigos es evidente, porque van en piloto automático pero el/los personajes controlado por el jugador no se me ocurre :(

**Comment by Arcoirisky** [comment]
Hola! Entiendo que puedas estar nervioso pero las issues no son para eso 😅 La recorreccion es el medio correcto para tu pregunta O:

**Comment by Arcoirisky** [comment]
Pero, no estás equivocado ouo
La idea de que fueran Thread O similares, eran porque debían estar atento a sus movimientos indicados por el jugador. Si lo resolviste como dices, no debería estar mal :D
