### ISSUE TITLE
Escribir código examen 

### ISSUE THREAD

**Issue by joaquineichholz** [IIC2233/Syllabus#857]
Hola, que cosas son recomendables programar a mano para estudiar para el examen?

**Comment by fringlesinthestreet** [comment]
Hola @joaquineichholz 

Te recomiendo realizar los exámenes de semestres pasados. Puedes encontrar los links a semestres pasados al final del [Syllabus](https://github.com/IIC2233/Syllabus).

**Comment by cjdelacuadra** [comment]
estuve viendo los examenes pasados y queria saber si la parte de escrita es necesariamente codigo o se puede decumentar nomas?

**Comment by jecastro1** [comment]
Hola a tod@s,

Daré un poco más de detalles respecto a lo que enfrentarán este viernes. Ustedes **tendrán** que escribir código, lo que se concentrará en dos preguntas del examen. 

Una de las preguntas es respecto a modelación con OOP, donde se les pedirá un diseño para solucionar un problema. Luego tendrán que escribir la declaración de clases y métodos de su diagrama. Eso incluye: 
- **Declarar las clases**, 
- **Colocar los `init`** con los atributos correspondientes
-  **Declarar los métodos** comentando qué son los parámetros y qué devuelve, pero sin implementarlos.

A modo de ejemplo, la parte de código de la pregunta de OOP podría lucir así:
```python
class A:
    def __init__(self, param_uno):
        self.param_uno = param_uno

    def metodo_uno(self, param_dos):
        # param_dos: corresponde a...
        # return: el resultado de multiplicar self.param_uno con param_dos
        
        # Devuelve la multiplicación entre self.param_uno y param_dos
        pass
```

Hay otra pregunta en donde esperamos que estén preparados para **implementar completamente** funciones. No se espera que recuerden de memoria los métodos ofrecidos por los paquetes internos de Python (e.g. `networking`, `threading`) ni librerías externas. Por ende, en este código no tendrán que usar nada que tenga que ser importado con la sentencia `import`.

Finalmente, algunos consejos para enfrentar la escritura de código:
- Vamos a pasar hojas cuadriculadas para estas dos preguntas. La idea es que puedan usar los cuadros para guiarse en la identación y quede un poco más ordenado.
- En cuanto a los algoritmos, es buena idea plantearse cómo funcionaría lo que quieren hacer en términos intuitivos.
- Si ven que su algoritmo les va quedando confuso, pueden escribir la idea que tuvieron para ayudar al corrector a entender su respuesta.
- Si no se acuerdan de algún método específico, siempre pueden poner un comentario de cuál era su intención y, al mismo tiempo, escribir el código con el nombre más probable de lo que querían hacer. Esto siempre va a ser mejor que no hacer nada, no se bloqueen.

En relación con las otras preguntas, van a ser principalmente conceptuales o de lectura de código.

Éxito en el estudio,
Jaime
