### ISSUE TITLE
diferencia en "extra" al comparar con resultado de procesamiento

### ISSUE THREAD

**Issue by cimoya2** [IIC2233/syllabus#857]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola! Resulta que al momento de probar mis respuestas a consultas sobre un documento, me di cuenta que en el caso del patrón 6 la comparación que recibo entre el resultado esperado y mi respuesta difiere en el largo, por ejemplo para el documento con identificador= 7 me entrega:
{'consulta': 6, 'documento': 7, 'estado': 'Listo', 'proceso': 'bdb754c656c20fb99cecc265756262fb', 'resultado': {'comparacion': [True, True], 'extra': {'largo': 'Respuesta tiene largo 2 (debería ser 9)'}}}
En la parte de largo mi respuesta entrega una lista con 2 diccionarios y según el resultado debería ser 9, pero al descargar el documento markdown y revisarlo, solo se ven 2 links, no 9 como indicaría el resultado, mi duda entonces hace referencia a que si **es posible que haya un error en la parte del largo que entrega el API?**

**Comment by aaossa** [comment]
Hola @cimoya2 , no hay un error de parte de la API, creo que estás asumiendo que en algo de la forma `[texto](referencia)` la referencia es una URL, pero viendo un documento Markdown este no siempre es el caso. Mira bien el documento, encontrarás que sí hay 9 apariciones del formato `[texto](referencia)`
