### ISSUE TITLE
Cómo importar de forma relativa en este caso

### ISSUE THREAD

**Issue by dedmu5** [IIC2233/syllabus#857]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Tengo el siguiente sistema de archivos:

T02
____main.py
____frontend
_________archivofront.py
____ backend
_________ archivoback.py

**Quiero importar una funcion contenida en T02/backend/archivoback.py desde T02/frontend/archivofront.py**. Ya leí las issues #706 y #837 pero no fueron concluyentes, ya que no era el mismo caso que el mío. Saludos!

**Comment by danckoo1** [comment]
una forma simple seria agregando al comienzo de `archivofront.py` lo siguiente:
```
import sys
import os
sys.path.insert(1, os.path.join(sys.path[0], '..', 'backend'))
```
avisame si te sirve!

**Comment by dedmu5** [comment]
> ```
> import sys
> import os
> sys.path.insert(1, os.path.join(sys.path[0], '..', 'backend'))
> import achivoback
> ```

¡Gracias por la pronta respuesta! Corrió al tiro. ¿Sabes si hacer esto cuenta como una mala práctica?
Saludos y gracias nuevamente

**Comment by danckoo1** [comment]
Existen formas que son mejores vistas, como el uso de imports relativos, etc. Pero dado que no son contenidos del curso esto no es considerado una mala práctica, aunque con lo que tendría ojo es que estás importando cosas de un backend a un front end, lo cual si está mal, ya que no respetarías su correcta separación, saludos!

**Comment by spplaza** [comment]
Hola tengo una duda personal, me sale el error ModuleNotFoundError: No module named 'flecha' cuando lo llamo desde otro archivo en la misma carpeta del frontend y ya no se que hacer. Estoy atenta a alguna respuesta. Por ahora solo veo poner la clase que quería modularizar en el mismo archivo donde trato de llamarlo.

**Comment by danckoo1** [comment]
@spplaza por casualidad  el archivo donde lo estás importando está en la misma carpeta que el main o está en algún sub directorio?

**Comment by spplaza** [comment]
Esta en la carpeta del frontend. En el main lo llamo como from frontend.clase_flecha import Flecha pero en el archivo dentro del frontend lo llamo como from clase_flecha import Flecha (que es la clase que quiero importar). Sin embargo, me dice que el modulo no existe. Antes no me funcionaba con los parametros porque me tiraba el mismo error (en la formativa AF03 importaban import parametros as p tanto en archivos de frontend como en el main y les funcionaba). La unica solucion en ese entonces fue copiar mi archivo parametros en T02 y despues en frontend para que me funcionara, pero ahora nada me sirve :c

**Comment by danckoo1** [comment]
Suponiendo que cuando ejecutas el código lo haces con el main, en el archivo del front cuando importes la otra clase igual hazlo con la notación de `from frontend.clase_flecha import Flecha` Y dime si funciona, sino haz un push a tu repositorio para poder ver mejor el error 🙌

**Comment by spplaza** [comment]
¡¡¡¡Si funciono!!!! Muchas gracias!
