### ISSUE TITLE
Error al importar haciendo pip3 install requests

### ISSUE THREAD

**Issue by ftgodoy** [IIC2233/syllabus#858]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Al momento de hacer pip3 install requests (y lo mismo con rematch) me tira una serie de errores dnde la ultima linea dice ImportError: cannot import name 'gen' from 'tornado' (unknown location), 
alguien me puede ayudar para poder partir la actividad? Gracias :)

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by aaossa** [comment]
¿Podrías probar instalando primero `tornado`? (`pip3 install tornado --upgrade`) Si eso no funciona, porfa indicame la versión de pip que estás usando (el *output* completo de `pip3 --version`)

**Comment by ftgodoy** [comment]
Al hacer pip3 --version me tira el mismo error.
![Captura de pantalla 2021-07-22 094711](https://user-images.githubusercontent.com/62154743/126673387-5fcfb010-66af-4fa8-9e0e-b203220115cf.png)

**Comment by ftgodoy** [comment]
Me sigue tirando el mismo error para cualquier cosa que haga con pip3.
![Captura de pantalla 2021-07-22 122011](https://user-images.githubusercontent.com/62154743/126673587-feb82524-b548-43ba-8742-5fecc02fae2d.png)

**Comment by lily416** [comment]
@ftgodoy, solo por si acaso y para estar seguros de que pip3 está funcionando con la versión de python correcta, ¿puedes ejecutar lo siguiente?

- `python3.7 -m pip install --upgrade pip`
- `python3.7 -m pip --version `
- `python3.7 -m pip install tornado --upgrade`

Avísanos si funciona y en caso de que vuelva a ocurrir un error, mándanos fotos de lo que aparece después de ejecutar cada consulta.

**Comment by ftgodoy** [comment]
Me dice esto 
![Captura de pantalla 2021-07-22 133919](https://user-images.githubusercontent.com/62154743/126684033-c3c47721-9b73-4ccc-a195-5378ce26e27e.png)

**Comment by ftgodoy** [comment]
y al hacer lo mismo sin el python3.7 -m me sale esto.
![Captura de pantalla 2021-07-22 134113](https://user-images.githubusercontent.com/62154743/126684248-dda8dfc3-31e8-46d5-829b-85a74792bcd9.png)

**Comment by lily416** [comment]
¿Qué te parece cuando cambias el `python3.7` por `python` o `py`? 

La última foto que mandaste ¿a cuál de los 3 comandos corresponde?

**Comment by ftgodoy** [comment]
Al hacer el cambio de python3.7 por python o py me sale el mismo ImportError.
La ultima foto corresponde a hacer pip install requests (tal como aparece en la primera linea)

**Comment by ftgodoy** [comment]
Por favor ayuda :( No puedo partir

**Comment by lily416** [comment]
@ftgodoy lo siento por la demora, estábamos hablando con los otros ayudantes para ver si encontrábamos alguna solución. Por ahora lo único que se nos ocurre es:

1. Desinstalar y volver a instalar python en tu computador. Si haces esto es importante que revises que no quede ninguna carpeta relacionada con las librerías instaladas, por lo que puede que sea necesario que las elimines a mano. 

2. Programar y ejecutar la actividad bonus en [Google Colaboratory o Colab](colab.research.google.com) (para simplificar). Colab, es un espacio de ejecución virtual, por lo que podrás instalar las librerías aunque presentes problemas para instalarlas de forma local. 

    Colab funciona al igual que un Jupyter Notebook, por lo que para instalar las librerías deberás hacer 
    ```
    !pip install pyrematch --upgrade
    !pip install requests --upgrade
    ```

    El único tema con Colab es que como es un ambiente virtual, por lo que se reiniciará cuando dejes de trabajar con él. ¿Qué significa esto? Cada vez que se reinicie el entorno de ejecución se borrarán los archivos que hayas subido y las librerías que hayas instalado, por lo que debes descargar los archivos si es que no quieres perderlos. 

   Finalmente, si llegas a utilizar Colab, debes tener ojo en la forma en que uses los archivos .py:
   - Si subes los archivos como un .py, para ejecutar los archivos deberás poner `!python nombre_archivo.py` en una celda y ejecutarla. 
   
        Para subir los archivos, debes seleccionar "archivos" (la carpeta que sale la izquierda) y después en "subir al almacenamiento de sesión": ![image](https://user-images.githubusercontent.com/26393515/126700038-5b7f5f07-7c21-43f6-9979-1a95398482af.png)

   - Si pones el contenido de los .py en las celdas, debes ejecutarlas como si fuera un jupyter notebook (con Ctrl + Enter o Shift + Enter). Pero ojo, que al momento de entregar la actividad debes seguir el formato indicado en el enunciado, por lo que deberás traspasar tus respuestas a los archivos .py entregados.


Esperamos que esto te permite realizar la actividad y cualquier cosa estamos atentos a tus dudas 👋
