### ISSUE TITLE
Mezclar herencia con metaclases

### ISSUE THREAD

**Issue by llloyola** [IIC2233/Syllabus#858]
Hola! Estudiando para el examen, decidí probar qué pasaría si intento hacer que una clase herede de más de una clase y que además tenga una metaclase personalizada. Leyendo un poco sobre el asunto, me quedó claro que es necesario que las superclases también tengan la misma metaclase que la que se quiere para la subclase (o eso entendí y estoy completamente equivocado jajajaj).

Sin embargo, no entiendo por qué me lanza este error:
![captura de pantalla 2018-07-04 a la s 00 22 41](https://user-images.githubusercontent.com/30671859/42256736-e72c2e7a-7f20-11e8-82b6-7868d24aa02d.png)

¿Quiere decir que la metaclase que le asigne a C debe ser una subclase de las metaclases en A y B? No estoy entendiendo 😢 

Luego, decidí probar eliminando la metaclase de la subclase C, pero me dice que C es _NoneType_, por lo que no es _callable_:
![captura de pantalla 2018-07-04 a la s 00 23 16](https://user-images.githubusercontent.com/30671859/42256738-ea206146-7f20-11e8-994c-18b22bb85a08.png)

¿Hay alguna forma de lograr lo que quiero? ¿Es posible juntar multiherencia y metaclases en una sola (sub)clase?

![potato](https://user-images.githubusercontent.com/30671859/42256970-49f05332-7f22-11e8-8795-ab8132cffcce.gif)

**Comment by fgbruna** [comment]
Hola @llloyola, lo primero que hiciste deberia funcionar si es que a `MiMeta` la haces heredar de `type`
Cuentame como te va!

**Comment by llloyola** [comment]
Oh! Pequeño detalle... Lo había olvidado por completo jajja

Mmm... Nop. Quedé en las mismas 😢 Me tira el mismo error del primer caso

**Comment by fgbruna** [comment]
@llloyola podrias mostrarme todo el codigo de lo que estás haciendo?

**Comment by llloyola** [comment]
La parte izquierda de la pantalla es todo el código, no hay nada más abajo.
¿Estoy omitiendo algo importante o fallando en algo muy obvio? jajja 😭

**Comment by fgbruna** [comment]
Recuerda que debes llamar al new de type si quieres que retorne tu clase!

**Comment by llloyola** [comment]
Oh! Toda la razón jajjaja No me di cuenta de que me faltaba el ```return super().__new__(meta, nombre, base_clases, diccionario)``` en el ```__new__``` de mi metaclase 😅 

Muchas gracias! Mejor que me pase ahora a que en el examen jajaja
