### ISSUE TITLE
Paso Incorrecto

### ISSUE THREAD

**Issue by enriquemolinare** [IIC2233/syllabus#858]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
TEngo una duda sobre una situacion de los pasos incorrecto que no fue mencionada. Por ejemplo si hay un paso normal en la casilla a y un paso combinado de 3 que corresponden a la casilla A, S, D. En el caso que el usuario presione A,S de forma simultaneo**¿El paso normal se considera correcto y el paso ASD se considera incorrecto?**
Una segunda pregunta, en la situacion que haya un paso combinado de 3 en A,S,W. El usuario  presiona solo S , desaparece la flecha S y se considera un paso incorrecto. Pasan unos microsegundos, y el usuario presiona W acertando a la flecha W del paso commbinado anterior. ***¿cuando presiona W  también se considera incorrecto?***
[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by aljara97** [comment]
Hola @enriquemolinare, con respecto a tu primera pregunta puedes apoyarte en lo que se preguntó en la issue #828 y hacer un supuesto sobre cómo manejar el hecho de que hayan dos flechas en una misma zona de captura a la vez. Con respecto a la segunda pregunta puedes suponer que no será necesario que se apreten al mismo tiempo, pero debes encargarte de verificar que se cumplen con las otras condiciones del enunciado.

**Comment by enriquemolinare** [comment]
No me queda claro la respuesta de la segunda pregunta, según el enunciado las flechas del paso combinada se deben presionar todas al mismo tiempo. Entonces una vez que desaparece una flecha del paso combinado como se debe contabilizar como incorrecto el paso una vez que se capturen las otras restantes?

**Comment by aljara97** [comment]
A lo que se refiere el enunciado es que para un paso combinado las flechas caerán al mismo tiempo, lo que te quiero decir es que no es necesario que presiones todas las flechas de ese paso. Para manejar un correcto acierto de este paso, una vez que aciertes una de las flechas podrías hacer que el programa espere a que el usuario presione la o las otras flechas restantes siguiendo la lógica de un paso correcto

**Comment by Zenos-Paradox** [comment]
respecto a esto; en el enunciado dice que cada **flecha** acertada da puntos. Si fallas el resto del paso recibes los puntos de las flechas que sí acertaste?

**Comment by enriquemolinare** [comment]
> A lo que se refiere el enunciado es que para un paso combinado las flechas caerán al mismo tiempo, lo que te quiero decir es que no es necesario que presiones todas las flechas de ese paso. Para manejar un correcto acierto de este paso, una vez que aciertes una de las flechas podrías hacer que el programa espere a que el usuario presione la o las otras flechas restantes siguiendo la lógica de un

**Comment by enriquemolinare** [comment]
perfecto. Entonces por ejemplo si un paso combinado de tres flechas, solo se captura una. Dicho paso se considera incorrecto. Luego quedan dos flechas restantes, entonces dicho paso pasaría a ser un paso combinado de dos flechas?. 
Lo mencionado anteriormente, sería un supuesto o es algo que se extrae del enunciado?

**Comment by aljara97** [comment]
No, el paso sería de tres flechas, solo deberías encargarte de que se capturen en el orden correspondiente, pero podría ser a destiempo o a la vez. Lo que mencionaste no sería un supuesto válido, ya que alterarías el funcionamiento del juego.

**Comment by aljara97** [comment]
Por favor no cierres la issue, puede servirle a otro compañer@
@Zenos-Paradox, por favor te pido que hagas esa pregunta en otra issue.

**Comment by fran-gl** [comment]
> No, el paso sería de tres flechas, solo deberías encargarte de que se capturen en el orden correspondiente, pero podría ser a destiempo o a la vez. Lo que mencionaste no sería un supuesto válido, ya que alterarías el funcionamiento del juego.

Entonces si se capturan todas las flechas de un paso combinado con un desfase de tiempo mínimo se puede considerar correcto el paso? O es considerado incorrecto?

**Comment by antoniaalcayaga** [comment]
Hola, me queda una duda con respecto a la respuesta de los pasos combinados. Esto quiere decir que el paso combinado solo se considerara dentro de los incorrectos si esta incompleto una vez que finalice de recorrer el sector donde se "atrapan" las flechas?, ya que por lo que entendí, si yo prieto una de las teclas pertenecientes al paso esta desaparece y luego aprieto la otra y completo el paso, este se consideraría un paso correcto o no? y las flechas apretadas por separado (dentro del paso combinado) no se considerarían pasos incorrectos o si?
Disculpa si soy repetitiva, pero no me queda claro:(

Gracias de antemano.

**Comment by aljara97** [comment]
Hola @antoniaalcayaga, exacto, puedes suponer que un paso se considerará correcto cuando termines de atrapar todas las flechas (sin que se escape ninguna). Solo debes preocuparte que no se presionen flechas extras a las del paso. Espero haber aclarado tu duda
