### ISSUE TITLE
Problemas con objeto que hereda de Qlabel y que aparece en otra ventana individual 

### ISSUE THREAD

**Issue by ignacioarteaga99** [IIC2233/syllabus#859]
Cree las clases DragLabel y DropLabel, ambos funcionan de buena manera, sin embargo, al instanciarlos en el __init__ de la clase MainWindow que es donde quiero que "actúen", los pinguinos sí se ven (y funciona el drag), pero para el drop se abre en otra ventana (que de hecho sí funciona porque puedo trasladar un pinguino a esa ventana). Me gustaría saber ¿por qué si es que lo instancio en el __init__  de MainWindow no se ve en ésta?

**Comment by JuaniAndres** [comment]
Hola @ignacioarteaga99 
Revise tu código es un detalle lo que te está dando problemas. Te falto entregarle el parent cuando llamas al ````init```` de la ````Qlabel```` dentro de tu clase ````DropLabel```` ósea deberías tener lo siguiente ````super().__init__(parent)````. Si no le entregas el padre (la ventana) a la Qlabel esta se abre una ventana distinta.
Me avisas si es que después de eso sigues con problemas
Éxito con la tarea 😄

**Comment by ignacioarteaga99** [comment]
Me funcionó! Muchas gracias! Te pasaste!

**Comment by JuaniAndres** [comment]
Qué bueno que te funciono, voy a dejar abierta la issues por si alguno de tus compañeros tiene el mismo problema. Nosotros después nos encargamos de cerrarla para que no te preocupes de ella.

**Comment by kalarconvl** [comment]
Hola!! Tengo una duda que está relacionada a esto pero no es igual. Me pasa que tengo tambien 2 clases: una Drag y otra Drop. El drag ya está funcionando pero en el drop me pasa que cuando suelto un pingüino el codigo si lo reconoce pero como que no aparece la imagen

**Comment by JuaniAndres** [comment]
Hola @kalarconvl 
Te parece si mejor abres una issues nueva con lo mismo que me mencionas solamente por un tema de orden y para que quede todo más dividido con un titulo distinto. Si puedes sube tu código a tu repositorio para poder revisarlo.

**Comment by kalarconvl** [comment]
Dale! Ya subí mi código, ahora abro una issue
