### ISSUE TITLE
Valores de posicion desplazados +1 unidad

### ISSUE THREAD

**Issue by NiceGuyWorz** [IIC2233/syllabus#859]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Viendo los resultados que arroja mi codigo, me doy cuenta que el primer resultado coincide con el enunciado pero los otros dos estas desplazados +1 (251 el correcto, el mio 252) etc
Mi duda es si existe algun error de enunciado o es mi codigo, estoy usando match.span tal como indica el material de estudio pero no entiendo lorque no coincide

![220115779_142775141226719_1496866722719075925_n](https://user-images.githubusercontent.com/80777014/126677282-e1a16eec-234c-4b13-a593-20dc1a908dd5.jpg)
![221080099_4068048549978466_1274388203562241569_n](https://user-images.githubusercontent.com/80777014/126677315-a2011bb2-a780-407c-9a80-b7ecba88f2e9.jpg)

De momento creo que esta todo completo pero no se me ocurre como solucionar ese detalle.

**Comment by aaossa** [comment]
Disculpa, lo mismo que #862 , te recomiendo continuar con otras consultas mientras. Le dimos una mirada con el team rematch y sospechamos que esto podría deberse a algún manejo raro de los espacios a nivel de OS (asumiendo que no realizaste ningún cambio o preprocesamiento). De todas formas, estoy casi seguro de que debería funcionar bien con los documentos que recibas desde la API (te recomiendo revisar de la misma forma: usar `str.find` y comparar con la posición que obtenga tu función). Si funciona bien ahí, seguramente era lo de los espacios. ¡Éxito con la actividad! 🙌
