### ISSUE TITLE
Duda sobre la exactitud de "grupo ya existente"

### ISSUE THREAD

**Issue by Rerro-r** [IIC2233/syllabus#86]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Tengo una duda con la parte 4.2.2 del enunciado en Crear Grupo. **Las instrucciones indican que se debe verificar que el nombre de grupo a crear no coincida con el nombre de un grupo ya existente. ¿Con grupo existente se refiere a todos los grupos que tiene el programa en el archivo `grupos.csv` o los grupos en donde el usuario es miembro?** 

Pregunto porque generalmente en los servicios de mensajería lo que importa es que el nombre de grupo no se repita con uno que ya tienes en tus chats. Perdón por hilar muy fino, pero me quedé con la duda 😊.

**Comment by RafaelEdwards** [comment]
Holaa, tu duda es muy válida!

Por la forma en que lo muestra el enunciado te recomiendo no repetir grupos que estén en "grupos.csv". De todas formas, cuando tengas este tipo de dudas en que el enunciado podría interpretarse de dos maneras parecidas y que no generan un cambio importante en el flujo del programa, te recomiendo hacerlo como te parezca más lógico y especificarlo en tu README.

Espero haberte ayudado y suerte con tu tarea :).
