### ISSUE TITLE
Duda bebestibles

### ISSUE THREAD

**Issue by Ilancf** [IIC2233/Syllabus#86]
* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Una duda con respecto a la carta de bebestible, si el jugador quiere tomar un bebestible, las acciones de descontar dinero y aplicar los efectos del bebestible, se tienen que reescribir en el "bebestibles.csv" o la clase bebestible debe debe hacer las respectivas modificaciones sin akterar el archivo "bebestibles.csv" original?

**Comment by MaxAl100** [comment]
[Soy estudiante]

Según el issue 80 (https://github.com/IIC2233/Syllabus/issues/80) no hay que cambiar información en el archivo "jugadores.csv", por lo que supongo que tampoco hay que hacerlo en ningún otro archivo. 

Hasta que responda un ayudante yo seguiría con esto en mente, pero es lo que me hace más sentido a mí.

**Comment by Gsalinas1506** [comment]
Hola! Efectivamente como dice @MaxAl100, **los archivos .csv que les entregamos no deben modificarse** ya que funcionan como información base de la cual el juego se alimenta. La idea es que con bebestibles.csv construyas los bebestibles para que el jugador sea capaz de consumirlo, pero esto no implica que el archivo de base deba ser sobreescrito.

Exito con la tarea! 🎲️🃏️
