### ISSUE TITLE
Archivo de acciones es consistente

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2233/syllabus#86]
Hola, el archivo de acciones es consistente? Es decir, si la CPU ejecuta una acción de ese archivo, no deberían haber errores de que no hay suficientes trabajadores disponibles para ejecutarla, por ejemplo?

Saludos

**Comment by lily416** [comment]
Hola :smile: 

No puedes asumir que el archivo de las acciones es consistente, así que al momento de que la CPU ejecute una acción debes comprobar que sea válida, en el caso de que no lo sea, la civilización no realizará ninguna acción es ese turno.

Saludos y éxito con la tarea :wave: 🏰

**Comment by fjhuanca** [comment]
Y el archivo de acciones_pendientes.csv si se puede asumir consistencia o no?

**Comment by lily416** [comment]
Sí, ya que son acciones que ya se están realizando. 
Además, como son archivos que ustedes tienen que escribir, se espera que la información que contenga sea correcta con respecto al estado de las distintas civilizaciones (los edificios que estén construyendo cuando se guarde el estado del juego).

Saludos :wave:

**Comment by jmwielandt** [comment]
Dado que en archivo `acciones_pendientes.csv` están las acciones **iniciadas** en un turno anterior, pero sus efectos (e.g. incorporación de una nueva unidad de soldado) no tienen lugar, los costos ya fueron pagados, por lo que **no** debes validarlos de nuevo (si tienes 1000 de piedra y gastas 800 en construir un muro, cuando ya lo termines no necesitas 800 de piedra en tus almacenes).

**Comment by fjhuanca** [comment]
Ok, muchas gracias a ambos
