### ISSUE TITLE
Subir Solución Ayudantía

### ISSUE THREAD

**Issue by maromero-21** [IIC2233/Syllabus#86]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.

Hola profesores y ayudantes!
Quería saber si existe la posibilidad de que suban el desarrollo de la Ayudantía 1 por favor o si es que alguien del curso la tiene que me la pueda compartir!

Muchas gracias!

**Comment by JulianC1111** [comment]
Segun entendí por alguna razon se había decidido que no la iban a subir cuando le pregunté a la ayudante.

**Comment by fvidalf** [comment]
Holaa @maromero-21 y @JulianC1111!

Por esta ocasión subimos la solución a la AY1, la cual está disponible ahora para que la revisen en el Syllabus. Los profes van a evaluar si será ese el caso para el resto de las ayudantías.

Saludos! ✌🏽
