### ISSUE TITLE
atributos en diagrama de clases

### ISSUE THREAD

**Issue by mjgutierrez1** [IIC2233/Syllabus#86]
En un diagrama de clases, en la parte de los atributos de una clase, ¿se ponen los atributos de  clase y objeto o sólo uno de esos (es decir, los que salen antes y después del __init__, o sólo uno de esos)?

**Comment by andresfdezc** [comment]
En diagrama de clases, los atributos de clases y de instancia se escriben en la división de al medio. Para indicar que un atributo o método es de clase puedes subrayar su nombre.

![main](https://user-images.githubusercontent.com/11430184/29439989-e87b4066-8397-11e7-8ac7-05d9906207e0.png)
