### ISSUE TITLE
El limite de caracteres por linea es 100 o 79?

### ISSUE THREAD

**Issue by sofiuni** [IIC2233/syllabus#86]
Hay que seguir PEP8 o la guia de estilos?

**Comment by MatiasDuhalde** [comment]
Hola!

_Supondré que en tu pregunta te refieres al número de caracteres por línea, el máximo de líneas por archivo en el curso es 400_

PEP 8 recomienda limitar los caracteres por línea a 79, sin embargo, esta restricción no hace mucho sentido en un contexto moderno, ahora las pantallas tienen mayor resolución y los editores que imponían este límite están obsoletos (ten en cuenta que PEP 8 fue escrito en 2001). Es por esto, que en esto curso flexibilizamos este punto y aumentamos el límite a 100.

**Por lo tanto, si te pasas de 79 caracteres, no tendrás problemas en tu puntaje, pero si te pasas de 100 recibirás un descuento de acuerdo a [este documento](https://github.com/IIC2233/syllabus/blob/master/Tareas/Descuentos.md).**

Si deseas auto-imponerte el límite de 79 caracteres (como lo recomienda PEP 8) eres libre de hacerlo.

Éxito en tu tarea!

**Comment by Drpinto1** [comment]
¡Hola!

Me gustaría complementar un poco la respuesta de Matías. 

En estricto rigor estamos siguiendo PEP8, pues en la sección de [máximo de caracteres por línea](https://www.python.org/dev/peps/pep-0008/#maximum-line-length), se especifica que si un equipo de trabajo completo está de acuerdo (en este caso el cuerpo docente de IIC2233), es posible extender el máximo de caracteres a 99, siempre y cuando se mantengan los comentarios y _docstrings_ en un máximo de 72.

¡Saludos!

**Comment by sofiuni** [comment]
Gracias! Si, me referia al limite de caracteres por linea. Veo que seguire el de 100.
