### ISSUE TITLE
Duda con salir

### ISSUE THREAD

**Issue by dianafuentesc** [IIC2233/syllabus#86]
En la pauta sale que hay que salir de forma correcta... a que se refiere esto?
Hay una forma incorrecta de salir?
Saludos!

**Comment by jmwielandt** [comment]
Hola!

Lo unico que puede terminar la ejecucion del programa es que la persona ponga voluntariamente "SALIR", o que gane o pierda la partida. Si el programa para por cualquier otro motivo, no esta saliendo correctamente.

Saludos~
