### ISSUE TITLE
Parámetros, máximo y mínimo caracteres

### ISSUE THREAD

**Issue by J0SEF4** [IIC2233/Syllabus#86]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Cuando verifico que el nuevo nombre de usuario no se exceda del máximo de caracteres o no cumple con el mínimo de caracteres. En este caso puedo hacer un if con ambas condiciones y mandar un comentario para ambos como por ejemplo: 
"No cumple con las condiciones de un nombre de usuario, pues no cumple con el mínimo o se excede del máximo de caracteres permitido. Será devuelto al Menú de Inicio". O debo para ambos casos hacer un if para cada uno con su respectivo comentario.

**Comment by Maxy15** [comment]
Hola! Queda a tu criterio si definir un comentario general o varios dependiendo del caso, lo importante es que le digas al usuario en la consola que hay un error. Espero te sirva! 😸

**Comment by J0SEF4** [comment]
Si! Muchas gracias!
