### ISSUE TITLE
Viaje en el tiempo

### ISSUE THREAD

**Issue by maxjosecr** [IIC2233/Syllabus#86]
Tengo unas dudas con el ingreso de una fecha distinta cada vez.

Por ejemplo, yo ingreso el 22 de marzo, hay un numero de incendios activos con sus puntos de poder, envío recursos para que un **incendio A** se apague completamente el 24 de marzo, actualizo y guardo los cambios en mi base de datos. Luego ingreso el 25 de marzo, y el incendio A tiene 0 puntos de poder, ejecuto, ocupo el programa, y guardo los cambios.
El enunciado dice **"cualquier cambio realizado durante la ejecución del programa deberá persistir en una próxima ejecución de éste. Lo anterior implica que deben actualizar las bases de datos(...)"**
, pero, si guardo la actualización del 25 de marzo, la próxima vez que ingrese estará cambiada la base de datos, y si por ejemplo, vuelvo a entrar el 22 de marzo, ese mismo incendio A estaría apagado.

¿Hay que hacer alguna suposición o hay algo que se me está pasando?
La única solución que se me ocurre sería agregando una columna más a la base de datos, se puede hacer esto?

Gracias

**Comment by hanavarrete** [comment]
Esto se respondió (y sigue) en la issue #72, saludos!

**Comment by maxjosecr** [comment]
La pregunta es parecida, pero la duda es distinta, se puede agregar una columna al .csv?

**Comment by FernandoPieressa** [comment]
@maxjosecr No puedes agregarle columnas al .csv, sin embargo tu puedes crear extra archivos que genere tu programa para guardar informacion adicional a la que nosotros entregamos.

Eso si es importante que tu programa cree esos archivos extra si no estan porque no puedes pedir en readme que creen un archivo extra para que tu programa funcione.

Saludos!
