### ISSUE TITLE
Flechas se van trancando

### ISSUE THREAD

**Issue by cristobal-larach** [IIC2233/syllabus#860]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, al comenzar a lanzar flechas, mi programa a veces funciona fluido, y de a poco se va quedando pegado. A veces termina cayéndose, con el siguiente error en Terminal: "malloc: *** error for object 0x7f8dfe162f10: pointer being freed was not allocated"

Hay veces en que se cae por lo mismo y lanza otro error: "zsh: segmentation fault /usr/local/bin/python3"

¿Alguna forma de solucionarlo? Dudo que sea por colapso de la RAM, ya que voy borrando los hilos de las flechas cuando llegan al fondo..

**Comment by aaossa** [comment]
Hola @cristobal-larach , creo que lo que está ocurriendo es que estás creando elementos gráficos pero no los almacenas en una estructura de Python. Por ejemplo, vas creando nuevos `QLabel`s dentro de una función, entonces al terminar de ejecutarse la función el objeto deja de existir... para Python, ya que para Qt sigue existiendo el elemento gráfico. Revisa si es que tus elementos gráficos quedan almacenados en una estructura (como parte de una lista) y dentro de un atributo en alguna clase 🤔 Ojalá sea eso, pero si no tienes algo así, avisa por acá mismo y vamos viendo más opciones ✨ ¡Éxito con tu tarea! 💪

**Comment by cristobal-larach** [comment]
No no, voy guardando cada flecha en una lista como atributo de la ventana apenas se crea, por lo que si podria acceder a ellas desde python... hay veces que funciona bien, y veces que se cae

**Comment by aaossa** [comment]
Y cuando las eliminas, ¿cómo lo vas haciendo?

**Comment by cristobal-larach** [comment]
.hide()
luego, cuando el nivel termina, re-defino la lista donde las iba almacenando como vacía

**Comment by aaossa** [comment]
¿Y el error ocurre antes de que termines un nivel por primera vez? Si no ocurre, entonces es posible que se algo en el proceso de eliminación. En tal caso, prueba iterando sobre la lista, utilizando el método `deleteLater()` sobre cada *wdiget* y luego declarando la lista como vacía 🤔

**Comment by cristobal-larach** [comment]
El error ocurre antes de que se complete por primera vez, a veces..

**Comment by cristobal-larach** [comment]
Al correr el codigo siempre me lanza un error "QEventLoop: Cannot be used without QApplication" en terminal, pero me viene pasando desde el inicio de la tarea y no parece influir en nada.. tiene algo que ver?

**Comment by cristobal-larach** [comment]
Ahi arreglé lo de QEventLoop, pero el programa se me  sigue pegando y cayendo aleatoriamente con el error zsh: segmentation fault  /usr/local/bin/python3

**Comment by aaossa** [comment]
Mmm ¿podrías subirlo a tu repo y decirme qué debo ejecutar? Le daré una mirada para ver qué puede ser, pero no podré responder pronto (pero sí hoy 😅 )

**Comment by cristobal-larach** [comment]
oka, debes ejecutar main.py. Muchas gracias

**Comment by cristobal-larach** [comment]
Hola Antonio! Encontraste algo raro?

**Comment by aaossa** [comment]
Hola @cristobal-larach , así es, dos cositas: 

* Para mover los *labels* de la ventana principal, debes hacerlo mediante señales, de forma que el *thread* principal sea el que haga el movimiento. En tu implementación, cada `QThread` está moviendo su propio *label*, por lo que "chocan" entre sí para actualizar la interfaz.
* Por otra parte, te recomiendo implementar otra señal (aparte de la del primer punto) para quitar las flechas una vez que el `QThread` termina de ejecutarse, ya que tu lista de flechas solo crece. Puedes comprobar esto imprimiendo el largo de `self.flechas` en tu método `crear_flecha`, y verás que solo crece, incluso cuando se ocultan flechas.

**Comment by cristobal-larach** [comment]
Extraordinario, era lo primero!

**Comment by cristobal-larach** [comment]
Hola Antonio, perdón por molestar. Cuando subí el código para que me ayudes
con mi problema, hice un push donde incluí la carpeta de sprites,
canciones, etc. (Archivos que no debían incluirse en el push final). Al
entregar la tarea, hice bien el ".gitignore" y no incluí ninguno de estos
archivos innecesarios, sin embargo no borré de mi repositorio los
innecesarios que te había subido en un principio. ¿Hay algún tipo de
descuento por eso? ¿Con el ".gitignore" fue suficiente? De antemano, muchas
gracias por tu ayuda!

Cristóbal
