### ISSUE TITLE
colisión multiple

### ISSUE THREAD

**Issue by Aloncarrasco** [IIC2233/syllabus#860]
que pasa si el mesero choca con 2 mesas a la vez? o si choca con una mesa y un chef a la vez?

**Comment by Christian-Klempau** [comment]
Has considerado usar on lock para los threads en ese caso?

**Comment by jitorcas** [comment]
Hola @Aloncarrasco!

Espero hayas podido solucionar el problema. Sin embargo, no veo en qué momento el chef colisionará con dos entidades al mismo tiempo, podría ser un caso muy particular que podrías modelarlo a tu criterio pero **debes** especificarlo en el **readme**. 

Éxito en la tarea! 💯
