### ISSUE TITLE
Consulta 3, duda formato insertar imagen

### ISSUE THREAD

**Issue by jamigone** [IIC2233/syllabus#860]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Tengo una duda relacionada al formato de la imagen para implementar la consulta 3: ¿se puede asumir que lo subrayado en la foto adjunta se mantiene constante o lo único genérico son los tags <>?

![imagen](https://user-images.githubusercontent.com/50121013/126681527-a78269f5-2143-4774-ad86-9fd58d26c92e.png)

**Comment by aaossa** [comment]
Sipis 👌 Puedes asumir que eso estará ahí

**Comment by luzmagurzua** [comment]
el https: tambien?

**Comment by aaossa** [comment]
Mmm no deberían necesitarlo para hacer el match 🤔 Creo que es más seguro que no lo consideres

**Comment by luzmagurzua** [comment]
ok gracias !!
