### ISSUE TITLE
Consulta 4, ¿se consultan ambos tipos de código?

### ISSUE THREAD

**Issue by jamigone** [IIC2233/syllabus#861]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Holaa, leyendo el enunciado no me queda claro si debemos implementar la consulta 4 para que verifique solo aquellos códigos que se presentan en bloque independiente (```), o también aquellos que están dentro de un bloque de texto (`).

De ser ambos, si hay código dentro de un bloque de texto ¿el valor de la key "contenido" será el código mismo? ya que me parece que no se puede especificar su lenguaje en este caso.

Quizás suene enredado, espero que se entienda 😅😅

**Comment by aaossa** [comment]
¡Hola! Lo siento, debería haberlo escrito más claro quizás 😅 Solo se consideran los bloques de código (los que tienen los 3 *backticks*), los que van dentro de un texto NO se consideran (tampoco tienen un lenguaje para capturar) 👌

**Comment by jamigone** [comment]
Súper! gracias profe

**Comment by luzmagurzua** [comment]
hola! :) 
para esta consulta, entonces sólo tenemos que entregar el nombre del lenguaje que aparece en el código, y lo demás no? (pero sí considerar todo lo que hay en el bloque para entregar las posiciones?)

**Comment by aaossa** [comment]
> para esta consulta, entonces sólo tenemos que entregar el nombre del lenguaje que aparece en el código, y lo demás no? (pero sí considerar todo lo que hay en el bloque para entregar las posiciones?)

Sipis, el texto tiene que ser el lenguaje, pero la posición es la del contenido del bloque (el código)

**Comment by luzmagurzua** [comment]
graciassss
