### ISSUE TITLE
Como reaccionar sobre distintos situaciones de captura de flecha

### ISSUE THREAD

**Issue by chineseJack564** [IIC2233/syllabus#861]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, leyendo el enunciado no me queda muy claro como quedan las flechas en momento de no asertar una flecha, usando el ejemplo del enuncia:
![image](https://user-images.githubusercontent.com/69604944/97349305-143ddd80-186e-11eb-819f-7383f4fd2fc7.png)
En este caso, los siguientes eventos pasa ? 
1. La flecha en S queda inhabilitado? O se puede ser recapturado? O desaparece?
2. La flecha que viene en seguida de W quedaria inhablitado? O no le debe afectar?
3. el combo actual se resetea? O mantenga hasta que la flecha pasa de largo y luego se resetea?

![image](https://user-images.githubusercontent.com/69604944/97349689-8a424480-186e-11eb-8b7d-6272c2f42e9f.png)
En este caso, que pasa con los siguientes eventos:
1. La flecha en D queda deshabilitado? O puede ser re capturado?

![image](https://user-images.githubusercontent.com/69604944/97350039-ffae1500-186e-11eb-81cb-540318e8a977.png)
En este caso, que pasa con los siguientes eventos:
1.La flecha que viene en S puede ser recapturado?
2. El combo actual se termina?

Saludos!!

**Comment by enriquemolinare** [comment]
En el caso D ( La segunda Imagen): Posteriormente de capturar W,si se  captura la flecha que se encuentre D, ¿El paso se considera correcto o incorrecto o neutro?

**Comment by JuaniAndres** [comment]
hola @chineseJack564 y @enriquemolinare 
Partiendo por orden:
En el caso C se realizó un paso incorrecto ya que no había flecha dentro de la zona de W por lo que el combo se reinicia. La flecha que viene después en W sigue siendo válida cuando llegue a la zona correspondiente y la flecha que está en la zona de S se puede capturar correctamente mientras este dentro de la zona por lo que no tiene que desaparecer o inhabilitarse por el error cometido.
En el caso D siguiendo lo que se menciona en la issues #858 pueden suponer que existe un margen de tiempo para apretar todas las flechas antes de considerar el paso combinado como incorrecto por lo que siguiendo el caso del ejemplo la flecha D podría ser capturada y considerar el paso como correcto. Igual les recomendaría mencionar si consideraron un margen de tiempo y cuanto fue en su readme solamente para que el corrector sepa.
En el caso F como se cometió un error se le reinicia el combo, pero todas las flechas que están fuera de la zona de captura se pueden capturar correctamente cuando entren a la zona.
Espero haberles dejado todos los casos más claros, me avisan si les surgen nuevas dudas.
Éxito programando 😄
