### ISSUE TITLE
Movimiento y colisiones en mapa cuadriculado.

### ISSUE THREAD

**Issue by Aloncarrasco** [IIC2233/syllabus#861]
que pasa si el movimiento no es continuo?
(en mi caso hice casillas pequeñas de 15x15 y todo funciona en base a eso)
por ejemplo, no puedo colocar un mueble en (65, 155) si no que en (60, 150) porque es una casilla valida en 15 x 15. La interfaz no es tan continua (el movimiento si se ve continuo), pero permite un mejor orden visual del posicionamiento de las cosas. 

En relación a esto, importa si el mesero se superpone con los muebles?, en mi caso ocurre, pero creando un efecto de tridimensionalidad que hace la visualización un poco más realista, es valido hacer esto?

**Comment by jitorcas** [comment]
Hola @Aloncarrasco!

Primero, el movimiento del chef se espera que sea **píxel por píxel** definida por el parámetro **VEL_MOVIMIENTO**. Ejemplo: si **VEL_MOVIMIENTO** es 10, debiese avanzar 10 pixeles por 10 pixeles independiente si las casillas pequeñas sean de 15 x 15. 
Segundo, en esta tarea no se pidió la creación de casillas, por lo que los objetos **deben** poder situarse en cualquier parte del mapa donde sea válido, independiente o no sea el inicio de una casilla. 
Tercero, la tarea es en **2D**, no pedimos que sea **3D**, por lo que dos superposiciones de objetos se debería considerar como una **colisión** y no debería ocurrir.
