### ISSUE TITLE
Sala del examen

### ISSUE THREAD

**Issue by HenryBlairG** [IIC2233/Syllabus#862]
Hola!

¿Cuál será la sala del examen?

Gracias 😄

**Comment by CristobalHV** [comment]
me sumo a la pregunta y añado: a que hora es el examen?

**Comment by HenryBlairG** [comment]
Es a las 15:30!!
de 15:30 - 18:00hrs 👍

**Comment by ciquezada** [comment]
Pero en que sala es??
