### ISSUE TITLE
qt designer ignorar archivos

### ISSUE THREAD

**Issue by CamilaArgomedo** [IIC2233/syllabus#862]
Hola! debo incluir en gitignore los archivos ".png", ".py" o  ".qrc" generados luego de hacer una ventana con imagen en qt designer?

**Comment by fdoflorenzano** [comment]
Hola @CamilaArgomedo,

Si dichos archivos son necesarios para el funcionamiento de tu programa y el equipo docente no es capaz de generarlos independientemente, **no debes ignorarlos**. El punto de ignorar archivos es no subir información innecesaria o que sea redundante. 

Saludos.
