### ISSUE TITLE
consulta 4 match.span me difiere en 1 caracter al del output esperado

### ISSUE THREAD

**Issue by JuanpaBC** [IIC2233/syllabus#862]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, para la consulta 4, logro obtener del texto el contenido del bloque de código, sin embargo, cuando aplico el método span a la variable que le asigné al bloque, me retorna la posición (334, 369). Esto difiere del output esperado en el test donde la posición es (334, 370). Yo asumo que estoy haciendo algo mal yo, pues si fuera un error del código, a estas alturas me imagino que ya habría una issue sobre lo mismo; asi que agradecería cualquier orientación que me ayude a desestancarme de este problema.

Acaso se considera el último caracter `\n` como parte del código? 

Desde ya gracias.

**Comment by aaossa** [comment]
En teoría, el caracter `\n` sí está dentro del bloque de código, porque está antes del cierre del mismo. Estoy casi seguro que con un pequeño cambio en tu expresión regular deberías poder capturar este caracter, sospecho que es algo muy chico. De todas formas, te recomiendo seguir con otras consultas si es que no logras resolver esa pequeña diferencia. ¡Éxito con la actividad 🙌 !

**Comment by JuanpaBC** [comment]
Vale me queda claro, gracias.
