### ISSUE TITLE
Esperar señales en un QThread

### ISSUE THREAD

**Issue by tqmbanados** [IIC2233/syllabus#862]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

Hola! Trabajando con QThreads, me encontré con una duda. Quiero que el QThread espere a una señal, pero por una cantidad de tiempo determinada, luego de la cual continúe con otra acción, algo similar al ```.wait()``` de la librería ```threading```.
Sin embagro, en la documentación de  Qt, el método ```wait()``` espera otro thread (similar a ```join()```), por lo que tendría que crear otra subclase de QThread que espere el evento antes de terminar. Esto me funciona, pero siento que se podría ahorrar mucho código y memoria al esperar directamente el evento. **¿Hay alguna manera de implementar la funcionalidad de esperar un evento o señal una cierta cantidad de tiempo en los QThreads?**

Gracias!

**Comment by aaossa** [comment]
Hola @tqmbanados , no sé si aún te sirva, pero dejo una posible respuesta, por si acaso. Creo que el objeto que podría servirte es [`QtCore.QWaitCondition`](https://doc.qt.io/qt-5/qwaitcondition.html) (lo pillé en [esta respuesta](https://stackoverflow.com/a/34347443) de StackOverflow). A ese objeto sí puedes hacerle `wait` y luego "emitirlo" (?) con `wakeAll`.

Sin embargo... aprovecho de dejar un *tip* más general: quizás apoyarte en una clase poco común de Qt resuelva justo el problema que tienes, pero **tu idea iba bien y funciona igual, y eso también tiene valor**. Entre (A) tener que leer la documentación para saber qué hace una clase específica y (B) implementar una solución que agrega un poco de complejidad pero es entendible... yo preferiría la segunda 👌 

Dicho esto.... igual quise darle una vuelta a la idea que comentaste. La dejo por si lo pensaste de otra manera y quieres compartirla, y por si a alguien le sirve en el futuro:

Una posible implementación sería hacer que tu `QThread` espere por cierto tiempo (`time.sleep(N)`) y luego ejecute la función alternativa. Sin embargo, como quieres que se llame a la función alternativa solo si la señal no ha sido emitida... entonces lo que necesitas es que tu `QThread` sea notificado de cuando se emita esta señal (tendrías que conectarlo a la señal) y verificar si esto ocurrió, modificando un atributo. Imagino que sería algo así (aviso: no probé el código 😅), que quizás implementaste de manera similar:

```python
class MiQThread:
    
    def __init__(self):
        super().__init__()
        # Primero asumo que la señal no ha sido emitida
        self.senal_fue_emitida = False

    def emitieron_la_senal(self):
        # Esta funcion va conectada a la señal
        # y si la emitieron, guardo el valor en un atributo
        self.senal_fue_emitida = True

    def run(self):
        # Espero por N segundos
        time.sleep(N)
        # Si no se ha emitido la señal, ejecuto la otra función
        if not self.senal_fue_emitida:
            funcion_alternativa()
```

Creo que no agrega mucha complejidad y no me parece una mala solución. ¿Poco común? Tal vez, pero 100% funcional y entendible. También creo que para que la solución sea 100% correcta requiere un *lock* en el atributo `self.senal_fue_emitida`, pero el punto más importante es que la idea va por ahí. 

Gracias por la pregunta, me entretuve armando la respuesta 😁✨

**Comment by tqmbanados** [comment]
Hola! La verdad no recuerdo muy bien que estaba tratando de hacer cuando escribí el issue... pero en la tarea terminé implementando algo similar a lo que pusiste arriba, en otro contexto. De todas maneras, me alegra saber que a veces una solución algo más compleja pero con menos clases también es correcta, porque igual me entretiene buscar formas de lograr lo que quiero con la menor cantidad de herramientas posible. Me alegro que el issue haya tenido una respuesta tan buena!
