### ISSUE TITLE
Problema con la resolución de las ventanas

### ISSUE THREAD

**Issue by jeria123** [IIC2233/syllabus#863]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola, mi problema es el siguiente, resulta que diseñe las ventanas para que se vieran grandes en mi monitor (2560 x 1440) sin embargo, cuando corro el código en otra pantalla de menor resolución  (como la de un notebook), solo se ve una parte del programa. Intente redimensionado la ventana mediante el método setGeometry pero es inútil, pues los labels y widgets no se encogen. ¿Existe forma de redimensionar todo, sin que tenga que rehacer las ventanas?
Foto de como se ve cuando utilizo el método setGeometry.
![res_issue](https://user-images.githubusercontent.com/69650368/97354020-8ebd2c00-1873-11eb-824b-a4f15cc9970b.png)

**Comment by knight-who-say-ni** [comment]
Holaa @jeria123 !!

Puedes agrandar la ventana?? Y si es así, se ve el resto de la ventana?? En ese caso no hay problema 😌, ya que quien te corrija lo podrá arreglar rapidamente para que se vea bien.

**Comment by knight-who-say-ni** [comment]
También se intentará que la persona que corrija tengo una pantalla de tamaño similar a la de los corregidos, asi evitamos los problemas con eso, asi que no te preocupes por ello 👌
