### ISSUE TITLE
Consulta 3, repetición de resultados 

### ISSUE THREAD

**Issue by luzmagurzua** [IIC2233/syllabus#863]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Esto me ha pasado varias veces, pero aún no me queda claro cómo se arregla: para la consulta 3, mi función encuentra el link, sin embargo vuelve a considerar el mismo link pero con una letra menos y así sucesivamente, mostrando un montón de resultados (cuando en realidad debería mostrar solo el primero). Me gustaría aclarar cómo se puede arreglar esto o a qué se debe

**Comment by nicovsj** [comment]
@luzmagurzua Esto ocurre ya que pyrematch es especial y encuentra todos los resultados de la consulta que colocas. Te pongo el siguiente ejemplo, supongamos que queremos extraer todos los números que estén entre dos comas ("`,`") en el siguiente documento:

`,012345,`

Si hacemos la consulta `!x{[0-9]+}` vas a obtener por ejemplo `012345`, pero también `12345`, `2345` , ..., `01234`, `0123`, ..., etc. es decir, todos los substrings. 

Ahora supongamos que hacemos `,!x{[0-9]+}`, bueno ahora estamos en el caso que creo que es el tuyo, pues vamos a obtener todos los prefijos: `012345`, `01234`, `0123`, `012`, `01` y  `0`. 

Así llegamos a la forma correcta de hacerlo, que sería `,!x{[0-9]+},`, esto nos da solamente `012345`.

Me imagino que estás haciendo algo así. Te recomiendo revisar tu consulta, y también revisa #854 donde quizás puedes sacar una idea. 

Saludos!

**Comment by luzmagurzua** [comment]
muchas gracias ! :)
