### ISSUE TITLE
Entidad Bocadillo

### ISSUE THREAD

**Issue by tedroppelmann** [IIC2233/syllabus#863]
Hola! Es motivo de descuento la no creación de la entidad bocadillo? Realizo los métodos de esta de otra forma que me funciona mucho mejor y no se si es necesario cambiarlo.

**Comment by DaHunterTime** [comment]
Hola!

Si bien no soy ayudante por lo que no podría decirte si se aplica un descuento o no, se habló de tratar a los bocadillos como entidades en la issue #821, suerte!

**Comment by bvasquezm** [comment]
Efectivamente, gracias @DaHunterTime por tu colaboración :)
