### ISSUE TITLE
metodo __init__ de una metaclase

### ISSUE THREAD

**Issue by ciquezada** [IIC2233/Syllabus#863]
Hola, a diferencia de lo que se dijo hoy, en el control C05 aparece lo siguiente: Métodos __new__ e __init__ se llaman al definir MiClase (y distinguir que el método __new__ se llama antes del __init__).

¿entonces el __init__ de la metaclase se llama al declarar la subclase, o está mal?

**Comment by Polea012** [comment]
Hola, efectivamente, el método __init__ de una metaclase es llamado después de __new__, e inicializa una clase que ya fue creada.
