### ISSUE TITLE
Repitencia de match dentro de las consultas

### ISSUE THREAD

**Issue by mtaguero** [IIC2233/syllabus#864]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Tengo una duda en general con las consultas. No estoy seguro por qué está pasando, pero he estado estancado un par de horas y no logro entender por que el match se repite dos veces en algunas funciones, como si leyera el documento dos veces. Es decir, se está guardando dos veces el match en el diccionario. He intentado cambiando los patrones, pero no puedo lograr que no se repita. Sería genial si me explicaran de qué depende esta repitencia para ver si puedo encontrar una solución :(.

**Comment by nicovsj** [comment]
Hola @mtaguero, 

¿Puedes verificar si es que las posiciones de tus resultados repetidos son las mismas? pyrematch es especial en el sentido de que si le escribes una consulta, te va a entregar todos los resultados, por lo que es común que dos resultados se vean parecidos pero en realidad tengan un caracter de diferencia (como un espacio, o un salto de línea).

Si ese es el problema, entonces debes arreglar tu consulta. Recuerda que puedes hacer uso de las _charclass negadas_ como se explicó en #854 si es que quieres hacer match con cualquier cosa que NO sean ciertos caracteres. 

Quedo atento a tu respuesta, saludos!

**Comment by mtaguero** [comment]
Utilizo charclass negadas y  las posiciones son exactamente las mismas. Pude arreglar las demás consultas porque tenía un error en el patrón, pero no puedo solucionarlo para la consulta 6.

**Comment by mtaguero** [comment]
Ahí logré arreglar el patrón, gracias :)

**Comment by nicovsj** [comment]
Hola @mtaguero, 

Quería pedir si es que me podrías mandar la consulta que te ocasionó el problema, porque si se estaban repitiendo los resultados exactos entonces eso es derechamente un bug de `pyrematch`. Mi correo es nicovsj@uc.cl (soy el desarrollador principal de la librería).
