### ISSUE TITLE
Flechas normales sobrepuestas

### ISSUE THREAD

**Issue by Gustav2000** [IIC2233/syllabus#864]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

(Hay muchas preguntas sobre flechas y creo haberlas leído todas para asegurarme de no repetir)
**Mi pregunta es con respecto a que si en la ronda de Aficionado y Maestro Cumbia se crean pasos de baile en un menor tiempo que en Principiante, manteniendo su VELOCIDAD_FLECHA (pixeles por segundo) esto termina en que se sobrepongan las flechas normales al no tener suficiente tiempo para distanciarse unas de otras. Esto está bien o estoy omitiendo algo?**

![image](https://user-images.githubusercontent.com/62355739/97355874-5539f000-1876-11eb-9ea7-685cffc80d83.png)

**Comment by jaimecoloma** [comment]
Hola @Gustav2000 !! Todo lo que mencionas es correcto y no existe ninguna falta o falla, esto puede pasar sin problemas (típico nivel extremo de guitar hero jaja), mucho éxito con lo que va quedando!

**Comment by Gustav2000** [comment]
Graciaas!!!
