### ISSUE TITLE
.gitignore T02: ¿importa resultado o redacción?

### ISSUE THREAD

**Issue by sbcorrea** [IIC2233/syllabus#864]
¡Hola! Tengo una duda sobre el `.gitignore`: en el enunciado se pide

> ignorar el enunciado, los archivo entregados mapa.csv, datos.csv y la carpeta llamada sprites.

Sin embargo, me incomodaría tener el enunciado en mi carpeta de repo personal, así que no lo copio desde syllabus. Además, me gusta tener toda la info previa que nos dan (`*.csv`) en una carpeta `database`, cuya ubicación y contenidos especifico en mi ReadMe. Por lo tanto, lo que termino ignorando son las carpetas `sprites`, `database` y los archivos autogenerados. Entonces, **¿está bien mi `.gitignore` si cambia su redacción pero el resultado, en términos de lo que termina subido a mi repo, es el esperado?**

Gracias de antemano 😄

**Comment by jbulness** [comment]
Hola @sbcorrea,

Tal como dices, lo que importa es el resultado, por lo que no importa como organizas los archivos en tu repositorio, siempre y cuando se cumpla con lo pedido.

**Comment by sbcorrea** [comment]
muchas gracias!
