### ISSUE TITLE
Control 8, recorrecciones actividades 

### ISSUE THREAD

**Issue by ValentinaAlvarezG** [IIC2233/Syllabus#865]
Hola, una consulta ya están puestas todas las notas del c8? Si es así, la instancia para recorregir es mañana junto con las tareas?.
Y lo otro, aun no están las recorrecciones de las últimas actividades, cierto? (específicamente la act13)   c:

**Comment by valerojasm** [comment]
Hola! Tengo la misma pregunta sobre el control 8!

**Comment by fringlesinthestreet** [comment]
Hola :)

Las notas del C8 y las recorrecciones de la AC13 estarán más tarde. Se dará un aviso al momento de subirlas (posiblemente se avise junto con el examen). 

La recorrección del C8 será presencial mañana.

**Comment by ciquezada** [comment]
los controles que aun no revisan los rellenaron con 1?? en caso contrario que pasa si hay un control sin nombre o que se haya perdido  para efectos de la recorreccion?? 
esque vivo muy lejos y no me gustaria ir solo porque si :/
