### ISSUE TITLE
Movimiento pre-ronda

### ISSUE THREAD

**Issue by ngaldamesr** [IIC2233/syllabus#865]
Hola! en la pre ronda se puede mover a MiuEnzo?

**Comment by Christian-Klempau** [comment]
En el enunciado encontré que: *Se podrá únicamente eliminar o comprar
mesas y contratar chefs.* Por lo que mover al mesero no clasificaría según lo que yo interpreté.

**Comment by fdoflorenzano** [comment]
Hola @ngaldamesr,

Como dice @Christian-Klempau (¡gracias!), no debería poderse.

Saludos.

**Comment by nachobascar** [comment]
Que pasaría si uno quisiera colocar una mesa o un chef donde está MiuEnzo?

**Comment by fdoflorenzano** [comment]
Hola @nachobascar,

Lo más lógico sería que no pudiera, ya que contaría como una colisión a inicio de juego que no le permite moverse a MiuEnzo. Como se arregla ese detalle, queda a tu criterio.

Saludos.
