### ISSUE TITLE
Parámetros de función consulta_x

### ISSUE THREAD

**Issue by Rerro-r** [IIC2233/syllabus#865]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

Hola! tengo una duda sobre las funciones de consultas.

¿Cada consulta debería definirse así: `def consulta_1(texto, patron)` o así: `def consulta_1(texto, patron=PATRON_1)`?

Perdón si es muy obvio, pero prefiero irme a la segura por la corrección automática.

**Comment by aaossa** [comment]
¡Hola! En la práctica dará lo mismo porque igual llamaremos a la función en el orden `consulta_1(texto, patron)`, entonces tu segunda definición igual funcionará bien. Déjalo como la segunda para tener puntos de estilo (?) adicionales, me gusta esa definición (no canjeables por puntaje en la evaluación). ¡Éxito con la actividad 🙌 !

**Comment by Rerro-r** [comment]
@aaossa muchas graciaaass ❤️
