### ISSUE TITLE
Imagenes en la interfaz con layouts

### ISSUE THREAD

**Issue by domja** [IIC2233/syllabus#866]
No puedo cargar las imagenes en la interfaz con layouts porque quedan deformes y no logro ajustarla, y si lo hago definiendo su geometria nomas entonces al cambiar el tamaño de la ventana la imagen no se ajusta a ese cambio, alguien sabe como se puede arreglar usando otras funciones o algo?

**Comment by furcelay** [comment]
En lo personal creo que es mejor que los objetos tengan un tamaño fijo, si se ajustan con el tamaño de la ventana pueden quedar desproporcionados y eso se vería mal o podría traerte otros problemas. Puedes fijar el tamaño de la ventana con `setFixedSize`.

**Comment by fdoflorenzano** [comment]
Hola @domja,

Como mostrado en un ejemplo en los videos de apoyo subidos y conversado en algunas *issues* (como la #818), el tema de imágenes en *layouts* es difícil, y hacer que se escalen automáticamente no es necesariamente fácil. Requeriría investigar sobre eventos de cambio de tamaño de ventana y/o sobre los atributos de `QLabel` con `QPixmap`.

Lo que sugiere @furcelay es muy válido, como forma de despreocuparse del cambio de tamaño de la ventana si no es realmente algo necesario.

Saludos.
