### ISSUE TITLE
Error al ejecutar

### ISSUE THREAD

**Issue by Rerro-r** [IIC2233/syllabus#866]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Me acaba de lanzar esto la terminal:
```
---------------- Probando CONSULTA consulta_1 ----------------

parse failed: ''
```

¿Qué significa?

**Comment by nicovsj** [comment]
Hola @Rerro-r, 

Me parece que es un error de parsing de `pyrematch`, lo que implica que estás escribiendo una consulta mal. Por favor revisa la consulta que podría estar ocasionando el problema. Si quieres me puedes escribir a nicovsj@uc.cl con tu consulta y te cuento lo que está mal (no la coloques acá para no dar tu respuesta a tus compañeros).

Saludos!
