### ISSUE TITLE
Mi porgrama se cae con muchos pingüinos

### ISSUE THREAD

**Issue by En-clases** [IIC2233/syllabus#866]
### Prerrequisitos

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, he implementado el ```drag and drop``` de los pingüinos y sus movimientos. Todo funciona bien siempre y cuando no hayan mas de 6 pingüinos (aproximadamente) en la pista de baile y jugar en la dificultad más difícil. Al tener muchos pingüinos el programa se cae sin lanzar ningún error. Cuál podría ser el problema?

**Comment by mtlehmann** [comment]
A mí me pasa lo mismo pero con las flechas cuando se juega en maestro (sin implementar los pingüinos). A veces me funciona bien y a veces no (en los otros niveles casi siempre me funciona bien) pero cuando hay muchas flechas el programa se me cae y se cierra solo :(

**Comment by knight-who-say-ni** [comment]
Hola @En-clases y @mtlehmann !!

Lo más probable que les pase es que estás teniendo **overthreading**, esto es, muchas threads corriendo al mismo tiempo, lo que provoca que su computador no pueda ir cambiando entre threads de manera eficiente.

¿Como arreglo esto? Primero que todo, revisar que esten usando la cantidad de threads justa y necesaria: quizá algunos se quedan abiertos por más tiempo del necesario, o están realizando varias acciones innecesarias. Tambien puede haber un time.sleep() por ahí que haga que todo se detenga en ocasiones 🤔 .

De todas formas, al tener muchos threads activos en cualquier computador se va a laguear, asi que no se esperen que testeemos 20 pingüinos bailando al mismo tiempo, por ejemplo.  Quiza estaría bueno mencionar en el readme la cantidad de pingüirines máxima que su programa puede tener antes de empezar a laguerse 👀 .

Espero haberles ayudado, cualquier cosa me responden 😄 . Exito programando!!

**Comment by En-clases** [comment]
Muchas graciass!! y perdón por el spam, pensé que no habían visto la issue.
