### ISSUE TITLE
Error resultados de test en consultas

### ISSUE THREAD

**Issue by matyjjn14** [IIC2233/syllabus#867]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola lo que pasa es que tengo problemas con lo que retorna mis funciones de consultas ya que al testearlas me arroja error cuando mis diccionarios estan dentro de listas como dice el enunciado: Aquí va un ejemplo:
[{'contenido': 'Titulo', 'posicion': (2, 8)}]
Entonces no sé por qué el test me los considera erroneo.
Espero me puedan ayudar, gracias!

**Comment by fernandosmither** [comment]
Tengo el mismo error, en mi caso en específico al ejecutar la última función de api.py con los parámetros, el servidor retorna como respuesta que la key "mensaje" debe ser una lista, sin embargo, lo he revisado mucho y sí estoy enviando una lista. A menos que estemos haciendo algo muy mal al enviar la request, diría que puede ser un typo en la api.

**Comment by aaossa** [comment]
Creo que son cosas distintas.

@fernandosmither revisa #853 y pregunta allá si tienes alguna duda.

@matyjjn14 no indicaste donde es tu error, pero dado que dijiste "testearlas" asumiré que ocurre algo en `test.py`. Fíjate que en el caso de `test.py`, `argumentos_1` y `output_esperado_1` (lo mismo para todas las consultas) son listas de elementos. Esto es para que puedas probar más de un ejemplo a la vez. Entonces, por ejemplo, `output_esperado_1` debería tener un elemento (indicando que es el *output* esperado del primer elemento en `argumentos_1`), y ese elemento es una lista con un diccionario (que es lo que debería retornar `consulta_1`). Sospecho que por eso podría ser tu error. Te recomiendo mirar el archivo test.py publicado en Syllbus, quizás lo modificaste:

https://github.com/IIC2233/syllabus/blob/49f1b87a3cd41115f916127192f796a7b50b0818/Bonus/test.py#L124-L126

¡Éxito en la actividad 🙌 !

**Comment by fernandosmither** [comment]
> Creo que son cosas distintas.
> 
> @fernandosmither revisa #853 y pregunta allá si tienes alguna duda.
> 
> @matyjjn14 no indicaste donde es tu error, pero dado que dijiste "testearlas" asumiré que ocurre algo en `test.py`. Fíjate que en el caso de `test.py`, `argumentos_1` y `output_esperado_1` (lo mismo para todas las consultas) son listas de elementos. Esto es para que puedas probar más de un ejemplo a la vez. Entonces, por ejemplo, `output_esperado_1` debería tener un elemento (indicando que es el _output_ esperado del primer elemento en `argumentos_1`), y ese elemento es una lista con un diccionario (que es lo que debería retornar `consulta_1`). Sospecho que por eso podría ser tu error. Te recomiendo mirar el archivo test.py publicado en Syllbus, quizás lo modificaste:
> 
> https://github.com/IIC2233/syllabus/blob/49f1b87a3cd41115f916127192f796a7b50b0818/Bonus/test.py#L124-L126
> 
> ¡Éxito en la actividad 🙌 !

Toda la razón, profesor. Se arregló utilizando `json` en vez de `data`. Cuál es la diferencia de ambos, y por qué en los ejemplos del notebook usabamos data? Yo pensaba que sí estábamos enviando json como tal

**Comment by aaossa** [comment]
@fernandosmither pregunta en la otra *issue*, esta es de un tema distinto

**Comment by matyjjn14** [comment]
@aaossa Pero entonces el output esperado es una lista de listas que contienen diccionarios?? es que en el enunciado aparece "lista de dict". Y, puede que suene un poco absurda la pregunta, pero por qué el output_esperado_1 siendo una lista con un elemento en su interior tiene una coma al final?

**Comment by aaossa** [comment]
> 
> 
> @aaossa Pero entonces el output esperado es una lista de listas que contienen diccionarios?? es que en el enunciado aparece "lista de dict". Y, puede que suene un poco absurda la pregunta, pero por qué el output_esperado_1 siendo una lista con un elemento en su interior tiene una coma al final?

El *output* esperado para una llamada a la función sí es una lista de diccionarios. Lo que digo es que en el *test* pones una lista de *outputs* (entonces ahí te queda la lista de listas con diccionarios), por que también tienes una lista de *inputs* (que es una lista con tuplas, porque la función recibe dos argumentos). Lo de la coma al final es más que nada por estilo, no afecta el resultado (sigue siendo una lista con un elemento)

**Comment by matyjjn14** [comment]
Ahhh perfecto, que extraño entonces, según yo lo que arrojan mis consultas cumplen con lo pedido, y el archivo test.py no está modificado

**Comment by aaossa** [comment]
Te recomiendo comparar el *output* directamente en el servidor, subiendo el resultado como se espera en la tercera función de la API. Revisar el *output* y, si te da un `"proceso"` es porque el formato está bien (si el formato está mal te dará un status `400 (Bad Request)`)
