### ISSUE TITLE
Flechas de hielo, el efecto es acumulable?

### ISSUE THREAD

**Issue by ignaciomansuy** [IIC2233/syllabus#867]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! 
Cuando se atrapa una flecha de hielo se reduce la velocidad de las otras flechas por un cierto tiempo. Mi duda es si este efecto es acumulable; es decir, si mientras el efecto aún está activo y se atrapa otra flecha de hielo se suma más tiempo al efecto?
Me parece que este detalle no está especificado en el enunciado, entonces quería saber si podemos hacer que este efecto se pueda aplicar solo si no hay otro efecto _hielo_ activo en ese instante.

Saludos!

**Comment by manearaya** [comment]
Hola @ignaciomansuy!

Tienes toda la razón, ese detalle no está especificado en el enunciado. Por lo tanto, queda a tu criterio qué hacer con el tiempo del efecto (si se acumula o si se reestablece). Recuerda incluir tu decisión en tu readme!

Lo que sí está especificado es la probabilidad de que aparezcan flechas y que (cuando corresponde) estas tengan un efecto, y evitar que ocurra alguna de estas cosas estaría en contra del enunciado. 

Éxito con la tarea!
