### ISSUE TITLE
Cargar partida

### ISSUE THREAD

**Issue by EmeraldMP** [IIC2233/syllabus#867]
Hola! si cargo partida entro en pre-ronda o ronda? no encuentro eso en el enunciado :(

**Comment by amparostevens** [comment]
Hola! No soy ayudante pero : 
- Al inicio de la página 9 del enunciado sale "al crear una **nueva partida** siempre comenzarás en la etapa de **ronda**".
- En el párrafo 4 de la sección **2. Flujo del juego** sale que la primera fase es **pre-ronda**.

 Por lo tanto al cargar una **partida existente** deberás comenzar en **pre-ronda**
Éxito con la tarea!

**Comment by EmeraldMP** [comment]
Muchas gracias por tu ayuda!

**Comment by furcelay** [comment]
Quiere decir que al seleccionar "nueva partida" en el menú de inicio se carga el mapa e inmediatamente comienzan a llegar clientes?

**Comment by fdoflorenzano** [comment]
¡Gracias @amparostevens por la respuesta!

@furcelay Por la descripción de ronda en el enunciado se intuye que sí, ya en etapa ronda los eventos de simulación comienzan. Además se menciona que el botón comenzar debe estar inhabilitado en ese estado.

**Comment by furcelay** [comment]
Muchas gracias!

**Comment by vblopez** [comment]
Hola quede un poco confundida con las dos respuestas, al cargar una partida existente hay que comenzar en pre-ronda ( pudiendo comprar cosas y con el boton comenzar habilitado ) o comenzar en ronda (con la simulacion ya activada y el boton comenzar deshabilitado) ?

**Comment by fdoflorenzano** [comment]
Hola @vblopez,

Al cargar una partida existente, siempre partes en pre-ronda. Es la nueva partida la única que parte en ronda.

Saludos.
