### ISSUE TITLE
como editar un qlabel si es que estoy conectandolo desde qtdesigner

### ISSUE THREAD

**Issue by elchocman** [IIC2233/syllabus#868]
### Duda
En qt designer cree labels "variables" es decir, un label que voy a cambiar a medida que se juege, por ejemplo en mi Ranking, tengo un titulo, la cosa es que abajo de este al conectar el label(su nombre es ranking) de qt designer con la ventana (MainWindow) y luego especifico que la funcion que la va a editar (tiene nombre rankeador) abriria el archivo..txt y luego haria un self.ranking.setText("texto") pero esto no esta alterando la ventana de ranking al abrirla para jugar. 
Este dato serviria para todos los labels.

**Comment by manearaya** [comment]
Hola @elchocman!

Se me ocurre que quizás tienes más de un label con el mismo nombre, o que estás usando un nombre distinto al que definiste en Qt Designer. 

Si no es eso, te podría servir llamar self.update() después del self.ranking.setText("texto"), que debería actualizar la ventana.

Si eso tampoco funciona, podrías subir lo que llevas a tu repositorio para que pueda revisar tu código.

Saludos!

**Comment by elchocman** [comment]
hola, si, probe con self.update() pero tampoco me funciono,lo voy a subir ahora a mi repositorio si es que es posible que revises cual seria el problema. graciaas

**Comment by elchocman** [comment]
ya lo subi :v

**Comment by manearaya** [comment]
Me parece que el problema es que no estás llamando a la función correcta, ya que si llamo a la función que cambia el label en el init sí se actualiza.

**Comment by elchocman** [comment]
@manearaya  muchas graciaaaas ahi me funciono, osea puse la funcion en el init nomas, aunque tengo mis sospechas, de que en qt designer estoy conectando el label a la funcion por medio de un linkActivated(qstring) que no se si eso esta bien

**Comment by manearaya** [comment]
Hmm tengo entendido que linkActivated solo va a servir si hay literalmente un link que apretar. Te recomiendo no complicarte y poner la función en el init, o algo parecido :)

**Comment by elchocman** [comment]
valeeee, muchas gracias te pasaste
