### ISSUE TITLE
Error en Ejecucion de test.py y no puedo revisar mi codigo.

### ISSUE THREAD

**Issue by JaToledo99** [IIC2233/syllabus#868]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

## Tengo bien installado todo (adjunto foto) pero al ejecutar me salen errores al importar pyrematch
No puedo usar test.py por estos errores, ya actualice e hice todo lo que hay en los docs del curso y el eneunciado. 

![image](https://user-images.githubusercontent.com/69644295/126751229-6221c55f-a38d-4065-8d4f-b47b7b0d0c1c.png)

![image](https://user-images.githubusercontent.com/69644295/126751322-49961221-b1cd-452d-a3e0-2b4537d52b16.png)

**Comment by aaossa** [comment]
¿Probaste ejecutando tu programa desde fuera de VS Code (por ejemplo desde cmd)?

**Comment by JaToledo99** [comment]
Todo sigue con el mismo error
![image](https://user-images.githubusercontent.com/69644295/126836999-6ac9d1f0-1903-4d2d-9ed8-13e4d379c583.png)
![image](https://user-images.githubusercontent.com/69644295/126837013-a803bd78-df2a-499e-be85-7bcc2ffe6ecd.png)

**Comment by aaossa** [comment]
¿Podrías probar desinstalando y reinstalando?

- `pip uninstall pyrematch`
- `pip install pyrematch`

Si eso no funciona, lo mejor sería que usaras Google Colab (considerando lo cerca de la hora de entrega), como explicó @lily416 en su comentario en esta *issue* (el punto 2): https://github.com/IIC2233/syllabus/issues/858#issuecomment-885186225
