### ISSUE TITLE
Efecto combinacion de teclas

### ISSUE THREAD

**Issue by amparostevens** [IIC2233/syllabus#868]
Hola! No me queda claro cuando tienen que tener efecto las teclas **M+O+N** y **R+T+G**. Debe ser sólo cuando se está en la ronda como con **F+I+N** o en la pre-ronda también?

**Comment by furcelay** [comment]
Creo que no está especificado en el enunciado por lo que lo mejor sería no restringirlo (que funcionen en ronda o pre-ronda) a excepción del F+I+N.

**Comment by jitorcas** [comment]
Hola @amparostevens!

Tal como dice @furcelay, no está especificado en el enunciado en qué momentos debiesen estar activos los efectos de las teclas, por lo que se asume que deben estar activas en todo momento a excepción de **F + I + N** la cual si se usa fuera de una ronda no debe tener efecto.

**Comment by cotefon** [comment]
¿la combinación de teclas puede ser en minúscula?

**Comment by jitorcas** [comment]
Hola @cotefon 

Si mal no recuerdo, `KeyPressEvent` no identifica entre mayúscula y minúscula, así que para identificarlo deberías implementar más código, por lo que te recomiendo aceptar ambos tipos.

**Comment by amparostevens** [comment]
Y si están activas sólo en la ronda se considera como incorrecto?

**Comment by jitorcas** [comment]
@amparostevens se considera como incompleto ya que no cumpliría con el requerimiento en su totalidad.
