### ISSUE TITLE
Problema con Drop en Drag and Drop

### ISSUE THREAD

**Issue by based-on-what** [IIC2233/syllabus#869]
Hola a todos, acabo de implementar esto en mi juego, pero tengo un gran problema al momento de "soltar" el QLabel que estoy arrastrando, les adjunto imágenes.

![arrastre1](https://user-images.githubusercontent.com/62000495/82969131-e8f05300-9f9c-11ea-8cf8-38c83b2f3e80.PNG)
En la primera, se ve que quiero arrastrar el _sprite_ del chef hacia el mapa, pero hay una mesa al costado izquierdo que se ve fuera de lugar.

![arrastre2](https://user-images.githubusercontent.com/62000495/82969137-ebeb4380-9f9c-11ea-8153-1a44fb32593c.PNG)
En la segunda, es el resultado de ese drop, en donde, aparte de quedar en una zona que no corresponde, queda con al resolución original (todos mis sprites son dos veces más grandes de lo que hay en la carpeta), ¿hay alguna forma de arreglarlo? En consola se imprimen las coordenadas del mouse cuando arrastro el QLabel y no muestra mayores complicaciones (o sea, las coordenadas coinciden), y al hacer _drop_ imprime las coordenadas en donde solté el ícono, pero siempre queda en el mismo lugar.

¿Cómo se puede solucionar? 

Saludos y gracias.

**Comment by furcelay** [comment]
Depende mucho de cómo lo hayas modelado, pero en general deberías modificar el dropEvent para que al ejecutarse mueva la entidad a la ubicación deseada y ajuste el tamaño.

Saludos!

**Comment by fdoflorenzano** [comment]
Hola @based-on-what,

Como dice @furcelay, depende bastante de tu implementación, y suena a un problema específico de tu programa. ¿Sigue ocurriendo lo mismo o pudiste arreglarlo desde entonces?

Saludos.

**Comment by based-on-what** [comment]
@furcelay @fdoflorenzano 

Ya está solucionado, y ya no tengo problemas de resolución de sprites, muchas gracias.
