### ISSUE TITLE
Restaurar desde un commit

### ISSUE THREAD

**Issue by Zenos-Paradox** [IIC2233/syllabus#869]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

Cómo puedo reemplazar los archivos de mi pc por los de mi repositorio? sólo con git pull?

**Comment by manearaya** [comment]
Hola @Zenos-Paradox!

Si quieres reemplazar los archivos que tienes en tu computador con los de tu repositorio , puedes abrir git bash en la carpeta principal y usar el comando `git restore *` (o puedes cambiar el * por alguna carpeta o archivo en específico si no quieres restaurar todo, [acá ](https://www.git-tower.com/learn/git/commands/git-restore/)puedes encontrar ejemplos). 

**Ten cuidado, porque borraría cualquier cambio que hayas hecho en tu computador después del último push!**

Era eso lo que necesitabas?

**Comment by Zenos-Paradox** [comment]
@manearaya Holam intenté hacerlo pero git instentó restaurar también los archivos dentro del .gitignore, que claro no encontró en el repositorio.

**Comment by manearaya** [comment]
Podrías usar `git restore archivo.py`, que restauraría el archivo individual y no trataría de restaurar todo.
