### ISSUE TITLE
Varias dudas formato corrección consultas.py y revisión API

### ISSUE THREAD

**Issue by mignacia** [IIC2233/syllabus#869]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola, tengo varias preguntas.
En primer lugar para la parte de consultas.py es con que si podemos asumir que el formato de los espacios de cada elemento que nos piden será siempre como en el markdown dado? 
Pondré los ejemplos en orden para que se entienda:
- En la consulta 1 siempre será # Título y no #Título ?
- Lo mismo para la consulta 2 , siempre será como ## sub titulo y no ##sub titulo ?
- En la consulta 3  será siempre <img src= "ejemplo/imagen" alt> y no cambiando los espacios como por ejemplo < img src = "ejemplo/imagen"alt > ?
- En la consulta 4 en el caso del check list será siempre [X] ejemplo y no [X]ejemplo. 
- En  la consulta 5 ( se que se ocupa ` pero es para que se vea y no se escriba como texto aquí) siempre será 
'''lenguaje
texto texto
'''
o podria ser que no haga el salto de línea inmediatamente dsps del lenguaje por ejemplo
'''lenguaje texto
texto texto
'''
- Finalmente en la consulta 6 siempre el contenido sera todo lo que esté en la misma linea de [link] (http...) ? sin incluir algun salto entre medio?

Creo que se entiende mi punto con los ejemplos, y lo otro un poco a parte, es si puedo asumir que los contenidos de la consulta 2 o 6 van a estar siempre después de un salto de linea? o pueden ir en la primera?

Por último con respecto a api.py tengo dos dudas. Uno es si se considera malo que al registrarme no se vea bien mi nombre ya que tiene tilde y ñ, entonces se cambia según eso. Se puede ver en /estudiantes mi usuario registrado es mignacia. Lo segundo es que no entiendo muy bien como se va a revisar esta parte, entonces me queda la duda si por ejemplo tenemos que dejar llamadas las 3 funciones hechas o basta con completarlas nada más. Además, de que no entiendo en su totalidad lo que aparece de probar una consulta sobre un documento, ya que estoy un poco enredada con el enunciado y lo que sale en la página de documentación. Por último, para crear el archivo que guarda el texto en la función descargar_documento asumimos que esta ruta parte ya en el directorio de la carpeta Bonus? o no sé si estoy entendiendolo bien

Desde ya muchas gracias y perdón por la extensión u.u

**Comment by aaossa** [comment]
Hola @mignacia , entiendo que puedas tener varias preguntas pero preferiría que no hicieras tantas en una sola *issue*. Quizás agruparlas o preguntar por Discord algunas sería más rápido. Le voy a poner un numerito cada pregunta por si después quieres (u otra persona) preguntar algo específico sobre una de mis respuestas. De todas formas, aquí vamos:

> 1. En la consulta 1 siempre será `# Título` y no `#Título` ?
> 1. Lo mismo para la consulta 2 , siempre será como `## sub titulo` y no `##sub titulo` ?

Para todos estos *headings*, el espacio después del `#` es requerido por el formato Markdown, por lo que puedes esperar que sea de la forma `# Titulo`

> 2. En la consulta 3 será siempre y no cambiando los espacios como por ejemplo < img src = "ejemplo/imagen"alt > ?

Lo respondí en #860 

> 3. En la consulta 4 en el caso del check list será siempre [X] ejemplo y no [X]ejemplo.

Lo mismo que en la primera pregunta, el espacio después del `]` es requerido por Markdown, por lo que puedes esperar que esté ahí.

> 4. En la consulta 5 siempre será (...)

El segundo formato que planteas no es válido, el primero sí es permitido por Markdown. 

> 5. Finalmente en la consulta 6 siempre el contenido sera todo lo que esté en la misma linea de [link] (http...) ? sin incluir algun salto entre medio?

Esto lo respondí en Discord si no me equivoco. Una línea se acaba cuando se salta a la siguiente línea.

> 6. (...) puedo asumir que los contenidos de la consulta 2 o 6 van a estar siempre después de un salto de linea? o pueden ir en la primera?

De acuerdo a la sintaxis de Markdown, sí pueden estar en la primera línea.

> 7. Uno es si se considera malo que al registrarme no se vea bien mi nombre ya que tiene tilde y ñ, entonces se cambia según eso.

No hay problema con esto, eso ya es manejo del *string* desde el lado del servidor

> 8. me queda la duda si por ejemplo tenemos que dejar llamadas las 3 funciones hechas o basta con completarlas nada más

Va a corregirse igual que las consultas: vamos a importar sus funciones y llamarlas por nuestra cuenta con un *input* y comparar el *output* con lo que debería retornar. Además vamos a darle una mirada a lo que quede en el servidor para validar que se haya recibido correctamente.

> 9. no entiendo en su totalidad lo que aparece de probar una consulta sobre un documento

La idea es que puedas enviar los resultados que obtuviste sobre un documento para una consulta en particular y el servidor te va a retornar un `proceso`. Con ese `proceso` podrás hacer una nueva consulta (`GET`) y ver si es que obtuviste el resultado correcto (comparamos tu resultado con el resultado esperado usando una solución en el servidor).

> 10. Por último, para crear el archivo que guarda el texto en la función descargar_documento asumimos que esta ruta parte ya en el directorio de la carpeta Bonus? 

En estricto rigor, da lo mismo donde esté la ruta, solo ocupen el parámetro y confíen (?) que será una ruta válida.

¡Éxito con la actividad 🙌 !
