### ISSUE TITLE
Sobre entidad juego, accion probabilidad_de_ganar

### ISSUE THREAD

**Issue by Fernanda1232123** [IIC2233/Syllabus#87]
### Prerrequisitos

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

La fórmula que hay en probabilidad_de_ganar en la entidad Juego tiene un 'Probabilidad_ganar_jugador', de donde se saca eso?

**Comment by jtvaldivia** [comment]
Hola, 
![Captura de Pantalla 2022-04-04 a la(s) 17 53 31](https://user-images.githubusercontent.com/80768875/161638503-2e92445f-bac3-42a8-9e00-996f862f678a.png)
en el enunciado en la entidad del jugador se ve la formula y la explicacion de esta.

**Comment by MaxAl100** [comment]
> Hola, quizás sea muy obvio pero, qué pasa si el juego no es su favorito? Qué valor se coloca entonces? 0?

En ese caso se pone 0, sí.
![image](https://user-images.githubusercontent.com/43099597/161823232-6e6c7471-a508-4214-8a50-1343d886a98d.png)

[imágen de la página 9 del enunciado]
