### ISSUE TITLE
Comportamiento inesperado open()

### ISSUE THREAD

**Issue by dlmed** [IIC2233/syllabus#87]
Hola, tengo un problema en una de las implementaciones que hago de open(), como no es un error, no puedo pegarlo o explicarlo aquí, ya que mostraría mi código. Quería saber si algún ayudante me puede ayudar (xd) explicándole cómo se genera el comportamiento inesperado y parte del código que puede provocarlo.

Saludos!

**Comment by dlmed** [comment]
Básicamente al hacer un:
with open("algo.csv", "r+", encoding="utf-8") as archivo:
    bla bla

Después de hacer lo que tiene que hacer con el archivo .csv, reviso este y al final se agrega una línea con un extracto de la línea anterior, como si hubiera hecho archivo.write(linea_anterior[-5:]))
me pasa con esta implementación, pero en otro lado del código tengo algo muy similar y no genera el mismo comportamiento errático.

**Comment by MatiasDuhalde** [comment]
Hola!

Puedes subir la última versión de tu código a tu repositorio?
Voy a revisarlo y ver si puedo emular el error.

**Comment by dlmed** [comment]
oka!

**Comment by dlmed** [comment]
Listo! en el msje del commit está el detalle

**Comment by MatiasDuhalde** [comment]
Hola!

Lo que hace tu programa es que al cerrar el archivo (saliendo del `with open("algo.csv", "r+", encoding="utf-8") as archivo`), este le agrega unos caracteres al final. ¿Cuántos caracteres? Es igual al largo del usuario que pusiste para dejar de seguir.

No te voy a mentir, desconozco la causa exacta de este comportamiento, pero supongo que se debe a la manera en que se maneja la posición del puntero y el offset de caracteres al hacer `write()` cuando trabajas el archivo en modo `r+`.

Eso sí, pude encontrar una solución relativamente simple. En lugar de leer y escribir en el archivo de una usando el modo `r+`, separa el proceso en dos `open()`, primero uno con modo `r` donde leas las líneas (y en tu caso las guardes en una lista), y segundo abrir con modo `w` para escribir las líneas ya procesadas.

Ojalá se entienda la explicación, y si sigues con problemas no dudes en preguntar!

**Comment by MatiasDuhalde** [comment]
Hola de nuevo xd

No pude quedarme dormido así que me puse a intentar arreglar el error, y encontré la causa :)

Lo que pasa es que cuando borras un usuario, se reduce la extensión del archivo (la cantidad de caracteres que este contiene). Cuando terminas de escribir el archivo, el programa se da cuenta de que el puntero no se encuentra exactamente en el final (te falta completar con **n** caracteres, **n** siendo el largo del nombre que borraste), por lo que rellena con caracteres (los que están al final del archivo) hasta llegar a la extensión que el archivo tenía originalmente. 

Para solucionar esto, está el método truncate() que corta todos los caracteres que le siguen al puntero actual.
Se ocupa de la siguiente forma: 
`archivo.truncate()`
Y en tu caso tienes que colocarlo antes de salir del bloque `with` que abres en modo `r+`.

Espero que esto resuelva tu problema y tus dudas, y si no, eres libre de preguntar de nuevo :smiley:

**Comment by dlmed** [comment]
Ahora si!!!!!!! Muchísimas gracias!!

**Comment by dlmed** [comment]
Una posible mejora sería poner el archivo.truncate() después del archivo.seek(0), ya que si en el for hay un error, quedaría la mitad con las líneas nuevas y la otra mitad de líneas viejas. Al poner el truncate() después del seek(0), si hay un error, queda el archivo hasta la mitad con las líneas nuevas y no las viejas, de tal forma que te das cuenta que hubo un error.
