### ISSUE TITLE
Duda sobre línea al final de los archivos ".csv"

### ISSUE THREAD

**Issue by RodrigoFritis** [IIC2233/syllabus#87]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola a todos, tengo una duda respecto sobre la línea final de los archivos ".csv". Dado que tenemos que escribir en ellos mi código presenta problemas cuando hay un "enter" o una linea en blanco al final de los archivos ".csv" que tengo que sobrescribir. Por lo tanto, ¿cómo debería asumir el final de un archivo .csv? Entiendo que no es algo arbitrario debido a que los "enter" al leer o escribir influyen.
Gracias

**Comment by ag-contreras** [comment]
Hola! Quizás podrías descargarte la extensión de archivos .csv en Visual Code y borrar ese espacio o también podrías hacer un slice de las líneas útiles para dejar afuera ese espacio en blanco. Ojala te sirva! :)

**Comment by IgnaciaJ** [comment]
Hola @RodrigoFritis te recomiendo escribir un código que elimine el último enter del archivo(o realizar un pop en la lista, luego de leer el csv). Suerte con la tarea!
