### ISSUE TITLE
Duda variables globales

### ISSUE THREAD

**Issue by jahernandez2** [IIC2233/Syllabus#87]
Hola! Estoy terminando la tarea y me di cuenta que hay penalización por variables globales... ¿existe algo para guardar inputs pedidos en un funcion f() para luego utilizarlos en una funcion g()? 
Saludos!

**Comment by tqmbanados** [comment]
Hola @jahernandez2 ! En general hay dos formas de hacer eso sin usar variables globales.
1.- Hacer que ambas funciones sean métodos de una clase, y guardar lo retornado por el input como atributo de la clase, que luego puedes usar en la otra función.
2.- Hacer que la primera función retorne el valor, y luego pasar el valor como argumento a la segunda función.

Espero serte de ayuda!
