### ISSUE TITLE
Código de fuentes online externas

### ISSUE THREAD

**Issue by Yeps3nM** [IIC2233/Syllabus#87]
### Prerrequisitos

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/20)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/19)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola! Todavía me quedan dudas de cómo debo utilizar correctamente código de fuentes online externas, no sé donde se debe indicar su uso dentro del código y si se utiliza algún formato de cita. Se debe aclarar qué sitio es, la linea exacta y la fecha?

**Comment by pedrozavalat** [comment]
Hola @Yeps3nM ! 😄 

Al momento de citar un codigo de una fuente online externa debes citarlo en tu **README**. 
Idealmente debes proporcionar el **link** de donde obtuviste el código, una breve **descripción** de su funcionalidad, y el nombre del archivo en el que implementaste el código (mencionando en las **lineas** en donde se encuentra). 
Una forma de citar el codigo puede ser la siguiente: 

1. \<link del código: <Breve_descripción>. Implementé este código en las líneas <numero_inicio> a <numero_fin> en el archivo <nombre_del_archivo> con el propósito de < funcionalidad >

Espero que haya aclarado tu duda, Saludos! :)

**Comment by Yeps3nM** [comment]
Sii me aclaró mi duda, muchísimas gracias !!!
