### ISSUE TITLE
Duda sobre eventos punto 8

### ISSUE THREAD

**Issue by geduran** [IIC2233/Syllabus#87]
En el punto 8 dice que los eventos (Invasión del archimago o asteroide) ocurren cada vez que uno visita un "nuevo" planeta, sin especifica si está conquistado o no. Asumo que con nuevo planeta se refiere a que no está conquistado?  Eso quiere decir que los eventos pueden ocurrir cuando invades un planeta, o sea antes de la batalla?

**Comment by Arcoirisky** [comment]
Hola! ¿Por qué no revisas la issue #95? :D quizás responda tu duda :D
