### ISSUE TITLE
Import de variables

### ISSUE THREAD

**Issue by nerrazuriz** [IIC2233/syllabus#87]
Hola! Estoy teniendo problema importando variables de un módulo a otro. Me pasa que, por ejemplo, en edificio.py tengo definida una variable y si quiero importarla a main.py, solo me deja si en main.py no he importado nada de edificio.py. Hay alguna forma de solucionarlo?
Gracias!

**Comment by Polea012** [comment]
Hola! Por lo que entiendo, ya has hecho import de edifico.py Una opción para solucionar el problema sería importar todas las variables que necesites en un solo import de la siguiente manera:
```Python 
from edificios import variable_1, variable_2,... etc
```

Ojalá que esto resuelva tu problema!

**Comment by nerrazuriz** [comment]
No es eso. Si es que en el modulo "x" quiero importar una variable del modulo "y", pero previamente en el módulo "y" había importado algo de "x", python me tira error y no puedo importar la variable. No sé si se entiende jajajajaja

**Comment by Polea012** [comment]
Ahh ahora entiendo. Eso es importación cruzada y por lo general es una mala práctica, principalmente porque te puede causar los errores que tienes ahora. Te sugiero que reevalues  cuáles son los módulos que deberían importar a otros módulos y revisar la modelación de tu solución. Puedes intentar dejar ciertas variables según alguna lógica en los módulos.
Éxito!

**Comment by nerrazuriz** [comment]
En el archivo "y" tengo:

from x import Algo
a = 1

En el archivo "x" tengo:

from y import a
class Algo:
    pass
print(a+2)

Y cuando corro el archivo x me sale error

**Comment by nerrazuriz** [comment]
Aaa perfecto, gracias!
