### ISSUE TITLE
Duda Dimensiones Tablero

### ISSUE THREAD

**Issue by sbarriag** [IIC2233/Syllabus#87]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, quería preguntar por las dimensiones del tablero que se nos entregan en el enunciado, por ejemplo en la Figura 1 nos dicen que es un tablero de 4x5, sin embargo si cuento la cantidad de filas y columnas tengo 5 y 6 respectivamente porque se cuenta el 0.

Entonces , si yo quisiera recorrer las filas el tablero con un ciclo for. Si yo tomara lo entregado en la class Tablero hiciera 

for fila in range(0, len(tablero)) 
celda = self.tablero[fila][algo]

Dado que la función for toma el rango como (min, max-1) si quisiera recorrer la fila completa, an algún momento tendria que sumarle 1 para hacer todo el recorrido? 

Pregunto por si tuve una interpretación errónea del enunciado
Muchas gracias

**Comment by ManuelV03** [comment]
Efectivamente ese tablero del enunciado es de 5 X 6. Igualmente, esa información no es del todo relevante considerando que si haces el for i in range(len(tablero)) podras recorrer todas las filas del tablero. Dime si se aclaró tu duda.

**Comment by sbarriag** [comment]
Entonces, es un error de enunciado que la Figura 1 diga 4x5 y no 5x6 . En ese caso me haría sentido poder recorrer todo con un for solo con el len(tablero)

Quedo atento

**Comment by Hernan4444** [comment]
Hola @sbarriag 

Si, fue un error del enunciado que dice 4x5, pero debe decir 5x6. 

Saludos!

**Comment by sbarriag** [comment]
Muchas gracias ahora si me hace sentido

Que tenga una buena semana
