### ISSUE TITLE
Ingresar fecha sin segundos

### ISSUE THREAD

**Issue by akaminetzkyp** [IIC2233/Syllabus#87]
Hola!

En el issue #80, @rpalmaotero dijo que podríamos considerar que el tiempo pasa en minutos. Como dentro del programa los segundos ya no van a existir, significa que podemos pedirle al usuario que su input de fecha sea de la forma "AAAA-MM-DD HH:MM" y no"AAAA-MM-DD HH:MM:SS"?

Saludos!

**Comment by FernandoPieressa** [comment]
Lo pueden considerar, saludos!

**Comment by akaminetzkyp** [comment]
Gracias! :D
