### ISSUE TITLE
Duda mercado AAABBB vs BBBAAA

### ISSUE THREAD

**Issue by andreslyon** [IIC2233/Syllabus#87]
no tengo muy claro si hay que implementar, todas las combinaciones posibles de mercados. 
de la forma que lo entiendo es que existe una moneda "real" en este caso los dcc, y uno los transa por alguna moneda virtual cualquiera. En el caso en que se debiese  crear el mercado AAADCC y DCCAAA, un bid en el mercado AAADCC sería equivalente a un ask en el mercado DCCAAA, y viceversa. entonces no me queda muy claro la lógica.  Luego, lo que se me ocurre que deberia ser es que para cada cryptomoneda (NNN) exista un mercado NNNDCC.

**Comment by cilopez** [comment]
Imaginemos dos mercados "inversos" de monedas A y B:
* En el primer mercado se vende N  monedas del tipo A  a un precio Q de monedas B, puedo obtener **a lo más** NQ de B.
* En el segundo compro N monedas del tipo  A a un precio Q, puedo obtener por como **mínimo**  NQ de B, ya que pueden existir ofertas por valores menores al que busco.

Por lo que los mercados **si son distintos**, en terminos de dinámica de ganancias.(consideramos en ambos casos que se vende o compra la totalidad de monedas), espero que se entienda :sweat_smile:

**Comment by luvalenz** [comment]
Imaginemos que tenemos una mercado AAABBB donde se transan las monedas A (de símbolo AAA) y B (de símbolo BBB). 

Sobre la pregunta sobre monedas "virtuales" y "reales":
No necesariamente la moneda A va a ser una moneda "real" y la moneda B una moneda virtual. Ambas pueden ser criptomonedas, así como también ambas podrían ser monedas tradicionales o una podría ser criptomoneda y la otra tradicional. Lo único que importa es que son contables y transables. Incluso podríamos pensar que son objetos físicos.

Sobre la equivalencia entre hacer ask y bid:
Hacer un ask (oferta de venta) en el mercado de AAABBB y hacer un bid (oferta de compra) en el mercado BBBAAA son operaciones que funcionan de forma diferente, pero tienen el mismo propósito:
 **en ambos casos yo estoy dispuesto a entregar AAA para recibir BBB.***

La diferencia de estas dos operaciones es que al hacer un ask en AAA, yo debo indicar cuál es la cantidad de monedas A que quiero vender y cuantas monedas B quiero recibir **por cada** moneda A. En cambio, al hacer un bid en el mercado BBBAAA yo debo indicar cuántas B quiero recibir y cuántas A estoy dispuuesto **por cada** a entregar por cada *B* que reciba.
