### ISSUE TITLE
Problema: Trailing unparsed en patrón

### ISSUE THREAD

**Issue by danvillablanca** [IIC2233/syllabus#870]
### Prerrequisitos

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Tengo un error en consultas.py que indica: "trailing unparsed: '...' ", donde '...' es el patrón que se prueba.
Probé en https://regex101.com/ el patrón y me funciona, pero en el código en python no. ¿Qué puede estar ocurriendo?

**Comment by aaossa** [comment]
#852 tiene el mismo error, revisaste esa *issue*?

**Comment by danvillablanca** [comment]
¡Hola! Revisé la issue, se resolvió el problema del trailing unparsed, pero ahora tengo otro problema: la consulta no entrega resultados (no genera la lista a retornarse, esta queda vacía). Subí mi código al repositorio.

**Comment by aaossa** [comment]
Difícil poder decir qué es, y no suena a un error específico. Te recomendaría darle una mirada a tu expresión regular y hacer otra *issue* si es que necesario, pero lo que describes suena a algo que deberías hacer tú 😅
