### ISSUE TITLE
Error con intersect()

### ISSUE THREAD

**Issue by Tsbalart** [IIC2233/syllabus#870]
Hola cuando intento importar el comando intersect() me aparece este error:
ImportError: cannot import name 'intersect' from 'PyQt5.QtCore' (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PyQt5/QtCore.so)
Lo estoy importando de esta manera:
from PyQt5.QtCore import intersect

**Comment by TdelrioC** [comment]
Segun yo es porque intersects() es metodo de QRect, que esta en Qtcore, entonces supongo que tendria que importarlo desde ahi, yo ando con un problema parecido

**Comment by rieg-ec** [comment]
Hola, no soy ayudante pero creo que el problema es que intersects() es un metodo de la clase QRect(), la manera de usarlo es recta1.intersects(recta2). Desconozco si hay alguna funcion intersects() fuera de alguna clase de Qt, si es asi ignorame. Espero que te sirva :)

**Comment by fdoflorenzano** [comment]
Hola @Tsbalart,

Busqué y como dicen @TdelrioC y @rieg-ec, el método `intersects` que encuentro no es directamente parte de `QtCore`, si no que es un método de instancias de `QRect`. 
¿Pudiste arreglar tu problema?

Saludos.

**Comment by Tsbalart** [comment]
Gracias a todos! Al final no use esa función, pero me esta funcionando lo que hice por ahora.
