### ISSUE TITLE
Tamaño de ventanas

### ISSUE THREAD

**Issue by rieg-ec** [IIC2233/syllabus#871]
Hola, para ahorrarme arreglar los problemas que trae ajustar el tamaño de la ventana de juego, ocupe ```seFixedSize()```, con lo que ahora el tamaño queda fijo. Mi pregunta es si es valido hacer esto, y cual seria el mejor tamaño (800x600 lo tengo ahora)

**Comment by benjavicente** [comment]
Hola! En el issue #797 se menciona que es válido. En cambio al tamaño, en el enunciado solo se pide almacenar al largo y ancho del mapa en `parámetros.py`. El mejor tamaño queda a criterio de uno, con que el _tamaño de las entidades tengan sentido y interfaz lo más clara y cómoda (dentro de lo posible)_ (#771), está bien.

**Comment by rieg-ec** [comment]
Gracias!
