### ISSUE TITLE
No resulta keyPressEvent pese a setFocusPolicy(Qt.NoFocus) en las combobox

### ISSUE THREAD

**Issue by mmontecino** [IIC2233/syllabus#871]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Intente hacer el override de keyPressEvent dentro de mi QWidget principal y como lei en otras personas que tuvieron problemas, en los combobox les aplique el método setFocusPolicy(Qt.NoFocus). Probé y nada, es más, en el override de keyPressEvent le puse para que me imprimiera la event.key() y tampoco paso nada. Mi Qwidget principal instancia dentro de él a otros. ¿Será este el problema?

**Comment by furcelay** [comment]
Hola @mmontecino !

Por lo que veo tu problema va por otro lado, viendo tu código el método `keyPressEvent` está en la clase `Zona_de_baile` (por favor recuerda el CamelCase 😣 ) pero la ventana activa (la ventana que contiene a todos los widgets y que se encarga de los eventos de teclado) que me parece que es `Ventana_juego` y no tiene definido un `keyPressEvent` y por eso no pasa nada al presionar las teclas. Si no quieres cambiar el modelamiento puedes hacer que el `keyPressEvent` de `Ventana_juego` haga un llamado al de `Zona_de_baile` pasandole el evento.

Espero que eso resuelva tu problema, Saludos!! 😄

**Comment by sofiaolmedos** [comment]
Hola @furcelay 
A mi tampoco me funciona el ```keyPressEvent``` y si lo estoy haciendo el override en la ventana de juego. He intentado de todo pero nada funciona :c

**Comment by mmontecino** [comment]
@furcelay si me di cuenta de eso, me costó, pero muchas gracias!

**Comment by furcelay** [comment]
> Hola @furcelay
> A mi tampoco me funciona el `keyPressEvent` y si lo estoy haciendo el override en la ventana de juego. He intentado de todo pero nada funciona :c

Hola @sofiaolmedos ! 
He estado viendo tu tarea pero el `keyPressEvent` solo tiene un `print` ¿está tu repositorio en la versión más reciente?, si no es así por favor actualízalo para poder revisar que es lo que pasa...

**Comment by sofiaolmedos** [comment]
> > Hola @furcelay
> > A mi tampoco me funciona el `keyPressEvent` y si lo estoy haciendo el override en la ventana de juego. He intentado de todo pero nada funciona :c
> 
> Hola @sofiaolmedos !
> He estado viendo tu tarea pero el `keyPressEvent` solo tiene un `print` ¿está tu repositorio en la versión más reciente?, si no es así por favor actualízalo para poder revisar que es lo que pasa...

El print lo puse para comprobar, porque no me estaba funcionando para la zona de baile.

**Comment by furcelay** [comment]
Me gustaría ayudarte pero no entiendo bien cual es el problema con el `keyPressEvent` 😅 , creo que para no spamear esta issue lo mejor es que abras una nueva en que expliques cual es el problema.
