### ISSUE TITLE
test.py solo me retorna un título

### ISSUE THREAD

**Issue by Rerro-r** [IIC2233/syllabus#871]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! El archivo test.py sólo me devuelve lo siguiente:

```
---------------- Probando CONSULTA consulta_1 ----------------

```

Y eso que, por ejemplo, mi `PATRON_1` es "#".

No sé qué está pasando :C.

**Comment by aaossa** [comment]
Es difícil poder decir exactamente qué es 🤔 ¿No te muestra nada sobre las otras consultas o sobre esa misma? Si llamas manualmente a la función de la consulta, te entrega una lista vacía o nada?

**Comment by Rerro-r** [comment]
@aaossa si llamo a la función sola no me retorna nada. Eso explicaría el por qué el test.py no pruebas las otras funciones?

**Comment by aaossa** [comment]
Es posible, tu función (por ejemplo, `consulta_1`) debería retornarte sí o sí una lista. La lista puede estar vacía o tener 10 diccionarios, pero debe retornar algo.

**Comment by Rerro-r** [comment]
Gracias @aaossa ya arreglé el problema! :D
