### ISSUE TITLE
Error multiherencia

### ISSUE THREAD

**Issue by TdelrioC** [IIC2233/syllabus#872]
Hola, al hacer multiherencia para detectar colisiones tengo el siguiente problema, mesero hereda de mesero heredaba solo de QObject igual como se modela en la ayudantia pero ahora para hacer las colisiones estoy tratando de hacer que hereden de QObject y QRect para poder detectar colisiones con interescts() de QRect, (las mesas y mesones tambien son QRects). El problema esta que cuando trato de hacer super().__init__(x,y,h,w) para dejarlo en las coordenadas  correctas me dice:

Segmentation fault: 11

Pense en manejarlo solo como un QRect igual que las mesas y sillas (que no tienen problemas) pero me sale este problema cuando corro el programa:

TypeError: Mesero cannot be converted to PyQt5.QtCore.QObject in this context

Me imagino que ese error se debe a que las señales son de un QObject entonces no funciona lo que ya tenia armado. Alguien sabe porque pueden ser esos errores y como se puede hacer para que QObject y QRect reciban los mismos x he y cuando se instancie, cosa que las colisiones tengan relacion al mov de el sprite.

**Comment by furcelay** [comment]
Estuve haciendo algunas pruebas y me pasa como dices, no logro hacer que un objeto herede de los dos. Probablemente se debe a como se definen estas clases en PyQt5. 

Lo que puedes hacer como alternativa es utilizar una relación de composición entre ellos (un QObject que contenga un QRect).

**Comment by fdoflorenzano** [comment]
Hola @TdelrioC y @furcelay,

Como mencionan, está complicada la cosa. Efectivamente el problema original es que sería necesario heredar de ambas clases, pero al intentarlo de varias formas me lanza error también. Yo también creo que debe ser un problema de como se implementan estas clases. Una alternativa simple es lo que indica @furcelay, utilizar composición y dejar como un atributo de cada instancia un objeto tal que cada uno herede de distintas clases para manejarlas por separado.

Saludos.

**Comment by TdelrioC** [comment]
Al final tome esa solución y funcióno perfecto para cómo quería hacer las colisiones
Gracias
