### ISSUE TITLE
Distribución de puntajes, envío de señales

### ISSUE THREAD

**Issue by Gustav2000** [IIC2233/syllabus#872]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

**En la distribución de puntajes (celda G4) pide hacer un correcto uso de señales para verificar que el nombre sea alfanumérico. Mi pregunta es si acaso no puedo realizar esta comprobación solo en el frontend de la ventana de inicio ya que es prácticamente sólo una línea o definitivamente es necesario hacer uso de señales?**

**Comment by knight-who-say-ni** [comment]
Holaa @Gustav2000 !!

En todo lo que en la pauta esta de azul se revisará que efectivamente halla un uso correcto de señales, aunque pueda parecer innecesario en ese caso. Recuerda que el frontend y backend deben ir separados, entonces no debiesen haber funciones o metodos que corresponden a uno en el otro 👀 .

Exito en la tarea!!

**Comment by Gustav2000** [comment]
Oka, gracias!!!
