### ISSUE TITLE
Problema al eliminar un Label

### ISSUE THREAD

**Issue by felipehen** [IIC2233/syllabus#873]
actualmente, tengo que los clientes se pueden ir de 2 formas, la primera es cuando ya han esperado mucho tiempo, y activan el método irse(), que prácticamente esconde los label con el método hide() y los saca de la lista de clientes activos que tiene mi programa, ademas de agregar un +1, a la cantidad de "clientes perdidos"

la otra forma, es cuando reciben su comida. en este caso, ocupan el método comer(), que es UNA COPIA del método irse, solamente que agrega un +1 en la cantidad de "clientes atendidos".

mi problema surge, que al activarse el método comer(), se agregan los valores, pero el label no se hace invisible, permitiéndome incluso pasar atraves de el. Para hacer que la imagen desaparezca, tengo que esperar a que el cliente, llegue a su tiempo máximo, ocupando el comando irse(), donde me termina agregando un cliente perdido, incluso cuando ya comió.

para intentar eliminar dicha imagen, e intentado ocupar .setVisible(False), y .hide(), pero ninguna parece funcionar.

**Comment by fdoflorenzano** [comment]
Hola @felipehen,

Es difícil analizar este caso, ya que suena a algo bastante específico. ¿Sigues con este problema? Noté que no has subido ningún avance a tu repositorio hace un tiempo, si subes tu última versión se puede analizar mejor el caso.

Saludos.

**Comment by felipehen** [comment]
Logre solucionarlo, reacribienso el metodo irse(), para que funcione en ambos casos.

Ademas me asegurare de resubir los archivos al sylabus, ya que preferi partir el trabajo de 0, para poder limpiar y mejorar el codigo. (Esto ya lo termine) muchas gracias
