### ISSUE TITLE
Aparecen unos puntitos cuando uso Drag

### ISSUE THREAD

**Issue by kalarconvl** [IIC2233/syllabus#873]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola!! Esta es una duda de un detalle nomas pero acabo de lograr implementar Drag (todavía no el Drop) pero pasa que cuando agarro un objeto draggeable y lo muevo, se mueve con unos puntos como se ve en esta foto (tuve que tomarle foto a la pantalla con el celular porque no sale el objeto que agarro con el mouse en el pantallazo):

![WhatsApp Image 2020-10-27 at 20 14 26](https://user-images.githubusercontent.com/68581172/97372056-75c37380-1891-11eb-8901-5dc1ace5e913.jpeg)

es por como están recortados los png u otro detalle o hice algo mal?

**Comment by kadroguett** [comment]
Hola @kalarconvl probablemente se deba al recorte de los png, de todos modos esto no afectará a la corrección así que no te preocupes por eso.

**Comment by kalarconvl** [comment]
Dalee gracias!
