### ISSUE TITLE
Función descargar_documento en api.py

### ISSUE THREAD

**Issue by luzmagurzua** [IIC2233/syllabus#873]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! :D
En la función descargar_documento de api.py, estoy retornando (para probar mi output) el "texto" que corresponde al documento markdown obtenido (cierto?). Bueno, cada vez que pruebo la función me aparece el número "201" junto con lo siguiente, y quería saber si estaba bien: 

201
```
{'id': 2, 'texto': "# Non ipsam illo\n\n### Doloremque placeat eum inventore alias\n\n## Enim at voluptatum accusamus accusantium eum nam\n\n### **Delectus magni ab sequi reprehenderit**\n\n* Dicta sed\n* Rerum ipsam\n* Similique reprehenderit et ea voluptatem\n* Obcaecati magnam maiores ipsam ea\n* Molestiae quae\n* Quidem hic voluptate quibusdam accusamus\n* Maiores mollitia quam quae minima\n\n### **Dicta facere sequi consequatur**\n\n* [x] Reprehenderit minus ut architecto consequatur\n* [x] Nostrum hic error\n* [ ] Eligendi autem perspiciatis tempora neque\n* [ ] Est excepturi unde magnam praesentium\n* [x] Animi accusantium adipisci nostrum quasi\n* [x] Consectetur\n* [ ] Sed quidem similique\n* [ ] Expedita\n* [ ] Cum\n\n### **Iusto voluptatibus eius deleniti**\n\n| **Modi eum** | **Impedit** |\n|---|---|\n| 4262.940994693592 | Nam aliquam ea id |\n| 5499.616905460174 | Commodi maxime natus deserunt |\n| 7461.677672814583 | Iure |\n| 6297.358753397638 | Pariatur autem debitis |\n| 35965.62357729484 | Cumque a consectetur possimus nobis |\n| 537.7457318385245 | Rerum corrupti |\n| 5440.38401886105 | Possimus |\n| 18675.612562633843 | Corrupti ipsam voluptas dolore magni |\n| 100.79400351403733 | Dolorem eaque nihil error |\n\n<img src='https://picsum.photos/id/140/2448/2448' alt>\n"}
```
A veces me aparece el número "400" pero eso se debe principalmente a que ya he consultado una vez sobre el mismo id o no? 

Gracias.

**Comment by luzmagurzua** [comment]
Quería agregar que no me queda muy claro especficamente esta parte (en amarillo): 

![Captura de Pantalla 2021-07-23 a la(s) 13 35 27](https://user-images.githubusercontent.com/80796978/126820124-20794f5a-eb19-4b72-a828-21bf4df99bd8.png)

**Comment by aaossa** [comment]
Hola @luzmagurzua , creo que estás imprimiendo el código equivocado, o al menos ese código no se relaciona con la obtención del documento. Ambos códigos son esperables en el contexto de un `POST`: `201 (Created)` significa que se creó un elemento en el servidor (esto ocurre cuando te registras en la aplicación), mientras que `400 (Bad Request)` significa que se realizó una solicitud incorrectamente (puede ser que te faltó algún valor esperado o que es un valor inválido, lo que ocurre por ejemplo si el username ya está ocupado). En el caso de la obtención del documento (esta acción es un `GET`), el servidor solo te debería retornar `200 (OK)` si es que ingresaste un identificador válido, pero te entregará un `400 (Bad Request)` en caso contrario.

Sobre tu segunda pregunta, lo que se espera es que uses la respuesta del servidor (la que colocaste en tu *issue* original), tomes el texto y ese *string* lo guardes en un archivo. Ese archivo deberá estar en la ruta `ruta_documento` (puedes asumir que es una ruta válida).

Avísame si algo no se entiende o quedas con otra duda. ¡Éxito con la actividad 🙌!

**Comment by luzmagurzua** [comment]
gracias profe!
Perdón lo de última hora,
pero en la función entregar_consulta me aparece esto: TypeError: in method 'RegEx_findIter', argument 2 of type 'std::string const &'

es un problema con mi función consulta :( y puede significar que lee un símbolo que no reconoce??

**Comment by aaossa** [comment]
La verdad no sé 🤔 Suena a algo de `pyrematch`, pero no sé si @nicovsj alcanza a responder 🤔 Ten ojo con la sintaxis que estás usando por si, como dices, hay un símbolo que estás usando incorrectamente

**Comment by nicovsj** [comment]
Hola @luzmagurzua, no entiendo bien porque te ocurre eso. Me puedes mandar tu consulta a nicovsj@uc.cl? Así te puedo decir si acaso es un error de parte de la sintaxis que estás usando o no.

**Comment by luzmagurzua** [comment]
gracias por sus rápidas respuestas. Ya mande el correo

**Comment by nicovsj** [comment]
Parece todo bien con la sintaxis de tus consultas, sin embargo tu error está diciendo que el type de la variable `texto` que le estás dando a `regex.finditer(texto)` no es el esperado, `texto` debe ser un string.

De hecho, si yo hago `regex.finditer(numero)` siendo `numero` un `int` me aparece el mismo error.

¿Hay alguna posibilidad de que ese sea el problema?

**Comment by luzmagurzua** [comment]
Pucha, si. Puede que le haya estado pasando a la función algo que no era texto, hice media apurada esa parte, pero ya entregúe :( mi cerebro ya no podía más jajajajja

Muchas gracias por toda la ayuda de estos días :)  ! 
Saludos !
