### ISSUE TITLE
"No puedo settear parent en otro thread"

### ISSUE THREAD

**Issue by Gsalinas1506** [IIC2233/syllabus#874]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Estoy modelando mi tarea de forma que la pantalla principal sea un `QWidget`, y que encima de este widget vayan pasando las flechas que son `QThreads`. Con lo que tenía del avance creo que podría modelar almenos una flecha bajando por la zona de ritmo. Basandome igual en lo que puse en mi avance, establecí que el `parent` de estas FlechasThread fuera este mismo Qwidget que era mi ventana principal, sin embargo, al intentarlo me aparece este error:

- `QObject::setParent: Cannot set parent, new parent is in a different thread`

**A que se puede deber?**

PD: por si sirve de algo... mi codigo está pusheado en mi repo

**Comment by jorge-ovalle** [comment]
Me pasa lo mismo no cacho qué onda :(

**Comment by jchamorrou** [comment]
+1

**Comment by JadrinaDA** [comment]
Hola! Gsalinas1506 vi tu código y tu error se debe a que estás mezclando front-end con back-end. En tu QThread misma estas intentando crear un QLabel cuyo padre existe en tu thread principal lo cual causa tu error. Además los labels son algo que el usuario puede ver por lo que pertenecen en el front-end. Lo que debes hacer para corregirlo es que tu ventana cree ella misma los labels que corresponden a las flechas y que los relacione con su objeto QThread (tal vez podrías usar un dict) luego al mover la flecha en el thread puedes mandar una señal a la ventana para que esta misma mueva el label. Así no tendrás un error de threads diferentes y tendrás una correcta separación de tu front-end y back-end. Jorge y jchamorrou creo que su problema debe ser parecido. Avísenme cómo les va y si tienen dudas no duden en mandarlas por aquí. Suerte!
