### ISSUE TITLE
Consulta 6 - Multiples links en una linea

### ISSUE THREAD

**Issue by mdomb** [IIC2233/syllabus#874]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] #875
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Me preguntaba si en la consulta 6 podia existir el caso que puedan haber dos o mas links en una misma linea del documento en Markdown.

**Comment by aaossa** [comment]
¡Hola! Sí, puede darse el caso (como en el documento 20) y su expresión regular debería capturar todos los *links* en una misma línea. Ojo que si una línea tiene dos *links*, en resultado habrán dos elementos que tengan en "contenido" el mismo texto dos veces pero cuyo valor en "posición" sería distinto. ¡Éxito con la actividad 🙌!
