### ISSUE TITLE
Problema con señales entre clases (DropEvent)

### ISSUE THREAD

**Issue by based-on-what** [IIC2233/syllabus#874]
Hola, tengo una duda tremenda, resulta que mientras implemento el evento _Drop_ del Drag and Drop, se emite una señal al momento de soltar la imagen, mediante una clase **X**, y la señal es **A**. Pues bien, cuando emito señales dentro de la misma clase, siendo el _target_ la función **B** (self.A.connect(self.**B**)), no hay problemas, se emite la señal y la función que la recibe actúa correctamente.

Sin embargo, si quiero conectar la señal con una función **C** de la clase **Y**, sencillamente no puedo, en el archivo principal (i.e. el que siempre corro desde la consola) instancio la clase que emite la señal, la conecto de la forma X.A.connect(Y.C) y no hay respuesta, algo sucede entre la emisión y el _target_, y las demás señales conectadas de la misma forma funcionan sin ningún problema.

Saludos y espero su ayuda, gracias.

**Comment by Araos827** [comment]
No se si te sirva pero podrias intentar ir poniendo print(event) en todas las funciones que esten involucradas en la transmision de la señal, asi podras hacerle como un seguimiento a la señal y a lo que se esta transmitiendo y podras ver en que parte se esta cortando la transimision. Luego puedes revisar si te falta o te sobra algun self o si es que alguna funcion no esta recibiendo o utilizando bien los parametros de la señal. Suerte!

**Comment by based-on-what** [comment]
> No se si te sirva pero podrias intentar ir poniendo print(event) en todas las funciones que esten involucradas en la transmision de la señal, asi podras hacerle como un seguimiento a la señal y a lo que se esta transmitiendo y podras ver en que parte se esta cortando la transimision. Luego puedes revisar si te falta o te sobra algun self o si es que alguna funcion no esta recibiendo o utilizando bien los parametros de la señal. Suerte!

Gracias por responder! Eso estuve haciendo todo el tiempo, ahí me di cuenta que el problema recaía en el archivo principal, imprimía cada línea para determinar qué sucedía con la señal, al final me decanté por otro método, pero gracias igualmente!
