### ISSUE TITLE
Drag and drop

### ISSUE THREAD

**Issue by Mario-uc** [IIC2233/syllabus#875]
Aún no entiendo como llevar a cabo esta función, he leido fuentes pero no las entiendo del todo.

**Comment by rieg-ec** [comment]
Hola, te dejo unas pistas sobre como lo hice yo a ver si te sirven (no soy ayudante):

Yo hago drag a un QLabel y drop en un QWidget; para esto hice un custom QLabel con override a la funcion MouseMoveEvent(), y en el QWidget al instanciarlo llamo a setAcceptDrops() con el parametro True. Dentro de la clase QWidget, debes hacer override a la funcion dragEnterEvent() y dropEvent() tambien.

No es muy detallada la explicacion pero googleando esos metodos deberia ayudarte. Esa funcionalidad es parte de las clases, solo debes hacer override a las funciones. Espero que te sirva

**Comment by fdoflorenzano** [comment]
Hola @Mario-uc,

Tu duda no es muy aterrizada como para darte una buena explicación. Es parte de lo pedido en la evaluación que investiguen alguna forma y lo implementen. ¿Cómo te fue desde publicaste esta *issue*?

Gracias a @rieg-ec por la cuidadosa explicación. Muchos de los métodos que se encuentran buscando en la web siguen esa idea y suele funcionar bien. También la recomiendo.

Saludosl
