### ISSUE TITLE
Cheatcode N + I  + V

### ISSUE THREAD

**Issue by totoiii** [IIC2233/syllabus#875]
** Es obligatorio que el cheatcode N + I  + V funcione si el juego está pausado?**
Es que tengo implementado que este cheatcode funcione solo si las flechas estan andando, y nose si es necesario que lo cambie

**Comment by kadroguett** [comment]
Hola @totoiii, en el enunciado no se explicita que deba o no funcionar en pausa así que puedes dejarlo a tu criterio siempre y cuando lo explicites en tu Readme.
