### ISSUE TITLE
Problema intersectando flechas con frames

### ISSUE THREAD

**Issue by YehudaGurovich** [IIC2233/syllabus#876]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Proveniendo de la issue #844, hago mi consulta.

Estoy utilizando el método intersects y no estoy seguro por que no me cambia el color del background cuando se intersectan. Las señales estan bien conectadas dado que al colocar un print en el método se imprime, pero nunca entra en el if flecha.geometry().intersects(frame.geometry()): por lo que sospecho que no se está actualizando la posición de la flecha en tiempo real, pero no se por qué pasa (quizá es algun .emit() mal puesto, pero no logro encontrar el error). 

**Update: He cambiado mucho desde lo mencionado. La parte de emisiones y señales está bien. Agregare los problemas que tengo en este momento.**
1. Los espacios (qframe) que estoy comparando con las flechas (qlabel) tienen su geometry() relativo al qframe al que pertenecen y las flechas (qlabel) absoluto a la ventana completa. Esto produce que las intersecciones no sean en el lugar correcto sino que mas arriba. ¿Hay alguna forma de colocar los geometry() de un qframe en otro y se mantengan absolutos a la posición de la ventana?. 
2. Con los nuevos cambios los qframes cambian de color titilando al tener varias flechas en la misma columna. Dado que según una flecha hay intersect y debería cambiar de color pero según la otra no debería entonces cambia entre un color y el otro por cada unidad de tiempo posible. Hay alguna funcion que retorne un *bool* sobre si es de cierto color un frame o no?

Ya hice git push (lo menciono porque en algunas issues piden que hagan git push)
El error deberia estar en *logica_ventanas.py* clase Juego y/o *juego_window.py* en las funciones intersectan y recibir_interseccion respectivamente. (correr el programa en el main, donde también se conectan las señales)

**Comment by furcelay** [comment]
Hola @YehudaGurovich !

Respondiendo a tus dudas:
1.  Lo que puedes hacer es cambiar la posición del `QRect` del `QFrame` antes de la intersección (solo mover el `QRect`, no el `QFrame`) tal que su posición sea relativa a la ventana. Suponiendo que tienes un atributo con este frame, supongamos que es `self.frame` y que está contenido en otro frame que ese sí está contenido por la ventana, lo que puedes hacer es:
```python
rect = self.frame.geometry()
rect.translate(self.frame.parent().pos())
```
Con eso trasladamos el `QRect` de tu frame sumándole la posición de su *parent* que por tu explicación me parece que sí es relativo a la ventana. Luego puedes obtener la intersección como `rect.intersects(flecha)`

2. Creo que estás confundiendo lo de los cambios de color en la tarea con el avance. En la tarea el color de la *zona de captura* cambia cuando presionas la tecla correspondiente, no cuando la flecha pasa por ella. Si la flecha pasa cuando presionas la tecla correspondiente esta desaparece, en otro caso sigue de largo sin que pase nada. De todos modos te recomiendo cambiar este comportamiento después de arreglar el punto 1 porque ver el cambio de color cuando pasa la flecha te servirá para ver si la intersección es correcta.

Espero haber resuelto tus dudas, Saludos!! 😄

**Comment by YehudaGurovich** [comment]
@furcelay Gracias! Logré implementar lo del punto 1. Ahora me pondré a revisar el tema de los eventos para luego cambiar el color solamente si se apreta la tecla! Gracias.
