### ISSUE TITLE
Animacion Presidente

### ISSUE THREAD

**Issue by nachobascar** [IIC2233/syllabus#876]
Hola, tengo una duda sobre el bonus del presidente,
¿Este también tiene que presentar un cambio en su sprite al pasar la mitad del tiempo de espera? Ya que solo hay una sprite en los entregados.

**Comment by jitorcas** [comment]
Hola @nachobascar!

Se espera que sea al igual que cualquier otro cliente, pero con funcionalidades especiales. Por lo anterior, **se debería** ver un cambio en el *sprite* al pasar la mitad del tiempo de espera. Al ser un bonus, podrías editar el *sprite* entregado y agregarle alguna diferencia en su aspecto, existen muchas páginas web donde puedes editar un *sprite*, también lo puedes hacer con Photoshop o buscar alguna *sprite* en internet que tenga relación con el presidente. 
En caso de utilizar otras *sprites* deberás **especificarlo** en el readme y subir una carpeta extra (diferente a la entregada) con los *sprites* adicionales.
