### ISSUE TITLE
Probar las funciones de api.py

### ISSUE THREAD

**Issue by Rerro-r** [IIC2233/syllabus#876]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Holi! ¿Qué pasa si pruebo las funciones de api.py? Esto perjudicaría la corrección? porque ya podría estar registrada como alumna en la api o da lo mismo?

**Comment by aaossa** [comment]
@Rerro-r dale no más, pruébalas. Después importaremos las funciones y le daremos nuestros propios *inputs*. Eso sí, si quieres probar la función en el mismo `api.py`, recuerda utilizar `if __name__ == '__main__':` para que no se ejecute tu código de prueba a la hora de importar las funciones 👌

**Comment by Rerro-r** [comment]
どうもありがとうございます 💞 
Dōmo arigatōgozaimasu 💞
