### ISSUE TITLE
Argumentos de entregar_consulta

### ISSUE THREAD

**Issue by Rerro-r** [IIC2233/syllabus#877]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Holuu (voy de nuevo). Al ejecutar entregar_consulta con el primer doc del api me devuelve lo siguiente:

`{'message': "El valor de 'respuesta' debe ser una lista"}` 

siendo que el valor de `respuesta` es el siguiente:

`[{'contenido': 'Aut voluptas vitae cupiditate quas atque architecto', 'posicion': (2, 53)}]`

Y todos los otros argumentos igual se los doy como debería unu. AiUdA p0r fAv0r.

**Comment by aaossa** [comment]
Quizás sea lo mismo que #853 , ¿podrías darle una mirada? y me dices si es?
