### ISSUE TITLE
ventanas diferentes

### ISSUE THREAD

**Issue by Aloncarrasco** [IIC2233/syllabus#877]
Puedo hacer que la ventana pre ronda y la ventana de ronda sean ventanas diferentes 
(respetando que las 2 muestren lo que tienen que mostrar)

**Comment by danckoo1** [comment]
hola! efectivamente puedes, tan solo recuerda ocultarlas y hacerlas aparecer cuando corresponda, cosa que el flujo no se vea afectado.
saludos
