### ISSUE TITLE
Imagen del Drop sí es aceptada pero no se ve

### ISSUE THREAD

**Issue by kalarconvl** [IIC2233/syllabus#877]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Estoy implementando el Drop y me pasa que cuando suelto la imagen de un pinguino o de un puffle en la pista de baile, el código sí lo acepta (comprobado con prints de que entra a las funciones respectivas y no entra cuando pongo un pinguino encima del otro) pero no se ven, es como si las imagenes se hicieran invisibles.

**Comment by JuaniAndres** [comment]
Una duda en que parte hay que ubicar la carpeta de sprites?

**Comment by kalarconvl** [comment]
T02/frontend/sprites/...

**Comment by JuaniAndres** [comment]
Lo que menciones pasa porque falto aplicarle un ````.show()```` a la QLabel que estas agregando a la pista. La razón es porque cuando ocupas show a la ventana todos los elementos dentro de esta también se les aplica el show pero si agregaste un elemento después del show de la ventana tienes que aplicarle manualmente el show a cada elemento nuevo para que se vea.
Un detalle que note ojo con los límites del área para drop porque si pones un pingüino muy abajo aparece cortado.
Me avisas si sigues con problemas 
Éxito con la tarea 😄

**Comment by kalarconvl** [comment]
Yaa ahí me funcionó! Gracias!! Pero solo me deja poner 2 pingüinos, es por temas de espacio? Y no sé si también te pasó pero el a medida que pongo pingüinos, la imagen sale con con cosas al fondo así:

![WhatsApp Image 2020-10-27 at 20 14 26](https://user-images.githubusercontent.com/68581172/97377605-34d25b80-189f-11eb-8bf3-abaab2947bf4.jpeg)

**Comment by kalarconvl** [comment]
Y otra cosa, que los pinguinos salgan cortados bajará la nota? Ni idea cómo puedo arreglarlo

**Comment by JuaniAndres** [comment]
Respecto a lo primero, no tuve problemas para poner más pingüinos y ese detalle que pasa en el drag no importa probablemente se deba a algo con la imagen png.
Respecto a lo segundo, si podría afectar pero la razón de que aparecen cortados es porque tus Qlabels de pingüinos están contenidos en tu label DropPistaBaile por lo que si alguna label de pingüino se sale del tamaño de de la DropPistaBaile se va a ver cortado.
Ojo también que almenos para mi no se están respetando las separaciones entre pingüinos para que también revises el tema de la intercesión para esto te recomiendo poner un par de prints para revisar en que if esta entrando tu código.
![t](https://user-images.githubusercontent.com/48482216/97378794-ff7b3d00-18a1-11eb-8a18-44c40188f0c3.PNG)
