### ISSUE TITLE
Orden de la lista

### ISSUE THREAD

**Issue by Rerro-r** [IIC2233/syllabus#878]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Holiu, hay veces que la lista de diccionarios me entregan los valores correctos pero en orden "de abajo para arriba" en el texto original y no en el orden natural de lectura, ¿lo debería arreglar?

**Comment by aaossa** [comment]
@Rerro-r  no debería afectar. Para confirmar, puedes utilizar la última función de la sección de API, donde puedes enviar tus respuestas al servidor y te dirá si están bien 👌 Recuerdo haberlo hecho de tal forma que le da lo mismo el orden de los elementos
