### ISSUE TITLE
Problema con señales

### ISSUE THREAD

**Issue by sebadelorenzo** [IIC2233/syllabus#878]
Hola, estoy ocupando una señal para actualizar el frame del chef mientras cocina y lo estoy haciendo a través de una señal del AI tal como se hizo en la ayudantía 8 (con señales para actualizar posición de mortys o la jeringa). El problema que estoy teniendo que al crear el atributo en la clase Chef que guarda la señal entregada por el AI, lo coloco como "None" tal como la ayudantía y luego cuando emito la señal utilizando el atributo me aparece que es un NoneType (lo cual encuentro lógico debido a que se definió así) y no puede emitir la señal.
Me pregunto por que en la ayudantía si funciona y cómo lo hace. Estoy haciendo algo mal? Algo me falta? 

Por otro lado, tengo otra señal que me esta fallando que tiene que ver con un QTimer. Al hacer timer.timeout.connet(metodo) no esta llamando al método por lo que no pasa nada. Probando de todo descubrí que al emitir un parámetro para la cual no esta diseñada (ej. la señal es para bool, pero al emitir escribo un string) se logra llamar al método con el timeout. No se si se entiende bien, ni yo entiendo bien que esta pasando y he intentando de todo y he buscado mucho y no logro encontrar porque se comporta así. Ayuaaaa :(

**Comment by tomasgv** [comment]
Hola @sebadelorenzo !!

Sobre tu primera duda, es probable que no estés cambiando el valor del atributo que debería tener la señal antes de emitirla o conectarla. Si te fijas en el código de la ayudantía, en el método `create` de la clase `AI`, se crea una instancia `Morty` y justo después se le asigna la señal a su atributo correspondiente.

Sobre la segunda, si al `QTimer` le entregas `self`, defines su duración, conectas el método que se llamará al llegar a `timeout` y lo activas usando `start()`, el problema tal vez no sea respecto a esto, sino con la señal que está activándolo. El caso de emitir un parámetro erróneo suena curioso, pues el programa debería detenerse levantando un `TypeError`. En caso de que sigas con este problema, agrega un comentario y revisaré tu código en busca de posibles causas :+1:

Saludos! ☕ 🐱

**Comment by sebadelorenzo** [comment]
gracias pude resolver la primera duda, pero todavia tengo problemas con el Qtimer

**Comment by tomasgv** [comment]
Traté de ejecutar tu código, pero se caía debido a otros errores 😔  (puede que estés haciendo cambios en este momento). 

Por lo que pude observar, quieres hacer que cuando el `QTimer` de la clase `Cliente` llegue a su fin, se emita cierta señal a través del método `enviar_dato`. Sin embargo, la señal que hace `emit` no está conectada. Noté que existe otra señal que sí lo está, pero nunca hace `emit`. ¿Será ese el problema?

¡Quedo atento! :eyes:
