### ISSUE TITLE
Bonus 9.3 Configuración de Parametros

### ISSUE THREAD

**Issue by raimundomartinez** [IIC2233/syllabus#879]
Hola! Tengo unas con este bonus. Primero, ¿la idea es que uno reescriba el documento python? Es decir, que los nuevos parámetros queden guardados en el script. Si es así, ¿Tienen algún consejo para implementar esto?

**Comment by furcelay** [comment]
Las librerías `pickle` y `json` sirven para eso, pero están entre las librerías prohibidas, entonces asumo que se busca que lo hagas a la antigua (leer el archivo y reescribirlo).

**Comment by jitorcas** [comment]
Hola @raimundomartinez!

Primero, la idea del bonus es que para modificar los parametros del juego no se deba hacer directamente desde el archivo `parametros.py` si no que a través de una interfaz.
Dicha interfaz deberá escribir en el archivo `parametros.py` y guardarlos solamente si el usuario presiona el botón **guardar**.

La manera en que lo hagas queda a tu criterio siempre y cuando utilices librerías que estén permitidas. 

Éxito!

**Comment by kipasten** [comment]
Hola, tengo una duda con este mismo tema porque pude implementarlo todo bien menos el hecho de que se vuelvan a importar con los parametros nuevos, es decir, si cambian los parametros, habria que cerrar y volver a abrir para ver los cambios aplicados...
Mi pregunta es:
¿Cómo se pueden actualizar los parametros con el programa funcionando?

**Comment by jitorcas** [comment]
Hola! @kipasten 

Puedes considerar las dos maneras descritas en el comentario para implementar tu bonus. https://github.com/IIC2233/syllabus/issues/680#issuecomment-637018521
