### ISSUE TITLE
No se presionan los botones en mac

### ISSUE THREAD

**Issue by Krmn390** [IIC2233/syllabus#879]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

No se si otras personas que usan macOS han tenido el mismo problema, pero en mi caso, despues de correr una cierta cantidad de veces mi codigo, los botones de todos mis menús dejaron de funcionar (parecen una imagen, no puedo presionarlos). ¿Por qué pasa esto? ¿tiene que ver con el hecho de que uso qt designer, o que uso mac? ¿O ambos?

pd: sin resolver esto no podré realizar mi tarea ;c pls send help

**Comment by JuaniAndres** [comment]
Hola @Krmn390 
Podrías subir tu código a tu repositorio para revisarlo

**Comment by Krmn390** [comment]
listo, lo acabo de subir

**Comment by Krmn390** [comment]
por cierto, mi codigo no esta para nada listo. Aunque me basta con hacer que los botones funcionen para poder seguir programando (;( de verdad te lo agradecería mucho!)

**Comment by JuaniAndres** [comment]
Revise tu código y  según lo que puedo ver los botones de la ventana de inicio funcionan correctamente. El boton de ranking permite  ir a la ventana de ranking pero el de comenzar gatilla el metodo click_button_comenzar pero no produce cambio probablemente por el codigo que dejaste comentado más por el lado de lo que gatilla la senal_nombre. Si quieres probar si esta funcionando correctamente el click agrega un print dentro del metodo al cual estas conectando el clicked por ejemplo en tu caso agregar un print dentro de click_button para revisar si eso se esta activando.
Prueba lo del print y me avisas si sigues con problemas

**Comment by JuaniAndres** [comment]
Encontré otro detalle ten cuidado que por ejemplo en la clase de Logica_del_juego te falto llamar al init de QObject ósea usar por ejemplo ````super().__init__()```` ya que si no realizas esto no obtienes lo que te entrega QObject como por ejemplo poder usar señales de pyqt5

**Comment by Krmn390** [comment]
ok ok, gracias por revisarlo! ver esos detalles
En cualquier caso, es un poco fome el tema de los botones porque no puedo probar mi codigo en mi computador: aun nada funciona aqui. Parece que es un tema de los mac (clásico). Ojala nos dieran mas tiempo porque programar a ojos cerrados realmente es dificil :|

**Comment by JuaniAndres** [comment]
Como te fue @Krmn390 ?
Otra idea que me dieron para descartar que sea un problema de mac es que pruebes correr alguna de las ventanas de los ejemplos de los contenidos que tenían botones para ver si te funcionan correctamente.
Me avisas cualquier cosa

**Comment by Krmn390** [comment]
Es que si puedo. He podido comer los ejemplos hasta ahora, pero no puedo probar mi codigo. No he podido desde el segundo dia de edición.

**Comment by Krmn390** [comment]
*correr jaja

**Comment by JuaniAndres** [comment]
Si quieres y puedes escríbeme por discord antes de las 1 para que me puedas mostrar lo que te esta pasando. Porque si te corren los ejemplos es más probable que sea un detalle en tu código como los que te mencione antes que un tema con mac

**Comment by JuaniAndres** [comment]
Ahora no voy a estar conectado por discord pero si quieres sube tus archivos a tu repositorio para revisarlos denuevo a ver si encuentro algún detalle que te siga dando problemas. Me parece igual raro que no te funcione ningún botón porque  probamos tu código del repositorio con mac. Lo que vimos era que botón de ranking no tenia ningún problema y el de comenzar no funcionaba por los detalles que te dije antes. La mejor herramienta que te puedo recomendar para ir viendo si los métodos se están llamando es poner algunos prints para que se impriman cosas en tu consola. Revisa esos detalles, prueba poniendo print a los métodos que conectas a clicked de tus botones y recuerda que para que las señales puedan interactuar con alguna clase,  la clase tienen que haber heredado de alguna clase de pyqt5 (es importante que llames al ````super().__init__()```` para que la herencia se haga correctamente) Lo ultimo si estas muy complicada con la entrega siempre puedes mandarle un mail al jefe de bienestar (bienestar.iic2233@ing.puc.cl) o al mail del curso planteando tu caso para ver alguna posible solución.
Quedo atento

**Comment by Krmn390** [comment]
Gracias por toda la ayuda pero creo que ya estoy un poco tarde. Llevo toda la semana ocupada con pruebas y asuntos personales pero bienestar no me pudo dar mas plazo para hacerla. 
Con respecto al tema de los botones, hoy mismo en la mañana estaba editando mis ventanas en Qt Designer y mi computador me tiró un Kernel Panic, luego se reinicio. Esto me ha estado pasando desde hace un tiempo, durante algunas pruebas, o cuando uso ciertas apps como R o VSCode. Me imagino que esta falla de los botones tiene que ver con este problema, que es solo de mi computador. Es fome porque desde que empecé que no he podido probar mi codigo.
He pasado días tratando de configurar mi cuenta git en el computador de mi hermana pero aún no logro nada (es muy lento y es window... no me acuerdo como usarlo).
Debo admitir que esta semana la he pasado muy mal por el tema de esta tarea, pero considero que una buena nota no merece mi salud mental ni estado anímico. Así que voy a seguir trabajando per sin mucha confianza de lo que saldrá de mi tarea.
Voy a estar conectada a Discord el resto de la tarde hasta la hora de entrega. Sinceramente, no se bien como usar Discord, así que cualquier cosa, soy Carmen usb#0870. Si pudiéramos hablar cortito sería bakan

**Comment by Krmn390** [comment]
Lol leí mal la primera frase. filo. Gracias igual.

**Comment by JuaniAndres** [comment]
Hola @Krmn390 
Lamento escuchar que tu semana a estado muy terrible. Como mencionas es más importante siempre tu salud y animo que la nota de la tarea así que no te preocupes si no logras terminar la tarea como querías. Igual todo lo que alcances a hacer va a sumar puntaje por lo que no es en vano y esta no es la ultima evaluación por lo que siempre se puede dar la vuelta.
Respecto a los problemas que estas teniendo con tu computador como no conozco mucho de mac estoy tratando de conseguirme a alguno de los ayudantes que tenga mac para que pueda ayudarte a ver que puede estar pasando. No te aseguro que encuentre uno disponible antes de que se acabe la tarea pero por ultimo puede igual servir para que no tengas el mismo problema para la próxima tarea. Cualquier cosa probablemente te hablemos por discord.
Mucho animo y sigo atento si te puedo ayudar con otra cosa

**Comment by Krmn390** [comment]
gracias :,)
