### ISSUE TITLE
Aumento de Tasa de minerales

### ISSUE THREAD

**Issue by felipe8797** [IIC2233/Syllabus#88]
Si el usuario quiere subir la tasa de producción en más de 10 esto es permitido? Podría aumentarla en 10000 unidades, o tiene como límite 10?

**Comment by Hernan4444** [comment]
@felipe8797 tal como dice tu compañero, las modificaciones no pueden superar la capacidad máxima, eso incluye el rango de las tasas.
Saludos ✌️
