### ISSUE TITLE
Incongruencia distribución de puntaje con enunciado en carta de bebestibles

### ISSUE THREAD

**Issue by FranciscoPinto1138** [IIC2233/Syllabus#88]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, tanto en el enunciado como en la distribución de puntaje (excel) aparece que se debe chequear si el jugador tiene suficiente dinero para comprar un bebestible. Sin embargo, en el excel se indica que cuando este no es el caso se debe volver a mostrar la carta de bebestibles, mientras que el enunciado dice que se debe volver al menú anterior (Menú principal). ¿Con qué opción debería quedarme? Sobre esto mismo, también aparece que se debe poder volver al menú de inicio, al principal y salir del programa, mientras que el enunciado no dice nada al respecto. Gracias :)

**Comment by antoniablanco** [comment]
Sobre volver a los menues necesarios siempre se debe poder volver. La pauta con la que los ayudantes corregimos es el excel asi que te recomiendo guiarte por lo que aparece ahi.
