### ISSUE TITLE
Mis funciones no se quieren llamar

### ISSUE THREAD

**Issue by batfido** [IIC2233/syllabus#88]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Tengo un gran problema usando modulos para resolver la tarea. Siguiendo los lineamientos dados en los contenidos del curso cree varios modulos atingentes a la solucion de la tarea, la mayoria con definiciones de funciones que son llamadas desde un modulo diseñado para correr el programa. Ahí es donde empieza mi problema, al probar las funciones en sus respectivos modulos estas funcionan como esperaria, pero al pedirles que llamen a una funcion que no se encuentra en su modulo original (habiendo sido ya importadas al modulo actual desde todos los modulos las funciones usadas).

Si dentro de la definicion de una funcion tiene que llamar a otra que esta en otro modulo me da error de tipo <funcion> not defined Esto a pesar de que la funcion llamada esta importada en el modulo. Este problema me tiene estancado ya que si bien tengo las funciones, no las puedo hacer correr y no logro entender que esta mal :sob: 
Gracias de antemano :pray:

**Comment by IgnaciaJ** [comment]
Hola @batfido, revisa si estas llamando a las funciones correctamente dentro de los otros módulos. Si no hay problema con eso, puedes subir tu avance a tu repositorio?
