### ISSUE TITLE
importar variable de otro programa

### ISSUE THREAD

**Issue by agustin18638937** [IIC2233/syllabus#88]
en un programa (1) tengo una variable supongamos a=input() , despues de ejecutarlo y darle un valor a "a" redirecciono a otro programa (2) donde para llevar la variable "a" del programa (1)  al programa (2) pongo: from programa(1) import "a".
Sin embargo, al ejecutar el programa (2) con la variable "a" me pide que haga un imput otra vez, ¿como podria solucionar este problema?

**Comment by KnowYourselves** [comment]
Hola @agustin18638937!

Antes de responder tu pregunta, a que te refieres exactamente con redireccionar?

Quedo atento!

**Comment by agustin18638937** [comment]
pongo:
exec(open("programa(2).py").read( ))
cuando llego a ese programa me pide un input otra vez (siendo que lo ingrese en el programa 1).

**Comment by KnowYourselves** [comment]
En primer lugar, si revisas la issue #4 te podrás ver que `exec` esta **completa y absolutamente prohibido.** Por qué?, puedes revisar [esta issue](https://github.com/IIC2233/syllabus-2019-2/issues/63) del semestre pasado donde hay una buena explicación.

Para entender por qué sucede el comportamiento que describes analicemos el flujo del código:

1. Se ejecuta `programa(1)`.
2. Se llega a la linea `a = input()` y se pide _input_ al usuario.
3. Se llega a la linea `exec(open("programa(2).py").read( ))`.
4. Se ejecuta `programa(2)`.
5. La primera linea que se ejecuta es `from programa(1) importa a`. El tema es que al hacer un import de cualquier tipo **se ejecuta el programa importado**, es decir, ahora se ejecuta `a = input()` nuevamente.

Es por esto que se pide _input_ dos veces. Ahora la recomendación es **no utilizar exec y eval**. En tu caso, si quieres pedir _input_ "desde otro archivo" puedes hacer la siguiente modelación:

**Programa 1**
```python3
def pedir_input():
    input_usuario = input()
    # Aqui se podrían agregar más pasos o lógica extra.
    return input_usuario
```

**Programa 2**
```python3
from programa_1 import pedir_input

# Con esta linea podemos pedir input con una funcion
# definida en otro archivo python.
input_usuario = pedir_input() 
```

Espero te haya ayudado y quedo atento a cualquier duda!
