### ISSUE TITLE
Partida ganada

### ISSUE THREAD

**Issue by pgaguilera** [IIC2233/Syllabus#88]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Si un usuario gana una partida ¿esta debe guardar las posiciones de bestias y descubiertas del tablero? si cargo esa partida ¿debo mencionar que el juego fue completado?

**Comment by Juampisaez** [comment]
Holaa 👋 @pgaguilera 
Ese punto es algo que no está especificado en el enunciado. De igual forma, tiene sentido que en caso de ganar solo se guarde el puntaje y no una partida, ya que el juego ya finalizó.

Quedo atento si surgen más dudas 👀
