### ISSUE TITLE
Id's de civilizaciones

### ISSUE THREAD

**Issue by catorres8** [IIC2233/syllabus#88]
Podemos estar seguros de que en el archivo civilizaciones.csv, estas siempre tendrán el mismo id??
Es decir, que si hago:
```
print(DCC.id)
print(Comarca.id)
print(Cobreloa.id)
```
Siempre voy a obtener:
```
0
1
2
```

**Comment by iqacevedo** [comment]
Hola @catorres8 

No puedes asumir eso. El id de una civilización puede cambiar en el archivo.

**Comment by MartinAracena** [comment]
Significa eso que pueden modificar su archivo y modificar el numero de civilizaciones que hay? 
Digamos como inventar una nueva civilización que se llame DCCD y que ahora en el archivo de inicio hayan 4 civilizaciones, ademas de esto cada una con cualquier numero de id?

**Comment by quememo** [comment]
si el id puede cambiar, es correcto asumir que el tipo (Ejemplo: tipo=Cobreloa) nunca cambiará?

**Comment by iqacevedo** [comment]
En general todo puede cambiar dentro de los archivos. Lo que puedes tener seguro es que el tipo será uno de los indicados en el enunciado.
