### ISSUE TITLE
Que pasa si tengo modelacion circular?

### ISSUE THREAD

**Issue by ptflores1** [IIC2233/Syllabus#88]
Que pasa si en mi tarea recurro a modelacion circular ?

**Comment by andresfdezc** [comment]
En la [ayudantía de esta semana](https://github.com/IIC2233/Syllabus/blob/master/Ayudantias/S02%20-%20Herencia%20y%20Clases%20Abstractas/S02%20-%20Herencia%2C%20Polimorfismo%20y%20Clases%20Abstractas.ipynb) dejamos [esta referencia](https://github.com/IIC2233-2016-1/syllabus/issues/481) al respecto

**Comment by andresfdezc** [comment]
En resumen, no lo hagas. ¿Qué va a pasar? Va a funcionar bien por un rato, después todo se complicará.

**Comment by ptflores1** [comment]
mmm... en general me encuentro con problemas del tipo "La clase A sabe que tiene instancias de la clase B pero la clase B no sabe a quien pertenece" como debería resolver este tipo de problemas si quiero que la clase B sepa a quien pertenece?

**Comment by rihanuch** [comment]
que pasa si ya hice el grueso de la tarea de esa forma y me funciona sin problema de forma extensiva? cambiar los métodos me implicaría rehaecer gran parte del código 😭

**Comment by sebacruzd** [comment]
Espero que con lo siguiente salgas de ese problema. @ptflores1 
Imaginemos que la **clase A** tiene el _atributo b,_ que es una _instancia_ de la **clase B**


```python
class B:

    def __init__(self, atr1, *args):
        self.algun_atributo_de_b = atr1
        ...

    def algun_metodo_de_b(self):
        print("hola, vengo desde la clase B")


class A:

    def __init__(self, objeto_b, *args):
        self.b = objeto_b
        ...

    def algun_metodo(self):
        datos = self.b.algun_atributo_de_b
        self.b.algun_metodo_de_b()

    def metodo_de_a(self):
        print("Hola, vengo desde la clase A")

```

Ahora, como el objeto de la clase B está contenido (como atributo) en una instancia de la clase A, no es necesario que el objeto B sepa donde está, ya que la instancia de la clase A está llamando a los métodos de la clase B.

**Comment by rihanuch** [comment]
se que en la practica no se da casi nunca esto, pero en esta tarea no sería lógico pensar que mi orden esta asociada a un usuario?

algo así como:

class Usuario:

    def __init__(self, *args):
        self.lista_con_ordenes_creadas_por_este_usuario = [orden1,orden2,...,ordenN]
        self.atributo = 0


class Orden:

    def __init__(self, creador=None, *args):
        self.creador = Usuario
        ...

    def restar(self, valor):
        self.creador.atributo -= valor

Digo que sería lógico hacerlo en este caso, ya que la orden es creada por alguien, y al hacer un match (por ejemplo), debe sumarle el dinero ganado, por lo que yo a través de la orden accedo a mi usuario y le hago un cambio 😖 🤔

**Comment by sebacruzd** [comment]
Hola, eso es referencia circular y no está permitido :cry: 
Deberás modificarlo para que no ocurra, no debería ser tan difícil modificarlo para eso. Es cosa de mover los métodos desde una clase a otra y ajustar desde dónde salen los atributos.
O también podrías cambiar todo, ya que si modificas todo lo que ya tienes podrías generar bugs y no darte cuenta.

**Comment by rihanuch** [comment]
En ninguna parte salia que no estaba permitido 😭 
El problema es que no es que yo utilice los atributos del Usuario en la orden, sino que al comprobar el match hago:


class Mercado:
    def __init__(*args)
        lista_ask = []
        lista_bid = []
       #atributos de clase

def match(self):
#parte del código
       for orden_a in self.ask:
            for orden_b in self.bid:
                if orden_a.price <= orden_b.price:
                    if orden_a.amount <= orden_b.amount:  # bid mayor en precio y cantidad
                        cant_gan_a = ora.price * ora.amount - self.tasa * ora.price * ora.amount * 
                      ....

**Comment by sebacruzd** [comment]
Tienes razón, no fue prohibido, por lo que **está permitido** para esta tarea excepcionalmente :smile: .
Eso sí, cualquier error o problema que esto genere sí influenciará en la nota de la tarea, por problemas de modelamiento.

De todas maneras, se **recomienda fuertemente** hacerlo sin referencia circular, ya que estarán programando de mejor manera.

**Comment by rihanuch** [comment]
ok! Mil gracias!!!!! 😄 😄 🎉 🎉

**Comment by rihanuch** [comment]
Me surgió una duda, si a la clase orden tiene como atributo el balance que tiene el usuario, eso sigue siendo modelacion circular?

**Comment by nebil** [comment]
Las referencias circulares forman parte de los no-tan-amigables colmillos de [:snake:](https://www.python.org/). Y como bien mencionó @andresfdezc, es posible que el programa funcione pero, por experiencia propia, cuando el _software_ va creciendo, es probable que cada vez sea más difícil agregarle nuevas funcionalidades. Además, mirando esto desde un punto de vista de la _ingeniería de software_, las referencias circulares provocarán que los módulos sufran de un [**alto acoplamiento**](https://en.wikipedia.org/wiki/Coupling_(computer_programming)), lo que **no es una característica deseable**. Ahora, para resolver algo así, es aconsejable rediseñar el código y las interacciones entre sus distintas piezas.

Ahora @rihanuch, volviendo a tu ejemplo, sí me parece bastante razonable que tus usuarios mantengan la información acerca de sus órdenes. Y si bien comprendo cuáles son tus razones para que una orden _conozca_ a su dueño, siento que, conceptualmente, no es _tarea_ de la orden cambiarle el dinero al usuario. Una orden es simplemente una orden. ¿Por qué habría, entonces, de meterse en el bolsillo de su dueño? **A primera vista**, yo no crearía este enlace bidireccional. Y luego, para calcular y actualizar el balance de los usuarios, podría, por ejemplo, iterar por cada orden que tiene un usuario, viendo cuáles están activas y cuáles ya hicieron _match_. A partir de esto, obtendría el saldo del usuario.

> Me surgió una duda, si a la clase orden tiene como atributo el balance que tiene el usuario, eso sigue siendo modelacion circular?

Sí, pienso que eso todavía seguiría siendo modelación circular, puesto que si es que la clase `Usuario` y la clase `Orden` vivieran en módulos diferentes, ambos tendrían que hacer un `import` del otro.

---

Por último, para aprender más acerca de los problemas de las referencias circulares, les sugiero estudiar lo que se discutió en #88. Así es, este horrible chiste también hace parte de las nefastas secuelas que las referencias circulares dejaron en mi mente. :roll_eyes:

**Comment by rihanuch** [comment]
Gracias! Como dato nomás, en mi caso ambos viven en módulos diferentes! Solo que le paso como argumento opcional el creador, o en este caso el balance 😁
