### ISSUE TITLE
Subir Tarea

### ISSUE THREAD

**Issue by DiegoPibe** [IIC2233/syllabus#88]
hola !! subi todos los archivos que necesita mi tarea, pero ahora no me deja subir la tarea, pongo :

$ git add Tarea0_ProgramacionAvanzada
fatal: pathspec 'Tarea0_ProgramacionAvanzada' did not match any files

no se que hacer :C

**Comment by gatochico** [comment]
Hola! Puedes mandar pantallazos de tu repositorio con la tarea, y luego de la consola al momento de ocurrir el error?

**Comment by DiegoPibe** [comment]
lo logreeeeeeeeee... gracias de todos modos, casi me mato.
