### ISSUE TITLE
Autonomia Helicopteros Enunciado Tarea 1

### ISSUE THREAD

**Issue by FJavierOss** [IIC2233/Syllabus#88]
Tengo una duda respecto a los helicópteros, porque estuve revisando "recursos.csv" y habían muchos helicópteros que tenían una autonomía de "0". Eso implicaría que en términos de código esos helicópteros están inoperantes, ¿esto es un error o se suponía que debía ser así?

**Comment by sebacruzd** [comment]
No es un error, los que tiene 0 están inoperantes como dices, por lo que debes considerar esos casos y hacer lo pertinente para tu programa.
