### ISSUE TITLE
Problema con subir los archivos al repositorio

### ISSUE THREAD

**Issue by Consuelo-Gamboa** [IIC2233/Syllabus#88]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido
Al momento de poner git add * me aparece que por el archivo gitignore no se me va a subir ningún archivo. El tema es que no he puesto nada en el gitignore y aún así me aparece esto

$ git add *
The following paths are ignored by one of your .gitignore files:
Tareas/T0/__pycache__
hint: Use -f if you really want to add them.
hint: Turn this message off by running
hint: "git config advice.addIgnoredFile false"

[Agrega aquí lo que quieras aportar o preguntar]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by fernandosmither** [comment]
Hola!

El mensaje que te aparece hace alusión a que **algún gitignore** está surtiendo efecto, entonces podrías revisar todos utilizando el criterio de búsqueda en tu buscador de archivos `.gitignore`. Ahora, por lo que puedo ver de tu error, está ignorando la carpeta pycache, la cual usualmente ya viene en algunos gitignores que les damos nosotros y está bien que no se suba, ya que esta carpeta pertenece a los archivos temporales de python.

Saludos y quedo atento a tus comentarios!
