### ISSUE TITLE
Problemas con los testcases

### ISSUE THREAD

**Issue by DiegooDSC** [IIC2233/Syllabus#88]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, me surgió una duda con los testcases. Cuando quiero ejecutar un subconjunto de testcases, como por ejemplo para el método crear_plano, pongo  py -m unittest -v -b tests_publicos.test_00_crear_plano.py y no me funciona, me aparace el siguiente error: module 'tests_publicos.test_00_crear_plano' has no attribute 'py'. Sin embargo, cuando lo ejecuto el codigo sin el .py (py -m unittest -v -b tests_publicos.test_00_crear_plano), no tengo problemas. Es normal que pase esto?

**Comment by R3Y3X** [comment]
holaaa, si es normal que pase, la segunda forma que es la que te funciona sin problemas corresponde a la manera correcta de ejecutar el test.
 Prueba de como se debe correr el test (instrucción sacada de la tarea 1 al final de la página 14):
![Captura de pantalla 2024-08-21 000523](https://github.com/user-attachments/assets/a4606f10-2d98-4749-998d-0071d6aa6656)
Éxito en tu tarea ⚡
