### ISSUE TITLE
Los QThreads se me caen y las flechas disminuyen su velocidad

### ISSUE THREAD

**Issue by jorge-ovalle** [IIC2233/syllabus#880]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by jorge-ovalle** [comment]
Hola! Tengo un problema con mi programa. En particular, después de un tiempo me aparece este error en el terminal: ```QThread: Destroyed while thread is still running```. No entiendo porque sucede todo el rato, los threads terminan cuando ya no se necesitan y borro cada label que no vaya a usar. Además, justo después de que se dejen de generar flechas, las flechas que quedan en pantalla disminuyen su velocidad y tampoco veo por qué. Espero me puedan ayudar! 

PD: Use el código 'hook', pero no me tira nada

**Comment by JuaniAndres** [comment]
Hola @jorge-ovalle 
Ese error que te aparece se debe probablemente a que no estas guardando tus QThread dentro de algún atributo ya que, si no lo guardas y termina el método donde creaste el thread, python detecta ese thread y lo trata de borrar generando ese error si el thread todavía estaba corriendo. La idea es el Qthread que creaste lo guardes y una vez que termine de correr lo borres. Respecto al tema de las flechas quizás la issue #860 te pueda servir y además se habla un poco de lo que te mencione antes.
Quedo atento si sigues con problemas

**Comment by jorge-ovalle** [comment]
Los threads creados los guardo en una lista llamada self.pasos_activos. Y terminan solos (salen del while del run) cuando se cumple cierta condición, entonces no entiendo el por qué me aparece ese error

**Comment by JuaniAndres** [comment]
Puedes subir tu código a tu repositorio para revisarlo.

**Comment by jorge-ovalle** [comment]
Ya está en el repo. Puedes ejecutar el main.py. En el frontend en ventana_juego.py están todas las funciones asociadas a la ventana de juego y en el archivo threads.py de la misma carpeta están definidos todos los threads

**Comment by JuaniAndres** [comment]
Revise tu código y efectivamente parece que todos los threads los guardas en atributos. Una cosa que puede estar pasando que causa que se cierre repentinamente tu programa es que Pyqt5 siga guardando algunas referencias de tus QThreads a pesar de que python los borre. Para asegurarnos de que borre todo eso es necesario que le apliques ````.deleteLater()```` antes de eliminar tus QThreads. En tu caso dentro del tu metodo desactivar_paso podrías agregar ````self.sender().deleteLater()```` antes de sacarlos de la lista. Respecto a que las flechas se mueven más lento me da la sensación de que se debe a que hay muchos threads al mismo tiempo o que pyqt5 está haciendo muchas cosas en paralelo sin embargo no te preocupes tanto por eso porque el movimiento se sigue viendo fluido además de que se nota la diferencia de velocidad de las doradas.
Ojalá te sirva lo del deleteLater pero si sigues con problemas me avisas.

**Comment by jorge-ovalle** [comment]
Es que las flechas se mueven notoriamente más lento justo después de que el generador deje de generar más flechas, antes todo bien. Lo raro que no hay ninguna señal que provoque eso.

**Comment by jorge-ovalle** [comment]
Espero me puedan ayudar con eso último que estoy medio atrasado :(

**Comment by JuaniAndres** [comment]
Que extraño porque hice la prueba y eso pareció ser suficiente para evitar que se caiga. Si puedes subir denuevo tu código para ver lo que cambiaste pero antes haz una prueba remplazando el delete de la label en desactivar_paso por un label.deleteLater() aunque dudo que sea eso

**Comment by jorge-ovalle** [comment]
Ya subí los cambios. Se cae cuando empiezo a jugar, incluso en principiante. Empiezo a teclear y se cierra sin tirarme ningún mensaje de error. Podría ser mi computador, pero no creo.

**Comment by jorge-ovalle** [comment]
De hecho aunque no toque nada y las flechas pasen de largo se cierra la ventana :((

**Comment by JuaniAndres** [comment]
Ya un detalle importante que el deleteLater tiene que ser antes de que borres el Qthread para que funcione prueba poner la linea 142 antes que la 141 de ventana_juego.py. Prueba ese cambio y me cuentas.

**Comment by jorge-ovalle** [comment]
Oka ahí si!!. Probé tres veces en maestro y la primera se cayó con el error de Qthead destroyed while thread is still running. Ahora lo que me falla es por qué la velocidad disminuye mucho cuando el generador se apaga.

**Comment by jorge-ovalle** [comment]
Mmm ya no se cierra por cerrarse, pero a veces se cierra y me aparece el error  Qthead destroyed while thread is still running. Será algo con mi modelación ?

**Comment by JuaniAndres** [comment]
Ese error se debe a que estas eliminando un Qthread que todavía no termina.  Fíjate que todos tus Qthreads se mantengan guardados en algún atributo hasta que terminen. Modificaste algo más porque a mi no me aparece ese error?
Respecto a lo de las flechas es un misterio que no e encontrado por más que reviso igual no es tan terrible

**Comment by jorge-ovalle** [comment]
Nop no he cambiado nada. Es que no aparece siempre. Me aparecio una 2 veces de las 5 que probé,

**Comment by JuaniAndres** [comment]
Si puedes escríbeme ahora o mañana vía discord me gustaría probar una cosa a ver si soluciona tu problema

**Comment by jorge-ovalle** [comment]
Apaño ahora para salir del cacho

**Comment by JuaniAndres** [comment]
Para cualquiera que tenga el error "Qthead destroyed while thread is still running" un truco que les puede ser útil para asegurarse de eliminar sus Qthreads solamente cuando estas terminaron  es ocupar la señal ````finished```` que es parte de la clase Qthread y que se emite solamente cuando el thread termina. Pueden ocupar ````connect```` para conectar esa señal a otro método que se encargue de borrar el Qthread de donde esta guardado.
