### ISSUE TITLE
Cheat Code FIN

### ISSUE THREAD

**Issue by raimundomartinez** [IIC2233/syllabus#880]
Hola! Implemente el cheat code para avanzar a la siguiente ronda pero tengo que esperar que todos los threads terminen, estos siendo los de los Cliente y el reloj interno Reloj. Cómo era mala práctica usar terminate, lo que yo hice fue que el cheat code FIN hace que una variable cambie de False a True y edité los métodos run de los threads para que se salten todos los time.sleep() que tienen. Mi problema es que a pesar de esto, pueden pasar entre 2 a 5 segundos para que efectivamente se termine la ronda. Así que tengo algunas preguntas:
1) ¿Porque creen que ocurre esto? ¿Es normal?
2) A pesar de la demora de tiempo, ¿Está bien implementada la funcionalidad? ¿Obtendría puntaje completo en la tarea?
3) ¿Se les ocurre una mejor manera de implementar esta funcionalidad?

Agradezco de antemano cualquier tipo de ayuda.

**Comment by furcelay** [comment]
1. Imagino por lo que dices que tienes un código como éste:
```python
def run(self):
    if not self.fin:
        time.sleep(self.tiempo_sleep)
        self.hacer_algo()
```
Y en un momento dado el estado del parámetro `self.fin` cambia de `False` a  `True`, entonces las entidades que aún no han pasado por la línea `if not self.fin:` no llegarán al `time.sleep(self.tiempo_sleep)`, pero los que ya estén en el `time.sleep(self.tiempo_sleep)` van a seguir en esta línea hasta que se acabe el tiempo del sleep. Por este motivo tarda en terminar la ronda.

2. Espero que un ayudante te pueda responder eso :(

3. Fuera de forzar a acabar los threads, lo que es claramente una mala práctica, no creo que exista una forma inmediata de terminarlos, pero sí puedes reducir el tiempo que tardan para que sea visualmente inmediato. Imagina que tienes una entidad que debe esperar 10 segundos antes de ejecutar una acción, en el código anterior el tiempo de espera al usar el comando FIN sería de 0 a 10 segundos. Si ahora lo cambias por algo como:
```python
def run(self):
    if not self.fin:
        time.sleep(5)
    if not self.fin:
        time.sleep(5)
        self.hacer_algo()
```
El tiempo máximo de espera se reduciría a 5 segundos, piensa entonces que puedes hacer esto n veces reduciendo el tiempo a `10/n` segundos. Claramente el código anterior replicado n veces sería horrible, te recomiendo revisar el material de `QThreads` porque ahí hay una pista de como puedes repetir un `time.sleep -> hacer_algo` varias veces.

**Comment by tomasgv** [comment]
Hola @raimundomartinez !!

Como dice @furcelay 🎉 , es probable que al ingresar el _cheat code_ más de alguna entidad esté pasando por un `time.sleep()`. En ese caso, es común que no todas las entidades se detengan al instante exacto en que se presionan las teclas. 

Un tiempo de espera relativamente largo puede indicar que los _threads_ están esperando demasiado tiempo antes de volver a verificar la condición de término. Puedes seguir el consejo de @furcelay para implementar esta funcionalidad de mejor manera.

Si pueden llegar a pasar 5 segundos entre ingresar el _cheat code_ y que la ronda termine, entonces eso estaría alejado de la idea de terminar la ronda al instante mencionada en el enunciado 😅 . Si bien existe cierto grado de flexibilidad en "instante", no debería demorarse un tiempo excesivo.

Saludos! ☕ 🐱
