### ISSUE TITLE
Duda postulación a ayudantía

### ISSUE THREAD

**Issue by JuanpaBC** [IIC2233/syllabus#880]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola, me pasa que me gustaría postular para ser ayudante, pero no para el próximo semestre (porque se me viene fuerte y ya soy ayudante de otro ramo). Cómo lo haría para postular en futuros semestres?

Desde ya muchas gracias.

**Comment by lily416** [comment]
Hola @JuanpaBC, espero te encuentres bien c: 

No es necesario que postules a la ayudantía justo después de haber dado el curso, también aceptamos postulantes de semestres anteriores 😄. Por lo general compartimos el formulario de postulación por [los grupos de Telegram del DCC (Departamento de Ciencias de la Computación)]( https://capitulo-acm-puc.github.io/grupos/), por lo que los próximos semestres podrás encontrar  la información necesaria por allá, también nos puedes escribir al correo del curso (iic2233@ing.puc.cl) para que así te envíen el formulario correspondiente. 

Espero que esto aclare tus dudas y esperamos verte en el formulario de postulación más adelante 🙌

**Comment by JuanpaBC** [comment]
Bkn! muchas gracias!
