### ISSUE TITLE
Sobreescribir archivos

### ISSUE THREAD

**Issue by amparostevens** [IIC2233/syllabus#881]
Hola! Me queda la duda de cuándo guardar la información de la partida en los archivos `.csv`. 
- El archivo`mapa` guarda la información _inicial_ de la partida y hay que sobreescribirlo cada vez que se _inicia una partida nueva_ y no cuando se guarda la partida? 
- El archivo `datos` guarda los datos _finales_ de la partida y sólo se sobreescribe al guardar la partida?

**Comment by jitorralba** [comment]
Hola! Por lo que entendí del enunciado, que mapa.csv se sobreescriba cuando se inicia una nueva partida no implica que no se tenga que sobreescribir cuando se guarde, ya que no tendría mucho sentido.
Y con respecto a datos.csv, en el encabezado de la sección Archivos del enunciado, dice "estos archivos deberán **modificarse** con cada nueva ejecución del programa" por lo que entiendo que ambos .csv deben sobreescribirse al iniciar y guardar partida.

**Comment by tomasgv** [comment]
Hola!!
Efectivamente es como dice @jitorralba :tada:

Al **crear una nueva partida** y al presionar el botón **guardar** en la ventana post-ronda, **debes** sobreescribir ambos archivos.

Saludos! ☕ 🐱
