### ISSUE TITLE
No logro conectar una señal a una función de un QObject en específico

### ISSUE THREAD

**Issue by clementevalladares** [IIC2233/syllabus#881]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

![imagen_issue](https://user-images.githubusercontent.com/69611854/97386272-3d805d00-18b2-11eb-8d0a-8587d860e766.png)
(Revisé issues pasados en donde había un problema similar, pero la respuesta no correspondía a mi problema)
Cuando presiono alguna tecla la señal es emitida y la puedo conectar dentro de ciertas clases. Sin embargo, cuando intento conectar esta señal a las funciones de un QObject en específico, estas funciones no son ejecutadas al emitirse la señal.
En el caso de la imagen, al apretar la tecla se debería estar ejecutando una función dentro de la clase que maneja el comportamiento de la flecha. Lo cual pude comprobar que no sucede poniendo prints dentro de estas funciones.

**Comment by CrisBerriosL** [comment]
Creo haber tenido el mismo problema, donde conectaba una señal a un método de un QObject en específico y al emitirse la señal el método no se ejecutaba. Conectando la misma señal a métodos de otras clases, estos si se ejecutaban correctamente, solo con este QObject específico no funcionaba bien. En mi código, generaba este QObject por medio de un QThread (porque debía generar varios de estos objetos constantemente), y al cambiar el código de forma que  NO se genere por un QThread, el problema se solucionó. Así que debe haber una relación extraña entre QObjects y QThreads que hacen que no funcionen bien las señales o algo así, al menos esa es mi hipótesis.

**Comment by clementevalladares** [comment]
Me pasó exactamente eso. Pero no pude implementar esa solución en mi código, tuve que cambiarlo para no requerir el uso de esa señal.
