### ISSUE TITLE
Entrega plato al cliente

### ISSUE THREAD

**Issue by 18638333** [IIC2233/syllabus#882]
Hola, se puede hacer que el mesero choque con la mesa que está ocupando el cliente para que le entregue el plato, en vez de que choque con el cliente mismo?

**Comment by furcelay** [comment]
Yo hice eso porque era complicado colisionar con el ciente que estaba "dentro" de la mesa, pero quedo atento a lo que dice algún ayudante 👀

**Comment by jitorcas** [comment]
Hola! @18638333 y @furcelay 

Si pueden implementar que el chef tenga una colisión con la mesa del cliente y le pueda entregar el bocadillo. Si bien no está especificado en el enunciado, se considerará como correcto en la pauta de evaluación. 
Para evitar alguna confusión, recuerden citar esta *issue* en su **README**

**Comment by 18638333** [comment]
A pesar de eso, igual debe colisionar con los clinetes?

**Comment by jitorcas** [comment]
@18638333 

Se aceptará como correcto y lo puedes implementar así.

**Comment by dlmed** [comment]
Hola, no me quedó claro lo último? qué pasa si no tengo implementado la colisión con los sprites de los clientes? Es decir, tengo colisiones con todos los objetos, menos los clientes, por lo que podría en algún momento pasar por encima de sus cabezas jaja. Esto cuenta como descuento?

**Comment by jitorcas** [comment]
Hola @dlmed!

Una parte es la **colisión especial** para entregar los pedidos, la cual se puede implementar colisionando con los clientes y las mesas o solo uno de estos, y otra parte es la colisión de los objetos en general, los cuales no deberían colisionar, si no que respetar las dimensiones de los mismos.
