### ISSUE TITLE
pasos totales

### ISSUE THREAD

**Issue by cnillanes** [IIC2233/syllabus#882]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! para el cálculo de la aprobación no me queda claro si pasos_totales = correctos + incorrectos o eso mismo + los que no se consideran ni correctos ni incorrectos

Gracias!

**Comment by jaimecoloma** [comment]
Hola @cnillanes ! Cuales serian esos pasos que no se consideran ninguno de los dos? Si un paso no es realizado se considera incorrecto, la suma de pasos_totales es pasos_correctos + pasos_incorrectos.
Mucho éxito!

**Comment by cnillanes** [comment]
Hola! el enunciado dice que si un paso no es realizado no se considera correcto ni incorrecto, por eso me surgió la duda y ahora estoy confundida porque me dices que se consideran incorrectos :/
<img width="895" alt="Captura de Pantalla 2020-10-28 a la(s) 01 12 55" src="https://user-images.githubusercontent.com/41082653/97390074-b97ea300-18ba-11eb-9205-44845b9e0174.png">

**Comment by jaimecoloma** [comment]
@cnillanes Toda la razon, disculpa, cuando lo busqué para corroborar no lo leí correctamente (semana estresante 😞 ). En la seccion 3.5 se menciona lo siguiente: "Al terminal el nivel se calculará la aprobación dada por el porcentaje de acierto. Si en un nivel se generaron pasos_totales pasos..." por lo que pasos totales son pasos generados, es decir suma de correctos, incorrectos y los otros como tu decías. De nuevo disculpame por el inconveniente!

**Comment by cnillanes** [comment]
Tranqui! Muchas gracias :)
