### ISSUE TITLE
QThread: Destroyed while thread is still running

### ISSUE THREAD

**Issue by domja** [IIC2233/syllabus#883]
No puedo crear 2 threads seguidos, si creo uno solo funciona bien pero al intentar crear más, como en uno de los ejemplos de las guias me sale ese error: QThread: Destroyed while thread is still running

**Comment by mariovaldesa** [comment]
Instancia desde antes el thread... si no lo tienes instanciado y estás en un ciclo te va a desaparecer... a mi me pasó eso jajajaj

**Comment by fdoflorenzano** [comment]
Hola @domja,

Ese error suele aparecer por algo similar a lo que menciona @mariovaldesa, un *thread* creado es automáticamente eliminado poco después de crearse. Depende bastante de la estructuración de tu código, pero un caso frecuente es crearlo en algún método sin contar una forma de referenciarlo más adelante. Similar al caso de las ventanas que se instancian dentro de un método pero no se guardan, como el siguiente ejemplo:

```python
    ...
    def crear_thred(self):
        mi_thread = MiThread()
        mi_thread.start()
```

Al terminar de ejecutar `crear_thred`, Python automáticamente elimina la variable ya que es local y no se referencia a futuro, lo cual fuerza cortar el *thread* iniciado. Si al crear el *thread* lo guardas en un atributo o en otro contenedor que sigue existiendo, entonces no será eliminado. Para el caso de múltiples *threads*, una alternativa puede ser guardar todos los *threads* en una lista u otra estructura de datos interna, cosa de que no sean eliminados al avanzar el código.

Pero en realidad, puede ser por otras razones también. ¿Sigues con este error? ¿Pudiste solucionarlo?

Saludos.
