### ISSUE TITLE
Duda con los niveles

### ISSUE THREAD

**Issue by cnillanes** [IIC2233/syllabus#883]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola estoy un poco confundida entre los conceptos de "niveles" y "dificultad". Si tengo aprobacion suficiente me puedo devolver a la ventana de juego y apretar comenzar como para partir nuevamente en dificultad principiante pero nivel 2? No podria como devolverme a la ventana de juego y re interactuar con cancion y dificultad? 
Cual sería la diferencia entre niveles, cambia algo en el desarrollo del juego?
Mi duda es porque sino cumplo la aprobacion me regresa a inicio y ahi puedo volver a pinchar comenzar y pasar a la ventana de juego (aunque registrando usuario nuevamente) y al final es medio parecido entonces no estoy viendo como hacer la diferencias en el código.
Espero se haya entendido mi duda (me costó explicarla)

Gracias desde ya!

**Comment by kadroguett** [comment]
Hola @cnillanes, básicamente si consigues el porcentaje de aprobación mínima puedes seguir jugando pasando al siguiente nivel, no es necesario enumerar los niveles ya que no es algo que se pida en el enunciado, lo importante es que se pueda seguir jugando y que se avance a la ventana de pre-ronda (luego de mostrar el resumen) para seleccionar `dificultad y canción`. En el caso de que no se alcance el mínimo de aprobación se deberá volver a la ventana de inicio (luego de mostrar el resumen), pidiendo nuevamente un nombre de usuario.
