### ISSUE TITLE
Actualizar ventana para mostrar nuevos QLabel

### ISSUE THREAD

**Issue by sscontreras** [IIC2233/syllabus#884]
Hola, quería saber si existe algún equivalente a realizar un 
![image](https://user-images.githubusercontent.com/62116064/83308508-e5471100-a1d4-11ea-9c9c-5da7b972867d.png)
para actualizar la ventana de juego con la creación de nuevos label al comprar chef o mesas, probé con self.update(), o el QApplication.processEvents() y nada.

**Comment by rieg-ec** [comment]
Hola, creo que con que de alguna manera ese label sea hijo de la ventana basta para que la ventana lo renderize. En mi caso por ejemplo, instancio los labels nuevos como atributos de la ventana , con eso basta. Si quieres eliminar un label, puedes llamar label.deleteLater() tambien.

**Comment by rieg-ec** [comment]
Hola, yo lo hago asi por ahora: cuando instancio el label llamo a label.show() para que se vea, y para eliminarlo ocupo label.deleteLater()

**Comment by sscontreras** [comment]
Lo intenté y no funciona, creo que es por que el label queda bajo el layout principal que es el que contiene al mapa, la única manera en la cual se muestra como corresponde es creando la ventana nuevamente, que vuelve a generar todos los label para mostrar y quedan encima, pero si creo nuevos ya teniendo la ventana creada se colocan bajo el mapa.

**Comment by mariovaldesa** [comment]
Si te quedan a abajo podis usar label.raise_()

**Comment by rieg-ec** [comment]
> Lo intenté y no funciona, creo que es por que el label queda bajo el layout principal que es el que contiene al mapa, la única manera en la cual se muestra como corresponde es creando la ventana nuevamente, que vuelve a generar todos los label para mostrar y quedan encima, pero si creo nuevos ya teniendo la ventana creada se colocan bajo el mapa.

Una pregunta, esos labels estas haciendo que sean childs de la ventana?

**Comment by Alonsinho1** [comment]
El metodo que escribiste al comienzo me parece una buena forma de implementarlo.

Cual consideras que es el problema con ese metodo?
