### ISSUE TITLE
El programa no me deja ejecutar mis archivos en la carpeta front-end

### ISSUE THREAD

**Issue by jigodoy** [IIC2233/syllabus#884]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola! Al momento de ejecutar mis ventanas en la carpeta front-end me dice que mi permiso a sido denegado (PermissionError: [Errno 13] Permission denied: 'front-end'), pero al mover mis archivos a la carpeta T02 funcionan correctamente.

**Comment by JuaniAndres** [comment]
Hola @jigodoy 
Me puedes comentar que editor de código estas usando y de que manera estas corriendo tus archivos
También si puedes hacer la prueba de correr el archivo .py desde la consola de tu computador para ver si ocurre el mismo error

**Comment by jigodoy** [comment]
Estoy ocupando visual studio, probé hacerlo desde la consola y me tira el mismo error. Dejé los archivos ui en la carpeta T02 y los llamo desde el frontend y ahi si me corre (corro el programa desde el main.py que esta en T02 también).

**Comment by JuaniAndres** [comment]
Si puedes subir lo que tienes a tu repositorio para revisarlo. Por mientras podrías probar si alguna de las cosas mencionadas en la issues #775 te sirve

**Comment by JuaniAndres** [comment]
Revise el código que estaba en tu repositorio y para importar tus ventanas en main.py te recomiendo ocupar ````from frontend.ventanas import Ventana1, Ventana2, etc```` y eliminar todo lo de ventanas que traspasaste a main. Tambien el path que tienes que poner en loadUiType de ventanas.py tiene que ser relativo al archivo donde partiste corriendo el código. Por ejemplo si partes corriendo el código desde main.py tienes que incluir la carpeta frontend en el path de loadUi osea ````frontend\archivo.ui```` (te recomiendo ocupar el join de la librería os para generar ese path). Un detalle python no permite importar elementos que estén en una carpeta superior por lo que desde ventanas.py no puedes importar tu DraggableLabel o te va a tirar un error. Lo ultimo que note es que tus ventanas no se muestran porque se genera el siguiente error con tus pinguinos ````AttributeError: 'QLabel' object has no attribute 'setDragEnabled'```` lo cual significa que esa Qlabel no tiene ese método que estas ocupando.
Te recomiendo para complementar que revises lo de la issues 775 y que si el problema persiste probablemente se deba a como estas corriendo tus archivos en visual studio en ese caso la issues #645 te puede servir.
Si nada de lo anterior te sirve me avisas para que lo veamos en detalle
