### ISSUE TITLE
mover pinguinos despues de comprarlos

### ISSUE THREAD

**Issue by totoiii** [IIC2233/syllabus#885]
**Se deben poder reposicionar los pinguinos si es que ya los posicionaste en la pista??**
Tengo implementado que una vez  puesto en la pista y comprado un pinguino o puffle este ya no puede volver a reposicionarse por el resto de toda la partida.

**Comment by kadroguett** [comment]
Hola @totoiii, en el enunciado no se especifica por lo que queda a tu criterio, recuerda mencionarlo en tu README.
