### ISSUE TITLE
Consulta sobre los 100 caracteres en README

### ISSUE THREAD

**Issue by felipehen** [IIC2233/syllabus#885]
Es necesario respetar la regla de los 100 caracteres por linea en el README?

**Comment by benjavicente** [comment]
Hola!

La regla de los 100 caracteres es parte de la guía de estilo de código, por lo que no debería aplicar en el README.

Aún así, un cambio de linea no separa un párrafo en archivo markdown, es decir

```txt
este es solo
un párrafo
```

_se ve como_

este es solo
un párrafo

**Comment by jitorcas** [comment]
Hola @felipehen 

Tal como dice @benjavicente, la regla de 100 carácteres corresponde a **PEP8**.

Si tu pregunta va ligada a la **adición/cambios** de líneas para corregir una tarea ya entregada, sí debería cumplir con **PEP8** y respetar los 100 carácteres por línea.
