### ISSUE TITLE
Paso combinado con tipo flecha

### ISSUE THREAD

**Issue by totoiii** [IIC2233/syllabus#886]
**¿Puedo hacer que mis pasos combinados sean de un mismo tipo?**
Ej: creo aleatoriamente un paso de 3 flechas y estas 3 flechas serán del mismo tipo.
 Esto me arreglaria el problema que tengo si es que por ejemplo creo un paso combinado de mas de una flecha pero una de ellas es dorada, esto provocaría que no bajen al mismo tiempo y pues me dificulta el saber si es que esta correcto o no el paso.
Si es que no se puede, que hacemos en el caso de que salga una dorada en un paso combinado?

**Comment by jaimecoloma** [comment]
Hola! @totoiii tu pregunta se respondió en la issue #721 (recuerda revisar el compilado). Si, como no se especifíca puedes dejarlo a tu criterio para que no te complique pero no olvides mencionarlo en el readme (y citar esta issue si quieres). Mucho éxito!
