### ISSUE TITLE
Flujo del juego muy cortado

### ISSUE THREAD

**Issue by janwandter** [IIC2233/syllabus#886]
Hola, estoy teniendo problemas cuando ejecuto el juego y se ejecutan acciones como que los clientes se van o los choques especiales, que hacen que la ventana del juego deje de responder por instantes (y estoy usando threads). Como no es ningún error en especial no se como abarcarlo.

**Comment by Alonsinho1** [comment]
Hola!

Lo mas probable que este ocurriendo es que al tener threads el programa se quede mucho tiempo ejecutando la función run de los threads y no avance con el resto. Una forma de solucionar esto, es acortando lo que hace la funcion run o simplemente reducir la cantidad de threads. 

Para chequear esto podrias poner varios prints en los run de los threads para ver si efectivamente tu programa se queda pegado (Algun sleep muy largo quizas) o si se queda mucho tiempo ejectuando alguna accion.

Suete
