### ISSUE TITLE
Entrega de archivos mapa.csv y datos.csv

### ISSUE THREAD

**Issue by Jairuru** [IIC2233/syllabus#887]
Podemos asumir que los archivos mapa.csv y datos.csv siempre existirán independientemente de si se ha jugado antes o no? Si no se puede, el botón seguir jugando puede funcionar igual al botón comenzar de nuevo?
Saludos, de antemano gracias^^

**Comment by furcelay** [comment]
Si mal no recuerdo se mencionaba que se podía asumir lo que dices

**Comment by jitorcas** [comment]
Hola @Jairuru 

Tal como dice @furcelay siempre puedes asumir que estarán presente los archivos `mapa.csv` y `datos.csv` por lo que los botones **seguir jugando** y **comenzar de nuevo** deben cumplir sus funciones especificas.
