### ISSUE TITLE
Threads y QTimer

### ISSUE THREAD

**Issue by daniela-carreno** [IIC2233/syllabus#887]
# Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, no he podido hacer que múltiples flechas bajen al mismo tiempo. Me pasa que no entiendo bien los threads, qthreads ni timers, qtimer y sus variaciones entonces ni siquiera sé si los estoy usando bien. Entiendo el espíritu de los threads pero usarlos más allá de contar las ovejas de los ejemplos se me ha complicado. La issue que más me ha ayudado es la #821, el resto aún son muy avanzadas para lo poco que llevo. Empecé con mucho tiempo, llevó una semana pegada con la aparición y bajada de flechas, ya no sé que hacer. Además, esto me impide hacer/probar muchas otras funcionalidades, como hacer desaparecer la flechas cuando se presione una tecla, cambiar de color la zona de captura cuando se intersecta con una flecha, contar el puntaje, calcular el porcentaje de aprobación, etc.

En concreto, al iniciar mi juego se envía señal a dos funciones en el back: `start_timer` y `start_juego`. La primera es un QTimer que va actualizando el contador de tiempo en la ventana de juego del front. La segunda es la lógica del juego. Mis dudas son:
1. El QTimer en cada iteración se supone que genera una nueva flecha (newPiece), esta la convierto a widget y la mando al front en una señal. Sé que está llegando bien porque puse un print a la secuencia de funciones que llevan el widget. Sin embargo, no me muestra la imagen en pantalla y ni idea si se desplaza correctamente. Ayer si slogré hacer que se moviera harcodeando el código, pero (mala mía) no hice push ni guardé otra versión antes de seguir programando. Entonces perdí la versión que funcionaba 😢  **me podrían ayudar mirando mi último push en por qué no se visualiza en pantalla?**
2.**¿ La segunda función tiene sentido ?** Separé `start_timer` de `start_juego` ya que el timer siempre va a contar segundo a segundo, mientras que el juego, dependiendo de la dificultad, sus acciones pueden tener otra ventana de tiempo.

**Comment by igbasly** [comment]
Hola @daniela-carreno :smile:

Creo entender hacia donde va tu problema, también comprendo que esto puede ser complejo y algo frustrante a veces, pero te pido paciencia porque se puede resolver 🙌.

* Primero, considerando lo que me explicas, se me ocurre que en problema de que no se muestren las flechas es por el simple hecho de que la envías desde el *backend*. Por cómo funcionan los widgets de PyQt si creas algún elemento de esta forma, en *frontend* debes considerar agregarlos en algún lado (ya sea configurar un *parent* o agregarlos a un _layout_) y mostrarlos, esto último haciendo `.show()` del elemento es cuestión, un label me parece.

:bulb: Siguiendo las buenas prácticas y una correcta separación de _frontend_ y _backend_, no deberías enviar el _widget_ hecho por la señal, lo correcto sería que envíes la información necesaria (el path de la imagen o el texto) para que la función de llegada de la señal en el _frontend_ arme el objeto y lo muestre.

* En cuanto a la segunda pregunta, si entiendo bien, me parece que lo ideal sería que no utilices dos señales pare evitar problemas de sincronización. Puedes enviar solo una señal y que la función se llegada de active el contador del tiempo, ahora como esto va constantemente funcionando creo que tendría sentido que sea un thread.

Espero que esto te ayude a aclarar las dudas respecto a cómo formular tu problema o los threads en general.
Ya sabes que puedes preguntar con con toda confianza y te ayudaremos en todo lo que podamos 😊. Mucho éxito en todo!!
