### ISSUE TITLE
Duda QSound

### ISSUE THREAD

**Issue by ChupetitoSuazo** [IIC2233/syllabus#888]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! al intentar poner una canción con QSound, me sale el error de "Error decoding source file: *". No se a que se puede deber, ya que la ruta de la canción la estoy obteniendo con "os.path.join" de la misma forma en que obtengo las rutas para los códigos y pinguinos (cambiando el nombre de la carpeta). Revise corriendo el programa desde la terminal y me salia el mismo error.

**Comment by JadrinaDA** [comment]
Hola! Ese error se puede deber a que el formato del audio que le estás dando es incorrecto, estás usando una canción dadas o buscaste otra? Sí es otra asegúrate que sea de extensión .wav.
También se puede deber a que el path es incorrecto, por lo que te recomiendo que intentes poner el path como un parámetro y pasarle ese parámetro a QSound para ver si es el join que está mal o si hay otro error. Avísame cómo te va!

**Comment by Margarita-Paz** [comment]
Hola, me ocurre el mismo error -> "Error decoding source file: *" y si puse la extensión .wav 😢

**Comment by Margarita-Paz** [comment]
Ya encontré mi error ajaj

**Comment by ChupetitoSuazo** [comment]
Cual era? aun no logro solucionarlo

**Comment by Margarita-Paz** [comment]
en mi caso uso mac y cuando no uso un archivo se me va a la nube, entonces el problema es que la canción no estaba descargada en el compu

**Comment by ChupetitoSuazo** [comment]
ahhh tuve el mismo error, mala jugada de mac jajaja, gracias!!
