### ISSUE TITLE
QPixmap no lee archivos .png

### ISSUE THREAD

**Issue by ealv-nms** [IIC2233/syllabus#888]
Al usar el código entregado en contenidos sobre como hacer aparecer imágenes con una QLabel , este funciona  perfecto con una imagen .jpg pero usar una imagen .png no funciona. No entrega ningún error ni nada parecido, solo no aparece la imagen en la ventana

**Comment by benjavicente** [comment]
¿Dónde estás ejecutando el código?

Puede que no aparezca la imagen porque el path es incorrecto. Asegurate que
```
print(os.path.join(os.getcwd(), ruta_imagen))
```
imprima la ruta correcta del archivo.

**Comment by danckoo1** [comment]
Hola! debería funcionar de igual forma para una .jpg como para una .png, por lo que tal como ya te lo mencionaron verifica que el parh sea correcto y que el label no este siendo tapado por algún otro widget de la ventana
