### ISSUE TITLE
Atributo de clase no definido (problema con señales)

### ISSUE THREAD

**Issue by Natydlb** [IIC2233/syllabus#889]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola! me sale el siguiente error "Pista_baile' object has no attribute 'flecha1'" pero flecha1 lo tengo definido en el init, por lo que no entiendo porque sale que no tengo ese atributo, también me salía el error "Pista_baile.senal_comienza_baile[] signal has 0 argument(s) but 2 provided" pero siguiendo el ejemplo que estaba en contenidos cuando conecto las señales no es necesario  ponerlo como función con los argumentos, por lo que no entiendo cuales son mis errores :( 

Muchas gracias!

**Comment by JadrinaDA** [comment]
Hola! Tu primer problema ocurre porque en el init estás definiendo la posición primero y tu posicion.setter llama a flecha1 antes de que esta sea creada. Basta con cambiar el orden y te debería funcionar. El segundo error se debe a que cuando defines una señal en la parte de arriba de tu clase debes indicarle los tipos de argumento que recibe. Por ejemplo en tu caso senal_revision_union recibe dos QRect por lo que deberías poner senal_revisar_union = pyqtSignal(QRect, QRect). También debes hacerlo para otra señales que reciban argumentos.  Espero haberte ayudado y éxito!

**Comment by Natydlb** [comment]
muchas gracias!!

**Comment by Natydlb** [comment]
hola disculpa, un event.key, de qué tipo de atributo es?

**Comment by JadrinaDA** [comment]
Debería ser un int. Suerte!
