### ISSUE TITLE
Error de teclado

### ISSUE THREAD

**Issue by JaviGuzman** [IIC2233/syllabus#889]
Hola, tengo un problema con mi computador y no sé cómo arreglarlo (ni cómo hice para que pasara esto), pero cuando imprimo una lista vacía, en vez de que me aparezcan los corchetes, me aparece èê (en vez de []). Y en los saltos de linea (al leer un archivo) en vez de que me aparezcan como \n me aparece çn. Con estos problemas, no puedo trabajar con los archivos 😢 

Esto me pasa si leo el archivo mapa.csv
![Captura de Pantalla 2020-05-30 a la(s) 21 21 12](https://user-images.githubusercontent.com/48359777/83342285-8f00cd80-a2bb-11ea-9ae1-8a3a0cfbd45d.png)

**Comment by furcelay** [comment]
¿Usas el encoding `uft-8` al leer los archivos? ¿No los has abierto con excel?

**Comment by Alonsinho1** [comment]
Me sumo a lo que dice furcelay, trata las opciones que dijo y ve lo que sale. Si se ha cambiado, es probable que se haya desconfigurado los archivos al abrirlos con excel, en cuyo caso seria bueno descargalos denuevo. Otra posibilidad, es que solo se vean distintos en el print (Quizas se haya desconfigurado los prints) pero en tema de codigo deberia funcionar bien, ya que estos cambios deberian ser consistentes.

Suerte

**Comment by JaviGuzman** [comment]
El problema no era solo al leer los archivos, sino que en la terminal, los caracteres se habían desconfigurado. Pero cerré todo y al volver a abrirlos se arregló :)
