### ISSUE TITLE
Hora de 'git push'

### ISSUE THREAD

**Issue by DanielSaavedra** [IIC2233/syllabus#89]
Estaba revisando el último push que hice. El comando lo escribí a las 19:59 en el Bash de Git, pero en GitHub aparece que se recibió a las 20:00 (20:00:04 según git log).
¿Eso significa que es un commit válido, o pasa a ser atraso?

**Comment by lily416** [comment]
Hola :relaxed: 

Prontamente en tu repositorio del ramo saldrá una issue indicando el commit que fue recolectado automáticamente, con ese podrás saber si el último commit que subiste es válido o si está atrasado. 

Esperemos que el commit sea válido 🤞🍀

**Comment by DanielSaavedra** [comment]
Ya! Ojalá :s

**Comment by zaertis0** [comment]
F
