### ISSUE TITLE
No tengo repositorio aún, qué puedo hacer?

### ISSUE THREAD

**Issue by fbehncke** [IIC2233/Syllabus#89]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.

### Problema

[Describe tu problema de manera detallada, explicando qué estás intentando hacer y explicando los errores o problemas que has encontrado. Se recomienda agregar fotos cuando sea posible]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by fbehncke** [comment]
Hola quería saber que puedo hacer ya que aún no tengo repositorio y debo avanzar en a tarea, gracias

**Comment by maromero-21** [comment]
Responder este form y te llegará la invitación a tu correo:
https://docs.google.com/forms/d/e/1FAIpQLSfWUa3wNi6GY0UnWgnJDruI9NYJSAwhkfRrIAoe5jOChp1FEg/viewform

**Comment by fbehncke** [comment]
Hola, hace unos días llené el formulario pero no me ha llegado ningún mail para crear el repositorio personal :( Espero poder hacerlo hoy pronto ya que no he podido partir la tarea por lo mismo. Agradecería tu ayuda.

Muchas gracias.

**Comment by Hernan4444** [comment]
Hola @fbehncke 

Puede ser que el mail llegó a SPAM, pero de todas formas, si no te ha llegado el mail,  Intenta hacer click en el [siguiente link](https://github.com/IIC2233/fbehncke-iic2233-2023-1/invitations). Este link solo será válido con tu cuenta "fbehncke" y te permitirá aceptar la invitación.

Quedamos atentos a cualqueir cosa,
Saludos c:

**Comment by fbehncke** [comment]
muchas gracias!
