### ISSUE TITLE
Duda sobre la forma de riego

### ISSUE THREAD

**Issue by mrebolledo03** [IIC2233/Syllabus#89]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [ ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
No entiendo el enunciado donde explica la forma que se riegan los planos de riego. Al ver la foto del enunciado y revisar los test case, al tener un circulo de área 1 no se incluyen las esquinas, pero al tener un circulo de área 2 se incluyen muchos mas puntos dentro de la matriz. **No entiendo cuando debo considerar los bordes y cuando no, o si podrían ser mas detallados en la definición del sistema de riego**

**Comment by Agusrush21** [comment]
Hola! mi recomendación para entender mejor el enunciado es que en vez de verlo como tal un circulo, verlo como un cuadrado que al momento de inscribir el circulo este no toma en cuenta las esquinas o dicho en otras palabras, es **un cuadrado el cual ignora las esquinas.**
Seguiría mas con mi explicación pero no estoy seguro de si seria una falta académica. Espero haberte ayudado
Un saludo de antemano.

**Comment by mrebolledo03** [comment]
Gracias, con eso me queda claro

**Comment by mariasofiawahl** [comment]
A mi tampoco me quedó claro cuando dice "un área igual a 2 significa extender el círculo 2 unidades más desde el centro" ¿Entonces area 2 es como un radio por así decirlo (considerando que en realidad es un cuadrado)?

**Comment by Agusrush21** [comment]
Mi recomendación como dije antes, no lo pienses como si fuera un circulo sino que es un cuadrado generado desde un centro x el cual al momento de inscribir un circulo, este **ignora las esquinas**
O dicho en otras palabras un cuadrado que ignora las esquinas
