### ISSUE TITLE
Pregunta sobre la pauta (guardado automatico)

### ISSUE THREAD

**Issue by franco-anfossi** [IIC2233/Syllabus#89]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
En la pauta cuando dice guardado automático en el punto 2.7 se refiere a que se debe guardar automáticamente cada vez que se haga una jugada o que el guardado es automático cuando el jugador quiera y elije la opción de guardar?

**Comment by TomasAlcalde** [comment]
Hola! En la distribución de puntaje, el guardado automático se refiere a que el archivo en el que se guardan las casillas descubiertas y bestias debe quedar ubicado dentro de una carpeta de partidas, sin necesidad de moverlo manualmente. Según enunciado, este archivo debe crearse o modificarse cuando el jugador escoge guardar la partida.
Espero haber resuelto tu duda, saludos.
