### ISSUE TITLE
volumenes ? y que hago con valores no definidos aun?

### ISSUE THREAD

**Issue by ptflores1** [IIC2233/Syllabus#89]
1.- No entiendo que son los volumenes de asks y bids. Me explican porfis?

2.- Que hago con valores como los mismos volumenes o best asks/bids spread, valor actual de un currency, etc. cuando no se pueden calcular aun?, es decir cuando no hay ordenes suficientes o algo por el estilo, los imprimo como un string diciendo algo como: "No se puede calcular aun"?

Gracias!

**Comment by nebil** [comment]
1. Los volúmenes de _ask_ y _bid_ son las sumas de los montos de _currency_ acumulados respectivamente, entre las órdenes activas. Para ofrecer un ejemplo más concreto, vamos a la figura 3 del enunciado, que aparece en la sección que describe el ficticio (pero emergente) mercado `NECCLP`. En este caso, el monto acumulado (o volumen) de _ask_ es cinco _nebcoins_, ya que hay dos ofertas activas de venta: una con dos _nebcoins_ y otra con tres _nebcoins_. Incluso, lo podemos verificar usando [:snake:](https://www.python.org/).

```python
>>> 2 + 3
5
```

Y por otra parte, el monto acumulado de _bid_ es de un _nebcoin_ y medio.

2. Efectivamente, podría ocurrir que no dispongas de información suficiente para calcular alguna métrica en particular. Por ejemplo, en el caso del _spread_ del mercado, se necesitará al menos una oferta de compra y otra de venta para computar la diferencia. Yo creo que, en aquel escenario, un resultado aceptable es devolver un _string_ que diga `"N/A"`.
