### ISSUE TITLE
README.md - Dudas sobre "Cosas implementadas y no implementadas"

### ISSUE THREAD

**Issue by ElTioAndresCabezas** [IIC2233/Syllabus#89]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Saludos!
A nosotros, en nuestro ```README.md``` nos exigen que especifiquemos lo que nuestro programa puede y no puede hacer. Si por error yo llegase a decir que mi programa tiene implementado algo que, durante corrección, un ayudante descubre que no funciona por completo. ¿Esto se penalizará como un "Readme que no fue desarrollado completamente" o como un "Readme deshonesto"?

Por ejemplo (no acorde a la realidad): Si yo especifico que en mi entrega, el usuario puede registrarse sin ningun problema, pero un ayudante descubre un error en mi codigo el cual hace que un usuario no pueda registrarse con ciertos nombres especificos. En teoria, eso significa que la funcion no esta totalmente implementada, pero al no saber, deje puesto en el readme que esta todo bien implementado.

Disculpas de antemano por lo rara de la pregunta, pero tengo miedo de hacer algo mal en el ```README.md``` y perder puntaje por eso.

**Comment by mmunoz12** [comment]
Hola @ElTioAndresCabezas!

Primero, recuerda que el Readme permite obtener des-descuento (como máximo 5 décimas) por lo que, ya sea si obtienes puntaje completo o no en tu Readme, no afectará directamente tu nota. Me refiero a que, en el caso de un mal Readme, simplemente no obtendrás puntaje para descontar descuento si es que tuviste. 

Lo ideal es que tu Readme sea lo más claro y honesto posible, de forma que para los ayudantes sea sencillo encontrar qué es lo que se realizó bien y qué no en tu tarea. Es entendible que a veces uno/a mismo/a no se da cuenta de los errores que puedan haber en el código, por lo que si esto ocurre no existe un descuento o penalización como tal en tu Readme. Sin embargo, entregar un Readme que explica cosas completamente diferentes a lo que realmente pasa en el código, no sería considerado un buen Readme y por ello, el ayudante podría no otorgar puntaje en este caso 😔.

De esta forma, los motivamos a hacer buenos Readmes, ojalá lo más claros y explicativos posible sobre qué se logró hacer y qué no, con la finalidad de que sea más sencillo para nosotros/as revisar sus tareas ☺️. 

Mucha suerte con tu entrega! Saludos!
