### ISSUE TITLE
Test case pieza explosiva

### ISSUE THREAD

**Issue by empanad4z** [IIC2233/Syllabus#89]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

En el test de H celda derecha me marca como Fail porque se espera un return de True. Esta bien hecho ese test? Porque en el ejemplo usado si la pieza esta en (1,3) y tiene un alcance de 4, el maximo alcance a la derecha seria hasta (1,6). Pero se espera que la explosion sí llegue a (1,9). Estará mal o hay algo que yo este entendiendo mal o no me este dando cuenta?
Adjunto foto del fail y del ejemplo
![image](https://github.com/IIC2233/Syllabus/assets/130818528/60317170-24a2-4747-be76-99957d584567)
![image](https://github.com/IIC2233/Syllabus/assets/130818528/8d11c292-c1e2-44d2-9244-b92f79e3c588)

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by Arielmanriquez** [comment]
Buenas noches, Esta issue está respondida en la issue #58, pero el cuento corto, es que la función verificar alcance solo verifica si la casilla esta en la misma columna/fila que la pieza.

**Comment by empanad4z** [comment]
Entonces ese test especificamente no tiene que ver con el alcance de la pieza, si no conque esté en la misma fila?

**Comment by Arielmanriquez** [comment]
Exacto, el enunciado tiene un ejemplo.
![image](https://github.com/IIC2233/Syllabus/assets/111719384/3afe289f-f3fd-4611-a73f-922335ce8275)

**Comment by empanad4z** [comment]
Aaah vale no habia entendido, el alcance de momento no tiene ningun uso en ese metodo jaja. Muchas gracias!
