### ISSUE TITLE
como restar puntos de ataque al atacar

### ISSUE THREAD

**Issue by jfpena1** [IIC2233/syllabus#89]
Cuando la civilizacion A ataca a la B (asumiendo que el poder de ataque es menor al de defensa), no me queda claro si es que debemos ir restandole el hp dañado de B a el poder de ataque de A. El enunciado menciona el "daño que sobró del ataque ", pero no explicita como modificar ese daño.

Muchas gracias!.

**Comment by jmwielandt** [comment]
Hola!
Te explico con un ejemplo, que es mucho más fácil.
Supongamos que tienes una civ. A y una civ. B.
A cuenta con:
- 1 muro con 50 de HP
- 3 soldados con 30 de HP cada uno.

B está atacando a A, el poder de ataque de B es de 80. Entonces en el cálculo del ataque, partimos con el muro:
```
HP_muro: 50
poder_ataque: 82

B ataca muro de A

HP_muro: 0 (50 - 50 [daño_realizado])
poder_ataque: 30 (80 - 50 [HP_quitado])

HP_soldado_1: 30
poder_ataque: 30

B ataca soldado_1 de A
HP_soldado_1: 0 (30 - 30 [daño_realizado])
poder_ataque: 2 (30 - 30 [HP_quitado])

HP_soldado_2: 30
poder_ataque: 2

B ataca soldado_2 de A
HP_soldado_2: 28 (30 - 2 [daño_realizado])
poder_ataque: 0 (2 - 2 [HP_quitado])

Fin del ataque
```

En otras palabras, el daño que se va causando a cada unidad se resta del poder de ataque y, si queda poder de ataque, pasa a atacar a la unidad siguiente.

Saludos!

**Comment by egarnham1** [comment]
Entonces la civilización B no puede volver a atacar a otra, porque no le queda poder de ataque? O al terminarse el ataque se restaura el poder de ataque al valor original?

**Comment by jmwielandt** [comment]
El mismo turno no puede volver a atacar, pero el siguiente sí y se recalcula su poder de ataque en función de las unidades que tenga vivas.
Para defender lo mismo, se recalcula el poder de defensa según las unidades vivas.
