### ISSUE TITLE
Error en asegurar_ruta (Lists differ)

### ISSUE THREAD

**Issue by h8lz** [IIC2233/Syllabus#89]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/20)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/19)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! tengo un error particular al ejecutar el test de asegurar ruta, el cual me dice que se ha modificado la red original, lo cual no entiendo ya que hice la copia correspondiente y solo cambie 1 por 0 tal como dice el enunciado. El tema es que la matriz resultante si está entre los resultados esperados del testcase.

Adjunto ejemplo del test_04 de asegurar_ruta

![ss test 04](https://github.com/IIC2233/Syllabus/assets/146779280/b0aa645c-ae01-453c-bf82-afd200672e1d)
![ss testcase](https://github.com/IIC2233/Syllabus/assets/146779280/0431c22c-3dfd-434f-b45f-211ee902cd99)

**Comment by SSParzival** [comment]
Buenas, lo que sucede es que cuando se está frente a una lista de listas en Python, la forma de asegurar que la copia sea distinta del objeto original (y no pases a modificar la red original) es diferente a cuando se intenta copiar una lista.

Recomiendo investigar en internet sobre formas para copiar correctamente una lista de listas sin modificar la lista de listas original; hay múltiples maneras válidas.

Adicionalmente, si quieres verificar que la forma que estás haciendo la copia es correcta, puedes hacer lo siguiente:

`lista_original = [ [1,2], [3,4] ]
copia = # Aquí poner cómo estás copiando la lista en la tarea.

copia[0][0] = 9

print(lista_original)`

Si `lista_original` no es `[ [1,2], [3,4] ]`, entonces la forma de copiar que estás utilizando es incorrecta y deberías investigar otra forma.

**Comment by h8lz** [comment]
Solucionado, muchas gracias 😊😊
