### ISSUE TITLE
Ordenar de forma ascendente y descendiente 

### ISSUE THREAD

**Issue by sofiuni** [IIC2233/syllabus#89]
No comprendo si esta bien el orden, en descendiente me da

2020-03-18
2020-05-09 

y en ascendiente me da:

2020-05-09
2020-03-18

Esta bien?

**Comment by gatochico** [comment]
Hola! Orden cronológico ascendiente implicaría ordernar del post **más antiguo al más nuevo**, siendo descendiente ir del post **más nuevo al más antiguo**. Por lo tanto, sería lo contrario del ejemplo que das.

Éxito en tu tarea! :nerd_face:
