### ISSUE TITLE
Problema con QtMultimedia

### ISSUE THREAD

**Issue by conyfernandezt** [IIC2233/syllabus#890]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)

### Contenido

Hola! Estaba tratando de hacer que suene la cancion con QtMultimedia y al correr el codigo me dice que este comando no exite. Ya revise que estuviera correctamente importado, que estuviera bien el codigo y no logro encontrar el error :(

**Comment by JadrinaDA** [comment]
Hola! Vi tu código y el problema es que importas de QtMultimedia un módulo llamada QMediaPlayer por lo tanto no tienes en tu programa QtMultimedia sino QMediaPlayer. Cuando importas de la forma from library import module solo puedes usar el módulo y ese es el punto porque usualmente se usa para no tener que importar la librería entera. Por lo tanto para que te funcione llama directamente las funciones desde QMediaPlayer. Por ejemplo debes poner player = QMediaPlayer() en vez de player = QtMultimedia.QMediaPlayer().

**Comment by conyfernandezt** [comment]
Hola! Cambie eso y ahora me corre esta parte, pero no suena nada :(

**Comment by conyortizsimpson** [comment]
Me pasa lo mismo, lo tiré en un windows y funciona el audio pero en MacOS no logro hacer que funcione. Encontré [esta documentación](https://forum.qt.io/topic/64265/qt-5-5-1-os-x-10-11-static-linkage-qt-multimedia) para que se pueda escuchar en MacOS pero no la entiendo completamente y además es de una versión anterior del SO (es del 2016 el post).

**Comment by JadrinaDA** [comment]
Hola! Si es un problema de mac entonces les podría servir [esta issue](https://github.com/IIC2233/syllabus/issues/888) donde sus compañeros resolvieron el problema. Conyfernandezt probé tu código y me funciona la música así que creo que tu problema podría ser similar al de ellos.

**Comment by rodrigopg908** [comment]
Hola, tengo un error al momento de querer escuchar la musica con QtMultimedia, busque en documentacion y el error en google, pero la solucion es cambiar en el path file// por file ///, pero de estar forma no quedaris un path relativo. que puedo hacer ?
el error es 👍 
DirectShowPlayerService::doSetUrlSource: Unresolved error code 0x80040216 (IDispatch error #22)
asi defini el path en parametros:
![image](https://user-images.githubusercontent.com/62294082/97741670-df29c900-1ac1-11eb-87be-58578c34d581.png)

**Comment by fran-gl** [comment]
Hola, tenía un problema similar con QtMultimedia y encontré que al poner QUrl.fromLocalFile(QFileInfo(path_relativo).absoluteFilePath()) sí funciona la música.
Esto está mal porque ocupa un path absoluto? O es válido usarlo?

**Comment by conyortizsimpson** [comment]
@fran-gl que sistema operativo tienes?

**Comment by fran-gl** [comment]
> @fran-gl que sistema operativo tienes?

macOS

**Comment by rodrigopg908** [comment]
Intente usar QUrl.fromLocalFile(QFileInfo(path_relativo).absoluteFilePath()) y aun asi me envia el mismo error, la venta no se cae pero la musica no suena,
