### ISSUE TITLE
Duda con qt-designer

### ISSUE THREAD

**Issue by felipehen** [IIC2233/syllabus#891]
En QT designer, tengo creado un objeto que designe como "Mapa", para representar el QLabel del mapa de la tarea, pero queria hacerle unas modificaciones, principalmente en el evento dropEvent(), y no se me ocurre como hacerlo dentro del QT Designer.

¿existe alguna forma de solo llamar a dicho objeto en la terminal, para hacer override en su código y que se guarde en el QT designer? o que al menos se guarde en el archivo .py

**Comment by Alonsinho1** [comment]
Hola!

Recuerda que Qt-designer deberia ser ocupado solo para temas de front-end cualquier y cosa que implique logica o funcionalidades de los widgets, es mejor hacerlo directamente desde un archivo.py.

Para esto importa la ventana en el archivo.py y define el metodo que quieras para la widget.

Suerte
