### ISSUE TITLE
ZeroDivisionError: Contenidos semana 11 - Jupyter "ejemplo"

### ISSUE THREAD

**Issue by riadeane** [IIC2233/syllabus#891]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola! Estaba leyendo los contenidos de la semana 11 y al ejecutar el primer ejemplo del tercer jupyter notebook, que ve la eficiencia de listas ligadas vs listas normales me tira un ZeroDivisionError. Solo quería avisar, asumo que pasa porque la lista accede al elemento muy rápidamente(?)

```
Buscar el elemento 500000 en la cola se demoró 0.058841 segundos.
Buscar el elemento 500000 en la lista se demoró 0.000000 segundos.
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-10-6763bda324d1> in <module>
     18 print(f"""Buscar el elemento {N // 2} en la lista se demoró """
     19       f"""{tiempo_lista:.6f} segundos.""")
---> 20 print(f"Buscar un elemento demoró en la cola {tiempo_cola/tiempo_lista:.2f} veces el tiempo de lista.")

ZeroDivisionError: float division by zero
```

**Comment by jtagle2** [comment]
Hola!
Efectivamente es porque se demora tan poco tiempo en acceder a un elemento de una lista, que el tiempo queda como cero. Modificaremos el ejemplo para seguir mostrando en la práctica las diferencias entre una y otra, sin que se caiga el programa.

Gracias por mostrar el error!
Saludos
