### ISSUE TITLE
Personalizar widgets creados en qtdesigner

### ISSUE THREAD

**Issue by tcouso** [IIC2233/syllabus#892]
Hola! 
Quiero sobrescribir algunos métodos de un label que definí en qtdesigner, específicamente para implementar drag'n drop. Basicamente, me interesa poder personalizar labels creados en qtdesigner (algo así como poder referenciarlos en mi código y modificarlos desde ahí, de manera semejante a como se hace con las ventanas). Se agradece mucho cualquier ayuda!

**Comment by furcelay** [comment]
No sé como hacer exactamente lo que dices, pero puedes crear tu subclase de `QLabel` en tu código y luego añadirla a un contenedor dentro de tu ventana cuando modifiques la ventana que creaste en QtDesigner (ve la pestaña containers en los widgets de QtDesigner). Recuerda que los `QLabels` se deben instanciar con el argumento `parent` que corresponde al widget que lo contiene (no tiene por qué ser tu ventana, también puede ser algo contenida en ella).

**Comment by cristozille** [comment]
Hola @tcouso, justamente lo que dice @furcelay debería funcionar. También en la issue #916 se habla mas del drag and drop para que lo revises :)
