### ISSUE TITLE
Versión de PyQt5 en MacOS

### ISSUE THREAD

**Issue by nicolascamhi** [IIC2233/syllabus#892]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

Hola! Cómo puedo hacer downgrade de una version de PyQt5 en Mac? He leído que la última versión tiene problemas en MacOS porque la ventana no se actualiza en tiempo real, sino que hay que cambiarse de ventana y volver a abrirla, lo que dificulta muchísimo el desarrollo de la tarea. He avanzado bastante sin solucionar el problema, pero llegué a un punto de la tarea donde es necesario que la ventana se actualice en tiempo real. He buscado en Google como hacerlo pero no he podido encontrar la respuesta.

Muchas gracias!

**Comment by aaossa** [comment]
Hola @nicolascamhi , ¿cómo instalaste PyQt5? Si lo hiciste con `pip`, tienes que usar el comando de la siguiente forma:

```bash
# En lugar de X, Y, Z usa la versión apropiada (por ejemplo, 5.15.1)
pip install --force-reinstall PyQt5==X.Y.Z
```

Avisa si te funciona o si lo instalaste de otra forma 👌

**Comment by nicolascamhi** [comment]
Gracias! Yo lo instalé con pip. Probé el método que me indicas pero me sale un error, adjunto screenshot del Terminal.

<img width="575" alt="Screen Shot 2020-10-28 at 14 40 27" src="https://user-images.githubusercontent.com/62315390/97475244-c38cba00-192b-11eb-8071-e79c80a9e71b.png">

**Comment by aaossa** [comment]
Mmm ¿por qué pruebas con esa versión en particular? Al parecer ya tienes esa versión instalada (asumo eso porque está usando un archivo de caché). Verifica la versión que tienes con `pip show PyQt5`, y ten ojo a cuál versión quieres "bajar". Por otra parte, si el problema no es funcional, sino que solo dificulta algo el trabajar, puede ser algo riesgoso cambiar mucho la versión de PyQt5, pero mientras estés en PyQt5>=5.0.0 debería funcionar bien 🤔

**Comment by nicolascamhi** [comment]
Mejor seguiré trabajando con la versión que ya tengo instalada, a pesar de que me esté generando algunos problemas. Gracias de todas maneras!

**Comment by nicolascamhi** [comment]
Probé con esa versión en particular porque en internet decía que es la más estable (The reason why we're using version 5.9.2 is that not all (Py)Qt releases are equally stable. This version is guaranteed to work) y que hay algunas que generan errores. No puedo seguir trabajando con la que tengo porque no puedo ir viendo si funciona lo que estoy programando.

<img width="580" alt="Screen Shot 2020-10-28 at 15 21 28" src="https://user-images.githubusercontent.com/62315390/97479700-48c69d80-1931-11eb-9b44-fbde38d3285f.png">

**Comment by aaossa** [comment]
¿Podrías probar con 5.10.1?

**Comment by nicolascamhi** [comment]
Me salió otro error ahora

![Uploading Screen Shot 2020-10-28 at 16.03.44.png…]()

**Comment by nicolascamhi** [comment]
Me salió otro error ahora

<img width="852" alt="Screen Shot 2020-10-28 at 16 03 44" src="https://user-images.githubusercontent.com/62315390/97484369-6d257880-1937-11eb-834f-d4934027aeee.png">

**Comment by aaossa** [comment]
Al parecer es un error de red, ¿podrías intentar nuevamente?

**Comment by nicolascamhi** [comment]
Nop, sigue saliendo un error. Ahora salió el error del principio
