### ISSUE TITLE
Widget.move() actua una sola vez y luego no vuelve a funcionar.

### ISSUE THREAD

**Issue by tvallotton** [IIC2233/syllabus#893]
### Prerrequisitos

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)

### Contenido

Por alguna razón en mi código no logro mover las flechas mas de una vez. Utilizo un QTimer para actualizar periódicamente la posición de las flechas pero solo se mueven la primera vez que se ejecuta el codigo y luego no se vuelven a mover. Acá coloco un código que replica el mismo problema.
```
import sys
from PyQt5.QtWidgets import QApplication, QMainWindow, QWidget, QLabel
from PyQt5.QtCore import QObject, pyqtSignal, QTimer



class MenuDeInicio(QWidget):

    def __init__(self):
        super().__init__()
        self.label = QLabel('Holiwis', self)
        self.numero = 0
        self.timer = QTimer()
        self.timer.timeout.connect(self.moveWidget)
        self.timer.setInterval(1000)
        self.timer.start()
        self.show()


    def moveWidget(self):
        print(f'Se ha "movido" {self.numero} veces')
        self.numero += 1
       # SOLO SE EJECUTA UNA VEZ
        self.label.move(10, 0)


class MainWindow(QMainWindow):

    def __init__(self):
        super().__init__()
        self.setWindowTitle('T02')
        self.setGeometry(200, 100, 250, 200)
        
        self.form = MenuDeInicio()
        self.setCentralWidget(self.form)


app = QApplication([])
form = MainWindow()
form.show()
sys.exit(app.exec_())

```
Como se puede ver por los print statements, el timer funciona correctamente, pero la posicion del Widget no se actualiza. Si me pudieran corregir el codigo de ejemplo por favor. Para yo poder corregir el de mi tarea.

**Comment by JuaniAndres** [comment]
Hola @tvallotton 
El problema que estas teniendo es que ````.move(10,0)```` lo que hace es mover el label a la posición 10,0 de tu ventana de Inicio como esa posición siempre es la misma el label no cambia de lugar. Para que notes la diferencia cambia lo siguiente:
````self.label.move(10, 0)```` -> ````self.label.move(10 * self.numero, 0)````
Con eso notaras que cada vez que llamas a moveWidget este se mueve 10 pixeles a la derecha debido a la multiplicación. 
Quedo atento si tienes más dudas
Éxito con la tarea 😄

**Comment by tvallotton** [comment]
Pense que move funcionaba relativo a su posicion actual. Muchas gracias!!
