### ISSUE TITLE
Error de codificación en uic.loadUiType

### ISSUE THREAD

**Issue by danielcrossg** [IIC2233/syllabus#893]
Hola!

Resulta que cundo uso uic para pasar un widget a mi código el programa falla por un error de codificación. Mi código es el siguiente:

from os import path
from PyQt5 import uic
from PyQt5.QtCore import pyqtSignal

window_name, base_class = uic.loadUiType(path.join('gui', 'ventana_inicio.ui'))

class VentanaInicio(window_name, base_class):
------------------------
Exception has occurred: UnicodeEncodeError
'ascii' codec can't encode character '\xf1' in position 2: ordinal not in range(128) 
------------------------
(...)

Falla en ese punto y de verdad ni idea que hacer...

**Comment by Alonsinho1** [comment]
Has tratado de colocar la dirección directamente, sin tener que ocupar join. No es lo ideal pero almenos de esta manera podremos ver si es un problema del join

**Comment by danielcrossg** [comment]
> 
> 
> Has tratado de colocar la dirección directamente, sin tener que ocupar join. No es lo ideal pero almenos de esta manera podremos ver si es un problema del join

nop, no sirve, me sigue tirando el mismo error

Exception has occurred: UnicodeEncodeError
'ascii' codec can't encode character '\xf1' in position 2: ordinal not in range(128)

**Comment by danielcrossg** [comment]
Ya lo resolví; estaba usando una ñ en un nombre de variable de clase. Lo corregí y el error pasó.

Pesar que reinstalé python por esto :@

**Comment by lily416** [comment]
@danielcrossg no cierres las issues, puede que alguien más tenga el mismo problema durante la tarea. Nosotros nos encargaremos de cerrarla cuando corresponda 😉
