### ISSUE TITLE
Uso de Layouts

### ISSUE THREAD

**Issue by fddelabarra** [IIC2233/syllabus#894]
Hola para la ventana de juego decido hacer como "Main" un VLayout, y dentro de este hay 2 HLayout, ya que decidí. Hacer la parte de arriba primero (donde va el logo, y las actualizaciones de la cantidad de clientes, dinero, etc) y abajo la zona de juego con la tienda, la cosa es que al hacerlo y ejecutarlo lo que me aparece al final son los HLayouts como "pegados" uno al lado de otro, como si los hubiera puesto en un HLayout, no entiendo por qué me pasa eso su los puse en un VLayout, no se cómo arreglarlo 

Ni sé si me hago entender

**Comment by bvasquezm** [comment]
Hola @fddelabarra! 

Si dentro de la distribución de layouts que elegiste, ves que aparecen “pegados”, es posible que necesites subdividir en más layouts lo que deseas ordenar (en este caso, la tienda y el mapa). Quizás en principio también sea buena idea utilizar dos tipos de layout distintos (mapa y tienda) para que no queden “pegados” uno al lado del otro, pero finalmente dependerá de como quieres que sea vea tu juego. Saludos!

**Comment by fddelabarra** [comment]
pero entonces tendria que ubicarlos usando coordenadas? queria evitar eso por comodidad y porque seria mas ordenado a mi parecer

**Comment by bvasquezm** [comment]
Para nada. Con subdividir, me refiero incorporar más Layouts dentro de las tres grandes divisiones que mencionas. Siempre puedes agregar más para que se vea más ordenado, finalmente lo único que hace un layout es “diseñar” (traducido al español) la estética de tu ventana, es decir, como se verán las cosas dentro de ella. Siguiendo siempre la lógica de ordenar su contenido de forma **vertical** u **horizontal**. Pero esto no tiene nada que ver con coordenadas (estas se usan para mostrar labels en sitios específicos de tu mapa), recuerda que inicialmente los layouts distribuyen **equitativamente** su contenido dentro de él. Espero te haya quedado más claro.

**Comment by fddelabarra** [comment]
es que llene de layouts en mi codigo, no se si podrias ver a que me refiero, pero si los subdividi como me dices tu

**Comment by bvasquezm** [comment]
Claro, puedes mostrar una foto de tu ventana y código si deseas.

**Comment by fddelabarra** [comment]
Bueno, digamos que tengo 

        vbox_main = QVBoxLayout()
        vbox_main.addStretch(1)       
        vbox_main.addLayout(hbox_arriba)
        vbox_main.addStretch(1)
        vbox_main.addLayout(hbox_abajo)
        vbox_main.addStretch(1)
        self.setLayout(vbox_main)

El hbox_arriba contiene el logo como QLabel, la reputacion, dinero, etc como etiquetas que de actualizarán (están en un V Layout), excepto la ronda que es un H Layout dentro del V Layout, ya que contiene la etiqueta ronda y el botón comenzar de la ore Ronda, t, y asi,

El hbox_abajo contiene un QLabel que es el mapa, y un V Layout que sería la tienda, que contiene etiqueta "tienda", el QLabel del chef y un H Layout ya que puse 2 tipos de mesa, lo que me queda se ve así

![1591037560460](https://user-images.githubusercontent.com/42189391/83443353-1cb5f780-a439-11ea-8542-a58c6721fd4b.jpg)


Por cierto Todo esto es más que nada de prueba, así que hay cosas como las etiquetas que no deberían tener nada escrito por ahora, solo era ver cómo quedaba

**Comment by bvasquezm** [comment]
En principio no debieses tener problemas si implementaste bien las QHBox, es decir, que efectivamente sean Hbox y no VBox u otra cosa jajajaj. Lo que me produce inquietud dentro de tu código, son los **Stretch**, ya que lo que hacen es comprimir el contenido dentro de tu layout para dejarlo en el centro y eso podría estar acoplando tus Layouts sin querer. Haz uso de stretch cuando sea netamente necesario centrar algo, sino prefiere el uso de spacings. Cuéntame como te va.

**Comment by fddelabarra** [comment]
Quite los Stretch y quedo peor 😅
![1591059379387](https://user-images.githubusercontent.com/42189391/83468309-e8a7fa00-a46b-11ea-8b3b-c3593beed2d1.jpg)

**Comment by bvasquezm** [comment]
Mmm. ¿Tienes una foto del código de esa parte? Quizás podemos encontrar algo mal definido entremedio.

**Comment by fddelabarra** [comment]
Es que tendría que mandar todo el código de esa ventana, no se si se puede hacer 😣

**Comment by bvasquezm** [comment]
Entonces te recomiendo que revises algunas cosas:

* Fíjate que hayas separado correctamente y agregado correctamente los elementos para cada Hbox y el Vbox principal.

* Recuerda que las dimensiones del mapa al ser cargado dentro de un layout, se adapta al mismo de forma automática, es decir, que se quieres verlo en tamaño completo te sugeriría no utilizar layouts (por lo menos para el mapa). Revisa la issue #818 para más información.

* Por último, mi intuición me dice que tu problema se debe a que todos los elementos se encuentran incluidos en un **único Layout horizontal**, quizás los nombraste de la misma forma y por ello no se encuentran separados en la ventana. 

Mucho más no puedo ayudarte, deberás averiguar cuál es la fuente del problema por tu cuenta. De todas formas te deseo todo el éxito y espero puedas solucionarlo!!

**Comment by fddelabarra** [comment]
Ok, gracias!, Veré qué puedo hacer
