### ISSUE TITLE
Uso de señales de Desginer

### ISSUE THREAD

**Issue by vaguirrevergara** [IIC2233/syllabus#895]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Tengo una duda sobre como se van a evaluar las señales, ¿puedo utilizar las señales de designer? ¿o todas las señales tengo que escribirlas en codigo? Obviamente no todas las señales se pueden hacer ahí pero las más simples por lo menos

**Comment by jaimecoloma** [comment]
Hola @vaguirrevergara ! Si puedes utilizar las señales de designer, quizas para evitar malentendidos puedes explicarlo en tu readme cosa de que tu ayudante correcto sepa que señales (botones por ejemplo) fueron conectadas por QtDesigner pero de todos modos no deben ser muchas.
Mientras sigas respetando back-end y front-end no veo ningun problema 😄 
Mucho éxito!

**Comment by vaguirrevergara** [comment]
Muchas gracias!
