### ISSUE TITLE
Platos preparados por el chef

### ISSUE THREAD

**Issue by knight-who-say-ni** [IIC2233/syllabus#895]
Hola!! Esta es una situacion un poco rebuscada, pero que pasa si es que solo queda un cliente, el chef termina de preparar su bocadillo pero en lo que el mesero va a buscar el plato se acaba el tiempo de espera del cliente... En este caso debería aumentar igual la cantidad de platos preparados por el chef??

Gracias!!

**Comment by jitorcas** [comment]
Hola @knight-who-say-ni !

Es un caso rebuscado, sin embargo en el enunciado no se especifica que **sólo** cuando el cliente recibe el bocadillo al chef se le suma un plato preparado, por lo que en el caso que expones **sí debería sumar un plato a la cantidad de platos preparados por el chef**.

Éxito en tu tarea 💯

**Comment by felipefuentesporras** [comment]
Una duda con respecto a un caso similar. Suponiendo lo anterior, pero que además el cliente era el ultimo de la ronda, y por tanto al irse la ronda termina, entonces el chef no alcanzo a "terminar" el plato. ¿ Esto significa que no aumenta la cantidad de platos preparados por el chef?

**Comment by jitorcas** [comment]
Hola @felipefuentesporras!

Solo los pedidos **terminados** se suman a los platos preparados por el chef.
