### ISSUE TITLE
Flecha no se mueve

### ISSUE THREAD

**Issue by Natydlb** [IIC2233/syllabus#896]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! la flecha no se mueve :( pero si se mueve (cambia su posición) cuando cierro la ventana y le pongo de nuevo run, es como que el programa si corriera pero no se actualizará y cuando le pongo run se actualiza la ubicación pero no se mueve más, que podría estar pasando?

**Comment by manearaya** [comment]
Hola @Natydlb!

De casualidad estás usando `move()` para mover la flecha? De ser así quizás te sirva el issue #893. 

También te puede servir usar el método `update()` del widget que se debería actualizar luego de cambiar las coordenadas de la flecha.

Si no es eso, podrías subir lo que llevas a tu repositorio para revisar tu código.

Saludos!

**Comment by Natydlb** [comment]
Lo intente y no funciono :(, ya subi mi código esta en pista_baile.py y pista_baile_BE.py

**Comment by manearaya** [comment]
Encontré que, como instancias las clases antes de conectar las señales, mandas las señales antes de que se conecten a los métodos respectivos: y como la señal nunca llega, la flecha nunca se mueve (si pones prints dentro de cada método, puedes ver que en el backend nunca se van a imprimir). Esto es porque haces que se manden las señales en el init de las clases, y después de que se inicializan conectas las señales. 

Para que esto no sea un problema, te recomiendo hacer que se manden las señales por alguna interacción con el usuario (como un keyPressEvent o algún botón en pantalla). De esta forma las señales se alcanzan a conectar, y de todas formas la partida debería empezar al apretar un botón.

También aprovecho de decirte que la ventana tiene como focuspolicy en Qt Designer NoFocus, y al estar así no va a recibir keyPressEvents. Si quieres que reciba deberías cambiar el foco.

Ojalá te sirva!

**Comment by Natydlb** [comment]
hola! hice todo eso :( lo conecte con el botón comenzar y sigue sin moverse :(

**Comment by manearaya** [comment]
Creo que el problema está en las conexiones de las señales. En el último push que subiste, si pones un print() en la función que usas para actualizar la ventana puedes ver que la función nunca se llama.

**Comment by Natydlb** [comment]
sii :( el problema esta cuando llamo a la función que es setter, en otra issue me dijeron que para llamar a esa funcion la ponga como atributo pero cuando la pongo como atributo creo que piensa que es el atributo "posición", como puedo acceder a esa función sin que me haga problema el ingreso por ser property?

**Comment by manearaya** [comment]
Lo que pasa es que en el código nunca estás llamando al setter. Si quieres que se llame  tendrías que hacer `self.posicion = valor` en `self.ubicacion()` , cosa que se tenga que llamar al setter para que cambie el valor. Si solo pones `return self.posicion` solo se llama al getter.

Es ese el problema?

**Comment by Natydlb** [comment]
sii creo que era eso! pero ahora cambie todo el código ( o la mayoría) porque estaba trabajando solo con una flecha, ahora lo modifique para que hubiera hartas pero me sale este error "QThread: Destroyed while thread is still running"

**Comment by manearaya** [comment]
Te recomiendo leer los issues que hay del tema 😅 (#900 y #931), y si sigue sin funcionar me avisas.

**Comment by Natydlb** [comment]
siii muchas gracias!! por fin se mueven
