### ISSUE TITLE
crear mi propio widget para Qt Designer

### ISSUE THREAD

**Issue by cotefon** [IIC2233/syllabus#897]
Hola :v: ! quisiera saber como hago para crear una clase (por ejemplo una clase MiBoton ) y luego hacer que un botón creado en Qt Designer tenga todos los atributos y metodos que posee la clase creada. He tratado utilizando la función promote to que tiene Qt designer pero no me ha funcionado :pensive: . Esto porque quiero hacer que cada cliente/mesa/chef sea una clase con sus propios atributos y metodos. :sweat_smile:

**Comment by tcouso** [comment]
Hola! Tenía el mismo problema y me sugirieron probar lo siguiente: https://github.com/IIC2233/syllabus/issues/892#issuecomment-636884019
Tampoco me ha funcionado la funcion ´promote()´ de 'QtDesigner´, así que probaré suerte de esta otra forma.
Saludos!

**Comment by cotefon** [comment]
@tcouso muchas gracias!
