### ISSUE TITLE
Uso de SytleSheets, widget hereda el stylesheet del parent

### ISSUE THREAD

**Issue by tqmbanados** [IIC2233/syllabus#897]
### Prerrequisitos

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola,
Estoy trabajando con StyleSheets para darle color y forma a la aplicación. Sin embargo, si a un widget le asigno un cierto style, todos los widgets "hijos" lo tienen también. Probé usar ```setStyleSheet``` en los widgets para "cancelar" el del ```parent```, pero no me ha funcionado. **¿Cómo puedo lograr que una QWidget tenga una StyleSheet particular sin que los widgets que contiene la tengan también?**
Gracias

**Comment by furcelay** [comment]
Hola @tqmbanados !

Para lograr lo que buscas debes usar la siguiente sintaxis en el *stylesheet*:
```
Clase#nombre_objeto {
    contenido del stylesheet
}
```
Eso sería para aplicarlo a un widget específico, si omites el `#nombre_objeto` se heredaría a todos los de la clase correspondiente, y lo que no va entre `{}` se hereda a todos. Ej:

```
QWidget#MiVentana {
	background-color: rgb(33, 33, 33);
}
QPushButton {
background-color: rgb(213, 213, 213);
font: 8pt "Arial Rounded MT Bold";
}
font: 10pt "Arial Rounded MT Bold";
```

Con eso por ejemplo haríamos que la ventana de nombre `MiVentana` (clase `QWidget`) tenga un fondo específico, los botones en ella tienen otras características y todo el contenido tiene un tipo de letra. Como ves a veces la herencia es útil para no escribir un *stylesheet* para cada objeto.

Saludos! :smile:

**Comment by tqmbanados** [comment]
Muchas gracias! Me aclaró muchísmo como funcionan los StyleSheets además que de internet igual me confundía.
