### ISSUE TITLE
Problemas para mover flechas a través de señales

### ISSUE THREAD

**Issue by JoMarchant** [IIC2233/syllabus#898]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hoy me funciona todo a excepción de algunos problemas para despejar la pista de flechas tras terminar una partida, y me propuse separar bien el front-end y back-end de mis flechas. Intenté emitir una señal desde el método run de mis flechas para  que conecten con un método que las mueva en su back-end. El problema es que el juego se cae cuando hago eso, mientras que si llamo directamente al método de la clase del back-end (dentro del run), las flechas se mueven sin problema.

No sé cual es el error en mis conexiones, revise que no se llamara la señal desde el thread principal. **Hice un push hace poco con algunos comentarios en las líneas que me traen problemas por si es posible que me ayuden :(**. Es en los módulos flechas.py, lógica-flechas.py y ventana_juego.py.

**Comment by furcelay** [comment]
Hola @JoMarchant !

Me parece que el problema está en que la señal `mover_flecha` se emite desde el *setter* de la posición de la flecha en el *front-end*, y esa señal se conecta con el método `mueve_flecha` del *back-end*, entonces, para que la señal que desencadena el movimiento se emita, primero debe ejecutarse el *setter*. En otras palabras la flecha solo se mueve si se ha movido antes y por inducción... ¡la flecha nunca se mueve!

Creo que el problema podría estar en que la lógica de las flechas está combinada entre el *front-end* y el *back-end*. Veo que en la clase `Flechas` del *front-end* es la que posee el *thread* que controla a la flecha y envía su posición a `LFlechas` en el *back-end*. Siguiendo la lógica de *front-end* y *back-end* lo ideal sería que el *thread* que mueva la flecha esté en el *back-end* y envíe la información al *front-end* para que ocurra el efecto visual (reposicionar el label), por lo que la secuencia de señales sería en el sentido opuesto (`LFlechas` enviandole la posición a `Flechas`). 

Es solo una observación, puedes resolver tu problema sin tener que cambiar toda la lógica del programa si cambias un poco lo que genera el problema.

Saludos! 😄

**Comment by JoMarchant** [comment]
Muchas gracias!! Lo voy a pensar un rato :D

**Comment by furcelay** [comment]
Hora que estoy viendo mejor quizás creo que confundí la señal `mover_flecha` con `senal_empieza_flecha` que es la que pienso que quieres usar para moverla (por el nombre creí que sería esa), pero no veo donde quieres emitir la señal... 

De todos modos creo que el comentario anterior puede ayudarte a resolver el problema.

**Comment by JoMarchant** [comment]
> Creo que el problema podría estar en que la lógica de las flechas está combinada entre el _front-end_ y el _back-end_. Veo que en la clase `Flechas` del _front-end_ es la que posee el _thread_ que controla a la flecha y envía su posición a `LFlechas` en el _back-end_. Siguiendo la lógica de _front-end_ y _back-end_ lo ideal sería que el _thread_ que mueva la flecha esté en el _back-end_ y envíe la información al _front-end_ para que ocurra el efecto visual (reposicionar el label), por lo que la secuencia de señales sería en el sentido opuesto (`LFlechas` enviandole la posición a `Flechas`).

Debería entonces cada flecha ser una instancia de ```LFlechas``` y cada una de esas tener asignada una instancia de ```Flecha```?

**Comment by furcelay** [comment]
Perdón por la demora en la respuesta pero estaba intentando entender más a fondo el problema. Creo que querías emitir la señal `senal_empieza_flecha` en el `run` de `Flecha`, pero el problema es que `LFlecha` corre en el *main thread* del programa, entonces al recibir la señal el método `mueve_flecha` deja pegado a todo el programa si se ejecuta de esa manera y por otro lado el `run` no tendría sentido porque solo envía la señal y se termina. 

Siguiendo lo que propones, que haya una instancia de `LFlechas` en el *back-end* y que se conecte con la instancia de `Flecha` correspondiente en el *front-end* podría ser una buena solución en términos de separación de *front-end* y *back-end*, y así se ejecutaría un *thread* dedicado a mover cada flecha. 

Pero te recomiendo considerar primero si puedes hacerlo sin tener que cambiar el modelamiento total del programa, considerando que lo que tienes ahora no es el ideal pero funciona correctamente.

**Comment by JoMarchant** [comment]
Decidí quedarme con lo que tengo...intenté cambiarlo funcionaba fluidamente pero a veces se caía aleatoriamente, y aparte se me hizo mas complicado implementar correctamente el efecto de flecha hielo. ¿Influirá mucho en mi puntaje de modularización si lo dejo como está?

**Comment by furcelay** [comment]
Me parece una opción válida dejarlo como lo tienes, considerando la complejidad de cambiarlo. No creo que afecte mucho tu puntaje porque fuera de eso la modularización está muy bien, más que nada tenlo en cuenta para la próxima tarea porque ahí la separación entre *back-end* y *front-end* será aún más importante.

Saludos!

**Comment by JoMarchant** [comment]
Muchas gracias por todos los comentarios y la ayuda!!
