### ISSUE TITLE
Built-ins Prohibidos

### ISSUE THREAD

**Issue by sebadelorenzo** [IIC2233/syllabus#898]
Hola! Para implementar el drag and drop encontré un código en stackoverflow que utilizan el comando `drag.exec_()`. Tengo entendido que el built in de `exec` esta prohibido por lo que quería preguntar si el `exec_` es lo mismo que `exec`. En otras palabras si puedo ocupar esa linea de código o no.

gracias de antemano!

**Comment by matiasmasjuan** [comment]
Hola @sebadelorenzo !

Esta pregunta fue respondida en las *Issues*: #822 y #686 . Pero en resumen, **si** puedes utilizar el método ```.exec_()``` ya que no tiene relación con el built in prohibido ```exec```.

Saludos!
