### ISSUE TITLE
QListWidget para drag and drop

### ISSUE THREAD

**Issue by Krmn390** [IIC2233/syllabus#899]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Tengo desde hace varios días problemas con la forma de programar el Drag and drop de los pingüinos. Sinceramente, he tratado de buscar la información correcta pero es que simplemente no se como aplicar esos comandos de manera práctica en el contexto de la tarea. ¿Qué es más recomendable: usar qlistwidgets o Drag and drop a secas? Por favor ayuda hasta ahora he tratado de programarlo a mano pero no logro llegar a lo que esperan para esta tarea.

**Comment by knight-who-say-ni** [comment]
Holaa @Krmn390 !!

Sobre como usar Drag&Drop, la verdad que no te puedo ayudar mucho, debido a las razones que se mencionan en la issue #835 :(.

Respecto a si usar QListWidget, si usando esa clase logras implementar lo que se pide (agarrar un pingüirin de la tienda y dejarlo en la pista de baile) de manera correcta, entonces no habrá problemas. En lo personal yo creo que es mejor implementarlo con Drag&Drop, ya que por lo que estuve viendo con QListWidget no se puede lograr lo pedido (aunque puede ser que me equivoque).

Exito programando!!
