### ISSUE TITLE
Colisión cliente

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#899]
Hola. En la sección de Clientes del enunciado T02, sale "puedes hacer que aparezcan instantáneamente en ellas", osea que cada vez que aparezca un cliente cada LLEGADA_CLIENTES, éste puede aparecer automáticamente en una mesa desocupada...
Pero, mi duda es que, en la sección Colisiones especiales, sale que si el Jugador colisiona con el cliente mientras lleva un plato, dejará el plato con el cliente...
¿Esto se refiere a la colisión misma de un Cliente?, o se refiere a la colisión de la mesa donde se encuentra el cliente¿?
Para mi es un poco obvio que sería la segunda opción de acuerdo a la primera afirmación. Pero no existen preguntas tontas xd, así que espero a que me lo confirmen :smile:

**Comment by jitorcas** [comment]
Hola @Camila-sty!

Efectivamente puedes asumir que chocando con la mesa del cliente se le entregará el plato. Esto está especificado en la *issue* #882 

Así es! no existen preguntas tontas, éxito en tu tarea! 💯
