### ISSUE TITLE
La terminal de Mac OS no encuentra el comando "Brew"

### ISSUE THREAD

**Issue by simonmb12** [IIC2233/Syllabus#9]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

Hola! Estoy tratando de actualizar git a su ultima versión y de instalar PyQt5. En ambos casos se utiliza el comando Brew:     "brew install git", "brew install pyqt5 --with-python3" pero me sale esta respuesta en la terminal: "-bash: brew: command not found".

**Comment by agucova** [comment]
¿Instalaste [Homebrew](https://brew.sh/) primero?

El error suele deberse a que o no has instalado homebrew todavía o bien a que tu shell (el programa de tu terminal) no tiene Homebrew registrado en `PATH`, la lista de directorios donde busca programas.

Si instalaste homebrew, sigue las instrucciones que aparecen tras instalarlo para agregarlo a `PATH`.

Si no las tienes, puedes probar el siguiente comando (asumiendo que usas `bash`, lo que parece ser correcto por tu error, y que estás usando una versión de macOS inferior a 10.14 Mojave):
```shell
echo 'PATH="/usr/local/bin:$PATH"' >> ~/.bash_profile
```

**Comment by Fernanda1232123** [comment]
Estoy teniendo un problema similar, ¿como sé si tengo instalado homebrew?
Y una vez instalado homebrew, ¿qué instrucciones debo seguir para agregarlo a PATH?

Yo no debiera caer en el último punto porque macOS no es inferior a 10.14

**Comment by simonmb12** [comment]
Yo tampoco tengo una versión inferior a la señalada. Creo que la mía es Big
Sur 11. algo

**Comment by agucova** [comment]
Para instalar homebrew, necesitan primero instalar las herramientas de línea de comando de Xcode con el siguiente comando:

```shell
xcode-select --install
```

Es posible que ya lo tengan instalado (si `git` funciona, ya lo tienen). Después, pueden correr este comando para instalar homebrew:
```shell
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```

Puede que tengan que seguir instrucciones en su terminal, y escribir `Y` (yes) para confirmar la instalación.

En versiones de macOS >= 10.14 Mojave, Homebrew se encarga del `PATH` por ustedes, por lo que necesitan hacer nada más que reiniciar su terminal.

**Comment by pedroriosg** [comment]
@simonmb12 y @Fernanda1232123 pudieron resolver sus problemas??

Saludos!
