### ISSUE TITLE
Duda importación módulos tablero.py y parametros.py

### ISSUE THREAD

**Issue by pazanelli** [IIC2233/syllabus#9]
¿Los módulos auxiliares debo importarlos usando un path desde el syllabus o los copio en mi repositorio personal y los importo directamente? En ese caso, ¿los subo a mi repositorio en GitHub o los guardo en una carpeta .gitignore?

**Comment by gatochico** [comment]
Hola! 
Puedes asumir que los módulos auxiliares que entregamos estarán en la misma ubicación que tu archivo `.py` principal (a ejecutar) y por lo tanto, pueden ser importados directamente. 

Por otro lado, todo archivo que entreguemos nosotros junto al enunciado de la tarea debe ir en el .gitignore :0 a menos que se explicite lo contrario.

Saludos y éxito con la tarea!!
