### ISSUE TITLE
Instalación de Software Obligatorio

### ISSUE THREAD

**Issue by andresfdezc** [IIC2233/Syllabus#9]
¡Hola!

En el Syllabus, en la carpeta de Ayudantías, encontrarán un [script de Python](https://github.com/IIC2233/Syllabus/blob/master/Ayudantias/S00%20-%20SetUp/setup_test.py) que pueden correr para revisar que todo esté instalado correctamente.

Quienes estén usando Ubuntu como sistema operativo, pueden quedarse con Python 3.5. El script anterior también funciona en estos casos.

Si tienen algún problema con este script pueden preguntar en esta issue.

Saludos.

**Comment by Pipelao** [comment]
Gracias por el script :)

**Comment by tanavarrete** [comment]
Me sale 
[PROBLEMA] El módulo None no fue instalado correctamente.
Que esta mal ?

**Comment by andresfdezc** [comment]
@tanavarrete ¿Cómo estás ejecutando el script (Sistema operativo, consola o ide, etc)?

**Comment by tanavarrete** [comment]
idle

**Comment by andresfdezc** [comment]
@tanavarrete ¿En Windows?

**Comment by tanavarrete** [comment]
Si, fui cambiando el código para ver que estaba fallando y parece que es numpy y matplotlib, pero no entiendo porque.

**Comment by Arcoirisky** [comment]
@tanavarrete Quizás las instalaste mal. También uso Windows y hace tiempo tenia problemas con esas dos librerías. Cuando hacía pip, aparecía como que funcionaba pero al momento de importarlas no servía de nada ¿Por qué no intentas instalar los .whl de esta página --> http://www.lfd.uci.edu/~gohlke/pythonlibs/ ?

Fue la única forma de que python no me diera problemas. Bajas el archivo según la libreria, la versión de python y los bits de tu computador. Por ejemplo: Si tienes python 3.6 de 64bits y quieres numpy entonces bajas "numpy‑1.13.1+mkl‑cp36‑cp36m‑win_amd64.whl", luego con la consola vas a la dirección en que lo descargaste y pones "pip install some-package.whl" pensando que some-package.whl es el archivo que quieres instalar.

Al menos eso me salvó a mi. Suerte!

**Comment by tanavarrete** [comment]
lo hice y me sale
C:\Users\toto>pip install numpy-1.13.1+mkl-cp36-cp36m-win_amd64.whl
"pip" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

**Comment by Arcoirisky** [comment]
Usas Wind 10?? 
https://cosasdellucho.blogspot.cl/2016/01/pythoncomo-solucionar-error-pip-en.html

Encontré esa página O:! ¿Ya lo probaste?

**Comment by tanavarrete** [comment]
No, Windows 8.1

**Comment by fnquinteros** [comment]
Hola! para solucionar ese error debería bastar con añadir la carpeta donde tienes instalado python al PATH de la consola de Windows. Tienes que acceder al Panel de Control, en el buscador escribe "variables de entorno". Haces click en editar variables de entorno. En la ventana que se abre, haces click en un botón que dice "variables de entorno...". Luego en la sección de variables del sistema buscas la que dice PATH, la editas y pegas la dirección de la carpeta donde está instalado Python. Con eso debería solucionarse 😄

**Comment by Arcoirisky** [comment]
Según otra fuente mágica --> http://recursospython.com/guias-y-manuales/instalacion-y-utilizacion-de-pip-en-windows-linux-y-os-x/

intenta acceder de forma manual a pip, si ejecuta algo entonces está instalado, sino entonces hay otro problema.

**Comment by tanavarrete** [comment]
Intente de las dos formas y todavía no puedo :(, con la segunda me sale esto:
El sistema no puede encontrar la ruta especificada.

**Comment by Arcoirisky** [comment]
¿Viste el edit de fnquinteros? agregar la dirección de la carpeta "scripts" que se encuentra en la carpeta donde tienes instalado python, al Path.

**Comment by tanavarrete** [comment]
Ahí cambio algo, ahora cuando pongo pip install numpy me sale:
Requirement already satisfied: numpy in c:\users\toto\appdata\local\programs\python\python36\lib\site-packages

**Comment by Arcoirisky** [comment]
Intenta de nuevo el .whl

**Comment by tanavarrete** [comment]
![error](https://user-images.githubusercontent.com/30701219/29151116-07bceac0-7d4d-11e7-9121-e8145d0d7dda.PNG)
No se porque me sale eso

**Comment by Arcoirisky** [comment]
¿Abriste la consola o ejecutaste el comando en la carpeta dónde está el archivo?

**Comment by tanavarrete** [comment]
En la consola

**Comment by Arcoirisky** [comment]
Sí, desde la consola pero debes llevarla hasta la carpeta dónde está descargado el .whl
Te mueves fácil con "cd NombreDeLaSiguienteCarpeta"

**Comment by tanavarrete** [comment]
Ahí pude. Muchas gracias!!!!!.

**Comment by Arcoirisky** [comment]
Yaaaay /o/
