### ISSUE TITLE
Windows: Incorrecta instalación de PyQt6 y Requests

### ISSUE THREAD

**Issue by DaniloCordova13** [IIC2233/Syllabus#9]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [x] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.

### Problema
Hola! Ayer estuve instalando todo lo necesario para el curso, y al momento de llegar a las librerías PyQt6 y Requests no me lanzaron ningún error en la consola WSL. Lo que sucede, es que al momento de verificar si es que están instaladas correctamente en VScode, me dice que estas no existen, dándome a entender que no se hizo la instalación a pesar de que no me tiraba ningún error. Cabe decir que ya intenté reiniciar el computador y hacer el procedimiento de nuevo, pero me sigue apareciendo lo mismo.
![Captura de pantalla (11)](https://github.com/IIC2233/Syllabus/assets/141789725/2557a98f-45d2-4dc8-96c5-619c2f55f8dd)

Saludos!

**Comment by Hernan4444** [comment]
Hola @DaniloCordova13 

Lo que ocurre es que VSCode está intentando ejecutar un python diferente al que instalaste en WSL. Para este curso, no se recomienda depender de VSCode para ejecutar archivos, sino utilizar únicamente la terminal.

Desde tu terminal con WSL, debes hacer `cd` para moverte a la carpeta que tienes tu archivo python, y luego hacer `python3 archivo.py` donde "archivo" es el nombre del archivo que quieres ejecutar. En los [contenidos](https://github.com/IIC2233/contenidos/blob/main/semana-01/1-terminal.ipynb) hay una explicación sobre el comando `cd`.

Con eso, podrás verificar que ya tienes todo instalado y poder ejecutar los diferentes archivos que crees en este curso. De todas formas, por mientras, puedes probar que está todo instalado haciendo lo siguiente:

1. En la terminal con WSL escribir `python3`
2. Con esto, se abrirá una consola de python en tu terminal. Escribir `from PyQt6 import QtGui` y `from requests import get`. Si ambos comandos corren bien, está todo listo.

Luego, en la experiencia del jueves, vamos a interactuar bastante con la terminal para movernos, ejecutar archivos, usar git, etc.

Por el momento, revisa que tengas todo instalado y avísanos si tienes algún error sobre eso.
Saludosヾ(＾-＾)ノ

**Comment by dvillas28** [comment]
Por lo que muestra la terminal en la imagen de la izquierda, el path en el que estas corriendo el programa es una ruta de Windows, lo que significa que estas abriendo VSCode desde Windows, mientras que instalaste `PyQt6` y `requests` en una terminal de Ubuntu.

Puedes abrir VSCode desde la terminal de Ubuntu usado el comando `code .` en el directorio en el que quieras trabajar en **Ubuntu**. Algo asi por ejemplo:

![image](https://github.com/IIC2233/Syllabus/assets/128737225/43d10a01-cf07-40d2-bbfa-620c656cbb7c)

 Si es que la conexion esta bien hecha, deberia señalarte que VSC esta 'corriendo' desde el WSL con Ubuntu en la esquina inferior izquierda, deberia verse algo asi: 

![image](https://github.com/IIC2233/Syllabus/assets/128737225/7bb26dc0-94cc-4605-bcec-bd69a125d903)

Luego de eso puedes probar las si librerías funcionan, como lo indico @Hernan4444 

Espero que te pueda ayudar :)

**Comment by benjasaldias** [comment]
Hola!! Me pasa lo mismo que a @DaniloCordova13 y al seguir los pasos que indica el profesor ocurre lo siguiente:

![Screenshot (4)](https://github.com/IIC2233/Syllabus/assets/141872703/5be49f06-980e-4c53-a218-71040cd3555c)

**Comment by Hernan4444** [comment]
Hola @benjasaldias 

Porfa revisa esta issue donde se habla de jsutamente ese problema con `libGL`
* https://github.com/IIC2233/Syllabus/issues/7
Saludos!

**Comment by DaniloCordova13** [comment]
Profe, seguí todos los pasos indicados y me tiraba el error de libEGL, así que me dirigí a esa issue para seguir las instrucciones, escribí  sudo apt install libgl1-mesa-glx, intenté desinstalar pyqt6 como dijo y me decía que no lo tenía instalado. Intenté instalarlo, no me tiró ningún error, asi que intenté verificar si estaba con lo indicado en esta misma issue, y me volvió a aparecer lo mismo de antes. Dejo ss para que se entienda mejor.
![Captura de pantalla (12)](https://github.com/IIC2233/Syllabus/assets/141789725/5a598c9d-0fb0-471f-b322-1d0f0e867259)

Saludos!

**Comment by Hernan4444** [comment]
Hola @DaniloCordova13  

En tu caso, si el problema es libEGL, entonces prueba con este comando

```cmd
sudo apt install  libegl1 libxkbcommon-x11-0 libopengl0
```

E intenta nuevamente hacer python3 y from PyQt6 import QtGui,

Avísame cómo te va,
Saludos!

**Comment by benjasaldias** [comment]
Tenía el mismo problema que @DaniloCordova13 y por lo menos a mí me funcionó. Muchas gracias!!!
Nos vemos el jueves :)

**Comment by DaniloCordova13** [comment]
Ahí me resultó profe, muchas gracias!!!! :yellow_heart:
