### ISSUE TITLE
Herencia de built-ins en diagrama de clases??

### ISSUE THREAD

**Issue by naquiroz** [IIC2233/Syllabus#9]
Como se representaría en un diagrama de clases la herencia de un _built-in_ (por ejemplo `list`)?

**Comment by bcsaldias** [comment]
Hola!

Citaré la Issue #8 :
> Estos diagramas UML forman parte de la documentación de una pieza de software, para hacer buen mantenimiento y uso del código en general.

UML es utilizado para **diseño de software**, sin atarse a ningún lenguaje en particular. En este caso, el diagrama de clases es para modelar la interacción entre las clases que componen una pieza de software. 

Cada vez que tengas una duda pregúntate: _"Esto es parte de OOP, o de este lenguaje en particular"_. Si es OOP, entonces hay una convención en UML para ese diseño, si es de un lenguaje en particular entonces, cito #8 :

> "deja claro tu diagrama ... indicando en el título del UML que se trata de un diagrama enfocado a Python 3.x."

Así, deberías indicar en el nombre de la clase _List \<built-in\>_ como referencia a que esa clase que estás diagramando es built-in. Esto pasa con muchos lenguajes como Java o C# también.

Por lo tanto, si algo es específico de un lenguaje lo importante es dejar especificadas esas particularidades para que cuando se lea e interprete el diagrama esté todo claro. En general, cada vez que se usa una clase u otra variable por referencia que no es creada por el desarrollador para uso estándar, se usa letra cursiva para llamar la atención (pasa con clases abstractas, e interfaces en otros lenguajes).

Saludos!
Belén
