### ISSUE TITLE
Descarga archivos

### ISSUE THREAD

**Issue by rafarencoretg** [IIC2233/Syllabus#9]
Hola! Una pregunta, cómo descargo archivos de contenidos para poder abrirlos en Jupyter Notebook?

**Comment by MaxAl100** [comment]
Hola, buenas tardes!

Existen dos posibilidades para poder descargar los archivos!

![image](https://user-images.githubusercontent.com/43099597/224504545-eab123f8-cfb5-4d96-bc69-795a4358a45e.png)

La primera es, apretando en "code" apretar luego en "download as zip" que descarga los archivos a tu computador en un archivo .zip que luego tendrías que extraer para acceder a estos.

![image](https://user-images.githubusercontent.com/43099597/224505128-f314b1f5-2cb7-46ae-91a4-148aae667585.png)

La otra opción (y, según yo, mejor) es copiar los archivos a tu computador a través de git. Primero tienes que ir a la carpeta donde quieres que los contenidos estén accesibles y tienes que apretar click derecho para luego apretar "git bash here". Con esto tienes que copiar en el github de contenidos el link que aparece en "Clone" con el cual vas a git bash y pones "git clone <link>". Esto descargará automáticamente la información que está en contenidos y no vas a tener que extraer ninguna carpeta. Otro beneficio es que, cuando los contenidos se actualicen puedes usar el comando "git pull" y los contenidos actualizados también se van a actualizar.

Con los jupyter notebooks descargados, tienes que ir a la terminal, arrastrar la carpeta con los contenidos para moverse en esta carpeta y luego escribir "jupyter notebook" para poder interactuar con los contenidos.

Cualquier duda extra me dices! 😄

**Comment by karenparejas** [comment]
ahi pude hacerlo, muchas gracias!
