### ISSUE TITLE
Duda archivo posts.csv

### ISSUE THREAD

**Issue by Francisco5674** [IIC2233/syllabus#9]
![image](https://user-images.githubusercontent.com/61996440/76691230-820eff00-6627-11ea-859f-5267d0b096aa.png)

En el archivo antes mencionado, existen dos posts compartiendo la linea 36, es eso normal?

**Comment by DCCollao** [comment]
Hola!
 Actualizamos nuevamente el archivo. Gracias por avisar!

**Comment by lily416** [comment]
@Francisco5674 se acaban de actualizar el archivo, si encuentras algún otro error (esperemos que ya no queden 😭) por favor avísanos. 😉

Saludos y éxito en la tarea 👋🐦
