### ISSUE TITLE
Cómo usar Jupyter para encontrar los notebooks

### ISSUE THREAD

**Issue by mnbenimeli** [IIC2233/syllabus#9]
Instalé Jupyter usando pip pero ahora no sé como encontrar los notebooks.
Al ejecutar "jupyter notebook" se me abre la interfaz en el navegador con una infinidad de carpetas y archivos .dll (que me lagean el computador bastante y hace difícil la exploración) y no sé como encontrar o correr los notebooks de los repositorios.

**Comment by ariel-m-s** [comment]
Hola @mnbenimeli!

En este curso tendrás que usar _jupyter notebook_ para leer e interactuar con archivos de extensión ```ipynb```.

Al ejecutar el comando ```jupyter notebook``` **por consola** se abrirá una nueva pestaña en tu navegador predeterminado. En esta pestaña podrás acceder **al directorio desde el que ejecutaste el comando** (y a todos los subdirectorios y archivos del directorio en cuestión). En esta misma interfaz podrás acceder a los archivos ```ipynb``` que en él se encuentren.

Si deseas, por ejemplo, acceder a los contenidos del curso, tendrás que **cambiar de directorio** utilizando el comando ```cd <path>```, reemplazando ```<path>``` por el ruta al repositorio de contenidos (asumiendo que ya lo tienes clonado en tu computador). Luego, tendrás que ejecutar el comando ```jupyter notebook```. Finalmente, una vez en el navegador, basta con hacer _click_ en el archivo a ejecutar.

Happy Pythoning 🐍

**Comment by clolate** [comment]
Hola, yo se que es latoso estar escribiendo el _path_ desde la consola y navegar, sobretodo si tienes muchas carpetas o guardaste los repositorios alejados del _main path_. Lo que yo hago para no estar luchando con la navegación es: 

1.  buscar la carpeta haciendo clicks (para mi es mucho más rápido que escribir, sobretodo si no te sabes de memoria el _path_)
2.  cuando llegues a la que buscas, haces click derecho y seleccionas `git bash here`
3.  cuando se abre la consola escribes `jupyter notebook`
4.  y listo, se abre el navegador directo donde quieres trabajar. 

tengo Windows, no se si sea distinto en mac.

**Comment by Drpinto1** [comment]
Hola!
Complementando la respuesta de @clolate, moverse a través de la interfaz gráfica te ayuda para que sea más intuituvo el proceso (y en algunos casos más rápido), pero esta opción no está disponible de la misma manera en todos los sistemas operativos.

- Windows: Como ya se dijo, en Windows puedes navegar en el explorador de archivos y luego seleccionar `open git bash here`

- Ubuntu/Debian: Similar a Windows, es posible usar el explorador de archivos para encontrar el directorio que deseas y luego hacer click derecho y seleccionar `abrir terminal aquí`

- Mac: A pesar de no venir por defecto la opción para abrir una terminal desde el explorador de archivos, existe una alternativa similar; debes navegar a la carpeta que deseas, para luego abrir una terminal, tipear `cd ` y arrastrar (desde el explorador a la terminal) el ícono de la carpeta a la que deseas ir. Esto copiará el path a la carpeta que elegiste, por lo que este método es un "truco" para hacer lo que explica @ariel-m-s en su segunda opción, sin necesidad de escribir a mano (y de hecho ni siquiera es necesario saber cual es) la ruta al archivo que deseas.

**Comment by mnbenimeli** [comment]
Ahí lo pude solucionar, el cmd estaba raro por tener múltiples sistemas operativos; gracias~~
