### ISSUE TITLE
setup_test.py error qt.qpa.plugin

### ISSUE THREAD

**Issue by SebastianFerra** [IIC2233/syllabus#9]
Hola! cuando corro el setup_test.py en visualcode studio me aparece lo siguiente:

Python está correctamente instalado
GIT está instalado correctamente
qt.qpa.plugin: Could not load the Qt platform plugin "windows" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: direct2d, minimal, offscreen, windows.

estoy utilizando Python 3.7.6 64-bit ('base': conda)

Como podría reinsalar qt o como lo resuelvo? Los instalé inicialmente como lo indica https://iic2233.github.io/wiki/software

**Comment by Pablok98** [comment]
Hola!
Por lo que veo, estas utilizando un _enviroment_ de conda/anaconda. A pesar de que hayas seguido las intrucciones del curso, ya sea a través de una nueva instalación de Python paralela o utilizando la misma base _conda_ que tenías , pasa a veces que los _paths_ se entrelazan y ocurren errores como estos. Te recomiendo desinstalar Anaconda y/o otras instalaciones de Python que tengas y realizar una instalación nueva de Python (tuve el mismo error y reinstalar _pyqt_ no funcionó). 
Si es que tienes dudas de como hacerlo no dudes en preguntar!

**Comment by SebastianFerra** [comment]
Gracias! Tengo instalado jupyter notebook por medio de anaconda, como lo mantengo pero desinstalo anaconda? (quizás estoy hablando nonsense)

**Comment by Pablok98** [comment]
Lamentablemente, es imposible mantener _jupyter_ al eliminar _anaconda_. Tendrás que desinstalar _conda_ por completo y reinstalar _jupyter_ en tu instalación de Python que usarás para el curso, pero no te preocupes, cualquier _jupyter notebook_ (archivo _.ipynb_) que tengas guardado no será eliminado en el proceso.

**Comment by SebastianFerra** [comment]
Ya reinstalé todo y me funciona bien el setup_test.py! así que gracias por eso. Ahora tengo una duda con la instalación de Jupyter, ya lo instale con python -m pip install jupyter, esto descarga la aplicación o me permite abrir .ipynb? como funciona eso :c

**Comment by Juampisaez** [comment]
Hola, para usar jupyter basta con abrir la consola en la ruta donde este el archivo.ipynb que quieras abrir, y escribir "jupyter notebook" o "jupyter lab" segun el que te acomode mas.
![image](https://user-images.githubusercontent.com/48323752/90180318-c8a28a00-dd7c-11ea-804f-9ce843c2dce9.png)
