### ISSUE TITLE
ACTIVIDADES

### ISSUE THREAD

**Issue by Dunkan1** [IIC2233/Syllabus#9]
hola, queria preguntar:
¿se nos informara de que materia trataran las actividades, antes de estas?
y si es asi ¿que tan antes?

**Comment by DiegoAndai** [comment]
Ya están todas con materia en el calendario en https://iic2233.github.io/calendario/ 😃 Si clickeas una actividad en la descripción sale el tema.

**Comment by Dunkan1** [comment]
gracias
