### ISSUE TITLE
Duda test_10_asegurar_ruta

### ISSUE THREAD

**Issue by Arielmild** [IIC2233/Syllabus#90]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/20)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/19)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola, al correr los tests cases para la última función de "asegurar ruta", hay 1 tipo de error de los casos fallidos que me causa inquietud y es que al probar el código con el test 09 me entrega una matriz válida como correcta, pero al probarla dentro de los tests me arroja error y dice que hay diferencias con la red original y que no se debería modificar (pero no es así), además me aparece el siguiente error:
AssertionError: Lists differ: [[0, 1, 0, 0, 0, 0], [0, 0, 1, 0, 0, 0], [0, 1, 0, 1, 0, 0[57 chars], 0]] != [[0, 1, 0, 0, 0, 1], [0, 0, 1, 0, 0, 1], [0, 1, 0, 1, 0, 0[57 chars], 0]]
Sé que actualizaron los tests, por lo que intenté hacer un git pull para ver si es que con los nuevos tests se me arreglaba pero me sigue tirando el mismo error. 
Si alguien sabe qué está pasando estaría muy agradecida. 
Saludos.

**Comment by SSParzival** [comment]
Buenas, lo que sucede es que cuando se está frente a una lista de listas en Python, la forma de asegurar que la copia sea distinta del objeto original (y no pases a modificar la red original) es diferente a cuando se intenta copiar una lista.

Recomiendo investigar en internet sobre formas para copiar correctamente una lista de listas sin modificar la lista de listas original; hay múltiples maneras válidas.

Adicionalmente, si quieres verificar que la forma que estás haciendo la copia es correcta, puedes hacer lo siguiente:

`lista_original = [ [1,2], [3,4] ]`
`copia = # Aquí poner cómo estás copiando la lista en la tarea.`

`copia[0][0] = 9`

`print(lista_original)`

Si `lista_original` no es `[ [1,2], [3,4] ]`, entonces la forma de copiar que estás utilizando es incorrecta y deberías investigar otra forma.

**Comment by Arielmild** [comment]
Ya comprendo, ahí logré arreglarlo. 
Muchas gracias por la orientación.
