### ISSUE TITLE
Validez Fechas

### ISSUE THREAD

**Issue by Rudyjb24** [IIC2233/Syllabus#90]
Las fechas que nuestro programa considera validas tienen alguna limite? Es decir si el usuario ingresa una fecha que existe en el año 1759 o 3026 nuestro programa debe aceptarlo? O existe un limite de fechas "plausibles", es decir que esten mas o menos centrados alrededor de las fechas de los incendios?

**Comment by hanavarrete** [comment]
#79 saludos

**Comment by Rudyjb24** [comment]
Ya habia visto el #79 y no va a eso mi duda, mi problema no es si el programa se cae o no ingresando una fecha fuera de formato (ya me asegure que eso no pase). Mi problema es saber si al ingresar un fecha poco relevante, como por ejemplo el 3 de marzo de 1560 ( que es un formato de fecha aceptable) el programa debería correr con esa fecha o debería pedir una fecha mas relevante? O esto se deja a juicio nuestro?

**Comment by Hernan4444** [comment]
@Rudyjb24 tal como se mencionó en #52 la fecha mínima de ingreso será el 2000 y en #82 la fecha máxima sera el 9999. Cualquier fecha entre medio de estos años es totalmente valida. Espero haber respondido tu duda.

Saludos!!
