### ISSUE TITLE
Duda sobre menú de juego

### ISSUE THREAD

**Issue by mvveram** [IIC2233/Syllabus#90]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, tengo la duda de cual es la diferencia entre guardar la partida y salir de la partida con guardar. Yo lo entiendo como que puedes guardar la partida y seguir jugando, y en la otra guardas y dejas de jugar. ¿Es así?

Además, si guardaste y seguiste jugando, y después sales sin guardar, el archivo creado debe contener solo la guardada ¿Verdad?

Muchas gracias de antemano

**Comment by vicentethomas** [comment]
Hola! Claro, es lo que mencionas. Puedes guardar la partida y seguir jugando, o guardar y salir. 
Con respecto a lo otro que mencionas, si tu guardas luego sigues jugando y después sales sin guardar, entonces vas a perder todo el progreso que hiciste tras guardar. Saludos!
