### ISSUE TITLE
Duda entrega tarea último commit

### ISSUE THREAD

**Issue by jahernandez2** [IIC2233/Syllabus#90]
Hola! Hice el último commit a las 20:00:XX, en teoría debería contar según la pauta, pero quiero estar seguro, me pueden confirmar como se revisa el último commit que cuenta? Ahí un pantallaso que corrobora en parte lo que digo
![image](https://user-images.githubusercontent.com/62116520/132076115-4b2aa193-70d3-4f25-bab1-b2c7d8b736e8.png)

**Comment by gatochico** [comment]
¡ Hola @jahernandez2 ! Si vas a tu repositorio, encontrarás una Issue llamada "T0", con el commit que se detectó fue el último dentro del plazo. Si haces click en este y luego "Browse Files", podrás ver el estado en que quedó tu repositorio al momento de ser recolectado.

Saludos!
