### ISSUE TITLE
Menú de prograposts: Volver al Menú de inicio

### ISSUE THREAD

**Issue by sofiuni** [IIC2233/syllabus#90]
Yo dividi el menu de prograposts en 2 partes, junto el de seguidores. Mi interfaz actual se ve asi:

1. ver posts
2. menu de seguidores
3. menu de prograposts
0. salir

en el Enunciado, 1. va dentro de 3, pero no esta especificado que debe estar en el mismo menu, o asi lo entendi yo. Para "menu de seguidores" dice que debe volver al menu anterior, osea al ver posts/menu seguidores/prograposts/salir, pero en "menu de prograposts", dice que hay que volver al menu de inicio. Yo dividi el menu de inicio y el menu que sigue, son ifs/whiles distintos, y mientras lo podria anidar eso podria causar complicaciones. Debo cerrar sesion y volver a ese menu, o solo volver atras? En el caso de volver al menu inicial, seria mejor anidarlos menus o crear una gran funcion que retorne un arreglo con todas las variables necesarias? esa me parece una muy mal idea pues causaria desorden en el codigo y seria muy complejo de leer y programar.

**Comment by gatochico** [comment]
Hola! 

Todo lo que no esté específicado explicitamente en el enunciado queda a tu libre diseño. Sin embargo, te recomendaría cumplir con lo que sí esta especificado tal como lo dice el enunciado (a pesar de que no estés de acuerdo con ello) con el fin de no perder puntos al momento de corregir. 

Una propuesta para tu pregunta es lo que dice la issue #67 , donde incluyen todo lo específicado en el enunciado, y además de eso agregan opciones extras, con el fin de hacer un menú más ordenado a su gusto. 

Espero haberte ayudado y éxito!! (:

**Comment by sofiuni** [comment]
Si, lei la issue, pero mi pregunta es mas como "tengo que ir al anterior o el de inicio?" hay que poner las dos funcionalidades? o puedo solo ir atras?

**Comment by gatochico** [comment]
En el menú de seguidores, la opcion de volver atrás implicaría que debes volver al menú que te deja elegir entre ir al menú de seguidores, menú de prograposts o salir.

Por otro lado, en el menú de prograposts te dice que se pueda volver al menu de Inicio, por lo que debería pedirse el inicio de sesión nuevamente. Si deseas, puedes incluir también la opción volver atrás que se comportaría como la del menú seguidores del párrafo anterior.
