### ISSUE TITLE
Duda sobre el control de flujo del programa 

### ISSUE THREAD

**Issue by jadaam** [IIC2233/syllabus#90]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

¡Hola! tengo un duda sobre el flujo del programa. Se asume que los archivos .csv serán utilizados únicamente por un usuario a la vez o debemos actualizar su contenido a lo largo de la ejecución del programa. Esto, asumiendo que hay varios usuarios que están  accediendo a la información del archivo y modificándolo continuamente (enviando mensajes, agregando contactos, etc), cómo sería el caso de un servidor real por ejemplo.

**Comment by Tsbalart** [comment]
Hola @jadaam! Para el caso de esta tarea puedes asumir que solo el usuario que ingreso en tu programa es el que está modificando los archivos, sin embargo, de igual forma debes actualizar los archivos .csv, para que en la siguiente ejecución los archivos esten actualizados con la ejecución anterior. En la última tarea veran Networking en donde podrán trabajar con múltiples usuarios conectados a la vez a un mismo servidor! Espero que se haya entendido y éxito con la tarea!

**Comment by jadaam** [comment]
Me quedo clarísimo, ¡muchas gracias!.
