### ISSUE TITLE
Duda diagrama de clases

### ISSUE THREAD

**Issue by mmsaavedra1** [IIC2233/Syllabus#90]
Si deseo hacer herencia de las "clases por defecto de Python", ejemplo:
```python
class Cosa(list):
    # codigo
```

¿Cómo gráfico esto en el diagrama?

**Comment by sebacruzd** [comment]
Pon la clase _list_, sin nada más que su nombre y que tu clase Cosa herede de ella. A la clase Cosa deberás hacerle el diagrama normalmente.
No es necesario especificar nada de _list_ ya que es una clase de Python.
