### ISSUE TITLE
Ejemplo Readme

### ISSUE THREAD

**Issue by Juan379** [IIC2233/syllabus#90]
Hola!
Ya habiendo entregado la tarea...hay algún ejemplo de readme el algún lado para poder referenciar un poco como debería ser uno correcto?

**Comment by entamburini** [comment]
Hola Juan!

Claro que hay ejemplos, te recomiendo primero ver el template que hay en cada carpeta de tareas, esa es la estructura esperada :). Después, se les avisó hace unos días que se les subieron ejemplos de readmes anteriores en [el syllabus](https://github.com/IIC2233/syllabus/tree/master/Tareas/Ejemplos%20Readmes). 

Más atenti para la otra 😉 

Saludos

**Comment by Juan379** [comment]
Jeje perdon. 😬
Gracias!
