### ISSUE TITLE
El sentido de probabilida_de_ganar

### ISSUE THREAD

**Issue by Fernanda1232123** [IIC2233/Syllabus#90]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola,

Entiendo como calcular probabilidad_de_ganar, pero no entiendo el sentido de ese cálculo. En teoría lo uso en la acción apostar dela entidad Jugador, pero no sé qué debería hacer con probabilidad_de_ganar. Hasta ahora tengo un random.choice para elegir si ganar o perder e informo solamente al usuario de su probabilidad de ganar. Pero no los tengo funcionando juntos.

¿Como funciona?

**Comment by MaxAl100** [comment]
Viendo la función dada en el enunciado,
![image](https://user-images.githubusercontent.com/43099597/161823794-6e40e224-6fa7-4847-8bc1-6f0d0db4ddb1.png)
se puede ver que el valor máximo de la función es 1.

Teniendo eso en mente, puedes comparar el valor de la función probabilidad de ganar y algún módulo de la librería random (como se dice en el enunciado) para ver si el jugador gana o no.

**Comment by Cinaraa** [comment]
Tengo otra duda, ¿a que se refiere el enunciado con comparar la probabilidad de ganar con el modulo generado random?

**Comment by LaSamada** [comment]
Hola!
Se refiere, basicamente, a comparar ambos valores y según ese resultado generar una respuesta u otra (considerando que random entrega un valor entre 0 y 1).
