### ISSUE TITLE
Ataque planeta durante la batalla

### ISSUE THREAD

**Issue by PhilippePotin** [IIC2233/Syllabus#90]
Antes de comenzar la batalla un planeta tiene una cantidad de ataque determinada por el numero de soldados/magos y el nivel de ataque respectivo de estos. Luego, con el desarrollo de la batalla se perderán soldados lógicamente. La cantidad de ataque del planeta se mantiene constante durante la batalla o disminuye tal como lo hace el numero de soldados/magos?

**Comment by Arcoirisky** [comment]
Hola! Cómo bien dices, la cantidad de ataque depende del número de soldados. En el enunciado, sección 7 puedes encontrar que dice "Cada ejército se
comporta como una entidad cuyo ataque es la suma de los ataques de todos sus soldados y su vida es la
suma de la vida de todos sus soldados". ¿Por qué no le vuelves a echar un ojo a esa sección y ves si se aclara más tu duda? :D

**Comment by pcseisdedos** [comment]
La idea es que cada soldado o msgo sea un objeto que tiene su vida y ataque? De ser así por qué se define una forma de calcular cuantos están vivos luego de una batalla? En caso que no sea así... cómo puedo saber cuales soldados murieron? Porque como todos tienen distinto ataque debería importar cuales están vivos para efectos del cálculo del ataque del ejercito.

**Comment by jminostroza** [comment]
Me uno a la pregunta anterior...

**Comment by pcseisdedos** [comment]
La verdad estoy medio confundido con esto, porque segun entiendo por el enunciado se "sugiere" de cierta forma que lo modelemos como un todo, porque para calcular los soldados vivos se usa la vida total dividida por el promedio, En base a eso yo simplemente diría que la vida del ejercito es:
 (el promedio del rango de la vida segun la raza) * cantidad de soldados
Por supuesto a lo anterior se le deberian sumar los magos segun corresponda.
Sin embargo por lo respondido en la issue #26 entiendo que se espera que cada soldado (y mago) sea modelado como una instancia aparte, con su propia vida y ataque, lo que complica bastante la modelación por lo que comenté aca hace unos días, pues no tendría como saber cuales soldados mueren primero y no tendría mucho sentido la fórmula para calcular sobrevivientes del enunciado, porque al ser objetos los sobrevivientes serían aquellos que tengan vida mayor a 0.
Además, siento que los datos de vida y ataque de cada soldado (y mago) no son tan importantes, porque no se guardan al finalizar el juego.
Por favor aclarar un poco para ver la mejor forma de modelar el problema.
Muchas gracias :)

**Comment by pcseisdedos** [comment]
Por favor aclarar un poco para ver la mejor forma de modelar el problema.
Muchas gracias :)

**Comment by Hernan4444** [comment]
Tal como se respondió en #26 se espera que cada soldado y mago sea una instancia aparte. No se especificó más sobre la situación de batalla para que ustedes tomaran algunas decisiones de como implementarlo. Para el calculo de sobrevivientes, se dijo en otra issue que pueden dividir por la vida promedio de los soldados, la vida mínima, vida máxima, la vida que es moda, etc y así obtener la cantidad, pero quienes también es decisión de ustedes.

El fin de esta parte es que **ustedes decidan la modelación** a implementar respetandolas restricciones señaladas: 
1. Ataque y vida diferente por soldado y mago.
2. Calcular los sobrevivientes según algunas decisiones que ustedes tomaron.
3. Asegurarse que las decisiones tomadas no generan inconsistencia como que aparezcan más sobrevivientes de los que había antes.

La idea de esto es aproximarlos un poco a la situación en donde uno debe tomar decisiones de diseño, pero respetando algunas condiciones solicitadas. En este caso, podrán tomar varias decisiones y mientras respeten los 3 puntos, estarán bien.

Saludos y espero haber aclarado mejor sus dudas sobre el sistema de batalla✌️
