### ISSUE TITLE
Acciones por turno

### ISSUE THREAD

**Issue by decastelli** [IIC2233/syllabus#90]
Es posible para el usuario realizar mas de una acción en un mismo turno, es decir construir edificios y extraer recursos por ejemplo?

**Comment by BFFV** [comment]
El usuario puede realizar todas las acciones que quiera en un turno, siempre y cuando cumpla con los requisitos en recursos o personas para realizar dichas acciones. La única excepción sería que solo puede atacar 1 vez en su turno.

**Comment by aacamhi** [comment]
La computadora también podría hacer más de una acción por turno? Porque en el archivo acciones.csv siempre realiza solo una

**Comment by BFFV** [comment]
En el caso de la computadora sólo realiza una, a diferencia del jugador.
