### ISSUE TITLE
Alternativa para las IDE?

### ISSUE THREAD

**Issue by M-Alva45** [IIC2233/Syllabus#90]
* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.

Hola, hay alguna alternativa mas rápida y eficiente a las interfaces de desarrollo?
Llevo alternando entre Sublime y Visual studio pero ambas me dan errores ajenos a mi codigo de los cuales desconozco el origen, trato de ejecutar los test cases y aveces funciona y a veces no. Es mas, para que se ejecute correctamente los test cases en visual studio, tengo que desinstalarlo y volverlo a instalar cada vez.
Llevo codeando en google collab por el momento ya que es la unica solucion a corto plazo que tengo.
Cualquier ayuda sería apreciada

**Comment by mskdancers** [comment]
Hola! En mi opinión VSCode es la mejor opción en cuanto a interfaces de desarrollo. Desafortunadamente, puede ser un poco difícil acostumbrarse, ya que tiene muchas funciones distintas. Si mandas una foto del error que te da VSCode podríamos ayudarte más :) 
saludos!

**Comment by mskdancers** [comment]
Además, recuerda que usaremos VSCode principalmente para editar el código, mientras que para correrlo usaremos directamente la terminal.
