### ISSUE TITLE
QTimer: Destroyed while trhead still running

### ISSUE THREAD

**Issue by amahns1** [IIC2233/syllabus#900]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

Hola!

Cómo se produce y cómo puede solucionarse el error QTimer: Destroyed while trhead still running?
Incluso ocupando los ejemplos de los contenidos aparece.

`       self.timer_flecha = QTimer(self)
        self.timer_flecha.setInterval(1000)
        self.timer_flecha.timeout.connect(self.creador_de_flechas)
        self.timer_flecha.start()

    def creador_de_flechas(self):

        thread_flecha = ThreadPrincipiante(self, self.width(), self.height())
        thread_flecha.actualizar.connect(self.actualizar_label)

    def actualizar_label(self, label, x, y):

        label.move(x, y)`

ThreadPrincipiante está en otro módulo. ¿Qué es lo que está mal implementado?

Gracias :)

**Comment by danckoo1** [comment]
Hola! supongo que tú error dice Qthread en vez de Qtimer o no?
Sobre el problema, supongo que es porque en el metodo `creador_de_flechas()` creas el thread en la variable `thread_flecha`, sin embargo a penas termina el método de ejecutarse la variable del thread deja de exitir y se destruye el thread. Todo esto bajo el supuesto de qué haces un `thread_flecha.start()` en alguna parte, ya que el error dice que está ejecutándose, avísame si era eso!

**Comment by amahns1** [comment]
Lo tengo asi por el ejemplo de los contenidos:

`self.timer_crea_comida = QTimer(self)
        self.timer_crea_comida.setInterval(1000)
        self.timer_crea_comida.timeout.connect(self.creador_de_comida)
        self.timer_crea_comida.start()

        self.comida = []

    def creador_de_comida(self):

        nueva_comida = Comida(self, self.width(), self.height())
        nueva_comida.actualizar.connect(self.actualizar_label)
        self.comida.append(nueva_comida)
        self.comida_creada += 1
        print(f"Has creado {self.comida_creada} unidades de comida\n")

    def actualizar_label(self, label, x, y):

        label.move(x, y)`

**Comment by danckoo1** [comment]
Si a lo que iba es que no estás haciendo el paso de guardar el thread, que en el ejemplo correspondería a
`self.comida.append(nueva_comida)`

**Comment by amahns1** [comment]
Aaah perdón te había entendido mal. Efectivamente era por eso.

Muchas muchas gracias! :)
