### ISSUE TITLE
Como no abrir la consola al ejecutar programa

### ISSUE THREAD

**Issue by Ignacioislae** [IIC2233/syllabus#900]
Hola,
tengo la siguiente duda: ¿Como hago para solo abrir la ventana y no abrir la consola al ejecutar mi programa?

Cada vez que ejecuto mi programa se abre la consola junto con la ventana/s que tiene mi programa, aveces es útil para revisar errores, pero me gustaría que una vez este listo no se abra por estética.

Saludos!

**Comment by kadroguett** [comment]
Hola @Ignacioislae 
Esta pregunta ya se contesto en la issue #710, recuerda revisar el compilado de issues para evitar duplicar dudas.

**Comment by Ignacioislae** [comment]
Dale gracias! Estare mas atento.
