### ISSUE TITLE
Duda con función de pausa y música

### ISSUE THREAD

**Issue by ngsuarez** [IIC2233/syllabus#901]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

En el enunciado sale que cuando se coloca la pausa, todo se detiene sin reiniciar a su estado inicial. **¿Esto también aplica a la música?** Es decir, ¿la música no puede partir desde 0 al reiniciar la ronda?

**Comment by jaimecoloma** [comment]
Hola @ngsuarez! Efectivamente la música debe empezar desde donde quedó, no se puede reiniciar.

**Comment by ngsuarez** [comment]
Ok! gracias

**Comment by margavicunas** [comment]
> Hola @ngsuarez! Efectivamente la música debe empezar desde donde quedó, no se puede reiniciar.

Hola! Pero en la Issue #777 dijeron que no era necesario que empezara desde donde quedó :(

**Comment by jaimecoloma** [comment]
Hola! @margavicunas, Qmedia si tiene la función de reanudar pero Qsound solo puede detener y empezar, finalmente para cumplir con los requisitos basta con detener y empezar la música. Mis disculpas si eso les pudo haber generado algun inconveniente! Mucho ánimo ❤️

**Comment by margavicunas** [comment]
Jaja tranquii, gracias por responder 💓
