### ISSUE TITLE
Cambiar nombre de sprites

### ISSUE THREAD

**Issue by BelenSilva1204** [IIC2233/syllabus#901]
Holaa, es posible cambiar los nombres de las sprites que nos entregaron?

**Comment by lily416** [comment]
Hola @BelenSilva1204, 

No deben cambiar los nombres de las sprites, debido a que deben ignorar la carpeta `sprites/`, lo cual podría causar problemas al momento de corregir tu tarea. Cada vez que se corrige, el correcto agrega los archivos y carpetas que les pedimos ignorar, lo que causaría que el ayudante tenga las imágenes con un _path_ distinto al que utilizaste.

Recuerda que para facilitar el acceso a los _paths_ de las imágenes, estas deben estar guardadas como parámetros en tu archivo `parametros.py`

Saludos y éxito en la tarea 👋🍭

**Comment by miguel-mrtnez** [comment]
Cómo lo hacemos si tenemos nuestras propias sprites personalizadas? creamos otra carpeta para almacenarlos y la subimos?

**Comment by lily416** [comment]
Hola @miguel-mrtnez,

En el enunciado se indica que deben crear otra carpeta y asegurarse que no sea ignorada por el `.gitignore`, ya que sino no se podrá realizar la corrección de sus tareas.

Saludos y éxito en la tarea 👋🍬
