### ISSUE TITLE
Error en Qt Designer: assitant.exe does not exist.

### ISSUE THREAD

**Issue by Ignacioislae** [IIC2233/syllabus#902]
Hola,
tengo el siguiente problema, tengo el Qt Designer y el assitant instalados, pero al usar el la funcionalidad Help en Qt Designer me lanza error porque no encuentra el archivo assitant.exe. ¿Como se puede solucionar?

Saludos!

PD: Adjunto imagen
![image](https://user-images.githubusercontent.com/53800034/83435047-8dddb680-a409-11ea-8eb6-56dfd8a29317.png)

**Comment by kadroguett** [comment]
Hola @Ignacioislae 
Prueba abriendo cmd e ingresando el siguiente comando:
mklink /J "path_error" "path_error_sin/bin"

Donde path_error es la ruta que te sale en el error hasta el segundo bin (sin contar assistant.exe) y path_error_sin/bin es la misma ruta pero quitándole el segundo /bin (o sea "...pyqt5_tools/Qt/bin").
Cuéntame si te resulta, yo lo hice recién y me funcionó.

**Comment by Ignacioislae** [comment]
No me funciono.

**Comment by kadroguett** [comment]
Cuando lo hiciste te apareció "unión creada para.." ? 
![image](https://user-images.githubusercontent.com/31357861/83706430-6cd1bd00-a5e5-11ea-849f-a5569fa20a76.png)

**Comment by Ignacioislae** [comment]
Sii

**Comment by kadroguett** [comment]
Y te sigue apareciendo el mismo error? podrías buscar la carpeta que te aparece en el error y sacarle un pantallazo por favor

**Comment by Ignacioislae** [comment]
![image](https://user-images.githubusercontent.com/53800034/83706799-6c85f180-a5e6-11ea-8b77-2515fc9aec96.png)

**Comment by Ignacioislae** [comment]
![image](https://user-images.githubusercontent.com/53800034/83706878-98a17280-a5e6-11ea-91df-d74ca6785ddb.png)

**Comment by kadroguett** [comment]
Está mal, en la primera línea es con dos `\bin` mientras que en la segunda es un solo `\bin`. Fíjate en la imagen que subí

**Comment by Ignacioislae** [comment]
![image](https://user-images.githubusercontent.com/53800034/83707216-79efab80-a5e7-11ea-88fd-51a5ec28dd7e.png)

Me esta tirando este mensaje ahora

**Comment by kadroguett** [comment]
Cuando abres `bin` vuelves a la misma carpeta?
![image](https://user-images.githubusercontent.com/31357861/83707363-d9e65200-a5e7-11ea-84cb-c25237daad59.png)

**Comment by Ignacioislae** [comment]
Sii, pero me agrega otro bin en el path arriba

**Comment by kadroguett** [comment]
En el path que usas en el cmd te falta entrar a Qt y bin, fijate que tiene que ser igual al del error

**Comment by Ignacioislae** [comment]
Ahora funciono! Gracias!

**Comment by kadroguett** [comment]
De nada, éxito en tu tarea!
