### ISSUE TITLE
Flecha espacio intersecciones

### ISSUE THREAD

**Issue by totoiii** [IIC2233/syllabus#902]
Tengo una duda que me genera una parte del enunciado:
""Cuando aparece esa flecha no pueden aparecer otras en la misma fila"" y entiendo a que se refiere a que si creo esta flecha no puedo crear otra al mismo tiempo que esta, ***es asi?***
y la duda es:
**¿Puede una flecha espacio intersectarse con otra flecha?*** Esto ocurriría en el caso de que despues de una flecha espacio saliera una flecha dorada y debido a su velocidad terminaria intersectando a la flecha espacio

**Comment by knight-who-say-ni** [comment]
Hola @totoiii !!

Efectivamente, si se crea una flecha espacio, no se deberían crear más flechas al mismo tiempo y que empiecen juntas.

Respecto a tu duda, debiera manejarse de la misma forma que las intersecciones entre otras flechas, como se menciona en las issues #796 y #845. La restricción de que la flecha espacio este sola en su fila va para cuando se crea, pero si es alcanzada por una dorada no hay contradicción a eso.

Espero haberte aclarado la duda, éxito programando!!
