### ISSUE TITLE
Problemas para debuggear QT en  VScode

### ISSUE THREAD

**Issue by sa-Appel** [IIC2233/syllabus#903]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

mi debbuger no funciona,  adjunto imagen del error que me tira, por lo que investigue es algo relacionado a debuggear QT,
![Capture](https://user-images.githubusercontent.com/62345634/97501675-753de200-1950-11eb-8188-47d878c18c66.PNG)
Si tienen mas claro que es o como solucionarlo,  ya que de base estoy atrasado con la tarea, no tengo como seguir trabajando

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by aaossa** [comment]
Hola @sa-Appel , disculpa, no entiendo bien tu problema. ¿Es algo relacionado con PyQt5 o con el uso de tu editor de texto? Si es lo último, podrías ejecutar el código desde la consola en lugar de solo desde VSCode. Si es lo primero, ¿podrías probar con un ejemplo chico y ver si te ocurre el mismo error? Dejaré un ejemplo de los contenidos para que revises si te funciona (en caso de ser lo primero). 

```python
import sys
from PyQt5.QtWidgets import QWidget, QApplication

class MiVentana(QWidget):
    def __init__(self):
        super().__init__()

        # Definimos la geometría de la ventana.
        # Parámetros: (x_superior_izq, y_superior_izq, ancho, alto)
        self.setGeometry(200, 100, 300, 300)

        # Podemos dar nombre a la ventana (Opcional)
        self.setWindowTitle('Mi Primera Ventana')


if __name__ == '__main__':
    app = QApplication([])
    ventana = MiVentana()
    ventana.show()
    sys.exit(app.exec_())
```

Si es algo específico de VSCode, revisa cómo estás ejecutando el *debugger*, hay una *issue* que habla un poco de esto: https://github.com/IIC2233/syllabus/issues/645. Espero tu respuesta para saber más de tu problema. ¡Ánimo y éxito con la tarea 🙌!

**Comment by sa-Appel** [comment]
No entendia muy bien lo que pasaba tampoco , creo que un error de QTread , al final cree un archivo .json nuevo y me funciona el debugger.
