### ISSUE TITLE
Ruta de los sprites.

### ISSUE THREAD

**Issue by based-on-what** [IIC2233/syllabus#903]
Hola a todos, actualmente, en mi programa para llamar a la ruta de los sprites, lo hago con el formato **f"sprites/{subcarpeta}/sprite.png"**, es decir, el _path_ está dentro del mismo programa, no lo tengo implementado en **parametros.py**, porque no vi nada explícito en el enunciado con respecto a esto (o quizás leí mal), ¿da lo mismo de qué forma esté implementado el path de los sprites en el programa o tiene que estar sí o sí en el archivo de parámetros?

Saludos y gracias.

**Comment by jitorcas** [comment]
Hola @based-on-what 

Tal como se dijo en la issue #901 para facilitar el acceso a los *paths*, se deberían incluir en `parametros.py`. 

Éxito en tu tarea! 💯

**Comment by based-on-what** [comment]
> Hola @based-on-what
> 
> Tal como se dijo en la issue #901 para facilitar el acceso a los _paths_, se deberían incluir en `parametros.py`.
> 
> Éxito en tu tarea! 💯

Ya implementé los paths en parametros.py, pero en formaro _string_, ("sprites/carpeta/sprite.png") no importando mediante os.path, ¿es eso relevante?

Saludos y gracias.

**Comment by TdelrioC** [comment]
> > Hola @based-on-what
> > 
> > Tal como se dijo en la issue #901 para facilitar el acceso a los _paths_, se deberían incluir en `parametros.py`.
> > 
> > Éxito en tu tarea! 💯
> 
> Ya implementé los paths en parametros.py, pero en formaro _string_, ("sprites/carpeta/sprite.png") no importando mediante os.path, ¿es eso relevante?
> 
> Saludos y gracias.

Usas el archivo parámetros.py para cargar los sprites, osea lo importas a algún lado para usarlo después? Creo que para eso es y eso es lo que hay que hacer. No sé si hay otras formas aparte de os.path supongo que sí funcionan otras formas debería estar bien.
No soy ayudante, también me pasó eso cuando empecé con sprites y eso fue lo que entendí del enunciado y issues

**Comment by jitorcas** [comment]
Hola! @TdelrioC y @based-on-what.

La idea de `os.path` es que no utiliza un separador ( '/ 'o ' \\') determinado para acceder a las rutas, por lo que si un ayudante tiene un sistema operativo diferente al tuyo no tendrá problemas al correr tu tarea y acceder a los archivos.
