### ISSUE TITLE
Issue con gitignore

### ISSUE THREAD

**Issue by CataSudo** [IIC2233/syllabus#904]
Hola, escribí en mi .gitignore ciertos documentos pero siguen aparenciendo en mi repositorio personal. ¿Por qué pasa esto?
Muchas gracias!

**Comment by Alonsinho1** [comment]
Hola!

habías subido estos archivo antes de hacer el gitignore?

si hiciste eso te recomiendo ocupar el comando rm de git

**Comment by mmunoz12** [comment]
Hola! me pasa lo mismo, las carpetas y los archivos siguen apareciendo en el repositorio aun asi despues de usar git rm.

**Comment by Alonsinho1** [comment]
Hmm, si usaste bien el comando siginificaria que hay errores en el gitignore.

Trata esto

1) Escribe en el gitingore todo lo que quieras ignorar.
2) Saca los arhivos que no quieres que se suban y ponlos en algun lado x
3) has push del repositorio
4) Los contenidos ya no deberian estar en git
5) vuelve a meter los archivos que quieres ignorar en tu repo
6) si haces push despues de esto no se te deberian subir  si el gitignore esta bien hecho

**Comment by mmunoz12** [comment]
Ya funciono! gracias!
