### ISSUE TITLE
Diseño Back-Front

### ISSUE THREAD

**Issue by totoiii** [IIC2233/syllabus#904]
Es considerado una mala forma de desarrollar el diseño back-front end la siguiente?:
-Creo una ventana en back-end y creo un QObject en el front que reciba como argumento a dicha ventana y que ese objeto lo unico que haga es realizar cambios en la interfaz en dicha ventana.

**Comment by aljara97** [comment]
Hola @totoiii! según lo que entiendo la clase QObject se encargaría de manejar la lógica de la ventana, en ese caso no correspondería a una adecuada separación entre backend y frontend, ya que, estas clases deben estar conectadas mediante señales. Te recomiendo revisar la issue #780 donde se aborda este tema en mayor profundidad.

Mucha suerte con tu tarea 🐧

**Comment by totoiii** [comment]
Es que aún asi estas dos carpetas se relacionan unicamente con señales, el backend que seria mi ventana recibe cosas de la interfaz, la trabaja y si es necesario cambiar algo en la interfaz, mi backend manda una señal al frontend y este es el que termina cambiando la interfaz. Lo unico distinto es que mi ventana está creada en el backend

**Comment by totoiii** [comment]
Si lo hago así, sigue siendo una buena practica?

**Comment by aljara97** [comment]
El resto está bien diseñado, pero tener una ventana instanciada en backend no es una buena práctica

**Comment by totoiii** [comment]
si lo dejo asi, tu creee que bajaría mucho la nota?

**Comment by aljara97** [comment]
Para esta tarea hay un item asociado a una adecuada separación backend y frontend y probablemente no obtengas el puntaje asociado en items en donde uses estas instancias, ya que no se hará con un correcto uso de señales.

Te recomiendo buscar una manera de crear ambas entidades de manera separada, ya que evitarás acoplamiento y cohesión, además de posibles errores asociados a esta modelación. En caso de que tengas algún problema creando esta separación siéntete libre de abrir otra issue.
