### ISSUE TITLE
Actualizar parámetros una vez se modificó parametros.py

### ISSUE THREAD

**Issue by furcelay** [IIC2233/syllabus#905]
Hola!
Puedo modificar sin problemas el archivo `parametros.py` (haciendo un open/write), pero al hacerlo no varían los valores de los parámetros en el módulo `parametros` en la ejecución actual del programa, los cambios solo se ven cuando se vuelve a ejecutar el programa y se importa nuevamente `parametros.py`. 

Para ejemplificar mi problema supongamos que tengo el siguiente archivo `parametros.py`:
```python
PARAMETRO_X = 1
```
Y el siguiente módulo que importa y modifica `parametros.py`:
```python
from parametros import PARAMETRO_X


def modificar_parametros():
    with open("parametros.py", 'w', encoding='utf-8') as archivo_parametros:
        archivo_parametros.write("PARAMETRO_X = 0\n")


def leer_archivo_parametros():
    with open("parametros.py", 'r', encoding='utf-8') as archivo_parametros:
        print(archivo_parametros.readline().strip())


def imprimir_parametro():
    print(f"PARAMETRO_X = {PARAMETRO_X}")


if __name__ == "__main__":
    leer_archivo_parametros()
    imprimir_parametro()

    modificar_parametros()

    leer_archivo_parametros()
    imprimir_parametro()
``` 

Al correr este archivo el otuput es el siguiente:
```python
PARAMETRO_X = 1
PARAMETRO_X = 1
PARAMETRO_X = 0
PARAMETRO_X = 1
```

Como se vé en el último print, si bien `PARAMETRO_X` se actualizó en `parametros.py`, este no cambió en el módulo `parametros`.

**Comment by lily416** [comment]
(La respuesta que viene a continuación se basa en lo dicho en [los comentarios de la issue #680](https://github.com/IIC2233/syllabus/issues/680#issuecomment-637035008))

Tal como comentabas anteriormente, al importar las variables del archivo `parametros.py` estas se guardan en un diccionario, por lo que se pueden modificar sus valores y **no esto no afectará al archivo `parametros.py`**. A su vez, si modificas el archivo después de importar las variables, estas **no se verán afectadas por los cambios del archivo**.

Por lo que, para cambiar los valores en la partida actual y que estos permanezcan en las siguientes ejecuciones del programa, deberás cambiar el valor de la variable importada y el contenido del archivo.

Espero que quede claro 😄 
Me encantaría poder mostrarte un ejemplo, pero es más de lo que te puedo decir 😞

**Comment by furcelay** [comment]
@lily416 Muchas gracias denuevo, tengo una idea de cómo solucionarlo cambiando la estructura de `parametros.py` para que almacene los parámetros de otro modo. Espero que funcione :upside_down_face:!

**Comment by lily416** [comment]
Esperemos que funcione. 🙏 
Si tienes algún problema no dudes en comentar o hacer otra issue. 😉

**Comment by furcelay** [comment]
Pude solucionar el problema, resultó muy bien y el código quedó más bello 😄 !

**Comment by milosoria** [comment]
@lily416 Hola! Si los paramteros no cambian una vez importado, es posible que el cambio en los parametros solo se apliquen en la siguiente partida? Esto significaría tener el puntaje del bonus?
Gracias!!
