### ISSUE TITLE
Parámetro LLEGADA_CLIENTES

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2233/syllabus#906]
Hola, en el enunciado dice que un cliente puede aparecer cada LLEGADA_CLIENTES, eso lo defino yo? Tampoco entiendo que hace un cliente si es que al cumplirse el tiempo LLEGADA_CLIENTES no hay mesas desocupadas, no puedo sentarlo todavia hasta que haya un tiempo vacio y pongo a correr su tiempo de espera para poder controlarlo ?

Por otro lado que pasa si es que un chef falla en crear un plato ? De esto me doy cuenta cuando el mesero va a retirar el plato (colisión entre mesero y chef) ? En este caso el mesero no retirase nada por que se equivoca el chef, este comenzará automáticamente a preparar un plato nuevamente? Por ultimo, si el plato se preparo pero el chef se equivoco, se descuenta dinero por haber preparado el plato aunque no se haya entregado?

**Comment by kadroguett** [comment]
Hola @dsepulveda3 
En primer lugar recuerda que las issues deben ser sobre un tópico en particular para así organizarlas de manera más sencilla, por lo que te responderé la primera pregunta y te pido que hagas la segunda en otra issue por favor.
Con respecto al parámetro LLEGADA_CLIENTES, si , tu defines el valor que este tomará. Como no se menciona en el enunciado puedes comenzar a correr el tiempo LLEGADA_CLIENTES en el momento en que se desocupen las mesas o bien que esté corriendo constantemente y no tomar en cuenta la probabilidad de cada cliente si es que las mesas se encuentran ocupadas. 
Por otro lado, te recomiendo comenzar a contar desde que se desocupan las mesas, ya que de otra forma si genera problemas para la corrección podrían descontarte puntos.

**Comment by dsepulveda3** [comment]
Emmm dale. Lo estaba haciendo de la primera manera y es bastante complicado. Que comando de thread me permite esperar hasta que ocurra un evento (que no sea tiempo).
O sea quiero un método que me permita dormir el run hasta que una variable se convierta en True por ejemplo

**Comment by kadroguett** [comment]
Te recomiendo revisar la documentación de Qthread: https://doc.qt.io/qt-5/qthread.html 
Ahí podrás encontrar una forma de implementar lo que buscas
