### ISSUE TITLE
Mi porgrama se cae con muchos pingüinos

### ISSUE THREAD

**Issue by En-clases** [IIC2233/syllabus#906]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, ayer subí la issue #866 pero parece que no la vieron :c. dejo acá lo que contenía: 

Hola, he implementado el drag and drop de los pingüinos y sus movimientos. Todo funciona bien siempre y cuando no hayan mas de 6 pingüinos (aproximadamente) en la pista de baile y jugar en la dificultad más difícil. Al tener muchos pingüinos el programa se cae sin lanzar ningún error. Cuál podría ser el problema?

**Comment by knight-who-say-ni** [comment]
Holaa @En-clases !!

Voy a cerrar esta issue, altiro te respondo la original 😁 . Llevamos la cuenta de que issues han sido o no respondidas, asi que si tu respuesta se demora mucho no es porque no hemos visto tu pregunta.
