### ISSUE TITLE
Implementar teclas simultaneas o secuencia

### ISSUE THREAD

**Issue by Mendez69** [IIC2233/syllabus#907]
Holaa quería saber si pueden dar alguna idea de como implementar un evento de teclas simultaneas o en secuencia, ya que el los contenidos solo aparece keyPressEvent para 1 tecla y no he encontrado nada en internet. Gracias

**Comment by lily416** [comment]
Hola @Mendez69, 

En la página 12 de la [Tarea 2 del 2019-2](https://github.com/IIC2233/syllabus-2019-2/blob/master/Tareas/T02/Enunciado.pdf), puedes encontrar un _tip_ de cómo implementar las teclas simultaneas. En el caso de las teclas en secuencia, hay que adaptar un poco la idea, ya que lo _sets_ no mantienen el orden en que se agregan los elementos.

Saludos y éxito en la tarea 👋🥞

**Comment by Mendez69** [comment]
gracias!!
