### ISSUE TITLE
Cantidad de pinguirines en la pista de baile

### ISSUE THREAD

**Issue by ignaciomansuy** [IIC2233/syllabus#907]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola! Me parece que en el enunciado no se especifica cual es la máxima cantidad de pinguirines que puede haber en la pista de baile. ¿Puedo definir que la cantidad máxima sea de, por ejemplo, 6 pinguirines? (especificando esto en mi readme obviamente)

Saludos! :)

**Comment by jaimecoloma** [comment]
Hola! Si bien no se especifica, uno debería poder poner hasta que hayan colisiones entre los espacios válidos en vez de settear un maximo.

**Comment by ignaciomansuy** [comment]
Claro, con un máximo me refería a un máximo de espacios. Hasta el momento tengo 6 espacios posibles donde colocarlos, está bien?

**Comment by jaimecoloma** [comment]
Si, por si acaso menciona esto en tu readme y etiqueta esta issue, pero la idea la cumples, si no se pueden poner por espacio y no debido a un parametro o limite debe estar bien!
