### ISSUE TITLE
Pedidos Clientes y Cocinar Chef

### ISSUE THREAD

**Issue by felipefuentesporras** [IIC2233/syllabus#908]
Tengo una duda con respecto a los pedidos de un cliente, que el enunciado se dice que la única colisión especial con el cliente es cuando se le entrega  un plato. Por tanto como manejo los pedidos? Esto significaría que yo puedo hacer que un chef cocine un plato sin importar que haya o no algún cliente en alguna mesa?

**Comment by jitorcas** [comment]
Hola @felipefuentesporras!

Efectivamente si tu modelación es así, podría el chef preparar un plato a pesar de que no haya un cliente, sin embargo debes considerar la situación descrita en esta issue. https://github.com/IIC2233/syllabus/issues/742#issuecomment-631135734

Por otro lado, para simplificar la tarea no se les pidió que implementaran la **"toma del pedido"** ya que únicamente se trabaja con un tipo de bocadillo, es por ello que el chef solo debe llevar los pedidos a los clientes y los clientes a penas aparecen comienzan a esperar su pedido. 

Éxito! 💯

**Comment by felipefuentesporras** [comment]
Ya muchas gracias!!

**Comment by felipefuentesporras** [comment]
También me surgió la siguiente duda, si es que mi mesero tiene un plato y colisiona con un chef que no esta cocinando, ¿ este debería cocinar igual?

**Comment by jitorcas** [comment]
@felipefuentesporras las colisiones especiales son independiente del estado en que está el mesero. Por lo que si el chef está disponible, debería comenzar a preparar un bocadillo. 

Recuerda mencionar todos estos casos en el **README** y citar la issue.

**Comment by felipefuentesporras** [comment]
Perfect!!
