### ISSUE TITLE
Duda sobre cómo subir mis propias imágenes

### ISSUE THREAD

**Issue by En-clases** [IIC2233/syllabus#908]
### Prerrequisitos

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, para la tarea he utilizado varias imágenes que no están incluidas dentro de la carpeta ```sprites``` que nos dieron. **Dichas imágenes deben estar dentro de una carpeta que a la vez debe estar dentro de la carpeta ```sprites``` o me equivoco?** Si es así, cómo las subo? esto ya que se supone que la carpeta ```sprites``` debe ser ignorada y por lo tanto las nuevas imágenes que coloque ahí también serán ignoradas.

**Comment by jaimecoloma** [comment]
Hola!! Tus sprites es mejor que las subas en una carpeta de nombre ```sprites_personalizadas```o algo por el estilo y esta carpeta la subes. Además para evitar confunsiones debes especificar en tu readme donde correr tu código con esa carpeta, para que se puedan visualizar tus sprites correctamente respetando los paths relativos. Espero haya quedado claro, si no puedes preguntarme de nuevo!

**Comment by En-clases** [comment]
Yaa gracias!!
