### ISSUE TITLE
Platos preparados por un chefs y platos fallidos

### ISSUE THREAD

**Issue by felipefuentesporras** [IIC2233/syllabus#909]
Cuando un chef termina un plato, ¿Cuenta como plato preparado a pesar de que por ejemplo no se le entregue nunca al cliente? ¿Y si un chef falla al preparar un plato, se debe seguir contando a platos preparados por el chef? También en caso de fallar haciendo el plato, ¿como se debería notificar al jugador?, ¿basta con que vuelva a estar disponible el chef y no muestre el plato listo?

**Comment by jitorcas** [comment]
Hola @felipefuentesporras!

Primero, si el chef **termina** el plato se considera en la **cantidad de platos preparados** por el chef, independiente si alcanza o no a dejárselo al cliente. 
Segundo, tal como dice el enunciado, si el chef falla un plato, la comida se perderá por lo que no debería contar en **cantidad de platos preparados** 
Tercero, en el enunciado no se especifica cómo se debe notificar, sin embargo hay distintas *sprites* asociadas al proceso en que está el chef, por lo que debería ser sencillo de ver cuando el chef falla y no entrega un bocadillo. 
Recuerda que cada detalle implementado bajo tu criterio y que no afecte el flujo del juego **debes** especificarlo en el **README**, también cómo resolviste los casos bordes.
