### ISSUE TITLE
Error de señales

### ISSUE THREAD

**Issue by YehudaGurovich** [IIC2233/syllabus#909]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

En mi tarea hasta ahora me funcionan bien las señales y he podido separar bien frontend y backend pero no logro entender por qué hay una señal, la de que trabaja el ranking que no me conecta bien a pesar de que he seguido el mismo procedimiento para hacerla que las otras señales. La señal no conecta dado que puse prints en las funciones  *abrir_ranking* y *editar_ranking* que pertenecen a *logica_ventanas.py* y *ranking_window.py* respectivamente. Mi tarea se corre en **main.py** y también se conectan las señales. (Ya hice push).
Gracias por la ayuda!

**Comment by JadrinaDA** [comment]
Hola! Tu problema es que no estás llamando a la función buscar_ranking para empezar la cadena de señales. Sabes que puedes conectar más de una función a una señal 🤩 ? Te recomiendo que conectes buscar_ranking a tu señal senal_abrir_ranking_window para asegurarte de obtener los puntajes después de que hayas hecho las conexiones entre el front-end y back-end (lo que causa que no funcione llamar a buscar_ranking del init). Además te aviso al tiro que tus self.pi (puntajes) son QWidgets y no puedes settearle texto por lo que tendrás que crear QLabels dentro de estos widgets para luego hacer setText a estos. Buena suerte y éxito!
