### ISSUE TITLE
entrega atrasada

### ISSUE THREAD

**Issue by Agustinuc** [IIC2233/Syllabus#91]
holaa, es que no se si se entrego bien mi commit. como puedo ver que commit sera revisado??
tengo mala señal y no se alcanzo a hacer el git push

**Comment by Agustinuc** [comment]
<img width="571" alt="Captura de pantalla 2021-09-03 a la(s) 20 27 38" src="https://user-images.githubusercontent.com/89665265/132076683-37503f15-3757-4e14-a603-865413412431.png">

**Comment by Agustinuc** [comment]
como se puede ver el primer commit final fue antes de las 8. entonces no contaria como atraso?
gracias

**Comment by gatochico** [comment]
¡Hola @Agustinuc!

Primero que todo, para verificar qué se revisara al ser recolectada tu tarea, debes ir a la Issue "T0" que se creó en tu repositorio y hacer click en el commit que indica esta. Luego, en la página donde te lleva ese link, haces click en "Browse Files" y podrás ver cuál fue el estado del repositorio al momento de recolección.

Respecto a tu imagen adicional, lo que marca allí es la hora del **commit** es decir, la hora en que hiciste `git commit` de ese conjunto de cambios. Esto es diferente a la hora que tomamos, que es la hora del **push**, es decir, la hora en que hiciste `git push` de ese commit. Esto lo hacemos ya que la hora del commit y push pueden ser distintas, por ejemplo si haces git commit de algo y luego push horas después. 

Por ende, la forma definitiva de saber si tu commit estuvo dentro del plazo es viendo la issue creada

Saludos!

**Comment by Agustinuc** [comment]
hola, pero si rellene el formulario y mande el hash del commit a corregir, ese seria el commit que me van a corregir o no? 
es que ando complicado con eso ya que el commit que me aparece en git es uno muy antiguo con tan solo el menu de inicio.
porfavor contestar 
disculpe las molestias

**Comment by gatochico** [comment]
Sí, si llenas el formulario de entrega atrasada usaremos el commit que pusiste ahí para revisar tu tarea, aplicando el descuento correspondiente dependiendo de qué tan atrasado estuvo.
