### ISSUE TITLE
Archivo usuario

### ISSUE THREAD

**Issue by Mardones567** [IIC2233/Syllabus#91]
Solo debe haber un archivo con el nombre de usuario y ahí va toda la información, como tablero, puntaje, etc?

**Comment by Emiliax16** [comment]
Hola @Mardones567 . Deben haber dos archivos. Uno llamado `puntajes.txt` donde se guarde el puntaje final al haber finalizado una partida y otro conjunto de archivos (dentro de una carpeta partidas) que tengan el siguiente formato: `nombre_usuario.txt`. Este último archivo se crea cada vez que un usuario desea guardar la partida que ha comenzado. Por lo tanto, ahí va toda la información que consideres fundamental para volver a recrear la partida desde ese punto, como el estado de tablero, puntaje hasta ese momento, etc. Saludos :smile:

**Comment by Mardones567** [comment]
En el archivo puntaje debe estar todos los puntales o solo los 10 mejores?.

**Comment by Emiliax16** [comment]
Se deben guardar todos los puntajes, pero al visualizar el ranking se deben mostrar sólo los 1 mejores que estén en el archivo`puntajes.txt`. Saludos!
