### ISSUE TITLE
properties en clases abstractas

### ISSUE THREAD

**Issue by joaquineichholz** [IIC2233/Syllabus#91]
Hola! ¿se puede usar una propertie en una clase abstracta para que todos sus descendientes la hereden?

Lo estoy intentando pero no me funciona bien, en mi clase abstracta, tengo un atributo secreto  (self.__atributo) y las propertie getter y setter para este, pero al tratar de setear la properti me aparece el siguiente error: "AttributeError: can't set attribute".  La única forma en que me funciona intentando heredar de la clase madre es dejar el atributo sin doble guion bajo y poner el getter y el setter en la subclase. Por otro lado, si dejo el atributo y las properties en la subclase funciona correctamente.

Me parece muy raro y no se porque no funciona correctamente :(

**Comment by fgbruna** [comment]
```python
from abc import ABCMeta, abstractmethod, abstractstaticmethod

class Madre(metaclass=ABCMeta):
    
    def __init__(self):
        self.__privado = 0
    
    @abstractmethod
    def abstracto(self):
        print('''Soy abstracto asi que mis 
                 subclases deben implementarme''')
    
    @property
    def privado(self):
        return self.__privado
    
    @privado.setter
    def privado(self, value):
        print('Modificando privado')
        self.__privado = value

class Hija(Madre):

    def __init__(self):
        super().__init__()
    
    @staticmethod
    def abstracto():
        print('Soy un metodo estatico :P')

def main():
    a = Hija()
    a.abstracto()
    a.privado += 1
    a.abstracto()

if __name__ == '__main__':
    main()

    
 ```
Te refieres a esto ?

**Comment by contranton** [comment]
Si no me equivoco, en Python 3.6 puedes usar los decoradores @abstractmethod y @property encadenados de la siguiente forma: 
```
from abc import ABC, abstractmethod

class Abstracta(ABC):
    
    @abstractmethod
    @property
    def una_propiedad_abstracta(self):
        print("Implementa mi getter!")

    @abstractmethod
    @una_propiedad_abstracta.setter
    def una_propiedad_abstracta(self):
        print("Implementa mi setter!")
```

El módulo `abc` además posee el decorador `@abstractproperty` pero según la documentación este está deprecado en versiones recientes de Python.
