### ISSUE TITLE
Duda sobre commit a revisar 

### ISSUE THREAD

**Issue by burgosibarra** [IIC2233/syllabus#91]
Mientras realizaba mi tarea hacia subidas parciales de mi código, y en la última instancia actualicé 3 archivos de mi código
Cuando me llega la issue sobre cuál commit van a revisar me aparece un código, el cual seleccione y me lleva a una página que indica los cambios que he realizado (que corresponderían a estos archivos)
Mi pregunta es si se me revisara todos mis archivos de código (los cuales son necesarios para ejecutar el juego) o solo los que modifique al último

**Comment by entamburini** [comment]
¡Hola!

Se te revisará todo el código que hayas subido hasta ese punto (incluyendo los de commits anteriores), si quieres estar más seguro, puedes apretar el botón que dice "Browse Files" y verás qué archivos existen :)

![image](https://user-images.githubusercontent.com/20786198/63219979-3a38ff80-c14c-11e9-8f12-a8c6045642a0.png)

Saludos :v:

**Comment by burgosibarra** [comment]
Gracias!!
