### ISSUE TITLE
astah, diagrama de clases

### ISSUE THREAD

**Issue by mjgutierrez1** [IIC2233/Syllabus#91]
¿Alguien sabe como pasar un diagrama de clases hecho en Astah a un formato que sirva para la entrega (por ejemplo una imagen)?

**Comment by mjgutierrez1** [comment]
Se le puede sacar un pantallazo, pero igual me interesa saberlo para mi uso personal del programa

**Comment by sebacruzd** [comment]
Hola, te recuerdo que las [reglas del foro](https://github.com/IIC2233/Syllabus/issues/26) indican que debes googlear antes de crear un issue. La respuesta sí está en google por lo que busqué, espero que la puedas encontrar ahí :smile: 

![imagen](https://user-images.githubusercontent.com/14894992/29440427-1dbee306-839b-11e7-9375-8c5a6ec1edd5.png)

Saludos!
