### ISSUE TITLE
Duda con atributos mínimos para clase Jugador y Bebestibles

### ISSUE THREAD

**Issue by TTrincado** [IIC2233/Syllabus#91]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Para las clases Jugador y bebestibles hay un atributo que de manera en la que quiero implementar no necesito un atributo de los que salen en el enunciado para ambas clases. ¿Es totalmente obligatorio implementar todos los atributos del enunciado? Porque  me acomodaría mucho obviar este par de atributos.

**Comment by Gsalinas1506** [comment]
Hola!
**SI** Debes implementar todos los atributos del enunciado aunque creas que es innecesario. No se a cual atributo en específico te refieres para el aso del Jugador, pero recuerda que hay una parte del programa en el que se deben mostrar todas las características del Jugador, por lo que te recomiendo fuertemente incluirlo de todos modos. Lo mismo para los Bebestibles, piensa que al beberse este afecta las características del jugador.

Espero haberte ayudado.
Éxito con la Tarea! 🎲️🃏️
