### ISSUE TITLE
Definición de función verificar_alcance de la clase PiezaExplosiva

### ISSUE THREAD

**Issue by sbarriag** [IIC2233/Syllabus#91]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola, quería preguntar por la función **verificar_alcance** de la clase **PiezaExplosiva**, para saber si esta retorna True o False solo debo preocuparme que la pieza posea esos movimientos hacia la posición objetivo? Es decir por ejemplo para una pieza del tipo **Vertical** me piden ver si es que puede alcanzar una posición que esté en la misma columna siempre retornará True? independiente si por el numero que acompaña la pieza, es decir su alcance, no puede llegar a ella?  

Muchas gracias

**Comment by Dominique236** [comment]
Hola!
Es correcto lo que dices, el número que acompaña a la pieza no es relevante para este método. Como menciona el ejemplo del enunciado, según el tipo de la pieza, solo hace falta ver si la posición entregada al método comparte columna, fila y/o diagonal, según corresponda, para poder retornar True o False.
Cuéntame si esto resuelve tu duda 😊

**Comment by sbarriag** [comment]
Me quedó claro, muchas gracias
