### ISSUE TITLE
eliminar prograposts iguales

### ISSUE THREAD

**Issue by BenjaLeyton** [IIC2233/syllabus#91]
hola, si publico dos prograposts iguales en distintos dias, y quiero eliminar ese prograposts, elimino los dos, o tengo que especificar la fecha del que quiero eliminar y solo borrar uno?.
Lo otro, tambien en el caso de que tenga dos igules publicados el mismo dia, elimino uno o los dos?

**Comment by DCCollao** [comment]
Hola! Te recomiendo revisar #17. Si aún así te quedan dudas, quedo atento!
