### ISSUE TITLE
Se pueden ocupar exceptions

### ISSUE THREAD

**Issue by afcarvallo** [IIC2233/Syllabus#91]
Se pueden ocupar exceptions en caso que tire error? 
try , except

**Comment by Hernan4444** [comment]
Si tu programa tira error significa que no está correctamente implementado y eso será considerado al momento de evaluar tu tarea. De todos modos puedes utilizar excepciones mientras que su uso esté correctamente justificada y se indique el error a la cual le estas haciendo la excepción. Ya está subido el material de excepciones así que te puedes documentar sobre a que nos referimos con indicar el error. Ten en cuenta que un mal uso de estas podría perjudicar en el puntaje de modelación.

Saludos!!

**Comment by aSPCA** [comment]
Hernan cuales son casos en que podria estar mal implementados?

**Comment by Hernan4444** [comment]
Para empezar es cuando no se especifica el error, es decir poner:
```
try:
  ...
except:
  ...
```

Una buena implementación haría:
```
try:
  ...
except: ValueError
  ...
except IndexError:
  ...
```

Y otra mala implementación es cuando se abusa de este para evitar usar IF/ELSE. Las excepciones son principalmente para el manejo de situaciones que son mas complicadas de manejar con solo if y else, como por ejemplo los input de un usuario.

Saludos!!!!
