### ISSUE TITLE
Duda con las coordenadas recibidas para verificar_alcance_bomba()

### ISSUE THREAD

**Issue by golosinas** [IIC2233/Syllabus#91]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/21)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/20)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Las coordenadas para esta función serán--o pueden ser--recibidas como un input? Aunque no creo que haya otra forma de recibir unas coordenadas cualquieras, pregunto para estar segura. En caso de que sí, se podría indicar un formato para el input? Por ejemplo: "Ingrese unas coordenadas de la forma ..."

EDIT: La pregunta surge porque asumí que se estaría revisando una bomba a la vez. ¿Esta función tiene que asegurarse de que _todas_ las bombas tengan el alcance correspondiente?

**Comment by Hernan4444** [comment]
Hola, @golosinas 

La coordenada no se pide por input, esta llega como segundo argumento de la función. Por otro lado, esta función solo verifica **una bomba** que es la indicada en la coordenada. La idea es que tu determines donde es apropiado utilizar esta función dentro de tu código.

Saludos!
