### ISSUE TITLE
Definición de atributos en Clases

### ISSUE THREAD

**Issue by fernandolalanne** [IIC2233/syllabus#91]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

[Describe tu duda de manera detallada, explicando los contenidos en cuestión y ojalá colocando código o un caso de uso de ejemplo]
Hola!! Quería preguntar si es posible que me expliquen por qué existen casos en los cuales no se definen todos los atributos en el __init__ cuando se crean clases. Por ejemplo:

class Televisor:
    ''' Clase que modela un televisor.
    '''
    
    def __init__(self, pulgadas, marca):
        self.pulgadas = pulgadas
        self.marca = marca
        self.encendido = False
        self.canal_actual = 0
        self._clave = "tv123"

En el código anterior dentro del __init__ se definen los atributos "pulgadas" y "marca" sin embargo, cuando definen los atributos mas abajo aparecen conceptos como encendido, canal_actual o cave, conceptos que no están definidos en la función. ¿En qué casos es posible hacer esto?

Desde ya muchas gracias!

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by ajuanchuto** [comment]
¡Hola!

Voy a explicarte con tu mismo ejemplo. Entonces tenemos la clase `Televisor`, que recibe la `marca` y las `pulgadas` al momento de crear una instancia `Televisor` de la siguiente forma:
```
1. class Televisor:
2. 
3. def __init__(self, pulgadas, marca):
4.     self.pulgadas = pulgadas
5.     self.marca = marca
6.     self.encendido = False
7.     self.canal_actual = 0
8.     self._clave = "tv123"
9.     
10. #Aquí llamas una instancia de Televisor de 32 pulgadas y marca LG
11. televisor_nuevo = Televisor(32, "LG")
```
Lo importante aquí es que al momento de instanciar un objeto de la clase `Televisor`, tu tienes que pasarle si o si los valores de sus `pulgadas` y la `marca`, sin eso no pueden crear tu `televisor_nuevo`. Sin embargo el televisor tiene otros atributos importantes, como por ejemplo, una clave general de fábrica que es igual para cualquier televisor que quieras crear. 

Esto mismo ocurre con el `canal_actual` ya que todos los televisores comienzan en el canal 0, pero no es lógico que tu al crear una instancia de un televisor escribas todo el tiempo que el `canal_actual` al inicio va a ser 0. Y finalmente pasa lo mismo con el atributo `encendido`.

**A modo de resumen:** No todos los atributos se tienen que pedir al momento de crear una instancia de un objeto ya que hay cosas que vienen por _"default"_ dentro de la misma clase. Por lo tanto, los atributos que están pedidos en la `línea 3` son aquellos que tu al momento de crear la instancia tienes que **especificar obligatoriamente**. Mientras que los atributos que están en las `líneas 6`, `7` y `8` ya vienen con un valor por _"default"_ cada vez que crees una instancia Televisor, por lo que no es necesario ponerlos en la `línea 3`.

Ojalá te haya quedado más claro, mucha suerte con el estudio! 😄
