### ISSUE TITLE
Mala practica transformar archivos .ui a .py

### ISSUE THREAD

**Issue by Ignacioislae** [IIC2233/syllabus#910]
Hola,
¿Es mala practica pasar los archivos .ui a .py con el comando: pyuic5 -x arch.ui -o arch-py? En lo personal me gusta mas transformar el archivo a .py porque así puedo después modificarlo y ademas puedo saber que Widgets y señales poseo sin tener que revisar el Qt Designer, tal vez tendré mas lineas de código, pero también tendré mas claridad en lo que estoy haciendo.

Se que hay otra issue que habla de este tema, pero no especifica si es mala practica o no, solo que no lo recomiendan.

Saludos!

**Comment by danckoo1** [comment]
Hola! para los efectos de la tarea no será considerado como una mala practica, por lo que eres libre de utilizarlo, sin embargo, en otros ámbitos desconozco si será calificado como mala practica. 
Eso si asegúrate de que todo siga funcionando correctamente para que no te cause errores mas adelante :)
(Por si alguien quisiera saber porque no se recomienda, pueden leer las issues #727 y #697 )

**Comment by Ignacioislae** [comment]
Dalee Gracias!
