### ISSUE TITLE
Como puedo volver a una versión antigua de mi programa en Git

### ISSUE THREAD

**Issue by fhola23** [IIC2233/syllabus#910]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola, tratando de agregarle una funcionalidad a mi tarea ya no corre. Quería saber si existe algún comando especial de git que me permita volver a tener mi tarea como mi ultimo push. Traté con un git restore que vi en otro issue pero logré que funcionara.

Muchas gracias de antemano

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by kadroguett** [comment]
Hola @fhola23, para volver a un `commit` anterior debes primero hacer:
`git log` 
De esta forma puedes obtener el ID del commit al que quieres volver. Luego debes hacer:
 `git reset --hard <ID del commit>`
Ojo que esto eliminará los commits posteriores.

**Comment by fhola23** [comment]
Muchísimas gracias!
