### ISSUE TITLE
Problemas con rect().getRect()

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#911]
Hola!
Resulta que una vez creado el QLabel de una sprite, dándole una coordenada x e y, además del largo y ancho, luego quiero saber si la coordenada (x, y, ancho, largo) queda guardada, pero no sucede.
Lo que hago es:
```
x = 100
y = 200
sprite = QLabel(self)
sprite.setGeometry(QtCore.QRect(x, y, 30, 40))
print(sprite.rect().getRect())
sprite.setPixmap(QPixmap(ruta_sprite).scaled(30, 40))
```
El print que retorna es (0, 0, 30, 40) y debería ser (100, 200, 30, 40) (creo yo).
En qué estaré fallando ?

**Comment by danckoo1** [comment]
Hola! tu problema es basicamente que el label y su repectivo rect se mueven de forma independiente. El tema ya fue comentado en la issue #798 , si no logra responder tu duda me avisas!
