### ISSUE TITLE
pyqtSignal y errores de codificacion

### ISSUE THREAD

**Issue by gaspcr** [IIC2233/syllabus#912]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, tengo un problema a la hora de emitir señales con pyqtSignal(), la cuestión es que al emitir una señal con un str -pyqtSignal(str)- me tira este error: **UnicodeEncodeError: 'ascii' codec can't encode character '\xf1' in position 9: ordinal not in range(128)**, busqué en internet y decía algo de que no debía convertir a texto utilizando str(), o algo así entendí. ¿Alguien sabe como solucionarlo o si tengo configurado algo mal en mi vsc?

**Comment by danckoo1** [comment]
Hola, de casualidad el nombre que le pusiste a la variable de la señal tiene una ñ? De ser así trata cambiándolo por una n y avísame si lo soluciona :)

**Comment by gaspcr** [comment]
jajaja soy idiota, puse señal en vez de senal xD, ty!
