### ISSUE TITLE
Desproporción tamaño Qt Designer v/s correr programa

### ISSUE THREAD

**Issue by jamigone** [IIC2233/syllabus#912]
Hola! En la imagen se visualiza la desproporción entre tamaño de la preview de mi ventana en Qt Designer (fondo) y el tamaño real al correr mi programa. Viendo los contenidos y, en particular, la ayudantía 08 noto que el tamaño de la preview debería ser el "correcto" (en ambos casos siempre se me vio + chico).

¿Hay alguna forma de solucionar esto?
Si bien podría hacer una ventana + grande en el Qt designer para que el tamaño real no se vea tan chico, espero que esa sea la última opción jaja. Si hago eso, incluso podría ser un problema para el/la ayudante, ya que probablemente se vería una ventana excesivamente grande.

Subí a mi repositorio de la T02 mi avance por si quieren verlo, si corren el archivo Ventana_inicio.py y lo comparan con VentanaInicio.ui pueden verificar si les ocurre el mismo problema. Dado los ejemplos de los contenidos y el video de la AY08, mi hipótesis es que solo me pasa a mí jajajaj

pd: tuve la duda si podía subir la imagen por alguna copia, pero asumí que sí podía porque esta es casi idéntica al ejemplo del enunciado (de hecho es más fea jajaja)

![imagen](https://user-images.githubusercontent.com/50121013/83475525-8267ab00-a45c-11ea-906b-973ce5475b64.png)

**Comment by jamigone** [comment]
Acabo de revisar la issue #718 y veo que no soy el único. Procederé a agrandar la ventana del Qt Designer para que se vea bien en el VSCode, pero me quedo con dos dudas:
1. ¿Existe alguna forma de trabajar con una ventana no tan grande el Qt designer y que represente el tamaño que quiero en el programa?.
2. Asumo que la respuesta es sí a la pregunta anterior, ya que el ayudante que realizó el video del Front-end en la AY08 le resulta: tamaño aparentemente similar en los minutos 2:40 [Ventana Qt] y 6:40 [Ventana programa]. No noté ningún código para que lo lograra, quizás es alguna configuración predeterminada, ¿cómo se haría?

**Comment by tomasgv** [comment]
Hola @jamigone !!

Si ya intentaste lo cambiar las _Size Constraints_ y aún se ve un tamaño diferente, entonces es posible que lo que esté distinto sea el _zoom_ de previsualización 🤔 . 

Esta configuración se encuentra en _Preferences_ > _Form_ (en Mac). Puede que el camino en Windows sea distinto, pero debería verse parecido a esto:
![Captura de Pantalla 2020-06-02 a la(s) 11 34 50](https://user-images.githubusercontent.com/48303402/83539602-3bfa6680-a4c5-11ea-8b33-80f7c7d1b6db.png)

En caso de que esté en 100% y se siga viendo más grande de lo esperado, puedes cambiarlo para modificar su tamaño más cómodamente. En ese caso tal vez _QtDesigner_ esté teniendo errores adaptándose a la resolución de tu pantalla 😯 

Espero que esto te haya sido de ayuda! ☕

**Comment by jamigone** [comment]
Sii @tomasgv !! Era debido a la resolución de la pantalla. Le bajé la resolución y ahora se ve de un tamaño normal. Gracias :)

**Comment by rkarac** [comment]
Holaa!! me pasa lo mismo pero no entendí como lo arreglaste, no se si podrías especificar.

**Comment by tomasgv** [comment]
Hola @rkarac!

Parece ser que lo que le funcionó a @jamigone fue bajar la resolución de su pantalla 🤔 

[Aquí](https://support.apple.com/es-us/guide/mac-help/mchl86d72b76/mac#:~:text=Set%20the%20resolution%20for%20a%20connected%20display&text=display%20is%20connected.-,On%20your%20Mac%2C%20choose%20Apple%20menu%20%3E%20System%20Preferences%2C,click%20Displays%2C%20then%20click%20Display.&text=Press%20and%20hold%20the%20Option,option%20for%20the%20second%20display.) hay un link que explica como hacerlo desde Mac, [aquí](https://www.laptopmag.com/articles/change-screen-resolution-in-windows-10) desde Windows, y [aquí](https://help.ubuntu.com/stable/ubuntu-help/look-resolution.html.en) desde Ubuntu. 

Avísame si te funciona c: 

¡Éxito con la tarea y el fin de semestre! 🃏
