### ISSUE TITLE
Colisiones especiales

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#913]
Hola.
Tengo implementadas las "colisiones", pero aún me quedan por implementar el tema de las "colisiones especiales". Mi problema es que, las "colisiones" funcionan correctamente, ósea, el mesero no atraviesa ni el mesón del chef, ni las mesas. Pero ahora necesito saber cuándo el mesero está "colisionando" con los clientes y el chef. Para esto quise probar el método  ```intersects``` , haciendo ```label_jugador.geometry().intersects.(label_objeto.geometry())```, y esto es True solo cuando (x, y, largo, ancho) son iguales. Pero esto nunca va a suceder, ya que como dije anteriormente la parte de "colisiones" (según lo que se pide en el enunciado) está implementada de tal forma que ninguna sprite esté en la misma coordenada. 
Entonces mis preguntas son las siguientes:
1- La "colisión" entre un label_1 y label_2 es cuando éstas tienen las mismas coordenadas "(x, y)"?. Si esto es así. Cómo podría identificar a través del método ```intersects``` que ambos labels se encuentran en la misma coordenada?. Esto ```label_jugador.geometry().intersects.(label_objeto.geometry())``` no me funciona, ya que el "largo" y "ancho" de los labels son distintos.
2- En la parte de "colisiones" yo no implementé el método ```intersects```, ya que lamentablemente no ví antes esto en el enunciado. Entonces yo implementé esto de tal manera que el mesero nunca se "apega" a un chef o mesa, ósea, que ninguna de sus coordenadas tocan otra sprite (no se superpone ningún pixel), lo cual no sé si está bien. Y ahora que quiero hacer la parte de "colisiones especiales" me dí cuenta que con ```intersects``` era mas sencillo. Pero mi problema está en que al avanzar con el mesero, nunca va a "colisionar" con algún chef o mesa, y éste es mi problema. Qué debo hacer?

**Comment by tomasgv** [comment]
Hola @Camila-sty !! 

1. A modo de afinar un poco más tu definición de `intersects()`: este método retorna `True` si existe al menos un pixel contenido en ambos `QRect`s. Esto hace posible comparar la intersección entre entidades `QRect` de distintos tamaños. Puedes consultar más sobre esto en la documentación de [_Qt_](https://doc.qt.io/qt-5/qrect.html#intersects) (C++) o en la de [_PySide2_](https://doc.qt.io/qtforpython/PySide2/QtCore/QRect.html#PySide2.QtCore.PySide2.QtCore.QRect.intersects) (muy similar a PyQt5).
2. ¡No te preocupes! Usar `intersects()` es una de muchas maneras posibles de implementar colisiones. No te puedo decir directamente que lo hagas de cierta manera, pero si lograste implementar colisiones normales, te quedaría entregar una manera de diferenciar a las entidades con las que el personaje colisiona. El hecho de que las entidades no se toquen nunca sí cuenta como colisión mientras se evite avanzar en una dirección inválida :+1:

Saludos! ☕  🐱

**Comment by Camila-sty** [comment]
Ok, pero entonces el método ```intersects()``` no me serviría para saber si existe una colisión del mesero con algún objeto, ya que no existe nunca un pixel en común ..¿?

**Comment by tomasgv** [comment]
Es probable que si usas `intersects()` del modo en que enunciaste anteriormente no funcione como esperes. Sin embargo, puedes usar este método con dos `QRect` cualesquiera, como por ejemplo, uno que esté corrido en X pixeles en la dirección de avance del personaje.
