### ISSUE TITLE
Error con método stop() QSound

### ISSUE THREAD

**Issue by Margarita-Paz** [IIC2233/syllabus#913]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! estoy utilizando QSound para reproducir las canciones, pero al momento de querer utilizar el método stop(), me lanza error **first argument of unbound method must have type 'QSound'**. He intentado escribirlo de muchas formas y también he buscado ejemplos en internet, pero no le he podido dar al clavo

**Comment by bvasquezm** [comment]
Hola @Margarita-Paz,

Creo que tu error podría deberse a que estás haciendo un llamado del método stop a través de la **clase** y no una **instancia** del objeto QSound. Es decir, debes llamar el método primero habiendo creado y asignado el objeto a alguna variable, atributo, etc.  Señala el mismo error _...unbound method must have type ‘QSound’_, es decir, el método no está atado a ninguna instancia del tipo QSound. Aprovechando, te recomiendo que revises la issue #777 si tienes dudas sobre el método stop(). Saludos!
