### ISSUE TITLE
Eliminar mesas y chef

### ISSUE THREAD

**Issue by r-moya-valenzuela** [IIC2233/syllabus#914]
Hola, en la pre-ronda se pueden eliminar las mesas, pero que pasa con los chefs ? O una vez creados ya no se pueden eliminar?

**Comment by kadroguett** [comment]
Hola @r-moya-valenzuela 
En la sección 5.2 del enunciado dice que tanto las mesas como los mesones se pueden eliminar al hacer click sobre ellos.
