### ISSUE TITLE
Mi ventana principal detecta mal las flechas

### ISSUE THREAD

**Issue by Gsalinas1506** [IIC2233/syllabus#914]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Tengo un problema con mi Tarea 2, específicamente en como la `Ventana Principal` detecta o no la presencia de flechas.
Mi ventana principal tiene la siguiente estructura:

![image](https://user-images.githubusercontent.com/68198662/97518179-864d1a00-1975-11eb-8e73-9d0d275075eb.png)

Mi intención es modelar la zona de ritmo de tal manera que cuando las flechas pasen por los cuadros amarillos, se registre en el programa esta intersección. Para esto, genero un QPixmap de una flecha, la cual es enviada al backend para que se mueva, movimiento que se ve plasmado nuevamente en el frontend. A su vez, los cuadros amarillos de la ventana principal son un QLabel. Mi frontend lo que debería hacer es que, al actualizar la posición de las flechas, se verifique si los QRects de las flechas y de los cuadros amarillos se están intersecando o no.

Para verificar esta intersección, quiero establecer que si **hay intersección**, el cuadro amarillo cambie a color verde, mientras que si no la hay, este retorne a su color amarillo. Sin embargo cuando una flecha está intersectando un cuadro amarillo, este cuadro empieza a titilar entre ambos colores hasta que la flecha termina de pasar, aun cuando siempre debería estar verde (ya que hay una flecha pasando por encima de él). En el video se ve un ejemplo de lo que me ocurre:

link del ejemplo (se ve mejor al ejecutar el código que en el video. _Solo implementado nivel principiante_):
[https://drive.google.com/file/d/1MAXbseDJaxg2doosw7o_NRRzPBr_EgIn/view?usp=sharing](url)

**¿A que se puede deber esta mala detección/detección intermitente?**

pd: el codigo está subido en mi repo

**Comment by knight-who-say-ni** [comment]
Holaa @Gsalinas1506 !! Lo que me tinca que puede estar pasando es que quiza actualizas el color del label cada vez que tiene una flecha intersectandolo, quiza es mejor actualizarlo solo cuando lo intersecta por primera vez y volver al color original cuando la deje de intersectar.

No se si se entiendo, sino cualquier cosa me avisas 😄 . Saludos!!
