### ISSUE TITLE
Problema con método 'connect': No puedo importar 'pyqtSignal'

### ISSUE THREAD

**Issue by nimorales97** [IIC2233/syllabus#915]
Estoy tratando de hacer que al apretar el botón 'Ver ranking' de mi ventana de inicio se abra la ventana correspondiente, para experimentar copié un código de los contenidos y lo adapté muy poco:
```
window_name, base_class = uic.loadUiType("ventana_inicio.ui")
class VentanaInicio(window_name, base_class):
    senal_ranking = pyqtSignal()
    def __init__(self):
        ...
        self.senal_ranking = None
        self.senal_ranking.connect(self.show)
```
Mi problema es que al llegar a la línea `self.senal_ranking.connect(self.show)`  me salta el siguiente error: `None type has no atribute 'connect'` también noté que en la línea `from PyQt5.QtCore import pyqtSignal` me aparece el subrayado rojo y el mensaje `No name 'pyqtSignal' in module 'PyQt5.QtCore'`
sin embargo cuando ejecuto el archivo original que copié de contenidos carga todo bien y no da ningún error.
*¿Cómo se arregla?*

**Comment by aaossa** [comment]
Hola @nimorales97 , en tu código de ejemplo tienes una línea `self.senal_ranking = None` que quita la referencia a la señal, por lo que luego no podrás utilizar ningún método relacionado porque ahora tienes un `None` en ese atributo. Debería funcionar bien si quitas esa línea. Sobre el subrayado en rojo, no es un error, sino que un mensaje de tu editor. Asumiré que estás en VSCode, así que te recomiendo ver esta *issue*: https://github.com/IIC2233/syllabus/issues/664. Avísame si te funciona o sigue sin funcionar tu duda con las señales 👌 ¡Éxito con la tarea!

**Comment by nimorales97** [comment]
Me funcionó! No entendí en qué consistía el mensaje pero corregí unos errores que tenía y ahora funciona todo bien. Muchas gracias!
