### ISSUE TITLE
Distinguir click en label

### ISSUE THREAD

**Issue by Mario-uc** [IIC2233/syllabus#916]
La función moussepressevent está asociado al drag, y no sé como hacer que se distinga con el click al querer eliminar el objeto

**Comment by furcelay** [comment]
Ve la documentación de [Drag and Drop](https://doc.qt.io/qt-5/dnd.html), justamente indican como distinguir un drag de un click en `mousePressEvent`.

**Comment by tomasgv** [comment]
Hola @Mario-uc !!

Justamente como dice @furcelay, en el ejemplo de la documentación se hace una diferenciación entre _drag_ y _click_ . Te recomiendo leerlo a fondo para entender lo que se hace en cada caso y cómo se diferencian. 

Es posible que no hayas implementado _Drag and Drop_ de esa manera, sin embargo, siempre existe una diferencia fundamental entre arrastrar una entidad y solo hacer _click_ sobre ella.

Saludos! ☕  🐱
