### ISSUE TITLE
Verificacion paso doble o triple

### ISSUE THREAD

**Issue by totoiii** [IIC2233/syllabus#916]
Tengo entendido que existen pasos que son obligatoriamente dobles o triples, (digo obligatoriamente porque en la issue #796 dicen que pueden existir pasos que tu decides si son triples o dobles debido a las flechas doradas). Estos pasos no se como identificar si es que son estan correctos o no ya que:
-
![image](https://user-images.githubusercontent.com/69605379/97520708-9b787780-197a-11eb-9833-f056f827f30c.png)

Las condiciones son : 
a) Todas las flechas que pertenecen al paso deben ser acertadas.
b) Los carriles que no pertenecen a dicho paso:
    b.1)Si es que no hay ninguna flecha no perteneciente al paso, este no debe estar presionado.
    b.2)Si es que hay alguna flecha no perteneciente al paso, este puede o no estar presionado.

Tengo dudas con respecto a la parte b) **debe ser asi de estricto??**  o puedo alivianar las condiciones

**Comment by aaossa** [comment]
Hola @totoiii , cuando hagas una *issue* por favor no borres el contenido de la plantilla, sino no sabremos si seguiste los pasos recomendados. ¡Gracias 🙌!

**Comment by knight-who-say-ni** [comment]
Holaa @totoiii !!

Efectivamente, la idea es que sea de esa forma, esto es evaluado en la pauta.

Saludos y exito programando!!
