### ISSUE TITLE
Boton Salir Ventana Ronda

### ISSUE THREAD

**Issue by mpmunoz13** [IIC2233/syllabus#917]
Hola, 
No me queda claro que debe hacer este boton. Me lleva a la ventana post ronda? Cumple la misma funcion que "FIN"? o termina el juego?

**Comment by jitorcas** [comment]
Hola! @mpmunoz13 

El botón salir en la **ventana de juego** debe terminar el juego en ese momento. La función de **"F + I + N"** es terminar la ronda y permite seguir jugando. 

Éxito en la tarea! 💯

**Comment by mpmunoz13** [comment]
@jitorcas Al terminar el juego en la ventana de juego se actualizan los archivos? Se guarda el progreso?

**Comment by jitorcas** [comment]
@mpmunoz13 Así es, en el enunciado en la **sección Archivos** piden lo siguiente:

> Estos archivos deber **modificarse** con cada nueva ejecución del programa.

Por lo que al cerrar el juego ya debiesen estar actualizado los archivos.

**Comment by francisca0308** [comment]
Hola! Perdón la insistencia en el punto, pero, si al salir se guarda el progreso en los archivos, cuál es la diferencia entre este botón y el botón guardar? Y el botón continuar de la ventana post-ronda también guarda el progreso?

**Comment by jitorcas** [comment]
Hola @francisca0308!
@dlmed podría ayudar a aclarar un poco :)

Si **no guardas** el progreso del juego con cada nueva ejecución del programa, entonces el botón **guardar** debería modificar los archivos guardando la última partida "N" en donde jugó el usuario, dejándola preparada para eventualmente jugar la partida "N+1".
Si ya implementaste **guardar** siguiendo la regla del enunciado de los *" (...) archivos deben modificarse con cada nueva ejecución del programa."* entonces implementa de todas formas el botón guardar y **cita esta *issue* en tu README** especificando la manera en que lo implementaste.
Cabe destacar que ambas opciones **deberían dejarte en la ronda "N+1"**, por ejemplo, si presiono *guardar* en la ventana post-ronda y luego *salgo* del programa para eventualmente volver a entrar y *seguir jugando*, debería *seguir jugando* en la ronda "N+1" y no en el final de la ronda "N".

**Comment by dlmed** [comment]
@jitorcas, pero si estoy jugando la ronda N (es decir, en mis datos.csv estaba guardado que llevaba N-1 rondas terminadas) y en medio de la partida salgo, al volver a cargar la partida no debería partir denuevo la pre-ronda correspondiente a la ronda N? ya que no se terminó dicha ronda como para partir en la ronda N + 1 y considerarla como ronda terminada, que es lo que se guarda en datos.csv

**Comment by jitorcas** [comment]
@dlmed 

Así es! el botón salir en la ventana del juego es independiente de los otros botones, y si sales en la partida "N" deberías volver a la pre-ronda de la partida "N".

Ahora, lo que especifiqué en la respuesta es en relación a cuando la partida ya está **terminada** y estás en post-ronda.
