### ISSUE TITLE
Problema con multiplicación de ventanas

### ISSUE THREAD

**Issue by fedezang** [IIC2233/syllabus#917]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, mi problema es que cuando ejecuto mi código este actúa como si hubiera multiples pestañas de juego a pesar de haber solamente una. 
Cuando juego 1 ronda se comporta normal, 
luego cuando juego por 2da vez: me aparecen 2 mensajes de alerta (cuando no se puede comenzar) en lugar de 1; se registra 2 veces el puntaje del usuario en vez de 1, aparece la ventana de resumen 2 veces. (como ejemplos)
y así sucesivamente para las n veces que juegue, aparecerán por ejemplo n puntajes del mismo usuario.
No sé cuál podría ser el error, ya que me ocupé de ocultar las ventanas cada vez que se terminan de ocupar.
Será un problema de mi computador o que podría ser?
Gracias de antemano

**Comment by JadrinaDA** [comment]
Hola! Tal vez estás ocultando las ventanas pero esto no significa que estas ya no existen. Mi pregunta es, estás destruyendo los objetos que estás creando al inicializar las ventanas y estás creando nuevas ventanas cada vez que empiezas un juego? Si la respuesta a esta última pregunta es sí te recomiendo que recicles los objetos en vez de crear nuevos. Al terminar un juego simplemente redirige el usuario a la ventana de inicio para poder partir de nuevo. Además acuérdate de terminar todos los threads cuando esto pase.

**Comment by fedezang** [comment]
Hola!, efectivamente estoy reciclando los objetos, los oculto y luego los muestro denuevo cuando es necesario. pero pareciera como que las señales que emite mi ventana de juego las emite n veces cuando juego por la enesima vez.
Cómo podría arreglar eso?

**Comment by fedezang** [comment]
![Captura de Pantalla 2020-10-29 a la(s) 12 41 59](https://user-images.githubusercontent.com/62078222/97597032-26418c80-19e4-11eb-81e9-301bba7c2368.png)
Esto me pasa por ejemplo la 2da vez que quiero jugar, pero hay solamente 1 ventana de juego. Es como si el botón de comenzar funcionara doble. La verdad no entiendo por qué podría pasar y ya revisé mi código por mucho tiempo.

**Comment by JadrinaDA** [comment]
Hola! Revise tu código y tu problema está ocurriendo porque conectas las señales múltiples veces al llamar repetidamente a init_gui. Esto causa que las funciones se ejecuten varias veces también. Te puedo dar dos opciones, conectar todas tus señales una vez en el main o utilizar un bool para comprobar que es la primera vez que estas conectando en init_gui. Yo usé lo segundo y esa misma ventana de error solo me apareció una vez. Buena suerte!

**Comment by fedezang** [comment]
Muchas Gracias! Una pregunta, no entendí muy bien lo del bool para comprobar que ya me conecté, porque en teoría me conecto desde la primera vez que quiero jugar, y después necesito init_gui para "reiniciar" la ventana de juego. Si ya estuviera conectado, no podría ocupar init_gui. Cómo compruebo la nueva conexión y reinicio mi ventana de juego?
Gracias de antemano

**Comment by JadrinaDA** [comment]
Puedes reiniciar la ventana pero te sugiero ponder un if del estilo if self.first == True: senal.connect(funcion). Solo para hacer la conexión misma una vez.

**Comment by fedezang** [comment]
Ya muchas gracias por la ayuda! voy a intentar que funcione
