### ISSUE TITLE
chef y clientes

### ISSUE THREAD

**Issue by simoneaston** [IIC2233/syllabus#918]
Hola, tengo dos dudas:
- si el mesero tiene un plato en la mano y choca con un chef. Este último se pone a cocianar?
(si esque el chef se pone a cocinar, casi nunca veríamos al chef esperando, porque normalmente cuando uno choca con algo, lo hace más de una vez)
- los clientes pagan cuando se van o cuando les doy la comida? (queda más claro y evidente el aumento de dinero si es cuando le doy la comida)

**Comment by Alonsinho1** [comment]
Hola!

- Si el mesero choco con un chef y el mesero tiene un plato, el chef se pondra a cocinar, siempre y cuando este no este cocinando algo actualmente. Lo unico que imposibilita a que este cocine, es que este se encuentre cocinando algo actualente

- El cliente debería irse cuando le das la comida, ya que la comida se la come instantáneamente.


Suerte!
