### ISSUE TITLE
Problema Drag and Drop

### ISSUE THREAD

**Issue by felipehen** [IIC2233/syllabus#919]
leyendo el foro, pude entender mas o menos como hacer un drag and drop. Cree un Label personalizado, sobreescribiendo el metodo MouseMoveEvent() y lo dropeo en mi MainWidget, donde tengo tanto el metodo dragEnterEvent() y dropEvent() sobreescritos, para que SOLO PRINTEEN, un mensaje, para saber si funcionan.

ademas, al alterar el metodo MouseMoveEvent(), del Label, hice que imprimiese las cordenadas del mouse, para saber si funciona o no. 

Al hacer esto, pude notar como me funciona el metodo de MouseMoveEvent, pero nunca se entra al metodo dragEnterEvent().

**Comment by cristozille** [comment]
Hola @felipehen! Modificaste también los métodos mousePressEvent() para que el drag se active al hacer click sobre el objeto? En la issue #916 se vie muestra un ejemplo de como hacer esto.
Cuéntame como te va :)

**Comment by felipehen** [comment]
si habia revisado eso, para comprobarlo, hice que una vez se completara la "distancia minima del drag", me imprimiera "EXITO", en la terminal. Pero incluso cuando esto sucede, aun asi mi codigo no entra al dragEvent

**Comment by cristozille** [comment]
Holaa suena como que el problema es de código. Sube lo que lleves a tu repositorio personal y lo puedo revisar :)

**Comment by felipehen** [comment]
Ya gracias, antes subi los archivos hace un rato, en mi ultimo commit.

**Comment by cristozille** [comment]
Hola, estuve revisando tu codigo y creo que el problema es como lo modularizaste. El dragEnterEvent() y el dropEvent() son atributos de un QLabel, por lo que deberías tener una clase que herede de QLabel (por ejemplo el mapa) y en esta agregar estos métodos. Ahi entonces la clase Juego() tendría el QLabel mapa que recibe los elementos  con dragEnterEvent() y dropEvent().
Por otra parte los objetos que muevas tambien deben ser clases que hereden de QLabel, tal como aparece en el link de la issue #916. Cambiando esas cosas debería funcionar :). Cuentame como te va.

**Comment by felipehen** [comment]
muchas gracias, al final si me faltaba eso, pero al parecer me faltaba una linea en MouseMoveEvent. ahora ya me funciona.

**Comment by cristozille** [comment]
Buenisimo!
