### ISSUE TITLE
Problema con "lag" en las flechas

### ISSUE THREAD

**Issue by ExRage2000** [IIC2233/syllabus#919]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola, tengo un problema con que durante el juego ocasionalmente todas **las flechas se ralentizan** todas al mismo tiempo y luego vuelven  a su velocidad original (como el lag).
El problema originalmente no era mucho, pero se ha ido acentuando con el avance de la tarea, al punto de que ahora pasan mas tiempo ralentizadas de lo que pasan en su velocidad normal.

Aquí hay un ejemplo del problema originalmente y de como esta ahora
![Captura de pantalla (75)_LI](https://user-images.githubusercontent.com/69613733/97512729-07ea7b00-1969-11eb-9b5e-c742dbc8bb20.jpg) ![Captura de pantalla (93)_LI](https://user-images.githubusercontent.com/69613733/97512757-1afd4b00-1969-11eb-83e9-8c947a4a9c87.jpg)
(Aunque no se muestra la velocidad, se puede ver el lag donde las flechas están mas juntas puesto que el timer no se detiene)

No tengo el típico problema del "QThread destroyed while still running" y uso un solo timer generador de flechas (threads) para los cuatro carriles, no se si el problema será eso o tendrá mas que ver con mi implementación de señales.

PD: He revisado otras issues con problemas similares pero ninguna me ha servido, pues en las otras el problema es que las flechas de carriles distintos se mueven a distintas velocidades, el problema principal es un "QThread destroyed while still running", se ha solucionado viendo el código del alumno, o el alumno ha solucionado su propio problema

**Comment by aaossa** [comment]
Hola, en #931 el problema se solucionó con un cambió chico, ¿podrías ver si te funciona?

> (...) creo que lo que ocurre es que tus QThread no tienen el mismo "ciclo de vida" que su parent. En tu caso, para arreglarlo debes asegurarte de pasarle el parent a través del super: super().__init__(parent). (...)

**Comment by eliasbruchfeld** [comment]
Hola! Me pasa exactamente lo mismo pero no me aparece "QThread destroyed while still running". De hecho no me aparece ningún error que me pueda dar una pista.  Me pasa también que si en parametros pongo una VELOCIDAD_FLECHA grande, el programa corre a velocidad lenta, en algunos momentos las flechas se "apuran" a la velocidad que deberian estar y despues se vuelven a poner lentas.

**Comment by ExRage2000** [comment]
> Hola, en #931 el problema se solucionó con un cambió chico, ¿podrías ver si te funciona?

El tema es que mis flechas ya tienen parent, que son carriles donde se generan, pero son widgets no threads, los unicos threads que uso son las flechas, el resto son widgets, mainwindows o el timer que las genera

**Comment by aaossa** [comment]
@ExRage2000 en `FlechaThread` no pasas el parent en super: `super().__init__()`. Igual puede ser que no esté viendo la última versión de tu programa, pero es lo que tienes en el repo ahora 😅

**Comment by ExRage2000** [comment]
> @ExRage2000 en `FlechaThread` no pasas el parent en super: `super().__init__()`. Igual puede ser que no esté viendo la última versión de tu programa, pero es lo que tienes en el repo ahora 😅

Lo intenté pero no cambió nada, acabo de subir el nuevo commit
(Si lo va a testear acuérdese de tener los sprites porque yo no los puedo subir)

**Comment by aaossa** [comment]
@ExRage2000 cuando corrí tu código me costó ver el efecto que comentabas. Eso sí, me llamó la atención que cuando paso el puntero por sobre el botón "Comenzar", las flechas se aceleran por un tiempo corto y luego vuelven a la normalidad.

Pasando a tu código, veo dos cosas que quizás contribuyan a este "lag" 🤔 En primer lugar, tu lista de flechas (`self.flechas_totales`) solo crece, por lo que cada vez estás ocupando más y más espacio. Al terminar el `run` de tus `FlechaThread` eliminaría el *thread* y también enviaría una señal para quitar la instancia de la lista. Por otra parte, el tiempo entre actualizaciones me parece que es muy pequeño (el tiempo que le das a `sleep`), pero no sé qué tanto está contribuyendo eso, podrías probar con un valor más grande (pero recuerda agrandar el tamaño del movimiento también).

Prueba con alguna de esas cosas y si sigues viendo el mismo efecto avísame y le doy otra mirada 👌 ¡Éxito con la tarea 🙌!

PS: También le falta el *parent* a tu `QTimer` (`GeneradorFlechas`)

**Comment by aaossa** [comment]
> 
> 
> Hola! Me pasa exactamente lo mismo pero no me aparece "QThread destroyed while still running". De hecho no me aparece ningún error que me pueda dar una pista. Me pasa también que si en parametros pongo una VELOCIDAD_FLECHA grande, el programa corre a velocidad lenta, en algunos momentos las flechas se "apuran" a la velocidad que deberian estar y despues se vuelven a poner lentas.

Lo mismo que en mi mensaje anterior: no estás eliminando las flechas de la lista en la que las agregas 🤔 Y también te falta el *parent* en el `QThread`. Prueba con lo mismo que recomendé en mi último mensaje y ve si te sirve, ojalá así sea 🙌 ¡Éxito con la tarea!

**Comment by eliasbruchfeld** [comment]
> > Hola! Me pasa exactamente lo mismo pero no me aparece "QThread destroyed while still running". De hecho no me aparece ningún error que me pueda dar una pista. Me pasa también que si en parametros pongo una VELOCIDAD_FLECHA grande, el programa corre a velocidad lenta, en algunos momentos las flechas se "apuran" a la velocidad que deberian estar y despues se vuelven a poner lentas.
> 
> Lo mismo que en mi mensaje anterior: no estás eliminando las flechas de la lista en la que las agregas 🤔 Y también te falta el _parent_ en el `QThread`. Prueba con lo mismo que recomendé en mi último mensaje y ve si te sirve, ojalá así sea 🙌 ¡Éxito con la tarea!

Si ahora estoy implementando lo de eliminar las flechas. Pero no me queda muy claro lo de que me falta el parent en el QThread. En el __init__ si tengo puesto self, parent, etc, etc y cuando lo llamo tambien uso self. Que significa que me falta entonces

**Comment by aaossa** [comment]
@eliasbruchfeld aparece en la *issue* que cité al inicio: `super().__init__(parent)`. Con eso te aseguras de que tu `QThread` sepa cuál es su *parent*

**Comment by ExRage2000** [comment]
@aaossa ok, le di un parent al timer, aumenté el tiempo de update (la velocidad no era necesario cambiarla ya que estaba programada para ajustarse sola) y descomenté el la función que borraba los threads de la lista

Ahora las flechas van menos fluidas (van como dando pequeños saltos, pero no se nota mucho) y el efecto del lag es menos visible, pero creo que sigue estando ahí ya que cuando las flechas pasan por el cuadrado azul se ve que algunas se siguen "acelerando", lo que significa que siguen andando más lentas de lo que deberían.
No creo que el problema sea el cuadrado, ya que si uno se fija bien uno ve que se aceleran pase o no pase alguna flecha por el cuadrado

Técnicamente en este punto podría ignorarlo y trabajar con las flechas más lentas, pero no creo que las medidas actuales sean una solución definitiva y ya me pasó una vez que el efecto fue incrementando al hacer mas complejo el programa (aun me faltan las flechas especiales)

PS: 
> cuando paso el puntero por sobre el botón "Comenzar", las flechas se aceleran por un tiempo corto

creo que eso es casualidad, solo he usado ese botón para iniciar el timer.
> me costó ver el efecto que comentabas

...si, el lag llegó a tal punto que la velocidad con retardo parece la normal y pareciera que el problema es que se aceleran en vez de que se frenan
