### ISSUE TITLE
[EjerProp 3.2] Error de tipeo en instrucciones.

### ISSUE THREAD

**Issue by DasVaca** [IIC2233/syllabus#92]
En el ejercicio propuesto 3.2 de la semana 2 se dice que debemos checkear con 'bajo' pero es con 'Bajo' 
(y así con los otros)
Me costó un rato encontrar por qué me daba mal el output y quizá le pasa a otros.

**Comment by aaossa** [comment]
Hola @DasVaca , gracias por reportar el 🐛 No creo que lo cambiemos en el repositorio público porque podríamos romper sus clones locales 😅 , pero  ya hice el cambio para los próximos semestres ✨ Mil gracias!
