### ISSUE TITLE
Modelaje "consistente con el enunciado"

### ISSUE THREAD

**Issue by IngisRedd** [IIC2233/syllabus#92]
Ya se que no pueden ayudarnos con el modelaje en si, pero no comprendo bien que piden con que sea "consistente con el enunciado", y lo encuentro algo vago. Ya que se trata de una característica evaluada de la tarea, me gustaría tener clarísimo en que consiste y donde están los límites de esta instrucción.
Por ejemplo, en el enunciado dice que "los soldados son entrenados específicamente en el cuartel". ¿Esto significa necesariamente que la clase Cuartel **debe** tener el método encargado de instanciar a los Soldados? O cuando dice que "los soldados son las unidades que tienen la capacidad de atacar a otras civilizaciones", ¿significa que la clase Soldado **debe** tener un método encargado del ataque a las civilizaciones rivales?
Cómo estos hay varios otros ejemplos. A mi criterio personal hay maneras bastante más eficientes de modelar todo esto, pero no se cuán literal debo tomar el enunciado para asegurar que mi modelo sea "consistente" con éste.
Agradecería su aclaraciones en este asunto

**Comment by fdoflorenzano** [comment]
¡Hola! 

Para responder esto, debemos recordar un poco el objetivo de las evaluaciones del curso, ya que las actividades y las tareas tienen objetivos distintos. 

Las actividades están pensadas para que ustedes se enfrenten a los conceptos que estudiaron en el material del curso, puedan aplicarlos y resolver dudas. Como deben ser resueltas en un periodo muy corto de tiempo, las instrucciones y modelaciones son más directas. Estas tienen un enfoque técnico, para que ustedes no tengan que pensar qué herramientas usar, sólo aplicar los conceptos.

El objetivo de las tareas, en cambio, es que ustedes puedan resolver un problema complejo usando de la mejor manera posible los conceptos vistos. Por lo tanto, no sólo deben entender las herramientas de programación, sino que deben pensar cómo usarlas de la mejor forma posible. En una tarea rara vez les vamos a decir qué herramientas usar ni cómo usarlas, ya una de las cosas que se está evaluando es que ustedes puedan tomar estas decisiones. Las tareas se asemejarán lo más posible a un problema real, donde tampoco tendrán nadie que les diga cuáles son las herramientas que conviene usar.

En la tarea 1, específicamente se está evaluando que ustedes puedan usar los conceptos vistos de OOP y puedan tomar decisiones acerca de cómo usar de la mejor forma estos conceptos vistos. 

¿Por qué usar OOP? Ya que usando herencia, composición y asociación donde corresponda, el código se convertirá en un reflejo de la realidad, modela la realidad. Eso junto a los conceptos de encapsulamiento e interfaz logramos modelar objetos con comportamiento y responsabilidades que hacen más entendible el código de un programa. Dentro de encapsulamiento encontrabamos el uso de properties en Python, y dentro de interfaz el uso de polimorfismo o duck typing. De nuevo, todos estos principios nos ayudan a crear programar organizados.

¿Por qué modelar la realidad y no priorizar la eficiencia? Por mantenimiento de código: usar OOP hace el código mucho más legible.  Cuando otro programador quiera extenderlo o modificarlo, sabrá dónde ir (a qué archivo, clase o método). Lo que hacemos en el curso es prepararlos para programar no solo para ustedes, sino que para puedan programar en un equipo  y para el mundo real. Un código puede cumplir con todas las funcionalidades requeridas, pero si no cumple con estándares de calidad, difícilmente perdurará en el tiempo, ya que será muy difícil mantenerlo o ampliarlo cuando sea necesario. Bajo esta idea también cae el uso que les pedimos de PEP8, modularizar, formato de entrega, etc...

Ahora, volviendo a tu pregunta. Esas frases que mencionas solo dan contexto y explicación al comportamiento del programa completo. Son requerimientos que debe cumplir el programa, pero que queda a tu responsabilidad el pensar como implementarlo de mejor manera. No todo debe ser tomado tan literal. También, no hay una única manera correcta de hacer la tarea, sin embargo, no sólo se les evaluará que la tarea funcione, sino que esté bien modelada y cumpla con estándares de buena calidad de código.

Fue un poco larga la respuesta, pero quisimos aprovechar la pregunta para recordar este mensaje de parte de los profes.

Saludos.

**Comment by IngisRedd** [comment]
Wow, gracias. No es la respuesta que esperaba, pero me dio harto que pensar (y modelar cosas de nuevo :sweat_smile:).
