### ISSUE TITLE
Acciones contra incendios 

### ISSUE THREAD

**Issue by fantinee** [IIC2233/Syllabus#92]
¿Un usuario de la ANAF puede asignar recursos o usuarios a un incendio de manera independiente? Es decir, sin haber seleccionado una estrategia de extinción. ¿O la única manera de contrarrestar los incendios es eligiendo una estrategia y aplicándola? 
En torno a lo último, ¿puedo elegir una estrategia tan solo para visualizarla? o se aplicara de forma automática al incendio en cuestión?

**Comment by sebacruzd** [comment]
No está definido, por lo que puede quedar a tu criterio.
Recuerda especificar tus decisiones en el README.md
