### ISSUE TITLE
Duda sobre los nombres de usuario y su implementacion

### ISSUE THREAD

**Issue by cpschulz** [IIC2233/Syllabus#92]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Estaba probando mi codigo y me sugio una duda de como tratar con un error de ```No such file or directory: 'partidas/usuario.txt'``` en caso que al querer cargar una partida guardada el usuario no exista.

Debo crear alguna forma de tratar con eso o puedo asumir que siempre se va a usar un usuario que exitia previamente?

**Comment by bernirosas** [comment]
En el enunciado recomendaban (no me acuerdo si para esa parte), usar la función isfile(), sino según yo está mal.

**Comment by Emiliax16** [comment]
Hola. Tal como dice @bernirosas, puedes utilizar `isfile()` para verificar si la partida con ese nombre de usuario existe. Se debe manejar la posibilidad de ingresar un usuario inexistente, tal como dice la parte de 5.3  _Cargar_ del enunciado. Saludos!
