### ISSUE TITLE
birthdate vs birthday

### ISSUE THREAD

**Issue by movaldivia** [IIC2233/Syllabus#92]
Unos de los datos del usuario es su cumpleaños según el pdf es birthdate pero según el csv es birthday. Me gustaría saber como se va a llamar este dato cuando lo prueben en la corrección, porque dependiendo de eso mi programa funciona o no.

**Comment by Hernan4444** [comment]
@movaldivia el pdf es el que manda, cuando corrigamos tomaremos lo que dice el pdf (me preocuparé de corregir cualquier detalle del script 😓) y por si acaso se probará tanto con birthday como con birthdate.

Saludos!!

**Comment by movaldivia** [comment]
@Hernan4444 jajaja la carita triste. Gracias por la info !
