### ISSUE TITLE
Correo automático enviado me informa que sera corregido un commit previo al que deseo

### ISSUE THREAD

**Issue by DonJavi-538** [IIC2233/syllabus#92]
Escribo este issue porque un correo automático me informa que se corregira el commit que realicé a las 20:00, pero envié el form para que se revisara uno posterior.

Ignoro el mensaje automático? o realicé mal el form?

**Comment by entamburini** [comment]
Hola!

Los commits posteriores a la hora de entrega se actualizarán mañana cuando cierre el form :) 

Saludos! :v:
