### ISSUE TITLE
Duda descuento "Cambio de lineas" 

### ISSUE THREAD

**Issue by jahernandez2** [IIC2233/Syllabus#92]
Hola, se menciona en los descuentos: 
Cambio de líneas: (hasta 5 décimas)
Se permite cambiar hasta 20 líneas de código por tarea, ya sea para corregir un error o mejorar
una funcionalidad. Este descuento puede aplicarse si se requieren cambios en el código después de
la entrega (incluyendo las entregas atrasadas). Dependiendo de la cantidad de líneas cambiadas se
descontará entre una y cinco décimas.

En relación a eso, ¿hasta cuando se puede hacer? ¿Son siempre 5 decimas?

**Comment by matiasmasjuan** [comment]
Hola @jahernandez2 !

Efectivamente, existe la posibilidad de cambiar **hasta** 20 líneas de código para corregir este tipo de errores. En relación al descuento, este se calcula como ```math.ceil(x/4)```, siendo ```x``` el número de líneas cambiadas. Por ejemplo, si se cambian 10 líneas de código, el descuento será de 3 décimas.

Saludos!

**Comment by benjaaguila** [comment]
Hola!,

Al leer esta issue me quedo la duda de si solo se pueden **modificar** hasta 20 líneas o si también se pueden **agregar**, ¿Hasta cuando se puede hacer?¿En caso de realizarlo como se valida para que el código sea corregido con las líneas modificadas?

**Comment by matiasmasjuan** [comment]
Hola @benjaaguila !

Responderé a tus preguntas en orden:

1. Si, el cambio de líneas aplica también para la **eliminación** y **agregación** de líneas. En estos casos, una línea eliminada o agregada cuenta como una linea modificada. 
2. Puedes incluirlo en tu archivo ```README.md```. Para los casos de entregas atrasadas, lo puedes mencionar en el mismo formulario correspondiente.
3. Siempre que exista registro de la solicitud de cambio de líneas, se modificarán. Por lo tanto, si lo mencionas correctamente en tu ```README.md``` detallando las lineas que quieras cambiar, el contenido de ellas, los archivos donde están ubicadas y además la nueva línea que debe ir en su lugar, no debería haber problemas. En el caso hipótetico de que no se viera, siempre existe la posibilidad de solicitar una **recorrección** de la tarea indicando las líneas a modificar.

Saludos!

**Comment by gitlobo** [comment]
Es posible saber quien corregirá la tarea para notificarlo por correo sobre cambios de lineas o posibles errores en un lugar particular?
En mi readme insinué algo,pero no estaba seguro y no tenia la solución en ese entonces… (ahora si la tengo).

**Comment by matiasmasjuan** [comment]
Hola @gitlobo !

**No**, no es posible saber el/la corrector/a de la tarea. Si se trata de un error que impide correr el programa correctamente, el ayudante realizará los cambios de línea correspondientes. Si el error es muy grande y no se puede solucionar en menos de 20 líneas, al momento de la **recorrección** puedes solicitar los cambios que estimes necesarios cumpliendo con el límite máximo permitido. Si bien es cierto que puede que al momento no se te haya ocurrido la solución y posterior a la entrega sí, parte de la evaluación consiste en probar su programa sistemáticamente antes de entregar la tarea, por lo que está bajo su responsabilidad corregir estos errores antes de tiempo.

Saludos!
