### ISSUE TITLE
Duda sobre creacion de funciones propias.

### ISSUE THREAD

**Issue by gaspar-mr05** [IIC2233/Syllabus#92]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola. Tengo la pequeña duda de acerca si se pueden crear funciones en el mismo archivo de las clases. por ejemplo crear una funcion en tablero.py

**Comment by mtaguero** [comment]
¡Hola @gaspar-mr05!

El enunciado dice lo siguiente:

“Puedes crear nuevos métodos, archivos y/o funciones si estimas conveniente, pero debes mantener el formato de los métodos entregados.” 

Lo importante de esto es que **NO PUEDES** modificar alguna clase, método o property que ya esté definida por el equipo docente. Dicho esto, puedes crear una nueva función dentro de `tablero.py`, pero te recomendaría que por orden lo hagas en un nuevo módulo llamado `funciones_propias.py` por ejemplo. Ojo que es un consejo. Sea cual sea tu decisión, ¡no olvides mencionarlo en tu README!

Avísame si quedó claro.

¡Éxito! 🎈
