### ISSUE TITLE
[corto] Números en variables PEP8

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#92]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### ¿Es aceptado el siguiente formato para variables?

![image](https://user-images.githubusercontent.com/66154723/112763176-c1618100-8fd9-11eb-8fde-3a18fc2c1e95.png)

**Comment by pabloist** [comment]
Hola! :)

Si bien entiendo la asignación que le das a cada una de las variables, te recomiendo ser más específico en cuanto al significado de cada una de ellas dado que podría ser considerado mala práctica por parte del ayudante corrector. Por ejemplo si queremos referirnos al título del menú, una variable podría ser _menu_title_ o _tit_menú_, y en caso de que tuvieras múltiples títulos se podría considerar la utilización de numerales para diferenciar las variables.

Saludos!

**Comment by fernandosmither** [comment]
> Hola! :)
> 
> Si bien entiendo la asignación que le das a cada una de las variables, te recomiendo ser más específico en cuanto al significado de cada una de ellas dado que podría ser considerado mala práctica por parte del ayudante corrector. Por ejemplo si queremos referirnos al título del menú, una variable podría ser _menu_title_ o _tit_menu_, y en caso de que tuvieras múltiples títulos se podría considerar la utilización de numerales para diferenciar las variables.
> 
> Saludos!

Entiendo. En este caso en particular, tengo el menú que tiene su mensaje txt_menu, y tiene dos submenús que serían txt_menu1 y txt_menu2. Consideré que puede ser más corto y mejor de ver en vez de poner txt_submenu1 o txt_menu_submenu1,
pero, ¿Qué prefieren ustedes los ayudantes?

**Comment by pabloist** [comment]
Particularmente en este caso la primera parte de tus variables _txt_ no aporta información relevante de la misma, por lo que podrías utilizar _submenu1_ y _submenu2_. En caso de que ya tengas variables definidas para _menu_ y _submenu_ y necesites utilizar el diferenciador de _txt_, te recomiendo _txt_submenu1_, en cuyo caso el largo no es un problema.

Saludos!

**Comment by fernandosmither** [comment]
Gracias. Resuelto!
