### ISSUE TITLE
Dudas varias Tarea 1

### ISSUE THREAD

**Issue by nhbravo** [IIC2233/Syllabus#92]
1) En el nivel de evolución se indica: "Evolución = ... + ((cantidad magos y soldados) / población total)...". No me queda claro qué números usar ahí, porque cantidad de magos + cantidad de soldados debiese ser igual a la población total. Por favor aclarar :)

2) En el apartado 14 se indica que, en caso de no estar especificado, no se pueden usar otras librerías de python, pero que se puede preguntar en el foro el uso de alguna otra. Pregunto, ¿puedo utilizar las librerías: collections, random, time?

3) En el apartado 6.4.1 se indica la existencia de un tercer edificio que no había sido previamente mencionado (escudo). ¿Lo tomamos en cuenta?, de ser así, ¿cuales son sus atributos?

Agradecería mucho alguna respuesta :)

**Comment by naquiroz** [comment]
No soy ayudante, pero creo que tus dudas ya fueron respondidas 😅

**Comment by nhbravo** [comment]
Encontré solo mi segunda duda resuelta! Si alguien sabe de la 1. y 3. sería de gran ayuda :)

**Comment by pcseisdedos** [comment]
la 1 y la 3 también están respondidas, en #24  y #23

**Comment by nhbravo** [comment]
Muchas gracias!
