### ISSUE TITLE
Bonus presidente

### ISSUE THREAD

**Issue by mariovaldesa** [IIC2233/syllabus#920]
En el bonus que es lo que define si me aumenta la reputación o me disminuye? Si le entrego el plato me aumenta? O si se lo entrego antes de que se enoje?

**Comment by cristozille** [comment]
Hola @mariovaldesa! Tu reputación aumenta si le entregas el pedido antes del tiempo de espera, pero disminuye su te demoras más del tiempo de espera.

**Comment by mariovaldesa** [comment]
Gracias

**Comment by cristozille** [comment]
Denadaa :)
