### ISSUE TITLE
Mis señales no logran concectar backend con frontend

### ISSUE THREAD

**Issue by franciscavelascog** [IIC2233/syllabus#920]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Las señales de mi ventana inicio y ventana de juego (frontend) en un principio si conectan correctamente con la lógica del juego, sin embargo las siguientes señales emitidas, no son capaces de conectar la ventana de juego con otros métodos del backend. Estas están correctamente escritas e instanciadas y ya revise todo error posible. Cómo puedo solucionar esto?

**Comment by jaimecoloma** [comment]
Hola @franciscavelascog, es un poco complejo darte una solución sin poder ver lo  que estas haciendo, podrias contarme en donde esta el error? prueba utilizando prints para saber hasta donde llega tu código para poder detectar más rapido tu problema.

**Comment by jaimecoloma** [comment]
Clone tu repositorio pero no me funciona correr el main.py,  hay algo que deba saber ? Quiero probar tu codigo

**Comment by franciscavelascog** [comment]
ya lo arreglé! gracias
