### ISSUE TITLE
Máximo de reputación

### ISSUE THREAD

**Issue by Juampisaez** [IIC2233/syllabus#921]
Hola queria saber si existe un maximo valor para la reputacion, revise el enunciado y no dice nada sobre eso (en una de esas se les paso o directamente no existe)

**Comment by bvasquezm** [comment]
Hola @Juampisaez,

Creo que se te pasó al leer el enunciado jajajaj. En la sección del DCCafé señala que el máximo de puntos o reputación es **5**. De todas maneras si te fijas en la fórmula para el cálculo de reputación, tiene como máximo 5 y mínimo 0. Suerte con tu tarea!!

**Comment by Juampisaez** [comment]
si cache, jejeje. Gracias
