### ISSUE TITLE
Problema conectando señales entre ventanas

### ISSUE THREAD

**Issue by pabloalvarez67** [IIC2233/syllabus#921]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola, tengo un problema chico. Tengo una señal que emito desde la ventana de juego la cual está igualada en el main con una señal de la ventana resumen. Le paso en este señal 5 ints, que son las cosas que quiero mostrar en mi ventana resumen!

No me funciona asignar esta señal a una funcion, y que luego de esta funcion se retornan los atributos. Hay alguna forma de hacer atrobutos de clase a los valores que le llegan esta función? para así después poder usarlos en su respectivo gui.

Saludos!

**Comment by jaimecoloma** [comment]
Hola @pabloalvarez67 ! Creo que no entendi muy bien tu problema, podrías explicarlo un poco más detallado y decir en donde te muestra un error?

**Comment by pabloalvarez67** [comment]
No me muestra ningun error.
tengo igual una señal_mostrar_resumen en la clase de la venta_resumen, y en la clase de la ventana_juego.

Esta señal al emitirse, emite 5 ints.
quiero pasarle los valores de esos ints como atributos de clase a la venta_resumen que quiero abrir, ya que esos ints son los valores que quiero mostrar de alguna forma en esa ventana_resumen.

Hay alguna forma de hacerlo? he estado probando conectar esa señal a un método de la clase ventana_resumen, y dentro de ese método asignar esos valores a atributos, por ejemplo:

def asignar_valores(self, p_obtenido, .........)
          self.puntaje_obtenido = p_obtenido
          ................

**Comment by pabloalvarez67** [comment]
Lo que pasa es que al principio les pongo None a esos valores (cuando hago el init), ya que si no me tira el error dentro del init_gui de la ventana que no tiene los atrobutos de clase que quiero mostrar

**Comment by jaimecoloma** [comment]
Creo que lo más facil es definir esos atributos en tu init como self.puntaje_obtenido = int y luego como mencionas en un método cambiarle el valor...  el error puede ser que quizás no se esta conectando la señal? que se emite pero no se conecta. Anda haciendo prints antes del emit para ver si llega ahi primero, luego verifica la conexion y luego anda al método donde conecta y has un print, por ahi podrias partir. Avisame si eso te ayuda. Recuerda tambien tener instanciada las clases donde conectas las señales

**Comment by pabloalvarez67** [comment]
acabo de confirmar que si llega al metodo que quería, y además si le llegan los valores dentro del método!
pero por alguna razón no puedo cambiar el valor del atributo desde la funcón :(

**Comment by jaimecoloma** [comment]
Solamente para entender, estas haciendo algo como:
self.att_a_cambiar = atributo_recibido_senal ??
Solo por si este podria ser el motivo, recuerda actualizar los valores en la intefaz! (y prueba haciendo un print luego de cambiarle el valor)

**Comment by pabloalvarez67** [comment]
me funcionó haciendo que el init_gui reciba las señales, y el init_gui hace los labels con esos valores que recibe.
Gracias igual @jaimecoloma  !

**Comment by jaimecoloma** [comment]
Me alegro! Éxito!
