### ISSUE TITLE
Rapidez del reloj

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#922]
Hola. No entiendo muy bien cómo es que a través de un parámetro debemos implementar la rapidez del reloj. Más que nada, quiero entender qué tipo de valor debemos asignarle¿? es un int, float ?. Y Si estoy usando QTimer, hay alguna manera de que éste considere éste parámetro?, con qué método de QTimer?

**Comment by cristozille** [comment]
Hola! La idea es que el reloj simule el paso del tiempo. Si estas usando QTimer podrías tener una función llamada pasar_minuto()  la cual indique que paso un minuto en el juego, y QTimer la ejecuta en un cierto intervalo de tiempo. Con esto, el parámetro a ingresar sería el intervalo de tiempo entre 'minutos'. Si dices que QTimer tenga intervalos dee 1 seg entonces por cada segundo el programa avanzará un minuto. Si pones 30 seg como intervalo eel programa avanzará 1 minuto por cada 30 seg que pasen. De esta forma tu controlas  que tan rápido fluye el programa. Esa es mas o menos la lógica de la rapidez del reloj.
