### ISSUE TITLE
Aprobación negativa

### ISSUE THREAD

**Issue by Sofia-Arratia** [IIC2233/syllabus#922]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola!

No se si estoy entendiendo bien el funcionamiento del cálculo de aprobación, ya que al tener un ejemplo en el que se muestra en una barra de progreso yo asumiría que el porcentaje debe ser mayor o igual a 0, pero sin embargo según como estoy entendiendo el porcentaje de aprobación, este puede llegar a ser negativo en caso de que se generen más pasos incorrectos que correctos. ¿Estoy entendiendo bien?, y en ese caso, ¿Debo setear la aprobación para que tenga un mínimo de 0 o en caso de que sea negativa debo mostrarlo?

Muchas gracias! ☺️ 

PD: Los pasos totales son todos los pasos que genera el jugador (presionando teclas), no los pasos que genera el juego (generando flechas), ¿No?

**Comment by jaimecoloma** [comment]
Hola @Sofia-Arratia !! Efectivamente lo que dices es correcto, la fórmula quedó con un fallo que puede generar que sea negativo el valor de la aprobación (y por ende más dificil pasar de nivel 😮 ), sin embargo se decidió mantener así para no generar cambios que puedan perjudicar a aquellos que ya lo tenian. Por esto si tu programa muestra una aprobación negativa **no seria incorrecto**! Si quisieras setear un mínimo de 0 sería mejor que lo especifiques en tu readme.
Sobre pasos totales te recomiendo leer esta issue (el final) #882 
Mucho éxito!!

**Comment by Sofia-Arratia** [comment]
¡Perfecto! Muchas gracias 😄 , otra pregunta corta, sería incorrecto si cambio la fórmula de aprobación para que solo contabilice los pasos correctos respecto a los totales? Sería así : 100* (pasos correctos / (pasos correctos + pasos incorrectos + pasos ignorados)) 
Esto sería solo porque me hace un poco más de sentido.
Muchas gracias!

**Comment by jaimecoloma** [comment]
Será mejor que no cambies la formula porque se corrige por código esa parte, sin embargo lo que si puedes hacer para que te haga más sentido es hacer lo que propusiste primero, que el valor minimo sea 0 y no negativo. Esto mencionalo en tu readme etiquetando esta issue si asi lo prefieres!

**Comment by Sofia-Arratia** [comment]
¡Perfecto! Muchas gracias 😄
