### ISSUE TITLE
Problemas con QThread-QTimer

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#923]
Hola, estoy haciendo una clase que hereda de ```QThread```, y en sus atributos puse un QTimer, y en el método ```run(self)``` del ```QThread``` quiero empezar este timer. Luego fuera de la clase pongo ```nombre_clase().start()``` pero me tira este error:
![image](https://user-images.githubusercontent.com/59337116/83572384-7b41ab00-a4f7-11ea-94f7-f3506cad47fe.png)
Qué estoy haciendo mal?

**Comment by danckoo1** [comment]
Según entiendo, el thread no lo estás almacenando en ninguna variable, por lo tanto este solo existe mientras haces el start e inmediatamente es destruido, lo cual provoca ese error. Entonces debes instanciar el thread en alguna variable y posteriormente llamar a su método start para que te funcione. 
Avísame cualquier cosa :)

**Comment by Camila-sty** [comment]
Sí eso era. Ahora tengo otro problema. Siguiendo la misma de idea de hacer una clase que herede de ```QThread``` donde en sus atributos instancio un ```QTimer```.
Pero quiero que comience cuando la instancio en otra clase que hereda de ```QObject```. En algún momento quiero que esta clase llamada ```Reloj``` comienze a ejecutar su método ```run()```, y que al mismo tiempo empiece este ```QTimer```.
La idea de mi clase  ```Reloj``` es la siguiente:
```
class Reloj(QThread):
    def __init__(self):
        super().__init__()
        self.timer = QTimer()
        self.timer.setInterval(segundos * 1000)
    def comenzar_tiempo(self):
        self.timer.start()
    def run(self):
        ......
       
```
Lo que yo hago, es que en un momento determinado de mi clase que hereda de ```QObject```, se instancie esta clase  ```Reloj```, pero en vez de colocar ```instancia_reloj.start()``` , llamo directamente al método ```comenzar_tiempo``` para que mi reloj y el método  ```run()``` se ejecuten. Me refiero a lo siguiente:
```
instancia_reloj= Reloj()
instancia_reloj.comenzar_tiempo()
```
Pero de esta manera, el método  ```run()``` de mi clase  ```Reloj``` no se ejecuta.
Yo no hice así porque se supone que dado el caso en como ocupé mi clase que hereda de ```QThread```, tiene el atributo ```self``` para el ```QTimer``` creado, entonces yo entendí que cuando éste ```QTimer``` empezaba, el método ```run()``` también lo hacía. Lo estoy entendiendo mal?
Qué debo hacer para que suceda lo que quiero que pase?

**Comment by Nicobuzeta** [comment]
De lo que entiendo, quieres que empieze a correr el timer al mismo tiempo que empiezes a correr el run(), osea cuando llames el start() del thread. Probablemente lo mas facil seria usar la señal `started` del thread. Esta señal se emite justo cuando tu llamas el start asique podrias hacer que la señal llame al start de tu timer.
```
class Reloj(QThread):
    def __init__(self):
        super().__init__()
        self.timer = QTimer()
        self.timer.setInterval(segundos * 1000)
        self.started.connect(self.timer.start)

    def run(self):
        ......
```
Tu otra opcion seria expandir el metodo start. Aca podrias directamente partir tu timer cuando llamas start().
```
class Reloj(QThread):
     def __init__(self):
        super().__init__()
        self.timer = QTimer()
        self.timer.setInterval(segundos * 1000)
    
    def start():
        self.timer.start()
        super().start()

    def run(self):
        ......
```

**Comment by Camila-sty** [comment]
Hice la segunda opción que me diste. Me tira este error:
![image](https://user-images.githubusercontent.com/59337116/83597180-a1397080-a534-11ea-8215-4d6573d5bfb2.png)
que es el mismo de un principio. Quizás estoy llamando mal al método.
Una pregunta, el ```start()``` no debería ser ```start(self)```?
Y entonces, haciendo lo que me propusiste en la segunda opción. Debería hacer:
```
instancia_reloj= Reloj()
instancia_reloj.start()
```
Y así conseguiría que mi ```QTimer``` iniciara y método ```run()``` se ejecutara?

**Comment by Nicobuzeta** [comment]
Se te arreglo antes y ahora te empezo a salir denuevo? 
Estas seguro que talvez no borraste el self antes?
En teorio ese mensaje te deberia salir solo si llamas `terminate()` (Creo que esa es la funcion) o pasa lo que dijo el @danckoo1 con el garbage collection que te borra la variable.
En todo caso, yo me confudi un poco y mientras lo que mande deberia funcionar, poner el timer en el start directamente tambien te deberia funcion.

**Comment by Camila-sty** [comment]
Pero haciendo eso, cómo hago correr el método ```run()``` ? tengo que instanciar la clase nomas?

**Comment by Camila-sty** [comment]
Haciendo lo último que mencionaste, y haciendo:
```
instancia_reloj= Reloj()
instancia_reloj.start()
```
Me vuelve a tirar el mismo error...

**Comment by Nicobuzeta** [comment]
Si te esta tirando un error probablemente es algo mas profunda y va a tener que ver una ayudante que pueda ver tu codigo.
Pero respondiendo tu pregunta

> Pero haciendo eso, cómo hago correr el método run()

Cuando tu corres start(). Esa funcionan automaticamente corre el run() asique no es necesario correr directamente el run().

```
instancia_reloj= Reloj()
instancia_reloj.start()
```
deberia ser 
```
self.instancia_reloj= Reloj()
instancia_reloj.start()
```
No se si asi lo tienes o lo pusiste asi para hacerlo mas corto, pero como dijieron antes. Sin el self, el thread se te va a borrar despues de declararlo.

**Comment by Camila-sty** [comment]
He implementado las opciones que me das. Aplicando esto:
```
class Reloj(QThread):
    def __init__(self):
        super().__init__()
        self.timer = QTimer()
        self.timer.setInterval(segundos * 1000)
    def run(self):
        self.timer.start()
       
```
Y en mi otra clase pongo:
```
self.instancia_reloj= Reloj()
self.instancia_reloj.start()
```
Con eso mismo. Me tira este error:
![image](https://user-images.githubusercontent.com/59337116/83648230-cdc8a900-a583-11ea-8522-0e4ff331ef3b.png)
Luego cambié algo, quedando así:
```
class Reloj(QThread):
    def __init__(self):
        super().__init__()
        self.timer = QTimer()
        self.timer.setInterval(segundos * 1000)
    def run(self):
        self.timer.start()
       
```
Y en mi otra clase pongo:
```
self.instancia_reloj= Reloj()
self.instancia_reloj.start()
```
Y con esto, no me tira ningun error. El método ```run()``` se ejecuta. Pero El ```QTimer``` no empieza....
No entiendo por qué. Si se supone que al comenzar esta clase que hereda de ```QThread``` y que ademas tiene como atributo ```self.timer = QTimer()``` , debería empezar el reloj si la clase comieza..

**Comment by Camila-sty** [comment]
Hice un push de mi tarea. Por si quieres revisar..
Mi clase ```Reloj``` está en el módulo ```logica.py``` , y yo instancio ésta clase ```Reloj``` en la clase ```Logica``` del mismo módulo.

**Comment by Camila-sty** [comment]
Lo logré hacer. Gracias!!
