### ISSUE TITLE
Como "matar" un thread

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2233/syllabus#924]
Hola, tengo una clase que hereda de thread. Quiero saber como parar/cortar su metodo run si es que un evento ocurre

**Comment by cristozille** [comment]
Hola! Los threads terminan cuando la función run() se completa. Te refieres a eso?

**Comment by dsepulveda3** [comment]
Nono me refiero a como pausar este o detenerlo por completo para que parta de nuevo.
O sea en el caso de que una persona se le de la comida quiero detener el run de mi cliente. El otro caso que pregunto para usar el boton pausar.

**Comment by cristozille** [comment]
Una  forma de parar  un thread es utilizando un lock() que se active cuando quieras pausar el thread. El thread se puede quedar esperando el lock.release() para continuar.  Por otro lado si el evento es otro thread puedes usar join() el cual permite al thread esperarlo antes de continuar.
