### ISSUE TITLE
Duda flechas de hielo y ralentización

### ISSUE THREAD

**Issue by jorgetf-desing** [IIC2233/syllabus#924]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, tengo la duda respecto al uso de estas flechas: lo primero, tengo entendido que se debe ralentizar la velocidad de las futuras flechas, pero también la generación de estas? ya que sino se empiezan a amontonar. Segundo, si se ralentizan las flechas también se debe ralentizar el tiempo? la barra de progreso se mueve más lenta? el nivel terminaría después?
Saludos

**Comment by manearaya** [comment]
Hola @jorgetf-desing!

El único efecto que tienen las flechas de hielo es modificar la **velocidad** de las flechas en un intervalo de tiempo. El resto de los tiempos se mantienen igual: las flechas se generan en el mismo intervalo de tiempo y el nivel debería durar lo mismo.

Con respecto al amontonamiento de las flechas, no está mal porque es entendible que la velocidad no va a ser suficiente como para que haya un espacio entre ellas (como en el issue #864).

Ojalá haya quedado claro!
