### ISSUE TITLE
Uso de librería Numpy

### ISSUE THREAD

**Issue by CatalinaGoldsack** [IIC2233/syllabus#925]
Hola! ¿Puedo usar la librería numpy para hacer crear una grilla de pixeles usados por los objetos del mapa??

**Comment by danckoo1** [comment]
Hola!, para mantener el orden en cuanto a las librerías permitidas y que todos estén al tanto, te invito a que lo preguntes dentro de la issue #680

**Comment by CatalinaGoldsack** [comment]
Uh! Perdón! voy :)
