### ISSUE TITLE
Bordes del mapa

### ISSUE THREAD

**Issue by BelenSilva1204** [IIC2233/syllabus#926]
![SmartSelectImage_2020-06-02-18-25-19](https://user-images.githubusercontent.com/62078553/83575857-06ba3c80-a4f6-11ea-89b3-a2adf2a96cd5.png)

Holaa, puedo crear el juego con posiciones validas como en el rectángulo amarillo de la foto o lo correcto seria poder jugar en todo el mapa colisionando con los arboles y la banca roja como marqué en rojo?

**Comment by kadroguett** [comment]
Hola @BelenSilva1204 
Lo correcto son los límites rojos. Si te complica mucho el tema de los árboles recuerda que ese elemento decorativo no es obligatorio.

**Comment by BelenSilva1204** [comment]
Ok, ¡muchas gracias!
