### ISSUE TITLE
Se me cae Python sin aviso alguno a pesar de tener solo un sub-thread

### ISSUE THREAD

**Issue by TMagini** [IIC2233/syllabus#927]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola, me pasa que a pesar de tener un solo sub-thread, el programa de vez en cuando se me cierra solo sin tirar ningún aviso alguno (principalmente en modo `Aficionado` y  `Maestro`), estuve leyendo las issues pero en su mayoría el cierre de la aplicación esta relacionado con tener muchos threads por lo que no se como hacerlo.

**Comment by fernandareyesc** [comment]
Hola! Tengo una duda similar, cuando estoy en la ventana de juego y aprieto el botón de iniciar juego se pega todo, me sale que python no responde. No se si debería revisar más el código o pueda ser un problema del programa.
Agradecería mucho si pudiesen ayudarme! ya que no he podido seguir avanzando por eso.
Muchas gracias desde ya!

**Comment by caroizquierdo** [comment]
Me pasa lo mismo y nose como arreglarlo nose como ver que funciones son las que me estan colapsando el programa

**Comment by JuaniAndres** [comment]
Hola @TMagini , @fernandareyesc y @caroizquierdo 
Lo primero que les puedo recomendar es que prueben ocupar el siguiente código de los contenidos de la semana 9 al [final de la parte de interfaces gráficas](https://github.com/IIC2233/contenidos/blob/master/semana-09/1-interfaces-gr%C3%A1ficas.ipynb) antes de instanciar a su ````QApplication```` :
````python
def hook(type, value, traceback):
    print(type)
    print(traceback)
sys.__excepthook__ = hook
````
Este código permite capturar y imprimir muchos de los errores pequeños que aparecen por el lado de  pyqt5. Lo segundo tengan cuidado con el manejo de sus threads esto igual depende de como estén modelando todo en su caso pero algunos consejos es que se aseguren de que sus thread terminen su run  y no se queden corriendo infinitamente. También de ir borrando sus threads después de que terminen y ya no sean necesarios (en el caso de QThreads utilicen ````.deleteLater()```` en el thread antes de borrarlo) 
Para que se borre su thread lo unico que tienen que hacer es eliminar ese thread de cualquier atributo asi python se encarga de borrarlo. Por ejemplo si yo tengo una lista de Qthreads podría implementar lo siguiente para ir borrando los threads
````python
def eliminar_Qthread(self, thread):
    thread.deleteLater()
    self.lista_de_qthreads.remove(thread)
````
Donde ````thread```` es la instancia de Qthread y ````lista_de_qthreads```` donde los almaceno
Prueben revisar lo que les dije y si siguen con problemas me avisan

**Comment by fernandareyesc** [comment]
Muchas gracias!! lo intentaré ahora!

**Comment by TMagini** [comment]
Hola @JuaniAndres , implemente lo que dijiste del `deleteLater()` solo que lo puse en el caso de hacertar una flecha unica, puse que haga el `deleteLater()` y que despues popeara (`.pop()`) la flecha de la lista y me tira error que he leído en otras issues de `QThread: Destroyed while thread is still running`

**Comment by JuaniAndres** [comment]
Creo saber la razón de porque estas teniendo ese error @TMagini. Ese error significa que estas tratando de eliminar un Qthread que todavía no termina su run. Eso puede  ocurrir incluso si la ultima línea del run es un señal.emit() que avisa al método que hace .pop(). Para asegurarnos de que el Qthread no sea borrado hasta que termine puedes utilizar la señal ````finished```` de cualquier Qthread que se emite solamente cuando el thread termina su run. Entonces puedes hacer ````thread.finished.connect(metodo_borra_Qthread)```` lo cual permite asegurarnos de no borrar threads antes de tiempo.
Si ese no era el problema me avisas y subes tu código a tu repositorio para poder revisarlo.

**Comment by caroizquierdo** [comment]
Hola @JuaniAndres tngo una duda es ma de contenido pero porque tenemos que guardar los threads en una lista? Para que sirve eso?
Y lo otro ya lo intente eliminandolos y sigue colapsando, hasta cambie el codigo entero y sigue sin funcionar

**Comment by TMagini** [comment]
@JuaniAndres intente lo que me dijiste y me pasa q mi run de los threads lo tengo con un while y una vez q termina el while aún sigue activo, y no se porque, por lo que nunca termina.

**Comment by JuaniAndres** [comment]
Hola @caroizquierdo 
La razón de porque guardamos las threads en algún atributo es porque si nosotros instanciamos un Qthread pero no lo guardamos automáticamente cuando el método o función termine python va a detectar la instancia y la va a borrar generando el ````QThread: Destroyed while thread is still running```` si le aplicaste .start()
Algo como este ejemplo simplificado:
````python
def funcion():
    variable=5

funcion()
print(variable)
````
Correr ese código entrega el siguiente error ````NameError: name 'a' is not defined```` que se debe a que  la variable deja de existir cuando termina la función. Quizas algo que se entendió mal, no es obligatorio guardar los threads en listas puedes guardarlos en cualquier otra estructura como por ejemplo diccionarios o simplemente como self.thread = MiThread lo importante es que la instancia quede guardada en algún lugar.
Si puedes, sube tu código para revisar que puede estar pasando 

@TMagini  Lo mismo confírmame que en tu repositorio esta lo que llevas

**Comment by TMagini** [comment]
@JuaniAndres ahí actualicé mi repositorio con el intento de `deleteLater()`

**Comment by JuaniAndres** [comment]
Creo que te falto hacer git push o es el commit ````Sin terminar con los QThreads````?

**Comment by TMagini** [comment]
@JuaniAndres perdón, se me habia caido el internet ahí se subio, es el commit `Intentando Borrar QThreads`

**Comment by caroizquierdo** [comment]
@JuaniAndres Ahi lo actualicee

**Comment by JuaniAndres** [comment]
Ya @TMagini  revise tu código pero el problema era lo que te decía que no puedes borrar un Qthread si este no a terminado. Cuando capturas una flecha en tu zona de captura el thread de la flecha sigue corriendo debido a como definiste el run de tu clase Arrow por lo que si le aplicas deleteLater y lo tratas de borrar con el pop vas a tener igual  el problema de ````QThread: Destroyed while thread is still running````. Tienes que asegurarte que el Qthread termino antes de borrarlo por lo que quizás tengas que modificar el run de Arrow  para que el thread se detenga si la flecha fue capturada o modificar en que momento borras las flechas.
Si quieres revisar lo que te estaba diciendo puedes agregar lo siguiente ````print(arrows[0].isFinished())````  en la linea 128 de logica_ventanas.py justo antes de lo de borrar la arrow y notaras que si corres el juego en dificultad principiante justo antes de que falle tu programa por capturar una flecha normal aparece False en consola eso es porque ````.isFinished()```` retorna True si el thread ya termino y False si todavía esta corriendo en tu caso si tratas de borrar cuando aparece False significa problemas. Dale una vuelta quizás te puede servir la señal finished o con modificar el run lo arreglas

**Comment by TMagini** [comment]
@JuaniAndres aplique lo q me dijiste y en la misma linea 128 aplique un `arrows[0].finished.connect(arrows[0].deleteLater)`, pero no me eliminaba ningún QThread, por lo que vi si efectivamente salía del run la flecha después de cumplir su función, poniendo un `print(self.isRunning())` afuera del while del run de la flecha y printea `True` y también puedo ver en el depurador de VisualStudio como se siguen sumando `Dummys`, que supongo que son los QThreads que nunca terminan. También probé cambiando la condición del while pero no entiendo porque saliendo del while no termina el QThread.

**Comment by JuaniAndres** [comment]
El tema es que deleteLater() lo que hace es que cuando se borre la parte de python de la Qthread  también se borre una parte de información que esta por el lado de pyqt. Por si solo deleteLater no va a borrar la instancia  de tu Qthread ya que es python el que lo tiene que borrar. El problema que estas teniendo es que tus flechas terminan de correr solamente cuando superan una altura "y" pero si tu apretas una tecla de tu zona de captura y hay una flecha tu tratas de borrar el Qthread que como todavía no supera el limite "y" por lo que sigue corriendo.
Si quieres háblame por discord y te puedo mostrar en que partes esta el problema

**Comment by JuaniAndres** [comment]
@caroizquierdo revise tu código en tu caso creo que deleteLater te esta generando errores por las señales constantes que recibe de Tiempo igual podrías sacar el deleteLater y según yo no debería darte problema ya que es Tiempo en tu caso el que hace casi toda la pega. Ojo con las líneas que tenias comentadas en ````mover_flecha```` ya que Tiempo sigue mandando señales constantemente a pesar de que la flecha ya supero el ````limite_y```` por lo que esas líneas comentadas terminarían emitiendo constantemente la ````senal_terminar_flecha```` por lo que tienes que hacer un ajuste para que la ````senal_terminar_flecha```` se emita solamente una vez por flecha.
Un detalle que podrías analizar si en tu caso la clase Flechas necesitan ser un Qthread ya que no estas corriendo ninguna función del estilo run o realizando algún comportamiento de QThread.
Prueba eliminar el deleteLater() y me avisas si sigues con problemas

**Comment by fernandareyesc** [comment]
hola! tengo una duda con la función que nos recomendaste usar, 
def eliminar_Qthread(self, thread):
    thread.deleteLater()
    self.lista_de_qthreads.remove(thread)
me pasa que uniendolo con lo de " thread.finished.connect(metodo_borra_Qthread)  ", al momento de enviarlo a que se elimine como es otra funcion el thread "ya no existe"? como es fuera de donde se crea no puedo usarlo para ingresarlo a la función de eliminar los threads. No se si entendí mal o ya debería plantearme hacer de nuevo partes del código jajaj.
Muchas gracias desde ya!

**Comment by JuaniAndres** [comment]
Hola @fernandareyesc 
Fue un detalle que no deje tan claro. La función eliminar_qthread no era más que un ejemplo simple para hacer una idea de a lo que me refería con borrar un QThread. Tienes razón con lo que comentas que ```` thread.finished.connect(metodo_borra_Qthread)````  no funcionaria correctamente con el ejemplo de la función eliminar_qthread porque la señal finished es una señal simple que no manda información del thread. Cuando le respondí a TMagini estaba pensando en un metodo distinto al que mostre asique voy a editar el mensaje anterior para dejar eso más claro. Igual si es que quieres lograr conectar finished a una función similar a eliminar_qthread directamente podrías ocupar el método ````sender()```` dentro de eliminar_qthread para obtener quien envió la señal que en este caso seria tu thread un ejemplo de eso puedes encontrarlo en los [contenidos de señales y eventos](https://github.com/IIC2233/contenidos/blob/master/semana-09/3-eventos-y-se%C3%B1ales.ipynb).
Perdón por la confusión y quedo atento si todavía no te queda tan claro a lo que me refiero

**Comment by fernandareyesc** [comment]
Aaaah entendí perfecto!! intentaré de nuevo.. mil gracias por tu ayuda!!
