### ISSUE TITLE
Descuadramiento de flecha y avance de ellas 

### ISSUE THREAD

**Issue by Natydlb** [IIC2233/syllabus#928]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola! he intentado de todo D: y no me avanza la flecha, intente que empezara dandole click al botón comenzar y nada, además como que no se cuadran bien, como lo tengo en qt designer, ayuda :( hice git push el problema esta en pista_baile.py y pista_baile_BE.py

**Comment by furcelay** [comment]
Hola @Natydlb !

Veo que los problemas al generar las flechas son los siguientes:
*  En el `__init__` de `Flecha` creas un `randint(0, 4)` pero solo verificas los números del 0 al 3, entonces cuando sale 4 no se define correctamente y el programa se cae (randint incluye los extremos), lo mismo pasa para el 2 pero porque en ese caso no defines `posicion_x`. Además recuerda que cuando tienes múltiples condiciones excluyentes se usa `if/elif`.
* Estás modificando el label de las flechas en el thread de la clase `Flecha`, pero como ese label está contenido en una ventana en un thread distinto el programa no sabe a dónde enviar la información del label. Para solucionar esto el thread debe saber quien es su *parent* para que así le envíe la información del label, entonces en el `__init__` de `Flecha` debes modificar la parte en que inicializas el `Qthread` a `super().__init__(parent)`
*  Aunque no es sobre las flechas tienes un problema con la zona de captura porque no has importado `Qt` y porque algunos de los `match2` son `QLabels` mientras que otros son `QRects`.

Espero que con eso puedas resolver tu problema, saludos! :smile:
