### ISSUE TITLE
Clausura DCCafe

### ISSUE THREAD

**Issue by mpmunoz13** [IIC2233/syllabus#928]
Hola! 
Cuando la reputación es cero y se clausura el cafe, que datos deben estar guardados al ingresar nuevamente al juego? Puedo poner "seguir" depues de haber perdido y volver a la ultima ronda antes de perder?

**Comment by jitorcas** [comment]
Hola @mpmunoz13!

Si el DCCafé es clausurado, y quieres poner "seguir" se debe reiniciar como se explica en la sección **3.6.1**
