### ISSUE TITLE
Drag and drop con Qlabel

### ISSUE THREAD

**Issue by dcastillo5** [IIC2233/syllabus#929]
Holaa! Estoy teniendo problemas implementando la parte encargada del drop.
 En términos generales lo que estoy intentando hacer es un drag de un Mesa(Qlabel) o Chef(Qlabel) y drop en otro Drop(Qlabel) creado previamente dentro del mapa. Sobrescribi el metodo dropEvent  en Drop(Qlabel) para que hiciera setPixmap sin embargo no se como identificar si fue Mesa(Qlabel) o Chef(Qlabel) desde el cual se hace el drag.

**Comment by Nicobuzeta** [comment]
Si no me equivoco, estas diciendo que ya pudiste hacer el drag and drop pero no sabes a que tipo de item pertenece el pixmap. Asumiendo que estas usando mimeData, puedes poner el tipo de tu drop en el texto del mimeData. De esta forma puedes leer el text para ver que tipo de objecto es.

**Comment by dcastillo5** [comment]
Sii Gracias!! 
Era eso
