### ISSUE TITLE
Más plazo para T02

### ISSUE THREAD

**Issue by Krmn390** [IIC2233/syllabus#929]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Hago esta issue cortita porque por lo menos en mi caso estoy segura de que no podré tener lista la tarea en el plazo estipulado. **¿Existe la opción de que nos den más plazo para esta tarea?**

**Comment by eliasbruchfeld** [comment]
comento para saber 👀

**Comment by aiarias** [comment]
x2 :(

**Comment by isvz** [comment]
x3

**Comment by aaossa** [comment]
Hola chiques,

Respondiendo a su duda directamente, en principio no habrá extensión de plazo para la T02. Sin embargo, les recuerdo que en caso de tener problemas personales o situaciones especiales en las que necesiten un apoyo de este tipo, pueden contactar a Tomás (jefe de bienestar, bienestar.iic2233@ing.puc.cl) o sus profes (nuestros correos están en la [página del curso](https://iic2233.github.io/)).

Sabemos que siempre pueden ocurrir situaciones imprevistas y que a veces necesitan una mano, y por eso desde el principio les transmitimos que tenemos los canales de comunicación que mencioné para que nos contacten. Créanme que preferimos que nos contacten por correo para poder conversar más fácilmente, ya que nos da una vía directa con ustedes. Por ahora cerraré la issue, ya que no trata directamente sobre la tarea (son para dudas de las evaluaciones, de contenidos, de instalación o administrativas, no para temas personales), pero les dejo la invitación a contactarnos en caso de que necesiten cualquier cosa. ¡Mucho ánimo y éxito con la tarea :sparkles:!

PS: Igual pueden contactarnos si están perdides con su tarea, cuenten con nosotres 🙏
