### ISSUE TITLE
Vida de edificios

### ISSUE THREAD

**Issue by Cschavez** [IIC2233/Syllabus#93]
Hola! en la tarea dice que cada edificio al ser creado entrega una cierta cantidad de vidas. Estas vidas se suman a las vidas de cada soldado o a la vida total del ejercito? Además, la cantidad de vidas del ejercito es la suma total de vidas de cada soldado o mago, no es cierto?

Muchas gracias !

**Comment by leolivares** [comment]
Al crear un edificio, este cuenta con su vida propia. Dicha vida no afecta la vida del ejercito.
Lee nuevamente la sección 7, y debería quedarte más claro (ambas preguntas).
Cualquier cosa pregunta nuevamente!

**Comment by leolivares** [comment]
Hola! @pcseisdedos 

1. Se refiere a la vida del ejercito como entidad (soldados y magos). Cuando llega a "0", significa que ya no hay ejercito.
2. Se refiere a dejar el planeta con todo al maximo. Poblacion y Edificios.

> ... deja el planeta con todas sus mejoras al máximo, todos sus edificios y con la población al máximo, para que te sea dificil recuperarlo.

Saludos!

**Comment by pcseisdedos** [comment]
ok, entonces los edificios nunca mueren? porque la batalla finaliza antes (yo tengo modelado que al ser atacado la vida se le resta directamente a los soldados, y si ya no quedan a los edificios, puede que no sea correcto)

**Comment by leolivares** [comment]
En el enunciado no se menciona nada de la vida de los edificios durante las batallas, por lo tanto no es necesario. #75 
El evento *Asteroide* es el que afectaría la vida de tus edificios.
