### ISSUE TITLE
Importar módulo dentro de módulo

### ISSUE THREAD

**Issue by akaminetzkyp** [IIC2233/Syllabus#93]
Hola!

Mi tarea necesita dos módulos (llamémoslos a y b) para funcionar. El módulo "a" necesita al módulo "b" para funcionar. Está bien si dentro del módulo "a" importo al módulo "b"? O no es recomendado hacer esto?

Busqué en internet pero no encontré una respuesta. :(

Saludos!

**Comment by sebacruzd** [comment]
Hola,

Está bien lo que mencionas, solo que si haces eso preocúpate de que no se ejecute nada en el módulo "b", ya que podrían intervenir en los resultados que esperas.
Para más información lee la respuesta que pusieron en el [issue 57](https://github.com/IIC2233/Syllabus/issues/57)

**Comment by akaminetzkyp** [comment]
Perfecto, gracias! 😄
