### ISSUE TITLE
Subí commit sin cambios 

### ISSUE THREAD

**Issue by Rafoxxa** [IIC2233/syllabus#93]
En el form subí un commit que hice de forma accidental (sin hacer cambios en mi código) después de ya haber subido todo en un commit que subí como 3 minutos antes. En ese caso se corregirá lo que subí 3 minutos antes o se considera como que no subí nada?

**Comment by entamburini** [comment]
¡Hola!

Se corrige el commit especificado en el form. Prima sobre el resto. Si quieres ver qué se corrige en ese commit, te recomiendo revisar en "Browse Files" y ver la carpeta T00, eso es lo que corregiremos :)
