### ISSUE TITLE
Pregunta sobre el funcionamiento del Commit de la T0

### ISSUE THREAD

**Issue by lsilvabw** [IIC2233/Syllabus#93]
Buenas noches, 
Me surgió una duda cuando mandaron el último email con el "commit" que se corregirá.
Yo hice solo dos commit, uno en el cual subí todos los archivos necesarios para la correcta ejecución del código y luego otro commit en donde actualice un solo archivo (flujo.py). Debido a que todos los otros archivos estaban bien no vi la necesidad de subir todos los demás archivos de nuevo. No se que pasa ahora, estoy medio perdido. Puedo especificar esto en el README?  para que consideren todos los archivos del commit:
"050b875fd16a8d9b7702a93e55f4cbef34e129e4"  (tarea o version desordenada)
excepto el el archivo "flujo.py" que fue subido posteriormente en el commit:
"c68962e73772e7ba79197f7a955870855d1d0534"   (flujo respetando pep8)

Que puedo hacer  ?

Agradecería mucho al ayuda, gracias.

Pd: mi pregunta es si es que van a considerar todos estos archivos a la hora de corregir o solo el que contiene el ultimo commit (flujo respetando pep8). 

[
![Screen Shot 2021-09-03 at 21 05 14](https://user-images.githubusercontent.com/89400260/132077544-73116397-6360-4899-8b85-d0ebb1c5b35c.png)
](url)

**Comment by maquiza** [comment]
Yo tengo la misma duda, me paso algo similar a ti. El último comió fue para actualizar una archivo y el anterior subí otros archivos que corresponden al programa. Me gustaría saber si consideran el último commit con el estado de la carpeta T0 del repositorio personal, o solo los archivos considerados en el último commit.

**Comment by Ferc28** [comment]
También tengo la misma duda.

**Comment by gatochico** [comment]
¡Hola! 

Cuando en la issue de la tarea se especifica el commit a revisar, esto significa que se revisará el estado de la carpeta /T0 de tu repositorio **hasta ese commit**. Es decir, todos los commits anteriores a ese deberían estar incluidos. 

Si quieren asegurarse de que se entregó todo lo que querían, pueden hacer click en el link del commit que aparece en la issue, y luego en la página que carga, apretar "Browse Files" y revisar la carpeta T0 del repositorio. En caso de que algo no se encuentre ahí, es que no se logró subir a tiempo y ahí deben llenar el formulario para entrega atrasada.

Saludos! Espero se entienda mi respuesta

**Comment by maquiza** [comment]
Ya, me queda claro. Gracias!!
