### ISSUE TITLE
Error SyntaxError: invalid syntax o <stdin>

### ISSUE THREAD

**Issue by franciscares** [IIC2233/syllabus#93]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ ]X Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Estaba corriendo mi código, no hice ningún cambio en el código, no cerré ni abrí un archivo. Lo hice correr nuevamente y Python me da este error:

& python c:/Users/franc/OneDrive/Escritorio/franciscares-iic2233-2021-1/Tareas/T0/prueba.py
  File "<stdin>", line 1
    & python c:/Users/franc/OneDrive/Escritorio/franciscares-iic2233-2021-1/Tareas/T0/prueba.py
    ^
SyntaxError: invalid syntax

**Comment by matiasmasjuan** [comment]
Hola @franciscares !

¿Cómo estas corriendo el código? ¿Qué visualizador de texto estás utilizando?

Saludos!

**Comment by franciscares** [comment]
Hola! Estoy usando vscode. Ya pude arreglarlo, gracias!
