### ISSUE TITLE
Duda .gitignore T00

### ISSUE THREAD

**Issue by CrisBerriosL** [IIC2233/syllabus#93]
Hola! Me nació una duda con respecto al archivo .gitignore que se nos recomienda crear para la tarea 00, ya que en el enunciado se indica que se recomienda ignorar archivos como el enunciado de la tarea, archivos que no sean pertinentes para el funcionamiento de la tarea, y los archivos indicados en la sección Archivos Entregados (tablero.py, parametros.py, puntajes.txt). Sin embargo estos últimos si son pertinentes para el funcionamiento de la tarea y se nos indica que debemos importarlos para utilizarlos correctamente en nuestro código. Entonces, ¿tenemos que ignorar estos archivos con .gitignore? ¿O no lo hacemos porque son si pertinentes para la tarea?

**Comment by YehudaGurovich** [comment]
Si agrego nuevos parametros entonces no coloco el parametros.py en el .gitignore o no coloco los nuevos parametros en el archivo de parametros.py?

**Comment by CrisBerriosL** [comment]
En el enunciado dice que no hay que modificar ni escribir código en ninguno de los 3 archivos entregados, asi que supongo que si uno quiere añadir nuevos parámetros hay que hacerlo en otro archivo.

**Comment by DCCollao** [comment]
@YehudaGurovich Cualquiera de las dos formas que mencionaste es válida, pero lo ideal es que lo menciones en tu `readme.md` para que el ayudante corrector se de cuenta de por qué no incluiste `parametros.py` en el `.gitignore`, o porqué creaste otro archivo teniendo ya `parametros.py`.

**Comment by ignaciomansuy** [comment]
¿Los archivos .gitignore.txt y .gitignore.wsp deben ser subidos al repositorio personal con git add, commit y push?

**Comment by DCCollao** [comment]
Solamente es necesario que suban el archivo `.gitignore`, pues `.gitignore.wsp` corresponde a un archivo generado por windows y no tiene que ver con la tarea ni los archivos.

Por otro lado, el archivo que mencionaste (`.gitignore.txt`) no tiene la extensión solicitada, pues le sobra el `.txt`.

**Comment by sbcorrea** [comment]
> @YehudaGurovich Cualquiera de las dos formas que mencionaste es válida, pero lo ideal es que lo menciones en tu `readme.md` para que el ayudante corrector se de cuenta de por qué no incluiste `parametros.py` en el `.gitignore`, o porqué creaste otro archivo teniendo ya `parametros.py`.
Hola! Si lo indico hiperclaro al principio y a lo largo del ReadMe (letras grandes y coloridas si es necesario), se vale cambiar y/o renombrar `parametros.py`? Subiéndolo a mi repo, claro...

**Comment by DCCollao** [comment]
¿Cuál sería el motivo? 👀

**Comment by sbcorrea** [comment]
Jejeee, como decidí escribir el programa completo en inglés, parametricé la configuración de idioma para el juego, almacenando todos los strings en un modulo llamado `espanol`. Por lo tanto, en `parametros`, necesito `import espanol as lang`. Además, como todo mi código está en inglés, me gustaría llamar al archivo `parameters.py` para que no genere confusiones a la hora de acceder a ellos.

**Comment by sbcorrea** [comment]
De hecho, si no es mucho problema me encantaría renombrar `puntajes.py` y `tablero.py` como `scores.py` y `board.py`, pero eso ya sería solo por manía de orden, porque no los voy a cambiar internamente, jajaja

**Comment by sbcorrea** [comment]
Ya hay borradores de todos mis módulos y de mi ReadMe subidos a mi repo personal, así que se puede revisar ahí si quieren entender viendo 😄

**Comment by DCCollao** [comment]
Hola @sbcorrea!
Luego de conversarlo un rato, llegamos a la conclusión de que es mejor que mantengas el nombre de todos los archivos y variables/constantes que te entregamos. Esto porque podría aumentar la dificultad de corrección en caso de encontrarnos con algún error.

**Comment by sbcorrea** [comment]
Okaa, gracias!

**Comment by Benja-c** [comment]
Hola los archivos pycache se agregan al gitignore o no es necesario?

**Comment by DCCollao** [comment]
Todo archivo que no sea necesario para la ejecución de tu tarea, además de los que pedimos nosotros por enunciado, debería estar incluido en el `.gitignore`
