### ISSUE TITLE
Match parcial

### ISSUE THREAD

**Issue by mesantamaria** [IIC2233/Syllabus#93]
Hola,

qué pasa con el resto de una order al tener un match parcial? Me refiero a que cuando una order tiene un match parcial, hay una parte que no es vendida todavía. Se debe crear una nueva order (con otro id) con esa información y restarle a la antigua lo que no se vendió?

**Comment by sebacruzd** [comment]
Hola, lo del id depende de ti, pero la prioridad (por la fecha/ hora de inicio de la orden) debe permanecer.
Hazlo pensando en los match que deben quedar guardados. 
Tip: Es más fácil/ mejor que un id este en más de un match o que solo pertenezca a uno?
