### ISSUE TITLE
Duda sobre el metodo comprar_bebestible() de la clase Jugador

### ISSUE THREAD

**Issue by SVenegasA** [IIC2233/Syllabus#93]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

A mí en el enunciado no me quedó nada claro si al momento en que el jugador decide comprar un bebestible este se debe tomar automáticamente o guardarlo como en un "inventario". Supongo que es automático porque si no, lógicamente el Jugador tendría un atributo llamado "bebestibles" pero me gustaría que alguien me lo aclarara

**Comment by Gsalinas1506** [comment]
Efectivamente. Si tienes dinero suficiente, al comprar un bebestible este se consume automáticamente y se aplican sus efectos

Éxito con la tarea! 🎲️🃏️
