### ISSUE TITLE
Duda caracteres maximos

### ISSUE THREAD

**Issue by solebravo** [IIC2233/Syllabus#93]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola! tenia una duda sobre los caracteres máximos que se pueden ocupar por formato en la tarea. Lo que pasa es que en un parte de mi código llamo a una función que recibe 5 parámetros y como tienen que tener nombres descriptivos me genera pasarme de los 100 caracteres (10 caracteres), entonces quería saber como era la penalización para eso o si no es tan estricto.
Gracias de antemano

**Comment by Emiliax16** [comment]
Hola @solebravo . Efectivamente hay descuento asociado por tener más de 100 caracteres por líneas, ya que es una buena práctica no superar este número. Hay maneras de manejar esto: en las funciones simplemente puedes escribir algunos parametros en una segunda línea y si tienes variables o condiciones, puedes agregar el caracter `\` para indicar que seguirás escribiendo en una segunda línea. Te dejo un ejemplo:
`def alguna_cosa(parametro1, parametro2, parametro3,`
`. . . . . parametro4):`
`. . . . . variable_1 = 'asdfghjkqweruhsdufhduhsdufhdsufhdf' + \`
`. . . . . 'hola'`
`. . . . . print(variable_1)`

Espero te sirva. Saludos!
