### ISSUE TITLE
Grupo Telegram

### ISSUE THREAD

**Issue by tedroppelmann** [IIC2233/syllabus#93]
Hola. Hace unos días creo que leí que existía un grupo de Telegram del curso, pero ahora no encuentro la info. Si alguien sabe algo sería de mucha ayuda!

**Comment by entamburini** [comment]
Yo se algo pero no wa decir 🤭🤭

**Comment by entamburini** [comment]
Nah, mentira. Creamos un canal de avisos donde se notifica cuando una issue es importante :) 

Si quieren unirse, pueden [apretar todo esto incluso el emoji 🚀 ](https://t.me/joinchat/AAAAAEdkHtwbL4MqHntSLw)
