### ISSUE TITLE
Inicializar atributos con None ¿Mala practica?

### ISSUE THREAD

**Issue by Jamesmoreno21** [IIC2233/syllabus#930]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola! Tengo una duda puntual, pues me pasa que no sé si inicializar atributos inicialmente con **None** es considerada mala práctica, o si sería correcto hacer un parámetro para cada atributo que parta en None (esto ultimo si encuentro que seria tedioso si 😕)

De antemano gracias! 😃

**Comment by manearaya** [comment]
Hola @Jamesmoreno21!

Inicializar atributos con None no se considera una mala práctica, pero debes tener cuidado con que no queden en None para que los puedas usar 😅 (es decir, que les asignes el valor correspondiente después).

Además te recuerdo que **cualquier path o valor constante debe ir como parámetro** de todas formas.

Éxito con la tarea!

**Comment by denisseleiva** [comment]
Holaa @manearaya 
Eso de **cualquier path o valor constante debe ir como parámetro** incluye a los valores de setGeometry() de las ventanas o de move() o resize() o eso no lo tengo que incluir?. Con respecto a lo mismo, en la pista de baile si quiero restringir el drop para límites en eje x y eje y, esos también los debo incluir en parámetros.py? 😅

**Comment by manearaya** [comment]
Sí deberías incluir esos valores, pero puedes asumir que esos no van a ser modificados al momento de corregir tu tarea (todos los valores que tengan que ver con paths o dimensiones de la ventana no van a ser modificados).

**Comment by denisseleiva** [comment]
@manearaya pero no van a ser demasiados parámetros? Porque considerando lo que me dices por cada label que tengo (o sea miles jajjajaj) tendría que parametrizar sus dimensiones 😥

**Comment by manearaya** [comment]
Sí deben ir 😅 pero para ahorrarte líneas podrías usar diccionarios para guardar los parámetros que mencionas (que también deben estar en ESTE_FORMATO).
