### ISSUE TITLE
Guardar Partida

### ISSUE THREAD

**Issue by felipefuentesporras** [IIC2233/syllabus#931]
Al leer el enunciado se menciona que se deben sobrescribir los datos al crear un nueva partida, pero la única instancia que dan para guardar partida es en el botón guardar de la ventana post ronda. Por tanto, si es que parto una partido nueva y juego varias rondas, y no guardo en la post ronda en ni un momento, entonces al volver a entrar al DCCafe y poner seguir jugando ¿debería jugar la partida anterior a esta?

De igual forma, si por ejemplo juego 1 ronda en una partida y guardo en la post ronda, y despues juego 2 rondas más, pero nunca guardo, al volver a entrar y seguir partida ¿debería cargar la partida de la ultima ronda que guarde?

**Comment by tomasgv** [comment]
Hola @felipefuentesporras !!

Como se menciona en la _issue_ #881, deberás sobrescribir estos datos al crear una nueva partida y al cargar una existente. Esto implica que la partida previamente guardada se sobrescribe al momento de crear una nueva.

Saludos! ☕ 🐱
