### ISSUE TITLE
Error - QThread: Destroyed while thread is still running

### ISSUE THREAD

**Issue by kalarconvl** [IIC2233/syllabus#931]
_Originally posted by @danckoo1 in https://github.com/IIC2233/syllabus/issues/750#issuecomment-713274754_

Hola!! Ayer agregué unas funciones a mi código y me empezó a salir el problema ```QThread: Destroyed while thread is still running``` que corta el flujo del programa y ni idea por qué empezó a salir. Pero es solo a veces, no cada vez que corre entonces no sé qué hacer. Leí la issue #750 y sí tengo una lista que guarda los Threads, cómo más se podrá solucionar?

**Comment by aaossa** [comment]
Hola @kalarconvl , creo que lo que ocurre es que tus `QThread` no tienen el mismo "ciclo de vida" que su *parent*. En tu caso, para arreglarlo debes asegurarte de pasarle el *parent* a través del `super`: `super().__init__(self). ¿Podrías probar y me dices si te funciona? ¡Éxito con la T02 ✨!

**Comment by kalarconvl** [comment]
Hola @aaossa ! Gracias! Puse parent como me dices y funciona y espero no me vuelva a salir ese error. Eso sí, ahora si pongo salir y volver a jugar me empiezan a salir cada vez más flechas por nivel jajaja todavía no pongo opción para que salgan más de 2 flechas por vez y me salen 4 o 5 ni idea por quee

**Comment by aaossa** [comment]
Mmm eso podría ser porque en tu método `salir` no estás terminando el `QTimer` en `timer_flechas` (en `Juego`). Puede ser que ese `QTimer` siga generando flechas una vez que vuelves al juego. Avísame si te funciona cambiándolo 🤔 Otra cosa: por alguna razón no veo tus flechas, incluso cuando moví los *sprites*, ¿estás usando unos *sprites* tuyos? Si es así, recuerda agregarlos ✨

**Comment by kalarconvl** [comment]
Sobre los sprites, estoy usando los que entregaron con el enunciado! Quizás es porque los tengo dentro de la carpeta frontend?

**Comment by aaossa** [comment]
Uhh ya, recuerda agregar en tu README dónde van los *sprites* (admito que no miré tu README, así que si ya lo anotaste, bacán 👌)

**Comment by kalarconvl** [comment]
Noo todavía no hago el README, tengo pendiente ponerlo! Y sobre lo de antes, si tengo implementado timer.stop() para el timer de las flechas para cuando sale 🤔 Las señales se pueden conectar a más de una función?

**Comment by kalarconvl** [comment]
Ahí creo que pillé el error, estaba definiendo los timers en el init del backend de la ventana de juego. Ahora los cambié a comenzar ronda y ya no pasa que salen más flechas. Será que se estaba crenaod un timer nuevo cada vez que se ponía comenzar?

**Comment by aaossa** [comment]
> Noo todavía no hago el README, tengo pendiente ponerlo! Y sobre lo de antes, si tengo implementado timer.stop() para el timer de las flechas para cuando sale 🤔 Las señales se pueden conectar a más de una función?

Sip, puedes conectar más de una función a una señal, simplemente tienes que hacer `connect` de nuevo 👌 

> Ahí creo que pillé el error, estaba definiendo los timers en el init del backend de la ventana de juego. Ahora los cambié a comenzar ronda y ya no pasa que salen más flechas. Será que se estaba creando un timer nuevo cada vez que se ponía comenzar?

Por lo que me explicas, parece que así es 🤔 Buen descubrimiento ✨ Esas cosas cuesta pillarlas pero así mismo vas conociendo tu código 🤓 

Avísame si estás OK con esta *issue*, creo que vas por buen camino 😊 ¡Ánimo y éxito con la tarea!

**Comment by kalarconvl** [comment]
Sii estoy ok 😄 Gracias!
