### ISSUE TITLE
Join en QThread

### ISSUE THREAD

**Issue by iastruque** [IIC2233/syllabus#932]
Necesito hacer un join, pero al pareces no esta implementado en QThread.
Lo que necesito hacer es que mi último cliente que inicio (start()) siga funcionando antes de que mi QThread principal termine su ejecución. 
En otras palabras, necesito que el thread princpal espere a que el último thread de cliente acabé

**Comment by Nicobuzeta** [comment]
Puedes usar `wait()`
https://doc.qt.io/qt-5/qthread.html#wait
```
cliente = QThread()
...
cliente.wait()
```

**Comment by Alonsinho1** [comment]
Hola!

La unica forma de que el main thread termine en esta tarea es si literalmente cierras todas kas ventanas, asi que el uso de join seria redundante.

Suerte!
