### ISSUE TITLE
Como concatenar un parametro de una función con un parámetro de otro archivo

### ISSUE THREAD

**Issue by Natydlb** [IIC2233/syllabus#933]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola! tengo una duda de como concatenar las siguientes cosas por ejemplo:

import parametros as p 

def hola(self, numero):
  ruta = p.Parametro_{numero}

suponiendo que numero es un numero x y que el Parámetro_x si existe

**Comment by aljara97** [comment]
Hola,  podrías probar importar un diccionario desde parámetros cuya key sea el atributo número que le entregas a la función.

Espero haberte ayudado, coméntame cómo te va
