### ISSUE TITLE
Dinero negativo

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#933]
Hola!
Qué pasa si el dinero llega a un valor donde si comprar un objeto, éste podría quedar negativo? No debería efectuarse la comprar? O puede quedar con un dinero negativo?

**Comment by jitorcas** [comment]
Hola @Camila-sty!

No debería efectuarse la compra, el DCCafé **no puede quedar con saldo negativo**. 

Saludos 💯

**Comment by dsepulveda3** [comment]
Cuanto cuesta cada mesa ? Eso lo debo poner en parametros como valor_mesa?? Estoy leyendo la tarea y no lo encuentro

**Comment by lily416** [comment]
@dsepulveda3 sí, debes definir el valor como un parámetro. Muchas veces hay parámetros que no son explícitos o que ustedes deberán crear debido a la forma en que funciona su código.

Saludos y éxito en la tarea 👋🍩
