### ISSUE TITLE
Error al llamar a una función

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#934]
Hola. Resulta que al llamar a una función determinada de otro módulo, me arroja un error que no entiendo por qué sucede:
![image](https://user-images.githubusercontent.com/59337116/83606786-25492380-a548-11ea-8236-8b1954cfbcd3.png)
Se supone que la función ```actualizar_archivo_datos()``` recibe un diccionario. Entonces yo en el módulo respectivo importe esta función que quiero utilizar y la llamo como ```actualizar_archivo_datos(dicc_datos)```.
Por qué podría suceder el error que me sale?

**Comment by kadroguett** [comment]
Hola @Camila-sty 
Puedes mostrarme una imagen de cómo definiste la función ?

**Comment by Camila-sty** [comment]
Mira, la función se encuentra en un módulo x1, pero no está dentro de ninguna clase. Es directamente una función llamada como mencioné anteriormente. 
Entonces, yo importo esta función en otro módulo x2 (tal cual con su nombre de función) . Pero en este módulo, yo llamo a esta función dentro del método de una clase de mi fronted. Y la llamo: ```actualizar_archivo_datos(dicc_datos)```. Donde ```dicc_datos```. es un diccionario.
Eso es lo que hago...

**Comment by Camila-sty** [comment]
Mi duda es que si el error de cómo estoy llamando a la función? O , que quizás dentro de esa función haya un error... ?

**Comment by kadroguett** [comment]
Si entiendo, quería asegurarme de que le habías agregado el (dicc_datos) al crear la función. De casualidad no tienes otra función con el mismo nombre en el módulo x2?

**Comment by Camila-sty** [comment]
> Si entiendo, quería asegurarme de que le habías agregado el (dicc_datos) al crear la función. De casualidad no tienes otra función con el mismo nombre en el módulo x2?
Yo verifiqué eso también. Pero si le estoy enviando el diccionario. 
No. La función ```actualizar_archivo_datos(dicc_datos)``` existe solo en el módulo x1, y no hay otra igual en el módulo x2

**Comment by kadroguett** [comment]
No me refería a si se lo estabas enviando, sino que al momento de crearla lo hicieras con `act_datos(diccio)` en lugar de `ac_datos()`
Pero si no es ninguna de esas opciones me ayudaría mucho ver tu código, podrías hacer un push cuando actualice tu computador? Por favor

**Comment by Camila-sty** [comment]
Existe una parecida que es ```actualizar_archivo_mapa(dicc_datos)```.
Pero no creo que influya 🤔

**Comment by Camila-sty** [comment]
@kadroguett ok. Te aviso cuando lo haga. Gracias!

**Comment by kadroguett** [comment]
@Camila-sty no sé si lo modificaste pero estuve revisando tu `archivo.py` y me fijé que como te mencionaba anteriormente, al crear la función no le agregas la variable que quieres pasarle, por eso te aparece ese error
![Screenshot_20200603-035930](https://user-images.githubusercontent.com/31357861/83611253-b4f1d080-a54e-11ea-894a-e765b95b6923.png)

**Comment by Camila-sty** [comment]
@kadroguett . Igual He cambiado el código después de ese push. Así que ahora lo actualicé. Pero ahora, sí recibe ese parámetro.

**Comment by Camila-sty** [comment]
Ah. Ya encontré el error. Por eso me parecía raro que vieras esa función. Lo que pasa es que efectivamente hay dos funciones que se llaman así, pero e el mismo módulo ```archivo.py``` .
Gracias gracias

**Comment by kadroguett** [comment]
Buena, de nada y éxtio en tu tarea!!
