### ISSUE TITLE
Finalizar ronda con trampa

### ISSUE THREAD

**Issue by felipefuentesporras** [IIC2233/syllabus#935]
Al finalizar la ronda con F+I+N, que pasa con la ¿reputación del local?, ¿se debe mantener?
Por que el problema que tengo es que si parto una ronda y la termino antes de que venga cualquier cliente, en la formula para calcularla reputación me queda un división tipo 0/0 y me tira un error

**Comment by jitorcas** [comment]
Hola @felipefuentesporras 

Al ser un caso especifico, lo puedes dejar a tu criterio la manera en que lo soluciones, siempre y cuando no influya ni contradiga el enunciado. 
Podrías tener un *check point* antes de pasar por la fórmula y atrapar el caso especial que estás viendo. 
**Recuerda mencionarlo en tu README y citar esta issue**
