### ISSUE TITLE
[Threads] [GUI] Problema para guardar el nombre

### ISSUE THREAD

**Issue by nimorales97** [IIC2233/syllabus#935]
### Prerrequisitos

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hice una clase **DCCumbia(Thread)** que represente al juego por así decirlo, y quiero que tenga un atributo `self.nombre` el cual saca su valor del input que pones en la ventana de inicio. A grandes razgos es esto: **Abres la ventana de inicio, escribes un nombre válido y al clickear en 'Comenzar' se actualiza self.nombre, se abre la ventana de preparacion e inicia el thread.**
La funcion de `VentanaInicio` que se activa con el clic es así:
```
def comenzar_juego(self):
    aux_nombre = self.input.text() #input es el nombre del QLineEdit

    if no es válido:
        ...

    elif self.senal_comenzar:
        ...
        self.nombre = aux_nombre # en el __init__ estaba: self.nombre = None
        self.senal_comenzar.emit()
        self.hide()
```
Estoy intentando hacer esto para que el thread capture el `ventata_inicio.nombre`:
```
if __name__ == '__main__':
    ...
    ventana_inicio = VentanaInicio()
    ...
    Inicio.senal_comenzar = Preparacion.senal_abrirse
    if (Inicio.senal_comenzar):
        aux_nombre = ventana_inicio.input.text()
        print(aux_nombre)
        juego = DCCumbia(aux_nombre)
        juego.start()
    sys.exit(app.exec_())

```
Y esta es mi clase DCCumbia:
```
class DCCumbia(Thread):

    def __init__(self, nombre):
        super().__init__()
        self.nombre = nombre
    
    def run(self):
        print(f'Mi nombre es {self.nombre}')
```
Pero no lo captura :c lo sé porque el print me retorna solo `Mi nombre es`
**Qué debo hacer para que lo capture?**

**Comment by furcelay** [comment]
Hola @nimorales97 !

Lo que me parece que ocurre es que cuando a la `VentanaInicio` emite la `senal_comenzar` la clase `DCCumbia` ya se ha inicializado con lo que había en `input` antes de que ingrese el nombre. Esto pasa porque las condiciones `if Inicio.senal_comenzar` y `elif self.senal_comenzar` siempre son verdaderas (la conversión a *bool* de los objetos es `True` siempore que no sea un objeto vacío, en este caso sería `False` solo si fuesen `None`), entonces el programa instancia `DCCumbia` de inmediato y no espera a que se reciba el input.

Como comentario, en la lógica de programación no lineal de GUI lo ideal es que en `main` las ventanas se inicialicen de inmediato y se conecten las señales y no hayan condiciones que impidan inicializar una u otra ventana (eso iría con la lógica de programación lineal), y que toda la información sea por señales. Para tu caso puedes hacer una pequeña variación en tus señales para lograr lo que buscas sin que la información se pase por `main`.

Saludos! 😄

**Comment by nimorales97** [comment]
Hola!
Primero que nada muchas gracias, ya pensaba que nadie me iba a responder 😓 Ahora me hace sentido lo que ocurre.
Respecto al comentario, ¿Podrías explicarme un poco más? Que no sé si lo entendí

**Comment by furcelay** [comment]
Lo que estás haciendo en tu programa es impedir que ```DCCumbia``` se inicialice hasta que el usuario ingrese un nombre, para el caso de esta tarea eso funcionaría pero no es lo ideal para escalar el programa (por ejemplo para la T03 eso sí sería un problema). Lo que podrías hacer es que la misma señal que se envía desde la ventana de inicio a ```DCCumbia``` transporte la información que se recibió en esa ventana (en vez de una señal vacía), de ese modo la comunicación es directa y no necesitas impedir que se inicialice.

**Comment by nimorales97** [comment]
Es que no entiendo cómo hacerlo:/ he estado buscando en los contenidos y en internet y no sé si estaré buscando mal o algo pero no sé cómo transmitir un valor string (en este caso el nombre) por una señal (que por lo que entiendo es eso lo que estoy haciendo)

**Comment by furcelay** [comment]
Te recomiendo revisar los contenidos de la [semana 09](https://github.com/IIC2233/contenidos/blob/master/semana-09/3-eventos-y-se%C3%B1ales.ipynb), en particular el ítem **Emisión de eventos con información**, ahí está explicado mejor de lo que podría hacerlo yo 😅 , fíjate en cuando se crea la señal, hay que darle el tipo de valor que transmite, y luego se envía en el `emit` y va a entrar como argumento en la función que lo recibe.
