### ISSUE TITLE
Presidente aparicion

### ISSUE THREAD

**Issue by felipefuentesporras** [IIC2233/syllabus#936]
En el enunciado se dice que tiene que el cliente tiene un 10% de aparecer en una ronda. Dice tambien que debe ser tratado como otro cliente, pero no me queda claro en que momento llega el presidente.
¿Puede llegar junto con un cliente normal?
¿Debe respetar el parametro LLEGADA_CLIENTE?
¿Se cuenta como un cliente extra o esta dentro del numero de clientes esperados en esa ronda?

**Comment by jitorcas** [comment]
Hola!

Tal como dice el enunciado *"un cliente puede aparecer cada `LLEGADA_CLIENTE`"*, a diferencia del presidente que *"La probabilidad de que aparezca **en una nueva ronda** es 10 por ciento"*. 
Por lo tanto, esa es la única diferencia entre ambos tipos de clientes. 
Con respecto a que se cuenta como un cliente extra te respondo en algunas horas más, sin embargo al no estar especifico podrías dejarlo a tu criterio. (Pero espera a la respuesta definitiva)

**Comment by jitorcas** [comment]
@felipefuentesporras 

Hay dos maneras de implementar el bonus del presidente, debes elegir la que más te acomode. 

1. Que la probabilidad de aparición esté ligada a la llegada del cliente al *DCCafé*, esto quiere decir que cada vez que llegue un cliente, este tendrá 10 por ciento de probabilidad de que sea el presidente. Ojo, que si se cumple la probabilidad debes bloquear esa funcionalidad ya que el presidente **solo aparece una vez por ronda**. Bajo este criterio, el presidente si contaría en la cantidad de clientes por ronda.

2. Que la probabilidad de aparición del presidente sea calculada al comienzo de cada ronda, y de cumplirse **tu decides en qué momento aparece el presidente**. Bajo este criterio el presidente podría o no contar en la cantidad de clientes por ronda, quedaría a tu criterio. 

Cualquiera de las dos opciones que elijas **debes** especificarla en tu README y describir el proceso. 
También recuerda que la probabilidad está puesta con un número en azul, lo que representa un parámetro y debe estar implementado como tal. 

Espero te haya quedado claro! 
Saludos y éxito 💯

**Comment by felipefuentesporras** [comment]
Me quedo muy claro, gracias
