### ISSUE TITLE
duda sobre atributo en clase

### ISSUE THREAD

**Issue by aayale** [IIC2233/syllabus#937]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido
Hola, estoy creando una clase y creo también como atributo un contador (para usarlo en un método después), lo escribo de esta forma

     class Clase(self):
           def __init__(self):
                self.contador = 0
                ...

El problema es que cuando lo uso en un método me sale el siguiente error: **'Clase' object has no attribute 'contador'**. Y no sé porque se produce esto (por consiguiente, no se como solucionarlo)

**Comment by aljara97** [comment]
Hola, podrías comentar la línea en que llamas a este atributo?

**Comment by aayale** [comment]
self.contador += 1

literalmente es solo eso:(

**Comment by aljara97** [comment]
Probablemente puede ser un problema con la identación de tu código, te recomiendo revisar si es que mezclaste tabs y espacios. También puede ser que estés llamando al atributo en un método fuera de la clase y por alguna razón se crea una inconsistencia, trata de revisar esto y si no puedes solucionarlo me comentas.

Mucha suerte 🐧
