### ISSUE TITLE
Error Thread

### ISSUE THREAD

**Issue by Juampisaez** [IIC2233/syllabus#937]
Hola tengo un problema, cada vez que corro mi codigo me tira el siguiente error
![image](https://user-images.githubusercontent.com/48323752/83649131-dc639000-a584-11ea-9d5d-540eba70c8d7.png)
La verdad es que no se porque ocurre, lo que si se es que ocurre cuando trato de iniciar un thread del chef, mientras otros dos threads estan en ejecucion.
Esto no ocurre siempre, no se porque. De repente funciona y aveces no

**Comment by kadroguett** [comment]
Hola @Juampisaez 
Me puedes mostrar cómo definiste el Qthread por favor

**Comment by Juampisaez** [comment]
![image](https://user-images.githubusercontent.com/48323752/83658752-a0cec300-a590-11ea-9232-fab5b599d16b.png)
![image](https://user-images.githubusercontent.com/48323752/83658837-bf34be80-a590-11ea-89ad-8159b139ab91.png)

**Comment by Juampisaez** [comment]
subi el codigo a mi repositorio, tal vez eso sea de mas ayuda

**Comment by kadroguett** [comment]
Prueba definiendo chef como self.chef
![Screenshot_20200603-115824](https://user-images.githubusercontent.com/31357861/83659488-9b25ad00-a591-11ea-81cc-d083cd15d802.png)

**Comment by Juampisaez** [comment]
por ahora funciona
