### ISSUE TITLE
Cambio nombres parámetros 

### ISSUE THREAD

**Issue by mariovaldesa** [IIC2233/syllabus#938]
Hola! Si tengo distintos nombres en los parámetros a los que salen en el enunciado importa? Igual se entienden... por ejemplo en vez de PLATOS_INTERMEDIOS tengo PLATOS_NIVEL_2

**Comment by jbulness** [comment]
Hola @mariovaldesa,

No importa que uses distintos nombres que los pedidos en el enunciado, siempre y cuando se entiendan y vengan señalados en el `README` los parámetros a los que les cambiaste el nombre y por cual se los cambiaste.
