### ISSUE TITLE
Labels creados no se visualizan

### ISSUE THREAD

**Issue by jorge-ovalle** [IIC2233/syllabus#939]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by jorge-ovalle** [comment]
Hola! Estoy creando labels para contener a los pingüinos, pero por alguna razón no se visualizan. He probado con label.show() y label.raise_(), pero nada :( . Los labels los defino en ventana_juego.py del frontend. Ya está todo en el repo.

**Comment by furcelay** [comment]
Hola @jorge-ovalle !

El problema es solamente que en las rutas a los *sprites* en tus parámetros tienes *pinquirines* en vez de *pinguirines*, cambiando el nombre se visualizan correctamente.

Saludos!

**Comment by jorge-ovalle** [comment]
Que pavo jaja. Muchas gracias!!
