### ISSUE TITLE
Import Loop Error

### ISSUE THREAD

**Issue by CataSudo** [IIC2233/syllabus#939]
Hola, debido a que post-ronda tiene un cierto loop al ser llamado tipo ventana principal - ventana post ronda - ventana principal, estoy teniendo problemas importando ventana post ronda en mi ventana principal ya que la importe en mi ventana post ronda. Hay alguna forma de arreglar este tipo de error? Me aparece ImportErrror. Entiendo que el error surge por este "loop", pero no entiendo como arreglarlo. 
<img width="891" alt="Screen Shot 2020-06-03 at 11 18 48" src="https://user-images.githubusercontent.com/62016215/83655134-079dad80-a58c-11ea-83b8-93072f5abe40.png">

**Comment by Alonsinho1** [comment]
Hola!

Podrias detallar un poco mas a profundidad el problema (Como esta siendo llamadas las funciones de PostRound y donde?

Pero tal como dices, el problema surge ya que el modulo_1 improta el modulo_2 y el modulo_2 importa al modulo_1, entonces queda en un loop infinito de improts. La forma de arreglar esto es que solo uno importe al otro. 

Lo que deberias hacer es utilizar señales para la comunicacion entre estos modulos y que la señal active una funcion del otro modulo

**Comment by CataSudo** [comment]
Si, acabo de actualizar mi repositorio! El problema esta en el main_window.py y post_round.py.
Estoy intentando connectar estos similar a la linea 59 en post_round.py, sin ser un button, sino solamente llamarlo en la linea 48 de mi main_window cuando acabe la ronda.

**Comment by Alonsinho1** [comment]
Ya le voy a echar una mirada en un ratito! y te repondo

**Comment by Alonsinho1** [comment]
No pude encontrar donde estabas haciendo los dos imports :c.

Pero tal como te dije si necesitas hacer import en los dos modulos, hay un problema de modelacion, siempre lo mas facil es utilizar señales que conecten metodos entre estos dos modulos y despues en un main.py los juntas
