### ISSUE TITLE
Tipo de los IDs

### ISSUE THREAD

**Issue by akaminetzkyp** [IIC2233/Syllabus#94]
Hola!

Todos los IDs en los archivos csv de la tarea son números. Sin embargo, arriba dice que son strings. Podemos suponer que los IDs siempre van a ser números, y nunca letras?

Saludos!

**Comment by sebacruzd** [comment]
No, no debes asumirlo, por lo que debes hacer tu programa pensando en que el ID puede tener letras.

**Comment by akaminetzkyp** [comment]
Perfecto, gracias!
