### ISSUE TITLE
Currencies

### ISSUE THREAD

**Issue by mmsaavedra1** [IIC2233/Syllabus#94]
En el enunciado menciona que cada usuario pide un balance de sus currencies.

¿A que se refiere dicho balance, y como puedo interpretar una currency, qué es?

**Comment by sebacruzd** [comment]
La una currency es cualquier tipo de moneda que pueda tener, ya sea CLP, NEBC, DCC, etc. Por lo que se debe mostrar cuánto se tiene de cada una.
Para ver lo del balance, revisa el issue #56
