### ISSUE TITLE
Duda sobre error: 'int' object is not subscriptable

### ISSUE THREAD

**Issue by czsanchez** [IIC2233/Syllabus#94]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/21)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/20)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Mi duda es que estaba creando una función en un módulo nuevo y al ejecutarlo en el archivo principal me sale el TypeError: 'int' object is not subscriptable. Más que nada me causa curiosidad porque según yo sí debería funcionar ya que bomba, lo que está intentando ser localizado con el índice sí es una lista y debería tomarla. No sé si es un problema mío de comprensión o simplemente hay algo raro que me está haciendo fallar.
El flujo es que bombas inicialmente es una lista de listas, y, por lo tanto, al meter el for con for bomba in bombas, bomba sería consecuentemente, una lista. Intenté imprimirlo para ver si realmente era un int y no una lista pero no y se me hace muy raro :(, pero realmente no encuentro como poder solucionarlo.
Adjunto foto de un extracto de mi código.

![image](https://user-images.githubusercontent.com/127255444/227796251-2a3b8dcf-db9c-447c-bd7d-703f10102e3a.png)

**Comment by franciscares** [comment]
Hola! Recuerda no subir código a las issues 😉

**Comment by Hernan4444** [comment]
Hola @czsanchez 

A priori, solo me la jugaría con que dentro de tu lista de `bombas` se pasó algun `int` en vez de una lista. O bien, que en algúna parte de modifica dicha lista por accidente, cambiando algún elemento dentro de ella por un `int`. Si todavía tienes el error, por favor subir el código e indicar como replicar dicho error para poder buscar la solución

Saludos c:
