### ISSUE TITLE
Edificos de partidas anteriores

### ISSUE THREAD

**Issue by JoaquinBurgos** [IIC2233/syllabus#94]
Si quiero cargar una partida anterior, como se que hp tienen los edificos ya construidos? por ejemplo si en la partida cargada ya me atacaron el cuartel donde se especifica con que hp quedo?

**Comment by jeschuwirth** [comment]
Saludos, 

En la issue #47 se habla del tema, lee la pregunta del alumno y la respuesta del ayudante.

Ojalá te sirva, sino comenta en esta issue cual parte no te quedó clara.

Suerte!
