### ISSUE TITLE
Dudas con testcase "est_llama_recorrer_clases_padres" en la actividad 1

### ISSUE THREAD

**Issue by anticarasosman** [IIC2233/Syllabus#94]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [ X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [ X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda.

### Duda

Estoy teniendo problemas descifrando lo que uno de los testcase esta revisando, específicamente
 "test_llama_recorrer_clases_padres" y "test_llama_recorrer_clases_padres2, los cuales me retornan: Expected: recorrer(<clases.FaitHibrido object at 0x7f6dda20b2b0>, 6.0)
Actual: recorrer(12) y Expected: recorrer(<clases.FaitHibrido object at 0x7f6dda1db430>, 5.0)
Actual: recorrer(10)" respectivamente. Intente revisar el archivo de test.py o entender mas acerca de lo que son los mock pero eso no me ayudo **¿Qué es lo que esos test cases me están indicando que estoy haciendo mal?**

![imagen_2023-08-27_142420399](https://github.com/IIC2233/Syllabus/assets/94928628/cd836fcc-47ea-4ab3-82ed-5a2091f51a80)

**Comment by Anehg** [comment]
me pasó lo mismo y creo que tiene que ver con la herencia, de hecho me pasa que se guardan mal los atributos en la clase creada
![image](https://github.com/IIC2233/Syllabus/assets/141879188/3e254716-b893-48f0-ad3e-1a8a66524255)

![ubuntu](https://github.com/IIC2233/Syllabus/assets/141879188/f0528db5-1e3d-4445-9c35-b8ae04de4d79)

como se ve en la imagen cree auto de clase faithibrido con por ejemplo rendimiento 7 y luego printeo el rendimiento y me da 95 que es el int que le asigne al atributo de bencina_favorita

**Comment by Anehg** [comment]
A mi me paso lo mismo y probablemente te suceda porque estas llamando a la funcion recorrer de los padres y les falta un metodo  (recuerda que al llamar a los metodos de los padres tienes que llamarlos con el metodo self + los que necesiten)

**Comment by anticarasosman** [comment]
> A mi me paso lo mismo y probablemente te suceda porque estas llamando a la funcion recorrer de los padres y les falta un metodo (recuerda que al llamar a los metodos de los padres tienes que llamarlos con el metodo self + los que necesiten)

Perdona a que te refieres con lo de llamarlos con "el metodo self + los que necesiten"?

**Comment by Anehg** [comment]
Por ejemplo para el metodo recorrer poner:
vehiculo_(electrico o bencina).recorrer(self,kilómetros)

**Comment by anticarasosman** [comment]
Eso tampoco era, lo que me confunde es que la función recorrer la escribí de la misma manera en la clase Telsa y el test case de recorrer las clases padres de Telsa si pasan.
