### ISSUE TITLE
Uso de try/except

### ISSUE THREAD

**Issue by Clemente24** [IIC2233/Syllabus#94]
Hola, quería saber si está permitido usar try y except para el manejo de inputs.

Gracias!

**Comment by iqacevedo** [comment]
Hola,

Si puedes siempre y cuando sepas utilizarlo bien, ya que en caso contrario el ayudante que te revise va a descontarte por su mal uso. Como consejo no utilices `except Exception`, siempre indica el tipo de excepción que estás manejando como pueden ser `ValueError`, `IndexError`, etc.

Saludos !
