### ISSUE TITLE
Fin del programa

### ISSUE THREAD

**Issue by MINGOD24** [IIC2233/syllabus#94]
Al cerrar sesion se debe terminar el programa? o se debe poder ingresar nuevamente?

**Comment by aljara97** [comment]
Hola @MINGOD24 en el único caso en que debes permitir que se termine el programa es al apretar la opción "Salir", la cual se encuentra en el Menú de Inicio y cuando logras iniciar sesión y puedes escoger a cuál menú acceder. En otros casos debes permitir escoger acceder a un menú anterior.

Espero haber aclarado tu duda 🐦

**Comment by MINGOD24** [comment]
gracias!

**Comment by etgutierrez** [comment]
al salir del programa, se debe cerrar la consola?? o solo no pedir más inputs??

**Comment by aljara97** [comment]
Hola @etgutierrez, se refiere a que el programa deja de correr en la consola, no solo que debe dejar de pedir inputs

**Comment by Benjale** [comment]
Hola @aljara97, tú mencionas lo siguiente: "En otros casos debes permitir escoger acceder a un menú anterior", sin embargo, en el enunciado, en el menú de propgraposts tiene como opción 5 volver al menú de inicio. Es opción debiera ser volver al menú anterior o no?
