### ISSUE TITLE
Duda archivo 

### ISSUE THREAD

**Issue by BenjaMedinaPUC** [IIC2233/Syllabus#94]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola! esperando que se encuentren bien, escribo por el motivo de que me surgió la siguiente duda:  el archivo "puntajes.txt" ¿Debe contener los 10 puntajes mas altos o puede guardar los puntajes de todos los usuarios que han jugado y al momento que me pidan visualizar el ranking muestro los 10 puntajes mas alto?

**Comment by kolk3y** [comment]
https://github.com/IIC2233/Syllabus/issues/91#issuecomment-1229259641
