### ISSUE TITLE
Duda entrega readme

### ISSUE THREAD

**Issue by lucastack** [IIC2233/syllabus#94]
Hola, si ya entregué mi tarea de acuerdo a la fecha de entrega pero no completé el readme, tengo que llenar el formulario avisando que haré un push posterior o solo lo hago y ya está?

**Comment by StroveLight** [comment]
Hola! Solo basta con subir el readme a tu repositorio, eso sí recuerda hacerlo durante el plazo dado y en la carpeta pedida
