### ISSUE TITLE
Duda enunciado detectar_plaga

### ISSUE THREAD

**Issue by vvialbarros** [IIC2233/Syllabus#94]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Mi duda es que pasa en el caso que un predio tenga 2 bloques distintos con el mismo codigo de cultivo, es decir en la esquina superior izquierda tiene plantado un bloque de codigo "1" y en la otra esquina tiene plantado otro bloque de codigo "1", en el caso de que se encuentre una plaga en el bloque de la esquina superior izquierda tambien debo eliminar el bloque de cultivo de la esquina inferior izquierda ya que tienen el mismo codigo o solo debo eliminar el bloque infectado directamente

**Comment by vgalfaro** [comment]
Hola! como bien te respondió tu compañero, debes eliminar todos las celdas que tengan el mismo código que la infectada, aparte, notar que no tendrás celdas de cultivos con el mismo código separados, ya que estos se plantan en bloque todo junto. Saludos!
