### ISSUE TITLE
No sé como encontrar el hash completo del commit

### ISSUE THREAD

**Issue by Fernanda1232123** [IIC2233/Syllabus#94]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola,
Tuve una confusión al subir mi tarea y me gustaría que me corrijan un commit anterior, pero no sé como encontrar el 'hash completo del commit' que piden en el formulario.
¿Me ayudan?

**Comment by gatochico** [comment]
Hola @Fernanda1232123 ,

Como se explicó en el anuncio enviado, en el syllabus, bajo la carpeta "Archivos Importantes" hay un tutorial de cómo obtener el commit para llenar el formulario. Te adjunto el [link ](https://github.com/IIC2233/Syllabus/blob/main/Archivos%20Importantes/Como%20obtener%20el%20commit.md) a este tutorial.

Saludos!

**Comment by Fernanda1232123** [comment]
Gracias, 
me quedó resuelta la duda
