### ISSUE TITLE
QThread no termina después de salir de su metodo run

### ISSUE THREAD

**Issue by TMagini** [IIC2233/syllabus#940]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola, me pasa que mi QThread no termina después de salir de su método run, tengo el método de esta manera:

```
def run(self):
        while self.position[1] < self.y_limit:
            y = self.position[1] + self.speed
            self.position = (self.position[0], y)
            sleep(0.1)
```

Por lo que si el QThread se pasa del límite y nunca termina y se me llena de QThreads, intente usar el método `deleteLater()`, pero cada q vez q lo uso me lanza el error `QThread: Destroyed while thread is still running`, que leyendo issues no supe como arreglar para que no me tire ese error.

**Comment by PDominguezW** [comment]
Tengo la misma duda

**Comment by kadroguett** [comment]
Hola @TMagini, estuve revisando tu código y al ejecutarlo varias veces y no tuve problemas, lograste solucionar el error?

**Comment by TMagini** [comment]
Hola @kadroguett , lo que pasa es que efectivamente funciona las flechas en todos los niveles, pero como que no se eliminan los QThreads por lo que al jugar más de 3 veces por ejemplo con el nivel maestro, la aplicación se me cierra y supongo que es por la cantidad de QThreads activos que tiene, por lo que intente usar el `deleteLater()` pero me tiraba ese error, por lo que lo saque y quede con los QThreads activos.

**Comment by JDomingoSilva** [comment]
Tengo la misma duda, no se como terminar bien los qthreads, ya que a los mios por ejemplo no les puse un metodo run()

**Comment by kadroguett** [comment]
Hola de nuevo, estuve intentando replicar lo que me dices sobre jugar 3 en modalidad de maestro pero no se me cerró, me pasaba que mientras jugaba se desactivaba la detección de teclas lo que no me permitía superar el nivel. Sin embargo investigué a que se puede deber tu problema y encontré que nunca sales correctamente del `run()` en tu Qthread, para esto debes agregar un `return`, al final del mismo para que de esta forma el `run()` finalice. 
Para más información sobre lo que te comento te recomiendo leer la siguiente pregunta de stack:
https://stackoverflow.com/questions/42679791/how-to-stop-a-qthread-in-qt
Cuéntame si esto soluciona tu problema sino para seguir investigando.

Sobre tu problema @JDomingoSilva tendría que revisar tu código, tienes subido a tu repositorio lo que llevas?
