### ISSUE TITLE
Forma en que se agregan QLabels a una ventana

### ISSUE THREAD

**Issue by francisca0308** [IIC2233/syllabus#940]
Hola! 
No sé muy bien cómo plantear mi pregunta, por lo mismo no pude encontrarla en los issues anteriores. Lo que estoy intentando entender es cómo se organizan las labels dentro de la ventana, si se agregan en forma de "capas" o todas superpuestas unas con otras. Lo que pasa es que para quitar las mesas y mesones no me funciona apretarlas, es como si no se encontraran, pero probando con el logo, que está puesto "más libre" dentro de la ventana me funciona perfecto.
No sé si se entiende bien la pregunta

**Comment by danckoo1** [comment]
Hola, podría decirse que se agregan en forma de capas, ya que si en una misma posición creas dos labels, el ultimo que creas quedara tapando al primero, y por lo tanto al hacer click en dicha posición se activara el `mousePressEvent` del label que esta mas arriba, sin embargo, si tus label no se encuentran superpuestos no deberías tener ningun problema, por lo tanto asegurate que tus mesas son el label que se encuentre "en la capa de mas arriba", para lo cual te podria resultar util el metodo `raise_()`
