### ISSUE TITLE
Colision mesero

### ISSUE THREAD

**Issue by FelipeLara00** [IIC2233/syllabus#941]
Hola, tengo una duda con el enunciado, en la parte de las colisiones que dice 'Durante una colision el personaje no debe detener su animacion de movimiento a pesar de que no avance en el mapa'. Quiere decir que cuando colisione con algo debe quedarse quieto con ese sprite?

**Comment by kadroguett** [comment]
Hola @FelipeLara00 
Se refiere a que los sprites deben seguir cambiando pese a estar chocando con algo, como caminar contra una pared.
