### ISSUE TITLE
Problema Threads

### ISSUE THREAD

**Issue by TdelrioC** [IIC2233/syllabus#942]
Hola, al cargar los clientes en el juego (parecido a como se cargan los mortys en la ayudantía) por alguna razón la señal que se manda desde el back al front para crear el sprite y almacenarlo en la lista de objetos del front no se manda para la primera mesa y cliente pero si para el resto, pero en el backend si queda creado el  cliente 0, lo que produce un problema porque cuando se manda la señal para luego eliminarlo no existe un cliente 0 en el front porque nunca le llego la señal  (pero si existe en cliente1, cliente2,...)
Alguien sabe porque se puede producir esto? 
Otra cosa es que han habido un par de veces que si se cargo todo bien sin modificar ninguna linea, pero me ha pasado pocas veces que esto es asi, por lo general falla.

**Comment by tomasgv** [comment]
Hola @TdelrioC !!

Es difícil decirte con certeza lo que está pasando únicamente a partir de esto, pero algo que puede estar ocurriendo es que al principio estés emitiendo la señal antes de conectarla (lo que no produce un error, sino que la señal no es recibida).

En caso de que no sea eso, puedes subir tu progreso a tu repositorio personal y buscaré posibles causas :+1:

¡Quedo atento! :eyes:

**Comment by TdelrioC** [comment]
Hola @tomasgv 

Acabo de abrirlo desde 0 y correrlo desde la terminal y funciono las primeras 3 veces (pense que se había arreglado magicamente) y a la cuarta fallo.

Subo ahora mi repositorio para que lo puedas mirar.

Muchas gracias!!!

**Comment by TdelrioC** [comment]
Las funciones y archivos relevantes a ese tema en mi repositorio son:
- crear_cliente en main_window.py (linea 73)
- la linea 253 de classes.py, que es donde se debería emitir la señal para ser recibida en crear_cliente

**Comment by tomasgv** [comment]
@TdelrioC 

Yap, lo que pasaba era lo siguiente:

En `main.py` llamabas al método `start` de `AI`. Eso luego emitía la señal que debería haber sido recibida en el `front-end`. El problema es que hiciste este llamado antes de conectar la señal, lo que hizo que en el primer _loop_ de `run` se emitiera sin tener un destino. Esto no ocurre después porque la conexión se hace antes de entrar nuevamente al ciclo. Esto puede explicar por qué solo a veces se logra hacer la conexión antes de emitir la señal (hay una diferencia _muy_ pequeña de tiempo entre hacer el primer `emit` en tu _back-end_ y `connect` en `main.py`).

La solución más directa a esto es mover el llamado a `start`, de modo que se haga después de la conexión de la señal.

Probé haciendo esto y funcionó (por si las dudas, lo ejecuté más de 3 veces)

Espero que te haya servido! 🐱 🐻

**Comment by TdelrioC** [comment]
Buenisimo gracias
Te pasaste!!
