### ISSUE TITLE
Flechas se acumulan después de varias rondas

### ISSUE THREAD

**Issue by P1NOCHO** [IIC2233/syllabus#942]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Tengo un problema con la implementación de las flechas y no logro solucionarlo.
El problema es que a medida que pasan las rondas, al aparecer flechas estas se van acumulando en las filas (por ejemplo, en la primera ronda me sale de a una flecha por fila (normal), en la segunda ronda me sale de a dos flechas por fila, en la tercera de a tres y así se acumulan). Creo que tiene que ver con algo que no logro cerrar bien al terminar las rondas pero no entiendo bien que puede ser :(

**Comment by sl1nky** [comment]
Ya lo solucione!

**Comment by srodriguezp** [comment]
Hola! Tengo el mismo error como lo solucionaste??

**Comment by sl1nky** [comment]
Fíjate de conectar las señales en el init de las clases. En mi caso hacia la conexión en un método entonces cada vez que pasaba por ese método duplicaba la señal (pasaba por ese método una vez por ronda).

**Comment by srodriguezp** [comment]
Buenisimo, gracias!
