### ISSUE TITLE
Ritmo de creación de flechas varía entre distintas corridas del programa.

### ISSUE THREAD

**Issue by P1NOCHO** [IIC2233/syllabus#943]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Tengo un problema con las flechas.
A veces (no siempre) las flechas me salen con una frecuencia mucho menor a la normal (aparece una cuando desaparece la anterior y de repente salen dos seguidas), pero me pasa un cuarto de las veces que corro mi programa, las otras veces todo funciona normal. Cuando ocurre este error, al cerrar la ventana me sale este mensaje en consola:

TypeError: Flecha.actualizar[QLabel, int, int].emit(): argument 1 has unexpected type 'QLabel'
[1]    54973 abort      python3 main.py

Pero si me fijé de indicar, al instanciar la señal, que el primer argumento es de tipo QLabel.

**Comment by furcelay** [comment]
Hola!
¿Sigues con el problema? Estaba buscando tu repositorio para revisar cual podría ser la causa del error pero no lo pude encontrar ¿este es el mismo usuario de GitHub con el que te registraste en el curso?

Saludos!

**Comment by sl1nky** [comment]
Hola! Perdon por no responder ayer, pero el problema se solucionó solo a medida que avancé en la tarea (no se como).
Gracias de todas formas!
