### ISSUE TITLE
Pinguirines no se reaccionan a las flechas

### ISSUE THREAD

**Issue by jorge-ovalle** [IIC2233/syllabus#944]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by jorge-ovalle** [comment]
Hola! Estoy teniendo problema con el movimiento de los pinguinos. Implementé el drag and drop sin problemas, pero los pinguinos posicionados no reaccionan a los pasos realizados. Espero me puedan ayudar con eso. Los pinguinos y la ventana de juego están implementados en ventana_juego.py del frontend. Todo se puede ejecutar en el main.py.

**Comment by JadrinaDA** [comment]
Hola Jorge! Lo que pasa es que tus pinguirines sí se están moviendo al ser capturadas las flechas pero vuelven a su posición neutra tan rápido que este cambio no se ve en la ventana. De hecho si comentas la parte en que cambias el sprite a neutro podrás ver cómo tus pinguirines bailan! Para lograr que el cambio entre posiciones se vea en la ventana debes utilizar un tipo de delay. Pero no basta con un sleep ya que este va a bloquear tu interfaz. Te recomiendo utilizar un timer que ejecute después de un rato una función que devuelva los pinguirines a su posición neutra. Saludos y éxito en tu tarea!
