### ISSUE TITLE
Tamaño Sprites pinguinos interfieren con dropaje

### ISSUE THREAD

**Issue by domingo2000** [IIC2233/syllabus#945]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

Hola, tengo una duda sobre el sprite del pinguino, porque en el enunciado dice que "estos no se pueden superponer", pero el sprite del pinguino que se entrego es mas grande que la imagen del pinguino en si, lo que hace que aunque el pinguino en si no se  superpone, esta parte invisible si lo hace, por lo tanto la pregunta es puedo suponer que no se puede superponer el sprite entregado en vez del pinguino en si?? o podrian subir el sprite con un mejor recorte cosa que al colisionar ambos sprites sea mas detallado esa superposicion??

**Comment by kadroguett** [comment]
Hola @domingo2000, puedes suponer que el sprite completo no se puede superponer, pero recuerda explicitarlo en tu README.
