### ISSUE TITLE
Desconfiguración de ventanas de juego

### ISSUE THREAD

**Issue by bcalfaro** [IIC2233/syllabus#946]
Hola! Tengo mis archivos de los módulos para las ventanas de juego (pre ronda y ronda específicamente), y cuando importo ciertos módulos, como el que contiene la clase del Mesero, al intentar correr la ventana, esta se desconfigura totalmente y se ve de esta manera:
![image](https://user-images.githubusercontent.com/62023620/83697163-4f442980-a5cc-11ea-9d4b-d33ba53ae822.png)
¿Alguna idea de qué pueda estar pasando?
Al eliminar las líneas donde importo las clases, no hay problema y la ventana vuelve a la normalidad, pero necesito las clases para poder realizar algunas funciones.

**Comment by cristozille** [comment]
Hola! Probablemente sea un error de código. Sube lo que lleves a tu repositorio para poder hecharle una mirada :).
Cuéntame con cuales módulos te ocurre.

**Comment by bcalfaro** [comment]
Acabo de subir los archivos. Los problemas son al importar mesero en el módulo ventana_ronda (líneas 7 y 169) y al importar otras_entidades en ventana_pre_ronda (líneas 6, 30, 31 y 32). Dejé las líneas con problemas como comentarios para que puedas ver cómo debiesen ir las ventanas.
Gracias!

**Comment by bcalfaro** [comment]
Todo esto pasó tratando de ver por qué se detecta la señal del teclado para mover al mesero, pero no lo mueve :(

**Comment by cristozille** [comment]
Falta el archivo 'ventana_inicio.ui', súbelo apenas puedas.

**Comment by bcalfaro** [comment]
listo!

**Comment by cristozille** [comment]
Hola @bcalfaro! Creo que encontre el problema. En otras_identidades.py el código de prueba faltó ponerlo adentro del: 
if __name__ == '__main__':
    codigo...
Cambie eso  y me funcionó bien. Recuerda ponerlo en todos  los códigos de prueba para no tener problemas al importar el  archivo ;)

**Comment by bcalfaro** [comment]
gracias!!

**Comment by cristozille** [comment]
Denadaa
