### ISSUE TITLE
Borrar Layouts

### ISSUE THREAD

**Issue by pabloalvarez67** [IIC2233/syllabus#946]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola! hay alguna forma de hacerle algo así como un .clear() a los layouts? digo esto por que a los labels se les puede hacer este método para borrarlos.

Quiero hacerlo para poder setear los valores de una ventana cada vez que se emite la señal que la muestra, porque quiero mostrar cosas diferentes.

Gracias!

**Comment by knight-who-say-ni** [comment]
Holaa @pabloalvarez67 !!

Quiza lo que se menciona aqui (https://stackoverflow.com/questions/10416582/replacing-layout-on-a-qwidget-with-another-layout) te sirva 👀

**Comment by pabloalvarez67** [comment]
> Holaa @pabloalvarez67 !!
> 
> Quiza lo que se menciona aqui (https://stackoverflow.com/questions/10416582/replacing-layout-on-a-qwidget-with-another-layout) te sirva 👀

@knight-who-say-ni  Me sirvió muchas gracias jajaja pense que no lo iba a poner solucionar! te pasaste
