### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#947]
Hola. Qué significa éste error:
![image](https://user-images.githubusercontent.com/59337116/83697059-f83e5480-a5cb-11ea-9b83-703b0a4d1584.png)
¿?
El error ocurre cuando quiero ocupar una función de otra clase para conseguir lo que ésta misma retorna. 
Aquí dejo mas o menos expresado lo que hago:
```
class Clase1(QObject):
    def __init__(self):
        super().__init__()

    def funcion1(self, nivel):
        #reputación y nivel son int
        ......
        tiempo = max(0.15 - reputacion - (nivel*2))
        return tiempo

class Clase2(QObject):
    def __init__(self):
        super().__init__()
    def funcion2(self):
        #defino el paramentro nivel y lista_x
        .......
        for i in range(0, len(lista_x)):
           clase1 = Clase1()
           tiempo = clase1.funcion1(nivel)
           #justo acá ocurre el error
          
```

**Comment by kadroguett** [comment]
Hola @Camila-sty 
Probablemente tu `lista_x` sea un float, para comprobarlo pon un `print` antes del `for`

**Comment by kadroguett** [comment]
Miento, leí mal tu problema lo siento.
Le estás agregando un solo argumento al `max`, el cual es de tipo float, por lo que no puede "seleccionar" un máximo ya que solo es un número. Para que funcione bien debes o bien agregarle otro argumento o derechamente quitar la función `max`

**Comment by Camila-sty** [comment]
Pero yo defino un valor para las variables que salen ahí, ```reputacion``` y ```nivel```, por eso hice el comentario en la función. No la quise escribir entera...
Entonces, la función ```max``` recibe un float y dos int

**Comment by Camila-sty** [comment]
Y estos valores fueron imprimidos antes para ver si en verdad los estaba leyendo, y sí, recive estos valores que con int

**Comment by kadroguett** [comment]
Lo que estás haciendo en max es restar 0.15 - reputación y nivel, debes separarlos por comas

**Comment by Camila-sty** [comment]
> Lo que estás haciendo en max es restar 0.15 - reputación y nivel, debes separarlos por comas

Veeeerdaaad! jajaja
