### ISSUE TITLE
Uso sys.exit(app.exec_())

### ISSUE THREAD

**Issue by soyjorgeperello** [IIC2233/syllabus#948]
Hola! En los built-in prohibidos aparece que no se puede usar exec pero tanto en las ayudantías como en los contenidos del curso utilizan el siguiente código para mostrar las ventanas de las interfaces:

if __name__ == '__main__':
    app = QApplication([])
    ventana = MiVentana()
    ventana.show()
    sys.exit(app.exec_())  ----> utilizan exec_()

Quería saber si este es lo mismo que el built in prohibido o si podemos usar este código.

Gracias!

**Comment by jitorcas** [comment]
Hola @soyjorgeperello 

Revisa las issues #898 #822 #686 que preguntan lo mismo!
Tambien puedes revisar el compilado de issues para verificar si tu duda ya fue resuelta anteriormente. 

Saludos y éxito! 💯
