### ISSUE TITLE
Mis flechas dejan rastro en ventana

### ISSUE THREAD

**Issue by Margarita-Paz** [IIC2233/syllabus#948]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! cuando mi flecha va descendiendo deja un rastro en la pantalla, pero después este desaparece ¿A qué se podría deber?
![image](https://user-images.githubusercontent.com/53887845/97661809-21b4bc80-1a54-11eb-92f3-958b8562f30d.png)

**Comment by furcelay** [comment]
Hola!
Perdón por la demora 😓 dado que tu problema es muy particular me gustaría probarlo en ejecución, pero al parecer la versión de tu repositorio no está actualizada, si el problema persiste actualiza tu repositorio para ver que puede causarlo (y deja un comentario aquí para saber que lo actualizaste). Si el problema ya está resuelto también comenta para marcar la issue.

Saludos!

**Comment by Margarita-Paz** [comment]
Hola! Mi programa se caía dsp de un rato de flechas, así que lo estoy arreglando. Si me siguen apareciendo las marcas te aviso.

Gracias!!
