### ISSUE TITLE
costo asociado al primer pinguirin

### ISSUE THREAD

**Issue by martin-santiago** [IIC2233/syllabus#949]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

Hola, es una duda simple, en el enunciado sale que el primer pinguirin no tiene costo asociado, queria saber si es válido interpretar esto como que podemos partir con $500 de esta manera podemos comprar el primer pinguirin sin haber jugado y no tendria "costo", o efectivamente debemos partir con 0$ y poder escoger el primer pinguino de todas formas ¿¿??

**Comment by aljara97** [comment]
Hola @martin-santiago, el primer pingüirin debe tener un costo igual a cero, por tanto, entregar una cantidad de dinero inicial igual al precio se escapa de la lógica del programa.
