### ISSUE TITLE
Duda test case 06 buscar y plantar

### ISSUE THREAD

**Issue by mrebolledo03** [IIC2233/Syllabus#95]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [ ] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

en el "python3 -m unittest -v -b tests_publicos.test_06_buscar_y_plantar_dificil" el test 01, sale que el plano_4 debe ser de 3x3, o sea alto = 3 y ancho = 3, pero al momento de printear la función el ancho y el alto me entrega alto 2 y ancho 1, lo que no corresponderia a ese test case, revisando el test case en python en una parte se programa esto:

resultado_estudiante = dccultivo.buscar_y_plantar(
            codigo_cultivo=4, alto=2, ancho=1
        )
        
en vez del predio_4 = Predio(codigo_predio="4", alto=3, ancho=3) que es lo que plantea el test case, **no sé si es un error de código del test o estoy entendiendo mal el test**

**Comment by Agusrush21** [comment]
No se si entendí bien tu pregunta, pero en ese test case se te presentan 2 planos uno de 3x3 con codigo_predio "4" y otro plano que es de 2x1 con codigo_predio "5".
Lo que hace el test es que al formar los predios con estos planos y utilizar el método de buscar_y_plantar, este bloque se plantara en el predio/plano de 2x1

**Comment by ignacio-sp** [comment]
Hola @mrebolledo03, tal como indica tu compañero, en ese test se crean 2 planos distintos (`plano_4` de 3x3 y `plano_5` de 2x1) los cuales se guardan en el atributo `plano` de los predios respectivos (`plano_4` a `predio_4` y `plano_5` a `predio_5`) para luego guardarlos en la clase `DCCultivo`.

Luego, se llama a la función `buscar_y_plantar` en donde se quiere plantar un **cultivo** de código 4 de tamaño 2x1, los atributos de esta función corresponden a **las caracteristicas del cultivo y no al predio en el que se está buscando plantar**, que si no me equivoco, es eso lo que está causando tu confusión (en otras palabras, ese `codigo_de_cultivo = 4` **no hace referencia al predio 4 de 3x3**), la tarea de la función es buscar entre los predios disponibles, un lugar en el que plantar dicho cultivo según lo indicado en el enunciado en el apartado 2.1

No sé si eso habrá resuelto la duda o era otra la duda, estoy atento a tu respuesta!

**Comment by mrebolledo03** [comment]
sii me queda claro, gracias
