### ISSUE TITLE
Tarea01: Lógica condiciones climaticas

### ISSUE THREAD

**Issue by AmbrosioV** [IIC2233/Syllabus#95]
Tengo un par de dudas sobre como las condiciones climáticas afectan el crecimiento de un incendio.
Las condiciones climáticas que ya acabaron pero estuvieron presente a lo largo de la vida de un incendio deben cumplir lo siguiente?: 
> 'En caso de que dos o mas condiciones meteorológicas del mismo tipo coincidan con un incendio, solo se debe tomar en cuenta la más reciente.'

Es decir, si hubo dos lluvias en el pasado que en un periodo se traslaparon, solo considero la primera parte de la que llego primero y luego tomo la que llega después hasta su termino (o eventual llegada de otra lluvia). O se aplican por el periodo completo que cada una estuvo presente. 
Osea mi duda es respecto a condiciones climáticas que comienzan y terminan, ya que el enunciado solo especifica dentro de las que continúan efectuándose (que solo se mira la última en aparecer).
EDIT: Osea se requiere una simulación estricta sobre la condición mencionada, que cada pronostico afecta hasta que otro lo reemplaza
Saludos

**Comment by rpalmaotero** [comment]
Si se traslapan para un incendio, considera la más reciente. Si no se traslapan, considera ambas por el periódo de tiempo que corresponda, es decir, desde la fecha de inicio hasta la de termino.

**Comment by AmbrosioV** [comment]
Considere el periodo de cada una hasta que encontrara otra posterior, o acabara o se topara con la fecha establecida. Creo que cumple de más con lo pedido
Cierro el caso

**Comment by AmbrosioV** [comment]
> En caso de que dos o mas condiciones meteorológicas del mismo tipo coincidan con un incendio, solo se
> debe tomar en cuenta la más reciente.
Me surgió otra duda, la mas reciente se refiere a la última que se topa el incendio a medida que crece o por fecha de inicio?

**Comment by Hernan4444** [comment]
@AmbrosioV se considera por fecha de inicio.

Saludos!
