### ISSUE TITLE
Duda Eventos

### ISSUE THREAD

**Issue by llloyola** [IIC2233/Syllabus#95]
Pueden ocurrir ambos eventos a la hora de visitar un planeta?

**Comment by IchottMano** [comment]
@llloyola Hola!
Como dice el enunciado en el punto 8, la probabilidad de que suceda un evento es única, por lo que sólo puede suceder uno de los dos eventos al visitar un planeta.
Saludos!

**Comment by geduran** [comment]
@IchottMano y los eventos pueden ocurrir siempre que uno visita un planeta, esté conquistado o no? 
Gracias!

**Comment by IchottMano** [comment]
@geduran Hola!
Efectivamente es siempre que se visita un planeta, esté conquistado o no.
Saludos!

**Comment by nhbravo** [comment]
En el enunciado (8) sale que son solo los planetas conquistados. ¿Qué indicación seguimos?

**Comment by IchottMano** [comment]
@nhbravo Hola!
Lo que dice en el enunciado en el punto 8 es que al visitar un planeta, el asteroide cae en uno de tus planetas conquistados, sin embargo no especifica que el planeta visitado esta conquistado o no.
Espero esto resuelva tu duda.
Saludos!

**Comment by nhbravo** [comment]
Gracias por la aclaración!

**Comment by Jj1martinez** [comment]
Pero si estoy visitando un planeta y me aparece un archimago, al vencerlo sigo visitando el planeta? o debo volver a entrar con probabilidad de que aparezca de nuevo el archimago?

**Comment by IchottMano** [comment]
@Jj1martinez Hola!
Eso queda a tu criterio.
Saludos!
