### ISSUE TITLE
Carpeta Save

### ISSUE THREAD

**Issue by icampusano** [IIC2233/syllabus#95]
Hola! Quería saber si podemos crear una carpeta "save" y subirla al repositorio y, por ende, asumir que existirá al momento de corregir. O es necesario que no exista esta carpeta y se cree sólo en caso de necesitarla (en otras palabras si el jugador parte un juego desde cero y decide guardar en algún punto).

Saludos!

**Comment by iqacevedo** [comment]
Hola,

Tienes 2 opciones:

1. Tal como dices subir una carpeta vacía. Pero tienes que asegurarte de que la carpeta se suba, para esto puedes agregarle un archivo vacío de nombre .gitkeep.
2. La otra opción, igualmente válida, es crear la carpeta en caso de que no exista.

Saludos !
