### ISSUE TITLE
Aclaración enunciado para metodo limpiar

### ISSUE THREAD

**Issue by bea-or** [IIC2233/Syllabus#95]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Duda

Hola, para el método limpiar de la clase tablero en el enunciado se indica def limpiar(self) -> None: mientras que en el archivo de tablero.py venia escrito limpiar(self) -> int: . Quería saber cual es el correcto en este caso.

Gracias!

**Comment by benjasaldias** [comment]
Holaa, tuve la misma duda.
Asumo que es None el correcto, porque en el párrafo del enunciado no especifican qué es lo que debiera retornar en caso de ser int.

**Comment by mtaguero** [comment]
¡Hola @bea-or!

Lo importante es que te des cuenta qué es lo que hace el método. En este caso, limpiar se describe como “Método que actualiza el tablero de la instancia para eliminar todos los peones de dicho tablero”. En comparación con otros métodos no dice que retorne algo (como dice @benjasaldias), por lo tanto, debería retornar None, tal como dice el enunciado.

¡Éxito! 🎈
