### ISSUE TITLE
Duda valor probabilidad de ganar (¿probabilidad negativa?)

### ISSUE THREAD

**Issue by alexandra-maker** [IIC2233/Syllabus#95]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Para la probabilidad de ganar en el juego, utilizando la formula: min(1, prob.ganar.jugador - (funcion)), existe la posibilidad de obtener una probabilidad negativa. Me preguntaba si tal vez es necesario tomar el valor absoluto de esa resta (prob.ganar.jugador - (funcion)) y así evitar ese problema.

**Comment by antoniablanco** [comment]
Aunque no es pedido en el enunciado y no se va a evaluar, puedes tomar el valor absoluto si es que prefieres para los calculos.

**Comment by mvvaldes** [comment]
Creo que tomar el valor absoluto no tiene mucho sentido, porque hace que estadísticas muy malas te den una mejor probabilidad de ganar, tendría más sentido hacer el máximo con cero

**Comment by mvvaldes** [comment]
En todo caso por como se calcula quien gana, da lo mismo que la probabilidad sea negativa
