### ISSUE TITLE
Buenas prácticas con sort

### ISSUE THREAD

**Issue by furcelay** [IIC2233/syllabus#95]
Existe una preferencia (por velocidad, claridad, etc.) entre estas dos maneras de ordenar una lista de objetos (de una clase que yo he creado) por un atributo del objeto?:

1. Usando `sorted()` o `list.sort()` con `key=alguna_funcion`, ejemplo:
``` python
class Objeto(object):
    def __init__(self, valor):
        self.atributo = valor

lista = [Objeto(valor) for valor in range(10, 0, -1)]
lista_ordenada = sorted(lista, key=lambda objeto: objeto.atributo)
```
2. Creando un método `__lt__` para la clase, ejemplo:
``` python
class Objeto(object):
    def __init__(self, valor):
        self.atributo = valor
    def __lt___(self, other):
        return self.atributo < other.atributo

lista = [Objeto(valor) for valor in range(10, 0, -1)]
lista_ordenada = sorted(lista)
```

**Comment by KnowYourselves** [comment]
Hola @furcelay!

**Excelente pregunta**! Analicemos dos casos de interés general:

1. Ordenar una lista de números.
2. Ordenar una lista de objetos.

En el caso uno compararemos `sort` con `sorted`, mientras que en el caso dos compararemos el uso de `lambda` con el uso de ` __lt__`.

## Caso 1
Para este caso, generamos una lista aleatoria de `10e6` elementos, con números aleatorios uniformes en el rango `[-1000, 1000]`. Los resultados promedios después de 20 tests fueron los siguientes:

- Sorted: 0.22436376810073852 seg.
- Sort:  &nbsp;&nbsp;&nbsp; 0.2008036494255066 seg.

Es decir, `sorted` es *levemente menos eficiente* que `sort`. Esto se debe a que ambos hacen el mismo proceso, pero la primera debe crear una nueva lista. Sin embargo `sorted` es más versátil, ya que sirve con cualquier iterable, no solo con listas.

En resumen, si bien `sort` es levemente más rápido que `sorted`, `sorted` es más utilizado, por el hecho que es más versátil, en especial cuando se quiere obtener una lista ordenada sin querer modificarla.

## Caso 2
En este caso, generamos dos listas de `10e6` elementos. Una con la clase `Objeto` sin `lt` y otra que si lo tiene, en ambos casos se utilizará `sorted` solo que en el primero se usará `lambda`. Los resultados promedios después de 20 tests fueron los siguientes:

1. lambda: 0.4130581855773926 seg.
2. lt: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 4.383601474761963 seg.

En este caso `lamba` es **10 veces más eficiente que el `lt`**. Esto se debe a que las clases en Python son **mucho _overhead_**, es decir, agregan muchos calculos y operaciones que estrictamente hablando, no son necesarias.

## Conclusiones

1. En general se utiliza `sorted`.
2. Usar `lambda` es mucho más rápido que `lt`..

Espero haberte ayudado!

**Comment by furcelay** [comment]
Me quedó muy claro, muchas gracias!!
