### ISSUE TITLE
Duda con if __name__ == __main__:

### ISSUE THREAD

**Issue by J0SEF4** [IIC2233/Syllabus#95]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Respecto a cuando uno uso if __name__ == __main__:. Eso todavía no entiendo:
- ¿Qué hace?
- ¿Cómo funciona?
- ¿Por qué funciona de tal manera?
- ¿Para que sirve?

Saludos y gracias por adelantado.

**Comment by J0SEF4** [comment]
Además, no entendí su uso y que hacia en el video de Consejos y Tips para las actividades que hay en canvas.

**Comment by fernandosmither** [comment]
Hola!

La variable `__name__` es una variable especial de python que se encuentra presente en todos los archivos por defecto (Aka. _built-in_), y puedes acceder a ella simplemente escribiendo `print(__name__)` y corriéndolo.
```python
print(__name__)
```
Output:
```output
__main__
```

Lo útil de esta variable, es que cambia su valor dependiendo de **en dónde se está ejecutando el archivo de python**.
Por ejemplo, si en el archivo mismo que estás ejecutando el código printeas su valor, te devolverá `__main__` (ahora verás por qué en las actividades el principal archivo a correr por lo general se llama `main.py`), sin embargo, si lo printeas desde un módulo externo..:

En este ejemplo tenemos los archivos `main.py` y `modulo_externo.py`. Dentro de `main.py` (que será el archivo que correremos) importaremos al módulo externo para que imprima el valor de su variable name.
![image](https://user-images.githubusercontent.com/66154723/132155540-3020d574-ca13-4e34-89d2-8d77a35d964f.png)
![image](https://user-images.githubusercontent.com/66154723/132155628-eb48fa84-04fd-42af-a799-63b915527580.png)

Espero que esto haya despejado tus dudas. Cabe recalcar que independiente del nombre del archivo que corres, su variable siempre se llamará `__main__`, mientras que las de archivos externos toman el valor del nombre del archivo.

Ahora bien, esto nos es útil cuando programamos archivos grandes que cuenten con varios módulos. Imagínate que quieres probar la funcionalidad de uno de estos, por ejemplo borrar un archivo en particular para probar esa funcionalidad. Como tu no quieres que este módulo sea corrido por tus futuros usuarios directamente, podemos hacer uso de la variable `__name__` para saber si el módulo fue corrido directamente, y así poder avisarle al usuario cómo debería correr nuestro código.

La verdad es que hay varios usos distintos para la sintaxis, pero por lo general está bien visto aplicarlo a nuestros módulos, y te será muy útil en el curso ya que en las tareas puedes probar directamente tus módulos y funciones, y puedes despreocuparte, ya que no se descontará que lo incluyas.

Ojalá te haya quedado más claro! quedo atento a tus cometarios 😄

**Comment by J0SEF4** [comment]
Ok, me quedo ahora bastante claro que cunado lo use me entrega el nombre del archivo py en el que estoy. Sin embargo, no entendí esta frase: "Cabe recalcar que independiente del nombre del archivo que corres, su variable siempre se llamará __main__, mientras que las de archivos externos toman el valor del nombre del archivo."
¿Quiere decir que el archivo en el que estoy corriendo todo el programa que tiene importaciones de otros archivos siempre se llamara __main__ y nunca por su nombre de archivo?

Gracias por la paciencia, tiempo y explicar todo tan detallado.

**Comment by fernandosmither** [comment]
> ¿Quiere decir que el archivo en el que estoy corriendo todo el programa que tiene importaciones de otros archivos siempre se llamara main y nunca por su nombre de archivo?

Exacto! Así es como llegamos a utilizar la sintaxis de la cual preguntaste.
