### ISSUE TITLE
No me funcionan los test_publicos

### ISSUE THREAD

**Issue by FelipeEscobarA** [IIC2233/Syllabus#95]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ ] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/20)).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/19)).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Estoy tratando de correr los test publicos, sin embargo me dan error todos (cabe destacar que voy por la funcion "ciclo mas corto" con todas las funciones anteriores bien programadas (corroboradas por mi criterio y pruebas propias). los trato correr desde la direccion "test_publicos (nombre del test).py" pero siempre me dan error, tambien ntente usando todos los test al mismo tiempo pero nada

**Comment by MaxAl100** [comment]
Hola! Perdón por la respuesta un día después, pero podrías enviar los mensajes de error que te dan? (sin mostrar código). Esto para ver cuál puede ser la razón del error...

**Comment by FelipeEscobarA** [comment]
> Hola! Perdón por la respuesta un día después, pero podrías enviar los mensajes de error que te dan? (sin mostrar código). Esto para ver cuál puede ser la razón del error...

 resulta ser que estaba haciendo el codigo en main.py y era en red.py XDD
