### ISSUE TITLE
Sobre modularización

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#95]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### if \_\_name__ == "\_\_main__"

Mi duda es más allá del curso, cuando creemos el archivo 'principal' de nuestro programa en python, ¿se debe comenzar con la modularización main? ¿o queda solamente como una utilidad para testear diferentes archivos y tener comportamientos distintos?

Recuerdo escucharle a un amigo que el no ponerlo es una mala práctica, sin embargo no he logrado encontrar mucho al respecto en internet, y al final de cuentas 1: no cambia en sí la ejecución del programa principal y 2: añade una identación y línea más, dificultando un poco la regla de los carácteres máximos.

También extiendo mi duda a su uso en los archivos utilizados como módulos, porque ahí sí veo más lógico añadir una advertencia de mal uso al intentar utilizar el módulo como el programa principal.

**Comment by Julius9** [comment]
Hola Fernando!. Como comentas el uso del [if __name__ == "__main__"] es mas una buena practica que otra cosa y se utiliza principalmente en los módulos no principales para evitar ejecutar el código de prueba de estos. Por ejemplo supongamos que tienes dos archivos el principal "main.py" y "funciones.py" donde escribiste las funciones que utilizaras en el main. Cuando importas este modulo "funciones.py" python ejecuta todas las lineas del modulo incluida las pruebas que pudiste haber realizado para corroborar el correcto funcionamiento de los métodos que definiste, esto puede ser complicado, engorroso y puede traer errores. Para evitar esto las pruebas dentro de un modulo a importar se utiliza el [if __name__ == "__main__"] y así no se ejecutan las lineas identadas en él. Por lo que no es necesario realizar esta sentencia en el archivo principal a ejecutar.

Para saber más sobre como python trabaja esta sentencia te recomiendo leer las respuestas de la siguiente pagina 
( https://stackoverflow.com/questions/419163/what-does-if-name-main-do )

**Comment by fernandosmither** [comment]
> Hola Fernando!. Como comentas el uso del [if **name** == "**main**"] es mas una buena practica que otra cosa y se utiliza principalmente en los módulos no principales para evitar ejecutar el código de prueba de estos. Por ejemplo supongamos que tienes dos archivos el principal "main.py" y "funciones.py" donde escribiste las funciones que utilizaras en el main. Cuando importas este modulo "funciones.py" python ejecuta todas las lineas del modulo incluida las pruebas que pudiste haber realizado para corroborar el correcto funcionamiento de los métodos que definiste, esto puede ser complicado, engorroso y puede traer errores. Para evitar esto las pruebas dentro de un modulo a importar se utiliza el [if **name** == "**main**"] y así no se ejecutan las lineas identadas en él. Por lo que no es necesario realizar esta sentencia en el archivo principal a ejecutar.
> 
> Para saber más sobre como python trabaja esta sentencia te recomiendo leer las respuestas de la siguiente pagina
> ( https://stackoverflow.com/questions/419163/what-does-if-name-main-do )

Perfecto, entonces en conclusión, el archivo principal **no es necesario** declarar name == main

**Comment by pabloist** [comment]
Hola!

No es necesario, pero se considera buena práctica. Lo importante es que al ejecutar el archivo main.py de tu programa, ejecute tu desarrollo.

Saludos!
