### ISSUE TITLE
\ufeff aparece al modificar mi archivo users

### ISSUE THREAD

**Issue by nmaturana97** [IIC2233/Syllabus#95]
hola al cargar el archivos users que modifique manualmente me aparece "\ufeff" al inicio de la primera linea, lo que me impide cargar bien los datos. ¿Esto pasara cuando ustedes corrijan con los archivos que enviaron? y, ¿por qué pasa esto?

**Comment by sebacruzd** [comment]
Hola, esto es por el archivo csv.
Un .strip o .replace es suficiente para removerlo.

Saludos!

**Comment by nmaturana97** [comment]
gracias. Sabes por que este no aparece si esq yo no modifico el archivo?

**Comment by nachocontreras** [comment]
Me pasa exactamente lo mismo. Al modificar el archivo, ya no puedo abrirlo de nuevo.

**Comment by sebacruzd** [comment]
Tiene que ver con la codificación del archivo. Sus programas probablemente usen una distinta a la codificación con la que venía el archivo.

Cuando lo abran prueben open(archivo, r, encoding="utf-8")

Leyendo [https://stackoverflow.com/questions/17912307/u-ufeff-in-python-string](esta página), al parecer con utf-16 ya no deberia aparecer \ufeff.

**Comment by nachocontreras** [comment]
gracias!
