### ISSUE TITLE
QThreads clientes

### ISSUE THREAD

**Issue by mmunoz12** [IIC2233/syllabus#950]
hola! creo que tengo un problema al crear los threads de cada cliente. Resulta que los voy creando a traves de un Qtimer, pero me pasa que si uso el metodo thread.isFinished() este siempre arroja True aun cuando el cliente si esta mostrandose, cambiando de sprites y todo. Es como si el programa no lo estuviera tomando como un thread una vez creado, esto impide que pueda trabajar con los clientes ya que dejan de existir en el programa pero siguen mostrandose bien en la interfaz. No se si se entiende pero que podría ser?

**Comment by bvasquezm** [comment]
Hola @mmunoz12!

En general los QObjects y/o Widgets al momento de ser creados no dejan de existir **a menos que lo señales de manera explícita**. Es decir, si dentro de la ejecución del QThread (el cual a diferencia de los QTimers, corre una única vez el loop) si no especificas la desaparición de un sprite u objeto, este permanecerá vivo sin lugar aparente en tu programa. Es por eso que usualmente tienen dos opciones:

* Hacer uso de QTimers y manejar todo con múltiples repeticiones de procesos.

* Hacer uso de QThreads, pero preocuparte de dejar todo en orden antes de que estos terminen. 

Espero haber sido claro con mi explicación. Desde luego si tienes más dudas, no te preocupes por preguntar!!

**Comment by mmunoz12** [comment]
mmm pero si mi cliente ya es un thread, y se esta ejecutando (aparece el sprite, se enoja y luego desaparece), porque el codigo lo tomaria como que el thread ya esta terminado si este aun no ha sido eliminado? me refiero a que arroja .isFinished = True siempre, siendo que esta "vivo" :(

**Comment by bvasquezm** [comment]
Me parece que puedes estar teniendo algún problema en el modelaje de tu thread. ¿Puedes hacer `git push` de lo que llevas para poder verlo mejor?

**Comment by mmunoz12** [comment]
ya lo solucione! no estaba iniciando bien el thread, gracias!

**Comment by bvasquezm** [comment]
😄 Me alegro, mucha suerte con tu tarea!
