### ISSUE TITLE
Parámetros PUNTOS_FLECHA

### ISSUE THREAD

**Issue by Gustav2000** [IIC2233/syllabus#951]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
**Hola, por enunciado sabemos que tenemos que usar el parámetro PUNTOS_FLECHAS, sin embargo mi pregunta es si este parámetro lo puedo usar en un diccionario donde esta sería la key ya que encuentro que sería más fácil poder buscar el puntaje de cada flecha si es de esta forma. La otra opción que quisiera saber si es válido es anotar efectivamente los parámetros solicitados y después en el mismo parametros.py crear el diccionario que digo, que utiliza como variables dichos valores.**

**Comment by JadrinaDA** [comment]
Hola Gustav! Sí puedes utilizar un diccionario. Puedes definir el diccionario mismo en parametros.py mientras que expliques esto en tu README y que respetes el formato del archivo. Es decir no hagas una función que cree un diccionario sino que define un parámetro que sea un diccionario. Un ejemplo sería PUNTOS_FLECHAS= {"normal": 10, "x2" : 20", ....}. Éxito!

**Comment by Gustav2000** [comment]
Yaa, muchas gracias!!!
