### ISSUE TITLE
Interaccion chef/mesero

### ISSUE THREAD

**Issue by Araos827** [IIC2233/syllabus#951]
Hola. me pasa que cuando el mesero recibe el plato el chef queda libre inmediatamente por lo que al estar colisionando con el mesero empieza a preparar otro plato altiro, sin la necesidad de volver a colisionarlo. No se si esto cuenta como valido o si es que el mesero tiene que estar desocupado para activar a algun chef.

**Comment by cristozille** [comment]
Hola! La idea es que el chef al entregar el plato quede 'libre', y tengas que volver a colisionar con él para que empiece a preparar otro plato.

**Comment by Araos827** [comment]
Con volver a colisionar te refieres a salir del hitbox y chocarlo denuevo? Es que en teoria el chef queda libre cuando entrega el bocadillo pero al estar en contaco con el mesero altiro se triggerea el 
if libre -> a cocinar. Tengo que implementarlo de la otra manera o puedo dejarlo asi?

**Comment by cristozille** [comment]
Debes salir del hitbox y chocarlo de nuevo. La idea es que el chef quede esperando hasta que tú le indiques que prepare otro plato.

**Comment by cristozille** [comment]
<img width="916" alt="Screen Shot 2020-06-03 at 22 37 18" src="https://user-images.githubusercontent.com/42190189/83708677-d4d6d200-a5ea-11ea-85e7-cb35b50b6bc8.png">
Aparece también el enunciado en la pagina 15 c:

**Comment by Araos827** [comment]
El problema que tengo con eso es que la posicion de los chefs es cualquier int y no es un multiplo de 10, pero el movimiento del mesero si lo es, por lo que la hit box no esta definida exactamente como dist = 0, en efecto la tengo definida entre un rango de distancias [0, x], para que independiente de si el chef esta posicionado en un multiplo de 10 o no igual se pueda chocar. Entonces, lo que pasa es que hay algunos chefs que se pueden colisionar desde dos distancias distintas, o dos "pasos" del mesero por lo que aveces cuando doy un paso hacia atras con el mesero, sigo adentro del hitbox de los chefs y altiro se activan denuevo D:, alguna sugerencia de como podria solucionar esto?

**Comment by cristozille** [comment]
Te entiendo. Algo que podrías implementar es un atributo de chef (un bool por ejemplo) que indique si esta el mesero en la hit box o no, y que una vez que sea True solo se pueda cambiar a False cuando el mesero este afuera. Así, en las colisiones revisas que el atributo sea False para empezar a cocinar. Se entiende?

**Comment by vWing7** [comment]
No se si es lo mismo pero en mi caso, si mantienes presionado hacia la mesa hace las 2 cosas rapidamente, porque entra al hitbox rapidamente 2 veces, estaría bien eso?

**Comment by cristozille** [comment]
Hola @vWing7, podrías explicar un poco mas? No entendí bien.

**Comment by vWing7** [comment]
Cuando se mantiene presionado para moverse en la dirección del chef y se obtiene el plato con comida, ya que se esta manteniendo presionado, el jugador interactua de nuevo con el chef y le dice que comience a preparar otro plato, lo que a simple vista se ve como si fuera una colisión que dice ambas cosas, pero en verdad fueron 2 colisiones consecutivas. Quería saber si está bien eso.

**Comment by cristozille** [comment]
Esta bien! Lo importante es que sean interacciones diferentes. Colócalo en el Readme.md para que el ayudante lo tenga claro ;)
