### ISSUE TITLE
Acción de Seguir jugando sin partidas guardadas

### ISSUE THREAD

**Issue by jonanortizvega** [IIC2233/syllabus#952]
Si se acciona el botón de Seguir Jugando en la ventana inicial y los archivos mapa.csv y datos.csv no tienen partidas guardadas generaría un error, hay que mostrar un aviso de que no hay partidas guardadas, si inicia una nueva partida si no hay partidas guardadas o se debe considerar como que esos archivos siempre contendrán una partida??

**Comment by danckoo1** [comment]
hola! puedes asumir que los archivos siempre existirán y contendrán una partida guardada.

**Comment by jonanortizvega** [comment]
Y el rango de valores que tendrá esa partida por defecto hay que especificarlos en el README o lo define el corrector?

**Comment by danckoo1** [comment]
hola, mil disculpas por atrasarme en responder. Sobre los valores, los unicos valores que se encuentran en un rango son los de `mapa.csv` que deben estar dentro de los parametros `LARGO_MAPA` Y `ANCHO_MAPA` por lo que te recomiendo que en tu readme menciones con que valores dejaste dichos parametros. En cuanto al resto deberían funcionar para cualquier valor,
saludos
