### ISSUE TITLE
Entidades sobre otras al cargar partida 

### ISSUE THREAD

**Issue by CristobalCarrascoD** [IIC2233/syllabus#953]
Al cargar una nueva partida se menciona que se tienen que poner en el mapa las mesas y los chefs de forma aleatoria, ademas se menciona que estos no pueden quedar encima de otra entidad. Es en esto ultimo con lo que tengo problema he estado buscando pero no encuentro como poder revisar que en la posición aleatoria en la que estoy poniendo el QLabel de la mesa o el chef, no haya otro QLabel. Alguna idea de como hacer esto? :)

**Comment by jbulness** [comment]
Hola @CristobalCarrascoD,

No sé en base a qué criterio ubicas los objetos en el mapa, pero si lo haces con algún tipo de coordenadas podrías generar los pares de coordenadas que necesitas y comparar que no sean iguales entre si, y luego asignar cada coordenada a una entidad.

Si lo estás haciendo de otra forma feliz que me expliques para poder ayudarte de mejor manera.

**Comment by CristobalCarrascoD** [comment]
Lo que hago es usar un random.randint con los valores dentro del rango posible dentro del mapa para ambas coordenadas x e y asi luego uso setGeometry con esas coordendas obtenidas aleatoriamente, para cada entidad. Pero con esto, al hacer denuevo random.randint a otra entidad, no se como hacer para saber si al poner la entidad en esa coordenada no va a haber otra entidad antes agregada, considerando que las entidades tienen sus propias dimensiones y, entonces, con solo tener guardadas todas las coordenadas en una lista no bastaría.

**Comment by jbulness** [comment]
Lo que podrías hacer es realizar ese proceso aparte de las entidades. Una función que tome el tamaño del mapa y las cantidades de entidades de cada tipo que necesitas y que arroje una primera coordenada, le sume un alto y ancho correspondiente a la entidad que necesita y guardas esa coordenada. Luego repites el proceso anterior, pero antes de guardarla verificas que los rango que abarcaría esta nueva entidad no se "cruzan" con los de la otra ya guardada, pero ojo que si se pueden "cruzar" solo alto o solo ancho (o ninguna de las dos), ya que esto significaría que están al mismo nivel en x o en y. Repites este proceso según la cantidad de coordenadas de cada tipo necesitas y luego se las agregas a las entidades cuando las creas.

**Comment by CristobalCarrascoD** [comment]
Ya voy a ver si me funciona, Gracias!
