### ISSUE TITLE
No se sobreescribe la tecla de espacio

### ISSUE THREAD

**Issue by Sofia-Arratia** [IIC2233/syllabus#953]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola!

Al tratar de implementar la tecla espacio de la misma manera que he implementado el resto de las teclas obligatorias wasd, mi ventana de juego se cierra inesperadamente, sin embargo si cambio la tecla de espacio por otra (por ejemplo F) funciona al igual que el resto de mis teclas implementadas, es decir, como esperaría yo que funcionara. ¿Por qué podría estar pasando esto? ¿Se necesita hacer algo especial para sobreescribir la acción de la tecla de espacio?

Muchas gracias ☺️

**Comment by manearaya** [comment]
Hola @Sofia-Arratia!

Creo que lo que está pasando es que al presionar el espacio, se activa el botón de salida que debes tener en tu ventana. Para evitar que el espacio accione botones, puedes usar `boton.setFocusPolicy(Qt.NoFocus)`, para que el botón no "pesque" a la tecla espacio.

Avísame si te funciona!
