### ISSUE TITLE
Bonus Configuración de parámetros

### ISSUE THREAD

**Issue by furcelay** [IIC2233/syllabus#954]
Hola!
Cuando en el enunciado se especifica que la ventana de configuración permita **editar todos los parámetros** ¿Quiere decir realmente todos los que yo haya definido en parametros.py?¿O basta con los del enunciado?

El problema es que tengo algunos parámtros que serían muy difíciles de editar en ese formato (listas, diccionarios, parametros definidos con operaciones de varios parámetros, etc.)

**Comment by tomasgv** [comment]
Hola @furcelay !!

Perdón por la demora 😔 , pero es como dices: para el _bonus_ basta con permitir editar los parámetros mencionados en el enunciado, es decir, los que tienen color azul.

Saludos! ☕  🐱

**Comment by furcelay** [comment]
Gracias!! :smile:
