### ISSUE TITLE
Problema con importacion de los archivos.ui

### ISSUE THREAD

**Issue by MaxBrinck** [IIC2233/syllabus#954]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ]x De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola, se que ya hay  hartas issues del problema pero nada me arregla el codigo. Me tira que un moduleimporterror porque no exite un archivo_rc, ya lo genere y sigue saliendo. Porfavor ayuda

**Comment by JuaniAndres** [comment]
Hola @MaxBrinck 
Puedes subir tu código a tu repositorio para poder revisarlo
