### ISSUE TITLE
Problema QTimer

### ISSUE THREAD

**Issue by vtunon7** [IIC2233/syllabus#955]
Hola! Estoy teniendo un problema al querer parar un QTimer. Cuando hago self.timer.stop() se me queda pegado todo el programa y muere. Hay alguna forma de parar los QTimers sin que muera todo el programa?

**Comment by danckoo1** [comment]
hola, ese comportamiento puede estar ocurriendo por diversas causas, sin embargo, debería ser posible detenerlo tal como tu lo mencionas sin problemas. Si quieres puedes hacer un push a tu repositorio para poder verlo con mas detalle.

**Comment by vtunon7** [comment]
Ok, gracias. Eso si cambie la parte que fallaba, voy a agregarlo comentado para que te ubiques.

**Comment by vtunon7** [comment]
Ahí esta subido, creo que me fallaba porque el stop() estaba dentro de un loop.
