### ISSUE TITLE
Drag and drop funciona a veces 

### ISSUE THREAD

**Issue by diego-ayala-2000** [IIC2233/syllabus#955]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola, que me pasa que a veces mi drag and drop funiciona y otras veces no. Creo que es problema de mi computador. Probaría en otro pero no tengo. Si se puede podrían ejecutar mi codigo para confirmalo porfavor.

**Comment by danckoo1** [comment]
Hola! Ya hiciste un push a tu repositorio para probarlo?

**Comment by diego-ayala-2000** [comment]
No te preocupes ya me consegui como probarlo. Gracias de todas maneras
