### ISSUE TITLE
Malas practicas con Qtimer y señales

### ISSUE THREAD

**Issue by felipefuentesporras** [IIC2233/syllabus#956]
Para usar Qtimer, ¿este se tiene que relacionar con el frontend directamente? Que mis QTimers se relacionan directamente con mi backend y esta va 'subiendo' la señal hasta la clase principal que se encarga de mandarle la señal al frontend. El juego me funciona sin problemas, pero no se si hacer una cadena de señales es la forma más correcta de llegar al fronend.

**Comment by jitorcas** [comment]
Hola! @felipefuentesporras 

Con respecto a tu duda, según lo que describes no le veo el problema a que tu `back-end` tenga la **lógica** del programa y tu `front-end` sea la **interfaz gráfica**. 
Lo que si me genera un poco de ruido, es el concepto de *'cadena de señales'* que mencionas, lo cual podría estar relacionada a una baja cohesión de tu programa.
Para que te quede más claro, te invito a revisar el material subido en la semana 9, lo cual explica con profundidad estos conceptos. 
[semana-09/4-diseño-front-back.ipynb](https://github.com/IIC2233/contenidos/blob/master/semana-09/4-dise%C3%B1o-front-back.ipynb)
éxito en la tarea! 💯
