### ISSUE TITLE
Asumir tipo última flecha

### ISSUE THREAD

**Issue by jorgetf-desing** [IIC2233/syllabus#956]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola, me gustaría saber si se puede asumir que la última flecha no va a ser dorada ni de hielo, con el fin de que el resumen de la ronda aparezca al momento de capturar la última flecha, y también porque la de hielo ya no tendría utilidad ya que no quedarían más flechas para ralentizar

**Comment by knight-who-say-ni** [comment]
Hola @jorgetf-desing !!

No puedes asumir eso. Si el tiempo que se debe ralentizar producto de una flecha hielo es menor que el tiempo que queda de juego, el juego deberá terminar en el tiempo que debe.

Saludos!!

**Comment by jorgetf-desing** [comment]
ok, gracias!
