### ISSUE TITLE
Animación elementos

### ISSUE THREAD

**Issue by Mario-uc** [IIC2233/syllabus#957]
Cuando hago que un label cambie de imagen, este objeto se me ve más pequeño. No sé a que se debe :(

**Comment by benjavicente** [comment]
El tamaño de la imagen nueva es igual al tamaño de la imagen anterior?
Puede pasar que, como el objeto ocupa una menor proporción respecto a la imagen anterior, al adaptar la imagen al tamaño del label este se ve más chico.

**Comment by cristozille** [comment]
Hola @Mario-uc, puedes utilizar el comando label.resize(tamaño x, tamaño y) y label.setScaledContents(True) cada vez que cambias la imagen para asegurarte que el tamaño se mantenga.
