### ISSUE TITLE
mostrar clientes

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#959]
Hola.
Resulta que estoy un poco confusa en cómo hacer que un cliente aparezca sentado en una silla. Lo que hice fue tomar la misma coordenada de la mesa en que se sentará el cliente. Entonces cree un ```QLabel``` para ese cliente y lo quise mostrar en la misma coordenada de la mesa, osea que debería aparecer "encima" de la mesa.
```

        label = QLabel(self)
        label.setGeometry(QtCore.QRect(x, y, 25, 35))
        label.setPixmap(QPixmap(ruta_label).scaled(25, 55))
        label.move(x, y)
        label.show()
        label.raise_()
```
Se supone que ```x``` e ```y``` están definidos como int y corresponden a la misma coordenada de esa mesa.
Pero no se muestra nada...
Por qué? Y qué podría hacer para solucionarlo?

**Comment by Camila-sty** [comment]
helpmeee:(

**Comment by Alonsinho1** [comment]
Hola, el error se podria deber a muchos problemas:

- Asegurate que la ruta efectivamente exista y sea la correcta. te recomiendo ocupar el metodo os.path.exists() para esto.

- Lo otro que podria ser es las coordenadas x e y se esten entregando mal.

- A pesar de que hagas raise_() quizas, luego le hagas raise_() a los otros labels en alguna funcion, entonces este aun asi queda en el fono del mapa

**Comment by Camila-sty** [comment]
Los primeros dos puntos que me mencionas, ya los ví, y están bien. 
No entendí tu último punto..¿?

**Comment by Alonsinho1** [comment]
Por ejemplo, en alguna parta tienes una funcion que se llame onda actualizar mapa y en esta le haces raise_() a todos los posibles labels. Entonces creas tu cliente y le haces raise_() luego se ejecuta la funcion que dije antes y hace que todos los labels se levanten quedando al cliente por debajo del mapa.

Otra posibilidad es que estes creando el label del cliente pero no almacenes este label en ninguna variable. Una forma de hacer esto es creando el label y despues almacenandolo en una lista que se llama lista_clientes. Algo de ese estilo

**Comment by jamigone** [comment]
Hola @Alonsinho1!
Tengo el mismo problema que @Camila-sty, pero al mostrar las mesas cuando creo un juego nuevo. Ya revisé que la ruta esté bien escrita, que las coordenadas estén ok, que las mesas las guardo en una variable de la clases y las mesas son los únicos labels -hasta ahora- que he ejecutado raise_()
Ocupé el método de QWidget: isVisible(), tal cual como dijo @danckoo1 en la issue #806, y efectivamente no están visibles las mesas (return False).
No sé qué podría estar pasando, hice git push por si puedes verlo (pliss), es el método "actualizar_mesa" del archivo "Ventana_juego.py".
Pd: Dejé los print de las coordenadas y del return isVisible.

**Comment by jamigone** [comment]
help pliss 😢 ⏳

**Comment by Alonsinho1** [comment]
@jamigone 

Hola! Esot un poco confundido. Es esto lo que deberia ver al ejecutar el main.py?


![image](https://user-images.githubusercontent.com/53799932/83953593-7179b980-a80f-11ea-8de3-138eb5c5d220.png)

**Comment by fdoflorenzano** [comment]
Hola @jamigone,

Tu programa no mueve los labels, están todos acumulados en la esquina superior derecha.

**Comment by Alonsinho1** [comment]
@jamigone 

Me sumo al comentario de @fdoflorenzano, efectivamente estas seteando todos los labels en la misma posición, entonces quedan todos encima uno de otros. Falta implementar el metodo move() en los labels. En cuanto por que a mi se me veía raro, no te preocupes, probablemente copie la carpeta de sprites.

**Comment by jamigone** [comment]
Sii @fdoflorenzano, en la imagen de @Alonsinho1 se ve que están todos esos labels juntos, no se me había ocurrido sacar la imagen de fondo de la cafetería para comprobarlo. Efectivamente me faltaba la linea de código donde ocupaba el método move() 😅, ahora sí se muestran y posiciones random.
¡Gracias a ambos!
