### ISSUE TITLE
Funcionamiento de probabilidad de flechas

### ISSUE THREAD

**Issue by barbarafcp** [IIC2233/syllabus#959]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Tengo una duda con respecto a la probabilidad de las flechas, por ejemplo, si elijo que las probabilidades sean:
PROB_NORMAL = 0.6
PROB_FLECHA_X2 = 0.2
PROB_FLECHA_DORADA = 0.1
PROB_FLECHA_HIELO = 0.1
Esto significa que si elijo una al azar, si me sale de 0 a 0.6 es una flecha normal, de 0.6 a 0.8 es una flecha x2 y así?

**Comment by manearaya** [comment]
Hola @barbarafcp!

Supongo que en la última línea te refieres a que elijes un número al azar para decidir que flecha debe caer, y eso estaría correcto: según tus parámetros, si cae entre 0 y 0.6 sería normal, entre 0.6 y 0.8 sería X2, entre 0.8 y 0.9 sería flecha dorada y entre 0.9 y 1 sería flecha hielo (da lo mismo el orden, lo importante es que cada flecha tenga su probabilidad bien representada).

Espero haber respondido tu pregunta!

**Comment by barbarafcp** [comment]
yaa! gracias!^-^
