### ISSUE TITLE
Interaccion del usuario con el programa

### ISSUE THREAD

**Issue by alexaptib** [IIC2233/Syllabus#96]
Tengo una duda de como el usuario interactúa con el juego. Se le tiene que dar las opciones que el tiene para hacer? Me refiero a hacer un respuesta = input("Que quieres hacer?"), para luego analizar 'respuesta' y ver que se debe hacer? Si es así, podría dar las opciones enumeradas para facilitar el uso del juego?

**Comment by mfanselmo1** [comment]
Hola! Si se puede dar las opciones enumeradas, pero tienes que asegurarte que el programa nunca se caiga por un input no esperado como sale en el punto 11 del enunciado.  Tambien puedes decir que se esperan los numeros para que se entienda mas facilmente.
