### ISSUE TITLE
Actualizar atributos del jugador

### ISSUE THREAD

**Issue by alexabedecarratz** [IIC2233/Syllabus#96]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola! 
Tengo la duda de si una vez empezado el juego con un determinado jugador, al cual a lo largo del juego se le cambian sus atributos, se vuelve al menu de inicio y se elige ese mismo jugador, ¿los atributos del jugador se reinician o se actualizan con los que quedaron luego de haber jugado ya con este?.

**Comment by Gsalinas1506** [comment]
Hola!

**NO**. Al volver al menú de inicio cuenta como que "iniciaste una partida nueva", por lo que los stats de cada jugador deben volver a los valores indicados en jugadores.csv.

Exito con la tarea! 🎲️🃏️
