### ISSUE TITLE
Importar libreria collections

### ISSUE THREAD

**Issue by jamigone** [IIC2233/syllabus#96]
Hola! revisando el material de la semana 1  (3-colas) noté que importan la libreria collections. Intenté importarla en mi pc, pero no me la reconoce (invalid syntax) aunque cuando pongo el mouse encima mi editor  me muestra para que sirve esta libreria. En fin, asumí que no la tengo instalada, pero no encontré en google cómo descargarla. Ayuda plis :)

**Comment by jamigone** [comment]
Update: me parece que es un problema general porque tampoco me reconoce la libreria random.

**Comment by Tito0906** [comment]
Holaa @jamigone, la libreria collections viene con python 3, por lo que no es necesario descargarla. Sobre el problema, ¿cómo estas importando la libreria? ¿Estas usando Visual Studio u otro editor? ¿Cuál es el mensaje que te aparece?

**Comment by jamigone** [comment]
tengo la versión 3.7.4 y sí, estoy usando VSC.

import collections

output: "invalid syntax"

También cambié el collentions por random, pero me aparece el mismo mensaje de error.

**Comment by jamigone** [comment]
Ya lo resolví, tuve que ocupar el comando exit() en el terminal de python. Tenía este mismo error :)

https://stackoverflow.com/questions/51540391/invalid-syntax-error-when-running-python-from-inside-visual-studio-code
