### ISSUE TITLE
Duda sobre los archivos que deben ser subidos.

### ISSUE THREAD

**Issue by ManuelOvalle** [IIC2233/Syllabus#96]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda
Hola! Me quedaron un par de dudas con este tema. Se supone que hay que subir los archivos necesarios para la ejecución del programa. Los archivos parametros.py y tablero.py son provistos y recomendados para añadir en el .gitignore, sin embargo, son necesarios en mi programa para que funcione. Los subo de todas maneras? O los ayudantes al corregir tendrán estos archivos y no será necesario subirlos. Por último, no me quedó claro si la carpeta partidas y el archivo puntajes.txt deben ser subidos vacíos? O pueden contener algún archivo o contenido producto de las pruebas que se ejecutaron al programa.

**Comment by vicentethomas** [comment]
Hola! Los archivos que vienen dados con el enunciado (tablero.py y parametros.py) puedes añadirlos al .gitignore ya que los ayudantes tenemos ese archivo. Con lo otro que comentas, como van a ser generados con tu código no es necesario que los subas, pero de igual forma que sepas que en esta entrega no hay descuento ni se evalúa el .gitignore.
