### ISSUE TITLE
Duda con respecto a cambio de lineas en tarea.

### ISSUE THREAD

**Issue by JZapataMA** [IIC2233/Syllabus#96]
### El cambio de lineas es indicado por elestudiante?
Hola!
Tengo una duda en como es el funcionamiento del cambio de lineas del codigo para la Tarea 0, de ser requerido, la indicacion de este cambio ha de ser indicada por el estudiante? o el ayudante corrector dara cuenta de esto?

**Comment by matiasmasjuan** [comment]
Hola @JZapataMA !

La idea del cambio de líneas es poder corregir algunos errores o mejorar ciertas funcionalidades de la tarea. Con respecto a tu pregunta, pueden ser **ambas**. En primera instancia, la idea es que el estudiante sea capaz de notificar mediante su ```README.md``` la(s) línea(s) de código que desea modificar. Para ello, se debe mencionar **cuál linea**, **el contenido de esa linea**, **el archivo donde está ubicada** y **la nueva linea que será reemplazada en su lugar** para cada linea que se quiere modificar. Para el caso de entregas atrasadas, también es posible notificarlo en el formulario respectivo. Además de esto, existe la posibilidad de que si el/la ayudante corrector/a encuentra un error que impida la correcta funcionalidad de la tarea (como algún error en el ```path``` o de ```sintaxis``` en alguna línea específica) este sea capaz de corregirlo aplicando el descuento correspondiente de cambio de líneas, de tal modo que el programa funcione corectamente.

Saludos!
