### ISSUE TITLE
Recursos Utilizados 

### ISSUE THREAD

**Issue by Rudyjb24** [IIC2233/Syllabus#96]
Un usuario ANAF puede hacer consultas especificas sobre los incendios que incluye una lista de recursos utilizados en cada uno. Esto se refiere una lista de cada recurso con su id propio o bien algo del estilo: se utilizaron 3 helicópteros 1 avión 5 brigadas y 1 bomberos?

**Comment by rpalmaotero** [comment]
Se deben individualizar cada uno de los recursos ocupados. Pueden ser los identificadores separados por comas.
