### ISSUE TITLE
Duda sobre integrantes mínimos en el grupo

### ISSUE THREAD

**Issue by franciscareti** [IIC2233/syllabus#96]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! En el enunciado aparece que cuando uno crea un grupo, este debe tener dos integrantes como mínimo. Si después de haber sido creado, usuarios abandonan el grupo quedando un solo integrante, el grupo debe eliminarse? o puede quedar con esta única persona si es que esta decide no abandonarlo? Gracias!!

**Comment by hsazos** [comment]
Hola @franciscareti!

Ya que no esta explicito en el enunciado, queda a criterio suyo como manejar esos casos. Tienen que ser consistentes en todos los grupos en que suceda eso. Saludos y ánimo con la tarea! 🦕
