### ISSUE TITLE
Clase Juego

### ISSUE THREAD

**Issue by jalliende** [IIC2233/syllabus#96]
Es necesario crear a la clase Juego, o puedo modelar las funciones de esta clase dentro de mi código principal? Ya que en el feedback sale señalado, pero en la rubrica de evaluación no esta especificado

**Comment by iqacevedo** [comment]
Hola !
Esos comentarios del feedback apuntaban a aquellos que usaron una clase ´Juego´ en su modelamiento. Algunos comentarios que mencionaban ´Juego´ apuntaban a las responsabilidades que les estaban dando a esa clase (cuando la definían). 

No podemos decirte como es que debes modelar tu tarea, pues uno de los objetivos es evaluar modelamiento. Tu modelamiento debe ser reflejo de lo que se pide en el enunciado, debes decidir si una clase de esas características es realmente necesaria, o bien basta con modelarlo como dices.
