### ISSUE TITLE
Uso de properties sin setter

### ISSUE THREAD

**Issue by benjastraub** [IIC2233/syllabus#96]
Hola, estaba viendo el contenido de la semana 2 y quedé con dudas respecto a cuándo vale la pena usar properties y cuándo no.

En el ejercicio 2 por ejemplo entiendo la utilidad ya que hace las verificaciones al instanciar el objeto o cuando queramos modificar los atributos. Además como recibe valores de fuera de la clase se utiliza el `getter` y `setter`. 

Pero en el ejercicio 1 **(spoiler alert)** como depreciación acumulada no ocupa un valor externo de la clase, no se utiliza un `setter` y se implementa algo como esto:
```
@property
def depreciacion_acumulada(self):
    return (self.precio / 10) * (datetime.datetime.now().year - self.fecha_de_compra)
```
¿Por qué es mejor en este caso implementar la property en vez de llamar directamente a `depreciacion_acumulada()`?

**Comment by jjaguillon** [comment]
Estimado

El uso de `getter` del caso del ejercicio 1, se refiere a un valor que quieres que se comporte como atributo, pero cuyo valor es **dinámico**, es decir, que cambia si alguna otro de los valores que depende (datetime.now, fecha_de_compra, precio) cambia.

Por otra parte, el caso del ejercicio 2, el uso de _properties_ se justifica debido a que el valor de la _property_ tiene ciertas condiciones, de ahí el uso de `setter`, mientras que el uso de `getter` es simplemente para definir que ese valor es _property_.

**Comment by dgzmr** [comment]
@jjaguillon hola, en el caso de la _property_ `username` como se justifica el `setter` ?

**Comment by jjaguillon** [comment]
@dgzmr Es para **escalar** el programa.

**¿Qué significa eso?**

En el contexto actual, el `setter` no parece ser necesario. Sin embargo...

Imagina el siguiente caso: 

Ahora, dado que la red social DCCgram escaló a más 100000 usuarios, quiero que los Usuarios tengan la siguiente condición:

- `username` debe contener 8 caracteres, con al menos una letra y un número.

Entonces tener previamente la property definida, nos permite cambiar rápidamente la condición del `setter`.

**Comment by dgzmr** [comment]
@jjaguillon Gracias por la respuesta, tengo otra duda sobre el ejercicio 2.
En el `__init__` de la clase usuario se tiene por ejemplo `self.__username = None` y luego `self.username = username`. No sería mas eficiente poner `self.__username = username`??

**Comment by jjaguillon** [comment]
@dgzmr Revisa la Issue #102
