### ISSUE TITLE
creacion de usuarios

### ISSUE THREAD

**Issue by nmaturana97** [IIC2233/Syllabus#96]
hola queria saber si puedo asumir que nadie se creará un usuario con el simbolo ";" en el nombre

**Comment by cilopez** [comment]
Puedes dejarlo en el readme  de tu tarea, aunque en la vida real siempre trataran de bugear tus programas :sweat_smile: , saludos!

**Comment by jtagle2** [comment]
![image](https://user-images.githubusercontent.com/6934080/29473129-ebe52592-842c-11e7-8eb1-7bd192516bac.png)

Saludos!

**Comment by nmaturana97** [comment]
ok, pondre las excepciones jajaja
