### ISSUE TITLE
Consulta Drag and Drop

### ISSUE THREAD

**Issue by TdelrioC** [IIC2233/syllabus#960]
Hola, alguien sabe si hay alguna manera de con MouseMoveEvent() o algun otro mouseEvent de poder hacerle click a unQlabel creado en qtdesigner, moverlo, soltarlo, y que me entregue una tupla del rect donde se dejo ese Qlabel (lo que seria el drag), para con esa info mandarla al backend, crear el objeto, ver que la pos sea valida etc... y luego actualizar el front con la nueva info del back para que se muestre la mesa  o chef(lo que seria el drop). Esto sin usar las funciones drag and drop, ya que si hay una manera de poder obtener esa tupla me saldria muy simple la implementación. 

Gracias!!

**Comment by cristozille** [comment]
Hola! La mejor forma de hacer esto es implementando el drag and drop mencionado en la issue #785 donde esta el link a la documentación de este. Creo que no hay otra forma de poder arrastrar un sprite, así que te recomiendo hacerlo de esa forma.
