### ISSUE TITLE
Distribucion de puntajes T02

### ISSUE THREAD

**Issue by Araos827** [IIC2233/syllabus#961]
Hola! Donde esta la distribucion de puntajes de la tarea 2? la busque y no la encuentro D:

**Comment by benjavicente** [comment]
[Aquí está](https://docs.google.com/spreadsheets/d/1FS5FFrtZ1jA66KazWNKcRXjpXWOEW-6dpA1ILD8iVbk)

**Comment by Araos827** [comment]
thnx <3
