### ISSUE TITLE
Problemas con cheatcodes 

### ISSUE THREAD

**Issue by jorge-ovalle** [IIC2233/syllabus#961]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by jorge-ovalle** [comment]
Hola! Tengo un problema con los cheatcodes. Implementé una manera para detectar los cheatcodes que debiera funcionar, sin embargo mi programa no reacciona. En particular, para el cheatcode ```M+O+N``` se debiera notar la subida de dinero en la interfaz. Revisé todas las señales y todo parece estar en orden. El procesamiento del cheatcode lo tengo implementado en la clase ```LogicaVentanaJuego``` del archivo del backend ```logica_ventanas.py```. Esta todo en el repositorio. Espero me puedan ayudar :))

**Comment by knight-who-say-ni** [comment]
Holaa @jorge-ovalle !!

Dos preguntas: el cheatcode NIV funciona correctamente??, y cuando compras un pingüirin, esta compra se ve reflejada en la tienda?? 
Si el problema es lo primero, entonces quiza tengas que arreglar el como interpretas los cheatcodes, si es el segundo, quiza es porque en la función de actualizar tienda le estas cambiando el texto a algun otro QLabel.

 Avisame si es alguna de esas, ya que una mirada a tu codigo me dice que tus señales están bien 😄 .

Saludos y exito en la tarea!!

**Comment by jorge-ovalle** [comment]
El niv tampoco funciona. Cuando localizo un pinguirin en alguna de las casillas habilitadas se descuenta lo que cuesta dicho pinguirin.

**Comment by jorge-ovalle** [comment]
Alguna idea jaja? He estado revisando y literalmente no encuentro lo malo en la modelacion de los cheatcodes

**Comment by knight-who-say-ni** [comment]
Holaa!! Tu error es que en logica_ventanas, con excepción de la linea 52, escribes `M0N` en vez de `MON` (con un cero en vez de o mayuscula). Probablemente lo escribiste mal una vez y el error persistio despues de copiar y pagar esa parte 😄.

Saludos y exito con lo que queda!!!

Pd: perdon por la demora en responder 😬
