### ISSUE TITLE
Aceleración del QTimer del juego en cada ronda

### ISSUE THREAD

**Issue by arturobugueno** [IIC2233/syllabus#962]
Tengo un problema cuando comienzo una ronda nueva. En resumen, cuando se juega la primera ronda desde que se abre el programa (cargando una partida o creando una nueva) no hay ningún problema con la velocidad de la señal del QTimer que controla el tiempo de la ronda. Sin embargo, al continuar jugando, el QTimer va subiendo cada vez su velocidad: si en la primera ronda el tiempo avanzaba normalmente, la ronda siguiente un segundo equivalen a dos en el juego, en la tercera, un segundo de tiempo normal son tres segundos en el juego, y así sucesivamente.
He buscado en varias partes pero no le logrado encontrar algo que lo solucione.

**Comment by danckoo1** [comment]
Mmh es un tanto difícil determinar la causa, pero a primera vista se me ocurre que quizás a medida que creas rondas vas creando qtimers adicionales que hacen lo mismo, por lo que empiezan a multiplicar la cantidad de veces que se emite la señal, provocando que parezca que el timer acelera, si no es el caso avísame para seguir pensándolo :)

**Comment by arturobugueno** [comment]
Solo tengo un QTimer. Lo único que hago cada vez que empiezo una ronda es determinar el intervalo (que siempre hago que sea el mismo). Ademas de eso, lo único que hago para volver a "resetearlo" es eliminar el contador de segundos (donde iba guardando el tiempo de la ronda) y parar el timer.

**Comment by danckoo1** [comment]
Hola mil disculpas por atrasarme en responder. Lo qué pasa es que cada vez que pasas a una nueva ronda haces el timeout.connect del timer, por lo que cada vez que se emite la señal la envía por así decirlo muchas veces a la misma función, porque los connect se van acumulando. Para solucionarlo tan solo debes hacer el Connect de tu timer una única vez en tu init y el problema debería solucionarse!

**Comment by arturobugueno** [comment]
Eso mismo era. Muchas gracias!
