### ISSUE TITLE
Requisito de pinguirin para iniciar ronda/baile

### ISSUE THREAD

**Issue by Jamesmoreno21** [IIC2233/syllabus#963]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola! Tengo una duda muy puntual, pasa que programé de forma que al ingresar a la ventana principal de DCCumbia, el usuario no puede comenzar la partida a menos que elija un pinguirin, pues el botón de comenzar partida está deshabilitado en ese momento hasta que ponga uno en la pista de baile, pero el enunciado dice que se debe emitir un aviso cuando intente iniciar, ¿puedo mantener la forma en que lo tengo? pues tengo un label que señala que para iniciar debe elegir primero un pinguino y que después podrá comenzar la partida.

Saludos y gracias de antemano 😄

**Comment by kadroguett** [comment]
Hola @Jamesmoreno21, como dice el enunciado debes emitir una alerta cuando se intenté iniciar sin Pinguirines :(. Espero que esto no te atrase mucho, Éxito en tu tarea!
