### ISSUE TITLE
Colisión chef y mesero

### ISSUE THREAD

**Issue by jorgemayol** [IIC2233/syllabus#963]
Hola!!! ¿El mesero puede dar la orden de cocinar a un chef cuando lleva un snack?
Pregunto esto porque cuando mi mesero recoge el snack y se sigue manteniendo la tecla que lo hace avanzar, el chef se pone a cocinar inmeditamente y se ve como si el chef hubiese fallado, pero solo fue que hubo 2 colisiones  seguidas con el chef.

**Comment by bvasquezm** [comment]
Hola @jorgemayol!

Debido a que no se señala explícitamente cuando falla el chef, podrías aplicar la probabilidad en cualquier momento (cuando termina de cocinar, entremedio, etc). Si te acomoda puedes incluir un delay para que no colisiones dos veces, eso si tendrías que crear un **nuevo parámetro** que indique la duración de este delay. En otras palabras, puedes arreglarlo como te acomode, pero debes justificarlo en el Readme. 
Saludos!!

**Comment by jorgemayol** [comment]
ok gracias!!
