### ISSUE TITLE
imagen mesero sobre la imagen de mesas y bajo la imagen de mesas

### ISSUE THREAD

**Issue by CamilaArgomedo** [IIC2233/syllabus#964]
Hola! cuando genero las mesas, el chef y el mesero para jugar el juego guardado me sale el mesero por debajo de las otras imágenes y para jugar un nuevo juego me aparece por arriba, por lo que no calza lo que había determinado antes como el choque con el objeto. ¿Existe alguna forma de controlar esto?

**Comment by danckoo1** [comment]
Hola, básicamente para controlar qué imagen es la que queda por encima debes tener en cuenta el orden en que vas creando los labels, por lo que probablemente cuando te queda el mesero bajo el resto de las imágenes es por que lo creas primero y posteriormente lo tapas con el resto de labels. Podrías asegurar la que imagen queda encima utilizando el método `raise_()` luego de crear todos los labels

**Comment by CamilaArgomedo** [comment]
muchas gracias!
