### ISSUE TITLE
uso de hide y close

### ISSUE THREAD

**Issue by eliasbruchfeld** [IIC2233/syllabus#964]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

¡Hola! Si tengo una ventana (mainwindow, qwidget, etc) y la quiero cerrar, ¿cual es la diferencia entre hacerlo con self.hide y self.close? Aparte del obvio significado de las palabras hide y close, que hace un método que no haga el otro.

**Comment by kadroguett** [comment]
Hola @eliasbruchfeld, la diferencia es que el método `hide` conserva la ventana en la memoria, mientras que `close` la destruye. De forma que si quieres volver a usar la ventana debes preferir utilizar `hide`.
