### ISSUE TITLE
Suposición parametros teclas para flechas y teclas para cheatchodes

### ISSUE THREAD

**Issue by riadeane** [IIC2233/syllabus#965]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola! 

Quería saber si debería suponer que nunca van a cambiar los parámetros de las teclas para las distintas flechas por aquellas teclas que permiten hacer cheatcodes (incluyendo los del bonus) o la tecla P para la pausa :) 

Gracias de antemano!

**Comment by aljara97** [comment]
Hola @riadeane! te refieres a que en el caso de la pausa esta siempre se implementará con la tecla P y los otros cheatcodes con las combinaciones del enunciado? Si es así, sí, esto no varía, siempre la pausa se producirá al presionar la tecla P, el dinero aumentará en `DINERO_TRAMPA` (esto sí es un parámetro :eyes:) al apretar M-O-N y el nivel terminará al presionar N-I-V.

Espero haber aclarado tu duda, cualquier cosa quedo atento 🐧

**Comment by riadeane** [comment]
Sii. Mi pregunta iba por el tema de que las teclas para reconocer las distintas flechas son parametros (`FLECHA_ARRIBA = "w"`, por ejemplo). Entonces, puedo asumir que nunca las van a cambiar a P, M, O, N, I, o V?

**Comment by aljara97** [comment]
Sí, nunca cambiaremos las flechas a usar para las distintas funcionalidades

**Comment by riadeane** [comment]
Gracias! :)
