### ISSUE TITLE
Duda sobre modularizacion 

### ISSUE THREAD

**Issue by aipostigo** [IIC2233/syllabus#965]
Tengo un archivo que contiene a mi ventana principal y para agregar los bonus me pasaria de las 400 lineas, como puedo hacer para agregarle metodos a mi clase de ventana principal desde otro archivo?

**Comment by cristozille** [comment]
Hola @aipostigo, puedes aplicar herencia de clases, creando una segunda con los métodos del bonus que herede de la primera. De todas formas augúrate de que este en el Readme :)
