### ISSUE TITLE
Caída del programa despues de jugar en niveles dificiles

### ISSUE THREAD

**Issue by fedezang** [IIC2233/syllabus#966]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! mi programa me tira el siguiente error
QThreadPipe: Unable to create pipe: Too many open files
QEventDispatcherUNIXPrivate(): Cannot continue without a thread pipe
zsh: abort      python3 main.py

esto me ocurre después de jugar los niveles difíciles, pero antes no me sucedía. será simplemente que mi computador no puede manejar el programa, o será un problema de mi código?
Los threads los almacenaba y los borro despues de una partida, por lo que no creo que sea problema de los threads
Y cuando lo corro en vscode no parece haber problema.

**Comment by furcelay** [comment]
Hola @fedezang !

Perdón por la demora 😓 , he averiguado sobre tu error y me parece que no es un tema directamente de tu programa sino una limitación del sistema operativo ya que MacOs restringe el número de archivos que pueden ser abiertos por *thread* (ya que el terminal es `zsh` intuyo que tienes un Mac, por favor comenta si me equivoco). Al menos no he logrado replicar tu error en mi OS, y me parece que no debería ocurrir si quien corrige tu tarea no usa Mac. 

Estoy esperando a que un ayudante con Mac pueda ver tu caso, podrías también modificar el modelamiento para que se abran menos archivos a la vez pero como estamos cerca de la hora de entrega te recomiendo lo siguiente:
*  Indica en tu README cuando ocurre el error y bajo qué condiciones. También explica que es una limitación del OS (indica que OS y la versión) y no directamente del programa y asegúrate de citar esta issue (basta con poner que es la issue #966).
*  Si es un problema para avanzar en tu tarea puedes probar con [esto](https://wilsonmar.github.io/maximum-limits/), yo no he podido probarlo :c pero si te funciona también te recomiendo indicarlo en tu README.

Saludos! 😄

**Comment by fedezang** [comment]
Perfecto, gracias!. Como igual corría en vscode lo pude probar y funcionaba.
