### ISSUE TITLE
Tiempo de espera bocadillo 

### ISSUE THREAD

**Issue by sofiaemd** [IIC2233/syllabus#966]
Hola! En el enunciado dice en la sección sobre bocadillos que el tiempo de espera se cuenta desde que se pide en el mesón, mientras que en clientes dice que se entrega propina dependiendo del tiempo transcurrido desde que llegó el cliente. ¿Cuál de estos dos tiempos es el correcto para calcular la calidad?
Muchas gracias

**Comment by jitorcas** [comment]
Hola @sofiaemd!

Estuve leyendo de nuevo el enunciado y no encontré en la sección *clientes* la parte donde se dice que la propina se calcula dependiendo del tiempo de espera del cliente, ¿Podrías especificar dónde aparece eso?
Con respecto a la **calidad**, se calcula en base a lo que sale especificado en **3.3 Bocadillos / calidad del pedido**, por lo que sería el tiempo desde que toman el pedido del mesón y se lo entrega al cliente. 
Saludos y éxito! 💯

**Comment by sofiaemd** [comment]
Lo acabo de leer de nuevo y me había confundido.. Habla de la propina y en la siguiente frase dice que el tiempo corre desde que llegan, pero se refiere al tiempo antes que se enojen 😅😅 Gracias!!

**Comment by jitorcas** [comment]
@sofiaemd 
Suele sucede! 

Mucho ánimo y éxito!
