### ISSUE TITLE
¿Para qué necesito "Pedidos totales"?

### ISSUE THREAD

**Issue by NikiHV** [IIC2233/syllabus#967]
Hola! En el enunciado apartado 3.6. dice que la entidad `DCCafe` debe tener "Pedidos totales", el cual es un `int` que contabiliza el total de pedidos por ronda. Sin embargo también dice que debe tener "Clientes ronda" que calcula la cantidad de clientes que deben aparecer por ronda. 

Como cada cliente hace un solo pedido, la cantidad de pedidos totales por ronda va a ser igual a la cantidad de clientes que vengan, por lo que no le encuentro sentido implementar ambos, ¿puedo NO implementar "pedidos totales"? 
En su lugar me serviría más implementar un "pedidos perdidos".

**Comment by bvasquezm** [comment]
Hola @NikiHV!

Entiendo lo que dices, pero el parámetro `PEDIDOS_TOTALES` se utiliza en una de las fórmulas. Si deseas eliminar uno de los dos parámetros, específica en tu Readme que para ambos casos utilizarás el mismo parámetro (clientes ronda y pedidos totales). O en su defecto, si aún así deseas implementar `PEDIDOS_PERDIDOS`, coméntalo de igual manera en tu Readme y no olvides utilizarlo correctamente en la fórmula respectiva.
