### ISSUE TITLE
Problema con argumento de una función 

### ISSUE THREAD

**Issue by Natydlb** [IIC2233/syllabus#967]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! me sale un error "pausar() missing 1 required positional argument: 'self', pero no es así porque en la funcion si lo tengo definido con el self, a no ser que el problema sea en la señal, pero no entiendo por qué necesitaría "self"

**Comment by manearaya** [comment]
Hola @Natydlb!

Creo que lo que está pasando es que en el main conectas las señales a la clase Flechas() y no a una instancia de ella.

**Comment by Natydlb** [comment]
pero como podría asignarle la instancia? si esta la defino dentro de la función que emite la señal, porque tampoco puedo importarla en el main, porque no esta definida como una clase o un atributo :(

**Comment by manearaya** [comment]
Eso ya depende de como modeles tu código 😅 

Si instancias a las flechas desde otra clase, podrías conectar la pausa a la clase "grande" y cambiar las flechas desde ahí, por ejemplo. Hay varias formas de implementarlo, pero no te puedo decir mucho más porque el objetivo de la tarea es que lo resuelvan ustedes 😅 

Mucha suerte!!

**Comment by Natydlb** [comment]
muchas  gracias!

**Comment by Natydlb** [comment]
hola, lo siento de nuevo, pude ingresar a la instancia de clase pero no me funciona el método acquire, ni el realease de lock , las flechas siguen en movimiento D:

**Comment by manearaya** [comment]
Hola! Perdón la demora :sweat_smile:

Lo que estás haciendo en el método de pausa de las flechas es **crear un lock cada vez que se entra en una pausa**, por lo que **no estás soltando el lock** cuando se vuelve a llamar el método. Este creo que es el problema principal.

Avísame cualquier otro problema! Voy a estar atenta.

**Comment by Natydlb** [comment]
Intente definiéndolo en el init el lock, pero tampoco me funciono :(

**Comment by manearaya** [comment]
En el último push que tienes además pasa que solo usas `lock.acquire`, y para llamar correctamente al método es `lock.acquire()`. 

Perdón por no darme cuenta de esto antes! Ahí debería funcionar bien. De todas formas quedo atenta.

**Comment by Natydlb** [comment]
Tampoco funciona:(((((

**Comment by manearaya** [comment]
Podrías hacer push? Implementé eso en el último push que tienes y sí me resultó 😅

**Comment by Natydlb** [comment]
ohhhh en serio?, subi mi ultimo push

**Comment by manearaya** [comment]
Claro, en tu push sigue la flecha. No se que había hecho pero ya está, perdón por la confusión 😅 

Creo que el problema es el hecho que estás usando un Lock(). Sirve para que no funcionen otros threads al mismo tiempo, pero la flecha en el que está el lock sigue bajando. Podrías usar una restricción en el run de la flecha, cosa que cuando se pause el run también, o podrías usar otra cosa en lugar del Lock()

Como en este caso lo que estás haciendo es esperar a que ocurra algo para que el thread vuelva a funcionar,  podrías considerar el uso de Event() (que debería estar en los contenidos), o un [QWaitCondition()](https://doc.qt.io/qtforpython/PySide2/QtCore/QWaitCondition.html).

Espero que ayude!
