### ISSUE TITLE
Problema con intersección de flechas

### ISSUE THREAD

**Issue by Natydlb** [IIC2233/syllabus#968]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! lei las issues asociadas a este problema y todas dicen que hay que ocupar el QRect y yo lo tengo puesto, pero como que esta bugeado porque a veces con mucha insistencia reconoce la flecha, pero hay veces que ni asi :( no se que hacer, ayuda :(

**Comment by aljara97** [comment]
Hola @Natydlb, podrías contarme cómo utilizas QRect de los labels y si ocupas algún método para comprobar la intersección de estos?

**Comment by Natydlb** [comment]
hola!! defino self.flecha1 y self.match_1 como dos Qrect, y voy actualizando la posición del qrect a medida que avanza la flecha, luego veo si se interceptan mediante: if self.flecha_1.intersects(self.match_1):

**Comment by aljara97** [comment]
Ok, podrías subir tus últimos cambios en tu repositorio para descartar que sea un problema de tu computador?

**Comment by Natydlb** [comment]
listo! en el archivo pista_baile.py en las funciones union() y keyReleaseEvent

**Comment by aljara97** [comment]
Hola, estuve probando tu código y de vez en cuando me funciona el método union (usas bien el método para comprobar la intersección de dos QRect). Sin embargo, sospecho que probablemente tu problema se debe a errores de modelación, ya que defines un atributo de clase que guarda la posición de una flecha y otro para una celda. Te recomiendo que revises la función `actualizar_label` y cuando la llamas, además te aconsejo usar prints de las coordenadas x e y en los métodos `union` y donde creas que sea necesario. Esto te puede ayudar a entender cómo estás utilizando los atributos y detectar algún error.

Mucho éxito y ánimo con lo que queda, cualquier duda puedes hacer una issue
