### ISSUE TITLE
Duda sobre QThreads

### ISSUE THREAD

**Issue by Araos827** [IIC2233/syllabus#968]
Hola! si tengo varias instancias de QThreads en una lista, antes de comenzar una ronda por ejemplo, y le hago run alguno, cuando este termine la instancia desaparece de la lista? o queda ahi como muerta y tengo que sacarla yo?

**Comment by cristozille** [comment]
Hola @Araos827, El QThread no desaparecería, así que tendrías que sacarlo tú una vez que termine.
