### ISSUE TITLE
Qthread y Qlabel herencia

### ISSUE THREAD

**Issue by Pelaysen** [IIC2233/syllabus#969]
hola, creé una clase que hereda de Qtread y de Qlabel, pero al partir el run() de la clase mediante clase.start(), no me corre (solo tiene un sleep y un print), pero si lo corro con clase.run()  me corre, pero no de forma paralela al programa principal, es decir, durante el sleep de aquel run, no puedo mover al mesero. ayudenme plizz.

**Comment by tomasgv** [comment]
Hola @Pelaysen!!

¿Es una sola clase con mulltiherencia de `QThread` y `QLabel`?
Si es así, deberás separarla en dos clases y comunicarlas mediante señales. No hace mucho sentido que una imagen sea un _thread_ también 🤔 

Lamentablemente, heredar de dos clases de PyQt no es soportado según la [documentación](https://www.riverbankcomputing.com/static/Docs/PyQt5/gotchas.html#multiple-inheritance).

Espero haberte ayudado! 😸
