### ISSUE TITLE
Archivo .ui en sprites y gitignore

### ISSUE THREAD

**Issue by nicolecll** [IIC2233/syllabus#969]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [ X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola, agregue imagenes a mis ventanas a traves qtdesigner, lei en una issue que esto era posible mientras tuviera los archivos .ui en la carpeta sprites, lo hice y me funciono, sin embargo segun enunciado la carpeta sprites se debe ignorar, por lo que no me queda claro que hacer en este caso. 
Trate de correr los archivos ui a otra carpeta pero las imagenes ya no se visualizan.

**Comment by knight-who-say-ni** [comment]
Hola @nicolecll !!

Una opción que tienes es subir tus .ui en la carpeta principal de tu tarea y **mencionar en tu readme** que estos deben ser movidos a  carpeta sprites 😄.

Saludos y exito con la tarea!!
