### ISSUE TITLE
input de acciones

### ISSUE THREAD

**Issue by acpopper** [IIC2233/syllabus#97]
mi duda es, si el input es de la forma "tipo_elemento;cantidad", entiendo que para "crear persona" la cantidad es la cantidad de personas a crear, pero en el caso de "recolectar_recurso" la cantidad seguida del ";" indica la cantidad de trabajadores que se asignarían a recolectar dicho recurso? (siendo que la cantidad recolectada por trabajador es una cantidad aleatoria).
Y lo segundo, en caso que el jugador haga una acción no permitida como por ejemplo construir un edificio cuando no tiene materiales se le notifica y puede decidir otra accion, en el caso de la computadora, que sucede si realizan acciones no permitidas (digamos atacar una civilizacion que ya perdió o construir un edificio que ya tiene)? Se salta su turno?
Gracias

**Comment by gatochico** [comment]
Hola! 

Efectivamente, el valor seguido del ";" en "Recolectar recursos" indica el número de trabajadores que se asignaron a dicha labor.

Respecto a tu segunda pregunta, si la acción elegida por la computadora no es válida, se salta el turno de esa civilización.

Éxito! :cat:
