### ISSUE TITLE
Control 1 / p. 10 (args y kwargs)

### ISSUE THREAD

**Issue by J0SEF4** [IIC2233/Syllabus#97]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X ] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola! Tengo una duda en la pregunta 10 del control 1 en canvas. La cual es la siguiente:

**EDIT: Pregunta 10 del control. Evitemos subir las respuestas** 😅

Respecto a esta pregunta no entiendo:
-  el desarrollo del código
-  las respuestas
-  como debo analizar cuales son las respuestas correctas
-  todavía no me queda claro el uso de *args y **kwargs, y que son.

Saludos y gracias por adelantado.
Josefa.

**Comment by tqmbanados** [comment]
Hola Josefa!
Primero que nada, me gustaría recordarte que no debes subir imágenes de código o controles respondidos a las issues o al discord. Quizás no te diste cuenta, pero en las imágenes que subiste tenías marcadas varias respuestas de la pregunta!
Trataré de contestar tus dudas una por una, pero partiré por la última.
#### ¿*args y **kwargs? 🤔 

La verdad, esta pregunta ya está contestada extensamente en el notebook de la semana 01 [*args y **kwargs](https://github.com/IIC2233/contenidos/blob/main/semana-01/7-args-kwargs.ipynb). Si luego de leer el notebook tienes dudas particulares, agradecería que me las dijeras en esta misma issue 😸. Lamentablemente hacer una explicación general de una materia esta fuera del *"scope"* de las issues, pero si me ayudas a entender **que** no entiendes, feliz te ayudo todo lo necesario.
En todo caso, en resumiendo en conceptos básicos, `*args` y `**kwargs` son una funcionalidad de Python que nos permite entregar o recibir una cantidad de variable de argumentos a una función o método. Tiene muchos usos, entre ellos:
1. Minimizar errores al entregar demasiados argumentos, o no los suficientes.
2. Facilitan el trabajo con herencia.
3. Permiten funcionalidades adicionales, como por ejemplo sumar una cantidad arbitraria de números (función `sum`), o concatenar una cantidad arbitraria de `str` (función `print`). Hay además muchas otras cosas que se pueden hacer! 

Ahora, sigo con las primeras tres preguntas.
#### Preguntas del Control 📖 

1. El desarrollo del código corresponde a la definición de una función en python genérica. En este caso, es una función de nombre `f`, que lo único que hace es imprimir en lineas separadas los argumentos que recibe. No es tan importante entender **qué** hace la función, pero si fijarse bien en **cómo** están definidos los argumentos que recibe. 
2. Cada respuesta corresponde a una posible *invocación de la función*. Hay que imaginarse un código ficticio, donde entre las varias líneas, se incluyen las distintas respuestas de la pregunta. Cada una de estas respuestas corresponde al **llamado de la función**. 
3. Las respuestas correctas son simplemente aquellas que corresponden a un llamado "válido" de la función. Un ejemplo podría ser este:
```python
def sumar_dos(argumento):
    return argumento + 2
```
Esta función recibe un número (`float` o `int`), le suma `2`, y retorna el valor. Sin embargo, hay varias formas de llamar la función que nos tirarían un error:
```python
sumar_dos("5")  # Python no puede sumar un int con un str, por lo que esta expresión es inválida
sumar_dos([5])  # Al igual que arriba, python no puede sumar un int con una list!
sumar_dos()  # la función debe recibir un argumento. En este caso también es un error!
sumar_dos(5, 7)  # la función sólo recibe UN argumento. Si enviamos dos es un error 
sumar_dos(38.6)  # Este SI es un llamado válido, pues si podemos sumar un float con un int!
```

Algo parecido debes hacer en la pregunta. Sin embargo, debes poner ojo principalmente en cuáles argumentos recibe la función y como lo hace!

#### Comentario Final

Si te fijas, la función `sumar_dos` de arriba podría justamente editarse para usar `*args` y `**kwargs` para evitar algunos de los errores que obtuvimos:
```python
def sumar_dos(*args, **kwargs):
    if len(args) > 0:
        return args[0] + 2
    else:
        return 2
```
Ahí, la función agarra **el primer argumento enviado** (`args[0]`), le suma 2 y retorna el valor. Sin embargo, podemos incluir cientos de argumentos adicionales al llamar la función. Estos no harán nada, pero al menos no tendremos un error!
Además, si no entregamos ningún argumento (`sumar_dos()`), La función lo reconoce, y retorna sólamente 2. 

¿Se te ocurren formas aún más eficientes o robustas de definir la función usando `*args` y `**kwargs`?

Finalmente, agradezco la paciencia de leer este *text wall*, y espero tu respuesta!

**Comment by J0SEF4** [comment]
Hola!
Ok, pensé que solo no se podía subir fotos de la tarea o actividades formativas, sumativas. Perdón.
Respecto a lo de *args y **kwargs: 
- no entiendo muy bien cuando se usa de esta forma: def función(*args, **kwargs):
Por ultimo, ahora me quedo claro en que debía enfocarme para dar la respuesta en esa pregunta.

Gracias.

**Comment by tqmbanados** [comment]
Oka!
Una función definida así (`funcion(*args, **kwargs`) significa que **_puede recibir una cantidad variada de argumentos_**.
Esto permite muchas funcionalidades, algunas de las cuáles ejemplificaré más abajo. Pero antes:
### ¿Cómo funciona?
Al definir una función así, estamos en el fondo creando dos argumentos adicionales: `args` y `kwargs`. El primero, `args`, es una `tuple`, mientras que el segundo, `kwargs` es un `dict`. Un ejemplo:
```python
def funcion(arg1, *args, **kwargs):
    print(type(arg1))  # la función type() retorna el tipo de objeto que es el argumento que recibe
    # En este caso, imprimiríamos el tipo del primer argumento recibido (si recibimos [1, 23, "34"], imprimiría "list".
    print(type(args))  # Esto imprimiría "tuple"
    print(type(**kwargs))  # Esto imprimiría "dict"
```

#### ¿Qué contienen estas estructuras?
La estructura definida por `*args` contiene **todos los argumentos _posicionales_ entregados al llamar la función**. Recordemos que los argumentos posicionales son aquellos que no tienen una *keyword* (o un "nombre") asociados, y la función los reconoce por su posición en el llamado. Es decir:
```python
def print_tuple(*args):
    print(args)

def print_third(*args):
    # función rara que sólo imprime el tercer argumento
    print(args[2])
        
print_tuple(1, 2, 3, "gatito", 4, 5)   # Esto imprimiría el string "(1, 2, 3, 'gatito', 4, 5)"
print_third(1, 2, 3, "gatito"; 4, 5, 6)   # Esto imprimiría sólo "3".
```

Por el otro lado, `**kwargs` contiene *todos los argumentos introducidos con palabra clave*. Recordemos que los argumentos con palabra clave son aquellos introducidos así: `funcion_x(argumento_palabra_clave="valor_argumento")`.
`kwargs` es entonces, un *diccionario*, donde la llave corresponde al **nombre** del argumento (o su  *palabra clave*), y el valor, su valor 🐱.
Aquí el ejemplo:
```python
def print_kwargs(**kwargs):
    print(kwargs)
    for key, value in kwargs.items():
        print(key, value)

print_kwargs(nombre="rayitas", especie="gato")
# Esto imprime primero un diccionario de esta forma: "{'nombre': 'rayitas', 'especie': 'gato'}". 
# Luego imprime cada elemento del diccionario por separado, con un espacio entre la llave y el valor. 
```

#### ¡Cuidado!

`*args` y `**kwargs` permiten introducir cantidades variables de argumentos, pero hay que tener ojo con la manera en la que se introducen. Justamente de eso trata la pregunta del control!

Un ejemplo, con la función `print_kwargs` de arriba podría ser el siguiente:
```python
print_kwargs(3)
# Esto nos tiraría un error, pues print_kwargs sólo recibe argumentos por palabra clave!
```

Finalmente, recuerdo que "args" y "kwargs" son solo nombres convencionales, pues lo importante al trabajar con ellos son el `*` y el `**`. Podemos usar cualquier nombre que prefiramos!

### Usos de `*args` y `**kwargs`
Hay infinitos usos para esta funcionalidad, aquí presentaré algunos de los más básicos. (Si te fijas, varios de estos ya están implementados en funcioines *built-in* de python!)

```python
def create_list(*args):
    # Esta función recibe una cantidad variable de argumentos, y retorna una lista con ellos. Análoga a list().
    new_list = []
    for arg in args:
        new_list.append(arg)
    return new_list


def multiply(*args):
    # Esta función recibe una cantidad variable de argumentos, y retorna la multiplicación de todos ellos!
    final = 1
    for arg in args:
        final *= arg
    return final

def expresion_avanzada(**kwargs):
    # Esta función recibe un diccionario donde las llaves corresponden al nombre de una operacion, 
    # mientras que los valores los "argumentos" de dicha operacion. Luego aplica estas operaciones, y suma sus resultados.
    # Si nos fijamos, sólo hay 4 operaciones posibles, pero no tienen que necesariamente hacerse todas.
    # Del mismo modo, podemos introducir más "keyword arguments" (u operaciones), y si bien la función no las realizará
    # tampoco tendremos un error
    # DISCLAIMER: hay formas mucho mejores de hacer esto jajaja, esto es sólo un ejemplo explicativo
    operaciones = tuple(kwargs.keys())   # Guardamos las llaves
    results = []
    # Realizamos cada operación, entregando como argumentos posicionales (*args) los values de cada operación.
    if "multiply" in operaciones:
         result = multiply(*kwargs['multiply'])
         results.append(result)
    if "sum" in operaciones:
        result = sum(*kwargs['sum'])
        results.append(result)
    if "max" in operaciones:
        result = max(*kwargs['max'])
        results.append(result)
    if "min" in operaciones:
        result = min(*kwargs['min'])
        results.append(result)
    return sum(results)


class DataHolder:
    # Imaginemos una clase que queremos usar para guardar datos, pero sólo de tipos específicos
    # Una vez más, hay mejores formas de lograr esto, pero sirve para ejemplificar :)
    def __init__(self, *args, **kwargs):
    """
    args corresponde a una tupla con los "tipos" de objeto que queremos guardar. Es decir, serán ints como "str", "list", "float". 
    Pueden haber strings que no pertenecen a ningún tipo de dato, pero esto no causará problemas
    kwargs corresponde a un dict con una cantidad grande de elementos. Queremos que el objeto guarde cada elemento
    como un atributo, donde el nombre del atributo es la llave. 
    Esto se puede hacer con una función muy útil llamada setattr().
    """
    for atributo, valor in kwargs.values():  
        if type(valor) in args:    # Sólo queremos guardar valores que corresponden a a ciertos tipos
            setattr(self, atributo, valor)   # Aquí estamos creando un atributo de nombre "atributo" y cuyo valor es "valor"
        else:
            print(f"El atributo de nombre {atributo} no es de un tipo permitido")

# Ejemplo de la clase de arriba
almost_json = DataHolder('int', 'float', 'bool', 'list', 'str', 'dict', 
                                           especie="gato", nombre="rayitas", peso=5.4, sobrenombres=('gata', 'ridicula'))
print(almost_json.especie)  # Printea "gato"
print(almost_json.nombre)  # Printea "rayitas"
print(almost_json.sobrenombres)  # Lanza error. 
```

Quizás me pasé un poco con los ejemplos al final, pero si logras entenderlos te puede servir mucho para entender bien args y kwargs, y sus distintos usos!

**Comment by J0SEF4** [comment]
Muchísimas gracias! Ahora lo entendí todo perfectamente. La única parte que no entendí bien fue ¿Por qué print(almost_json.sobrenombres)  # Lanza error? ¿No debería escribir: ('gata', 'ridicula')? Y si es que no, como podría escribir ambas, entonces?
Muchas gracias por su tiempo, paciencia y explicar tan detalladamente.

**Comment by tqmbanados** [comment]
Hola! Es por como definimos el `__init__` de la clase. Recuerda que sólo aceptaremos datos que sean de los tipos que entregamos al crear la clase. Dado que no entregamos el tipo `"tuple"`, no se guardan esos atributos. Por esto, al pedir ese atributo, nos lanza un error.
