### ISSUE TITLE
Duda de parametros.py

### ISSUE THREAD

**Issue by BFry712** [IIC2233/syllabus#97]
Para el caso de NUM_BARCOS y RADIO_EXP estos dos valores siempre serán igual a 3?

**Comment by BFry712** [comment]
Hola @jitorcas !
una duda, los valores los debemos preguntar la usuario o deben tomar cualquier valor aleatorio para cada partida entre [1,N x M] y mayor que 1, el numero de barcos y radio respectivamente?

**Comment by jitorcas** [comment]
@BFry712 

La idea es que el archivo `parametros.py` sea modificado antes de comenzar una partida, por lo que no es necesario que se le pregunte al usuario por la cantidad de barcos ni el radio de expansión, ya que esos valores estarán definidos antes de comenzar a jugar. 

Éxito! 💯

**Comment by sbcorrea** [comment]
> Hola @BFry712!
> 
> La idea de los parámetros es que puedan variar los valores, por lo que **no siempre** serán igual a 3. La cantidad de barcos estará entre [1, N x M] y el radio siempre será mayor que 1.

Hola! Me confundí un poco, porque el enunciado dice que si las bombas especiales tienen radio 1, se comportan como bomba normal. Entonces no me queda claro si cubrir el caso de que el radio sea 1

**Comment by jitorcas** [comment]
@sbcorrea 

Hola! Lamento lo tardío de la respuesta. La issue #179 responde a tu pregunta! 

Si debes cubrir el caso de que el radio **igual a 1** tal como dice el enunciado. Si quedas con dudas siempre puedes preguntar de nuevo o abrir una issue replanteando tu pregunta. 

Éxito en la tarea! ⚓️

**Comment by sbcorrea** [comment]
Ya, muchas gracias!
