### ISSUE TITLE
entrega de tarea

### ISSUE THREAD

**Issue by SamWeinstein** [IIC2233/syllabus#97]
hola, me acabo de dar cuenta que me llego el mensaje automático indicando que no entregue la tarea a tiempo. Creí haberla entregado, pues hice git add con todos los archivos necesarios, luego git commit (con su respectivo mensaje) y luego git push sin ningún problema, hice todo lo que nos enseñaron en el curso para subir tareas pero al parecer no fue suficiente. Ahora que me di cuenta que aparentemente no he entregado la tarea, entre a mi repositorio en el terminal y puse git status y dice lo siguiente: 

Your branch and 'origin/master' have diverged,
and have 1 and 1 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

All conflicts fixed but you are still merging.
  (use "git commit" to conclude merge)

Tal como nos enseñaron en el curso, hice lo que dice git status, es decir hice git commit y me dice lo siguiente: 

Found a swap file by the name "~/Desktop/IIC2233/SamWeinstein-iic2233-2019-2/.gi
t/.COMMIT_EDITMSG.swp"
          owned by: Sams   dated: Mon Aug 19 01:45:34 2019
         file name: ~Sams/Desktop/IIC2233/SamWeinstein-iic2233-2019-2/.git/COMMI
T_EDITMSG
          modified: YES
         user name: Sams   host name: Samuels-MacBook-Air.local
        process ID: 15517
While opening file "/Users/Sams/Desktop/IIC2233/SamWeinstein-iic2233-2019-2/.git
/COMMIT_EDITMSG"
             dated: Mon Aug 19 02:29:55 2019
      NEWER than swap file!

Tambien, tal como dice git status hice git pull y me dice lo siguiente:

error: You have not concluded your merge (MERGE_HEAD exists).
hint: Please, commit your changes before merging.
fatal: Exiting because of unfinished merge.

Busque en la materia del curso y también en los slides de la primera clase y no hay información en el curso para resolver esto. Envié a modo de evidencia la tarea por mail solo para que quedara algún registro de que la hice. Espero poder enviar la tarea algún día y poder obtener una nota mayor a 1.0 pues según mis registros hice todo lo que debía hacer y aparentemente la tarea no se puede enviar por algún extraño error con git en el terminal.
Gracias.

**Comment by entamburini** [comment]
Hola Sam,

Este tipo de dudas no van aquí. Mandaste un mail así que se te responderá por esa vía :)

Saludos! ✌️
