### ISSUE TITLE
Caracteres especiales (ñ y tildes)

### ISSUE THREAD

**Issue by nicolaspoli** [IIC2233/syllabus#97]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

He estado buscando y no logro que las "ñ" o las vocales con tilde se impriman como corresponde. He intentado el método de encoding: utf-8 entre otras cosas, pero sigo sin poder arreglarlo. Hay algo que hice que cambió estos caracteres? (porque en el archivo original no se ven así). Que puedo hacer para arreglarlo?

Gracias de antemano :D

PD: un ejemplo de lo que se imprime:  QuÃ© tal? Me gustÃ³  el hotel que reservÃ©. 10 - 4.

**Comment by Juampisaez** [comment]
Hola @nicolaspoli 
Te recomiendo si tienes una copia del archivo del syllabus, ir probando directamente. En particular podrias tratar de usar el `encoding` con `utf-8`, y si no funciona, trata sin poner nada. A un compañero tuyo le funciono.

Avisame si se soluciona :)

**Comment by nicolaspoli** [comment]
Hola! al final en el grupo pusieron un par de soluciones y una me sirvió. Poner  **, encoding = "utf-8"** al final de los open en los archivos donde se generaran problemas, en vez de al principio del .py. (ej: archivo = open("grupos.csv", "r" , encoding = "utf-8") )

Así que ya está solucionado, gracias por tu respuesta :D
