### ISSUE TITLE
Evaluación Diagrama de clases

### ISSUE THREAD

**Issue by waknaudt** [IIC2233/Syllabus#97]
Hola, escribo aquí porque un ayudante me acaba de decir que la entrega preliminar del diagrama de clases era evaluada, la cual no entregué puesto que hasta ahora pensaba que se refería al inicio del período de entrega, y en ninguna parte del enunciado de la tarea menciona que la entrega preliminar sería evaluada. Mi pregunta es: ¿Es cierto que es evaluada la entrega preliminar, o sólo la final?
En caso de que sea evaluada, ¿Perderé puntos por algo que nunca se dijo que contaba puntaje?

**Comment by mfanselmo1** [comment]
Hola! Tal como sale en la issue [#82](https://github.com/IIC2233/Syllabus/issues/82) ambos entregables seran evaluados. Recuerda que es una tarea, y seria raro que algo que se pida no sea evaluado.

**Comment by waknaudt** [comment]
El decir "sería raro" es una apreciación subjetiva. Y como es subjetiva, tal como usted lo entiende de esa forma yo lo entendí de otra. Si se dejan las cosas ambiguas entonces se da espacio para interpretaciones. Y en el enunciado de la tarea, en la sección de diagrama de clases, no se hace ninguna mención de lo que usted dice. Simplemente se dice que se evaluará el diagrama de clases, que equivale al 8% de la nota. Entonces yo entendí que lo que valía era la versión final, ya que sería "raro" evaluar dos veces un mismo punto.

**Comment by Hernan4444** [comment]
Hola, 
Para empezar, el enunciado dice Diagrama de Clases 8% y arriba aparece que son 2 entregas, una preliminar y otra final; y el preliminar sigue siendo parte del diagrama de clases. En ninguna parte se dice que es opcional. Ese fue un supuesto que debiste haber confirmado tal como lo hizo la persona de la issue #82.

Además, cabe destacar lo que se dijo en la issue #3 
> Este foro está para que compartan sus dudas. También será usado para publicar información relevante en algunos casos. Este es un medio oficial de comunicación por lo que es tu deber revisarlo periódicamente, ojalá todos los días, para que no estés desinformado/a.

Por lo tanto, de haber visto la issue como se recomendó, podrías haber visto que si era evaluado y tener tiempo para crearlo. Respondiendo tu duda final: Si, perderás una parte del puntaje por no entregar una parte de la tarea en los tiempos establecidos, pero quiero enfatizar que el preliminar  solo es un pequeño porcentaje de la tarea, no repercute mucho, asi que animo, todavía se puede optar a una excelente nota.

Saludos.

**Comment by waknaudt** [comment]
> En ninguna parte se dice que es opcional. 
Y en ninguna parte se dice que es requerido. 
> Ese fue un supuesto que debiste haber confirmado tal como lo hizo la persona de la issue #82.
Estás asumiendo que tuve una duda, la cual no tuve. De haberla tenido por supuesto que habría preguntado acá. Yo estaba seguro que lo que se evaluaba era la final, porque eso fue lo que entendí del enunciado, ya que en la parte de diagrama de clases no mencionaba una evaluación separada. No fue hasta que el ayudante me dijo que sí se evaluaba que se me formó la duda.

Además, si estuviera tan claro entonces no hubieran habido dudas, las cuales ustedes mismos confirman que hubo. Por ende, claramente no estaba claro que sería evaluada. Entonces me queda otra duda: ¿No creen ustedes que los criterios de evaluación deben ser claros y explícitos? 

> Por lo tanto, de haber visto la issue como se recomendó, podrías haber visto que si era evaluado y tener tiempo para crearlo.

La issue que linkean fue creada el Domingo, día mismo de la entrega. No sé exactamente a que hora se publicó, pero en el momento que yo revisé no vi nada. Por algo las cosas se dicen con tiempo.

>Respondiendo tu duda final: Si, perderás una parte del puntaje por no entregar una parte de la tarea en los tiempos establecidos, pero quiero enfatizar que el preliminar solo es un pequeño porcentaje de la tarea, no repercute mucho, asi que animo, todavía se puede optar a una excelente nota.

Eso es como que te roben y te digan "ánimo, es sólo un pequeño porcentaje de lo que tienes". Sigue siendo un robo. Por lo tanto el reclamo sigue siendo válido, sin importar si vale 1%, 5%, 50% o 99%.

**Comment by bcsaldias** [comment]
Estimados,

Solo para aclarar, todas las entregas preliminares llevan evaluación.

Hemos analizado el enunciado y entendemos la confusión. En la sección de "Diagrama de clases" del enunciado se habla de solo "una" entrega de "un" diagrama, por lo tanto esto podría causar ambigüedad y/o falta de información precisa.

Es importante recalcar que siempre que se hable de "entregables", es porque estos son evaluados.

Por esta vez y para ser justos con todos quedamos en lo siguiente:

- [ ] Si se entregó un diagrama correcto, se darán 2 puntos en la entrega preliminar. Y el diagrama final valdrá 6 puntos.
- [ ] Si se entregó un diagrama incorrecto o no se entregó, el diagrama final valdrá el total de 8 puntos.

Cabe recalcar que se indicó que eran dos entregables, sin embargo faltó decir cómo se entregaba el preliminar. No es apropiado hacer una analogía con un robo para argumentar. En el cuerpo docente, estamos enfocados en buscar y aplicar metodologías justas para evaluar su aprendizaje. 

Recomiendo estar siempre atentos al foro, ya que de vez en cuando alguien se cuestiona cosas que nisiquiera a nosotros se nos habrían ocurrido.

Saludos y éxito con lo que queda de la tarea!

Ps: el diagrama final se entrega en el repositorio privado de cada alumno y NO en un Google form.

Belén

**Comment by bcsaldias** [comment]
- [ ] > Si se entregó un diagrama correcto, se darán 2 puntos en la entrega preliminar. Y el diagrama final valdrá 6 puntos.- [ ] > Si se entregó un diagrama incorrecto o no se entregó, el diagrama final valdrá el total de 8 puntos.
