### ISSUE TITLE
Duda sobre la property piezas_explosivas_invalidas de la clase Tablero 

### ISSUE THREAD

**Issue by sbarriag** [IIC2233/Syllabus#97]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, tengo una duda sobre la parte de piezas_explosivas_invalidas de la clase Tablero. Resulta que el enunciado dice "Una pieza explosiva no es válida si la cantidad de celdas a destruir no equivale exactamente al alcance máximo que tenga dicha pieza" y mi duda es si a esto se refiere con que el numero de celdas a las cuales la pieza potencialmente pueda llegar sea mayor o igual al numero que trae la pieza?

Para que se entienda mejor mi duda, planteo los siguientes casos

Ejemplo 1: Tengo un tablero de 2x2  de la siguiente manera [[R1, --],[--,--]], la Reina puede hacer explotar cualquiera de las 3 celdas en blanco, por lo que al poder explotar en alguna contaría como pieza válida?

Ejemplo 2: Tablero 2x2 [[R3, --],[--,--]] la Reina también sería valida por poder explotar en los 3?

Ejemplo 3: [[R4, --],[--,--]] sería válida? Puesto que se cuenta su mismo espacio para explotar

y por último Ejemplo 4:  [[R5, --],[--,--]] sería inválida puesto que hay menos celdas posibles en que pueda explotar que la que su número pide?? 

Disculpen las molestias y muchas gracias de antemano por su respuesta

**Comment by Segismundios** [comment]
Yo lo hice considerando inválida sólo el caso del ejemplo 4 y anduvo bien.

**Comment by Hernan4444** [comment]
Hola @sbarriag 

Antes de todo, recomiendo revisar los anuncios de Canvas, justo se mandó uno donde se indicó que se actualizó el enunciado específicamente en esa _property_ 😅 porque no estaba correctamente explicada. Además, se indicó en qué [issue](https://github.com/IIC2233/Syllabus/issues/72) fue tratado este problema.

Respecto a tu duda, solo el ejemplo 4 es inválido, puesto que es una pieza cuyo número es más grande que la cantidad máxima de celdas a destruir. Esa reina máximo puede destruir las 4 celdas, así que con un 1, 2, 3 o 4, será válida, pero con 5 ya es imposible de dar una solución a dicha pieza explosiva y por eso es inválida.

¡Mucho éxito con tu tarea!
Saludosヾ(＾-＾)ノ

**Comment by sbarriag** [comment]
Perfecto muchas gracias, si había visto el anuncio pero me paso que cuando reemplace el enunciado por el nuevo, se quedó el original por eso seguia teniendo el error 

Muchas gracias!
