### ISSUE TITLE
Desconectarse para realizar los cambios Tarea 1

### ISSUE THREAD

**Issue by IchottMano** [IIC2233/Syllabus#97]
Buenos días, 
escribo para preguntar si es válido pedirle al usuario que cierre su sesión actual para poder cambiar de *Trader* a *Investor*, pregunto porque no encontré nada al respecto el el pdf de la tarea.
Muchas gracias

**Comment by fdominguezclaro** [comment]
Puede quedar a tu criterio. Acuérdate de especificarlo en el Readme. 

Suerte!
