### ISSUE TITLE
Incidencia de condición meteorológica sobre incendio

### ISSUE THREAD

**Issue by monicabelen** [IIC2233/Syllabus#97]
¿La tasa de propagación de un incendio aumenta en función del TIEMPO que el incendio se expone a una condición meteorológica? o simplemente, cambia si se expone o no se expone?

Es que es raro para mi que, por ejemplo, la tasa de un incendio que se expuso 1 hora al viento aumente en igual proporción que otro incendio que se expuso 60 horas al viento.

**Comment by rpalmaotero** [comment]
Tal como dice el enunciado, las tasas son por unidad de tiempo.
