### ISSUE TITLE
ocupar reverse = True y eval()

### ISSUE THREAD

**Issue by mvveram** [IIC2233/Syllabus#97]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola,

He visto lo de `sort` y tenia la duda si se podía ocupar `reverse = True` o tampoco se puede?
Y ¿Se puede ocupar `eval()` que es para convertir un string de lista en una lista?

Muchas gracias de antemano

**Comment by vicentethomas** [comment]
Hola! Recuerda que para preguntar sobre librerías y built-ins debes hacerlo en los comentarios de la issue #21. De igual forma, te comento que puedes utilizar `sort` y cambiar el parámetro `reverse`. Por otro lado `eval()` es uno de los built-ins que salen como estrictamente prohibidos y su uso es un 1,0 automáticamente sin discusión 😮
