### ISSUE TITLE
Demora solucionar_tablero()

### ISSUE THREAD

**Issue by Fopazov** [IIC2233/Syllabus#97]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/21)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/20)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Definí la función solucionar tablero y me funciona correctamente para tableros de 2 a 4 dimensiones. Luego de 5 se demora más. Si la dimensión es mayor a 5 el tiempo de demora es demasiado. ¿Está bien? Sé que con las dimensiones aumenta en gran cantidad las iteraciones, pero no sé si debería pasar lo que estoy comentando.

**Comment by pedrozavalat** [comment]
Hola @Fopazov,
Para toda issue que realices, verifica que no se repita en el [Compilado de Issues T0](https://github.com/IIC2233/Syllabus/issues/21), ya que otro estudiante realizó la misma pregunta.
* #69 

Por favor, para las próximas issues que hagas, revisa en el compilado y verifica que otra persona no haya realizado una pregunta igual a la tuya. En el caso que no encuentres ninguna respuesta que resuelva tu duda, realizas una nueva issue. Así evitamos tener preguntas duplicadas. Ademas, debes marcar los Prerrequisitos para toda issue que realices.

Saludos :)

**Comment by pedrozavalat** [comment]
Hola @Fopazov,
Para toda issue que realices, verifica que no se repita en el [Compilado de Issues T0](https://github.com/IIC2233/Syllabus/issues/21), ya que otro estudiante realizó la misma pregunta.
* #69 

Por favor, para las próximas issues que hagas, revisa en el compilado y verifica que otra persona no haya realizado una pregunta igual a la tuya. En el caso que no encuentres ninguna respuesta que resuelva tu duda, realizas una nueva issue. Así evitamos tener preguntas duplicadas. Ademas, debes marcar los Prerrequisitos para toda issue que realices.

Saludos :)

**Comment by Fopazov** [comment]
Hola, disculpa. Mala mía. Gracias por la respuesta!
