### ISSUE TITLE
Dudas sobre el uso de .gitignore en la T1.

### ISSUE THREAD

**Issue by NicolasOlmosQuiroga** [IIC2233/Syllabus#97]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

¡Hola!, tenia dos dudas sobre el uso de gitignore.

1. ¿Al repositorio debemos subir el archivo .gitignore o debemos ignorarlo tambien?
2. ¿Hay alguna manera de saber si se subio a mi repositorio la carpeta __pychache__?, al menos yo no la veo pero no se si se subio en el primer push que hice y no se ve, o si que no aparezca significa que no esta.

Eso nomas, ¡muchas gracias!

**Comment by jtvaldivia** [comment]
Hola, 
a tu primera pregunta mejor no lo ignores, para que tu corrector pueda revisar que hayas ocupado correctamente el arhivo .gitignore. 
Por ultimo, si no te sale el archivo en el repositorio significa que no esta,  pero igualmente ponlo en el .gitignore para que no haya ningun error.
