### ISSUE TITLE
Python Not Responding

### ISSUE THREAD

**Issue by CataSudo** [IIC2233/syllabus#970]
Hola, ayer probe mi codigo sin problemas pero hoy cada vez que lo corro me aparece Application not Responding cuando se abre Python. ¿Qué paso?

**Comment by cristozille** [comment]
Hola! Probablemente sea un error de dónde lo estes corriendo. Te recomiendo cerrar y abrir el programa. Y si no funciona, trata reiniciando el computador. De todas formas sube tu código al repositorio para evitar que se pierda.
