### ISSUE TITLE
El metodo run() de los threads puede recibir una señal?, pasa que cuando corro el main me dice que no recibio el argumento de la señal.

### ISSUE THREAD

**Issue by nlewin99** [IIC2233/syllabus#971]

**Comment by nlewin99** [comment]
Este es el error que sufro: run() missing 1 required positional argument: 'event', no tengo claro si se debe a que el run no puede recibir señales o algo hize mal, pero he replicado el metodo, de todas las señales de mi codigo. Saludos, Nicolás!

**Comment by maggiemunoz** [comment]
te refieres a que una señal haga que el metodo run parta?

**Comment by nlewin99** [comment]
Hola @maggiemunoz, ya lo solucione!, gracias de todas formas.
