### ISSUE TITLE
Duda mala práctica parametros.py

### ISSUE THREAD

**Issue by Tvergara** [IIC2233/syllabus#971]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola, tengo una duda de cómo almacenar los ```path``` en el ```parametros.py```. En el enunciado ejemplifica, con diccionario con sus values como listas. Pero en mi código sólo definí una función que me retornaba el path (dentro del parametros.py). Resulta que si intento hacer un diccionario con todos los path, terminaría teniendo diccionarios enormes, y si lo separo en distintos sub-diccionarios, en el código igual se tendría que revisar más casos para ver qué diccionario usar. ¿Está mal el uso de una función de esta forma?

Ejemplo de la función: 
```
def PATH_PINGUINO(color, posicion):
    return {path}
```
con ```{path}``` siendo el path obviamente (la función haría algún proceso para determinar el path).

**Comment by aljara97** [comment]
Hola @Tvergara, no es un uso adecuado de parámetros el utilizar funciones en este módulo, ya que este se encarga solo de almacenar valores constantes. Sin embargo la definición de esta función es una buena idea, te recomiendo agregarla en algún módulo de tu código y que los valores constantes que le entregues a esta se almacenen en `parametros.py`.

También te recomiendo que comentes esto en tu readme y cites esta issue, para que el o la ayudante que corrija tu tarea tenga claridad de esto. 
Mucha suerte 🐧
