### ISSUE TITLE
Pep8

### ISSUE THREAD

**Issue by CataSudo** [IIC2233/syllabus#972]
Respecto a lineas de texto tipo:
```
        self.label.setText(
            "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600; color:#005733;\">¡Bienvenido al mejor café virtual del DCC!</span></p></body></html>")
```
Que saque textual de QT Designer, deben seguir el pep8? Lo que me complica es tiene mas de 100 caracteres.

**Comment by bvasquezm** [comment]
Hola @CataSudo!

Recuerda que siempre puedes hacer uso de carácter `\` para cortar líneas y así no superar el máximo de caracteres. Todas las líneas se consideran.

**Comment by jamigone** [comment]
Hola @bvasquezm!
¿También se incluyen las líneas de los comentarios?
Coloqué el link de una página como referencia a una parte de mi código, pero esta sobrepasa las 100 carácteres (llega a la 130).
¿Debería cortar el link y dividirlo en la cantidad de líneas para cumplir el Pep8?
¿Es correcto hacer esto?

**Comment by bvasquezm** [comment]
Hola @jamigone,

Intenta que los comentarios no sobrepasen los 100 caracteres, en caso de excederlos comentarlo en el Readme. En el caso de los links, deberás *señalar la línea específica* en la que se encuentra en tu Readme. Saludos!
