### ISSUE TITLE
Duda sobre como hacer override de keyPressEvent en ventana creada por QtDesigner

### ISSUE THREAD

**Issue by gaspcr** [IIC2233/syllabus#973]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Mi problema es que no logro hacer override en mi ventana principal (la cual cree en QtDesigner), intento re-definir, por ejemplo, el método keyPressEvent y el vscode no me reconoce el método como que ya existiera, además al intentar hacer que mi ventana principal herede de QWidget (pues keyPressEvent es de esa clase) me arroja error indicándome que ya está heredando del mismo.

¿Debería importar mi .ui file de otra manera para poder hacer override correctamente?, lo hice tal como se indica en los contenidos de la semana-10

**Comment by JadrinaDA** [comment]
Hola! Viendo tu código estás definiendo keyPressEvent en la clase incorrecta, ya que esta se encuentra en la clase Capturador y no en la Ventana Principal. Lo moviste para intentar resolver tu problema? Además el metodo es case sensitive por lo que debería ser keyPressEvent y no KeyPressEvent  Sobre heredar de QWidget ya estás heredando de el porque uic.loadUiType de entrega un parametro baseclass que contiene a QWidget.

**Comment by gaspcr** [comment]
Hola, si ese es una versión antigua de mi código jaja si lo estoy intentando en la clase VentanaPrincipal, puedo actualizarlo ahora para que veas. En la clase prueba me aparece para hacer override de keyPressEvent,

![imagen](https://user-images.githubusercontent.com/69615288/97780050-f8358700-1b60-11eb-8c5f-09503388ac91.png)

Mas no puedo en la clase VentanaPrincipal
![imagen](https://user-images.githubusercontent.com/69615288/97780077-2b781600-1b61-11eb-98b4-0334aff4576b.png)

**Comment by gaspcr** [comment]
Al parecer ya lo solucioné :D

**Comment by JadrinaDA** [comment]
Me alegro. Éxito en la tarea!
