### ISSUE TITLE
Eliminar Qlabel

### ISSUE THREAD

**Issue by CataSudo** [IIC2233/syllabus#974]
Hola! Estoy un poco confundida sobre la pauta dice: "Las mesas y el chef se pueden eliminar haciendo click. Se impide que el jugador se quede sin elementos en el mapa." Estas mesas y chefs son las del drag and drop o son todas las mesas/chefs?
Gracias!

**Comment by tomasgv** [comment]
Hola @CataSudo !!

Eso se refiere a todas las mesas y chefs que están ubicados en el **mapa** del _DCCafé_. Esto abarca a las iniciales y las que compres.

Si con "las del _drag and drop_" te referías a las que se muestran en la **tienda**, entonces no debes poder eliminar aquellas. 

Saludos! ☕  😸
