### ISSUE TITLE
funcion progreso fuciona perfectamente pero al mismo tiempo retorna error cada vez q se usa

### ISSUE THREAD

**Issue by elchocman** [IIC2233/syllabus#974]
### Duda
holaaa, es que funcion progreso fuciona perfectamente pero al mismo tiempo retorna error cada vez q se usa, el error es "TypeError: funcion_progreso() missing 1 required positional argument: 'totales' " , donde la funcion progreso necesita de las flechas totales creadas hasta el momento y de las flechas totales que se crearan por ronda, las cuales si llegan a la funcion porque se calcula correctamente el progreso en la barra

**Comment by elchocman** [comment]
en cuanto a esto, no me afecta en nada al desarrollo de mi programa, solo que llena la terminal de typeError ....

**Comment by aaossa** [comment]
Hola @elchocman , en alguna parte debes estar llamando de manera incorrecta a la función. Si funciona, quizás es porque en otra parte llamas a la función correctamente. Fui a ver tu código por si pillaba algo pero no has hecho *commits* recientemente 😅 Te recomiendo hacer *push* para tener tu repo actualizado y poder ayudarte más fácilmente.

**Comment by elchocman** [comment]
@aaossa  voy a hacer un push ahora, por si le podrias echar una mirada

**Comment by aaossa** [comment]
@elchocman es porque efectivamente estás llamando tu función desde dos lugares: desde tu código (método `creador` en tu `MainWindow`) y también desde el archivo *.ui, porque lo conectaste desde Qt Designer. El problema es porque en Qt Designer no le pasas los argumentos a la función y por eso funciona (gracias al código) y lanza la excepción (por Qt Designer). Para dejar de causar la excepción basta con que borres la conexión desde Qt Designer 👌

**Comment by elchocman** [comment]
@aaossa graciaaaaaaasss ahi me funcionoooo, y bueno tengo otro problema que es que mi flecha de hielo despues de que congele siento que hace que cada flecha q atrape despues de esta congele un poco a las demas, el problema es que nose si es por que se bugea la imagen o es que tengo un error de codigo. saludos y graacias

**Comment by aaossa** [comment]
@elchocman no estoy seguro de qué podría ser a la primera 😅 Dado que no se relaciona con esta *issue*, te recomendaría ver si hay una parecida y, si no la hay, hacer otra *issue*. ¡Éxito con la Tarea ✨!

**Comment by elchocman** [comment]
yaaa gracias
