### ISSUE TITLE
Problema creacion flechas 

### ISSUE THREAD

**Issue by sofiaolmedos** [IIC2233/syllabus#975]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola! Tengo un problema con la creación y movimiento de las flechas en los modos de Aficionado y Maestro. Me pasa que como se crean y se mueven a distintos tiempos, **se me acumulan las flechas en y**. Por ejemplo en Aficionado llega un punto en que tengo tres flechas al mismo tiempo en la misma posición y, entonces al llegar a la zona es como una triple, pero no debería ser así.
Pero me pasan que no se pegan, como debería pasar.  

![Captura de pantalla (135)_LI](https://user-images.githubusercontent.com/69520545/97769608-238d8700-1b0b-11eb-89e8-d9faa1f51f1a.jpg)

**Comment by furcelay** [comment]
Hola @sofiaolmedos !

Lo ideal es que el número de flechas por fila sea a lo más la que permite la dificultad. Ya que todas se mueven a la misma velocidad no debería ocurrir que se junten (a excepción del caso especial de las flechas doradas, caso en que puedes permitirlo mientras especifiques en tu README como tratas ese caso). En tu caso el problema ocurre porque el intervalo en que se crean las flechas en las dificultades *Aficionado* y *Maestro cumbia* es menor al que tardan las flechas en actualizarse, entonces por ejemplo se crean flechas cada 0.5 segundos pero se desplazan cada 1 segundo y cada dos filas se genera una superpuesta. Para solucionarlo basta reducir el intervalo del `QTimer` de las flechas (además te recomiendo hacerlo para que el movimiento sea fluido y no a "saltitos", con un valor de 50 a mí me funcionó perfecto si además reducía el parámetro `VELOCIDAD_FLECHA`).

Espero que eso resuelva tu problema, saludos!! 😄

**Comment by sofiaolmedos** [comment]
@furcelay muchas gracias!! Sospechaba que era eso :)
