### ISSUE TITLE
Error MainWindow.ui

### ISSUE THREAD

**Issue by mdabarca1** [IIC2233/syllabus#975]
Holaaa! Cuando le doy git add a mi MainWindow.ui me sale el siguiente warning: warning: 
LF will be replaced by CRLF in Tareas/T02/MainWindow.ui.
The file will have its original line endings in your working directory

![Captura de pantalla (91)](https://user-images.githubusercontent.com/62114181/83923857-200af500-a751-11ea-8db0-c9f3d90a6454.png)

Busqúe el warning y encontré lo siguiente:
https://es.stackoverflow.com/questions/320373/por-qu%C3%A9-al-hacer-git-add-me-dice-lf-will-be-replaced-by-crlf-the-file-will-h
https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings

¿Como podría arreglarlo? No quiero embarrarla y lo que pasa es que mi código ya no me abre la ventana cuando le doy la señal, y antes de hacerle unos cambios a MainWindow.ui sí la abría. No estoy segura si no me abre la ventana por lo que dice el warning o quizás es por otra cosa 😢 😢

**Comment by aaossa** [comment]
Hola @mdabarca1, primero que todo, es un *warning* así que no te preocupes. A lo que se refiere, es que como estás en Windows, los saltos de línea en tus archivos se codifican de cierta manera distinta a los de otras plataformas (como Ubuntu). Lo que hace git es guardar los saltos de una misma manera para asegurar compatibilidad cuando tu código sea utilizado en otros sistemas operativos. En resumen, no te preocupes, git maneja ese tema por ti y solo te está avisando que lo hace, puedes subir tu código tranquilamente ✨

**Comment by mdabarca1** [comment]
@aaossa muchas graciaas! 😄
