### ISSUE TITLE
Posición de la flecha no se actualiza bien en pantalla

### ISSUE THREAD

**Issue by nimorales97** [IIC2233/syllabus#976]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
**Contexto:** Apreto un botón, aparece una flecha en la ventana, se inicia automáticamente un thread, éste emite señales cambiando su posición (del label flecha) haciéndolo bajar. Debería llegar a un cierto punto y desaparecer.
*(Pondré un poco de código resumido sólo para que se entienda bien lo que hago, puede pasar directo al problema abajo).*
**Código: (es más o menos esto)**
```
class Ventana(...):
    iniciar_thread_flecha = pyqtSignal()
    senal_bajar = pyqtSignal(int)
    def __init__(self):
        ...
        self.pushButton.clicked.connect(self.poner_flecha)
        self.aux = None
        self.senal_bajar.connect(self.mover_flecha)
    def poner_flecha(self):
        ... # Definir la flecha en self.aux y ponerla en la ventana
        self.iniciar_thread_flecha.emit()
    def mover_flecha(self, pasos):
        self.aux.move(0, pasos)
        self.aux.updateGeometry()


class Flecha(QThread):
    empezar = pyqtSignal()
    senal_bajar = pyqtSignal(int)
    def __init__(self, direccion, tipo, _id):
        ...
        self.posicion = 0
        self.alive = True
        self.empezar.connect(self.start)
    def run(self):
        while self.alive:
            print(self.alive)
            self.senal_bajar.emit(VELOCIDAD_FLECHA)
            self.posicion += 0.07*VELOCIDAD_FLECHA
            if (self.posicion >= 316): #Tope del layout
                print("murió")
                print(self.posicion)
                self.alive = False
```
**Problema:** En efecto la flecha aparece, baja un poco y se detiene (es la que apunta hacia abajo, las otras las tengo ahí de antes). Los prints en la consola me indican que todo funcionó bien:
![WhatsApp Image 2020-10-30 at 11 51 43 PM](https://user-images.githubusercontent.com/30670006/97769597-0658b880-1b0b-11eb-9cca-54e02d1ff42f.jpeg)
*¿Por qué no cambia la posición en la ventana?*

Edit: agregué `print(self.aux.y())` a la función que cambia **la posición** y **vale todo el rato 20**, por eso no cambiaba en la ventana, aún así no tiene sentido eso porque las señales se van emitiendo en cada ciclo. **¿Por qué sólo la recibe la primera vez?**

**Comment by knight-who-say-ni** [comment]
Holaa @nimorales97 !!

Ojo 👀  que el metodo `move(x, y)` lo que hace es poner tu label en la posición (x,y), NO moverlo x a la derecha e y hacia abajo.

Exito en la tarea!!

**Comment by nimorales97** [comment]
> Holaa @nimorales97 !!
> 
> Ojo 👀  que el metodo `move(x, y)` lo que hace es poner tu label en la posición (x,y), NO moverlo x a la derecha e y hacia abajo.
> 
> Exito en la tarea!!

Primero que nada muchas gracias por darte el tiempo de responder a esta hora, y 2do muchas gracias no sabía eso y ahora me funciona 😭 gracias!
