### ISSUE TITLE
duda reiniciar partida

### ISSUE THREAD

**Issue by maggiemunoz** [IIC2233/syllabus#976]
hola! cuando dicen que las mesas y mesones comienzan en una posición aleatoria, se refiere a completamente aleatoria tipo con un random o podemos nosotros cambiarlo de alguna manera (por ejemplo que las mesas aparezcan a la izquierda y los mesones a la derecha o algo por ese estilo)

**Comment by danckoo1** [comment]
Hola!, efectivamente debe ser una posicion aleatoria, pero debes tener ojo con que no te quede parte de los label fuera del mapa, ni que queden dos objetos sobrepuestos.
