### ISSUE TITLE
randint(0, 1)

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#977]
Hola. Tengo una duda con corroborar si una probabilidad existe o no.
Yo estaba tomando ```randint(0, 1)```  para compararla con una probabilidad "x", pero recién me dí cuenta que esto toma valores "cero" o "uno", porque considera solo números enteros. Y se supone que la probabilidad toma valores decimales... 
Se puede hacer con "randint" también?

**Comment by Camila-sty** [comment]
Hice esta issue para saber más que nada si la idea que tengo de comparar una probabilidad está bien? 
Entonces que ```uniform``` me serviría en este caso. Entonces está bien si compruebo que un "proba_x" sucede?
```
probabilidad = uniform(0, 1)
if proba_x >= probabilidad:
    #proba_x sucede
else:
    #no sucede
```

**Comment by danckoo1** [comment]
Hola, si el ejemplo que entregas esta perfecto!
