### ISSUE TITLE
Clientes que llegan al local

### ISSUE THREAD

**Issue by dlmed** [IIC2233/syllabus#978]
Hola! resulta que estoy probando el programa y siempre me llega 1 cliente más del que debería jaja. Revisé el código y no he encontrado indicios de error. Si alguien me pudiera ayudar sería genial.

Saludos

PD: está pusheado con datos.csv y mapa.csv

**Comment by dlmed** [comment]
Creo que ya encontré el problema, hay un timer que está generando clientes hasta que un contador llegue a cero. Dicho contador disminuye cada vez que se va un cliente, por lo que hay un momento en que han llegado n clientes y el cliente #n está siendo atendido, entonces aún no llega a cero el contador, por lo que puede que mande otro cliente si es que LLEGADA_CLIENTES es menos al tiempo de espera de este último cliente.

**Comment by dlmed** [comment]
Solucionado!

**Comment by danckoo1** [comment]
genial!, justo iba a ver tu repo
