### ISSUE TITLE
Valores en parametros.py

### ISSUE THREAD

**Issue by denisseleiva** [IIC2233/syllabus#978]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [x ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [ x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola!! Estuve mirando las issues con respecto a los parámetros en que se menciona que todos los números constantes tienen que parametrizarse. Para mi tarea no usé QDesigner, es decir, todos mis labels, widgets, botones, imagenes, etc., los agregué con setGeometry() o move() o resize(). ¿De verdad tienen que ir todos estos números en parámetros.py? Serían miles de números, creo que usaría como 300 línas de código sólo en importar parámetros 🙃 **ayuda**

**Comment by knight-who-say-ni** [comment]
Holaa @denisseleiva !!

Tu duda ya fue resuelta en la issue #760 .

Exito en la tarea!!
