### ISSUE TITLE
como extraer el QRect de un QLabel

### ISSUE THREAD

**Issue by sofiuni** [IIC2233/syllabus#979]
En alguna parte de la uni, no recuerdo si ayudantia o contenido dijieron algo de que los QLabels ya tenian un QRect, quiero ver si el personaje esta dentro del mapa que es un QLabel, como puedo extraer el QRect?

**Comment by matiasmasjuan** [comment]
Hola @sofiuni !

Tal vez la *Issue* #798 te pueda ser útil.
*Spoiler*: Puedes hacer uso del método: ```label.geometry()``` que retorna un ***QRect*** de ```label```.

Saludos y mucho éxito con la tarea! 😄

**Comment by sofiuni** [comment]
Si! Eso es lo que necesitaba, gracias!
