### ISSUE TITLE
Delay entre funciones

### ISSUE THREAD

**Issue by kalarconvl** [IIC2233/syllabus#979]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola! Tengo una función para que la zona de captura cambie de color cuando hay una flecha encima y me funcionaba muy bien, pero ahora que le agregué la parte de apretar teclas y verificar el puntaje empezó a tener delay: no funciona exactamente cuando está la flecha encima supongo que porque cada segundo el Thread principal tiene que ver muchas cosas. Son solo unos milisegundos pero se nota al ojo y se ve como lento. Cómo se puede arreglar o da lo mismo?

**Comment by JadrinaDA** [comment]
Hola! Como dices tú este delay probablemente se debe a que tienes un thread haciendo múltiples cosas. Lo que puedes intentar es dividir las tareas en múltiples threads que funcionen en paralelo.  Por ejemplo puedes hacer un QThread que cada cierto tiempo revise el puntaje. Igual no te preocupes porque vamos a corregir tu tarea en base si es funcional y no eficiente.
