### ISSUE TITLE
modulos parametros y tablero

### ISSUE THREAD

**Issue by Juampisaez** [IIC2233/syllabus#98]
Hola, tengo la duda de si los modulos parametros y tablero se consideran como librerias propias o externas? , tambien queria saber, si en caso de no haber modularizado el codigo (porque no excede las 600 lineas) es necesario poner como librerias propias las clases que se encuentran dentro del mismo codigo? (estas clases estan escritas como variables mismas para simplificar un poco el flujo)

**Comment by jeschuwirth** [comment]
Saludos,

Recuerda que el readme es para ayudar al corrector de tu tarea, por lo tanto no es necesario que coloques los módulos tablero.py y parametros.py en el readme.md, puesto que el ayudante ya sabe que son y como funcionan. Puedes agregarlos de todos modos a librerías propias por si tienes ganas de volver a revisar tu tarea en el futuro y te quieres guiar con el readme, pero para la corrección no es necesario.

En cuanto a la segunda pregunta la idea de modularizar es más que sólo no superar las 600 líneas, es que las clases y las funciones que trabajan con ellas estén divididas correctamente y que al momento de ver tu tarea sepas inmediatamente que hay en cada archivo. Como para la corrección sólo les pedimos las 600 líneas y es la primera tarea no hay problema que subas todo junto, pero si subes tres archivos llamados módulo1.py, módulo2.py y módulo3.py, entonces vas a recibir el descuento de modularización aunque no superen las 600 líneas, ya que no cumples el propósito de modularizar.

Ojalá haya quedado claro para que puedas entregar un readme completo :)

Suerte!
