### ISSUE TITLE
Duda con suerte_principiante

### ISSUE THREAD

**Issue by TatyFlores** [IIC2233/Syllabus#98]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

En el enunciado cuando se habla de suerte_principiante del jugador casual, se dice que esta bonificación se mantendrá a lo largo de la estadía en DCCasino, pero después dice que solo se aplicará la bonificación al primer juego dentro del DCCasino, por lo que no tengo claro cuándo se aplicaría la bonificación ni cuánto dura exactamente.

![image](https://user-images.githubusercontent.com/101210892/162265233-3d873618-2385-41c3-9be5-8fcd59651c24.png)

**Comment by jtvaldivia** [comment]
Hola, 
a lo que se refiere el enunciado es que tu solo podras aplicar el efecto al apostar por primera vez en un juego. Esto se refiere a que si tu aplicas el efecto le das una cantidad X de suerte al jugador y esta cantidad despues de su turno se queda en las caracteristicas del jugado, pero este efecto de darle mas cantidad solo se podra hacer 1 vez por cada juego.

**Comment by nicolasgarciaes** [comment]
No me queda claro todavía, si el jugador en una segunda instancia juega otro juego nuevo, se realiza nuevamente otra bonificación es decir, su suerte sería = suerte inicial + bonificación * 2 ?

**Comment by jtvaldivia** [comment]
Mira piensalo de esta manera  cada vez que juegas un juego nuevo tu debes hacer suerte = suerte_actual +bonificacion de esta manera aumentando la suerte en esa cantidad, de esta manera si jugaras una segunda vez un juego seria suerte = suerte_actual(incluyendo la bonificacion que ya tuvo por el juego anterior) + bonificacion.

**Comment by Dvckhv** [comment]
hola, respecto a la accion, al final de la explicación menciona que se debe ejecutar * una unica vez  en la primera apuesta* y que es permanente, no logro ver donde dice que se hace 1 vez por juego

**Comment by jtvaldivia** [comment]
Hola,
 perdon me equivoque en decirles q tenia q ser tal manera, porque la idea es que tenga libertad de interpretacion en este caso. Por esto, modelen segun lo que entendieron del enunciado, puede ser para una unica vez o para cada vez que juegas un juego por primera vez. Lo importante es que lo aclaren en el readme.md lo que quisieron hacer y que tenga sentido con el enunciado, para que de esta manera tu ayudante sepa como lo pensaste.
