### ISSUE TITLE
Duda sobre la base de datos

### ISSUE THREAD

**Issue by NicolasCabello** [IIC2233/Syllabus#98]
Buenas!, he buscado dentro de las preguntas pero aun no me queda claro, en la base de datos se deben "actualizar los datos" cuando se agregan cosas, pero en el caso de que un incendio llega a potencia 0, igual se debe actualizar? o solo se mantiene en 0 hasta que cierre el programa?

**Comment by FernandoPieressa** [comment]
Hola! No debes borrar los incendios apagados de la base de datos por lo tanto no hay que actualizarlos en ese caso.

Saludos!
