### ISSUE TITLE
Duda Flujo registrarse o iniciar sesión fallidamente varias veces

### ISSUE THREAD

**Issue by mignacia** [IIC2233/syllabus#98]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, tengo una duda respecto del flujo del usuario al registrarse o iniciar sesión y equivocarse. Existe algún límite de intentos para poder realizar estas acciones, o siempre debe volver al menú de inicio, aunque se equivoque 500 veces en alguna de las opciones?
Muchas gracias!

**Comment by Tsbalart** [comment]
Hola @mignacia! No hay límite de intentos, siempre se debe respetar ese flujo, no importa cuantas veces se equivoque el usuario. Éxito con la tarea!
