### ISSUE TITLE
Ocupar consultas.csv

### ISSUE THREAD

**Issue by 18638333** [IIC2233/syllabus#98]
El programa no me deja abrir los archivos, ya que dice que no lo encuentra en el directorio, a pesar de estar trabajando en la misma carpeta en la que se encuentra el archivo, lo mismo me pasó con la tarea, y tuve que indicarle la carpeta en la que se encuentra el archivo. Por lo que voy a tener problemas con el 'main', podría modificarlo?

**Comment by KnowYourselves** [comment]
Hola @18638333!

Las preguntas de actividades deben ser realizadas en el _Discord_ del curso.

Saludos!
