### ISSUE TITLE
Semana 3 : Defaultdicts

### ISSUE THREAD

**Issue by Osiries1111** [IIC2233/Syllabus#98]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues).
* [ X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda.

### Duda

Cuando realizo un diccionario con Defaultdicts ya sea con una función o no, cómo puedo llamar cada key por separado, ya sea para imprimirlo o para utilizar el valor para alguna otra cosa? no me quedó claro si es igual como cuando se tiene un diccionario normal.

**Comment by mskdancers** [comment]
Hola! El acceso a los valores de un **defaultdict** se hace de la misma forma que en un diccionario normal, es decir:
```python
mi_diccionario = defaultdict(None)
mi_diccionario["key1"] = 1
mi_diccionario["key2"] = 2

# Si queremos acceder al valor de la llave "key2" usamos la misma notación:
print(mi_diccionario["key2"])
# --> 2

# si accedemos a con una llave que todavía no le asociamos un valor, nos retornará None
print(mi_diccionario["key3"])
# --> None
```
Ahora, si queremos acceder a las llaves de un **defaultdict** podemos usar el método **keys()**, que nos entrega los valores de las llaves que hemos definido hasta el momento (en este caso serían **"key1"** y **"key2"**).
Saludos!

**Comment by Osiries1111** [comment]
Gracias!! ahora si me quedó claro
