### ISSUE TITLE
Control 2

### ISSUE THREAD

**Issue by J0SEF4** [IIC2233/Syllabus#98]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda
En la pregunta 8 del control 2 al escribir un atributo que no fue definido, ¿Porque, igualmente lo imprime?
Pregunta  6, una opción es: "  Toda property debe tener un getter y un setter. " Sin embargo, según yo puede tener solo un getter o no?

Saludos y gracias por adelantado.
Josefa

**Comment by fernandosmither** [comment]
Hola!

Sobre tu primera pregunta, el único atributo que se imprime es marca, el cual es definido después de la instanciación de spark, de clase Auto.

Sobre la segunda, según  he podido revisar,  la alternativa a la que haces referencia no está marcada como correcta, ya que como tú mencionas, una property podría solamente estar definida con su getter.

Quedo atento a tus comentarios!

**Comment by J0SEF4** [comment]
Muchas gracias, me quedo claro.
