### ISSUE TITLE
entregar pedido

### ISSUE THREAD

**Issue by Camila-sty** [IIC2233/syllabus#980]
Hola.
Cuando el mesero toma el pedido del cliente y luego va hacia el chef y éste empieza a cocinar. En necesario que ese bocadillo que prepara ese chef sea el que le corresponda a ese cliente? 
O está la opción de que el mesero le lleve la comida de cualquier chef a cualquier cliente?

**Comment by tomasgv** [comment]
Hola @Camila-sty !!

No es necesario entregarle un bocadillo específico a los clientes, por lo que el mesero puede llevar un pedido de cualquier chef a cualquier cliente :+1:

Si implementaste un sistema para tomar pedidos de los clientes, entonces recuerda especificarlo en tu README. 

Saludos! 😸
