### ISSUE TITLE
Ventana post ronda

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2233/syllabus#981]
Hola, me queda la duda de si cuando termina mi "Reloj", y dejan de llegar clientes en la ronda, debo cerrar la ventana ronda para abrir la post ronda y luego abrir ronda nuevamente si apreto continuar?? O no debo cerrar ronda y debo abrir post ronda encima ?? O da lo mismo

Saludos, 
De antemano muchas gracias

**Comment by danckoo1** [comment]
hola, puede que se te haya pasado pero en el enunciado dice " Al finalizar la ronda, el DCCafe debe quedar preparado para la siguiente ronda. Esta ventana no se debe cerrar al pasar a la post-ronda" en la seccion de Ventana de Ronda.
