### ISSUE TITLE
Problema al intentar salir

### ISSUE THREAD

**Issue by jorge-ovalle** [IIC2233/syllabus#981]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by jorge-ovalle** [comment]
Al apretar el botón salir se envía una señal a todos los qthreads activos para que detengan su ejecución. Internamente, cuando el thread recibe esa señal sale de su loop y envía una señal para que se ejecute un deleteLater. Al final de cada loop de run hay una función que sirve para actualizar la posición del paso. El problema surge porque al parece el thread se borra antes de actualizar por última vez la posición, por lo que me tira un error diciéndome que el thread o el objeto no tiene el atributo de posición. No entiendo como arreglar esa situación. El thread asociado a cada paso está en el archivo threads.py del backend. Está todo subido en el repositorio y se puede ejecutar todo desde el main.

**Comment by furcelay** [comment]
Hola!

Perdón por la tardanza 😓 lo que podrías hacer en el caso que mencionas es usar eventos para sincronizar la actualización de la flecha y el `deleteLater` al salir del programa. Por ejemplo imagino que podrías usar `Event` de `threading` (o su equivalente en PyQt5 `QWaitCondition`, viendo tu código ya sabes usarlos) tal que el método que elimina el objeto espere a que el *thread* que actualiza la flecha haya terminado.

Revisando tu código veo que antes de salir pausas el programa, pero el problema es que pausar deja al *thread* en espera y por eso no puede terminar, entonces si implementas lo del comentario anterior manteniendo el comportamiento actual acabarás en un *death lock* 😣 (estarás esperando a que termine pero impidiendo que lo haga). Tienes que ver como compatibilizar ambos eventos para que no se borre el *thread* hasta que termine pero puedas asegurar que va a terminar.

Saludos!! 😄
