### ISSUE TITLE
Choque mesero cliente

### ISSUE THREAD

**Issue by 18638333** [IIC2233/syllabus#982]
Hola, al poner que el mesero choque con los clientes, tengo el riesgo de que el mesero se quede atrapado si es que está parado en un lugar donde va a aparecer un cliente. 
¿Será mejor que bloquee los espacion donde pueden aparecer los clientes, de manera que el mesero nunca se quede atrapado, o dejo que el mesero entre en esa zona, bajo el riesgo de que se quede atrapado?

**Comment by danckoo1** [comment]
hola!, dada las opciones que mencionas encuentro que la mejor es que bloquees momentaneamente los lugares donde puede aparecer un cliente para evitar que el mesero quede atrapado. Sin embargo, si fuese posible sería mejor primero crees la posicion del cliente que llegará, y si esta tiene conflictos con la posicion actual del mesero la vuelvas a definir en una posicion distina las veces que sea necesario, para posteriormente crear el label del cliente, estando seguro que el mesero no quedara atrapado.
