### ISSUE TITLE
Al iniciar una flecha se detiene la ya existente

### ISSUE THREAD

**Issue by nimorales97** [IIC2233/syllabus#982]
### Prerrequisitos
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
**Aún** estoy tratando de hacer que funcione lo de las flechas en mi programa. Hice un botón que al apretarlo aparece una flecha, automáticamente empieza a bajar hasta llegar al tope para desaparecer. **El problema es: pulso el botón, comienza a bajar una flecha, pulso de nuevo para que se vean dos flechas (porque me imagino que eso podría pasar con alguna canción), pero la primera se detiene al iniciarse la segunda y se queda ahí congelada**, y además es como si sumara su velocidad porque cada una va más rápido que la anterior. (*Sí, tengo puros errores extraños*).
No puedo poner mi código esta vez porque tendría que poner casi toda la tarea :(

**Comment by manearaya** [comment]
Hola @nimorales97!

Se me ocurre que estás usando la misma instancia de flecha. Es decir, al apretar el botón empieza a bajar una flecha y al apretar el botón de nuevo esa misma flecha es la que se reinicia, en lugar de hacer otra flecha.

Con respecto a la velocidad, quizás estás haciendo un += en alguna parte, que sumado a lo anterior provocaría que la velocidad aumente cada vez que se apreta  el botón.

No sabría decirte mucho más sin ver tu código, pero si hicieras push para que lo pueda revisar tendría más idea de lo que está pasando 😅.

Quedo atenta a tu respuesta.

**Comment by nimorales97** [comment]
Holaa, perfecto, lo haré ahora mismo

**Comment by nimorales97** [comment]
Tengo 2 archivos, en el mainT02 respaldo cambié el código para que en vez de guardar la flecha en una variable se guarde en una instancia de una clase, pero pasa el mismo problema.
La secuencia es ingresar algun nombre > comenzar > comenza ronda > lanzar flecha

**Comment by manearaya** [comment]
Podrías subir tu archivo de parámetros? no se puede ejecutar sin él 😅

**Comment by nimorales97** [comment]
Perdoon, crei que habia subido todo

**Comment by manearaya** [comment]
Con respecto a la velocidad, creo que lo que está pasando es que defines en el label que baje y además defines en el thread de la flecha que baje. Creo que se están sumando ambas cosas y por esto baja más rápido. Solo debería definirse una vez el movimiento de la flecha.

Igual sigo revisando!

**Comment by nimorales97** [comment]
Yaa lo revisaré, gracias!

**Comment by manearaya** [comment]
Hola! Malinterpreté tu código 😅 está bien lo que haces de llamar a que el label se mueva desde el thread (no es que el label se mueva solo).

Lo que veo ahora que está pasando es que llamas 2 veces al run del QThread cada vez que se apreta el botón. Como queda poco tiempo para la entrega te estoy haciendo updates cortitos, cosa que puedas ir revisando.

**Comment by nimorales97** [comment]
Si me dí cuenta de que algunas cosas ocurren dos veces, pero nunca encontré la fuente

**Comment by manearaya** [comment]
Creo que conectaste el botón al método en Designer y después en código. Si comentas en el código la conección entre el botón y el método sale solo una flecha.

**Comment by nimorales97** [comment]
Sii, ya no me acordaba, graxias! Ahora solo sigo teniendo el problema de las flechas que se interrumpen

**Comment by manearaya** [comment]
Sip! Sigo revisando eso 😅

**Comment by manearaya** [comment]
Creo que encontré el problema. 

En `flecha_bajar` de tu clase `V_Juego1` usas siempre `self.posicion_flechas` para identificar la flecha que baja, y este se va actualizando cada vez que se hace una flecha nueva, y por esto solo se mueve la útlima flecha que creas. Esto explica lo de la velocidad, ya que cada flecha que se crea llama al método, pero el método solo le avisa a una flecha que se mueva.

**Comment by nimorales97** [comment]
Ahí me funcionó por fin, tuve que modificar la clase pero funcionó! Muchas gracias ♡♡
