### ISSUE TITLE
Uso de QTimers en vez de QThreads

### ISSUE THREAD

**Issue by dlmed** [IIC2233/syllabus#983]
Hola, como en el enunciado sale que uno de los objetivos de la tarea es el uso de *threadings*, quería saber si este se cumplía al usar QTimers (dado que son bien parecidos). La verdad no use en ningún lago QThreads, solo QTimers para el tema de los relojes.

**Comment by bvasquezm** [comment]
Hola @dlmed!

Esta issue fue respondida en la #786. De todas maneras, te respondo que sí es considerado como uso de threads. Saludos.

**Comment by dlmed** [comment]
Gracias! Sorry por el duplicate, no supe cómo buscar la issue
