### ISSUE TITLE
Contenidos de parametros.py

### ISSUE THREAD

**Issue by Sofia-Arratia** [IIC2233/syllabus#983]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

¡Hola!

Tengo un par de dudas sobre qué cosas entran en parametros.py y de que manera. Por ejemplo, ¿Es correcto usar os.path.join() en los mismos parametros.py y guardar el path así? O tiene que venir por ejemplo en formato tupla para luego ser transformado a path dentro del programa. También, si hago uso de fonts, ¿Debo anotar como parámetros todos los componentes que usé para setear esa font, como tamaño y tipo (ej. Arial)? ¿O puedo setear el font en los mismos parametros.py e importarla así?

¡Muchas gracias! ☺️

**Comment by JadrinaDA** [comment]
Hola! En parametros.py deben estar solo cosas constantes como números o paths relativos. Por lo tanto te recomiendo no hacer el join en el mismo parametros.py. Puedes poner el string del path relativo completo como parámetro para así no tener que hacer join después. También puedes ponerlo como tupla y luego hacer el join. Es tu decisión. Los fonts y sus componentes no necesitan ir en parametros.py porque no son algo que realmente afectan el desarrollo del programa y por lo tanto su ajuste no es necesario. Puedes hacerlo si quieres pero no es necesario.
