### ISSUE TITLE
Bocadillo en mano cuando cliente se fue

### ISSUE THREAD

**Issue by dlmed** [IIC2233/syllabus#984]
Hola, quería saber qué debería hacer con el bocadillo que se está cocinando o lo lleva en mano el mesero, pero antes de entregarlo, el cliente se va, debería implementar una forma de eliminar aquel bocadillo cierto? estaba pensando que si colisiona con alguna mesa vacía, se pierda lo que lleva en la mano.

**Comment by jitorcas** [comment]
Hola @dlmed!

No es necesario que elimines el bocadillo ya que **todos** los clientes consumen lo mismo, por lo que podrías entregárselo a otro cliente. 
Ahora toda implementación adicional que no afecte el flujo del juego debes especificarla en tu **README**!

Éxito en la tarea! 💯

**Comment by dlmed** [comment]
Es que en mi implementación tengo que cada pedido corresponde a un número de mesa, por lo que solo se le puede entregar al cliente de dicha mesa. Esto lo hice porque los tiempos de entrega (desde que se toma el pedido hasta que se entrega) los cuenta un timer interno del bocadillo, por lo que este no sería el correcto si es entregado a otra persona que no lo pidió. Por esto se me hace más fácil botar el pedido si es que se fue el cliente que lo pidió, pero no se si es válido hacer esto.

**Comment by jitorcas** [comment]
@dlmed 
¿Como implementas el "tomar" un pedido? ¿Hay alguna parte según tu criterio donde se contradiga el enunciado?

**Comment by jitorcas** [comment]
@dlmed 
Me preocupa un poco que el "tomar" un pedido te esté limitando acciones del flujo general, entiendo que como lo hiciste tiene mucho sentido en un flujo de la "vida real", sin embargo no era necesario simular una toma de pedido para no complicarles mucho la tarea, si pudieses explicarme lo que hiciste para conversarlo con los ayudantes y darte una solución más concreta, sería perfecto!

**Comment by dlmed** [comment]
El proceso que implementé es el siguiente:
1. Llega cliente a una mesa -> comienza su timer de tiempo de espera
2. Mesero colisiona con mesa del cliente, toma pedido -> inicia timer del bocadillo
3. Mesero colisiona con Chef, le entrega el pedido, el chef empieza a cocinar dicho pedido
4. Chef termina de cocinar o falla
5. Mesero colisiona con Chef del punto 4, recibe el bocadillo del pedido o en su defecto le pide que vuelva al punto 3.
6. Mesero colisiona con mesa del cliente -> timer de bocadillo para, se calcula prob_propina (calidad bocadillo) y se entrega bocadillo.

Durante todo el proceso, el Mesero tiene un atributo manos, el cual puede ser 'nada', 'pedido' o 'bocadillo', dependiendo de con quién haya colisionado anteriormente. Por esto,  en el juego, se debe hacer una cosa a la vez, es decir, si se toma un pedido, no se puede tomar otro hasta que se entregue el pedido a algún chef; de la misma forma, si se tiene un bocadillo en mano para ser entregado, no se puede tomar algún pedido hasta que se entregue este bocadillo. Es por esto que planteo que si un cliente se va antes de entregarle el bocadillo, se pueda botar este de alguna forma, en este caso, planteo que pueda ser colisionando con una mesa vacía. (Así le da más dinamismo al juego y posibilidad de hacer estrategias)

**Comment by jitorcas** [comment]
@dlmed 

Veo que le agregaste harta dificultad al flujo planteado. Conversando con los ayudantes llegamos a la siguiente conclusión:

Vemos **dificultad adicional de corrección** con respecto a asignar un bocadillo con un cliente, para evitar esto te proponemos que le pongas un *label* o algún identificador para saber a quién le pertenece cada pedido, podría ser un número en la mesa o algo por el estilo (no pedimos nada elaborado, puede ser texto).

Con respecto a **eliminar el bocadillo** dejándolo en una mesa vacía, te lo permitiremos dado el flujo que implementaste, sin embargo queda a criterio del ayudante aplicar descuento en dificultad de corrección. Para evitar malos entendidos, porfavor se muy claro en el **README** y cita esta *issue*. 

Ahora como apreciación personal, leí una *issue* donde hablas sobre la `LLEGADA_CLIENTES` y que un cliente a una mesa vacía podría llegar en 0 segundos , esto podría ser un problema si tienes un bocadillo que debes eliminar porque deberás esperar que se vaya otro cliente y tener una mesa vacía para poder eliminarlo, piénsalo bien. 

Éxito en la tarea 💯

**Comment by dlmed** [comment]
O sea, no tengo problemas en implementarlo de tal forma que le pueda dar cualquier bocadillo a cualquier cliente. Solo manifestaba posible incongruencia. Gracias por la respuesta!

**Comment by jitorcas** [comment]
@dlmed 
Así es, si implementaras que cualquier bocadillo se pudiese entregar a cualquier cliente no habría problemas.

En ese sentido deberías eliminar la parte de tomar pedidos. 

Éxito!

**Comment by dlmed** [comment]
Sin embargo es necesario que le tome el pedido con anterioridad para poder entregarle cualquier bocadillo, ya que el tiempo de espera que corresponde a la probabilidad de propina inicia cuando se le toma el pedido al cliente

**Comment by jitorcas** [comment]
@dlmed 

Eso especifícalo en el **README**. 

También podrías tomar el tiempo desde que llega el cliente, nosotros esperábamos que desde ese punto calcularan el **tiempo_espera**, pero en virtud del tiempo de entrega de la tarea, déjalo como está implementado y en el README pon todo lo que asumiste y cita las *issues*

**Comment by dlmed** [comment]
Es que en el enunciado decía:

"donde tiempo espera está dado según el tiempo que demora el mesero en entregarle el bocadillo
al cliente, **desde que toman el pedido del mesón**..."

**Comment by jitorcas** [comment]
Así es!
De todas formas hay distintas maneras de implementarlo, lo único que te pedimos es que cites esta *issue* para que el ayudante esté en conocimiento de cómo lo implementaste.
