### ISSUE TITLE
Erro de git "otro proceso en curso"

### ISSUE THREAD

**Issue by joseMaravena** [IIC2233/syllabus#984]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

[Agrega aquí lo que quieras aportar o preguntar]
Intentando eliminar archivos del repositorio me apareció que otro proceso del git está en curso, ¿Como puedo detener este proceso para poder continuar?
[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by aljara97** [comment]
Hola, este error se debe a que estás intentando manejar dos procesos de git a la vez. En primer lugar te recomiendo hacer una copia en otra carpeta de los archivos de tu tarea y luego seguir las instrucciones de la issue #274.

Mucha suerte y me cuentas cómo te va
