### ISSUE TITLE
Importar parametros en módulo usado por Designer

### ISSUE THREAD

**Issue by Zenos-Paradox** [IIC2233/syllabus#985]
* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Estoy usando le funcionalidad de "promote" de designer para hacer el drag and drop. En el archivo `.py` donde se encuentran las clases para promover quiero importar algo de `parametros.py` pero, al intentarlo, obtengo el error
`ImportError: cannot import name 'PENG_SIZE' from 'parametros'`
Qué puede ser? intenté poner `.parámetros` en véz, pero tampoco funcionó.

**Comment by aaossa** [comment]
Hola @Zenos-Paradox , pueden ser un montón de cosas. Si tu archivo se llama `parametros.py`, entonces el `import` debería tener `parametros` (sin la tilde). En cuanto a tu duda en sí, ¿estás importando parámetros de manera relativa al archivo ejecutado? ¿Qué archivo estás ejecutando? Creo que esta respuesta en una *issue* podría servirte: https://github.com/IIC2233/syllabus/issues/712#issuecomment-712311543

**Comment by Zenos-Paradox** [comment]
Perdón, lo escribí sin la tilde en el código, por costumbre se la puse ahora. Estoy importando parámetros relativo al main, que funciona con el resto de mi código. Revisé esa issue, pero no estoy seguro de que aplique a mi caso: creo que es un problema con QDesigner

**Comment by Zenos-Paradox** [comment]
`main.py`, Si estás ejecutando el archivo de mi repositorio, en `frontend/draggables.py` hay que descomentar la línea 5 (o por ahí):  `from parametros import PENG_SIZE`

**Comment by aaossa** [comment]
@Zenos-Paradox creo que lo que ocurre es a causa de que estás usando mal un parámetro 🤔 (bueno, haciendo que algo sea un parámetro cuando no lo es). Lo pude arreglar moviendo la definición de `PENG_SIZE` a la línea justo arriba de `MAIN_WIN`. No estoy 100% seguro de por qué ocurre, supongo que tiene que ver con el orden en que ocurre la creación de la ventana y el uso del parámetro, pero lo cierto es que puedes "parcharlo" moviendo la línea como hice yo. 

Ahora, si quieres hacerlo de **la manera correcta**, te recomendaría que `MAIN_WIN` sea solo el *path* al archivo y no la carga de la ventana. Ahora mismo estás cargando en parámetros toda la ventana, lo que es incorrecto. En `main_window.py` deberías tener la línea `window_name , base_class = uic.loadUiType(MAIN_WIN)`. Con esto, funciona perfecto y lo estarías implementando bien 👌 ¡Éxito con la tarea ✨!

**Comment by Zenos-Paradox** [comment]
Gracias! funcionó. Tienes razón, moveré la carga de la ventana.
