### ISSUE TITLE
Llegada clientes

### ISSUE THREAD

**Issue by dlmed** [IIC2233/syllabus#985]
Hola, quiero saber si la forma que tengo implementada la llegada de clientes es válida o no. Lo que hago es tener un reloj que cada LLEGADA_CLIENTES segundos verifica si hay una mesa disponible, y si no la hay, espera al siguiente período, y así hasta que no vengan más clientes. El tema con esto es que tanto al apretar *Comenzar* o al momento de que un cliente deje una mesa desocupada, el siguiente cliente en venir no viene después de un tiempo regular después de esta acción, sino que cuando el reloj que cuenta cada LLEGADA_CLIENTES tiempo hace tic toc. Entonces, por ejemplo, al apretar *Comenzar*, se puede esperar 0 segundos o hasta LLEGADA_CLIENTES segundos para que aparezca un cliente; lo mismo si se desocupa una mesa.

En #906 recomiendan hacerlo esperando a que hayan mesas desocupadas para correr el reloj de LLEGADA_CLIENTES, pero quiero saber si la forma que la hice también es válida especificandolo en mi README.

**Comment by bvasquezm** [comment]
Hola @dlmed,

Puedes implementar lo que comentas a tu criterio, no hay problema en que el primer cliente llegue de inmediato o en el tiempo señalado. Sin embargo, para los otros clientes se espera que respetes el uso del parámetro `LLEGADA_CLIENTES`y por supuesto, hayan mesas desocupadas. Espero haya quedado claro, saludos!

**Comment by dlmed** [comment]
Con lo último te refieres a que LLEGADA_CLIENTES debe contarse desde que haya una mesa desocupada? Es decir, no puede ser un reloj externo que cuente cada LLEGADA_CLIENTES tiempo y que ingrese un cliente cada dicho período si es que hay una mesa desocupada?

**Comment by bvasquezm** [comment]
Me refiero a que deben cumplirse *ambas condiciones* para que un cliente pueda aparecer. Debe cumplirse el tiempo de espera y que estén las mesas desocupadas. Saludos!

**Comment by dlmed** [comment]
Si, mi duda va en la sutileza del **cumplirse el tiempo de espera**, ya que puede cumplirse (desde mi punto de vista) desde que entró el último cliente o desde que se desocupó una mesa.
