### ISSUE TITLE
Cantidad de pinguinos en pista de baile

### ISSUE THREAD

**Issue by tomasnusser** [IIC2233/syllabus#986]
Hola!
Tengo una duda con la cantidad de pinguinos en la pista. Yo hice el drag and drop y funciona perfectamente pero como el enunciado no lo especifica, yo hice que al comprar un pinguino (el rojo por ejemplo) y ponerlo en un espacio vacío een la pista de baile, el rojo desaparece de la tienda, es decir, no se pueden comprar más rojos (teniendo un máximo de 5 pinguinos). 
Si especifico esto en el readme estaría bien?  Vi una issue que era parecida pero no sé si tenía mi mismo sistema de que no se puede comprar el mismo pinguino mas de una vez.
Muchas gracias :)

**Comment by knight-who-say-ni** [comment]
Holaa @tomasnusser !!

No debería haber un limite en la cantidad maxima de pingüirines de un color que puedes comprar. El unico limite es el espacio disponible en la pista de baile 😄, pero debería ser posible llenarla con puros pingüirines rojos, por ejemplo.

Exito con lo que queda!!
