### ISSUE TITLE
Qué pasa cuando se pierde la partida?

### ISSUE THREAD

**Issue by dlmed** [IIC2233/syllabus#986]
Hola, en complemento con la issue #928, qué sucede específicamente cuando se pierde? Me refiero, deberíamos borrar los datos guardados para que no pueda partir del mismo punto que antes de haber perdido? Se debería dar la opción de Guardar en post-ronda? Una opción que estoy pensando es que al perder, se guarde en los datos que la reputación es 0 y que al comenzar el juego, si se selecciona cargar partida, si se lee en los datos guardados que la reputación es 0, se crea una nueva partida.

**Comment by bvasquezm** [comment]
Hola @dlmed,

Al perder la partida efectivamente se debiese volver a iniciar el mapa con los datos especificados en **Reinicio de mapa** (3.6.1). Como si fuese una nueva partida. Saludos!

**Comment by dlmed** [comment]
Ahhhhh, muchas gracias por tu respuesta!
