### ISSUE TITLE
Acciones al salir del juego

### ISSUE THREAD

**Issue by dlmed** [IIC2233/syllabus#987]
Hola, no me queda claro con las issues #949 y #917, al presionar el botón Salir, tanto el de la ventana ronda y post-ronda, se debería salir del juego sin acciones adicionales? Es decir, los únicos datos que quedan guardados son aquellos que se guardaron al *partir la partida*?

**Comment by bvasquezm** [comment]
Hola @dlmed,

Como se señala en las otras issues, parte de los objetivos es que guardes constantemente el progreso de la partida, es decir, al momento de presiona el botón salir, debiese quedar todo guardado tal como lo dejaste (preferentemente al iniciar nuevamente, comenzar en pre-ronda). Todo lo adicional a lo mencionado, queda a tu criterio de implementación, pero de ser significativo coméntalo en el Readme. Saludos!

**Comment by dlmed** [comment]
Pero, no me hace sentido que se guarden los cambios que se hacen en esa partida si no se ha terminado la ronda, es decir, los efectos en el mapa y platos preparados por chefs. En cambio, lo veo como que la única forma de guardar una partida (y sus avances relacionados de la previa pre-ronda, ronda) es que se haga al momento de apretar Guardar en la post-ronda. Así, al presionar Salir, estoy descartando todo lo que hice desde la previa etapa de pre-ronda en adelante.

**Comment by bvasquezm** [comment]
Entiendo tu preocupación. Pero como se señala en la issue #917, en la sección de archivos menciona la necesidad de guardar con cada ejecución. Ahora, el botón de salir como cualquier programa, considera el guardado de archivos (piénsalo en un juego por ejemplo). El botón “guardar”, es más un guardar y seguir jugando por sobre un guardar y salir. Es una forma segura de guardar tu progreso. Consulta si sigues teniendo dudas, saludos!!

**Comment by dlmed** [comment]
Pero **ejecución** no se refiere a cada vez que inicio el programa? O en su defecto, entonces tengo que guardar los datos cada vez que haga algún cambio, ya sea agregar/sacar mesa/chef, platos cocinados, reputación, etc.? El problema que veo con esto es que no se da la posibilidad de volver a intentar la ronda si es que la reputación obtenida es positiva, por lo que el botón Guardar de la post-ronda no tiene sentido si es que no se aprieta, ya que se habrían guardado los datos de todo lo que pasó en la partida, menos la reputación. Por esto planteo la posibilidad de solo guardar cuando se indica al completar una ronda, ya que si se decide no guardar, se parte desde los datos guardados en la última ronda.

**Comment by bvasquezm** [comment]
Dado que no está bien especificado en el enunciado. Puedes limitar la opción de guardado al botón **guardar** en la post ronda. De todas formas si sales del programa, debe quedar guardado según la última vez que presionaste el botón de guardado. Pero preparado para la ronda siguiente y no la anterior (como si ya hubiese pasado la última ronda). Saludos!

**Comment by dlmed** [comment]
Entendido. Lo último no lo entendí muy bien si; en el caso de haber guardado en la post-ronda N, después juego la ronda N+1 y me salgo a la mitad, cuando me vuelva a meter, cargando los datos guardados, me debería permitir comenzar la ronda N+1 denuevo, ya que no la he pasado (?)

**Comment by bvasquezm** [comment]
Precisamente. Lo que señalas! :)
