### ISSUE TITLE
QThread nunca terminan

### ISSUE THREAD

**Issue by ian-fell** [IIC2233/syllabus#987]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola,
Tengo el problema que muchos parecen tener con los QThreads, que es que nunca terminan y solo se van acumulando. Cada vez que se publica una issue al respecto la leo para intentar implementar cosas nuevas, como agregar un ```return``` según dice #940 , también agregue el ```parent``` según #919 , intenté usar ```deleteLater``` como explica #860 y asi más cosas, y todavía no logro solucionar el problema.
Tengo la tarea cerca del término pero este problema no lo he podido solucionar, y lo que provoca es que cada vez el programa vaya más "pegado" debido a la cantidad de threads que hay activos. Subí mi código al repositorio por si lo quieren revisar.

**Comment by furcelay** [comment]
Hola @ian-fell !

Te cuento que he estado un buen rato probando tu tarea y creo haber encontrado todas las causas del error `QThread: Destroyed while thread is still running`, identifico tres principales causas del error:
1.  Se produce el error porque efectivamente destruyes el *thread* cuando aún está corriendo ya que ejecutas `deleteLater` dentro del `run` del mismo *thread*. Ese método debe ser usado fuera del `run`, por lo que podrías enviar una señal para eliminarlo justo cuando termina el `run` y que desencadene el `deleteLater` (otra opción sería removerlos después de que termine la ronda).
2.  No asignar el *parent* a todos los `QThreads` (solo `Flecha` lo tiene, faltaría `Termino` y `EfectoHielo`).
3. No hay sincornización entre la información entre *threads* ya que tienes varios threads que acceden, añaden y eliminan flechas de la lista de flechas pero no utilzas *locks* u otra herramienta para asegurar que no se modifique la información mientras otro *thread* lo hace (por ejemplo genera un error si eliminas una flecha mientras otro *thread* itera sobre ella).

Además hay otro punto que si bien no arroja ese error sí hace que el programa se pegue:
*  Siempre que tengas un *thread* que se ejecute dentro de un *loop* debe haber un `sleep` o de otro modo ocupará un exceso de recursos, en particular `Termino` y `EfectoHielo` no lo tienen.

Espero que eso te ayude a terminar tu tarea, saludos!! 😄
