### ISSUE TITLE
Entidades señaladas en negrita como atributos del DCCafe

### ISSUE THREAD

**Issue by dlmed** [IIC2233/syllabus#989]
Hola, en el pie de página de la página 8 se menciona que las entidades señaladas en negrita deben ser guardadas como atributos del DCCafe. Dentro de estas están por ejemplo, **dinero**, **ganancias**, **pagos** y **propinas**. Debo contabilizar todas estas variables en atributos separados?? o basta con tener un atributo **dinero** que vaya aumentando cada vez que se gana dinero por medio del precio de bocadillos y propinas?

**Comment by jbulness** [comment]
Hola @dlmed,

Las entidades a las que se hacen referencia que deben ir guardadas en atributos en el DCCafe son los empleados (chefs y meseros/as), las mesas y los clientes. El dinero se debe guardar en el archivo `datos.csv`.
