### ISSUE TITLE
Baile pinguinos

### ISSUE THREAD

**Issue by jorgetf-desing** [IIC2233/syllabus#989]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [ x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Hola me gustaría saber si los pinguinos se mueven a apretar cualquier tecla, ya que como menciona el enunciado: "Cada vez que se haga un paso nuevo, los pingüirines deberán cambiar su sprite para reflejar el movimiento efectuado", por lo que interpreté que esto era tanto para pasos correctos como incorrectos ya que no se especifica lo contrario.
Gracias!

**Comment by aljara97** [comment]
Hola @jorgetf-desing, ya que la distribución de puntaje dice que 

> Se muestra consistencia entre las teclas apretadas y el movimiento del pingüirin

Puedes asumir este supuesto, sin embargo, te recomiendo incluirlo en tu readme y citar esta issue para que el o la ayudante que corrija tu tarea tenga claridad de esto.

Mucha suerte 🐧

**Comment by jorgetf-desing** [comment]
Ok citaré la issue entonces, gracias!
