### ISSUE TITLE
Cálculo de soldados/magos después de una batalla

### ISSUE THREAD

**Issue by jpmoraga1** [IIC2233/Syllabus#99]
En las fórmulas que aparecen en el enunciado aparecen los parámetros "vida de un mago" y "vida de un soldado". ¿Esto significa tomar a algún mago/soldado aleatorio y hacer el cálculo en base a eso?

**Comment by leolivares** [comment]
Revisa los comentarios de la issue #26.
Eso debería responder tu duda!
