### ISSUE TITLE
Duda readme apartado implementaciones 

### ISSUE THREAD

**Issue by Amath3o** [IIC2233/Syllabus#99]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/3.-Reglas-del-foro-(issues)).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/11)).
* [X] Mi duda no se trata sobre una librería o *built-in*, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/10)).
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, mi duda es a que se refiere con implementacion de consola de consola en el apartado de cosas implementadas y no implementadas del readme, si es que main.py se ejecute a traves de la consola o algo mas

**Comment by ignacio-sp** [comment]
Hola @Amath3o, puedes observar a qué corresponde cada ítem del README basándote en lo que se muestra en el [excel de distribución de puntajes](https://docs.google.com/spreadsheets/d/12jjvyw0yogXF3UogpczyISZ27w4ramVQqtL9lKuC-q0/edit?usp=sharing]
) que se indica en el enunciado.

En particular, para la consola se espera que esta sea a prueba de errores y que se visualice correctamente las opciones correspondientes. Además, como el README es una guía para la corrección, es una buena idea que indiques todo lo que consideres necesario para la corrección en este apartado que se encuentre relacionado a la consola.

Espero que haya quedado más claro, estoy atento!

**Comment by Amath3o** [comment]
Entiendo, no habia entendido que eso era parte de readme, muchas gracias
