### ISSUE TITLE
Sobre properties

### ISSUE THREAD

**Issue by Fernanda1232123** [IIC2233/Syllabus#99]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/4)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/1)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, 

Tengo todo listo menos las properties, no sé por qué me tira error. Según yo están construidas igual que en las entregadas en las actividades. Subí mi tarea a mi repositorio, las properties están comentadas.
¿Lo podrían mirar y decirme como lo mejoro?
Gracias

**Comment by tamyhan** [comment]
Hola Fernanda! Revisé tu código y tienes un error muy chico. Las properties deben retornar un atributo con nombre distinto al nombre de la property. En general el mismo nombre con uno o dos guiones bajos antes, lo que los convierten en atributos privados (solo se acceden dentro de los métodos de la misma clase). 
Por ejemplo, en tu property **energia**, debes retornar `self._energia` en vez de `self.energia`. Y el atributo `self._energia` es el que se debe definir en el `_init_` en vez de `self.energia`. 
Si te fijas bien, así es como está en los contenidos y actividades.

Hacerlo como lo tienes en tu código tira error porque la property se está llamando a sí misma y, por lo tanto, hay un error de recursión. Es como que un método se retorne a sí mismo, se llamaría infinitamente. 

Espero que se entienda!!

**Comment by Fernanda1232123** [comment]
Voy a ver si funciona. No lo hice como atributo privado porque llamo esos atributos desde otros métodos para cambiarlos (sumarlos o restarlos). ¿Igual funcionaría?

**Comment by Fernanda1232123** [comment]
Ya intenté ponerlos privado y me tira error. El error es porque quiero acceder a esos atributos en otras partes del código y no me deja porque están privados.
¿Se entiende?

**Comment by tamyhan** [comment]
Para cambiarlos debes modificar la property. De esa manera se llama a su setter, que modifica el atributo privado de acuerdo a las condiciones que definas. 

Por ejemplo, si quieres modificar `self._energia` puedes hacer `self.energia += 5`. Ahí lo que pasa es que se llamaría al setter, y luego según las condiciones que tengas definidas, se modifica el valor del atributo privado `self._energia`. 

Ojo eso sí con la definición de tus setters, que también me fijé que estás modificando la misma property en vez del atributo privado, y que no le estás pasando todos los parámetros necesarios. Estos deben ser `self` y `valor`, donde `valor` corresponde al valor final con el que quedaría el atributo después de modificarlo. Por ejemplo, si `self._energia = 5` y tu haces `self.energia += 5`, el valor final una vez modificado sería 10. Si tu quieres que el valor máximo de `self._energia` sea 8, entonces defines que en caso de que `valor > 8`, `self._energia = 8`, y en otros casos `self._energia = valor`. Esos límites se definen en el setter. 

En los contenidos de la semana 2, hay varios ejemplos de cómo usar los *setters* y *getters*, y de cómo modificar atributos a través de las properties. Fíjate bien en particular, en dos cosas: cuándo se usa el atributo privado, y en los parámetros que recibe el setter. 

Te dejo el link donde se explica: 
[https://github.com/IIC2233/contenidos/blob/67f06cce3ed0bcad1a7724f8e522c2ec69a85300/semana-02/2-properties.ipynb](url)

Avísame si te funciona o si sigues teniendo dudas!!
