### ISSUE TITLE
Poderes líderes

### ISSUE THREAD

**Issue by csmeneses** [IIC2233/syllabus#99]
Cuando se explican las habilidades especiales de cada líder, tanto para el Gran Polea como para Cruz existen bonificaciones en los recursos recolectados.
¿sus recursos aumentan cada turno en el porcentaje indicado? o simplemente cada vez que se recolecta, se obtiene un x% mas?

![Captura](https://user-images.githubusercontent.com/48298696/55360686-80e2d180-54ab-11e9-89bb-0b4adbcfe227.JPG)

**Comment by BFFV** [comment]
Hola!
La respuesta es lo segundo, se obtiene un x% más de lo que los trabajadores recolectaron en ese turno.
Suerte en lo que resta de la tarea!

**Comment by RositaMunoz** [comment]
En esta misma línea, con respecto a la reparación de murallas de La Comarca, ésta es solo si han atacado a la civilización, o el hp de cada muralla va aumentando cada turno? Como dice 'en cada turno su muralla recupere un cuarto de su HP máxima' no me queda claro si es solo si hp actual es menor a hp íntegro(llegando como tope a su hp íntegro), o si es cada turno, y el hp de cada muralla aumenta siempre 
No sé si se entiende hajaha

**Comment by BFFV** [comment]
Es sólo si su HP es menor al íntegro, después de eso deja de recuperarse hasta ser dañada nuevamente.

**Comment by RositaMunoz** [comment]
gracias!
