### ISSUE TITLE
dónde subir readme?

### ISSUE THREAD

**Issue by Gjescalante** [IIC2233/syllabus#99]
Hola! el readme de las tareas  debe ir en alguna carpeta especial? o solo se sobre escribe el readme que venía de ejemplo en nuestro repo ?
Pregunto porque leí algo así en otra issue pero no he encontrado nada especifico en las pautas o en las slides de la primera clase :(

**Comment by DCCollao** [comment]
Hola!

Tu ``readme.md`` debe estar ubicado en la misma carpeta en que se encuentra tu tarea, es decir, ``T00`` dentro de tu repositorio. En esa carpeta ya hay un template de ``readme.md`` que puedes modificar para hacer el tuyo, quizás inspirándote también en los que subimos como ejemplo.

Saludos y éxito!
