### ISSUE TITLE
Optimizar funcion solucionar tablero

### ISSUE THREAD

**Issue by Cristian1754** [IIC2233/Syllabus#99]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [ X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/21)).
* [X ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/20)).
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [ X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [ X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

Hola, como a mucha gente el codigo al solucionar tablero de mas de 5x5 se demora mucho, por ejemplo a mi el de 7x7 se demora mas de media hora per funciona. Tengo una idea de como optimizar la funcion pero nose si este permitido dentro de las reglas del enunciado.

Me gustaria verificar el tablero solo una vez y de ahi en adelante solo verificar las tortugas que voy colocando. Es decir, me gustaria dejar afuera de la funcion la validacion del tablero original, claro que en el menu de acciones tendria que validar el tablero antes de ejecutar la funcion, pero nose si eso se pueda hacer.

**Comment by Hernan4444** [comment]
Hola @Cristian1754 

No hay problema si quieres hacer una forma más optimizada, aunque tenemos en consideración que tableros grandes se demora muucho más y cuando se corrija esto, los ayudantes lo tendrán 100% presente.

Saludos c:
