### ISSUE TITLE
Dudas tarea

### ISSUE THREAD

**Issue by ChayoPerez** [IIC2233/Syllabus#99]
1) Los archivos csv tengo que actualizarlos al momento de agregar un usuario/incendio/pronostico?
2) Estrategias:
Estoy súper confundida. Tengo entendido que después de que el miembro de ANAF elige un incendio y una modalidad se le imprime una especie de plan de acción en pantalla y se guarda la info también en un archivo. Esa estrategia queda registrada como que empezó a llevarse a cabo en t_0. De ahí según el usuario se mueva en el tiempo (cualquier tiempo superior a t_0) , los estados_actuales van a reflejar cómo se encontrarían los incendios, recursos y pronósticos meteorologicos en ese momento considerando la estrategia, la base de datos inicial y la diferencia entre fechas. Está eso bien? Mis otras preguntas son:
3) Qué pasa si viajo hacia atrás en el tiempo antes de que la estrategia fuera creada? Se anula? Puedo crear estrategias nuevas desde el pasado?
4) Se considera que los incendios han ido creciendo desde su fecha_inicio?

Gracias

**Comment by DiegoAndai** [comment]
Creo que lo que preguntas ya fue preguntado (si me equivoco corrígeme):

1. #54, #46 y #44 

2. Claro, así es. Te sugiero que si no lo tienes claro, dale un par de vueltas más al enunciado, esta todo ahí. Si ya lo has leído y sigues sin entenderlo vuelve a preguntar aquí mismo. Trata de que las preguntas sean lo más detalladas posible, así te podemos responder mejor.

3. #86 y #72 

4. #29

Por favor, revisa las issues que ya se han abierto antes de crear una nueva. Si encuentras una que tiene que ver con lo que vas a preguntar pregunta ahí, y si encuentras lo que ibas a preguntar... bueno ya no necesitas preguntarlo. Así todo se mantiene más ordenado y podemos responder más eficientemente.

Saludos
