### ISSUE TITLE
[Corto] Sobre algunos usuarios...

### ISSUE THREAD

**Issue by fernandosmither** [IIC2233/syllabus#99]
* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/45)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### ¿Por qué si el límite de caracteres que nos piden programar es de 15, hay usuarios que ya vienen en los .csv con 17 caracteres (por ejemplo) ?
![image](https://user-images.githubusercontent.com/66154723/112773548-d3a8e280-900c-11eb-98ff-8a9a363a2185.png)

**Comment by Tsbalart** [comment]
Hola @fernandosmither! Un ligero error en los archivos ups. De todas formas no debiera alterar el funcionamiento de tu tarea, y apegate a las instrucciones del enunciado, esas son las que mandan! Éxito con la tarea!

**Comment by fernandosmither** [comment]
Muchas gracias! @Tsbalart , resuelto.
