### ISSUE TITLE
duda sobre celdas_afectadas y alcance maximo

### ISSUE THREAD

**Issue by juanivegam** [IIC2233/Syllabus#99]
### Prerrequisitos
(Marcar colocando una `X` entre los corchetes los ítems que ya hiciste, así: `"[X]"`)

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/6.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/Syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/Syllabus/issues/56)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/Syllabus/issues/55)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (coordinacion.iic2233@gmail.com).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

[Hola! Tengo una duda sobre el método celdas_afectadas. Para calcular la cantidad de celdas afectadas,  ¿hay que conciderar el máximo de cada pieza explosiva? Es decir, ¿las celdas afectadas podrían ser mayor al alcance asociado a la pieza o se concidera el alcance de cada pieza como un tope? Muchas gracias de antemano por la ayuda.]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by Mcroquevielle** [comment]
Hola!! En este caso, sólo importa el tipo de pieza, y si hay peones interfiriendo. Entonces, las celdas afectadas sí podrían ser mayores al alcance asociado a la pieza.

**Comment by juanivegam** [comment]
Perfecto muchas gracias
