### ISSUE TITLE
Duda sobre ejercicio propuesto de ayudantia OOP2

### ISSUE THREAD

**Issue by svilaza** [IIC2233/Syllabus#99]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola! En el ejercicio propuesto de la ayudantia se definió la clase: 
```Triatleta(Maratonista, Ciclista, Nadador)``` heredando de las clases `Maratonista`, `Ciclista` y `Nadador`, esta clase tenia el metodo ```competir()``` que utilizaba el `super().competir` (Cada clase super clase tambien tiene el metodo competir). Mi duda es que al utilizar el metodo `competir()` de Triatleta parece que se ejecutan los metodos de las superclases de derecha a izquierda, es decir, primero la de nadador, luego la de ciclista y finalmente la de maratonista y no en el sentido contrario como tenia entendido que pasaba. Por qué ocurre esto?

**Comment by camilagonzalezp** [comment]
Hola @svilaza! 

Al final resulta que si se ejecutan los métodos de las clases de izquierda a derecha, ya que si haces prints al principio de cada método ```competir``` te vas a dar cuenta que si se sigue el orden de multiherencia, sólo que no se apreciaba por la falta de prints 🙌🏻

¡Éxito! ✨
