### ISSUE TITLE
Calcular reputacion

### ISSUE THREAD

**Issue by EmeraldMP** [IIC2233/syllabus#990]
Hola me entro la duda de cómo se calcula la repurtacion. Por lo que se divide es por el total de clientes atentidos + clientes perdidos ( que depende de donde hago F+I+N) o se divide por todos los clientes que deberían pasar es decir los clientes ya definidos por ronda?

**Comment by jitorcas** [comment]
Hola! @EmeraldMP 

Siguiendo lo expuesto en el enunciado, se divide en *pedidos_totales* que corresponde a la cantidad de clientes que fueron al DCCafé, por lo que no deberían contar los clientes que faltan por llegar en caso de aplicar *cheat code* **”F + I + N”**

Espero te haya quedado más claro! 
Éxito en la tarea 💯
