### ISSUE TITLE
Programa se me cae al iterar las flechas

### ISSUE THREAD

**Issue by nico-sv** [IIC2233/syllabus#990]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, lo que sucede es que cuando instancio una única flecha el programa me corre bacán, pero cuando intento meterle un while o un for para ir instanciando las flechas el programa se me cae aún cuando mando señales para eliminar los QThreads :(
he intentado cambiar dónde hago el loop, tipos de loop, sleeps absurdos y sólamente me funciona cuando instancio un único thread.

**Comment by furcelay** [comment]
Hola @nico-sv !

Estuve revisando tu tarea para ver la posible causa del error pero me da la impresión de que lograste resolver el problema por tu cuenta. Por favor comenta si efectivamente lo solucionaste o si aún necesitas ayuda para resolverlo,

Saludos! :smile:
