### ISSUE TITLE
Cómo emitir señales con informacion

### ISSUE THREAD

**Issue by gaspcr** [IIC2233/syllabus#991]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Estoy intentando separar mi back y front-end de la t2 y necesito para ello que una función de mi front-end reciba argumentos de información generada en mi back-end, seguí los pasos de cómo hacerlo, según se muestra en la semana 9 y me arroja error en mi función del front-end de que la misma no está recibiendo los argumentos que necesita. ¿Estaré haciéndolo mal?

**Comment by aaossa** [comment]
Hola @gaspcr , algo general tu pregunta, pero asumo que estás usando señales para "emitir los argumentos" hacia el *front-end*. En ese caso, recuerda que la señal debe indicar cuáles son los argumentos que se emiten y que la función a la que la conectas debe recibir exactamente esos argumentos (excepto `self` si es que se trata de un método de una clase)

**Comment by gaspcr** [comment]
Sí, así lo tengo precisamente, y nada :(

**Comment by aaossa** [comment]
¿Qué error ves exactamente?

**Comment by gaspcr** [comment]
Me dice que mi funcion a, la cuál es la que debe recibir los argumentos en mi front-end, no está recibiendo ningún argumento

**Comment by aaossa** [comment]
Mejor podrías subir tu código? Imagino que esto en verdad es de la T02 😅 Si es así, avísame y le doy una mirada, pero en alguna parte debe estar faltando emitir la señal correctamente. De casualidad, hiciste la conexión en Qt Designer o en código?

**Comment by gaspcr** [comment]
Subo ahora mismo el código, la conexión la hice en código, en Qt Designer nunca aprendí cómo hacerlo xd

**Comment by aaossa** [comment]
Cuál es la función que debo ver? Podrías mostrarme el mensaje de error? Ahí debería aparecer

**Comment by gaspcr** [comment]
Ya subí el código, la cuestión es que tengo que crear una flecha de la clase Flecha, esta necesita unos datos que deben ser escogidos al azar, por ende solicita esos datos en el back-end (logica_ventanas), funciona de tal manera que existen dos QTimers, uno que crea la flecha y otro que solicita los datos, el QTimer que solicita los datos se encarga de llamar a una funcion que va emitiendo la señal solicitando los datos para que le lleguen a la función generador_flecha

**Comment by gaspcr** [comment]
TypeError: SenalesInformacion.senal_datos_flecha[str, str, int] signal has 3 argument(s) but 0 provided, este me aparece ahora que reconstruí lo que había hecho antes de colocar el post, pero era algo similar antes

**Comment by aaossa** [comment]
@gaspcr en `logica_ventanas.py` declaras la señal `senal_datos_flecha` con `str,` `str` e `int`. En la clase `Principal` la emites bien, le pasas 3 valores, pero la misma señal, en `VentanaPrincipal` (`ventana_principal.py`) la emites sin argumentos en el método `funcion_emite_senal`. Si es la misma señal tienes que darle siempre la misma cantidad de argumentos (con el tipo apropiado). Si necesitas otra señal, tienes que crear una nueva.

**Comment by gaspcr** [comment]
Es decir, para emitir la senal que solicita los datos debo crear otra senal, o ya con pasarle los args a esa señal basta?

**Comment by aaossa** [comment]
Depende de lo que quieras que haga la señal. Si la señal representa lo mismo y debe ejecutar el mismo método, entonces usa la misma. Si tu señal representa algo distinto o necesitas que se conecte a otro método (o con otros argumentos) tendrás que crear un nueva señal.

**Comment by gaspcr** [comment]
Es que, lo que necesito que haga esa señal sea llamar a la función del back-end, para que ésta última le entregue (mediante señales) la info necesaria a mi funcion del front-end. Pero si emito otra señal distinta, la senal **senal_datos_flecha** en qué momento del front-end la debería usar?, porque como lo puse ahora, es como entendí que se hacía según el ejemplo.

**Comment by aaossa** [comment]
@gaspcr lo que me preguntas es demasiado general y en verdad depende de tu tarea, así que no puedo guiarte mucho. Solo intento hacerte ver que lo que tienes es equivalente a tener una función que recibe 3 argumentos y en una parte la llamas con 3 argumentos (lo esperado) y en otra parte sin argumentos. ¿Cómo arreglar esto? Define otra función (otra señal en este caso) que no reciba argumentos o dale los argumentos para evitar el error inicial. 

¿Quizás te confunde la dirección de la señal? Si quieres emitir algo del *front-end* al *back-end* usas una señal, y si necesitas algo que vaya en la otra dirección (*back-end* a *front-end*) necesitarás otra distinta 🤔

**Comment by gaspcr** [comment]
Aah, vale vale voy entendiendo, muchas gracias!
