### ISSUE TITLE
¿Se puede usar 'global' en la tarea? ¿Como recibo el valor retornado por un thread?

### ISSUE THREAD

**Issue by sofiuni** [IIC2233/syllabus#991]
^, tengo una clase que hereda de Timer, funciona perfecto y si le doy una funcion con 'print()' todo funciona bien. El problema es que quiero utilizar el valor retornado por el Timer. ¿Que debo hacer?

**Comment by lily416** [comment]
Hola @sofiuni, 

Como sale en la issue #680, el uso de variables globales se considera una mala práctica y su uso será penalizado con un descuento.

Para evitar el uso de variables globales te recomiendo hacer una clase que controle todo el programa (o por lo menos el backend) y que esta se encargue de almacenar el Timer y los valores relacionados.

Saludos y éxito en la tarea :wave: :dango:

**Comment by sofiuni** [comment]
Gracias, pero no entiendo como crearia una clase que almacene los valores, no se como conseguir el valor en el primer lugar. ¿Me puedes ayudar un poco por favor?

**Comment by fdoflorenzano** [comment]
Hola @sofiuni,

Lo que menciona @lily416 es que en vez de usar variables globales, uses atributos de instancias clases para almacenar y guardar valores. Algo del estilo:
```python

class ClaseGeneral:

    def __init__(self, ...):
        self.variable = valor_inicial


    def actualizar_valor(self, nuevo_valor):
        self.valor = nuevo_valor

```

Ahora, siguiendo lo segundo que preguntas. No nos queda claro a qué te refieres con "el valor retornado por el Timer", ya que este como los *threads* no retornan un valor específico como funciones, son hilos de ejecución que ejecutan código. Ahora, intuyo que lo que necesitas es actualizar algo externo (como el atributo `varible` del ejemplo) desde el *timer*. Para eso puedes utilizar una señal que envié hacia afuera del *timer* un nuevo valor, y si lo conectas a algo que actualice el valor (como el método `actualizar_valor`), podría funcionar. Por ejemplo:

```python
class MiTimer(QTimer):  

    # envía un valor de tipo int, es solo un ejemplo, puede ser cualquiera
    senal_actualizar = pyqtSignal(int) 

    def __init__(self, ...):
        super().__init__()
        self.setInterval(1000)
        self.timeout.connect(self.enviar_dato)

    def enviar_dato(self):
        ...
        self.senal_actualizar.emit(nuevo_valor)


clase_general = ClaseGeneral()
timer = MiTimer()
timer.senal_actualizar.connect(clase_general.actualizar_valor)
timer.start()
```

El *timer* anterior enviará cada vez que se ejecute `enviar_dato` una señal con un valor nuevo que actualizará el atributo en `clase_general`. 

Espero se entienda, cualquier cosa nos avisas.

Saludos.

**Comment by sofiuni** [comment]
Cree una señal y estoy usando eso para crear los clientes y sus QLabels respectivos pero no respeta mi condicion if y los pone todos en el mismo lugar... que estoy haciendo mal?

**Comment by fdoflorenzano** [comment]
@sofiuni, ¿es eso sobre la duda original de esta *issue* o es otra cosa?  Parece un *bug* separado y es un problema de condiciones y moviendo los *labels*, si es el caso, deberías abrir otra *issue* explicando eso. Te recomiendo agregar *prints* para seguir el flujo y el estado de tus atributos para ver que pasa.

Si es sobre este tema, creo que faltan detalles ya que no encuentro la relación.

Saludos.

**Comment by sofiuni** [comment]
Ok gracias, use prints y se cual es el problema pero no entiendo por que me lo da. Abrire otra issue.
