### ISSUE TITLE
botón continuar ventana post-ronda

### ISSUE THREAD

**Issue by CamilaArgomedo** [IIC2233/syllabus#992]
Hola! en el enunciado no se dice nada sobre el botón "continuar" ( o yo no lo encontré en la sección de ventana post-ronda), pero en la distribución de puntajes dice "se puede continuar, guardar y salir" a que se refiere exactamente con continuar? cuenta si para continuar debo cliquear los botones: "guardar"->"salir" -> (llega a ventana pre-ronda) "seguir jugando"? o debo si o si hacer un botón continuar que haga esa función?

**Comment by jitorcas** [comment]
Hola!

Considerando que estás en la ronda “N”, el botón continuar te debería llevar a la Pre-ronda de la ronda “N+1”.
El método que propones es un poco más complejo y podría dificultad la corrección de tu tarea. 

Éxito! 💯

**Comment by CamilaArgomedo** [comment]
oka muchas gracias! tenia una confusión con ventana pre-ronda y ventana inicio:)
