### ISSUE TITLE
Problema con keyPressEvent

### ISSUE THREAD

**Issue by Pablomaluk** [IIC2233/syllabus#993]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola tengo un problema al momento de hacer override del keyPressEvent en la ventana de juego. Algunas teclas como shift y ctrl generan un evento, pero no reconoce ninguna letra del teclado. Es un problema porque no puedo implementar ni las flechas ni los cheats. Probe abriendo en terminal, y llevo horas buscando en internet y cambiando el código sin suerte

**Comment by knight-who-say-ni** [comment]
Holaa @Pablomaluk !!

Estuve revisando tu codigo pero en ninguna parte le haces override a keyPressEvent, asi que no puedo revisar si lo estas haciendo bien...

Si te acomoda, recuerda que puedes cambiar las teclas a apretar para ciertas acciones, basta con que lo tengas como parametro y lo menciones en tu readme 😃.

Exito en lo que queda!!!

**Comment by knight-who-say-ni** [comment]
Tambien podria ser que tienes el mismo problema que las issues #738 y #853 👀
