### ISSUE TITLE
Problema con condicion, entra a condicion cuando no debe y se montan los personajes. 

### ISSUE THREAD

**Issue by sofiuni** [IIC2233/syllabus#993]
Tengo una funcion conectada a una señal y un timer que cada x segundos genere un cliente. Mi problema es que el timer y señal no fallan si no la funcion tiene una condicion en la cual no deberia entrar cada ejecucion, deberia entrar despues de algunas ejecuciones del ciclo. Pero entra todas las veces al principio donde hay un return (si no entra en todos) y se cae el programa debido a que se llena la memoria de QLabels en el mismo lugar. No veo el problema, me pueden ayudar? El codigo esta en mi repo.

**Comment by fdoflorenzano** [comment]
Hola @sofiuni,

El problema es que la condición siempre se cumple con el primer elemento de la lista que iteras, y al escribir `return` nunca revisa los otros elementos. Como tu lista siempre comienza con un elemento con posiciones `0, 0`, este siempre cumple la condición de tener coordenadas distintas a lo indicado.

Noté esto agregrando *prints* de los elementos en la ejecución de tu programa, para ver que era y lo que no se recorría. Te recomiendo hacer lo mismo y darle una vuelta al algoritmo que estás realizando.

Saludos.

**Comment by sofiuni** [comment]
Cree una variable llamada borrar_0 la cual es True si x es 0. Entra a la definicion, pero mas abajo no entra al if (probe con prints) y no borra el valor. Por que pasa esto?

**Comment by fdoflorenzano** [comment]
¿Será por el `return` que interrumpe la ejecución?

**Comment by sofiuni** [comment]
Ese debe ser el problema! Como lo puedo hacer entonces?

**Comment by sofiuni** [comment]
Estoy teniendo muchos problemas con las señales y me gustaria un poco de ayuda

**Comment by fdoflorenzano** [comment]
Hola @sofiuni, ¿qué pasó con el problema original? ¿Lo pudiste solucionar? Si la duda nueva es distinta, debes abrir una nueva *issue*, con tu duda específica para saber como ayudarte.

**Comment by sofiuni** [comment]
Tengo dos problemas, una es con señales y el otro es de una condicion, pero igual esta relacionado a las señales. Necesito ayuda con las dos, y las does estan en issues distintas. Me puede ayudar o redirigir a alguien que me pueda ayudar? Gracias.

**Comment by fdoflorenzano** [comment]
Sigo a espera que expliques los problemas.

El punto de armar temas en *issues* separadas es para separar los problemas y que se asignen encargados para cada una, en vez de ver muchos temas en solo una. Además así es más fácil buscar problemas que otras personas tuvieron.
