### ISSUE TITLE
Ubicación random de muebles a veces no funciona

### ISSUE THREAD

**Issue by dlmed** [IIC2233/syllabus#994]
Hola, estoy probando mi programa y a veces la ubicación random de los muebles no funciona, es decir, hay veces que inicio una partida nueva y se ubican en posiciones que se traslapan. Quería saber si alguien puede revisar mi código y ayudarme a encontrar el fallo. La implementación de esto está en ```ventana_juego.py```, línea 188. De antemano muchas gracias!

**Comment by cristozille** [comment]
Hola @dlmed, para evitar que las mesas se traslapen te recomiendo guardar como atributos las posiciones de las mesas ya puestas, y tener una función que revise que la posición entregada por el random() no se cruce con otras. Para esto te recomiendo tomar en consideración el tamaño de las mesas, si las tienes en 10x20 pixeles (por ejemplo) revisas que la posición entregada por el random() este por lo menos a un rango de 20 pixeles de distancia. Se  cacha?

**Comment by dlmed** [comment]
eso hago :(

**Comment by cristozille** [comment]
En qué línea defines las posiciones de las mesas? No lo puedo encontrar en tu código.

**Comment by dlmed** [comment]
ventana_juego.py línea 210

**Comment by dlmed** [comment]
acabo de hacer un push nuevo

**Comment by cristozille** [comment]
Hola @dlmed! Hice un cambio en los signos de las líneas 255-258 de ventana_juego.py. Como las coordenadas comienzan en la esquina superior izquierda y aumentan hacia la derecha, para settear el largo izquierdo sería la coordenada - pm.CHEF_AJU_LEFT. De la misma forma, para el largo hacia arriba seria la coordenada - pm.CHEF_AJU_TOP, y para la derecha y abajo sería coordenada + parámetro. 
Estuve probando y parece que se solucionó. Lo otro sería empezar a probar con distintos valores en los parámetros para las dimensiones del chef para que las mesas estén mas alejadas.

**Comment by dlmed** [comment]
Es que los ajustes son: cuánto hay que achicar por lado los QRect, siendo todos positivos. Entonces en el mismo sentido de tu comentario, por eso los había puesto con esos signos

**Comment by cristozille** [comment]
Entonces lo mejor que se me ocurre es modificar los valores de los parámetros para que intesrects() revise mas pixeles del largo  ancho del QLabel, para asegurarte que no se toquen.
