### ISSUE TITLE
Referencias externas en el codigo.

### ISSUE THREAD

**Issue by felipehen** [IIC2233/syllabus#995]
Hola, la verdad, al hacer mi codigo, referencie varios codigos sacados de internet, de forma extraña, y queria saber si es necesario que las cambie.

las refencie de la siguiente forma:

en el archivo.py, ponia "# Argumento sacado de internet, revisar README, referencia X", con X siendo un numero. Y en el readme, hay una seccion unica de referencias, que indica: de donde se saco el archivo, que es lo que hace, y donde se ocupa.

En el caso que si tenga que cambiarlo, ¿hay algun problema con que una linea comentada supere los 100 caracteres?

**Comment by cristozille** [comment]
Hola! Esta bien de esa forma. Y las líneas que sean comentadas (que partan con #)  también deben tener menos de 100 caracteres.
