### ISSUE TITLE
Video cierre actividad formativa 4

### ISSUE THREAD

**Issue by margavicunas** [IIC2233/syllabus#995]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

Holis, podrían subir algún video/presentación sobre la resolución de la actividad formativa 4? Ayudaría mucho mucho para apoyar el estudio 🥺❤️ 

Si no se puede no se preocupen y muchas gracias de todos modos 🌻

**Comment by lily416** [comment]
Hola @margavicunas,

Ya se encuentra subido el cierre 😄, lo puedes encontrar en los módulos de la semana 11. 
Lamentamos la demora en subir los cierres 🙇.   

Saludos y que tengas una linda semana 🌻❤️

**Comment by margavicunas** [comment]
MILLONES DE GRACIAS ❤️ y que estés súper tú también :3
