### ISSUE TITLE
Problemas con gitignore  en mac

### ISSUE THREAD

**Issue by JulioGalvez** [IIC2233/syllabus#996]
Hola! mi computador no me permite crear archivos que empiecen con "." ya que esta oculto para mac, que puedo hacer?

**Comment by Alonsinho1** [comment]
Hola!

Lo más simple es crear el archivo .gitignore directamente desde tu editor de texto.

**Comment by JulioGalvez** [comment]
hola la cree. desde. el editor de texto de GitHub
aún así me aparecen en el repositorio los archivos que debe ignorar

**Comment by Alonsinho1** [comment]
eso fue por que los subiste antes de hacer el gitignore, aqui tienes una solucion.   #904

**Comment by JulioGalvez** [comment]
El tema es que cuando hago el git pull como para "adquirir" el archivo .gitignore, mi computador   no lo adquiere, aparece +/-

**Comment by JulioGalvez** [comment]
existe otra forma de escribir el nombre del archivo que no sea ".gitignore"??

**Comment by Alonsinho1** [comment]
Hola!

Primero por eso mismo no es recomendable crearlo desde git. Causa muchos problemas en como se mandan los archivos. Quizas te sirve hacer git pull --rebase

Segundo, no que yo sepa. Sin embargo, tal como te dije antes, crear el gitignore desde el editor de texto no es problema. Abres tu editor de texto en la carpeta que estas trabjando y presionar _new file_ y listo. Yo he trabajado con mac desde que era ~pibe~ alumno del ramo y nunca he tenido problemas creado el gitignore de esa manera

**Comment by JulioGalvez** [comment]
Hice lo que me dijiste y además creé una carpeta con los archivos a ignorar colocando solo el nombre de la carpeta en el gitignore y funciono sin problemas, muchas. gracias!!
