### ISSUE TITLE
Contenidos AS jueves 5

### ISSUE THREAD

**Issue by mleon17** [IIC2233/syllabus#996]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

[Describe tu duda de manera detallada, explicando los contenidos en cuestión y ojalá colocando código o un caso de uso de ejemplo]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by mleon17** [comment]
Hola, quería saber cuales son los contenidos que entran para la siguiente AS. Gracias

**Comment by aaossa** [comment]
Hola @mleon17 , el foco de la evaluación de esta semana será la materia de la semana 12 (**Estructuras nodales II - Grafos**). Si bien los contenidos del curso son acumulativos, lo que significa que puedes usar cualquier contenido ya visto en el curso, el foco de la evaluación está en la materia de la semana 👌  Adicionalmente, te recomendaría darle una mirada los contenidos de la semana 11, por si te ayudan a entender mejor los de la 12. Si tienes cualquier duda sobre los contenidos, abre una nueva *issue* y entre ayudantes y profes les respondemos ✨ ¡Éxito con tu estudio 💪!
