### ISSUE TITLE
Eliminar Carpeta de repositorio

### ISSUE THREAD

**Issue by soyjorgeperello** [IIC2233/syllabus#997]
Hola!

Quería saber como eliminar una carpeta de mi repositorio ya que subí la carpeta de "sprites" antes de crear el .gitignore.

Gracias!

**Comment by danckoo1** [comment]
Hola, si quieres que la carpeta no se borre de tu computador pero si del repositorio, bastaría con usar `git rm -r --cached FolderName ` y posteriormente hacer un commit y un push, saludos!
