### ISSUE TITLE
Readme y referenciar código externo

### ISSUE THREAD

**Issue by jorge-ovalle** [IIC2233/syllabus#997]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Hola! En el readme me faltó indicar fuentes de código externo que utilicé en mi tarea. Podría agregarlas ahora o el commit ya está bloqueado :( ? Me acordé a último momento y no alcancé a agregarlo al Readme

**Comment by aaossa** [comment]
Hola @jorge-ovalle , hace unos minutos respondí casi la misma duda en esta *issue*: https://github.com/IIC2233/syllabus/issues/795#issuecomment-721084714. Te dejo la respuesta:

> (...) en ese caso basta con que lo agregues en tu README 👌 No hay problema con que lo agregues ahora porque solo es una referencia, y nos sirve más para el análisis posterior que para la corrección en sí 🔍

Si tienes otra duda pregunta por acá mismo no más ✨

**Comment by jorge-ovalle** [comment]
Perfecto. Muchas gracias!!
