### ISSUE TITLE
Commit a revisar

### ISSUE THREAD

**Issue by BelenSilva1204** [IIC2233/syllabus#998]
Holaa, no sé muy bien que hacer en este caso, pero subi los archivos de mi tarea alrededor de las 19:40 con "git add", "git commit -m" y "git push" pero luego de pushearlos me di cuenta de que me falto un archivo por lo que hice de nuevo "git add", "git commit -m" y "git push" pero sólo con el archivo que me faltaba y ahora que enviaron el correo de confirmación del commit a revisar, me di cuenta de que tomaron el último commit que tiene sólo un archivo😞

**Comment by fdoflorenzano** [comment]
Hola,

Cuando se dice que es un *commit* a revisar, no significa que solo se revisa los cambios incluidos en tal *commit*, significa que se considera tu entrega como el estado de tu repositorio **hasta** ese *commit*. Cada *commit* indica solo los cambios en el repositorio desde el último *commit*, el estado de tu repositorio es al final el resultado acumulado de todos los *commits* en orden.

Entonces, por lo que cuentas, tu último *commit* de entrega fue el que subiste con solo cambios de un archivo, y ese fue detectado como el último *commit* de entrega, por lo que está bien. Se considera como tu entrega todos los cambios subidos hasta ese *commit*.

Saludos.

**Comment by BelenSilva1204** [comment]
Ohh ya entiendo perfectamente, me había asustado ¡Muchas gracias!
