### ISSUE TITLE
Ejercicio 3.2 Semana 10

### ISSUE THREAD

**Issue by denisseleiva** [IIC2233/syllabus#998]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x ] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola! Tengo una duda con este ejercicio. En el enunciado dice que existe_camino recibe el valor de los nodos que tiene que analizar, pero en la lista de tuplas conexiones no aparece el número 12, sin embargo el largo de conexiones sí es 12, entonces mi pregunta es ¿Los nodos que tengo que crear son al final el largo de la lista de tuplas conexiones? ¿O quizás en el ejercicio debería decir print(grafo.existe_camino(10, **11**))? 

Gracias! 😁

**Comment by MatiasDuhalde** [comment]
Hola @denisseleiva !

El hecho de que el largo de conexiones sea 12 es sólo una coincidencia! :sweat_smile:

Se supone que conexiones la lista de aristas que tiene el grafo (direccional). Por lo tanto, los nodos serían los valores que aparecen en esta lista. Por ejemplo, el nodo 3 tiene las aristas (3, 2), (3, 4) y (3, 5) que salen desde él, y (2, 3) que llega hasta él desde 2.

Explicando un poco el ejercicio, los valores que recibe el método serían el nodo desde donde empezar, y el nodo final, por lo tanto, en el caso de `grafo.existe_camino(10, 12)`, 10 sería el nodo desde donde empezar la búsqueda, y 12 hasta el que debo llegar desde 10. En el caso de que se pueda llegar (es decir, exista un camino) desde 10 hasta 12, el método debería retornar `True`. En caso contrario, debería retornar `False`!

Dado que el nodo 12 no se encuentra en la lista de conexiones, este nodo no existe en el grafo, por lo que el método debe retornar `False` en este caso.

Ojalá esto aclare un poco el ejercicio 😄

**Comment by denisseleiva** [comment]
Ahhh capto, entonces para confirmar el número de nodos sería 11? @MatiasDuhalde

**Comment by MatiasDuhalde** [comment]
@denisseleiva Efectivamente, en la lista de conexiones del ejercicio hay 11 nodos!

**Comment by denisseleiva** [comment]
Buenisimoo, muchas gracias!! @MatiasDuhalde
