### ISSUE TITLE
Duda con descuentos

### ISSUE THREAD

**Issue by RenatoVWS** [IIC2233/syllabus#999]
Hola!

Tengo una pregunta sobre los descuentos y des-descuentos. ¿Los des-descuentos se aplican al total de descuentos: `(mín(total_descuentos_aplicados, 10) + descuento_por_entrega_atrasada + descuento_por_usar_algo_prohibido)` o solo a los descuentos aplicados?

Ojalá me puedan ayudar,
Saludos!

**Comment by lily416** [comment]
Hola @RenatoVWS,

Los des-descuentos solo se aplican a los descuentos aplicados, por lo que la fórmula para calcular los descuentos es la siguiente:
```máx(mín(total_descuentos_aplicados, 10) - des-descuentos, 0) + descuento_por_usar_algo_prohibido + descuento_por_entrega_atrasada```

Saludos y que tengas una buena semana 👋😸

**Comment by RenatoVWS** [comment]
Muchas gracias!
