### ISSUE TITLE
Duda con Listas Ligadas

### ISSUE THREAD

**Issue by jpvergaralb** [IIC2233/syllabus#999]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda

Hola, tengo una duda con listas ligadas. Es posible asignarle a cada valor de una lista un nodo? Asi como la funcion zip une el i-esimo elementos de dos conjuntos.
Mi duda nace por el ejercicio propuesto 3 de la semana 11, donde podria ingresar todos los valores de los nodos en una lista y hacer sort.
Un ejemplo particular seria, a partir de una lista = [4, 2, 6, 7], crear una lista ligada de la forma: 4 -> 2 -> 6 -> 7.

Gracias de antemano.

**Comment by Pablok98** [comment]
Hola! No estoy del todo seguro si entendí bien tu pregunta, por lo que comentame si es que no te respondo adecuadamente.

Con respecto a si es posible convertir una lista genérica a una lista ligada, sí es posible. Recuerda que la lista ligada que se ve en los cuadernos de la materia es más que nada una "base" o un modelo, el cual puedes utilizar para hacer estructuras más complejas. La implementación dependerá de como estructuras tu código, pero siempre está la opción de crear una nueva lista ligada, iterar por cada elemento de la lista genérica y para cada uno crear un nodo nuevo e insertarlo en la lista ligada.

Ahora bien, según lo que escribes, para ordenar una lista ligada lo que quieres hacer es:
1. A partir de la lista ligada, crear una lista genérica.
2. Ordenar la lista genérica.
3. Crear una lista ligada a partir de la lista genérica ordenada (o eliminar los valores de la lista ligada e insertarlos en orden).

Si bien este proceso tendría el resultado esperado, estarías perdiendo todos los beneficios que trae la lista ligada y sería muy ineficiente. Aunque no se evalúa eficiencia en el curso, de todas maneras la idea es utilizar correctamente las estructuras que implementas y aprovechar los métodos que construyes. Piensa que, en este caso, estarías iterando por toda la lista ligada, luego iterando denuevo para ordenar la nueva lista y luego iterando denuevo para crear o insertar los elementos ordenados, lo cual parece un poco redundante. Puede que el _built-in_ `sort()` de Python sea tentador, pero aunque te tome una línea llamarlo, Python tiene que leer hartas líneas detras para obtener el resultado 😮 

Espero que esto responda tu pregunta, de lo contrario respondeme y lo resolvemos 😄

**Comment by jpvergaralb** [comment]
Hola, sí respondiste mi duda y me queda clara tu respuesta. 

Muchas gracias!
